### ISSUE TITLE
findOrCreate isn't working inside of a transaction

### ISSUE THREAD

**Issue by obo20** [sequelize/sequelize#10020]
## What are you doing?

I'm trying to utilize findOrCreate within a sequelize transaction.

```js
db.sequelize.transaction(function (t) {
            // chain all your queries here. make sure you return them.
            return Contract.findOrCreate({
                where: {},
                defaults: {
                    config_hash: req.body.config_hash,
                    config: req.body.config
                },
                transaction: t
            });
        }).then(function (result) {
            return res.status(200).json(result);
        }).catch(function (err) {
            return res.status(400).json({
                error: err
            });
        });
```

## What do you expect to happen?
I wanted this to work. 

Note - Things work if I use "Contract.create" inside of a transaction, and "Contract.findOrCreate" also works outside of a transaction.

## What is actually happening?
I get the following stack trace error:

```
TypeError: Invalid Version: 0
at new SemVer (/Users/myrepo/api/node_modules/sequelize/node_modules/semver/semver.js:291:11)
at compare (/Users/myrepo/api/node_modules/sequelize/node_modules/semver/semver.js:578:10)
at Function.gte (/Users/myrepo/api/node_modules/sequelize/node_modules/semver/semver.js:627:10)
at Object.insertQuery (/Users/myrepo/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:150:18)
at QueryInterface.insert (/Users/myrepo/api/node_modules/sequelize/lib/query-interface.js:896:37)
at Promise.try.then.then.then (/Users/myrepo/api/node_modules/sequelize/lib/model.js:3694:53)
at tryCatcher (/Users/myrepo/api/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/Users/myrepo/api/node_modules/bluebird/js/release/promise.js:512:31)
at Promise._settlePromise (/Users/myrepo/api/node_modules/bluebird/js/release/promise.js:569:18)
at Promise._settlePromise0 (/Users/myrepo/api/node_modules/bluebird/js/release/promise.js:614:10)
at Promise._settlePromises (/Users/myrepo/api/node_modules/bluebird/js/release/promise.js:694:18)
at _drainQueueStep (/Users/myrepo/api/node_modules/bluebird/js/release/async.js:138:12)
at _drainQueue (/Users/myrepo/api/node_modules/bluebird/js/release/async.js:131:9)
at Async._drainQueues (/Users/myrepo/api/node_modules/bluebird/js/release/async.js:147:5)
at Immediate.Async.drainQueues (/Users/myrepo/api/node_modules/bluebird/js/release/async.js:17:14)
at runCallback (timers.js:810:20)
at tryOnImmediate (timers.js:768:5)
at processImmediate [as _immediateCallback] (timers.js:745:5)
```

__Dialect:__ postgres 
__Dialect version:__ I'm not sure how to find this
__Database version:__ 10.5
__Sequelize version:__ 4.39.0
__Tested with latest release:__ Yes - 4.39.0

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Can you show me how you initialized Sequelize, looks like you are passing invalid `databaseVersion` value

**Comment by obo20** [comment]
> Can you show me how you initialized Sequelize, looks like you are passing invalid `databaseVersion` value

Certainly:
```js
const Sequelize = require('sequelize');
const sequelize = new Sequelize('me', 'me', null, {
    host: 'localhost',
    port: 5432,
    dialect: 'postgres',
    operatorsAliases: false,
    pool: {
        max: 5,
        min: 0,
        acquire: 30000,
        idle: 10000
    }
});
```

I'm not sure sure where to find the databaseVersion you're talking about

**Comment by sushantdhiman** [comment]
Hmm, not sure. Error you submitted in original description occurs when `databaseVersion` is invalid semver. Do you have more information so this can be reproduced. May be try with different database image?

**Comment by Wolfie010** [comment]
I am experiencing this issue. I have a transaction that does a bunch of finds, inserts and relational inserts, It hangs on findOrCreate as well as model.addModel(model2). 

I am using lambda and rds.

**Comment by tiagomestreteixeira** [comment]
I'm facing the same issue on sequelize version: 4.42.0

**Comment by papb** [comment]
@tiagomestreteixeira Can you please open a new issue about it, filling in the issue template, including a SSCCE, and also link to this one? And also try with sequelize v5?

**Comment by RRicardotj** [comment]
I'm facing the same issue
