### ISSUE TITLE
Model.scope() does not work.

### ISSUE THREAD

**Issue by Tnarita0000** [sequelize/sequelize#10079]
## What are you doing?
I've defined two models and a scope.
models:  `user` and `subscription`
scope: `user.withEnableSubscription`

Relation: `user` has one `subscription`, `subscription` belongs to `user`.
```js
/* user model */
module.exports = (sequelize, DataTypes) => {
  const user = sequelize.define('user', {
    /* ... attributes */ 
  },
    scopes: {
      withEnableSubscription: {
        include: [
          {
            model: subscription,
            where: {
              $or: [
                { status: "active" },
                { status: "trial" },
              ],
            },
            required: true,
          },
        ],
      },
    },
  user.associate = function(models) {
    user.hasOne(models.subscription);
  };  
  return user;
};
```
```js
/* subscription model */
module.exports = (sequelize, DataTypes) => {
  const subscription = sequelize.define('subscription', {
    /* ... attributes */
  }, {});

  subscription.associate = function(models) {
    subscription.belongsTo(models.user);
  };  
  return subscription;
};
```

## What do you expect to happen?
I wanna get user instances these have a subscription of valid status, so I've defined scope as `INNER JOIN` query.
But it is doesn't work, so output this error stacktrace.

**code**
```js
const users =  await user.scope("withEnableSubscription").findAll();
```

**error**
```
(node:1894) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getTableName' of undefined
    at Function._validateIncludedElement (/Users/naritatakuya/git/SignalPremium/node_modules/sequelize/lib/model.js:466:30)
    at options.include.options.include.map.include (/Users/naritatakuya/git/SignalPremium/node_modules/sequelize/lib/model.js:395:37)
    at Array.map (<anonymous>)
    at Function._validateIncludedElements (/Users/naritatakuya/git/SignalPremium/node_modules/sequelize/lib/model.js:390:39)
    at Promise.try.then.then (/Users/naritatakuya/git/SignalPremium/node_modules/sequelize/lib/model.js:1577:14)
    at tryCatcher (/Users/naritatakuya/git/SignalPremium/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/naritatakuya/git/SignalPremium/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/naritatakuya/git/SignalPremium/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/naritatakuya/git/SignalPremium/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/naritatakuya/git/SignalPremium/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/Users/naritatakuya/git/SignalPremium/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/naritatakuya/git/SignalPremium/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/naritatakuya/git/SignalPremium/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/naritatakuya/git/SignalPremium/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
```

## What is actually happening?
It works so nice when I execute without `scope`.
```js
 const users = await user.findAll({
    include: [
      {   
        model: subscription,
        where: {
          $or: [
            { status: "active" },
            { status: "trial" },
          ],  
        },  
        required: true,
      },  
    ],  
  }); 
```

__Dialect:__ postgres
__Database version:__ 10.4
__Sequelize version:__ 4.39.0
__Tested with latest release:__ No

**Comment by SimonSchick** [comment]
This looks like `subscription` is undefined when assigning it to `model`.

**Comment by Tnarita0000** [comment]
@SimonSchick 
Thanks for reply.
What should I do to solve this happen?

**Comment by sushantdhiman** [comment]
```js
const Sequelize = require('./index');
const sequelize = require('./test/support').createSequelizeInstance();

const Task = sequelize.define('task', {
  active: {
    type: Sequelize.DataTypes.BOOLEAN,
    defaultValue: false
  }
});

const User = sequelize.define('user', {

},
  {
    scopes: {
      withEnableSubscription: {
        include: [
          {
            model: Task,
            where: {
              [Sequelize.Op.or]: [
                { active: true }
              ]
            },
            required: true
          }
        ]
      }
    }
  });

Task.User = Task.belongsTo(User);
User.Task = User.hasOne(Task);

sequelize.sync({ force: true }).then(() => {
  return Promise.all([
    User.create({
      id: 1,
      task: {
        active: true
      }
    }, {
        include: [User.Task]
      }),
    User.create({
      id: 2,
      task: {
        active: false
      }
    }, {
        include: [User.Task]
      }),
    User.create({
      id: 3,
      task: {
        active: true
      }
    }, {
      include: [User.Task]
    })
  ]);
}).then(() => {
  return User.scope('withEnableSubscription').findAll().then(result => {
    console.log(JSON.stringify(result, null, 2));
  });
}).catch(e => {
  console.log(e);
});
```

```
[
  {
    "id": 1,
    "createdAt": "2018-11-20T03:53:01.368Z",
    "updatedAt": "2018-11-20T03:53:01.368Z",
    "task": {
      "id": 1,
      "active": true,
      "createdAt": "2018-11-20T03:53:01.381Z",
      "updatedAt": "2018-11-20T03:53:01.381Z",
      "userId": 1
    }
  },
  {
    "id": 3,
    "createdAt": "2018-11-20T03:53:01.370Z",
    "updatedAt": "2018-11-20T03:53:01.370Z",
    "task": {
      "id": 3,
      "active": true,
      "createdAt": "2018-11-20T03:53:01.386Z",
      "updatedAt": "2018-11-20T03:53:01.386Z",
      "userId": 3
    }
  }
]

```
