### ISSUE TITLE
.sync({alter:true)} causes issue with Boolean Default Values in MSSQL

### ISSUE THREAD

**Issue by Justintlai** [sequelize/sequelize#10101]
## What are you doing?

Creating a model with a boolean that has a `defaultValue: false` in **MSSQL** 

```js
isAdmin: { type: DataTypes.BOOLEAN, defaultValue: false, allowNull: false }
```

## What do you expect to happen?
When running the app with `alter: true` it should automatically update and alter tables requiring updates.

## What is actually happening?
The line that it errors on is relating to the boolean field with a default value.

`Executing (default): ALTER TABLE [solution_managers] ALTER COLUMN [isAdmin] BIT NOT NULL DEFAULT 0;`

The error given by sequelize:
```js
Unhandled rejection SequelizeDatabaseError: Incorrect syntax near the keyword 'DEFAULT'.
    at Query.formatError (\node_modules\sequelize\lib\dialects\mssql\query.js:315:12)
    at Request.connection.lib.Request [as userCallback] (\node_modules\sequelize\lib\dialects\mssql\query.js:107:25)
    at Request.callback (\node_modules\tedious\lib\request.js:37:27)
    at Connection.endOfMessageMarkerReceived (\node_modules\tedious\lib\connection.js:1880:20)
    at Connection.dispatchEvent (\node_modules\tedious\lib\connection.js:997:36)    at Parser.tokenStreamParser.on (\node_modules\tedious\lib\connection.js:827:14)
    at Parser.emit (events.js:182:13)
    at Parser.parser.on.token (\node_modules\tedious\lib\token\token-stream-parser.js:27:14)
    at Parser.emit (events.js:182:13)
    at addChunk (\node_modules\readable-stream\lib\_stream_readable.js:301:12)
    at readableAddChunk (\node_modules\readable-stream\lib\_stream_readable.js:283:11)
    at Parser.Readable.push (\node_modules\readable-stream\lib\_stream_readable.js:247:10)
    at Parser.Transform.push (\node_modules\readable-stream\lib\_stream_transform.js:149:32)
    at Parser.afterTransform (\node_modules\readable-stream\lib\_stream_transform.js:92:10)
    at Parser._transform (\node_modules\tedious\lib\token\stream-parser.js:40:7)    at Parser.Transform._read (\node_modules\readable-stream\lib\_stream_transform.js:185:10)
    at Parser.Transform._write (\node_modules\readable-stream\lib\_stream_transform.js:173:83)
    at doWrite (\node_modules\readable-stream\lib\_stream_writable.js:429:139)
    at writeOrBuffer (\node_modules\readable-stream\lib\_stream_writable.js:418:5)
    at Parser.Writable.write (\node_modules\readable-stream\lib\_stream_writable.js:327:11)
    at Parser.addEndOfMessageMarker (\node_modules\tedious\lib\token\token-stream-parser.js:45:24)
    at Connection.message (\node_modules\tedious\lib\connection.js:1869:32)
```

__Dialect:__ mssql 
__Dialect version:__ XXX
__Database version:__ SQL SERVER 2016
__Sequelize version:__ 4.41.0
__Tested with latest release:__ 5.0.0-beta.13

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by lyh2668** [comment]
I found the same problem as you.

**Comment by sushantdhiman** [comment]
May I get some SSCCE so this can be fixed, I wasn;t able to reproduce this 

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396

**Comment by Taher62** [comment]
Is this issue solved ?
I have the same problem

**Comment by papb** [comment]
@Taher62 Please open a [new bug report](https://github.com/sequelize/sequelize/issues/new?assignees=&labels=&template=bug_report.md&title=) and fill the template.

**Comment by dionrodrigues** [comment]
I encountered this problem here too, it occurs because he tries to change the default value of the column with "ALTER COLUMN" in my experience with MSSQL this is impossible to do this way. In MSSQL whenever a table with a default value is created, it adds a constraint for that value. I know it's a lot of work, so here where I work we never change the default value, my suggestion for developers is to remove the update from the default value of the query when using connection.sync ({alter: true}).

Useful link: https://stackoverflow.com/questions/15547210/modify-default-value-in-sql-server

**Comment by Angrigo** [comment]
still an issue, any news? 
    "sequelize": "^6.5.0",
    "sequelize-cli": "^6.2.0",
    "tedious": "^9.2.3",

**Comment by BevanLandoByte** [comment]
I am also experiencing the problem
"sequelize": "^6.6.5"
"tedious": "^11.0.7"

**Comment by devtaha** [comment]
same problem I was facing 
in my case I was running sync with **force true** while no tables were there in db

that why such error occurred for me 
It might help someone.
