### ISSUE TITLE
Error: Invalid value ...  when add new associated

### ISSUE THREAD

**Issue by taphuocanh** [sequelize/sequelize#10133]
## I have two datatable has defined similarly in relation n: m

```js
// users table
const users = sequelize.define('users', {
    username: Sequelize.STRING,
    password: Sequelize.STRING,
}, {
    paranoid: true
});

// companies table
const companies = sequelize.define('companies', {
    name: Sequelize.STRING,
    host: Sequelize.STRING,
    prefix: Sequelize.STRING,
    options: Sequelize.JSON,
 }, {
    paranoid: true
 });

// connection table of two tables
OwnerCompanyModel = sequelize.define('OwnerCompany', {
    userId: Sequelize.INTEGER,
    companyId: Sequelize.INTEGER,
}, {
    freezeTableName: true,
    paranoid: true
});

// relations
users.belongsToMany(models.companiesModel, { as: 'Companies', through: 'OwnerCompany' })
companies.belongsToMany(models.usersModel, { as: 'Owners', through: 'OwnerCompany' })

```
After the user authentication process, I saved the the authenticated user instanceto the express request by a middleware as follows

```
function (req, res, next) {
    let user = await usersModel.findOne({ 
        where: {
            ...
        } 
    })
    ...
    req.user = user
    next()
}
```

## Problem
In a router: 
```
getById: async (req, res, next) => {
    try {
        const company = await req.user.getCompanies({ 
            where: { 
                id: req.params.companyId 
            },
            includes: [
                { model: usersModel, as: 'Owners' },
            ] 
        })
        return res.json(company)
    } catch (e) {
        return res.json({ status: 'error', code: '9999', message: e.message, file: current_file })
    }
}
```
Then result is exactly what I want, with a company by id returned.

In another router 

```
addNew: async (req, res, next) => {
    try {
        const { name, host } = req.body
        var isUnique = 0
        while (!isUnique) {
            var prefix = Math.random().toString(36).slice(-5)
            isUnique = companiesModel.count({ where: { prefix: prefix } })
        }
        const companyData = {
            name: name,
            host: host,
            prefix: prefix
        }
        const company = await companiesModel.create(companyData)
        const user = await usersModel.findById(req.user.id)
        await user.addCompanies(company)
        return res.json(company)
    } catch (e) {
        return res.json({ status: 'error', code: '9999', message: e.message, file: current_file })
    }
},
```
Then result is exactly what I want, with a new company created returned. But if I change the second route, instead of find user from data user from req variable, then I use straight user saved in the req variable as in first route, to the following, the error result:
```
addNew: async (req, res, next) => {
    try {
        const { name, host } = req.body
        var isUnique = 0
        while (!isUnique) {
            var prefix = Math.random().toString(36).slice(-5)
            isUnique = companiesModel.count({ where: { prefix: prefix } })
        }
        const companyData = {
            name: name,
            host: host,
            prefix: prefix
        }
        const company = await companiesModel.create(companyData)
        //const user = await usersModel.findById(req.user.id)
        await req.user.addCompanies(company)
        return res.json(company)
    } catch (e) {
        return res.json({ status: 'error', code: '9999', message: e.message, file: current_file })
    }
},
```
I get error

```
Error: Invalid value companies {
  dataValues:
   { id: 4,
     name: 'test organization 1',
     host: 'http://localhost',
     prefix: '2si51',
     updatedAt: 2018-11-06T14:10:10.386Z,
     createdAt: 2018-11-06T14:10:10.386Z },
  _previousDataValues:
   { name: 'test organization 1',
     host: 'http://localhost',
     prefix: '2si51',
     id: 4,
     options: undefined,
     createdAt: 2018-11-06T14:10:10.386Z,
     updatedAt: 2018-11-06T14:10:10.386Z,
     deletedAt: undefined },
  _changed:
   { name: false,
     host: false,
     prefix: false,
     id: false,
     options: false,
     createdAt: false,
     updatedAt: false,
     deletedAt: false },
  _modelOptions:
   { timestamps: true,
     validate: {},
     freezeTableName: false,
     underscored: false,
     underscoredAll: false,
     paranoid: true,
     rejectOnEmpty: false,
     whereCollection: null,
     schema: null,
     schemaDelimiter: '',
     defaultScope: {},
     scopes: [],
     indexes: [],
     name: { plural: 'companies', singular: 'company' },
     omitNull: false,
     sequelize:
      Sequelize {
        options: [Object],
        config: [Object],
        dialect: [Object],
        queryInterface: [Object],
        models: [Object],
        modelManager: [Object],
        connectionManager: [Object],
        importCache: {},
        test: [Object] },
     hooks: {},
     uniqueKeys: {} },
  _options: { isNewRecord: true, _schema: null, _schemaDelimiter: '' },
  __eagerlyLoadedAssociations: [],
  isNewRecord: false }
    at Object.escape (C:\Users\PLH\Desktop\Nodejs Project\api-thuphi\node_modules\sequelize\lib\sql-string.js:66:11)
    at Object.escape (C:\Users\PLH\Desktop\Nodejs Project\api-thuphi\node_modules\sequelize\lib\dialects\abstract\query-generator.js:936:22)
    at _joinKeyValue.value.map.item (C:\Users\PLH\Desktop\Nodejs Project\api-thuphi\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2371:69)
    at Array.map (<anonymous>)
    at Object._whereParseSingleValueObject (C:\Users\PLH\Desktop\Nodejs Project\api-thuphi\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2371:52)
    at Object.whereItemQuery (C:\Users\PLH\Desktop\Nodejs Project\api-thuphi\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2129:19)
    at Utils.getComplexKeys.forEach.prop (C:\Users\PLH\Desktop\Nodejs Project\api-thuphi\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1996:25)
    at Array.forEach (<anonymous>)
    at Object.whereItemsQuery (C:\Users\PLH\Desktop\Nodejs Project\api-thuphi\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1994:35)
    at value.map.item (C:\Users\PLH\Desktop\Nodejs Project\api-thuphi\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2192:30)
    at Array.map (<anonymous>)
    at Object._whereGroupBind (C:\Users\PLH\Desktop\Nodejs Project\api-thuphi\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2191:21)
    at Object.whereItemQuery (C:\Users\PLH\Desktop\Nodejs Project\api-thuphi\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2104:19)
    at Utils.getComplexKeys.forEach.prop (C:\Users\PLH\Desktop\Nodejs Project\api-thuphi\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1996:25)
    at Array.forEach (<anonymous>)
    at Object.whereItemsQuery (C:\Users\PLH\Desktop\Nodejs Project\api-thuphi\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1994:35)
    at Object.getWhereConditions (C:\Users\PLH\Desktop\Nodejs Project\api-thuphi\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2458:19)
    at Object.selectQuery (C:\Users\PLH\Desktop\Nodejs Project\api-thuphi\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1142:28)
    at QueryInterface.select (C:\Users\PLH\Desktop\Nodejs Project\api-thuphi\node_modules\sequelize\lib\query-interface.js:1105:27)
    at Promise.try.then.then.then (C:\Users\PLH\Desktop\Nodejs Project\api-thuphi\node_modules\sequelize\lib\model.js:1604:34)
    at tryCatcher (C:\Users\PLH\Desktop\Nodejs Project\api-thuphi\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\PLH\Desktop\Nodejs Project\api-thuphi\node_modules\bluebird\js\release\promise.js:512:31)
```

## What is actually happening?
__Dialect:__ mysql
__Database version:__ 5.7.21
__Sequelize version:__ 4.39.0

|Mysql details |     |
|-----------------|----------|
|innodb_version|	5.7.21|
|protocol_version|	10|
|slave_type_conversions|	|
|tls_version|	TLSv1,TLSv1.1|
|version|	5.7.21-cll-lve|
|version_comment|	MySQL Community Server - (GPL)|
|version_compile_machine|	x86_64|
|version_compile_os|	Linux|

Please help me, thank you!

**Comment by sushantdhiman** [comment]
I was able to reproduce this issue

```js
'use strict';

const Sequelize = require('./index');
const sequelize = require('./test/support').createSequelizeInstance();

const users = sequelize.define('users', {
  username: Sequelize.STRING,
  password: Sequelize.STRING
}, {
  paranoid: true
});

// companies table
const companies = sequelize.define('companies', {
  name: Sequelize.STRING,
  host: Sequelize.STRING,
  prefix: Sequelize.STRING,
  options: Sequelize.JSON
}, {
  paranoid: true
});

const companies1 = sequelize.define('companies', {
  name: Sequelize.STRING,
  host: Sequelize.STRING,
  prefix: Sequelize.STRING,
  options: Sequelize.JSON
}, {
  paranoid: true
});

// connection table of two tables
const OwnerCompanyModel = sequelize.define('OwnerCompany', {
  userId: Sequelize.INTEGER,
  companyId: Sequelize.INTEGER
}, {
  freezeTableName: true,
  paranoid: true
});

// relations
users.belongsToMany(companies, { as: 'Companies', through: 'OwnerCompany' })
companies.belongsToMany(users, { as: 'Owners', through: 'OwnerCompany' })

sequelize.sync({ force: true })
  .then(async () => {
    const companyData = {
      name: 'name',
      host: 'host',
      prefix: 'prefix'
    };
    const company = await companies1.create(companyData);
    const user = await users.create({});

    await user.addCompanies(company);
  });
```

```js
Error: Invalid value companies {
  dataValues: 
   { id: 1,
     name: 'name',
     host: 'host',
     prefix: 'prefix',
     updatedAt: 2018-11-15T05:43:07.174Z,
     createdAt: 2018-11-15T05:43:07.174Z,
     options: null,
     deletedAt: null },
  _previousDataValues: 
   { name: 'name',
     host: 'host',
     prefix: 'prefix',
     id: 1,
     options: null,
     createdAt: 2018-11-15T05:43:07.174Z,
     updatedAt: 2018-11-15T05:43:07.174Z,
     deletedAt: null },
  _changed: 
   { name: false,
     host: false,
     prefix: false,
     id: false,
     options: false,
     createdAt: false,
     updatedAt: false,
     deletedAt: false },
  _modelOptions: 
   { timestamps: true,
     validate: {},
     freezeTableName: false,
     underscored: false,
     paranoid: true,
     rejectOnEmpty: false,
     whereCollection: null,
     schema: null,
     schemaDelimiter: '',
     defaultScope: {},
     scopes: {},
     indexes: [],
     name: { plural: 'companies', singular: 'company' },
     omitNull: false,
     sequelize: 
      Sequelize {
        options: [Object],
        config: [Object],
        dialect: [Object],
        queryInterface: [Object],
        models: [Object],
        modelManager: [Object],
        connectionManager: [Object],
        importCache: {},
        test: [Object] },
     hooks: {} },
  _options: 
   { isNewRecord: true,
     _schema: null,
     _schemaDelimiter: '',
     attributes: undefined,
     include: undefined,
     raw: undefined,
     silent: undefined },
  isNewRecord: false }
     attributes: undefined,
    at Object.escape (/var/www/github/sequelize/lib/sql-string.js:66:11)
    at PostgresQueryGenerator.escape (/var/www/github/sequelize/lib/dialects/abstract/query-generator.js:965:22)
    at _joinKeyValue.value.map.item (/var/www/github/sequelize/lib/dialects/abstract/query-generator.js:2357:69)
    at Array.map (<anonymous>)
    at PostgresQueryGenerator._whereParseSingleValueObject (/var/www/github/sequelize/lib/dialects/abstract/query-generator.js:2357:52)
    at PostgresQueryGenerator.whereItemQuery (/var/www/github/sequelize/lib/dialects/abstract/query-generator.js:2140:19)
    at Utils.getComplexKeys.forEach.prop (/var/www/github/sequelize/lib/dialects/abstract/query-generator.js:2045:25)
    at Array.forEach (<anonymous>)
    at PostgresQueryGenerator.whereItemsQuery (/var/www/github/sequelize/lib/dialects/abstract/query-generator.js:2043:35)
    at value.map.item (/var/www/github/sequelize/lib/dialects/abstract/query-generator.js:2179:30)
    at Array.map (<anonymous>)
    at PostgresQueryGenerator._whereGroupBind (/var/www/github/sequelize/lib/dialects/abstract/query-generator.js:2178:21)
    at PostgresQueryGenerator.whereItemQuery (/var/www/github/sequelize/lib/dialects/abstract/query-generator.js:2114:19)
    at Utils.getComplexKeys.forEach.prop (/var/www/github/sequelize/lib/dialects/abstract/query-generator.js:2045:25)
    at Array.forEach (<anonymous>)
    at PostgresQueryGenerator.whereItemsQuery (/var/www/github/sequelize/lib/dialects/abstract/query-generator.js:2043:35)
    at PostgresQueryGenerator.getWhereConditions (/var/www/github/sequelize/lib/dialects/abstract/query-generator.js:2454:19)
    at PostgresQueryGenerator.selectQuery (/var/www/github/sequelize/lib/dialects/abstract/query-generator.js:1286:28)
    at QueryInterface.select (/var/www/github/sequelize/lib/query-interface.js:1106:27)
    at Promise.try.then.then.then (/var/www/github/sequelize/lib/model.js:1750:34)
From previous event:
    at Function.findAll (/var/www/github/sequelize/lib/model.js:1747:8)
    at BelongsToMany.add (/var/www/github/sequelize/lib/associations/belongs-to-many.js:692:38)
    at model.obj.(anonymous function) [as addCompanies] (/var/www/github/sequelize/lib/associations/helpers.js:64:40)
    at sequelize.sync.then (/var/www/github/sequelize/sscce.js:55:16)
    at <anonymous>

````

Looks like you have defined double models. You are trying to associate an company instance which doesn't belong to actual `companies` model you defined relationship with `users`.
