### ISSUE TITLE
[Bug] [postgres] [latest] query hangs, then spits out huge stack trace after 5 minutes beta-14

### ISSUE THREAD

**Issue by fraywing** [sequelize/sequelize#10143]
## What are you doing?

```js

// config
const sequelize = new Sequelize(
  DB_NAME,
  null,
  null,
  {
    dialect: 'postgres',
    host: DB_HOST,
    operatorsAliases: () => {},
    schema: 'blah',
    searchPath: 'blah',
    logging: NODE_ENV !== 'test' && log,
    benchmark: true,
    port: process.env.DB_PORT || 5432,
    hooks: {
      beforeConnect: async db => {
        // fetch the aws secrets or dev props
        const secretsPromise = await getSecret(secretName, {
          username: DB_USER,
          password: DB_PASS
        })
          .catch(err => {
            throw Error(err);
          });

        db.username = secretsPromise.username;
        db.password = secretsPromise.password;
      }
    },
    define: {
    // don't delete database entries but set the newly added attribute deletedAt
    // to the current date (when deletion was done). paranoid will only work if
    // timestamps are enabled
      paranoid: true,
      timestamps: true,
      freezeTableName: true,
      ID: 'ID'
    }
  }
);

sequelize.authenticate()
  .then(() => {
    if (NODE_ENV !== 'test') {
      console.info(chalk.green(`🙌 Database connection has been established successfully in ${NODE_ENV} mode! 🙌`));
    }
  })
  .catch(err => {
    console.error(chalk.red('🖕 Unable to connect to the database:'), err);
  });

export default sequelize;


// breaking code
const user = await User.findByPk(2);
 console.log(user)
```

## What do you expect to happen?

Give me a `User`

## What is actually happening?

Hangs for about 5 minutes after executing the query, and then prints out a HUGE circular dependency of every model in my DB. 

```
SELECT query time: 2ms
Executing (default): Executed (default): SELECT "ID", "Title", "Description", "Order", "State", "updatedAt", "createdAt", "deletedAt", "UserID", "ProjectID" FROM "rupie"."User" AS "User" WHERE ("User"."deletedAt" IS NULL AND "User"."ID" = '2');
```

Here is a small sample:

```
 Promise {
                                 _bitField: 0,
                                 _fulfillmentHandler0: undefined,
                                 _rejectionHandler0: undefined,
                                 _promise0: undefined,
                                 _receiver0: undefined,
                                 _trace:
                                  { Error
                                      at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/Users/austin/Dev/RupieNetwork/node_modules/bluebird/js/release/debuggability.js:411:19)
                                      at Promise._resolveFromExecutor (/Users/austin/Dev/RupieNetwork/node_modules/bluebird/js/release/promise.js:480:10)
                                      at new Promise (/Users/austin/Dev/RupieNetwork/node_modules/bluebird/js/release/promise.js:79:10)
                                      at new Deferred (/Users/austin/Dev/RupieNetwork/node_modules/generic-pool/lib/Deferred.js:13:21)
                                      at new ResourceLoan (/Users/austin/Dev/RupieNetwork/node_modules/generic-pool/lib/ResourceLoan.js:17:5)
                                      at Pool._dispatchPooledResourceToNextWaitingClient (/Users/austin/Dev/RupieNetwork/node_modules/generic-pool/lib/Pool.js:274:18)
                                      at _trackOperation.then.isValid (/Users/austin/Dev/RupieNetwork/node_modules/generic-pool/lib/Pool.js:179:12)
                                      at tryCatcher (/Users/austin/Dev/RupieNetwork/node_modules/bluebird/js/release/util.js:16:23)
                                      at Promise._settlePromiseFromHandler (/Users/austin/Dev/RupieNetwork/node_modules/bluebird/js/release/promise.js:512:31)
                                      at Promise._settlePromise (/Users/austin/Dev/RupieNetwork/node_modules/bluebird/js/release/promise.js:569:18)
                                      at Promise._settlePromise0 (/Users/austin/Dev/RupieNetwork/node_modules/bluebird/js/release/promise.js:614:10)
                                      at Promise._settlePromises (/Users/austin/Dev/RupieNetwork/node_modules/bluebird/js/release/promise.js:694:18)
                                      at _drainQueueStep (/Users/austin/Dev/RupieNetwork/node_modules/bluebird/js/release/async.js:138:12)
                                      at _drainQueue (/Users/austin/Dev/RupieNetwork/node_modules/bluebird/js/release/async.js:131:9)
                                      at Async._drainQueues (/Users/austin/Dev/RupieNetwork/node_modules/bluebird/js/release/async.js:147:5)
                                      at Immediate.Async.drainQueues (/Users/austin/Dev/RupieNetwork/node_modules/bluebird/js/release/async.js:17:14)
                                      at processImmediate (timers.js:632:19)
                                      at process.topLevelDomainCallback (domain.js:120:23)
                                    _parent:
                                     { Error
                                         at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/Users/austin/Dev/RupieNetwork/node_modules/bluebird/js/release/debuggability.js:411:19)
                                         at Promise._then (/Users/austin/Dev/RupieNetwork/node_modules/bluebird/js/release/promise.js:232:17)
                                         at Promise.then (/Users/austin/Dev/RupieNetwork/node_modules/bluebird/js/release/promise.js:125:17)
                                         at Pool._testOnBorrow (/Users/austin/Dev/RupieNetwork/node_modules/generic-pool/lib/Pool.js:170:7)
                                         at Pool._dispense (/Users/austin/Dev/RupieNetwork/node_modules/generic-pool/lib/Pool.js:240:14)
                                         at Pool.acquire (/Users/austin/Dev/RupieNetwork/node_modules/generic-pool/lib/Pool.js:453:10)
                                         at promise.then (/Users/austin/Dev/RupieNetwork/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:300:24)
                                         at tryCatcher (/Users/austin/Dev/RupieNetwork/node_modules/bluebird/js/release/util.js:16:23)
                                         at Promise._settlePromiseFromHandler (/Users/austin/Dev/RupieNetwork/node_modules/bluebird/js/release/promise.js:512:31)
                                         at Promise._settlePromise (/Users/austin/Dev/RupieNetwork/node_modules/bluebird/js/release/promise.js:569:18)
                                         at Promise._settlePromiseCtx (/Users/austin/Dev/RupieNetwork/node_modules/bluebird/js/release/promise.js:606:10)
                                         at _drainQueueStep (/Users/austin/Dev/RupieNetwork/node_modules/bluebird/js/release/async.js:142:12)
                                         at _drainQueue (/Users/austin/Dev/RupieNetwork/node_modules/bluebird/js/release/async.js:131:9)
                                         at Async._drainQueues (/Users/austin/Dev/RupieNetwork/node_modules/bluebird/js/release/async.js:147:5)
                                         at Immediate.Async.drainQueues (/Users/austin/Dev/RupieNetwork/node_modules/bluebird/js/release/async.js:17:14)
                                         at processImmediate (timers.js:632:19)
                                         at process.topLevelDomainCallback (domain.js:120:23)
                                       _parent:
                                        { Error
                                            at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/Users/austin/Dev/RupieNetwork/node_modules/bluebird/js/release/debuggability.js:411:19)
                                            at Promise._then (/Users/austin/Dev/RupieNetwork/node_modules/bluebird/js/release/promise.js:232:17)
                                            at Promise.then (/Users/austin/Dev/RupieNetwork/node_modules/bluebird/js/release/promise.js:125:17)
                                            at ConnectionManager.getConnection (/Users/austin/Dev/RupieNetwork/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:299:20)
                                            at Transaction.prepareEnvironment (/Users/austin/Dev/RupieNetwork/node_modules/sequelize/lib/transaction.js:122:60)
                                            at Sequelize._clsRun (/Users/austin/Dev/RupieNetwork/node_modules/sequelize/lib/sequelize.js:1014:26)
                                            at Function._clsRun (/Users/austin/Dev/RupieNetwork/node_modules/sequelize/lib/sequelize.js:1059:21)
                                            at Sequelize.transaction (/Users/austin/Dev/RupieNetwork/node_modules/sequelize/lib/sequelize.js:1013:22)
                                            at transaction (/Users/austin/Dev/RupieNetwork/src/server/clients/gigClient.js:78:20)
                                            at tryCatch (/Users/austin/Dev/RupieNetwork/node_modules/regenerator-runtime/runtime.js:62:40)
                                            at Generator.invoke [as _invoke] (/Users/austin/Dev/RupieNetwork/node_modules/regenerator-runtime/runtime.js:296:22)
                                            at Generator.prototype.(anonymous function) [as next] (/Users/austin/Dev/RupieNetwork/node_modules/regenerator-runtime/runtime.js:114:21)
                                            at asyncGeneratorStep (/Users/austin/Dev/RupieNetwork/src/server/clients/gigClient.js:30:103)
                                            at _next (/Users/austin/Dev/RupieNetwork/src/server/clients/gigClient.js:32:194)
                                            at /Users/austin/Dev/RupieNetwork/src/server/clients/gigClient.js:32:364
                                            at new Promise (<anonymous>)
                                            at /Users/austin/Dev/RupieNetwork/src/server/clients/gigClient.js:32:97
                                            at fetchCreateGig (/Users/austin/Dev/RupieNetwork/src/server/clients/gigClient.js:70:28)
                                            at _callee2$ (/Users/austin/Dev/RupieNetwork/src/server/controllers/gigController.js:82:26)
                                            at tryCatch (/Users/austin/Dev/RupieNetwork/node_modules/regenerator-runtime/runtime.js:62:40)
                                            at Generator.invoke [as _invoke] (/Users/austin/Dev/RupieNetwork/node_modules/regenerator-runtime/runtime.js:296:22)
                                            at Generator.prototype.(anonymous function) [as next] (/Users/austin/Dev/RupieNetwork/node_modules/regenerator-runtime/runtime.js:114:21)
                                            at asyncGeneratorStep (/Users/austin/Dev/RupieNetwork/src/server/controllers/gigController.js:22:103)
                                            at _next (/Users/austin/Dev/RupieNetwork/src/server/controllers/gigController.js:24:194)
                                            at /Users/austin/Dev/RupieNetwork/src/server/controllers/gigController.js:24:364
                                            at new Promise (<anonymous>)
                                            at /Users/austin/Dev/RupieNetwork/src/server/controllers/gigController.js:24:97
                                            at /Users/austin/Dev/RupieNetwork/src/server/controllers/gigController.js:72:26
                                          _parent: undefined,
                                          _promisesCreated: 0,
                                          _length: 1,
                                          _promiseCreated: null },
                                       _promisesCreated: 0,
                                       _length: 2,
                                       _promiseCreated: null },
                                    _promisesCreated: 0,
                                    _length: 3,
                                    _promiseCreated: null } },
                              _creationTimestamp: 1541720164677,
```

and stuff like

```
                                                          size: 0,
                                                          __data__: { hash: [Hash], map: Map {}, string: [Hash] } } },
                                                    _hasHstoreAttributes: false,
                                                    _isHstoreAttribute:
                                                     { [Function: memoized]
                                                       cache:
                                                        MapCache {
                                                          size: 0,
                                                          __data__: { hash: [Hash], map: Map {}, string: [Hash] } } },
                                                    _hasRangeAttributes: false,
                                                    _isRangeAttribute:
                                                     { [Function: memoized]
                                                       cache:
                                                        MapCache {
                                                          size: 0,
                                                          __data__: { hash: [Hash], map: Map {}, string: [Hash] } } },
                                                    _hasJsonAttributes: false,
                                                    _isJsonAttribute:
                                                     { [Function: memoized]
                                                       cache:
                                                        MapCache {
                                                          size: 0,
                                                          __data__: { hash: [Hash], map: Map {}, string: [Hash] } } },
                                                    _hasVirtualAttributes: false,
                                                    _isVirtualAttribute:
                                                     { [Function: memoized]
                                                       cache:
                                                        MapCache {
                                                          size: 0,
                                                          __data__: { hash: [Hash], map: Map {}, string: [Hash] } } },
                                                    _hasGeometryAttributes: false,
                                                    _isGeometryAttribute:
                                                     { [Function: memoized]
                                                       cache:
                                                        MapCache {
                                                          size: 0,
                                                          __data__: { hash: [Hash], map: Map {}, string: [Hash] } } },
                                                    _hasDefaultValues: false,
                                                    tableAttributes:
                                                     { createdAt:
                                                        { type: DATE { options: [Object], _length: '' },
                                                          allowNull: false,
                                                          _autoGenerated: true,
                                                          Model: [Circular],
                                                          fieldName: 'createdAt',
                                                          _modelAttribute: true,
                                                          field: 'createdAt' },
                                                       updatedAt:
                                                        { type: DATE { options: [Object], _length: '' },
                                                          allowNull: false,
                                                          _autoGenerated: true,
                                                          Model: [Circular],
                                                          fieldName: 'updatedAt',
                                                          _modelAttribute: true,
                                                          field: 'updatedAt' },
                                                       deletedAt:
                                                        { type: DATE { options: [Object], _length: '' },
                                                          _autoGenerated: true,
                                                          Model: [Circular],
                                                          fieldName: 'deletedAt',
                                                          _modelAttribute: true,
                                                          field: 'deletedAt' },
                                                       FeatureID:
                                                        { _autoGenerated: true,
                                                          type: UUID {},
                                                          primaryKey: true,
                                                          references: { model: [Object], key: 'ID' },
                                                          onDelete: 'CASCADE',
                                                          onUpdate: 'CASCADE',
                                                          Model: [Circular],
                                                          fieldName: 'FeatureID',
                                                          _modelAttribute: true,
                                                          field: 'FeatureID' },
                                                       TaskID:
                                                        { _autoGenerated: true,
                                                          type: UUID {},
                                                          primaryKey: true,
                                                          references: { model: [Object], key: 'ID' },
                                                          onDelete: 'CASCADE',
                                                          onUpdate: 'CASCADE',
                                                          Model: [Circular],
                                                          fieldName: 'TaskID',
                                                          _modelAttribute: true,
                                                          field: 'TaskID',
                                                          allowNull: true } },
                                                    
```
__Dialect:__ postgres
__Dialect version:__  
    "pg": "^7.6.1",
    "pg-hstore": "^2.3.2"
__Database version:__ postgres:10.5
__Sequelize version:__ "5.0.0-beta.14", but also latest 4.x
__Tested with latest release:__ yes

Pretty sure this has something to do with the new `sequelize-pool` thing, wasn't happening in an older version of beta

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by fraywing** [comment]
Also note: this only happens when I attempt to console.log the resolved promise, express will stringify it and return it in the response just fine. Utterly bizarre.

**Comment by shizpi** [comment]
The exact same is happening with me and I tracked it down also to logging.

Removing this solves it:
```
Raven.config(process.env.SENTRY_DSN, {
    environment: ENV,
    autoBreadcrumbs: true,
}).install()
app.use(Raven.requestHandler())
```

It hangs here:
```
models.sync().catch(err => console.error(err.stack)).then(() => {
  app.listen(port, () => {
    console.log(`The server is running at http://localhost:${port}/`)
  })
})
```

**Comment by sushantdhiman** [comment]
Looks like an issue with serialization, https://github.com/getsentry/raven-node/issues/231. You can enable `benchmark` mode to verify that indeed query is executed quickly but logging is trying to stringify whole object somewhere hangs node process
