### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by anandundavia** [sequelize/sequelize#10150]
## What are you doing?

I am trying to:
1. Create a User.
2. Create an Organization and then set the created User as the admin.

Here is the code:
```js
const Sequelize = require("sequelize");

const connectionOptions = {
    username: "sa",
    password: "Test@123",
    dialect: "mssql",
    host: "localhost",
    port: 1433,
    operatorsAliases: false,
    benchmark: true,

    pool: {
        max: 5,
        min: 0,
        acquire: 30000,
        idle: 10000
    },
    // Dialect specific options. These will be passed to the db driver
    dialectOptions: {
        encrypt: false
    }
};

const sequelize = new Sequelize(connectionOptions);

const User = sequelize.define(
    "User",
    {
        firstName: Sequelize.STRING,
        lastName: Sequelize.STRING
    },
    { underscored: true }
);

const Organization = sequelize.define(
    "Organization",
    {
        name: Sequelize.STRING
    },
    { underscored: true }
);

Organization.belongsTo(User, {
    as: "admin",
    foreignKey: {
        allowNull: false
    }
});

const createUserAndOrganization = async () => {
    // step 1
    await User.create({
        firstName: "John",
        lastName: "Doe"
    });

    // step 2
    const adminToSet = await User.findOne({ where: { firstName: "John" } });
    const org = Organization.build({
        name: "my-awesome-organization"
    });
    org.setAdmin(adminToSet);
};

const authenticated = async () => {
    try {
        await sequelize.sync({ force: true });
        await createUserAndOrganization();
    } catch (e) {
        console.error(e);
    }
};

sequelize
    .authenticate()
    .then(authenticated)
    .catch(err => {
        console.log(`[${err.name}]`, `[${err.original.code}]`, `${err.original.message}`);
    });

```

## What do you expect to happen?
It would create User with name `John Doe`, It would create Organization named `my-awesome-organization` and add John Doe as admin ( primary key of `John Doe` would be added to  `my-awesome-organization` as foreign key named `admin_id` )

## What is actually happening?
It throes error saying: 
```
TypeError: Cannot read property 'id' of undefined
```
Here is the complete stack trace:
```
/Users/anand/Desktop/node_modules/sequelize/lib/dialects/mssql/query.js:378
      id = id || results && results[0][this.getInsertIdField()];
                                      ^

TypeError: Cannot read property 'id' of undefined
    at Query.handleInsertQuery (/Users/anand/Desktop/node_modules/sequelize/lib/dialects/mssql/query.js:378:39)
    at Query.formatResults (/Users/anand/Desktop/node_modules/sequelize/lib/dialects/mssql/query.js:179:12)
    at Request.connection.lib.Request [as userCallback] (/Users/anand/Desktop/node_modules/sequelize/lib/dialects/mssql/query.js:109:26)
    at Request.callback (/Users/anand/Desktop/node_modules/tedious/lib/request.js:37:27)
    at Connection.endOfMessageMarkerReceived (/Users/anand/Desktop/node_modules/tedious/lib/connection.js:1880:20)
    at Connection.dispatchEvent (/Users/anand/Desktop/node_modules/tedious/lib/connection.js:997:36)
    at Parser.tokenStreamParser.on (/Users/anand/Desktop/node_modules/tedious/lib/connection.js:827:14)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at Parser.parser.on.token (/Users/anand/Desktop/node_modules/tedious/lib/token/token-stream-parser.js:27:14)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at addChunk (/Users/anand/Desktop/node_modules/readable-stream/lib/_stream_readable.js:301:12)
    at readableAddChunk (/Users/anand/Desktop/node_modules/readable-stream/lib/_stream_readable.js:283:11)
    at Parser.Readable.push (/Users/anand/Desktop/node_modules/readable-stream/lib/_stream_readable.js:247:10)
    at Parser.Transform.push (/Users/anand/Desktop/node_modules/readable-stream/lib/_stream_transform.js:149:32)
    at Parser.afterTransform (/Users/anand/Desktop/node_modules/readable-stream/lib/_stream_transform.js:92:10)
    at Parser._transform (/Users/anand/Desktop/node_modules/tedious/lib/token/stream-parser.js:40:7)
    at Parser.Transform._read (/Users/anand/Desktop/node_modules/readable-stream/lib/_stream_transform.js:185:10)
    at Parser.Transform._write (/Users/anand/Desktop/node_modules/readable-stream/lib/_stream_transform.js:173:83)
    at doWrite (/Users/anand/Desktop/node_modules/readable-stream/lib/_stream_writable.js:429:139)
    at writeOrBuffer (/Users/anand/Desktop/node_modules/readable-stream/lib/_stream_writable.js:418:5)
```

Dialect: mssql
Dialect version: (Tedius) ^3.0.1
Database version: Microsoft SQL Server 2017 (RTM-CU11) (KB4462262) - 14.0.3038.14 (X64) Developer Edition (64-bit) on Linux (Ubuntu 16.04.5 LTS)
Sequelize version: 4.41.2
Tested with latest release: Yes (4.41.2)

**PS: I am running mssql on Docker**

**Comment by anandundavia** [comment]
I am gonna try doing that soon. But I have this feeling that that won't fix the issue. I don't see how waiting for a promise to get resolved would solve the issue.

**Comment by sushantdhiman** [comment]
@tsasaki609 and I discussed in that in PR, as you know this instance is just built (and lacks primary key) we offer `save: false` option which will prevent `save` call when setting association.

Alternatively you can build and save instances with `include` perhaps, failing for undefined reference with cryptic message is odd but there is not good way to handle this case.

May be we can fix undefined reference then SQL can fail due to missing foreign key?

**Comment by rajendra0968** [comment]
docker add karne k baad ye aa raha h 
    "message": "Cannot read property 'findOne' of undefined"

**Comment by ephys** [comment]
Closing for inactivity
