### ISSUE TITLE
Seeding values to identity column on MSSQL

### ISSUE THREAD

**Issue by mubaidr** [sequelize/sequelize#10185]
## What are you doing?
Trying to seed data using seeder (including identity values)

```js
const data = [
  {
    ID: 1,
    DESCRIPTION: 'Male',
  },
  {
    ID: 2,
    DESCRIPTION: 'Female',
  },
  {
    ID: 3,
    DESCRIPTION: 'Other',
  },
].map(d => {
  d.CREATED_AT = new Date()
  d.UPDATED_AT = new Date()
  return d
})

const TBL_NAME = 'CAT_GENDER'
// TODO: fix forighn key check and identity insert
module.exports = {
  up: async queryInterface => {
    await queryInterface.sequelize.query(`SET IDENTITY_INSERT ${TBL_NAME } ON`)
    await queryInterface.bulkInsert(TBL_NAME, data, {})
    await queryInterface.sequelize.query(`SET IDENTITY_INSERT ${TBL_NAME } OFF`)
  },
  down: queryInterface => queryInterface.bulkDelete(TBL_NAME, null, {}),
}
```

## What do you expect to happen?
Data should be inserted successfully. 

## What is actually happening?
MSSQL DB error

_Output, either JSON or SQL_
```bash
RequestError: Cannot insert explicit value for identity column in table 'CAT_GENDER' when IDENTITY_INSERT is set to OFF.
```

__Dialect:__ mssql
__Dialect version:__ "tedious": "^3.0.1"
__Database version:__ MSSQL 2012
__Sequelize version:__ 4.41.2
__Tested with latest release:__ yes, 4.41.2

Related issue: https://github.com/sequelize/sequelize/issues/9671

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
This flag is global `SET IDENTITY_INSERT ${TBL_NAME } ON`? If not it is possible `insert` query ran on different connection. You can try wrapping this operation in transaction

**Comment by mubaidr** [comment]
Global option is not available in MSSQL and adding traction option to all queries still does not work: 

```js
up: async (queryInterface, Sequelize) =>
    queryInterface.sequelize
      .transaction(
        {
          isolationLevel: Sequelize.Transaction.ISOLATION_LEVELS.SERIALIZABLE,
        },
        async transaction => {
          await queryInterface.sequelize.query(
            `SET IDENTITY_INSERT ${TBL_NAME} ON`,
            {
              transaction,
            },
          )
          await queryInterface.bulkInsert(TBL_NAME, data, {
            transaction,
          })
          await queryInterface.sequelize.query(
            `SET IDENTITY_INSERT ${TBL_NAME} OFF`,
            {
              transaction,
            },
          )
          // your transactions
        },
      )
      .then(result => {
        console.log(result)
        // transaction has been committed. Do something after the commit if required.
      })
      .catch(err => {
        console.log(err)
        // do something with the err.
      }),
```

BTW am I using correct traction type? 
```js
isolationLevel: Sequelize.Transaction.ISOLATION_LEVELS.SERIALIZABLE
```

**Comment by sushantdhiman** [comment]
Show query logs

**Comment by mubaidr** [comment]
Here it is: 

```bash
RequestError: Cannot insert explicit value for identity column in table 'CAT_GENDER' when IDENTITY_INSERT is set to OFF.
       at RequestError (D:\Current\ors-node\api\node_modules\tedious\lib\errors.js:32:12)
       at Parser.tokenStreamParser.on.token (D:\Current\ors-node\api\node_modules\tedious\lib\connection.js:639:32)
       at Parser.emit (events.js:182:13)
       at Parser.parser.on.token (D:\Current\ors-node\api\node_modules\tedious\lib\token\token-stream-parser.js:27:14)
       at Parser.emit (events.js:182:13)
       at addChunk (D:\Current\ors-node\api\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:301:12)
       at readableAddChunk (D:\Current\ors-node\api\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:283:11)
       at Parser.Readable.push (D:\Current\ors-node\api\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:247:10)
       at Parser.Transform.push (D:\Current\ors-node\api\node_modules\tedious\node_modules\readable-stream\lib\_stream_transform.js:149:32)
       at doneParsing (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:80:14)
       at token (D:\Current\ors-node\api\node_modules\tedious\lib\token\infoerror-token-parser.js:48:5)
       at call.lineNumber (D:\Current\ors-node\api\node_modules\tedious\lib\token\infoerror-token-parser.js:13:19)
       at awaitData (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:185:7)
       at Parser.awaitData (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:109:7)
       at Parser.readUInt32LE (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:182:10)
       at parser.readBVarChar.procName (D:\Current\ors-node\api\node_modules\tedious\lib\token\infoerror-token-parser.js:12:90)
       at readBuffer.data (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:322:9)
       at awaitData (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:314:7)
       at Parser.awaitData (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:109:7)
       at Parser.readBuffer (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:311:10)
       at readUInt8.length (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:321:12)
       at awaitData (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:129:7)
       at Parser.awaitData (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:109:7)
       at Parser.readUInt8 (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:126:10)
       at Parser.readBVarChar (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:320:10)
       at parser.readBVarChar.serverName (D:\Current\ors-node\api\node_modules\tedious\lib\token\infoerror-token-parser.js:11:22)
       at readBuffer.data (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:322:9)
       at awaitData (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:314:7)
     message:
      "Cannot insert explicit value for identity column in table 'CAT_GENDER' when IDENTITY_INSERT is set to OFF.",
     code: 'EREQUEST',
     number: 544,
     state: 1,
     class: 16,
     serverName: 'MUBAIDR-DESKTOP\\SQLEXPRESS',
     procName: '',
     lineNumber: 1,
     sql:
      "INSERT INTO [CAT_GENDER] ([ID],[DESCRIPTION],[CREATED_AT],[UPDATED_AT]) VALUES (1,N'Male','2018-11-21 09:36:25.690 +00:00','2018-11-21 09:36:25.690 +00:00'),(2,N'Female','2018-11-21 09:36:25.690 +00:00','2018-11-21 09:36:25.690 +00:00'),(3,N'Other','2018-11-21 09:36:25.690 +00:00','2018-11-21 09:36:25.690 +00:00');" }
```

**Comment by sushantdhiman** [comment]
This is error stack not query logs

**Comment by mubaidr** [comment]
How to get query logs, please?

**Comment by sushantdhiman** [comment]
Turn on logging with `logging: console.log`

**Comment by mubaidr** [comment]
Logging only: 
```bash
== CAT_GENDER: migrating =======
Executing (b69ec226aaaa16de7407): SET IDENTITY_INSERT CAT_GENDER ON
Executing (b69ec226aaaa16de7407): INSERT INTO [CAT_GENDER] ([ID],[DESCRIPTION],[CREATED_AT],[UPDATED_AT]) VALUES (1,N'Male','2018-11-21 09:55:28.350 +00:00','2018-11-21 09:55:28.350 +00:00'),(2,N'Female','2018-11-21 09:55:28.350 +00:00','2018-11-21 09:55:28.350 +00:00'),(3,N'Other','2018-11-21 09:55:28.350 +00:00','2018-11-21 09:55:28.350 +00:00');
```
Complete with error: 
```bash
Loaded configuration file "config\config.js".
Using environment "development".
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules\sequelize\lib\sequelize.js:242:13
tedious deprecated The default value for `options.encrypt` will change from `false` to `true`. Please pass `false` explicitly if you want to retain current behaviour. node_modules\sequelize\lib\dialects\mssql\connection-manager.js:70:26
== CAT_GENDER: migrating =======
Executing (b69ec226aaaa16de7407): SET IDENTITY_INSERT CAT_GENDER ON
Executing (b69ec226aaaa16de7407): INSERT INTO [CAT_GENDER] ([ID],[DESCRIPTION],[CREATED_AT],[UPDATED_AT]) VALUES (1,N'Male','2018-11-21 09:55:28.350 +00:00','2018-11-21 09:55:28.350 +00:00'),(2,N'Female','2018-11-21 09:55:28.350 +00:00','2018-11-21 09:55:28.350 +00:00'),(3,N'Other','2018-11-21 09:55:28.350 +00:00','2018-11-21 09:55:28.350 +00:00');
{ SequelizeDatabaseError: Cannot insert explicit value for identity column in table 'CAT_GENDER' when IDENTITY_INSERT is set to OFF.
    at Query.formatError (D:\Current\ors-node\api\node_modules\sequelize\lib\dialects\mssql\query.js:315:12)
    at Request.connection.lib.Request [as userCallback] (D:\Current\ors-node\api\node_modules\sequelize\lib\dialects\mssql\query.js:107:25)
    at Request.callback (D:\Current\ors-node\api\node_modules\tedious\lib\request.js:37:27)
    at Connection.endOfMessageMarkerReceived (D:\Current\ors-node\api\node_modules\tedious\lib\connection.js:1880:20)
    at Connection.dispatchEvent (D:\Current\ors-node\api\node_modules\tedious\lib\connection.js:997:36)
    at Parser.tokenStreamParser.on (D:\Current\ors-node\api\node_modules\tedious\lib\connection.js:827:14)
    at Parser.emit (events.js:182:13)
    at Parser.parser.on.token (D:\Current\ors-node\api\node_modules\tedious\lib\token\token-stream-parser.js:27:14)
    at Parser.emit (events.js:182:13)
    at addChunk (D:\Current\ors-node\api\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:301:12)
    at readableAddChunk (D:\Current\ors-node\api\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:283:11)
    at Parser.Readable.push (D:\Current\ors-node\api\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:247:10)
    at Parser.Transform.push (D:\Current\ors-node\api\node_modules\tedious\node_modules\readable-stream\lib\_stream_transform.js:149:32)
    at Parser.afterTransform (D:\Current\ors-node\api\node_modules\tedious\node_modules\readable-stream\lib\_stream_transform.js:92:10)
    at Parser._transform (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:40:7)
    at Parser.Transform._read (D:\Current\ors-node\api\node_modules\tedious\node_modules\readable-stream\lib\_stream_transform.js:185:10)
    at Parser.Transform._write (D:\Current\ors-node\api\node_modules\tedious\node_modules\readable-stream\lib\_stream_transform.js:173:83)
    at doWrite (D:\Current\ors-node\api\node_modules\tedious\node_modules\readable-stream\lib\_stream_writable.js:429:139)
    at writeOrBuffer (D:\Current\ors-node\api\node_modules\tedious\node_modules\readable-stream\lib\_stream_writable.js:418:5)
    at Parser.Writable.write (D:\Current\ors-node\api\node_modules\tedious\node_modules\readable-stream\lib\_stream_writable.js:327:11)
    at Parser.addEndOfMessageMarker (D:\Current\ors-node\api\node_modules\tedious\lib\token\token-stream-parser.js:45:24)
    at Connection.message (D:\Current\ors-node\api\node_modules\tedious\lib\connection.js:1869:32)
    at Connection.dispatchEvent (D:\Current\ors-node\api\node_modules\tedious\lib\connection.js:997:36)
    at MessageIO.messageIo.on (D:\Current\ors-node\api\node_modules\tedious\lib\connection.js:897:14)
    at MessageIO.emit (events.js:182:13)
    at Message.message.on (D:\Current\ors-node\api\node_modules\tedious\lib\message-io.js:34:14)
    at Message.emit (events.js:187:15)
    at endReadableNT (D:\Current\ors-node\api\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:1038:12)
  name: 'SequelizeDatabaseError',
  parent:
   { RequestError: Cannot insert explicit value for identity column in table 'CAT_GENDER' when IDENTITY_INSERT is set to OFF.
       at RequestError (D:\Current\ors-node\api\node_modules\tedious\lib\errors.js:32:12)
       at Parser.tokenStreamParser.on.token (D:\Current\ors-node\api\node_modules\tedious\lib\connection.js:639:32)
       at Parser.emit (events.js:182:13)
       at Parser.parser.on.token (D:\Current\ors-node\api\node_modules\tedious\lib\token\token-stream-parser.js:27:14)
       at Parser.emit (events.js:182:13)
       at addChunk (D:\Current\ors-node\api\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:301:12)
       at readableAddChunk (D:\Current\ors-node\api\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:283:11)
       at Parser.Readable.push (D:\Current\ors-node\api\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:247:10)
       at Parser.Transform.push (D:\Current\ors-node\api\node_modules\tedious\node_modules\readable-stream\lib\_stream_transform.js:149:32)
       at doneParsing (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:80:14)
       at token (D:\Current\ors-node\api\node_modules\tedious\lib\token\infoerror-token-parser.js:48:5)
       at call.lineNumber (D:\Current\ors-node\api\node_modules\tedious\lib\token\infoerror-token-parser.js:13:19)
       at awaitData (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:185:7)
       at Parser.awaitData (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:109:7)
       at Parser.readUInt32LE (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:182:10)
       at parser.readBVarChar.procName (D:\Current\ors-node\api\node_modules\tedious\lib\token\infoerror-token-parser.js:12:90)
       at readBuffer.data (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:322:9)
       at awaitData (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:314:7)
       at Parser.awaitData (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:109:7)
       at Parser.readBuffer (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:311:10)
       at readUInt8.length (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:321:12)
       at awaitData (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:129:7)
       at Parser.awaitData (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:109:7)
       at Parser.readUInt8 (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:126:10)
       at Parser.readBVarChar (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:320:10)
       at parser.readBVarChar.serverName (D:\Current\ors-node\api\node_modules\tedious\lib\token\infoerror-token-parser.js:11:22)
       at readBuffer.data (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:322:9)
       at awaitData (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:314:7)
     message:
      "Cannot insert explicit value for identity column in table 'CAT_GENDER' when IDENTITY_INSERT is set to OFF.",
     code: 'EREQUEST',
     number: 544,
     state: 1,
     class: 16,
     serverName: 'MUBAIDR-DESKTOP\\SQLEXPRESS',
     procName: '',
     lineNumber: 1,
     sql:
      "INSERT INTO [CAT_GENDER] ([ID],[DESCRIPTION],[CREATED_AT],[UPDATED_AT]) VALUES (1,N'Male','2018-11-21 09:55:28.350 +00:00','2018-11-21 09:55:28.350 +00:00'),(2,N'Female','2018-11-21 09:55:28.350 +00:00','2018-11-21 09:55:28.350 +00:00'),(3,N'Other','2018-11-21 09:55:28.350 +00:00','2018-11-21 09:55:28.350 +00:00');" },
  original:
   { RequestError: Cannot insert explicit value for identity column in table 'CAT_GENDER' when IDENTITY_INSERT is set to OFF.
       at RequestError (D:\Current\ors-node\api\node_modules\tedious\lib\errors.js:32:12)
       at Parser.tokenStreamParser.on.token (D:\Current\ors-node\api\node_modules\tedious\lib\connection.js:639:32)
       at Parser.emit (events.js:182:13)
       at Parser.parser.on.token (D:\Current\ors-node\api\node_modules\tedious\lib\token\token-stream-parser.js:27:14)
       at Parser.emit (events.js:182:13)
       at addChunk (D:\Current\ors-node\api\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:301:12)
       at readableAddChunk (D:\Current\ors-node\api\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:283:11)
       at Parser.Readable.push (D:\Current\ors-node\api\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:247:10)
       at Parser.Transform.push (D:\Current\ors-node\api\node_modules\tedious\node_modules\readable-stream\lib\_stream_transform.js:149:32)
       at doneParsing (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:80:14)
       at token (D:\Current\ors-node\api\node_modules\tedious\lib\token\infoerror-token-parser.js:48:5)
       at call.lineNumber (D:\Current\ors-node\api\node_modules\tedious\lib\token\infoerror-token-parser.js:13:19)
       at awaitData (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:185:7)
       at Parser.awaitData (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:109:7)
       at Parser.readUInt32LE (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:182:10)
       at parser.readBVarChar.procName (D:\Current\ors-node\api\node_modules\tedious\lib\token\infoerror-token-parser.js:12:90)
       at readBuffer.data (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:322:9)
       at awaitData (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:314:7)
       at Parser.awaitData (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:109:7)
       at Parser.readBuffer (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:311:10)
       at readUInt8.length (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:321:12)
       at awaitData (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:129:7)
       at Parser.awaitData (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:109:7)
       at Parser.readUInt8 (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:126:10)
       at Parser.readBVarChar (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:320:10)
       at parser.readBVarChar.serverName (D:\Current\ors-node\api\node_modules\tedious\lib\token\infoerror-token-parser.js:11:22)
       at readBuffer.data (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:322:9)
       at awaitData (D:\Current\ors-node\api\node_modules\tedious\lib\token\stream-parser.js:314:7)
     message:
      "Cannot insert explicit value for identity column in table 'CAT_GENDER' when IDENTITY_INSERT is set to OFF.",
     code: 'EREQUEST',
     number: 544,
     state: 1,
     class: 16,
     serverName: 'MUBAIDR-DESKTOP\\SQLEXPRESS',
     procName: '',
     lineNumber: 1,
     sql:
      "INSERT INTO [CAT_GENDER] ([ID],[DESCRIPTION],[CREATED_AT],[UPDATED_AT]) VALUES (1,N'Male','2018-11-21 09:55:28.350 +00:00','2018-11-21 09:55:28.350 +00:00'),(2,N'Female','2018-11-21 09:55:28.350 +00:00','2018-11-21 09:55:28.350 +00:00'),(3,N'Other','2018-11-21 09:55:28.350 +00:00','2018-11-21 09:55:28.350 +00:00');" },
  sql:
   "INSERT INTO [CAT_GENDER] ([ID],[DESCRIPTION],[CREATED_AT],[UPDATED_AT]) VALUES (1,N'Male','2018-11-21 09:55:28.350 +00:00','2018-11-21 09:55:28.350 +00:00'),(2,N'Female','2018-11-21 09:55:28.350 +00:00','2018-11-21 09:55:28.350 +00:00'),(3,N'Other','2018-11-21 09:55:28.350 +00:00','2018-11-21 09:55:28.350 +00:00');" }
== CAT_GENDER: migrated (0.046s)
```

**Comment by mubaidr** [comment]
Running these generated queries in SQL runs fine. Looks like the session between queries is not being maintained so the option is not enabled (`SET IDENTITY_INSERT CAT_GENDER ON`) when second query is executed.

**Comment by sushantdhiman** [comment]
Looks like `SET IDENTITY_INSERT CAT_GENDER ON` works per statement level, connection is same, as evident by logs (transaction id is same). You have to do this by raw query

**Comment by mubaidr** [comment]
Interesting. Thanks

Is there anyway I can get query generated by `BulkInsert`?

**Comment by jasonlttl** [comment]
No idea if this is a good way to do this or not, but the bulkInsert method will actually perform the identity_insert statements on its own if you pass in some extra information. In this example, "id" is an autoincrementing value.

```
    return queryInterface.bulkInsert('connections', [
      { id: 1, type: 'Blah', approved: true },
      { id: 101, type: 'Blah2', approved: true }
    ], {}, {
      'id': {
        autoIncrement: true
      }
    });
```

[See the needIdentityInsertWrapper logic here](https://github.com/sequelize/sequelize/blob/master/lib/dialects/mssql/query-generator.js#L304)

**Comment by papb** [comment]
@jasonlttl Thanks for the info, does this help you @mubaidr ?

**Comment by mubaidr** [comment]
Good enough.

**Comment by siyer-contractor** [comment]
Tried this and doesn't work

Model
```

module.exports = (sequelize, DataTypes) => {
    const Client = sequelize.define("Client", {
        Id: {
            primaryKey: true,
            type: "INTEGER IDENTITY(1,1)",
        },

        Name:{
            type: "VARCHAR(250)",
            allowNull: false,
            validate: {
                notEmpty: true
            }
        },

        AddressLine1:{
            type: "VARCHAR(500)",
            allowNull: false,
            validate: {
                notEmpty: true
            }
        },

        AddressLine2:{
            type: "VARCHAR(500)",
            allowNull: true,
        },

        AddressLine3:{
            type: "VARCHAR(500)",
            allowNull: true,
        },

        Postcode:{
            type: "VARCHAR(10)",
            allowNull: false,
            validate: {
                notEmpty: true
            }
        },

        City:{
            type: "VARCHAR(100)",
            allowNull: true,
        },

        
        County:{
            type: "VARCHAR(50)",
            allowNull: true,
        },


        Country:{
            type: "VARCHAR(100)",
            allowNull: true,
        },

        ContactNumber : {
            type: "VARCHAR(20)",
            allowNull: true,
        },


        Email : {
            type: "VARCHAR(500)",
            allowNull: true,
        },

        CreatedAt :{
            type:"datetimeoffset(7) DEFAULT GETDATE()",
            allowNull: false
        },

        UpdatedAt :{
            type:"datetimeoffset(7)",
            allowNull: true
        }

    },
    {freezeTableName: true,  createdAt: false,updatedAt: false}
    );

    Client.associate=models=>{
        Client.hasMany(models.Invoice,{foreignKey:"ClientId"})
    }

   return Client;
}

```

```
var db = require('../models')

module.exports = async function () {
    return await db.Client.bulkCreate(
        [{
            Id:1,
            name:"Company",
            AddressLine1:"Add 1",
            Postcode:"Postcode",
            City:"UK"
        }],{},
        {
            autoincrement :true,
            needIdentityInsertWrapper:true
        }
    )
}
```
