### ISSUE TITLE
Models are not loading nested objects with HasMany

### ISSUE THREAD

**Issue by victorschinaider** [sequelize/sequelize#10222]
## What are you doing?
I have two models:

First: 
``` typescript
export function initVinculo(sequelize: SequelizeInterface) {
  const attributes: SequelizeAttributes<Partial<Vinculo> & any> = {
    id: {
      type: Sequelize.INTEGER,
      primaryKey: true,
      autoIncrement: true,
      field: 'IdVinculo',
    },
    atoNomeacao: {
      type: Sequelize.STRING,
      field: 'NomeacaoAto',
    },
    IdPessoa: {
      type: Sequelize.INTEGER,
      field: 'IdPessoa',
      references: {
        model: 'Servidor',
        key: 'id',
      },
    },
  };

  const VinculoDef = sequelize.define<VinculoInstance, Partial<Vinculo & any>>(
    'Vinculo',
    attributes,
    {
      tableName: 'Vinculo',
      schema: 'dbo',
    },
  );

  return VinculoDef;
}
```

Second:
 
``` typescript 
export function initServidor(sequelize: SequelizeInterface) {
  const attributes: SequelizeAttributes<Partial<Servidor> & any> = {
    id: {
      type: Sequelize.INTEGER,
      primaryKey: true,
      autoIncrement: true,
      field: 'IdPessoa',
    },
    'dadosServidor.nome': {
      type: Sequelize.STRING,
      field: 'Nome',
    },
    'dadosServidor.cpf': {
      type: Sequelize.STRING,
      field: 'CPF',
    },
    'dadosServidor.matricula': {
      type: Sequelize.STRING,
      field: 'Matricula',
    },
    'dadosServidor.digito': {
      type: Sequelize.SMALLINT,
      field: 'Digito',
    },
    'dadosServidor.dataNascimento': {
      type: Sequelize.DATE,
      field: 'DataNascimento',
    },
    'dadosServidor.sexo.sigla': {
      type: Sequelize.CHAR,
      field: 'Sexo',
    },
    'dadosServidor.dataEstadoCivil': {
      type: Sequelize.DATE,
      field: 'DataEstadoCivil',
    },
    'dadosServidor.nomePai': {
      type: Sequelize.STRING,
      field: 'PaiNome',
    },
    'dadosServidor.nomeMae': {
      type: Sequelize.STRING,
      field: 'MaeNome',
    },
  };

  const ServidorDef = sequelize.define<
    ServidorInstance,
    Partial<Servidor & any>
  >('Servidor', attributes, {
    tableName: 'Pessoa',
  });

  ServidorDef.associate = ({ Vinculo }: { Vinculo: VinculoModel }) => {
    ServidorDef.hasMany(Vinculo, {
      as: 'vinculos',
      foreignKey: 'IdPessoa',
    });
  };

  return ServidorDef;
}
```

And i'm trying to load results with association hasMany:
 
``` typescript
await this.db.models.Servidor.findAndCount({
      limit: 10,
      offset: 0,
      include: [
        {
          model: this.db.models.Vinculo,
          as: 'vinculos',
        },
      ],
    });
```

## What do you expect to happen?
That all things are loaded correct.

## What is actually happening?
```
Executing (default): SELECT [Servidor].*, [vinculos].[IdVinculo] AS [vinculos.id], [vinculos].[NomeacaoAto] AS [vinculos.atoNomeacao], [vinculos].[IdPessoa] AS [vinculos.IdPessoa] FROM (SELECT [Servidor].[IdPessoa] AS [id], [Nome] AS [dadosServidor.nome], [CPF] AS [dadosServidor.cpf], [Matricula] AS [dadosServidor.matricula], [Digito] AS [dadosServidor.digito], [DataNascimento] AS [dadosServidor.dataNascimento], [Sexo] AS [dadosServidor.sexo.sigla], [DataEstadoCivil] AS [dadosServidor.dataEstadoCivil], [PaiNome] AS [dadosServidor.nomePai], [MaeNome] AS [dadosServidor.nomeMae] FROM [Pessoa] AS [Servidor] ORDER BY [Servidor].[IdPessoa] OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY) AS [Servidor] LEFT OUTER JOIN [dbo].[Vinculo] AS [vinculos] ON [Servidor].[id] = [vinculos].[IdPessoa];

/home/schinaider/Documentos/rh-api-v2/node_modules/sequelize/lib/dialects/abstract/query.js:551
                primaryKeyAttributes = includeMap[prefix].model.primaryKeyAttributes;
                                                          ^
TypeError: Cannot read property 'model' of undefined
    at Function._groupJoinData (/home/schinaider/Documentos/rh-api-v2/node_modules/sequelize/lib/dialects/abstract/query.js:551:59)
    at Query.handleSelectQuery (/home/schinaider/Documentos/rh-api-v2/node_modules/sequelize/lib/dialects/abstract/query.js:284:31)
    at Query.formatResults (/home/schinaider/Documentos/rh-api-v2/node_modules/sequelize/lib/dialects/mssql/query.js:215:21)
    at Request.connection.lib.Request [as userCallback] (/home/schinaider/Documentos/rh-api-v2/node_modules/sequelize/lib/dialects/mssql/query.js:109:26)
    at Request.callback (/home/schinaider/Documentos/rh-api-v2/node_modules/tedious/lib/request.js:37:27)
    at Connection.endOfMessageMarkerReceived (/home/schinaider/Documentos/rh-api-v2/node_modules/tedious/lib/connection.js:1880:20)
    at Connection.dispatchEvent (/home/schinaider/Documentos/rh-api-v2/node_modules/tedious/lib/connection.js:997:36)
    at Parser.tokenStreamParser.on (/home/schinaider/Documentos/rh-api-v2/node_modules/tedious/lib/connection.js:827:14)
    at Parser.emit (events.js:182:13)
    at Parser.EventEmitter.emit (domain.js:442:20)
    at Parser.parser.on.token (/home/schinaider/Documentos/rh-api-v2/node_modules/tedious/lib/token/token-stream-parser.js:27:14)
    at Parser.emit (events.js:182:13)
    at Parser.EventEmitter.emit (domain.js:442:20)
    at addChunk (/home/schinaider/Documentos/rh-api-v2/node_modules/tedious/node_modules/readable-stream/lib/_stream_readable.js:301:12)
    at readableAddChunk (/home/schinaider/Documentos/rh-api-v2/node_modules/tedious/node_modules/readable-stream/lib/_stream_readable.js:283:11)
    at Parser.Readable.push (/home/schinaider/Documentos/rh-api-v2/node_modules/tedious/node_modules/readable-stream/lib/_stream_readable.js:247:10)
    at Parser.Transform.push (/home/schinaider/Documentos/rh-api-v2/node_modules/tedious/node_modules/readable-stream/lib/_stream_transform.js:149:32)
    at Parser.afterTransform (/home/schinaider/Documentos/rh-api-v2/node_modules/tedious/node_modules/readable-stream/lib/_stream_transform.js:92:10)
    at Parser._transform (/home/schinaider/Documentos/rh-api-v2/node_modules/tedious/lib/token/stream-parser.js:40:7)
    at Parser.Transform._read (/home/schinaider/Documentos/rh-api-v2/node_modules/tedious/node_modules/readable-stream/lib/_stream_transform.js:185:10)
    at Parser.Transform._write (/home/schinaider/Documentos/rh-api-v2/node_modules/tedious/node_modules/readable-stream/lib/_stream_transform.js:173:83)
    at doWrite (/home/schinaider/Documentos/rh-api-v2/node_modules/tedious/node_modules/readable-stream/lib/_stream_writable.js:429:139)
```

**Comment by sushantdhiman** [comment]
Follow the issue template, specify required versions

-----------------------


Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
