### ISSUE TITLE
Source instance is inserted on belongsTo.createAssociation()

### ISSUE THREAD

**Issue by frlinw** [sequelize/sequelize#10268]
```js
## What are you doing?
I want to build an instance, create its belongsTo association then save the instance

const Office = sequelize.define('Office', {
  id: {
    type: Sequelize.UUID,
    defaultValue: Sequelize.UUIDV4,
    primaryKey: true
  }
  name: Sequelize.STRING
})

const User = sequelize.define('user', {
  id: {
    type: Sequelize.UUID,
    defaultValue: Sequelize.UUIDV4,
    primaryKey: true
  },
  name: {
      type: Sequelize.STRING
  }
  phone: {
      type: Sequelize.STRING
  },
  color: {
     type: DataTypes.STRING,
     defaultValue: 'green'
  }
})

User.belongsTo(Office, {
      as: 'office',
      foreignKey: 'officeId'
})

const create = async () => {
  const user = User.build({
    name: 'John',
    phone: '000000000',
  }, {
    isNewRecord: true
  })

 console.log(user.name) // 'John'
 console.log(user.color) // 'green'

  await user.createOffice({}) // <---- user is created here
  // tried with { save: false } as options, but generate the following error
  // UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'then' of undefined
  //    at target.create.then.newAssociatedObject (...\node_modules\sequelize\lib\associations\belongs-to.js:231:9)

  await user.save()

  console.log(user.name) // 'John'
  console.log(user.color) // undefined
}
```

## What do you expect to happen?
The built instance should be saved on .save() call only (it's not necessary to save the source instance of a belongsTo association)

## What is actually happening?
the built user is saved during user.createOffice().
All defaultValue are lost if you call user.save() after

__Dialect:__ postgres
__Sequelize version:__ 5.0.0-beta.13
__Tested with latest release:__ Yes, 5.0.0-beta.15

**Comment by justinkalland** [comment]
Here is a complete [SSCCE](http://sscce.org/) example. It helps greatly when the bug can reproduced with a simple copy and paste.

```js
const Sequelize = require('./');

const sequelize = new Sequelize({
  dialect: 'sqlite',
  file: ':memory:'
});

const Office = sequelize.define('Office', {
  id: {
    type: Sequelize.UUID,
    defaultValue: Sequelize.UUIDV4,
    primaryKey: true
  },
  name: Sequelize.STRING
});

const User = sequelize.define('user', {
  id: {
    type: Sequelize.UUID,
    defaultValue: Sequelize.UUIDV4,
    primaryKey: true
  },
  name: {
      type: Sequelize.STRING
  },
  phone: {
      type: Sequelize.STRING
  },
  color: {
     type: Sequelize.STRING,
     defaultValue: 'green'
  }
});

User.belongsTo(Office, {
      as: 'office',
      foreignKey: 'officeId'
});

(async () => {
  await Office.sync()
  await User.sync()
  
  const user = User.build({
    name: 'John',
    phone: '000000000',
  }, {
    isNewRecord: true
  })

  console.log(user.name) // 'John'
  console.log(user.color) // 'green'

  await user.createOffice({}) // <---- user is saved here (and it shouldn't)
  // tried with { save: false } as options, but generate the following error
  // UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'then' of undefined
  //    at target.create.then.newAssociatedObject (...\node_modules\sequelize\lib\associations\belongs-to.js:231:9)

  await user.save()

  console.log(user.name) // 'John'
  console.log(user.color) // undefined
})();
```

**Comment by justinkalland** [comment]
I agree this looks like a bug, I would also expect that the user record would not be inserted until `user.save()`. One thing I did notice on your example is at the end you had ```console.log(user.color) // undefined``` but on my execution that outputs `green` (as expected).

**Comment by justinkalland** [comment]
Digging deeper, here is where the source (`user`) gets saved: https://github.com/sequelize/sequelize/blob/9c0f0414623805136a24fc584d634b3a132e8211/lib/associations/belongs-to.js#L204-L211

This is also how the foreign key gets set on the source (in this case the `officeId` on the `user`).

So the question is what we want to be the expected behavior. I would expect that if the `user` already exists (is persisted to the database), that creating the office would save (persist) the `officeId` automatically. And I suspect this behavior is heavily relied upon. However I can see @frlinw's point that with a new record you may not expect it to be saved.

A proposed work around for this particular example is to create the office (not using `User.createOffice()`) and then updating the `user.officeId` and saving when you feel it is appropriate.

I will hold off on further work until we can gather more feedback and decide what should be the behavior.

**Comment by frlinw** [comment]
> One thing I did notice on your example is at the end you had console.log(user.color) // undefined but on my execution that outputs green (as expected).
It's because my exemple is wrong, you have to reselect the user from the db:
```js
const savedUser = User.findOne({ where: { id: user.id } })
console.log(savedUser.color) // undefined
```
`.createOffice()` just create the user with officeId then on `user.save()` there is an update which ignores defaultValues
```
// createOffice()
INSERT INTO "User" ("id","officeId") VALUES ($1,$2);
// save() defaultValue disappeared
UPDATE "User" SET "name"=$1,"phone"=$2 WHERE "id" = $3
```
> However I can see @frlinw's point that with a new record you may not expect it to be saved.
I my real case, I overrided the `create` method so the save of the user must be the last thing to do because there is an afterCreate hooks which expects some data.
