### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by deigratia** [sequelize/sequelize#10318]
when i want to join my model this exception was thrown, is anybody know how to solve this?
this is my code 

```js
Riwayat.hasMany(Regis, {foreignKey: 'id_pasien_baru'})
Regis.belongsTo(Riwayat, {foreignKey: 'id_pasien_baru'});

Riwayat.findAll({
    where:{id_pasien_baru:req.params.id},include:[Regis]
  }).then(Riwayat => {
    res.send(Riwayat)
  })
  .catch(err => {
    res.send('error')
  })
```

```
TypeError: Cannot read property 'name' of undefined
    at Function._validateIncludedElement (D:\axon\node_modules\sequelize\lib\model.js:535:42)
    at options.include.options.include.map.include (D:\axon\node_modules\sequelize\lib\model.js:395:37)
    at Array.map (<anonymous>)
    at Function._validateIncludedElements (D:\axon\node_modules\sequelize\lib\model.js:390:39)
    at Promise.try.then.then (D:\axon\node_modules\sequelize\lib\model.js:1570:14)
    at tryCatcher (D:\axon\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\axon\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\axon\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\axon\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\axon\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (D:\axon\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (D:\axon\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (D:\axon\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues (D:\axon\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
::1 - - [04/Jan/2019:09:12:11 +0000] "GET /api/join/237 HTTP/1.1" 200 5
```

**Comment by mkaufmaner** [comment]
This error is thrown when the association does not exist.  First, make sure you are defining your associations properly.  Second, I would recommend passing the association object you want to include like so;
```js
Riwayat.hasMany(Regis, {
	as: 'Regi'
	foreignKey: 'id_pasien_baru'
});

Regis.belongsTo(Riwayat, {
	as: 'Riwayat',
	foreignKey: 'id_pasien_baru'
});

Riwayat.findAll({
	include: [
		{
			association: Riwayat.associations.Regi
		}
	],
	where: {
		id_pasien_baru: req.params.id
	}
}).then((riwayats) => {
	res.send(riwayats);
}).catch(err => {
	res.send('error');
});
```

**Comment by deigratia** [comment]
oh thanks

**Comment by deigratia** [comment]
> This error is thrown when the association does not exist. First, make sure you are defining your associations properly. Second, I would recommend passing the association object you want to include like so;
> 
> ```js
> Riwayat.hasMany(Regis, {
> 	as: 'Regi'
> 	foreignKey: 'id_pasien_baru'
> });
> 
> Regis.belongsTo(Riwayat, {
> 	as: 'Riwayat',
> 	foreignKey: 'id_pasien_baru'
> });
> 
> Riwayat.findAll({
> 	include: [
> 		{
> 			association: Riwayat.associations.Regi
> 		}
> 	],
> 	where: {
> 		id_pasien_baru: req.params.id
> 	}
> }).then((riwayats) => {
> 	res.send(riwayats);
> }).catch(err => {
> 	res.send('error');
> });
> ```

if join 3 where the association table is dropped?

**Comment by deigratia** [comment]
> This error is thrown when the association does not exist. First, make sure you are defining your associations properly. Second, I would recommend passing the association object you want to include like so;
> 
> ```js
> Riwayat.hasMany(Regis, {
> 	as: 'Regi'
> 	foreignKey: 'id_pasien_baru'
> });
> 
> Regis.belongsTo(Riwayat, {
> 	as: 'Riwayat',
> 	foreignKey: 'id_pasien_baru'
> });
> 
> Riwayat.findAll({
> 	include: [
> 		{
> 			association: Riwayat.associations.Regi
> 		}
> 	],
> 	where: {
> 		id_pasien_baru: req.params.id
> 	}
> }).then((riwayats) => {
> 	res.send(riwayats);
> }).catch(err => {
> 	res.send('error');
> });
> ```

@

**Comment by deigratia** [comment]
> > This error is thrown when the association does not exist. First, make sure you are defining your associations properly. Second, I would recommend passing the association object you want to include like so;
> > ```js
> > Riwayat.hasMany(Regis, {
> > 	as: 'Regi'
> > 	foreignKey: 'id_pasien_baru'
> > });
> > 
> > Regis.belongsTo(Riwayat, {
> > 	as: 'Riwayat',
> > 	foreignKey: 'id_pasien_baru'
> > });
> > 
> > Riwayat.findAll({
> > 	include: [
> > 		{
> > 			association: Riwayat.associations.Regi
> > 		}
> > 	],
> > 	where: {
> > 		id_pasien_baru: req.params.id
> > 	}
> > }).then((riwayats) => {
> > 	res.send(riwayats);
> > }).catch(err => {
> > 	res.send('error');
> > });
> > ```
> 
>

if join 3 where the association table is dropped?

@mkaufmaner

**Comment by jerrywang1981** [comment]
another root cause could be Array.prototype.find was overwritten by other packages, e.g. the package 'collections' would overwrite Array.prototype.find and change the function signature. if you have same error message, and package 'collections', try to uninstall package 'collections' to see if it works.
