### ISSUE TITLE
Model named 'record' throws an error when inserting a new row through findOrCreate

### ISSUE THREAD

**Issue by craig-gordon** [sequelize/sequelize#10323]
## What are you doing?
Using Sequelize 5.0.0-beta.15, I am executing a simple findOrCreate query for a model named Record (table name 'record') that is creating a new table row. In every other permutation of this query there is no error.
1) Finding an existing row in the 'record' table through findOrCreate() yields a normal result.
2) Creating a new row in the 'record' table through create() yields a normal result.
3) Creating a new row in a different table (example: 'document') through findOrCreate() yields a normal result.

```js
const database = new Sequelize(/* options */, {
  define: {
    freezeTableName: true
  },
  /* other parameters */
});
```

```js
const Record = database.define('record', {
  /* model attributes */
});

Record.belongsTo(Player);
Player.hasMany(Record);
```
```js
Record.findOrCreate({where: {
  playerId: 1
  /* other parameters */
}});
```

## What do you expect to happen?
Calling Record.findOrCreate() with data not yet in the database should return the [instance, created] promise like normal.

## What is actually happening?
I receive this error:
```js
Unhandled rejection SequelizeDatabaseError: PL/pgSQL functions cannot accept type record
    at Query.formatError (C:\Users\cyghf\Desktop\wrhistory\node_modules\sequelize\lib\dialects\postgres\query.js:376:16)
    at query.catch.err (C:\Users\cyghf\Desktop\wrhistory\node_modules\sequelize\lib\dialects\postgres\query.js:86:18)
    at tryCatcher (C:\Users\cyghf\Desktop\wrhistory\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\cyghf\Desktop\wrhistory\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\cyghf\Desktop\wrhistory\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\cyghf\Desktop\wrhistory\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\cyghf\Desktop\wrhistory\node_modules\bluebird\js\release\promise.js:689:18)
    at Async._drainQueue (C:\Users\cyghf\Desktop\wrhistory\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\cyghf\Desktop\wrhistory\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\cyghf\Desktop\wrhistory\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

__Dialect:__ postgres
__Dialect version:__ pg@^7.7.1 (also tested with pg@^7.4.3)
__Database version:__ 10.4 (AWS RDS Engine version)
__Sequelize version:__ 5.0.0-beta.15
__Tested with latest release:__ Yes

**Comment by mubaidr** [comment]
`record ` is a built in variable for pgSQL databases. You need to use other model name.

**Comment by sushantdhiman** [comment]
^ OR we need to properly quote model name when constructing that error handling function
