### ISSUE TITLE
ARRAY(ENUM) does not work in Migrations (postgres)

### ISSUE THREAD

**Issue by MunifTanjim** [sequelize/sequelize#10388]
## What are you doing?

**migration file**: `./project/database/migrations/20190101060000-create-info.js`

```js
'use strict'

module.exports = {
  up: (queryInterface, Sequelize) => {
    try {
      return queryInterface.createTable('Infos', {
        InfoId: {
          allowNull: false,
          autoIncrement: true,
          primaryKey: true,
          type: Sequelize.INTEGER
        },
        type: {
          allowNull: false,
          defaultValue: ['personal'],
          type: Sequelize.ARRAY(
            Sequelize.ENUM([
              'current',
              'permanent',
              'home',
              'office',
              'personal'
            ])
          )
        },
        createdAt: {
          allowNull: false,
          type: Sequelize.DATE
        },
        updatedAt: {
          allowNull: false,
          type: Sequelize.DATE
        }
      })
    } catch (err) {
      console.log(err)
      throw err
    }
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.dropTable('Infos')
  }
}
```

The main issue is with the **`Sequelize.ARRAY(Sequelize.ENUM([...]))`** part.

## What do you expect to happen?

The migration to be successful...

## What is actually happening?

```
Sequelize CLI [Node: 8.11.4, CLI: 5.4.0, ORM: 5.0.0-beta.15]

Loaded configuration file "configs/sequelize-cli.config.js".
Using environment "development".
== 20190101060000-create-info: migrating =======
TypeError: Cannot read property 'getTableName' of undefined
    at ARRAY._stringify (./project/node_modules/sequelize/lib/dialects/postgres/data-types.js:573:54)
    at ARRAY.stringify (./project/node_modules/sequelize/lib/data-types.js:33:17)
    at PostgresQueryGenerator.escape (./project/node_modules/sequelize/lib/dialects/abstract/query-generator.js:955:30)
    at PostgresQueryGenerator.attributeToSQL (./project/node_modules/sequelize/lib/dialects/postgres/query-generator.js:502:31)
    at PostgresQueryGenerator.attributesToSQL (./project/node_modules/sequelize/lib/dialects/postgres/query-generator.js:578:45)
    at QueryInterface.createTable (./project/node_modules/sequelize/lib/query-interface.js:233:38)
    at Object.up (./project/database/migrations/20190101060000-create-info.js:6:29)
    at ./project/node_modules/umzug/lib/migration.js:130:33
    at Generator.next (<anonymous>)
    at step (./project/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at ./project/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

ERROR: Cannot read property 'getTableName' of undefined
```

__Dialect:__ postgres
__Dialect version:__ `"pg": "^7.8.0", "pg-hstore": "^2.3.2",`
__Database version:__ 11.1
__Sequelize version:__ 5.0.0-beta.15
__Tested with latest release:__ 5.0.0-beta.15

**Comment by MunifTanjim** [comment]
👋🏼

**Comment by jetaimefrc** [comment]
Still not working, hope you can fix @papb 

![Screen Shot 2019-08-05 at 12 04 01](https://user-images.githubusercontent.com/24296018/62440176-20c1ac00-b779-11e9-865b-0f67804b3452.png)

**Comment by papb** [comment]
Is this solely an issue with migrations, or something similar can be reproduced without the CLI?

**Comment by jetaimefrc** [comment]
> Is this solely an issue with migrations, or something similar can be reproduced without the CLI?

It's migrations!

**Comment by papb** [comment]
@jetaimefrc Are you saying that running the `queryInterface.createTable()` call outside the migrations environment works?

**Comment by jetaimefrc** [comment]
I do migrate up to migrations table! Yes, I used queryInterface.createTable()

**Comment by papb** [comment]
I discovered that this is not a Migrations issue. I opened a clean new issue to track this: #11285

**Comment by LWanjiru** [comment]
Hope this helps. I was stuck too long trying to figure it out after I got major bugs on a project. Here's the link to how I solved it ==> https://github.com/sequelize/sequelize/issues/11285#issuecomment-1729660886
