### ISSUE TITLE
belongsToMany Selecting non existing columns

### ISSUE THREAD

**Issue by challapradyumna** [sequelize/sequelize#10387]
## What are you doing?

Team Model

```js
module.exports = (sequelize, DataTypes) => {
  const Team = sequelize.define('Team', {
    name: DataTypes.STRING,
    description: DataTypes.TEXT
  }, {});
  Team.associate = function(models) {
    models.Team.belongsToMany(models.User, {
      through: {
        model: models.TeamUser,
        unique: false,
      },
      foreignKey: 'teamId'
    });
  };
  return Team;
};
```
User Model
```js
module.exports = (sequelize, DataTypes) => {
  const User = sequelize.define('User', {
    email: DataTypes.STRING
  }, {});
  User.associate = function(models) {
    // associations can be defined here
  };
  return User;
};
```

TeamUser Model
```js
module.exports = (sequelize, DataTypes) => {
  const TeamUser = sequelize.define('TeamUser', {
    teamId: DataTypes.INTEGER,
    userId: DataTypes.INTEGER
  }, {});
  TeamUser.associate = function(models) {
    models.TeamUser.hasMany(models.Team,{foreignKey: 'id',sourceKey:'teamId'})
    models.TeamUser.hasMany(models.User,{foriegnKey: 'id',sourceKey:'userId'})
  };
  return TeamUser;
};
```
Code for selection
```js
db.Team.findOne({
        where: {
            id: req.params.id
        }
    }).then(team => {
        if (team != null) {
            console.log(team.getUsers());  //Trying to get Users of Team - This is where it breaks
            res.status(200).json(team);
        } else {
            res.status(404);
        }
    })
```

## What do you expect to happen?
Get all Users of Team

## What is actually happening?
Executing (default): SELECT `User`.`id`, `User`.`email`, `User`.`createdAt`, `User`.`updatedAt`, `User`.`TeamUserTeamId`, `TeamUser`.`teamId` AS `TeamUser.teamId`, `TeamUser`.`userId` AS `TeamUser.userId`, `TeamUser`.`createdAt` AS `TeamUser.createdAt`, `TeamUser`.`updatedAt` AS `TeamUser.updatedAt`, `TeamUser`.`UserId` AS `TeamUser.UserId` FROM `Users` AS `User` INNER JOIN `TeamUsers` AS `TeamUser` ON `User`.`id` = `TeamUser`.`UserId` AND `TeamUser`.`teamId` = 4;

Unhandled rejection SequelizeDatabaseError: **Unknown column 'User.TeamUserTeamId' in 'field list'**
    at Query.formatError (/Users/challa.pradyumna/Documents/ServerConnect/server/node_modules/sequelize/lib/dialects/mysql/query.js:247:16)
    at Query.handler [as onResult] (/Users/challa.pradyumna/Documents/ServerConnect/server/node_modules/sequelize/lib/dialects/mysql/query.js:68:23)
    at Query.execute (/Users/challa.pradyumna/Documents/ServerConnect/server/node_modules/mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/Users/challa.pradyumna/Documents/ServerConnect/server/node_modules/mysql2/lib/connection.js:455:32)
    at PacketParser.onPacket (/Users/challa.pradyumna/Documents/ServerConnect/server/node_modules/mysql2/lib/connection.js:73:18)
    at PacketParser.executeStart (/Users/challa.pradyumna/Documents/ServerConnect/server/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/challa.pradyumna/Documents/ServerConnect/server/node_modules/mysql2/lib/connection.js:80:31)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

_Output, either JSON or SQL_

__Dialect:__ mysql / postgres / sqlite / mssql / any
__Dialect version:__ Mysql
__Database version:__ 5.6
__Sequelize version:__ 4.42
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Spelling mistake with `foreignKey` on this line

```js
TeamUser.hasMany(User,{ foriegnKey: 'id',sourceKey:'userId' })
```
