### ISSUE TITLE
[QUESTION] How I can associate an model with an belongsToMany through?

### ISSUE THREAD

**Issue by bloodf** [sequelize/sequelize#10395]
## What are you doing?
I've got 3 tables:
 - Users
 - Tournaments
 - Roles

Each tournament, can have many Users, that has an specific role on that tournament.

So I will make an table for joining Users to Tournaments, and I need a table to join the last table to a role. So an user for a tournament has a role.

#### Tournament Model
```js
models.Tournaments.belongsToMany(models.Users, {
      through: 'TournamentUser',
    });
```
#### User Model
```js
models.Users.belongsToMany(models.Tournaments, {
      through: 'TournamentUser',
    });
```

#### Tournament Model (Idea)
```js
models.Tournaments.belongsToMany(models.TournamentUser, {
      through: 'TournamentRole',
    });
```

### Error
```json
Debugger attached.
/Users/heitor/Versionamento/TournamentManager/node_modules/sequelize/lib/associations/mixin.js:37
      throw new Error(this.name + '.belongsToMany called with something that\'s not a subclass of Sequelize.Model');
      ^

Error: Tournaments.belongsToMany called with something that's not a subclass of Sequelize.Model
    at Function.belongsToMany (/Users/heitor/Versionamento/TournamentManager/node_modules/sequelize/lib/associations/mixin.js:37:13)
    at Function.Tournament.associate (/Users/heitor/Versionamento/TournamentManager/server/models/tournaments.js:13:24)
    at Object.keys.forEach (/Users/heitor/Versionamento/TournamentManager/server/models/index.js:37:19)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/heitor/Versionamento/TournamentManager/server/models/index.js:35:17)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/heitor/Versionamento/TournamentManager/server/controllers/Authentication.js:3:5)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/heitor/Versionamento/TournamentManager/server/handlers/Authentication.js:4:34)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
```

__Dialect:__ postgres
__Dialect version:__ latest
__Database version:__ latest
__Sequelize version:__ latest
__Tested with latest release:__ Yes

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by peabnuts123** [comment]
Just posting this around on all these similar issues; I ran into this error because i was importing my Models from another folder i.e. the file where my model was defined was importing `sequelize` from a different node_modules. This meant that the `instanceof` check was false because, even though my models WERE inheriting from `Model` from `sequelize` - it was a different class, technically (with all the same properties and attributes). 

You can think of a `foo instanceof MyClass` check as comparing the prototype of `foo` all the way up the chain e.g. `foo.__proto__ === MyClass.prototype`, `foo.__proto__.__proto__ === MyClass.prototype` etc. until either `__proto__` is `null` (in which case `instanceof = false`) or the `===` equality check is true (in which case `instanceof = true`). So this is why a different instance of the `Sequelize.Model.prototype` object would return `false` for an `instanceof` check. 

This is a pretty unique scenario so I solved it by symlinking the `node_modules` from my database project to my "shared code" project. Just wanted to post this in case anybody else was doing a similar thing, in an attempt to save somebody from a couple of hours of WTFing.

**Comment by nbkhope** [comment]
@peabnuts123 I have a project that defines some models as a separate npm package. When I import those models in my project and start my application, I get an error when it calls `.associate`:

```
Error: ModelNameGoesHere.hasMany called with something that's not a subclass of Sequelize.Model
```

`ModelNameGoesHere` is a model that is defined in a separate npm package. That is, it comes from

```
import ModelNameGoesHere from 'some-separate-npm-package'
```

When I copy the code from the package into my application, the problem goes away.

Is there any solution to this?

**Comment by vadivelJ96** [comment]
I think reading above all questions , sequelize ORM should be specific to the error.
 for eg , the above issue i also faced that  when defining relations in sequelize we use associations and sequelize works fine when all the model and relation in single file. But when i seperate the model and even though using require the circular dependency happens but the error we see will not show it as an circular dependency. All I know is it is easy to provide a dedicated topic in documentation .so that users will love to use code on thier way rather than a rigid structure . hope I find in the docs. thank you
