### ISSUE TITLE
MSSQL: Second connection error not handled and crashes the app

### ISSUE THREAD

**Issue by lckj210** [sequelize/sequelize#10406]
## What are you doing?

Doing a simple findAll operation on a non-existing host, for example, 192.168.1.222:1433.

The first error due to ETIMEOUT will be captured by this connectHandler, which is fine.
https://github.com/sequelize/sequelize/blob/8df9b8f3c8ff15427d8adbeb2c712dfe7df694d4/lib/dialects/mssql/connection-manager.js#L59-L73
```
{ SequelizeConnectionError: Failed to connect to 192.168.1.222:1433 in 1000ms
    at Promise.tap.catch.error (/node_modules/sequelize/lib/dialects/mssql/connection-manager.js:126:17)
    at tryCatcher (/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (timers.js:632:19)
    at process.topLevelDomainCallback (domain.js:120:23)
  name: 'SequelizeConnectionError',
  parent:
   { ConnectionError: Failed to connect to 192.168.1.222:1433 in 1000ms
       at ConnectionError (/node_modules/tedious/lib/errors.js:12:12)
       at Connection.connectTimeout (/node_modules/tedious/lib/connection.js:936:28)
       at Timeout._onTimeout (/node_modules/tedious/lib/connection.js:906:16)
       at listOnTimeout (timers.js:324:15)
       at processTimers (timers.js:268:5)
     message: 'Failed to connect to 192.168.1.222:1433 in 1000ms',
     code: 'ETIMEOUT' },
  original:
   { ConnectionError: Failed to connect to 192.168.1.222:1433 in 1000ms
       at ConnectionError (/node_modules/tedious/lib/errors.js:12:12)
       at Connection.connectTimeout (/node_modules/tedious/lib/connection.js:936:28)
       at Timeout._onTimeout (/node_modules/tedious/lib/connection.js:906:16)
       at listOnTimeout (timers.js:324:15)
       at processTimers (timers.js:268:5)
     message: 'Failed to connect to 192.168.1.222:1433 in 1000ms',
     code: 'ETIMEOUT' } }
```

Second error ESOCKET will surface around 1 minute later and is not captured by this errorHandler because the listener is removed after the first error in connectHandler. The app crashes.

https://github.com/sequelize/sequelize/blob/8df9b8f3c8ff15427d8adbeb2c712dfe7df694d4/lib/dialects/mssql/connection-manager.js#L59-L73

```
{ ConnectionError: Connection lost - connect ETIMEDOUT 192.168.1.222:1433
    at ConnectionError (/node_modules/tedious/lib/errors.js:12:12)
    at Connection.socketError (/node_modules/tedious/lib/connection.js:1020:28)
    at /node_modules/tedious/lib/connection.js:861:25
    at Socket.onError (/node_modules/tedious/lib/connector.js:49:9)
    at Socket.emit (events.js:188:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
  message: 'Connection lost - connect ETIMEDOUT 192.168.1.222:1433',
  code: 'ESOCKET' }
```

__Dialect:__ mssql
__Dialect version:__ 4.1.3
__Database version:__ XXX
__Sequelize version:__ 5.0.0-beta.16
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Thanks for this report will try to fix this soon

**Comment by bertolo1988** [comment]
Same here.
