### ISSUE TITLE
Model Indexes fields with sequelize.fn returns error 'undefined must be unique'

### ISSUE THREAD

**Issue by balestrinc** [sequelize/sequelize#10420]
## Defining indexes with sequelize.fn
I'm trying to define a unique index case insensitive, so as we can define fields with a sequelize object, I was trying to add an index using `sequelize.fn`. That worked, although the error message is coming like 'undefined must be unique'.

![image](https://user-images.githubusercontent.com/1029844/52343348-f62bac00-29fe-11e9-96a6-d8cd42f4d55e.png)

### Model Definition

```js
sequelize.define('Profile', {
    customerId: {
      type: STRING,
      allowNull: false,
      primaryKey: true
    },
    nickname: {
      type: STRING,
      allowNull: false
    },
    createdAt: {
      type: DATE,
      field: 'createdat'
    },
    updatedAt: {
      type: DATE,
      field: 'updatedat'
    }
  },
  {
    indexes: [
      {
        unique: true,
        name: 'profileUniqueNickname',
        fields: [sequelize.fn('lower', sequelize.col('nickname'))]
      }
    ]
  }
  );
```

### The stacktrace:

```
{ SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/projects/profiles/node_modules/sequelize/lib/dialects/sqlite/query.js:417:16)
    at Statement.afterExecute (/projects/profiles/node_modules/sequelize/lib/dialects/sqlite/query.js:119:32)
    at Statement.replacement (/projects/profiles/node_modules/sqlite3/lib/trace.js:19:31)
  name: 'SequelizeUniqueConstraintError',
  errors:
   [ ValidationErrorItem {
       message: 'undefined must be unique',
       type: 'unique violation',
       path: null,
       value: null,
       origin: 'DB',
       instance: [Object],
       validatorKey: 'not_unique',
       validatorName: null,
       validatorArgs: [] } ],
  fields: [ undefined ],
  parent:
   { Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: index 'profileUniqueNickname'
     errno: 19,
     code: 'SQLITE_CONSTRAINT',
    ...
```

## Expect validation message
`'nickname must be unique'`

## Actual validation message
`'undefined must be unique'`
This happen because the field definition is a function, so cannot replace it in the message. It would be nice if it would be possible to define an alias in this case

__Dialect:__ sqlite
__Sequelize version:__ 4.42.0
__Tested with latest release:__ v4.42.0

**Comment by seyfeddineZig** [comment]
I have the same issue, Do you have a solution for it ?

**Comment by balestrinc** [comment]
@seyfeddineZig No, I don't :/

**Comment by hauste77** [comment]
up
