### ISSUE TITLE
Sequelize min length field validation incorrect

### ISSUE THREAD

**Issue by sjhsieh** [sequelize/sequelize#10432]
I have a user model defined with a password field that has a min length of 6:
```
      password: {
          type: DataTypes.TEXT,
          allowNull: false,
          validate: {
          min: {
              args: 6,
              msg: "Password must be more than 6 characters"
            }
          }
      }
```

For the most part it works fine, but there are very rare occurrences that it will not work. This specific one is 8 characters: 4wikwp3q and I get the following error when I try to insert it into the database:

```
{ SequelizeValidationError: Validation error: Password must be more than 6 characters
    at Promise.all.then (/Users/steve/moov/moov-api/node_modules/sequelize/lib/instance-validator.js:77:15)
    at tryCatcher (/Users/steve/moov/moov-api/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/steve/moov/moov-api/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/steve/moov/moov-api/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/steve/moov/moov-api/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/steve/moov/moov-api/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/steve/moov/moov-api/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/Users/steve/moov/moov-api/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/Users/steve/moov/moov-api/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/Users/steve/moov/moov-api/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/Users/steve/moov/moov-api/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/steve/moov/moov-api/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/steve/moov/moov-api/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/steve/moov/moov-api/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/steve/moov/moov-api/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
  name: 'SequelizeValidationError',
  errors: 
   [ ValidationErrorItem {
       message: 'Password must be more than 6 characters',
       type: 'Validation error',
       path: 'password',
       value: '4wikwp3q',
       origin: 'FUNCTION',
       instance: [User],
       validatorKey: 'min',
       validatorName: 'min',
       validatorArgs: [Array],
       __raw: [Error] } ] }
```

**Comment by sushantdhiman** [comment]
Odd, I'll need a SSCCE to work on a fix

-------------------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396

**Comment by gyanjd** [comment]
use len instead of min.
