### ISSUE TITLE
"as" not working for eager loading

### ISSUE THREAD

**Issue by Ablu** [sequelize/sequelize#1044]
Hi,

I have two tables, one is `mana_accounts`. It has an `id`. The other one is `mana_characters`. It has and `id` and an `user_id` which references the `id` in `mana_accounts`. Now I try to do something like this:

``` c++
var Sequelize = require('sequelize-sqlite').sequelize;
var sequelize = new Sequelize('', '', '', {
    dialect: 'sqlite',
    storage: '/home/ablu/tales/sourceoftales/mana.db',
    define: {
        timestamps: false
    }
});

var Account = sequelize.define('mana_accounts', {
    id: { type: Sequelize.INTEGER, primaryKey: true}
});

var Character = sequelize.define('mana_characters', {
    id: { type: Sequelize.INTEGER, primaryKey: true },
    user_id: {
        type: Sequelize.INTEGER,
        references: "mana_accounts",
        referencesKey: "id"
    }
});

Character.belongsTo(Account, {foreignKey: 'user_id'});
Account.hasMany(Character, {foreignKey: 'user_id', as: "chars"});

Account.findAll({ include: [Character]}).success(function (accounts) {
    console.log(JSON.stringify(accounts))
});
```

However i get an error here:

```
Error: mana_characters is not associated to mana_accounts!
    at module.exports.validateIncludedElement (/home/ablu/node_modules/sequelize-sqlite/node_modules/sequelize/lib/dao-factory.js:1154:17)
    at null.<anonymous> (/home/ablu/node_modules/sequelize-sqlite/node_modules/sequelize/lib/dao-factory.js:337:42)
    at Array.map (native)
    at module.exports.DAOFactory.findAll (/home/ablu/node_modules/sequelize-sqlite/node_modules/sequelize/lib/dao-factory.js:336:43)
    at Object.<anonymous> (/home/ablu/WebstormProjects/untitled/main.js:26:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

Now... if i remove the `as: "chars"` part it works fine (well the collection of character is called manaCharacters then and not chars...

Since I am only following the docs here i suspect that this is a bug...

Regards,
Ablu

**Comment by sunitJindal** [comment]
The link to documentation is changed. [http://docs.sequelizejs.com/en/latest/docs/models-usage/#eager-loading](http://docs.sequelizejs.com/en/latest/docs/models-usage/#eager-loading)
