### ISSUE TITLE
" SequelizeDatabaseError: A column has been specified more than once in the order by list. Columns in the order by list must be unique" on MsSql when ordering by pk using limit

### ISSUE THREAD

**Issue by pathikrit-repo-personal** [sequelize/sequelize#10447]
I am using Sequelize  and while my query needs to be the last entered data in the table so I am using order by id(primary key ) and limit 1(I checked findOne method as well as findAll). but that throws the error.
I am giving all the details for debug.
MSSQL version:14.0.1000.169,
Sequelize version: 4.42.0,
router code:
UserShiftAllocationsModel.findAll({
            where: {
                user_master_id: user_id,
                end_date: null
            },
            include: [
                {
                    model: ShiftsModel,
                    as: 'ShiftsMaster',
                    attributes: ['id', 'name']
                }
            ],
            order: [
                ['id', 'DESC']
            ],
            attributes: ['id'],
            limit: 1
        }).then((user_current_shift) => {
            res.json({code: 200, success: true, msg: user_current_shift});
        });
executed Query:
SELECT [ShiftAllocations].[id], [ShiftsMaster].[id] AS [ShiftsMaster.id], [ShiftsMaster].[name] AS [ShiftsMaster.name] FROM [user_shift_allocation] AS [ShiftAllocations] LEFT OUTER JOIN [shift_master] AS [ShiftsMaster] ON [ShiftAllocations].[shift_master_id] = [ShiftsMaster].[id] WHERE [ShiftAllocations].[user_master_id] = 116 AND [ShiftAllocations].[end_date] IS NULL ORDER BY [ShiftAllocations].[id] DESC, [ShiftAllocations].[id] OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY;
Stack Trace:
 at Query.formatError (G:\cf-hrms\node_modules\sequelize\lib\dialects\mssql\query.js:315:12)
    at Request.connection.lib.Request [as userCallback] (G:\cf-hrms\node_modules\sequelize\lib\dialects\mssql\query.js:107:25)
    at Request.callback (G:\cf-hrms\node_modules\tedious\lib\request.js:37:27)
    at Connection.endOfMessageMarkerReceived (G:\cf-hrms\node_modules\tedious\lib\connection.js:1880:20)
    at Connection.dispatchEvent (G:\cf-hrms\node_modules\tedious\lib\connection.js:997:36)
    at Parser.tokenStreamParser.on (G:\cf-hrms\node_modules\tedious\lib\connection.js:827:14)
    at Parser.emit (events.js:182:13)
    at Parser.parser.on.token (G:\cf-hrms\node_modules\tedious\lib\token\token-stream-parser.js:27:14)
    at Parser.emit (events.js:182:13)
    at addChunk (G:\cf-hrms\node_modules\readable-stream\lib\_stream_readable.js:296:12)
    at readableAddChunk (G:\cf-hrms\node_modules\readable-stream\lib\_stream_readable.js:278:11)
    at Parser.Readable.push (G:\cf-hrms\node_modules\readable-stream\lib\_stream_readable.js:239:10)
    at Parser.Transform.push (G:\cf-hrms\node_modules\readable-stream\lib\_stream_transform.js:139:32)
    at Parser.afterTransform (G:\cf-hrms\node_modules\readable-stream\lib\_stream_transform.js:88:10)
    at Parser._transform (G:\cf-hrms\node_modules\tedious\lib\token\stream-parser.js:40:7)
    at Parser.Transform._read (G:\cf-hrms\node_modules\readable-stream\lib\_stream_transform.js:177:10)
    at Parser.Transform._write (G:\cf-hrms\node_modules\readable-stream\lib\_stream_transform.js:164:83)
    at doWrite (G:\cf-hrms\node_modules\readable-stream\lib\_stream_writable.js:405:139)
    at writeOrBuffer (G:\cf-hrms\node_modules\readable-stream\lib\_stream_writable.js:394:5)
    at Parser.Writable.write (G:\cf-hrms\node_modules\readable-stream\lib\_stream_writable.js:303:11)
    at Parser.addEndOfMessageMarker (G:\cf-hrms\node_modules\tedious\lib\token\token-stream-parser.js:45:24)
    at Connection.message (G:\cf-hrms\node_modules\tedious\lib\connection.js:1869:32)
Model Structure:
[for debug uses.txt](https://github.com/sequelize/sequelize/files/2864867/for.debug.uses.txt)

Note: The way I see it When the query is generated it is using  "OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY;" And not using Top or limit so after order by  **id,** another **id** is used for using next keyword.

P.S : Appreciate your hard work.

**Comment by pathikrit-repo-personal** [comment]
I think when ordering by primary key DESC its better to use Top in mssql

**Comment by pathikrit-repo-personal** [comment]
Is there any update?

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396

**Comment by dsbert** [comment]
Related https://github.com/sequelize/sequelize/issues/11258

**Comment by ajoshi08** [comment]
I am also runing into the same issue, is there any update on this ?
