### ISSUE TITLE
Op.any does not work when typeValidation = true

### ISSUE THREAD

**Issue by simonbrent** [sequelize/sequelize#10463]
## What are you doing?

```js
const sequelize = new Sequelize('database', 'username', 'password', { typeValidation: true });
const model = sequelize.define('foo', {
  id: { type: Sequelize.INTEGER }
});
model.findAll({ where: { [Sequelize.Op.any]: [1,2] } }).then(console.log);
```

## What do you expect to happen?
Records 1 and 2 are logged

## What is actually happening?
```
Unhandled rejection SequelizeValidationError: [1,2] is not a valid integer
at INTEGER.validate (node_modules/sequelize/lib/data-types.js:175:11)
at Object.escape (node_modules/sequelize/lib/dialects/abstract/query-generator.js:917:26)
at Object._whereParseSingleValueObject (node_modules/sequelize/lib/dialects/abstract/query-generator.js:2387:49)
...
```

This is because the `escape` function in query-generator requires `options.isList` to be true for an array value to be correctly validated, but on line 2387 it is called without any options: `this.escape(value, field)`.
The same is true for Op.all. On lines 2418 and 2422, escape is called for Op.any/Op.all with `isList = true`, but these lines only apply to ANY/ALL conditions which are nested, e.g. 
```
{ where: { [Sequelize.Op.not]: { [Sequelize.Op.any]: [ 1, 2 ] } }
```

__Dialect:__ postgres
__Dialect version:__ 10
__Sequelize version:__ 4.42.0
__Tested with latest release:__ Yes

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by reezer** [comment]
This is not just related to typeValidation cases. This is a fixed minimal example (id missing in the above):

```
const model = sequelize.define('user', {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true,
  }
}, {
    tableName: 'users',
    underscored: true,
  });

model.findOne({
  where: {
    id: { [Sequelize.Op.any]: [1, 2] }
  }
}).then(console.log);
```

**Comment by simonbrent** [comment]
Urgh, sorry about that. Fixed my initial comment.
