### ISSUE TITLE
MSSQL upsert do not user hasTrigger

### ISSUE THREAD

**Issue by manjirinamjoshi** [sequelize/sequelize#10477]
I am trying to use "sequelize" mssql to be able to do "upsert". The table has triggers and the upsert is failing.

```js
const Ticket = sequelize.define('Tickets', {
                Code: {type: Sequelize.STRING, primaryKey: true},
                Event: Sequelize.STRING
            }, { timestamps: false, tableName: 'Tickets', freezeTableName: true, hasTrigger: true });
            sequelize.sync().then(() => Ticket.upsert({
                Code: 'janedoe',
                Event: 'TEST:TEST'
            }));
```

The exact error is -

Unhandled rejection SequelizeDatabaseError: The target table 'Tickets_target' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause.
    at Query.formatError (/et/repo/serverless-access-mgmt/node_modules/sequelize/lib/dialects/mssql/query.js:315:12)
    at Request.connection.lib.Request [as userCallback] (/et/repo/serverless-access-mgmt/node_modules/sequelize/lib/dialects/mssql/query.js:107:25)
    at Request.callback (/et/repo/serverless-access-mgmt/node_modules/tedious/lib/request.js:37:27)

__Dialect:mssql
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ 4.42.0
__Tested with latest release:__ No (If yes, specify that version)

I tried to set "hasTrigger" in model.js for upsert, but didnt help - 

options.hasTrigger =  this.options ? this.options.hasTrigger : false;
return this.QueryInterface.upsert(this.getTableName(options), insertValues, updateValues, instance.where(), this, options);

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
```js
const Sequelize = require('./index');
const sequelize = require('./test/support').createSequelizeInstance();

const Ticket = sequelize.define('Tickets', {
	Code: {
		type: Sequelize.STRING,
		primaryKey: true
	},
	Event: Sequelize.STRING
}, {
	timestamps: false,
	tableName: 'Tickets',
	freezeTableName: true,
	hasTrigger: true
});

const triggerQuery = 'create trigger Tickets_ChangeTrig on [Tickets] for insert,update, delete \n' +
                          'as\n' +
                            'SET NOCOUNT ON\n' +
                            'if exists(select 1 from inserted)\n' +
                            'begin\n' +
                              'select * from inserted\n' +
                            'end\n' +
                            'if exists(select 1 from deleted)\n' +
                            'begin\n' +
                              'select * from deleted\n' +
                            'end\n';

sequelize
	.sync({ force: true })
	.then(() => {
		return main()
	});

const main = async () => {
	try {
		await sequelize.query(triggerQuery);
		await Ticket.upsert({
			Code: 'janedoe',
			Event: 'TEST:TEST'
		}, {
			logging: console.log
		});
	} catch (err) {
		console.log(err)
	}
}
```

**Comment by iantrudell** [comment]
Any update on this? Also experiencing the same issue with upsert and hasTriggers: true throwing the same error as above

**Comment by redhatva** [comment]
Also having same issue.. Why can't the options.hasTrigger be supported for upsert?
