### ISSUE TITLE
Invalid usage of the option NEXT in the FETCH statement.

### ISSUE THREAD

**Issue by MichaelJCole** [sequelize/sequelize#10472]
Here are the issues [symptoms](https://stackoverflow.com/a/54837260/1483977) and [context (copied below)](https://github.com/tediousjs/tedious/issues/872).

The root cause is Sequalize is preparing SQL statements with NEXT and FETCH, but w/o an ORDER BY.  This doesn't make sense to the server.  E.g.

```
SELECT [LawyerID], [LawInfDeptID], [LawInfInitials], [LawInfLawyerName], [LawInfNickName], [createdAt], [updatedAt] FROM [LawInf] AS [Lawyers] OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY;
```

See https://github.com/sequelize/sequelize/blob/master/lib/dialects/mssql/query-generator.js#L860

The [proposed fix](https://stackoverflow.com/a/48050217/1483977) seems like it could create two ORDER BY statements, which isn't quite a solution.

--- Context ---

Hi there, I'm just starting to use Tedious through the feathers-sequelize package.  

I'm getting an [error that seems related to SQL Server versions](https://stackoverflow.com/questions/30632779/tedious-or-sequelize-uses-the-wrong-syntax-for-findone/54837260#54837260).

SQL Server is a new animal for me.  Anything obvious I'm missing?  

Thank you!

I'm working with this version of mssql:
```
Microsoft SQL Server 2014 - 12.0.2000.8 (X64) 
	Feb 20 2014 20:04:26 
	Copyright (c) Microsoft Corporation
	Express Edition (64-bit) on Windows NT 6.3 <X64> (Build 17134: ) 
```

It looks like the app starts and talks with the database.  When I use a bad password, I get an appropriate error.  Here's a good startup.  I'm connecting to an existing database schema, so these create tables shouldn't have an effect:
```
[nodemon] 1.18.10
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node src/`
info: Feathers application started on http://localhost:3030
Executing (default): IF OBJECT_ID('[MattInf]', 'U') IS NULL CREATE TABLE [MattInf] ([MatterID] BIGINT NOT NULL , [ClientInfoClientID] BIGINT NULL, [MatterInfoRespLwyr] BIGINT NULL, [MatterInfoDefRateAmt] FLOAT NULL, [MatterInfoFileDesc] NVARCHAR(900) NULL, [MatterInfoMatterNum] NVARCHAR(25) NULL, [MatterInfoOpenDate] BIGINT NULL, [MatterInfoSortName] NVARCHAR(70) NULL, [createdAt] DATETIMEOFFSET NOT NULL, [updatedAt] DATETIMEOFFSET NOT NULL, PRIMARY KEY ([MatterID]));
Executing (default): EXEC sys.sp_helpindex @objname = N'[MattInf]';
Executing (default): IF OBJECT_ID('[ClntInfV5]', 'U') IS NULL CREATE TABLE [ClntInfV5] ([ClientInfoClientID] BIGINT NOT NULL , [ClientInfoSortName] NVARCHAR(40) NULL, [createdAt] DATETIMEOFFSET NOT NULL, [updatedAt] DATETIMEOFFSET NOT NULL, PRIMARY KEY ([ClientInfoClientID]));
Executing (default): EXEC sys.sp_helpindex @objname = N'[ClntInfV5]';
Executing (default): IF OBJECT_ID('[LawInf]', 'U') IS NULL CREATE TABLE [LawInf] ([LawyerID] BIGINT NOT NULL , [LawInfDeptID] BIGINT NULL, [LawInfInitials] NVARCHAR(10) NULL, [LawInfLawyerName] NVARCHAR(3000) NULL, [LawInfNickName] NVARCHAR(20) NULL, [createdAt] DATETIMEOFFSET NOT NULL, [updatedAt] DATETIMEOFFSET NOT NULL, PRIMARY KEY ([LawyerID]));
Executing (default): EXEC sys.sp_helpindex @objname = N'[LawInf]';
```
Here's the connection code:

```
const url = require('url');
const Sequelize = require('sequelize');

module.exports = function (app) {
  const connectionString = app.get('mssql');
  const connection = url.parse(connectionString);
  const database = connection.path.substring(1, connection.path.length);
  const { port, hostname } = connection;
  const [ username, password ] = (connection.auth || ':').split(':');
  const sequelize = new Sequelize(database, username, password, {
    dialect: 'mssql',
    host: hostname,
    logging: app.get('debug_mssql') ? console.log : false,  // customized logging
    operatorsAliases: false,
    define: {
      freezeTableName: true
    },
    dialectOptions: {
      port: parseInt(port),           // added parseInt()
      encrypt: false,
      //instanceName: 'wont_work_with_port'
    }
  });
```

Here is the model I'm using w/ sequelize:
```
// See http://docs.sequelizejs.com/en/latest/docs/models-definition/
// for more of what you can do here.
const Sequelize = require('sequelize');
const DataTypes = Sequelize.DataTypes;

module.exports = function (app) {
  const sequelizeClient = app.get('sequelizeClient');
  const Lawyers = sequelizeClient.define('Lawyers', {
    // Primary Key
    LawyerID: {
      type: DataTypes.BIGINT,
      primaryKey: true,
      allowNull: false
    },
    // Foreign Keys
    // Fields
    LawInfDeptID: {
      type: DataTypes.BIGINT,
      allowNull: true,
    },
    LawInfInitials: {
      type: DataTypes.STRING(10),
      allowNull: true,
    },
    LawInfLawyerName: {
      type: DataTypes.STRING(3000),
      allowNull: true,
    },
    LawInfNickName: {
      type: DataTypes.STRING(20),
      allowNull: true,
    },
  }, {
    tableName: 'LawInf',
    hooks: {
      beforeCount(options) {
        options.raw = true;
      },
    },
  });

  // eslint-disable-next-line no-unused-vars
  Lawyers.associate = function (models) {
    // Define associations here
    // See http://docs.sequelizejs.com/en/latest/docs/associations/
  };

  return Lawyers;
};

```
When I try to access a LawInf, I get this error:

```
Executing (default): SELECT count(DISTINCT([Lawyers].[LawyerID])) AS [count] FROM [LawInf] AS [Lawyers];
Executing (default): SELECT [LawyerID], [LawInfDeptID], [LawInfInitials], [LawInfLawyerName], [LawInfNickName], [createdAt], [updatedAt] FROM [LawInf] AS [Lawyers] OFFSET 0 ROWS FETCH NEXT 10 ROWS ONLY;
error: NotFound: Invalid usage of the option NEXT in the FETCH statement.
    at new NotFound (/home/michael/scm/project/app/sync/node_modules/@feathersjs/errors/lib/index.js:114:17)
    at exports.errorHandler.error (/home/michael/scm/project/app/sync/node_modules/feathers-sequelize/lib/utils.js:28:20)
    at tryCatcher (/home/michael/scm/project/app/sync/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/michael/scm/project/app/sync/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/michael/scm/project/app/sync/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/michael/scm/project/app/sync/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/michael/scm/project/app/sync/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/home/michael/scm/project/app/sync/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/michael/scm/project/app/sync/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/michael/scm/project/app/sync/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/home/michael/scm/project/app/sync/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

**Comment by MichaelJCole** [comment]
The default pagination is set somewhere to: `{ default: 10, max: 50 }`

A workaround for this bug is to `app.set('paginate', false)`

```
// sequelize.js
const url = require('url');
const Sequelize = require('sequelize');

module.exports = function (app) {
  const connectionString = app.get('mssql');
  ...
  const sequelize = new Sequelize(database, username, password, {
    dialect: 'mssql',
    host: hostname,
    logging: app.get('debug_mssql') ? console.log : false,  // eslint-disable-line
    operatorsAliases: false,
    define: {
      freezeTableName: true
    },
    dialectOptions: {
      port: parseInt(port),
      encrypt: false,
    }
  });
  const oldSetup = app.setup;

  app.set('sequelizeClient', sequelize);
  app.set('paginate', false);     // <-  This clears the default pagination as a workaround.

 ...
```

**Comment by di1eep** [comment]
I have the same issue and i'm working on mssql dialect to resolve this. hope to submit a PR soon.

**Comment by donvie** [comment]
https://github.com/realdubb/sequelize/commit/0c4674013486be36e96e1c310a91aaa95bd931de
this will fixed all your problem

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/sequelize/pull/12261
