### ISSUE TITLE
MS SQL Insert with "returning: false" causes "Cannot read property 'id' of undefined" error

### ISSUE THREAD

**Issue by groboclown** [sequelize/sequelize#10541]
## What are you doing?

With the MS SQL dialect, I'm running a simple model create but without returning values.  It does not have an autoincrement primary key, but instead the code generates a custom primary key.

```js
MyModel.create({ value: 'myvalue', myCustomPk: 'customPk'}, {
  isNewRecord: true,
  returning: false
});
```

## What do you expect to happen?

This should perform the insert and return a promise without any records.

## What is actually happening?

Instead, it fails with an exception:

```
project/node_modules/sequelize/lib/dialects/mssql/query.js:378                                                                                                           
      id = id || results && results[0][this.getInsertIdField()];
                                      ^

TypeError: Cannot read property 'id' of undefined
    at Query.handleInsertQuery (project/node_modules/sequelize/lib/dialects/mssql/query.js:378:39)                                                                       
    at Query.formatResults (project/node_modules/sequelize/lib/dialects/mssql/query.js:179:12)                                                                           
    at Request.connection.lib.Request [as userCallback] (project/node_modules/sequelize/lib/dialects/mssql/query.js:109:26)                                              
    at Request.callback (project/node_modules/tedious/lib/request.js:37:27)                                                                                              
    at Connection.endOfMessageMarkerReceived (project/node_modules/tedious/lib/connection.js:2118:20)                                                                    
```

If I change the `returning: false` to `returning: true` the error does not occur.

Note that I'm using the sequelize-typescript library to wrap the model and create invocation, but the underlying error happens within the sequelize library itself.

__Dialect:__ mssql
__Dialect version:__ tedious 5.0.3
__Database version:__ MS SQL Server 12.0.5605.1
__Sequelize version:__ 4.43.0
__Tested with latest release:__ Yes

**Comment by groboclown** [comment]
This issue looks related to #9823, but in my case I don't have any db triggers.  Additionally, the generated SQL reported by logging runs without issue from the database.

**Comment by groboclown** [comment]
After upgrading to version 5.1.0, and transitioned to using native sequelize typescript support, I'm still seeing this issue:

```typescript
MyModel.create(values, { returning: false, isNewRecord: true })
```

In order to get past this issue, I switched to an explicit build then save:

```typescript
MyModel
  .build(values, { isNewRecord: true })
  .save()
```

**Comment by gabegorelick** [comment]
Possible duplicate of #10633.

**Comment by Mustachipleb** [comment]
https://github.com/sequelize/sequelize/issues/10633 is closed as being fixed in v7. I'm not going to try to migrate to v7 from v6 after just going to v6 from v5. This is behaviour which limits us to only being able to replace the offending function call with a raw query.
Will this be fixed in v6?
