### ISSUE TITLE
Executing .findOrCreate with WHERE clause containing created_at cause "invalid date"

### ISSUE THREAD

**Issue by luckyguido** [sequelize/sequelize#10545]
## What are you doing?

Executing .findOrCreate with WHERE clause containing created_at cause "invalid date"
```js
        db.piece.findOrCreate({
            where: {
                serial: (123456).toString(),
                created_at: { [Op.gte]: moment().subtract(1, 'days').toDate() } 
            },
            defaults: {
                serial: 123456,
                model: 1,
                status: 1,
                scrap_description: 0,
                data: { tagTest: true }
            }
        }).spread(function (delivered, created) {
           /* ... */
        });
```

## What do you expect to happen?
Executing findOrCreate correctly

## What is actually happening?
Exception thrown:
    Unhandled rejection SequelizeDatabaseError: sintassi di input non valida per il tipo timestamp with time zone: "Invalid date"
        at Query.formatError (.\node_modules\sequelize\lib\dialects\postgres\query.js:363:16)
        at query.catch.err (.\node_modules\sequelize\lib\dialects\postgres\query.js:86:18)
        at tryCatcher (.\node_modules\bluebird\js\release\util.js:16:23)
        at Promise.module.exports.Promise._settlePromiseFromHandler (.\node_modules\bluebird\js\release\promise.js:512:31)
        at Promise.module.exports.Promise._settlePromise (.\node_modules\bluebird\js\release\promise.js:569:18)
        at Promise.module.exports.Promise._settlePromise0 (.\node_modules\bluebird\js\release\promise.js:614:10)
        at Promise.module.exports.Promise._settlePromises (.\node_modules\bluebird\js\release\promise.js:690:18)
        at _drainQueueStep (.\node_modules\bluebird\js\release\async.js:138:12)
        at _drainQueue (.\node_modules\bluebird\js\release\async.js:131:9)
        at Async._drainQueues (.\node_modules\bluebird\js\release\async.js:147:5)
        at Immediate.e.Async.drainQueues (.\node_modules\bluebird\js\release\async.js:17:14)
        at runCallback (timers.js:649:20)
        at tryOnImmediate (timers.js:622:5)
        at processImmediate [as _immediateCallback] (timers.js:594:5)

## Additional notes
Same query done using **updated_at** instead of **created_at** field work correctly.

__Dialect: postgres
__Dialect version: ???
__Database version: 9.6
__Sequelize version: 4.43.0
__Tested with latest release: yes

**Comment by LeeMartin77** [comment]
We have also had the same problem this morning, following a migration from MySQL
