### ISSUE TITLE
Views in database cause Sequelize.import to crash

### ISSUE THREAD

**Issue by joaoe** [sequelize/sequelize#10546]
## What are you doing?

My database has some views. `SequelizeAuto` generates modules for the views as if they were tables. Then `Sequelize.import` crashes because the view does not have a primary key over the `Id` column.

```js
const Sequelize = require('sequelize')
const SequelizeAuto = require('sequelize-auto')
const path = require('path')
const fs = require('fs')
const glob = require('glob-promise')


globals = {
  host: "localhost",
  databaseName: "testcase",
  login: "USERNAME",
  password: "PASSWORD",

  dialect: "...",
  port: 12345,

  createSchema: "CREATE VIEW aaa AS SELECT 1 id, 'a' name;",
  clearSchema: "DROP VIEW aaa;",

  modelsFolder: path.join(__dirname, 'testcasemodels'),
  jsGlob: path.join(__dirname, 'testcasemodels/*.js')

}

console.log(`Connecting to ${globals.databaseName}:${globals.login}:${globals.password}`)

var db = new Sequelize(
  globals.databaseName, globals.login, globals.password, {
    host: globals.host,
    port: globals.port,
    dialect: globals.dialect,
  });

//db.query(globals.clearSchema).catch(function(err){});
db.query(globals.createSchema).
  then(function() {
      fs.unlinkSync(globals.aaaModelJs);
      return new Promise(function(resolve, reject) {
        console.log(`Generating schema from ${globals.databaseName}:${globals.login}:${globals.password}`)
        var auto = new SequelizeAuto(globals.databaseName, globals.login, globals.password, {
          host: globals.host,
          port: globals.port,
          dialect: globals.dialect,
          encrypt: false,

          directory: globals.modelsFolder,
          camelCase: true,
          indentation: 2,
          spaces: true
        })

        auto.run(function(err) {
          if (err) reject(err)
          resolve(auto)
        });
      });
    }).
  then(function(auto) {
      // CRASHES HERE!
      db.import(globals.aaaModelJs)
      return finishAndCleanup();
    }).
  catch(finishAndCleanup);

function finishAndCleanup(err){
  if (err) {
    console.log(err);
  }
  console.log('Cleaning up')
  return db.query(globals.clearSchema).then(callExit, callExit);
}

function callExit() {
  process.exit()
}
```

## What do you expect to happen?
One of:
a) the view should perhaps not generate a model, since views are used to help reuse repetitive SQL.
b) if a model is generated, the model file should perhaps tell that it is a view and not a table. Sequelize then would have a read-only API (no insert, update or delete in the model, unless the view as insert/update/delete triggers) and would ignore the lack of keys

This is how the model looks like
```js
/* jshint indent: 2 */

module.exports = function(sequelize, DataTypes) {
  return sequelize.define('aaa', {
    id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      field: 'id'
    },
    name: {
      type: DataTypes.STRING,
      allowNull: false,
      field: 'name'
    }
  }, {
    tableName: 'aaa'
  });
};
```

## What is actually happening?
Crash!
```
Error: A column called 'id' was added to the attributes of 'aaa' but not marked with 'primaryKey: true'
    at Function._addDefaultAttributes (node_modules\sequelize\lib\model.js:111:15)
    at Function.init (node_modules\sequelize\lib\model.js:841:10)
    at Sequelize.define (node_modules\sequelize\lib\sequelize.js:344:11)
    at module.exports (scripts\testcasemodels\aaa.js:4:20)
    at Sequelize.import (node_modules\sequelize\lib\sequelize.js:400:32)
    at scripts\testcase.js:58:53
```
__Dialect:__ mssql
__Dialect version:__ XXX
__Database version:__ 14
__Sequelize version:__ 4.43.0
__Tested with latest release:__ Yes

**Comment by sushantdhiman** [comment]
Views are not supported

**Comment by joaoe** [comment]
If VIEWS are not supported, then `SequelizeAuto` should ignore them.

**Comment by sushantdhiman** [comment]
You can open a PR or issue to sequelize-auto for that
