### ISSUE TITLE
SequelizeUniqueConstraintError: custom error message doesn't work

### ISSUE THREAD

**Issue by bullsei** [sequelize/sequelize#10559]
## What are you doing?
I am trying to get a custom error message when i am trying to create the same value twice in my table. 

I just create a simple database with psql: **create database test**
this is a minimum example which lets me reproduce this:

```
const Sequelize = require("sequelize");
const sequelize = new Sequelize("postgres://postgres:postgres@localhost:5432/test", {
	dialect: "postgres",
	protocol: "postgres",
	dialectOptions: {
		ssl: true
	}
});

sequelize.define("user", {
	username: {
		type: Sequelize.STRING,
		unique: {
			args: true,
			msg: "Username already taken"
		},
		allowNull: false
	},
});

const createUsers = async () => {
	try {
		await sequelize.models.user.create({ username: "testuser" });
		await sequelize.models.user.create({ username: "testuser" });
	} catch (error) {
		console.log(error);
	}
};

sequelize.sync({ force: true }).then(createUsers);

```

## What do you expect to happen?
I expect my custom error message "Username already taken" to show up.

## What is actually happening?
i get this: SequelizeUniqueConstraintError: doppelter Schlüsselwert verletzt Unique-Constraint »users_username_key«

the weird thing about this is when i connect to my heroku database instead my custom error message shows up. So i wonder if i did something wrong with my local database or if this is an actual bug.

__Dialect:__ postgres
__Dialect version:__ not sure
__Database version:__  PostgreSQL 10.7 (Ubuntu 10.7-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0, 64-bit

__Sequelize version:__ 5.1.0
__Tested with latest release:__ last version thats available via "npm install sequelize"

**Comment by bullsei** [comment]
I looked a bit more into this and i found out that the custom error message is working when i set **lc_messages** to **en_US.UTF-8** in my **postgresql.conf** file. So this is a locale problem. Is this fixable in any way other than hardcoding all the locale dependend error messages into the code?

**Comment by SimonSchick** [comment]
Sequelize extracts field names etc. from the error messages, iirc there is no way to extract them otherwise.

**Comment by sushantdhiman** [comment]
Yes we parse messages with regex and extract fields name from that, can you show full error which include original error property as well? Postgres provide error code so it should be possible to handle other locale as well

**Comment by bullsei** [comment]
Thanks for the reply. Here is the complete error object:
``````
{ SequelizeUniqueConstraintError: doppelter Schlüsselwert verletzt Unique-Constraint »users_username_key«
    at Query.formatError (/home/whatever/NodeApps/MyStuff/sequelize-test/node_modules/sequelize/lib/dialects/postgres/query.js:327:16)
    at query.catch.err (/home/whatever/NodeApps/MyStuff/sequelize-test/node_modules/sequelize/lib/dialects/postgres/query.js:76:18)
    at tryCatcher (/home/whatever/NodeApps/MyStuff/sequelize-test/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/whatever/NodeApps/MyStuff/sequelize-test/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/whatever/NodeApps/MyStuff/sequelize-test/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/whatever/NodeApps/MyStuff/sequelize-test/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/whatever/NodeApps/MyStuff/sequelize-test/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/home/whatever/NodeApps/MyStuff/sequelize-test/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/whatever/NodeApps/MyStuff/sequelize-test/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/whatever/NodeApps/MyStuff/sequelize-test/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/whatever/NodeApps/MyStuff/sequelize-test/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (timers.js:637:19)
  name: 'SequelizeUniqueConstraintError',
  errors: {},
  fields: undefined,
  parent:
   { error: doppelter Schlüsselwert verletzt Unique-Constraint »users_username_key«
       at Connection.parseE (/home/whatever/NodeApps/MyStuff/sequelize-test/node_modules/pg/lib/connection.js:555:11)
       at Connection.parseMessage (/home/whatever/NodeApps/MyStuff/sequelize-test/node_modules/pg/lib/connection.js:380:19)
       at TLSSocket.<anonymous> (/home/whatever/NodeApps/MyStuff/sequelize-test/node_modules/pg/lib/connection.js:120:22)
       at TLSSocket.emit (events.js:197:13)
       at addChunk (_stream_readable.js:288:12)
       at readableAddChunk (_stream_readable.js:269:11)
       at TLSSocket.Readable.push (_stream_readable.js:224:10)
       at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)
     name: 'error',
     length: 231,
     severity: 'FEHLER',
     code: '23505',
     detail: 'Schlüssel »(username)=(testuser)« existiert bereits.',
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: 'public',
     table: 'users',
     column: undefined,
     dataType: undefined,
     constraint: 'users_username_key',
     file: 'nbtinsert.c',
     line: '434',
     routine: '_bt_check_unique',
     sql:
      'INSERT INTO "users" ("id","username","email","createdAt","updatedAt") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING *;' },
  original:
   { error: doppelter Schlüsselwert verletzt Unique-Constraint »users_username_key«
       at Connection.parseE (/home/whatever/NodeApps/MyStuff/sequelize-test/node_modules/pg/lib/connection.js:555:11)
       at Connection.parseMessage (/home/whatever/NodeApps/MyStuff/sequelize-test/node_modules/pg/lib/connection.js:380:19)
       at TLSSocket.<anonymous> (/home/whatever/NodeApps/MyStuff/sequelize-test/node_modules/pg/lib/connection.js:120:22)
       at TLSSocket.emit (events.js:197:13)
       at addChunk (_stream_readable.js:288:12)
       at readableAddChunk (_stream_readable.js:269:11)
       at TLSSocket.Readable.push (_stream_readable.js:224:10)
       at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)
     name: 'error',
     length: 231,
     severity: 'FEHLER',
     code: '23505',
     detail: 'Schlüssel »(username)=(testuser)« existiert bereits.',
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: 'public',
     table: 'users',
     column: undefined,
     dataType: undefined,
     constraint: 'users_username_key',
     file: 'nbtinsert.c',
     line: '434',
     routine: '_bt_check_unique',
     sql:
      'INSERT INTO "users" ("id","username","email","createdAt","updatedAt") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING *;' },
  sql:
   'INSERT INTO "users" ("id","username","email","createdAt","updatedAt") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING *;' }
``````

**Comment by SimonSchick** [comment]
@bullsei did you manually add the `>>` and `<<` or is that the locale doing it?
In any case, I _think_ we can relax the regex match from `/Key \((.*?)\)=\((.*?)\)/` to `(/((.*?)\)=\((.*?)\)/`, as this seems to be consistent.
@sushantdhiman thoughts?

**Comment by bullsei** [comment]
I didn't add this manually, but I just checked again just to make sure. It really exists in the detail property.
