### ISSUE TITLE
Double mapping in model.js causes updates to fail by using a non-primary key

### ISSUE THREAD

**Issue by dinamic** [sequelize/sequelize#10589]
## What are you doing?

```js
const User = sequelize.define(
  "User",
  {
    userId: {
      field: "id",
      type: Sequelize.INTEGER,
      primaryKey: true,
      autoIncrement: true,
      allowNull: true
    },
    id: {
      field: "uuid",
      type: Sequelize.UUIDV4,
      allowNull: false
    },
    emailAddress: {
      field: 'email',
      type: Sequelize.STRING,
      allowNull: false
    },
    ...

const user = User.findByPk(8);
user.update({emailAddress: 'nikola.petkanski7@jiminny.com'});
```

## What do you expect to happen?
_user.update() and user.save() to work_

## What is actually happening?

```
Unhandled rejection SequelizeDatabaseError: (conn=2517, no: 1292, SQLState: 22007) Truncated incorrect DOUBLE value: 'N\xEF\xBF\xBDI\xEF\xBF\xBD\xEF\xBF\xBD\xEF\xBF\xBD3='
sql: UPDATE `users` SET `email`=?,`updated_at`=? WHERE `uuid` = ? - parameters:['nikola.petkanski7@jiminny.com','2019-03-21 13:04:46.587',8]
    at Query.formatError (/Users/nikola/Projects/Jiminny/stack/node_modules/sequelize/lib/dialects/mariadb/query.js:306:16)
    at connection.query.then.catch.err (/Users/nikola/Projects/Jiminny/stack/node_modules/sequelize/lib/dialects/mariadb/query.js:89:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

__Dialect:__ any
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ XXX
__Tested with latest release:__ Yes (5.1.0)

**Comment by dinamic** [comment]
As per my debugging tools show, here's where the issue comes from:

[model.js:3789](https://github.com/sequelize/sequelize/blob/master/lib/model.js#L3789) constructs the where clause and uses database field names to do so. In my instance, it maps `userId = 8` to `id = 8`.
 [model.js:3790](https://github.com/sequelize/sequelize/blob/master/lib/model.js#L3790) comes around and looking at the model fields, maps `id` to `uuid`.

This is a bug, but I'm not deeply familiar with the internals and am scared not to break anything if I touch any of these functions.

**Comment by dinamic** [comment]
@sushantdhiman I would appreciate your thoughts on this.
