### ISSUE TITLE
Associations with migrations, getters are not a function

### ISSUE THREAD

**Issue by gnorbsl** [sequelize/sequelize#10621]
## What are you doing?

If have two objects with a 1:many association, I'm defining the models as followed

```js
'use strict';
module.exports = (sequelize, DataTypes) => {
  const Locations = sequelize.define('Locations', {
    owner: DataTypes.INTEGER,
    latitude: DataTypes.DOUBLE,
    longitude: DataTypes.DOUBLE
  }, {});

  Locations.associate = function(models) {
    // associations can be defined here
    Locations.hasMany(models.LocationOpeningHours, {
      as: 'locationOpeningHours',
      foreignKey: 'locationId',
      sourceKey: 'id',
    })
  };
  return Locations;
};

```

```js
'use strict';
module.exports = (sequelize, DataTypes) => {
  const LocationOpeningHours = sequelize.define('LocationOpeningHours', {
    locationId: DataTypes.INTEGER,
    weekday: DataTypes.TINYINT,
    hours: DataTypes.STRING
  }, {});
  LocationOpeningHours.associate = function(models) {
    // associations can be defined here
    LocationOpeningHours.belongsTo(models.Locations,
        {
          as: 'locations',
          foreignKey: 'id',
          sourceKey: 'locationId',
        })
  };
  return LocationOpeningHours;
};

```

## What do you expect to happen?

```js
 locations.findOne({where: {id: locationId}})
            .then(location => {
                   location.getLocationOpeningHours()
}
```

I expect to see the locationOpeningHours for this location

## What is actually happening?

I get the error:

```
TypeError: location.getLocationOpeningHours is not a function
    at locations.findOne.then.location (/home/patric/WebstormProjects/beercoin-backend-nodejs/db/models/locationsmodel.js:765:26)
    at tryCatcher (/home/patric/WebstormProjects/beercoin-backend-nodejs/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/patric/WebstormProjects/beercoin-backend-nodejs/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/patric/WebstormProjects/beercoin-backend-nodejs/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/patric/WebstormProjects/beercoin-backend-nodejs/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/patric/WebstormProjects/beercoin-backend-nodejs/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/home/patric/WebstormProjects/beercoin-backend-nodejs/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/patric/WebstormProjects/beercoin-backend-nodejs/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/patric/WebstormProjects/beercoin-backend-nodejs/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/home/patric/WebstormProjects/beercoin-backend-nodejs/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

```

__Dialect:__ mysql
__Sequelize version:__ 5.1.1
__Tested with latest release: yes

**Comment by SimonSchick** [comment]
Please post a single executable repro please.
Have you inspected the prototype to see if association functions were created?
Code looks sane but I suspect you aren't calling `associate`.

**Comment by gnorbsl** [comment]
@SimonSchick that was the issue... Thank you very much I was sitting at this stuff for way too long.
