### ISSUE TITLE
(v5) Unable to query on Model in typescript

### ISSUE THREAD

**Issue by pasupulaphani** [sequelize/sequelize#10620]
## What are you doing?
Unable to query on Model in typescript

Ex: http://docs.sequelizejs.com/manual/typescript.html

```js
class Product extends Model {
  public id!: number;
  public name!: string;
  public lessonId!: number;
}

Product.init(
  {
    name: {
      unique: true,
      allowNull: false,
      type: DataTypes.STRING
    },
    lessonId: {
      allowNull: false,
      field: "lesson_id",
      type: DataTypes.INTEGER
    }
  },
  {
    sequelize,
    tableName: "products"
  }
);

Product.findByPk(1).then(res => console.log(res));
```

## What do you expect to happen?
Return row info

## What is actually happening?
Errors with "Model cannot be invoked without 'new'" error

```
api_1       | Executing (default): SELECT "id", "name", "lesson_id" AS "lessonId", "created_at" AS "createdAt", "updated_at" AS "updatedAt" FROM "products" AS "Product" WHERE "Product"."id" = 1;
api_1       | Unhandled rejection TypeError: Class constructor Model cannot be invoked without 'new'
api_1       |     at new Product (/opt/api/src/models/index.ts:48:42)
api_1       |     at Function.build (/opt/api/node_modules/sequelize/lib/model.js:2143:12)
api_1       |     at valueSets.map.values (/opt/api/node_modules/sequelize/lib/model.js:2163:41)
api_1       |     at Array.map (<anonymous>)
api_1       |     at Function.bulkBuild (/opt/api/node_modules/sequelize/lib/model.js:2163:22)
api_1       |     at Query.handleSelectQuery (/opt/api/node_modules/sequelize/lib/dialects/abstract/query.js:296:27)
api_1       |     at query.catch.then.then.queryResult (/opt/api/node_modules/sequelize/lib/dialects/postgres/query.js:196:23)
api_1       | From previous event:
api_1       |     at Query.run (/opt/api/node_modules/sequelize/lib/dialects/postgres/query.js:87:8)
api_1       |     at Promise.try.then.connection (/opt/api/node_modules/sequelize/lib/sequelize.js:574:22)
api_1       | From previous event:
api_1       |     at Promise.resolve.retryParameters (/opt/api/node_modules/sequelize/lib/sequelize.js:571:10)
api_1       |     at /opt/api/node_modules/retry-as-promised/index.js:70:21
api_1       |     at new Promise (<anonymous>)
api_1       |     at retryAsPromised (/opt/api/node_modules/retry-as-promised/index.js:60:10)
api_1       |     at Promise.try (/opt/api/node_modules/sequelize/lib/sequelize.js:551:30)
api_1       | From previous event:
api_1       |     at Sequelize.query (/opt/api/node_modules/sequelize/lib/sequelize.js:508:23)
api_1       |     at QueryInterface.select (/opt/api/node_modules/sequelize/lib/query-interface.js:1115:27)
api_1       |     at Promise.try.then.then.then (/opt/api/node_modules/sequelize/lib/model.js:1747:34)
api_1       |     at runCallback (timers.js:705:18)
api_1       |     at tryOnImmediate (timers.js:676:5)
api_1       |     at processImmediate (timers.js:658:5)
api_1       |     at process.topLevelDomainCallback (domain.js:120:23)
```

__Dialect:__ / postgres
__Database version:__ 10
__Sequelize version:__ 5.1.1
__Tested with latest release:__ Yes

**Comment by pasupulaphani** [comment]
This is happening when  ```await sequelize.sync();``` is not used.

**Comment by SimonSchick** [comment]
If you are not giving us the full code, we can't help you, your stack trace refers to a line `48`, your code sample doesn't include that.

**Comment by pasupulaphani** [comment]
I finally found the issue. It is to do with the target TS compilation in my project.

**Comment by SET001** [comment]
@pasupulaphani how exactly you solved this? I'm experiencing here the same issue.

**Comment by pasupulaphani** [comment]
@SET001 check for compilerOptions.target. I'm now using "es2018".
