### ISSUE TITLE
Underscored option doesn't work

### ISSUE THREAD

**Issue by valyefimov** [sequelize/sequelize#1063]
I use underscore style for created_at, updated_at and deleted_at columns. In config  I've defined "underscored: true" option but when I'm trying to find data, pg module throws an exeception:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
error: column "deletedAt" doesn't exists
    at Connection.parseE (/home/val/www/fastintop_trunk/fastintop/node_modules/pg/lib/connection.js:526:11)
    at Connection.parseMessage (/home/val/www/fastintop_trunk/fastintop/node_modules/pg/lib/connection.js:371:17)
    at Socket.<anonymous> (/home/val/www/fastintop_trunk/fastintop/node_modules/pg/lib/connection.js:86:20)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:526:21)
```

Sequelize MUST use deleted_at column instead of deletedAt.
Here's a list of the modules and their versions
- NodeJs: 0.10.20
- sequelize: ~2.0.0-beta.1
- pg: ~2.3.1

**Comment by mericsson** [comment]
+1 Is there a way to inform sequelize mode:create to use underscored/snake_case when creating updatedAt and createdAt columns?

**Comment by mickhansen** [comment]
@mericsson `model:create` is the CLI, not the core library, open an issue for the CLI at the CLI codebase if you're having issues with it.
