### ISSUE TITLE
alias inside of where statement results in table.alias

### ISSUE THREAD

**Issue by IamFlowZ** [sequelize/sequelize#10748]
## What are you doing?

```js
table.findAll({
attributes: cols,
where: {
  $or: [
    {
      title: {
        $like: 'Boat%'
      }
    },
    {
      description: {
        $like: '%boat%'
      }
    }
  ]
}
```

## What do you expect to happen?
I'm expecting the resulting sql to look like 'table.title LIKE "%" OR table.description LIKE "%"'

## What is actually happening?
After some tinkering, it looks like the sql that is being compiled is table.$or IN (_objects specified in or array_).

_Output, either JSON or SQL_
name: 'SequelizeDatabaseError',
  parent:
   { Error: Unknown column 'resource.$or' in 'where clause'
       at Packet.asError (/home/ec2-user/environment/api/node_modules/mysql2/lib/packets/packet.js:684:17)
       at Query.execute (/home/ec2-user/environment/api/node_modules/mysql2/lib/commands/command.js:28:26)
       at Connection.handlePacket (/home/ec2-user/environment/api/node_modules/mysql2/lib/connection.js:449:32)
       at PacketParser.Connection.packetParser.p [as onPacket] (/home/ec2-user/environment/api/node_modules/mysql2/lib/connection.js:72:12)
       at PacketParser.executeStart (/home/ec2-user/environment/api/node_modules/mysql2/lib/packet_parser.js:75:16)
       at Socket.Connection.stream.on.data (/home/ec2-user/environment/api/node_modules/mysql2/lib/connection.js:79:25)
       at Socket.emit (events.js:193:13)
       at addChunk (_stream_readable.js:296:12)
       at readableAddChunk (_stream_readable.js:277:11)
       at Socket.Readable.push (_stream_readable.js:232:10)
       at TCP.onStreamRead (internal/stream_base_commons.js:150:17)
     code: 'ER_BAD_FIELD_ERROR',
     errno: 1054,
     sqlState: '42S22',
     sqlMessage: "Unknown column 'resource.$or' in 'where clause'",
     sql:
      'SELECT `type`, `url`, `description`, `title` FROM `resources` AS `resource` WHERE `resource`.`$or` IN (NULL);' },
  original:
   { Error: Unknown column 'resource.$and' in 'where clause'
       at Packet.asError (/home/ec2-user/environment/api/node_modules/mysql2/lib/packets/packet.js:684:17)
       at Query.execute (/home/ec2-user/environment/api/node_modules/mysql2/lib/commands/command.js:28:26)
       at Connection.handlePacket (/home/ec2-user/environment/api/node_modules/mysql2/lib/connection.js:449:32)
       at PacketParser.Connection.packetParser.p [as onPacket] (/home/ec2-user/environment/api/node_modules/mysql2/lib/connection.js:72:12)
       at PacketParser.executeStart (/home/ec2-user/environment/api/node_modules/mysql2/lib/packet_parser.js:75:16)
       at Socket.Connection.stream.on.data (/home/ec2-user/environment/api/node_modules/mysql2/lib/connection.js:79:25)
       at Socket.emit (events.js:193:13)
       at addChunk (_stream_readable.js:296:12)
       at readableAddChunk (_stream_readable.js:277:11)
       at Socket.Readable.push (_stream_readable.js:232:10)
       at TCP.onStreamRead (internal/stream_base_commons.js:150:17)
     code: 'ER_BAD_FIELD_ERROR',
     errno: 1054,
     sqlState: '42S22',
     sqlMessage: "Unknown column 'resource.$or' in 'where clause'",
     sql:
      'SELECT `type`, `url`, `description`, `title` FROM `resources` AS `resource` WHERE `resource`.`$and` IN (NULL);' },
  sql:
   'SELECT `type`, `url`, `description`, `title` FROM `resources` AS `resource` WHERE `resource`.`$or` IN (NULL);' }

__Dialect:__ mysql2 
__Dialect version:__ 1.6.5
__Database version:__ 5.5.62
__Sequelize version:__ 5.3.0
__Tested with latest release:__ Yes 5.3.0

**Note :** I would also like to add, __this__ does work correctly. So it's probably an issue with the aliasing.

```js
    where: {
          [Op.or]: [
            {
              title: {
                [Op.like]: 'Boat%'
              }
            },
            {
              description: {
                [Op.like]: '%boat%'
              }
            }
          ]
        }
```

**Comment by SimonSchick** [comment]
Aliasing is explicitly opt-in now, please post a full repro if you believe this is an error.
I'd strongly suggest moving to symbols by the way.

**Comment by IamFlowZ** [comment]
That's what I ended up doing. The largest reason for me posting the issue, is the documentation makes no mention of the fact that $__ is an alias for the given operation and is fairly misleading.

**Comment by papb** [comment]
> That's what I ended up doing. The largest reason for me posting the issue, is the documentation makes no mention of the fact that $__ is an alias for the given operation and is fairly misleading.

Can you expand on this, please?

**Comment by Petrichor-Dev** [comment]
I'm using sequelize version 6.25.3 and found the same issue. This is what i do.
Hopefully can help

`where:{
              [Op.or]: {
                [Op.or]: [
                  {
                    title: {
                      [Op.like]: 'boat%'
                    }
                  },
                  {
                    description: {
                      [Op.like]: '%boat%'
                    }
                  }
                ]
              }
            }`
//WHERE ((title LIKE 'boat%' OR description LIKE '%boat%))
