### ISSUE TITLE
sequelize with tedious lts

### ISSUE THREAD

**Issue by Royalsspirit** [sequelize/sequelize#10759]
## What are you doing?

I tried to connect to mssql database with driver tedious
```js
const Sequelize = require('sequelize');

const MSSQL_HOST = process.env.mssqlHost || '127.0.0.1';
const MSSQL_USER = process.env.mssqlUser || 'root';
const MSSQL_PWD = process.env.mssqlPwd || 'root';
const MSSQL_DBNAME = process.env.mssqlDbname || 'DB';


const sequelize = new Sequelize(MSSQL_DBNAME, MSSQL_USER, MSSQL_PWD, {
  dialect: 'mssql',
  host: MSSQL_HOST,
  logging: false, // disable logging; default: console.log
  dialectOptions: {
    authenticate: {
      userName: MSSQL_USER,
      password: MSSQL_PWD,
    },
    encrypt: true,
  },
});

sequelize
  .authenticate()
  .then(() => {
    console.log('Connection has been established successfully to the mssql database.');
  })
  .catch((err) => {
    console.error('Unable to connect to the mssql database:', err);
  });


```

## What do you expect to happen?
_I wanted Foo!_
`Connection has been established successfully to the mssql database.`
## What is actually happening?
_But the output was bar!_
```
Unable to connect to the mssql database: { SequelizeAccessDeniedError: Login failed for user ''.                                                                                                             
    at Connection.connection.on.err (/home/majkic/Documents/log/easylog-api/node_modules/sequelize/lib/dialects/mssql/connection-manager.js:107:20)                                                          
    at emitOne (events.js:125:13)                                                                                                                                                                            
    at Connection.emit (events.js:221:7)                                                                                                                                                                     
    at Connection.message (/home/majkic/Documents/log/easylog-api/node_modules/tedious/lib/connection.js:1972:18)                                                                                            
    at Connection.dispatchEvent (/home/majkic/Documents/log/easylog-api/node_modules/tedious/lib/connection.js:1172:36)                                                                                      
    at MessageIO.messageIo.on (/home/majkic/Documents/log/easylog-api/node_modules/tedious/lib/connection.js:1045:14)                                                                                        
    at emitNone (events.js:115:13)                                                                                                                                                                           
    at MessageIO.emit (events.js:218:7)                                                                                                                                                                      
    at Message.message.on (/home/majkic/Documents/log/easylog-api/node_modules/tedious/lib/message-io.js:32:14)                                                                                              
    at emitNone (events.js:120:20)                                                                                                                                                                           
    at Message.emit (events.js:218:7)                                                                                                                                                                        
    at endReadableNT (/home/majkic/Documents/log/easylog-api/node_modules/tedious/node_modules/readable-stream/lib/_stream_readable.js:1077:12)                                                              
    at _combinedTickCallback (internal/process/next_tick.js:138:11)                                                                                                                                          
    at process._tickCallback (internal/process/next_tick.js:180:9)                                                                                                                                           
  name: 'SequelizeAccessDeniedError', 
```
First, i was thinking that is an issue regarding tedious but finally, i have succeed to connect using last tedious object configuration format but not with sequelize.

_Output, either JSON or SQL_

__Dialect: mssql 
__Dialect version: 5.0.5
__Database version: 2012
__Sequelize version: 4.43.1

**Comment by Royalsspirit** [comment]
Ok my bad, with sequelize LTS it works as expected.

Sorry for the noise

**Comment by pritamacharjee** [comment]
how to solve it?
