### ISSUE TITLE
bulkCreate does not throw AggregateError

### ISSUE THREAD

**Issue by SET001** [sequelize/sequelize#10773]
The [docs](http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-bulkCreate) say:

> If validation fails, the promise is rejected with an array-like AggregateError

However, instead array-like `AggregateError`, it rejects with single instance of `SequelizeDatabaseError`.

the model:

```
const seqModel = <ItemStatic<Person>>sequelize.define('Person', {
  id: {
    type: new DataTypes.INTEGER(),
    allowNull: false,
    autoIncrement: true,
    primaryKey: true,
  },
  age: new DataTypes.INTEGER(),
  name: new DataTypes.STRING,
}, {
  timestamps: false,
  tableName: 'Person',
})
```

the code that should throw array of errors

```
        const items = [
          {
            name: 'Lila',
          },
          {
            name: 'Frodo',
            age: 'asdasd',
          },
          {
            name: 'Ken',
            age: 'wrong age',
          },
        ]
        try {
          const res = await seqModel.bulkCreate(items, { validate:true })
          console.log(res)
        } catch (e) {
          console.log(e)
        }

```

## What do you expect to happen?
bulkCreate to throw an array-like AggregateError

## What is actually happening?
bulkCreate to throwing single instance of SequelizeDatabaseError:

```
{ SequelizeDatabaseError: Incorrect integer value: 'asdasd' for column 'age' at row 2
    at Query.formatError (/home/set/www/cloudbeds/jarvis/node_modules/sequelize/lib/dialects/mysql/query.js:241:16)
    at Query.handler [as onResult] (/home/set/www/cloudbeds/jarvis/node_modules/sequelize/lib/dialects/mysql/query.js:48:23)
    at Query.execute (/home/set/www/cloudbeds/jarvis/node_modules/mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/home/set/www/cloudbeds/jarvis/node_modules/mysql2/lib/connection.js:449:32)
    at PacketParser.Connection.packetParser.p [as onPacket] (/home/set/www/cloudbeds/jarvis/node_modules/mysql2/lib/connection.js:72:12)
    at PacketParser.executeStart (/home/set/www/cloudbeds/jarvis/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.Connection.stream.on.data (/home/set/www/cloudbeds/jarvis/node_modules/mysql2/lib/connection.js:79:25)
    at Socket.emit (events.js:193:13)
    at addChunk (_stream_readable.js:296:12)
    at readableAddChunk (_stream_readable.js:277:11)
    at Socket.Readable.push (_stream_readable.js:232:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:150:17)
  name: 'SequelizeDatabaseError',
  parent:
   { Error: Incorrect integer value: 'asdasd' for column 'age' at row 2
       at Packet.asError (/home/set/www/cloudbeds/jarvis/node_modules/mysql2/lib/packets/packet.js:684:17)
       at Query.execute (/home/set/www/cloudbeds/jarvis/node_modules/mysql2/lib/commands/command.js:28:26)
       at Connection.handlePacket (/home/set/www/cloudbeds/jarvis/node_modules/mysql2/lib/connection.js:449:32)
       at PacketParser.Connection.packetParser.p [as onPacket] (/home/set/www/cloudbeds/jarvis/node_modules/mysql2/lib/connection.js:72:12)
       at PacketParser.executeStart (/home/set/www/cloudbeds/jarvis/node_modules/mysql2/lib/packet_parser.js:75:16)
       at Socket.Connection.stream.on.data (/home/set/www/cloudbeds/jarvis/node_modules/mysql2/lib/connection.js:79:25)
       at Socket.emit (events.js:193:13)
       at addChunk (_stream_readable.js:296:12)
       at readableAddChunk (_stream_readable.js:277:11)
       at Socket.Readable.push (_stream_readable.js:232:10)
       at TCP.onStreamRead (internal/stream_base_commons.js:150:17)
     code: 'ER_TRUNCATED_WRONG_VALUE_FOR_FIELD',
     errno: 1366,
     sqlState: 'HY000',
     sqlMessage:
      "Incorrect integer value: 'asdasd' for column 'age' at row 2",
     sql:
      "INSERT INTO `Person` (`id`,`name`,`age`) VALUES (NULL,'Lila',NULL),(NULL,'Frodo','asdasd'),(NULL,'Ken','wrong age');" },
  original:
   { Error: Incorrect integer value: 'asdasd' for column 'age' at row 2
       at Packet.asError (/home/set/www/cloudbeds/jarvis/node_modules/mysql2/lib/packets/packet.js:684:17)
       at Query.execute (/home/set/www/cloudbeds/jarvis/node_modules/mysql2/lib/commands/command.js:28:26)
       at Connection.handlePacket (/home/set/www/cloudbeds/jarvis/node_modules/mysql2/lib/connection.js:449:32)
       at PacketParser.Connection.packetParser.p [as onPacket] (/home/set/www/cloudbeds/jarvis/node_modules/mysql2/lib/connection.js:72:12)
       at PacketParser.executeStart (/home/set/www/cloudbeds/jarvis/node_modules/mysql2/lib/packet_parser.js:75:16)
       at Socket.Connection.stream.on.data (/home/set/www/cloudbeds/jarvis/node_modules/mysql2/lib/connection.js:79:25)
       at Socket.emit (events.js:193:13)
       at addChunk (_stream_readable.js:296:12)
       at readableAddChunk (_stream_readable.js:277:11)
       at Socket.Readable.push (_stream_readable.js:232:10)
       at TCP.onStreamRead (internal/stream_base_commons.js:150:17)
     code: 'ER_TRUNCATED_WRONG_VALUE_FOR_FIELD',
     errno: 1366,
     sqlState: 'HY000',
     sqlMessage:
      "Incorrect integer value: 'asdasd' for column 'age' at row 2",
     sql:
      "INSERT INTO `Person` (`id`,`name`,`age`) VALUES (NULL,'Lila',NULL),(NULL,'Frodo','asdasd'),(NULL,'Ken','wrong age');" },

```

Dialect: mysql
Tested with latest release: 5.5.0

**Comment by sushantdhiman** [comment]
Yes `AggregateError` is for any validation error caught by Sequelize. In your case as per validations defined by you, Sequelize instances were built correctly. But they were incorrect for database level restrictions. Those database level errors will flow like single error instances.

You can opt for more strict validations with [`typeValidation = true`](https://github.com/sequelize/sequelize/blob/93e64a9a6f4bef0e606e993271ed963fa0f530a9/lib/sequelize.js#L91)
