### ISSUE TITLE
[BUG] sequelize.sync ({alter:true}) not altering tables.

### ISSUE THREAD

**Issue by iwaduarte** [sequelize/sequelize#10788]
## What are you doing?

I have this simple model 
```js

   const Access_Metric = sequelize.define('access_metric', {

        user_id: {
            type: DataTypes.INTEGER,
        },

    }, {
        underscored: true,
        //tableName: ''

    });

    return Access_Metric;
};
```
And I am running a sync.
```js
sequelize.sync({alter: true,
    logging:true}).then( status => {
    if (status) console.log(status.models);

}).catch(error => console.log(error));

```
## What do you expect to happen?
I expect the table in the database to create a field called user_id.

## What is actually happening?

**I am receiving an error:**

Executing (default): CREATE TABLE IF NOT EXISTS `access_metrics` (`id` INTEGER NOT NULL auto_increment , `user_id` INTEGER, `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;

{ DatabaseError [SequelizeDatabaseError]: Duplicate column name **'created_at'**
sqlMessage: "Duplicate column name 'created_at'",
     sql:
  'ALTER TABLE `access_metrics` ADD `created_at` DATETIME NOT NULL;' },

__Dialect:__ mariadb
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ v 5.3.5
__Tested with latest release:__  Yes. It was working in the version v 4.42.0, I had to update due to snyk pointing some security issues. 

What I think it would be a solution (at least for my case):
I have seen you guys removed the use of indexes. Maybe that is why the bug is occurring. I am not sure. Altough we could use the power of MARIADB and:

ALTER TABLE table_name **ADD COLUMN IF NOT EXISTS** column_name tinyint(1) DEFAULT 0;
https://stackoverflow.com/questions/972922/add-column-to-mysql-table-if-it-does-not-exist/33755258

Any thoughts on this? I really depend upon this feature specially in fast-paced-one-man-carries-all type of environment. Thank you.

**Comment by mirkojotic** [comment]
@sushantdhiman is adding this feature to mariaDB something possible and something we want to pursue?

**Comment by iwaduarte** [comment]
Any updates?

**Comment by binbashtv** [comment]
I'm having this same issue on version 5.7.1 with MySQL.

**Comment by iwaduarte** [comment]
Oh well. I think the only option is to downgrade. If this clearly BUG will be ignored.

**Comment by binbashtv** [comment]
Upgraded to v5.8.0, still an issue.

`{ SequelizeDatabaseError: Duplicate column name 'created_at'
    at Query.formatError (E:\node_files\crypto\crypto-portfolio-v2\node_modules\sequelize\lib\dialects\mysql\query.js:241:16)
    at Query.handler [as onResult] (E:\node_files\crypto\crypto-portfolio-v2\node_modules\sequelize\lib\dialects\mysql\query.js:48:23)
    at Query.execute (E:\node_files\crypto\crypto-portfolio-v2\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (E:\node_files\crypto\crypto-portfolio-v2\node_modules\mysql2\lib\connection.js:449:32)
    at PacketParser.Connection.packetParser.p [as onPacket] (E:\node_files\crypto\crypto-portfolio-v2\node_modules\mysql2\lib\connection.js:72:12)
    at PacketParser.executeStart (E:\node_files\crypto\crypto-portfolio-v2\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.Connection.stream.on.data (E:\node_files\crypto\crypto-portfolio-v2\node_modules\mysql2\lib\connection.js:79:25)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  name: 'SequelizeDatabaseError',
  parent:
   { Error: Duplicate column name 'created_at'
       at Packet.asError (E:\node_files\crypto\crypto-portfolio-v2\node_modules\mysql2\lib\packets\packet.js:684:17)
       at Query.execute (E:\node_files\crypto\crypto-portfolio-v2\node_modules\mysql2\lib\commands\command.js:28:26)
       at Connection.handlePacket (E:\node_files\crypto\crypto-portfolio-v2\node_modules\mysql2\lib\connection.js:449:32)
       at PacketParser.Connection.packetParser.p [as onPacket] (E:\node_files\crypto\crypto-portfolio-v2\node_modules\mysql2\lib\connection.js:72:12)
       at PacketParser.executeStart (E:\node_files\crypto\crypto-portfolio-v2\node_modules\mysql2\lib\packet_parser.js:75:16)
       at Socket.Connection.stream.on.data (E:\node_files\crypto\crypto-portfolio-v2\node_modules\mysql2\lib\connection.js:79:25)
       at Socket.emit (events.js:189:13)
       at addChunk (_stream_readable.js:284:12)
       at readableAddChunk (_stream_readable.js:265:11)
       at Socket.Readable.push (_stream_readable.js:220:10)
       at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
     code: 'ER_DUP_FIELDNAME',
     errno: 1060,
     sqlState: '42S21',
     sqlMessage: 'Duplicate column name \'created_at\'',
     sql:
      'ALTER TABLE `account_details` ADD `created_at` DATETIME NOT NULL;' },
  original:
   { Error: Duplicate column name 'created_at'
       at Packet.asError (E:\node_files\crypto\crypto-portfolio-v2\node_modules\mysql2\lib\packets\packet.js:684:17)
       at Query.execute (E:\node_files\crypto\crypto-portfolio-v2\node_modules\mysql2\lib\commands\command.js:28:26)
       at Connection.handlePacket (E:\node_files\crypto\crypto-portfolio-v2\node_modules\mysql2\lib\connection.js:449:32)
       at PacketParser.Connection.packetParser.p [as onPacket] (E:\node_files\crypto\crypto-portfolio-v2\node_modules\mysql2\lib\connection.js:72:12)
       at PacketParser.executeStart (E:\node_files\crypto\crypto-portfolio-v2\node_modules\mysql2\lib\packet_parser.js:75:16)
       at Socket.Connection.stream.on.data (E:\node_files\crypto\crypto-portfolio-v2\node_modules\mysql2\lib\connection.js:79:25)
       at Socket.emit (events.js:189:13)
       at addChunk (_stream_readable.js:284:12)
       at readableAddChunk (_stream_readable.js:265:11)
       at Socket.Readable.push (_stream_readable.js:220:10)
       at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
     code: 'ER_DUP_FIELDNAME',
     errno: 1060,
     sqlState: '42S21',
     sqlMessage: 'Duplicate column name \'created_at\'',
     sql:
      'ALTER TABLE `account_details` ADD `created_at` DATETIME NOT NULL;' },
  sql:
   'ALTER TABLE `account_details` ADD `created_at` DATETIME NOT NULL;' }`

**Comment by SimonSchick** [comment]
I will do a bisect tomorrow, hit me up if I forget about it 😅

**Comment by SimonSchick** [comment]
@iwaduarte I'd also ask you to be patient, we're working on this in our free time.

**Comment by iwaduarte** [comment]
@SimonSchick  I am patient. I do know that is a free contribution to a opensource cause. I am sorry if it seemed otherwise.

**Comment by SimonSchick** [comment]
I have identified https://github.com/sequelize/sequelize/pull/9529 as the culprit, you're free to poke this, I'm super jetlagged and will drag myself back to bed.

**Comment by SimonSchick** [comment]
Disregard that insomnia kicked in.

@iwaduarte can you confirm the following change resolves your issue?

```
diff --git a/lib/model.js b/lib/model.js
index 1022e751..637e59fe 100644
--- a/lib/model.js
+++ b/lib/model.js
@@ -1296,7 +1296,7 @@ class Model {
             const removedConstraints = {};
 
             _.each(attributes, (columnDesc, columnName) => {
-              if (!columns[columnName]) {
+              if (!columns[columnName] && !columns[attributes[columnName].field]) {
                 changes.push(() => this.QueryInterface.addColumn(this.getTableName(options), attributes[columnName].field || columnName, attributes[columnName]));
               }
             });
```

**Comment by iwaduarte** [comment]
@SimonSchick  which version is this ? The problem does not occur in the version 4.43.2 (only the security warning). Am I missing something?

**Comment by iwaduarte** [comment]
Oh now I see the merge dates the beta version.
