### ISSUE TITLE
Sequelize Unhandled rejection TypeError: Class constructor Model cannot be invoked without 'new'

### ISSUE THREAD

**Issue by nviethuan** [sequelize/sequelize#10783]
## I can't define model using extends from Model abstract class

I using babel@7, webpack, and sequelize@5. anything is ok when I using `sequelize.define(...)` but when i using with extends it not working with my road.

my model
users.js
```js
export class Users extends Model {
  static init(sequelize) {
    return super.init({
      id: {
        type: DataTypes.STRING(36),
        primaryKey: true,
        unique: true,
        allowNull: false,
        defaultValue: () => uuidv4(), // uuid@3.3.2
        validate: {
          isUUID: 36
        }
      },
      username: {
        type: DataTypes.STRING(36),
        unique: true,
        allowNull: false
      },
      password: {
        type: DataTypes.STRING,
        allowNull: false
      },
      firstname: {
        type: DataTypes.STRING(100),
        allowNull: false
      },
      lastname: {
        type: DataTypes.STRING(100),
        allowNull: false
      },
      role: {
        type: DataTypes.STRING(10),
        allowNull: true
      },
      createdDate: {
        type: DataTypes.DATE,
        defaultValue: () => DateUtil.getUTCDateTime()
      },
      isDeleted: {
        type: DataTypes.INTEGER(1),
        defaultValue: 0
      }
    },
    {
      tableName: 'users',
      modelName: 'users',
      ...baseOptions, // my options, that's ok.
      sequelize
    });
  }

  static associate(models) {
    return this.associations = {
      playlists: Users.hasMany(models['playlists'])
    };
  }
}
```
my intance Database file
database.js
```js
export class Database {
  constructor() {
    Database.instance.authenticate()
    .then(() => {
      Object.values(models).map(model => {
        return model.init(Database.instance);
      }).filter(model => {
        return (typeof model.associate).includes('function');
      }).forEach(model => {
        model.associate(Database.instance.models);
      });
      Database.instance.sync().then(() => {
     /**
        i can't create this record with models
        I changed `Database.instance.models.users` to Users from extends class
        but it's not working so. 
      */
        Database.instance.models.users.create({
          "username": "anc123",
          "password": "anc123",
          "firstname": "anc",
          "lastname": "nguyen"
        }).then(() => {
          console.log('ok');
        }).catch(err => {
          console.error(err);
        });
        console.log('Initialize database has been established successfully.');
      });
    })
    .catch((error) => {
      console.error('Unable to initialize to the database:', error);
    });
  }

  static get instance() {
    if(!Database._instance) {
      Database._instance = new Sequelize(DB_CONFIG);
    }
    return Database._instance;
  }
}
```
in my main
```js
...
import { Database } from '../'
new Database();
```

## Error:
```
Unhandled rejection TypeError: Class constructor Model cannot be invoked without 'new'
    at new users (C:\Users\Hydrogener\Desktop\noquere\soul\src\models\users.js:32:19)
    at Function.build (C:\Users\Hydrogener\Desktop\noquere\soul\node_modules\sequelize\lib\model.js:2141:12)
    at Function.create (C:\Users\Hydrogener\Desktop\noquere\soul\node_modules\sequelize\lib\model.js:2194:17)
    at Function.create (C:\Users\Hydrogener\Desktop\noquere\soul\src\models/users.js:65:5)
    at create (C:\Users\Hydrogener\Desktop\noquere\soul\src\helpers/database.js:17:40)
    at tryCatcher (C:\Users\Hydrogener\Desktop\noquere\soul\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Hydrogener\Desktop\noquere\soul\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\Hydrogener\Desktop\noquere\soul\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\Hydrogener\Desktop\noquere\soul\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\Hydrogener\Desktop\noquere\soul\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (C:\Users\Hydrogener\Desktop\noquere\soul\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (C:\Users\Hydrogener\Desktop\noquere\soul\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\Users\Hydrogener\Desktop\noquere\soul\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Hydrogener\Desktop\noquere\soul\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

__Dialect:__ mysql
__Dialect version:__ ???
__Database version:__ 5.7
__Sequelize version:__ 5.6.0
__Tested with latest release:__ No (If yes, specify that version)

**Note :** I had use `@babel/plugin-transform-classes` and `@babel/plugin-proposal-class-properties` for babel plugin.

**Comment by SimonSchick** [comment]
Please highlight the corresponding line.

**Comment by nviethuan** [comment]
It's woked with ver@5.7.0 thanks, details my model:
```javascript
import { DataTypes, Model } from 'sequelize';
import baseOptions from './base';
import { USERS, PLAYLISTS } from '../../constants';
import DateUtil from '../lib/date-util';
import uuidv4 from 'uuid/v4';

class Users extends Model {
  static init(sequelize) {
    return super.init({
      id: {
        type: DataTypes.STRING(36),
        primaryKey: true,
        unique: true,
        allowNull: false,
        defaultValue: () => uuidv4()
      },
      username: {
        type: DataTypes.STRING(36),
        unique: true,
        allowNull: false
      },
      password: {
        type: DataTypes.STRING,
        allowNull: false
      },
      firstname: {
        type: DataTypes.STRING(100),
        allowNull: false
      },
      lastname: {
        type: DataTypes.STRING(100),
        allowNull: false
      },
      role: {
        type: DataTypes.STRING(10),
        allowNull: true
      },
      createdDate: {
        type: DataTypes.DATE,
        defaultValue: () => DateUtil.getUTCDateTime()
      },
      isDeleted: {
        type: DataTypes.INTEGER(1),
        defaultValue: 0
      }
    },
    {
      tableName: USERS,
      ...baseOptions,
      sequelize,
      modelName: USERS
    });
  }

  static associate(models) {
    return this.associations = {
      playlists: Users.hasMany(models[PLAYLISTS])
    };
  }
}
```

**Comment by nviethuan** [comment]
I'm sorry but when I apply Model usage then not working.
I cannot  create record with Model init.

config.js
```js
const host = 'localhost';
const username = 'root';
const password = 'root';
const database = 'maudio';

// database management system
const dialect = 'mysql';

const pool = {
  acquire: 30000,
  idle: 10000,
  max: 5,
  min: 0
};

const authdb = {
  host, username, password
};

const replication = {
  read: authdb,
  write: authdb
};

/**
 * Read node_modules\@types\sequelize\index.d.ts
 * @line 5924
 * node_modules\sequelize\types\lib\sequelize.d.ts
 */
export const DB_CONFIG = {
  dialect,
  pool,
  username,
  password,
  port: 9999,
  database,
  replication
};
```

test.js
```js
import { DB_CONFIG } from './config';
import Sequelize from 'sequelize';

const sequelize = new Sequelize(DB_CONFIG);

class User extends Sequelize.Model {}
User.init({
  username: {
    type: Sequelize.DataTypes.STRING
  }
}, { sequelize, modelName: 'user' });
class Project extends Sequelize.Model {}
Project.init({
  name: {
    type: Sequelize.DataTypes.STRING
  }
}, { sequelize, modelName: 'project' });

sequelize.sync().then(() => {
  User.create({
    username: 'john_doe'
  });
});
```

# My logging Error:
```
Executing (default): CREATE TABLE IF NOT EXISTS `users` (`id` INTEGER NOT NULL auto_increment , `username` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `users` FROM `noquere`
Executing (default): CREATE TABLE IF NOT EXISTS `projects` (`id` INTEGER NOT NULL auto_increment , `name` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `projects` FROM `noquere`
Unhandled rejection TypeError: Class constructor Model cannot be invoked without 'new'
    at new user (C:\Users\Hydrogener\Desktop\noquere\soul\test.js:19:29)
    at Function.build (C:\Users\Hydrogener\Desktop\noquere\soul\node_modules\sequelize\lib\model.js:2140:12)
    at Function.create (C:\Users\Hydrogener\Desktop\noquere\soul\node_modules\sequelize\lib\model.js:2193:17)
    at create (C:\Users\Hydrogener\Desktop\noquere\soul/test.js:20:8)
    at tryCatcher (C:\Users\Hydrogener\Desktop\noquere\soul\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Hydrogener\Desktop\noquere\soul\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\Hydrogener\Desktop\noquere\soul\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\Hydrogener\Desktop\noquere\soul\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\Hydrogener\Desktop\noquere\soul\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (C:\Users\Hydrogener\Desktop\noquere\soul\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (C:\Users\Hydrogener\Desktop\noquere\soul\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\Users\Hydrogener\Desktop\noquere\soul\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Hydrogener\Desktop\noquere\soul\node_modules\bluebird\js\release\async.js:17:14)    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

# How can I using Models usage with that?

**Comment by SimonSchick** [comment]
This doesn't make any sense, your stacktrace must be broken or your file is wrong.
These stack frames:

`at create (C:\Users\Hydrogener\Desktop\noquere\soul/test.js:20:8)` and 
`at new user (C:\Users\Hydrogener\Desktop\noquere\soul\test.js:19:29)` conflict each other (also see slashes).

This is very likely a transpilation issue with babel and not with sequelize.

The line it fails at would be `return new this(values, options);` but then calls back into your code which makes no sense unless your transpilation settings are super wrong.

**Comment by nviethuan** [comment]
Thanks you so much.
I fixed it, just remove `@babel/plugin-transform-classes` pluggin and add
```json
{
  "presets": [
    ["env", {
      "targets": {
        "node": "current"
      }
    }]
  ]
}
```

**Comment by 103cuong** [comment]
Hi guys, I have the same issue with tsc (TypeScript compiler).

### model

```typescript
import { Model, DataTypes } from 'sequelize';
import sequelize from './';
import { OrderStatus } from '../components/constants';

class Order extends Model {
  public id!: number;
  public total!: number;
  public finalTotal!: number;
  public status: OrderStatus;
  public start_date: Date;
  public end_date: Date;
  public created_at: Date;
  public updated_at: Date;
}

Order.init({
  id: {
    type: DataTypes.UUID,
    primaryKey: true,
    defaultValue: DataTypes.UUIDV4
  },
  total: {
    type: DataTypes.INTEGER,
    allowNull: true,
  },
  finalTotal: {
    type: DataTypes.INTEGER,
    allowNull: true,
    validate: {
      len: {
        args: [2, 5],
        msg: 'Name must be from 2 to 5 characters in length'
      },
    }
  },
  status: {
    type: DataTypes.ENUM(OrderStatus.InProcess, OrderStatus.Done)
  },
}, {
  sequelize,
  tableName: 'orders',
})

export default Order;
```

### sequelize.import

```typescript
const modelsPath = `${__dirname}/../src/models`;
  const models = fs
    .readdirSync(modelsPath)
    .filter((filename: string) => /model.ts$/.test(filename))
    .reduce((total: any, filename: string) => {
      const model = sequelize.import(path.join(modelsPath, filename));
      total[capitalize(model.name)] = model;
      return total;
    }, {});

  // Sets up the associations for each model.
  Object.keys(models).forEach((modelName: string) => {
    if ('associate' in models[modelName]) {
      models[modelName].associate(models);
    }
  });
```

### error

```sh
TypeError: Class constructor Order cannot be invoked without 'new'
      at Sequelize.import (node_modules/sequelize/lib/sequelize.js:486:38)
      at /home/cuongw/Workspace/SaveMoney/service-template/test/utils.ts:18:37
      at Array.reduce (<anonymous>)
      at Object.exports.prepareModels (test/utils.ts:17:6)
      at Object.exports.loadFixtures (test/utils.ts:35:18)
      at Context.<anonymous> (test/order.test.ts:16:11)
      at processImmediate (internal/timers.js:456:21)
```

Please tell me a solution. Thank all.

**Comment by 103cuong** [comment]
Hi guys, I have the same issue with tsc (TypeScript compiler).

### version

```json
{
  "sequelize": "^5.21.6",
  "ts-node": "^8.10.1",
  "typescript": "^3.7.2"
}
```

### model

```typescript
import { Model, DataTypes } from 'sequelize';
import sequelize from './';
import { OrderStatus } from '../components/constants';

class Order extends Model {
  public id!: number;
  public total!: number;
  public finalTotal!: number;
  public status: OrderStatus;
  public start_date: Date;
  public end_date: Date;
  public created_at: Date;
  public updated_at: Date;
}

Order.init({
  id: {
    type: DataTypes.UUID,
    primaryKey: true,
    defaultValue: DataTypes.UUIDV4
  },
  total: {
    type: DataTypes.INTEGER,
    allowNull: true,
  },
  finalTotal: {
    type: DataTypes.INTEGER,
    allowNull: true,
    validate: {
      len: {
        args: [2, 5],
        msg: 'Name must be from 2 to 5 characters in length'
      },
    }
  },
  status: {
    type: DataTypes.ENUM(OrderStatus.InProcess, OrderStatus.Done)
  },
}, {
  sequelize,
  tableName: 'orders',
})

export default Order;
```

### sequelize.import

```typescript
const modelsPath = `${__dirname}/../src/models`;
  const models = fs
    .readdirSync(modelsPath)
    .filter((filename: string) => /model.ts$/.test(filename))
    .reduce((total: any, filename: string) => {
      const model = sequelize.import(path.join(modelsPath, filename));
      total[capitalize(model.name)] = model;
      return total;
    }, {});

  // Sets up the associations for each model.
  Object.keys(models).forEach((modelName: string) => {
    if ('associate' in models[modelName]) {
      models[modelName].associate(models);
    }
  });
```

### error

```sh
TypeError: Class constructor Order cannot be invoked without 'new'
      at Sequelize.import (node_modules/sequelize/lib/sequelize.js:486:38)
      at /home/cuongw/Workspace/SaveMoney/service-template/test/utils.ts:18:37
      at Array.reduce (<anonymous>)
      at Object.exports.prepareModels (test/utils.ts:17:6)
      at Object.exports.loadFixtures (test/utils.ts:35:18)
      at Context.<anonymous> (test/order.test.ts:16:11)
      at processImmediate (internal/timers.js:456:21)
```

Please tell me a solution. Thank all.

**Comment by tolumide-ng** [comment]
Hello @kimcuong060498 any information on how you were able to resolve this?

**Comment by agueroveraalvaro** [comment]
> Thanks you so much.
> I fixed it, just remove `@babel/plugin-transform-classes` pluggin and add
> 
> ```json
> {
>   "presets": [
>     ["env", {
>       "targets": {
>         "node": "current"
>       }
>     }]
>   ]
> }
> ```

If I remove the @babel/plugin-plugin-transform-classes I got:

```
Error: [BABEL]: Cannot find module '@babel/plugin-transform-classes'
Require stack:
- /Users/alvaro/NodeProjects/healthy_stones/node_modules/@babel/preset-env/lib/available-plugins.js
- /Users/alvaro/NodeProjects/healthy_stones/node_modules/@babel/preset-env/lib/plugins-compat-data.js
- /Users/alvaro/NodeProjects/healthy_stones/node_modules/@babel/preset-env/lib/normalize-options.js
- /Users/alvaro/NodeProjects/healthy_stones/node_modules/@babel/preset-env/lib/index.js
- /Users/alvaro/NodeProjects/healthy_stones/node_modules/@babel/core/lib/config/files/module-types.js
- /Users/alvaro/NodeProjects/healthy_stones/node_modules/@babel/core/lib/config/files/configuration.js
- /Users/alvaro/NodeProjects/healthy_stones/node_modules/@babel/core/lib/config/files/index.js
- /Users/alvaro/NodeProjects/healthy_stones/node_modules/@babel/core/lib/index.js
- /Users/alvaro/NodeProjects/healthy_stones/node_modules/@babel/register/lib/cache.js
- /Users/alvaro/NodeProjects/healthy_stones/node_modules/@babel/register/lib/node.js
- /Users/alvaro/NodeProjects/healthy_stones/node_modules/@babel/register/lib/nodeWrapper.js
- /Users/alvaro/NodeProjects/healthy_stones/node_modules/@babel/register/lib/index.js
- /Users/alvaro/NodeProjects/healthy_stones/node_modules/@babel/node/lib/_babel-node.js (While processing: /Users/alvaro/NodeProjects/healthy_stones/node_modules/@babel/preset-env/lib/index.js)
```

🤔 any idea or solution? thanks!
