### ISSUE TITLE
Connection timeout doesn't fire when DNS resolves

### ISSUE THREAD

**Issue by dustinsmith1024** [sequelize/sequelize#10805]
## What are you doing?

I am trying to timeout a connection and/or query after a 2 seconds when DNS resolves but firewall rules (or anything else) prevent a connection.

```js
const Sequelize = require(`sequelize`);
const pg = require(`pg`);
const connectionString = `postgres://user:pass@db.app.cn:5432/db`;

const pool = new pg.Pool({
  connectionString: connectionString,
  application_name: `user-service`,
  connectionTimeoutMillis: 2000,
});

pool.query(`SELECT now();`).then(console.log, (e) => console.error(`pg errback`, e));

const sequelize = new Sequelize({
  dialect: `postgres`,
  database: `db`,
  host: `db.app.cn`,
  port: 5432,
  username: `user`,
  password: `pass`,
  //   dialectOptions: {
  //     statement_timeout: 2000,
  //     statementTimeout: 2000,
  //   },
  pool: {
    // max: 1,
    // min: 1,
    acquire: 2000,
    // idle: 3000,
    // handleDisconnects: true,
  },
});

sequelize.query(`SELECT now()`).then(console.log, (e) => console.error(`sequelize errback`, e));
sequelize.authenticate().then(console.log, (e) => console.error(`sequelize auth errback`, e));

```

## What do you expect to happen?

I expect the `#query` and `#authenticate` to error out at the `acquire` timeout which is 2 seconds.

## What is actually happening?

Timeout doesn't happen right away. The `pg.Pool` version does timeout after 2 seconds though.

```
pg errback Error: Connection terminated due to connection timeout
    at Connection.con.once (/app/node_modules/pg/lib/client.js:200:9)
    at Object.onceWrapper (events.js:277:13)
    at Connection.emit (events.js:189:13)
    at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:76:10)
    at Socket.emit (events.js:189:13)
    at TCP._handle.close (net.js:600:12)
sequelize errback { SequelizeConnectionError: connect ETIMEDOUT 10.33.11.99:5432
    at connection.connect.err (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:182:24)
    at Connection.connectingErrorHandler (/app/node_modules/pg/lib/client.js:140:14)
    at Connection.emit (events.js:189:13)
    at Socket.reportStreamError (/app/node_modules/pg/lib/connection.js:71:10)
    at Socket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
From previous event:
    at ConnectionManager.connect (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:121:12)
    at sequelize.runHooks.then (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:309:50)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at ConnectionManager._connect (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:309:8)
    at ConnectionManager.getConnection (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:247:46)
    at Promise.try (/app/node_modules/sequelize/lib/sequelize.js:571:36)
From previous event:
    at Promise.resolve.retryParameters (/app/node_modules/sequelize/lib/sequelize.js:552:66)
    at /app/node_modules/retry-as-promised/index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (/app/node_modules/retry-as-promised/index.js:60:10)
    at Promise.try (/app/node_modules/sequelize/lib/sequelize.js:552:30)
From previous event:
    at Sequelize.query (/app/node_modules/sequelize/lib/sequelize.js:509:23)
    at Object.<anonymous> (/app/src/datasources/seq.js:33:11)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
  name: 'SequelizeConnectionError',
  parent:
   { Error: connect ETIMEDOUT 10.33.11.99:5432
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1104:14)
     errno: 'ETIMEDOUT',
     code: 'ETIMEDOUT',
     syscall: 'connect',
     address: '10.33.11.99',
     port: 5432 },
  original:
   { Error: connect ETIMEDOUT 10.33.11.99:5432
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1104:14)
     errno: 'ETIMEDOUT',
     code: 'ETIMEDOUT',
     syscall: 'connect',
     address: '10.33.11.99',
     port: 5432 } }
sequelize auth errback { SequelizeConnectionError: connect ETIMEDOUT 10.33.11.99:5432
    at connection.connect.err (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:182:24)
    at Connection.connectingErrorHandler (/app/node_modules/pg/lib/client.js:140:14)
    at Connection.emit (events.js:189:13)
    at Socket.reportStreamError (/app/node_modules/pg/lib/connection.js:71:10)
    at Socket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
From previous event:
    at ConnectionManager.connect (/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:121:12)
    at sequelize.runHooks.then (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:309:50)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at ConnectionManager._connect (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:309:8)
    at ConnectionManager.getConnection (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:247:46)
    at Promise.try (/app/node_modules/sequelize/lib/sequelize.js:571:36)
From previous event:
    at Promise.resolve.retryParameters (/app/node_modules/sequelize/lib/sequelize.js:552:66)
    at /app/node_modules/retry-as-promised/index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (/app/node_modules/retry-as-promised/index.js:60:10)
    at Promise.try (/app/node_modules/sequelize/lib/sequelize.js:552:30)
From previous event:
    at Sequelize.query (/app/node_modules/sequelize/lib/sequelize.js:509:23)
    at Object.<anonymous> (/app/src/datasources/seq.js:33:11)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
  name: 'SequelizeConnectionError',
  parent:
   { Error: connect ETIMEDOUT 10.33.11.99:5432
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1104:14)
     errno: 'ETIMEDOUT',
     code: 'ETIMEDOUT',
     syscall: 'connect',
     address: '10.33.11.99',
     port: 5432 },
  original:
   { Error: connect ETIMEDOUT 10.33.11.99:5432
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1104:14)
     errno: 'ETIMEDOUT',
     code: 'ETIMEDOUT',
     syscall: 'connect',
     address: '10.33.11.99',
     port: 5432 } }
```

__Dialect:__ postgres
__Dialect version:__ ? 
__Database version:__ 9.6.11
__Sequelize version:__ 5.7
__Tested with latest release:__ Yes

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by dustinsmith1024** [comment]
Sorry there is no timing in there. It takes over 60 seconds to throw the connection error in the Sequelize version.  2 seconds for the pg version.

**Comment by papb** [comment]
> 
> 
> Sorry there is no timing in there. It takes over 60 seconds to throw the connection error in the Sequelize version. 2 seconds for the pg version.

@dustinsmith1024 Hi, it is not clear to me if you still have this issue or not. If this is still an issue, please let me know and I will reopen it.
