### ISSUE TITLE
nodejs.TimeoutError: ResourceRequest timed out

### ISSUE THREAD

**Issue by acodercat** [sequelize/sequelize#10808]
## What are you doing?
nodejs.TimeoutError: ResourceRequest timed out

```js
    pool: {
      max:  1000,
      acquire: 5000
    },
```

__Dialect:postgres
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:5.1
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
It is impossible to get this error on v5, we are not using `generic-pool` any more. There is no such error in `sequelize-pool`. https://github.com/sushantdhiman/sequelize-pool/search?q=Resource&unscoped_q=Resource

So are you really using v5 @acodercat?

**Comment by acodercat** [comment]
sorry, I use 4.*

**Comment by acodercat** [comment]
```ResourceRequest timed out
    at ResourceRequest._fireTimeout (/home/codercat/Desktop/MAPS/MAPS-cd/node_modules/generic-pool/lib/ResourceRequest.js:62:17)
    at Timeout.bound (/home/codercat/Desktop/MAPS/MAPS-cd/node_modules/generic-pool/lib/ResourceRequest.js:8:15)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
From previous event:
    at new Deferred (/home/codercat/Desktop/MAPS/MAPS-cd/node_modules/generic-pool/lib/Deferred.js:13:21)
    at new ResourceRequest (/home/codercat/Desktop/MAPS/MAPS-cd/node_modules/generic-pool/lib/ResourceRequest.js:23:5)
    at Pool.acquire (/home/codercat/Desktop/MAPS/MAPS-cd/node_modules/generic-pool/lib/Pool.js:450:29)
    at promise.then (/home/codercat/Desktop/MAPS/MAPS-cd/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:274:24)
From previous event:
    at ConnectionManager.getConnection (/home/codercat/Desktop/MAPS/MAPS-cd/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:273:20)
    at Promise.try (/home/codercat/Desktop/MAPS/MAPS-cd/node_modules/sequelize/lib/sequelize.js:554:34)
From previous event:
    at Promise.resolve.retryParameters (/home/codercat/Desktop/MAPS/MAPS-cd/node_modules/sequelize/lib/sequelize.js:454:64)
    at /home/codercat/Desktop/MAPS/MAPS-cd/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/home/codercat/Desktop/MAPS/MAPS-cd/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/home/codercat/Desktop/MAPS/MAPS-cd/node_modules/sequelize/lib/sequelize.js:454:28)
    at QueryInterface.select (/home/codercat/Desktop/MAPS/MAPS-cd/node_modules/sequelize/lib/query-interface.js:1104:27)
    at Promise.try.then.then.then (/home/codercat/Desktop/MAPS/MAPS-cd/node_modules/sequelize/lib/model.js:1598:34)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Function.findAll (/home/codercat/Desktop/MAPS/MAPS-cd/node_modules/sequelize/lib/model.js:1595:8)
    at DynamicFeatureGenerationService.getWeather (/home/codercat/Desktop/MAPS/MAPS-cd/app/service/dynamic_feature_generation.js:21:45)
    at DynamicFeatureGenerationService.generateAHour (/home/codercat/Desktop/MAPS/MAPS-cd/app/service/dynamic_feature_generation.js:43:33)
    at GridDynamicFeature.subscribe (/home/codercat/Desktop/MAPS/MAPS-cd/app/schedule/grid_dynamic_feature.js:38:77)
    at Object.task (/home/codercat/Desktop/MAPS/MAPS-cd/node_modules/egg-schedule/lib/load_schedule.js:37:22)
    at Messenger.app.messenger.on.info (/home/codercat/Desktop/MAPS/MAPS-cd/node_modules/egg-schedule/app.js:46:21)
    at Messenger.emit (events.js:182:13)
    at Messenger._onMessage (/home/codercat/Desktop/MAPS/MAPS-cd/node_modules/egg/lib/core/messenger/ipc.js:116:12)
    at process.emit (events.js:187:15)
    at emit (internal/child_process.js:812:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) name: 'TimeoutError' }```

**Comment by sushantdhiman** [comment]
Set `acquire` to higher value, current setting means it will wait only 5 sec to acquire. Set it like 30 sec or more. Also you probably also want to limit `max`, this means number of connection sequelize will open
