### ISSUE TITLE
Associate two tables in different databases

### ISSUE THREAD

**Issue by alexnfsc175** [sequelize/sequelize#10807]
I need to create an association between tables in two different databases on postgreSQL. if I use table1.hasOne(table2...) sequelize assumes both in the same database when it creates the SQL statement.

but I'm having this error:

```js
  SequelizeDatabaseError: esquema "schemaTest" não existe
      at Query.formatError (/usr/app/node_modules/sequelize/lib/dialects/postgres/query.js:351:16)
      at query.catch.err (/usr/app/node_modules/sequelize/lib/dialects/postgres/query.js:68:18)
      at tryCatcher (/usr/app/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/usr/app/node_modules/bluebird/js/release/promise.js:512:31)
      at Promise._settlePromise (/usr/app/node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromise0 (/usr/app/node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (/usr/app/node_modules/bluebird/js/release/promise.js:690:18)
      at _drainQueueStep (/usr/app/node_modules/bluebird/js/release/async.js:138:12)
      at _drainQueue (/usr/app/node_modules/bluebird/js/release/async.js:131:9)
      at Async._drainQueues (/usr/app/node_modules/bluebird/js/release/async.js:147:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/usr/app/node_modules/bluebird/js/release/async.js:17:14)
      at processImmediate (timers.js:632:19)
```
apparently the query is running in the wrong database.
is there any configuration to change this behavior?

packages versions:
```json
"dependencies": {
    "koa": "^2.7.0",
    "koa-mount": "^4.0.0",
    "koa-router": "^7.4.0",
    "nodemon": "^1.18.10",
    "pg": "^7.9.0",
    "pg-hstore": "^2.3.2",
    "sequelize": "^5.2.12",
    "ts-node": "^8.0.3",
    "tslint": "^5.15.0",
    "typescript": "^3.4.1"
  },
  "devDependencies": {
    "@types/bluebird": "^3.5.26",
    "@types/koa": "^2.0.48",
    "@types/koa-mount": "^3.0.1",
    "@types/koa-router": "^7.0.40",
    "@types/node": "^11.11.3",
    "@types/validator": "^10.11.0",
    "tslint-clean-code": "^0.2.9"
  }
```

**Comment by papb** [comment]
I believe there is no way to do this currently in Sequelize.

**Comment by ephys** [comment]
This issue is related to https://github.com/sequelize/sequelize/issues/12449
