### ISSUE TITLE
Include on through association

### ISSUE THREAD

**Issue by njdart** [sequelize/sequelize#10828]
## What are you doing?
I have two models, `Patient`, and `Device` that are linked through a reference table `PatientDevice`. The linking table also contains references to the `User` table about who made changes to the associations (createdBy, updatedBy, etc). When I use an `include` within 
 the `through` block of a query, it results in a `Cannot read property 'indexOf' of undefined` error

```js
'use strict';

const Sequelize = require('sequelize');

const sequelize = new Sequelize('test', 'postgres', 'postgres', {
    dialect: 'postgres'
});

(async function() {
    await sequelize.authenticate();

    const User = sequelize.define('user', {
        name: Sequelize.STRING
    });

    const Patient = sequelize.define('patient', {
        name: Sequelize.STRING
    });

    const Device = sequelize.define('device', {
        serial: Sequelize.STRING
    });

    const PatientDevice = sequelize.define('patientDeviceAssociation', {
        patient: {
            type: Sequelize.INTEGER,
            foreignKey: {
                references: Patient
            }
        },
        device: {
            type: Sequelize.INTEGER,
            foreignKey: {
                references: Device
            }
        },
        createdBy: {
            type: Sequelize.INTEGER,
            foreignKey: {
                references: User
            }
        },
        updatedBy: {
            type: Sequelize.INTEGER,
            foreignKey: {
                references: User
            }
        }
    });

    Device.belongsToMany(Patient, {
        through: PatientDevice,
        foreignKey: 'device',
        otherKey: 'patient'
    });

    PatientDevice.belongsTo(User, {
        as: 'creator',
        foreignKey: 'createdBy'
    });

    PatientDevice.belongsTo(User, {
        as: 'updater',
        foreignKey: 'updatedBy'
    });

    await sequelize.sync({force: true});

    const user = await User.create({name: 'Dr. Jimmie'});
    const device = await Device.create({serial: '1234'});
    const patient = await Patient.create({name: 'Sick Doris'});
    await device.addPatient(patient, {through: {createdBy: user.id, updatedBy: user.id}});

    // This does not return the creator or updater users
    const foundDevice = await Device.findOne({
        where: { serial: '1234' },
        include: [
            { all: true, nested: true }
        ]
    });
    console.dir(foundDevice.toJSON(), {depth: null});

    // this does return the association
    const foundAssociation = await PatientDevice.findOne({include: [ {all: true, any: true}]});
    console.dir(foundAssociation.toJSON(), {depth: null});

    // This causes the crash and exception below
    const foundDevice2 = await Device.findOne({
        where: { serial: '1234' },
        include: [
            {
                model: Patient,
                through: {
                    // commenting out the include property stops the crash
                    include: [
                        {
                            model: User,
                            as: 'creator'
                        },
                        {
                            model: User,
                            as: 'updater'
                        }
                    ]
                }
            }
        ]
    });
    console.dir(foundDevice2.toJSON(), {depth: null});
    await sequelize.close();
})();
```

## What do you expect to happen?
(if it works) A response containing the `creator` and `updater` associations, or (if it doesn't work) no exception to be thrown and the `include` in the `through` to be ignored
```js
// const device = ...
{
    id: 1,
    serial: '1234',
    createdAt: '2019 - 04 - 23T11: 42: 53.364Z',
    updatedAt: '2019 - 04 - 23T11: 42: 53.364Z',
    patients:
        [{
            id: 1,
            name: 'Sick Doris',
            createdAt: '2019 - 04 - 23T11: 42: 53.369Z',
            updatedAt: '2019 - 04 - 23T11: 42: 53.369Z',
            patientDeviceAssociation:
            {
                patient: 1,
                device: 1,
                createdBy: 1,
                updatedBy: 1,
                createdAt: '2019 - 04 - 23T11: 42: 53.382Z',
                updatedAt: '2019 - 04 - 23T11: 42: 53.382Z',
                creator:
                {
                    id: 1,
                    name: 'Dr. Jimmie',
                    createdAt: '2019 - 04 - 23T11: 42: 53.345Z',
                    updatedAt: '2019 - 04 - 23T11: 42: 53.345Z'
                },
                updater:
                {
                    id: 1,
                    name: 'Dr. Jimmie',
                    createdAt: '2019 - 04 - 23T11: 42: 53.345Z',
                    updatedAt: '2019 - 04 - 23T11: 42: 53.345Z'
                }
            },
        }]
}
```

## What is actually happening?
```
(node:6746) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'includes' of undefined
    at model.set (/home/nic/playground/sequelize/node_modules/sequelize/lib/model.js:3473:80)
    at model.set (/home/nic/playground/sequelize/node_modules/sequelize/lib/model.js:3444:18)
    at model._initValues (/home/nic/playground/sequelize/node_modules/sequelize/lib/model.js:169:10)
    at new Model (/home/nic/playground/sequelize/node_modules/sequelize/lib/model.js:114:10)
    at new patientDeviceAssociation (/home/nic/playground/sequelize/node_modules/sequelize/lib/sequelize.js:357:19)
    at Function.build (/home/nic/playground/sequelize/node_modules/sequelize/lib/model.js:2140:12)
    at model._setInclude (/home/nic/playground/sequelize/node_modules/sequelize/lib/model.js:3607:85)
    at model.set (/home/nic/playground/sequelize/node_modules/sequelize/lib/model.js:3475:14)
    at model.set (/home/nic/playground/sequelize/node_modules/sequelize/lib/model.js:3444:18)
    at model._initValues (/home/nic/playground/sequelize/node_modules/sequelize/lib/model.js:169:10)
    at new Model (/home/nic/playground/sequelize/node_modules/sequelize/lib/model.js:114:10)
    at new patient (/home/nic/playground/sequelize/node_modules/sequelize/lib/sequelize.js:357:19)
    at Function.build (/home/nic/playground/sequelize/node_modules/sequelize/lib/model.js:2140:12)
    at valueSets.map.values (/home/nic/playground/sequelize/node_modules/sequelize/lib/model.js:2160:41)
    at Array.map (<anonymous>)
    at Function.bulkBuild (/home/nic/playground/sequelize/node_modules/sequelize/lib/model.js:2160:22)
    at model._setInclude (/home/nic/playground/sequelize/node_modules/sequelize/lib/model.js:3610:83)
    at model.set (/home/nic/playground/sequelize/node_modules/sequelize/lib/model.js:3475:14)
    at setKeys (/home/nic/playground/sequelize/node_modules/sequelize/lib/model.js:3432:20)
    at model.set (/home/nic/playground/sequelize/node_modules/sequelize/lib/model.js:3440:13)
    at model._initValues (/home/nic/playground/sequelize/node_modules/sequelize/lib/model.js:169:10)
    at new Model (/home/nic/playground/sequelize/node_modules/sequelize/lib/model.js:114:10)
```
[This seems to be the line that caused the issue](https://github.com/sequelize/sequelize/blob/2bb6098d50cfd6b9eae6a3ece6668792a91d99fa/lib/model.js#L3473)

## Environment
Dialect:
- [ ] mysql
- [x] postgres `10.6` (docker `postgres:10.6`)
- [ ] sqlite
- [ ] mssql
- [ ] any

Dialect **library** version: `pg-native 3.0.0, pg 7.10.0 `
Database version: 10.6
Sequelize version: 5.7.4
Node Version: 8.12.0
OS: Arch Linux (both native and within docker `node:carbon-alpine`)

Tested with latest release:
- [ ] No
- [x] Yes, specify that version: 5.7.4

**Comment by SimonSchick** [comment]
I think this might fix it:

```patch
diff --git a/lib/dialects/abstract/query.js b/lib/dialects/abstract/query.js
index 2d0a6a35..036585c4 100755
--- a/lib/dialects/abstract/query.js
+++ b/lib/dialects/abstract/query.js
@@ -187,16 +187,20 @@ class AbstractQuery {
   }
 
   handleInsertQuery(results, metaData) {
-    if (this.instance) {
-      // add the inserted row id to the instance
-      const autoIncrementAttribute = this.model.autoIncrementAttribute;
-      let id = null;
+    if (!this.instance) {
+      return;
+    }
+    // add the inserted row id to the instance
+    const autoIncrementAttribute = this.model.autoIncrementAttribute;
+    if (!autoIncrementAttribute) {
+      return;
+    }
+    let id = null;
 
-      id = id || results && results[this.getInsertIdField()];
-      id = id || metaData && metaData[this.getInsertIdField()];
+    id = id || results && results[this.getInsertIdField()];
+    id = id || metaData && metaData[this.getInsertIdField()];
 
-      this.instance[autoIncrementAttribute] = id;
-    }
+    this.instance[autoIncrementAttribute] = id;
   }
 
   isShowTablesQuery() {
diff --git a/lib/dialects/mssql/query.js b/lib/dialects/mssql/query.js
index f23c94f4..ea41b6d2 100644
--- a/lib/dialects/mssql/query.js
+++ b/lib/dialects/mssql/query.js
@@ -359,23 +359,27 @@ class Query extends AbstractQuery {
   }
 
   handleInsertQuery(results, metaData) {
-    if (this.instance) {
-      // add the inserted row id to the instance
-      const autoIncrementAttribute = this.model.autoIncrementAttribute;
-      let id = null;
-      let autoIncrementAttributeAlias = null;
-
-      if (this.model.rawAttributes.hasOwnProperty(autoIncrementAttribute) &&
-        this.model.rawAttributes[autoIncrementAttribute].field !== undefined)
-        autoIncrementAttributeAlias = this.model.rawAttributes[autoIncrementAttribute].field;
-
-      id = id || results && results[0][this.getInsertIdField()];
-      id = id || metaData && metaData[this.getInsertIdField()];
-      id = id || results && results[0][autoIncrementAttribute];
-      id = id || autoIncrementAttributeAlias && results && results[0][autoIncrementAttributeAlias];
-
-      this.instance[autoIncrementAttribute] = id;
+    if (!this.instance) {
+      return;
     }
+    // add the inserted row id to the instance
+    const autoIncrementAttribute = this.model.autoIncrementAttribute;
+    if (!autoIncrementAttribute) {
+      return;
+    }
+    let id = null;
+    let autoIncrementAttributeAlias = null;
+
+    if (this.model.rawAttributes.hasOwnProperty(autoIncrementAttribute) &&
+      this.model.rawAttributes[autoIncrementAttribute].field !== undefined)
+      autoIncrementAttributeAlias = this.model.rawAttributes[autoIncrementAttribute].field;
+
+    id = id || results && results[0][this.getInsertIdField()];
+    id = id || metaData && metaData[this.getInsertIdField()];
+    id = id || results && results[0][autoIncrementAttribute];
+    id = id || autoIncrementAttributeAlias && results && results[0][autoIncrementAttributeAlias];
+
+    this.instance[autoIncrementAttribute] = id;
   }
 }
 ```

Fee free to create a PR with this and a test case ❤️

**Comment by njdart** [comment]
@SimonSchick Thanks for the quick response.

I applied the diff, but it hasn't changed the error i was getting, although I am using postgres now mysql. I couldn't find an equivalent bit in `lib/dialects/postgres/query.js`. Any advice?

**Comment by SimonSchick** [comment]
Uhh, I think I posted this in the wrong issue 😅

**Comment by njdart** [comment]
I ended up working around this by searching for the joining table, including the models, and applying the where on that model's include.

It doesn't read quite as nice as I would like, but it works.

```js
'use strict';

const Sequelize = require('sequelize');

const sequelize = new Sequelize('postgres', 'postgres', 'postgres', {
    dialect: 'postgres'
});

(async function() {
    await sequelize.authenticate();

    const User = sequelize.define('user', {
        name: Sequelize.STRING
    });

    const Patient = sequelize.define('patient', {
        name: Sequelize.STRING
    });

    const Device = sequelize.define('device', {
        serial: Sequelize.STRING
    });

    const PatientDevice = sequelize.define('patientDeviceAssociation', {
        patientId: Sequelize.INTEGER,
        deviceId: Sequelize.INTEGER,
        createdBy: Sequelize.INTEGER,
        updatedBy: Sequelize.INTEGER
    });

    Device.belongsToMany(Patient, {
        through: PatientDevice,
        foreignKey: 'deviceId',
        otherKey: 'patientId'
    });

    Patient.belongsToMany(Device, {
        through: PatientDevice,
        foreignKey: 'patientId',
        otherKey: 'deviceId'
    });

    PatientDevice.belongsTo(Patient, {
        foreignKey: 'patientId'
    });

    PatientDevice.belongsTo(Device, {
        foreignKey: 'deviceId'
    });

    PatientDevice.belongsTo(User, {
        as: 'creator',
        foreignKey: 'createdBy'
    });

    PatientDevice.belongsTo(User, {
        as: 'updater',
        foreignKey: 'updatedBy'
    });

    await sequelize.sync({force: true});

    const user = await User.create({name: 'Dr. Jimmie'});
    const device = await Device.create({serial: '1234'});
    const patient = await Patient.create({name: 'Sick Doris'});
    await device.addPatient(patient, {through: {createdBy: user.id, updatedBy: user.id}});

    const foundAssociation2 = await PatientDevice.findAll({
        include: [
            Patient,
            {
                model: Device,
                where: {
                    serial: '1234'
                }
            },
            {
                model: User,
                as: 'creator'
            },
            {
                model: User,
                as: 'updater'
            }
        ]
    });
    console.dir(foundAssociation2.map(el => el.toJSON()), {depth: null});
    /*
    [{
        patientId: 1,
        deviceId: 1,
        createdBy: 1,
        updatedBy: 1,
        createdAt: '2019 - 04 - 24T12: 37: 07.259Z',
        updatedAt: '2019 - 04 - 24T12: 37: 07.259Z',
        patient:
        {
            id: 1,
            name: 'Sick Doris',
            createdAt: '2019 - 04 - 24T12: 37: 07.247Z',
            updatedAt: '2019 - 04 - 24T12: 37: 07.247Z'
        },
        device:
        {
            id: 1,
            serial: '1234',
            createdAt: '2019 - 04 - 24T12: 37: 07.240Z',
            updatedAt: '2019 - 04 - 24T12: 37: 07.240Z'
        },
        creator:
        {
            id: 1,
            name: 'Dr. Jimmie',
            createdAt: '2019 - 04 - 24T12: 37: 07.223Z',
            updatedAt: '2019 - 04 - 24T12: 37: 07.223Z'
        },
        updater:
        {
            id: 1,
            name: 'Dr. Jimmie',
            createdAt: '2019 - 04 - 24T12: 37: 07.223Z',
            updatedAt: '2019 - 04 - 24T12: 37: 07.223Z'
        }
    }]
    */

    await sequelize.close();
})();
```

**Comment by olafwrieden** [comment]
@njdart I am facing the very same issue. In my case, a User belongs to many Accounts through a AccountUser table. However, a user could be of various roles in the relation (Admin, Owner, etc) which are defined in another table. I too tried the include in the same way you have and get `Cannot read property 'includes' of undefined` error.
I would think this is a common use case and spent about a week and a half trying to get it working. No luck. Is someone from the Sequelize.js community addressing this? It's clearly an issue.

**Comment by papb** [comment]
It is possible to do this already, but it requires a little 'trick'. I plan on documenting it in the near future. Please hang on just a little longer :grimacing:

If you do not hear from me after a while feel free to call my attention on this again.

**Comment by cristianszwarc** [comment]
@papb thanks for your amazing work with the documentation.

might you please elaborate on "but it requires a little 'trick'"? already went through your PR multiple times but still trying to find out how to include associations to the linking/through record.

thanks!

**Comment by ridakk** [comment]
@papb i have been searching for the same thing `how to include on through`, could you please show the trick you mentioned?

**Comment by mjy78** [comment]
Would also love to know the secret @papb :)

**Comment by osminosm** [comment]
@papb +1 for pointing the part where we can ``include in through``

**Comment by osvaldokalvaitir** [comment]
I am wondering how it includes too, has it been resolved?

**Comment by muhammadfazeel** [comment]
has it been resolved?

**Comment by muhammadfazeel** [comment]
here is the solution check this stackoverflow question 
https://stackoverflow.com/questions/64890300/sequelize-include-on-through-association

**Comment by eperezf** [comment]
I'm having the same issue. The StackOverflow issue is not related.

**Comment by eperezf** [comment]
I'm having the same issue. The StackOverflow issue is not related.

@papb where can we see the solution?

**Comment by fraywing** [comment]
@papb @sushantdhiman any movement on this? This should be a totally legal thing to do.

**Comment by techuila** [comment]
any update on this?

**Comment by Nakroma** [comment]
also wondering - am in need of this

**Comment by osvaldokalvaitir** [comment]
me too

**Comment by Nakroma** [comment]
A workaround that I'm using right now is having the through table as its own standalone one with 1:N relationships between the two M:N tables.

**Comment by techuila** [comment]
@Nakroma same.

but it would be really nice if it's possible to include on through associations.

**Comment by pulsovi** [comment]
> 
> 
> I'm having the same issue. The StackOverflow issue is not related.
> 
> @papb where can we see the solution?

Hello all,

I have the same issue, I came across this page which pointed me in the right direction, thank you all.

I think @papb is talking about this: https://sequelize.org/master/manual/advanced-many-to-many.html#through-tables-versus-normal-tables-and-the--quot-super-many-to-many-association-quot-
