### ISSUE TITLE
Regression when using attributes in scopes.

### ISSUE THREAD

**Issue by vekexasia** [sequelize/sequelize#10896]
## What are you doing?
When using a custom attribute with a sequelize.literal, mostly every query fails cause of this line
https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/query-generator.js#L1383

On this line the `attr[0]` element is {val: 'whatever literal'} which obviously does not have the `includes` method. I'm not sure where in time this stopped working but it is between latest (5.8.5) and 4.42.0.

```ts
describe('test', () => {
  beforeEach(async () => {
    @Table({ tableName: 'brocca' })
    @DefaultScope({
      attributes: [[sequelize.literal('meow'), 'aaa']],
    })
    class Brocca extends Model<Brocca> {}
    const bit = new Sequelize({ dialect: 'postgres' });
    bit.addModels([Brocca]);
    await Brocca.findAll();

    process.exit(0);
  });
  it('test', () => {
    // console.log('a');
  });
});
```
**To Reproduce**
1. Define models copy paste the code above
2. Run the test
3. See stack

## What do you expect to happen?
_I want it to keep working as it was in in 4.x?_

## What is actually happening?
_error is thrown_

```
TypeError: attr[0].includes is not a function
    at attributes.map.attr (node_modules/sequelize/lib/dialects/abstract/query-generator.js:1385:29)
    at Array.map (<anonymous>)
    at PostgresQueryGenerator.escapeAttributes (node_modules/sequelize/lib/dialects/abstract/query-generator.js:1370:37)
    at PostgresQueryGenerator.selectQuery (node_modules/sequelize/lib/dialects/abstract/query-generator.js:1134:28)
    at QueryInterface.select (node_modules/sequelize/lib/query-interface.js:1120:27)
    at Promise.try.then.then.then (node_modules/sequelize/lib/model.js:1748:34)
    at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/release/async.js:17:14)
```

## Environment
Dialect:
- [ ] mysql
- [x] postgres
- [ ] sqlite
- [ ] mssql
- [ ] any
Dialect **library** version: - not sure how to get that. -
Database version: irrelevant
Sequelize version: 5.8.5
Node Version: 10
OS: ubuntu
If TypeScript related: TypeScript version: irrelevant
Tested with latest release:
- [ ] No
- [x] Yes, specify that version:  5.8.5

--- Also opened an issue here - https://github.com/RobinBuschmann/sequelize-typescript/issues/614

**Comment by SimonSchick** [comment]
Can you post the repro without the decorators eg. plain sequelize?

Also can you please ensure you only have 1 version of sequelize installed, this case is covered by an instanceof check, the only way I can see that failing is with multiple versions of the `Literal` class existing.

**Comment by vekexasia** [comment]
Hey @SimonSchick Apparently it works with this plain code:

```ts
import * as sequelize from 'sequelize';
import { Sequelize as SSequelize } from 'sequelize';
import { DefaultScope, Model, Sequelize, Table } from 'sequelize-typescript';

describe('test', () => {
  it('test', async () => {
    // console.log('a');
    @Table({ tableName: 'brocca' })
    @DefaultScope({
      attributes: [[sequelize.literal('meow'), 'aaa']],
    })
    class Brocca extends Model<Brocca> {}
    const bit = new Sequelize({ dialect: 'postgres', logging: true });
    bit.addModels([Brocca]);
    await Brocca.findAll();

  });
  it('test2', async () => {
    class Brocca extends Model {}
    const s = new SSequelize('test', 'test', 'password', {dialect: 'postgres', logging: true});
    Brocca.init({}, {
      defaultScope: {
        attributes: [[sequelize.literal('meow'), 'aaa']],
      },
      sequelize: s,
      tableName: 'brocca',
    });
    console.log('hey');
    await Brocca.findAll();
  });
});

```

**Comment by SimonSchick** [comment]
So you are saying `test2` works?
In this case please close this issue and contact the sequelize-typescript authors.

**Comment by vekexasia** [comment]
Correct. It works. I've already opened a ticket there. Thanks for helping out.
