### ISSUE TITLE
TypeError: Cannot read property 'sync' of undefined

### ISSUE THREAD

**Issue by explorer2309** [sequelize/sequelize#1091]
I am just starting with sequelize and sqlite3 on windows. This is my code:

```
var Sequelize = require('sequelize');
var DataTypes = Sequelize;

var sequelize = new Sequelize('test', '', '', {
  dialect: 'sqlite'
});

var Series, Trainer;          
// Series has a trainer_id = Trainer.id foreign reference key after we call Trainer.hasMany(series)
Series = sequelize.define('Series', {
  title:        DataTypes.STRING,
  sub_title:    DataTypes.STRING,
  description:  DataTypes.TEXT,
  // Set FK relationship (hasMany) with `Trainer`
  trainer_id: {
    type: DataTypes.INTEGER,
    references: "Trainer",
    referencesKey: "id"
  }
});

Trainer = sequelize.define('Trainer', {
  first_name: DataTypes.STRING,
  last_name:  DataTypes.STRING
});

Trainer.hasMany(Series);

sequelize.sync({ force: true }).success(function(){
  console.log('success');
});
```

When I run this, I get error:

```
 C:\Temp\sequelize\node_modules\sequelize\lib\query-chainer.js:78
      var emitter = serial.klass[serial.method].apply(serial.klass, serial
                                ^
TypeError: Cannot read property 'sync' of undefined
    at exec [as fct] (C:\Temp\sequelize\node_modules\sequelize\lib\query-chainer.js:78:37)
    at null.<anonymous> (C:\Temp\sequelize\node_modules\sequelize\lib\emitters\custom-event-emitter.js:25:18)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
```

But it works fine when I take out the statements setting the primary key field

```
 trainer_id: {
   type: DataTypes.INTEGER,
   references: "Trainer",
   referencesKey: "id"
 }
```

Am I doing something wrong?

Thanks!

**Comment by nirajbisht** [comment]
Unable to connect to the database: TypeError: Cannot read property 'sync' of undefined 
please help me I m stuck in between  this my DB table are not been sync
