### ISSUE TITLE
Associations belongsToMany M:N

### ISSUE THREAD

**Issue by qqaimh** [sequelize/sequelize#10934]
As you know, in some countries, as the Internet FireWall we can't viste StackOverflow or Slack.
So we have to put the question here. I am so sorry.
....................................................................................................................................................................................................
I have two tables, they are M:N association. After I set up the associations, I find the instance didn`t have the getXXs( ) and setXXs( ） or getXXs( ) and setXXs( ）not work
....................................................................................................................................................................................................
```js
User.js ( It contains all the models)

var dbseq = require('../db');
var seq = dbseq.Sequelize;

let userDao = dbseq.defineModel('users', {
    email: {
        type: seq.STRING(100),
        primaryKey: true,
        // validate: {isEmail: true}
    },
    password: seq.STRING,
    salt: seq.STRING(100),
    tiehanhan: {
        type: seq.FLOAT,
        defaultValue: 10
    },
    costmoney: {
        type: seq.FLOAT,
        defaultValue: 0.0
    },
    nickname: {
        type: seq.STRING,
        unique: true
    },
    phonenumber: {
        type: seq.STRING(100),
        allowNull: true,
        unique: true
    }
});

let VipMatchesDao = dbseq.defineModel('vipmatches', {
    vipid: {
        type: seq.STRING(80),
        primaryKey: true
    },
    vipmatch: seq.STRING,
    vipprice: seq.FLOAT,
    vipbei: seq.FLOAT,
    vipresult:seq.STRING
});



let userorder = dbseq.defineModel('user_order', {
    orderid: {
        type: seq.INTEGER,
        primaryKey: true,
        autoIncrement: true
    },
    orderstatus: seq.STRING
});

userDao.belongsToMany(VipMatchesDao, {as: 'order',through: userorder});
VipMatchesDao.belongsToMany(userDao, {as: 'user',through: userorder});

userDao.sync();
VipMatchesDao.sync();
userorder.sync();

module.exports= {userDao,VipMatchesDao,userorder};
..............................................................................................................................................................................
Controller.js , I use koa .

const {userDao, VipMatchesDao,userorder}= require("../data/model/Users")

 userDao.findOne({where: {nickname :user.nickname}}).then(res=>{
                    console.log(res.getOrders( ));
                  });
..............................................................................................................................................................................................

**To Reproduce**
Steps to reproduce the behavior:
1. The model userDao, VipMatchesDao
2. Run the join table userorder also good
3. But when I use the models in the Controller.js , the error occurs just as below. If I use getOrders( ), the error is 'res.getOrders is not a function'. the setOrders( ) also not work.

## What do you expect to happen?
I expect the get set function  work.....

## What is actually happening?
this is the error :
Unhandled rejection TypeError: res.getOrders is not a function
    at userDao.findOne.then.res (E:\nodekoa\controller\showController.js:99:37)
    at tryCatcher (E:\nodekoa\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\nodekoa\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (E:\nodekoa\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (E:\nodekoa\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (E:\nodekoa\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (E:\nodekoa\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (E:\nodekoa\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (E:\nodekoa\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\nodekoa\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

## Environment
Dialect:
- [1 ] mysql
- [ ] postgres
- [ ] sqlite
- [ ] mssql
- [ ] any
Dialect library version: mysql2 1.6.5
Database version: 8.0.11 MySQL Community Server - GPL  
Sequelize version: 5.8.5
Node Version: 10.13.0
OS: Win 10
If TypeScript related: TypeScript version: XXX
Tested with latest release:
- [ ] No
- [ 1] Yes, specify that version: 5.8.5

**Comment by qqaimh** [comment]
help help help .....

**Comment by SimonSchick** [comment]
Pretty sure you flipped the association naming here, inspecting the methods manually might give you a better idea, also feel free to join slack for further instructions

**Comment by qqaimh** [comment]
> Pretty sure you flipped the association naming here, inspecting the methods manually might give you a better idea, also feel free to join slack for further instructions

I had see many times
