### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of undefined. when using order by for nested association  column 

### ISSUE THREAD

**Issue by jayprakash941** [sequelize/sequelize#10933]
applying for order by in nested column but getting error

```js

let  orderQuery = `DESC`
query = {where: {status:4,eventModelId:eventModelId,logisticStatus:Number(queryParams.logisticType)},
                    include: [ {model:hcpUserModel,include:[{model: userModel, required: true},{model:hcpLogisticModel,attributes:['attendanceStatus','cancellationReason','updatedAt']}]},
                     {model:eventPledgeModel,require:true,include:[
                    {model:userModel,require:true,include:[{model:gpUserModel}]}]},
                    {model: eventPackageModel,required: true,include:[
                    {model:packageItemDetailModel}]}],order:['$hcpUserModel.userModel.name$',orderQuery]}
using 
order:['$hcpUserModel.userModel.name$',orderQuery]} for order by

Got Error
(node:8378) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of undefined
    at Object.collection.forEach (/node_modules/sequelize/lib/dialects/abstract/query-generator.js:824:61)
    at Array.forEach (<anonymous>)
    at Object.quote (/node_modules/sequelize/lib/dialects/abstract/query-generator.js:752:18)
    at Object.getQueryOrders (/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1740:34)
    at Object.selectQuery (/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1183:27)
    at QueryInterface.select (/node_modules/sequelize/lib/query-interface.js:1105:27)
    at Promise.try.then.then.then (/node_modules/sequelize/lib/model.js:1598:34)
    at bound (domain.js:301:14)
    at runBound (domain.js:314:12)
    at tryCatcher (/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler /(node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
(node:8378) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)


## Environment
Dialect:
- [x] mysql

Dialect **library** version:
Database version: ^1.6.5
Sequelize version:  ^4.42.0
Node Version: 8
OS: XXX

**Comment by SimonSchick** [comment]
Please make your example more
