### ISSUE TITLE
Cannot find module 'sequelize/types/lib/hooks'

### ISSUE THREAD

**Issue by ShintaroNippon** [sequelize/sequelize#10953]
Hi there I'm using an app typescript node js

and in deploy to heroku I got this error

node_modules/sequelize-typescript/dist/hooks/shared/hook-meta.d.ts:2:32 - error TS2307: Cannot find module 'sequelize/types/lib/hooks'.

2 import { SequelizeHooks } from "sequelize/types/lib/hooks";

I have tried tsc build and same error on locally ...

My package.json is
```

  "dependencies": {
       "bcrypt": "^3.0.2",
       "bluebird": "^3.5.1",
       "body-parser": "^1.18.2",
       "dotenv": "^6.2.0",
       "express": "^4.16.2",
       "express-statsd": "^0.3.0",
       "express-validator": "^5.3.0",
       "hashids": "^1.2.2",
       "jsonwebtoken": "^8.4.0",
       "mailgun-js": "^0.22.0",
       "mysql2": "^1.5.1",
       "nyc": "^13.1.0",
       "reflect-metadata": "^0.1.10",
       "sequelize": "^4.37.5",
       "sequelize-typescript": "^1.0.0-alpha.1",
       "strong-error-handler": "^2.3.0",
       "supertest": "^3.3.0",
       "uuid": "^3.3.2"   },  
"devDependencies": {
       "@types/express": "^4.0.39",
       "@types/mocha": "2.2.41",
       "@types/node": "^8.10.39",
       "mocha": "^5.2.0",
       "ts-node": "^3.3.0",
       "tslint": "^5.8.0",
       "typescript": "^2.8.1"   }
```

thanks in advance
```

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'tsc' ]
2 info using npm@6.4.1
3 info using node@v10.15.1
4 verbose run-script [ 'pretsc', 'tsc', 'posttsc' ]
5 info lifecycle sequelize-typescript-starter@1.0.0~pretsc: sequelize-typescript-starter@1.0.0
6 info lifecycle sequelize-typescript-starter@1.0.0~tsc: sequelize-typescript-starter@1.0.0
7 verbose lifecycle sequelize-typescript-starter@1.0.0~tsc: unsafe-perm in lifecycle true
8 verbose lifecycle sequelize-typescript-starter@1.0.0~tsc: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/carlosmanuelmouravieira/Desktop/MyBoxIt-API--master/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/carlosmanuelmouravieira/Desktop/MyBoxIt-API--master/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle sequelize-typescript-starter@1.0.0~tsc: CWD: /Users/carlosmanuelmouravieira/Desktop/MyBoxIt-API--master
10 silly lifecycle sequelize-typescript-starter@1.0.0~tsc: Args: [ '-c', 'tsc' ]
11 silly lifecycle sequelize-typescript-starter@1.0.0~tsc: Returned: code: 2  signal: null
12 info lifecycle sequelize-typescript-starter@1.0.0~tsc: Failed to exec tsc script
13 verbose stack Error: sequelize-typescript-starter@1.0.0 tsc: `tsc`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid sequelize-typescript-starter@1.0.0
15 verbose cwd /Users/carlosmanuelmouravieira/Desktop/MyBoxIt-API--master
16 verbose Darwin 18.5.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "tsc"
18 verbose node v10.15.1
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 2
22 error sequelize-typescript-starter@1.0.0 tsc: `tsc`
22 error Exit status 2
23 error Failed at the sequelize-typescript-starter@1.0.0 tsc script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

**Comment by fareshan** [comment]
I had a similar issue. I fixed it by replacing:
```ts
import { where } from "sequelize/types";
```
by
```ts
import { where } from "sequelize";
```

By the way, you are using non compatible versions of sequelize, sequelize-typescript and typescript. Read the docs of sequelize-typescript

**Comment by kousherAlam** [comment]
Thank you @fareshan
