### ISSUE TITLE
BelongsToMany association does not working

### ISSUE THREAD

**Issue by Chemistry1026** [sequelize/sequelize#10954]
## What are you doing?
Hello, I am sorry for my bad English. There was a problem, I can not associate the Model after creating it through include using belongsToMany.

Tried to associate the model with the data for [this tutorial](http://docs.sequelizejs.com/manual/associations.html#hasmany---belongstomany-association)

```js
//Publisher Model
module.exports = (sequelize, DataTypes) => {
    const Publisher = sequelize.define('Publisher', {
        id: {
            allowNull: false,
            autoIncrement: true,
            primaryKey: true,
            type: DataTypes.INTEGER
        },

        name: {
            type: DataTypes.STRING
        },

        description: {
            type: DataTypes.TEXT
        },

        date: {
            type: DataTypes.STRING
        },

        createdAt: {
            allowNull: false,
            type: DataTypes.DATE,
        },

        updatedAt: {
            allowNull: false,
            type: DataTypes.DATE,
        }
    }, {});
    Publisher.associate = function (models) {
        Publisher.belongsToMany(models.Track, {
            hooks: true,
            through: {
                model: models.ItemPublisher,
                unique: false,
            },
            foreignKey: 'PublisherId',
            constraints: false
        });
    };
    return Publisher;
};

//Track model
'use strict';
module.exports = (sequelize, DataTypes) => {
    const Track = sequelize.define('Track', {
        artist: {
            type: DataTypes.STRING,
            allowNull: false,
        },

        name: {
            type: DataTypes.STRING,
            allowNull: false,
        },

        date: {
            type: DataTypes.STRING,
            allowNull: false,
        },

        bpm: DataTypes.INTEGER,
        description: DataTypes.TEXT,
        lyric: DataTypes.TEXT,
        published: DataTypes.BOOLEAN,

        UserId: DataTypes.INTEGER,
    }, {
        indexes: [{
            unique: false,
            fields: ['userId', 'fileId', 'pictureId', 'artists', 'name'],
        }],

        hooks: {
            afterDestroy(track, options) {
                // track.
            },

            afterBulkDestroy(options) {

            }
        },
    });

    Track.associate = function (models) {
        Track.User = Track.belongsTo(models.User, {
            hooks: true,
        });

        Track.File = Track.belongsToMany(models.File, {
            hooks: true,
            through: {
                model: models.ItemFile,
                unique: false,
                scope: {
                    fileable: 'track',
                },
            },
            foreignKey: 'FileableId',
            constraints: false,
        });

        Track.Picture = Track.belongsToMany(models.Picture, {
            hooks: true,
            through: {
                model: models.ItemPicture,
                unique: false,
                scope: {
                    picturable: 'track',
                },
            },
            foreignKey: 'PicturableId',
            constraints: false,
        });

        Track.Artists = Track.belongsToMany(models.Artist, {
            hooks: true,
            through: {
                model: models.ItemArtist,
                unique: false,
                scope: {
                    artistable: 'track',
                },
            },
            foreignKey: 'ArtistableId',
            constraints: false
        });

        Track.Publishers = Track.belongsToMany(models.Publisher, {
            hooks: true,
            through: {
                model: models.ItemPublisher,
                unique: false,
                scope: {
                    publisherable: 'track',
                },
            },
            foreignKey: 'PublisherableId',
            constraints: false
        });

        Track.Genres = Track.belongsToMany(models.Genre, {
            hooks: true,
            through: {
                model: models.ItemGenre,
                unique: false,
                scope: {
                    genreable: 'track',
                },
            },
            foreignKey: 'GenreableId',
            constraints: false
        });
    };

    return Track;
};

//ItemPublisher Model
module.exports = (sequelize, DataTypes) => {
    const ItemPublisher = sequelize.define('ItemPublisher', {
        id: {
            allowNull: false,
            autoIncrement: true,
            primaryKey: true,
            type: DataTypes.INTEGER
        },
        PublisherId: DataTypes.INTEGER,
        publisherable: DataTypes.STRING,
        PublisherableId: {
            type: DataTypes.INTEGER,
            references: null,
        },
    }, {});
    ItemPublisher.associate = function (models) {
        // associations can be defined here
    };
    return ItemPublisher;
};

// TracksController
let Artists = await Artist.findAll({
    where: {
        name: {
            [Op.in]: ['Radiology'],
        },
    },
});

let Genres = await Genre.findAll({
    where: {
        name: {
            [Op.in]: ['Electro House']
        }
    },
});

let Publishers = await Publisher.findAll({
    where: {
        name: {
            [Op.in]: ['Dharma Worldwide'],
        }
    },
});

let Pictures = await Picture.findOne({
    where: {
        name: '1523719749-radiology-phobia.jpg',
    }
});

let Files = await File.findOne({
    where: {
        name: 'c47a07b7-53ef-455c-a947-f9d4aae27fb6-128.mp3',
    }
});

Track.create({
    artist: 'Radiology',
    name: 'Phobia',
    date: '2018-04-13',
    published: true,
    UserId: 1,
    Artists,
    Genres,
    Publishers,
    Pictures,
    Files,
}, {
    include: [
        Track.Publishers,
        Track.Artists,
        Track.Genres,
        Track.File,
        Track.Picture,
    ],
}).then(async track => {
    res.status(200).json(track);
}).catch(e => console.log(e));
```
**To Reproduce**
1. I get all the data from (genres, pictures, etc.). Because All models are interconnected, chose the belongsToMany connection.
2. Created a polymorphic link ItemModel.
3. When I try to attach them to each other, the data is recorded in the main tables, not in the relationship.

## What do you expect to happen?
_Attach relation_

## What is actually happening?
**Data transmitted by me**
```json
{
    "artist": "Radiology",
    "name": "Phobia",
    "date": "2018-04-13",
    "published": true,
    "UserId": 1,
    "Artists": [
    {
        "id": 3,
        "name": "Radiology",
        "description": null,
        "date": null,
        "createdAt": "2019-05-15T06:18:35.026Z",
        "updatedAt": "2019-05-15T06:18:35.026Z"
    }],
    "Genres": [
    {
        "id": 1,
        "name": "Electro House",
        "description": null,
        "date": null,
        "createdAt": "2019-05-15T06:18:35.030Z",
        "updatedAt": "2019-05-15T06:18:35.030Z"
    }],
    "Publishers": [
    {
        "id": 2,
        "name": "Dharma Worldwide",
        "description": null,
        "date": null,
        "createdAt": "2019-05-15T06:18:35.030Z",
        "updatedAt": "2019-05-15T06:18:35.030Z"
    }],
    "Pictures":
    {
        "path": "http://localhost:7000/uploads/stored/4/",
        "id": 4,
        "name": "1523719749-radiology-phobia.jpg",
        "createdAt": "2019-05-15T06:18:35.031Z",
        "updatedAt": "2019-05-15T06:18:35.031Z"
    },
    "Files":
    {
        "path": "http://localhost:7000/uploads/stored/4/",
        "id": 4,
        "name": "c47a07b7-53ef-455c-a947-f9d4aae27fb6-128.mp3",
        "createdAt": "2019-05-15T06:18:35.034Z",
        "updatedAt": "2019-05-15T06:18:35.034Z"
    }
}
```

```sql
Executing (default): SELECT "id", "name", "description", "date", "createdAt", "updatedAt" FROM "Artists" AS "Artist" WHERE "Artist"."name" IN ('Radiology');
Executing (default): SELECT "id", "name", "description", "date", "createdAt", "updatedAt" FROM "Genres" AS "Genre" WHERE "Genre"."name" IN ('Electro House');
Executing (default): SELECT "id", "name", "description", "date", "createdAt", "updatedAt" FROM "Publishers" AS "Publisher" WHERE "Publisher"."name" IN ('Dharma Worldwide');
Executing (default): SELECT "id", "name", "path", "createdAt", "updatedAt" FROM "Pictures" AS "Picture" WHERE "Picture"."name" = '1523719749-radiology-phobia.jpg' LIMIT 1;
Executing (default): SELECT "id", "name", "path", "createdAt", "updatedAt" FROM "Files" AS "File" WHERE "File"."name" = 'c47a07b7-53ef-455c-a947-f9d4aae27fb6-128.mp3' LIMIT 1;
Executing (default): INSERT INTO "Tracks" ("id","artist","name","date","published","UserId","createdAt","updatedAt") VALUES (DEFAULT,$1,$2,$3,$4,$5,$6,$7) RETURNING *;
Executing (default): INSERT INTO "Publishers" ("id","name","description","date","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5,$6) RETURNING *;
Executing (default): INSERT INTO "Artists" ("id","name","description","date","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5,$6) RETURNING *;
{ SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/Users/macbookpro/Desktop/Work/site/node_modules/sequelize/lib/dialects/postgres/query.js:312:18)
    at query.catch.err (/Users/macbookpro/Desktop/Work/site/node_modules/sequelize/lib/dialects/postgres/query.js:71:18)
    at tryCatcher (/Users/macbookpro/Desktop/Work/site/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/macbookpro/Desktop/Work/site/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/macbookpro/Desktop/Work/site/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/macbookpro/Desktop/Work/site/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/macbookpro/Desktop/Work/site/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/Users/macbookpro/Desktop/Work/site/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/macbookpro/Desktop/Work/site/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/macbookpro/Desktop/Work/site/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/macbookpro/Desktop/Work/site/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
  name: 'SequelizeUniqueConstraintError',
  errors:
   [ ValidationErrorItem {
       message: 'id must be unique',
       type: 'unique violation',
       path: 'id',
       value: '2',
       origin: 'DB',
       instance: [Publisher],
       validatorKey: 'not_unique',
       validatorName: null,
       validatorArgs: [] } ],
  fields: { id: '2' },
  parent:
   { error: duplicate key value violates unique constraint "Publishers_pkey"
       at Connection.parseE (/Users/macbookpro/Desktop/Work/site/node_modules/pg/lib/connection.js:602:11)
       at Connection.parseMessage (/Users/macbookpro/Desktop/Work/site/node_modules/pg/lib/connection.js:399:19)
       at Socket.<anonymous> (/Users/macbookpro/Desktop/Work/site/node_modules/pg/lib/connection.js:121:22)
       at Socket.emit (events.js:182:13)
       at addChunk (_stream_readable.js:283:12)
       at readableAddChunk (_stream_readable.js:264:11)
       at Socket.Readable.push (_stream_readable.js:219:10)
       at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
     name: 'error',
     length: 195,
     severity: 'ERROR',
     code: '23505',
     detail: 'Key (id)=(2) already exists.',
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: 'public',
     table: 'Publishers',
     column: undefined,
     dataType: undefined,
     constraint: 'Publishers_pkey',
     file: 'nbtinsert.c',
     line: '535',
     routine: '_bt_check_unique',
     sql:
      'INSERT INTO "Publishers" ("id","name","description","date","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5,$6) RETURNING *;' },
  original:
   { error: duplicate key value violates unique constraint "Publishers_pkey"
       at Connection.parseE (/Users/macbookpro/Desktop/Work/site/node_modules/pg/lib/connection.js:602:11)
       at Connection.parseMessage (/Users/macbookpro/Desktop/Work/site/node_modules/pg/lib/connection.js:399:19)
       at Socket.<anonymous> (/Users/macbookpro/Desktop/Work/site/node_modules/pg/lib/connection.js:121:22)
       at Socket.emit (events.js:182:13)
       at addChunk (_stream_readable.js:283:12)
       at readableAddChunk (_stream_readable.js:264:11)
       at Socket.Readable.push (_stream_readable.js:219:10)
       at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
     name: 'error',
     length: 195,
     severity: 'ERROR',
     code: '23505',
     detail: 'Key (id)=(2) already exists.',
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: 'public',
     table: 'Publishers',
     column: undefined,
     dataType: undefined,
     constraint: 'Publishers_pkey',
     file: 'nbtinsert.c',
     line: '535',
     routine: '_bt_check_unique',
     sql:
      'INSERT INTO "Publishers" ("id","name","description","date","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5,$6) RETURNING *;' },
  sql:
   'INSERT INTO "Publishers" ("id","name","description","date","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5,$6) RETURNING *;' }
Executing (default): INSERT INTO "Genres" ("id","name","description","date","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5,$6) RETURNING *;
Executing (default): INSERT INTO "Files" ("id","name","path","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5) RETURNING *;
Executing (default): INSERT INTO "Pictures" ("id","name","path","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5) RETURNING *;
```

## Environment
Dialect:
- [x] postgres
Dialect **pg** version: 7.11.0
Database version: 11.2
Sequelize version: 5.8.6
Node Version: 10.15.0
OS: macOS Mojave

**Comment by papb** [comment]
Sequelize requires you to [file new issues](https://github.com/sequelize/sequelize/issues/new/choose) with specific [issue templates](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [StackOverflow](https://stackoverflow.com/) (using the [sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js)) or on [Slack](https://sequelize.slack.com).
