### ISSUE TITLE
belongsTo and hasOne foreignKey added to SQL with foreignKey and underscored set

### ISSUE THREAD

**Issue by kevinlammers** [sequelize/sequelize#10967]
## What are you doing?
Execute a model.findAll operation using a scope that includes a belongsTo associated model.

```js
// code here
```
**To Reproduce**
1. Define models TimeZone and TimeZoneLanguage (see attached). These have a 1:M association.
2. Run the following (this is abbreviated but should suffice as an example:

// Reference the model
const model = Sequelize["TimeZoneLanguage"];
// Apply the scope
model = model.scope("TimeZoneLanguage_Angular_SelectList")
// Execute the query
const records = await model.findAll();

3. See error
name: 'SequelizeDatabaseError',
    message: 'column TimeZoneLanguage.TimeZoneId does not exist',
    operation: 'dbRetrieve',
    original: DatabaseError [SequelizeDatabaseError]: column TimeZoneLanguage.TimeZoneId does not exist
        at Query.formatError (C:\Users\klammers.GT\WebstormProjects\alkali-cloud-server\node_modules\sequelize\lib\dialects\postgres\query.js:354:16)
        at C:\Users\klammers.GT\WebstormProjects\alkali-cloud-server\node_modules\sequelize\lib\dialects\postgres\query.js:71:18
    From previous event:
        at Query.run (C:\Users\klammers.GT\WebstormProjects\alkali-cloud-server\node_modules\sequelize\lib\dialects\postgres\query.js:64:23)
        at C:\Users\klammers.GT\WebstormProjects\alkali-cloud-server\node_modules\sequelize\lib\sequelize.js:577:22
    From previous event:
        at C:\Users\klammers.GT\WebstormProjects\alkali-cloud-server\node_modules\sequelize\lib\sequelize.js:574:10
        at C:\Users\klammers.GT\WebstormProjects\alkali-cloud-server\node_modules\retry-as-promised\index.js:70:21
        at new Promise (<anonymous>)
        at retryAsPromised (C:\Users\klammers.GT\WebstormProjects\alkali-cloud-server\node_modules\retry-as-promised\index.js:60:10)
        at C:\Users\klammers.GT\WebstormProjects\alkali-cloud-server\node_modules\sequelize\lib\sequelize.js:554:30
    From previous event:
        at Sequelize.query (C:\Users\klammers.GT\WebstormProjects\alkali-cloud-server\node_modules\sequelize\lib\sequelize.js:511:23)
        at QueryInterface.select (C:\Users\klammers.GT\WebstormProjects\alkali-cloud-server\node_modules\sequelize\lib\query-interface.js:1119:27)
        at C:\Users\klammers.GT\WebstormProjects\alkali-cloud-server\node_modules\sequelize\lib\model.js:1744:34
        at processImmediate (internal/timers.js:439:21)
    From previous event:
        at Function.findAll (C:\Users\klammers.GT\WebstormProjects\alkali-cloud-server\node_modules\sequelize\lib\model.js:1741:8)
        at Object.dbRetrieve (C:\Users\klammers.GT\WebstormProjects\alkali-cloud-server\dist\alkali-cloud-server\core\sequelize\lib\core.sequelize.lib.data-access.js:176:37)
        at Timeout.findAll [as _onTimeout] (C:\Users\klammers.GT\WebstormProjects\alkali-cloud-server\src\core\sequelize\lib\tests\unit\sequelize.lib.tests.unit.find-all.js:15:19)
        at listOnTimeout (internal/timers.js:531:17)
        at processTimers (internal/timers.js:475:7) {
      name: 'SequelizeDatabaseError',
      parent: [Error],
      original: [Error],
      sql: 'SELECT "TimeZoneLanguage"."id", "TimeZoneLanguage"."name", ' +
        '"TimeZoneLanguage"."language_code" AS "languageCode", ' +
        '"TimeZoneLanguage"."TimeZoneId", "TimeZone"."id" AS ' +
        '"TimeZone.id", "TimeZone"."is_active" AS "TimeZone.isActive" ' +
        'FROM "a_time_zone_language" AS "TimeZoneLanguage" INNER JOIN ' +
        '"a_time_zone" AS "TimeZone" ON ' +
        '"TimeZoneLanguage"."time_zone_id" = "TimeZone"."id" AND ' +
        '"TimeZone"."is_active" = true ORDER BY ' +
        '"TimeZoneLanguage"."name";'
    }

## What do you expect to happen?
Per the documentation:  In all cases the default foreign key can be overwritten with the foreignKey option. When the foreign key option is used, Sequelize will use it as-is.  As such, "TimeZoneLanguage"."TimeZoneId should not be included in the SQL statement.

SELECT
	"TimeZoneLanguage"."id",
	"TimeZoneLanguage"."name",
	"TimeZoneLanguage"."language_code" AS "languageCode",
	"TimeZone"."id" AS "TimeZone.id",
	"TimeZone"."is_active" AS "TimeZone.isActive"
FROM "a_time_zone_language" AS "TimeZoneLanguage"
INNER JOIN
	"a_time_zone" AS "TimeZone" ON "TimeZoneLanguage"."time_zone_id" = "TimeZone"."id" AND "TimeZone"."is_active" = true
ORDER BY
	"TimeZoneLanguage"."name";

## What is actually happening?
"TimeZoneLanguage"."TimeZoneId" is being injected into the Select statement even though underscored is set to true in the model options and foreignKey is set to timeZoneId in the association options.

SELECT
	"TimeZoneLanguage"."id",
	"TimeZoneLanguage"."name",
	"TimeZoneLanguage"."language_code" AS "languageCode",
	"TimeZoneLanguage"."TimeZoneId",
	"TimeZone"."id" AS "TimeZone.id",
	"TimeZone"."is_active" AS "TimeZone.isActive"
FROM "a_time_zone_language" AS "TimeZoneLanguage"
INNER JOIN
	"a_time_zone" AS "TimeZone" ON "TimeZoneLanguage"."time_zone_id" = "TimeZone"."id" AND "TimeZone"."is_active" = true
ORDER BY
	"TimeZoneLanguage"."name";

_Output, either JSON or SQL_

## Environment
Dialect:
- [ ] mysql
- [x ] postgres
- [ ] sqlite
- [ ] mssql
- [ ] any
Dialect **library** version: XXX
Database version: 10.7-2
[TimeZoneLanguage.js.txt](https://github.com/sequelize/sequelize/files/3192952/TimeZoneLanguage.js.txt)
[TimeZone.js.txt](https://github.com/sequelize/sequelize/files/3192953/TimeZone.js.txt)

Sequelize version: 5.8.6
Node Version: 12.0.0
OS: Windows 7
If TypeScript related: TypeScript version: 3.4.5
Tested with latest release:
- [ ] No
- [ ] Yes, specify that version:

**Comment by kevinlammers** [comment]
I had a typeo in the attributes in the scope. I had TimeZoneId where I should have had timeZoneId.
