### ISSUE TITLE
Can't add new command when connection is in closed state

### ISSUE THREAD

**Issue by koi646** [sequelize/sequelize#11004]
when I create model instant include longtext attr, and this attr is big string, it's wrong。

```js
// model attr
        want_code: {
            type: TEXT('medium'),
            allowNull: false 
        }
```
when i use instant.create({want_code}), want_code is big string (such 100000 chars)， it will happen。

## error
```
nodejs.SequelizeDatabaseError: Can't add new command when connection is in closed state
    at Query.formatError (/data/bxyle/server/lotteryServer/node_modules/sequelize/lib/dialects/mysql/query.js:247:16)
    at Query.handler [as onResult] (/data/bxyle/server/lotteryServer/node_modules/sequelize/lib/dialects/mysql/query.js:68:23)
    at Connection._addCommandClosedState (/data/bxyle/server/lotteryServer/node_modules/mysql2/lib/connection.js:139:11)
    at Connection.query (/data/bxyle/server/lotteryServer/node_modules/mysql2/lib/connection.js:534:17)
    at Utils.Promise (/data/bxyle/server/lotteryServer/node_modules/sequelize/lib/dialects/mysql/query.js:77:25)
    at Promise._execute (/data/bxyle/server/lotteryServer/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/data/bxyle/server/lotteryServer/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/data/bxyle/server/lotteryServer/node_modules/bluebird/js/release/promise.js:79:10)
    at Query.run (/data/bxyle/server/lotteryServer/node_modules/sequelize/lib/dialects/mysql/query.js:57:12)
    at Promise.try.then.connection (/data/bxyle/server/lotteryServer/node_modules/sequelize/lib/sequelize.js:558:20)
    at tryCatcher (/data/bxyle/server/lotteryServer/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/data/bxyle/server/lotteryServer/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/data/bxyle/server/lotteryServer/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/data/bxyle/server/lotteryServer/node_modules/bluebird/js/release/promise.js:606:10)
    at _drainQueueStep (/data/bxyle/server/lotteryServer/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (/data/bxyle/server/lotteryServer/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/data/bxyle/server/lotteryServer/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/data/bxyle/server/lotteryServer/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
name: "SequelizeDatabaseError"
parent: {"fatal":true,"sql":"ROLLBACK;"}
original: {"fatal":true,"sql":"ROLLBACK;"}
sql: "ROLLBACK;"
```

## Environment
Dialect:
- [ ] mysql

Database version: MYSQL 5.7
Sequelize version: 4.43.0
Node Version: 12.0.0
OS: centons 8

**Comment by papb** [comment]
I did not understand.

Please provide a [MCVE](stackoverflow.com/help/minimal-reproducible-example).
