### ISSUE TITLE
findOne adds "ORDER BY" internally breaking MSSQL

### ISSUE THREAD

**Issue by myleshk** [sequelize/sequelize#11018]
## What are you doing?
Trying to get count of the whole table records while executing some other aggregate functions like "max", while there is no `group by` specified. 

**To Reproduce**
1. Define model:
```js
sequelize.define('item', {
    id: {
         type: DataTypes.STRING,
         allowNull: false,
         primaryKey: true
    },
    column_1: {
        type: DataTypes.DATE,
	allowNull: true,
    }
});
```
2. Run the following
```js
const result = await model.Item.findOne({
    attributes: [
        [db.sequelize.fn('max', db.sequelize.col('column_1')), 'max_column_1'],
        [db.sequelize.fn('count', '1'), 'count']
    ],
});
```

3. See error
```
SequelizeDatabaseError: Column "item.id" is invalid in the ORDER BY clause because it is not contained in either an aggregate function or the GROUP BY clause.
    at Query.formatError (/project-path/node_modules/sequelize/lib/dialects/mssql/query.js:309:12)
    at Request.connection.lib.Request [as userCallback] (/project-path/node_modules/sequelize/lib/dialects/mssql/query.js:69:23)
    at Request.callback (/project-path/node_modules/tedious/lib/request.js:37:27)
    at Connection.endOfMessageMarkerReceived (/project-path/node_modules/tedious/lib/connection.js:2149:20)
    at Connection.dispatchEvent (/project-path/node_modules/tedious/lib/connection.js:1172:36)
    at Parser.tokenStreamParser.on (/project-path/node_modules/tedious/lib/connection.js:975:14)
    at Parser.emit (events.js:193:13)
    at Parser.parser.on.token (/project-path/node_modules/tedious/lib/token/token-stream-parser.js:27:14)
    at Parser.emit (events.js:193:13)
    at addChunk (/project-path/node_modules/tedious/node_modules/readable-stream/lib/_stream_readable.js:297:12)
    at readableAddChunk (/project-path/node_modules/tedious/node_modules/readable-stream/lib/_stream_readable.js:279:11)
    at Parser.Readable.push (/project-path/node_modules/tedious/node_modules/readable-stream/lib/_stream_readable.js:240:10)
    at Parser.Transform.push (/project-path/node_modules/tedious/node_modules/readable-stream/lib/_stream_transform.js:139:32)
    at Parser.afterTransform (/project-path/node_modules/tedious/node_modules/readable-stream/lib/_stream_transform.js:88:10)
    at Parser._transform (/project-path/node_modules/tedious/lib/token/stream-parser.js:41:7)
    at Parser.Transform._read (/project-path/node_modules/tedious/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at Parser.Transform._write (/project-path/node_modules/tedious/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/project-path/node_modules/tedious/node_modules/readable-stream/lib/_stream_writable.js:405:139)
    at writeOrBuffer (/project-path/node_modules/tedious/node_modules/readable-stream/lib/_stream_writable.js:394:5)
    at Parser.Writable.write (/project-path/node_modules/tedious/node_modules/readable-stream/lib/_stream_writable.js:303:11)
    at Parser.addEndOfMessageMarker (/project-path/node_modules/tedious/lib/token/token-stream-parser.js:45:24)
    at Connection.message (/project-path/node_modules/tedious/lib/connection.js:2138:32)
```

## What do you expect to happen?
`SELECT max([column_1]) AS [max_column_1],count(1) AS [count] FROM [item] AS [item];`

## What is actually happening?
`SELECT max([column_1]) AS [max_column_1],count(1) AS [count] FROM [item] AS [item] ORDER BY [item].[id] OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY;`

## Environment
Dialect:
- mssql
Dialect **tedious** version: 6.1.1
Database version: Microsoft SQL Azure (RTM) - 12.0.2000.8 
Sequelize version: both v4 and v5
Node Version: 11.15.0
OS: Mac OS

Tested with latest release:
- Yes, v5.8.7

**Comment by sushantdhiman** [comment]
This is how `findOne` works, it limits records by 1. Use `findAll`

**Comment by myleshk** [comment]
ok `findAll` works.
