### ISSUE TITLE
RequestError: Timeout: Request failed to complete in 15000ms

### ISSUE THREAD

**Issue by nash90** [sequelize/sequelize#11035]
Issue: unable to set requestTimeout with configuration parameter for "mssql" dilect
No matter whatever value is in requestTimeout parameter, the driver sets default value of "15000ms".
Hence, Timeout error occurs for all query that takes longer than 15s.

Application log is as follows:
```
Executing (default): SELECT [AnalysisTagID], [RefDate], [CategorySet], [AssetID], [Category] FROM [EMA_RiskAllocCategoriesView] AS [EMA_RiskAllocCategoriesView] ORDER BY [EMA_RiskAllocCategoriesView].[AssetID] OFFSET 0 ROWS FETCH NEXT 3 ROWS ONLY;
Error EMA_RiskAllocCategoriesView.getAll DatabaseError [SequelizeDatabaseError]: Timeout: Request failed to complete in 15000ms
    at Query.formatError (/Users/abinash/Desktop/my-app/new-dashboard/ember-electron/resources/sapiat-server/node_modules/sequelize/lib/dialects/mssql/query.js:309:12)
    at Request.userCallback (/Users/abinash/Desktop/my-app/new-dashboard/ember-electron/resources/sapiat-server/node_modules/sequelize/lib/dialects/mssql/query.js:69:23)
    at Request.callback (/Users/abinash/Desktop/my-app/new-dashboard/ember-electron/resources/sapiat-server/node_modules/tedious/lib/request.js:37:27)
    at Connection.message (/Users/abinash/Desktop/my-app/new-dashboard/ember-electron/resources/sapiat-server/node_modules/tedious/lib/connection.js:2181:24)
    at Connection.dispatchEvent (/Users/abinash/Desktop/my-app/new-dashboard/ember-electron/resources/sapiat-server/node_modules/tedious/lib/connection.js:1172:36)
    at MessageIO.<anonymous> (/Users/abinash/Desktop/my-app/new-dashboard/ember-electron/resources/sapiat-server/node_modules/tedious/lib/connection.js:1045:14)
    at MessageIO.emit (events.js:200:13)
    at Message.<anonymous> (/Users/abinash/Desktop/my-app/new-dashboard/ember-electron/resources/sapiat-server/node_modules/tedious/lib/message-io.js:32:14)
    at Message.emit (events.js:205:15)
    at endReadableNT (/Users/abinash/Desktop/my-app/new-dashboard/ember-electron/resources/sapiat-server/node_modules/tedious/node_modules/readable-stream/lib/_stream_readable.js:1077:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  name: 'SequelizeDatabaseError',
  parent: RequestError: Timeout: Request failed to complete in 15000ms
      at RequestError (/Users/abinash/Desktop/my-app/new-dashboard/ember-electron/resources/sapiat-server/node_modules/tedious/lib/errors.js:32:12)
      at Connection.requestTimeout (/Users/abinash/Desktop/my-app/new-dashboard/ember-electron/resources/sapiat-server/node_modules/tedious/lib/connection.js:1117:21)
      at Timeout._onTimeout (/Users/abinash/Desktop/my-app/new-dashboard/ember-electron/resources/sapiat-server/node_modules/tedious/lib/connection.js:1085:14)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7) {
    message: 'Timeout: Request failed to complete in 15000ms',
    code: 'ETIMEOUT',
    sql: 'SELECT [AnalysisTagID], [RefDate], [CategorySet], ' +
      '[AssetID], [Category] FROM [EMA_RiskAllocCategoriesView] ' +
      'AS [EMA_RiskAllocCategoriesView] ORDER BY ' +
      '[EMA_RiskAllocCategoriesView].[AssetID] OFFSET 0 ROWS ' +
      'FETCH NEXT 3 ROWS ONLY;'
  },
```
## What are you doing?

sequelize is instantiated as follows
```js
const sequelize = new Sequelize(config.db.schema, config.db.username, config.db.password, {  
  "host": config.db.url,
  "dialect": "mssql",
  "dialectOptions": {
    "requestTimeout": 300000
  },
  pool: {
    max: 5,
    min: 0,
    acquire: 30000,
    idle: 10000
  }
});
```

A query that does full scan in a large table is run as follows:

```
EMA_RiskAllocCategoriesView.findAll({
    }).catch((err)=>{
      console.log("Error EMA_RiskAllocCategoriesView.getAll",err)
    });
```
**To Reproduce**
1. Initiate sequelize with 30s
2. Use a query that takes longer than 15s
3. See error

## What do you expect to happen?
Not thow request timeout error for queries that run for 30s if sequelize is set to have requestTimeout of 30s.

## What is actually happening?
Timeout Error for all query that takes longer than 15 s

_Output, either JSON or SQL_

## Environment
Dialect:
- mssql

Dialect **library** version: tedious 6.1.2
Database version: mcr.microsoft.com/mssql/server:2017-latest (docker)
Sequelize version: 5.8.7
Node Version: v12.3.1
OS: osx
If TypeScript related: TypeScript version: XXX
Tested with latest release:
-  No

Self investigation.
hard coded fix is to change the value of the following variable in "lib/connection.js" module of tedious library
const DEFAULT_CLIENT_REQUEST_TIMEOUT = 15 * 1000;

**Comment by cbogwill** [comment]
@nash90:
I had the same issue.  Try doing this instead:
```
"dialectOptions": {
    options: { "requestTimeout": 300000 }
  },
```

**Comment by papb** [comment]
@nash90 Does the above workaround work for you?

**Comment by Yaowenjie** [comment]
@cbogwill 
It seems not working for my case. BTW, I am using `mssql` dialect.

**Comment by nash90** [comment]
@papb @Yaowenjie 
The solution provided by @cbogwill worked.

**Comment by nash90** [comment]
> @nash90:
> I had the same issue. Try doing this instead:
> 
> ```
> "dialectOptions": {
>     options: { "requestTimeout": 300000 }
>   },
> ```

Thanks, This solution worked .

**Comment by Yaowenjie** [comment]
@cbogwill @nash90 
Yes, that works. I missed the `options` level.

**Comment by nash90** [comment]
> @cbogwill @nash90
> Yes, that works. I missed the `options` level. Thank you, all!

By the way, that setting was in this code of the sequelize
https://github.com/sequelize/sequelize/pull/11045/files#diff-3aa0e1a84e1c794951afaa682fde719dR60

**Comment by ongkristopher** [comment]
> @nash90:
> I had the same issue. Try doing this instead:
> 
> ```
> "dialectOptions": {
>     options: { "requestTimeout": 300000 }
>   },
> ```

> Ignoring invalid configuration option passed to Connection: options. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration options to a Connection

this is showing on my log using that format.

**Comment by jeserg** [comment]
const config = {
  user: 'login',
  password: 'pass',
  server: '10.11.24.15',
  port: 1433,
  database: 'base',
  **requestTimeout: 130000,**
  pool: {
    max: 10,
    min: 0,
    idleTimeoutMillis: 130000
  }
}

**Comment by ashokkumarg** [comment]
I tried using the both the dialectOptions to the configuration as below but still I face the same issue

> dialectOptions: {
>    "requestTimeout": 300000
>    }
> 
>   "dialectOptions": {
>     options: { "requestTimeout": 300000 }
>   }
> 


```
const DBConfig = {
  user: 'username',
  password: '*******',
  host: 'host name',
  port: 1455,
  database: 'database name',
  server: 'server name',
  dialect: "mssql"
};
```

**Comment by 854770857** [comment]
@ashokkumarg 
How was it resolved in the end?

**Comment by jepalen** [comment]
For me in NodeJs with Mssql worked just this small change:
just put outside of the options the field requestTimeout

const config = {
user: 'login',
password: 'pass',
server: '10.11.24.15',
port: 1433,
database: 'base',
'requestTimeout': 130000,
options: {
'enableArithAbort': true,
'idleTimeoutMillis': 130000
},

**Comment by davidbouckaert** [comment]
Hello, anno 2021 I've got this working with the following code (I'm connecting to Azure, so I need encryption).

`const knex = require('knex')({
  client: 'mssql',
  connection: {
    host: '*****',
    user: '*****',
    password: '*****',
    options: { requestTimeout: 300000, encrypt: true },
  },
});`

**Comment by tensajougan8** [comment]
You need to hard code it 
add this to the config 
> dialectOptions:{
>         requestTimeout: 300000 
>     }

add the following to 
\sequelize\lib\dialects\mssql\connection-manager-> connectionConfig 

> requestTimeout: config.dialectOptions.requestTimeout

by  @nash90

**Comment by SpringsTea** [comment]
A lot of different methods thrown around here, so I figured I'd put out what actually worked for me.

```
const connection = require('knex')({
  client: 'mssql',
  connection: {
    host :  'hostaddress',
    user : user,
    password : password,
    requestTimeout: 600000,// this part worked for me, 10 min timeout
    database : 'DBName'
  }
});
```

Putting `requestTimeout` in `options` or `dialectOptions` was not working for me.

**Comment by jhunexjun** [comment]
This is my config and it worked for me.

```js
const sqlConfig = {
	user: process.env.DB_USERNAME,
	password: process.env.DB_PASSWORD,
	database: process.env.DB_DATABASE,
	server: process.env.DB_SERVER,
	pool: {
		max: 10,
		min: 0,
		idleTimeoutMillis: 15000
	},
	options: {
		encrypt: false, // for azure
		trustServerCertificate: true, // change to true for local dev / self-signed certs
		// useUTC: false	// (defaults: true)
	},
	requestTimeout: 600000, // I just added this one
}
```

**Comment by ramon-allink** [comment]
Thanks @cbogwill! Works perfect for me

**Comment by itskelechi** [comment]
it looks like we're just extending the timeout window instead of fixing why its timing out? did anyone try closing existing pools that were left open? Isn't increasing timeout window stalling the application?
