### ISSUE TITLE
Azure SQL Server not working

### ISSUE THREAD

**Issue by TraceLD** [sequelize/sequelize#11128]
```js
var sequelize = new Sequelize('dbName', 'username', 'password', {
	host: 'myserver.database.windows.net',
	dialect: 'mssql',
	pool: {
		max: 5,
		min: 0,
		idle: 10000
	},
	dialectOptions: {
		encrypt: true
	}
});
```

results in the following error:

```
Unhandled rejection SequelizeConnectionError: Server requires encryption, set 'encrypt' config option to true.
    at Promise.catch.error (C:\Users\Lukasz\Desktop\barcabot-all\barcabot-charts\node_modules\sequelize\lib\dialects\mssql\connection-manager.js:141:17)
    at tryCatcher (C:\Users\Lukasz\Desktop\barcabot-all\barcabot-charts\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Lukasz\Desktop\barcabot-all\barcabot-charts\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (C:\Users\Lukasz\Desktop\barcabot-all\barcabot-charts\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (C:\Users\Lukasz\Desktop\barcabot-all\barcabot-charts\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (C:\Users\Lukasz\Desktop\barcabot-all\barcabot-charts\node_modules\bluebird\js\release\promise.js:695:18)
    at _drainQueueStep (C:\Users\Lukasz\Desktop\barcabot-all\barcabot-charts\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (C:\Users\Lukasz\Desktop\barcabot-all\barcabot-charts\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\Users\Lukasz\Desktop\barcabot-all\barcabot-charts\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Lukasz\Desktop\barcabot-all\barcabot-charts\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

I'm clearly adding encrypt but it's not working. Doing `options: { encrypt: true }` instead of dialectOptions has the same effect.

**Comment by TraceLD** [comment]
For anyone that also has the same problem, I fixed it by changing `dialectOptions` to this:
```js
dialectOptions: {
		options: {
			encrypt: true
		}
	}
```
