### ISSUE TITLE
Could not start my project due to: Type error

### ISSUE THREAD

**Issue by nayaya25** [sequelize/sequelize#11248]
Hello! I was trying to start my node/express app but I get this error.
`
A:\Portal_project\customer-portal\Server\node_modules\sequelize\lib\utils.js:94
  return str.trim().replace(/[-_\s]+(.)?/g, (match, c) => c.toUpperCase());
                                                            ^

TypeError: Cannot read property 'toUpperCase' of undefined
    at str.trim.replace (A:\Portal_project\customer-portal\Server\node_modules\sequelize\lib\utils.js:94:61)
    at String.replace (<anonymous>)
    at Object.camelize (A:\Portal_project\customer-portal\Server\node_modules\sequelize\lib\utils.js:94:21)
    at new BelongsTo (A:\Portal_project\customer-portal\Server\node_modules\sequelize\lib\associations\belongs-to.js:42:31)
    at Function.<anonymous> (A:\Portal_project\customer-portal\Server\node_modules\sequelize\lib\associations\mixin.js:105:25)
    at Function.MGBCard.associate (A:\Portal_project\customer-portal\Server\db\models\mgbcard.js:16:15)
    at Object.keys.forEach.modelName (A:\Portal_project\customer-portal\Server\db\models\index.js:30:19)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (A:\Portal_project\customer-portal\Server\db\models\index.js:28:17)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (A:\Portal_project\customer-portal\Server\api\controllers\customerController.js:1:78)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)`

**Comment by papb** [comment]
Sequelize requires you to [file new issues](https://github.com/sequelize/sequelize/issues/new/choose) with specific [issue templates](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [StackOverflow](https://stackoverflow.com/) (using the [sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js)) or on [Slack](https://sequelize.slack.com).
