### ISSUE TITLE
SequelizeDatabaseError: Cannot truncate a table referenced in a foreign key constraint

### ISSUE THREAD

**Issue by marcpre** [sequelize/sequelize#11289]
## What are you doing?

I have defined two models, **company** and **dividend**

```js
My `company.js` model looks like the following:

    'use strict';
    module.exports = (sequelize, DataTypes) => {
      const Company = sequelize.define('Company', {
        company_name: DataTypes.STRING,
        company_link: DataTypes.STRING,
        ticker: DataTypes.STRING,
        description: DataTypes.STRING
      }, {});
      Company.associate = function(models) {
        Company.hasMany(models.Rating, { onDelete: 'cascade' });
        Company.hasMany(models.Dividend, { onDelete: 'cascade' });
      };
      return Company;
    };

My `dividend.js` model looks like the following:

    'use strict';
    module.exports = (sequelize, DataTypes) => {
      const Dividend = sequelize.define('Dividend', {
        period: DataTypes.STRING,
        amount: DataTypes.FLOAT,
        payable_date: DataTypes.DATE,
      }, {});
      Dividend.associate = function(models) {
        Dividend.belongsTo(models.Company, { onDelete: 'cascade' });
      };
      return Dividend;
    };

My `truncate.js` function looks like the following:

    const models = require('../models');
    
    const truncateTable = (modelName) =>
      models[modelName].destroy({
        where: {},
        force: true,
      });
    
    module.exports = async function truncate(model) {
      if (model) {
        return truncateTable(model);
      }
    
      return Promise.all(
        Object.keys(models).map((key) => {
          if (['sequelize', 'Sequelize'].includes(key)) return null;
          return truncateTable(key);
        })
      );
    }
```

## What do you expect to happen?
I want to truncate the model with a foreign key constraint

## What is actually happening?

When trying to truncate both models I get the following error:
```
    { SequelizeDatabaseError: Cannot truncate a table referenced in a foreign key constraint (`test-db`.`dividends`, CONSTRAINT
    `dividends_ibfk_1` FOREIGN KEY (`CompanyId`) REFERENCES `test-db`.`companies` (`id`))
        at Query.formatError (c:\test\node_modules\sequelize\lib\dialects\mysql\query.js:239:16)
        at Query.handler [as onResult] (c:\test\node_modules\sequelize\lib\dialects\mysql\query.js:46:23)
        at Query.execute (c:\test\node_modules\mysql2\lib\commands\command.js:30:14)
        at Connection.handlePacket (c:\test\node_modules\mysql2\lib\connection.js:449:32)
        at PacketParser.Connection.packetParser.p [as onPacket] (c:\test\node_modules\mysql2\lib\connection.js:72:12)
        at PacketParser.executeStart (c:\test\node_modules\mysql2\lib\packet_parser.js:75:16)
        at Socket.Connection.stream.on.data (c:\test\node_modules\mysql2\lib\connection.js:79:25)
        at Socket.emit (events.js:189:13)
        at addChunk (_stream_readable.js:284:12)
        at readableAddChunk (_stream_readable.js:265:11)
        at Socket.Readable.push (_stream_readable.js:220:10)
        at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
      name: 'SequelizeDatabaseError',
      parent:
       { Error: Cannot truncate a table referenced in a foreign key constraint (`test-db`.`dividends`, CONSTRAINT `dividends_ibfk_1` FOREIGN KEY (`CompanyId`) REFERENCES `test-db`.`companies` (`id`))
           at Packet.asError (c:\test\node_modules\mysql2\lib\packets\packet.js:684:17)
           at Query.execute (c:\test\node_modules\mysql2\lib\commands\command.js:28:26)
           at Connection.handlePacket (c:\test\node_modules\mysql2\lib\connection.js:449:32)
           at PacketParser.Connection.packetParser.p [as onPacket] (c:\test\node_modules\mysql2\lib\connection.js:72:12)
           at PacketParser.executeStart (c:\test\node_modules\mysql2\lib\packet_parser.js:75:16)
           at Socket.Connection.stream.on.data (c:\test\node_modules\mysql2\lib\connection.js:79:25)
           at Socket.emit (events.js:189:13)
           at addChunk (_stream_readable.js:284:12)
           at readableAddChunk (_stream_readable.js:265:11)
           at Socket.Readable.push (_stream_readable.js:220:10)
           at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
         code: 'ER_TRUNCATE_ILLEGAL_FK',
         errno: 1701,
         sqlState: '42000',
         sqlMessage:
          'Cannot truncate a table referenced in a foreign key constraint (`test-db`.`dividends`, CONSTRAINT `dividends_ibfk_1`
    FOREIGN KEY (`CompanyId`) REFERENCES `test-db`.`companies` (`id`))',
         sql: 'TRUNCATE `Companies`' },
      original:
       { Error: Cannot truncate a table referenced in a foreign key constraint (`test-db`.`dividends`, CONSTRAINT `dividends_ibfk_1` FOREIGN KEY (`CompanyId`) REFERENCES `test-db`.`companies` (`id`))
           at Packet.asError (c:\test\node_modules\mysql2\lib\packets\packet.js:684:17)
           at Query.execute (c:\test\node_modules\mysql2\lib\commands\command.js:28:26)
           at Connection.handlePacket (c:\test\node_modules\mysql2\lib\connection.js:449:32)
           at PacketParser.Connection.packetParser.p [as onPacket] (c:\test\node_modules\mysql2\lib\connection.js:72:12)
           at PacketParser.executeStart (c:\test\node_modules\mysql2\lib\packet_parser.js:75:16)
           at Socket.Connection.stream.on.data (c:\test\node_modules\mysql2\lib\connection.js:79:25)
           at Socket.emit (events.js:189:13)
           at addChunk (_stream_readable.js:284:12)
           at readableAddChunk (_stream_readable.js:265:11)
           at Socket.Readable.push (_stream_readable.js:220:10)
           at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
         code: 'ER_TRUNCATE_ILLEGAL_FK',
         errno: 1701,
         sqlState: '42000',
         sqlMessage:
          'Cannot truncate a table referenced in a foreign key constraint (`test-db`.`dividends`, CONSTRAINT `dividends_ibfk_1`
    FOREIGN KEY (`CompanyId`) REFERENCES `test-db`.`companies` (`id`))',
         sql: 'TRUNCATE `Companies`' },
      sql: 'TRUNCATE `Companies`' }
```
## Environment
Dialect:
- [x] mysql

Dialect **"mysql2"** version: `"^1.6.5",`
Database version: Server-Version: 10.1.39-MariaDB - mariadb.org binary distribution
Sequelize version: `^5.8.6`
Node Version: `v10.15.3`
OS: Windows 7

**Comment by sushantdhiman** [comment]
Use `cascade` option https://sequelize.org/master/class/lib/model.js~Model.html#static-method-truncate
