### ISSUE TITLE
.sync({alter:true)} causes issue with Boolean Default Values in MSSQL

### ISSUE THREAD

**Issue by Taher62** [sequelize/sequelize#11303]
What are you doing?
Creating a model with a boolean that has a defaultValue: false in MSSQL

isAdmin: { type: DataTypes.BOOLEAN, defaultValue: false, allowNull: false }
What do you expect to happen?
When running the app with alter: true it should automatically update and alter tables requiring updates.

What is actually happening?
The line that it errors on is relating to the boolean field with a default value.

Executing (default): ALTER TABLE [solution_managers] ALTER COLUMN [isAdmin] BIT NOT NULL DEFAULT 0;

The error given by sequelize:

Unhandled rejection SequelizeDatabaseError: Incorrect syntax near the keyword 'DEFAULT'.
    at Query.formatError (\node_modules\sequelize\lib\dialects\mssql\query.js:315:12)
    at Request.connection.lib.Request [as userCallback] (\node_modules\sequelize\lib\dialects\mssql\query.js:107:25)
    at Request.callback (\node_modules\tedious\lib\request.js:37:27)
    at Connection.endOfMessageMarkerReceived (\node_modules\tedious\lib\connection.js:1880:20)
    at Connection.dispatchEvent (\node_modules\tedious\lib\connection.js:997:36)    at Parser.tokenStreamParser.on (\node_modules\tedious\lib\connection.js:827:14)
    at Parser.emit (events.js:182:13)
    at Parser.parser.on.token (\node_modules\tedious\lib\token\token-stream-parser.js:27:14)
    at Parser.emit (events.js:182:13)
    at addChunk (\node_modules\readable-stream\lib\_stream_readable.js:301:12)
    at readableAddChunk (\node_modules\readable-stream\lib\_stream_readable.js:283:11)
    at Parser.Readable.push (\node_modules\readable-stream\lib\_stream_readable.js:247:10)
    at Parser.Transform.push (\node_modules\readable-stream\lib\_stream_transform.js:149:32)
    at Parser.afterTransform (\node_modules\readable-stream\lib\_stream_transform.js:92:10)
    at Parser._transform (\node_modules\tedious\lib\token\stream-parser.js:40:7)    at Parser.Transform._read (\node_modules\readable-stream\lib\_stream_transform.js:185:10)
    at Parser.Transform._write (\node_modules\readable-stream\lib\_stream_transform.js:173:83)
    at doWrite (\node_modules\readable-stream\lib\_stream_writable.js:429:139)
    at writeOrBuffer (\node_modules\readable-stream\lib\_stream_writable.js:418:5)
    at Parser.Writable.write (\node_modules\readable-stream\lib\_stream_writable.js:327:11)
    at Parser.addEndOfMessageMarker (\node_modules\tedious\lib\token\token-stream-parser.js:45:24)
    at Connection.message (\node_modules\tedious\lib\connection.js:1869:32)
Dialect: mssql
Dialect version: XXX
Database version: SQL SERVER 2016
Sequelize version: 4.41.0
Tested with latest release: 5.0.0-beta.13

**Comment by papb** [comment]
Please improve the formatting of your issue. All the markdown structure was lost. The markdown structure from your other attempt #11301 was correct, although you didn't fill anything.

Once you fix your issue presentation I will reopen it.
