### ISSUE TITLE
"TypeError: results.map is not a function" when calling connection.sync()

### ISSUE THREAD

**Issue by rschpdr** [sequelize/sequelize#11324]
## What are you doing?

```js
// app.ts

import * as functions from 'firebase-functions';
import router from './routes';

const express = require('express');

const cors = require('cors')({
  origin: true
});

const app = express();

app.use(cors);
app.use('/', router);

export const api = functions.https.onRequest((request, response) => {
  if (!request.path) {
    request.url = `/${request.url}`;
  }

  return app(request, response);
});

// load models

const fs = require('fs');
const path = require('path');
const basename = path.basename(module.filename);

import config from '../config';

const Sequelize = require('sequelize');
// const fs = require('fs');
// const path = require('path');
// const basename = path.basename(module.filename);

const db = {};

if (config.sequelize.length) {
  config.sequelize.map(dbConfig => {
    db[dbConfig.name] = new Sequelize(
      dbConfig.database,
      dbConfig.username,
      dbConfig.password,
      {
        host: dbConfig.host,
        dialect: dbConfig.dialect,
        port: dbConfig.port,
        query: { type: Sequelize.QueryTypes.SELECT }
      }
    );
  });
}

fs.readdirSync(path.resolve(__dirname, '../models'))
  .filter(
    file =>
      file.indexOf('.') !== 0 && file !== basename && file.slice(-3) === '.js'
  )
  .forEach(async file => {
    const requires = {};

    const fileName = file.split('.')[0];

    requires[fileName] = require(`${path.resolve(
      __dirname,
      '../models'
    )}/${file}`);

    if (requires[fileName].default) {
      db['MYSQL_TEST'][fileName] = requires[fileName].default.init(
        db['MYSQL_TEST']
      );
 }
    }
  });

const syncModels = async () => {
  await db['MYSQL_TEST'].sync();
};

syncModels();

export default db;

// the model

const Sequelize = require('sequelize');

export default class Unidade extends Sequelize.Model {
  static init(sequelize) {
    return super.init(
      {
        id: {
          type: Sequelize.INTEGER,
          autoIncrement: true,
          primaryKey: true
        },
        unidade: {
          type: Sequelize.STRING(150),
          allowNull: false
        },
        sigla: {
          type: Sequelize.STRING,
          allowNull: false
        },
        codEmpresa: {
          type: Sequelize.STRING(20),
          allowNull: false
        },
        cnpj: {
          type: Sequelize.INTEGER(14),
          allowNull: false
        },
        razaoSocial: {
          type: Sequelize.STRING(255),
          allowNull: false
        },
        empresa: {
          type: Sequelize.STRING,
          allowNull: false
        },
        centroCusto: {
          type: Sequelize.STRING,
          allowNull: false
        },
        createdBy: {
          type: Sequelize.STRING,
          allowNull: false
        },
        modifiedBy: {
          type: Sequelize.STRING,
          allowNull: true
        },
        estadoId: {
          type: Sequelize.INTEGER
        },
        areaId: {
          type: Sequelize.INTEGER
        }
      },
      {
        sequelize,
        modelName: 'unidade'
      }
    );
  }
}

// the endpoint

const express = require('express');
const router = express.Router();
import sequelize from '../../init/sequelize';

router.post('/create', async (req, res) => {
  console.log(req.body);

  try {
    const Unidade = sequelize['MYSQL_TEST'].unidades;
    req.body.createdBy = 'foo.bar@test.com';

    const result = await Unidade.create(req.body);

    console.log('RESULT => ', result);
  } catch (err) {
    console.log('ERROR => ', err);
  }
});

export default router;
```
**To Reproduce**
1. Emulate function
2. Fire a request to the /create endpoint
3. sequelize.sync() will throw the error

## What do you expect to happen?
_Database tables are synced to the model_

## What is actually happening?
The error below is an unhandled exception but I did some tests with a try/catch around sequelize.sync() and can confirm that it's being thrown by the sync reject function.

````
TypeError: results.map is not a function
    at Query.handleSelectQuery (/home/pedro/dev/KPEyes/kpeyes-energisa/back-end/node_modules/sequelize/lib/dialects/abstract/query.js:305:24)
    at Query.formatResults (/home/pedro/dev/KPEyes/kpeyes-energisa/back-end/node_modules/sequelize/lib/dialects/mysql/query.js:132:19)
    at Utils.Promise.then.then.results (/home/pedro/dev/KPEyes/kpeyes-energisa/back-end/node_modules/sequelize/lib/dialects/mysql/query.js:80:31)
    at tryCatcher (/home/pedro/dev/KPEyes/kpeyes-energisa/back-end/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/pedro/dev/KPEyes/kpeyes-energisa/back-end/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/home/pedro/dev/KPEyes/kpeyes-energisa/back-end/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/home/pedro/dev/KPEyes/kpeyes-energisa/back-end/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/home/pedro/dev/KPEyes/kpeyes-energisa/back-end/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/home/pedro/dev/KPEyes/kpeyes-energisa/back-end/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/pedro/dev/KPEyes/kpeyes-energisa/back-end/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/pedro/dev/KPEyes/kpeyes-energisa/back-end/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/home/pedro/dev/KPEyes/kpeyes-energisa/back-end/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
````

## Environment
Dialect:
- [x] mysql
- [ ] postgres
- [ ] sqlite
- [ ] mssql
- [ ] any
Dialect **library** version: mysql2 => 1.6.1
Database version: 5.7.14
Sequelize version: 5.15.0
Node Version: 8.16.0
OS: elementary OS loki
If TypeScript related: TypeScript version: not Typescript related I think but anyway: 3.4.5
Tested with latest release:
- [ ] No
- [x] Yes, specify that version:  5.15.0

**Comment by papb** [comment]
To assist with bugs, we need you to provide a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)) to allow contributors to work on this on a timely manner. In particular, the code must be **short/minimal**. Please fix your issue making your code a real SSCCE/MCVE/reprex. Once you do, the issue will be reopened.

**Comment by fandepeng1993** [comment]
Has the problem been solved? How did you solve it? I had the same problem
![1](https://github.com/sequelize/sequelize/assets/24711462/999e79ed-bdbb-47fe-95d3-54a1355df9b8)
![222](https://github.com/sequelize/sequelize/assets/24711462/9a09f9b0-6043-4e2e-a6d5-06299fd47953)

**Comment by impuLssse** [comment]
problem is solved?
