### ISSUE TITLE
Unable to findAll with distinct on and order

### ISSUE THREAD

**Issue by Jigar-Freightwalla** [sequelize/sequelize#11342]
I have a model `Model` which has fields `type` and `date_field`. I am attempting to find all entries having distinct value of `type` , ordered descending by the `date_field` and having type value in the specified array of values.

Thus for the following input:

```
type           dateField
  a               19-8-19
  b               21-8-19
  a               21-8-19
  c               21-8-19
  d               14-8-19
```

And for type values in `[ 'a', 'b', 'c' ]`, the expected output is:

```
type           dateField
  b               21-8-19
  a               21-8-19
  c               21-8-19
```

Code:
```
Model.findAll({
                where: {
                    type: {
                        $in: typesArray
                    }
                },
                attributes: [
                    [sequelize.fn('DISTINCT ON', sequelize.col('type'))],
                    'date_field'
                ],
                order: [['type', 'DESC'], ['date_field', 'DESC']]
            })
```

Expected (Postgres) query:
```
SELECT DISTINCT ON("type") "type", "date_field" FROM "Models" AS "Model" WHERE "Model"."type" IN ('a', 'b', 'c') ORDER BY "Model"."type" DESC, "Model"."date_field" DESC;
```

**To Reproduce**
1. Define models X, Y, ...
2. Run the following
3. See error

## What do you expect to happen?
Rows with expected output as mentioned above

## What is actually happening?
Throws an error `s.replace is not a function`

Stack trace:
```
TypeError: s.replace is not a function
    at Object.removeTicks (/Users/node_modules/sequelize/lib/utils.js:403:14)
    at Object.addTicks (/Users/node_modules/sequelize/lib/utils.js:399:29)
    at Object.quoteIdentifier (/Users/node_modules/sequelize/lib/dialects/postgres/query-generator.js:853:20)
    at Object.quoteIdentifiers (/Users/node_modules/sequelize/lib/dialects/abstract/query-generator.js:938:19)
    at /Users/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1085:82
    at Array.map (native)
    at Object.selectQuery (/Users/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1067:55)
    at QueryInterface.select (/Users/node_modules/sequelize/lib/query-interface.js:669:25)
    at Model.<anonymous> (/Users/node_modules/sequelize/lib/model.js:1398:32)
    at Model.tryCatcher (/Users/node_modules/sequelize/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.module.exports.Promise._settlePromiseFromHandler (/Users/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise.module.exports.Promise._settlePromise (/Users/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise.module.exports.Promise._settlePromise0 (/Users/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise.module.exports.Promise._settlePromises (/Users/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/node_modules/sequelize/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/node_modules/sequelize/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.e.Async.drainQueues (/Users/node_modules/sequelize/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

## Environment
Dialect:
- [ ] mysql
- [x] postgres
- [ ] sqlite
- [ ] mssql
- [ ] any
Dialect **library** version: XXX
Database version: XXX
Sequelize version: 3.30.4
Node Version: 6.13.4
OS: XXX
If TypeScript related: TypeScript version: XXX
Tested with latest release:
- 

- [x] No

- [ ] Yes, specify that version: 

Note:
The sequelize [docs](https://sequelize.org/master/class/lib/model.js~Model.html#static-method-findAll) do mention that the attributes array expects a second element as "the name you want the attribute to have in the returned instance", which is not applicable in this case since we do not want the "DISTINCT ON" to be applied to an alias.

**Comment by papb** [comment]
Can you please test with latest sequelize version, so we can know if the problem was already fixed at some point?

**Comment by Jigar-Freightwalla** [comment]
@papb - Hi, unfortunately that is not a trivial task in my case since there are too many breaking changes to be able to switch to the latest sequelize version and test out the problem. Would you have links to any (dummy) sequelize project that uses the latest sequelize version ?

**Comment by callmesoul** [comment]
i use latest sequelize version,but has same promise

```
const location = ctx.model.literal(`ST_GeomFromText('POINT(113.967908 22.573543)', 4326)`);
    const distance = ctx.model.fn('ST_Distance_Sphere', ctx.model.col('location'), location)
    const query = ctx.request.query
    const page = query.page ? parseInt(query.page) : 1
    const size = query.size ? parseInt(query.size) : 12
    const where = query.where ? JSON.parse(query.where) : {}
    const offset = (page - 1) * size
    const datas = await ctx.model.Pet.findAndCountAll({
        offset,
        limit: size,
        where,
        attributes: ['id', ['distance', distance]],
        order: 'distance'
    })
```
