### ISSUE TITLE
Hook beforeBulkCreate with Bcrypt: Don't change the password with a hash

### ISSUE THREAD

**Issue by alxmcr** [sequelize/sequelize#11353]
### What are you doing?

I have a User's seeder where I'm generating multiples User's objects (name, username, password, email, and role), also I'm trying to hash passwords for every User's object.

**models/User.js**

```js
"use strict";

const bcrypt = require("bcrypt");

module.exports = (sequelize, DataTypes) => {
    const User = sequelize.define(
        "User", {
            name: {
                type: DataTypes.STRING,
                defaultValue: ""
            },
            username: {
                type: DataTypes.STRING,
                defaultValue: "",
                unique: true
            },
            password: {
                type: DataTypes.STRING,
                defaultValue: ""
            },
            email: {
                type: DataTypes.STRING,
                defaultValue: ""
            },
            role: {
                type: DataTypes.STRING,
                defaultValue: "comun"
            }
        }, {
            tableName: "User"
        }
    );
    User.associate = function(models) {
        // associations can be defined here
    };

    User.prototype.validPassword = function(password) {
        return bcrypt.compareSync(password, this.password);
    };

    User.beforeSave((user, options) => {
        const {
            password
        } = user;

        var saltRounds = 10;
        var salt = bcrypt.genSaltSync(saltRounds);
        var hash = bcrypt.hashSync(password, salt);
        user.password = hash;
    });

    User.beforeBulkCreate((users, options) => {
        for (const user of users) {
            const {
                password
            } = user;

            var saltRounds = 10;
            var salt = bcrypt.genSaltSync(saltRounds);
            var hash = bcrypt.hashSync(password, salt);
            user.password = hash;
        }
    });

    User.beforeBulkUpdate((users, options) => {
        for (const user of users) {
            const {
                password
            } = user;

            var saltRounds = 10;
            var salt = bcrypt.genSaltSync(saltRounds);
            var hash = bcrypt.hashSync(password, salt);
            user.password = hash;
        }
    });
    return User;
};
```

**seeders/20190825022226-demo-user.js**

```js
'use strict';

module.exports = {
    up: (queryInterface, Sequelize) => {
        return queryInterface.bulkInsert('User', generateUsers(10), {});
    },

    down: (queryInterface, Sequelize) => {
        return queryInterface.bulkDelete('User', null, {});
    }
};

function generateUsers(n) {
    var users = [];

    for (var i = 0; i < n; i++) {
        var user = {
            name: 'name ' + i,
            username: 'username ' + i,
            password: 'hello',
            email: `${makeid(3)}@mail.com`,
            role: `guess`,
            createdAt: new Date(),
            updatedAt: null
        }

        users.push(user);
    }

    return users;
}


/*
  Created by Jake
  Source: https://stackoverflow.com/questions/1349404/generate-random-string-characters-in-javascript
*/
function makeid(length) {
    var result = '';
    var characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    var charactersLength = characters.length;
    for (var i = 0; i < length; i++) {
        result += characters.charAt(Math.floor(Math.random() * charactersLength));
    }
    return result;
}
```

**Run npm command**

```bash
npx sequelize db:seed:all
```

### What do you expect to happen?

I want all users created by a seeder to have a **hash** generated by bcrypt as a password.

### What is actually happening?

Passwords values aren't hashes generated by bcrypt, they are **simple strings**.

```json
[
    {
        "id": 1,
        "name": "name 0",
        "username": "username 0",
        "password": "hello",
        "email": "4JU@mail.com",
        "role": "guess",
        "createdAt": "2019-08-25T03:06:25.000Z",
        "updatedAt": null
    },
    {
        "id": 2,
        "name": "name 1",
        "username": "username 1",
        "password": "hello",
        "email": "Ey9@mail.com",
        "role": "guess",
        "createdAt": "2019-08-25T03:06:25.000Z",
        "updatedAt": null
    }
]
```

### Additional context

![image](https://user-images.githubusercontent.com/8689897/63645131-9f00d680-c6c5-11e9-812c-fcf4e86fcd93.png)

### Environment

- Sequelize version: 5.15.1 
- Node.js version: 12.6.0
- Operating System: Windows 10
- Bcrypt version: 3.0.6

### How does this problem relate to dialects?

- [X] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [X] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
Hello, calling `bulkInsert` does not trigger the `beforeBulkCreate` hook, please try calling `bulkCreate` instead and let me know. Should work.

**Comment by alxmcr** [comment]
Hi @papb! Thanks for your message!

I've changed `bulkInsert `for `bulkCreate`, but unfortunately, I have another error:

`ERROR: queryInterface.bulkCreate is not a function`

This is my code modified:

```
module.exports = {
    up: (queryInterface, Sequelize) => {
        return queryInterface.bulkCreate('User', generateUsers(10), {});
    },

    down: (queryInterface, Sequelize) => {
        return queryInterface.bulkDestroy('User', null, {});
    }
};
```

Please, can you help me with this problem? I'll appreciate your help.

**Comment by papb** [comment]
You have to use the model itself instead of `queryInterface`. Import your model in the migration file and call `user.bulkCreate`

**Comment by alxmcr** [comment]
@papb I've changed `queryInterface` for `User`, but unfortunately I have another error:

`records.map is not a function`

Now, my code is:
**seeders/20190825022226-demo-user.js**

```
const models = require("../models");
const User = models.User;

module.exports = {
    up: (queryInterface, Sequelize) => {
        return User.bulkCreate('User', generateUsers(10), {});
    },

    down: (queryInterface, Sequelize) => {
        return User.bulkDestroy('User', null, {});
    }
};
```

Please, can you help me with this problem? I'll appreciate your help.

**Comment by papb** [comment]
Can you please post full stacktrace?

**Comment by alxmcr** [comment]
Of course, no problem.

```bash
> npx sequelize db:seed:all


Sequelize CLI [Node: 12.6.0, CLI: 5.5.0, ORM: 5.15.1]

Loaded configuration file "config\config.json".
Using environment "development".
== 20190825022226-demo-user: migrating =======

ERROR: records.map is not a function

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! login-passport-jwt@0.0.0 filldb: `npx sequelize db:seed:all`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the login-passport-jwt@0.0.0 filldb script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

and the npm log is:

```
9 verbose lifecycle login-passport-jwt@0.0.0~filldb: CWD: G:\login-passport-jwt
10 silly lifecycle login-passport-jwt@0.0.0~filldb: Args: [ '/d /s /c', 'npx sequelize db:seed:all' ]
11 silly lifecycle login-passport-jwt@0.0.0~filldb: Returned: code: 1  signal: null
12 info lifecycle login-passport-jwt@0.0.0~filldb: Failed to exec filldb script
13 verbose stack Error: login-passport-jwt@0.0.0 filldb: `npx sequelize db:seed:all`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:203:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:203:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid login-passport-jwt@0.0.0
```

**Comment by papb** [comment]
I was not able to reproduce... Can you create a GitHub repository that I can clone and run some command to see your problem?

**Comment by alxmcr** [comment]
Of course @papb! No problem. I'm so sorry for my delay in my response.  This [my repo](https://github.com/alxmcr/login-passport-jwt/tree/sequelize-bcrypt-v1) with SQLite configured. The branch is `sequelize-bcrypt-v1`. I have two commands: `npm run migrate` and `npm run filldb`

Please, can you help me with this problem? I'll appreciate your help.

**Comment by sushantdhiman** [comment]
I think your haven't read documentation. `User.bulkCreate('User', generateUsers(10), {});` wont work because it accepts array in first argument

https://sequelize.org/master/class/lib/model.js~Model.html#static-method-bulkCreate

Read reference on how to use a given method and adjust your code accordingly

**Comment by alxmcr** [comment]
Thanks @papb and @sushantdhiman for your help!

I resolved my problem! Yes, I wasn't passing the parameters correctly to the bulkCreate method, I'm so sorry. Now, my code is like this:

```
const models = require("../models");
const User = models.User;

module.exports = {
    up: (queryInterface, Sequelize) => {
        return User.bulkCreate(generateUsers(12), {});
    },

    down: (queryInterface, Sequelize) => {
        return User.destroy({
            where: {},
            truncate: true /* this will ignore where and truncate the table instead */
        });
    }
};
```

And It works!.

This is a screenshot from DB Browser for SQLite:

![image](https://user-images.githubusercontent.com/8689897/64065600-5b363180-cbdd-11e9-9aa3-8266147a6ab9.png)

**Passwords encrypted!** 😃

Thanks again for your help and time! Thank you! Have a nice day!
