### ISSUE TITLE
SequelizeConnectionError: authentication failed for user "admin": too many failed login attempts

### ISSUE THREAD

**Issue by ubreddy** [sequelize/sequelize#11371]
## Issue Description
Occasionally Sequeliize starts throwing loging errors on postgre connections...
the same user id and password work when connected again from a different machine...

SequelizeConnectionError: authentication failed for user "appserveruser": too many failed login attempts

### What are you doing?

```js
const sequelize = new Sequelize(config.database.name, config.database.username, config.database.password, {
            host: config.database.host,
            dialect: config.database.dialect,
            operatorsAliases: false,
            logging: config.database.loggingEnabled,
            dialectOptions: {
                ssl: config.database.ssl != undefined ? JSON.parse(config.database.ssl) : true
            },
            pool: {
                max: 10,
                min: 0,
                acquire: 40000,
                idle: 10000
            },
            define: {
                underscored: true,
                freezeTableName: true,
                schema: config.database.schemaName
            },
        });

```

### What do you expect to happen?

Connection to work all the time.

### What is actually happening?

Errors as above.

```
Unhandled Rejection at: SequelizeConnectionError: authentication failed for user "admin": too many failed login attempts
    at connection.connect.err (/home/node/app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:182:24)
    at Connection.connectingErrorHandler (/home/node/app/node_modules/pg/lib/client.js:191:14)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at TLSSocket.<anonymous> (/home/node/app/node_modules/pg/lib/connection.js:126:12)

```

### Environment

- Sequelize version: 5.8.12
- Node.js version: 8.12 
- Operating System: win 10

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ubreddy** [comment]
This issue occurs when there is a connection limit set on the user id and the poolsize exhausts that limit.
