### ISSUE TITLE
Issue on query-generator upsertQuery

### ISSUE THREAD

**Issue by charles-dejager** [sequelize/sequelize#11427]
## Issue Description
In query-generator.js on line 457 the test for clauses.length returns true, but the clauses element is an array with the first element being a null.
`
   if (clauses.length === 0) {
      throw new Error('Primary Key or Unique key should be passed to upsert query');
    } else {
`

  console.log of clauses gives [null, {...}]

### What are you doing?
`
VariantData
            .upsert({
                  values: values,
                  field: variantData.field,
                  variant_uuid: variant_uuid,
                },
                {
                  where: {
                    variant_uuid: variant_uuid,
                    field: variantData.field,
                  },
                })
`

### What do you expect to happen?
  The else clause should first check if the clause element is an Object or if it is null
`
if (clauses.length === 0) {
      throw new Error('Primary Key or Unique key should be passed to upsert query');
    } else {
      // Search for primary key attribute in clauses -- Model can have two separate unique keys
      for (const key in clauses) {
        if (clauses[key] === null || clauses[key].constructor !== Object) {
          break;
        }
        ...
`

### What is actually happening?

An error is being generated 

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at MSSQLQueryGenerator.upsertQuery (/Users/djagercd/dev/mm_edds/server/node_modules/sequelize/lib/dialects/mssql/query-generator.js:463:29)
    at QueryInterface.upsert (/Users/djagercd/dev/mm_edds/server/node_modules/sequelize/lib/query-interface.js:929:37)
    at Promise.try.then (/Users/djagercd/dev/mm_edds/server/node_modules/sequelize/lib/model.js:2471:38)
    at bound (domain.js:400:14)
    at runBound (domain.js:413:12)
    at tryCatcher (/Users/djagercd/dev/mm_edds/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/djagercd/dev/mm_edds/server/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/Users/djagercd/dev/mm_edds/server/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/Users/djagercd/dev/mm_edds/server/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/Users/djagercd/dev/mm_edds/server/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/Users/djagercd/dev/mm_edds/server/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/djagercd/dev/mm_edds/server/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/djagercd/dev/mm_edds/server/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/djagercd/dev/mm_edds/server/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (timers.js:637:19)
    at process.topLevelDomainCallback (domain.js:126:23)
(node:7354) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.

```

### Environment

- Sequelize version: 6.0.0 
- Node.js version: 11.10.0 
- Operating System: MacOS

### How does this problem relate to dialects?

- [X] I think this problem happens regardless of the dialect.
- [X] I don't know, I was using mssql (5.1.0) and tedious (5.0.3)

### Would you be willing to resolve this issue by submitting a Pull Request?

- [X] Yes, I have the time but I don't know how to start, I would need guidance.

**Comment by papb** [comment]
Hello, thanks for the report! You have posted a code snippet that shows the problem but is not entirely self-contained (i.e. I can't just copy-paste it and run it). Please provide a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)) to allow contributors to work on this on a timely manner.

> Sequelize version: 6.0.0

Please try v5 instead, v6 is still alpha.
