### ISSUE TITLE
error TypeError: include.model.getTableName is not a function

### ISSUE THREAD

**Issue by nitishkumarnitc** [sequelize/sequelize#11575]
Issue Description
    error TypeError: include.model.getTableName is not a function
### What are you doing?
    I am calling Campaign.getCampaignByCampaignId(1) . 

   My code is something like this. 

'use strict';
let CampaignImages = require('./campaignimages');
module.exports = (sequelize, DataTypes) => {
    const Campaign = sequelize.define('Campaign', {
        name: {
            type: DataTypes.STRING,
            unique: true,
            allowNull: false,
        },
        isActive: {
            type: DataTypes.BOOLEAN,
            defaultValue: false,
            allowNull: true,
        },
        templateId: {
            type: DataTypes.NUMBER,
            defaultValue: 1
        },

    }, {
        classMethods: {

        }
    });

    Campaign.associate = function (models) {
        // associations can be defined here
        Campaign.hasMany(models.CampaignImages, {
            foreignKey: 'campaignId',
            as: 'images'
        })
    };

    
    Campaign.getCampaignByCampaignId = function (campaignId) {
        console.log("Campaign.getCampaignByCampaignId ", campaignId)
        return this.findOne({
            where: {
                id: campaignId
            },
            attributes: ['name', 'isActive', 'templateId'],
            include: [{model: CampaignImages, as: 'images', attributes: ['url', 'position']}]
        })
    }

    return Campaign;
};

I am getting the following error -> 

Error in getting Campaign.getCampaignByCampaignId , error TypeError: include.model.getTableName is not a function
    at Function._validateIncludedElement (/Users/nitish/Documents/campaigns/node_modules/sequelize/lib/model.js:586:30)
    at options.include.options.include.map.include (/Users/nitish/Documents/campaigns/node_modules/sequelize/lib/model.js:516:37)
    at Array.map (<anonymous>)
    at Function._validateIncludedElements (/Users/nitish/Documents/campaigns/node_modules/sequelize/lib/model.js:511:39)
    at Promise.try.then.then (/Users/nitish/Documents/campaigns/node_modules/sequelize/lib/model.js:1725:14)
    at tryCatcher (/Users/nitish/Documents/campaigns/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/nitish/Documents/campaigns/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/nitish/Documents/campaigns/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/nitish/Documents/campaigns/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/nitish/Documents/campaigns/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/nitish/Documents/campaigns/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/nitish/Documents/campaigns/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/nitish/Documents/campaigns/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/nitish/Documents/campaigns/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

**Comment by papb** [comment]
Sequelize requires you to [file new issues](https://github.com/sequelize/sequelize/issues/new/choose) with specific [issue templates](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

When a bug is reported, we really need a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)) to be able to easily reproduce it. Without this, we simply can't help you in a timely manner. I suggest using the [sequelize-sscce repository](https://github.com/papb/sequelize-sscce).

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [StackOverflow](https://stackoverflow.com/) (using the [sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js)) or on [Slack](https://sequelize.slack.com).
