### ISSUE TITLE
Could not catch error in try catch block

### ISSUE THREAD

**Issue by sugumarv** [sequelize/sequelize#11632]
```
    try{
        const connect_to_database = async () =>{
            const sequelize = new Sequelize('testing','sugumar','mypassward',{
                host:'127.0.0.1',
                dialect:'mysql'
            })
            await sequelize.authenticate()
        }
        connect_to_database()
    }catch(e){

    }
```

In the above I have given the wrong password, I expect the the catch block to run, but instead I get the error in terminal
```

(node:25701) UnhandledPromiseRejectionWarning: SequelizeAccessDeniedError: Access denied for user 'sugumar'@'localhost' (using password: YES)
at Promise.tap.then.catch.err (/home/user/Desktop/sugumar/testing/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:125:19)
at tryCatcher (/home/user/Desktop/sugumar/testing/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/home/user/Desktop/sugumar/testing/node_modules/bluebird/js/release/promise.js:547:31)
```

Posted the code also in 

https://stackoverflow.com/questions/58659113/try-and-catch-does-not-catch-promise-errors/58659577?noredirect=1#comment103622517_58659577

**Comment by sugumarv** [comment]
Not an issue
