### ISSUE TITLE
SequelizeDatabaseError: operator does not exist: integer ~ unknown

### ISSUE THREAD

**Issue by prudhvichitturi** [sequelize/sequelize#11668]
We are trying to migrate from mysql to postgresql. We are using the regex for id but that is not working as it works with mysql.

usage:(resolvers.js)

`Query: {
database: (root, {id, gId}, {db, user}) => {
  console.log('user is', user);
  let conditions = computeIdAndgId(id, gId);
  return db.Database.findOne({
    where: {
      [Op.and] : [{
        id: {
          [Op.notIRegexp]: '[0-9]'
        }
      }, ...conditions],
      tenant: user.tenant
    },
    raw: true
  });
}
}`

ended up with the following error

`SequelizeDatabaseError: operator does not exist: integer ~ unknown
at Query.formatError (/node_modules/sequelize/lib/dialects/postgres/query.js:354:16)
at query.catch.err (/node_modules/sequelize/lib/dialects/postgres/query.js:71:18)
at tryCatcher (/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/node_modules/bluebird/js/release/promise.js:547:31)
at Promise._settlePromise (/node_modules/bluebird/js/release/promise.js:604:18)
at Promise._settlePromise0 (/node_modules/bluebird/js/release/promise.js:649:10)
at Promise._settlePromises (/node_modules/bluebird/js/release/promise.js:725:18)
at _drainQueueStep (/node_modules/bluebird/js/release/async.js:93:12)
at _drainQueue (/node_modules/bluebird/js/release/async.js:86:9)
at Async._drainQueues (//node_modules/bluebird/js/release/async.js:102:5)
at Immediate.Async.drainQueues (/node_modules/bluebird/js/release/async.js:15:14)
at runCallback (timers.js:789:20)
at tryOnImmediate (timers.js:751:5)
at processImmediate [as _immediateCallback] (timers.js:722:5)
These are the sql queries formed for different databases through sequelize ORM:`

MYSQL Query (working):
`` SELECT `id`, `name`, `username`, `password`, `type` FROM `database` AS `database` WHERE (`database`.`id` REGEXP '[0-9]' AND `database`.`id` = '1') AND `database`.`tenant` = 1 LIMIT 1;``

POSTGRESQL Query (not-working):

` SELECT "id", "name", "username", "password", "type" FROM "database" AS "database" WHERE ("database"."id" ~ '[0-9]' AND "database"."id" = '1') AND "database"."tenant" = 1 LIMIT 1`

**Comment by papb** [comment]
Sequelize requires you to [file new issues](https://github.com/sequelize/sequelize/issues/new/choose) with specific [issue templates](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE). This issue will be closed for not following the issue template. Take a look in our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues).

When a bug is reported, we really need a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)) to be able to easily reproduce it. Without this, we simply can't help you in a timely manner. I suggest using the [sequelize-sscce repository](https://github.com/papb/sequelize-sscce).

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [StackOverflow](https://stackoverflow.com/) (using the [sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js)) or on [Slack](https://sequelize.slack.com).
