### ISSUE TITLE
electron Error: Please install sqlite3 package manually

### ISSUE THREAD

**Issue by Siffre** [sequelize/sequelize#11677]
WARNING  Compiled with 4 warnings                                                                                                                     2:02:41 PM

 warning  in ./node_modules/sequelize/lib/sequelize.js

Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/sequelize/lib/dialects/abstract/connection-manager.js

Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/sequelize/lib/dialects/abstract/connection-manager.js

Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/any-promise/register.js

Critical dependency: the request of a dependency is an expression

  File                      Size                     Gzipped

  dist_electron/index.js    4059.60 KiB              769.57 KiB

  Images and other types of assets omitted.

 INFO  Launching Electron...
Debugger listening on ws://127.0.0.1:50444/353bb2a0-c895-46bc-9026-196f0ef1f3a1
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
App threw an error during load
Error: Please install sqlite3 package manually
    at ConnectionManager._loadDialectModule (webpack:///./node_modules/sequelize/lib/dialects/abstract/connection-manager.js?:81:15)
    at new ConnectionManager (webpack:///./node_modules/sequelize/lib/dialects/sqlite/connection-manager.js?:22:21)
    at new SqliteDialect (webpack:///./node_modules/sequelize/lib/dialects/sqlite/index.js?:14:30)
    at new Sequelize (webpack:///./node_modules/sequelize/lib/sequelize.js?:324:20)
    at eval (webpack:///./src/background.js?:17:19)
    at Module../src/background.js (/Users/siffre/Documents/qbspy/qbDesktop/dist_electron/index.js:6333:1)
    at __webpack_require__ (/Users/siffre/Documents/qbspy/qbDesktop/dist_electron/index.js:20:30)
    at eval (webpack:///multi_./src/background.js?:1:18)
    at Object.0 (/Users/siffre/Documents/qbspy/qbDesktop/dist_electron/index.js:6356:1)
    at __webpack_require__ (/Users/siffre/Documents/qbspy/qbDesktop/dist_electron/index.js:20:30)
    at /Users/siffre/Documents/qbspy/qbDesktop/dist_electron/index.js:84:18
    at Object.<anonymous> (/Users/siffre/Documents/qbspy/qbDesktop/dist_electron/index.js:87:10)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at loadApplicationPackage (/Users/siffre/Documents/qbspy/qbDesktop/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.09:16)
    at Object.<anonymous> (/Users/siffre/Documents//qbspy/qbDesktop/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:1)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
(node:14322) [SEQUELIZE0002] DeprecationWarning: The logging-option should be either a function or false. Default: console.log
(node:14322) [SEQUELIZE0002] DeprecationWarning: The logging-option should be either a function or false. Default: console.log

electron@7.1.1    sqlite3@3.4.1    sequelize@5.21.2

I don't how to solve it, please help me, thank you everyone!

**Comment by Siffre** [comment]
electron and sqlite3 are well, but sequelize is not

**Comment by Siffre** [comment]
I solve it via :

import Sequelize from "sequelize"

const sqlite3 = require('sqlite3').verbose()


const seqObj = new Sequelize('database', null, null, {
  pool: {
    max: 5,
    min: 0,
    acquire: 30000,
    idle: 10000
  },
  // 手动配置sqlite3，默认的不会被识别
  dialectModule: sqlite3,
  dialect: 'sqlite',
  storage: './database.sqlite'
})

**Comment by papb** [comment]
Possibly related: #13169

**Comment by ihewro** [comment]
> Possibly related: #13169

This problem is easy to reproduce, as long as you use webpack and don't put sequenize in the external variable

**Comment by ihewro** [comment]
> I solve it via :
> 
> import Sequelize from "sequelize"
> 
> const sqlite3 = require('sqlite3').verbose()
> 
> const seqObj = new Sequelize('database', null, null, {
> pool: {
> max: 5,
> min: 0,
> acquire: 30000,
> idle: 10000
> },
> // 手动配置sqlite3，默认的不会被识别
> dialectModule: sqlite3,
> dialect: 'sqlite',
> storage: './database.sqlite'
> })

Hi, how do use sequelize in the render process, this method just make sense in the main process

**Comment by ldoubil** [comment]
> 我通过以下方式解决它：
> 
> 从“续集”导入续集
> 
> const sqlite3 = require（'sqlite3'）.verbose（）
> 
> const seqObj = new Sequelize（'database'， null， null， { pool： { max： 5， min： 0， acquire： 30000， idle： 10000 }， // 手动配置 sqlite3，默认的不会被识别 dialectModule： sqlite3， dialect： 'sqlite'， storage： './database.sqlite' })

谢谢你的方法，管用！！！
