### ISSUE TITLE
'Converting circular structure to JSON' when sync() is called (5.21.2)

### ISSUE THREAD

**Issue by z16844** [sequelize/sequelize#11706]
### What are you doing?

To test creating DB schemas, I called sync(). 
And, I got the message "Unhandled rejection TypeError: Converting circular structure to JSON" regardless 'force' is 'true' or 'false'

* DB connection and Model definitions 
```js
const Sequelize = require('sequelize');
const sequelize = new Sequelize(process.env.DB_NAME, process.env.DB_USER, process.env.DB_PASS,{
  host: process.env.DB_HOST,
  dialect: 'mariadb', // I just tried to put 'mysql' with mariadb, and it showed same output with warning messages.
  dialectOptions: {
    collate: 'utf8mb4_general_ci',
    useUTC: false, 
    timezone: 'Etc/GMT0'
  }
})

module.exports = {
  sequelize: sequelize,
  User: sequelize.define('user', {
    name: Sequelize.STRING
  })
}
```

* The code calling sync()
```js
sequelize.sync({force: false })
            .then(done)
            .catch((err) => { throw err })
````

### What do you expect to happen?

It should created a table with fields

### What is actually happening?

* Stack Trace with 'dialect: mariadb'
```
Executing (default): CREATE TABLE IF NOT EXISTS `users` (`id` INTEGER NOT NULL auto_increment , `name` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `users`
Unhandled rejection TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Sequelize'
    |     property 'dialect' -> object with constructor 'MariadbDialect'
    --- property 'sequelize' closes the circle
    at JSON.stringify (<anonymous>)
    at ./node_modules/mocha/lib/runnable.js:422:64
    at tryCatcher (./node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (./node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (./node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (./node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (./node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (./node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (./node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (./node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (./node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
```
* Stack Trace with 'dialect: mysql'
```
Executing (default): CREATE TABLE IF NOT EXISTS `users` (`id` INTEGER NOT NULL auto_increment , `name` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `users`
Unhandled rejection TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Sequelize'
    |     property 'dialect' -> object with constructor 'MysqlDialect'
    --- property 'sequelize' closes the circle
    at JSON.stringify (<anonymous>)
    at ./node_modules/mocha/lib/runnable.js:422:64
    at tryCatcher (./node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (./node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (./node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (./node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (./node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (./node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (./node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (./node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (./node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:439:21)
```

### Environment

- Sequelize version: 5.21.2 
- Node.js version: 12.12.0
- Operating System: macOS Catalina 10.15.1
- DB : Ver 15.1 Distrib 10.4.6-MariaDB, for osx10.15
- NPM : 6.12.0

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by galenyuan** [comment]
any workaround?

**Comment by Swadish** [comment]
I had this problem while trying to call destructuring on an entity, for example:

```typescript
console.log(...commission);
```

**Comment by jmen95** [comment]
I have the same problem.

**Comment by Ch3rlO** [comment]
As @Swadish says This problem shows when I try to destructure an object something like that
```js
const fullEmployee = (user, lang = 'ar') => ({
  ...user,
  location: lang === 'ar' ? user.location.name : user.location.name_en,
  skills: user.employee.skills.map(({ id, name }) => ({ id, name })),
})
```

So what I did to fix it 

```js
const fullEmployee = (user, lang = 'ar') => ({
  ...user.dataValues,
  location: lang === 'ar' ? user.location.name : user.location.name_en,
  skills: user.employee.skills.map(({ id, name }) => ({ id, name })),
})
```

**Comment by jonathas** [comment]
This error happens for me only when I try to print the result of sequelize.sync()
The response there contains a circular structure

**Comment by iamgabrielsoft** [comment]
The best way to solve this issue is to use .then method. it solve mine!

const _dev = await Dev.findOne({ 
            where: { username },   
            logging: false
        }).then(res => {
            return res.dataValues; 
        
        }).catch(err => {
            console.log('err', err)
            return err
        })
   
        return _dev
        
    } catch (error) {
        console.log(error)
    }


@iamgabrielsoft

**Comment by GolgothaAksanti** [comment]
> I had this problem while trying to call destructuring on a model, for example:
> 
> ```ts
> console.log(...model);
> ```
> 
> Resolved it removing the `...`

this worked for me. Thanks.

**Comment by gaiousantonio0909** [comment]
You can try this 
```javascript
{ ...(blog.get({ plain: true })), user: findUser.data }
```
