### ISSUE TITLE
Unrecognized datatype for attribute XXX

### ISSUE THREAD

**Issue by fotock** [sequelize/sequelize#11737]
I defined a shortcut in an another .js for common STRING fields:
```js
    safeString: {
        type: Sequelize.DataTypes.STRING,
        defaultValue: '',
        validate: {
            not: /[';%&\-\(\)]/gui
        }
    },
```
and then used it in model definitions:
```js
const util = require('../lib/utils')
module.exports = (sequelize, DataTypes) => {
    const YuSuan = sequelize.define('YuSuan', {
        id: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true // 自增字段必须要有!
        },
        daqu: util.safeString,
       //...
```

it gives the following error:
```log
Error: Unrecognized datatype for attribute "YuSuan.daqu"
    at rawAttributes._.mapValues (/web/www/vendor-budget/node_modules/sequelize/lib/model.js:1005:15)
    at /web/www/vendor-budget/node_modules/lodash/lodash.js:13401:38
```

**Comment by sushantdhiman** [comment]
```daqu: util.safeString``` doesn't look like a valid Sequelize type to me

**Comment by papb** [comment]
Hi @fotock, interesting idea, to be honest I would have guessed this should work, can you please provide a [sequelize-sscce](https://github.com/papb/sequelize-sscce) for this? Thanks
