### ISSUE TITLE
toString being added as an additional attribute although it is not part of the model

### ISSUE THREAD

**Issue by vineethr007** [sequelize/sequelize#11750]
### What are you doing?

Trying to do an upsert operation in MSSQL dialect.

In models.js
//Customer
const Customer = sequelize.define("customer", {
  id: {
    primaryKey: true,
    type: Sequelize.UUID
  },
  customer_id: Sequelize.STRING,
  customer_name: Sequelize.STRING,
  account_id: Sequelize.STRING,
  is_active: Sequelize.BOOLEAN
});

In api.js
....
...
updateCustomerList: async(customer_list) => {
    try {
      const customer_records=await Promise.all(customer_list.map(item => {
        models.Customer.upsert(item)
      }))
      return { customers: customer_records };
    } catch (err) {
      return { err: "ERROR: " + err };
    }

### What do you expect to happen?

No error

### What is actually happening?

An error is thrown.

Output here
```

Unhandled rejection Error: Invalid value [Function: toString]
    at Object.escape (D:\Projects\abc\node_modules\sequelize\lib\sql-string.js:65:11)
    at MSSQLQueryGenerator.escape (D:\Projects\abc\node_modules\sequelize\lib\dialects\abstract\query-generator.js:986:22)
    at updateKeys.filter.map.key (D:\Projects\abc\node_modules\sequelize\lib\dialects\mssql\query-generator.js:480:28)
    at Array.map (<anonymous>)
    at MSSQLQueryGenerator.upsertQuery (D:\Projects\abc\node_modules\sequelize\lib\dialects\mssql\query-generator.js:479:8)
    at QueryInterface.upsert (D:\Projects\abc\node_modules\sequelize\lib\query-interface.js:948:37)
    at Promise.try.then (D:\Projects\abc\node_modules\sequelize\lib\model.js:2491:38)
From previous event:
    at Promise.try.then (D:\Projects\abc\node_modules\sequelize\lib\model.js:2490:10)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Function.upsert (D:\Projects\abc\node_modules\sequelize\lib\model.js:2461:8)
    at Promise.all.customer_list.map.item (D:\Projects\abc\api.js:41:25)
    at Array.map (<anonymous>)
    at Object.updateCustomerList_SQL (D:\Projects\abc\api.js:40:62)
    at syncDB (D:\Projects\abc\index.js:215:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Additional context

Saw failure at 
  if (!options.fields) {
      options.fields = Object.keys(instance._changed);
    }

Dirty fix done:

D:\Projects\abc\node_modules\sequelize\lib\model.js

Line 3739

  changed(key, value) {
    if (key && **key!=="toString"**) {
      if (value !== undefined) {
....
.....

### Environment

- Sequelize version: 5.21.2
- Node.js version: 10.15.3
- Operating System: Windows 10
- If TypeScript related: TypeScript version: NA

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [X ] I think this problem happens only for the following dialect(s): MSSQL
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ X] No, I don't have the time and I wouldn't even know how to start.

**Comment by papb** [comment]
You have posted a code snippet that shows the problem but is not entirely self-contained (i.e. I can't just copy-paste it and run it). Please provide a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)) to allow contributors to work on this on a timely manner. I suggest using the [sequelize-sscce repository](https://github.com/papb/sequelize-sscce) for this.

Also please [improve formatting](https://guides.github.com/features/mastering-markdown/) in your post.
