### ISSUE TITLE
Error generating query for Many-To-One and Many-To-Many Linking to same table

### ISSUE THREAD

**Issue by DeliciousJaffa** [sequelize/sequelize#11773]
Using sequelize 5.21.3 with MariaDB, I seem to be unable to have two includes of the same table, one being Many to One (Event Owner), the other being Many to Many (Event Attendees)
This previously worked in 4.44.0 which was then upgraded to what must have been an incorrectly released v5 version "6.0.0" on the 5th of July 2019 where it continued to work.
I'm now trying to go back to an actual version (v5.21.3) but I'm running into the following error below:
```
Unhandled rejection TypeError: Cannot read property 'map' of undefined,
    at MySQLQueryGenerator.generateThroughJoin (/usr/src/app/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1734:50),
    at MySQLQueryGenerator.generateInclude (/usr/src/app/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1540:24),
    at MySQLQueryGenerator.selectQuery (/usr/src/app/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1183:34),
    at QueryInterface.select (/usr/src/app/node_modules/sequelize/lib/query-interface.js:1122:27),
    at /usr/src/app/node_modules/sequelize/lib/model.js:1757:34,
    at processImmediate (internal/timers.js:439:21),
    at process.topLevelDomainCallback (domain.js:130:23),
From previous event:,
    at Function.findAll (/usr/src/app/node_modules/sequelize/lib/model.js:1755:8),
    at Function.findOne (/usr/src/app/node_modules/sequelize/lib/model.js:1924:17),
    at Function.findByPk (/usr/src/app/node_modules/sequelize/lib/model.js:1888:17),
    at /usr/src/app/routes/event.js:26:22,
    at paramCallback (/usr/src/app/node_modules/express/lib/router/index.js:404:7),
    at param (/usr/src/app/node_modules/express/lib/router/index.js:384:5),
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:410:3),
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10),
    at Function.handle (/usr/src/app/node_modules/express/lib/router/index.js:174:3),
    at router (/usr/src/app/node_modules/express/lib/router/index.js:47:12),
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5),
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13),
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7,
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12),
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10),
    at /usr/src/app/node_modules/express/lib/router/index.js:635:15,
    at next (/usr/src/app/node_modules/express/lib/router/index.js:260:14),
    at Function.handle (/usr/src/app/node_modules/express/lib/router/index.js:174:3),
    at router (/usr/src/app/node_modules/express/lib/router/index.js:47:12),
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5),
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13),
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7,
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12),
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10),
    at /usr/src/app/app.js:73:5,
```
Query:
```js
models.Event.findByPk(eventID, {
    include: [
        {model: models.User, as: "Attendees"},
        {model: models.User, as: "Owner"}
    ]
}
```
Alternative query with same error:
```js
models.Event.findByPk(eventID, {
    include: ["Attendees", "Owner"]
}
```

Defines:
User:
```js
sequelize.define("User",{
    intID: {
        type: DataTypes.INTEGER.UNSIGNED,
        primaryKey: true,
        autoIncrement: true
    },
    steamID: {
        type: DataTypes.BIGINT.UNSIGNED,
        unique: true
    },
    discordID: {
        type: DataTypes.BIGINT.UNSIGNED,
        unique: true
    },
    discordAvatar: {
        type: DataTypes.STRING,
        allowNull: true
    },
    name: {
        type: DataTypes.STRING,
        defaultValue: "Unknown Player",
        allowNull: false
    },
    member: {
        type: DataTypes.BOOLEAN,
        defaultValue: false,
        allowNull: false
    },
    admin: {
        type: DataTypes.BOOLEAN,
        defaultValue: false,
        allowNull: false
    },
    active: {
        type: DataTypes.BOOLEAN,
        defaultValue: true
    },
    email: {
        type: DataTypes.STRING,
        validate: {isEmail: true},
        allowNull: true
    },
    banned: {
        type: DataTypes.BOOLEAN,
        defaultValue: false
    }
},{
    defaultScope: {
        include: "DiscordUser"
    },
    getterMethods: {
        discordAvatarURL() {
            if (this.DiscordUser) return this.DiscordUser.discordAvatarURL;
            if (this.discordAvatar && this.discordID) return `https://cdn.discordapp.com/avatars/${this.discordID}/${this.discordAvatar}.png`;
            return `https://cdn.discordapp.com/embed/avatars/${this.intID % 5}.png`;
        },
        discordMention() {
            if (this.discordID) return `<@${this.discordID}>`;
            return null;
        },
        discordMentionOrName() {
            if (this.discordID) return `<@${this.discordID}>`;
            return this.name;
        },
        steamProfileURL() {
            if (this.steamID) return `https://steamcommunity.com/profiles/${this.steamID}`;
            return null;
        }
    }
});
```
Event:
```js
sequelize.define("Event",{
    id: {
        type: DataTypes.INTEGER.UNSIGNED,
        primaryKey: true,
        autoIncrement: true
    },
    owner: {
        type: DataTypes.INTEGER.UNSIGNED,
        allowNull: false
    },
    name: {
        type: DataTypes.STRING,
        defaultValue: "Unnamed Operation",
        allowNull: false
    },
    description: {
        type: DataTypes.TEXT,
        allowNull: true
    },
    map: {
        type: DataTypes.STRING,
        allowNull: true
    },
    time: {
        type: DataTypes.DATE,
        allowNull: true
    },
    missionKey: {
        type: DataTypes.UUID,
        defaultValue: DataTypes.UUIDV4,
        allowNull: false
    },
    publish: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
        defaultValue: false
    },
    discordMessage: {
        type: DataTypes.BIGINT.UNSIGNED,
        allowNull: true
    },
    imageType: {
        type: DataTypes.STRING
    },
    missionUploaded: {
        type: DataTypes.DATE
    }
},{
    getterMethods: {
        slug() {
            if (this.name) return `${this.id}-${slugify(this.name)}`;
            return this.id.toString();
        },
        image() {
            if (this.imageType) return `https://s3-${config.AWS.REGION}.amazonaws.com/${config.AWS.BUCKET}/event/${this.id}/image.${this.imageType}`;
            return null;
        },
        missionName() {
            if (this.map && this.missionUploaded) return `nut_e${this.id}.${this.map}.pbo`;
            return null;
        }
    }
});
```
EventAttendee:
```js
sequelize.define("EventAttendee",{
    attending: {
        type: DataTypes.TINYINT.UNSIGNED,
        defaultValue: 0,
        allowNull: false
    },
    attended: {
        type: DataTypes.BOOLEAN,
        defaultValue: 0,
        allowNull: false,
    }
});
```

Assocation defines:
```js
Event.belongsToMany(User,{
    as: "Attendees",
    through: EventAttendee,
    foreignKey: 'event',
    otherKey: 'user'
});
User.belongsToMany(Event,{
    through: EventAttendee,
    foreignKey: 'user',
    otherKey: 'event'
});
User.hasMany(Event,{
    foreignKey: "owner",
    sourceKey: "intID",
    onDelete: "RESTRICT"
});
Event.belongsTo(User,{
    as: "Owner",
    targetKey: "intID",
    foreignKey: "owner"
});
```

**Comment by DeliciousJaffa** [comment]
Apologies for the lack of formatting/template, the issue templates did not show after going through GitHub's authentication flow for some reason.

**Comment by DeliciousJaffa** [comment]
Resolved via changing
```js
models.Event.findByPk(eventID, {
    include: [
        {model: models.User, as: "Attendees"},
        {model: models.User, as: "Owner"}
    ]
}
```
to
```js
models.Event.findByPk(eventID, {
    include: [
        {model: models.User, as: "Owner"},
        {model: models.User, as: "Attendees", through: "EventAttendee"}
    ]
}
```
