### ISSUE TITLE
SequelizeConnectionError

### ISSUE THREAD

**Issue by uteegull** [sequelize/sequelize#11797]
App started on port 9000
This error occured ConnectionError [SequelizeConnectionError]: password authentication failed for user "postgres"
    at F:\authsystem\node_modules\sequelize\lib\dialects\postgres\connection-manager.js:182:24
    at Connection.connectingErrorHandler (F:\authsystem\node_modules\pg\lib\client.js:194:14)
    at Connection.emit (events.js:210:5)
    at Socket.<anonymous> (F:\authsystem\node_modules\pg\lib\connection.js:128:12)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  name: 'SequelizeConnectionError',
  parent: error: password authentication failed for user "postgres"
      at Connection.parseE (F:\authsystem\node_modules\pg\lib\connection.js:604:13)
      at Connection.parseMessage (F:\authsystem\node_modules\pg\lib\connection.js:403:19)
      at Socket.<anonymous> (F:\authsystem\node_modules\pg\lib\connection.js:123:22)
      at Socket.emit (events.js:210:5)
      at addChunk (_stream_readable.js:309:12)
      at readableAddChunk (_stream_readable.js:290:11)
      at Socket.Readable.push (_stream_readable.js:224:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
    name: 'error',
    length: 104,
    severity: 'FATAL',
    code: '28P01',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'auth.c',
    line: '333',
    routine: 'auth_failed'
  },
  original: error: password authentication failed for user "postgres"
      at Connection.parseE (F:\authsystem\node_modules\pg\lib\connection.js:604:13)
      at Connection.parseMessage (F:\authsystem\node_modules\pg\lib\connection.js:403:19)
      at Socket.<anonymous> (F:\authsystem\node_modules\pg\lib\connection.js:123:22)
      at Socket.emit (events.js:210:5)
      at addChunk (_stream_readable.js:309:12)
      at readableAddChunk (_stream_readable.js:290:11)
      at Socket.Readable.push (_stream_readable.js:224:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
    name: 'error',
    length: 104,
    severity: 'FATAL',
    code: '28P01',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'auth.c',
    line: '333',
    routine: 'auth_failed'
  }
}

this is the errror i am facing.
my connection string
var sequelize = new Sequelize("postgres://postgres:postgres@localhost/authsystem");

**Comment by papb** [comment]
Sequelize requires you to [file new issues](https://github.com/sequelize/sequelize/issues/new/choose) with specific [issue templates](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE). This issue will be closed for not following the issue template. Take a look in our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues).

When a bug is reported, we really need a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)) to be able to easily reproduce it. Without this, we simply can't help you in a timely manner. I suggest using the [sequelize-sscce repository](https://github.com/papb/sequelize-sscce).

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [StackOverflow](https://stackoverflow.com/) (using the [sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js)) or on [Slack](https://sequelize.slack.com).
