### ISSUE TITLE
Provide guidance on how to avoid connection issues with Amazon infrastructure (TimeoutError: ResourceRequest timed out)

### ISSUE THREAD

**Issue by papb** [sequelize/sequelize#11835]
There is a very very long issue (#7884) about issues when connecting to Amazon infrastructure.

Once, [in a comment](https://github.com/sequelize/sequelize/issues/7884#issuecomment-339564687), @sushantdhiman suggested writing some documentation guidance on how to resolve this issue.

So it would be great to have somewhere in our docs some instructions to help people overcome this.

I believe all the necessary information can be found in #7884, but it is certainly very messy right now.

**Comment by felipsmartins** [comment]
same here:

```
ResourceRequest timed out","stack":"TimeoutError: ResourceRequest timed out\n    at ResourceRequest._fireTimeout (/app/node_modules/generic-pool/lib/ResourceRequest.js:62:17)
  at Timeout.bound [as _onTimeout] (/app/node_modules/generic-pool/lib/ResourceRequest.js:8:15)
  at ontimeout (timers.js:469:11)\n    at tryOnTimeout (timers.js:304:5)\n    at Timer.listOnTimeout (timers.js:264:5)
``` 

```
(node:37) UnhandledPromiseRejectionWarning: 
Unhandled promise rejection (rejection id: 150):
  TimeoutError: ResourceRequest timed out
```
