### ISSUE TITLE
Sequelize  Nestjs Postgresql port issue

### ISSUE THREAD

**Issue by SOHELAHMED7** [sequelize/sequelize#11880]
## Issue Description

While following the guide (https://docs.nestjs.com/recipes/sql-sequelize) for postgresql database (https://dev.to/nedsoft/getting-started-with-sequelize-and-postgres-emp), I kept `port` 3306 and got below error

```ts
import { Sequelize } from 'sequelize-typescript';
import { Cat } from '../src/app/seqdatabase_module/cat.entity';

export const databaseProviders = [
  {
    provide: 'SEQUELIZE',
    useFactory: async () => {
      const sequelize = new Sequelize({
        dialect: 'postgres',
        host: 'localhost',
        port: 3306,
        username: '--',
        password: '--',
        database: 'nestjs'
      });
      sequelize.addModels([Cat]);
      await sequelize.sync();
      return sequelize;
    }
  }
];

```

```
node_modules/pg/lib/connection.js:124
      var eventName = msg.name === 'error' ? 'errorMessage' : msg.name
                          ^
TypeError: Cannot read property 'name' of undefined
    at Socket.<anonymous> (node_modules/pg/lib/connection.js:124:27)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23)

```

Solved it removing port 3306 (commenting that line)

Request to change error message to more meaningful message insteal of above one. For e.g. `port to postgres is invalid` or something similar

### StackOverflow / Slack attempts

Not as such but added a note https://github.com/satminav/support/issues/1

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [x] I don't know.
- [x] might be related to only postgresql

### Would you be willing to resolve this issue by submitting a Pull Request?

if the solution is small(does not take too much time), I will be  happy to contribute.

Feel free to ask more details if needed

**Comment by sushantdhiman** [comment]
Not sure what went wrong but it works, perhaps using old pg version?

```js
const sequelize = new Sequelize({
  dialect: 'postgres',
  host: 'localhost',
  port: 3306,
  username: '--',
  password: '--',
  database: 'nestjs'
});

{ SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306
    at connection.connect.err (/var/www/git/sequelize/lib/dialects/postgres/connection-manager.js:172:24)
    at Connection.connectingErrorHandler (/var/www/git/sequelize/node_modules/pg/lib/client.js:191:14)
    at Connection.emit (events.js:198:13)
    at Socket.reportStreamError (/var/www/git/sequelize/node_modules/pg/lib/connection.js:71:10)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'SequelizeConnectionRefusedError',
  parent:
   { Error: connect ECONNREFUSED 127.0.0.1:3306
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
     errno: 'ECONNREFUSED',
     code: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 3306 },
  original:
   { Error: connect ECONNREFUSED 127.0.0.1:3306
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
     errno: 'ECONNREFUSED',
     code: 'ECONNREFUSED',
     syscall: 'connect',
     address: '127.0.0.1',
     port: 3306 } }

```
