### ISSUE TITLE
Illegal Operation on a directory

### ISSUE THREAD

**Issue by jperera84** [sequelize/sequelize#11910]
## Issue Description
Trying to run a seed file I always got the following error.

### What are you doing?
I created a seed file using the sequelize CLI, it creates perfectly fine, I also have migrations file and it doesn't have any issue, but when trying to run the npm script: `"seed": "npx sequelize-cli db:seed:all"` I got the error mentioned above.^

Seed file:
```js
/* eslint-disable no-unused-vars */
"use strict";

module.exports = {
	up: (queryInterface, Sequelize) => {
		return queryInterface.bulkInsert("permission", [
			{ permissionName: "CREATOR", permissionDescription: "NO RESTRICTIONS"}
		], {});
	},

	down: (queryInterface, Sequelize) => {
		return queryInterface.bulkDelete("permission", null, {});
	}
};
```
Project Structure:
<img width="191" alt="Screen Shot 2020-02-06 at 8 09 34 AM" src="https://user-images.githubusercontent.com/13193138/73939718-11522580-48b8-11ea-90cc-c4693c2979c0.png">

Sequelize config.js

```js
const config = require("../../config");
const path = require("path");

module.exports = {
	development: {
		username             : config.DB_USER,
		password             : config.DB_PASS,
		database             : config.DB_DATABASE,
		host                 : config.DB_HOST,
		port                 : config.DB_PORT,
		dialect              : "mysql",
		migrationStorage     : "sequelize",
		seederStorage        : "json",
		seederStoragePath    : path.resolve("db", "seeders"),
		migrationStoragePath : path.resolve("db", "migrations")
	},
```

### What do you expect to happen?

It runs without any error.

### What is actually happening?

> Sequelize CLI [Node: 12.5.0, CLI: 5.5.1, ORM: 5.19.2]
> 
> Loaded configuration file "db/config/config.js".
> Using environment "development".
> == 20200204234710-seed-permissions: migrating =======
> 
> ERROR: EISDIR: illegal operation on a directory, open '/Users/xxxxxxx/Documents/yyyyyyyy/db/seeders'
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! prop-mgm-api@1.0.0 seed: `npx sequelize-cli db:seed:all`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the prop-mgm-api@1.0.0 seed script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/jpmorales/.npm/_logs/2020-02-06T12_59_32_612Z-debug.log

### Environment

- Sequelize version: sequelize@5.19.2 
- Node.js version: v12.5.0 and v13.x.x.
- Operating System: MACOS and Linux

### How does this problem relate to dialects?

- [x ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by jperera84** [comment]
This is the entire Node log:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/jpmorales/.nvm/versions/node/v12.5.0/bin/node',
1 verbose cli   '/Users/jpmorales/.nvm/versions/node/v12.5.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'seed'
1 verbose cli ]
2 info using npm@6.12.0
3 info using node@v12.5.0
4 verbose run-script [ 'preseed', 'seed', 'postseed' ]
5 info lifecycle prop-mgm-api@1.0.0~preseed: prop-mgm-api@1.0.0
6 info lifecycle prop-mgm-api@1.0.0~seed: prop-mgm-api@1.0.0
7 verbose lifecycle prop-mgm-api@1.0.0~seed: unsafe-perm in lifecycle true
8 verbose lifecycle prop-mgm-api@1.0.0~seed: PATH: /Users/jpmorales/.nvm/versions/node/v12.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/jpmorales/Documents/Training/prop-mgm-api/node_modules/.bin:/Users/jpmorales/.rbenv/shims:/Users/jpmorales/.rbenv/shims:/Users/jpmorales/.rbenv/bin:/Users/jpmorales/.rvm/gems/ruby-2.4.1/bin:/Users/jpmorales/.rvm/gems/ruby-2.4.1@global/bin:/Users/jpmorales/.rvm/rubies/ruby-2.4.1/bin:/Users/jpmorales/.nvm/versions/node/v12.5.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Users/jpmorales/.rbenv/shims:/Users/jpmorales/.rbenv/bin:/Users/jpmorales/.rvm/gems/ruby-2.4.1/bin:/Users/jpmorales/.rvm/gems/ruby-2.4.1@global/bin:/Users/jpmorales/.rvm/rubies/ruby-2.4.1/bin:/Users/jpmorales/.nvm/versions/node/v12.5.0/bin:/Users/jpmorales/.rvm/bin
9 verbose lifecycle prop-mgm-api@1.0.0~seed: CWD: /Users/jpmorales/Documents/Training/prop-mgm-api
10 silly lifecycle prop-mgm-api@1.0.0~seed: Args: [ '-c', 'npx sequelize-cli db:seed:all' ]
11 silly lifecycle prop-mgm-api@1.0.0~seed: Returned: code: 1  signal: null
12 info lifecycle prop-mgm-api@1.0.0~seed: Failed to exec seed script
13 verbose stack Error: prop-mgm-api@1.0.0 seed: `npx sequelize-cli db:seed:all`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/jpmorales/.nvm/versions/node/v12.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:200:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/jpmorales/.nvm/versions/node/v12.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:200:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid prop-mgm-api@1.0.0
15 verbose cwd /Users/jpmorales/Documents/Training/prop-mgm-api
16 verbose Darwin 18.7.0
17 verbose argv "/Users/jpmorales/.nvm/versions/node/v12.5.0/bin/node" "/Users/jpmorales/.nvm/versions/node/v12.5.0/bin/npm" "run" "seed"
18 verbose node v12.5.0
19 verbose npm  v6.12.0
20 error code ELIFECYCLE
21 error errno 1
22 error prop-mgm-api@1.0.0 seed: `npx sequelize-cli db:seed:all`
22 error Exit status 1
23 error Failed at the prop-mgm-api@1.0.0 seed script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by jperera84** [comment]
I fixed this changing my .sequelizerc file:
```
'use strict';

const path = require('path');

module.exports = {
    config: path.join(__dirname, 'db/config/config.js'),
    'seeders-path': path.join(__dirname, 'db/seeders'),
    'models-path': path.join(__dirname, 'models'),
    'migrations-source-path': path.join(__dirname, 'db/migrations_source'),
    'migrations-compiled-path': path.join(__dirname, 'db/migrations_compiled'),
    'migrations-path': path.join(__dirname, 'db/migrations')
};
```
