### ISSUE TITLE
Unable to use sequelize version 5.21.5. Getting error error Error: Invalid value { DeletionIndicator: { ne: '1' } }     at Object.escape (/var/task/node_modules/sequelize/lib/sql-string.js:65:11)

### ISSUE THREAD

**Issue by abhijeetsaxena7cr** [sequelize/sequelize#11971]
## Issue Description
Unable to use sequelize version 5.21.5. Getting error error Error: Invalid value { DeletionIndicator: { ne: '1' } }     at Object.escape (/var/task/node_modules/sequelize/lib/sql-string.js:65:11)

### What are you doing?
I am using sequlize version   5.21.5. and mysql2  "mysql": "^2.12.0",
    "mysql2": "^2.1.0",  with my node.js code for AWS lambda but getting the starnge error 

### What do you expect to happen?
I want it to run 

### What is actually happening?

Getting error error Error: Invalid value { DeletionIndicator: { ne: '1' } }     at Object.escape (/var/task/node_modules/sequelize/lib/sql-string.js:65:11)
```
Output here
 Error: Invalid value { DeletionIndicator: { ne: '1' } }     at Object.escape (/var/task/node_modules/sequelize/lib/sql-string.js:65:11)```

### Additional context

Add any other context or screenshots about the feature request here.

### Environment

- Sequelize version: XXX <!-- run `npm list sequelize` to obtain this -->5.21.5
- Node.js version: XXX <!-- run `node -v` to obtain this -->12.16.1
- Operating System: XXX Windows
- If TypeScript related: TypeScript version: XXX

## Issue Template Checklist

<!-- Please answer the questions below. If you don't, your issue may be closed. -->

### How does this problem relate to dialects?

<!-- Choose one. -->

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): <!-- Put dialect(s) here -->
- [ ] I don't know, I was using dialect: 'mysql',, with connector library version - I don't know and database version    "mysql": "^2.12.0",
    "mysql2": "^2.1.0",

### Would you be willing to resolve this issue by submitting a Pull Request?

<!-- Remember that first contributors are welcome! -->


- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
Create a https://github.com/papb/sequelize-sscce and comment so I can understand what is your issue
