### ISSUE TITLE
TypeError: Invalid Version: 0

### ISSUE THREAD

**Issue by RRicardotj** [sequelize/sequelize#11999]
Im facing an issue when I do findOrCreate using a transacction
this is the code
```js
import { user, order } from '~/src/models'

export default async (input, { transaction }) => {
  const { tripScheduleId } = input
  const [firstPassenger] = input.passengers

  const [userCreated] = await user.findOrCreate({
    where: { email: firstPassenger.emailAddress },
    defaults: {
      email: firstPassenger.emailAddress
    },
    transaction
  })

  return order.create({ buyerId: userCreated.id, tripScheduleId }, { transaction })
}
```
and sequelize is returning me this error
```
TypeError: Invalid Version: 0
    at new SemVer (/Users/ricardorodriguez/Documents/WeDevelop/raft/web-backend/node_modules/semver/semver.js:296:11)
    at compare (/Users/ricardorodriguez/Documents/WeDevelop/raft/web-backend/node_modules/semver/semver.js:585:10)
    at Function.gte (/Users/ricardorodriguez/Documents/WeDevelop/raft/web-backend/node_modules/semver/semver.js:634:10)
    at Object.insertQuery (/Users/ricardorodriguez/Documents/WeDevelop/raft/web-backend/node_modules/sequelize-views-support/node_modules/sequelize/lib/dialects/abstract/query-generator.js:150:18)
    at QueryInterface.insert (/Users/ricardorodriguez/Documents/WeDevelop/raft/web-backend/node_modules/sequelize-views-support/node_modules/sequelize/lib/query-interface.js:896:37)
    at /Users/ricardorodriguez/Documents/WeDevelop/raft/web-backend/node_modules/sequelize-views-support/node_modules/sequelize/lib/model.js:3685:53
    at tryCatcher (/Users/ricardorodriguez/Documents/WeDevelop/raft/web-backend/node_modules/bluebird/js/release/util.js:16:23) ...
```

I don't know why this is happened

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).

**Comment by bakkerthehacker** [comment]
## Issue Description

When calling `findOrCreate()` with a transaction, sometimes an error of `TypeError: Invalid Version: 0` is thrown. 

### What are you doing?

I tried to create a SSCCE that reproduces this issue but that testing harness can't reproduce this issue.  It is very flakey and calling `sequelize.sync()` or `sequelize.authenticate()` stop the error from occurring.  

The following seed does reproduce the error but only if the `TestModel` has been created or `.sync()`ed outside of the seed.

```javascript
module.exports = {
  up: (queryInterface, Sequelize) => queryInterface.sequelize.transaction(async (transaction) => {
    const TestModel = queryInterface.sequelize.define('TestModel', {
      name: {
        type: Sequelize.STRING,
        allowNull: false,
        unique: true,
        validate: {
          notEmpty: true,
        },
      },
      code: {
        type: Sequelize.STRING,
        allowNull: false,
        unique: true,
        validate: {
          notEmpty: true,
        },
      },
    }, {
    });

    await TestModel.findOrCreate({
      where: {
        code: 'TEST',
      },
      defaults: {
        name: 'test',
      },
      transaction,
    });
  }),
};

```

### What do you expect to happen?

I expect the `findOrCreate()` to suceed.  

### What is actually happening?

`findOrCreate()` fails with the error:

```
ERROR: TypeError: Invalid Version: 0
    at new SemVer (/code/thing/node_modules/sequelize/node_modules/semver/semver.js:314:11)
    at compare (/code/thing/node_modules/sequelize/node_modules/semver/semver.js:647:10)
    at Function.gte (/code/thing/node_modules/sequelize/node_modules/semver/semver.js:703:10)
    at PostgresQueryGenerator.insertQuery (/code/thing/node_modules/sequelize/lib/dialects/abstract/query-generator.js:222:18)
    at QueryInterface.insert (/code/thing/node_modules/sequelize/lib/query-interface.js:885:37)
    at /code/thing/node_modules/sequelize/lib/model.js:3989:52
From previous event:
    at model.save (/code/thing/node_modules/sequelize/lib/model.js:3966:8)
    at Function.create (/code/thing/node_modules/sequelize/lib/model.js:2230:8)
    at /code/thing/node_modules/sequelize/lib/model.js:2336:19
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at Function.findOrCreate (/code/thing/node_modules/sequelize/lib/model.js:2324:8)
    at /code/thing/seeders/20200306155918-categories.js:127:22
```

### Additional context

This is a print out of the `this.sequlize.options` when this fails: 
```javascript
{
  dialect: 'postgres',
  dialectModule: null,
  dialectModulePath: null,
  host: 'localhost',
  protocol: 'tcp',
  define: {},
  query: {},
  sync: {},
  timezone: '+00:00',
  clientMinMessages: 'warning',
  standardConformingStrings: true,
  logging: [Function],
  omitNull: false,
  native: false,
  replication: false,
  ssl: undefined,
  pool: {},
  quoteIdentifiers: true,
  hooks: {},
  retry: { max: 5, match: [ 'SQLITE_BUSY: database is locked' ] },
  transactionType: 'DEFERRED',
  isolationLevel: null,
  databaseVersion: 0,
  typeValidation: false,
  benchmark: false,
  minifyAliases: false,
  logQueryParameters: false,
  port: '5432'
}
```

### Environment

- Sequelize version: 5.22.3
- Node.js version: 12.16.3
- Operating System: Linux Mint 19

**Comment by sushantdhiman** [comment]
@bakkerthehacker Please test with `master` or `v6` branch. If you still find this issue, open a new issue on Github

**Comment by bakkerthehacker** [comment]
This issue does not happen in sequelize 6.

**Comment by bakkerthehacker** [comment]
It would still be nice so have a fix for v5. Most of the semver lte/gte checks in v5 have the right check, this one seems to be just missing an extra check on databaseVersion.
