### ISSUE TITLE
Model.create doesn't work with $ in field

### ISSUE THREAD

**Issue by miiguelperes** [sequelize/sequelize#12106]
### What are you doing?

I'm trying to insert a model, but I'm getting the following error:

```
Error: Named bind parameter "$VERSION" has no value in the given object.
    at formatBindParameters.sql.replace (D:\www\Backend\teste\node_modules\sequelize\lib\dialects\abstract\query.js:105:15)
    at String.replace (<anonymous>)
    at Function.formatBindParameters (D:\www\Backend\teste\node_modules\sequelize\lib\dialects\abstract\query.js:90:15)
    at Function.formatBindParameters (D:\www\Backend\teste\node_modules\sequelize\lib\dialects\postgres\query.js:28:27)
    at query.Promise.try (D:\www\Backend\teste\node_modules\sequelize\lib\sequelize.js:616:52)
From previous event:
    at Sequelize.query (D:\www\Backend\teste\node_modules\sequelize\lib\sequelize.js:578:23)
    at QueryInterface.insert (D:\www\Backend\teste\node_modules\sequelize\lib\query-interface.js:894:27)
    at save.Promise.try.then.then.then (D:\www\Backend\teste\node_modules\sequelize\lib\model.js:4024:52)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at model.save (D:\www\Backend\teste\node_modules\sequelize\lib\model.js:4001:8)
    at Function.create (D:\www\Backend\teste\node_modules\sequelize\lib\model.js:2227:8)
    at Object.create (D:\www\Backend\teste\dist\api\services\EmpresaService.js:36:44)
```

My model contains fields with $, and according to '\ lib \ dialects \ abstract \ query.js: 90: 15', the skipUnescape option should escape the $ character.

I don't know if I'm putting this option in the wrong place or if this bug was not completely fixed according to:

https://github.com/sequelize/sequelize/commit/43c4f6b73cf53152efd1393dccd26d6186e67980

Any help is welcome, thanks to everyone!

### Environment

- Sequelize version: 6.0.0-beta.5
- Node.js version: v10.16.0
- Operating System: Windows 10

**Comment by sushantdhiman** [comment]
Please submit some reproducible code & follow template

Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
