### ISSUE TITLE
DescribeTableQuery on mssql case sensitive

### ISSUE THREAD

**Issue by arnaud-moncel** [sequelize/sequelize#12193]
### What are you doing?

Hi guys 👋 and thank you for your amazing package.
I have some trouble with this function https://github.com/sequelize/sequelize/blob/a5a60f9ff1ca0b0e8d4743f82b4047227153fadb/lib/dialects/mssql/query-generator.js#L188
on a mssql DB with ` Latin1_General_CS_AS` collation.

Please see the following error.

```bash
SequelizeDatabaseError: Invalid object name 'information_schema.TABLE_CONSTRAINTS'.
    at Query.formatError (/Users/arnaudmoncel/lumber/node_modules/sequelize/lib/dialects/mssql/query.js:314:12)
    at Request.userCallback (/Users/arnaudmoncel/lumber/node_modules/sequelize/lib/dialects/mssql/query.js:74:23)
    at Request.callback (/Users/arnaudmoncel/lumber/node_modules/tedious/lib/request.js:40:14)
    at Connection.endOfMessageMarkerReceived (/Users/arnaudmoncel/lumber/node_modules/tedious/lib/connection.js:2273:20)
    at Connection.dispatchEvent (/Users/arnaudmoncel/lumber/node_modules/tedious/lib/connection.js:1220:36)
    at Parser.<anonymous> (/Users/arnaudmoncel/lumber/node_modules/tedious/lib/connection.js:1023:14)
    at Parser.emit (events.js:210:5)
    at Parser.<anonymous> (/Users/arnaudmoncel/lumber/node_modules/tedious/lib/token/token-stream-parser.js:27:14)
    at Parser.emit (events.js:210:5)
    at addChunk (/Users/arnaudmoncel/lumber/node_modules/readable-stream/lib/_stream_readable.js:297:12)
    at readableAddChunk (/Users/arnaudmoncel/lumber/node_modules/readable-stream/lib/_stream_readable.js:279:11)
    at Parser.Readable.push (/Users/arnaudmoncel/lumber/node_modules/readable-stream/lib/_stream_readable.js:240:10)
    at Parser.Transform.push (/Users/arnaudmoncel/lumber/node_modules/readable-stream/lib/_stream_transform.js:139:32)
    at Parser.afterTransform (/Users/arnaudmoncel/lumber/node_modules/readable-stream/lib/_stream_transform.js:88:10)
    at Parser._transform (/Users/arnaudmoncel/lumber/node_modules/tedious/lib/token/stream-parser.js:41:7)
    at Parser.Transform._read (/Users/arnaudmoncel/lumber/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at Parser.Transform._write (/Users/arnaudmoncel/lumber/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/Users/arnaudmoncel/lumber/node_modules/readable-stream/lib/_stream_writable.js:405:139)
    at writeOrBuffer (/Users/arnaudmoncel/lumber/node_modules/readable-stream/lib/_stream_writable.js:394:5)
    at Parser.Writable.write (/Users/arnaudmoncel/lumber/node_modules/readable-stream/lib/_stream_writable.js:303:11)
    at Parser.addEndOfMessageMarker (/Users/arnaudmoncel/lumber/node_modules/tedious/lib/token/token-stream-parser.js:45:24)
    at Connection.message (/Users/arnaudmoncel/lumber/node_modules/tedious/lib/connection.js:2262:32)
```

### What do you expect to happen?

I've identified three mistakes that are causing the problem.

Two of them use `INFORMATION_SCHEMA` as lowercase, and putting them in uppercase should fix the problem.
https://github.com/sequelize/sequelize/blob/a5a60f9ff1ca0b0e8d4743f82b4047227153fadb/lib/dialects/mssql/query-generator.js#L205-L206

The last one is to use `pk.constraint_type` as uppercase 
https://github.com/sequelize/sequelize/blob/a5a60f9ff1ca0b0e8d4743f82b4047227153fadb/lib/dialects/mssql/query-generator.js#L196
when it is declared as lowercase
https://github.com/sequelize/sequelize/blob/a5a60f9ff1ca0b0e8d4743f82b4047227153fadb/lib/dialects/mssql/query-generator.js#L203-L209

I hope I've helped you and given you enough context.
Thank you for your time.

### Environment

- Sequelize version: 5.21.7 
- Node.js version: 12.13.0 
- Operating System: macOs Catalina version 10.15.4 (19E287)

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [X] I think this problem happens only for the following dialect(s): mssql with case sensitive collation
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
Please submit a PR if you can spare some time, thanks :)

**Comment by arnaud-moncel** [comment]
Thank you @JuarezLustosa & @sushantdhiman ❤️

**Comment by arnaud-moncel** [comment]
Hi guys 👋 , Do you have any idea when this change will be released?
Thank you 😄

**Comment by sushantdhiman** [comment]
@arnaud-moncel This issue is fixed in master branch targeting v6-beta.

If you can submit this PR for v5 branch it will get released automatically as next v5 stable release

**Comment by arnaud-moncel** [comment]
Oh ok ! I understand thank you i will do that.
