### ISSUE TITLE
Azure: Error: Please install tedious package manually

### ISSUE THREAD

**Issue by CamelJohn** [sequelize/sequelize#12254]
## Issue Description

```
Error: Please install tedious package manually
```
This is the error i'm getting. I've seen threads before, about this issue - none of them work at the moment.

### What are you doing?

My node server is hosted somewhere, connecting to a sql server on Azure cloud.
Using Sequelize, tedious, mssql.

```
const Sequelize = require('sequelize/index').Sequelize;

const sequelize = new Sequelize(
  process.env.DATABASE,
  process.env.DATABASE_USER,
  process.env.DATABASE_PASSWORD,
  {
    host: process.env.DATABASE_HOST,
    dialect: 'mssql',
    // dialectModule: 'tedious',
    dialectOptions: {
      options: {
        encrypt: true,
        useUTC: false,
        dateFirst: 1,
        trustServerCertificate: true,
        enableArithAbort: false,
      },
    },
  }
);

module.exports = sequelize;
```

### What do you expect to happen?

Have a working connection like i do on localhost

### What is actually happening?

 ```
Error: Please install tedious package manually
    at ConnectionManager._loadDialectModule (D:\home\site\wwwroot\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:81:15)
    at new ConnectionManager (D:\home\site\wwwroot\node_modules\sequelize\lib\dialects\mssql\connection-manager.js:17:21)
    at new MssqlDialect (D:\home\site\wwwroot\node_modules\sequelize\lib\dialects\mssql\index.js:14:30)
    at new Sequelize (D:\home\site\wwwroot\node_modules\sequelize\lib\sequelize.js:324:20)
    at Object.<anonymous> (D:\home\site\wwwroot\util\database.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\home\site\wwwroot\server.js:6:19)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\Program Files (x86)\iisnode\interceptor.js:459:1)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
Application has thrown an uncaught exception and is terminated:
Error: Please install tedious package manually
    at ConnectionManager._loadDialectModule (D:\home\site\wwwroot\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:81:15)
    at new ConnectionManager (D:\home\site\wwwroot\node_modules\sequelize\lib\dialects\mssql\connection-manager.js:17:21)
    at new MssqlDialect (D:\home\site\wwwroot\node_modules\sequelize\lib\dialects\mssql\index.js:14:30)
    at new Sequelize (D:\home\site\wwwroot\node_modules\sequelize\lib\sequelize.js:324:20)
    at Object.<anonymous> (D:\home\site\wwwroot\util\database.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\home\site\wwwroot\server.js:6:19)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\Program Files (x86)\iisnode\interceptor.js:459:1)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
```

### Environment

- Sequelize version: 5.21.7 
- Node.js version: 13.9.0
- Operating System: Windows 10 x64

### How does this problem relate to dialects?

- [x] I don't know, I was using 'mssql', with tedious version 8.0.3 and sql server on Azure

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] No, I don't have the time and I wouldn't even know how to start. don't have the know how

**Comment by soryy708** [comment]
Are you using `webpack`?

**Comment by CamelJohn** [comment]
No. But if you have a fix that involves webpack i might consider it

**Comment by sushantdhiman** [comment]
Run this command to find out if you got Sequelize installed globally by mistake

```
npm ls -g --depth=0
```

Should print something like this

```
/home/sushant/.nvm/versions/node/v12.16.1/lib
+-- firebase-tools@8.0.2
+-- flow-typed@3.1.0
+-- flowgen@1.10.0
+-- http-server@0.12.3
+-- node-pre-gyp@0.14.0
`-- npm@6.14.4
```

If you find `sequelize` or `tedious` in that list, remove them with

```
npm uninstall -g sequelize tedious
```

After that do a fresh `npm install` under your project.

**Comment by CamelJohn** [comment]
Thans, but i did not see sequelize or tedious there.
I'ts important to say that on a local machine this did not happen.
I have an Azure account, on which I'm runing a SQL Server database (2000).
When my nodejs was local all was fine when connection and querrying the db on Azrue.
As soon as i deployed nodejs to Azure - this started happening.

**Comment by sushantdhiman** [comment]
What is the output of this command

```npm ls --depth=0```

**Comment by CamelJohn** [comment]
+-- create-react-app@3.4.1
+-- node@14.0.0
+-- npm@6.14.4
+-- webpack@4.43.0
`-- webpack-cli@3.3.11

**Comment by sushantdhiman** [comment]
So you haven't installed `sequelize` or `tedious` in your project?

**Comment by sushantdhiman** [comment]
```npm ls --depth=0``` Make sure you are running it without `-g` flag

**Comment by CamelJohn** [comment]
+-- axios@0.19.2
+-- bcryptjs@2.4.3
+-- body-parser@1.19.0
+-- express@4.17.1
+-- formdata-node@2.1.1
+-- jsonwebtoken@8.5.1
+-- mssql@6.2.0
+-- nodemailer@6.4.6
+-- nodemon@2.0.3
+-- sequelize@5.21.7
+-- tedious@8.3.0
`-- uuid-token-generator@1.0.0

**Comment by sushantdhiman** [comment]
These are from server, right?

**Comment by CamelJohn** [comment]
from my nodejs app on my local machine.

**Comment by sushantdhiman** [comment]
Where it works already, so that won't help. You need to post results for your production env

**Comment by CamelJohn** [comment]
Thanks papb, I'm new to github - and to opening issues.
I thought the Headline would give context to the issue :) hope I didn't cause trouble

**Comment by sushantdhiman** [comment]
Can you show me you `package.json`?

**Comment by CamelJohn** [comment]
"dependencies": {
    "axios": "^0.19.2",
    "bcryptjs": "^2.4.3",
    "body-parser": "^1.19.0",
    "express": "^4.17.1",
    "formdata-node": "^2.1.1",
    "jsonwebtoken": "^8.5.1",
    "mssql": "^6.1.0",
    "nodemailer": "^6.4.5",
    "sequelize": "^5.21.7",
    "tedious": "^8.3.0",
    "uuid-token-generator": "^1.0.0"
  }

**Comment by sushantdhiman** [comment]
Not sure if we can help anymore, if you can submit some code which doesn't work or project link we might be able to help. But can't say anything with just `package.json`

**Comment by papb** [comment]
See #13169
