### ISSUE TITLE
Belongs-To-Many: Missing mention of defaults change in V5 upgrade documentation

### ISSUE THREAD

**Issue by LaurentVB** [sequelize/sequelize#12327]
### What was unclear/insufficient/not covered in the documentation

The upgrade to v5 documentation does not mention a breaking change in defaults for `belongsToMany` relationships. In v4, providing a `through` model with a primary key would suffice to prevent Sequelize from creating a unique key on the through table.

`Survey.belongsToMany(models.User, { through: models.UserSurvey });`

With v5 it is now mandatory to add the `unique: false` config on the through model when defining the relationship. 

`Survey.belongsToMany(models.User, { through: { model: models.UserSurvey, unique: false } });`

Found this after upgrading to v5. Some tests started to throw a duplicate key error. Traced the issue thanks to this SO answer (https://stackoverflow.com/a/58439584/424352) but it would probably be worth it having it stated in upgrade docs.

Additionally, the v5 documentation of `belongsToMany` still states the following: 
> Belongs-To-Many creates a unique key when primary key is not present on through model.

implying that having a primary key on the through model would prevent this unique key creation. As seen above, this is not true anymore in v5.

### If possible: Provide some suggestion on how we can enhance the docs

v5 documentation for belongsToMany could be changed to:
> Belongs-To-Many creates a unique key on through model. This unique key name can be overridden using `uniqueKey` option. To prevent creating this unique key, use the `unique: false` option.

v5 upgrade guide could include a note like the following
> Belongs-To-Many relationship now always add a unique key on the through model, unless you use the `unique: false` option when defining the relationship.

Not sure about the copy guidelines for documentation though. 
I can submit a PR if someone validates the suggested language changes.

### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
Hmm, this looks like an unintentional breaking change

**Comment by sushantdhiman** [comment]
After studying this issue, it seems you have defined a primary key on model yourself, right? In that case unique key will be created by Sequelize.

Can you also show example for code which used to work with v4 but no longer working with v5/v6

**Comment by LaurentVB** [comment]
Hi Sushant,
Yes, I have a primary key defined on the join model. According to the documentation, this should prevent Sequelize to create the unique constraint on the pair of foreign keys. It was in v4, but in v5, it requires an additional config on the `belongsToMany` relationship.

The following code works in v4. But in v5 it throws `SequelizeUniqueConstraintError: Validation error`.

```js 
const User = sequelize.define('user', {
  id: {
    type: Sequelize.UUID,
    primaryKey: true,
    defaultValue: Sequelize.UUIDV4
  }
});

const Survey = sequelize.define('survey', {
  id: {
    type: Sequelize.UUID,
    primaryKey: true,
    defaultValue: Sequelize.UUIDV4
  }
});

const UserSurvey = sequelize.define('userSurvey', {
  id: {
    type: Sequelize.UUID,
    primaryKey: true,
    defaultValue: Sequelize.UUIDV4
  }
});

UserSurvey.belongsTo(Survey, { foreignKey: { allowNull: false } });
UserSurvey.belongsTo(User, { foreignKey: { allowNull: false } });

Survey.belongsToMany(User, { through: { model: UserSurvey } });
User.belongsToMany(Survey, { through: { model: UserSurvey } });

describe('sequelize', () => {
  it('allows to create several records with the same foreign keys in the join table', async () => {
    await sequelize.sync({ force: true });
    const user = await User.create();
    const survey = await Survey.create();
    await UserSurvey.create({ userId: user.id, surveyId: survey.id });
    await UserSurvey.create({ userId: user.id, surveyId: survey.id });
  });
});
```

The way to make it work in v5 is to add a `unique: false` property on the `belongsToMany` config, which is not documented, hence this issue.

```js
Survey.belongsToMany(User, { through: { model: UserSurvey, unique: false } });
User.belongsToMany(Survey, { through: { model: UserSurvey, unique: false } });
```

Imho, requiring the config is pretty much ok, more explicit, less magic. But the documentation should be updated accordingly.

**Comment by sushantdhiman** [comment]
I tried this code with v4

```js
const Sequelize = require("./index");
const DataTypes = Sequelize.DataTypes;
const sequelize = require("./test/support").createSequelizeInstance({});

const assert = require("assert");

(() => {
  const User = sequelize.define("user", {
    id: {
      type: Sequelize.UUID,
      primaryKey: true,
      defaultValue: Sequelize.UUIDV4,
    },
  });

  const Survey = sequelize.define("survey", {
    id: {
      type: Sequelize.UUID,
      primaryKey: true,
      defaultValue: Sequelize.UUIDV4,
    },
  });

  const UserSurvey = sequelize.define("userSurvey", {
    id: {
      type: Sequelize.UUID,
      primaryKey: true,
      defaultValue: Sequelize.UUIDV4,
    },
  });

  UserSurvey.belongsTo(Survey, { foreignKey: { allowNull: false } });
  UserSurvey.belongsTo(User, { foreignKey: { allowNull: false } });

  Survey.belongsToMany(User, { through: { model: UserSurvey } });
  User.belongsToMany(Survey, { through: { model: UserSurvey } });

  return sequelize.sync({ force: true }).then(() => {
    return User.create().then(u => {
      return Survey.create().then(s => {
        return UserSurvey.create({ userId: u.id, surveyId: s.id }).then(() => {
          return UserSurvey.create({ userId: u.id, surveyId: s.id });
        });
      });
    });
  }).catch(e => console.log(e))
})()
```

```sql
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators lib/sequelize.js:245:13
Executing (default): DROP TABLE IF EXISTS `userSurveys`;
Executing (default): DROP TABLE IF EXISTS `surveys`;
Executing (default): DROP TABLE IF EXISTS `users`;
Executing (default): DROP TABLE IF EXISTS `users`;
Executing (default): CREATE TABLE IF NOT EXISTS `users` (`id` UUID PRIMARY KEY, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
Executing (default): PRAGMA INDEX_LIST(`users`)
Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_users_1`)
Executing (default): DROP TABLE IF EXISTS `surveys`;
Executing (default): CREATE TABLE IF NOT EXISTS `surveys` (`id` UUID PRIMARY KEY, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
Executing (default): PRAGMA INDEX_LIST(`surveys`)
Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_surveys_1`)
Executing (default): DROP TABLE IF EXISTS `userSurveys`;
Executing (default): CREATE TABLE IF NOT EXISTS `userSurveys` (`id` UUID PRIMARY KEY, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `surveyId` UUID NOT NULL REFERENCES `surveys` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, `userId` UUID NOT NULL REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE, UNIQUE (`surveyId`, `userId`));
Executing (default): PRAGMA INDEX_LIST(`userSurveys`)
Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_userSurveys_1`)
Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_userSurveys_2`)
Executing (default): INSERT INTO `users` (`id`,`createdAt`,`updatedAt`) VALUES ('52800d2e-6c59-4931-b83f-957b9b85279b','2020-06-23 08:48:26.029 +00:00','2020-06-23 08:48:26.029 +00:00');
Executing (default): INSERT INTO `surveys` (`id`,`createdAt`,`updatedAt`) VALUES ('0550b3c3-a1b3-40b7-979a-50698f6cb692','2020-06-23 08:48:26.049 +00:00','2020-06-23 08:48:26.049 +00:00');
Executing (default): INSERT INTO `userSurveys` (`id`,`createdAt`,`updatedAt`,`surveyId`,`userId`) VALUES ('35df4edf-1b6f-4540-9258-fef6362c1492','2020-06-23 08:48:26.054 +00:00','2020-06-23 08:48:26.054 +00:00','0550b3c3-a1b3-40b7-979a-50698f6cb692','52800d2e-6c59-4931-b83f-957b9b85279b');
Executing (default): INSERT INTO `userSurveys` (`id`,`createdAt`,`updatedAt`,`surveyId`,`userId`) VALUES ('dc678865-e219-46ae-be59-4efe848022ee','2020-06-23 08:48:26.057 +00:00','2020-06-23 08:48:26.057 +00:00','0550b3c3-a1b3-40b7-979a-50698f6cb692','52800d2e-6c59-4931-b83f-957b9b85279b');
{ SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/var/projects/oss/sequelize/lib/dialects/sqlite/query.js:425:16)
    at Statement.afterExecute (/var/projects/oss/sequelize/lib/dialects/sqlite/query.js:119:32)
    at Statement.wrappedAfterExecute (/var/projects/oss/sequelize/lib/dialects/sqlite/query.js:256:39)
    at Statement.replacement (/var/projects/oss/sequelize/node_modules/sqlite3/lib/trace.js:19:31)
From previous event:
    at executeSql (/var/projects/oss/sequelize/lib/dialects/sqlite/query.js:107:21)
    at Database.database.serialize (/var/projects/oss/sequelize/lib/dialects/sqlite/query.js:305:18)
    at resolve (/var/projects/oss/sequelize/lib/dialects/sqlite/query.js:102:21)
From previous event:
    at Query.run (/var/projects/oss/sequelize/lib/dialects/sqlite/query.js:100:12)
    at Promise.try.then.connection (/var/projects/oss/sequelize/lib/sequelize.js:561:20)
From previous event:
    at Promise.resolve.retryParameters (/var/projects/oss/sequelize/lib/sequelize.js:558:8)
    at /var/projects/oss/sequelize/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/var/projects/oss/sequelize/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/var/projects/oss/sequelize/lib/sequelize.js:457:28)
    at QueryInterface.insert (/var/projects/oss/sequelize/lib/query-interface.js:901:27)
    at Promise.try.then.then.then (/var/projects/oss/sequelize/lib/model.js:3685:53)
From previous event:
    at model.save (/var/projects/oss/sequelize/lib/model.js:3661:8)
    at Function.create (/var/projects/oss/sequelize/lib/model.js:2023:8)
    at UserSurvey.create.then (/var/projects/oss/sequelize/sscce.js:50:29)
From previous event:
    at Survey.create.then.s (/var/projects/oss/sequelize/sscce.js:49:68)
From previous event:
    at User.create.then.u (/var/projects/oss/sequelize/sscce.js:48:30)
From previous event:
    at sequelize.sync.then (/var/projects/oss/sequelize/sscce.js:47:26)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at __dirname (/var/projects/oss/sequelize/sscce.js:46:42)
    at Object.<anonymous> (/var/projects/oss/sequelize/sscce.js:55:3)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
    at bootstrap_node.js:507:3
  name: 'SequelizeUniqueConstraintError',
  errors: 
   [ ValidationErrorItem {
       message: 'surveyId must be unique',
       type: 'unique violation',
       path: 'surveyId',
       value: '0550b3c3-a1b3-40b7-979a-50698f6cb692',
       origin: 'DB',
       instance: [Object],
       validatorKey: 'not_unique',
       validatorName: null,
       validatorArgs: [] },
     ValidationErrorItem {
       message: 'userId must be unique',
       type: 'unique violation',
       path: 'userId',
       value: '52800d2e-6c59-4931-b83f-957b9b85279b',
       origin: 'DB',
       instance: [Object],
       validatorKey: 'not_unique',
       validatorName: null,
       validatorArgs: [] } ],
  fields: [ 'surveyId', 'userId' ],
  parent: 
   { Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: userSurveys.surveyId, userSurveys.userId
       at Error (native)
     errno: 19,
     code: 'SQLITE_CONSTRAINT',
     sql: 'INSERT INTO `userSurveys` (`id`,`createdAt`,`updatedAt`,`surveyId`,`userId`) VALUES (\'dc678865-e219-46ae-be59-4efe848022ee\',\'2020-06-23 08:48:26.057 +00:00\',\'2020-06-23 08:48:26.057 +00:00\',\'0550b3c3-a1b3-40b7-979a-50698f6cb692\',\'52800d2e-6c59-4931-b83f-957b9b85279b\');' },
  original: 
   { Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: userSurveys.surveyId, userSurveys.userId
       at Error (native)
     errno: 19,
     code: 'SQLITE_CONSTRAINT',
     sql: 'INSERT INTO `userSurveys` (`id`,`createdAt`,`updatedAt`,`surveyId`,`userId`) VALUES (\'dc678865-e219-46ae-be59-4efe848022ee\',\'2020-06-23 08:48:26.057 +00:00\',\'2020-06-23 08:48:26.057 +00:00\',\'0550b3c3-a1b3-40b7-979a-50698f6cb692\',\'52800d2e-6c59-4931-b83f-957b9b85279b\');' },
  sql: 'INSERT INTO `userSurveys` (`id`,`createdAt`,`updatedAt`,`surveyId`,`userId`) VALUES (\'dc678865-e219-46ae-be59-4efe848022ee\',\'2020-06-23 08:48:26.057 +00:00\',\'2020-06-23 08:48:26.057 +00:00\',\'0550b3c3-a1b3-40b7-979a-50698f6cb692\',\'52800d2e-6c59-4931-b83f-957b9b85279b\');' }
```

This code still throws for me in v4?

Inspecting code it seems, either PK or UNIQUE KEY on `sourceId + targetId` is always created. I'll accept a PR to clarify documentation, it should say you need to pass `unique: false` if you want to prevent unique key generation & omit any ambiguous language for the same

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/pull/12481
