### ISSUE TITLE
Error whn

### ISSUE THREAD

**Issue by MikeBazhenov** [sequelize/sequelize#12351]
```TypeError: Cannot read property 'length' of undefined
at Function._groupJoinData (/opt/project/node_modules/sequelize/lib/dialects/abstract/query.js:668:33)
at Query.handleSelectQuery (/opt/project/node_modules/sequelize/lib/dialects/abstract/query.js:278:31)
at /opt/project/node_modules/sequelize/lib/dialects/postgres/query.js:196:23```

## Issue Description

### What are you doing?

<!--
We have a repository dedicated to make it easy for you to create an SSCCE.
https://github.com/papb/sequelize-sscce
Please consider using it, everyone wins!
-->

**Here is the link to the SSCCE for this issue:** LINK-HERE <!-- add a link to the SSCCE -->

<!--
If you don't want to use the SSCCE repository, you can also post a MINIMAL, SELF-CONTAINED code that reproduces the issue. It must be runnable by simply copying and pasting into an isolated JS file, except possibly for the database connection configuration.
Check http://sscce.org/ or https://stackoverflow.com/help/minimal-reproducible-example to learn more about SSCCE/MCVE/reprex.
-->

```js
// You can delete this code block if you have included a link to your SSCCE above!
// MINIMAL, SELF-CONTAINED code here (SSCCE/MCVE/reprex)
```

### What do you expect to happen?

_I wanted Foo!_

### What is actually happening?

_The output was Bar!_

```
Output here
```

### Environment

- Sequelize version: XXX 
- Node.js version: XXX 
- Operating System: XXX
- If TypeScript related: TypeScript version: XXX

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
