### ISSUE TITLE
Error when I'm using separate true flag

### ISSUE THREAD

**Issue by MikeBazhenov** [sequelize/sequelize#12354]
### What are you doing?

I'm trying to get entities with HasMany relations, and it is works slow so I decided to add separate true flag in include options.

```typescript
include.push({
        model: PostTags,
        required: true,
        separate: true,
        attributes: [],
        where: {
          tag_id: filter.tag,
        },
      });

const result = await this.TABLE.findAndCountAll<Post>({
      where,
      offset: (page - 1) * limit,
      limit,
      order: [['created_at', 'DESC']],
      include: include.concat([Agency]),
    });
```

### What is actually happening?
Sequelize throws an exception

```
TypeError: Cannot read property 'length' of undefined
at Function._groupJoinData (/opt/project/node_modules/sequelize/lib/dialects/abstract/query.js:668:33)
at Query.handleSelectQuery (/opt/project/node_modules/sequelize/lib/dialects/abstract/query.js:278:31)
at /opt/project/node_modules/sequelize/lib/dialects/postgres/query.js:196:23
```

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using Postgres, with connector library version 7.18.2 and database version 11.6

### Environment

- Sequelize version: 5.21.12
- Node.js version: 12
- Operating System: alpine
- If TypeScript related: TypeScript version: 3.6.3

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

### Use case
Need to create three tables:
Posts
* id

PostTags
* post_id
* tag_id

Tags
* id

And run query like this:
```
Posts.findAndCountAll({
   include: [{
      model: PostTags,
      required: true,
      separate: true,
      attributes: [],
      where: {
         tag_id: filter.tag,
      },
   }]
})
```

**Comment by sushantdhiman** [comment]
It works on `master`

```js
(async () => {  
  const Post = sequelize.define("post", {}, { timestamps: false });  
  const Tag = sequelize.define("tag", {}, { timestamps: false });  
  const PostTag = sequelize.define("post_tag", {}, { timestamps: false });  
  
  PostTag.removeAttribute('id');  
  
  Post.hasMany(PostTag);  
  Tag.hasMany(PostTag);  
  
  PostTag.belongsTo(Post);  
  PostTag.belongsTo(Tag);  
  
  await sequelize.sync({ force: true });  

  await Post.bulkCreate([{ id: 1 }, { id: 2 }, { id: 3 }]);
  await Tag.bulkCreate([{ id: 1 }, { id: 2 }, { id: 3 }]);
  await PostTag.bulkCreate([
    { postId: 1, tagId: 2 },
    { postId: 2, tagId: 1 },
    { postId: 2, tagId: 2 },
  ]);
  
  const result = await Post.findAndCountAll({  
    include: [  
      {  
        model: PostTag,  
        required: true,  
        separate: true,  
        attributes: [],  
        where: {
          tagId: 2,
        },
      },
    ],
  });

  console.log(result);
})().catch((e) => console.error(e));
```

It fails with `QueryError` if `attributes: []` are empty, as model is missing PK there is nothing to select.

```sql
Executing (default): DROP TABLE IF EXISTS "post_tags" CASCADE;
Executing (default): DROP TABLE IF EXISTS "tags" CASCADE;
Executing (default): DROP TABLE IF EXISTS "posts" CASCADE;
Executing (default): DROP TABLE IF EXISTS "posts" CASCADE;
Executing (default): CREATE TABLE IF NOT EXISTS "posts" ("id"   SERIAL , PRIMARY KEY ("id"));
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'posts' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
Executing (default): DROP TABLE IF EXISTS "tags" CASCADE;
Executing (default): CREATE TABLE IF NOT EXISTS "tags" ("id"   SERIAL , PRIMARY KEY ("id"));
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'tags' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
Executing (default): DROP TABLE IF EXISTS "post_tags" CASCADE;
Executing (default): CREATE TABLE IF NOT EXISTS "post_tags" ("postId" INTEGER REFERENCES "posts" ("id") ON DELETE SET NULL ON UPDATE CASCADE, "tagId" INTEGER REFERENCES "tags" ("id") ON DELETE SET NULL ON UPDATE CASCADE);
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'post_tags' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
Executing (default): INSERT INTO "posts" ("id") VALUES (1),(2),(3) RETURNING "id";
Executing (default): INSERT INTO "tags" ("id") VALUES (1),(2),(3) RETURNING "id";
Executing (default): INSERT INTO "post_tags" ("postId","tagId") VALUES (1,2),(2,1),(2,2) RETURNING "postId","tagId";
Executing (default): SELECT count("post"."id") AS "count" FROM "posts" AS "post";
Executing (default): SELECT "post"."id" FROM "posts" AS "post";
{ SequelizeQueryError: Attempted a SELECT query for model 'post_tag' as "post_tag" without selecting any columns
    at PostgresQueryGenerator._throwOnEmptyAttributes (/var/projects/oss/sequelize/lib/dialects/abstract/query-generator.js:2077:11)
    at PostgresQueryGenerator.selectFromTableFragment (/var/projects/oss/sequelize/lib/dialects/abstract/query-generator.js:2081:10)
    at PostgresQueryGenerator.selectQuery (/var/projects/oss/sequelize/lib/dialects/abstract/query-generator.js:1308:34)
    at PostgresQueryInterface.select (/var/projects/oss/sequelize/lib/dialects/abstract/query-interface.js:939:27)
    at Function.findAll (/var/projects/oss/sequelize/lib/model.js:1741:47)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'SequelizeQueryError' }
```

if I remove `attributes: []` then it works

```sql
Executing (default): DROP TABLE IF EXISTS "post_tags" CASCADE;
Executing (default): DROP TABLE IF EXISTS "tags" CASCADE;
Executing (default): DROP TABLE IF EXISTS "posts" CASCADE;
Executing (default): DROP TABLE IF EXISTS "posts" CASCADE;
Executing (default): CREATE TABLE IF NOT EXISTS "posts" ("id"   SERIAL , PRIMARY KEY ("id"));
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'posts' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
Executing (default): DROP TABLE IF EXISTS "tags" CASCADE;
Executing (default): CREATE TABLE IF NOT EXISTS "tags" ("id"   SERIAL , PRIMARY KEY ("id"));
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'tags' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
Executing (default): DROP TABLE IF EXISTS "post_tags" CASCADE;
Executing (default): CREATE TABLE IF NOT EXISTS "post_tags" ("postId" INTEGER REFERENCES "posts" ("id") ON DELETE SET NULL ON UPDATE CASCADE, "tagId" INTEGER REFERENCES "tags" ("id") ON DELETE SET NULL ON UPDATE CASCADE);
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'post_tags' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
Executing (default): INSERT INTO "posts" ("id") VALUES (1),(2),(3) RETURNING "id";
Executing (default): INSERT INTO "tags" ("id") VALUES (1),(2),(3) RETURNING "id";
Executing (default): INSERT INTO "post_tags" ("postId","tagId") VALUES (1,2),(2,1),(2,2) RETURNING "postId","tagId";
Executing (default): SELECT count("post"."id") AS "count" FROM "posts" AS "post";
Executing (default): SELECT "post"."id" FROM "posts" AS "post";
Executing (default): SELECT "postId", "tagId" FROM "post_tags" AS "post_tag" WHERE ("post_tag"."postId" IN (1, 2, 3) AND "post_tag"."tagId" = 2);
{
  "count": 3,
  "rows": [
    {
      "id": 1,
      "post_tags": [
        {
          "postId": 1,
          "tagId": 2
        }
      ]
    },
    {
      "id": 2,
      "post_tags": []
    },
    {
      "id": 3,
      "post_tags": []
    }
  ]
}
```

In either case, there is no `TypeError`

**Comment by MikeBazhenov** [comment]
@sushantdhiman As I see from this code, error is possible when `$prevKeyPrefix` still be undefined, there is no checking for undefined value.
<img width="592" alt="Снимок экрана 2020-06-09 в 13 10 32" src="https://user-images.githubusercontent.com/1553430/84112441-f4d71d00-aa52-11ea-8ef5-ff7cf2c85902.png">

**Comment by sushantdhiman** [comment]
We are working on improving this https://github.com/sequelize/sequelize/pull/12220

**Comment by MikeBazhenov** [comment]
@sushantdhiman Nice, thank you! Have a nice day! :)
