### ISSUE TITLE
During one-to-many joins, the ALIAS in the representative table is exposed to an empty string, resulting in an error.

### ISSUE THREAD

**Issue by rarchive** [sequelize/sequelize#12371]
### What are you doing?

I'm trying to join one-to-many.

- repository.js
```
        models.User.findOne({
            where: {userId, isValid},
            attributes: ['name', 'description', 'imagePath'],
            include: [
              model: this,
              as: 'permissions',
              attributes: ['permission'],
              required: true
            ],
        });
```

- User.js
```
export default class User extends Model {
    static init(sequelize) {
        return super.init(columns, {tableName: 'user', freezeTableName: true, sequelize});
    }

    static associate(models) {
        this.hasMany(models.UserPermission, {foreignKey: 'userId', as: 'permissions', constraints: false});
    }
    ...
}
```

- UserPermission.js
```

export default class UserPermission extends Model {
    static init(sequelize) {
        return super.init(columns, {tableName: 'user_permission', freezeTableName: true, sequelize});
    }
    ...
}
```

### What do you expect to happen?

A proper alias should be given.

like this:
```
SELECT `o`.`userId`,
       `o`.`name`,
       `o`.`description`,
       `o`.`imagePath`,
       `permissions`.`userId`     AS `permissions.userId`,
       `permissions`.`permission` AS `permissions.permission`
FROM `user` AS `o`
         LEFT OUTER JOIN `user_permission` AS `permissions`
                         ON `o`.`userId` = `permissions`.`userId` AND `permissions`.`isValid` = true
WHERE `o`.`userId` = '1234'
  AND `o`.`isValid` = true;
```

### What is actually happening?

However, error due to empty alias.

Error log:
```
DatabaseError [SequelizeDatabaseError]: Column 'userId' in field list is ambiguous
    at Query.formatError (/var/task/node_modules/sequelize/lib/dialects/mysql/query.js:244:16)
    at Query.handler [as onResult] (/var/task/node_modules/sequelize/lib/dialects/mysql/query.js:51:23)
    at Query.execute (/var/task/node_modules/mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/var/task/node_modules/mysql2/lib/connection.js:417:32)
    at PacketParser.onPacket (/var/task/node_modules/mysql2/lib/connection.js:75:12)
    at PacketParser.executeStart (/var/task/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/var/task/node_modules/mysql2/lib/connection.js:82:25)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  parent: Error: Column 'userId' in field list is ambiguous
      at Packet.asError (/var/task/node_modules/mysql2/lib/packets/packet.js:712:17)
      at Query.execute (/var/task/node_modules/mysql2/lib/commands/command.js:28:26)
      at Connection.handlePacket (/var/task/node_modules/mysql2/lib/connection.js:417:32)
      at PacketParser.onPacket (/var/task/node_modules/mysql2/lib/connection.js:75:12)
      at PacketParser.executeStart (/var/task/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/var/task/node_modules/mysql2/lib/connection.js:82:25)
      at Socket.emit (events.js:310:20)
      at addChunk (_stream_readable.js:286:12)
      at readableAddChunk (_stream_readable.js:268:9)
      at Socket.Readable.push (_stream_readable.js:209:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
    code: 'ER_NON_UNIQ_ERROR',
    errno: 1052,
    sqlState: '23000',
    sqlMessage: "Column 'userId' in field list is ambiguous",
    sql: "SELECT ``.`userId`, ``.`name`, ``.`description`, ``.`imagePath`, `permissions`.`userId` AS `permissions.userId`, `permissions`.`permission` AS `permissions.permission` FROM `user` AS `` LEFT OUTER JOIN `user_permission` AS `permissions` ON ``.`userId` = `permissions`.`userId` AND `permissions`.`isValid` = true WHERE ``.`userId` = '7688696a-93de-47a0-931a-3441435943a1' AND ``.`isValid` = true;",
    parameters: undefined
  },
```

parsed sql:
```
SELECT ``.`userId`,
       ``.`name`,
       ``.`description`,
       ``.`imagePath`,
       `permissions`.`userId`     AS `permissions.userId`,
       `permissions`.`permission` AS `permissions.permission`
FROM `user` AS ``
         LEFT OUTER JOIN `user_permission` AS `permissions`
                         ON ``.`userId` = `permissions`.`userId` AND `permissions`.`isValid` = true
WHERE ``.`userId` = '7688696a-93de-47a0-931a-3441435943a1'
  AND ``.`isValid` = true;
```

The problem is this: [`user` AS ``]

### Additional context

Why is this happening? Is there a way to force alias on the representative table?

thanks

### Environment

- Sequelize version: 5.21.12
- Node.js version: 12.18.0
- Operating System: AWS lambda

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by rarchive** [comment]
No problems occur after completely reconfiguring the lambda and serverless environment.
