### ISSUE TITLE
Error: `values.map` is not a function

### ISSUE THREAD

**Issue by dalisoft** [sequelize/sequelize#12396]
## Issue Description

`values.map` is not a function error on query with PostgreSQL connection (on others didn't tested)

### What are you doing?

<details>
<summary>Model file</summary>

```js
import DataTypes from 'sequelize';
import { v4 as uuidV4 } from 'uuid';
import sequelize from '../connections/postgres.js';

export default sequelize.define('Document', {
  id: {
    type: DataTypes.UUID,
    defaultValue() {
      return uuidV4();
    },
    primaryKey: true,
  },
  tag: {
    type: DataTypes.ARRAY(DataTypes.STRING),
    allowNull: false,
  },
  createdAt: {
    type: DataTypes.STRING,
    defaultValue() {
      return new Date().toISOString();
    },
  },
});
```
</details>

```js
const tags = ['foo', 'bar']
Docs.findAll({
      where: {
        [sequelize.Op.or]: tags.map((_value) => ({
          tag: { [sequelize.Op.iLike]: `%${_value}%` },
        })),
      },
    })
```

### What do you expect to happen?

As described like here

![From docs page](http://joxi.ru/brRkzqjcYb7ORm?d=1)

I am used similar syntax and excepted to see search results

### What is actually happening?

I am used similar syntax, but error happened: `values.map is not a function`

<details>
<summary>Stack trace</summary>

```
TypeError: values.map is not a function\n' +
    '    at ARRAY._value (/Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/sequelize/lib/dialects/postgres/data-types.js:458:19)\n' +
    '    at ARRAY._stringify (/Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/sequelize/lib/dialects/postgres/data-types.js:473:29)\n' +
    '    at ARRAY.stringify (/Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/sequelize/lib/data-types.js:23:19)\n' +
    '    at PostgresQueryGenerator.escape (/Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:976:30)\n' +
    '    at PostgresQueryGenerator._whereParseSingleValueObject (/Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2556:41)\n' +
    '    at PostgresQueryGenerator.whereItemQuery (/Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2272:21)\n' +
    '    at /Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2173:25\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at PostgresQueryGenerator.whereItemsQuery (/Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2171:35)\n' +
    '    at /Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2307:30\n' +
    '    at Array.map (<anonymous>)\n' +
    '    at PostgresQueryGenerator._whereGroupBind (/Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2306:21)\n' +
    '    at PostgresQueryGenerator.whereItemQuery (/Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2242:19)\n' +
    '    at /Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2173:25\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at PostgresQueryGenerator.whereItemsQuery (/Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2171:35)\n' +
    '    at PostgresQueryGenerator.getWhereConditions (/Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2583:19)\n' +
    '    at PostgresQueryGenerator.selectQuery (/Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1315:28)\n' +
    '    at QueryInterface.select (/Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/sequelize/lib/query-interface.js:1122:27)\n' +
    '    at /Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/sequelize/lib/model.js:1759:34\n' +
    'From previous event:\n' +
    '    at Function.findAll (/Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/sequelize/lib/model.js:1757:8)\n' +
    '    at Module.searchiLike (file:///Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/src/controllers/docs.js:17:17)\n' +
    '    at file:///Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/src/routes/docs/index.js:28:29\n' +
    '    at file:///Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/src/helpers/wrap-route.js:2:18\n' +
    '    at Layer.handle [as handle_request] (/Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/express/lib/router/layer.js:95:5)\n' +
    '    at next (/Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/express/lib/router/route.js:137:13)\n' +
    '    at /Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/express-json-validator-middleware/src/index.js:63:5\n' +
    '    at Layer.handle [as handle_request] (/Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/express/lib/router/layer.js:95:5)\n' +
    '    at next (/Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/express/lib/router/route.js:137:13)\n' +
    '    at Route.dispatch (/Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/express/lib/router/route.js:112:3)\n' +
    '    at Layer.handle [as handle_request] (/Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/express/lib/router/layer.js:95:5)\n' +
    '    at /Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/express/lib/router/index.js:281:22\n' +
    '    at Function.process_params (/Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/express/lib/router/index.js:335:12)\n' +
    '    at next (/Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/express/lib/router/index.js:275:10)\n' +
    '    at Function.handle (/Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/express/lib/router/index.js:174:3)\n' +
    '    at router (/Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/express/lib/router/index.js:47:12)\n' +
    '    at Layer.handle [as handle_request] (/Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/express/lib/router/layer.js:95:5)\n' +
    '    at trim_prefix (/Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/express/lib/router/index.js:317:13)\n' +
    '    at /Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/express/lib/router/index.js:284:7\n' +
    '    at Function.process_params (/Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/express/lib/router/index.js:335:12)\n' +
    '    at next (/Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/express/lib/router/index.js:275:10)\n' +
    '    at /Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/express-jwt/lib/index.js:128:7\n' +
    '    at /Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/async/lib/async.js:52:16\n' +
    '    at Immediate.<anonymous> (/Users/dalisoft/Desktop/Workdir/MyScreen/myscreen-docs-server/node_modules/async/lib/async.js:1206:34)\n' +
    '    at processImmediate (internal/timers.js:456:21)'
```
</details>

### Environment

- Sequelize version: v5.21.11
- Node.js version: v14.4.0
- Operating System: macOS Mojave (10.14.6)
- If TypeScript related: -

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by sushantdhiman** [comment]
These operators (like, ilike) are supported for `string`, you are trying to use it on `string[]`. Something like this should work

```js
const tags = ["foo", "bar"];
  await Doc.findAll({
    where: {
      [Sequelize.Op.or]: [                                 
        {
          tag: { [Sequelize.Op.contains]: tags },                                         
        },
      ],
    },
  });
```

Read more https://www.postgresql.org/docs/12/functions-array.html
