### ISSUE TITLE
Inconsistent behavior when using findOrCreate

### ISSUE THREAD

**Issue by Lumpiasty** [sequelize/sequelize#12397]
### Post a minimal code sample that reproduces the issue, including models and associations

I don't think that this issue is related to any model, because it happens with every model.
```
Model.findOrCreate({
  where: {
    // something here
  }
}).then(result => {
  result.save(); // Unhandled rejection TypeError: code.save is not a function
});
```
Throws error:
```
Unhandled rejection TypeError: result.save is not a function
    at // trace to above code here
    at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
```
However, assuming instance exists following code works flawlessly:
```
Model.findOne({
  where: {
    // something here
  }
}).then(result => {
  result.save();
});
```
### What do you expect to happen?

`findOrCreate` method binds prototype functions to instance or exception is made in docs

### What is actually happening?

`findOrCreate` method is not binding prototype functions to instance (does not matter if builtin or user defined)

###  Which dialect you are using (postgres, mysql etc)?
`mariadb`

### Which sequelize version you are using?
Node: 14.2.0, ORM: 5.21.12

**Comment by sushantdhiman** [comment]
[`findOrCreate`](https://sequelize.org/master/class/lib/model.js~Model.html#static-method-findOrCreate) Needs to return an array so you can determine if row was created or not.

Please read the docs
