### ISSUE TITLE
bug with "fn": Error: Named bind parameter "$123" has no value in the given object.

### ISSUE THREAD

**Issue by jitesh-prajapati123** [sequelize/sequelize#12443]
Can not use input with $ for any mysql function.

Fn { fn: 'md5', args: [ 'Testing$123' ] }
Error: Named bind parameter "$123" has no value in the given object.
    at sql.replace (D:\projects\servavillage\cloud-infrastructure\deploy\express\functions\node_modules\sequelize\lib\dialects\abstract\query.js:102:15)
    at String.replace (<anonymous>)
    at Function.formatBindParameters (D:\projects\servavillage\cloud-infrastructure\deploy\express\functions\node_modules\sequelize\lib\dialects\abstract\query.js:87:15)
    at Function.formatBindParameters (D:\projects\servavillage\cloud-infrastructure\deploy\express\functions\node_modules\sequelize\lib\dialects\mysql\query.js:26:25)
    at Promise.try (D:\projects\servavillage\cloud-infrastructure\deploy\express\functions\node_modules\sequelize\lib\sequelize.js:628:52)

Please check screen shot.

![error](https://user-images.githubusercontent.com/19203741/86034086-9997b980-ba57-11ea-9fce-8fcc385376a7.png)

**Comment by sushantdhiman** [comment]
Sequelize requires you to file new issues with a specific [issue template](https://github.com/sequelize/sequelize/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). Please don't ignore our [contribution guidelines](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md#issues) and template structure. They help us quickly triage issues.

Note that this issue will be closed for not following the issue template. You may open a new issue or update this one with correct template. You can add any additional information to your issue.

----------------------------

Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com).
