### ISSUE TITLE
Reconnect after 'Connection terminated unexpectedly' error event

### ISSUE THREAD

**Issue by kaiyer-de** [sequelize/sequelize#12474]
### What are you doing?

I'm trying to connect a NodeJS application to a Postgres database. Everything works fine until my database container suddenly stops working , the connection is terminated and the application crashes. To force this behavior I just stop my database container and restart it. 

Here is my configuration:

```js
const sequelize = new Sequelize(
  database,
  username,
  password,
  {
    host
    port,
    dialect: 'postgres',
    logging: false,
    operatorsAliases: Sequelize.Op,
    retry: {
      match: [
        Sequelize.ConnectionError,
        Sequelize.ConnectionRefusedError,
        Sequelize.HostNotReachableError,
        Sequelize.InvalidConnectionError,
        Sequelize.ConnectionTimedOutError,
      ],
      max: Infinity,
    },
    pool: {
      max: 3,
      min: 0,
      idle: 10000,
      evict: 10000,
      acquire: 10000,
    },
  },
);
```

### What do you expect to happen?

As soon as the database is up and running Sequelize should reconnect or give me some other way to handle the error.

### What is actually happening?

The application crashes with the following output:

```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: Connection terminated unexpectedly
    at Connection.con.once (/node_modules/pg/lib/client.js:272:71)
    at Object.onceWrapper (events.js:286:20)
    at Connection.emit (events.js:198:13)
    at Socket.stream.on (/node_modules/pg/lib/connection.js:102:10)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at connectedErrorHandler (/node_modules/pg/lib/client.js:221:10)
    at Connection.con.once (/node_modules/pg/lib/client.js:289:9)
    at Object.onceWrapper (events.js:286:20)
    [... lines matching original stack trace ...]
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

### Environment

- Sequelize version: 6.3.0 
- Node.js version: v10.21.0 
- Operating System: macOS / Debian

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [x] I don't know, I was using postgres, with connector library version 8.2.1 and database version 10.10

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by kaiyer-de** [comment]
This was not an issue with sequelize, sorry if i caused any inconveniences
