### ISSUE TITLE
use_env_variable returns undefined because not string value

### ISSUE THREAD

**Issue by kzunino** [sequelize/sequelize#12528]
**What you are doing?**
I am trying to deploy a PERN app to Heroku using sequelize. When I configure my production settings in the config.js file as per sequelize-CLI docs I am throwing an error:

``` 

internal/validators.js:107
 throw new ERR_INVALID_ARG_TYPE(name, 'string', value);

 TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined
at validateString (internal/validators.js:107:11)
at Url.parse (url.js:155:3)
at Object.urlParse [as parse] (url.js:150:13)
at new Sequelize (/app/node_modules/sequelize/lib/sequelize.js:187:28)
at Object.<anonymous> (/app/models/index.js:14:15) 

```

**Post a minimal code sample that reproduces the issue, including models and associations**
```
production: {
    use_env_variable: process.env.DATABASE_URL,
    dialect: 'postgres',
    dialectOptions: {
      ssl: {
        require: true,
        rejectUnauthorized: false, // <<<<<<< YOU NEED THIS TO FIX UNHANDLED REJECTION 
      },
    },
  },
```
**What do you expect to happen?**
I expect the environment variable, which is effectively a URI connection string to the postgress database add-on in Heroku to parse the string.

**What is actually happening?**
What is happening is that use_env_variable is being send as an argument to `/app/node_modules/sequelize/lib/sequelize.js:187:28` and inside this module it is passed as an object, not a string. Below is a snippet of the module where the problem occurs. `url.parse(options[0])` expects to accept a string as an argument and is instead given an object which is undefined. If i modify this snippet to accept the value as per the documentation like this `const urlParts = url.parse(options.use_env_variable, true);` I don't seem to run into the same error again. I get an error about the SSL, which I fixed from an earlier bug report by changing my production figuration.

```
constructor(database, username, password, options) {
    let config;

    if (arguments.length === 1 && typeof database === 'object') {
      // new Sequelize({ ... options })
      options = database;
      config = _.pick(options, 'host', 'port', 'database', 'username', 'password');
    } else if (
      (arguments.length === 1 && typeof database === 'string') ||
      (arguments.length === 2 && typeof username === 'object')
    ) {
      // new Sequelize(URI, { ... options })

      config = {};
      options = username || {};

      // url.parse wants to access the object like an array, however, first item is always undefined and it 
      // needs to access the use_env_variable, which is attached to username argument
     // const urlParts = url.parse(options.use_env_variable, true);

      const urlParts = url.parse(arguments[0], true);

      options.dialect = urlParts.protocol.replace(/:$/, '');
      options.host = urlParts.hostname;
```

Which dialect you are using (postgres, mysql etc)?
**Which sequelize version you are using?**
```
    "node": ^12.0.0
    "sequelize": "^5.21.11",
    "sequelize-cli": "^5.5.1"
```

**Comment by bozzmob** [comment]
I am facing the same issue.


```

internal/validators.js:120
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Url.parse (url.js:159:3)
    at Object.urlParse [as parse] (url.js:154:13)
    at new Sequelize (/mnt/d/work/roughwork/backend/node_modules/sequelize/lib/sequelize.js:185:28)
    at Object.<anonymous> (/mnt/d/work/roughwork/backend/src/sequelize.js:11:19)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19) {
  code: 'ERR_INVALID_ARG_TYPE'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! youtubeclone-backend@1.0.0 start: `node src/server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the youtubeclone-backend@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by sasa6277** [comment]
I have same issue
```
Sequelize CLI [Node: 12.16.1, CLI: 5.5.1, ORM: 5.22.3]

Loaded configuration file "config\config.json".
Using environment "development".

ERROR: Error parsing url: undefined


```

**Comment by zkinsk** [comment]
This has worked for me. 
```
use_env_variable: DATABASE_URL,
```

I don't think you need `process.env` as you are already declaring `use_env_variable`

**Comment by agus7fauzi** [comment]
i have no ide, anyone can give other solution?

**Comment by ArthurGuez** [comment]
> This has worked for me.
> 
> ```
> use_env_variable: DATABASE_URL,
> ```
> 
> I don't think you need `process.env` as you are already declaring `use_env_variable`

Could you be more specific please?
Where did you use : use_env_variable: DATABASE_URL ?
Thanks

**Comment by zkinsk** [comment]
@ArthurGuez  So in the intial example:
```
production: {
    use_env_variable: process.env.DATABASE_URL,
    dialect: 'postgres',
    dialectOptions: {
      ssl: {
        require: true,
        rejectUnauthorized: false, // <<<<<<< YOU NEED THIS TO FIX UNHANDLED REJECTION 
      },
    },
  },
```

I instead did this: 

```
production: {
    use_env_variable: DATABASE_URL,
    dialect: 'postgres',
    dialectOptions: {
      ssl: {
        require: true,
        rejectUnauthorized: false, // <<<<<<< YOU NEED THIS TO FIX UNHANDLED REJECTION 
      },
    },
  },
```
Because you are already saying find this as an environment variable with `use_env_variable`

**Comment by ArthurGuez** [comment]
Thanks @zkinsk :)

It's working for me now 👍

**Comment by amauryplayero** [comment]
I am having the same issue

**Comment by ephys** [comment]
Looking into sequelize-cli's source code, `use_env_variable` must be the name of the environment variable, as a string. So to fix the above example:

```javascript
production: {
    use_env_variable: 'DATABASE_URL',
    dialect: 'postgres',
    dialectOptions: {
      ssl: {
        require: true,
        rejectUnauthorized: false, // <<<<<<< YOU NEED THIS TO FIX UNHANDLED REJECTION 
      },
    },
  },
```
