### ISSUE TITLE
Sequelize error: Dialect needs to be explicitly supplied as of v4.0.0

### ISSUE THREAD

**Issue by Arya4514** [sequelize/sequelize#12645]
when i run npm start dev or any other environment it shows the follwoing error

Error: Dialect needs to be explicitly supplied as of v4.0.0
    at new Sequelize (H:\demo\Node_Shop\node_modules\sequelize\lib\sequelize.js:281:13)
    at Object.<anonymous> (H:\demo\Node_Shop\models\index.js:5:19)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (H:\demo\Node_Shop\server.js:3:10)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)

i dont able to know how to add production,development and test
 
"Sequelize error: Dialect needs to be explicitly supplied as of v4.0.0" 

this is my [repository](https://github.com/Arya4514/node_sequelize)

**Comment by thecpdubguy** [comment]
In your models/index.js
```node
const dbConfig = require("../config/db.config");

const Sequelize = require("sequelize");
const sequelize = new Sequelize(dbConfig.DB, dbConfig.USER, dbConfig.PASSWORD, {
  host: dbConfig.HOST,
  dialect: dbConfig.DIALECT,
  operatorsAliases: false,

});
```

The
```javascript
const dbConfig = require("../config/db.config")
```
needs to refer to the environment. Something like
```javascript
const dbConfig = require("../config/db.config")['development']
```

**Comment by Arya4514** [comment]
> In your models/index.js
> 
> ```js
> const dbConfig = require("../config/db.config");
> 
> const Sequelize = require("sequelize");
> const sequelize = new Sequelize(dbConfig.DB, dbConfig.USER, dbConfig.PASSWORD, {
>   host: dbConfig.HOST,
>   dialect: dbConfig.DIALECT,
>   operatorsAliases: false,
> 
> });
> ```
> 
> The
> 
> ```js
> const dbConfig = require("../config/db.config")
> ```
> 
> needs to refer to the environment. Something like
> 
> ```js
> const dbConfig = require("../config/db.config")['development']
> ```

i have done changes but still its showing new error

H:\demo\Node_Shop\models\index.js:6
const sequelize = new Sequelize(dbConfig.DB, dbConfig.USER, dbConfig.PASSWORD, {
                                         ^

TypeError: Cannot read property 'DB' of undefined
    at Object.<anonymous> (H:\demo\Node_Shop\models\index.js:6:42)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (H:\demo\Node_Shop\server.js:3:10)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! signup@1.0.0 start: `node server.js "dev"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the signup@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Dell\AppData\Roaming\npm-cache\_logs\2020-08-31T04_19_53_928Z-debug.log

**Comment by thecpdubguy** [comment]
I see that you changed the code to
```js
const dbConfig = require("../config/db.config")[process.env.NODE_ENV];
```

Make sure NODE_ENV is set

**Comment by Arya4514** [comment]
> I see that you changed the code to
> 
> ```js
> const dbConfig = require("../config/db.config")[process.env.NODE_ENV];
> ```
> 
> Make sure NODE_ENV is set

i have seted NODE_ENV in package.json file 

`      "scripts": {
        "start": "node server.js",
        "dev": "cross-env NODE_ENV=development & nodemon server.js",
        "test": "cross-env NODE_ENV=test jest --testTimeout=10000",
        "prod": "cross-env NODE_ENV=production & nodemon server.js"
     },`

**Comment by thecpdubguy** [comment]
Are you still running `npm start dev`? this is running the `npm start` script, to run dev or prod, you must use `npm run dev` or `npm run prod`

https://docs.npmjs.com/cli/run-script

**Comment by Arya4514** [comment]
> Are you still running `npm start dev`? This is running the `npm start` script, to run dev or prod, you must use `npm run dev` or `npm run prod`
> 
> start does not have a NODE_ENV set so `const dbConfig = require("../config/db.config")[process.env.NODE_ENV];` is undefined
> 
> https://docs.npmjs.com/cli/run-script

D:\demos\Node-shop>npm run dev

> signup@1.0.0 dev D:\demos\Node-shop
> cross-env NODE_ENV=development & nodemon server.js

[nodemon] 2.0.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server.js`
D:\demos\Node-shop\models\index.js:5
const sequelize = new Sequelize(dbConfig.DB, dbConfig.USER, dbConfig.PASSWORD, {
                                         ^

TypeError: Cannot read property 'DB' of undefined
    at Object.<anonymous> (D:\demos\Node-shop\models\index.js:5:42)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\demos\Node-shop\server.js:3:10)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by thecpdubguy** [comment]
The next issue is with your script.

`cross-env NODE_ENV=development & nodemon server.js` is not passing NODE_ENV as an environment variable because the & is making the command run in the background. The line should be `cross-env NODE_ENV=developmen nodemon server.js`

This is not a sequelize issue. Please don't continue debugging your code here.

**Comment by Arya4514** [comment]
thank you for help
