### ISSUE TITLE
Error: Unknown prepared statement handler (2) given to mysqld_stmt_execute

### ISSUE THREAD

**Issue by AfterThreeYears** [sequelize/sequelize#12656]
### What are you doing?

I updated the database with Sequelize, but I encountered the following error
```js
const http = require('http');
const Sequelize = require('sequelize');

const sequelize = new Sequelize('test', 'root', '123456', {
  host: '127.0.0.1',
  port: 3306,
  dialect: 'mysql',
});

const {
  BIGINT,
  STRING,
} = Sequelize;

class Nav extends Sequelize.Model {}
Nav.init({
  id: {
    type: BIGINT({
      length: 20,
      unsigned: true,
    }),
    primaryKey: true
  },
  title: {
    type: STRING,
    allowNull: false,
  },
}, {
  timestamps: true,
  tableName: 'mall_config_navigation',
  underscored: true,
  freezeTableName: true,
  createdAt: 'gmt_created',
  updatedAt: 'gmt_modified',
  sequelize,
});


http.createServer((req, res) => {
  Nav.update({
    title: 'new title',
  }, {
    where: {
      id: 1,
    },
  }).then(() => {
    console.log('success');
  }).catch(error => {
    console.error('error', error);
  })
  res.writeHead(200, { 'Content-Type': 'text/plain' });
  res.end('hello');
}).listen(8081, () => {
  console.log('http//:127.0.0.1:8081');
});
```

**Here is the link to the SSCCE for this issue:** LINK-HERE 

```js
// You can delete this code block if you have included a link to your SSCCE above!
// MINIMAL, SELF-CONTAINED code here (SSCCE/MCVE/reprex)
```

### What do you expect to happen?

_I wanted Update successful!_

### What is actually happening?

_The output But it will fail!_

```js
Executing (default): UPDATE `mall_config_navigation` SET `title`=?,`gmt_modified`=? WHERE `id` = ?
success
Executing (default): UPDATE `mall_config_navigation` SET `title`=?,`gmt_modified`=? WHERE `id` = ?
error DatabaseError [SequelizeDatabaseError]: Unknown prepared statement handler (2) given to mysqld_stmt_execute
    at Query.formatError (E:\wy\industry-wechat-node\node_modules\sequelize\lib\dialects\mysql\query.js:245:16)
    at Execute.handler [as onResult] (E:\wy\industry-wechat-node\node_modules\sequelize\lib\dialects\mysql\query.js:51:23)
    at Execute.execute (E:\wy\industry-wechat-node\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (E:\wy\industry-wechat-node\node_modules\mysql2\lib\connection.js:417:32)
    at PacketParser.onPacket (E:\wy\industry-wechat-node\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (E:\wy\industry-wechat-node\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (E:\wy\industry-wechat-node\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
  name: 'SequelizeDatabaseError',
  parent: Error: Unknown prepared statement handler (2) given to mysqld_stmt_execute
      at Packet.asError (E:\wy\industry-wechat-node\node_modules\mysql2\lib\packets\packet.js:712:17)
      at Execute.execute (E:\wy\industry-wechat-node\node_modules\mysql2\lib\commands\command.js:28:26)
      at Connection.handlePacket (E:\wy\industry-wechat-node\node_modules\mysql2\lib\connection.js:417:32)
      at PacketParser.onPacket (E:\wy\industry-wechat-node\node_modules\mysql2\lib\connection.js:75:12)
      at PacketParser.executeStart (E:\wy\industry-wechat-node\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (E:\wy\industry-wechat-node\node_modules\mysql2\lib\connection.js:82:25)
      at Socket.emit (events.js:311:20)
      at addChunk (_stream_readable.js:294:12)
      at readableAddChunk (_stream_readable.js:275:11)
      at Socket.Readable.push (_stream_readable.js:209:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
    code: 'ER_UNKNOWN_STMT_HANDLER',
    errno: 1243,
    sqlState: 'HY000',
    sqlMessage: 'Unknown prepared statement handler (2) given to mysqld_stmt_execute',
    sql: 'UPDATE `mall_config_navigation` SET `title`=?,`gmt_modified`=? WHERE `id` = ?',
    parameters: [ 'new title', '2020-08-28 16:36:34', 1 ]
  },
  original: Error: Unknown prepared statement handler (2) given to mysqld_stmt_execute
      at Packet.asError (E:\wy\industry-wechat-node\node_modules\mysql2\lib\packets\packet.js:712:17)
      at Execute.execute (E:\wy\industry-wechat-node\node_modules\mysql2\lib\commands\command.js:28:26)
      at Connection.handlePacket (E:\wy\industry-wechat-node\node_modules\mysql2\lib\connection.js:417:32)
      at PacketParser.onPacket (E:\wy\industry-wechat-node\node_modules\mysql2\lib\connection.js:75:12)
      at PacketParser.executeStart (E:\wy\industry-wechat-node\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (E:\wy\industry-wechat-node\node_modules\mysql2\lib\connection.js:82:25)
      at Socket.emit (events.js:311:20)
      at addChunk (_stream_readable.js:294:12)
      at readableAddChunk (_stream_readable.js:275:11)
      at Socket.Readable.push (_stream_readable.js:209:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
    code: 'ER_UNKNOWN_STMT_HANDLER',
    errno: 1243,
    sqlState: 'HY000',
    sqlMessage: 'Unknown prepared statement handler (2) given to mysqld_stmt_execute',
    sql: 'UPDATE `mall_config_navigation` SET `title`=?,`gmt_modified`=? WHERE `id` = ?',
    parameters: [ 'new title', '2020-08-28 16:36:34', 1 ]
  },
  sql: 'UPDATE `mall_config_navigation` SET `title`=?,`gmt_modified`=? WHERE `id` = ?',
  parameters: [ 'new title', '2020-08-28 16:36:34', 1 ]
}
```

### Additional context

I think may be related to this [question](https://github.com/sidorares/node-mysql2/issues/805), I am [here](https://github.com/sequelize/sequelize/blob/v5.22.3/lib/dialects/mysql/query.js#L41) to add the **connection.unprepare(sql);** And the error disappears

### Environment

- Mysql: 5.7.20-19-log , **I think this is very important and has not been reproduced in other versions**。
- Sequelize version: 5.22.3
- Node.js version: 12.16.1
- mysql2 version: 2.1.0
- Operating System: Windows10 or MaxOS

### How does this problem relate to dialects?

- [x] I think this problem happens only for the following dialect(s): mysql
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX
- [ ] I think this problem happens regardless of the dialect.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by perpyy** [comment]
You can try adding a configuration:  pool.min = 0
```json
const sequelize = new Sequelize('test', 'root', '123456', {
  host: '127.0.0.1',
  port: 3306,
  dialect: 'mysql',
  pool: {
     min: 0
  }
});
```
