### ISSUE TITLE
[question] column defaultValue does not allowed to set Sequelize.literal?

### ISSUE THREAD

**Issue by ghost** [sequelize/sequelize#12678]
### What was unclear/insufficient/not covered in the documentation

I found some suggestions that using liter('CURRENT_TIMESTAMP') to setting defaultValue for Date type.

But i get next exception
* version
  * sequelize@6.3.5
  * dialet: mysql
* code
```javascript
queryInterface.createTable('TestTable', {
    Id: {
    type: DataTypes.STRING(30),
    allowNull: false,
    primaryKey: true,
  },  
  CreatedAt: {
    type: DataTypes.DATE,
    defaultValue: Sequelize.literal("CURRENT_TIMESTAMP")
  }
}, {
  timestamp: false
});
```
* exception
```
error: Error: Invalid value Literal { val: 'CURRENT_TIMESTAMP' }
    at Object.escape (D:\se\node_modules\sequelize\lib\sql-string.js:65:11)
    at MySQLQueryGenerator.escape (D:\se\node_modules\sequelize\lib\dialects\abstract\query-generator.js:985:22)
    at MySQLQueryGenerator.attributeToSQL (D:\code\se\node_modules\sequelize\lib\dialects\mysql\query-generator.js:379:36)
    at MySQLQueryGenerator.attributesToSQL (D:\se\node_modules\sequelize\lib\dialects\mysql\query-generator.js:434:45)
    at MySQLQueryInterface.createTable (D:\se\node_modules\sequelize\lib\dialects\abstract\query-interface.js:222:38)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

defaultValue not allowed allowed literal?
And how can i set defaultValue CURRENT_TIMESTAMP for DataTypes.Date on mysql?

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ O ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ O ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by tysoncadenhead** [comment]
I'm getting the same error on `Sequelize CLI [Node: 14.6.0, CLI: 5.1.3, ORM: 5.21.6]`
