### ISSUE TITLE
Uncaught exception occasionally thrown during connection in Postgres

### ISSUE THREAD

**Issue by dtjohnson** [sequelize/sequelize#12704]
## Issue Description

Postgres connections can result in uncaught exceptions if an error occurs shortly after new connection is made.

### What are you doing?

I've seen random issues in my production application where uncaught "Connection terminated unexpectedly" errors are thrown by the pg client and are not handled by the connection manager, which crashes the application. I was able to reproduce this using some minimal code that will queue up a bunch of connections that just have a long delay and then force killing them through the Postgres console.

```js
const Sequelize = require('sequelize');

const sequelize = new Sequelize('DB', 'USER', 'PASS', {
    dialect: 'postgres',
    host: 'HOST',
    pool: {
        min: 1,
        max: 1,         
    }
});

for (let i = 0; i < 20; i++) {
    sequelize.query('SELECT pg_sleep(10000)').catch(err => console.log(`Error during query: ${err.message}`));
}
```
Right after starting this, I ran the following in the Postgres console repeatedly as fast as possible:
```sql
select pg_terminate_backend(pid) from pg_stat_activity where datname='DB';
```

This will usually result in a crash. This seems to be happening because a [connection startup query](https://github.com/sequelize/sequelize/blob/master/src/dialects/postgres/connection-manager.js#L222) is being issued _before_ the [error handler is registered](https://github.com/sequelize/sequelize/blob/master/src/dialects/postgres/connection-manager.js#L232).

While my example is contrived, I suspect that in my production application, the pool is occasionally making connections to the database that are succeeding, but that startup query is failing, which results in an uncaught exception that crashes the application.

### What do you expect to happen?

I expect the error to be handled rather than crash the application.

### What is actually happening?

The application crashes with an uncaught exception thrown from an error before the error handler is subscribed. Below is some sample console output. Note that I added an additional debug line before [L222](https://github.com/sequelize/sequelize/blob/master/src/dialects/postgres/connection-manager.js#L222) to show the query issued before the error handler subscription.

```
  sequelize:pool pool created with max/min: 1/1, no replication +0ms
  sequelize:connection:pg connection acquired +0ms
  sequelize:connection:pg Executing query SET client_min_messages TO warning;SET TIME ZONE INTERVAL '+00:00' HOUR TO MINUTE; +1ms
  sequelize:connection:pg connection acquired +246ms
  sequelize:connection:pg Executing query SET client_min_messages TO warning;SET TIME ZONE INTERVAL '+00:00' HOUR TO MINUTE; +0ms
  sequelize:pool connection acquired +663ms
  sequelize:sql:pg Executing (default): SELECT pg_sleep(10000) +0ms
Executing (default): SELECT pg_sleep(10000)
  sequelize:pool connection released +716ms
  sequelize:pool connection acquired +1ms
  sequelize:sql:pg Executing (default): SELECT pg_sleep(10000) +714ms
Executing (default): SELECT pg_sleep(10000)
Error during query: terminating connection due to administrator command
  sequelize:connection:pg connection error Connection terminated unexpectedly +972ms
  sequelize:pool connection released +29ms
Error during query: Connection terminated unexpectedly
  sequelize:pool connection destroy +0ms
  sequelize:connection:pg connection acquired +138ms
  sequelize:connection:pg Executing query SET client_min_messages TO warning;SET TIME ZONE INTERVAL '+00:00' HOUR TO MINUTE; +0ms
  sequelize:pool connection acquired +277ms
  sequelize:sql:pg Executing (default): SELECT pg_sleep(10000) +306ms
Executing (default): SELECT pg_sleep(10000)
  sequelize:pool connection released +58ms
  sequelize:pool connection acquired +0ms
  sequelize:sql:pg Executing (default): SELECT pg_sleep(10000) +58ms
Executing (default): SELECT pg_sleep(10000)
Error during query: terminating connection due to administrator command
  sequelize:connection:pg connection error Connection terminated unexpectedly +199ms
  sequelize:pool connection released +1ms
Error during query: Connection terminated unexpectedly
  sequelize:pool connection destroy +0ms
  sequelize:connection:pg connection acquired +130ms
  sequelize:connection:pg Executing query SET client_min_messages TO warning;SET TIME ZONE INTERVAL '+00:00' HOUR TO MINUTE; +0ms
  sequelize:pool connection acquired +165ms
  sequelize:sql:pg Executing (default): SELECT pg_sleep(10000) +167ms
Executing (default): SELECT pg_sleep(10000)
  sequelize:pool connection released +215ms
  sequelize:pool connection acquired +0ms
  sequelize:sql:pg Executing (default): SELECT pg_sleep(10000) +214ms
Executing (default): SELECT pg_sleep(10000)
Error during query: terminating connection due to administrator command
  sequelize:connection:pg connection error Connection terminated unexpectedly +250ms
  sequelize:pool connection released +1ms
Error during query: Connection terminated unexpectedly
  sequelize:pool connection destroy +0ms
  sequelize:connection:pg connection acquired +215ms
  sequelize:connection:pg Executing query SET client_min_messages TO warning;SET TIME ZONE INTERVAL '+00:00' HOUR TO MINUTE; +0ms
  sequelize:pool connection acquired +258ms
  sequelize:sql:pg Executing (default): SELECT pg_sleep(10000) +259ms
Executing (default): SELECT pg_sleep(10000)
  sequelize:pool connection released +144ms
  sequelize:pool connection acquired +0ms
  sequelize:sql:pg Executing (default): SELECT pg_sleep(10000) +145ms
Executing (default): SELECT pg_sleep(10000)
Error during query: terminating connection due to administrator command
  sequelize:connection:pg connection error Connection terminated unexpectedly +189ms
  sequelize:pool connection released +1ms
Error during query: Connection terminated unexpectedly
  sequelize:pool connection destroy +1ms
  sequelize:connection:pg connection acquired +218ms
  sequelize:connection:pg Executing query SET client_min_messages TO warning;SET TIME ZONE INTERVAL '+00:00' HOUR TO MINUTE; +0ms
  sequelize:pool connection acquired +259ms
  sequelize:sql:pg Executing (default): SELECT pg_sleep(10000) +260ms
Executing (default): SELECT pg_sleep(10000)
  sequelize:pool connection released +334ms
  sequelize:pool connection acquired +0ms
  sequelize:sql:pg Executing (default): SELECT pg_sleep(10000) +334ms
Executing (default): SELECT pg_sleep(10000)
Error during query: terminating connection due to administrator command
  sequelize:connection:pg connection error Connection terminated unexpectedly +378ms
  sequelize:pool connection released +2ms
Error during query: Connection terminated unexpectedly
  sequelize:pool connection destroy +1ms
  sequelize:connection:pg connection acquired +166ms
  sequelize:connection:pg Executing query SET client_min_messages TO warning;SET TIME ZONE INTERVAL '+00:00' HOUR TO MINUTE; +0ms
  sequelize:pool connection acquired +311ms
  sequelize:sql:pg Executing (default): SELECT pg_sleep(10000) +314ms
Executing (default): SELECT pg_sleep(10000)
  sequelize:pool connection released +258ms
  sequelize:pool connection acquired +0ms
  sequelize:sql:pg Executing (default): SELECT pg_sleep(10000) +258ms
Executing (default): SELECT pg_sleep(10000)
Error during query: terminating connection due to administrator command
  sequelize:connection:pg connection error Connection terminated unexpectedly +404ms
  sequelize:pool connection released +1ms
Error during query: Connection terminated unexpectedly
  sequelize:pool connection destroy +0ms
  sequelize:connection:pg connection acquired +338ms
  sequelize:connection:pg Executing query SET client_min_messages TO warning;SET TIME ZONE INTERVAL '+00:00' HOUR TO MINUTE; +0ms
Error during query: terminating connection due to administrator command
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: Connection terminated unexpectedly
    at Connection.<anonymous> (REDACTED/node_modules/pg/lib/client.js:123:73)
    at Object.onceWrapper (events.js:420:28)
    at Connection.emit (events.js:314:20)
    at Socket.<anonymous> (REDACTED/node_modules/pg/lib/connection.js:102:12)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1244:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on Client instance at:
    at Client._handleErrorEvent (REDACTED/node_modules/pg/lib/client.js:310:10)
    at Connection.<anonymous> (REDACTED/node_modules/pg/lib/client.js:140:16)
    at Object.onceWrapper (events.js:420:28)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

### Environment

- Sequelize version: 6.3.5
- Node.js version: 14.8.0
- Operating System: OS X 10.14.6
- If TypeScript related: No

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [x] I think this problem happens only for the following dialect(s): Postgres
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by oLejikOnMyEvent** [comment]
same problem.
After docker restart with nestjs and pg
