### ISSUE TITLE
Id autoIncrement is not working correctly

### ISSUE THREAD

**Issue by Zolyder** [sequelize/sequelize#12731]
I used the method `bulkCreate()` to send 1000 users (with the ids present), and everything works correctly.

Then I decided to use the method `create()` after post the 1000 users, but apparently bulkCreate does not detect the last id, and when I use the method `create()`, it gives me this error:

```js
original: error: duplicate key value violates unique constraint "users_pkey"
      at Parser.parseErrorMessage (/Users/admin/Documents/Development/Job/Challenges/Owlish back and front/API-Google-Maps/Backend-Google-Maps/node_modules/pg-protocol/dist/parser.js:278:15)
      at Parser.handlePacket (/Users/admin/Documents/Development/Job/Challenges/Owlish back and front/API-Google-Maps/Backend-Google-Maps/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/Users/admin/Documents/Development/Job/Challenges/Owlish back and front/API-Google-Maps/Backend-Google-Maps/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/Users/admin/Documents/Development/Job/Challenges/Owlish back and front/API-Google-Maps/Backend-Google-Maps/node_modules/pg-protocol/dist/index.js:8:42)
      at Socket.emit (events.js:315:20)
      at addChunk (_stream_readable.js:295:12)
      at readableAddChunk (_stream_readable.js:271:9)
      at Socket.Readable.push (_stream_readable.js:212:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
    length: 180,
    severity: 'ERROR',
    code: '23505',
    detail: 'Key (id)=(9) already exists.',
    ...
```
If you see, it's sending (id)=(9). If I call again method `create()` is increasing every call to method `create()` (id=10, id=11, ...), when apparently should be after 1000. id must be after 1001, 1002, 1003...

I found a problem similar to this [Link](https://github.com/sequelize/sequelize/issues/1186).

### Environment

- Sequelize version: 6,3,5 
- Node.js version: 12.18.3 
- Operating System: Catalina 10.15.7

**Comment by ZhuchkouAA** [comment]
the same thing with me. does not autoincrement work with bulk? is there any way out solution?
