### ISSUE TITLE
UnhandledPromiseRejectionWarning: SequelizeValidationError: notNull Violation: Lead.id cannot be null

### ISSUE THREAD

**Issue by spantheslayer** [sequelize/sequelize#12770]
```
"use strict";
module.exports = (Sequelize, DataTypes) => {
  var Lead = Sequelize.define("Lead", {
    id: {
      allowNull: false,
      primaryKey: true,
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUID4,
    },
   email: {
      allowNull: false,
      type: DataTypes.STRING,
    },
  });
  return Lead;
};
```

even If I set the id property allowNull: false  it is giving me the error .

When I remove the whole attribute it creates the table but gives another warning error 

```
Executing (default): INSERT INTO "Leads" ("email","createdAt","updatedAt") VALUES ($1,$2,$3) RETURNING "id","email","createdAt","updatedAt";
(node:16724) UnhandledPromiseRejectionWarning: SequelizeDatabaseError: null value in column "id" violates not-null constraint
    at Query.formatError (/home/span/Desktop/p/express-node/node_modules/sequelize/lib/dialects/postgres/query.js:386:16)
    at Query.run (/home/span/Desktop/p/express-node/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /home/span/Desktop/p/express-node/node_modules/sequelize/lib/sequelize.js:619:16
    at async PostgresQueryInterface.insert (/home/span/Desktop/p/express-node/node_modules/sequelize/lib/dialects/abstract/query-interface.js:734:21)
    at async model.save (/home/span/Desktop/p/express-node/node_modules/sequelize/lib/model.js:3954:35)
    at async Function.create (/home/span/Desktop/p/express-node/node_modules/sequelize/lib/model.js:2207:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16724) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16724) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Here is the link to the SSCCE for this issue:**  https://ci.appveyor.com/project/papb/sequelize-sscce/builds/35822055 

This should insert the table but it gives this weird issue

- Sequelize version: 6.3.5
- Node.js version: 14.14.0
- Operating System: manjaro gnome mikah 20.1.1
- "dialect": "postgres",

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time but I don't know how to start, I would need guidance.

**Comment by ayushnigamsworld** [comment]
Umm, sorry but your id column is Primary Key.
It can't be null in any case possible.
Can you specify what Sequelize function you are using and how ?
Because I don't see id going in the Insert SQL statement.
