### ISSUE TITLE
Error: Cannot pass SequelizeMethod as a bind parameter - use escape instead

### ISSUE THREAD

**Issue by gabmmontenegro** [sequelize/sequelize#12781]
### What are you doing?

Updating a boolean field by filtering the query with a field of type CHAR(32).BINARY which represents a SHA256 hash.

```javascript
await Push.update(
  { is_active: false },
  {
    where: {
      identifier: Sequelize.fn('unhex', '46070d4bf934fb0d4b06d9e2c46e346944e322444900a435d7d9a95e6d7435f5')
    },
  }
```

**Here is the link to the SSCCE for this issue:** 
- [FORK](https://github.com/gabmmontenegro/sequelize-sscce/blob/patch-1/src/sscce.js)
- [PULL REQUEST](https://github.com/papb/sequelize-sscce/pull/122)
- [CI BUILD: MYSQL JOB FAILURE](https://travis-ci.com/github/papb/sequelize-sscce/jobs/403582780)

### What do you expect to happen?

Updated row.

### What is actually happening?

The same behavior of my environment as shown below was reproduced in the SSCCE CI build - links above.
```
2020-10-22T05:26:27.263Z|error|a9ed004571b145758b28a5cd3744610b|1:2|DELETE:/v1/account/push?identifier=46070d4bf934fb0d4b06d9e2c46e346944e322444900a435d7d9a95e6d7435f5|Error: Cannot pass SequelizeMethod as a bind parameter - use escape instead
    at MySQLQueryGenerator.format (/home/gabrielm/development/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1004:15)
    at MySQLQueryGenerator.whereItemQuery (/home/gabrielm/development/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2356:46)
    at /home/gabrielm/development/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2247:25
    at Array.forEach (<anonymous>)
    at MySQLQueryGenerator.whereItemsQuery (/home/gabrielm/development/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2245:35)
    at MySQLQueryGenerator.whereQuery (/home/gabrielm/development/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2218:24)
    at MySQLQueryGenerator.updateQuery (/home/gabrielm/development/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:408:116)
    at MySQLQueryInterface.bulkUpdate (/home/gabrielm/development/api/node_modules/sequelize/lib/dialects/abstract/query-interface.js:861:37)
    at Function.update (/home/gabrielm/development/api/node_modules/sequelize/lib/model.js:3175:54)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Function.removePush (/home/gabrielm/development/api/src/app/services/PushService.js:86:30)
    at async Function.delete (/home/gabrielm/development/api/src/app/services/PushService.js:56:21)
    at async delete (/home/gabrielm/development/api/src/app/controllers/PushController.js:23:23)
```

### Additional context

- The same filtering query on Push.findOne() works fine.

### Environment

- Sequelize version: tested on 5.21.1 and 6.3.5 versions with same behavior 
- Node.js version: v12.16.1
- Operating System: Ubuntu 18.04 LTS

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [X] I don't know, I was using mysql, with connector library version mysql2 (1.7.0 and 2.2.5) and database version 5.7

### Would you be willing to resolve this issue by submitting a Pull Request?
- [ ] Yes, I have the time and I know how to start.
- [X] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by Karbust** [comment]
I have this issue to, on 6.3.4 and 6.3.5.

I use the same code on two separate functions but only one gives this error. They're both wrapped with Promise.all and transaction, but one works and the other doesn't.

I'm using sequelize.fn('PASSWORD', string) on both functions.

**Comment by gabmmontenegro** [comment]
Hi @Karbust - thanks for contributing to this thread. 

Well done. It works good for both of us because we are dealing with a fixed-length field, but we should consider it as a temporary solution because LIKE operator affects the query performance.

This approach with a non-fixed length field brings other issues, including severe security vulnerabilities, once the query has potential to affect other rows. 

This is a very relevant fix for the next release.
