### ISSUE TITLE
ConnectionError [SequelizeConnectionError]: Failed to connect to 192.168.31.247:1433 - Cannot call write after a stream was destroyed

### ISSUE THREAD

**Issue by hohnworld** [sequelize/sequelize#12788]
**package.json**

```
{
  "name": "demo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "sequelize": "^6.3.5",
    "tedious": "^9.2.1"
  }
}
```

**index.js**

```
const { Sequelize } = require('sequelize');
const sequelize = new Sequelize('db_test', 'sa', 'Hohnsql52)', {
    host: '192.168.31.247',
    dialect:'mssql'
  });

async function test() {
    try {
        await sequelize.authenticate();
        console.log('1111111111111111111111111111111111');
    } catch (error) {
        console.error('0000000000000000000000000000000:', error);
    }
}

test();
```

```
D:\demo>node index.js
tedious deprecated The default value for "config.options.validateBulkLoadParameters" will change from `false` to `true` in the next major version of `tedious`. Set the value to `true` or `false` explicitly to silence this message. node_modules\sequelize\lib\dialects\mssql\connection-manager.js:63:28
(node:6432) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
0000000000000000000000000000000: ConnectionError [SequelizeConnectionError]: Failed to connect to 192.168.31.247:1433 - Cannot call write after a stream was destroyed
    at ConnectionManager.connect (D:\demo\node_modules\sequelize\lib\dialects\mssql\connection-manager.js:138:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  parent: ConnectionError: Failed to connect to 192.168.31.247:1433 - Cannot call write after a stream was destroyed
      at ConnectionError (D:\demo\node_modules\tedious\lib\errors.js:13:12)
      at Connection.socketError (D:\demo\node_modules\tedious\lib\connection.js:1653:56)
      at Socket.<anonymous> (D:\demo\node_modules\tedious\lib\connection.js:1417:14)
      at Socket.emit (events.js:327:22)
      at errorOrDestroy (internal/streams/destroy.js:108:12)
      at onwriteError (_stream_writable.js:418:5)
      at onwrite (_stream_writable.js:445:5)
      at doWrite (_stream_writable.js:399:11)
      at writeOrBuffer (_stream_writable.js:387:5)
      at Socket.Writable.write (_stream_writable.js:318:11) {
    code: 'ESOCKET'
  },
  original: ConnectionError: Failed to connect to 192.168.31.247:1433 - Cannot call write after a stream was destroyed
      at ConnectionError (D:\demo\node_modules\tedious\lib\errors.js:13:12)
      at Connection.socketError (D:\demo\node_modules\tedious\lib\connection.js:1653:56)
      at Socket.<anonymous> (D:\demo\node_modules\tedious\lib\connection.js:1417:14)
      at Socket.emit (events.js:327:22)
      at errorOrDestroy (internal/streams/destroy.js:108:12)
      at onwriteError (_stream_writable.js:418:5)
      at onwrite (_stream_writable.js:445:5)
      at doWrite (_stream_writable.js:399:11)
      at writeOrBuffer (_stream_writable.js:387:5)
      at Socket.Writable.write (_stream_writable.js:318:11) {
    code: 'ESOCKET'
  }
}

D:\demo>
```
![cs](https://user-images.githubusercontent.com/24633370/97115740-5c0c1a00-1733-11eb-8035-4d72793c81e2.png)

**Comment by creffect** [comment]
Please try: 

const sequelize = new Sequelize('db_test', 'sa', 'Hohnsql52)', {
    host: '192.168.31.247',
    dialect:'mssql',
    dialectOptions: {
            options: {
                encrypt: false
            }
        }
  });
