### ISSUE TITLE
issue with uuid on creating new Sequelize object 

### ISSUE THREAD

**Issue by yarinsn** [sequelize/sequelize#12796]
## Issue Description
App this crashing on startup while trying to create an instance of Sequelize.

### What are you doing?
trying to create an instance of Sequelize:
`sequelize = new Sequelize(config.dbname, null, null, config.options);`

### What is actually happening?
Azure logs:
```
2020-10-27T22:25:16.814947276Z Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './v4' is not defined by "exports" in /home/site/wwwroot/node_modules/sequelize/node_modules/uuid/package.json
2020-10-27T22:25:16.815013278Z     at applyExports (internal/modules/cjs/loader.js:490:9)
2020-10-27T22:25:16.815026078Z     at resolveExports (internal/modules/cjs/loader.js:506:23)
2020-10-27T22:25:16.815034678Z     at Function.Module._findPath (internal/modules/cjs/loader.js:634:31)
2020-10-27T22:25:16.815042978Z     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:27)
2020-10-27T22:25:16.815051179Z     at Function.Module._load (internal/modules/cjs/loader.js:841:27)
2020-10-27T22:25:16.815058979Z     at Module.require (internal/modules/cjs/loader.js:1025:19)
2020-10-27T22:25:16.815066979Z     at Module.patchedRequire [as require] (/home/site/wwwroot/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
2020-10-27T22:25:16.815075479Z     at require (internal/modules/cjs/helpers.js:72:18)
2020-10-27T22:25:16.815084279Z     at Object. (/home/site/wwwroot/node_modules/sequelize/lib/dialects/abstract/query-generator/transaction.js:3:16)
2020-10-27T22:25:16.815093580Z     at Module._compile (internal/modules/cjs/loader.js:1137:30)
2020-10-27T22:25:16.815101580Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
2020-10-27T22:25:16.815109480Z     at Module.load (internal/modules/cjs/loader.js:985:32)
2020-10-27T22:25:16.815118980Z     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
2020-10-27T22:25:16.815127280Z     at Module.require (internal/modules/cjs/loader.js:1025:19)
2020-10-27T22:25:16.815135281Z     at Module.patchedRequire [as require] (/home/site/wwwroot/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
2020-10-27T22:25:16.815143481Z     at require (internal/modules/cjs/helpers.js:72:18) {
2020-10-27T22:25:16.815151181Z   code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
2020-10-27T22:25:16.815159081Z }
```

### Environment
- sequelize@6.3.5
- node@12.16.3

### How does this problem relate to dialects?

- [ ]  I think this problem happens regardless of the dialect.
- [ ]  I think this problem happens only for the following dialect(s):
- [X]  I don't know, I was using mssql, with connector library version 6.1.1 and database version 12.0.2000.8 (Microsoft SQL Azure (RTM))

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ]  Yes, I have the time and I know how to start.
- [X]  Yes, I have the time but I don't know how to start, I would need guidance.
- [ ]  No, I don't have the time, although I believe I could do it if I had the time...
- [ ]  No, I don't have the time and I wouldn't even know how to start.

**Comment by yarinsn** [comment]
not a problem with Sequelize.
