### ISSUE TITLE
Adding Attributes on a Join Table Not Working

### ISSUE THREAD

**Issue by santiagogarza** [sequelize/sequelize#12820]
## Issue Description
It appears there may be a bug where attributes are not being set on a through table.

### What are you doing?
I have a Many-to-Many association defined between two models `UserModel` and `HangModel`, through a custom table `HangUsers`. 

```
const HangModel = rootRequire('/models/Hang');
const UserModel = rootRequire('/models/User');

const HangUsers = database.define('HangUsers', {
  id: {
    type: Sequelize.INTEGER(10).UNSIGNED,
    primaryKey: true,
    autoIncrement: true,
  },
  hangId: {
    type: Sequelize.INTEGER(10).UNSIGNED,
    references: {
      model: HangModel,
      key: 'id',
    },
  },
  userId: {
    type: Sequelize.INTEGER(10).UNSIGNED,
    references: {
      model: UserModel,
      key: 'id',
    },
  },
  rsvp: {
    type: Sequelize.STRING,
    allowNull: false,
    validate: {
      isIn: {
        args: [ 'pending', 'joined' ],
        msg: 'The rsvp provided is invalid',
      },
    },
  },
});

UserModel.hasMany(HangUsers, { as: 'invitations' });
HangModel.hasMany(HangUsers, { as: 'invites' });

UserModel.belongsToMany(HangModel, { through: HangUsers });
HangModel.belongsToMany(UserModel, { through: HangUsers });
```

The through table has a column `rsvp`, that I'm trying to populate when I add users to a hang:

```
const user = await UserModel.create();
const hang = await HangModel.create();
await hang.addUser(user, { through: { rvsp: 'joined' } });
```

However, I'm getting an error:

```
AggregateError
    at recursiveBulkCreate (/Users/sgarza62/ditto-app/api/node_modules/sequelize/lib/model.js:2600:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Function.bulkCreate (/Users/sgarza62/ditto-app/api/node_modules/sequelize/lib/model.js:2824:12)
    at async Promise.all (index 0)
    at async BelongsToMany.add (/Users/sgarza62/ditto-app/api/node_modules/sequelize/lib/associations/belongs-to-many.js:740:30)
    at async /Users/sgarza62/ditto-app/api/routes/hangs.js:121:3 {
  name: 'AggregateError',
  errors: [
    BulkRecordError [SequelizeBulkRecordError]: notNull Violation: HangUsers.rsvp cannot be null
        at /Users/sgarza62/ditto-app/api/node_modules/sequelize/lib/model.js:2594:25
        at processTicksAndRejections (internal/process/task_queues.js:97:5) {
      name: 'SequelizeBulkRecordError',
      errors: [ValidationError],
      record: [HangUsers]
    }
  ]
}
```

When I allow null on the rsvp column, the `HangUsers` row *is* created, but the rsvp value is `NULL`.

It seems the `{ through: { rsvp: 'joined' } }` parameter is being ignored.

I've done this all according to the [BelongsToMany docs][1] and the [Advanced M:N Associations docs][2], where it says:

> However, defining the model by ourselves has several advantages. We can, for example, define more columns on our through table:
>
> ```
> const User_Profile = sequelize.define('User_Profile', {
>   selfGranted: DataTypes.BOOLEAN
> }, { timestamps: false });
> User.belongsToMany(Profile, { through: User_Profile });
> Profile.belongsToMany(User, { through: User_Profile });
> ```
>
> With this, we can now track an extra information at the through table,
> namely the selfGranted boolean. For example, when calling the
> user.addProfile() we can pass values for the extra columns using the
> through option.
> 
> Example:
> 
> ``` 
> const amidala = await User.create({ username: 'p4dm3', points: 1000 });
> const queen = await Profile.create({ name: 'Queen' });
> await amidala.addProfile(queen, { through: { selfGranted: false } });
> const result = await User.findOne({
>   where: { username: 'p4dm3' },  
>   include: Profile
> });
> console.log(result);
> ```

  [1]: https://sequelize.org/master/class/lib/associations/belongs-to-many.js~BelongsToMany.html
  [2]: https://sequelize.org/master/manual/advanced-many-to-many.html

**Here is the link to the SSCCE for this issue:** [https://github.com/papb/sequelize-sscce/pull/129/files](https://github.com/papb/sequelize-sscce/pull/129/files) 

### What do you expect to happen?
I expect the attribute on the through table to be set when I use `hang.addUser(user, { through: { rvsp: 'joined' } });`. 

### What is actually happening?
The rsvp attribute on the through table is always `null`. 

### Environment

- Sequelize version: 6.3.5 
- Node.js version: 12.16.2 
- Operating System: 10.14.6

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by santiagogarza** [comment]
It was just a typo in the attribute name. Oops!
