### ISSUE TITLE
mssql transaction insert sql timeout

### ISSUE THREAD

**Issue by Messilimeng** [sequelize/sequelize#12886]
## Issue Description
 i use sequlize with mssql 2014， when i insert sql query ，but sometime can success sometime timeout
the config is：
    getConnection(connStr) {
        const connName = connStr ? connStr : this.connStr;
        this.config = think.config('model')[connName];
        this._sequelize = new Sequelize(this.config.database, this.config.user, this.config.password, {
            host: this.config.host,
            dialect: this.config.type,
            dialectOptions: {
                requestTimeout: 15000,
            },
            benchmark: true,
            logging: this.log,
            pool: {
                max: 500,
                min: 0,
                maxIdleTime: 3600 * 30,
                idle: 10000
            },
            timezone: "+08:00",
            trustServerCertificate: true
        });
        return this._sequelize;
    }
i use transaction
code
let trans = await tdbconn.startransaction()
            let options = { transaction: trans }
await tdbconn.model('Attendence_AdjustAll').addMany(TempAttendenceinfo, options)
 await trans.commit();
the error info is

 original: RequestError: Timeout: Request failed to complete in 15000ms
      at RequestError (/home/catherine/www/tapc/node_modules/tedious/lib/errors.js:32:12)
      at Connection.requestTimeout (/home/catherine/www/tapc/node_modules/tedious/lib/connection.js:1230:46)
      at Timeout._onTimeout (/home/catherine/www/tapc/node_modules/tedious/lib/connection.js:1198:14)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7) {
    code: 'ETIMEOUT',
    sql: "INSERT INTO Attendence_AdjustAll( StoreNumber,EID,OriginalStartTime,OriginalEndTime,IsDel,DoType,AdjustStartTime,AdjustEndTime,WorkMinutes,OffDutyMinutes,WorkHours,OffDutyHours,AttendenceDate,AddTime,AddBy,UpdateBy,UpdateTime ) VALUES ('1450120','15169730',2157,-1,0,2,2200,0,120,120,2,2,'2020-12-02','2020-12-03 09:21:21','jack','jack','2020-12-03 09:21:21'),('1450120','12757859',-1,1810,0,2,0,300,180,180,3,3,'2020-12-02','2020-12-03 09:21:21','jack','jack','2020-12-03 09:21:21'),('1450120','13927374',515,1214,0,2,530,1200,390,30,6.5,0.5,'2020-12-02','2020-12-03 09:21:21','jack','jack','2020-12-03 09:21:21'),('1450120','12757859',1810,2130,0,2,1830,2130,180,0,3,0,'2020-12-02','2020-12-03 09:21:21','jack','jack','2020-12-03 09:21:21'),('1450120','14523877',1337,1658,0,2,1330,1700,210,0,3.5,0,'2020-12-02','2020-12-03 09:21:21','jack','jack','2020-12-03 09:21:21'),('1450120','12894144',1445,2034,0,2,1430,2030,360,0,6,0,'2020-12-02','2020-12-03 09:21:21','jack','jack','2020-12-03 09:21:21'),('1450120','13927374',1230,1332,0,2,1230,1330,60,0,1,0,'2020-12-02','2020-12-03 09:21:21','jack','lee','2020-12-03 09:21:21');",
    parameters: undefined
  },
### What are you doing?

**Here is the link to the SSCCE for this issue:** LINK-HERE 

```js
// You can delete this code block if you have included a link to your SSCCE above!
// MINIMAL, SELF-CONTAINED code here (SSCCE/MCVE/reprex)
```

### What do you expect to happen?

_I wanted Foo!_

### What is actually happening?

_The output was Bar!_

```
Output here
```

### Environment

- Sequelize version: XXX 
- Node.js version: XXX 
- Operating System: XXX
- If TypeScript related: TypeScript version: XXX

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by Messilimeng** [comment]
table locked long time
