### ISSUE TITLE
When using replication in config , db:migrate won't use the variable.

### ISSUE THREAD

**Issue by markrity** [sequelize/sequelize#12899]
### What are you doing?

I'm using read replication functionality in my config file it looks like this :
```
    "replication": {
      "read": [{ "use_env_variable": "READ_DB_CONNECTION_STRING" }],
      "write": { "use_env_variable": "WRITE_DB_CONNECTION_STRING" }
    },
```

All works good, but the issue is when I try to db:migrate , those variables can't be reached.

### What do you expect to happen?

I would expect it to use write by default, since its a migration

### What is actually happening?

```
) UnhandledPromiseRejectionWarning: Error: Command failed: ./node_modules/.bin/sequelize db:migrate
(node:45) [SEQUELIZE0004] DeprecationWarning: A boolean value was passed to options.operatorsAliases. This is a no-op with v5 and should be removed.
ERROR: connect ECONNREFUSED 127.0.0.1:3306
    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:483:12)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
(node:37) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

It didn't know which connect string to use , so it tried the default `127.0.0.1:3306`  

### Environment

- Sequelize version: 5.5.1 
- Node.js version: 12.18.3 
- Operating System: ubuntu 20:04 

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by markrity** [comment]
unstale
