### ISSUE TITLE
Unexpected token ...

### ISSUE THREAD

**Issue by KhairulHabibSamaon** [sequelize/sequelize#12901]
## Issue Description
unable to deploy to server because of unexpected ... ins lib/sequelize.js

### What are you doing?

i would like to dockerize the express apps into AWS ECS but it's returning error:

```
/srv/node_modules/sequelize/lib/sequelize.js:277
      ...options
      ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/srv/node_modules/sequelize/index.js:8:18)
```

### What do you expect to happen?

what i aspect is it should dockerize properly

### What is actually happening?

it's returning this error

```
/srv/node_modules/sequelize/lib/sequelize.js:277
      ...options
      ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/srv/node_modules/sequelize/index.js:8:18)
HAUZ-MBP-1:client HAUZDevTeam$ sequelize version
```

### Environment

- Sequelize version: sequelize@6.3.5  
- Node.js version: v10.15.3 
- Operating System: MAC OS catalina v 10.15.7
- If TypeScript related: TypeScript version: XXX

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [/ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [/ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by huangyingzheng** [comment]
I had encountered the same problem, did you find the solution? orz

**Comment by KhairulHabibSamaon** [comment]
> I had encountered the same problem, did you find the solution? orz

@huangyingzheng , couldn't find any solution, end up i'm just using normal query method because had another thing to focus on to save my time.

**Comment by modihemant409** [comment]
if anyone found solution
