### ISSUE TITLE
SYNTAX ERROR.

### ISSUE THREAD

**Issue by anor731** [sequelize/sequelize#12924]
```
/home/me/Code/Trader/node_modules/sequelize/lib/dialects/postgres/query.js:386
        return new sequelizeErrors.DatabaseError(err);
               ^

DatabaseError [SequelizeDatabaseError]: syntax error at or near "ON"
    at Query.formatError (/home/me/Code/Trader/node_modules/sequelize/lib/dialects/postgres/query.js:386:16)
    at Query.run (/home/me/Code/Trader/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async /home/me/Code/Trader/node_modules/sequelize/lib/sequelize.js:619:16
    at async PostgresQueryInterface.upsert (/home/me/Code/Trader/node_modules/sequelize/lib/dialects/abstract/query-interface.js:790:12)
    at async Function.upsert (/home/me/Code/Trader/node_modules/sequelize/lib/model.js:2482:20)
    at async Object.<anonymous> (/home/me/Code/Trader/api/binance/fetchKlines1m.js:16:25)
    at async Promise.all (index 0)
    at async handleTicks (/home/me/Code/Trader/api/binance/fetchKlines1m.js:14:24) {
  parent: error: syntax error at or near "ON"
      at Parser.parseErrorMessage (/home/me/Code/Trader/node_modules/pg-protocol/dist/parser.js:278:15)
      at Parser.handlePacket (/home/me/Code/Trader/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/home/me/Code/Trader/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/home/me/Code/Trader/node_modules/pg-protocol/dist/index.js:10:42)
      at Socket.emit (node:events:376:20)
      at addChunk (node:internal/streams/readable:304:12)
      at readableAddChunk (node:internal/streams/readable:279:9)
      at Socket.Readable.push (node:internal/streams/readable:218:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:192:23) {
    length: 92,
    severity: 'ERROR',
    code: '42601',
    detail: undefined,
    hint: undefined,
    position: '589',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'scan.l',
    line: '1145',
    routine: 'scanner_yyerror',
    sql: 'INSERT INTO "kline" ("symbol","interval","time","open","high","low","close","volume","closeTime","assetVolume","buyBaseVolume","createdAt","updatedAt") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) ON CONFLICT ("closeTime") DO UPDATE SET "interval"=EXCLUDED."interval","symbol"=EXCLUDED."symbol","time"=EXCLUDED."time","open"=EXCLUDED."open","high"=EXCLUDED."high","low"=EXCLUDED."low","close"=EXCLUDED."close","volume"=EXCLUDED."volume","closeTime"=EXCLUDED."closeTime","assetVolume"=EXCLUDED."assetVolume","buyBaseVolume"=EXCLUDED."buyBaseVolume","updatedAt"=EXCLUDED."updatedAt" ON CONFLICT DO NOTHING RETURNING "id","symbol","interval","time","open","high","low","close","volume","closeTime","assetVolume","buyBaseVolume","createdAt","updatedAt";',

PostgreSQL linux

```

**Comment by vlapo** [comment]
@anor731 provide example. Stack trace is useless without more description.
