### ISSUE TITLE
Fail on connecting multiple mssql databases

### ISSUE THREAD

**Issue by Avital103** [sequelize/sequelize#12950]
### What are you doing?

**Here is the link to the SSCCE for this issue:** https://github.com/papb/sequelize-sscce/pull/142

### What do you expect to happen?

_I expect sequelize to connect to the two databases_

### What is actually happening?

_only one connection is connected. the first one is destroyed_

```
fail DB1_CONNECTION
ConnectionError [SequelizeConnectionError]: Connection lost - read ECONNRESET
    at ConnectionManager.connect (C:\...\node_modules\sequelize\lib\dialects\mssql\connection-manage
r.js:138:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at ConnectionManager._connect (C:\...\node_modules\sequelize\lib\dialects\abstract\connection-ma
nager.js:318:24)
    at C:\...\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:250:32
    at ConnectionManager.getConnection (C:\...\node_modules\sequelize\lib\dialects\abstract\connecti
on-manager.js:280:7)
    at C:\...\node_modules\sequelize\lib\sequelize.js:613:26
    at Sequelize.authenticate (C:\...\node_modules\sequelize\lib\sequelize.js:867:5) {
  parent: ConnectionError: Connection lost - read ECONNRESET
      at ConnectionError (C:\...\node_modules\tedious\lib\errors.js:13:12)
      at Connection.socketError (C:\...\node_modules\tedious\lib\connection.js:1660:54)
      at Socket.<anonymous> (C:\...\node_modules\tedious\lib\connection.js:1420:14)
      at Socket.emit (events.js:327:22)
      at emitErrorNT (internal/streams/destroy.js:106:8)
      at emitErrorCloseNT (internal/streams/destroy.js:74:3)
      at processTicksAndRejections (internal/process/task_queues.js:80:21) {
    code: 'ESOCKET'
  },
  original: ConnectionError: Connection lost - read ECONNRESET
      at ConnectionError (C:\...\node_modules\tedious\lib\errors.js:13:12)
      at Connection.socketError (C:\...\node_modules\tedious\lib\connection.js:1660:54)
      at Socket.<anonymous> (C:\...\node_modules\tedious\lib\connection.js:1420:14)
      at Socket.emit (events.js:327:22)
      at emitErrorNT (internal/streams/destroy.js:106:8)
      at emitErrorCloseNT (internal/streams/destroy.js:74:3)
      at processTicksAndRejections (internal/process/task_queues.js:80:21) {
    code: 'ESOCKET'
  }
}
Executing (default): SELECT 1+1 AS result
connected DB2_CONNECTION
```

### Additional context

If I change one of the connections to mysql, both connect OK.
If both are mysql it also works OK.

### Environment

- Sequelize version: 6.3.5 
- Node.js version: 14.15.1 
- Operating System: windows
- If TypeScript related: TypeScript version: 4.1.3

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- I think this problem happens only for the following dialect(s): mssql
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
-  Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by cx5168** [comment]
same issue

**Comment by jamaica474** [comment]
Having same problem. In my app I'm consecutively connecting to 2 databases, and it looks like latter connection overwrites former one. As soon as second connection is established queries to the first one stop working

**Comment by WikiRik** [comment]
I think this issue is related; https://github.com/sequelize/sequelize/issues/14050
