### ISSUE TITLE
Getting an error when trying to associate 3 models

### ISSUE THREAD

**Issue by MichaelGrigoryan25** [sequelize/sequelize#12972]
## Issue Description
(Before creating this issue I have searched for my problem in the Sequelize GitHub repo issues, StackOverflow and YouTube)
Hi! I am trying to create associations between 3 models. User, Post and Comment The documentation was kind of unclear on the associations part. I think that part should be improved a bit by providing more real-world examples. So here are my models' code(generated with Sequelize CLI).

`user.js`

```js
"use strict";
const { Model } = require("sequelize");
module.exports = (sequelize, DataTypes) => {
  class user extends Model {
    /**
     * Helper method for defining associations.
     * This method is not a part of Sequelize lifecycle.
     * The `models/index` file will call this method automatically.
     */
    static associate(models) {
      // define association here
      this.hasMany(models.Comment, {
        foreignKey: "userId",
        as: "user",
      });
    }
  }
  user.init(
    {
      email: DataTypes.STRING,
      password: DataTypes.TEXT,
      name: DataTypes.STRING,
    },
    {
      sequelize,
      modelName: "user",
    }
  );
  return user;
};

```

`post.js`

```js
"use strict";
const { Model } = require("sequelize");
module.exports = (sequelize, DataTypes) => {
  class Post extends Model {
    /**
     * Helper method for defining associations.
     * This method is not a part of Sequelize lifecycle.
     * The `models/index` file will call this method automatically.
     */
    static associate(models) {
      // define association here
      this.hasMany(models.Comment, {
        foreignKey: "userId",
        as: "posts",
      });
    }
  }
  Post.init(
    {
      title: DataTypes.STRING,
      description: DataTypes.TEXT,
      imageUrl: DataTypes.STRING,
    },
    {
      sequelize,
      modelName: "Post",
      tableName: "posts",
    }
  );
  return Post;
};
```

and `comment.js`

```js
"use strict";
const { Model } = require("sequelize");
module.exports = (sequelize, DataTypes) => {
  class Comment extends Model {
    /**
     * Helper method for defining associations.
     * This method is not a part of Sequelize lifecycle.
     * The `models/index` file will call this method automatically.
     */
    static associate(models) {
      // define association here
      this.belongsTo(models.Post, {
        foreignKey: "postId",
        as: "comments",
      });
    }
  }
  Comment.init(
    {
      comment: DataTypes.STRING,
    },
    {
      sequelize,
      modelName: "Comment",
      tableName: "posts",
    }
  );
  return Comment;
};
```

And the error that I get is

```
TypeError: include.model.getTableName is not a function
    at Function._validateIncludedElement (C:\Users\micha\Desktop\blog\node_modules\sequelize\lib\model.js:579:30)
    at C:\Users\micha\Desktop\blog\node_modules\sequelize\lib\model.js:509:37
    at Array.map (<anonymous>)
    at Function._validateIncludedElements (C:\Users\micha\Desktop\blog\node_modules\sequelize\lib\model.js:504:39)
    at Function.findAll (C:\Users\micha\Desktop\blog\node_modules\sequelize\lib\model.js:1723:12)
    at async Function.findOne (C:\Users\micha\Desktop\blog\node_modules\sequelize\lib\model.js:1917:12)
    at async C:\Users\micha\Desktop\blog\routes\post.js:16:18
```

If applicable, you can add some code. In this case, an SSCCE/MCVE/reprex is much better than just an isolated code snippet.

### StackOverflow / Slack attempts

I haven't asked questions on StackOverflow but I searched for them. So far I have tried these 3
https://stackoverflow.com/questions/35974514/sequelize-association-error-cannot-read-property-gettablename-of-undefined
https://stackoverflow.com/questions/54734509/how-to-join-two-tables-cannot-read-property-gettablename-of-undefined
https://stackoverflow.com/questions/58134975/sequelize-association-error-include-model-gettablename-is-not-a-function

### Additional context
Here's my `post.route.js` code where I want to join comment table with the post table based on the post id I have

```js
const path = require("path");
const jwt = require("jsonwebtoken");
const { unlinkSync } = require("fs");
const router = require("express").Router();

const DataTypes = require("sequelize");
const { sequelize } = require("../models/index");

const Post = require("../models/post");
const User = require("../models/user");
const Comment = require("../models/comment");

// Get the post page
router.get("/:postId", async (req, res) => {
  try {
    const post = await Post(sequelize, DataTypes).findOne({
      where: {
        id: req.params.postId,
      },
      include: [
        {
          model: Comment,
          as: "comments",
          where: {
            postId: req.params.postId,
          },
        },
      ],
    });

    if (!post) {
      return res.redirect("/");
    } else if (post) {
      jwt.verify(req.cookies.jwt, process.env.JWT, async (err, data) => {
        if (err)
          return res.render("post", {
            post: post,
            currentAccount: null,
            adminLoggedIn: req.cookies.adminLoggedIn,
          });
        else if (data) {
          const currentAccount = await User.findOne({ where: { id: data.id } });
          return res.render("post", {
            post: post,
            currentAccount: currentAccount,
            adminLoggedIn: req.cookies.adminLoggedIn,
          });
        }
      });
    }
  } catch (error) {
    console.error(error);
    return res.redirect("/");
  }
});

router.post("/comment/:postId", async (req, res) => {
  try {
    const { comment } = req.body;
    const post = await Post(sequelize, DataTypes).findOne({
      where: {
        id: req.params.postId,
      },
    });

    if (!post) {
      return res.redirect("/");
    } else if (post) {
      jwt.verify(req.cookies.jwt, process.env.JWT, async (err, data) => {
        if (err) return res.redirect("/");
        else if (data) {
          await Comment.create({
            authorId: data.id,
            comment: comment,
            postId: post.id,
          });
          return res.location.reload();
        }
      });
    }
  } catch (error) {
    console.error(error);
    return res.redirect("/");
  }
});

// Delete a post
router.post("/delete/:postId", async (req, res) => {
  try {
    const foundPost = await Post(sequelize, DataTypes).findOne({
      where: {
        id: req.params.postId,
      },
    });

    if (!foundPost) return res.redirect("/");
    else if (foundPost) {
      if (req.cookies.adminLoggedIn) {
        unlinkSync(path.join("public", "images", foundPost.imageUrl));
        await foundPost.destroy();
        return res.redirect("/");
      } else {
        return res.redirect("/");
      }
    }
  } catch (error) {
    console.error(error);
    return res.redirect("/");
  }
});

module.exports = router;
```

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [X] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by Spekpannenkoek** [comment]
```
      include: [
        {
          model: Comment,
          as: "comments",
          where: {
            postId: req.params.postId,
          },
        },
      ],
```

You need to pass a class that inherits from Model here, but you're actually passing a _function that returns a class that inherits from Model_. The `module.exports` value in `models/comment.js` is `(sequelize, DataTypes) => class Comment extends Model { ... }`, which is not the same as `module.exports = class Comment extends Model { ... }`.

You should be able to instead use `sequelize.model('Comment')` or `sequelize.models.Comment` to get a reference to the class. 

Also, I think there's a typo here; `userId` seems an odd choice when associating posts with comments?

```
      this.hasMany(models.Comment, {
        foreignKey: "userId",
        as: "posts",
      });
```

**Comment by MichaelGrigoryan25** [comment]
Thanks for the answer. Yeah there may be mistakes and typos all around I'm coming from a MongoDB so I don't really understand how things are done with Sequelize. I'm not closing this issue for now because I can't figure out how to find an association by a parameter. Can you please provide a link to the documentation.

**Comment by Spekpannenkoek** [comment]
>  I can't figure out how to find an association by a parameter.

Do you mean you want to, for example, find users who have a posted at a certain date?

You do that with the `where` parameter under `include`:

```
User.findAll({
  include: [{
    model: Posts
    where: {
      // createdAt or some other value
    }
  }]
})
``` 

Not sure where that's documented on the main docs, but you can [find it in the reference](https://sequelize.org/master/class/lib/model.js~Model.html#static-method-findAll): `options.include[].where`

**Comment by MichaelGrigoryan25** [comment]
Yes, kind of. I want to find them by their ID. also thanks for your answer. really appreciate it

**Comment by juancruzsosagab** [comment]
do you solve this michael? @michaelgrigoryan25
