### ISSUE TITLE
[Mssql] [Docker] Connection Error: Failed to connect to <>:1433 - socket hang up.

### ISSUE THREAD

**Issue by mrch4n** [sequelize/sequelize#12982]
## Connecting to Mssql from Docker not success.

Everything's fine when I run the code from host.

But when I run the code inside Docker container, the connection not success and has the following error:

```
[SequelizeConnectionError]: Failed to connect to mssqlServer.local:1433 - socket hang up
    at ConnectionManager.connect (/usr/src/app/node_modules/sequelize/lib/dialects/mssql/connection-manager.js:138:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ConnectionManager._connect (/usr/src/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:318:24)
    at async /usr/src/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:32
    at async ConnectionManager.getConnection (/usr/src/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:280:7)
    at async /usr/src/app/node_modules/sequelize/lib/sequelize.js:613:26
    at async Sequelize.authenticate (/usr/src/app/node_modules/sequelize/lib/sequelize.js:867:5)
    at async SnapshotDb.connect (/usr/src/app/models/mssql.js:38:13)
    at async iie (/usr/src/app/devmssql.js:6:5) {
  parent: ConnectionError: Failed to connect to mssqlServer.local:1433 - socket hang up
      at ConnectionError (/usr/src/app/node_modules/tedious/lib/errors.js:13:12)
      at Connection.socketError (/usr/src/app/node_modules/tedious/lib/connection.js:1652:56)
      at Connection.socketEnd (/usr/src/app/node_modules/tedious/lib/connection.js:1682:12)
      at Socket.<anonymous> (/usr/src/app/node_modules/tedious/lib/connection.js:1422:14)
      at Socket.emit (events.js:327:22)
      at endReadableNT (internal/streams/readable.js:1327:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21) {
    code: 'ESOCKET'
  },
  original: ConnectionError: Failed to connect to mssqlServer.local:1433 - socket hang up
      at ConnectionError (/usr/src/app/node_modules/tedious/lib/errors.js:13:12)
      at Connection.socketError (/usr/src/app/node_modules/tedious/lib/connection.js:1652:56)
      at Connection.socketEnd (/usr/src/app/node_modules/tedious/lib/connection.js:1682:12)
      at Socket.<anonymous> (/usr/src/app/node_modules/tedious/lib/connection.js:1422:14)
      at Socket.emit (events.js:327:22)
      at endReadableNT (internal/streams/readable.js:1327:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21) {
    code: 'ESOCKET'
  }
```

My calling script:
```
mssql = new Sequelize(config.mssql.db, config.mssql.username, config.mssql.password, {
    logging: console.log,
    host: config.mssql.server,
    dialect: 'mssql',
});

myModel = mssql.define('Enrollment', {
    COL_ONE: { type: DataTypes.STRING, allowNull: true },
    // other columns go here
}, {
        tableName: 'myMssqlTable',
        timestamps: false,
});

mssql.authenticate() // <- Error occurs here
```

I have go into the docker container (by `docker exec -it` command) and do ping test with success result, and able to use `sequelize-automate` to output a correct model.

Don't know what is going wrong or anything I missed.

### Versioning
- Host: macOS Catalina 10.15.7
- Docker: Docker Desktop 3.1.0
- Docker Image: node:14.15.4-buster
- MS SQL Server 2016
- Sequelize: 6.4.0
- Tedious: 11.0.1

### Is this issue dialect-specific?

- [ ] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [x] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by cah-manoj-kumar** [comment]
same issue with     
    "sequelize": "^5.15.1",
    "sequelize-cli": "^5.4.0",
    "tedious": "^11.0.5"

when I tried with older tedious version ^6.7.0 then it works fine.

**Comment by jonaseickhoff** [comment]
I had the same problem. I switched back from docker node buster image to stretch image and it works fine. Dont know whats wrong with buster image and mssql

**Comment by 1365436742** [comment]
You can try it to solve

dialect: 'mssql',
  dialectOptions: {
    options: {
      "encrypt": false
    }
  }

**Comment by bouchlihz** [comment]
@1365436742 Thanks a lot I have been struggling for day, your solution worked for me : "encrypt": false

**Comment by JuriVitali** [comment]
I had the same problem and it worked for me too.  Thank you

**Comment by obed-peralta** [comment]
> You can try it to solve
> 
> ```js
> dialect: 'mssql',
>   dialectOptions: {
>     options: {
>       "encrypt": false
>     }
>   }
> ```

**I Love U <3**

**Comment by NatanBrito** [comment]
It's work in my project too, thanksss !

**Comment by akki0824** [comment]
Hi, can anyone help exactly where we should add this block is it in the database.js or .sequence

**Comment by akki0824** [comment]
where to add this snippet

**Comment by bouchlihz** [comment]
> Hi, can anyone help exactly where we should add this block is it in the database.js or .sequence

@akki0824 it's up to you where you defined your mssqlconfig :

{
  "mssqlConfig": {
    "user": "xxx",
    "server": "xxx",
    "password": "xxx",
    "database": "xx",
    "connectionTimeout": 1200000,
    "requestTimeout": 1200000,
    "pool": {
      "max": 10,
      "min": 2,
      "idleTimeoutMillis": 30000
    },
    "options": {
      "host": "xxxx",
      "enableArithAbort": true,
      "operatorsAliases": 0,
      "dialect": "mssql",
      "charset": "utf8",
      "collate": "utf8_unicode_ci",
      "encrypt": false,
      **"dialectOptions": {
        "supportBigNumbers": true,
        "bigNumberStrings": true,
        "options": {
          "encrypt": false
          }
      }**
    }
  }
}

**Comment by pols63** [comment]
> You can try it to solve
> 
> ```js
> dialect: 'mssql',
>   dialectOptions: {
>     options: {
>       "encrypt": false
>     }
>   }
> ```

THANKS!!!!!!!!!!
