### ISSUE TITLE
Add `rejectOnEmpty` in nonCascadingOptions

### ISSUE THREAD

**Issue by c060604** [sequelize/sequelize#13133]
### Is your feature request related to a problem? Please describe.

Assume I have `Product` model with a hasMany association to the `Tag` model ("a product can have many tags associated with it").

```js
Product.hasMany(Tag)
```

some data in db like:
`product`
| id| name |
|-|-|
| 1 | P1|
|2 | P2|

`tag`
| id | productId | name |
|-|-|-|
|1| 1 | T1|
| 2 | 1| T2|

**1.  query with `separate: false` and `rejectOnEmpty: true`**

```js
const data = await Product.findByPk(2, {
  include: {
    model: Tag,
    required: false,
    separate: false,
  },
  rejectOnEmpty: true
});
console.log(data);
```
output
```js
// Product 2
{
  id: 2,
  name: "P2",
  tags: []
}
```
**2. query with `separate: true` and `rejectOnEmpty: true`**

```js
const data = await Product.findByPk(2, {
  include: {
    model: Tag,
    required: false,
    separate: true,
  },
  rejectOnEmpty: true
});
console.log(data);
```
output
```
nodejs.SequelizeEmptyResultError:
    at Function.findAll (/Users/nobody1/projects/Mesh/mesh-delivery-service/node_modules/sequelize/lib/model.js:1769:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at HasMany.get (/Users/nobody1/projects/Mesh/mesh-delivery-service/node_modules/sequelize/lib/associations/has-many.js:228:21)
    at /Users/nobody1/projects/Mesh/mesh-delivery-service/node_modules/sequelize/lib/model.js:1842:19
    at async Promise.all (index 0)
    at Function._findSeparate (/Users/nobody1/projects/Mesh/mesh-delivery-service/node_modules/sequelize/lib/model.js:1817:5)
    at Function.findAll (/Users/nobody1/projects/Mesh/mesh-delivery-service/node_modules/sequelize/lib/model.js:1772:12)
    at Function.findOne (/Users/nobody1/projects/Mesh/mesh-delivery-service/node_modules/sequelize/lib/model.js:1924:12)
    at Function.findByPk (/Users/nobody1/projects/Mesh/mesh-delivery-service/node_modules/sequelize/lib/model.js:1890:12)
    at FooBoot.serverDidReady (/Users/nobody1/projects/Mesh/mesh-delivery-service/app.ts:58:22)
    at /Users/nobody1/projects/Mesh/mesh-delivery-service/node_modules/egg-core/lib/lifecycle.js:207:11
name: "SequelizeEmptyResultError"
```

This query will run two sql
```sql
select * from product where id = 2;
select * from tag where productId = 2;      // The result is empty.
```

And when the second sql is executed, sequelize will assert the query result is not empty.

https://github.com/sequelize/sequelize/blob/5b16b32259f0599a6af2d1eb625622da9054265e/lib/model.js#L1759

### Describe the solution you'd like

The second query with `separate: true` should return the same result with the first query, instead of throw the error.

### Why should this be in Sequelize

I think Sequelize should make sure the two queries above return the same results whatever the value of `separate` is true or false.

### Describe alternatives/workarounds you've considered

It seems that the `rejectOnEmpty` will be passed to the separate query options.

I found that `nonCascadingOptions` does not contain the `rejectOnEmpty` property.

https://github.com/sequelize/sequelize/blob/5b16b32259f0599a6af2d1eb625622da9054265e/lib/model.js#L32

I consider that `nonCascadingOptions` may contains `rejectOnEmpty` property, then subqueries will not assert the results is empty.

```
// List of attributes that should not be implicitly passed into subqueries/includes.
const nonCascadingOptions = ['rejectOnEmpty', 'include', 'attributes', 'originalAttributes', 'order', 'where', 'limit', 'offset', 'plain', 'group', 'having'];
```

### Additional context

None

### Is this feature dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ

### Would you be willing to implement this feature by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by hexpunk** [comment]
This is still an issue.  I don't think it should be stale.

**Comment by hexpunk** [comment]
@sequelize, I think this should be reopened.  I got bit by this as well.  This seems like a non-intuitive behavior.
