### ISSUE TITLE
bulkCreate, returning id's wrong

### ISSUE THREAD

**Issue by cskiwi** [sequelize/sequelize#13137]
### What are you doing?
This is sort of a bug report, may be a lack of documentation (or I didn't find them)

I'm trying to insert bulk items, but I'm having trouble receiving the ID's of items that already existed in the database.
I made some tests to check some configurations, but so far all fail. 

The reason for the bug request is the fact that the `bulkCreate` returns wrong id's, this seems very misleading (and could give issues).

```js
import { Club, DataBaseHandler } from '@badvlasim/shared';

describe('custom', () => {
  let databaseService: DataBaseHandler;
  beforeAll(async () => {
    databaseService = new DataBaseHandler({
      dialect: 'sqlite',
      storage: ':memory:',
      logging: (...msg) => console.log(msg)
    });
  });

  beforeEach(async () => {
    // Clear eveything
    await DataBaseHandler.sequelizeInstance.sync({ force: true });
  });

  it('ignoreduplicates', async () => {
    await new Club({
      name: 'Testing'
    }).save();

    const club2 = new Club({
      name: 'Testing'
    }).toJSON() as any;

    const dbClub = await Club.bulkCreate([club2], {
      ignoreDuplicates: true
    });

    const findCountAll = await Club.findAndCountAll();
    expect(findCountAll.count).toEqual(1);
    expect(dbClub[0].id).toEqual(findCountAll.rows[0].id);
  });

  it('updateOnDuplicate', async () => {
    await new Club({
      name: 'Testing'
    }).save();

    const club2 = new Club({
      name: 'Testing'
    }).toJSON() as any;

    const dbClub = await Club.bulkCreate([club2], {
      updateOnDuplicate: ['name'],
      returning: true
    });

    const findCountAll = await Club.findAndCountAll();
    expect(findCountAll.count).toEqual(1);
    expect(dbClub[0].id).toEqual(findCountAll.rows[0].id);
  });

  it('returning', async () => {
    await new Club({
      name: 'Testing'
    }).save();

    const club2 = new Club({
      name: 'Testing'
    }).toJSON() as any;

    const dbClub = await Club.bulkCreate([club2], {
      ignoreDuplicates: true,
      returning: ['id']
    });

    const findCountAll = await Club.findAndCountAll();
    expect(findCountAll.count).toEqual(1);
    expect(dbClub[0].id).toEqual(findCountAll.rows[0].id);
  });
});

```

### What do you expect to happen?

I want to create a bulk set of objects, but return the original id's on duplicates

### What is actually happening?

I got a new Id

```
 FAIL  src/import/__tests__/custom.spec.tsx (6.824s)
  ● custom › ignoreduplicates

    expect(received).toEqual(expected) // deep equality

    Expected: "55708a08-8c5a-4908-80ff-07171e6ece12"
    Received: "abe193c7-1547-496f-b675-284472da0867"

      31 |     const findCountAll = await Club.findAndCountAll();
      32 |     expect(findCountAll.count).toEqual(1);
    > 33 |     expect(dbClub[0].id).toEqual(findCountAll.rows[0].id);
         |                          ^
      34 |   });
      35 |
      36 |   it('updateOnDuplicate', async () => {

      at Object.<anonymous> (src/import/__tests__/custom.spec.tsx:33:26)

  ● custom › updateOnDuplicate

    expect(received).toEqual(expected) // deep equality

    Expected: "32a433cc-9e57-4727-9ff9-7d6d0045c18d"
    Received: "0992ea19-b31d-491d-9614-12648f56c657"

      50 |     const findCountAll = await Club.findAndCountAll();
      51 |     expect(findCountAll.count).toEqual(1);
    > 52 |     expect(dbClub[0].id).toEqual(findCountAll.rows[0].id);
         |                          ^
      53 |   });
      54 |
      55 |   it('returning', async () => {

      at Object.<anonymous> (src/import/__tests__/custom.spec.tsx:52:26)

  ● custom › returning

    expect(received).toEqual(expected) // deep equality

    Expected: "403111f9-4661-4c6b-965d-102a0791a60e"
    Received: "e1d41a5f-4682-4f45-b974-e7b9e7c89659"

      69 |     const findCountAll = await Club.findAndCountAll();
      70 |     expect(findCountAll.count).toEqual(1);
    > 71 |     expect(dbClub[0].id).toEqual(findCountAll.rows[0].id);
         |                          ^
      72 |   });
      73 | });
      74 |

      at Object.<anonymous> (src/import/__tests__/custom.spec.tsx:71:26)


=============================== Coverage summary ===============================
Statements   : 3.76% ( 36/957 )
Branches     : 0% ( 0/620 )
Functions    : 0% ( 0/247 )
Lines        : 3.93% ( 36/915 )
================================================================================
Test Suites: 1 failed, 7 skipped, 1 of 8 total
Tests:       3 failed, 28 skipped, 31 total
Snapshots:   0 total
Time:        9.324s, estimated 18s
Ran all test suites with tests matching "custom".

Watch Usage: Press w to show more.
```

### Environment

- Sequelize version: 6.5.0 
- Node.js version: 14.5.0 
- Operating System: Windows 10 Pro
- If TypeScript related: TypeScript version: 3.8.3

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ten-ecb** [comment]
Still an issue.
