### ISSUE TITLE
ConnectionError [SequelizeConnectionError]: connect ETIMEDOUT

### ISSUE THREAD

**Issue by Spectrevuln-sketch** [sequelize/sequelize#13361]
can anyone help me why, Sequelize Return error in any my app is working fine in php
but my node js app its retrun error
ConnectionError [SequelizeConnectionError]: connect ETIMEDOUT
    at ConnectionManager.connect (/var/www/cms.storymadeid.com/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:126:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ConnectionManager._connect (/var/www/cms.storymadeid.com/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:318:24)
    at async /var/www/cms.storymadeid.com/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:32 {
  parent: Error: connect ETIMEDOUT
      at Connection._handleTimeoutError (/var/www/cms.storymadeid.com/node_modules/mysql2/lib/connection.js:178:17)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7) {
    errorno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    fatal: true
  },
  original: Error: connect ETIMEDOUT
      at Connection._handleTimeoutError (/var/www/cms.storymadeid.com/node_modules/mysql2/lib/connection.js:178:17)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7) {
    errorno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    fatal: true
  }
}
(node:4962) UnhandledPromiseRejectionWarning: SequelizeConnectionError: connect ETIMEDOUT
    at ConnectionManager.connect (/var/www/cms.storymadeid.com/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:126:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ConnectionManager._connect (/var/www/cms.storymadeid.com/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:318:24)
    at async /var/www/cms.storymadeid.com/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:32
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4962) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4962) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

any solution

**Comment by rbsherry** [comment]
same issue

**Comment by hidayahhtaufik** [comment]
same issue

**Comment by hidayahhtaufik** [comment]
My solve problem is setting configure at Production and PORT follow place to your deploy app

**Comment by rbsherry** [comment]
In our case upgrading node version from 10 to 14 solved the issue

**Comment by hidayahhtaufik** [comment]
Oke thank you for information

**Comment by teb111** [comment]
i have this same issue, But this didn't work

**Comment by aqibburq** [comment]
I have same issue. can someone  post the solution.

**Comment by teb111** [comment]
Please check the port you're trying to connect to with sequelize

**Comment by aqibburq** [comment]
const sequelize = new Sequelize(DB_DBNAME, DB_USERNAME, DB_PASSWORD, {
  host: DB_HOSTNAME,
  dialect: 'mysql',
  port: 3306,
  define: {
    // charset: 'utf8mb4',
    // collate: 'utf8mb4_unicode_ci'
  },
  dialectOptions: {
    // charset: 'utf8mb4'
  },
  logging: false,
  pool: {
    max: 5,
    min: 0,
    acquire: 30000,
    idle: 10000
  }
});

**Comment by teb111** [comment]
const Sequelize = require('sequelize')
const fs = require('fs')
const path = require('path')
require('dotenv').config()
const certificatePath = path.join(__dirname, '/DigiCertGlobalRootCA.crt.pem')

const serverCa = [fs.readFileSync(certificatePath, 'utf8')]

const sequelize = new Sequelize(
  process.env.DB,
  process.env.DB_USER,
  process.env.DB_PASSWORD,
  {
    host: process.env.DB_HOST,
    dialect: 'mysql',
    port: process.env.DB_PORT,
    dialectOptions: {
      ssl: {
        rejectUnauthorized: true,
        ca: serverCa
      }
    },
    define: {
      timestamps: false,
      freezeTableName: true
    }
  }
)

module.exports = sequelize

**Comment by teb111** [comment]
This is how i connect

**Comment by hidayahhtaufik** [comment]
you can check your connection and customize your port and running again

**Comment by OneWithTheInternet** [comment]
For me configuring the port variable "MYSQLPORT" or "DB_PORT" while setting up Sequelize configuration solved the issue.

**Comment by OneWithTheInternet** [comment]
const { Sequelize } = require('sequelize');

const dbConnect = new Sequelize(process.env.MYSQLDATABASE , process.env.MYSQLUSER, process.env.MYSQLPASSWORD, {
    host: process.env.MYSQLHOST,
    dialect: process.env.MYSQLDIALECT,
    port: process.env.MYSQLPORT
});

**Comment by OneWithTheInternet** [comment]
const { Sequelize } = require('sequelize');

const dbConnect = new Sequelize(process.env.MYSQLDATABASE , process.env.MYSQLUSER, process.env.MYSQLPASSWORD, {
    host: process.env.MYSQLHOST,
    dialect: process.env.MYSQLDIALECT,
    port: process.env.MYSQLPORT
});

module.exports = dbConnect;

**Comment by imKira97** [comment]
I am stuck here too from long time , I have used all the above mentioned code but it didnt worked 

const Sequelize = require("sequelize");

const sequelize = new Sequelize(
  process.env.DB_SCHEMA_NAME,
  process.env.SCHEMA_USER_NAME,
  process.env.SCHEMA_USER_PWD,
  {
    host: process.env.DB_HOST,
    dialect: "mysql",
    port: process.env.PORT_NUMBER,
  }
);
module.exports = sequelize;

**Comment by imKira97** [comment]
The above same code is running properly in ec2 instance  
but when i am doing it in vscode its throwing me error

**Comment by ShravanKumarD** [comment]
module.exports = {
    HOST: process.env.HOST,
    USER: process.env.USER,
    PASSWORD: process.env.PASSWORD,
    DB: process.env.DB,
    dialect: process.env.dialect,
     port:process.env.DB_PORT,
    pool: {
        max: 5,
        min: 0,
        acquire: 30000,
        idle: 10000,
    },
};


i am getting this on all platforms 

error ConnectionError [SequelizeConnectionError]: connect ETIMEDOUT
    at ConnectionManager.connect (/Users/mac/Downloads/Development/node_rts/onlineearning_node/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:102:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/mac/Downloads/Development/node_rts/onlineearning_node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
    at async /Users/mac/Downloads/Development/node_rts/onlineearning_node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32 {
  parent: Error: connect ETIMEDOUT
      at Connection._handleTimeoutError (/Users/mac/Downloads/Development/node_rts/onlineearning_node/node_modules/mysql2/lib/connection.js:205:17)
      at listOnTimeout (node:internal/timers:573:17)
      at process.processTimers (node:internal/timers:514:7) {
    errorno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    fatal: true
  },
  original: Error: connect ETIMEDOUT
      at Connection._handleTimeoutError (/Users/mac/Downloads/Development/node_rts/onlineearning_node/node_modules/mysql2/lib/connection.js:205:17)
      at listOnTimeout (node:internal/timers:573:17)
      at process.processTimers (node:internal/timers:514:7) {
    errorno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    fatal: true
  }
}
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

ConnectionError [SequelizeConnectionError]: connect ETIMEDOUT
    at ConnectionManager.connect (/Users/mac/Downloads/Development/node_rts/onlineearning_node/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:102:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/mac/Downloads/Development/node_rts/onlineearning_node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
    at async /Users/mac/Downloads/Development/node_rts/onlineearning_node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32 {
  parent: Error: connect ETIMEDOUT
      at Connection._handleTimeoutError (/Users/mac/Downloads/Development/node_rts/onlineearning_node/node_modules/mysql2/lib/connection.js:205:17)
      at listOnTimeout (node:internal/timers:573:17)
      at process.processTimers (node:internal/timers:514:7) {
    errorno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    fatal: true
  },
  original: Error: connect ETIMEDOUT
      at Connection._handleTimeoutError (/Users/mac/Downloads/Development/node_rts/onlineearning_node/node_modules/mysql2/lib/connection.js:205:17)
      at listOnTimeout (node:internal/timers:573:17)
      at process.processTimers (node:internal/timers:514:7) {
    errorno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    fatal: true
  }
}

Node.js v20.11.1
[nodemon] app crashed - waiting for file changes before starting...
[nodemon] restarting due to changes...
[nodemon] starting `node app.js`
error ConnectionError [SequelizeConnectionError]: connect ETIMEDOUT
    at ConnectionManager.connect (/Users/mac/Downloads/Development/node_rts/onlineearning_node/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:102:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ConnectionManager._connect (/Users/mac/Downloads/Development/node_rts/onlineearning_node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
    at async /Users/mac/Downloads/Development/node_rts/onlineearning_node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32 {
  parent: Error: connect ETIMEDOUT
      at Connection._handleTimeoutError (/Users/mac/Downloads/Development/node_rts/onlineearning_node/node_modules/mysql2/lib/connection.js:205:17)
      at listOnTimeout (node:internal/timers:573:17)
      at process.processTimers (node:internal/timers:514:7) {
    errorno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    fatal: true
  },

**Comment by GregCarl** [comment]
Hello, 
I had the same issue trying to connect to MYSQL. 
I changed all my .env variable code as the one proposed by Railway.
That solve my issue.
