### ISSUE TITLE
DB username was capitalized unexpectedly when passing an object as the initialization arguments

### ISSUE THREAD

**Issue by marcong95** [sequelize/sequelize#13393]
## Issue Creation Checklist

[x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

My DB username was capitalized unexpectedly when passing an object as the initialization arguments, but it's ok when I build the connect URL manually.

### SSCCE

**Here is the link to the SSCCE for this issue:** [LINK-HERE](https://gist.github.com/marcong95/5bd764d54a4676ec7509a97ee53fda65) 

### What do you expect to happen?

Connect to the database.

### What is actually happening?

My username was captialize. You can see the username in the first line of the error message is "Marco" rather than "marco"

```
 ConnectionError [SequelizeConnectionError]: password authentication failed for user "Marco"
    at Client._connectionCallback (C:\Users\Marco\Documents\Programs\ES\util-server\node_modules\sequelize\lib\dialects\postgres\connection-manager.js:184:24)
    at Client._handleErrorWhileConnecting (C:\Users\Marco\Documents\Programs\ES\util-server\node_modules\pg\lib\client.js:305:19)
    at Client._handleErrorMessage (C:\Users\Marco\Documents\Programs\ES\util-server\node_modules\pg\lib\client.js:325:19)
    at Connection.emit (node:events:369:20)
    at C:\Users\Marco\Documents\Programs\ES\util-server\node_modules\pg\lib\connection.js:115:12
    at Parser.parse (C:\Users\Marco\Documents\Programs\ES\util-server\node_modules\pg-protocol\dist\parser.js:40:17)
    at Socket.<anonymous> (C:\Users\Marco\Documents\Programs\ES\util-server\node_modules\pg-protocol\dist\index.js:10:42)
    at Socket.emit (node:events:369:20)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:288:9) {
  parent: error: password authentication failed for user "Marco"
      at Parser.parseErrorMessage (C:\Users\Marco\Documents\Programs\ES\util-server\node_modules\pg-protocol\dist\parser.js:278:15)
      at Parser.handlePacket (C:\Users\Marco\Documents\Programs\ES\util-server\node_modules\pg-protocol\dist\parser.js:126:29)
      at Parser.parse (C:\Users\Marco\Documents\Programs\ES\util-server\node_modules\pg-protocol\dist\parser.js:39:38)
      at Socket.<anonymous> (C:\Users\Marco\Documents\Programs\ES\util-server\node_modules\pg-protocol\dist\index.js:10:42)
      at Socket.emit (node:events:369:20)
      at addChunk (node:internal/streams/readable:313:12)
      at readableAddChunk (node:internal/streams/readable:288:9)
      at Socket.Readable.push (node:internal/streams/readable:227:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 101,
    severity: 'FATAL',
    code: '28P01',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'auth.c',
    line: '333',
    routine: 'auth_failed'
  },
  original: <same as parent>
}
```

### Additional context

The connection can be established successfully when using the commented statement, which provide an manually built URL. The issue still exist even if I replace the `process.env.DB_PASSWORD` with my actually password.

### Environment

- Sequelize version: 6.6.5 
- Node.js version: 15.14.0 
- PostgreSQL version: 12.6

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [x] I don't know, I was using PostgreSQL, with connector library version 8.5.1 and database version 12.6

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by medgardo** [comment]
In your [sscce](https://gist.github.com/marcong95/5bd764d54a4676ec7509a97ee53fda65#file-sscce-js-L7), try updating your connection options to use `username` instead of `user`.

My guess is that Postgres is picking up your operating system username. The Sequelize class constructor doesn't have a `user` parameter that I see: https://sequelize.org/master/class/lib/sequelize.js~Sequelize.html#instance-constructor-constructor

**Comment by marcong95** [comment]
> In your [sscce](https://gist.github.com/marcong95/5bd764d54a4676ec7509a97ee53fda65#file-sscce-js-L7), try updating your connection options to use `username` instead of `user`.
> 
> My guess is that Postgres is picking up your operating system username. The Sequelize class constructor doesn't have a `user` parameter that I see: https://sequelize.org/master/class/lib/sequelize.js~Sequelize.html#instance-constructor-constructor

It works! Thanks a lot for your help with such a silly mistake...
