### ISSUE TITLE
Associations not using Model tableName attribute

### ISSUE THREAD

**Issue by aleexnl** [sequelize/sequelize#13416]
## Issue Creation Checklist

- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### SSCCE

**Here is the link to the SSCCE for this issue:** LINK-HERE 

```js
// Instance
const connection = new Sequelize(
  process.env.NEXTJS_APP_DB_DATABASE,
  process.env.NEXTJS_APP_DB_USERNAME,
  process.env.NEXTJS_APP_DB_PASSWORD,
  {
    dialect: 'mysql',
    port: process.env.NEXTJS_APP_DB_PORT,
    host: process.env.NEXTJS_APP_DB_HOST,
    logging: false,
    define: {
      freezeTableName: true,
      timestamps: false
    }
  }
);
// Models
const SharedStrategy = sequelize.define(
  'SharedStrategy',
  {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      field: 'shared_strategies_id',
      autoIncrement: true
    },
    userId: {
      type: DataTypes.STRING,
      field: 'user_id',
      allowNull: false,
      references: {
        model: User,
        key: 'id'
      }
    },
    title: {
      type: DataTypes.STRING,
      allowNull: false
    },
    sharedAt: {
      type: DataTypes.DATE,
      defaultValue: Sequelize.NOW,
      field: 'shared_date'
    },
    downloads: {
      type: DataTypes.INTEGER,
      defaultValue: 0
    },
    image: {
      type: DataTypes.TEXT('long')
    },
    timeframeId: {
      type: DataTypes.INTEGER,
      allowNull: false,
      field: 'timeframe'
    },
    tickerId: {
      type: DataTypes.INTEGER,
      allowNull: false,
      references: { model: Ticker, key: 'id' },
      field: 'asset'
    },
    profit: { type: DataTypes.FLOAT, allowNull: false, defaultValue: 0.0 },
    risk: { type: DataTypes.FLOAT, allowNull: false, defaultValue: 0.0 }
  },
  {
    sequelize,
    tableName: 'shared_strategies'
  }
);
const Ticker = sequelize.define(
  'Ticker',
  {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
      field: 'TICKER_ID'
    }
  },
  {
    name: {
      type: DataTypes.STRING,
      field: 'TICKER_NAME'
    },
    displayName: {
      type: DataTypes.STRING,
      field: 'display_name'
    }
  },
  {
    sequelize,
    tableName: 'ticker'
  }
);

// Relationship
SharedStrategy.belongsTo(Ticker, {
  foreignKey: 'tickerId',
  as: 'ticker'
});
// Query
 const sharedStrategy = await SharedStrategy.findOne({
      where: { id },
      include: { model: Ticker, as: 'ticker' }
    });
```

### What do you expect to happen?

When finding the models and using include, get the realtionship between strategy & ticker
```json
{
    "id": 1,
    "userId": 1,
    "title": "Funny name",
    "sharedAt": "2021-07-30T12:10:21.000Z",
    "downloads": 0,
    "image": "",
    "timeframeId": "4",
    "tickerId": "120",
    "profit": 0.00,
    "risk": 0.00,
    "ticker": { 
        "id": 120
    }
}
```

### What is actually happening?

Getting an error because database.Ticker not found, while tableName is ticker.

As shown in the query generated by Sequelize, tableName is used as alias instead as a table name.

```
DatabaseError [SequelizeDatabaseError]: Table 'database.Ticker' doesn't exist
    at Query.formatError (/Users/aleexnl/Workspace/app/node_modules/sequelize/lib/dialects/mysql/query.js:265:16)
    at Query.run (/Users/aleexnl/Workspace/app/node_modules/sequelize/lib/dialects/mysql/query.js:77:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/aleexnl/Workspace/app/node_modules/sequelize/lib/sequelize.js:619:16
    at async MySQLQueryInterface.select (/Users/aleexnl/Workspace/app/node_modules/sequelize/lib/dialects/abstract/query-interface.js:953:12)
    at async Function.findAll (/Users/aleexnl/Workspace/app/node_modules/sequelize/lib/model.js:1753:21)
    at async Function.findOne (/Users/aleexnl/Workspace/app/node_modules/sequelize/lib/model.js:1917:12)
    at async handler (webpack-internal:///./pages/api/shared-strategies/[id]/index.js:15:28)
    at async apiResolver (/Users/aleexnl/Workspace/app/node_modules/next/dist/next-server/server/api-utils.js:8:1)
    at async DevServer.handleApiRequest (/Users/aleexnl/Workspace/app/node_modules/next/dist/next-server/server/next-server.js:66:462) {
  parent: Error: Table 'database.Ticker' doesn't exist
      at Packet.asError (/Users/aleexnl/Workspace/app/node_modules/mysql2/lib/packets/packet.js:712:17)
      at Query.execute (/Users/aleexnl/Workspace/app/node_modules/mysql2/lib/commands/command.js:28:26)
      at Connection.handlePacket (/Users/aleexnl/Workspace/app/node_modules/mysql2/lib/connection.js:425:32)
      at PacketParser.onPacket (/Users/aleexnl/Workspace/app/node_modules/mysql2/lib/connection.js:75:12)
      at PacketParser.executeStart (/Users/aleexnl/Workspace/app/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/Users/aleexnl/Workspace/app/node_modules/mysql2/lib/connection.js:82:25)
      at Socket.emit (node:events:394:28)
      at addChunk (node:internal/streams/readable:312:12)
      at readableAddChunk (node:internal/streams/readable:287:9)
      at Socket.Readable.push (node:internal/streams/readable:226:10) {
    code: 'ER_NO_SUCH_TABLE',
    errno: 1146,
    sqlState: '42S02',
    sqlMessage: "Table 'database.Ticker' doesn't exist",
    sql: "SELECT `SharedStrategy`.`shared_strategies_id` AS `id`, `SharedStrategy`.`user_id` AS `userId`, `SharedStrategy`.`title`, `SharedStrategy`.`shared_date` AS `sharedAt`, `SharedStrategy`.`downloads`, `SharedStrategy`.`image`, `SharedStrategy`.`timeframe` AS `timeframeId`, `SharedStrategy`.`asset` AS `tickerId`, `SharedStrategy`.`profit`, `SharedStrategy`.`risk`, `ticker`.`TICKER_ID` AS `ticker.id` FROM `shared_strategies` AS `SharedStrategy` LEFT OUTER JOIN `Ticker` AS `ticker` ON `SharedStrategy`.`asset` = `ticker`.`TICKER_ID` WHERE `SharedStrategy`.`shared_strategies_id` = '61';",
    parameters: undefined
  },
  original: Error: Table 'database.Ticker' doesn't exist
      at Packet.asError (/Users/aleexnl/Workspace/app/node_modules/mysql2/lib/packets/packet.js:712:17)
      at Query.execute (/Users/aleexnl/Workspace/app/node_modules/mysql2/lib/commands/command.js:28:26)
      at Connection.handlePacket (/Users/aleexnl/Workspace/app/node_modules/mysql2/lib/connection.js:425:32)
      at PacketParser.onPacket (/Users/aleexnl/Workspace/app/node_modules/mysql2/lib/connection.js:75:12)
      at PacketParser.executeStart (/Users/aleexnl/Workspace/app/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/Users/aleexnl/Workspace/app/node_modules/mysql2/lib/connection.js:82:25)
      at Socket.emit (node:events:394:28)
      at addChunk (node:internal/streams/readable:312:12)
      at readableAddChunk (node:internal/streams/readable:287:9)
      at Socket.Readable.push (node:internal/streams/readable:226:10) {
    code: 'ER_NO_SUCH_TABLE',
    errno: 1146,
    sqlState: '42S02',
    sqlMessage: "Table 'database.Ticker' doesn't exist",
    sql: "SELECT `SharedStrategy`.`shared_strategies_id` AS `id`, `SharedStrategy`.`user_id` AS `userId`, `SharedStrategy`.`title`, `SharedStrategy`.`shared_date` AS `sharedAt`, `SharedStrategy`.`downloads`, `SharedStrategy`.`image`, `SharedStrategy`.`timeframe` AS `timeframeId`, `SharedStrategy`.`asset` AS `tickerId`, `SharedStrategy`.`profit`, `SharedStrategy`.`risk`, `ticker`.`TICKER_ID` AS `ticker.id` FROM `shared_strategies` AS `SharedStrategy` LEFT OUTER JOIN `Ticker` AS `ticker` ON `SharedStrategy`.`asset` = `ticker`.`TICKER_ID` WHERE `SharedStrategy`.`shared_strategies_id` = '61';",
    parameters: undefined
  },
  sql: "SELECT `SharedStrategy`.`shared_strategies_id` AS `id`, `SharedStrategy`.`user_id` AS `userId`, `SharedStrategy`.`title`, `SharedStrategy`.`shared_date` AS `sharedAt`, `SharedStrategy`.`downloads`, `SharedStrategy`.`image`, `SharedStrategy`.`timeframe` AS `timeframeId`, `SharedStrategy`.`asset` AS `tickerId`, `SharedStrategy`.`profit`, `SharedStrategy`.`risk`, `ticker`.`TICKER_ID` AS `ticker.id` FROM `shared_strategies` AS `SharedStrategy` LEFT OUTER JOIN `Ticker` AS `ticker` ON `SharedStrategy`.`asset` = `ticker`.`TICKER_ID` WHERE `SharedStrategy`.`shared_strategies_id` = '61';",
  parameters: undefined
}

```

### Additional context

No additional context needed in my opinion, the problem is clear: When defining a relationship (I don't know if hasMany, etc. has the same problem) tableName is used as table alias while building the query.

### Environment

- Sequelize version: 6.6.5 
- Node.js version: 16.6.1 

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [x] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by aleexnl** [comment]
The problem was the model definition, {} where nested bad :/
Sorry for the inconvenience!
