### ISSUE TITLE
just  can't work  this  code just can't work together  i don't what happend  sombody  help me  i wan't sleeeeeep help

### ISSUE THREAD

**Issue by yanwuguangjun** [sequelize/sequelize#13447]
## Issue Creation Checklist

[ ] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

i used sequelize by typscrept

this  code  0x01 and 0x02 they are in defferent file and they r  just can't work together  i don't what happend . sombody  help me  i wan't sleeeeeep will  help

#### code  0x01
```ts
SchedulerData.belongsTo(TmpTask,{
    foreignKey:'taskid',
    targetKey:'id'
})

or 

SchedulerData.hasOne(TmpTask,{
    sourceKey: 'taskid',
    foreignKey: 'id',
})

```

with

#### code   0x02
```ts
TmpTask.hasOne(SchedulerData, {
    sourceKey: 'id',
    foreignKey: 'taskid',
});

```

if i use one the other i will be  trrigger errror like

`E:\tuo_q\custom_server\node_modules\_sequelize@6.6.5@sequelize\lib\associations\mixin.js:93
      throw new Error(`${source.name}.${_.lowerFirst(Type.name)} called with something that's not a subclass of Sequelize.Model`);
            ^
Error: SchedulerData.belongsTo called with something that's not a subclass of Sequelize.Model
    at Function.<anonymous> (E:\tuo_q\custom_server\node_modules\_sequelize@6.6.5@sequelize\lib\associations\mixin.js:93:13)
    at Object.<anonymous> (E:\tuo_q\custom_server\src\model\SchedulerData.ts:110:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (E:\tuo_q\custom_server\node_modules\_ts-node@9.1.1@ts-node\src\index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (E:\tuo_q\custom_server\node_modules\_ts-node@9.1.1@ts-node\src\index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
`

**Comment by yanwuguangjun** [comment]
they are need in a  one file

**Comment by FreeLancerPT** [comment]
Hello, can you explain exacly what you did?
I am using sequelize V7 after  the update it shows the same error as you. 
Thanks
