### ISSUE TITLE
Many to many association fooInstance.getBars() function spitting out TypeError when using an "include" option

### ISSUE THREAD

**Issue by r9119** [sequelize/sequelize#13450]
## Issue Creation Checklist

[x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description
When trying to use an "include" option in a many to many fooInstance.getBars() function a JS TypeError is spit out saying that "options.include.push() is not a function"

Rundown of what I'm trying to do with the code:
I have a many to many assoc between a User and Workflow model, I am trying to fetch all the workflows from a user. When using this code I get the desired output but it includes the User object with every workflow which I'd like it not to:
```js
const userWorkflows = await WorkflowInstance.findAll({
    include: [
        {
            model: User,
            where: {
                id: req.query.id
            }
        },
        {
            model: TaskInstance,
            include: {
                model: ControlInstance
            }
        }
    ]
})
```
So I decided to switch to the fooInstance.getBars() method to leave out said User object with the code:
```js
const user = await User.findByPk(req.query.id)

const userWorkflows = await user.getWorkflowInstances({
    include: {
        model: TaskInstance,
        include: {
            model: ControlInstance
        }
    }
})
```
Which results in the error:
```
TypeError: options.include.push is not a function
    at BelongsToMany.get (C:\...\server\node_modules\sequelize\lib\associations\belongs-to-many.js:452:23)
    at model.obj.<computed> [as getWorkflowInstances] (C:\...\server\node_modules\sequelize\lib\associations\helpers.js:56:39)
    at indexWorkflows (C:\...\server\src\controllers\UserController.js:60:46)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

I don't think there is an issue with my code, as all other assoc methods have worked with these two models, and the error is linked to a file in the sequelize node package

### Additional context

Just having the "include" option in the function as an option regardless of associated model gives the same error.
I opened a [stackoverflow](https://stackoverflow.com/questions/68829494/sequelize-js-many-to-many-association-getter-function-not-accepting-an-eager-loa) question about this earlier but got nothing

### Environment

- Sequelize version: 6.6.5
- Node.js version: 14.15.4

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by melosomelo** [comment]
Don't know if this is a good practice or not, but I just put `push: () => {}` and it worked.

**Comment by melosomelo** [comment]
Just to leave a quick update here: 

I took a look into the source code and clearly the association code expects `include` field to be an array, hence the whole `TypeError: options.include.push is not a function`.

`      options.include = options.include || [];
      options.include.push({
        association: this.oneFromTarget,
        attributes: options.joinTableAttributes,
        required: true,
        paranoid: _.get(options.through, 'paranoid', true),
        where: throughWhere
      });
    }`

Just put your object inside an array and it should work.

P.S: If you just put `push: () => {}` as I did all of your configs for the query will be lost.

**Comment by elijahmontenegro** [comment]
> Just to leave a quick update here:
> 
> I took a look into the source code and clearly the association code expects `include` field to be an array, hence the whole `TypeError: options.include.push is not a function`.
> 
> ```
> options.include = options.include || [];
> options.include.push({
>   association: this.oneFromTarget,
>   attributes: options.joinTableAttributes,
>   required: true,
>   paranoid: _.get(options.through, 'paranoid', true),
>   where: throughWhere
> });
> }
> ```
> 
> Just put your object inside an array and it should work.
> 
> P.S: If you just put `push: () => {}` as I did all of your configs for the query will be lost.

How did you access the options.include function.
I am having the same error as you calling user.getBoards (a M:M query like yours).
I have a extra column 'state' specified in User_Board (many to many through table) 
trying to return the extra column in user.getBoards() by specifying includes.

**Comment by rafiyutama** [comment]
> Just to leave a quick update here:
> 
> I took a look into the source code and clearly the association code expects `include` field to be an array, hence the whole `TypeError: options.include.push is not a function`.
> 
> ```
> options.include = options.include || [];
> options.include.push({
>   association: this.oneFromTarget,
>   attributes: options.joinTableAttributes,
>   required: true,
>   paranoid: _.get(options.through, 'paranoid', true),
>   where: throughWhere
> });
> }
> ```
> 
> Just put your object inside an array and it should work.
> 
> P.S: If you just put `push: () => {}` as I did all of your configs for the query will be lost.

thank you ... this is really helping.. so in my case I just add '[]' to the include.. I got the idea after reading this

const userWorkflows = await user.getWorkflowInstances({
    include: [{  // square bracket here
        model: TaskInstance,
        include: {
            model: ControlInstance
        }
    }] // and here
})

and it works
