### ISSUE TITLE
Error at many-to-many relationship

### ISSUE THREAD

**Issue by Khuzha** [sequelize/sequelize#13508]
## Issue Creation Checklist

[+] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### SSCCE

**Here is the link to the SSCCE for this issue:** https://github.com/ASUDR/backend/blob/dev/src/db/models/university/Hostel.ts#L41

```js
import Sequelize, { Optional } from 'sequelize';
import sequelize from '../../sequelize';
import { Faculty } from '../..';

const { DataTypes, Model } = Sequelize;

export interface HostelAttributes {
  id: number;
  name: string;
}

export interface HostelAttributesInput extends Optional<HostelAttributes, 'id'> {}
export interface HostelAttributesOutput extends Required<HostelAttributes> {}

export class Hostel
  extends Model<HostelAttributes, HostelAttributesInput>
  implements HostelAttributes {
  public id: number;
  public name: string;
}

Hostel.init({
  id: {
    type: DataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: true
  },

  name: {
    type: DataTypes.STRING(32),
    allowNull: false,
    unique: true
  }
}, {
  sequelize,
  schema: 'university',
  modelName: 'hostels',
  timestamps: false
});

Hostel.belongsToMany(Faculty, {
  through: 'university.hostels_to_faculties',
  sourceKey: 'hostel_id',
  targetKey: 'faculty_id',
  onUpdate: 'CASCADE',
  onDelete: 'CASCADE'
});
```

### What do you expect to happen?

I need m2m relationsheep between Hostel and Faculty models

### What is actually happening?

I get this error at running code:

```
/opt/app/node_modules/sequelize/lib/associations/belongs-to-many.js:129
    this.sourceKeyField = this.source.rawAttributes[this.sourceKey].field || this.sourceKey;
```
(here is arrow that points out to `field` at `this.source.rawAttributes[this.sourceKey].field`)
```
TypeError: Cannot read properties of undefined (reading 'field')
    at new BelongsToMany (/opt/app/node_modules/sequelize/lib/associations/belongs-to-many.js:129:69)
    at Function.belongsToMany (/opt/app/node_modules/sequelize/lib/associations/mixin.js:64:25)
    at file:///opt/app/dist/db/models/university/Hostel.js:24:8
    at ModuleJob.run (node:internal/modules/esm/module_job:183:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
    at async handleMainPromise (node:internal/modules/run_main:63:12)
```

### Environment

- Sequelize version: 6.6.2
- Node.js version: 16
- TypeScript version: 4.3.5

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by Khuzha** [comment]
I fixed this error by creating the model for junction table:
```
import Sequelize, { Optional } from 'sequelize';
import sequelize from '../../sequelize';

const { DataTypes, Model } = Sequelize;

export interface FacultyHostelsAttributes {
  id: number;
  hostelId: number;
  facultyId: number;
}

export interface FacultyHostelsAttributesInput extends Optional<FacultyHostelsAttributes, 'id'> {}
export interface FacultyHostelsAttributesOutput extends Required<FacultyHostelsAttributes> {}

export class FacultyHostels
  extends Model<FacultyHostelsAttributes, FacultyHostelsAttributesInput>
  implements FacultyHostelsAttributes {
    public id: number;
    public hostelId: number;
    public facultyId: number;
}

FacultyHostels.init({
  id: {
    type: DataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: true
  },

  hostelId: {
    type: DataTypes.INTEGER,
    field: 'hostel_id',
    allowNull: false
  },

  facultyId: {
    type: DataTypes.INTEGER,
    field: 'faculty_id',
    allowNull: false
  }
}, {
  sequelize,
  schema: 'objects',
  modelName: 'faculty_hostels',
  timestamps: false
});
```

And changing `belongsToMany` arguments:
```
Hostel.belongsToMany(Faculty, {
  through: FacultyHostels,
  onUpdate: 'CASCADE',
  onDelete: 'CASCADE'
});

Faculty.belongsToMany(Hostel, {
  through: FacultyHostels,
  onUpdate: 'CASCADE',
  onDelete: 'CASCADE'
});
```

more: https://github.com/ASUDR/backend/blob/main/src/db/models/university/Hostel.ts

**Comment by radcapitalist** [comment]
Was the underlying problem just that you had not defined the junction table model?  Because I have a junction table model defined and I am getting this same error when I add a **belongsToMany** association on either side.
