### ISSUE TITLE
Sync alter:true not working enum

### ISSUE THREAD

**Issue by agomyrat** [sequelize/sequelize#13526]
**IN MSSQL:**
`await sequelize.sync({ alter: true });`

Executing (default): ALTER TABLE [item_images] ALTER COLUMN [type] VARCHAR(255) CHECK ([type] IN(N'normal', N'schema', N'usage'));

My model:
```
const { Sequelize, Model, DataTypes, Op } = require('sequelize');
module.exports = (sequelize) => {
    sequelize.define(
        'item_images',
        {
            id: {
                type: DataTypes.INTEGER,
                autoIncrement: true,
                primaryKey: true,
            },
            item_id: {
                type: DataTypes.INTEGER,
                allowNull: false,
            },
            type: {
                type: DataTypes.ENUM('normal', 'schema', 'usage'),
                allowNull: false,
                defaultValue: 'normal',
            },
            original_img: {
                type: DataTypes.STRING,
            },
            big_img: {
                type: DataTypes.STRING,
            },
            medium_img: {
                type: DataTypes.STRING,
            },
            small_img: {
                type: DataTypes.STRING,
            },

            last_updated: {
                type: DataTypes.INTEGER,
            },
            main_image: {
                type: DataTypes.BOOLEAN,
            },
        },
        {
            sequelize,
            paranoid: true,
            underscored: true,
            timestamps: true,
            scopes: {
                normal: {
                    where: {
                        type: 'normal',
                    },
                },
                mainImage: {
                    where: {
                        type: 'normal',
                        main_image: true,
                    },
                },
            },
        }
    );
};
```

SequelizeDatabaseError: Incorrect syntax near the keyword &#39;CHECK&#39;.<br> &nbsp; &nbsp;at Query.formatError (D:\4. MY PROJECT\E_COMMERCE\node_modules\sequelize\lib\dialects\mssql\query.js:314:12)<br> &nbsp; &nbsp;at Query._run (D:\4. MY PROJECT\E_COMMERCE\node_modules\sequelize\lib\dialects\mssql\query.js:93:18)<br> &nbsp; &nbsp;at runMicrotasks (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at processTicksAndRejections (internal/process/task_queues.js:95:5)<br> &nbsp; &nbsp;at async D:\4. MY PROJECT\E_COMMERCE\node_modules\sequelize\lib\sequelize.js:619:16<br> &nbsp; &nbsp;at async Function.sync (D:\4. MY PROJECT\E_COMMERCE\node_modules\sequelize\lib\model.js:1349:11)<br> &nbsp; &nbsp;at async Sequelize.sync (D:\4. MY PROJECT\E_COMMERCE\node_modules\sequelize\lib\sequelize.js:793:35)<br> &nbsp; &nbsp;at async D:\4. MY PROJECT\E_COMMERCE\controllers\denemeControllers.js:14:18</pre>

**Comment by agomyrat** [comment]
IN MSSQL
