### ISSUE TITLE
Sequelize replication authenticate occurs fatal error

### ISSUE THREAD

**Issue by EgorCloud** [sequelize/sequelize#13537]
## Issue Creation Checklist

[x]I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### SSCCE

```js
const { Sequelize } = require("sequelize");
const sequelize = new Sequelize("database", null, null, {
    port:3306,
    dialect:"mysql",
    replication: {
        read: [{
            host:"8.8.8.8",
            username:"read-1-username",
            password:"read-1-password",

        }],
        write: {
            host:"1.1.1.1",
            username:"write-username",
            password:"write-password",
        },
    },
});
sequelize.authenticate()
```

### What do you expect to happen?
```
Executing (default): SELECT 1+1 AS result
```

### What is actually happening?
```
"C:\Program Files\nodejs\node.exe" test-sequelize.js
[Project path]\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:178
        this.pool[connection.queryType].destroy(connection);
                                        ^

TypeError: Cannot read property 'destroy' of undefined
    at Object.destroy ([Project path]\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:178:41)
    at Connection.<anonymous> ([Project path]\node_modules\sequelize\lib\dialects\mysql\connection-manager.js:100:23)
    at Connection.emit (events.js:376:20)
    at Connection._notifyError ([Project path]\node_modules\mysql2\lib\connection.js:236:12)
    at Connection._handleFatalError ([Project path]\node_modules\mysql2\lib\connection.js:167:10)
    at Connection._handleNetworkError ([Project path]\node_modules\mysql2\lib\connection.js:180:10)
    at Socket.emit (events.js:376:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

### Environment

- Sequelize version: 6.6.5
- Node.js version: v14.17.0

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by gaurav16694** [comment]
Hey i am seeing this issue
looks like some issue with the libarary

**Comment by EgorCloud** [comment]
@gaurav16694 So I already found a solution (workaround). It is required to indicate the version of the database.
```js
const { Sequelize } = require("sequelize");
const sequelize = new Sequelize("database", null, null, {
    port:3306,
    dialect:"mysql",
    databaseVersion: 8, // required field
    replication: {
        read: [{
            host:"8.8.8.8",
            username:"read-1-username",
            password:"read-1-password",

        }],
        write: {
            host:"1.1.1.1",
            username:"write-username",
            password:"write-password",
        },
    },
});
sequelize.authenticate()
```

**Comment by Arrow2702** [comment]
@EgorCloud : The Sequelize version is 6.8.0 and when we try to add databaseVersion it throws us an error : **Object literal may only specify known properties, and 'databaseVersion' does not exist in type 'Options'.** I checked in the interface of options and it does not contain the databaseVersion.

**Comment by EgorCloud** [comment]
Hi, @Arrow2702.
You should look at the sources for this project. https://github.com/sequelize/sequelize/blob/v6/lib/dialects/abstract/connection-manager.js#L246
I recommend disabling the check for the line / file where the connection code is written

**Comment by WikiRik** [comment]
I am reopening this issue so the required databaseVersion can be documented in the docs and in the types

**Comment by gaurav16694** [comment]
Hello @WikiRik what is the current solution to the problem
we are not able to add databaseVersion during Sequalize initialization?

**Comment by WikiRik** [comment]
> @EgorCloud : The Sequelize version is 6.8.0 and when we try to add databaseVersion it throws us an error : **Object literal may only specify known properties, and 'databaseVersion' does not exist in type 'Options'.** I checked in the interface of options and it does not contain the databaseVersion.

@gaurav16694 if you are using TypeScript and get the same error as above you can disable checks for the line/file where you initialize Sequelize like @EgorCloud suggested in a previous comment. I will update the TypeScript typings so databaseVersion is included

**Comment by daniel-zavacky** [comment]
I am getting same error and setting databaseVersion did not resolve it.

I was debugging the issue and I noticed that `this.pool[connection.queryType].destroy(connection)` failed because connection did not contain **queryType** (read/write). This attribute is set in `create` function of new read/write pool immediately after connection is created. The problem is that `this._connect` is async function which contains multiple async steps (**beforeConnection hook**, `dialect.connectionManager.connect` (which for postgres contains multiple async actions) and **afterConnection hook**). Therefore if error occurs in process of creating of connection, connection will not contain **queryType** and because of this it will fail as described in issue.

Fix should be easy, setting **queryType** to connection should happen immediately after connection is created. I can create PR in which I will fix it by passing **queryType** to config param of `this._connect` (while still keeping setting of **queryType** after `this._connect` for dialects which do not need to be updated) in _dialects/abstract/connection-manager_ and then setting this attribute immediately after connection is created (in connect function for dialects which need it) in _dialects/{dialect}/connection-manager_
<br>
![image](https://github.com/sequelize/sequelize/assets/125864782/6d596aea-4743-4ad4-a9b2-1e712c553c1b)
_dialects/abstract/connection-manager_
<br>
![image](https://github.com/sequelize/sequelize/assets/125864782/059d2f90-9679-4b2f-8275-6d6fc6a1f545)
_dialects/{dialect}/connection-manager_
<br>
let me know if proposed fix would be sufficient
