### ISSUE TITLE
Index with name - s.replace is not a function

### ISSUE THREAD

**Issue by MrNickGreene** [sequelize/sequelize#13545]
## Bug Description

I have this in my Typsescript model for speciifying the indexes. I am using sequelize-auto to generate these, and it's a valid format according to the sequelize docs:

```ts
FacebookPageConnections.init({
    facebookPlatformConnectionId: {
      type: DataTypes.INTEGER,
      allowNull: false,
      primaryKey: true,
      references: {
        model: 'facebook_platform_connections',
        key: 'id'
      },
      field: 'facebook_platform_connection_id'
    },
    pageId: {
      type: DataTypes.BIGINT,
      allowNull: false,
      primaryKey: true,
      field: 'page_id'
    },
    name: {
      type: DataTypes.STRING(255),
      allowNull: true
    },
    accessToken: {
      type: DataTypes.STRING(255),
      allowNull: true,
      field: 'access_token'
    },
    createdAt: {
      type: DataTypes.DATE,
      allowNull: false,
      field: 'created_at'
    },
    updatedAt: {
      type: DataTypes.DATE,
      allowNull: true,
      field: 'updated_at'
    },
    deletedAt: {
      type: DataTypes.DATE,
      allowNull: true,
      field: 'deleted_at'
    }
  }, {
    sequelize,
    tableName: 'facebook_page_connections',
    schema: 'public',
    timestamps: false,
    indexes: [
      {
        name: "facebook_page_connections_pkey",
        unique: true,
        fields: [
          { name: "facebook_platform_connection_id" },
          { name: "page_id" },
        ]
      },
    ]
  });
```

When calling bulkUpdate with UpdateOnDuplicate specified:
``` ts 
await FacebookPageConnections.bulkCreate(connectedAccounts, {
    updateOnDuplicate: ["name", "accessToken", "updatedAt", "deletedAt"],
  });
  ```

I receive the following error: 
`s.replace is not a function`

StackTrace:
```
'TypeError: s.replace is not a function\n    at Object.removeTicks (C:\\src\\threshold360-node\\src\\api\\node_modules\\sequelize\\lib\\utils.js:351:12)\n    at Object.quoteIdentifier (C:\\src\\threshold360-node\\src\\api\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-generator\\helpers\\quote.js:50:35)\n    at PostgresQueryGenerator.quoteIdentifier (C:\\src\\threshold360-node\\src\\api\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-generator.js:900:24)\n    at C:\\src\\threshold360-node\\src\\api\\node_modules\\se…\\sequelize\\lib\\dialects\\abstract\\query-generator.js:291:49)\n    at PostgresQueryInterface.bulkInsert (C:\\src\\threshold360-node\\src\\api\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-interface.js:834:27)\n    at recursiveBulkCreate (C:\\src\\threshold360-node\\src\\api\\node_modules\\sequelize\\lib\\model.js:2711:52)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Function.bulkCreate (C:\\src\\threshold360-node\\src\\api\\node_modules\\sequelize\\lib\\model.js:2837:12)'
```

It seems that the replaceTicks function is expecting a string array, when an object[] with name fields is acceptable.
<img width="443" alt="remove ticks function" src="https://user-images.githubusercontent.com/20054659/136598186-de5ff3f9-0452-4c2e-aedd-5bbc2d79e3b6.png">

### What do you expect to happen?

Records to be Upserted as expected.

### What is actually happening?

Error: `s.replace is not a function`

replaceTicks is expecting a string, when it is an object.
`s.replace` needs to be `s.name.replace` in this scenario.
Or the names need to be passed into this function.

#### Additional Info

I think this is either a fault of the replaceTicks function, or the code that generates the upsertKeys.

### Environment

- Sequelize version: 6.6.5
- Node.js version: 16.9.1
- If TypeScript related: TypeScript version: 4.4.3

### How does this problem relate to dialects?

- [x] I think this problem happens regardless of the dialect.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by MrNickGreene** [comment]
bump

**Comment by hohoaisan** [comment]
I have the same issue

**Comment by ephys** [comment]
@MrNickGreene / @hohoaisan could either of you create a [SSCCE](https://github.com/papb/sequelize-sscce) to help us investigate this issue?

**Comment by ruiaraujolink** [comment]
I'm facing the same issue, any solution?

**Comment by devbeoservice** [comment]
same issue, using typescript. seems like object gets passed to removetick but only during bulkcreate.

object looks like {
  name: 'id',
  length: undefined,
  order: undefined,
  collate: undefined
}

gl

**Comment by JuliaRakitina** [comment]
+1 same issue (

**Comment by ephys** [comment]
We won't be able to help if we can't reproduce the issue. We need a complete [SSCCE](https://github.com/papb/sequelize-sscce) that reproduces it.

**Comment by JuliaRakitina** [comment]
@ephys ok, will provide it soon

**Comment by hohoaisan** [comment]
@ephys I have managed to reproduce this issue, check out [this pull request on SSCCE](https://github.com/sequelize/sequelize-sscce/pull/225).
I believe the issue occurs once bulkCreate with option updateOnDuplicate was set in a table that has multiple primary keys.

**Comment by hohoaisan** [comment]
I had checked the log and seems only PostgreSQL and SQLite have this issue, (MSSQL doesn't count arcording to "mssql does not support the updateOnDuplicate option."). Check the before and after bulkCreate in each pipeline's log.

**Comment by ephys** [comment]
Thank you ❤️ I'll look into fixing this as soon as I'm available

**Comment by timPrachasri** [comment]
@ephys Hi, I've got the same issue, quick question, if I just use a loop create rather than bulk create (wrapped with transaction), would that significantly reduce a database speed or sth?

**Comment by ephys** [comment]
@timPrachasri it depends on how many entities you are inserting. `bulkCreate` executes everything in one big `INSERT`. Using `insert` would result in one query per call.

It's not ideal but if it's blocking you, it may be an acceptable solution until a fix is available

**Comment by ephys** [comment]
Yep! But the transaction will revert all calls if there was an issue
Actually wrapped in a transaction, it's 2 extra calls:
- start transaction
- and commit (or rollback) transaction

**Comment by devbeoservice** [comment]
```
//hax
  if(s.name){
    s = s.name
  }
```
  
super hacky fix. don't use it however might help with debug.

**Comment by natoszme** [comment]
Hi everyone! Same bug here. @ephys do you have an ETA for the fix? Thanks!

**Comment by JuliaRakitina** [comment]
I wrote my own workaround with a raw query :-/

**Comment by ephys** [comment]
No ETA yet, my focus is currently on #13817. If you know what is causing the issue, don't hesitate to open a PR with a test and the fix, otherwise this will have to wait until that other issue is resolved :/

**Comment by avrelaun** [comment]
Same issue here

**Comment by k4lu-0p** [comment]
up

**Comment by davidchriqui** [comment]
Same issue

**Comment by pandrews-hdai** [comment]
Having the same problem as well.  Definitely resulting from Sequelize's attempt to guess what columns are part of the unique key to write the upsert around.  The root cause of the issue seems to be in the bulkCreate() method in model.js in the IF block around line 1646 in version 6.21.6, in a very subtle difference in how Unique keys are handled vs a named index when trying to guess what keys to make part of the upsert conflict keys list.

model.uniqueKeys[i].fields contains a simple list of strings while model._indexes[i].fields contains a list of objects of which name is a property.

So if Sequelize guesses the "first unique key" to use for upsert conflicts then eventually it passes a string to Utils.removeTicks(), but if Sequelize guesses an index specified on the model (May require more than 1 field as part of the index, haven't tested) then it passes an object to Utils.removeTicks() instead of the field name so the method blows up.

A possible patch could be to simply replace this block of code
```
            if (i.unique && !i.where) {
              upsertKeys.push(...i.fields);
            }
```
with this block:
```
            if (i.unique && !i.where) {
              upsertKeys.push(...i.fields.map((field) => field.name));
            }
```
Which does resolve the error by normalizing the upsertKeys list that's generated to only include strings regardless of whether Sequelize uses unique keys or unique indexes, but may demonstrate my fundamental lack of knowledge of the finer points of operating inside the Sequelize core or a knock-on glitch of the way Robin's sequelize-typescript project generates Sequelize models from decorators, because it uses the name of the Typescript class' decorated property instead of the DB table name if that's specified via the @Column() decorator.  If I can find a clean resolution on my own I may be able to fork and open a PR but for now this should be good debugging information for someone more familiar with Sequelize's internal methods for resolving field names.

**Comment by pandrews-hdai** [comment]
I have a functioning workaround requiring no fixes in Sequelize itself, but some checks or type defs might help future-proof the functionality:

IF you are defining the indexes declaratively like in the original example from @MrNickGreene don't define your field list using the object notation with names, IE
```
        fields: [
          "facebook_platform_connection_id",
          "page_id",
        ]
```
Instead of:
```
        fields: [
          { name: "facebook_platform_connection_id" },
          { name: "page_id" },
        ]
```

If you're defining your models using sequelize-typescript's @Table and @Column decorators, define the indexes on the @Table decorator so that you can specify the database field names:
```
@Table({
  modelName: 'facebook_platform_connections',
  freezeTableName: true,
  indexes: [{ name: 'facebook_page_connections_pkey', fields: ['facebook_platform_connection_id', 'page_id'], unique: true }],
})
```

**Comment by ephys** [comment]
Looks like you did the necessary research to fix this :) If you're motivated, we'd love a PR that adds a failing test & the fix you mentioned

**Comment by natoszme** [comment]
What should I do if I have the following? @pandrews-hdai 
```
{
  name: "pk_shipment",
  unique: true,
  fields: [
    { name: "id" },
  ]
}
```

**Comment by NathanAllmeida** [comment]
nothing yet? same problem

**Comment by ephys** [comment]
I'm pretty sure this was fixed in Sequelize 7 as we cleaned up indices recently

**Comment by kabra4** [comment]
i also have the same problem.

**Comment by antypko** [comment]
What if unique index is not based on table columns but on result of function like ST_SnapToGrid?

**Comment by noahsaso** [comment]
I encounter the same issue using `bulkCreate` with `updateOnDuplicate` when a unique index exists with fields that must be defined as an object with `name` because another property is set (like `order` or `operator`).

A workaround for v6 is to set `conflictAttributes` manually in `bulkCreate` to the names of the fields in the unique index, so it uses those strings instead of finding the unique index that contains object fields when it expects strings.
