### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by ethergru** [sequelize/sequelize#13662]
```
Expertise.findAll({
        where: {
          expertId: userId
        },
        include: [
          {
            model: User,
            as: 'expert',
            attributes: [
              'avatar',
              'firstname',
              'lastname',
            ]
          }, {
            model: ExpertiseReview,
            as: 'reviews',
          }
        ],
      })
```
It is working. and then I've added this one.
```
attributes:[
   [sequelize.fn('AVG', sequelize.col('reviews.rate')), 'avgRating'],
],
```
or
```
attributes:[
   [sequelize.fn('COUNT', sequelize.col('reviews.rate')), 'countRating'],
],
```
the following error has occurred.
```
[0]   TypeError: Cannot read property '0' of undefined
[0]     at D:\...\expertise.controller.ts:71:64
[0]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
How can I solve this problem?

**Comment by Bishwodahal** [comment]
Is the problem still unsolved?
What sql query did it generate?

**Comment by ephys** [comment]
stale bot closed this but I still want to give you a response: the error arises in `expertise.controller.ts` so it looks like an issue in your code?

Nonetheless it's going to be difficult to help with without a SSCCE (https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md#opening-an-issue-to-report-a-bug) which replicates the issue.
