### ISSUE TITLE
Query while connected to MySQL, get the rare error "Connection lost: The server closed the connection".

### ISSUE THREAD

**Issue by nishibata** [sequelize/sequelize#13984]
## Issue Creation Checklist

[x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

When I use Sequelize's Pool and run a query on a MySQL connection, I rare get an error. The error is "Connection lost: The server closed the connection".

The error cannot be avoided by using the retry.

### What do you expect to happen?

If the query is disconnected when it is executed, we want the connection to be destroyed, and when we retry, we want it to succeed.

### What is actually happening?

This is StackTrace.
```js
stack: Error
    at Query.run (/workspace/node_modules/sequelize/dist/lib/dialects/mysql/query.js:52:25)
    at /workspace/node_modules/sequelize/dist/lib/sequelize.js:313:28
    at async MySQLQueryInterface.select (/workspace/node_modules/sequelize/dist/lib/dialects/abstract/query-interface.js:396:12)
    at async Function.findAll (/workspace/node_modules/sequelize/dist/lib/model.js:1119:21)
    at async Function.findOne (/workspace/node_modules/sequelize/dist/lib/model.js:1213:12)
    at async Function.findByPk (/workspace/node_modules/sequelize/dist/lib/model.js:1200:12)
```

When I examined the contents of this error, it was a "SequelizeDatabaseError" with a code of "PROTOCOL_CONNECTION_LOST".

The ConnectionManager implemented for MySQL is designed to handle the connection's error event and destroy the connection from the Pool.
However, the mysql2 connection passes the error to the onResult of the command if the command has already been added. And there are cases where the error event is not emit.

This is an excerpt from the mysql2 connection implementation.
```js
    if (this._command && this._command.onResult) {
      this._command.onResult(err);
~~~~~~~~~~~
    if (bubbleErrorToConnection || this._pool) {
      this.emit('error', err);
    }
```

So, after getting the pool from the ConnectionManager, if the connection is disconnected for some reason at the time of executing the query, Sequelize will not destroy this connection, right?

If this error occurs in query.run, I think the connection will just be returned to the Pool.
```js
      const connection = await (options.transaction ? options.transaction.connection : this.connectionManager.getConnection(options));
      if (this.options.dialect === "db2" && options.alter) {
        if (options.alter.drop === false) {
          connection.dropTable = false;
        }
      }
      const query = new this.dialect.Query(connection, this, options);
      try {
        await this.runHooks("beforeQuery", options, query);
        checkTransaction();
        return await query.run(sql, bindParameters);
      } finally {
        await this.runHooks("afterQuery", options, query);
        if (!options.transaction) {
          await this.connectionManager.releaseConnection(connection);
        }
      }
```

### Additional context

There may be a feature I'm not aware of that avoids this.

### Environment

- Sequelize version: 6.12.5 
- Node.js version: 14.18.1 
- mysql2 version: 2.3.3

### How does this problem relate to dialects?

- [ ] I think this problem happens regardless of the dialect.
- [X] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [X] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by nishibata** [comment]
I used a transaction for my query. But an error occurred. However, it is a rare error as well. Out of hundreds of thousands of requests, there is about one chance of failure.
```
Error: Can't add new command when connection is in closed state
    at Connection._addCommandClosedState (/workspace/node_modules/mysql2/lib/connection.js:148:17)
    at Connection.query (/workspace/node_modules/mysql2/lib/connection.js:546:17)
    at results (/workspace/node_modules/sequelize/dist/lib/dialects/mysql/query.js:60:22)
    at new Promise (<anonymous>)
    at Query.run (/workspace/node_modules/sequelize/dist/lib/dialects/mysql/query.js:59:25)
    at /workspace/node_modules/sequelize/dist/lib/sequelize.js:313:28
    at async MySQLQueryInterface.startTransaction (/workspace/node_modules/sequelize/dist/lib/dialects/abstract/query-interface.js:515:12)
    at async Transaction.prepareEnvironment (/workspace/node_modules/sequelize/dist/lib/transaction.js:85:7)
    at async Sequelize.transaction (/workspace/node_modules/sequelize/dist/lib/sequelize.js:457:7)
```

MySQL timeout setting is 8 hours. User requests are sent incessantly for 24 hours. So, there is little chance of a timeout from MySQL.
Is Sequelize's operation to destroy idle connections safe?
I don't know the cause, but I think there are very rare cases where a connection that has already been closed is used.

**Comment by ksze** [comment]
I'm also running into the "Can't add new command when connection is in closed state" problem. What's really weird is that this happens even when I create a new Sequelize instance and explicitly close it every time.

**Comment by brandonw** [comment]
Found this while searching for transaction retry issues.. you are likely encountering the same issue that we are. The issue is not sourced from a bug in connection management, but rather the requirements of transactional queries.

A transaction is tied tightly to a connection because that is where the transactional context is stored. If you try and retry a query that is within a transaction, the normal sequelize behavior of:

1. release the connection you just tried executing with when it failed
2. acquire a new connection and try the same query again

Is not done, because releasing the connection effectively cancels the transaction, which is "giving up" the retry process early.

Instead, it just repeatedly retries with the same connection, and the node-mysql2 [default] driver gives you the Can't add new command when connection is in closed state" error, in essence telling you "this connection is already closed, you can't use it".
