### ISSUE TITLE
ConnectionManager.getConnection was called after the connection manager was closed!

### ISSUE THREAD

**Issue by ufhy** [sequelize/sequelize#14141]
## Issue Creation Checklist

[ x ] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description
Running some simple query (MySQL) for SELECt and INSERT without any model 

### SSCCE

**Here is the link to the SSCCE for this issue:** LINK-HERE 

```js
import { Command, CommandRunner, Option } from 'nest-commander';
import { Sequelize } from 'sequelize-typescript';
import * as bcrypt from 'bcrypt';
import { ConfigService } from '@nestjs/config';
import { v4 as uuidv4 } from 'uuid';
import { formatISO9075 } from 'date-fns';
import { now } from '@/support/helpers/date';
import { QueryTypes } from 'sequelize';
import { Role } from '@/features/user/models/role.model';
import { green, red } from 'colors';

@Command({
  name: 'user:admin',
  description: 'Generate or update admin user',
})
export class UserAdmin implements CommandRunner {
  constructor(
    private readonly sequelize: Sequelize,
    private readonly configService: ConfigService,
  ) {}

  async run(passedParam: string[], options?: { username?: string; role?: string }): Promise<void> {
    // User generate/update
    const username = options.username ? options.username : 'administrator';
    let user = await this.sequelize.query('SELECT * FROM user_users WHERE username = :username', {
      replacements: { username },
      plain: true,
      raw: true,
      type: QueryTypes.SELECT,
    });
    if (!user) {
      const password = 'qwerty';
      const saltOrRounds = this.configService.get<number>('hasing.rounds');
      const salt = await bcrypt.genSalt(saltOrRounds);
      const hash = await bcrypt.hash(password, salt);
      await this.sequelize.query(
        'INSERT INTO user_users (uid, username, email, password, password_salt, created_at, updated_at) VALUES (:uid, :username, :email, :password, :password_salt, :created_at, :updated_at)',
        {
          replacements: {
            uid: uuidv4(),
            username,
            email: 'cms_admin@localhost.test',
            password: hash,
            password_salt: salt,
            created_at: formatISO9075(now()),
            updated_at: formatISO9075(now()),
          },
          raw: true,
          type: QueryTypes.INSERT,
        },
      );
      user = await this.sequelize.query('SELECT * FROM user_users WHERE username = :username', {
        replacements: { username },
        plain: true,
        raw: true,
        type: QueryTypes.SELECT,
      });
    }

    // Role generate/update
    const roleName = options.role ? options.role : 'super-admin';
    let role = await this.sequelize.query('SELECT * FROM user_roles WHERE name = :role', {
      replacements: { role: roleName },
      plain: true,
      raw: true,
      type: QueryTypes.SELECT,
    });
    if (!role) {
      await this.sequelize.query(
        'INSERT INTO user_roles (name, description, created_at, updated_at) VALUES (:name, :description, :created_at, :updated_at)',
        {
          replacements: {
            name: roleName,
            description: 'Super admin role',
            created_at: formatISO9075(now()),
            updated_at: formatISO9075(now()),
          },
          raw: true,
          type: QueryTypes.INSERT,
        },
      );
      role = await this.sequelize.query('SELECT * FROM user_roles WHERE name = :role', {
        replacements: { role: roleName },
        plain: true,
        raw: true,
        type: QueryTypes.SELECT,
      });
    }

    this.sequelize
      .query('SELECT * FROM user_permissions', {
        raw: true,
        type: QueryTypes.SELECT,
      })
      .then(async (permissions) => {
        const transaction = await this.sequelize.transaction();
        try {
          permissions.forEach(async (permission: { id: string; name: string }) => {
            const hasPermission = await this.sequelize.query(
              'SELECT * FROM user_role_permissions WHERE role_id = :role_id AND permission_id = :permission_id',
              {
                replacements: {
                  role_id: (role as Role).id,
                  permission_id: permission.id,
                },
                plain: true,
                raw: true,
                type: QueryTypes.SELECT,
              },
            );
            if (!hasPermission) {
              await this.sequelize.query(
                'INSERT INTO user_role_permissions (role_id, permission_id) VALUES (:role_id, :permission_id)',
                {
                  replacements: {
                    role_id: (role as Role).id,
                    permission_id: permission.id,
                  },
                  raw: true,
                  type: QueryTypes.INSERT,
                },
              );
            }
          });

          await transaction.commit();

          console.log(green('Successfully generated/updated admin user'));
        } catch (err) {
          console.log(red(err));
          await transaction.rollback();
        }
      });
  }

  @Option({
    flags: '-u, --username <username>',
    description: 'Generate or update with username e.g. --username=administrator)',
  })
  parseUsername(value: string) {
    return value;
  }

  @Option({
    flags: '-r, --role <role>',
    description: 'Generate or update with role e.g. --role=super-admin)',
  })
  parseRole(value: string) {
    return value;
  }
}
```

### What do you expect to happen?

Expected to insert multiple rows in mysql using permission.foreach()

### What is actually happening?

After query (SELECT) one row in foreach statement message always ``ConnectionManager.getConnection was called after the connection manager was closed``

```
yarn run v1.22.17
$ ts-node -r tsconfig-paths/register console/main.ts user:admin
Executed (default): SELECT 1+1 AS result Elapsed time: 1ms
Executed (default): SELECT * FROM user_users WHERE username = 'administrator' Elapsed time: 2ms
Executed (default): SELECT * FROM user_roles WHERE name = 'super-admin' Elapsed time: 1ms
Executed (default): SELECT * FROM user_permissions Elapsed time: 4ms
/Volumes/Home/Documents/SourceCode/kmacca_node/macca-backend/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:113
      throw new Error('ConnectionManager.getConnection was called after the connection manager was closed!');
            ^
Error: ConnectionManager.getConnection was called after the connection manager was closed!
    at ConnectionManager.getConnection (/Volumes/Home/Documents/SourceCode/kmacca_node/macca-backend/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:113:13)
    at Transaction.prepareEnvironment (/Volumes/Home/Documents/SourceCode/kmacca_node/macca-backend/node_modules/sequelize/lib/transaction.js:115:60)
    at Sequelize.transaction (/Volumes/Home/Documents/SourceCode/kmacca_node/macca-backend/node_modules/sequelize/lib/sequelize.js:1105:25)
    at /Volumes/Home/Documents/SourceCode/kmacca_node/macca-backend/console/commands/user/admin.command.ts:96:50
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Additional context

Maybe sequelize has some connection configure to handle this?

### Environment

- Sequelize version: 6.15.0 
- Node.js version: 16.13.0 
- Yarn version: 1.22.1 
- If TypeScript related: TypeScript version: 4.3.5 

### How does this problem relate to dialects?

- [ x ] I think this problem happens regardless of the dialect.
- [ ] I think this problem happens only for the following dialect(s): 
- [ ] I don't know, I was using PUT-YOUR-DIALECT-HERE, with connector library version XXX and database version XXX

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ufhy** [comment]
damn i was wrong
this is my reference..

https://stackoverflow.com/a/38362312
