### ISSUE TITLE
Error to connect SEQUELIZE with Redshift

### ISSUE THREAD

**Issue by apinto2-scc** [sequelize/sequelize#14190]
## Issue Creation Checklist

- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### SSCCE

package.json
```
{
  "name": "core-datawarehouse",
  "version": "1.0.0",
  "description": "Manage SOS datawarehouse by code.",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/scc-cscs/core-datawarehouse.git"
  },
  "author": "A.PINTO",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/scc-cscs/core-datawarehouse/issues"
  },
  "homepage": "https://github.com/scc-cscs/core-datawarehouse#readme",
  "dependencies": {
    "@sequelize/core": "^7.0.0-alpha.10",
    "mysql2": "^2.3.3",
    "pg": "^8.7.3",
    "pg-hstore": "^2.3.4",
    "sequelize": "^6.17.0"
  }
}

```

index.js
```
const { Sequelize } = require('@sequelize/core');

const sequelize = new Sequelize('database', 'user', 'password', {
  host: '127.0.0.1',
  port: '3312',
  dialect: 'postgres',
  dialectOptions: {
    clientMinMessages: 'ignore'
  }
});

sequelize.authenticate().then(function(sucess){
    console.log("success");
}).catch(function(error){
    console.log(error);
})
```

### What do you expect to happen?

I expect to have a success message to connect on redshift db

### What is actually happening?

_The output was Bar!_

```
error: unrecognized configuration parameter "standard_conforming_strings"
    at Parser.parseErrorMessage (C:\Repos\core-datawarehouse\node_modules\pg-protocol\dist\parser.js:287:98)
    at Parser.handlePacket (C:\Repos\core-datawarehouse\node_modules\pg-protocol\dist\parser.js:126:29)
    at Parser.parse (C:\Repos\core-datawarehouse\node_modules\pg-protocol\dist\parser.js:39:38)
    at Socket.<anonymous> (C:\Repos\core-datawarehouse\node_modules\pg-protocol\dist\index.js:11:42)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 161,
  severity: 'ERROR',
  code: '42704',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: '../src/pg/src/backend/utils/misc/guc.c',
  line: '36182',
  routine: 'flatten_set_variable_args'
}
```

### Additional context

N/A

### Environment

- Sequelize version: ^7.0.0-alpha.10
- Node.js version: v17.2.0
- If TypeScript related: TypeScript version:
- Database & Version: AWS Redshift
- Connector library & Version: "pg": "^8.7.3", "pg-hstore": "^2.3.4",

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [x] No, I don't have the time and I wouldn't even know how to start.

**Comment by ephys** [comment]
I don't think we support redshift. It's not fully compliant with postgres so it's likely missing some option we (or the pg package) use.

**Comment by WikiRik** [comment]
We do support Redshift, see the documentation about that here; https://sequelize.org/v6/manual/dialect-specific-things.html

I would recommend using v6 for now, v7 is still in early alpha. Does this issue also occur on v6?

Also, it seems you have both in your package.json now which might also cause issues later on.

**Comment by apinto2-scc** [comment]
> We do support Redshift, see the documentation about that here; https://sequelize.org/v6/manual/dialect-specific-things.html
> 
> I would recommend using v6 for now, v7 is still in early alpha. Does this issue also occur on v6?
> 
> Also, it seems you have both in your package.json now which might also cause issues later on.

I updated my package.json and still have the same issue.

```
{
  "name": "core-datawarehouse",
  "version": "1.0.0",
  "description": "Manage SOS datawarehouse by code.",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/scc-cscs/core-datawarehouse.git"
  },
  "author": "A.PINTO",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/scc-cscs/core-datawarehouse/issues"
  },
  "homepage": "https://github.com/scc-cscs/core-datawarehouse#readme",
  "dependencies": {
    "mysql2": "^2.3.3",
    "pg": "^8.7.3",
    "pg-hstore": "^2.3.4",
    "sequelize": "^6.17.0"
  }
}
```

```
error: unrecognized configuration parameter "standard_conforming_strings"
    at Parser.parseErrorMessage (C:\Repos\core-datawarehouse\node_modules\pg-protocol\dist\parser.js:287:98)
    at Parser.handlePacket (C:\Repos\core-datawarehouse\node_modules\pg-protocol\dist\parser.js:126:29)
    at Parser.parse (C:\Repos\core-datawarehouse\node_modules\pg-protocol\dist\parser.js:39:38)
    at Socket.<anonymous> (C:\Repos\core-datawarehouse\node_modules\pg-protocol\dist\index.js:11:42)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 161,
  severity: 'ERROR',
  code: '42704',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: '../src/pg/src/backend/utils/misc/guc.c',
  line: '36182',
  routine: 'flatten_set_variable_args'
```

**Comment by ephys** [comment]
Apparently you can disable setting the `standard_conforming_strings` parameter https://github.com/sequelize/sequelize/blob/04607c4b85db9c590c6b9d735822d3000f063641/src/sequelize.js#L152

**Comment by apinto2-scc** [comment]
> Apparently you can disable setting the `standard_conforming_strings` parameter
> 
> https://github.com/sequelize/sequelize/blob/04607c4b85db9c590c6b9d735822d3000f063641/src/sequelize.js#L152
> 
> It's unfortunate that we don't test against redshift but I can't find an official docker image for it

Thank you for your help, I was able to connect successfully.
Below the snippet in success :

```
const { Sequelize } = require('sequelize');

const sequelize = new Sequelize('database', 'user', 'password', {
  host: '127.0.0.1',
  port: '3312',
  dialect: 'postgres',
  standardConformingStrings: false,
  dialectOptions: {
    clientMinMessages: 'ignore'
  }
});

sequelize.authenticate().then(function(sucess){
    console.log("success");
}).catch(function(error){
    console.log(error);
})
```

**Comment by apinto2-scc** [comment]
🙏🙏🙏
