### ISSUE TITLE
Error when attempting to connect to DB2 database using the ibmi dialect

### ISSUE THREAD

**Issue by sammichael25** [sequelize/sequelize#14193]
I'm following the documentation steps here [https://sequelize.org/master/manual/dialect-specific-things.html#ibm-i](https://sequelize.org/master/manual/dialect-specific-things.html#ibm-i) to connect to a db2 database through an existing odbc connection. However when I replace the DSN with my ODBCs name and fill in the UID and PWD I'm getting the following error.

`src/config/database.config.ts(3,7): error TS2451: Cannot redeclare block-scoped variable 'db'.
src/config/database.config.ts(4,5): error TS2322: Type '"ibmi"' is not assignable to type 'Dialect | undefined'.
src/config/database.config.ts(10,7): error TS2451: Cannot redeclare block-scoped variable 'db'.`

This is an example what my connection looks like below. I've also tried it with v6

```typescript
import { Sequelize } from "@sequelize/core";

const db = new Sequelize(`${process.env.DSN}`, 'root', 'pa$$w0rd', {
    dialect: 'ibmi',
    dialectOptions: {
      odbcConnectionString: 'CMT=1;NAM=0;DATABASE=testdb;HOSTNAME=172.20.0.1;UID=root;PWD=pa$$w0rd;PORT=3000'
    }
  });
```

**Comment by ephys** [comment]
`ibmi` is [missing from our typings](https://github.com/sequelize/sequelize/blob/main/src/sequelize.d.ts#L171). You can use `// @ts-expect-error` until we resolve this.

**Comment by sammichael25** [comment]
Adding `// @ts-expect-error` throws another error

```
throw new Error(`The dialect ${this.getDialect()} is not supported. Supported dialects: mssql, mariadb, mysql, postgres, db2, ibmi and sqlite.`);
        ^
Error: The dialect imbi is not supported. Supported dialects: mssql, mariadb, mysql, postgres, db2, ibmi and sqlite.
    at new Sequelize (C:\Users\00011945\Downloads\nodejs-api-from-scratch-master\node_modules\@sequelize\core\lib\sequelize.js:193:15)
    at Object.<anonymous> (C:\Users\00011945\Downloads\nodejs-api-from-scratch-master\dist\config\database.config.js:4:12)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\00011945\Downloads\nodejs-api-from-scratch-master\dist\app.js:12:43)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
```

However connecting like the undermentioned works but then the query generated throws a syntax error.

```typescript
import { Sequelize } from "@sequelize/core";
import { DataTypes } from "@sequelize/core";

const db = new Sequelize(`ibmi://10.250.90.32:1526/${process.env.DSN}`);

const DeviceModel = db.define('Device', {
        device_id: {type: DataTypes.INTEGER, allowNull: true},
        timestamp: {type: DataTypes.STRING, allowNull: true},
        status: {type: DataTypes.STRING, allowNull: true},
        sent_to_netmon: {type: DataTypes.INTEGER, allowNull: true},
        seq_nbr: {type: DataTypes.INTEGER, allowNull: true},
        raw_status: {type: DataTypes.STRING, allowNull: true},
        userid: {type: DataTypes.STRING, allowNull: true},
        ack_timestamp: {type: DataTypes.STRING, allowNull: true},
    }, {});

try {
    const devices= await DeviceModel.findAll();
    console.log(devices)
} catch (error) {
    if(error instanceof Error)
    console.log(error)
}
```

The above code throws the following. I'm guessing its because of the quotes around the selected fields.
```
Executing (default): SELECT "id", "device_id", "timestamp", "status", "sent_to_netmon", "seq_nbr", "raw_status", "userid", "ack_timestamp", "createdAt", "updatedAt" FROM "Devices" AS "Device"
Error
    at Query.run (C:\Users\00011945\Downloads\nodejs-api-from-scratch-master\node_modules\@sequelize\core\lib\dialects\ibmi\query.js:25:24)
    at C:\Users\00011945\Downloads\nodejs-api-from-scratch-master\node_modules\@sequelize\core\lib\sequelize.js:321:28
    at async IBMiQueryInterface.select (C:\Users\00011945\Downloads\nodejs-api-from-scratch-master\node_modules\@sequelize\core\lib\dialects\abstract\query-interface.js:402:12)
    at async Function.findAll (C:\Users\00011945\Downloads\nodejs-api-from-scratch-master\node_modules\@sequelize\core\lib\model.js:1136:21)
    at async App.initialiseDatabaseConnection (C:\Users\00011945\Downloads\nodejs-api-from-scratch-master\dist\app.js:56:30) {
  name: 'SequelizeDatabaseError',
  parent: {
    state: '42000',
    code: -201,
    message: '[Informix][Informix ODBC Driver][Informix]A syntax error has occurred.'
  },
  original: {
    state: '42000',
    code: -201,
    message: '[Informix][Informix ODBC Driver][Informix]A syntax error has occurred.'
  },
  sql: undefined,
  parameters: {}
}
```

**Comment by ephys** [comment]
Is it possible you have a typo? The error says you used dialect `imbi` instead of `ibmi`

As for the syntax error, I'll hand off this part to @markdirish as I have no experience with db2 or ibmi

**Comment by sammichael25** [comment]
You were right, fixing the typo got rid of the first error. Now I just have the syntax error. Thanks for the help so far.
