### ISSUE TITLE
invalid input syntax for type interval: "undefined"

### ISSUE THREAD

**Issue by sivabalan02** [sequelize/sequelize#14493]
Whenever i running select or insert query i getting this following error 

```invalid input syntax for type interval: "undefined"
    at Parser.parseErrorMessage (xxxx/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (xxxx/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (xxxx/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (xxxxx/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
```

This is my package.json file 

```	"dependencies": {
		"apn": "^2.2.0",
		"aws-sdk": "^2.1090.0",
		"bcrypt": "^5.0.1",
		"date-and-time": "^2.0.1",
		"decimal.js": "^10.3.1",
		"dotenv": "^10.0.0",
		"express": "^4.17.1",
		"express-group-routes": "^1.1.0",
		"fcm-node": "^1.6.1",
		"handlebars": "^4.7.7",
		"helmet": "^4.6.0",
		"ioredis": "^4.28.2",
		"joi": "^17.5.0",
		"jose": "^4.3.7",
		"lodash": "^4.17.21",
		"mmmagic": "^0.5.3",
		"multer": "^1.4.4",
		"nodemailer": "^6.7.2",
		"pg": "^8.7.1",
		"pg-hstore": "^2.3.4",
		"rate-limiter-flexible": "^2.3.6",
		"sequelize": "^6.12.0-beta.3",
		"sequelize-cli": "^6.3.0",
		"winston": "^3.3.3",
		"winston-daily-rotate-file": "^4.5.5",
		"winston-mail": "^2.0.0"
	},
	"devDependencies": {
		"better-docs": "^2.3.2",
		"chai": "^4.3.6",
		"chai-http": "^4.3.0",
		"cross-env": "^7.0.3",
		"@faker-js/faker": "^6.1.2",
		"jsdoc": "^3.6.7",
		"mocha": "^7.1.0",
		"mochawesome": "^7.1.3",
		"nodemon": "^2.0.15",
		"nyc": "^15.1.0"
	}
```

Node: v16.13.1
NPM: 8.1.2
OS: ubuntu 20.04
Postgresql: 14.2.1

**Comment by ephys** [comment]
We won't be able to help you without a SSCCE that replicates the issue, we don't have enough information https://github.com/sequelize/sequelize-sscce

**Comment by sivabalan02** [comment]
I forgot to set the timezone. now its working. Thanks for the reply
