### ISSUE TITLE
Upgrading from v5.21.13 to v6.21.3 results in "Please install mysql2 package manually" errors

### ISSUE THREAD

**Issue by asnaseer-resilient** [sequelize/sequelize#14780]
## Issue Creation Checklist

- [x] I understand that my issue will be automatically closed if I don't fill in the requested information
- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

We upgraded from v5.21.13 to v6.21.3 and now see "Please install mysql2 package manually" error when trying to construct a `Sequelize` object.

### Reproducible Example

We used to construct the `Sequelize` object as follows:
```
const sequelize = new Sequelize('mysql://my-host-name:3306/call_flow_designer_api_db_dev', {
      dialect: 'mysql',
      ...other options not relevant to this issue...
    });
```
We use webpack to bundle our code and our package.json contains these relevant dependencies:
```
  ...
  "dependencies": {
    ...,
    "mysql2": "^2.3.3",
    "noop2": "^2.0.0",
    "reflect-metadata": "^0.1.13",
    "sequelize": "^6.21.3",
    "sequelize-typescript": "^2.1.3",
    "umzug": "^3.1.1"
  },
  "devDependencies": {
    ...,
    "@types/node": "^17.0.25",
    "@types/sequelize": "^4.28.14",
    "ts-loader": "^9.3.1",
    "ts-node": "^10.8.2",
    "typescript": "^4.7.4",
    "webpack": "^5.73.0",
    "webpack-cli": "^4.10.0",
    "webpack-node-externals": "^3.0.0"
  },
  ...
```
The error we see is:
```
"trace":["Error: Please install mysql2 package manually","    at ConnectionManager._loadDialectModule (/var/task/db-schema-migrator.js:140620:15)","    at new ConnectionManager (/var/task/db-schema-migrator.js:148388:21)","    at new MysqlDialect (/var/task/db-schema-migrator.js:148306:30)","    at new Sequelize (/var/task/db-schema-migrator.js:98620:20)","    at new DbSchemaMigrationsRunner (/var/task/db-schema-migrator.js:185133:29)","    at LambdaDbSchemaMigrator.<anonymous> (/var/task/db-schema-migrator.js:185180:45)","    at Generator.next (<anonymous>)","    at fulfilled (/var/task/db-schema-migrator.js:185159:58)","    at processTicksAndRejections (internal/process/task_queues.js:95:5)"]}
```

We then found this issue - https://github.com/sequelize/sequelize/issues/9608

Which indicated that we can solve the problem by specifying `dialectModule` in the options to the constructor as follows:
```
import mysql2 from 'mysql2';

const sequelize = new Sequelize('mysql://my-host-name:3306/call_flow_designer_api_db_dev', {
      dialect: 'mysql',
      dialectModule: mysql2,
      ...other options not relevant to this issue...
    });
```
However, this still produced the same error.
We then had a look in the code to see why this still failed and believe there is a bug there.

In `src/sequelize.js` it correctly sets up `this.options` to contain both `dialect` and `dialectModule`. However, these options do not seem to be transferred into `connectionConfig` within the constructor and hence they also do not appear in `this.config` when that is initialised further on in the constructor.
If you then look in `connection-manager.ts` here https://github.com/sequelize/sequelize/blob/b382a3239137bebdef26912f75780041efa0ad98/src/dialects/abstract/connection-manager.ts#L134
you will notice that the `_loadDialectModule` method refers to `this.sequelize.config.dialectModulePath` and `this.sequelize.config.dialectModule` which are always undefined due to the above bug (we think).

### What do you expect to happen?

We should be able to successfully construct a `Sequelize` object.

### What is actually happening?

We see error:
Please install mysql2 package manually

### Environment

- Sequelize version: v6.21.3
- Node.js version: 14.17.5
- If TypeScript related: TypeScript version: 4.7.4
- Database & Version: We use AWS Aurora MySQL 5.7
- Connector library & Version: N/A

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [ ] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by WikiRik** [comment]
No worries, thanks for the followup!

**Comment by asnaseer-resilient** [comment]
Just to confirm, the instructions at https://github.com/sequelize/sequelize/issues/9608 did indeed work for us - we just forgot to update all places where we were constructing a `Sequelize` object.
