### ISSUE TITLE
Relation's attribute in top level where clause with limit

### ISSUE THREAD

**Issue by martinboulais** [sequelize/sequelize#15121]
## Issue Creation Checklist

- [X] I understand that my issue will be automatically closed if I don't fill in the requested information
- [X] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

When querying a model with a relation with a condition on one of the relation's attributes and a limit, Sequelize throws an error because of an invalid SQL request.

This issue has already been reported here : https://github.com/sequelize/sequelize/issues/12635
But the issue has been closed using a workaround (using `duplicating: false`) that is not viable in every situation, and particularly if we need to fetch other relation (one to many or many to many) because the limit will apply on the duplicated rows.

### Reproducible Example

Here is the link to the SSCCE for this issue: [SSCCE](https://github.com/sequelize/sequelize-sscce/pull/239)

### What do you expect to happen?

When querying a relation and applying a where condition on one of this relation's attributes, I expect to get the resulting models with the other relations needed and in the specified limit without having to use `duplicating: false` option.

### What is actually happening?

An error is thrown (example from the SSCCE CI):
```
Error
    at Database.<anonymous> (/home/runner/work/sequelize-sscce/sequelize-sscce/node_modules/sequelize/src/dialects/sqlite/query.js:227:27)
    at /home/runner/work/sequelize-sscce/sequelize-sscce/node_modules/sequelize/src/dialects/sqlite/query.js:225:50
    at new Promise (<anonymous>)
    at Query.run (/home/runner/work/sequelize-sscce/sequelize-sscce/node_modules/sequelize/src/dialects/sqlite/query.js:225:12)
    at /home/runner/work/sequelize-sscce/sequelize-sscce/node_modules/sequelize/src/sequelize.js:649:28
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async SQLiteQueryInterface.select (/home/runner/work/sequelize-sscce/sequelize-sscce/node_modules/sequelize/src/dialects/abstract/query-interface.js:1001:12)
    at async Function.findAll (/home/runner/work/sequelize-sscce/sequelize-sscce/node_modules/sequelize/src/model.js:1816:21)
    at async run (/home/runner/work/sequelize-sscce/sequelize-sscce/src/sscce-sequelize-6.ts:136:11)
    at async wrappedRun (/home/runner/work/sequelize-sscce/sequelize-sscce/setup/runner.ts:34:7) {
  name: 'SequelizeDatabaseError',
  parent: [Error: SQLITE_ERROR: no such column: Bar.name] {
    errno: 1,
    code: 'SQLITE_ERROR',
    sql: "SELECT `Foo`.*, `Bar`.`id` AS `Bar.id`, `Bar`.`name` AS `Bar.name`, `Baz`.`id` AS `Baz.id`, `Baz->BarBaz`.`FooId` AS `Baz.BarBaz.FooId`, `Baz->BarBaz`.`BazId` AS `Baz.BarBaz.BazId` FROM (SELECT `Foo`.`id`, `Foo`.`BarId` FROM `Foos` AS `Foo` WHERE `Bar`.`name` = 'first' LIMIT 2) AS `Foo` LEFT OUTER JOIN `Bars` AS `Bar` ON `Foo`.`BarId` = `Bar`.`id` LEFT OUTER JOIN ( `BarBazs` AS `Baz->BarBaz` INNER JOIN `Bazs` AS `Baz` ON `Baz`.`id` = `Baz->BarBaz`.`BazId`) ON `Foo`.`id` = `Baz->BarBaz`.`FooId`;"
  },
  original: [Error: SQLITE_ERROR: no such column: Bar.name] {
    errno: 1,
    code: 'SQLITE_ERROR',
    sql: "SELECT `Foo`.*, `Bar`.`id` AS `Bar.id`, `Bar`.`name` AS `Bar.name`, `Baz`.`id` AS `Baz.id`, `Baz->BarBaz`.`FooId` AS `Baz.BarBaz.FooId`, `Baz->BarBaz`.`BazId` AS `Baz.BarBaz.BazId` FROM (SELECT `Foo`.`id`, `Foo`.`BarId` FROM `Foos` AS `Foo` WHERE `Bar`.`name` = 'first' LIMIT 2) AS `Foo` LEFT OUTER JOIN `Bars` AS `Bar` ON `Foo`.`BarId` = `Bar`.`id` LEFT OUTER JOIN ( `BarBazs` AS `Baz->BarBaz` INNER JOIN `Bazs` AS `Baz` ON `Baz`.`id` = `Baz->BarBaz`.`BazId`) ON `Foo`.`id` = `Baz->BarBaz`.`FooId`;"
  },
  sql: "SELECT `Foo`.*, `Bar`.`id` AS `Bar.id`, `Bar`.`name` AS `Bar.name`, `Baz`.`id` AS `Baz.id`, `Baz->BarBaz`.`FooId` AS `Baz.BarBaz.FooId`, `Baz->BarBaz`.`BazId` AS `Baz.BarBaz.BazId` FROM (SELECT `Foo`.`id`, `Foo`.`BarId` FROM `Foos` AS `Foo` WHERE `Bar`.`name` = 'first' LIMIT 2) AS `Foo` LEFT OUTER JOIN `Bars` AS `Bar` ON `Foo`.`BarId` = `Bar`.`id` LEFT OUTER JOIN ( `BarBazs` AS `Baz->BarBaz` INNER JOIN `Bazs` AS `Baz` ON `Baz`.`id` = `Baz->BarBaz`.`BazId`) ON `Foo`.`id` = `Baz->BarBaz`.`FooId`;",
  parameters: {}
}
```

### Environment

Environment used to run locally the SSCCE

- Sequelize version: 6.25.0
- Node.js version: v16.15.0
- If TypeScript related: TypeScript version: 4.5.5
- Database & Version: mariadb 10.3
- Connector library & Version: mariadb 3.0.1,

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [X] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [ ] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by ephys** [comment]
Thank you for the thorough sscce and description

This is an issue we're aware of and that we're currently investigating

To help us in our API design, could you tell me how you expect the following to behave?

```ts
await Foo.findAll({
  where: {
    '$Bar.name$': 'first'
  },
  include: [
    'Bar',
    {association: 'Baz'},
  ],
  limit: 2
});
```

is it the following?

- Return 2 Foo
- For each Foo, return all Bar whose `name` is `first`
- For each Foo, return all Baz

**Comment by martinboulais** [comment]
Thank you for your quick reply

- I would expect at most two `Foo` (my example is not impacted by the limit actually, but the objective was simply to show the error) that have a related `Bar` whose have a name of `'first'`
- And, for the two `Foo` I expect them to have the related `Bar` and the complete list of `Baz` filled.

This is not the case in the example, but real-world examples may even require where conditions inside the `Baz` association

**Comment by martinboulais** [comment]
Still an issue

**Comment by ephys** [comment]
This will take some time but I've taken this issue into account in the redesign of `findAll` at #15260
