### ISSUE TITLE
Redshift: function array_agg(smallint) does not exist

### ISSUE THREAD

**Issue by Praxxian** [sequelize/sequelize#15193]
## Bug Description

When connecting to Redshift using the postgres dialect, anything that uses describeTableQuery, showIndexesQuery, or pgListEnums in postgres/query-generator.js will fail because redshift does not have the array_agg function. From my experience, this occurs during any attempt to sync() or use the CLI to run a migration.

### What do you expect to happen?

Redshift is claimed to be supported through postgres, so sync() and CLI migrations should complete without errors.

### What is actually happening?

`ERROR: function array_agg(smallint) does not exist`

### Environment
- Sequelize version: 6.21.4
- Node.js version: v16.17.0
- If TypeScript related: TypeScript version: 4.8.2
- Database & Version: AWS Redshift
- Connector library & Version: pg@8.8.0

## Would you be willing to resolve this issue by submitting a Pull Request?
- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [x] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by WikiRik** [comment]
Hi! The support on Redshift is fully done with the help of the community since we as maintainers do not have access to an instance to run these tests locally or on our CI.
What I did see is that [`LISTAGG`](https://docs.aws.amazon.com/redshift/latest/dg/r_LISTAGG.html) might be a valid replacement for Redshift but that isn't included in postgres. So on initial thought this would mean that Redshift would become a different implementation with almost exclusively extending `postgres`. A different approach to support both at the same time would be nice, since we're generally against new dialects that do not support local/CI testing.

**Comment by aldex32** [comment]
Hi! Is there any progress about this issue?

**Comment by WikiRik** [comment]
Not as far as we know. As mentioned in my previous comment, the maintainers do not have a way of testing Amazon Redshift so this is something the community has to pick up. We're happy to help and review any PR that will be opened for this issue

**Comment by dyroffk** [comment]
I bumped into this issue attempting to run migrations against Redshift and after swapping `array_agg` for `LISTAGG` as [suggested](https://github.com/sequelize/sequelize/issues/15193#issuecomment-1293800997) it errors with:
```json
{
    "errorType": "error",
    "errorMessage": "could not identify an ordering operator for type int2vector",
    "code": "42883",
    "length": 199,
    "name": "error",
    "severity": "ERROR",
    "hint": "Use an explicit ordering operator or modify the query.",
    "file": "../src/pg/src/backend/parser/parse_oper.c",
    "line": "239",
    "routine": "ordering_oper",
    "sql": "SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, LISTAGG(a.attnum) as column_indexes, LISTAGG(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'SequelizeMeta' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;",
    "stack": [
      "error: could not identify an ordering operator for type int2vector",
      "    at Parser.parseErrorMessage (/var/task/index.js:51745:98)",
      "    at Parser.handlePacket (/var/task/index.js:51586:25)",
      "    at Parser.parse (/var/task/index.js:51510:34)",
      "    at TLSSocket.<anonymous> (/var/task/index.js:51786:44)",
      "    at TLSSocket.emit (node:events:513:28)",
      "    at addChunk (node:internal/streams/readable:324:12)",
      "    at readableAddChunk (node:internal/streams/readable:297:9)",
      "    at Readable.push (node:internal/streams/readable:234:10)",
      "    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)",
      "    at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17)"
    ]
}
```
I'm going to continue working on this, but wanted to provide some visibility that there are other changes required
