### ISSUE TITLE
z/OS support for db2 dialect

### ISSUE THREAD

**Issue by Stoyz** [sequelize/sequelize#15262]
## Issue Creation Checklist

- [X] I understand that my issue will be automatically closed if I don't fill in the requested information
- [X] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### Describe the feature you'd like to see implemented

It would be nice if the db2 dialect supported z/OS.

Currently it seems to work for Linux, Unix and Windows only as the [query to check the db version](https://github.com/sequelize/sequelize/blob/main/src/dialects/db2/query-generator.js#L83) doesn't work for z/OS.
See the following error output when trying to connect to a z/OS hosted db.
```
Could not open connection Error
    at Query._run (/home/theia/sequelize-test/node_modules/sequelize/src/dialects/db2/query.js:35:22)
    at Query.run (/home/theia/sequelize-test/node_modules/sequelize/src/dialects/db2/query.js:171:23)
    at /home/theia/sequelize-test/node_modules/sequelize/src/sequelize.js:649:28
    at async Db2QueryInterface.databaseVersion (/home/theia/sequelize-test/node_modules/sequelize/src/dialects/abstract/query-interface.js:128:12)
    at async Sequelize.databaseVersion (/home/theia/sequelize-test/node_modules/sequelize/src/sequelize.js:977:12)
    at async /home/theia/sequelize-test/node_modules/sequelize/src/dialects/abstract/connection-manager.js:260:31
    at async ConnectionManager.getConnection (/home/theia/sequelize-test/node_modules/sequelize/src/dialects/abstract/connection-manager.js:280:7)
    at async /home/theia/sequelize-test/node_modules/sequelize/src/sequelize.js:637:26
    at async Sequelize.authenticate (/home/theia/sequelize-test/node_modules/sequelize/src/sequelize.js:971:5) {
  name: 'SequelizeDatabaseError',
  parent: [Error: [IBM][CLI Driver][DB2] SQL0440N  No authorized routine named "SYSPROC.ENV_GET_INST_INFO" of type "" having compatible arguments was found.  SQLSTATE=42884
  ] {
    error: '[node-ibm_db] SQL_ERROR',
    sqlcode: -440,
    state: '42884',
    sql: 'select service_level as VERSION from TABLE (sysproc.env_get_inst_info()) as A'
  },
  original: [Error: [IBM][CLI Driver][DB2] SQL0440N  No authorized routine named "SYSPROC.ENV_GET_INST_INFO" of type "" having compatible arguments was found.  SQLSTATE=42884
  ] {
    error: '[node-ibm_db] SQL_ERROR',
    sqlcode: -440,
    state: '42884',
    sql: 'select service_level as VERSION from TABLE (sysproc.env_get_inst_info()) as A'
  },
  sql: 'select service_level as VERSION from TABLE (sysproc.env_get_inst_info()) as A',
  parameters: {}
}
```

For as far as I know, the query to check the version in z/OS is `SELECT GETVARIABLE('SYSIBM.VERSION') FROM SYSIBM.SYSDUMMY1` which, in my case, retrieves DSN12010.

Also, in my opinion, the dialectOptions could be used to set the platform on which the db is hosted, e.g.:
```ts
const sequelize = new Sequelize("DBNAME", "USER", "PWD", {
    dialect: "db2",
    dialectOptions: {
        options: {
            platform: "zos"
        }
    }
});
```

### Describe why you would like this feature to be added to Sequelize

In my opion the db2 dialect would be incomplete if it cannot work with all db2 platforms.

### Is this feature dialect-specific?

- [ ] No. This feature is relevant to Sequelize as a whole.
- [X] Yes. This feature only applies to the following dialect(s): db2

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [X] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in implementing my feature.

---

*Indicate your interest in the addition of this feature by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by ephys** [comment]
Our stance regarding z/OS has not changed. Without a way to include z/OS in our test suites, we cannot officially support it

**Comment by oxydeon** [comment]
We use [patch-package](https://www.npmjs.com/package/patch-package) to be able to use Sequelize with Db2 on z/os.
Just need to change the query in versionQuery():
```
   versionQuery() {
-    return "select service_level as VERSION from TABLE (sysproc.env_get_inst_info()) as A";
+    return "SELECT GETVARIABLE('SYSIBM.VERSION') FROM SYSIBM.SYSDUMMY1";
   }
```

**Comment by ephys** [comment]
Note that we still accept PRs that improve the compatibility with zOS as long as they don't break the support for linux DB2, but that we cannot guarantee the long-term stability and cannot declare to officially support that database without having a way to integration test it
