### ISSUE TITLE
Sequelize does not throws original error after rolling back

### ISSUE THREAD

**Issue by anaconda875** [sequelize/sequelize#15265]
I have a function that create a user:

```
let transaction = await db.sequelize.transaction();
try {
    let user = await db.User.create({username, password}, {transaction}).toObject()

    await transaction.commit();
    return user;
} catch (e) {
    let result = await transaction.rollback();
    throw e;
}
```

It will failed at .toObject() since there is no such method
But I got this log printed

```
Executing (a01c2157-86bd-409c-8b37-b2399d352e3e): START TRANSACTION;
Executing (a01c2157-86bd-409c-8b37-b2399d352e3e): ROLLBACK;
C:\Users\hflbt\Desktop\igloo_backend\node_modules\sequelize\lib\sequelize.js:293
        const error = new Error(`${options.transaction.finished} has been called on this transaction(${options.transaction.id}), you can no longer use it. (The rejected query is at
tached as the 'sql' property of this error)`);
                      ^

Error: rollback has been called on this transaction(a01c2157-86bd-409c-8b37-b2399d352e3e), you can no longer use it. (The rejected query is attached as the 'sql' property of this e
rror)
    at checkTransaction (C:\Users\hflbt\Desktop\igloo_backend\node_modules\sequelize\lib\sequelize.js:293:23)
    at C:\Users\hflbt\Desktop\igloo_backend\node_modules\sequelize\lib\sequelize.js:303:7
    at C:\Users\hflbt\Desktop\igloo_backend\node_modules\retry-as-promised\index.js:64:21
    at new Promise (<anonymous>)
    at retryAsPromised (C:\Users\hflbt\Desktop\igloo_backend\node_modules\retry-as-promised\index.js:54:10)
    at Sequelize.query (C:\Users\hflbt\Desktop\igloo_backend\node_modules\sequelize\lib\sequelize.js:299:12)
    at PostgresQueryInterface.insert (C:\Users\hflbt\Desktop\igloo_backend\node_modules\sequelize\lib\dialects\abstract\query-interface.js:308:42)
    at User.save (C:\Users\hflbt\Desktop\igloo_backend\node_modules\sequelize\lib\model.js:2432:79)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Function.create (C:\Users\hflbt\Desktop\igloo_backend\node_modules\sequelize\lib\model.js:1344:12) {
  sql: 'INSERT INTO "users" ("id","username","password","createdAt","updatedAt") VALUES (DEFAULT,$1,$2,$3,$4) RETURNING "id","username","password","createdAt","updatedAt";'
}
```

What I'm expecting is that the original error get printed on the log, too. Like
```

C:\Users\hflbt\Desktop\igloo_backend\src\service\user.service.js:43
                user.toObject();
                     ^

TypeError: user.toObject is not a function
    at C:\Users\hflbt\Desktop\igloo_backend\src\service\user.service.js:43:22
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\hflbt\Desktop\igloo_backend\node_modules\sequelize\lib\sequelize.js:506:18
    at async Object.module.exports.persistCredentials (C:\Users\hflbt\Desktop\igloo_backend\src\service\user.service.js:40:16)
    at async C:\Users\hflbt\Desktop\igloo_backend\src\index.js:50:14
```

I tried to debug to my code and see that after it catch Error, then it call let result = await transaction.rollback();, but throw e; is never be reached. Am I doing wrong somewhere (I'm noob at js)? Need your help

dependencies:

```
"config": "^3.3.8",
"joi": "^17.6.4",
"pg": "^8.8.0",
"sequelize": "^6.25.3",
"sequelize-cli": "^6.5.2",
"soap": "^0.43.0",
"winston": "^3.8.2"
```

**Comment by ephys** [comment]
If we look at the query execution order, this is what happens:

1. `START TRANSACTION`
2. `ROLLBACK`
3. `INSERT INTO "Users" ("id","name") VALUES (DEFAULT,$1) RETURNING "id","name"`

A few important things to note:

- `ROLLBACK` is executed *before* `INSERT INTO`. This is because this statement:
  ```ts
  await db.User.create({username, password}, {transaction}).toObject()
  ```
  is equivalent to this:
  ```ts
  await (db.User.create({username, password}, {transaction}).toObject())
  ```
  NOT this:
  ```ts
  (await db.User.create({username, password}, {transaction})).toObject()
  ```
  Therefore, JavaScript tries to execute `toObject` *before* it awaits `create`. As a result:
- `create` is called, then the catch block is immediately executed before `create` has time to be awaited. 
- The above cause the promise returned by `create` to become unhandled.
- Because `ROLLBACK` occurs before `create`, `create` will error and its promise will be rejected.
- because the promise returned by `create` is unhandled, node emits an "unhandled rejection"
  ![image](https://user-images.githubusercontent.com/1280915/200905063-49b38d16-8b4a-4c57-b9e4-e12bdbd723f7.png)
- Your "user.toObject is not a function" error *is thrown* but it's hidden by the unhandled rejection.

This isn't something caused by Sequelize, it's what happens when you have [unhandled rejections](https://nodejs.org/api/process.html#event-unhandledrejection).

The solution to avoid an unhandled promise in your code is to write this:

```ts
(await db.User.create({username, password}, {transaction})).toObject()
```

instead of this:

```ts
await db.User.create({username, password}, {transaction}).toObject()
```
