### ISSUE TITLE
[Node 18.12] Association functions are all undefined

### ISSUE THREAD

**Issue by garrettg123** [sequelize/sequelize#15272]
## Issue Creation Checklist

- [X] I understand that my issue will be automatically closed if I don't fill in the requested information
- [X] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

After updating from Node 12 to Node 18, I get the following error (and similar errors from other resolvers). I tried updating to latest Sequelize and am seeing the same error.
```
TypeError: context.user.getAssessment is not a function
    at assessment (/Users/gsquare567/Sites/borderpass/server/resolvers/assessment.ts:31:41)
    at /Users/gsquare567/Sites/borderpass/node_modules/graphql-middleware/src/applicator.ts:34:9
    at middleware (/Users/gsquare567/Sites/borderpass/node_modules/graphql-shield/src/generator.ts:70:22)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  locations: [ { line: 2, column: 3 } ],
  path: [ 'assessment' ]
}
```

### Reproducible Example

Here is the link to the SSCCE for this issue:

### What do you expect to happen?

Associations should be defined as functions.

### What is actually happening?

Associations are no longer defined as functions after upgrade Node 12 > 18. 

### Environment

- Sequelize version:
├─ sequelize-cli@6.2.0
├─ sequelize-pool@7.1.0
└─ sequelize@6.25.5
- Node.js version: v18.12.1
- If TypeScript related: TypeScript version: typescript@4.8.4
- Database & Version: postgres (PostgreSQL) 14.2
- Connector library & Version:
    "pg": "^8.4.2",
    "pg-hstore": "^2.3.3",

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [X] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by ephys** [comment]
Sequelize 6 is tested against Node 18, and association mixins tests are not failing. Without an SSCCE we won't be able to see whether we can replicate the issue.
