### ISSUE TITLE
SSCCE repo fails to make pg database

### ISSUE THREAD

**Issue by garrettg123** [sequelize/sequelize#15273]
gsquare567@GG-MBP ~/S/borderpass-sequelize-sscce-associations-undefined> ./setup/postgres/10/start.sh
++ dirname -- ./setup/postgres/10/start.sh
+ cd -P -- ./setup/postgres/10
+ docker-compose -p sequelize-postgres-10 down --remove-orphans
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 670, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1255, in request
  File "http/client.py", line 1301, in _send_request
  File "http/client.py", line 1250, in endheaders
  File "http/client.py", line 1010, in _send_output
  File "http/client.py", line 950, in send
  File "docker/transport/unixconn.py", line 43, in connect
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 439, in send
  File "urllib3/connectionpool.py", line 726, in urlopen
  File "urllib3/util/retry.py", line 410, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 670, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1255, in request
  File "http/client.py", line 1301, in _send_request
  File "http/client.py", line 1250, in endheaders
  File "http/client.py", line 1010, in _send_output
  File "http/client.py", line 950, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 237, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 199, in perform_command
  File "compose/cli/command.py", line 60, in project_from_options
  File "compose/cli/command.py", line 152, in get_project
  File "compose/cli/docker_client.py", line 41, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 221, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[81289] Failed to execute script docker-compose

**Comment by WikiRik** [comment]
It seems that `docker-compose` is not installed on your PC causing the initial error. That causes the start-up sequence to fail and therefore no database is created.
The SSCCE should work once you've installed `docker-compose` v1.

**Comment by fzn0x** [comment]
> Wrong!
> 
> ```
> gsquare567@GG-MBP ~/S/borderpass-sequelize-sscce-associations-undefined> docker-compose --version
> docker-compose version 1.29.0, build 07737305
> ```

What do you mean by wrong?

**Comment by ephys** [comment]
They do have docker-compose installed (though there are more respectful ways of saying someone is mistaken)

It looks like the issue is some sort of network error, or a file is missing?

> requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

Not quite sure what it could be

**Comment by ephys** [comment]
I have no idea which version of docker/docker compose is required. I'm always on the latest available version and we're not developing a docker addon so we don't have tests against a minimum docker version. I guess we could state "use the latest docker version" but even that isn't factual since I don't go and launch the sscce repo every time we have a docker update :/ makes it difficult to update

I'm not reopening since I can't reproduce the issue. This is very likely a problem with your docker setup. I'm still trying to help you though (though the tone isn't motivating)

**Comment by ephys** [comment]
I just encountered the same error while starting a docker container. The problem was that Docker Desktop wasn't running. It could also be the source of your issue
