### ISSUE TITLE
SequelizeDatabaseError: null value in column "id" of relation "table" violates not-null constraint

### ISSUE THREAD

**Issue by jteesang** [sequelize/sequelize#15351]
## Issue Creation Checklist

[x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Issue Description

A clear and concise description of what is this issue about.

If applicable, you can add some code. In this case, an SSCCE/MCVE/reprex is much better than just an isolated code snippet.

Upgrading from Sequelize v4.44.4 to v6 and getting a SequelizeDatabaseError when inserting a row to a table even though the value (breadcrumb_id) has been generated when inserting into the joint table (breadcrumb_to_term_submission).

`error: null value in column "breadcrumb_id" of relation "breadcrumb_to_term_submission" violates not-null constraint
`

### Additional context
Logs from the service show that breadcrumb_id is populated with value of 23.
```
===> [✓] > BREADCRUMBS_SERVICE > createBreadcrumb ->  successfully created a [create] breadcrumb with id: [23]
Executing (default): INSERT INTO "breadcrumb_to_term_submission" ("breadcrumb_id","submission_id","created_at","updated_at") VALUES ($1,$2,$3,$4) RETURNING "breadcrumb_id","submission_id","created_at","updated_at","created_at","updated_at","breadcrumb_id";

  ===> [x] > BREADCRUMBS_SERVICE > createBreadcrumbToTermSubmission ->  error creating a breadcrumb with id: [23] relationship to term with id: [35] with error: [SequelizeDatabaseError: null value in column "breadcrumb_id" of relation "breadcrumb_to_term_submission" violates not-null constraint]
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
```

Here's the full error log:
```
  original: error: null value in column "breadcrumb_id" of relation "breadcrumb_to_term_submission" violates not-null constraint
      at Parser.parseErrorMessage (/Users/xxx/backend/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/Users/xxx/backend/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/Users/xxx/backend/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/Users/xxx/backend/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 314,
    severity: 'ERROR',
    code: '23502',
    detail: 'Failing row contains (null, 35, 2022-11-28 17:23:55.57+00, 2022-11-28 17:23:55.57+00).',
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: 'public',
    table: 'breadcrumb_to_term_submission',
    column: 'breadcrumb_id',
    dataType: undefined,
    constraint: undefined,
    file: 'execMain.c',
    line: '1953',
    routine: 'ExecConstraints',
    sql: 'INSERT INTO "breadcrumb_to_term_submission" ("breadcrumb_id","submission_id","created_at","updated_at") VALUES ($1,$2,$3,$4) RETURNING "breadcrumb_id","submission_id","created_at","updated_at","created_at","updated_at","breadcrumb_id";',
    parameters: [
      null,
      35,
      '2022-11-28 17:23:55.570 +00:00',
      '2022-11-28 17:23:55.570 +00:00'
    ]
  },
  sql: 'INSERT INTO "breadcrumb_to_term_submission" ("breadcrumb_id","submission_id","created_at","updated_at") VALUES ($1,$2,$3,$4) RETURNING "breadcrumb_id","submission_id","created_at","updated_at","created_at","updated_at","breadcrumb_id";',
  parameters: [
    null,
    35,
    '2022-11-28 17:23:55.570 +00:00',
    '2022-11-28 17:23:55.570 +00:00'
  ]
}
```
### Is this issue dialect-specific?

- [x] No. This issue is relevant to Sequelize as a whole.
- [ ] Yes. This issue only applies to the following dialect(s): XXX, YYY, ZZZ
- [ ] I don't know.

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I don't know how to start, I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ephys** [comment]
Unfortunately without a SSCCE, it's not possible for us to debug this

If you can replicate the issue in http://github.com/sequelize/sequelize-sscce, we should be able to debug and fix this
