### ISSUE TITLE
NodeJS 18 LTS Invalid Date

### ISSUE THREAD

**Issue by wenerme** [sequelize/sequelize#15391]
## Issue Creation Checklist

- [x] I understand that my issue will be automatically closed if I don't fill in the requested information
- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

dataValues contains valid Date, but the final bind became Invalid Date

```
Trace: Executing (default): INSERT INTO "auth"."sessions" ("id","expires_at","session_token","user_id","created_at","updated_at") VALUES (gen_ulid(),$1,$2,$3,$4,$5) RETURNING "id","expires_at","session_token","user_id","user_agent","last_user_agent","created_at","updated_at","user_id"; "Invalid Date", "62d3478d-a2d6-458f-8abb-c77e76b118c0", "01gk8vam8hkp0eq79ztdva7nvf", "Invalid Date", "Invalid Date" {
    plain: false,
    raw: false,
    logging: [Function: trace],
    hooks: true,
    validate: true,
    fields: [
      'id',
      'expires',
      'sessionToken',
      'userId',
      'userAgent',
      'lastUserAgent',
      'createdAt',
      'updatedAt',
      'UserId'
    ],
    defaultFields: [
      'id',
      'expires',
      'sessionToken',
      'userId',
      'userAgent',
      'lastUserAgent',
      'createdAt',
      'updatedAt',
      'UserId'
    ],
    returning: true,
    hasTrigger: undefined,
    dialect: 'postgres',
    dialectModule: PG {
      defaults: {
        host: 'localhost',
        user: undefined,
        database: undefined,
        password: null,
        connectionString: undefined,
        port: 5432,
        rows: 0,
        binary: false,
        max: 10,
        idleTimeoutMillis: 30000,
        client_encoding: '',
        ssl: false,
        application_name: undefined,
        fallback_application_name: undefined,
        options: undefined,
        parseInputDatesAsUTC: false,
        statement_timeout: false,
        lock_timeout: false,
        idle_in_transaction_session_timeout: false,
        query_timeout: false,
        connect_timeout: 0,
        keepalives: 1,
        keepalives_idle: 0,
        parseInt8: [Setter]
      },
      Client: [class Client extends EventEmitter] {
        Query: [class Query extends EventEmitter]
      },
      Query: [class Query extends EventEmitter],
      Pool: [class BoundPool extends Pool],
      _pools: [],
      Connection: [class Connection extends EventEmitter],
      types: {
        getTypeParser: [Function: getTypeParser],
        setTypeParser: [Function: setTypeParser],
        arrayParser: [Object],
        builtins: [Object]
      },
      DatabaseError: [class DatabaseError extends Error]
    },
    dialectModulePath: null,
    dialectOptions: {
      connect_timeout: '10',
      application_name: 'wecom-web',
      search_path: 'auth,public'
    },
    host: '192.168.76.110',
    protocol: 'tcp',
    define: {},
    query: {},
    sync: {},
    timezone: 'Asia/Shanghai',
    keepDefaultTimezone: false,
    standardConformingStrings: true,
    omitNull: false,
    native: false,
    replication: [Object: null prototype] {
      write: {
        database: '',
        username: '',
        password: '',
        host: '',
        port: 5432,
        protocol: 'tcp',
        ssl: undefined,
        dialectOptions: [Object]
      },
      read: []
    },
    ssl: undefined,
    quoteIdentifiers: true,
    retry: { max: 5, match: [ 'SQLITE_BUSY: database is locked' ] },
    transactionType: 'DEFERRED',
    isolationLevel: null,
    databaseVersion: 0,
    typeValidation: false,
    benchmark: false,
    minifyAliases: false,
    logQueryParameters: true,
    database: '',
    username: '',
    password: '',
    pool: { max: 5, min: 0, idle: 10000, acquire: 60000, evict: 1000 },
    port: 5432,
    type: 'INSERT',
    instance: Session {
      dataValues: {
        id: [Fn],
        sessionToken: '62d3478d-a2d6-458f-8abb-c77e76b118c0',
        userId: '01gk8vam8hkp0eq79ztdva7nvf',
        expires: 2023-01-03T15:06:57.809Z,
        updatedAt: 2022-12-04T19:15:25.139Z,
        createdAt: 2022-12-04T19:15:25.139Z
      },
      _previousDataValues: { sessionToken: undefined, userId: undefined, expires: undefined },
      uniqno: 1,
      _changed: Set(3) { 'sessionToken', 'userId', 'expires' },
      _options: {
        isNewRecord: true,
        _schema: 'auth',
        _schemaDelimiter: '',
        attributes: undefined,
        include: undefined,
        raw: undefined,
        silent: undefined,
        model: Session
      },
      isNewRecord: true
    },
    bind: {
      sequelize_1: 'Invalid Date',
      sequelize_2: '62d3478d-a2d6-458f-8abb-c77e76b118c0',
      sequelize_3: '01gk8vam8hkp0eq79ztdva7nvf',
      sequelize_4: 'Invalid Date',
      sequelize_5: 'Invalid Date'
    },
    bindParameterOrder: [
      'sequelize_1',
      'sequelize_2',
      'sequelize_3',
      'sequelize_4',
      'sequelize_5'
    ],
    model: Session
  }
      at Sequelize.log (/app/apps/auth/.next/server/chunks/697.js:70230:15)
      at PostgresQuery._logQuery (/app/apps/auth/.next/server/chunks/697.js:52023:22)
      at PostgresQuery.run (/app/apps/auth/.next/server/chunks/697.js:61342:27)
      at /app/apps/auth/.next/server/chunks/697.js:70001:28
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Sequelize.queryRaw (/app/apps/auth/.next/server/chunks/697.js:69985:12)
      at async PostgresQueryInterface.insert (/app/apps/auth/.next/server/chunks/697.js:51506:21)
      at async Session.save (/app/apps/auth/.next/server/chunks/697.js:69249:35)
      at async Session.create (/app/apps/auth/.next/server/chunks/697.js:68073:12)
      at async handler (/app/apps/auth/.next/server/pages/api/testx.js:187:17)
  Error
      at PostgresQuery.run (/app/apps/auth/.next/server/chunks/697.js:61344:25)
      at /app/apps/auth/.next/server/chunks/697.js:70001:28
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Sequelize.queryRaw (/app/apps/auth/.next/server/chunks/697.js:69985:12)
      at async PostgresQueryInterface.insert (/app/apps/auth/.next/server/chunks/697.js:51506:21)
      at async Session.save (/app/apps/auth/.next/server/chunks/697.js:69249:35)
      at async Session.create (/app/apps/auth/.next/server/chunks/697.js:68073:12)
      at async handler (/app/apps/auth/.next/server/pages/api/testx.js:187:17)
      at async Object.apiResolver (/app/node_modules/.pnpm/next@13.0.6_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/api-utils/node.js:363:9)
      at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@13.0.6_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/next-server.js:474:9) {
    name: 'SequelizeDatabaseError',
    sql: 'INSERT INTO "auth"."sessions" ("id","expires_at","session_token","user_id","created_at","updated_at") VALUES (gen_ulid(),$1,$2,$3,$4,$5) RETURNING "id","expires_at","session_token","user_id","user_agent","last_user_agent","created_at","updated_at","user_id";',
    parameters: [
      'Invalid Date',
      '62d3478d-a2d6-458f-8abb-c77e76b118c0',
      '01gk8vam8hkp0eq79ztdva7nvf',
      'Invalid Date',
      'Invalid Date'
    ],
    [cause]: error: invalid input syntax for type timestamp with time zone: "Invalid Date"
        at Parser.parseErrorMessage (/app/apps/auth/.next/server/chunks/697.js:28262:98)
        at Parser.handlePacket (/app/apps/auth/.next/server/chunks/697.js:28101:29)
        at Parser.parse (/app/apps/auth/.next/server/chunks/697.js:28014:38)
        at Socket.<anonymous> (/app/apps/auth/.next/server/chunks/697.js:27797:42)
        at Socket.emit (node:events:513:28)
        at addChunk (node:internal/streams/readable:324:12)
        at readableAddChunk (node:internal/streams/readable:297:9)
        at Readable.push (node:internal/streams/readable:234:10)
        at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
      length: 173,
      severity: 'ERROR',
      code: '22007',
      detail: undefined,
      hint: undefined,
      position: undefined,
      internalPosition: undefined,
      internalQuery: undefined,
      where: "unnamed portal parameter $1 = '...'",
      schema: undefined,
      table: undefined,
      column: undefined,
      dataType: undefined,
      constraint: undefined,
      file: 'datetime.c',
      line: '4056',
      routine: 'DateTimeParseError',
      sql: 'INSERT INTO "auth"."sessions" ("id","expires_at","session_token","user_id","created_at","updated_at") VALUES (gen_ulid(),$1,$2,$3,$4,$5) RETURNING "id","expires_at","session_token","user_id","user_agent","last_user_agent","created_at","updated_at","user_id";',
      parameters: [
        'Invalid Date',
        '62d3478d-a2d6-458f-8abb-c77e76b118c0',
        '01gk8vam8hkp0eq79ztdva7nvf',
        'Invalid Date',
        'Invalid Date'
      ]
    }
  }
 
```

### Reproducible Example

Here is the link to the SSCCE for this issue:

### What do you expect to happen?

Works as in v16

### Environment

- Sequelize version: alpha.19
- Node.js version: v18.12.1
- If TypeScript related: TypeScript version:
- Database & Version: pg 15
- Connector library & Version:

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [ ] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by ephys** [comment]
I can't replicate this issue with the information you've provided

I've tried the following:

Sequelize 7.0.0-alpha.19
pg 8.8.0
postgres docker image: postgis/postgis:15-3.3 (postgres 15 + postgis)

```ts
const sequelize = createSequelize7Instance({
  logQueryParameters: true,
  timezone: 'Asia/Shanghai',
  keepDefaultTimezone: false,
  define: {
    timestamps: false,
  },
});

class User extends Model {}

User.init(
  {
    birthday: DataTypes.DATE,
  },
  { sequelize }
);

await sequelize.sync({ force: true });

const user = await User.create({
  birthday: new Date('2021-01-01'),
});
```

And it resulted in the following query:

```sql
INSERT INTO "Users" ("id","birthday") VALUES (DEFAULT,$1) RETURNING "id","birthday"; "2021-01-01 08:00:00.000 +08:00"
```

As the issue template indicates, you'll have better luck getting a bug fixed if you replicate it in this repository:https://github.com/sequelize/sequelize-sscce

**Comment by wenerme** [comment]
@ephys Thanks for your time, I'll make a repro.

**Comment by wenerme** [comment]
maybe caused by pnpm introduced multi sequelize
