### ISSUE TITLE
Or.in with an array not working and returns TypeError: values.map is not a function

### ISSUE THREAD

**Issue by HMhamedminaee** [sequelize/sequelize#15530]
Hi when I try 

  ```
  const paramPostgres: QueryBuilder = {
       raw: false,
       nest: true,
       include: [{
           model: UserAccountDeRepository.getInstance().model, as: "userAccountTableAlias",
           required: true,
           attributes: []
       }],
       attributes: [
         "is_archived",
         "details",
         "status",
         "creation_time",
         "metadata",
         "id",
         "last_accessed_on",
         "datasources",
         [Sequelize.col('userAccountTableAlias.account'), 'account'],
         [Sequelize.col('userAccountTableAlias.user'), 'user']
         ],
       where: {
        datasources: { [Op.in]: ["4205d27c-c1a7-4655-b1cd-13c3fc463f8e", "094116d9-93d7-4a15-9ef7-599424c35fb1","9398996a-c04f-475b-b089-ff48c8c1656b"] 

      }

       },
        order:[
        "last_accessed_on"
        ],
        limit : 20,
        offset: 0
      }

       return this.findAll(paramPostgres)
           .then((result: any) => {
               return Promise.resolve(result);
           }).catch((err) => {
            return Promise.reject(err) 
           });
```
to get the list of rows where datasources is in any combination of this array  ["4205d27c-c1a7-4655-b1cd-13c3fc463f8e", "094116d9-93d7-4a15-9ef7-599424c35fb1","9398996a-c04f-475b-b089-ff48c8c1656b"] 
I get 

```
TypeError: values.map is not a function
    at ARRAY._value (/opt/app-root/node_modules/sequelize/lib/dialects/postgres/data-types.js:379:19)
    at ARRAY._stringify (/opt/app-root/node_modules/sequelize/lib/dialects/postgres/data-types.js:393:29)
    at ARRAY.stringify (/opt/app-root/node_modules/sequelize/lib/data-types.js:22:19)
    at PostgresQueryGenerator.escape (/opt/app-root/node_modules/sequelize/lib/dialects/abstract/query-generator.js:722:30)
    at /opt/app-root/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1943:71
    at Array.map (<anonymous>)
    at PostgresQueryGenerator._whereParseSingleValueObject (/opt/app-root/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1943:52)
    at PostgresQueryGenerator.whereItemQuery (/opt/app-root/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1763:21)
    at /opt/app-root/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1684:25
    at Array.forEach (<anonymous>)
```
Am I missing anything or is this a bug?

**Comment by ephys** [comment]
Hello,

Please follow the [issue template](https://github.com/sequelize/sequelize/blob/main/.github/ISSUE_TEMPLATE/bug_report.md) when submitting a bug report, including and most importantly the SSCCE, as it's unlikely we'll be able to help you without a reproducible example.
