### ISSUE TITLE
attr[0].includes is not a function

### ISSUE THREAD

**Issue by ryanwaite28** [sequelize/sequelize#15531]
## Issue Creation Checklist

- [x] I understand that my issue will be automatically closed if I don't fill in the requested information
- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

When using `fn`, `cast`, `col` on `attributes` for select queries, i get errors. Current version of sequelize installed: `"sequelize": "^6.28.0"`

### Reproducible Example

1. for a select query, add sequelize functions for the attributes like AVG or COUNT

Here is my code:

```typescript
import * as Sequelize from 'Sequelize';

let sequelize = new Sequelize.Sequelize(<string> process.env.DATABASE_URL, {
      dialect: 'postgres',
      dialectOptions: {
        ssl: false,
        rejectUnauthorized: false
      },
      logging: false
    });

export const common_model_options: Sequelize.InitOptions = {
  sequelize: sequelizeInst,

  paranoid: true,
  timestamps: true,
  freezeTableName: true,
  underscored: true,
  createdAt: 'created_at',
  updatedAt: 'updated_at',
  deletedAt: 'deleted_at',
};

export const common_model_fields = {
  id:           { type: Sequelize.INTEGER, primaryKey: true, autoIncrement: true },
  uuid:         { type: Sequelize.STRING, defaultValue: uuidv1 }
};

export const Notice = <MyModelStatic> sequelize.define('Notice', {
  ...common_model_fields,

  owner_id:            { type: Sequelize.INTEGER, allowNull: false, references: { model: User, key: 'id' } },

  parent_notice_id:    { type: Sequelize.INTEGER, allowNull: true, references: { model: 'Notice', key: 'id' } }, // if this notice is a reply to another
  quoting_notice_id:   { type: Sequelize.INTEGER, allowNull: true, references: { model: 'Notice', key: 'id' } }, // if this notice is quoting another
  share_notice_id:     { type: Sequelize.INTEGER, allowNull: true, references: { model: 'Notice', key: 'id' } }, // if this notice is a share of another

  body:                { type: Sequelize.STRING(500), allowNull: true },
  tags:                { type: Sequelize.STRING, allowNull: false, defaultValue: '' },

  is_explicit:         { type: Sequelize.BOOLEAN, allowNull: false, defaultValue: false },
  is_private:          { type: Sequelize.BOOLEAN, allowNull: false, defaultValue: false },
  visibility:          { type: Sequelize.STRING(75), allowNull: false, defaultValue: '' },
}, { ...common_model_options, tableName: `Notice`, modelName: `Notice` });

Notice.hasMany(Notice, { as: 'notice_replies', foreignKey: 'parent_notice_id', sourceKey: 'id' });
Notice.belongsTo(Notice, { as: 'parent_notice', foreignKey: 'parent_notice_id', targetKey: 'id' });
Notice.hasMany(Notice, { as: 'notice_quotes', foreignKey: 'quoting_notice_id', sourceKey: 'id' });
Notice.belongsTo(Notice, { as: 'quote_notice', foreignKey: 'quoting_notice_id', targetKey: 'id' });
Notice.hasMany(Notice, { as: 'notice_shares', foreignKey: 'share_notice_id', sourceKey: 'id' });
Notice.belongsTo(Notice, { as: 'share_notice', foreignKey: 'share_notice_id', targetKey: 'id' });

// now the failing part:

const noticeStats = await Notice.findOne({
    where: { id: 1 },
    attributes: {
      include: [
        [fn('COUNT', col('Notice.parent_notice_id')), 'replies_count'] // this causes the bug
      ]
    },
    group: ['Notice.parent_notice_id'],
  });

```

### What do you expect to happen?

The returned model/data has the additional attributes specified in the query

### What is actually happening?

a bug:

```
/Users/ryanwaite/Developer/avenger-server-express/node_modules/Sequelize/lib/dialects/abstract/query-generator.js:1048
        } else if (!attr[0].includes("(") && !attr[0].includes(")")) {
                            ^

TypeError: attr[0].includes is not a function
    at /Users/ryanwaite/Developer/avenger-server-express/node_modules/Sequelize/lib/dialects/abstract/query-generator.js:1048:29
    at Array.map (<anonymous>)
    at PostgresQueryGenerator.escapeAttributes (/Users/ryanwaite/Developer/avenger-server-express/node_modules/Sequelize/lib/dialects/abstract/query-generator.js:1035:37)
    at PostgresQueryGenerator.selectQuery (/Users/ryanwaite/Developer/avenger-server-express/node_modules/Sequelize/lib/dialects/abstract/query-generator.js:843:28)
    at PostgresQueryInterface.select (/Users/ryanwaite/Developer/avenger-server-express/node_modules/Sequelize/lib/dialects/abstract/query-interface.js:407:59)
    at Function.findAll (/Users/ryanwaite/Developer/avenger-server-express/node_modules/Sequelize/lib/model.js:1134:47)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Function.findOne (/Users/ryanwaite/Developer/avenger-server-express/node_modules/Sequelize/lib/model.js:1228:12)
    at async test (/Users/ryanwaite/Developer/avenger-server-express/dist/scripts/test-notice-manager.script.js:86:25)

```

### Environment

Local

```
"dependencies": {
    "@aws-sdk/client-s3": "^3.32.0",
    "@aws-sdk/client-ses": "^3.224.0",
    "@aws-sdk/node-http-handler": "^3.32.0",
    "@googlemaps/google-maps-services-js": "^3.1.16",
    "@overnightjs/core": "^1.6.9",
    "@overnightjs/jwt": "^1.1.14",
    "@overnightjs/logger": "^1.1.9",
    "@sendgrid/mail": "^6.5.4",
    "@types/bcrypt-nodejs": "0.0.31",
    "@types/bluebird": "^3.5.28",
    "@types/client-sessions": "^0.8.0",
    "@types/cookie-parser": "^1.4.2",
    "@types/cors": "^2.8.6",
    "@types/express": "^4.17.14",
    "@types/express-fileupload": "^1.1.0",
    "@types/jsonwebtoken": "^8.5.0",
    "@types/node": "^18.11.11",
    "@types/node-mailjet": "^3.3.3",
    "@types/nunjucks": "^3.1.3",
    "@types/socket.io": "^2.1.3",
    "@types/uuid": "^8.3.1",
    "@types/validator": "^10.11.3",
    "autoprefixer": "^9.6.1",
    "aws-sdk": "^2.1013.0",
    "axios": "^0.21.4",
    "bcrypt": "^3.0.6",
    "bcrypt-nodejs": "0.0.3",
    "body-parser": "^1.19.0",
    "class-transformer": "^0.5.1",
    "class-transformer-validator": "^0.9.1",
    "class-validator": "^0.14.0",
    "clean-webpack-plugin": "^3.0.0",
    "client-sessions": "^0.8.0",
    "cloudinary": "^1.20.0",
    "cookie-parser": "^1.4.5",
    "cors": "^2.8.5",
    "css-loader": "^3.2.0",
    "dotenv": "^16.0.3",
    "expo-server-sdk": "^3.6.0",
    "express": "^4.18.2",
    "express-device": "^0.4.2",
    "express-fileupload": "^1.1.6-alpha.5",
    "express-validator": "^6.14.2",
    "fs": "0.0.1-security",
    "html-loader": "^0.5.5",
    "html-webpack-plugin": "^3.2.0",
    "http-status-codes": "^1.3.2",
    "jsonwebtoken": "^8.5.1",
    "moment": "^2.29.4",
    "moment-precise-range-plugin": "^1.3.0",
    "moment-range": "^4.0.2",
    "moment-strftime": "^0.5.0",
    "multer": "^1.4.5-lts.1",
    "net": "^1.0.2",
    "nexmo": "^2.7.0",
    "ngrok": "^4.3.3",
    "node-mailjet": "^3.3.1",
    "nodemon": "^2.0.20",
    "nunjucks": "^3.2.0",
    "peer": "^0.6.1",
    "pg": "^8.8.0",
    "pg-hstore": "^2.3.4",
    "postcss-loader": "^3.0.0",
    "reflect-metadata": "^0.1.13",
    "sequelize": "^6.28.0",
    "socket.io": "^4.5.1",
    "stripe": "^11.2.0",
    "ts-loader": "^6.2.0",
    "tslib": "^2.0.1",
    "tslint": "^5.20.0",
    "typeorm": "^0.2.24",
    "typescript": "^4.9.3",
    "unirest": "^0.6.0",
    "uuid": "^8.3.2",
    "uws": "^100.0.1",
    "validator": "^13.7.0"
  },
  "devDependencies": {
    "parcel-bundler": "^1.12.4",
    "ts-node": "^10.9.1",
    "webpack": "^4.41.2",
    "webpack-cli": "^3.3.9"
  }
```

node: 16.17.0
npm: 8.15.0

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [ ] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by ryanwaite28** [comment]
sorry, there appears to be a bug on my end.

**Comment by WikiRik** [comment]
No worries, thanks for the feedback

**Comment by 7-happy** [comment]
"sequelize": "4.44.3"  got the same error
