### ISSUE TITLE
[MySQLv5.7] Updating existing records with no changes breaks when DATEONLY field is '0000-00-00'

### ISSUE THREAD

**Issue by LucidThought** [sequelize/sequelize#15541]
## Bug Description

The project described in this report is using MySQL 5.7, 

I have a DATEONLY field in my model:
```sql
  const Contact = sequelize.define(
    'Contact',
    {
      id: {
        type: DataTypes.STRING,
        primaryKey: true,
      },
      dateOfBirth: {
        type: DataTypes.DATEONLY,
        allowNull: true,
      },
    },
  );
```

The project was recently upgraded from Sequelize v3 to Sequelize v6.27.0, and now update operations fail on records containing zero values for this date field. The update happens in a findOne.then block:
```javascript
        const updateContact = await Contact.findOne({
          where: {
            id: inputContact.id,
          },
        }).then((contact) => {
          contact.dateOfBirth = inputContact.dateOfBirth || null;

          return contact.save();
        });
```
The problem I'm having is with records that have '0000-00-00' as their `dateOfBirth` and that field along with the rest of `inputContact` matches the existing record exactly (so the update should be empty, as no columns are actually being changed). An UPDATE is attempted, and fails because of some date parsing issue (see the expected/actual results sections below)

### Reproducible Example

Example code given in this bug report report description

### What do you expect to happen?

I expect, in terms of SQL, for nothing to happen. The DB row is unchanged, as the supplied values match the stored record in the database.

### What is actually happening?

I can tell from logs that an UPDATE is being attempted, and is failing because of an invalid value in the `dateOfBirth` field. The value being supplied to the update function is the string '0000-00-00', but somehow this is being translated into the string 'Invalid date'. The error message and stack trace that is shown on the terminal: 
```
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: Invalid date, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (/home/alata/code/mad/node_modules/moment/moment.js:324:25)
    at configFromString (/home/alata/code/mad/node_modules/moment/moment.js:2550:19)
    at configFromInput (/home/alata/code/mad/node_modules/moment/moment.js:2993:13)
    at prepareConfig (/home/alata/code/mad/node_modules/moment/moment.js:2976:13)
    at createFromConfig (/home/alata/code/mad/node_modules/moment/moment.js:2943:44)
    at createLocalOrUTC (/home/alata/code/mad/node_modules/moment/moment.js:3037:16)
    at createLocal (/home/alata/code/mad/node_modules/moment/moment.js:3041:16)
    at hooks (/home/alata/code/mad/node_modules/moment/moment.js:16:29)
    at DATEONLY._stringify (/home/alata/code/mad/node_modules/sequelize/lib/data-types.js:352:12)
    at DATEONLY.stringify (/home/alata/code/mad/node_modules/sequelize/lib/data-types.js:22:19)
    at DATEONLY.bindParam (/home/alata/code/mad/node_modules/sequelize/lib/data-types.js:30:35)
    at MySQLQueryGenerator.format (/home/alata/code/mad/node_modules/sequelize/lib/dialects/abstract/query-generator.js:746:29)
    at MySQLQueryGenerator.updateQuery (/home/alata/code/mad/node_modules/sequelize/lib/dialects/abstract/query-generator.js:330:58)
    at MySQLQueryInterface.update (/home/alata/code/mad/node_modules/sequelize/lib/dialects/abstract/query-interface.js:352:37)
    at model.save (/home/alata/code/mad/node_modules/sequelize/lib/model.js:2432:79)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Executing (default): UPDATE `contact` SET `dateOfBirth`=?,`updatedAt`=? WHERE `id` = ?
(node:118415) UnhandledPromiseRejectionWarning: Error
    at Query.run (/home/alata/code/mad/node_modules/sequelize/lib/dialects/mysql/query.js:52:25)
    at /home/alata/code/mad/node_modules/sequelize/lib/sequelize.js:314:28
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at MySQLQueryInterface.update (/home/alata/code/mad/node_modules/sequelize/lib/dialects/abstract/query-interface.js:355:12)
    at model.save (/home/alata/code/mad/node_modules/sequelize/lib/model.js:2432:35)
(node:118415) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:118415) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The contents of the `contact` object that is build after the findOne and content change, immediately before the `contact.save()`  shown in the example are logged to the console before this failure (note that the object passed to update this record contains the values shown in `_previousDataValues` exactly, so the supplied dateOfBirth is '0000-00-00'):
```
Contact {
  dataValues: {
    id: '7f35d63a24a7a6b9953610fb83f871a8',
    dateOfBirth: 'Invalid date'
  },
  _previousDataValues: {
    id: '7f35d63a24a7a6b9953610fb83f871a8',
    dateOfBirth: '0000-00-00'
  },
  uniqno: 1,
  _changed: Set { 'dateOfBirth' },
  _options: {
    isNewRecord: false,
    _schema: null,
    _schemaDelimiter: '',
    raw: true,
    attributes: [
      'id',
      'dateOfBirth'
    ]
  },
  isNewRecord: false
}

```

### Environment

- Sequelize version: 6.27.0
- Node.js version: 12.22.12
- If TypeScript related: TypeScript version: n/a
- Database & Version: MYSQL 5.7
- Connector library & Version: mysql2@2.3.3

## Would you be willing to resolve this issue by submitting a Pull Request?

- No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by ephys** [comment]
How did you get `0000-00-00` in a date column in mysql? Their minimum value is `1000-01-01`. Am I missing something?

**Comment by LucidThought** [comment]
> How did you get `0000-00-00` in a date column in mysql? Their minimum value is `1000-01-01`. Am I missing something?

As per MySQL 5.7 [documentation](https://dev.mysql.com/doc/refman/5.7/en/datetime.html):

> 
> MySQL permits a “relaxed” format for values specified as strings, in which any punctuation character may be used as the delimiter between date parts or time parts. In some cases, this syntax can be deceiving. For example, a value such as '10:11:12' might look like a time value because of the :, but is interpreted as the year '2010-11-12' if used in date context. The value '10:45:15' is converted to '0000-00-00' because '45' is not a valid month.
> 
> The only delimiter recognized between a date and time part and a fractional seconds part is the decimal point.
> 
> The server requires that month and day values be valid, and not merely in the range 1 to 12 and 1 to 31, respectively. With strict mode disabled, invalid dates such as '2004-04-31' are converted to '0000-00-00' and a warning is generated. With strict mode enabled, invalid dates generate an error. To permit such dates, enable [ALLOW_INVALID_DATES](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_allow_invalid_dates). See Section 5.1.10, “Server SQL Modes”, for more information.
> 
> MySQL does not accept TIMESTAMP values that include a zero in the day or month column or values that are not a valid date. The sole exception to this rule is the special “zero” value '0000-00-00 00:00:00', if the SQL mode permits this value. The precise behavior depends on which if any of strict SQL mode and the [NO_ZERO_DATE](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_no_zero_date) SQL mode are enabled; see Section 5.1.10, “Server SQL Modes”.
> 

No normally, no, zero dates are not permitted. But in expanded use of the database situations like this occur which result in zero dates being saved, which crashes the application.

**Comment by ephys** [comment]
OK should be easy enough to fix. If the input is a string and follows the format `YYYY-MM-DD`, we can use the value as-is: https://github.com/sequelize/sequelize/blob/main/src/dialects/abstract/data-types.ts#L1365-L1376
