### ISSUE TITLE
Renaming attributes with eager loading returns error

### ISSUE THREAD

**Issue by OscarHYCheung** [sequelize/sequelize#1556]
``` JS
Users
    .findAll({
        include: [{
            model: Profiles,
            attributes: [
                'id',
                'avatar',
                ['first_name', 'firstName']
            ]
        }]
    })
    .success(function (users) {
        result.data = users;
        result.total = users.length;
        res.json(result);
    });
```

This gives error:

```
Executing (default): SELECT * FROM `users` WHERE `users`.`id`=1 AND `users`.`deleted_at` IS NULL LIMIT 1;
TypeError: Object first_name,firstName has no method 'replace'
    at Object.module.exports.removeTicks (/Users/project/node_modules/sequelize/lib/utils.js:528:14)
    at Object.module.exports.addTicks (/Users/project/node_modules/sequelize/lib/utils.js:524:29)
    at Object.module.exports.QueryGenerator.quoteIdentifier (/Users/project/node_modules/sequelize/lib/dialects/mysql/query-generator.js:412:20)
    at /Users/project/node_modules/sequelize/lib/dialects/abstract/query-generator.js:614:60
    at Array.map (native)
    at generateJoinQueries (/Users/project/node_modules/sequelize/lib/dialects/abstract/query-generator.js:613:46)
    at Object.<anonymous> (/Users/project/node_modules/sequelize/lib/dialects/abstract/query-generator.js:743:29)
    at Array.forEach (native)
    at Object.module.exports.QueryGenerator.selectQuery (/Users/project/node_modules/sequelize/lib/dialects/abstract/query-generator.js:742:25)
    at module.exports.QueryInterface.select (/Users/project/node_modules/sequelize/lib/query-interface.js:714:35)
```

**Comment by milovanderlinden** [comment]
It works in almost any case, except when using limit and offset. I found this out today when trying to implement paging. Will dig in the issue deeper to see if I can find out where the alias is used to join instead of the real field name.

**Comment by milovanderlinden** [comment]
It happens with a findAll that has included models
```javascript
  var options = {
    attributes: [
      ['id', 'service_request_id'],
      ['category_id', 'service_code'],
      'status',
      ['location', 'address'],
      ['latitude', 'lat'],
      ['longitude', 'long'],
      ['enteredDate', 'requested_datetime'],
      ['lastModified', 'updated_datetime']
    ],
    include: [{
      model: models.service,
      attributes: ['service_name']
    }, {
      model: models.issue,
      attributes: ['description'],
      include: [{
        model: models.media
      }]
    }, {
      model: models.person,
      attributes: ['firstname', 'middlename', 'lastname'],
      include: [{
        model: models.department,
        attributes: ['name']
      }]
    }],
    order: [
      ['enteredDate', 'DESC']
    ],
    offset: 0,
    limit: 10

  };


models.request.findAll(options).then(function(results) {});
```

**Comment by felixfbecker** [comment]
@milovanderlinden please open a new issue.
