### ISSUE TITLE
Incorrect handling of postgres table aliases in where clauses when using non-default schema in >= 7.0.0-alpha.20

### ISSUE THREAD

**Issue by chriswheeldon-peakon** [sequelize/sequelize#15749]
## Issue Creation Checklist

- [x] I understand that my issue will be automatically closed if I don't fill in the requested information
- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

I am using sequelize and postgres and setting a non-default schema (i.e. not `public`) when initialising sequelize. When I make a find query with a where condition I am seeing that sequelize is aliasing the table (e.g. `FROM "schema"."table" as "Alias"`) and is using that alias in the where clause. However, it is producing an invalid statement by prefixing the alias with the schema (e.g. `WHERE "schema"."Alias" ...`).

I can not reproduce this in 7.0.0-alpha.19. I had a brief look through the changelog and suspect that https://github.com/sequelize/sequelize/pull/15274 could be a candidate for introducing this regression but have not confirmed.

### Reproducible Example

I have attempted to create a minimal, reproducible example at https://github.com/chriswheeldon-peakon/sequelize-v7-alias-bug

### What do you expect to happen?

Where the table alias is used in the where clause it should not be prefixed with the schema.

### What is actually happening?

When using a non-default schema (i.e. not public) then sequelize is prefixing the alias with the schema when referring to it in th where clause.

### Environment

- Sequelize version: >= 7.0.0-alpha.20
- Node.js version: v18.14.1
- Database & Version: PostgreSQL 14.3
- Connector library & Version: pg@8.8.0

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [ ] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by frostzt** [comment]
In your code provided if I remove the `schema` from `Sequelize` init options:

```js
const sequelize = new Sequelize({
  dialect: "postgres",
  host: process.env.PGHOST,
  port: process.env.PGPORT,
  username: process.env.PGUSER,
  password: process.env.PGPASSWORD,
  database: process.env.PGDATABASE,
  // NO SCHEMA HERE
});
```

Now where you initialize the `Entity` table I passed the schema like this:

```js

class Entity extends Sequelize.Model {}
Entity.init(
  {
    id: { type: DataTypes.INTEGER, primaryKey: true },
    prop: { type: DataTypes.STRING, allowNull: false },
  },
  { sequelize, tableName: "entity", schema: "dev" }
);
```

Now it generates this!

```sql
SELECT "id", "prop", "createdAt", "updatedAt" FROM "dev"."entity" AS "Entity" WHERE "Entity"."prop" = 'hello, world' LIMIT 1;
```

**Comment by ephys** [comment]
I wonder if this is fixed in https://github.com/sequelize/sequelize/pull/15598, considering it completely rewrites how WHERE generates

**Comment by chriswheeldon-peakon** [comment]
@ephys I have run my mvcc example against your branch locally and I no longer see the issue 🥳 

Do you think it is worth attempting to fix this in current master or better to just wait for your PR to land?

**Comment by ephys** [comment]
The PR is ready and is waiting for a review. Considering how horribly complex the old WHERE code was, I would prefer waiting for that PR to land 😅

That being said if you or anyone already knows how to fix it, I have no problem merging an intermediary PR to fix it :)

**Comment by ephys** [comment]
https://github.com/sequelize/sequelize/pull/15598 has been merged :)

**Comment by chriswheeldon-peakon** [comment]
Thank you @ephys! I tested again and my now code now doesn't get as far as generating a query at all. Instead the following code from https://github.com/chriswheeldon-peakon/sequelize-v7-alias-bug gives an error when sequelize parses the where:

```JS
class Entity extends Sequelize.Model {}
Entity.init(
  {
    id: { type: DataTypes.INTEGER, primaryKey: true },
    prop: { type: DataTypes.STRING, allowNull: false },
  },
  { sequelize, tableName: "entity" }
);
await sequelize.sync();

await Entity.findOne({ where: { prop: "hello, world" } });
```

```
BaseError [SequelizeBaseError]: Invalid value received for the "where" option. Refer to the sequelize documentation to learn which values the "where" option accepts.
Value: { prop: 'hello, world' }
```

Is that error expected now? I think it should work from the latest docs. Forcing prop to be cast to `::text` does work.

**Comment by ephys** [comment]
The error you posted is missing details on what exactly failed, can you check what the "cause" property of the error says?

Some testing frameworks unfortunately don't print the error cause yet

**Comment by jfow** [comment]
I'm also looking at this issue in the repro rep, cause printed below:

```
/Users/jeffrey.fowler/development/sequelize-v7-alias-bug/node_modules/@sequelize/core/lib/dialects/abstract/where-sql-builder.js:158
      throw new import_base_error.BaseError(`Invalid value received for the "where" option. Refer to the sequelize documentation to learn which values the "where" option accepts.
            ^

BaseError [SequelizeBaseError]: Invalid value received for the "where" option. Refer to the sequelize documentation to learn which values the "where" option accepts.
Value: { prop: 'hello, world' }
    at WhereSqlBuilder.formatWhereOptions (/Users/jeffrey.fowler/development/sequelize-v7-alias-bug/node_modules/@sequelize/core/lib/dialects/abstract/where-sql-builder.js:158:13)
    at PostgresQueryGenerator.whereItemsQuery (/Users/jeffrey.fowler/development/sequelize-v7-alias-bug/node_modules/@sequelize/core/lib/dialects/abstract/query-generator-typescript.js:160:33)
    at PostgresQueryGenerator.selectQuery (/Users/jeffrey.fowler/development/sequelize-v7-alias-bug/node_modules/@sequelize/core/lib/dialects/abstract/query-generator.js:1059:28)
    at PostgresQueryInterface.select (/Users/jeffrey.fowler/development/sequelize-v7-alias-bug/node_modules/@sequelize/core/lib/dialects/abstract/query-interface.js:923:37)
    at Entity.findAll (/Users/jeffrey.fowler/development/sequelize-v7-alias-bug/node_modules/@sequelize/core/lib/model.js:959:47)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Entity.findOne (/Users/jeffrey.fowler/development/sequelize-v7-alias-bug/node_modules/@sequelize/core/lib/model.js:1091:12)
    at async file:///Users/jeffrey.fowler/development/sequelize-v7-alias-bug/index.js:30:1 {
  [cause]: TypeError: Cannot read properties of undefined (reading 'getReach')
      at SyntaxNode.getReach (/Users/jeffrey.fowler/development/sequelize-v7-alias-bug/node_modules/bnf-parser/bin/syntax.js:70:50)
      at Sequence.parseSingle (/Users/jeffrey.fowler/development/sequelize-v7-alias-bug/node_modules/bnf-parser/bin/parser.js:347:32)
      at Sequence.parse (/Users/jeffrey.fowler/development/sequelize-v7-alias-bug/node_modules/bnf-parser/bin/parser.js:271:28)
      at Sequence.parse (/Users/jeffrey.fowler/development/sequelize-v7-alias-bug/node_modules/bnf-parser/bin/parser.js:323:25)
      at Rule.parse (/Users/jeffrey.fowler/development/sequelize-v7-alias-bug/node_modules/bnf-parser/bin/parser.js:389:28)
      at Parser.parse (/Users/jeffrey.fowler/development/sequelize-v7-alias-bug/node_modules/bnf-parser/bin/parser.js:425:29)
      at parseAttributeSyntaxInternal (/Users/jeffrey.fowler/development/sequelize-v7-alias-bug/node_modules/@sequelize/core/lib/utils/attribute-syntax.js:97:34)
      at memoized (/Users/jeffrey.fowler/development/sequelize-v7-alias-bug/node_modules/lodash/memoize.js:62:23)
      at /Users/jeffrey.fowler/development/sequelize-v7-alias-bug/node_modules/@sequelize/core/lib/dialects/abstract/where-sql-builder.js:215:88
      at Array.map (<anonymous>)
}
```

**Comment by ephys** [comment]
Ok that is 100% a bug

**Comment by WikiRik** [comment]
Might be due to the new `bnf-parser` version; https://github.com/sequelize/sequelize/pull/15792

**Comment by ephys** [comment]
I was just about to say this :) Updated bnf-parser in our repo and our tests fail.
We'll pin the dependency for now & look into this
