### ISSUE TITLE
Unable to deal with special methods/mixins when the primary key implements getters and setters

### ISSUE THREAD

**Issue by YannickDa** [sequelize/sequelize#15861]
## Issue Creation Checklist

- [x] I understand that my issue will be automatically closed if I don't fill in the requested information
- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

It's impossible to use special methods/mixins on an association when a model's primary key implements getters and setters.

### Reproducible Example

Sorry, I can't fork the sequelize-sscce repository on my Github account (I got an error 500).

But this is the source code to reproduce the bug:

```javascript
import { Sequelize, Model, DataTypes } from "sequelize"

const sequelize = new Sequelize("sqlite::memory:")

class User extends Model {}
User.init({
  id: {
    type: DataTypes.STRING(10).BINARY,
    primaryKey: true,
    get() {
      return this.getDataValue("id")?.replace(/(.{3})(.{4})(.{3})/, "$1-$2-$3")
    },
    set(value) {
      this.setDataValue("id", value?.replace(/-/g, "")?.toLowerCase())
    },
  },
  username: DataTypes.STRING,
  birthday: DataTypes.DATE,
}, { sequelize, modelName: "user" })

class Email extends Model {}
Email.init({
  email: DataTypes.STRING,
}, { sequelize, modelName: "email" })

User.hasMany(Email)
Email.belongsTo(User)

await sequelize.sync()

const jane = await User.create({
  id: "aieopzicdn",
  username: 'janedoe',
  birthday: new Date(1980, 6, 20),
})

console.log(jane.toJSON())

const email = await Email.create({
  email: "janedoe@test.com",
})

console.log(email.toJSON())

await jane.addEmail(email)

console.log(await jane.countEmails())
```

### What do you expect to happen?

Email is associated with my user:

```bash
Executing (default): SELECT name FROM sqlite_master WHERE type='table' AND name='users';
Executing (default): CREATE TABLE IF NOT EXISTS `users` (`id` VARCHAR BINARY(10) PRIMARY KEY, `username` VARCHAR(255), `birthday` DATETIME, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
Executing (default): PRAGMA INDEX_LIST(`users`)
Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_users_1`)
Executing (default): SELECT name FROM sqlite_master WHERE type='table' AND name='emails';
Executing (default): CREATE TABLE IF NOT EXISTS `emails` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `email` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `userId` VARCHAR BINARY(10) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE);
Executing (default): PRAGMA INDEX_LIST(`emails`)
Executing (default): INSERT INTO `users` (`id`,`username`,`birthday`,`createdAt`,`updatedAt`) VALUES ($1,$2,$3,$4,$5);
{
  id: 'aieopzicdn',
  username: 'janedoe',
  birthday: 1980-07-19T22:00:00.000Z,
  updatedAt: 2023-03-27T12:54:07.661Z,
  createdAt: 2023-03-27T12:54:07.661Z
}
Executing (default): INSERT INTO `emails` (`id`,`email`,`createdAt`,`updatedAt`) VALUES (NULL,$1,$2,$3);
{
  id: 1,
  email: 'janedoe@test.com',
  updatedAt: 2023-03-27T12:54:07.666Z,
  createdAt: 2023-03-27T12:54:07.666Z
}
Executing (default): UPDATE `emails` SET `userId`=$1,`updatedAt`=$2 WHERE `id` IN (1)
Executing (default): SELECT COUNT(`email`.`id`) AS `count` FROM `emails` AS `email` WHERE `email`.`userId` = 'aieopzicdn';
1
```

### What is actually happening?

Got a SequelizeForeignKeyConstraintError error:

```bash
Executing (default): SELECT name FROM sqlite_master WHERE type='table' AND name='users';
Executing (default): CREATE TABLE IF NOT EXISTS `users` (`id` VARCHAR BINARY(10) PRIMARY KEY, `username` VARCHAR(255), `birthday` DATETIME, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
Executing (default): PRAGMA INDEX_LIST(`users`)
Executing (default): PRAGMA INDEX_INFO(`sqlite_autoindex_users_1`)
Executing (default): SELECT name FROM sqlite_master WHERE type='table' AND name='emails';
Executing (default): CREATE TABLE IF NOT EXISTS `emails` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `email` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `userId` VARCHAR BINARY(10) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE);
Executing (default): PRAGMA INDEX_LIST(`emails`)
Executing (default): INSERT INTO `users` (`id`,`username`,`birthday`,`createdAt`,`updatedAt`) VALUES ($1,$2,$3,$4,$5);
{
  id: 'aie-opzi-cdn',
  username: 'janedoe',
  birthday: 1980-07-19T22:00:00.000Z,
  updatedAt: 2023-03-27T12:55:02.669Z,
  createdAt: 2023-03-27T12:55:02.669Z
}
Executing (default): INSERT INTO `emails` (`id`,`email`,`createdAt`,`updatedAt`) VALUES (NULL,$1,$2,$3);
{
  id: 1,
  email: 'janedoe@test.com',
  updatedAt: 2023-03-27T12:55:02.674Z,
  createdAt: 2023-03-27T12:55:02.674Z
}
Executing (default): UPDATE `emails` SET `userId`=$1,`updatedAt`=$2 WHERE `id` IN (1)
node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^

Error
    at Database.<anonymous> (/Users/yannick/workspace/listenleon/testsequelize/node_modules/sequelize/lib/dialects/sqlite/query.js:185:27)
    at /Users/yannick/workspace/listenleon/testsequelize/node_modules/sequelize/lib/dialects/sqlite/query.js:183:50
    at new Promise (<anonymous>)
    at Query.run (/Users/yannick/workspace/listenleon/testsequelize/node_modules/sequelize/lib/dialects/sqlite/query.js:183:12)
    at /Users/yannick/workspace/listenleon/testsequelize/node_modules/sequelize/lib/sequelize.js:315:28
    at async SQLiteQueryInterface.bulkUpdate (/Users/yannick/workspace/listenleon/testsequelize/node_modules/sequelize/lib/dialects/abstract/query-interface.js:366:12)
    at async email.update (/Users/yannick/workspace/listenleon/testsequelize/node_modules/sequelize/lib/model.js:2010:28)
    at async HasMany.add (/Users/yannick/workspace/listenleon/testsequelize/node_modules/sequelize/lib/associations/has-many.js:267:5)
    at async file:///Users/yannick/workspace/listenleon/testsequelize/test.js:45:1 {
  name: 'SequelizeForeignKeyConstraintError',
  parent: [Error: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed] {
    errno: 19,
    code: 'SQLITE_CONSTRAINT',
    sql: 'UPDATE `emails` SET `userId`=$1,`updatedAt`=$2 WHERE `id` IN (1)'
  },
  original: [Error: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed] {
    errno: 19,
    code: 'SQLITE_CONSTRAINT',
    sql: 'UPDATE `emails` SET `userId`=$1,`updatedAt`=$2 WHERE `id` IN (1)'
  },
  sql: 'UPDATE `emails` SET `userId`=$1,`updatedAt`=$2 WHERE `id` IN (1)',
  parameters: {},
  table: undefined,
  fields: undefined,
  value: undefined,
  index: undefined,
  reltype: undefined
}

Node.js v18.12.1
```

### Environment

- Sequelize version: 6.30.0 and 7.0.0-alpha.23
- Node.js version: v18.12.1
- Database & Version: SQLite 3
- Connector library & Version: sqlite3@5.1.6

## Would you be willing to resolve this issue by submitting a Pull Request?

Is it related to this part of the code?
https://github.com/sequelize/sequelize/blob/main/packages/core/src/associations/has-many.ts#L428

Does it call the get method without the raw option? I'm new to Sequelize; I don't know this library well yet.

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [x] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by ephys** [comment]
This is definitely caused by association methods making `raw` queries, which don't produce models, and therefore don't have getter/setters

**Comment by YannickDa** [comment]
If I add the option `{raw: true}` on every call of get method is not a good way to resolve this bug?

It can break something somewhere else?

**Comment by ephys** [comment]
It's not something you can fix on your end, I'm also not sure whether it's going to break something, but we'll find out when we implement the fix and run our test suites

**Comment by YannickDa** [comment]
I mean if I propose a fix for this library. Not only on my side on my project. 

I'm new with this library, if you think it's possible to fix this bug adding this option, I can try to propose a fix.

**Comment by olegnechiporuk** [comment]
I had a similar issue.  My setup: 
- node: 20.10.0
- sequelize: 6.35.2
- typescript: 5.3.3
- next: 14.0.4

My models were defined extending Model class: 
 ```
class User extends Model<InferAttributes<User>, InferCreationAttributes<User>> {
  ...
}
class Role extends Model<InferAttributes<Role >, InferCreationAttributes<Role >> {
  ...
} 

User.init(UserProps, {
    sequelize,
    tableName: "Users",
});
Role.init(RoleProps, {
    sequelize,
    tableName: "Roles",
});
const UserRole = sequelize.define("UserRole", {}, { timestamps: false })
User.belongsToMany(Role, { through: UserRole });
Role.belongsToMany(User, { through: UserRole });
```

In development mode (`next dev`) it was working file and mixins like `User.getRoles()` were defined and I was able to use them. 
But in production mode (`next build && next start`) it was not working. mixins like getRoles() were undefined. 

Adding model name to the definition solved the issue in my case: 
```
User.init(UserProps, {
    sequelize,
    tableName: "Users",
    modelName: "User",
});
``` 

I hope it will save time to somebody.
