### ISSUE TITLE
Postgres: Cloning DataType.ARRAY fails in the context of `withScope`

### ISSUE THREAD

**Issue by jfo** [sequelize/sequelize#15860]
## Issue Creation Checklist

- [x] I understand that my issue will be automatically closed if I don't fill in the requested information
- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

I've run into this in the context of [scopes](https://sequelize.org/docs/v7/other-topics/scopes/#definition), so that's what the reproduction will be using, but I assume it would have unintended effects in other areas.

Cloning a model with an attribute whose DataType is an array of other DataTypes results in a error. Does not seem to matter what the subtype is.

```
  [cause]: Error: This DataType is already attached to attribute... // etc
``` 

[This patch](https://github.com/sequelize/sequelize/compare/main...jfo:sequelize:jfo/clone-diff) naively "fixes" it, but I doubt it's that straightforward.

### Reproducible Example

Here is the link to the SSCCE for this issue:

https://github.com/jfo/sequelize-repro/blob/main/scope.js

The resulting error, in full:

```
BaseError [SequelizeBaseError]: An error occurred while normalizing attribute "arrayOfStrings" in model "Thing".
    at ModelDefinition.refreshAttributes (/Users/jeffrey.fowler/code/sharding/node_modules/@sequelize/core/lib/model-definition.js:497:15)
    at new ModelDefinition (/Users/jeffrey.fowler/code/sharding/node_modules/@sequelize/core/lib/model-definition.js:314:10)
    ... 4 lines matching cause stack trace ...
    at Thing.withScope (/Users/jeffrey.fowler/code/sharding/node_modules/@sequelize/core/lib/model.js:802:25)
    at /Users/jeffrey.fowler/code/sharding/scope.js:44:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [cause]: Error: This DataType is already attached to attribute Thing#arrayOfStrings, and therefore cannot be attached to attribute Thing#arrayOfStrings.
      at STRING.attachUsageContext (/Users/jeffrey.fowler/code/sharding/node_modules/@sequelize/core/lib/dialects/abstract/data-types.js:297:13)
      at ARRAY.attachUsageContext (/Users/jeffrey.fowler/code/sharding/node_modules/@sequelize/core/lib/dialects/abstract/data-types.js:1331:25)
      at ARRAY.withUsageContext (/Users/jeffrey.fowler/code/sharding/node_modules/@sequelize/core/lib/dialects/abstract/data-types.js:285:30)
      at ModelDefinition.refreshAttributes (/Users/jeffrey.fowler/code/sharding/node_modules/@sequelize/core/lib/model-definition.js:401:53)
      at new ModelDefinition (/Users/jeffrey.fowler/code/sharding/node_modules/@sequelize/core/lib/model-definition.js:314:10)
      at initModel (/Users/jeffrey.fowler/code/sharding/node_modules/@sequelize/core/lib/model-typescript.js:321:27)
      at Thing.init (/Users/jeffrey.fowler/code/sharding/node_modules/@sequelize/core/lib/model-typescript.js:245:5)
      at Thing._createModelVariant (/Users/jeffrey.fowler/code/sharding/node_modules/@sequelize/core/lib/model.js:887:11)
      at Thing._withScopeAndSchema (/Users/jeffrey.fowler/code/sharding/node_modules/@sequelize/core/lib/model.js:870:24)
      at Thing.withScope (/Users/jeffrey.fowler/code/sharding/node_modules/@sequelize/core/lib/model.js:802:25)
}

```

### What do you expect to happen?

Deep cloning

### What is actually happening?

Shallow cloning

### Environment

- Sequelize version: 7.0.0-alpha.25
- Node.js version: v18.13.0
- Database & Version: Postgres 14.1
- Connector library & Version: pg 8.10.0

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [ ] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by ephys** [comment]
Your patch looks like the correct solution to me, all we're missing is a regression test

**Comment by jfo** [comment]
In that case let me do a bit more due diligence on that patch because iirc, I may have seen some failures unrelated to scopes when I attempted it in our api code. I'm happy to add a regression test if you can direct me to docs or examples on how / where to add them and run locally 🙂

**Comment by jfo** [comment]
Thanks, that's very helpful. I'll update this issue with questions or progress when I have some time to look at it.

**Comment by jfo** [comment]
The failures I had had in mind have to do with another patch I have already applied to temporarily address a different issue, which I will link back to here if I end up needing to report that one. In the interim I should be able to find the time to attempt the suggested fix for the original issue.

**Comment by bra1n** [comment]
I ran into the same issue today and decided to write a short test for @jfo's fix and put everything into a PR: #15994

**Comment by jfo** [comment]
Ha I had finally cleared some time to come back to this this week 😅 thanks @bra1n and obv lgtm :)

**Comment by bra1n** [comment]
Talk about great timing... :grin:

**Comment by bra1n** [comment]
2 years later and this problem is unfortunately still happening... 😬

**Comment by klondikemarlen** [comment]
I'm getting this error as well.

I'm doing
```ts
import {
  DataTypes,
  Model,
  Op,
  sql,
  type CreationOptional,
  type InferAttributes,
  type InferCreationAttributes,
} from "@sequelize/core"
import { Attribute } from "@sequelize/core/decorators-legacy"

export enum RoleNames {
  ADMIN = "admin",
  USER = "user",
  PRE_APPROVED_TRAVEL_ADMIN = "pre_approved_travel_admin",
  DEPARTMENT_ADMIN = "department_admin",
  TRAVEL_DESK_USER = "travel_desk_user",
}

class User extends Model<InferAttributes<User>, InferCreationAttributes<User>> {
  @Attribute(DataTypes.ARRAY(DataTypes.STRING))
  declare roles: CreationOptional<string[]>

  static establishScopes(): void {
    this.addScope("isTravelDeskUser", () => ({
      where: {
        roles: {
          [Op.contains]: [RoleNames.TRAVEL_DESK_USER],
        },
      },
    }))
  }
}
```
then
```ts
const users = await User.withScope("isTravelDeskUser").findAll()
```

I think I'm probably going to have to convert the column to a "string" column and store the data as a comma separated list.
Then write some raw sql to do the appropriate role contains check.
