### ISSUE TITLE
Multiple hasOne associations in same model to same target not working with hooks

### ISSUE THREAD

**Issue by MrStanDu33** [sequelize/sequelize#16007]
## Issue Creation Checklist

- [x] I understand that my issue will be automatically closed if I don't fill in the requested information
- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

I am currently working on upgrading from Sequelize v6.x.x to Sequelize v7.x.x.

In my project, I have on model named `Action`, and one named `ActionGoto`.

let say this is their definition :
```js
const Action = instance.define('Action', {},  { tableName: 'Action' });
const ActionGoto = instance.define('Action_Goto', {});
```
This model declaration is simplified as other columns are irrelevent for this demonstration.

The goal is to have any instances of `ActionGoto` to refer an `Action`, so it has a relation defined by this code :
```js
Action.hasOne(ActionGoto, {
  as: 'Goto',
  foreignKey: { name: 'ActionId', ...cascadeHooks },
});
ActionGoto.belongsTo(Action);
```
But this `ActionGoto`, in addition to being refered to an `Action`, link to another `Action` (kinda like a bridge).
So after adding the second relationship, we have this code :
```js
Action.hasOne(ActionGoto, {
  as: 'Goto',
  foreignKey: {
    name: 'ActionId',
    onDelete: 'CASCADE',
    onUpdate: 'CASCADE',
  },
});
Action.hasOne(ActionGoto, {
  foreignKey: {
    name: 'TargetActionId',
    onDelete: 'CASCADE',
    onUpdate: 'CASCADE',
  },
});
ActionGoto.belongsTo(Action);
```

This code used to work and match my expectations since the beginning.

But since Sequelize v7.x.x, foreign keys definitions must match.
So if I declare on one side some hooks, I need to declare them on the other side.

So I made this change :
```js
Action.hasOne(ActionGoto, {
  as: 'Goto',
  foreignKey: {
    name: 'ActionId',
    onDelete: 'CASCADE',
    onUpdate: 'CASCADE',
  },
});
Action.hasOne(ActionGoto, {
  foreignKey: {
    name: 'TargetActionId',
    onDelete: 'CASCADE',
    onUpdate: 'CASCADE',
  },
});

ActionGoto.belongsTo(Action, {
  foreignKey: {
    name: 'ActionId',
    onDelete: 'CASCADE',
    onUpdate: 'CASCADE',
  },
});
ActionGoto.belongsTo(Action, {
  foreignKey: {
    name: 'TargetActionId',
    onDelete: 'CASCADE',
    onUpdate: 'CASCADE',
  },
});
```
Obviously this would not work, and it does !
<details>
  <summary>I get this error :</summary>
  <br/>
  <blockquote>Sorry for bad formatting, got hard time with GitHub formatting wrong the whole code block, so I had to split it :/</blockquote>
<pre>
AssociationError [SequelizeAssociationError]: Defining HasOne association "Action_Goto" from Action to Action_Goto failed
    at defineAssociation (/var/www/SansPriseDeBot/node_modules/@sequelize/core/lib/associations/helpers.js:165:11)
    at HasOne.associate (/var/www/SansPriseDeBot/node_modules/@sequelize/core/lib/associations/has-one.js:104:49)
    ... 2 lines matching cause stack trace ...
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [cause]: AssociationError [SequelizeAssociationError]: The association "Action_Goto" needs to define the BelongsTo association "Action" from Action_Goto to Action,
  but that child association has already been defined as BelongsTo, to Action by this call:
</pre><pre>
  Action.hasOne(Action_Goto, {
    as: 'Goto',
    foreignKey: { name: 'ActionId', onDelete: 'CASCADE', onUpdate: 'CASCADE' },
    hooks: false,
    name: { plural: 'Gotos', singular: 'Goto' }
  })
</pre><pre>
  That association would be re-used if compatible, but it is incompatible because their options are not reconcilable:
</pre><pre>
  Options of the association to create:
  {
    as: 'Action',
    foreignKey: { name: 'TargetActionId', onDelete: 'CASCADE', onUpdate: 'CASCADE' },
    hooks: false,
    name: { plural: 'Actions', singular: 'Action' }
  }
</pre><pre>
  Options of the existing association:
  {
    as: 'Action',
    foreignKey: { name: 'ActionId', onDelete: 'CASCADE', onUpdate: 'CASCADE' },
    hooks: false,
    name: { plural: 'Actions', singular: 'Action' }
  }
</pre><pre>
      at assertAssociationUnique (/var/www/SansPriseDeBot/node_modules/@sequelize/core/lib/associations/helpers.js:101:9)
      at defineAssociation (/var/www/SansPriseDeBot/node_modules/@sequelize/core/lib/associations/helpers.js:149:3)
      at BelongsTo.associate (/var/www/SansPriseDeBot/node_modules/@sequelize/core/lib/associations/belongs-to.js:176:49)
      at new HasOne (/var/www/SansPriseDeBot/node_modules/@sequelize/core/lib/associations/has-one.js:84:48)
      at /var/www/SansPriseDeBot/node_modules/@sequelize/core/lib/associations/has-one.js:112:14
      at defineAssociation (/var/www/SansPriseDeBot/node_modules/@sequelize/core/lib/associations/helpers.js:163:64)
      at HasOne.associate (/var/www/SansPriseDeBot/node_modules/@sequelize/core/lib/associations/has-one.js:104:49)
      at Action.hasOne (/var/www/SansPriseDeBot/node_modules/@sequelize/core/lib/model.js:3294:39)
      at file:///var/www/SansPriseDeBot/src/Models/index.js:106:11
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
</pre>
</details>

This error seemed logical to me, as I would just have to remove the duplicated `ActionGoto.belongsTo()` declaration.
So we would end with something like this :
```js
Action.hasOne(ActionGoto, {
  as: 'Goto',
  foreignKey: {
    name: 'ActionId',
    onDelete: 'CASCADE',
    onUpdate: 'CASCADE',
  },
});
Action.hasOne(ActionGoto, {
  foreignKey: {
    name: 'TargetActionId',
    onDelete: 'CASCADE',
    onUpdate: 'CASCADE',
  },
});

ActionGoto.belongsTo(Action, {
  foreignKey: {
    name: 'ActionId',
    onDelete: 'CASCADE',
    onUpdate: 'CASCADE',
  },
});
```
But then, It would crash as the second `ActionGoto.hasOne()` (the one who refers `TargetActionId`) do not longer have an associated `belongsTo` declaration.

So as I cannot write two `belongsTo` declaration from the same model referring the same other model, and writing only one leads to an error due to the second `hasOne` not having a matching `belongsTo` declaration, what should I do to make it work ?

For better understanding, here is a little diagram explaining what I am trying to do :
![image](https://github.com/sequelize/sequelize/assets/22714562/db1b9d66-d4c0-4cbf-9b3c-1bc9ab3531fc)

### Reproducible Example

Here is the link to the SSCCE for this issue: https://github.com/sequelize/sequelize-sscce/pull/254

### What do you expect to happen?

At least one of these cases :
- We should have either a way to use one `belongsTo` declaration for the two `hasOne` declarations (without having to precise the `foreignKey` name)
- We should be able to define two `belongsTo` matching the two `hasOne` declarations (one for each one)

### What is actually happening?

- When we use only one `belongsTo` declaration without giving the `foreingKey` name, we get yelled at.
- When we use only one `belongsTo` declaration with the `foreingKey` name, we get yelled at.
- When we use two `belongsTo` declarations with the corresponding `foreingKey`,, we get yelled at.

Every times we get this error :
```
That association would be re-used if compatible, but it is incompatible because their options are not reconcilable
```

### Environment

- Sequelize version: `@sequelize/core@7.0.0-alpha.23`
- Node.js version: `v18.11.0`
- Database & Version: `mysql  Ver 15.1 Distrib 10.5.19-MariaDB`
- Connector library & Version: `mysql2 v3.3.0`

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [X] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [ ] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by MrStanDu33** [comment]
By the way, It seems quite similar to [this](https://github.com/sequelize/sequelize/issues/15625) issue, but he does not have hooks, so that is not a problem for him.

**Comment by MrStanDu33** [comment]
I have checked, the fact that `foreignKey` hooks must be provided both in `hasOne` and `belongsTo` seems to be implemented in version [7.0.0-alpha.14](https://github.com/sequelize/sequelize/releases/tag/v7.0.0-alpha.14)

**Comment by MrStanDu33** [comment]
In fact, it seems that this example [documented here](https://sequelize.org/docs/v7/core-concepts/assocs/#multiple-associations-involving-the-same-models) is not reproducible at all, leading to an error :

```js
const Team = instance.define('Team', {});
const Game = instance.define('Game', {});

Team.hasOne(Game, { as: 'HomeTeam', foreignKey: 'homeTeamId' });
Team.hasOne(Game, { as: 'AwayTeam', foreignKey: 'awayTeamId' });
Game.belongsTo(Team);
```

error :

![image](https://github.com/sequelize/sequelize/assets/22714562/3682cc13-4f19-40db-8ab5-4eae45a410b8)

**Comment by ephys** [comment]
The documentation for v7 is not merged yet, so what you see on the website is incorrect. See https://github.com/sequelize/website/pull/330#issuecomment-1455038636 instead

Specifically, this is the page you'll want: https://6404627a0dfed06840d8efb6--sequelize-site.netlify.app/docs/v7/associations/has-one/

It uses decorators but the functional API you used is the same thing, the decorator just makes sure associations are defined after all models are defined

Basically you're trying to define two different hasOne associations to the same model.
hasOne associations automatically define their inverse (belongsTo) association, as the belongsTo association is the one that represents the actual database association & owns the foreign key

Because you don't provide a name for the inverse association, it tries to create two belongs to associations with the same inferred name, but can't because they use two different foreign keys

Here is what we recommend:

- drop the belongsTo association, use the `inverse` option instead
- name the inverse association

```ts
Action.hasOne(ActionGoto, {
  as: 'Goto',
  foreignKey: {
    name: 'ActionId',
    onDelete: 'CASCADE',
    onUpdate: 'CASCADE',
  },
  inverse: {
    as: 'action1'
  },
});

Action.hasOne(ActionGoto, {
  foreignKey: {
    name: 'TargetActionId',
    onDelete: 'CASCADE',
    onUpdate: 'CASCADE',
  },
  inverse: {
    as: 'action2',
  },
});
```
