### ISSUE TITLE
Transactions not closing their connections

### ISSUE THREAD

**Issue by causal-agent** [sequelize/sequelize#1601]
I'm using transactions (connected to a Postgres database) and after I call `commit()` or `rollback()` on them, their connections are left open, causing a `sorry, too many clients already` error to happen later on in my application when I try to start more transactions.

Output from `SELECT * FROM pg_stat_activity;` after a transaction has run and completed:

```
-[ RECORD 1 ]----+--------------------------------
datid            | 1551576
datname          | listens
pid              | 12586
usesysid         | 16384
usename          | curtis
application_name | psql
client_addr      | 
client_hostname  | 
client_port      | -1
backend_start    | 2014-04-06 16:57:43.994157-04
xact_start       | 2014-04-06 16:58:19.613453-04
query_start      | 2014-04-06 16:58:19.613453-04
state_change     | 2014-04-06 16:58:19.613455-04
waiting          | f
state            | active
query            | select * from pg_stat_activity;
-[ RECORD 2 ]----+--------------------------------
datid            | 1551576
datname          | listens
pid              | 12646
usesysid         | 16384
usename          | curtis
application_name | 
client_addr      | 127.0.0.1
client_hostname  | 
client_port      | 33059
backend_start    | 2014-04-06 16:58:14.909206-04
xact_start       | 
query_start      | 2014-04-06 16:58:14.956924-04
state_change     | 2014-04-06 16:58:14.957053-04
waiting          | f
state            | idle
query            | COMMIT;
```

**Comment by kishita101** [comment]
I am still facing the same issue!
```
Error: ConnectionManager.getConnection was called after the connection manager was closed!
server  |     at ConnectionManager.getConnection (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:70:13)
server  |     at /app/node_modules/sequelize/lib/sequelize.js:305:111
server  |     at /app/node_modules/retry-as-promised/dist/index.js:59:25
server  |     at new Promise (<anonymous>)
server  |     at retryAsPromised (/app/node_modules/retry-as-promised/dist/index.js:48:12)
server  |     at Sequelize.query (/app/node_modules/sequelize/lib/sequelize.js:300:12)
server  |     at MySQLQueryInterface.select (/app/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:33)
server  |     at Function.findAll (/app/node_modules/sequelize/lib/model.js:1140:47)
server  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
server  |     at async Function.findOne (/app/node_modules/sequelize/lib/model.js:1240:12)
```
