### ISSUE TITLE
Issue with combining Op.overlap and Op.not

### ISSUE THREAD

**Issue by benlutz** [sequelize/sequelize#16053]
## Issue Creation Checklist

- [X] I understand that my issue will be automatically closed if I don't fill in the requested information
- [X] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

Currently running feathersJS with Sequelize and a Postgres Database.

I am trying to query combining the `Op.not` and `Op.contains` operator, to get a result that is not matching an array of dates. Using the `Op.contains` operator by itself works as intended.

### What do you expect to happen?

using this query
````
query = {
   dates: {
      Op.not: {
         Op.overlap: ['2023-05-24T22:00:00.000Z', '2023-05-25T22:00:00.000Z']
      }
   }
}

````

I expect it to return all results, that do not have a `dates` array containing any of these given dates.

### What is actually happening?

It throws this error:

````
 err: "TypeError: values.map is not a function\n    at ARRAY._value (/app/node_modules/sequelize/src/dialects/postgres/data-types.js:460:19)\n    at ARRAY._stringify (/app/node_modules/sequelize/src/dialects/postgres/data-types.js:475:29)\n    at ARRAY.stringify (/app/node_modules/sequelize/src/data-types.js:24:19)\n    at PostgresQueryGenerator.escape (/app/node_modules/sequelize/src/dialects/abstract/query-generator.js:1065:30)\n    at PostgresQueryGenerator._whereParseSingleValueObject (/app/node_modules/sequelize/src/dialects/abstract/query-generator.js:2775:41)\n    at PostgresQueryGenerator.whereItemQuery (/app/node_modules/sequelize/src/dialects/abstract/query-generator.js:2475:21)\n    at /app/node_modules/sequelize/src/dialects/abstract/query-generator.js:2376:25\n    at Array.forEach (<anonymous>)\n    at PostgresQueryGenerator.whereItemsQuery (/app/node_modules/sequelize/src/dialects/abstract/query-generator.js:2374:35)\n    at PostgresQueryGenerator.getWhereConditions (/app/node_modules/sequelize/src/dialects/abstract/query-generator.js:2802:19)"

````

### Environment

- Sequelize version: 6.12.4
- Node.js version: v18.12.1
- If TypeScript related: TypeScript version: 5.0.2
- Database & Version: postgres:14.1-alpine
- Connector library & Version: pg 8.7.3

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [X] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by ephys** [comment]
try this:

```ts
query = {
  [Op.not]: {
    dates: {
      [Op.overlap]: ['2023-05-24T22:00:00.000Z', '2023-05-25T22:00:00.000Z']
    }
  }
}
```

**Comment by benlutz** [comment]
Wow... well, yes that works. Thank you!

**Comment by ephys** [comment]
You're welcome :)

Support for that variant was added in Sequelize 7: https://github.com/sequelize/sequelize/blob/8cce991f0b1d6956637b77bbdf0f491dc7fbd451/packages/core/test/unit/sql/where.test.ts#L770
