### ISSUE TITLE
SequelizeConnectionError: Failed to lookup instance - Azure Sql Database

### ISSUE THREAD

**Issue by kamlesh-nb** [sequelize/sequelize#16054]
We are trying to migrate applications from on-prem to Azure App Service (Windows), when we run the app it throw following exception. TCPPING works fine with the database hostname.

Please help!

**SequelizeConnectionError**: F**ailed to lookup instance on** <name>.windows.net - recvmsg EINVAL
    at Connection.<anonymous> (C:\home\site\wwwroot\node_modules\sequelize\lib\dialects\mssql\connection-manager.js:113:20)
    at Connection.emit (node:events:527:28)
    at C:\home\site\wwwroot\node_modules\tedious\lib\connection.js:972:16
    at C:\home\site\wwwroot\node_modules\tedious\lib\instance-lookup.js:66:13
    at Socket.onError (C:\home\site\wwwroot\node_modules\tedious\lib\sender.js:106:9)
    at Socket.emit (node:events:527:28)
    at UDP.onMessage [as onmessage] (node:dgram:919:17)
    at UDP.callbackTrampoline (node:internal/async_hooks:130:17)

**Comment by ephys** [comment]
Please follow the issue template or open a discussion if it's an help request instead of a bug report
