### ISSUE TITLE
Support Cockroach DB Store columns

### ISSUE THREAD

**Issue by jiqiang90** [sequelize/sequelize#16107]
## Issue Creation Checklist

- [x] I understand that my issue will be automatically closed if I don't fill in the requested information
- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### Describe the feature you'd like to see implemented

Env:

- nodejs 18
- sequelize 6.32.0

Our project are using sequelize with cockroach db, everything works except when we manually created a Store columns with cockroach db, it will failed to sync the model. 

Store column (https://www.cockroachlabs.com/docs/v23.1/create-index#store-columns) is helping us significantly improve the query performance, we have tried composite indexes but seems didn't help much.

Here is an example of the table and cockroach index definition

```SQL

create table if not exists polkadot.events
(
    id           text    not null
        primary key,
    module       text    not null,
    event        text    not null,
    block_height numeric not null
);

alter table polkadot.events
    owner to root;

create index if not exists "0xc0c9768d1987b60f"
    on polkadot.events (block_height);

create index if not exists "0x46e7a495bb4c21d1"
    on polkadot.events (event);

create index if not exists "0x62b8f3181611d490"
    on polkadot.events (module);

```

``` SQL
CREATE INDEX events_block_height_idx ON postgres.polkadot.events USING btree (block_height ASC) STORING (module, event)
```

It currently throwing this error:

```
Cannot read properties of undefined (reading 'match')
    at /Users/jiatwork/ofn/subql/node_modules/sequelize/src/dialects/postgres/query.js:174:32
    at Array.map (<anonymous>)
    at Query.run (/Users/jiatwork/ofn/subql/node_modules/sequelize/src/dialects/postgres/query.js:165:44)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/jiatwork/ofn/subql/node_modules/sequelize/src/sequelize.js:650:16
    at async PostgresQueryInterface.showIndex (/Users/jiatwork/ofn/subql/node_modules/sequelize/src/dialects/abstract/query-interface.js:600:12)
    at async Function.sync (/Users/jiatwork/ofn/subql/node_modules/sequelize/src/model.js:1413:29)
    at async Sequelize.sync (/Users/jiatwork/ofn/subql/node_modules/sequelize/src/sequelize.js:825:9)
```

I been doing some debugging , and find out in https://github.com/sequelize/sequelize/blob/99c3530c49d286fd0045712307110cd4f7f52add/src/dialects/postgres/query.js#L151
with our index defination will return `[ 'block_height ASC) STORING (module', ' event' ]`, which isn't correct.

With the `showIndexes` query I can see there are 3 IndKey, and attribute will got undefined due to out the range.
<img width="1410" alt="image" src="https://github.com/sequelize/sequelize/assets/10431657/1477d600-b560-45dd-9cc9-fef9522f7f08">

My questions is how can we get around with the manually created indexes? Is the a way to ignore these indexes from the model sync ?  Or is that possible to support such index definitions?  

### Describe why you would like this feature to be added to Sequelize

This will make Sequelize more adpatable with Cockroach db. 

### Is this feature dialect-specific?

- [ ] No. This feature is relevant to Sequelize as a whole.
- [x] Yes. This feature only applies to the following dialect(s): 

### Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [ ] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in implementing my feature.

---

*Indicate your interest in the addition of this feature by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by WikiRik** [comment]
Looping @divye11 in since they are working on improving CockroachDB support in v7
