### ISSUE TITLE
destroy() fails without pointing to the code that failed

### ISSUE THREAD

**Issue by theunreal** [sequelize/sequelize#16113]
## Issue Creation Checklist

- [ x] I understand that my issue will be automatically closed if I don't fill in the requested information
- [ x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

When I'm checking the console log of my NodeJS application, I sometimes see the following error:

This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
```
Error
    at Query.run (/scratch/pokearena-server/node_modules/sequelize/lib/dialects/mysql/query.js:52:25)
    at /scratch/pokearena-server/node_modules/sequelize/lib/sequelize.js:315:28
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
    at async MySQLQueryInterface.bulkDelete (/scratch/pokearena-server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:403:12)
    at async Function.destroy (/scratch/pokearena-server/node_modules/sequelize/lib/model.js:1838:16)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error
    at Query.run (/scratch/pokearena-server/node_modules/sequelize/lib/dialects/mysql/query.js:52:25)
    at /scratch/pokearena-server/node_modules/sequelize/lib/sequelize.js:315:28
    at async MySQLQueryInterface.bulkDelete (/scratch/pokearena-server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:403:12)
    at async Function.destroy (/scratch/pokearena-server/node_modules/sequelize/lib/model.js:1838:16)
```

The issue is, it points nowhere in my code, so I can't understand what is the query/operation that caused it.

### Reproducible Example
I have no idea since the error do not point to anywhere in my code, just saying something about sequelize bulkDelete operation

### What do you expect to happen?

Sequelize to point me to the right place in my code / or operation that failed.

### What is actually happening?

The error above

### Environment

To find the version numbers for the three systems below use the following commands:

`-- sequelize@6.31.1
MySQL 8.0.19
- Node.js version: v18.14.0

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [x ] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by ephys** [comment]
The stack trace does not stop inside of our code, so it looks like it's your code that has an issue. This does not look like a bug on our end.

**Comment by theunreal** [comment]
@ephys The whole stack trace is from `node_modules/sequelize`. How is it my code?

**Comment by ephys** [comment]
Everything from Sequelize is complete: The stack ends at `YourModel.destroy`, which means there is likely something regarding how `YourModel.destroy` was called that caused it to lose track there. The only place in our codebase where we call the `destroy` static method ourselves is in the [`truncate`](https://github.com/sequelize/sequelize/blob/a3213f053bcc4534073e56def64f22392edaf28c/src/model.js#L2998) static method, and I don't see anything special there.

Combined with the fact that the error you posted is a unhandled promise rejection warning, I think the source of the issue is that one of your calls to `destroy` is not awaited. Compare these two examples where in one of them I await my call, and in the other I don't. The first one has an incomplete stacktrace

Not awaiting:

![Screenshot 2023-07-05 at 14 09 11](https://github.com/sequelize/sequelize/assets/1280915/2a2bc1eb-1398-48e3-ad4d-f2d5db515f0d)

Awaiting:

![image](https://github.com/sequelize/sequelize/assets/1280915/634666ca-6964-459a-b11c-6fbe7667aabd)

In this example, view `a` as `Model.destroy`, and `b` as whichever code you wrote that called `Model.destroy`
