### ISSUE TITLE
createTableQuery failing in 7.0.0-alpha.27  (works in 26)

### ISSUE THREAD

**Issue by vandohman7** [sequelize/sequelize#16172]
## Issue Creation Checklist

- [x] I understand that my issue will be automatically closed if I don't fill in the requested information
- [ ] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description
```bash

My script to sync my database suddenly started throwing errors... rolling back ot alpha.26 fixed it.

Error: The following options are not supported by createTableQuery in postgres: charset, collate
    at buildInvalidOptionReceivedError (/Users/nalberg/Sites/af-spro/node_modules/@sequelize/core/src/utils/check.ts:131:10)
    at rejectInvalidOptions (/Users/nalberg/Sites/af-spro/node_modules/@sequelize/core/src/utils/check.ts:126:11)
    at PostgresQueryGenerator.createTableQuery (/Users/nalberg/Sites/af-spro/node_modules/@sequelize/core/src/dialects/postgres/query-generator.js:99:7)
    at PostgresQueryInterface.createTable (/Users/nalberg/Sites/af-spro/node_modules/@sequelize/core/src/dialects/abstract/query-interface.js:188:37)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Function.sync (/Users/nalberg/Sites/af-spro/node_modules/@sequelize/core/src/model.js:751:7)
    at async Sequelize.sync (/Users/nalberg/Sites/af-spro/node_modules/@sequelize/core/src/sequelize.js:908:9)

```

### Reproducible Example

Here is the link to the SSCCE for this issue:

### What do you expect to happen?

The sync should create database tables

### What is actually happening?
It errors.

### Environment

- Sequelize version: 7.0.0-alpha.27
- Node.js version: 18.13
- If TypeScript related: TypeScript version: 5.0.4
- Database & Version: postgres:15-alpine
- Connector library & Version: pg - 8.11.0,  pg-hstore - 2.3.4

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [x] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by nawlbergs** [comment]
I have this exact same problem

**Comment by WikiRik** [comment]
Thanks for using the alpha version! We're working towards restricting our functions to only allow the options that the dialect supports and in your case you seem to be using the `charset` and `collate` options which are not supported in postgres. Are you able to find instances of those options where you use `createTable` in your code?

**Comment by nawlbergs** [comment]
ah... ok.. yea i've switched between mysql and postgres a bit...  ill pull out the charset and collate and see if it works.
```js
 const options: Options = {
      logging: false, //console.log,
      logQueryParameters: true,
      pool: {
        // handleDisconnects: true,
        max: 13, // max number of connections in pool
        min: 1, // min number of connections in pool
        idle: 10000, // time active connection can be idle before being evicted from pool
        acquire: 20000, // time to wait to establish new connection for pool
      },
      define:{
        // defaults
        charset: 'utf8mb4',
        collate: 'utf8mb4_unicode_ci',
        timestamps: true,
        createdAt: 'createdOn',
        updatedAt: 'modifiedOn',
      },
    };
```

**Comment by nawlbergs** [comment]
Yea its works if I remove: 
```
        charset: 'utf8mb4',
        collate: 'utf8mb4_unicode_ci',
```
You can close this... Vandohman7 is my sons account.. i accidently posted while i was logged in as him.
Thanks.
