### ISSUE TITLE
Commit 6d9a58e7 broke the enum support in CockroachDB

### ISSUE THREAD

**Issue by dapeleg-dn** [sequelize/sequelize#16191]
## Issue Creation Checklist

- [x] I understand that my issue will be automatically closed if I don't fill in the requested information
- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

The change in `query-generator.js` in [commit 6d9a58e7](https://github.com/sequelize/sequelize/commit/6d9a58e7556de614133c2d16ba6ee8e8cebd5fa0) by @aristov caused enum to stop working when using the "PostgreSQL-compatible" [CockroachDB](https://www.cockroachlabs.com/). 

The change in the commit is replacing `CREATE TYPE ${enumName} AS ${values};` with `DO ${this.escape(``BEGIN CREATE TYPE ${enumName} AS ${values}; EXCEPTION WHEN duplicate_object THEN null; END``)};`

This fails in CockroachDB because the `DO` syntax is not supported. Here's a dump from the tests of the `sequelize-cockroachdb` project:

```
  2) QueryInterface
       createTable
         enums
           should work with enums (1):
     at or near "do": syntax error
  Error
      at Query.run (node_modules/sequelize/lib/dialects/postgres/query.js:50:25)
      at /app/node_modules/sequelize/lib/sequelize.js:315:28
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /app/node_modules/sequelize/lib/dialects/postgres/query-interface.js:117:76
      at async PostgresQueryInterface.ensureEnums (node_modules/sequelize/lib/dialects/postgres/query-interface.js:117:20)
      at async PostgresQueryInterface.createTable (node_modules/sequelize/lib/dialects/abstract/query-interface.js:85:5)
      at async Context.<anonymous> (tests/create-table_test.js:118:9)

```

I understand that the purpose of this commit was to not fail on `CREATE TYPE` if the type already exists. The syntax that was used is valid in PostgreSQL DB. However, on CockroachDB which should be "PostgreSQL compatible", this syntax is not supported. They use a much simpler [syntax](https://www.cockroachlabs.com/docs/stable/create-type.html): `CREATE TYPE IF NOT EXISTS ...`.

I know that `sequelize-cockroachdb` is an independent project that is not related to you, the core Sequelize team, but maybe there's a better way to get the requested behavior of this change without breaking the support of CockroachDB. 

My point here is to let you know that this change breaks something elsewhere. I think this is something you prefer to be aware of.

I also created an [issue](https://github.com/cockroachdb/sequelize-cockroachdb/issues/153) in `sequelize-cockroachdb` project.

### Reproducible Example

See [this test](https://github.com/cockroachdb/sequelize-cockroachdb/blob/master/tests/enum_test.js) of `sequelize-cockroachdb` project.

### What do you expect to happen?

Tests of the `sequelize-cockroachdb` project should succeed with no exception regarding the unsupported `do` command.

### What is actually happening?

Enum tests of the `sequelize-cockroachdb` project are failing because of the `do` command. See [this CI output (once GitHub Actions will run)](https://github.com/dapeleg-dn/sequelize-cockroachdb/actions/workflows/ci.yml) and see the stack trace above.

### Environment

- Sequelize version: 6.32.1
- Node.js version: 20.3.1
- If TypeScript related: TypeScript version: 
- Database & Version: cockroachdb/cockroach:v21.2.4
- Connector library & Version: pg (node-postgres) 8.11.1

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [x] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by WikiRik** [comment]
This is something that needs to be fixed in the CockroachDB implementation, which is a separate project for v6 and there is a PR in progress for v7. Therefore I'll close this issue here
