### ISSUE TITLE
[BUG?] V7 ALPHA - key already exists on sync

### ISSUE THREAD

**Issue by nawlbergs** [sequelize/sequelize#16314]
## Issue Creation Checklist

- [x] I understand that my issue will be automatically closed if I don't fill in the requested information
- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

I'm getting a `relation "survey_layout_question_surveyLayoutQuestionSetId_surveyQuestion" already exists` on a postgres database with no tables in it on sync.  I have a lot of tables now and this seems to be an outlier.. so I decided to make an issue:

If I add my through relation to my surveyQuestion table:
```js
    db.surveyQuestion.belongsToMany(db.surveyLayoutQuestionSet, {
      through: db.surveyLayoutQuestion,
      foreignKey: 'surveyQuestionId',
      otherKey: 'surveyLayoutQuestionSetId',
    });
```
Postgres complains and tells me the key already exists???
```js
 ========== SCRIPT ERROR [initial-database-sync] ==========
DatabaseError [SequelizeDatabaseError]: relation "survey_layout_question_surveyLayoutQuestionSetId_surveyQuestion" already exists
    at PostgresQuery.formatError (C:\Users\alber\sites\af-spro\node_modules\@sequelize\core\src\dialects\postgres\query.js:421:16)
    at PostgresQuery.run (C:\Users\alber\sites\af-spro\node_modules\@sequelize\core\src\dialects\postgres\query.js:61:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\alber\sites\af-spro\node_modules\@sequelize\core\src\sequelize.js:735:16
    at async Sequelize.queryRaw (C:\Users\alber\sites\af-spro\node_modules\@sequelize\core\src\sequelize.js:715:12)
    at async PostgresQueryInterface.addIndex (C:\Users\alber\sites\af-spro\node_modules\@sequelize\core\src\dialects\abstract\query-interface.js:510:12)
    at async Function.sync (C:\Users\alber\sites\af-spro\node_modules\@sequelize\core\src\model.js:852:7)
    at async Sequelize.sync (C:\Users\alber\sites\af-spro\node_modules\@sequelize\core\src\sequelize.js:908:9) {
  sql: 'CREATE UNIQUE INDEX "survey_layout_question_surveyLayoutQuestionSetId_surveyQuestionId_unique" ON "survey_layout_question" ("surveyQuestionId", "surveyLayoutQuestionSetId")',
  parameters: {},
  [cause]: error: relation "survey_layout_question_surveyLayoutQuestionSetId_surveyQuestion" already exists
      at Parser.parseErrorMessage (C:\Users\alber\sites\af-spro\node_modules\pg-protocol\src\parser.ts:369:69)
      at Parser.handlePacket (C:\Users\alber\sites\af-spro\node_modules\pg-protocol\src\parser.ts:188:21)
      at Parser.parse (C:\Users\alber\sites\af-spro\node_modules\pg-protocol\src\parser.ts:103:30)
      at Socket.<anonymous> (C:\Users\alber\sites\af-spro\node_modules\pg-protocol\src\index.ts:7:48)
      at Socket.emit (node:events:513:28)
      at Socket.emit (node:domain:489:12)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Socket.Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 145,
    severity: 'ERROR',
    code: '42P07',
    detail: undefined,
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'index.c',
    line: '872',
    routine: 'index_create',
    sql: 'CREATE UNIQUE INDEX "survey_layout_question_surveyLayoutQuestionSetId_surveyQuestionId_unique" ON "survey_layout_question" ("surveyQuestionId", "surveyLayoutQuestionSetId")',
    parameters: undefined
  }
}
Warning: run-commands command "ts-node --project=apps/server/tsconfig.app.json apps/server/scripts/db-sync.ts" exited with non-zero status code
```

It works if I comment out the code...  and these are the keys on the table (just the 1 for the ID):

![image](https://github.com/sequelize/sequelize/assets/1325984/add76a93-3f5d-4ae9-bb8d-9714fd0ad91b)
![image](https://github.com/sequelize/sequelize/assets/1325984/9447fe53-7253-4e85-8c82-fee8005a3da1)

Forcing the key name also solves it...   the error cause says that the relation already exists... but it does not.. 
is this a `key is too long` error in reality...???  or just sequelize not generating a valid unique key by default?
```js
    db.surveyQuestion.belongsToMany(db.surveyLayoutQuestionSet, {
      through: {
        unique: 'surveyQuestion2questionSet',
        model: db.surveyLayoutQuestion,
      },
      foreignKey: 'surveyQuestionId',
      otherKey: 'surveyLayoutQuestionSetId',
    });
```

### Reproducible Example

Here is the link to the SSCCE for this issue:

### What do you expect to happen?

A table and key constraints to be produced.

### What is actually happening?

Error is thrown. See above error.

### Environment

- Sequelize version: `@sequelize/core@7.0.0-alpha.27`
- Node.js version: `18.13.0`
- TypeScript version:  `typescript@5.1.5`
- Database & Version: `PostgreSQL 15.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit`
- Connector library & Version: `pg@8.11.0`

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [x] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by ephys** [comment]
Yes the issue is that the identifier is too long and gets truncated. The identifier in the SQL is `survey_layout_question_surveyLayoutQuestionSetId_surveyQuestionId_unique`, which truncated to postgres' limit of 63 bytes results in `survey_layout_question_surveyLayoutQuestionSetId_surveyQuestion`.

I'll keep this open with the intended fix of throwing if the generated identifier is too long so we can ask the user to provide their own

**Comment by CODEOrz** [comment]
sequelize will auto create an Index , but the name of index is too long for MySQL.
how can use define index by themselves?

**Comment by ephys** [comment]
If I'm not mistaken, all indexes support a "name" option that you can use to name the index. If not provided, Sequelize will infer one: https://sequelize.org/docs/v7/models/indexes/#single-column-index

**Comment by ephys** [comment]
Closing in favor of https://github.com/sequelize/sequelize/issues/15362, as we already had a task for this after all
