### ISSUE TITLE
Change in transaction behavior in Sequelize 6.5 and up

### ISSUE THREAD

**Issue by matthewpalmer** [sequelize/sequelize#16312]
## Issue Creation Checklist

- [x] I understand that my issue will be automatically closed if I don't fill in the requested information
- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

Hi,

I'm trying to update an old application's dependencies, and I found an issue with Sequelize starting from version 6.5.0. I'm not actually sure that Sequelize is incorrect, but it's a weird behavior change that I wanted to ask about.

I think it's the change in behavior for transactions introduced in Sequelize 6.5 by #12841. Specifically, I think it might be [this change](https://github.com/sequelize/sequelize/compare/v6.4.0...v6.5.0#diff-2d59dabfa7d7e5c021c94f91e258828edd7a157aa179771976999685ac1e72bfL59) that affects when the stored CLS transaction is nulled.

In Sequelize 6.4 and below, the CLS transaction was set to null before the `COMMIT` was sent. In Sequelize 6.5+, the CLS transaction is nulled after the `COMMIT` happens. 

The effect of this is that if you issue two queries in a row where the second one isn't `await`ed, in Sequelize 6.4 and below it would perform the second query outside of the transaction (in 6.4.0 the first call to sequelize nulled the CLS transaction before the second query started, but that's not the case starting in 6.5.0). In Sequelize 6.5+, this throws an error because the second query tries to reuse the transaction even though that transaction is already over.

The two relevant versions of sequelize are 6.4.0 and 6.5.0, with 6.4.0 not throwing and 6.5.0 throwing the error.

I'm not actually sure what the correct behavior would be here, since I can understand that you might think it's weird that I'm running non-`await`ed queries from inside a transaction. So I just wanted to ask a few questions (see below). It kind of seems unrelated to the linked PR's intention, and an interesting change to happen for a `6.4.0` to `6.5.0` release, which makes me think it might be unintentional? I'm not sure.

Thanks very much for your help! 😄

### Reproducible Example

To reproduce, run the example with 6.4.0 and then run with 6.5.0. I've used postgres and a simple `Users` table with `id`, `emailAddress`, and `notes` columns. (It's not dependent on the actual queries/table structure, you can do it with anything.)

```js
// sequelize-weird-behavior-example.js
const db = require('./db');

db.transaction(async (t1) => {
    const users = await db.models.User.findAll();
    
    // Trigger a second query that isn't in the promise chain.
    // (In my real Express.js web app, this is an update to the Sessions table that is triggered by "res.send" 
    // which goes via "res.send" -> "res.end" -> express-session -> connect-session-sequelize -> sequelize.)
    db.models.User.update(
        { notes: `Updated note at ${new Date}`},
        {
            where: { emailAddress: 'testing@example.com' }
        }
    );

    return users;
});
```

```js
// db.js
const Sequelize = require('sequelize');
const clsHooked = require('cls-hooked');
const namespace = new clsHooked.createNamespace('sequelize-cls-namespace');

Sequelize.useCLS(namespace);

const DB_URI = `postgres://matthewpalmer:@localhost:5432/testingsessionbug`

const sequelize = new Sequelize(DB_URI, {
    logging: console.log,
});

sequelize.define('User', {
    id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
    },
    emailAddress: {
        type: Sequelize.DataTypes.STRING
    },
    notes: {
        type: Sequelize.DataTypes.STRING
    },
}, {
});

module.exports = sequelize;
```

### What do you expect to happen?

I just wanted to ask a few questions about this change:

* what's the intended/correct behavior of Sequelize here?
* is this change in behavior intentional? (If it is, hopefully I can figure out a way to work around it. If not, I might be able to investigate whether I can fix it in Sequelize.)
* is it valid to use a non-`await`ed query inside a transaction auto-callback? is there any way to do so?

### What is actually happening?

When running on Sequelize 6.4.0, the example works:

```
minimal-current-versions ⟩ node sequelize-weird-behavior-example.js
Executing (82e3682e-0040-4363-a454-0ecb87c0b69d): START TRANSACTION;
Executing (82e3682e-0040-4363-a454-0ecb87c0b69d): SELECT "id", "emailAddress", "notes", "createdAt", "updatedAt" FROM "Users" AS "User";
Executing (82e3682e-0040-4363-a454-0ecb87c0b69d): COMMIT;
Executing (default): UPDATE "Users" SET "notes"=$1,"updatedAt"=$2 WHERE "emailAddress" = $3
```

When running on Sequelize 6.5.0, the example crashes with an error:

```
minimal-current-versions ⟩ node sequelize-weird-behavior-example.js
Executing (64a2ccb9-a375-444e-87c6-dd451efaf835): START TRANSACTION;
Executing (64a2ccb9-a375-444e-87c6-dd451efaf835): SELECT "id", "emailAddress", "notes", "createdAt", "updatedAt" FROM "Users" AS "User";
Executing (64a2ccb9-a375-444e-87c6-dd451efaf835): COMMIT;
/Users/matthewpalmer/Projects/sequelize-sessions-bug/minimal-current-versions/node_modules/sequelize/lib/sequelize.js:598
        const error = new Error(`${options.transaction.finished} has been called on this transaction(${options.transaction.id}), you can no longer use it. (The rejected query is attached as the 'sql' property of this error)`);
                      ^

Error: commit has been called on this transaction(64a2ccb9-a375-444e-87c6-dd451efaf835), you can no longer use it. (The rejected query is attached as the 'sql' property of this error)
    at checkTransaction (/Users/matthewpalmer/Projects/sequelize-sessions-bug/minimal-current-versions/node_modules/sequelize/lib/sequelize.js:598:23)
    at /Users/matthewpalmer/Projects/sequelize-sessions-bug/minimal-current-versions/node_modules/sequelize/lib/sequelize.js:611:7
    at /Users/matthewpalmer/Projects/sequelize-sessions-bug/minimal-current-versions/node_modules/retry-as-promised/index.js:70:21
    at new Promise (<anonymous>)
    at retryAsPromised (/Users/matthewpalmer/Projects/sequelize-sessions-bug/minimal-current-versions/node_modules/retry-as-promised/index.js:60:10)
    at Sequelize.query (/Users/matthewpalmer/Projects/sequelize-sessions-bug/minimal-current-versions/node_modules/sequelize/lib/sequelize.js:606:12)
    at PostgresQueryInterface.bulkUpdate (/Users/matthewpalmer/Projects/sequelize-sessions-bug/minimal-current-versions/node_modules/sequelize/lib/dialects/abstract/query-interface.js:881:33)
    at User.update (/Users/matthewpalmer/Projects/sequelize-sessions-bug/minimal-current-versions/node_modules/sequelize/lib/model.js:3175:54)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  sql: 'UPDATE "Users" SET "notes"=$1,"updatedAt"=$2 WHERE "emailAddress" = $3'
}

Node.js v18.16.1
```

### Environment

- Sequelize version: 6.4.0 and 6.5.0, cls-hooked 4.2.2
- Node.js version: 18.16.1
- If TypeScript related: TypeScript version: n/a
- Database & Version: postgres
- Connector library & Version: pg

Thanks for your help 😄

**Comment by ephys** [comment]
This is the expected behavior. If you want a query to not use the transaction stored in CLS, you need to set its `transaction` option to `null`

- [v7 documentation](https://sequelize.org/docs/v7/querying/transactions/#escaping-the-transaction)
- [v6 documentation](https://sequelize.org/docs/v6/other-topics/transactions/#concurrentpartial-transactions)

**Comment by matthewpalmer** [comment]
Great, thanks so much for getting back to me so quickly 😄
