### ISSUE TITLE
Sqlite: Rows created with queryInterface.insert() cannot be loaded again

### ISSUE THREAD

**Issue by jlherren** [sequelize/sequelize#16340]
## Issue Creation Checklist

- [x] I understand that my issue will be automatically closed if I don't fill in the requested information
- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

Date values created via `queryInterface.insert()` are stored as timestamps and cannot be loaded again, whereas those created via `queryInterface.bulkInsert()` are stored as a formatted string and work fine.

### Reproducible Example

```JavaScript
const {DataTypes, Model, Sequelize} = require('sequelize');

class Configuration extends Model {
}

async function main() {
    let sequelize = new Sequelize({
        'dialect': 'sqlite',
        'storage': 'test.db',
    });
    let queryInterface = sequelize.getQueryInterface();
    await queryInterface.createTable('configurations', {
        id:        {
            type:          DataTypes.INTEGER,
            allowNull:     false,
            primaryKey:    true,
            autoIncrement: true,
        },
        createdAt: {
            type:      DataTypes.DATE,
            allowNull: false,
        },
        updatedAt: {
            type:      DataTypes.DATE,
            allowNull: false,
        },
    });
    await queryInterface.insert(null, 'configurations', {
        createdAt: new Date(),
        updatedAt: new Date(),
    });
    await queryInterface.bulkInsert('configurations', [{
        createdAt: new Date(),
        updatedAt: new Date(),
    }]);

    Configuration.init({}, {sequelize});

    await Configuration.findAll();
}

main();
```

### What do you expect to happen?

The code above should be able to retrieve both rows correctly.

### What is actually happening?

Output of the above snippet:

```
Executing (default): CREATE TABLE IF NOT EXISTS `configurations` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
Executing (default): INSERT INTO `configurations` (`createdAt`,`updatedAt`) VALUES ($1,$2);
Executing (default): INSERT INTO `configurations` (`createdAt`,`updatedAt`) VALUES ('2023-08-02 20:42:25.919 +00:00','2023-08-02 20:42:25.919 +00:00');
Executing (default): SELECT `id`, `createdAt`, `updatedAt` FROM `Configurations` AS `Configuration`;
<project-root>/node_modules/sequelize/lib/dialects/sqlite/data-types.js:39
      if (!date.includes("+")) {
                ^

TypeError: date.includes is not a function
    at parse (<project-root>/node_modules/sequelize/lib/dialects/sqlite/data-types.js:39:17)
    at Query.applyParsers (<project-root>/node_modules/sequelize/lib/dialects/sqlite/query.js:289:14)
    at <project-root>/node_modules/sequelize/lib/dialects/sqlite/query.js:112:80
    at <project-root>/node_modules/lodash/lodash.js:13469:38
    at <project-root>/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (<project-root>/node_modules/lodash/lodash.js:3032:24)
    at Function.mapValues (<project-root>/node_modules/lodash/lodash.js:13468:7)
    at <project-root>/node_modules/sequelize/lib/dialects/sqlite/query.js:93:18
    at Array.map (<anonymous>)
    at Query._handleQueryResponse (<project-root>/node_modules/sequelize/lib/dialects/sqlite/query.js:92:25)
```

Dump of the resulting `test.db`:

```
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE `configurations` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL);
INSERT INTO configurations VALUES(1,1691008945916,1691008945916);
INSERT INTO configurations VALUES(2,'2023-08-02 20:42:25.919 +00:00','2023-08-02 20:42:25.919 +00:00');
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('configurations',2);
COMMIT;
```

### Environment

- Sequelize version: 6.32.1
- Node.js version: 16.20.1
- sqlite3 version: 5.1.6

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [x] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by skypesky** [comment]
same problem

**Comment by skypesky** [comment]
I want to replace prisma, when using sequelize, the previous time field saves the value as a number, which is a timestamp.

When date is a number in sqlite, sequelize doesn't work when querying the records, this is solved by the following code, hopefully this problem can be fixed.


```ts
  class DATE extends BaseTypes.DATE {
    static parse(date, options) {
      // track: https://github.com/sequelize/sequelize/issues/16340
      if (typeof data === 'string' && !date.includes('+')) {
        return new Date(date + options.timezone);
      }
      return new Date(date);
    }
  }
```

**Comment by skypesky** [comment]
@jlherren 

If you don't want to wait a long time for an official fix, I've released a fixed version that you can install and try to see if it works.

@see npm: https://www.npmjs.com/package/skypesky-sequelize
@see github: https://github.com/skypesky/sequelize-patch
