### ISSUE TITLE
FindAll hasMany include at second level nested fail to Cannot read properties of undefined

### ISSUE THREAD

**Issue by limac3** [sequelize/sequelize#16436]
## Issue Creation Checklist

- [x] I understand that my issue will be automatically closed if I don't fill in the requested information
- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

When use findAll method in a model that have nested second level includes hasMany fail to query getting an error:
~~~
TypeError: Cannot read properties of undefined (reading 'ContentUsers')
~~~
At final example I include a temporary solution

### Reproducible Example

~~~
const { Sequelize, Model, DataTypes: Types } = require("sequelize");
const env = process.env.NODE_ENV || "development";
const config_file = require("./database/config/config.js");
const config = config_file[env];
const sequelize = new Sequelize(
  config.database,
  config.username,
  config.password,
  config
);
class Content extends Model {}
class ContentUser extends Model {}
class RelatedContent extends Model {}
Content.init(
  {
    content_id: { type: Types.INTEGER, primaryKey: true, autoIncrement: true },
    content_status_id: {
      type: Types.INTEGER,
      allowNull: false,
    },
  },
  {
    sequelize,
    schema: "llta",
    modelName: "Content",
    tableName: "content",
    createdAt: "created_at",
    updatedAt: "updated_at",
  }
);
ContentUser.init(
  {
    content_user_id: { type: Types.INTEGER, primaryKey: true },
    content_id: { type: Types.INTEGER, allowNull: false },
    user_id: { type: Types.INTEGER, allowNull: false },
    taken_status: { type: Types.INTEGER, allowNull: false },
  },
  {
    sequelize,
    schema: "llta",
    modelName: "ContentUser",
    tableName: "content_user",
    createdAt: "created_at",
    updatedAt: "updated_at",
  }
);
RelatedContent.init(
  {
    related_content_id: {
      type: Types.INTEGER,
      primaryKey: true,
      autoIncrement: true,
    },
    content_id: { type: Types.INTEGER, allowNull: false },
    content_parent_id: { type: Types.INTEGER, allowNull: false },
    is_related_content_path: {
      type: Types.BOOLEAN,
      allowNull: false,
      defaultValue: false,
    },
    related_content_order: Types.INTEGER,
  },
  {
    sequelize,
    schema: "llta",
    modelName: "RelatedContent",
    tableName: "related_content",
    createdAt: "created_at",
    updatedAt: "updated_at",
  }
);
RelatedContent.belongsTo(Content, { as: "content", foreignKey: "content_id" });
Content.hasMany(ContentUser, { foreignKey: "content_id" });
const app = async () => {
  let related_path = [75, 76];
  let rpath = await RelatedContent.findAll({
    where: { content_parent_id: related_path, is_related_content_path: true },
    attributes: ["content_parent_id"],
    include: [
      {
        model: Content,
        as: "content",
        where: { content_status_id: 5, content_type_id: 1 },
        attributes: [], // this line can be the problem, is you add an attribute, the query resolve
        //attributes: ["content_id"],
        include: [
          { model: ContentUser, attributes: ["user_id", "taken_status"] },
        ],
      },
    ],
  });
  if (rpath)
    rpath.map((r) => {
      let rr = r.toJSON();
      let data = {
        id: rr.content_parent_id,
        users: rr.content.ContentUsers,
      };
      console.log("Data:", data);
    });
  sequelize.close();
};
app();
~~~

#### Temporary solution:
I find a solution, adding an attribute to model previous in the query in this case to "Content" model.
If the line 84: "attributes: []" is modified like the line 85 (commented) "attributes: ['content_id']" adding an attribute in the include for the first level, the query resolve without errors

### What do you expect to happen?
 The findAll must to resolve the query in database, getting the data, in this example with console.log :
~~~
Executing (default): SELECT "RelatedContent"."related_content_id", "RelatedContent"."content_parent_id", "content"."content_id" AS "content.content_id", "content->ContentUsers"."content_user_id" AS "content.ContentUsers.content_user_id", "content->ContentUsers"."user_id" AS "content.ContentUsers.user_id", "content->ContentUsers"."taken_status" AS "content.ContentUsers.taken_status" FROM "llta"."related_content" AS "RelatedContent" INNER JOIN 
"llta"."content" AS "content" ON "RelatedContent"."content_id" = "content"."content_id" AND "content"."content_status_id" = 5 AND "content"."content_type_id" = 1 LEFT OUTER JOIN "llta"."content_user" AS "content->ContentUsers" ON "content"."content_id" = "content->ContentUsers"."content_id" WHERE "RelatedContent"."content_parent_id" IN (75, 76) AND "RelatedContent"."is_related_content_path" = true;
Data: { id: 75, users: [] }
Data: {
  id: 75,
  users: [
    { user_id: 3, taken_status: 1 },
    { user_id: 4, taken_status: 0 },
    { user_id: 24, taken_status: 0 },
    { user_id: 26, taken_status: 0 },
    { user_id: 34, taken_status: 1 },
    { user_id: 40, taken_status: 1 }
  ]
}
Data: {
  id: 75,
  users: [
    { user_id: 3, taken_status: 1 },
    { user_id: 4, taken_status: 0 },
    { user_id: 24, taken_status: 0 },
    { user_id: 33, taken_status: 0 },
    { user_id: 36, taken_status: 0 },
    { user_id: 40, taken_status: 1 }
  ]
}
Data: {
  id: 76,
  users: [
    { user_id: 3, taken_status: 1 },
    { user_id: 4, taken_status: 1 },
    { user_id: 24, taken_status: 1 },
    { user_id: 33, taken_status: 1 },
    { user_id: 34, taken_status: 1 },
    { user_id: 36, taken_status: 0 },
    { user_id: 39, taken_status: 1 },
    { user_id: 40, taken_status: 1 }
  ]
}
Data: {
  id: 76,
  users: [
    { user_id: 3, taken_status: 1 },
    { user_id: 33, taken_status: 1 },
    { user_id: 35, taken_status: 1 },
    { user_id: 38, taken_status: 1 },
    { user_id: 40, taken_status: 1 }
  ]
}
~~~

### What is actually happening?

~~~
Executing (default): SELECT "RelatedContent"."related_content_id", "RelatedContent"."content_parent_id", "content->ContentUsers"."content_user_id" AS "content.ContentUsers.content_user_id", "content->ContentUsers"."user_id" AS "content.ContentUsers.user_id", "content->ContentUsers"."taken_status" AS "content.ContentUsers.taken_status" FROM "llta"."related_content" AS "RelatedContent" INNER JOIN "llta"."content" AS "content" ON "RelatedContent"."content_id" = "content"."content_id" AND "content"."content_status_id" = 5 AND "content"."content_type_id" = 1 LEFT OUTER JOIN "llta"."content_user" AS "content->ContentUsers" ON "content"."content_id" = "content->ContentUsers"."content_id" WHERE "RelatedContent"."content_parent_id" IN (75, 76) AND "RelatedContent"."is_related_content_path" = true;
C:\Apps\node\icsmx-llta-websvc-gql\node_modules\sequelize\lib\dialects\abstract\query.js:527
            if (!$parent[$lastKeyPrefix]) {
                        ^

TypeError: Cannot read properties of undefined (reading 'ContentUsers')
    at AbstractQuery._groupJoinData (C:\Apps\node\node_modules\sequelize\lib\dialects\abstract\query.js:527:25)
    at Query.handleSelectQuery (C:\Apps\node\node_modules\sequelize\lib\dialects\abstract\query.js:211:31)
    at Query.run (C:\Apps\node\node_modules\sequelize\lib\dialects\postgres\query.js:157:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Apps\node\node_modules\sequelize\lib\sequelize.js:315:16
    at async PostgresQueryInterface.select (C:\Apps\node\node_modules\sequelize\lib\dialects\abstract\query-interface.js:407:12)
    at async RelatedContent.findAll (C:\Apps\node\node_modules\sequelize\lib\model.js:1140:21)
    at async app (C:\Apps\node\test17.js:76:15)

Node.js v18.13.0
~~~

### Environment

- Sequelize version: 6.32.1
- Node.js version: 18.13.0
- If TypeScript related: TypeScript version:
- Database & Version: PostgreSQL 15
- Connector library & Version: pg 8.8.0

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [x] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by bongster** [comment]
Hi. I also still got a similar issue. has any progress?
