### ISSUE TITLE
Sequelize query with PostgreSQL Prepared Transaction doesn't release database connection

### ISSUE THREAD

**Issue by Mamun724** [sequelize/sequelize#16459]
## Issue Creation Checklist

- [x] I understand that my issue will be automatically closed if I don't fill in the requested information
- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

We were in need of updating two PostgreSQL databases at the same time. That means if an update fails on a database the other database's update should also fail. We have described the scenario [here](https://github.com/sequelize/sequelize/discussions/15915#discussion-5071509).

Based on the scenario @ephys helped us to achieve that under [this reply](https://github.com/sequelize/sequelize/discussions/15915#discussioncomment-5580088). The solution was working as expected. Thanks to @ephys for the solution.

Recently we have found that our system is getting the SequelizeConnectionAcquireTimeoutError after 5 invocations of the code snippet from [the reply](https://github.com/sequelize/sequelize/discussions/15915#discussioncomment-5580088). After some investigation, we have found that the connection created by Sequelize to execute the Prepared Transaction statements was not closed automatically. We have also not found any way to close the connection manually. We were using the default connection pool settings provided by Sequelize.

### Reproducible Example

[Here](https://github.com/Mamun724/SequelizeConnectionAcquireTimeoutError-in-Sequelize-with-prepared-transaction) is the link to the SSCCE for this issue. Please update the database URLs in the .env file at the root before testing.

### What do you expect to happen?

I want to perform as many prepared transactions as possible without restarting the Node.js process. In other words, the connection to the database should be automatically(or manually) closed after the transactions are completed with success or failure.

### What is actually happening?

After the execution of the transactions, the connections opened to the first database(the database with prepared transaction), are not getting released back to the connection pool of Sequelize.

Stack Trace(here **some-path** is used to obfuscate an absolute path):
```
ConnectionAcquireTimeoutError [SequelizeConnectionAcquireTimeoutError]: Operation timeout
    at ConnectionManager.getConnection (some-path\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:206:15)
    at async some-path\node_modules\sequelize\lib\sequelize.js:305:26
    at async PostgresQueryInterface.select (some-path\node_modules\sequelize\lib\dialects\abstract\query-interface.js:407:12)
    at async Function.findAll (some-path\node_modules\sequelize\lib\model.js:1140:21)     
    at async verifyInsert (some-path\index.js:86:17)
    at async main (some-path\index.js:98:5) {
  parent: TimeoutError: Operation timeout
      at Timeout.<anonymous> (some-path\node_modules\sequelize-pool\lib\Deferred.js:17:25)      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7),
  original: TimeoutError: Operation timeout
      at Timeout.<anonymous> (some-path\node_modules\sequelize-pool\lib\Deferred.js:17:25)      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)
```

### Environment

- Sequelize version: 6.32.1
- Node.js version: v16.20.1
- If TypeScript related: TypeScript version: not used
- Database & Version: PostgreSQL 14
- Connector library & Version: pg@8.11.3

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [ ] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by askzhangbo** [comment]
Has this issue been addressed?

**Comment by ephys** [comment]
Considering it's basically the same issue, I'll close in favor of #16480
