### ISSUE TITLE
Sequelize 7 should allow models to be registered on another instance when the original instance has been closed

### ISSUE THREAD

**Issue by kenrick95** [sequelize/sequelize#16483]
## Issue Creation Checklist

- [x] I understand that my issue will be automatically closed if I don't fill in the requested information
- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

https://github.com/sequelize/sequelize/issues/15389 blocks from registering a model on another instance even if the original instance has been closed.

The use case I have is that I have a service that has dynamic config listener so I could change the database connection credentials on runtime. To achieve this, I would close the db connection and then re-initialize db connection with the new config. However, at this point, I couldn't do so since I will be blocked by this error:

```
Error: Model Configuration has already been initialized. Models can only belong to one Sequelize instance. Registering the same model with multiple Sequelize instances is not yet supported. Please see https://github.com/sequelize/sequelize/issues/15389
    at registerModelDefinition (/node_modules/.pnpm/@sequelize+core@7.0.0-alpha.27_mysql2@3.6.0/node_modules/@sequelize/core/lib/model-definition.js:625:11)
    at initModel (/node_modules/.pnpm/@sequelize+core@7.0.0-alpha.27_mysql2@3.6.0/node_modules/@sequelize/core/lib/model-typescript.js:326:55)
    at initDecoratedModel (/node_modules/.pnpm/@sequelize+core@7.0.0-alpha.27_mysql2@3.6.0/node_modules/@sequelize/core/lib/decorators/shared/model.js:108:41)
    at /node_modules/.pnpm/@sequelize+core@7.0.0-alpha.27_mysql2@3.6.0/node_modules/@sequelize/core/lib/sequelize-typescript.js:119:91
    at Array.filter (<anonymous>)
    at DbClient.addModels (/node_modules/.pnpm/@sequelize+core@7.0.0-alpha.27_mysql2@3.6.0/node_modules/@sequelize/core/lib/sequelize-typescript.js:119:37)
```

Perhaps when `sequelize.close()` is called, it should remove the related models from `model-definition.ts`'s `modelDefinitions` weakmap?

### Reproducible Example

Here is the link to the SSCCE for this issue: https://github.com/kenrick95/sequelize-sscce-model-reuse

PR for the CI run here: https://github.com/sequelize/sequelize-sscce/pull/263

### What do you expect to happen?

Model can be registered on another Sequelize instance when the original Sequelize instance has been closed.

### What is actually happening?

Model cannot be registered on another Sequelize instance when the original Sequelize instance has been closed.

### Environment

- Sequelize version: 7.0.0-alpha.27
- Node.js version: 16.20.1
- If TypeScript related: TypeScript version: 5.1.3
- Database & Version: mysql 5.7.29
- Connector library & Version: mysql2@3.6.0

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [ ] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by ephys** [comment]
Unfortunately there are too many unknowns to easily disable this safeguard. Too many things rely on the Sequelize instance once models are initialized. We're slowly working on cleanly separating concepts but by the time we're done, #15389 will basically be ready

What I can recommend, if what you need is limited to changing the credentials, would be to update the configuration passed to the `beforeConnect` hook. Here is another thread that talks about this: https://github.com/sequelize/sequelize/issues/14136#issuecomment-1076492372

You can also kill all connections by calling `sequelize.connectionManager.pool.destroyAllNow()`, instead of closing Sequelize itself.

**Comment by ephys** [comment]
Considering the above message, I will be closing this issue

**Comment by ephys** [comment]
Following PR #17077, you should be able to register a model again after calling the upcoming `sequelize.removeAllModels()` method.

I have to warn however that even though a lot of work has gone into making the `ModelDefinition` class the source of truth, I cannot currently guarantee you won't experience any weird behavior if you do this
