### ISSUE TITLE
ERROR: Please install sqlite3 package manually (again)

### ISSUE THREAD

**Issue by LunaticMuch** [sequelize/sequelize#16589]
## Issue Creation Checklist

- [X] I understand that my issue will be automatically closed if I don't fill in the requested information
- [X] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

In a simple default installation, sqlite3 support does not work, leading to some errors difficult/impossible do debug.
The issue has been reported in the past #11174 with a set of workarounds, which not even worked in all cases. 
In my case, it fails as included into a NextJS v13 project. I do not find any reason for that other than Sequelize does not correctly use `sqlite3` library

### Reproducible Example

I have a test case on [codesandbox](https://codesandbox.io/p/github/LunaticMuch/upgraded-dollop/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cln8nvqj800073t6esrx9pz5h%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cln8nvqj800033t6ejrn8c7v0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cln8nvqj800053t6emkywm17w%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cln8nvqj800063t6ez7g2dhj6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cln8nvqj800033t6ejrn8c7v0%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cln8nvqj700023t6ecdyuyfdo%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cln8nvqj800033t6ejrn8c7v0%2522%252C%2522activeTabId%2522%253A%2522cln8nvqj700023t6ecdyuyfdo%2522%257D%252C%2522cln8nvqj800063t6ez7g2dhj6%2522%253A%257B%2522id%2522%253A%2522cln8nvqj800063t6ez7g2dhj6%2522%252C%2522activeTabId%2522%253A%2522cln8nw7wo00893t6ee1f3pd4z%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522cln8nw7wo00893t6ee1f3pd4z%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522cln8nvqj800053t6emkywm17w%2522%253A%257B%2522id%2522%253A%2522cln8nvqj800053t6emkywm17w%2522%252C%2522activeTabId%2522%253A%2522cln8nvqj800043t6epdy1j0ef%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cln8nvqj800043t6epdy1j0ef%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cln8nvqxz000ue7hp7ozvdlia%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cln8nw5ub006q3t6esrniqkl6%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) now - I am working towards an sscce one even though is not going to be exactly the same
,

### What do you expect to happen?

Calling [this endpoint](http://localhost:3000/api/dummy?query=test), while running locally, should create a test user in a sqlite memory database

### What is actually happening?

The server returns `Error: Please install sqlite3 package manually` thrown this line

```
const sequelize = new Sequelize('sqlite::memory:');
```

The stack trace is the following

```
 ⨯ node_modules/sequelize/lib/dialects/abstract/connection-manager.js (55:14) @ ConnectionManager._loadDialectModule
 ⨯ Error: Please install sqlite3 package manually
    at ConnectionManager._loadDialectModule (webpack-internal:///(rsc)/./node_modules/sequelize/lib/dialects/abstract/connection-manager.js:55:23)
    at new ConnectionManager (webpack-internal:///(rsc)/./node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:18:25)
    at new SqliteDialect (webpack-internal:///(rsc)/./node_modules/sequelize/lib/dialects/sqlite/index.js:13:34)
    at new Sequelize (webpack-internal:///(rsc)/./node_modules/sequelize/lib/sequelize.js:200:24)
    at eval (webpack-internal:///(rsc)/./models/user.ts:6:19)
    at (rsc)/./models/user.ts (/Users/scislagh/_TEST/nextjs-sequelize/.next/server/app/api/dummy/route.js:194:1)
    at __webpack_require__ (/Users/scislagh/_TEST/nextjs-sequelize/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./app/api/dummy/route.ts:5:70)
    at (rsc)/./app/api/dummy/route.ts (/Users/scislagh/_TEST/nextjs-sequelize/.next/server/app/api/dummy/route.js:183:1)
    at __webpack_require__ (/Users/scislagh/_TEST/nextjs-sequelize/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fapi%2Fdummy%2Froute&page=%2Fapi%2Fdummy%2Froute&appPaths=&pagePath=private-next-app-dir%2Fapi%2Fdummy%2Froute.ts&appDir=%2FUsers%2Fscislagh%2F_TEST%2Fnextjs-sequelize%2Fapp&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&rootDir=%2FUsers%2Fscislagh%2F_TEST%2Fnextjs-sequelize&isDev=true&tsconfigPath=tsconfig.json&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!:16:118)
    at (rsc)/./node_modules/next/dist/build/webpack/loaders/next-app-loader.js?name=app%2Fapi%2Fdummy%2Froute&page=%2Fapi%2Fdummy%2Froute&appPaths=&pagePath=private-next-app-dir%2Fapi%2Fdummy%2Froute.ts&appDir=%2FUsers%2Fscislagh%2F_TEST%2Fnextjs-sequelize%2Fapp&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&rootDir=%2FUsers%2Fscislagh%2F_TEST%2Fnextjs-sequelize&isDev=true&tsconfigPath=tsconfig.json&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D! (/Users/scislagh/_TEST/nextjs-sequelize/.next/server/app/api/dummy/route.js:172:1)
    at __webpack_require__ (/Users/scislagh/_TEST/nextjs-sequelize/.next/server/webpack-runtime.js:33:43)
    at __webpack_exec__ (/Users/scislagh/_TEST/nextjs-sequelize/.next/server/app/api/dummy/route.js:204:39)
    at /Users/scislagh/_TEST/nextjs-sequelize/.next/server/app/api/dummy/route.js:205:637
    at __webpack_require__.X (/Users/scislagh/_TEST/nextjs-sequelize/.next/server/webpack-runtime.js:163:21)
    at /Users/scislagh/_TEST/nextjs-sequelize/.next/server/app/api/dummy/route.js:205:47
    at Object.<anonymous> (/Users/scislagh/_TEST/nextjs-sequelize/.next/server/app/api/dummy/route.js:208:3)
    at Module._compile (node:internal/modules/cjs/loader:1257:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1115:32)
    at Module._load (node:internal/modules/cjs/loader:962:12)
    at Module.require (node:internal/modules/cjs/loader:1139:19)
    at mod.require (/Users/scislagh/_TEST/nextjs-sequelize/node_modules/next/dist/server/require-hook.js:64:28)
    at require (node:internal/modules/helpers:121:18)
    at requirePage (/Users/scislagh/_TEST/nextjs-sequelize/node_modules/next/dist/server/require.js:109:84)
    at /Users/scislagh/_TEST/nextjs-sequelize/node_modules/next/dist/server/load-components.js:59:84
    at async loadComponentsImpl (/Users/scislagh/_TEST/nextjs-sequelize/node_modules/next/dist/server/load-components.js:59:26)
    at async DevServer.findPageComponentsImpl (/Users/scislagh/_TEST/nextjs-sequelize/node_modules/next/dist/server/next-server.js:438:36) {
  page: '/api/dummy'
```

### Environment

- Sequelize version: 6.33.0
- Node.js version: 20.3.1 
- If TypeScript related: TypeScript version:  5.2.2
- Database & Version: SQLite 5.1.6
- Connector library & Version: 

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [X] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by vatro** [comment]
Hi! I've just resolved this issue in my Next.js 13 app connecting to an IBM Db2 database using `"@sequelize/core": "^7.0.0-alpha.32"`, but the issue should be the same, since I was also getting the `Please install ibm_db package manually` error. Adding this to `next.config.js` did the trick:

```js
const nextConfig = {
  experimental: {
    serverComponentsExternalPackages: ['@sequelize/core'],
  },
}
```
You might also take a look at: [Next.js 13 `next.config.js` `serverComponentsExternalPackages` docs](https://nextjs.org/docs/app/api-reference/next-config-js/serverComponentsExternalPackages)

**Comment by LunaticMuch** [comment]
@vatro you are correct. That config item solves. For NextJS v13  + AppRouter + Sequelize v6 you need

```
const nextConfig = {
  experimental: {
    serverComponentsExternalPackages: ['sequelize'],
  },
}
```

**Comment by jasongalvin** [comment]
For NextJS v15:

```javascript
const nextConfig = {
  serverExternalPackages: ['sequelize'],
}
```
