### ISSUE TITLE
Got invalid value when the data query is work (checked on ssms)

### ISSUE THREAD

**Issue by alfi-dim** [sequelize/sequelize#16591]
### Discussed in https://github.com/sequelize/sequelize/discussions/16590

<div type='discussions-op-text'>

<sup>Originally posted by **alfi-dim** October  2, 2023</sup>
need help, got Invalid value when do findOne by name (my dialect is mssql)
```
const data = await this.roleModel.findOne({
      where: {
        name: {
          [Op.substring]: name,
        },
      },
    });
```

i've check the query myself using ssms based on sequelize log, and it sure return the correct data
`Executing (default): SELECT [id], [name] FROM [roles] AS [roles] WHERE [roles].[name] LIKE N'%Store Manager%' ORDER BY [roles].[id] OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY;
`

this is my full error log
```
Error: Invalid value roles {
  dataValues: { id: 'roles-0001', name: 'Store Manager' },
  _previousDataValues: { id: 'roles-0001', name: 'Store Manager' },
  uniqno: 1,
  _changed: Set(0) {},
  _options: {
    isNewRecord: false,
    _schema: null,
    _schemaDelimiter: '',
    raw: true,
    attributes: [Array]
  },
  isNewRecord: false
}
    at Object.escape (D:\Belajar\BISA_API\node_modules\sequelize\lib\sql-string.js:53:11)
    at MSSQLQueryGenerator.escape (D:\Belajar\BISA_API\node_modules\sequelize\lib\dialects\abstract\query-generator.js:763:22)
    at MSSQLQueryGenerator.whereItemQuery (D:\Belajar\BISA_API\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1821:102)
    at D:\Belajar\BISA_API\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1734:25
    at Array.forEach (<anonymous>)
    at MSSQLQueryGenerator.whereItemsQuery (D:\Belajar\BISA_API\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1732:35)
    at MSSQLQueryGenerator.getWhereConditions (D:\Belajar\BISA_API\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2075:19)
    at MSSQLQueryGenerator.selectQuery (D:\Belajar\BISA_API\node_modules\sequelize\lib\dialects\abstract\query-generator.js:988:28)
    at MSSqlQueryInterface.select (D:\Belajar\BISA_API\node_modules\sequelize\lib\dialects\abstract\query-interface.js:407:59)
    at access_controls.findAll (D:\Belajar\BISA_API\node_modules\sequelize\lib\model.js:1140:47)

```
please help me, and thanks in advance</div>

**Comment by ephys** [comment]
Continuing in https://github.com/sequelize/sequelize/discussions/16590 to avoid duplicates
