### ISSUE TITLE
#initializeTTLTracking() Unexpected token '('

### ISSUE THREAD

**Issue by EyuphanMandiraci** [sequelize/sequelize#16723]
Hello i got this error in startup.
`root@sinanisler:/var/www/eyuphanmandiraci.com# npm start

> eyuphanmandiraci.com@1.0.0 start
> node ./bin/www

/var/www/eyuphanmandiraci.com/node_modules/mysql2/node_modules/lru-cache/dist/cj                                                                                                                                   s/index.js:359
    #initializeTTLTracking() {
                          ^

SyntaxError: Unexpected token '('
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/var/www/eyuphanmandiraci.com/node_modules/mysql2/nod                                                                                                                                   e_modules/lru-cache/dist/cjs/index-cjs.js:5:36)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
`

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by clmn386** [comment]
hi use: npm i mysql2@2.3.3
;)

**Comment by RAISEMEUP007** [comment]
> hi use: npm i mysql2@2.3.3 ;)

Thank you very much @clmn386

**Comment by ephys** [comment]
This means your node version does not support private class methods, which were added in node 14.6.0

**Comment by rbuzeta** [comment]
Same problem with node v20.11.0. It doesn't seem to be the version of node

**Comment by pablo-lopes-smava** [comment]
> This likely means your node version does not support private class methods, which were added in node 14.6.0

For me, upgrading to the node v14 solved the issue. Thanks!
