### ISSUE TITLE
BelongsToMany stops working after closing a connection and redefining with a new Sequelize instance: ConnectionManager.getConnection() was called after the connection manager was closed

### ISSUE THREAD

**Issue by ilmiont** [sequelize/sequelize#16755]
## Bug Description

I am developing a desktop app that works with SQLite files on the user's machine. One SQLite file is open at a time. In common with other desktop apps, the user should be able to "Close" the file, then "Open" another one in the same app session. A different physical file is being referenced, but the same Sequelize Models are used (the database schema is the same for all files the user will open).

I believe this should be possible by closing the first Sequelize connection, creating a new Sequelize instance that's connected to the second file, and redefining the Models to reference the second Sequelize instance.

However, `BelongsToMany` relationships are not getting redefined correctly. When `set<BelongsToMany>` is called on a model, Sequelize throws a `ConnectionManager.getConnection() was called after the connection manager was closed!` error.

The following example demonstrates the problem.

### Reproducible Example

```javascript
const {DataTypes, Model, Sequelize} = require("sequelize");

class User extends Model {}

class Team extends Model {}


async function initModels(sequelize) {

	User.init(
		{
			UserName: {
				type: DataTypes.STRING,
				allowNull: false
			}
		},
		{
			sequelize,
			modelName: "User"
		}
	);



	Team.init(
		{
			TeamName: {
				type: DataTypes.STRING,
				allowNull: false
			}
		},
		{
			sequelize,
			modelName: "Team"
		}
	);


	const UsersTeams = sequelize.define(
		`UsersTeams`,
		{
			"UserId": {
				type: DataTypes.INTEGER,
				references: {
					model: User,
					key: "id"
				}
			},
			"TeamId": {
				type: DataTypes.INTEGER,
				references: {
					model: Team,
					key: "id"
				}
			}
		},
		{
			freezeTableName: true
		}
	);


	User.belongsToMany(Team, {through: UsersTeams});
	Team.belongsToMany(User, {through: UsersTeams});


	await sequelize.sync();

}


(async function main() {


	let sequelize;


	/** FIRST CONNECTION */


	sequelize = new Sequelize({
		dialect: "sqlite",
		storage: "db1.sqlite"
	});

	await initModels(sequelize);

	const user1 = await User.create({UserName: "Test User (DB 1)"});
	const team1 = await Team.create({TeamName: "Test Team (DB 1)"});
	await user1.setTeams([team1]);

	await sequelize.close();
	sequelize = null;


	/** SECOND CONNECTION */


	sequelize = new Sequelize({
		dialect: "sqlite",
		storage: "db2.sqlite"
	});

	await initModels(sequelize);

	const user2 = await User.create({UserName: "Test User (DB 2)"});
	const team2 = await Team.create({TeamName: "Test Team (DB 2)"});
	await user2.setTeams([team2]);

	await sequelize.close();
	sequelize = null;


})();

```

### What do you expect to happen?

- The script should run to completion without any errors.
- Everything under "First Connection" should write to `db1.sqlite`.
- Everything under "Second Connection" should write to `db2.sqlite`.

### What is actually happening?

The script crashes on line 108 with the following stack trace:

```
Error: ConnectionManager.getConnection was called after the connection manager was closed!
    at ConnectionManager.getConnection (/home/james/@scratch/sequelize-bug-test/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:70:13)
    at /home/james/@scratch/sequelize-bug-test/node_modules/sequelize/lib/sequelize.js:305:111
    at /home/james/@scratch/sequelize-bug-test/node_modules/retry-as-promised/dist/index.js:59:25
    at new Promise (<anonymous>)
    at retryAsPromised (/home/james/@scratch/sequelize-bug-test/node_modules/retry-as-promised/dist/index.js:48:12)
    at Sequelize.query (/home/james/@scratch/sequelize-bug-test/node_modules/sequelize/lib/sequelize.js:300:12)
    at SQLiteQueryInterface.select (/home/james/@scratch/sequelize-bug-test/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:33)
    at Function.findAll (/home/james/@scratch/sequelize-bug-test/node_modules/sequelize/lib/model.js:1140:47)
    at async BelongsToMany.set (/home/james/@scratch/sequelize-bug-test/node_modules/sequelize/lib/associations/belongs-to-many.js:451:27)
    at async main (/home/james/@scratch/sequelize-bug-test/sequelize.js:108:2)
```

### Environment

- Sequelize version: 6.35.0 (also reproduced in 7.0.0-alpha.9)
- Node.js version: v18
- Database & Version: SQLite
- Connector library & Version: `sqlite3` (also reproduced in `@journeyapps/sqlcipher` which I'm usually in the real app)

## Would you be willing to resolve this issue by submitting a Pull Request?

(In theory, yes; I have already spent a lot of time reading the source trying to investigate what's happening, but I haven't succeeded in understanding the relevant areas.)

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [ ] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by ephys** [comment]
You can't reassign a model to another Sequelize instance. The newer alpha throw an error if you try to do that.

What can be done however is:
- Making it possible to change the credentials used by sqlite by unifying sqlite connections with the other dialects (make it use the pool but limit the pool's size to 1, so you can tell the pool to close all connections then change the DB path in `beforeConnect`)
- Wait for #15389 (will be a while, but we're working on it)
- Recreate all models every time you create a new instance
