### ISSUE TITLE
The utf8mb4 is not working

### ISSUE THREAD

**Issue by arshidkv12** [sequelize/sequelize#16827]
## Bug Description

The utf8mb4 is not working. I can not insert emojis. It is working with localhost. But the remote connection has a bug.

### Reproducible Example

 Set the remote server as follows. 
https://i.imgur.com/Ktx8flD.png

Then execute the following code.

```
const sequelize = new Sequelize( config.DB_DATABASE, config.DB_USERNAME, config.DB_PASSWORD, {
    host: config.DB_HOST,
    dialect: 'mysql',
    logging: false, 
    keepDefaultTimezone: true,
    timezone: dayjs().format('Z'),
    define: {
      timestamps: false, 
        charset: 'utf8mb4',      
    }
  });

sequelize.query(
    "INSERT INTO emails (`subject`)  VALUES ($subject);", { 
      bind: { 
        from: 'subject test👌'
      },
      type: QueryTypes.INSERT
     });
```

### What do you expect to happen?

I want to insert emoji in the **MySQL** database.

### What is actually happening?

The emoji is stored as ???. 
 
### Environment

 

- Sequelize version: **6.35.1**
- Node.js version: 16.14.2
- Database & Version: 10.3.39-MariaDB-cll-lve 
- Connector library & Version: MYSQL2 3.6.5
 

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by arshidkv12** [comment]
Sorry... I am confused. 
I can see the following outputs from packets. 
*this.handshake* value is *cesu8* from `mysql2/lib/commands/client_handshake.js` file.

**Comment by WikiRik** [comment]
Ah, I was looking at the creation of the database but not at the actual insert. I'll do some more tests later.
cesu8 from these is a converted version of utf8 indeed and not the wanted utf8mb4 (which they do have mapping for in https://github.com/sidorares/node-mysql2/blob/master/tools/generate-charset-mapping.js unless they do a double mapping for some reason)

**Comment by WikiRik** [comment]
Can you try this;
```
const sequelize = new Sequelize( config.DB_DATABASE, config.DB_USERNAME, config.DB_PASSWORD, {
    host: config.DB_HOST,
    dialect: 'mysql',
    logging: false, 
    keepDefaultTimezone: true,
    timezone: dayjs().format('Z'),
    define: {
      timestamps: false, 
      dialectOptions: {
        charset: 'utf8mb4',
      }
    }
  });
```

**Comment by arshidkv12** [comment]
> Can you try this;
> 
> ```
> const sequelize = new Sequelize( config.DB_DATABASE, config.DB_USERNAME, config.DB_PASSWORD, {
>     host: config.DB_HOST,
>     dialect: 'mysql',
>     logging: false, 
>     keepDefaultTimezone: true,
>     timezone: dayjs().format('Z'),
>     define: {
>       timestamps: false, 
>       dialectOptions: {
>         charset: 'utf8mb4',
>       }
>     }
>   });
> ```

Sorry.. it is not working.

**Comment by arshidkv12** [comment]
It is working if I add the following code (each time).

connection.query("SET CHARACTER SET utf8mb4");
connection.query(
  'INSERT INTO emails ( `subject` )   VALUES (" subject 👋" );',
);

**Comment by WikiRik** [comment]
Yup, we're not setting the property correctly when we open a new connection with MySQL. I was hoping that the dialectOptions would fix it, but I need to take a proper look to see what happens and how we can fix it

**Comment by ephys** [comment]
`dialectOptions` doesn't go in `define`, that's for setting defaults for model definitions

Try moving it to the top level:

```
const sequelize = new Sequelize({
  dialectOptions: { // here
    charset: 'utf8mb4',
  },
});
```

**Comment by arshidkv12** [comment]
Sorry... It is not working.

**Comment by lohart13** [comment]
Just a quick comment on this, I've run a quick demo, and it is working perfectly with the `charset` set in the `define` options of the sequelize instance.

Looking at your code example, your named bind parameters doesn't match up. You have a named bind parameter in the query called `subject` however in the bind options you only have `from`.

Please try the below code and see how you get on.

```typescript
const sequelize = new Sequelize(config.DB_DATABASE, config.DB_USERNAME, config.DB_PASSWORD, {
  host: config.DB_HOST,
  dialect: 'mysql',
  logging: false,
  keepDefaultTimezone: true,
  timezone: dayjs().format('Z'),
  define: {
    timestamps: false,
    charset: 'utf8mb4',
  },
});

await sequelize.query(
  'INSERT INTO emails (`subject`) VALUES ($subject);', {
    bind: {
      subject: 'subject test👌',
    },
    type: QueryTypes.INSERT,
  },
);
```

If this doesn't work, please share the code used to create the table/model.

**Comment by arshidkv12** [comment]
Please check it ![https://i.imgur.com/NWo5lTr.png](https://i.imgur.com/NWo5lTr.png)
 
 I manually created the table by phpmyadmin.
I am connecting to a remote database (Shared host)

I tried as bellow code but not working 

```nodejs
const sequelize = new Sequelize(config.DB_DATABASE, config.DB_USERNAME, config.DB_PASSWORD, {
  host: config.DB_HOST,
  dialect: 'mysql',
  logging: false,
  keepDefaultTimezone: true,
  timezone: dayjs().format('Z'),
  define: {
    timestamps: false,
    charset: 'utf8mb4',
  },
});

await sequelize.query(
  'INSERT INTO emails (`subject`) VALUES ($subject);', {
    bind: {
      subject: 'subject test👌',
    },
    type: QueryTypes.INSERT,
  },
);```

**Comment by lohart13** [comment]
Ok, have you built a sequelize model for the database or are you just using the `query` method to interact with the database from sequelize?

Can you enable logging and set `logQueryParameters` to true in the sequelize instance and share the output, see example below.

```ts
const sequelize = new Sequelize(config.DB_DATABASE, config.DB_USERNAME, config.DB_PASSWORD, {
  host: config.DB_HOST,
  dialect: 'mysql',
  logging: console.debug,
  logQueryParameters: true,
  keepDefaultTimezone: true,
  timezone: dayjs().format('Z'),
  define: {
    timestamps: false,
    charset: 'utf8mb4',
  },
  dialectOptions: {
    charset: 'utf8mb4',
  },
});
```

**Comment by arshidkv12** [comment]
Sorry.. not working. 

It inserted as `subject test????`.
![img](https://i.imgur.com/O5FacHU.png)

Log
```bash
Executing (default): INSERT INTO emails (`from`, `to`, `header`, `raw`, `attachments`, `subject`, `body`, `inbox_id`, `read`,  `created_at`, `updated_at`)      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?); " text", " text", "JSON.stringify(header)", "uuid", "[]", "subject test👌", " text", 1, false, "2024-02-09 03:15:27", "2024-02-09 03:15:27" {
  plain: false,
  raw: true,
  logging: [Function: debug],
  showWarnings: false,
  bind: {
    from: 'parsed.from.text',
    to: 'parsed.to.text',
    header: 'JSON.stringify(header)',
    raw: 'uuid',
    attachments: '[]',
    subject: 'subject test👌',
    body: ' text',
    inbox_id: 1,
    read: false,
    created_at: '2024-02-09 03:15:27',
    updated_at: '2024-02-09 03:15:27'
  },
  type: 'INSERT'
}
```

**Comment by lohart13** [comment]
Looking at the data in the issue with the packages and version you appear to be using the `mysql2` package for the MariaDB database.
Can you please try switching to the `mariadb` package and see if this resolves the issue.
You'll need to change the sequelize instance to be:

```ts
const sequelize = new Sequelize(config.DB_DATABASE, config.DB_USERNAME, config.DB_PASSWORD, {
  host: config.DB_HOST,
  dialect: 'mariadb',
  logging: console.debug,
  logQueryParameters: true,
  keepDefaultTimezone: true,
  timezone: dayjs().format('Z'),
  define: {
    timestamps: false,
    charset: 'utf8mb4',
  },
  dialectOptions: {
    charset: 'utf8mb4',
  },
});
```

**Comment by arshidkv12** [comment]
Error

```nodejs
dialects/mariadb/connection-manager.js:100
          throw new SequelizeErrors.ConnectionError(err);
                ^

ConnectionError [SequelizeConnectionError]: (conn=87433581, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1003ms
    at ConnectionManager.connect (/Users/arshid/Downloads/email-server/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:100:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ConnectionManager._connect (/Users/arshid/Downloads/email-server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
    at async /Users/arshid/Downloads/email-server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32
    at async ConnectionManager.getConnection (/Users/arshid/Downloads/email-server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)
    at async /Users/arshid/Downloads/email-server/node_modules/sequelize/lib/sequelize.js:305:26 {
  parent: SqlError: (conn=87433581, no: 45012, SQLState: 08S01) Connection timeout: failed to create socket after 1003ms
      at Object.module.exports.createFatalError (/Users/arshid/Downloads/email-server/node_modules/mariadb/lib/misc/errors.js:88:10)
      at Connection.connectTimeoutReached (/Users/arshid/Downloads/email-server/node_modules/mariadb/lib/connection.js:1033:24)
      at listOnTimeout (node:internal/timers:561:11)
      at processTimers (node:internal/timers:502:7)
   From event:
      at /Users/arshid/Downloads/email-server/node_modules/mariadb/lib/connection.js:141:13
      at new Promise (<anonymous>)
      at Connection.connect (/Users/arshid/Downloads/email-server/node_modules/mariadb/lib/connection.js:130:12)
      at Object.createConnection (/Users/arshid/Downloads/email-server/node_modules/mariadb/promise.js:38:17)
      at ConnectionManager.connect (/Users/arshid/Downloads/email-server/node_modules/sequelize/lib/dialects/mariadb/connection-manager.js:71:41)
      at ConnectionManager._connect (/Users/arshid/Downloads/email-server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:61)
      at async /Users/arshid/Downloads/email-server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32
      at async ConnectionManager.getConnection (/Users/arshid/Downloads/email-server/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)
      at async /Users/arshid/Downloads/email-server/node_modules/sequelize/lib/sequelize.js:305:26 {
    sqlMessage: 'Connection timeout: failed to create socket after 1003ms',
    sql: null,
    fatal: true,
    errno: 45012,
    sqlState: '08S01',
    code: 'ER_CONNECTION_TIMEOUT'
  },
```

**Comment by lohart13** [comment]
Ok, try increasing the connection and socket timeouts, for example:
```ts
const sequelize = new Sequelize(config.DB_DATABASE, config.DB_USERNAME, config.DB_PASSWORD, {
  host: config.DB_HOST,
  dialect: 'mariadb',
  logging: console.debug,
  logQueryParameters: true,
  keepDefaultTimezone: true,
  timezone: dayjs().format('Z'),
  define: {
    timestamps: false,
    charset: 'utf8mb4',
  },
  dialectOptions: {
    charset: 'utf8mb4',
    connectTimeout: 10000,
    socketTimeout: 10000,
  },
});
```

**Comment by arshidkv12** [comment]
It is saving `subject test????` :(

**Comment by lohart13** [comment]
Something else to try, can you see if changing to the alpha version of sequelize helps (`@sequelize/core`).
I'd recommend uninstalling the `sequelize` package while testing.
Please note, you'll need to update all uses of `sequelize` with `@sequelize/core`.

**Comment by arshidkv12** [comment]
Please check it https://github.com/sidorares/node-mysql2/issues/2303

**Comment by japson** [comment]
My connection settings:
`const Sequelize = require("sequelize");
const sequelize = new Sequelize(dbConfig.DB, dbConfig.USER, dbConfig.PASSWORD, {
  host: dbConfig.HOST,
  dialect: dbConfig.dialect,
  operatorsAliases: false,

define: {
    timestamps: false,
    charset: 'utf8mb4',
  },
  dialectOptions: {
      charset: 'utf8mb4'
    }
    });

const db = {};

db.Sequelize = Sequelize;
db.sequelize = sequelize;

db.sequelize.query("SET NAMES utf8mb4;");
db.sequelize.query("SET CHARSET utf8mb4;");

module.exports = db;
`
It's work.

**Comment by arshidkv12** [comment]
I want execute `sequelize.query("SET NAMES utf8mb4;");` before each query. It has performance issues.

**Comment by japson** [comment]
**alternative solution**
It is possible to solve the problem on the frontend.
Convert emoji to code before writing to the database (**codePointAt**):
```
str.replace(
            /\p{Emoji_Presentation}/gu,
            char => `\\u{${char.codePointAt(0).toString(16)}}`
        );  
//\u{1f61c} dgdf g \u{1f9b4} gdfgdf \u{1f631}
```
Convert code to emoji before publishing (**fromCodePoint**):
```
const regex=/(\\u{)(\w*)(})/gm;
         return str.replace(
             regex,function(match,p1, p2){return String.fromCodePoint(parseInt(p2, 16))}
// 😜 dgdf g 🦴 gdfgdf 😱
```

**Comment by gazhay** [comment]
Just hit this (or similar) in production.

Export table row by row as JSON from sequelize,
When you go to import that data into another identical database MySQL is throwing
```original: Error: Cannot create a JSON value from a string with CHARACTER SET 'binary'.```

Yet there is no binary data (all utf8) - both databases created by the sequelize code

**Comment by gazhay** [comment]
> Just hit this (or similar) in production.
> 
> Export table row by row as JSON from sequelize, When you go to import that data into another identical database MySQL is throwing `original: Error: Cannot create a JSON value from a string with CHARACTER SET 'binary'.`
> 
> Yet there is no binary data (all utf8) - both databases created by the sequelize code
> 
> Edit: FYI
> 
> ```
> original: Error: Cannot create a JSON value from a string with CHARACTER SET 'binary'.
>       at Packet.asError (/scratch/clubladder/node_modules/mysql2/lib/packets/packet.js:728:17)
>       at Execute.execute (/scratch/clubladder/node_modules/mysql2/lib/commands/command.js:29:26)
>       at Connection.handlePacket (/scratch/clubladder/node_modules/mysql2/lib/connection.js:489:32)
>       at PacketParser.onPacket (/scratch/clubladder/node_modules/mysql2/lib/connection.js:94:12)
>       at PacketParser.executeStart (/scratch/clubladder/node_modules/mysql2/lib/packet_parser.js:75:16)
>       at Socket.<anonymous> (/scratch/clubladder/node_modules/mysql2/lib/connection.js:101:25)
>       at Socket.emit (node:events:520:28)
>       at addChunk (node:internal/streams/readable:559:12)
>       at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
>       at Readable.push (node:internal/streams/readable:390:5) {
>     code: undefined,
>     errno: 3144,
>     sqlState: '22032',
>     sqlMessage: "Cannot create a JSON value from a string with CHARACTER SET 'binary'.",
>     sql: 'INSERT INTO `fixtures` (`id`,`flipped`,`homeTeam`,`homeTeamName`,`awayTeam`,`awayTeamName`,`date`,`status`,`fromChallenge`,`replacedBy`,`zwiftEventUrl`,`zwiftEventId`,`addedToZwiftPower`,`streamLinks`,`homeSignups`,`awaySignups`,`ineligibleSignups`,`preRaces`,`homeRoster`,`awayRoster`,`rosterDate`,`world`,`route`,`chosenWorld`,`chosenRoute`,`chosenDistLap`,`chosenPU1`,`chosenPU2`,`zwiftDirectData`,`specialExtras`,`eventAddedTime`,`eventAddedBy`,`sentEmailFlag`,`sentEmailId`,`seenReply`,`guessZwiftId`,`routeId`,`owner`,`zwiftName`,`zwiftDistance`,`zwiftElevation`,`zwiftNumLaps`,`zwiftDuration`,`scoreMethod`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);',
>     parameters: [
>       24,
>       false,
>       19,
>       'ESCO Fiendtini',
>       31,
>       'Rhinos Ivory G1',
>       '2023-04-11 17:30:00',
>       3,
>       38,
>       19,
>       'Club Ladder ESCO Fiendtini v Rhinos Ivory G1    https://www.zwift.com/events/view/3653408',
>       3653408,
>       'No',
>       null,
>       '[64890,470190,1098217,1451274,3013595]',
>       '[52513,882956,1449102,4163979,4763334]',
>       '[]',
>       '{"away":[],"home":[],"other":[]}',
>       null,
>       null,
>       null,
>       'New York',
>       'Knickerbocker Reverse',
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       null,
>       false,
>       null,
>       null,
>       null,
>       2001106885,
>       0,
>       'Club Ladder ESCO Fiendtini v Rhinos Ivory G1 \n\n',
>       16800,
>       null,
>       null,
>       null,
>       null,
>       '2023-04-07 15:23:28',
>       '2024-05-26 11:44:05'
>     ]
>   },
> ```
> 
> From JSON
> 
> ```
> {"id":24,"flipped":false,"homeTeam":19,"homeTeamName":"ESCO Fiendtini","awayTeam":31,"awayTeamName":"Rhinos Ivory G1","date":"_date_2023-04-11T17:30:00.000Z","status":3,"fromChallenge":38,"replacedBy":19,"zwiftEventUrl":"Club Ladder ESCO Fiendtini v Rhinos Ivory G1    https://www.zwift.com/events/view/3653408","zwiftEventId":3653408,"addedToZwiftPower":"No","streamLinks":null,"homeSignups":"[64890,470190,1098217,1451274,3013595]","awaySignups":"[52513,882956,1449102,4163979,4763334]","ineligibleSignups":"[]","preRaces":{"away":[],"home":[],"other":[]},"homeRoster":null,"awayRoster":null,"rosterDate":null,"world":"New York","route":"Knickerbocker Reverse","chosenWorld":null,"chosenRoute":null,"chosenDistLap":null,"chosenPU1":null,"chosenPU2":null,"zwiftDirectData":null,"specialExtras":null,"eventAddedTime":null,"eventAddedBy":null,"sentEmailFlag":false,"sentEmailId":null,"seenReply":null,"guessZwiftId":null,"routeId":2001106885,"owner":0,"zwiftName":"Club Ladder ESCO Fiendtini v Rhinos Ivory G1 \n\n","zwiftDistance":16800,"zwiftElevation":null,"zwiftNumLaps":null,"zwiftDuration":null,"scoreMethod":null,"createdAt":"_date_2023-04-07T15:23:28.000Z","updatedAt":"_date_2023-07-21T07:18:40.000Z"}
> ```

For reference, If I make the SQL query by copying the logged query and pasting in the parameters, it works.

Seems it isn't the data but sequelize somewhere
