### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by dafyn** [sequelize/sequelize#16855]
Executing (default): SELECT 1+1 AS result
Connection to the database has been established successfully.
Executing (default): IF OBJECT_ID('[Users]', 'U') IS NOT NULL DROP TABLE [Users];
Executing (default): IF OBJECT_ID('[UserRoles]', 'U') IS NOT NULL DROP TABLE [UserRoles];
Unable to connect to the database: Error
    at Query.run (C:\Users\PinniSOFT\my-nodejs-project\node_modules\sequelize\lib\dialects\mssql\query.js:107:25)
    at C:\Users\PinniSOFT\my-nodejs-project\node_modules\sequelize\lib\sequelize.js:315:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MSSqlQueryInterface.dropTable (C:\Users\PinniSOFT\my-nodejs-project\node_modules\sequelize\lib\dialects\abstract\query-interface.js:111:5)
    at async UserRoles.drop (C:\Users\PinniSOFT\my-nodejs-project\node_modules\sequelize\lib\model.js:1007:12)
    at async Sequelize.drop (C:\Users\PinniSOFT\my-nodejs-project\node_modules\sequelize\lib\sequelize.js:429:9)
    at async Sequelize.sync (C:\Users\PinniSOFT\my-nodejs-project\node_modules\sequelize\lib\sequelize.js:366:7) {
  name: 'SequelizeDatabaseError',
  parent: RequestError: Could not drop object 'UserRoles' because it is referenced by a FOREIGN KEY constraint.
      at RequestTokenHandler.onErrorMessage (C:\Users\PinniSOFT\my-nodejs-project\node_modules\tedious\lib\token\handler.js:287:21)   
      at Readable.<anonymous> (C:\Users\PinniSOFT\my-nodejs-project\node_modules\tedious\lib\token\token-stream-parser.js:18:33)      
      at Readable.emit (node:events:514:28)
      at addChunk (node:internal/streams/readable:376:12)
      at readableAddChunk (node:internal/streams/readable:349:9)
      at Readable.push (node:internal/streams/readable:286:10)
      at next (node:internal/streams/from:98:31)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    code: 'EREQUEST',
    number: 3726,
    state: 1,
    class: 16,
    serverName: 'DESKTOP-0LMSKB4\\SQLEXPRESS',
    procName: '',
    lineNumber: 1,
    sql: "IF OBJECT_ID('[UserRoles]', 'U') IS NOT NULL DROP TABLE [UserRoles];",
    parameters: undefined
  },
  original: RequestError: Could not drop object 'UserRoles' because it is referenced by a FOREIGN KEY constraint.
      at RequestTokenHandler.onErrorMessage (C:\Users\PinniSOFT\my-nodejs-project\node_modules\tedious\lib\token\handler.js:287:21)   
      at Readable.<anonymous> (C:\Users\PinniSOFT\my-nodejs-project\node_modules\tedious\lib\token\token-stream-parser.js:18:33)      
      at Readable.emit (node:events:514:28)
      at addChunk (node:internal/streams/readable:376:12)
      at readableAddChunk (node:internal/streams/readable:349:9)
      at Readable.push (node:internal/streams/readable:286:10)
      at next (node:internal/streams/from:98:31)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    code: 'EREQUEST',
    number: 3726,
    state: 1,
    class: 16,
    serverName: 'DESKTOP-0LMSKB4\\SQLEXPRESS',
    procName: '',
    lineNumber: 1,
    parameters: undefined
  },
  sql: "IF OBJECT_ID('[UserRoles]', 'U') IS NOT NULL DROP TABLE [UserRoles];",
  parameters: {}
}
PS C:\Users\PinniSOFT\my-nodejs-project> node auth.js
Executing (default): SELECT 1+1 AS result
Connection to the database has been established successfully.
Unable to connect to the database: Error: Database "DBDemo" does not match sync match parameter "/_test$/"
    at Sequelize.sync (C:\Users\PinniSOFT\my-nodejs-project\node_modules\sequelize\lib\sequelize.js:359:15)
    at C:\Users\PinniSOFT\my-nodejs-project\auth.js:23:22
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
PS C:\Users\PinniSOFT\my-nodejs-project> node auth.js
Executing (default): SELECT 1+1 AS result
Connection to the database has been established successfully.
Executing (default): IF OBJECT_ID('[Users]', 'U') IS NOT NULL DROP TABLE [Users];        
Executing (default): IF OBJECT_ID('[UserRoles]', 'U') IS NOT NULL DROP TABLE [UserRoles];
Unable to connect to the database: Error
    at Query.run (C:\Users\PinniSOFT\my-nodejs-project\node_modules\sequelize\lib\dialects\mssql\query.js:107:25)
    at C:\Users\PinniSOFT\my-nodejs-project\node_modules\sequelize\lib\sequelize.js:315:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MSSqlQueryInterface.dropTable (C:\Users\PinniSOFT\my-nodejs-project\node_modules\sequelize\lib\dialects\abstract\query-interface.js:111:5)
    at async UserRoles.drop (C:\Users\PinniSOFT\my-nodejs-project\node_modules\sequelize\lib\model.js:1007:12)
    at async Sequelize.drop (C:\Users\PinniSOFT\my-nodejs-project\node_modules\sequelize\lib\sequelize.js:429:9)
    at async Sequelize.sync (C:\Users\PinniSOFT\my-nodejs-project\node_modules\sequelize\lib\sequelize.js:366:7) {
  name: 'SequelizeDatabaseError',
  parent: RequestError: Could not drop object 'UserRoles' because it is referenced by a FOREIGN KEY constraint.
      at RequestTokenHandler.onErrorMessage (C:\Users\PinniSOFT\my-nodejs-project\node_modules\tedious\lib\token\handler.js:287:21)   
      at Readable.<anonymous> (C:\Users\PinniSOFT\my-nodejs-project\node_modules\tedious\lib\token\token-stream-parser.js:18:33)      
      at Readable.emit (node:events:514:28)
      at addChunk (node:internal/streams/readable:376:12)
      at readableAddChunk (node:internal/streams/readable:349:9)
      at Readable.push (node:internal/streams/readable:286:10)
      at next (node:internal/streams/from:98:31)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    code: 'EREQUEST',
    number: 3726,
    state: 1,
    class: 16,
    serverName: 'DESKTOP-0LMSKB4\\SQLEXPRESS',
    procName: '',
    lineNumber: 1,
    sql: "IF OBJECT_ID('[UserRoles]', 'U') IS NOT NULL DROP TABLE [UserRoles];",
    parameters: undefined
  },
  original: RequestError: Could not drop object 'UserRoles' because it is referenced by a FOREIGN KEY constraint.
      at RequestTokenHandler.onErrorMessage (C:\Users\PinniSOFT\my-nodejs-project\node_modules\tedious\lib\token\handler.js:287:21)   
      at Readable.<anonymous> (C:\Users\PinniSOFT\my-nodejs-project\node_modules\tedious\lib\token\token-stream-parser.js:18:33)      
      at Readable.emit (node:events:514:28)
      at addChunk (node:internal/streams/readable:376:12)
      at readableAddChunk (node:internal/streams/readable:349:9)
      at Readable.push (node:internal/streams/readable:286:10)
      at next (node:internal/streams/from:98:31)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    code: 'EREQUEST',
    number: 3726,
    state: 1,
    class: 16,
    serverName: 'DESKTOP-0LMSKB4\\SQLEXPRESS',
    procName: '',
    lineNumber: 1,
    sql: "IF OBJECT_ID('[UserRoles]', 'U') IS NOT NULL DROP TABLE [UserRoles];",
    parameters: undefined
  },
  sql: "IF OBJECT_ID('[UserRoles]', 'U') IS NOT NULL DROP TABLE [UserRoles];",
  parameters: {}
}

**Comment by WikiRik** [comment]
Please use the provided issue template. You can update this issue and we can re open
