### ISSUE TITLE
Defining HasMany association failed

### ISSUE THREAD

**Issue by wguerram** [sequelize/sequelize#17074]
## Issue Creation Checklist

- [x] I understand that my issue will be automatically closed if I don't fill in the requested information
- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

Defining HasMany association "materials" from Product to ProductMaterial failed

### Reproducible Example

This is how i define the association

`@HasMany(() => ProductMaterial, /* foreign key */ 'productId')
  declare materials?: NonAttribute<ProductMaterial[]>;`

I'm currently using version 7.0.0-alpha.35.

sequelize.sync({alter: true}) 

works fine, but when I update to version 7.0.0-alpha.36

I get the error message Defining HasMany association "materials" from Product to ProductMaterial failed

I dropped the references manually in the database thinking that might be a conflict but I get the same error.

### What do you expect to happen?

Have sync() continue working as with version 7.0.0-alpha.35

### What is actually happening?

when I update to version 7.0.0-alpha.36

I get the error message Defining HasMany association "materials" from Product to ProductMaterial failed

The error is thrown when I instantiate new Sequelize(...params), before I run sync.

Loos like the error happens in this method

https://github.com/sequelize/sequelize/blob/c0915787d1458ec78f5de8df365dbc873ecd6620/packages/core/src/associations/helpers.ts#L174

This is the error i get

https://github.com/sequelize/sequelize/blob/c0915787d1458ec78f5de8df365dbc873ecd6620/packages/core/src/associations/helpers.ts#L225

### Environment

- Sequelize version: 7.0.0-alpha.36
- Node.js version: 20.10.0
- If TypeScript related: TypeScript version: 5.3.3
- Database & Version: postgresql:latest
- Connector library & Version: pg:8.11.3

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [x] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

*Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed.*

**Comment by ephys** [comment]
The error message normally includes a "cause" property that goes into more detail. Printing the cause may not be supported yet by the system you're using but you can catch the error and use console.dir on it to see it

If you can post it, we should be able to help more

**Comment by wguerram** [comment]
Hi, thanks for your reply. One hint, I'm making two associations to the same product table using two different fields, productId and productParentId, probably that's making the conflict.

here is the output of console.dir

`AssociationError [SequelizeAssociationError]: Defining HasMany association "materials" from Product to ProductMaterial failed
    at defineAssociation (/workspaces/my-app/node_modules/@sequelize/core/src/associations/helpers.ts:222:11)
    at Function.associate (/workspaces/my-app/node_modules/@sequelize/core/src/associations/has-many.ts:160:12)
    ... 2 lines matching cause stack trace ...
    at Sequelize (/workspaces/my-app/node_modules/@sequelize/core/src/sequelize.js:438:12)
    at initializeDbConnection (/workspaces/my-app/apps/api/src/config/db.config.ts:13:21)
    at Object.<anonymous> (/workspaces/my-app/apps/api/src/index.ts:29:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._compile (/workspaces/my-app/node_modules/esbuild-register/dist/node.js:2258:26)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10) {
  [cause]: AssociationError [SequelizeAssociationError]: The association "materials" needs to define the BelongsTo association "product" from ProductMaterial to Product,
  but that child association has already been defined as BelongsTo, to Product by this call:
  
  ProductMaterial.belongsTo(Product, {
    foreignKey: { name: 'productId' },
    as: 'product',
    hooks: false,
    name: { plural: 'products', singular: 'product' }
  })
  
  That association would be re-used if compatible, but it is incompatible because their options are not reconcilable:
  
  Options of the association to create:
  {
    as: 'product',
    foreignKey: { name: 'productParentId' },
    hooks: false,
    name: { plural: 'products', singular: 'product' }
  }
  
  Options of the existing association:
  {
    as: 'product',
    foreignKey: { name: 'productId' },
    hooks: false,
    name: { plural: 'products', singular: 'product' }
  }
      at assertAssociationUnique (/workspaces/my-app/node_modules/@sequelize/core/src/associations/helpers.ts:115:9)
      at defineAssociation (/workspaces/my-app/node_modules/@sequelize/core/src/associations/helpers.ts:202:3)
      at Function.associate (/workspaces/my-app/node_modules/@sequelize/core/src/associations/belongs-to.ts:247:12)
      at HasMany (/workspaces/my-app/node_modules/@sequelize/core/src/associations/has-many.ts:116:52)
      at <anonymous> (/workspaces/my-app/node_modules/@sequelize/core/src/associations/has-many.ts:178:14)
      at defineAssociation (/workspaces/my-app/node_modules/@sequelize/core/src/associations/helpers.ts:220:69)
      at Function.associate (/workspaces/my-app/node_modules/@sequelize/core/src/associations/has-many.ts:160:12)
      at initDecoratedAssociations (/workspaces/my-app/node_modules/@sequelize/core/src/decorators/legacy/associations.ts:139:28)
      at Sequelize.addModels (/workspaces/my-app/node_modules/@sequelize/core/src/sequelize-typescript.ts:285:7)
      at Sequelize (/workspaces/my-app/node_modules/@sequelize/core/src/sequelize.js:438:12)
}
2024-02-11 13:42:42:4242 error: Failed to connect to db: Defining HasMany association "materials" from Product to ProductMaterial failed`

**Comment by ephys** [comment]
Yep that's exactly what is causing the conflict

You're creating a `HasMany` association called `materials` that goes from `Product` to `ProductMaterial`

This association needs to create its inverse `BelongsTo` association that goes from `ProductMaterial` to `Product`, because `BelongsTo` association are the associations that actually control foreign keys.

It generates a default one based on the name of the target, so in this instance it named it `product`.

You already have an association called `product` that goes from `ProductMaterial` to `Product`, but it can't be reused by Sequelize because it uses a different foreign key.

It therefore needs to use a different name. To do this, you can use the `inverse` option in your `@HasMany` decorator, like this: https://sequelize.org/docs/v7/associations/has-one/#inverse-association

**Comment by wguerram** [comment]
@ephys you're awesome!!!

Thanks for your help, that did the trick 🙌
