### ISSUE TITLE
Where clause failed on second level nested include

### ISSUE THREAD

**Issue by mlegenhausen** [sequelize/sequelize#1718]
Following example:

``` js
var co = require('co');
var Sequelize = require('sequelize');

var sequelize = new Sequelize('sequelize-test', 'root', '');

var Parent = sequelize.define('Parent', {});
var Child1 = sequelize.define('Child1', {});
var Child2 = sequelize.define('Child2', {});

Parent.hasMany(Child1);
Child1.belongsTo(Parent);

Child1.hasMany(Child2);
Child2.belongsTo(Child1);

co(function* () {
    yield sequelize.sync({
        force: true
    });

    var parent = yield Parent.create();
    var child1 = yield Child1.create();
    var child2 = yield Child2.create();

    yield parent.addChild1(child1);
    yield child1.addChild2(child2);

    var result = yield Parent.find({
        attributes: ['id'], // Added for better query readability
        include: [
            {
                model: Child1,
                attributes: ['id'],
                include: [
                    {
                        model: Child2,
                        attributes: ['id'],
                        where: {
                            id: child2.id
                        }
                    }
                ]
            }
        ]
    });

    console.log(result);
})();
```

Which produces the following output:

```
Executing (default): INSERT INTO `Parents` (`id`,`createdAt`,`updatedAt`) VALUES (DEFAULT,'2014-05-07 08:44:29','2014-05-07 08:44:29');
Executing (default): INSERT INTO `Child1s` (`id`,`createdAt`,`updatedAt`) VALUES (DEFAULT,'2014-05-07 08:44:29','2014-05-07 08:44:29');
Executing (default): INSERT INTO `Child2s` (`id`,`createdAt`,`updatedAt`) VALUES (DEFAULT,'2014-05-07 08:44:29','2014-05-07 08:44:29');
Executing (default): SELECT * FROM `Child1s` AS `Child1` WHERE (`Child1`.`ParentId`=1 AND `Child1`.`id`=1);
Executing (default): UPDATE `Child1s` SET `id`=1,`createdAt`='2014-05-07 08:44:29',`updatedAt`='2014-05-07 08:44:29',`ParentId`=1 WHERE `id`=1
Executing (default): SELECT * FROM `Child2s` AS `Child2` WHERE (`Child2`.`Child1Id`=1 AND `Child2`.`id`=1);
Executing (default): UPDATE `Child2s` SET `id`=1,`createdAt`='2014-05-07 08:44:29',`updatedAt`='2014-05-07 08:44:29',`Child1Id`=1 WHERE `id`=1
Executing (default): SELECT `Parent`.*, `Child1s`.`id` AS `Child1s.id`, `Child1s`.`id` AS `Child1s.id`, `Child1s.Child2s`.`id` AS `Child1s.Child2s.id`, `Child1s.Child2s`.`id` AS `Child1s.Child2s.id` FROM (SELECT `Parent`.`id` FROM `Parents` AS `Parent` WHERE (SELECT `Child1Id` FROM `Child2s` AS `Child1s.Child2s` WHERE `Child1s`.`id` = `Child1s.Child2s`.`Child1Id` LIMIT 1) IS NOT NULL LIMIT 1) AS `Parent` LEFT OUTER JOIN `Child1s` AS `Child1s` ON `Parent`.`id` = `Child1s`.`ParentId` INNER JOIN `Child2s` AS `Child1s.Child2s` ON `Child1s`.`id` = `Child1s.Child2s`.`Child1Id` AND `Child1s.Child2s`.`id`=1;
/Users/mlegenhausen/dev/github/sequelize-test/node_modules/co/index.js:290
    throw err;
          ^
Error: ER_BAD_FIELD_ERROR: Unknown column 'Child1s.id' in 'where clause'
    at Query.Sequence._packetToError (/Users/mlegenhausen/dev/github/sequelize-test/node_modules/mysql/lib/protocol/sequences/Sequence.js:30:14)
    at Query.ErrorPacket (/Users/mlegenhausen/dev/github/sequelize-test/node_modules/mysql/lib/protocol/sequences/Query.js:82:18)
    at Protocol._parsePacket (/Users/mlegenhausen/dev/github/sequelize-test/node_modules/mysql/lib/protocol/Protocol.js:205:24)
    at Parser.write (/Users/mlegenhausen/dev/github/sequelize-test/node_modules/mysql/lib/protocol/Parser.js:62:12)
    at Protocol.write (/Users/mlegenhausen/dev/github/sequelize-test/node_modules/mysql/lib/protocol/Protocol.js:37:16)
    at Socket.<anonymous> (/Users/mlegenhausen/dev/github/sequelize-test/node_modules/mysql/lib/Connection.js:73:28)
    at Socket.EventEmitter.emit (events.js:104:17)
    at readableAddChunk (_stream_readable.js:156:16)
    at Socket.Readable.push (_stream_readable.js:123:10)
    at TCP.onread (net.js:520:20)
```

The error occurs cause of the `where` clause of Child2. If I remove the clause it works.

Note: I am using generators for better readability to start this use node 0.11.x with `--harmony` flag.

**Comment by Celadora** [comment]
This solves the problem of the query error, but if I use it the where clause no longer constrains the query. I need both. Is there any work around to this other than doing two separate queries?
