### ISSUE TITLE
postgres-array not resolved with yarn v4 (Error: Please install postgres-array package manually)

### ISSUE THREAD

**Issue by QuentinFarizon** [sequelize/sequelize#17272]
## Issue Creation Checklist

- [x] I understand that my issue will be automatically closed if I don't fill in the requested information
- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

I have started a new project with yarn v4 and sequelize, and I can't connect with postgres.

```
Error: Please install postgres-array package manually

Error: @sequelize/core tried to access postgres-array, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

### What do you expect to happen?

postgres-array is installed, it should find it (I installed pg which brings it through pg-types).

### What is actually happening?

```
/project-path/.yarn/__virtual__/@sequelize-core-virtual-22c149e4d2/4/.yarn/berry/cache/@sequelize-core-npm-7.0.0-alpha.33-3306c2ef8d-10c0.zip/node_modules/@sequelize/core/src/dialects/abstract/connection-manager.ts:140
        throw new Error(`Please install ${moduleName} package manually`);
              ^
Error: Please install postgres-array package manually
    at PostgresConnectionManager._loadDialectModule (/project-path/.yarn/__virtual__/@sequelize-core-virtual-22c149e4d2/4/.yarn/berry/cache/@sequelize-core-npm-7.0.0-alpha.33-3306c2ef8d-10c0.zip/node_modules/@sequelize/core/src/dialects/abstract/connection-manager.ts:140:15)
    at new PostgresConnectionManager (/project-path/.yarn/__virtual__/@sequelize-core-virtual-22c149e4d2/4/.yarn/berry/cache/@sequelize-core-npm-7.0.0-alpha.33-3306c2ef8d-10c0.zip/node_modules/@sequelize/core/src/dialects/postgres/connection-manager.ts:67:33)
    at new PostgresDialect (/project-path/.yarn/__virtual__/@sequelize-core-virtual-22c149e4d2/4/.yarn/berry/cache/@sequelize-core-npm-7.0.0-alpha.33-3306c2ef8d-10c0.zip/node_modules/@sequelize/core/src/dialects/postgres/index.ts:103:30)
    at new Sequelize (/project-path/.yarn/__virtual__/@sequelize-core-virtual-22c149e4d2/4/.yarn/berry/cache/@sequelize-core-npm-7.0.0-alpha.33-3306c2ef8d-10c0.zip/node_modules/@sequelize/core/src/sequelize.js:416:20)
    at getSequelizeInstance (/project-path/api/core/sequelize.ts:36:10)
    at connect (/project-path/api/core/sequelize.ts:16:23)
    at getModels (/project-path/api/models/index.ts:13:60)
    at Object.<anonymous> (/project-path/api/bin/worker.ts:17:33)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module.m._compile (/project-path/.yarn/__virtual__/ts-node-virtual-1c21828d8d/4/.yarn/berry/cache/ts-node-npm-10.9.2-3f3890b9ac-10c0.zip/node_modules/ts-node/src/index.ts:1618:23)

```

```
[$  (master)]$ yarn why sequelize
[$  (master)]$ yarn why @sequelize/core
└─ api@workspace:api
   └─ @sequelize/core@npm:7.0.0-alpha.33 [ee769] (via npm:7.0.0-alpha.33 [ee769])
[$  (master)]$ yarn why pg
└─ api@workspace:api
   └─ pg@npm:8.11.3 [ee769] (via npm:8.11.3 [ee769])
[$  (master)]$ yarn why postgres-array
└─ pg-types@npm:2.2.0
   └─ postgres-array@npm:2.0.0 (via npm:~2.0.0)

```

### Environment

- Sequelize version: 7.0.0-alpha.37
- Node.js version: 20.9.0
- If TypeScript related: TypeScript version: 5.4.4
- Database & Version: PostgreSQL 16
- Connector library & Version: pg 8.11.3

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [x] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [ ] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

_Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed._

**Comment by WikiRik** [comment]
This should be fixed in the next alpha release where we use `@sequelize/postgres` where postgres-array is defined explicitly. See https://github.com/sequelize/sequelize/blob/main/packages/postgres/package.json

We will release that alpha once we've updated the docs; https://github.com/sequelize/website/pull/742

**Comment by ephys** [comment]
This has now been released - https://github.com/sequelize/sequelize/releases/tag/v7.0.0-alpha.40
