### ISSUE TITLE
Unable to find dialect at

### ISSUE THREAD

**Issue by Kaliph** [sequelize/sequelize#17295]
## Bug Description

I am using sequelize and @fyreware/mysql-data-api to connect to a AWS Aurora mysql database. When using Node.js 16
everything works just fine. As soon as I upgrade the AWS Lambda version to Node.js 18 or higher, I get the following error message. When I run my code in serverless-offline lambda emulator also on Node.js 20 I can´t reproduce the issue.
In my case I can only reproduce it running my code in AWS Lambda function at the moment.
I found another thread on Stackoverflow. Seems it is not only me, facing this issue.
[issue on stackoverflow](https://stackoverflow.com/questions/78129886/unable-to-find-dialect-at-journeyapps-sqlcipher)

```
{
  "errorType": "Error",
  "errorMessage": "Unable to find dialect at @fyreware/mysql-data-api",
  "trace": [
    "Error: Unable to find dialect at @fyreware/mysql-data-api",
    "    at ConnectionManager._loadDialectModule (/var/task/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:53:17)",
    "    at new ConnectionManager (/var/task/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:30:21)",
    "    at new MysqlDialect (/var/task/node_modules/sequelize/lib/dialects/mysql/index.js:13:30)",
    "    at new Sequelize (/var/task/node_modules/sequelize/lib/sequelize.js:194:20)",
    "    at file:///var/task/config/db.js:9:19",
    "    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)",
    "    at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)",
    "    at async _tryAwaitImport (file:///var/runtime/index.mjs:1008:16)",
    "    at async _tryRequire (file:///var/runtime/index.mjs:1057:37)",
    "    at async _loadUserApp (file:///var/runtime/index.mjs:1081:16)"
  ]
}
```

### Reproducible Example

```
const sequelize = new Sequelize(env.AWS_DATA_API_DATABASE_NAME, env.DATABASE_USERNAME, env.AWS_DATA_API_SECRET_ARN, {
  host: env.AWS_DATA_API_RESOURCE_ARN,
  port: env.DATABASE_PORT,
  logging: env.DATABASE_LOGGING,
  freezeTableName: env.DATABASE_FREEZE_TABLE_NAME,
  dialect: env.DATABASE_DIALECT,
  dialectOptions: {
    connectTimeout: 1000
  },
  dialectModulePath: '@fyreware/mysql-data-api',
  pool: env.DATABASE_POOL,
  query: { raw: true },
  define: {
    timestamps: env.DATABASE_TIMESTAMPS,
    underscored: env.DATABASE_UNDERSCORED,
  }
});
```

### What do you expect to happen?

Connection to the database is established

### What is actually happening?

Connection fails

### Environment

- Sequelize version: 6.37.3
- Node.js version: > 18.x
- If TypeScript related: TypeScript version:
- Database & Version: AWS Aurora mysql serverless
- Connector library & Version: mysql2 3.9.7

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [x] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

_Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed._

**Comment by DorianMazur** [comment]
What version of serverless-offline are you using?
Recently I published new version v13.4.0 -> https://github.com/dherault/serverless-offline/releases/tag/v13.4.0
This version updates all docker images, because https://github.com/lambci/docker-lambda are deprecated for some time.

**Comment by Kaliph** [comment]
@DorianMazur I am using the latest version of serverless-offline 13.4.0. But my code works properly with serverless-offline.
It just happens in AWS Lambda function with Node.js version v18 or v20. With Node.js 16 everything works well.
