### ISSUE TITLE
Node.js start fails on Linux platform due to invalid ELF header error

### ISSUE THREAD

**Issue by zN3utr4l** [sequelize/sequelize#17318]
## Issue Creation Checklist

- [x] I understand that my issue will be automatically closed if I don't fill in the requested information
- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

I'm trying to create a nodejs app on windows that only runs on linux, when building I install the dependencies like this `"SET "npm_config_arch=ia32" ; SET "npm_config_target_arch=ia32" ; SET "npm_config_platform=linux" ; Yarn install"` (as suggested here https://github.com/yarnpkg/yarn/issues/2221#issuecomment-872021336)

but it goes wrong

```
/home/pi/test/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:57
throw err;
^

Error: /home/pi/test/node_modules/sqlite3/build/Release/node_sqlite3.node: invalid ELF header
at Module._extensions..node (node:internal/modules/cjs/loader:1452:18)
at Module.load (node:internal/modules/cjs/loader:1197:32)
at Module._load (node:internal/modules/cjs/loader:1013:12)
at Module.require (node:internal/modules/cjs/loader:1225:19)
at require (node:internal/modules/helpers:177:18)
at bindings (/home/pi/test/node_modules/bindings/bindings.js:112:48)
at Object.<anonymous> (/home/pi/test/node_modules/sqlite3/lib/sqlite3-binding.js:1:37)
at Module._compile (node:internal/modules/cjs/loader:1356:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
at Module.load (node:internal/modules/cjs/loader:1197:32) {
code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.19.1
```

### Environment

- Sequelize version: `sequelize@6.37.3`
- Node.js version: `v18.20.2`
- If TypeScript related: TypeScript version: `typescript@5.4.5`
- Database & Version:  `sqlite3@5.1.7`
- Connector library & Version:  `sqlite3@5.1.7`

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [x] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

_Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed._

**Comment by WikiRik** [comment]
I'll reply in #17317
