### ISSUE TITLE
MSSQL instanceName not working

### ISSUE THREAD

**Issue by semics-tech** [sequelize/sequelize#17428]
## Issue Creation Checklist

- [ x] I understand that my issue will be automatically closed if I don't fill in the requested information
- [ x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

I'm unable to connect to an MSSQL instance with a specified instanceName.

### Reproducible Example

```javascript
import { Sequelize } from '@sequelize/core'
import { MsSqlDialect } from '@sequelize/mssql'
const options= {
  dialect: MsSqlDialect,
  server: "SERVER",
  database: "DATABASE",
  trustServerCertificate: true,
  requestTimeout: 300000,
  authentication: {
    type: "default",
    options: {
      userName: USERNAME,
      password: PASSWORD,
    },
  },
  instanceName: "INSTANCE_NAME",
}


const sequelize = new Sequelize(options)


await sequelize.query('select 1')
```

Here is the link to the SSCCE for this issue:

```
ConnectionError [SequelizeConnectionError]: Failed to connect to SERVER:1433 - Could not connect (sequence)
    at MsSqlConnectionManager.connect (PROJECTPATH\node_modules\@sequelize\mssql\lib\connection-manager.js:123:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async connect (PROJECTPATH\node_modules\@sequelize\core\lib\sequelize-typescript.js:466:28)
    at async Object.create (PROJECTPATH\node_modules\@sequelize\core\lib\abstract-dialect\replication-pool.js:78:28) {
  [cause]: ConnectionError: Failed to connect to RQ6LUNASQL01SB:1433 - Could not connect (sequence)
      at Connection.socketError (PROJECTPATH\node_modules\tedious\lib\connection.js:1338:28)
      at PROJECTPATH\node_modules\tedious\lib\connection.js:1131:14
      at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
    code: 'ESOCKET'
  }
}
```
### What do you expect to happen?

As per the documentation page https://sequelize.org/docs/v7/databases/mssql/ I would expect the server to connect

### What is actually happening?

An error is being thrown because the instanceName is not being sent to the MSSQL / Tedious package correctly.

### Environment

- @sequelize/core version: 7.0.0-alpha.37
- Node.js version: 20.15.1
- If TypeScript related: TypeScript version:
- Database & Version: SQL Server 2019
- Connector library & Version: mssql / tedious

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [ x] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

_Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed._

**Comment by WikiRik** [comment]
Can you install `@sequelize/core` 7.0.0-alpha.41? It's not published under the `latest` tag but the `alpha` tag. You need to install the same version for `@sequelize/mssql` as well

**Comment by semics-tech** [comment]
@WikiRik okay so I forgot that I made a manual change to get to this error.

I have installed the `7.0.0-alpha.41` version and am getting the original error but the error I was getting above has been solved.

The first error is `ConnectionError [SequelizeConnectionError]: Port and instanceName are mutually exclusive, but 1433 and INSTANCENAME provided` which can be solved by removing the following line in `MsSqlConnectionManager.connect`

![image](https://github.com/user-attachments/assets/f3162b29-2944-469b-be1c-59a6f08ab9a8)

I can raise a PR or do you know if this fix will be included in a later version?
