### ISSUE TITLE
SequelizeDatabaseError with Oracle procedure call

### ISSUE THREAD

**Issue by komalguptaLearner** [sequelize/sequelize#17422]
### Discussed in https://github.com/sequelize/sequelize/discussions/17421

<div type='discussions-op-text'>

<sup>Originally posted by **komalguptaLearner** July 17, 2024</sup>
Getting issue with oracle procedure call using sequelize. The error is-
Executing (default): CALL "DSSUSER"."CLOSE_ORDER_ON_FSO_CLOSE"('', '15619455', 1721043225323, TO_DATE('2024-07-15 11:33:45', 'YYYY-MM-DD HH24:MI:SS'));
data-> {}
C:\komal\gitRepo\dss-msp\ordercaptureservice\node_modules\sequelize\lib\dialects\oracle\query.js:461
  return new SequelizeErrors.DatabaseError(err);
      ^

DatabaseError [SequelizeDatabaseError]: Cannot read properties of undefined (reading '0')
  at OracleQuery.formatError (C:\komal\gitRepo\dss-msp\ordercaptureservice\node_modules\sequelize\lib\dialects\oracle\query.js:461:12)
  at OracleQuery.run (C:\komal\gitRepo\dss-msp\ordercaptureservice\node_modules\sequelize\lib\dialects\oracle\query.js:225:18)

VERSION details - "@sequelize/core": "^7.0.0-alpha.37", "sequelize": "^6.37.3", "oracledb": "^6.4.0"</div>

**Comment by komalguptaLearner** [comment]
I tried updating query.js at highlighted. It was observed that data is {} after a proc call, so when it calls data.rows[0] it gives above error. I marked it instead data.rows, where it was working. However, I can't make any change in nodemodules-
else if (this.isCallQuery()) {
console.log('data->', data);
result = data.rows[0];
}
