### ISSUE TITLE
Using encryption (journeyapps/sqlcipher) in sqllite, there is no problem with normal use, but an error will be reported when using transactions

### ISSUE THREAD

**Issue by paokuaikuai** [sequelize/sequelize#17467]
### Environment version
nodejs：V14.15.0
sqlite3@^5.1.4
journeyapps/sqlcipher@^5.3.1
sequelize@^6.29.0

### This is the database related configuration
`
const path = require("path");
const { Sequelize } = require('sequelize');
const file = path.join(__dirname, '../ecg.db');
const LOG = require("./log4js").logger("SequelizeConnectDb");

const sequelize = new Sequelize({
  pool: {
    max: 5,
    min: 0,
    acquire: 30000,
    idle: 10000
  },
  dialect: 'sqlite',
  storage: file,
  dialectModulePath: '@journeyapps/sqlcipher',
  logging: false, 
  logging: msg => LOG.info(msg)
});

sequelize.query('PRAGMA cipher_compatibility = 3');
sequelize.query("PRAGMA key = 'xxx'");

//使用 .authenticate() 函数测试连接是否正常
sequelize.authenticate().then(() => {
  LOG.info('Connection has been established successfully.')
}).catch(err => {
  LOG.error('Unable to connect to the database:', err)
})

module.exports = sequelize;
`
### Using transactions will result in an error
`
        let transaction = null;
        let ecgEntity = null;
        let hasError = false;
        let err = null;
        try {
            transaction = await sequelize.transaction();
            ecgEntity = await ecg.create(this.buildEcgData(ecgInfo, user), { transaction });

            await ecg.update({ filePath: AppConfig.getHolterRootPath(ecgEntity.id) }, { where: { id: ecgEntity.id }, transaction });
            await bpDetail.bulkCreate(this.buildBpData(ecgEntity, bpList), { transaction });
        } catch (e) {
            await transaction.rollback();
        }
 
`
### Error Message
'SQLITE_NOTADB: file is not a database'
'Error\n    at Database.<anonymous> (F:\\Code\\ECGBP\\trunk\\holter-bp\\node_modules\\sequelize\\lib\\dialects\\sqlite\\query.js:185:27)\n    at Database.callbackTrampoline (internal/async_hooks.js:129:14)\n    at F:\\Code\\ECGBP\\trunk\\holter-bp\\node_modules\\sequelize\\lib\\dialects\\sqlite\\query.js:183:50\n    at new Promise (<anonymous>)\n    at Query.run (F:\\Code\\ECGBP\\trunk\\holter-bp\\node_modules\\sequelize\\lib\\dialects\\sqlite\\query.js:183:12)\n    at F:\\Code\\ECGBP\\trunk\\holter-bp\\node_modules\\sequelize\\lib\\seque…CGBP\\trunk\\holter-bp\\node_modules\\sequelize\\lib\\dialects\\abstract\\query-interface.js:308:21)\n    at async model.save (F:\\Code\\ECGBP\\trunk\\holter-bp\\node_modules\\sequelize\\lib\\model.js:2490:35)\n    at async Function.create (F:\\Code\\ECGBP\\trunk\\holter-bp\\node_modules\\sequelize\\lib\\model.js:1362:12)\n    at async DBService.beginImport (F:\\Code\\ECGBP\\trunk\\holter-bp\\areas\\system\\service\\ecgFileService.js:92:25)\n    at async F:\\Code\\ECGBP\\trunk\\holter-bp\\areas\\system\\service\\ecgFileService.js:542:35'

**Comment by yourromchikkkkk** [comment]
@paokuaikuai Have you found the solution?
