### ISSUE TITLE
Transactions are closed before Sequelize retries the operation.

### ISSUE THREAD

**Issue by PoolFlamingo** [sequelize/sequelize#17466]
## Issue Creation Checklist

- [x] I understand that my issue will be automatically closed if I don't fill in the requested information
- [x] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

### What do you expect to happen?

If massive data changes are made to a table, using multiple transactions for each update or insertion into the table, if the database connection/request limit is reached ("Deadlock"), it must correctly retry up to a maximum of 3 times to obtain a connection and then make changes.

### What is actually happening?

When the maximum number of simultaneous connections is reached, a "deadlock" is generated, and the retry configuration is correctly activated, but by the time the retry is performed, the transaction has been closed with a rollback, preventing it from performing the expected operation.

``` Bash
Error: rollback has been called on this transaction(1b6302cc-19b0-4c39-9e89-71628e44b6ce), you can no longer use it. (The rejected query is attached as the 'sql' property of this error)
    at checkTransaction (\node_modules\sequelize\lib\sequelize.js:294:23)
    at \node_modules\sequelize\lib\sequelize.js:304:7
    at \node_modules\retry-as-promised\dist\index.js:59:25
    at new Promise (<anonymous>)
    at retryAsPromised (\node_modules\retry-as-promised\dist\index.js:48:12)
    at Timeout._onTimeout (\node_modules\retry-as-promised\dist\index.js:94:21)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {
  sql: 'INSERT INTO `media_sources` (`uuid`,`author`,`name`,`path`,`gallery`,`type`,`hidden`,`data`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?,?,?);'
}
Error: rollback has been called on this transaction(1b6302cc-19b0-4c39-9e89-71628e44b6ce), you can no longer use it. (The rejected query is attached as the 'sql' property of this error)
    at checkTransaction (\node_modules\sequelize\lib\sequelize.js:294:23)
    at \node_modules\sequelize\lib\sequelize.js:304:7
    at \node_modules\retry-as-promised\dist\index.js:59:25
    at new Promise (<anonymous>)
    at retryAsPromised (\node_modules\retry-as-promised\dist\index.js:48:12)
    at Timeout._onTimeout (\node_modules\retry-as-promised\dist\index.js:94:21)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {
  sql: 'INSERT INTO `media_sources` (`uuid`,`author`,`name`,`path`,`gallery`,`type`,`hidden`,`data`,`createdAt`,`updatedAt`) VALUES (?,?,?,?,?,?,?,?,?,?);'
}
```

### Description
I am doing an operation on my local server to update all records that point to video type files uploaded by users of my server. What I am looking for is to generate thumbnails of the mentioned videos (there are 238) that do not have this property, then I proceed to register these thumbnails as images under the same system. Here I leave the function that is an iteration for the registration of one of the 238 thumbnails that have been previously generated.
``` Typescript
async function FileSaveAndRegistration(file:File, gallery:string, hidden:boolean, author:number, subpath?:string, saveFile:boolean=true):Promise<MediaSource>
{
    try {
        const originalName=file.name;
        const ext=path.extname(originalName)||mime.extension(file.type)||"";
        const baseName=path.basename(originalName, ext);
        const tmpUUID=await CreateUniqueUUID(async (uuid)=>{
            const finalName=`${baseName}_${uuid}${ext}`;
            const ipath=`/${finalName}`;
            const mediaSrc=await MediaSource.findOne({where:{path:ipath}, attributes:FiSe<MediaSource>("uuid")});
            return !mediaSrc;
        });
    
        let finalName=`${baseName}_${tmpUUID}${ext}`;
        let ipath=`/${finalName}`;
        if(subpath)
            ipath=path.posix.join(subpath, ipath);
    
        const rmFile=saveFile?await SaveFile(ipath, file):undefined;
        const mainType=file.type.split("/")[0];
        const dimensions=await MediaSource.CalculateDimensions(mainType, path.join(root, env.MEDIA_PATH, path.dirname(ipath), file.name));
    
        let rmPath:string|undefined=undefined;
        try {
            //This is where the deadlock error is usually generated.
            const mediaSrc=await MediaSource.sequelize!.transaction(async (transaction)=>{
                const mediaSrc=await MediaSource.create({
                    name:originalName,
                    author,
                    data:{
                        size:file.size,
                        baseName,
                        dimensions:dimensions as [number, number]
                    },
                    gallery,
                    path:path.posix.join(ipath),
                    type:file.type,
                    hidden
                }, {transaction});
        
                finalName=`${baseName}_${mediaSrc.uuid}${ext}`;
                ipath=`/${finalName}`;
                if(subpath)
                    ipath=path.posix.join(subpath, ipath);
        
                const oldPath=saveFile?mediaSrc.path:path.join(subpath||"", file.name);
                mediaSrc.path=path.posix.join(ipath);
                rmPath=await RenameFileToPermanantName(oldPath, mediaSrc.path);
        
                return await mediaSrc.save({transaction});
            });
    
            return mediaSrc;
        } catch (err:any) {
            if(rmFile)
                await rmFile(rmPath);
    
            throw err;
        }
    } catch (err:any) {
        console.error(err);
        throw err;
    }
}
```

I have searched for information in different places and in different ways, but I have not been able to find a definitive solution, since this error does not always happen, since this operation sometimes runs without jumping _deadlock_, and other times it does happen, causing an inconsistency in the results of my tests. I have tried to configure the _pool_ property of the main connection that I use in the models, and I have also tried to leave the default values ​​​​by only specifying the number of retries.
``` Typescript
const main=new Sequelize({
    dialect:"mariadb",
    host:env.SQL_DB_HOST,
    database:env.SQL_DB_NAME,
    username:env.SQL_DB_USER,
    password:env.SQL_DB_PASS,
    attributeBehavior:"escape",
    port:env.SQL_DB_PORT?Number(env.SQL_DB_PORT):undefined,
    timezone:"+02:00",
    pool:{ 
        //En un principio esto no se debe de poner, ya que aunque solo ponga max se casca ante operaciones grandes. 
        //Parece ser que se ajusta automáticamente.
        acquire:Number(env.SQL_DB_CONNECTION_TIMEOUT), //30000
        evict:Number(env.SQL_DB_EVIC_TIMEOUT), //8000
        idle:Number(env.SQL_DB_IDLE_TIMEOUT), //10000
        max:Number(env.SQL_DB_MAX_CONN), //5
        maxUses:TryParseNumber(env.SQL_DB_QUEUE_LIMIT)||undefined // 0 so undefined
    },
    dialectOptions: {
        connectTimeout: 60000 // 60 segundos
    },
    retry:{
        match: [
            ConnectionError,
            ConnectionTimedOutError,
            TimeoutError,
            /Deadlock/i
        ],
        max: 3, // Maximum retry 3 times
        backoffBase: 1000, // Initial backoff duration in ms. Default: 100,
        backoffExponent: 1.5, // Exponent to increase backoff each try. Default: 1.1
    },
    logging:true
});
```

If you need more information, do not hesitate to ask. Thanks in advance.

### Environment

- Sequelize version: 6.37.3
- Node.js version: v20.12.1
- Database & Version: 10.4.32-MariaDB

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [x] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

_Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed._

**Comment by caarmen** [comment]
Been banging my head about this problem for the past couple of days! Glad to see we're not alone 😅 

For info, we've done this workaround, to:
* disable retries for sql queries inside a transaction
* use retry-as-promised outside transactions, to retry the whole transaction:

```javascript
const retry = require('retry-as-promised').default;

// ...

await retry(async () => {
    await database.transaction(async (t) => { // do retries on the whole transaction
        const myModel = MyModel.findOne({
            where: {/* your filters here */},
            {
                transaction: t,
                t.LOCK.UPDATE,
                retry: {
                    name: "individual query name to help with debugging",
                    max: 1, // disable individual request retries
                }
            }
        });
        // Other queries here with similar retry options
        // ...

    }); // end of transaction
},{ // transaction retry options:
    max: 5,
    name: "some transaction name to help with debugging",
    match: [
        /* your patterns here for detecting retriable errors */
    ]
});
```
