### ISSUE TITLE
SequelizeConnectionAcquireTimeoutError  - Sequelize Connection Pool Exhaustion and Timeout Errors on MySQL 8

### ISSUE THREAD

**Issue by NevilDabre** [sequelize/sequelize#17535]
## Issue Creation Checklist

- [y] I understand that my issue will be automatically closed if I don't fill in the requested information
- [y] I have read the [contribution guidelines](https://github.com/sequelize/sequelize/blob/main/CONTRIBUTING.md)

## Bug Description

After upgrading to MySQL 8.0.37, we started encountering connection pool exhaustion in Sequelize, where the pool reaches its maximum connection limit (500), causing a timeout error when trying to acquire new connections.

/![Image](https://github.com/user-attachments/assets/707f5af0-8792-4f07-9ce6-5ba227668110)

We have configured the connection pool with a max of 500 connections, but over time, the pool is exhausted, and no new connections are being released back into the pool. This results in the following error:

```javascript
SequelizeConnectionAcquireTimeoutError: Operation timeout
    at ConnectionManager.getConnection 
    at async MySQLQueryInterface.select
``` 

It appears that connections are not properly closing after certain requests, leading to the pool filling up and eventually timing out. The idle       idle and evict doesn't seem working. We were using MySQL 5.7v but not faced this issue.

### Reproducible Example

**Environment:**
Sequelize version: 6.29.0
MySQL version: 8.0.37
Node.js version: 18.x
MySQL2 version: 3.9.8
Cloud Provider: Azure

**SequelizeJS config**

```javascript
const Sequelize = require('sequelize');
const moment = require('moment')
const config = require('./config');

// Don't import logger(Winston) to avoid Circular Redundancy
const { createLogger, transports } = require('winston');
 
const dbLogger = createLogger({
  transports: [
    new transports.Console()
  ]
});

let sequelize = null;
  
    const mysqlCert = Buffer.from(process.env.MYSQL_SSL, 'base64').toString();
    // Pool config Refer here - https://sequelize.org/api/v6/class/src/sequelize.js~sequelize#instance-constructor-constructor
    const poolConfig = {
      max: 500,
      min: 50,
      acquire: 60000,
      idle: 10000,
      evict: 1000
    };
    sequelize = new Sequelize(config.db.name, config.db.user, config.db.password, {
      host: config.db.host,
      port: config.db.port,
      dialect: 'mysql',
      define: {
        freezeTableName: true,
        underscored: true,
        timestamps: false,
      },
      pool: poolConfig,
      dialectOptions: {
        dateStrings: true, // reading from database
        typeCast(field, next) {
          if (field.type === 'DATETIME') {
            return field.string();
          }
          return next();
        }, // reading from database
        ssl: {
          cert: mysqlCert,
        },
        
      },
    });
  
  sequelize
    .authenticate()
    .then(() => {
      dbLogger.info('Sequelize connection has been established successfully.');

        const connectionPool = sequelize?.connectionManager?.pool;

      setInterval(() => {
        const availableConnections = connectionPool?.available;
        const usedConnections = connectionPool?.using;
        const waitingConnections = connectionPool?.waiting;
        const maxUsesPerResource = connectionPool?.maxUsesPerResource;

        dbLogger.info(`Sequelize connections info availableConnections = ${availableConnections} usedConnections = ${usedConnections} waitingConnections = ${waitingConnections}`);
      }, 30000);

    })
    .catch((err) => {
    dbLogger.error(`Sequelize - authenticate ${err}.`);
  });
}

module.exports = sequelize;

``` 

### What do you expect to happen?

Connections should be properly released back into the pool after each request, preventing the pool from reaching its maximum capacity.

### What is actually happening?

Connections are not being released after certain requests, leading to the pool filling up and eventually causing SequelizeConnectionAcquireTimeoutError.

Complete stack trace:
```javascript
SequelizeConnectionAcquireTimeoutError: Operation timeout
    at ConnectionManager.getConnection (/home/node/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:204:15)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processTimers (node:internal/timers:509:9)
    at async /home/node/node_modules/sequelize/lib/sequelize.js:305:26
    at async MySQLQueryInterface.select (/home/node/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)
    at async company.findAll (/home/node/node_modules/sequelize/lib/model.js:1134:21)
    at async company.findOne (/home/node/node_modules/sequelize/lib/model.js:1228:12)
    at async isBrazeEnabledResolve (/home/node/src/graphql/customers/braze/braze-resolvers.js:69:25)
    at async Promise.all (index 0)
    at async graphqlMiddleware (/home/node/node_modules/express-graphql/index.js:125:26)
``` 

### Environment

- Sequelize version: 6.29.0
- Node.js version: 18
- If TypeScript related: TypeScript version: NA
- Database & Version:  MySQL 8.0.37 Current (Previous 5.7)
- Connector library & Version: MySQL2 v3.9.8

## Would you be willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time and I know how to start.
- [ ] Yes, I have the time but I will need guidance.
- [ ] No, I don't have the time, but my company or I are [supporting Sequelize through donations on OpenCollective](https://opencollective.com/sequelize).
- [ ] No, I don't have the time, and I understand that I will need to wait until someone from the community or maintainers is interested in resolving my issue.

---

_Indicate your interest in the resolution of this issue by adding the 👍 reaction. Comments such as "+1" will be removed._

**Comment by mihailo-cimet** [comment]
I can confirm that we are having the same issue. I'd like to see some interest in resolving this.

**Comment by HsinHeng** [comment]
https://github.com/sidorares/node-mysql2/releases/tag/v3.11.1

Maybe you can upgrade node-mysql2 to 3.11.1

**Comment by prashant0078** [comment]
I can confirm we are facing same issue
