### ISSUE TITLE
Cannot call method 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by ArkeologeN** [sequelize/sequelize#1886]
I've existing schema / database built and now I need to connect models together. I'm using MySQL on the back. Tables are like:

```
# Users.
'id' is PRIMARY KEY
...

# Posts
'id' is PRIMARY KEY
'author_id' is FOREIGN KEY to -> Users.id
......
```

When I try to add like this:

``` javascript
User.hasMany(Post, {foreignKey: 'author_id', as: 'Post'});
```

It throws:

```
TypeError: Cannot call method 'toLowerCase' of undefined
    at Object.module.exports.combineTableNames (/var/www/carspot/node_modules/sequelize/lib/utils.js:361:51)
    at new module.exports.HasMany (/var/www/carspot/node_modules/sequelize/lib/associations/has-many.js:25:36)
    at Mixin.hasMany (/var/www/carspot/node_modules/sequelize/lib/associations/mixin.js:52:21)
    at sequelize.define.classMethods.associate (/var/www/carspot/models/users.js:76:20)
................
```

OR when I try to add a `belongsTo` like this:

``` javascript
Post.belongsTo(User);
```

it throws:

```
TypeError: Cannot read property 'language' of undefined
    at new module.exports.BelongsTo (/var/www/carspot/node_modules/sequelize/lib/associations/belongs-to.js:23:77)
    at Mixin.belongsTo (/var/www/carspot/node_modules/sequelize/lib/associations/mixin.js:33:21)
    at sequelize.define.classMethods.associate (/var/www/carspot/models/posts.js:37:20)
    at /var/www/carspot/models/index.js:25:27
```

Can anyone figure out what's wrong with it?

**Comment by 480Dev** [comment]
I had a similar error which was corrected by accessing the parent folder and recreating a new file with a .js extension.

**Comment by ugurcanalyuz** [comment]
When I thoroughly researched this, I noticed the following:
TEXT(255) :)
