### ISSUE TITLE
Event Emitter leak?

### ISSUE THREAD

**Issue by myndzi** [sequelize/sequelize#1893]
I'm getting this error:

```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at process.EventEmitter.addListener (events.js:160:15)
    at process.on.process.addListener (node.js:769:26)
    at new module.exports.ConnectorManager (/home/search/boiler/node_modules/sequelize/lib/dialects/mysql/connector-manager.js:157:13)
    at TransactionManager.getConnectorManager (/home/search/boiler/node_modules/sequelize/lib/transaction-manager.js:33:36)
    at TransactionManager.query (/home/search/boiler/node_modules/sequelize/lib/transaction-manager.js:52:15)
    at module.exports.Sequelize.query (/home/search/boiler/node_modules/sequelize/lib/sequelize.js:330:36)
    at null.fct (/home/search/boiler/node_modules/sequelize/lib/sequelize.js:410:10)
    at null.<anonymous> (/home/search/boiler/node_modules/sequelize/lib/emitters/custom-event-emitter.js:24:18)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
Executing (default): SELECT 1+1 AS result
```

I am instantiating sequelize multiple times, up to about 5. I'm super swamped, can anyone point me in the right direction to running this down?

**Comment by venkatesh-tr** [comment]
Sorry, but I don't agree with you @mickhansen. We do have a solution here which uses single database per tenant. Even I am facing same issue. Is there a work-around for this problem atleast?

Can I increase the max listeners somehow?

**Comment by mickhansen** [comment]
@venkatesh-tr We're not using event emitters anymore. And in any case it was only ever a warning. And you can change the emitters settings globally with node.js

**Comment by hanrea** [comment]
Look here~
https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/connection-manager.js#L42

```javascript
    this.onProcessExit = this.onProcessExit.bind(this);

    process.on('exit', this.onProcessExit);

    this.initPools();
```

There listen process's exit event  ,if  start many Sequelize  instance , may be crush by  ` EventEmitter memory leak detected.` error.

I think this way is not good, if Sequelize want manger , It's can create globe connection manager queue, and listen once `process' exit` event. 

Nother way, turn to choese

```javascript
var squ1 = new Sequelize()
var que2 = new Sequelize()


process.on('exit', ()=>{
      squ1.close();
      squ2.close()
});

``` 

In my project ,I want connect 1000 database,testing~~~
