### ISSUE TITLE
[dev13] findOrCreate()  will block sequelize if meets errors

### ISSUE THREAD

**Issue by ryanking8215** [sequelize/sequelize#2238]
I find `findOrCreate()` uses transaction in `dev13`, I don't know whether the problem is caused by transaction.

If executes `findOrCreate()` some times, about 4 or 5 times, every time make it throw error, i.e. Validation Error,
After that, sequelize will be blocked. 

I don't know how to fix it.

demo:

``` javascript
var Sequelize = require("sequelize")
var Promise = require("bluebird")

var db = new Sequelize('test_seq', 'root', '', {
    port: 3306
})

var User = db.define('user', {
    no: {type:Sequelize.INTEGER, allowNull:false, primaryKey:true},
    name: {type:Sequelize.STRING,allowNull:false}
},{
    tableName: "user",
    timestamps: false
})

function test_findOrCreate(times) {
    times = times || 0
    console.log("try ", times)
    if (times > 10) {
        throw new Error("try too many times")
    }

    /*without name, trigger ValidationError */
    User.findOrCreate({where:{no:1},defaults:{}})
    .timeout(5000)
    .then(function(){
        return true
    })
    .catch(Sequelize.ValidationError,function(err){
        console.log("validaton error")
        return test_findOrCreate(times+1) // do again
    })
}

db.sync({force:true})
.then(function(){
    return test_findOrCreate()
})
.catch(function(err){
    console.log(err)
})
```

outputs:

```
Executing (undefined): DROP TABLE IF EXISTS `user`;
Executing (undefined): DROP TABLE IF EXISTS `user`;
Executing (undefined): CREATE TABLE IF NOT EXISTS `user` (`no` INTEGER NOT NULL , `name` VARCHAR(255) NOT NULL, PRIMARY KEY (`no`)) ENGINE=InnoDB;
try  0
Executing (fd490811-a785-497a-95cc-fc361cef02e1): START TRANSACTION;
Executing (fd490811-a785-497a-95cc-fc361cef02e1): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (fd490811-a785-497a-95cc-fc361cef02e1): SET autocommit = 1;
Executing (fd490811-a785-497a-95cc-fc361cef02e1): SELECT `no`, `name` FROM `user` AS `user` WHERE `user`.`no`=1;
validaton error
try  1
Executing (857b4b95-b43e-42f0-81ed-f49eb53f00b7): START TRANSACTION;
Executing (857b4b95-b43e-42f0-81ed-f49eb53f00b7): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (857b4b95-b43e-42f0-81ed-f49eb53f00b7): SET autocommit = 1;
Executing (857b4b95-b43e-42f0-81ed-f49eb53f00b7): SELECT `no`, `name` FROM `user` AS `user` WHERE `user`.`no`=1;
validaton error
try  2
Executing (93eb9d95-18f0-46a7-8836-294ced4542cd): START TRANSACTION;
Executing (93eb9d95-18f0-46a7-8836-294ced4542cd): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (93eb9d95-18f0-46a7-8836-294ced4542cd): SET autocommit = 1;
Executing (93eb9d95-18f0-46a7-8836-294ced4542cd): SELECT `no`, `name` FROM `user` AS `user` WHERE `user`.`no`=1;
validaton error
try  3
Executing (401bf292-ad07-42bc-9e0a-549ad62472e9): START TRANSACTION;
Executing (401bf292-ad07-42bc-9e0a-549ad62472e9): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (401bf292-ad07-42bc-9e0a-549ad62472e9): SET autocommit = 1;
Executing (401bf292-ad07-42bc-9e0a-549ad62472e9): SELECT `no`, `name` FROM `user` AS `user` WHERE `user`.`no`=1;
validaton error
try  4
Executing (7af582b4-122c-49a0-9c50-d14ede422bd5): START TRANSACTION;
Executing (7af582b4-122c-49a0-9c50-d14ede422bd5): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (7af582b4-122c-49a0-9c50-d14ede422bd5): SET autocommit = 1;
Executing (7af582b4-122c-49a0-9c50-d14ede422bd5): SELECT `no`, `name` FROM `user` AS `user` WHERE `user`.`no`=1;
validaton error
try  5

Possibly unhandled TimeoutError: operation timed out after 5000 ms
    at Promise$_afterTimeout (/data/prj/learn_and_test/node/sequelize/new/node_modules/sequelize/node_modules/sequelize-bluebird/js/main/timers.js:45:15)
    at null._onTimeout (/data/prj/learn_and_test/node/sequelize/new/node_modules/sequelize/node_modules/sequelize-bluebird/js/main/timers.js:30:9)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
^C%                                           
```

My demo calls `findOrCreate()` 10 times, but outputs show it is called 5 times, and blocked.

**Comment by soymilkkk** [comment]
Can findOrCreate() call more than 5 times now?
