### ISSUE TITLE
hasOne association create throws error if no object is given

### ISSUE THREAD

**Issue by mlegenhausen** [sequelize/sequelize#2327]
``` js
var Sequelize = require('sequelize');

var sequelize = new Sequelize('sequelize-test', 'root', '');

var A = sequelize.define('A', {});
var B = sequelize.define('B', {});

A.hasOne(B);
B.belongsTo(A);

sequelize.sync({
    force: true
})
.then(function () {
    return A.create();
})
.then(function (a) {
    return a.createB();
});
```

Console output:

```
Executing (default): DROP TABLE IF EXISTS `Bs`;
Executing (default): DROP TABLE IF EXISTS `As`;
Executing (default): DROP TABLE IF EXISTS `As`;
Executing (default): CREATE TABLE IF NOT EXISTS `As` (`id` INTEGER NOT NULL auto_increment , `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `As`
Executing (default): DROP TABLE IF EXISTS `Bs`;
Executing (default): CREATE TABLE IF NOT EXISTS `Bs` (`id` INTEGER NOT NULL auto_increment , `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `AId` INTEGER, PRIMARY KEY (`id`), FOREIGN KEY (`AId`) REFERENCES `As` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `Bs`
Executing (default): INSERT INTO `As` (`id`,`createdAt`,`updatedAt`) VALUES (DEFAULT,'2014-09-22 16:29:00','2014-09-22 16:29:00');
Possibly unhandled TypeError: Cannot set property 'AId' of undefined
    at instancePrototype.(anonymous function) [as createB] (/Users/mlegenhausen/dev/github/sequelize-test/node_modules/sequelize/lib/associations/has-one.js:150:38)
    at /Users/mlegenhausen/dev/github/sequelize-test/has-one-create.js:18:11
From previous event:
    at reduce (/Users/mlegenhausen/dev/github/sequelize-test/node_modules/sequelize/node_modules/sequelize-bluebird/js/main/reduce.js:147:17)
    at Function.Promise$Reduce (/Users/mlegenhausen/dev/github/sequelize-test/node_modules/sequelize/node_modules/sequelize-bluebird/js/main/reduce.js:156:12)
    at module.exports.Sequelize.drop (/Users/mlegenhausen/dev/github/sequelize-test/node_modules/sequelize/lib/sequelize.js:722:20)
    at module.exports.Sequelize.sync (/Users/mlegenhausen/dev/github/sequelize-test/node_modules/sequelize/lib/sequelize.js:682:19)
    at Object.<anonymous> (/Users/mlegenhausen/dev/github/sequelize-test/has-one-create.js:11:11)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
```

The problem is that on line 150 the `values` object is `undefined`. Calling `a.createB({})` solves the problem. The problem does not occur with `hasMany` and `create`.

Used current master version.

**Comment by ms88privat** [comment]
I run into this today with hasMany too ...
