### ISSUE TITLE
Possibly unhandled TypeError: Cannot call method 'then' of undefined

### ISSUE THREAD

**Issue by tshaddix** [sequelize/sequelize#2434]
I continue to get an error...

```
Possibly unhandled TypeError: Cannot call method 'then' of undefined
    at .../node_modules/sequelize/lib/sequelize.js:908:37
    at tryCatch1 (.../node_modules/sequelize/node_modules/sequelize-bluebird/js/main/util.js:43:21)
    at Promise$_callHandler [as _callHandler] (.../node_modules/sequelize/node_modules/sequelize-bluebird/js/main/promise.js:639:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (.../node_modules/sequelize/node_modules/sequelize-bluebird/js/main/promise.js:653:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (.../node_modules/sequelize/node_modules/sequelize-bluebird/js/main/promise.js:817:14)
    at Promise$_settlePromises [as _settlePromises] (.../node_modules/sequelize/node_modules/sequelize-bluebird/js/main/promise.js:951:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (.../node_modules/sequelize/node_modules/sequelize-bluebird/js/main/async.js:75:12)
    at Async$consumeFunctionBuffer (.../node_modules/sequelize/node_modules/sequelize-bluebird/js/main/async.js:38:14)
    at process._tickCallback (node.js:419:13)
```

I have reduced my code to trimmed version below and continue to get the error.

``` js
router.post('/', function(req, res, next){
    sequelize.transaction(function(t) {
        User.find({
            where : {
                email : email
            },
            transaction : t
        }).complete(function(err, user){
            t.commit()
                .complete(function() {
                    res.status(200).json('hi');
                });
        });
    });
});
```

Dialect: PG

What am I missing?

**Comment by jbarros35** [comment]
I had the same issue here, sequelize.transaction is undefined.
router.post('/', secret.ensureAuthorized, function(req, res) {
	console.log(sequelize.transaction);
}

log printed:
undefined

**Comment by janmeier** [comment]
@jbarros35 please try to play ball with us and give us something to work on. When you post a 3 line sample there is no way I can attempt to reproduce your problem. 

Try to come up with a self contained example thst shows your issue 


My guess is that the sequelize variable is not a sequelize instance. If your are just requiring sequelize directly you get the sequelize constructor, not an instance. You have to instantiate it with connection details first

**Comment by jbarros35** [comment]
POST /api/posts/ 200 38.196 ms - 231
Unhandled rejection Error: commit has been called on this transaction(c457e532-b
164-43dc-9b0e-432be031fe36), you can no longer use it

sequelize.transaction({autocommit: false}, function (t) {		
		
		return models.post.build().updateAttributes({
				title: req.body.title,
				shortdescription: req.body.description.substring(0,255),
				description: req.body.description,
				titleImage: req.body.titleImage, 
				link: req.body.link,
				userid: req.body.userid	
			}, {transaction: t}).then(function(post){
				newpost = post;	
				// create categories
				var tags = req.body.categories;
				 
				models.hashtag.bulkCreate(tags, {transaction: t}).then(function(){
					newpost.setTags(tags, {transaction: t});
				});			
		});
		
		
	}).then(function (result) {
	    // Transaction has been committed
	    // result is whatever the result of the promise chain returned to the transaction callback is
	    if (newpost) {
			res.json(newpost);
		}
	    console.log(result);
	}).catch(function (e) {
	    // Transaction has been rolled back
	    // err is whatever rejected the promise chain returned to the transaction callback is
		throw e;
	});

**Comment by janmeier** [comment]
Posting the same code in multiple issues will not get you an answer faster @jbarros35 !
