### ISSUE TITLE
Batch Model Imports in 2.0.0-rc2 Broken?

### ISSUE THREAD

**Issue by maximilianschmitt** [sequelize/sequelize#2446]
Hi, im using [this method](http://sequelizejs.com/articles/express#models-index-js) to import my models and with the 2.0.0-rc2 it doesn't seem to longer work. I'm getting this error on start up:

```
util.js:556
  ctor.prototype = Object.create(superCtor.prototype, {
                          ^
TypeError: Object prototype may only be an Object or null
    at Function.create (native)
    at Object.exports.inherits (util.js:556:27)
    at module.exports.Model.init (/vagrant/node_modules/sequelize/lib/model.js:230:10)
    at module.exports.Sequelize.define (/vagrant/node_modules/sequelize/lib/sequelize.js:483:38)
    at DocumentEmailInvite (/vagrant/app/models/document-email-invite.js:4:41)
```

This is my model file:

``` js
'use strict';

var DocumentEmailInvite = function(sequelize, DataTypes) {
	var DocumentEmailInvite = sequelize.define('DocumentEmailInvite',
		{
			email: DataTypes.STRING
		},
		{
			getterMethods: {
				type: function() {
					return 'email';
				}
			},
			classMethods: {
				associate: function(models) {
					DocumentEmailInvite.belongsTo(models.Document);
					DocumentEmailInvite.belongsTo(models.User, { as: 'Issuer' });
				}
			}
		}
	);

	return DocumentEmailInvite;
};

module.exports = DocumentEmailInvite;
```

I was using 2.0.0-dev13 before and didn't get that error. Did anything change with sequelize.import? Thanks for your help! :)

**Comment by janmeier** [comment]
Canoot reproduce, closing
