### ISSUE TITLE
SequelizeDatabaseError: error: syntax error at or near "BIGSERIAL"

### ISSUE THREAD

**Issue by danielstjules** [sequelize/sequelize#2492]
Hi there! I've been playing around with the latest RC for sequelize and noticed that I couldn't create tables with a BIGINT UNSIGNED primary key. I haven't gone through all of the commits since the tag (https://github.com/sequelize/sequelize/compare/v2.0.0-rc2...master) but it doesn't seem to be fixed in master. Here's an example:

``` javascript
"use strict";
module.exports = {
  up: function(migration, DataTypes, done) {
    migration.createTable("Transaction", {
      id: {
        type: DataTypes.BIGINT.UNSIGNED,
        allowNull: false,
        autoIncrement: true,
        primaryKey: true
      },
      createdAt: {
        type: DataTypes.DATE,
        allowNull: false
      },
      updatedAt: {
        type: DataTypes.DATE,
        allowNull: false
      }
    }).done(done);
  },
  down: function(migration, DataTypes, done) {
    migration.dropTable("Transactions").done(done);
  }
};
```

```
20141027211701-create-transaction.js
Completed in 3ms
Possibly unhandled SequelizeDatabaseError: error: syntax error at or near "BIGSERIAL"
  at [object Object].module.exports.Query.formatError (/git/project/node_modules/sequelize/lib/dialects/postgres/query.js:278:16)
  at [object Object].<anonymous> (/git/project/node_modules/sequelize/lib/dialects/postgres/query.js:63:21)
  at [object Object].EventEmitter.emit (events.js:95:17)
  at [object Object].Query.handleError (/git/project/node_modules/pg/lib/query.js:101:8)
  at [object Object].<anonymous> (/git/project/node_modules/pg/lib/client.js:176:26)
  at [object Object].EventEmitter.emit (events.js:95:17)
  at Socket.<anonymous> (/git/project/node_modules/pg/lib/connection.js:109:12)
  at Socket.EventEmitter.emit (events.js:95:17)
  at Socket.<anonymous> (_stream_readable.js:746:14)
  at Socket.EventEmitter.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:408:10)
  at emitReadable (_stream_readable.js:404:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at Socket.Readable.push (_stream_readable.js:127:10)
  at TCP.onread (net.js:526:21)
```

**Comment by thirumal** [comment]
Just FYI for others who come searching via Google. Even declaring INTEGER.UNSIGNED as your primary key with auto increment is not valid, this translates into UNSIGNED SERIAL which is not a valid data type.

**Comment by falmp** [comment]
For the record, it doesn't need to be auto increment. `INTEGER.UNSIGNED` with `primaryKey: true` and `allowNull: false` will throw that error.

```
var User = sequelize.define('User', {
    id: { type: DataTypes.INTEGER.UNSIGNED, allowNull: false, primaryKey: true },
    name: { type: DataTypes.STRING, allowNull: false },
    email: { type: DataTypes.STRING, allowNull: false }
  });
```

```
2015-03-04T05:29:42.079Z - debug: Executing (default): CREATE TABLE IF NOT EXISTS "Users" ("id" INTEGER UNSIGNED NOT NULL , "name" VARCHAR(255) NOT NULL, "email" VARCHAR(255) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));
Possibly unhandled SequelizeDatabaseError: syntax error at or near "UNSIGNED"
```

I suppose this could be in the documentation (using PostgreSQL here).

**Comment by falmp** [comment]
Well, actually, not even `primaryKey: true` or `allowNull: false` is needed to trigger the error. Is this a problem with PostgreSQL?

```
var SearchProcess = sequelize.define("SearchProcess", {
    code: { type: DataTypes.STRING, allowNull: false },
    title: { type: DataTypes.STRING, allowNull: false },
    totalItems: { type: DataTypes.INTEGER.UNSIGNED, allowNull: false },
    completedItems: { type: DataTypes.INTEGER.UNSIGNED, allowNull: false }
  });
```

```
2015-03-04T05:38:05.652Z - debug: Executing (default): CREATE TABLE IF NOT EXISTS "SearchProcesses" ("id"   SERIAL , "code" VARCHAR(255) NOT NULL, "title" VARCHAR(255) NOT NULL, "totalItems" INTEGER UNSIGNED NOT NULL, "completedItems" INTEGER UNSIGNED NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "deletedAt" TIMESTAMP WITH TIME ZONE, "UserId" INTEGER REFERENCES "Users" ("id") ON DELETE SET NULL ON UPDATE CASCADE, PRIMARY KEY ("id"));
Possibly unhandled SequelizeDatabaseError: syntax error at or near "UNSIGNED"
```

**Comment by mickhansen** [comment]
@falmp PG doesn't have UNSIGNED afaik.

**Comment by falmp** [comment]
Hmm, indeed. Wouldn't it be better if Sequelize abstract this and treat it accordingly?

**Comment by mickhansen** [comment]
@falmp perhaps, personally i don't like it when things fail silently.

**Comment by falmp** [comment]
Well, me neither. :) But on this case I believe one of the purposes of an ORM is to abstract the underlying implementation, so we could easily change the dialect and not worry about it. What do you think?

**Comment by falmp** [comment]
For instance, on the express-example application, you use SQLite on development and MySQL on test and production (https://github.com/sequelize/express-example/blob/master/config/config.json). On a real application you could use MySQL on test and production, with UNSIGNED fields, and PostgreSQL on development - that would trigger this error.

**Comment by mickhansen** [comment]
@falmp I generally agree, but i also think it might be too utopian. MySQL doesn't support JSON, SQLITE doesnt support subjoins etc. If you're using more advanced features you're f*ed anyway.

But yeah, for UNSIGNED an abstraction would probably be fine.

**Comment by mickhansen** [comment]
Perhaps normalize and log a warning.

**Comment by falmp** [comment]
Maybe a note about it on the documentation would be fine too (you do state JSON, ARRAY, etc. being available only in PostgreSQL). :)
