### ISSUE TITLE
use sequelize in node-webkit

### ISSUE THREAD

**Issue by jackiesun8** [sequelize/sequelize#2642]
When i use sequelize in node-webkit and call sync() method on returned model I encounter below error:
Possibly unhandled Error: TypeError: Illegal invocation
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler](E:workspacevagrant_datapomelo-toolsnode_modulessequelizenode_modulesbluebirdjsmainpromise.js:670:58)
    at Promise$_settlePromiseAt (E:\workspace\vagrant_data\pomelo-tools\node_modules\sequelize\node_modules\bluebird\js\main\promise.js:826:14)
    at Promise._settlePromiseAt (E:\workspace\vagrant_data\pomelo-tools\node_modules\sequelize\lib\promise.js:66:18)
    at Promise$_settlePromises [as _settlePromises](E:workspacevagrant_datapomelo-toolsnode_modulessequelizenode_modulesbluebirdjsmainpromise.js:969:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer](E:workspacevagrant_datapomelo-toolsnode_modulessequelizenode_modulesbluebirdjsmainasync.js:75:12)
    at Async$consumeFunctionBuffer (E:\workspace\vagrant_data\pomelo-tools\node_modules\sequelize\node_modules\bluebird\js\main\async.js:38:14)
    at process._tickCallback (node.js:382:11) E:\workspace\vagrant_data\pomelo-tools\node_modules\sequelize\node_modules\bluebird\js\main\capture…:95
How to solve this problem?

**Comment by fjcero** [comment]
I have a similar issue. @jackiesun8 what do you mean with `node-main`, which is the content of that script? I'm able to run `sync()` method but the next error is happening when I tried to do a `save()` or `get()`

```js
/Users/fjcero/project/node_modules/sequelize/node_modules/bluebird/js/main/captured_trace.js:478 Unhandled rejection Error: TypeError: Illegal invocation
  at Object.ensureErrorObject (/Users/fjcero/project/node_modules/sequelize/node_modules/bluebird/js/main/util.js:228:20)
  at Promise._rejectCallback (/Users/fjcero/project/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:416:22)
  at Promise._settlePromiseFromHandler (/Users/fjcero/project/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:460:17)
  at Promise._settlePromiseAt (/Users/fjcero/project/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:530:18)
  at Promise._settlePromises (/Users/fjcero/project/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:646:14)
  at Async._drainQueue (/Users/fjcero/project/node_modules/sequelize/node_modules/bluebird/js/main/async.js:177:16)
  at Async._drainQueues (/Users/fjcero/project/node_modules/sequelize/node_modules/bluebird/js/main/async.js:187:10)
  at Immediate.Async.drainQueues [as _onImmediate] (/Users/fjcero/project/node_modules/sequelize/node_modules/bluebird/js/main/async.js:15:14)
  at processImmediate [as _immediateCallback] (timers.js:321:17)
```

**Comment by jackiesun8** [comment]
@fjcero please refer to node-webkit document about node-main

**Comment by fjcero** [comment]
@jackiesun8 OK.
