### ISSUE TITLE
[rc3]  many-to-many Object [object SequelizeModel] has no method 'get'

### ISSUE THREAD

**Issue by dylanfoster** [sequelize/sequelize#2669]
my model

``` javascript
"use strict";

module.exports = function(sequelize, dataTypes){
  var Projects = sequelize.define("Projects", {
    name: dataTypes.STRING,
    start: dataTypes.DATE,
    end: dataTypes.DATE,
    keywords: dataTypes.ARRAY(dataTypes.STRING),
    status: dataTypes.STRING
  }, {
    classMethods: {
      associate: function(models){
        Projects.hasMany(models.Users);
      }
    }
  });
  return Projects;
};
```

my test

``` javascript
  it("has many users", function(done){
    Projects.create({ name: "project A" }).then(function(project){
      Users.create({ name: "John Smith" }).then(function(userA){
        Users.create({ name: "Jane Doe" }).then(function(userB){
          project.setUsers([userA, userB]).then(project.getUsers)
          .then(function(user){
            expect(user[0].name).to.eql("John Smith");
            expect(user[1].name).to.eql("Jane Doe");
            done();
          });
        });
      });
    });
  });
```

This works in `rc2` but is broken in `rc3`

Full Stack;

``` shell
Possibly unhandled TypeError: Object [object SequelizeModel] has no method 'get'
    at module.exports.HasManyDoubleLinked.injectGetter (/Users/Shared/git/dossier/node_modules/sequelize/lib/associations/has-many-double-linked.js:35:65)
    at obj.(anonymous function) (/Users/Shared/git/dossier/node_modules/sequelize/lib/associations/has-many.js:330:43)
    at tryCatch1 (/Users/Shared/git/dossier/node_modules/sequelize/node_modules/bluebird/js/main/util.js:45:21)
    at Promise$_callHandler [as _callHandler] (/Users/Shared/git/dossier/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:660:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/Users/Shared/git/dossier/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:675:18)
    at Promise$_settlePromiseAt (/Users/Shared/git/dossier/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:845:14)
    at Promise._settlePromiseAt (/Users/Shared/git/dossier/node_modules/sequelize/lib/promise.js:66:18)
    at Promise$_settlePromises [as _settlePromises] (/Users/Shared/git/dossier/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:988:14)
    at Promise.b (domain.js:183:18)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/Users/Shared/git/dossier/node_modules/sequelize/node_modules/bluebird/js/main/async.js:77:12)
    at Async$consumeFunctionBuffer (/Users/Shared/git/dossier/node_modules/sequelize/node_modules/bluebird/js/main/async.js:40:14)
```

**Comment by tcoulter** [comment]
I'm receiving a similar error. How would you fix his model so that it's scoped properly? 

I'm coming from an older version of sequelize and now migration doesn't want to work.

**Comment by mickhansen** [comment]
@tcoulter well it doesn't have anything to do with his model, it's how javascript handles the `this` reference.
