### ISSUE TITLE
Problem running migration: Possibly unhandled SequelizeUniqueConstraintError

### ISSUE THREAD

**Issue by grahamb** [sequelize/sequelize#2722]
I'm having an issue running migrations. I'm getting `Problem running migration: Possibly unhandled SequelizeUniqueConstraintError`. The migration appears to have run (the columns were created) but there's no entry for the migration in the SequelizeMeta table.

I'm on Postgres, but I've had the same error with sqlite. Sequelize 2.0.0-rc3

```
± express-app on master(bcaed75::23 hours ago) ↑1 ✖  npm-exec sequelize db:migrate

Sequelize [Node: 0.10.33, CLI: 0.3.3, ORM: 2.0.0-rc2]

Loaded configuration file 'config/config.json'.
Using environment 'development'.
[22:15:01] Using sequelizefile ~/Dropbox/code/personal/pj/express-app/node_modules/sequelize-cli/lib/sequelizefile.js
[22:15:01] Starting 'db:migrate'...
EventEmitter#success|ok is deprecated, please use promise-style instead.
EventEmitter#failure|fail|error is deprecated, please use promise-style instead.
[22:15:01] Finished 'db:migrate' after 43 ms
Running migrations...
20141211214928-add-program-columns.js
Possibly unhandled SequelizeUniqueConstraintError:
  at [object Object].module.exports.Query.formatError (/Users/grahamb/Dropbox/code/personal/pj/express-app/node_modules/sequelize/lib/dialects/postgres/query.js:264:18)
  at [object Object].<anonymous> (/Users/grahamb/Dropbox/code/personal/pj/express-app/node_modules/sequelize/lib/dialects/postgres/query.js:63:21)
  at [object Object].emit (events.js:95:17)
  at [object Object].Query.handleError (/Users/grahamb/Dropbox/code/personal/pj/express-app/node_modules/pg/lib/query.js:99:8)
  at [object Object].<anonymous> (/Users/grahamb/Dropbox/code/personal/pj/express-app/node_modules/pg/lib/client.js:163:26)
  at [object Object].emit (events.js:95:17)
  at Socket.<anonymous> (/Users/grahamb/Dropbox/code/personal/pj/express-app/node_modules/pg/lib/connection.js:109:12)
  at Socket.emit (events.js:95:17)
  at Socket.<anonymous> (_stream_readable.js:764:14)
  at Socket.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:426:10)
  at emitReadable (_stream_readable.js:422:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at Socket.Readable.push (_stream_readable.js:127:10)
  at TCP.onread (net.js:528:21)
```

The migration file is [here](https://gist.github.com/9d007621291e8a296b3a).

**Comment by preetamshah** [comment]
what was the fix you did for SequelizeMeta table?

**Comment by grahamb** [comment]
No clue, sorry - you're commenting on a nearly five year old issue. I'm not using Sequelize anymore.
