### ISSUE TITLE
suddenly... Possibly unhandled TypeError: Cannot call method 'commit' of undefined

### ISSUE THREAD

**Issue by Ahmed-90** [sequelize/sequelize#2741]
Hi,

I'm building a Bot (aka daemon) which listen to a server via TCP socket and register/update data to DB (using Sqlite3 in dev)

the it works fine for hours data is correct the database works like a charm.. then suddenly i get this error every time there is new data to commit..:
```
Possibly unhandled TypeError: Cannot call method 'commit' of undefined
    at Object.<anonymous> (/home/nodejs/a90ts3/node_modules/sequelize/lib/model.js:1164:33)
    at Object.finallyHandler (/home/nodejs/a90ts3/node_modules/sequelize/node_modules/bluebird/js/main/finally.js:63:31)
    at tryCatch1 (/home/nodejs/a90ts3/node_modules/sequelize/node_modules/bluebird/js/main/util.js:45:21)
    at Promise$_callHandler [as _callHandler] (/home/nodejs/a90ts3/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:660:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/home/nodejs/a90ts3/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:675:18)
    at Promise$_settlePromiseAt (/home/nodejs/a90ts3/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:845:14)
    at Promise._settlePromiseAt (/home/nodejs/a90ts3/node_modules/sequelize/lib/promise.js:66:18)
    at Promise$_settlePromises [as _settlePromises] (/home/nodejs/a90ts3/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:988:14)
    at Promise$_rejectPromises [as _rejectPromises] (/home/nodejs/a90ts3/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:981:10)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/home/nodejs/a90ts3/node_modules/sequelize/node_modules/bluebird/js/main/async.js:77:12)
    at Async$consumeFunctionBuffer (/home/nodejs/a90ts3/node_modules/sequelize/node_modules/bluebird/js/main/async.js:40:14)
    at process._tickCallback (node.js:419:13)

```

i used sequelize-cli to do ```sequelize init``` and generated the model and the migration etc...

here is my code to create or update
```JavaScript
		db.timeOn.findOrCreate({
			where: { uid: cached.data.client_unique_identifier},
			defaults: {
				dbid: cached.data.client_database_id,
				uid: cached.data.client_unique_identifier,
				nick: cached.data.client_nickname,
				time: timeOn
			}
		}).spread(function(user, created) {
			if(!created){
				user.time += timeOn;
				util.log(util.inspect(user.time));
				user.save();
			}
			delete onlineClients[data.clid], user, created;
		});
```

am officially stuck :smiley: since it works like a charm for over 6 hours then this... tried it in 2 different sessions... 

Thanks in advance

//add forgot to mention the version
```Json
    "sequelize": "^2.0.0-rc3",
    "sequelize-cli": "^0.3.3",
```

**Comment by janmeier** [comment]
@Ahmed-90 please comment here / reopen if you issue is not solved on master

**Comment by jpotts18** [comment]
This might be a dumb answer, but when I closed my Sqlite Browser it started working again. I was causing the Sqlite to be busy

**Comment by mickhansen** [comment]
@jpotts18 The general issue was that we didn't handle bad connections very well in the findOrCreate code :)
