### ISSUE TITLE
save fails if model contains attribute named length

### ISSUE THREAD

**Issue by ebrian** [sequelize/sequelize#2778]
I'm executing some really simple logic that works in 2.0.0-rc2 but not in >= 2.0.0-rc3.

```js
models.mail_items
    .findOne({
	    where : {
	        mail_item_id : 12
	    }
    }).then(function(item) {
	    item.mail_package_id = 2;

	    return item.save();
    });
```

If I add

```js
.then(null, function(err) { console.log(err.stack); })
```

onto item.save();

I get this stack:
```
RangeError: Invalid array length
    at /media/m/2-WorkingTrees/myrvmail-node/front/node_modules/sequelize/lib/dialects/abstract/query-generator.js:298:34
    at forOwn (/media/m/2-WorkingTrees/myrvmail-node/front/node_modules/sequelize/node_modules/lodash/dist/lodash.js:2105:15)
    at Function.forEach (/media/m/2-WorkingTrees/myrvmail-node/front/node_modules/sequelize/node_modules/lodash/dist/lodash.js:3302:9)
    at Object.module.exports.QueryGenerator.updateQuery (/media/m/2-WorkingTrees/myrvmail-node/front/node_modules/sequelize/lib/dialects/abstract/query-generator.js:297:17)
    at module.exports.QueryInterface.update (/media/m/2-WorkingTrees/myrvmail-node/front/node_modules/sequelize/lib/query-interface.js:534:35)
    at /media/m/2-WorkingTrees/myrvmail-node/front/node_modules/sequelize/lib/instance.js:601:43
From previous event:
    at /media/m/2-WorkingTrees/myrvmail-node/front/node_modules/sequelize/lib/instance.js:578:25
From previous event:
    at module.exports.Instance.save (/media/m/2-WorkingTrees/myrvmail-node/front/node_modules/sequelize/lib/instance.js:500:23)
    at null.<anonymous> (/media/m/2-WorkingTrees/myrvmail-node/front/api/controllers/striker/MailController.js:232:42)
    at Promise._settlePromiseAt (/media/m/2-WorkingTrees/myrvmail-node/front/node_modules/sequelize/lib/promise.js:66:18)
From previous event:
    at Function.Promise$Bind [as bind] (/media/m/2-WorkingTrees/myrvmail-node/front/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:274:9)
    at module.exports.Model.findAll (/media/m/2-WorkingTrees/myrvmail-node/front/node_modules/sequelize/lib/model.js:684:20)
    at module.exports.Model.findOne (/media/m/2-WorkingTrees/myrvmail-node/front/node_modules/sequelize/lib/model.js:779:36)
    at /media/m/2-WorkingTrees/myrvmail-node/front/api/controllers/striker/MailController.js:224:34
    at _fulfilled (/media/m/2-WorkingTrees/myrvmail-node/front/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/media/m/2-WorkingTrees/myrvmail-node/front/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/media/m/2-WorkingTrees/myrvmail-node/front/node_modules/q/q.js:749:13)
    at /media/m/2-WorkingTrees/myrvmail-node/front/node_modules/q/q.js:509:49
    at flush (/media/m/2-WorkingTrees/myrvmail-node/front/node_modules/q/q.js:108:17)
```

Not sure if it's a real issue or just me being dumb.

**Comment by fhc023** [comment]
Could paste the model schema. I have got the same error because of defining a field which name is `length`.

**Comment by ebrian** [comment]
Here is my schema:
```js
var moment = require('moment');

module.exports = function(sequelize, DataTypes) {
    return sequelize
        .define('mail_items', {
            mail_item_id : {
                type : DataTypes.INTEGER,
                primaryKey : true,
                autoIncrement : true
            },

            mail_package_id : DataTypes.INTEGER,
            account_id : DataTypes.INTEGER,
            mail_item_type_id : DataTypes.INTEGER,
            sender : DataTypes.STRING,
            weight : DataTypes.DECIMAL(4,2),
            length : DataTypes.INTEGER,
            width : DataTypes.INTEGER,
            height : DataTypes.INTEGER,
            scan_status : DataTypes.INTEGER,
            scan_priority : DataTypes.INTEGER,
            scan_requested : DataTypes.DATE,
            trash_status : DataTypes.INTEGER,
            trash_processed : DataTypes.DATE,
            user_created : DataTypes.INTEGER,
            date_created : DataTypes.DATE,
            user_modified : DataTypes.INTEGER,
            date_modified : DataTypes.DATE
        },
        {
            hooks : {
                beforeCreate : function(mail_item) {
                    mail_item.date_created = moment().format('YYYY-MM-DD HH:mm:ss');
                    mail_item.date_modified = moment().format('YYYY-MM-DD HH:mm:ss');
                },

                beforeUpdate : function(mail_item) {
                    mail_item.date_modified = moment().format('YYYY-MM-DD HH:mm:ss');
                }
            }
        }
    );
};
```

**Comment by ebrian** [comment]
Yep, look at that. I have a field called length.

**Comment by mickhansen** [comment]
It appears there's a bug, because you should obviously be allowed to have an attribute named length.

**Comment by ebrian** [comment]
To clarify, it's the save that fails.

**Comment by mickhansen** [comment]
@ebrian Ah, of course, thank you
