### ISSUE TITLE
Unique Constraint Error crashing application

### ISSUE THREAD

**Issue by kdelemme** [sequelize/sequelize#2844]
Hello guys,

I am coming across an issue where sequelize throws an error whenever I violate a unique index.

Here's the stack trace:

```
{ [Error: ER_DUP_ENTRY: Duplicate entry '10592690' for key 'UniqueMessageId']
  code: 'ER_DUP_ENTRY',
  errno: 1062,
  sqlState: '23000',
  index: 0,
  sql: 'INSERT INTO `messages` (`id`,`message_id`,`created_at`,`updated_at`,`deleted_at`) VALUES (....);
}

Users/kevin/bn.workspaces/mmp/bn.omniture-data-gatherer/node_modules/mysql/lib/protocol/Parser.js:82
        throw err;
              ^
ReferenceError: callee is not defined
    at module.exports.Query.formatError (/Users/kevin/bn.workspaces/mmp/bn.omniture-data-gatherer/node_modules/sequelize/lib/dialects/mysql/query.js:115:21)
    at Query._callback (/Users/kevin/bn.workspaces/mmp/bn.omniture-data-gatherer/node_modules/sequelize/lib/dialects/mysql/query.js:38:23)
    at Query.Sequence.end (/Users/kevin/bn.workspaces/mmp/bn.omniture-data-gatherer/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query.ErrorPacket (/Users/kevin/bn.workspaces/mmp/bn.omniture-data-gatherer/node_modules/mysql/lib/protocol/sequences/Query.js:93:8)
    at Protocol._parsePacket (/Users/kevin/bn.workspaces/mmp/bn.omniture-data-gatherer/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/Users/kevin/bn.workspaces/mmp/bn.omniture-data-gatherer/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/Users/kevin/bn.workspaces/mmp/bn.omniture-data-gatherer/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/kevin/bn.workspaces/mmp/bn.omniture-data-gatherer/node_modules/mysql/lib/Connection.js:82:28)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
```

You can reproduce this issue by creating a db with a `messages` table with id, message_id, created_at, updated_at, deleted_at columns with a unique constraint on `message_id` and by running this script:

```
var Sequelize = require('sequelize');

var sequelize = new Sequelize('db', 'user', 'passwd', { dialect: 'mysql' });

var Message = sequelize.define('message', {
  id: {
    type: Sequelize.BIGINT(20),
    primaryKey: true,
    autoIncrement: true
  },
  message_id: { 
    type: Sequelize.INTEGER,
    unique: 'uniqueMessageIndex'
  }
},
{
  timestamps: true,
  paranoid: true,
  underscored: true
});

var data = [{ message_id: 1}, { message_id: 2}, { message_id: 3}, { message_id: 4}];

Message.bulkCreate(data).then(function() {
  return Message.bulkCreate(data);
}).error(function(err) {
  console.log(err);
  console.log('KO');
});
``` 

And this is the migration script:

```
up: function (migration, Datatypes, done) {
  migration.createTable('messages', {
    id: {
      type: Datatypes.BIGINT(20),
      primaryKey: true,
      autoIncrement: true
    },
    message_id: { 
      type: Datatypes.INTEGER,
      unique: 'uniqueMessageIndex'
    }
  }).then(function() {
    return migration.addIndex('messages', ['message_id'], { indexName: 'UniqueMessageId', indicesType: 'UNIQUE' });
  }.then(done);
}
```

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/blob/master/lib/dialects/mysql/query.js#L118 seems to be the culprit.

Guess all that code was written with an instance calling it in mind, @janmeier?

**Comment by janmeier** [comment]
Callee is a model as far as I remember so it seems that bulk create is just not passing the model correctly. 

This also means that it will fail for raw queries without a callee though

**Comment by mickhansen** [comment]
@janmeier the presence of a `__options` check usually indicates an instance, https://github.com/sequelize/sequelize/blob/master/lib/instance.js#L35

**Comment by mickhansen** [comment]
A check is now in https://github.com/sequelize/sequelize/blob/master/lib/dialects/mysql/query.js#L118, should be fixed, re-open otherwise.
