### ISSUE TITLE
Cannot read property '__options' of null` doing bulk create 

### ISSUE THREAD

**Issue by stonecold123** [sequelize/sequelize#2855]
Please check out my table schema http://sqlfiddle.com/#!2/531667/2 I'm using mysql version 5.5

 I have two tables `post` and `choice`. The first one stores people's replies to threads and `choice` stores their vote options in the threads. People can cast more than one vote in a thread. I want to use `post_id` and `choice_id` as the composite primary keys for `choice` table but from what I have read in another thread, that isn't possible yet, so I add an auto-increment id field to the `choice` model
```
module.exports = function(sequelize,DataTypes){
  var choice = sequelize.define('choice', {
   id:{type:DataTypes.INTEGER,autoIncrement: true, primaryKey: true},
   post_id: DataTypes.INTEGER,
   choice_id:DataTypes.INTEGER,
  },
  {
    timestamps: false,
    freezeTableName: true,
    tableName: 'choice'

  });
  return choice;
}
```
But when I do a `bulk create` with this code, 

```
var db = require('./db/managedb');
socket.on("message",function(data){ 
  db.post.create({user_id:data[0].user_id,content:data[0].text,timestamp:new Date()}).then(function(post){
           var post_id = post.dataValues.post_id; // get last inserted post_id
           var object_arr = data.filter(function(item){  
              // create an array of objects for bulkCreate
               return 'choice_id' in item;
            }).map( function( item ){
              return { post_id:post_id,choice_id:item['choice_id'] }
           });     
           db.choice.bulkCreate(object_arr).then(function(result){ 
             // ****problem with bulk create***
              console.log(result);
           })           
  }) 
})
```
I'm getting this error:

```
Executing (default): INSERT INTO `post` (`user_id`,`content`,`timestamp`) VALUES ('90','trytrrtyrt','2015-01-07 17:40:09');

Executing (default): INSERT INTO `choice` (`id`,`choice_id`,`post_id`) VALUES (NULL,'389','43'),(NULL,'396','43');

/usr/nodejs/bin/node_modules/mysql/lib/protocol/Parser.js:82
        throw err;
              ^
TypeError: Cannot read property '__options' of null`

 at module.exports.Query.formatError (/usr/nodejs/bin/node_modules/sequelize/lib/dialects/mysql/query.js:11    8:36)
    at Query._callback (/usr/nodejs/bin/node_modules/sequelize/lib/dialects/mysql/query.js:38:23)
    at Query.Sequence.end (/usr/nodejs/bin/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query.ErrorPacket (/usr/nodejs/bin/node_modules/mysql/lib/protocol/sequences/Query.js:93:8)
    at Protocol._parsePacket (/usr/nodejs/bin/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/usr/nodejs/bin/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/usr/nodejs/bin/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/usr/nodejs/bin/node_modules/mysql/lib/Connection.js:82:28)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:745:14)`
```

Apparently the NULL value shouldn't be inserted into the `id` field. How can I fix that?
I have tried adding `omitNull: true` to the configuration but it isn't working.

Example of `object_arr` inserted into the table:
```
 [ { choice_id: '389',
    post_id: 53
  },
  { choice_id: '396',
    post_id: 53
  }
 ]
```

**Comment by mickhansen** [comment]
bulkCreate issue should be fixed by https://github.com/sequelize/sequelize/commit/530f28bc5292d8542cf729c59e4daf2efdbd9403

But apparently you're getting a unique error with the call.

**Comment by stonecold123** [comment]
Is it possible to make it not insert anything into the auto-increment id field, which is causing the error?

`Executing (default): INSERT INTO `choice` (`id`,`choice_id`,`post_id`) VALUES (NULL,'389','43'),(NULL,'396','43');`
