### ISSUE TITLE
Foo.save() with no changed fields causes SQL Syntax Error

### ISSUE THREAD

**Issue by stnever** [sequelize/sequelize#2894]
Hello,

I'm using version ^2.0.0rc3 . I retrieved an object from the database using `Foo.findOne({where:{id:12345}})` and then immediately called `save()` on the resulting instance. Since no fields were really changed, the generated SQL was
```sql
UPDATE `T_FOO` SET  WHERE `ID`=12345
```
...which is really a syntax error. I'd expect that, if no fields were changed, the update would not even happen. I suppose this wouldn't be an error; perhaps the result could include a `updated` flag that would indicate whether or not it happened.

If I call `.set('fullName', 'some other value')` to change a field, then the update command is well-formed and executes successfully.

Since I'm using a few non-default options, I have the following Mocha testcase that reproduces the problem. The filename needs to be changed, of course. The SQL to create the table is just:
```sql
create table T_FOO ( ID INTEGER NOT NULL PRIMARY KEY, FULL_NAME VARCHAR );
```

Test case:
```javascript
var Sequelize = require('sequelize');
var sequelize = new Sequelize('somedb', null, null, {
dialect: 'sqlite', storage: '/.../testfoo.sqlite3'});
var assert = require('assert');

var Foo = sequelize.define('Foo', {
  id: { type: Sequelize.INTEGER, field: 'ID' },
  fullName: { type: Sequelize.STRING, field: 'FULL_NAME'}
}, {
  timestamps: false, underscored: true, tableName: 'T_FOO'
})

describe('Foo', function() {

  it('should retrieve and save', function(done) {

    Foo.destroy({where:{id: 12345}})
      .then(function() {
        return Foo.build({
          id: 12345,
          fullName: 'Some Name'
        })
      })

      .then(function(foo) {
        console.log('Saving right after build')
        return foo.save();
      })

      .then(function(foo) {
        console.log('Retrieving after save')
        return Foo.findOne({where:{id: 12345}})
      })

      .then(function(retrievedFoo) {
        assert(retrievedFoo != null);
        console.log('Saving right after findOne')
        // if the following line is uncommented the test passes
        // retrievedFoo.set('fullName', 'Something Else')
        return retrievedFoo.save();
      })

      .then(
          function(ci) {
            console.log('Saved successfully')
            assert(ci != null);
            done();
          }
      ).done();

  })
})
```

Relevant output on my machine:
```
Executing (default): DELETE FROM `T_FOO` WHERE `ID`=12345
Saving right after build
Executing (default): INSERT INTO `T_FOO` (`ID`,`FULL_NAME`) VALUES (12345,'Some Name');
Retrieving after save
Executing (default): SELECT `ID` AS `id`, `FULL_NAME` AS `fullName` FROM `T_FOO` AS `Foo` WHERE `Foo`.`ID`=12345;
Saving right after findOne
Executing (default): UPDATE `T_FOO` SET  WHERE `ID`=12345

  1) Foo should retrieve and save:
     Uncaught SequelizeDatabaseError: SQLITE_ERROR: near "WHERE": syntax error
      at module.exports.Query.formatError (/.../sequelize/lib/dialects/sqlite/query.js:217:16)
      at /.../sequelize/lib/dialects/sqlite/query.js:53:31
      at Statement.errBack (/.../sqlite3/lib/sqlite3.js:16:21)
```

**Comment by mickhansen** [comment]
Was already fixed in https://github.com/sequelize/sequelize/commit/c7671687082cc8402a012cc39ed7cf8c7723dd2d
