### ISSUE TITLE
updateAttributes, partial update fails on validation on v2.0.0-rc7

### ISSUE THREAD

**Issue by OlivierCuyp** [sequelize/sequelize#2905]
I can't succeed to make a partial update with updateAttributes when there is required field(s).

Here an exemple of what I'm trying to achieve :

```js
var Invoice = sequelize.define('invoice', {
    invoice_number: {
      type: DataTypes.INTEGER,
      allowNull: false
    },
    total_in_cents:  DataTypes.INTEGER
});
```

The following piece code fails on invoice_number validation and I don't get what wrong in that code.

```js
Invoice.find({
  where: { invoice_number: 1}
})
.then(function (invoice) {
  return invoice.updateAttributes({
    total_in_cents: 1000
  });
})
```

The invoice exists and tried to limit the updated fields with the fields options, still the same error.

Here is the error message I get :

```
SequelizeDatabaseError: null value in column "invoice_number" violates not-null constraint
      at module.exports.Query.formatError (/Users/olivier/Projects/wooking/node_modules/sequelize/lib/dialects/postgres/query.js:302:16)
      at null.<anonymous> (/Users/olivier/Projects/wooking/node_modules/sequelize/lib/dialects/postgres/query.js:64:21)
      at EventEmitter.emit (events.js:95:17)
      at Query.handleError (/Users/olivier/Projects/wooking/node_modules/pg/lib/query.js:101:8)
      at null.<anonymous> (/Users/olivier/Projects/wooking/node_modules/pg/lib/client.js:176:26)
      at EventEmitter.emit (events.js:95:17)
      at Socket.<anonymous> (/Users/olivier/Projects/wooking/node_modules/pg/lib/connection.js:109:12)
      at Socket.EventEmitter.emit (events.js:95:17)
      at Socket.<anonymous> (_stream_readable.js:746:14)
      at Socket.EventEmitter.emit (events.js:92:17)
      at emitReadable_ (_stream_readable.js:408:10)
      at emitReadable (_stream_readable.js:404:5)
      at readableAddChunk (_stream_readable.js:165:9)
      at Socket.Readable.push (_stream_readable.js:127:10)
      at TCP.onread (net.js:528:21)
```

**Comment by mickhansen** [comment]
Hmm that is strange. Can you try showing the SQL outputted for the update?

**Comment by OlivierCuyp** [comment]
After re-checking my code, the issue comes from the fact the I didn't save my invoice in the first place.
I just build it then tries to updateAttributes like this:

```js
  var invoice = Invoice.build({
    invoice_number: 1,
    total_in_cents: 1000
  });
 
// Later on

  invoice.updateAttributes({
    total_in_cents: 1000
  });
```

Sorry about this ...

**Comment by mickhansen** [comment]
Ah yeah that'll do it :)
