### ISSUE TITLE
eager loading multiple associations

### ISSUE THREAD

**Issue by muuuub** [sequelize/sequelize#2926]
I'm writing a small expressjs app and I have the following sequelize associations:

    // Library model association
    Library.hasMany(models.Books, { as : "novels"  });
    
    // Book model association
    Book.belongsTo(models.Library);
    Book.hasMany(models.User, { as : 'borrowers', through: models.BookHistory });
    
    // User model association
    User.hasMany(models.Book, { as: 'rented_books', through: models.BookHistory }); 

I'm trying to fetch novels and their borrowing history at a certain library:

    models.Library.find( { where: { name: 'library1' }, include: [
            { model: models.Books, as: 'novels', where: { checked_out: false }, include: [
                    {model: models.User,  as: 'borrowers', through: models.BookHistory } 
           } ]
     }]).then(function(library) {
               // Send data back for rendering in view
               res.json( {'library': library});
     });

So that I can ask something specific like "Give me the first borrower for this novel": 

    // In display.html
    <span> {{ library.novels[10].borrowers[0].name }} </span>

But the 'inner' `include: [ model: models.User ... through: models.BookHistory]` seems to be causing the error:

````
Possibly unhandled TypeError: Object #<Object> has no method 'slice'
    at module.exports.validateIncludedElement (/home/vn/projs/express/src/app_express/node_modules/sequelize/lib/model.js:1993:55)
    at module.exports.validateIncludedElements (/home/vn/projs/express/src/app_express/node_modules/sequelize/lib/model.js:1953:63)
    at module.exports.validateIncludedElement (/home/vn/projs/express/src/app_express/node_modules/sequelize/lib/model.js:2044:34)
    at module.exports.validateIncludedElements (/home/vn/projs/express/src/app_express/node_modules/sequelize/lib/model.js:1953:63)
    at module.exports.validateIncludedElement (/home/vn/projs/express/src/app_express/node_modules/sequelize/lib/model.js:2044:34)
    at module.exports.validateIncludedElements (/home/vn/projs/express/src/app_express/node_modules/sequelize/lib/model.js:1953:63)
    at Promise.bind.then.then.then.then.QueryInterface.select.Utils._.defaults.type (/home/vn/projs/express/src/app_express/node_modules/sequelize/lib/model.js:703:36)
    at tryCatch1 (/home/vn/projs/express/src/app_express/node_modules/sequelize/node_modules/bluebird/js/main/util.js:45:21)
    at Promise$_callHandler [as _callHandler] (/home/vn/projs/express/src/app_express/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:660:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/home/vn/projs/express/src/app_express/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:675:18)
````

Removing the inner include avoids the error. Also, since a completely new library with brand new books don't have any borrowers yet, `BookHistory` would be empty. 

Is there a way eager load nested associations in sequelize?

Using sequelize 2.0.0-rc7

**Comment by mickhansen** [comment]
`include: [ model: models.User ... through: models.BookHistory]`
Should be:
`include: [ {model: models.User}]`

Include elements should either be a Model, an Association or an object containing a model property and optionally an as, where and include property.

You can't/don't need to define through on the include, you do that on the association call.

**Comment by mickhansen** [comment]
Hmm, only piece of code in `lib/model` that uses `slice` is https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1992 which is for `include.attributes` but i don't see you using attributes anywhere

**Comment by mickhansen** [comment]
@muuuub what was the issue? Your solution might help future users :)
