### ISSUE TITLE
lib error mysql not supported, even though using postgresql

### ISSUE THREAD

**Issue by recursor94** [sequelize/sequelize#2959]
I've been trying to follow the tutorial here

http://sequelizejs.com/articles/express#bin-www

but when I try to run the app after adding the sequelize code to the bin-www shell I encounter this error:

Error: The dialect mysql is not supported. (Error: Please install mysql package manually)
    at new module.exports.Sequelize (/home/andrew/projects/nodeblog/node_modules/sequelize/lib/sequelize.js:188:13)
    at Object.<anonymous> (/home/andrew/projects/nodeblog/models/index.js:9:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/andrew/project

**Comment by mickhansen** [comment]
Have you defined the dialect in the Sequelize options?

**Comment by recursor94** [comment]
Yes,  I have those set in app.js


var Sequelize = require('sequelize')

  , sequelize = new Sequelize('database_name', 'username', 'password', {  //I have no authentification information yet
      dialect: "postgres", // or 'sqlite', 'postgres', 'mariadb'
      port:    5432, // or 5432 (for postgres)
    });
 
sequelize
  .authenticate()
  .complete(function(err) {
    if (!!err) {
      console.log('Unable to connect to the database:', err);
    } else {
      console.log('Connection has been established successfully.');
    }
  });

**Comment by mickhansen** [comment]
Errors comes from here: https://github.com/sequelize/sequelize/blob/master/lib/dialects/mysql/connection-manager.js#L16
That codepath should really only be triggered if using mysql dialect. Very strange.

By the way `complete` is deprecated.

**Comment by recursor94** [comment]
The error doesn't appear,  by the way, if I run node app.js.

but when I run bin/www I get that error thrown at me.  I'm new to nodejs, so I'm still trying to figure out how everything works.

As a tangent I'm also a bit confused about authentification.  Installing pg creates a local database, correct?  I don't have a password or database name yet and I'm getting a refusal to connect error thrown at me.  How do I set the authentification information?

**Comment by mickhansen** [comment]
@recursor94 installing PG does NOT create a database for you. That only happens in sqlite since it will just use an in memory store. for PG you actually have to setup a database with credentials etc.

**Comment by recursor94** [comment]
Thank you for the information.  Here's a link to the www file if it helps identify the source of the problem

https://github.com/recursor94/simple-blog/blob/master/bin/www

**Comment by janmeier** [comment]
In config.json the dialect is set as mysql https://github.com/recursor94/simple-blog/blob/master/config/config.json
