### ISSUE TITLE
Model.findAll() - Error when ordering by nested included model attribute

### ISSUE THREAD

**Issue by shaunerikson** [sequelize/sequelize#2964]
Using version 2.0.0-rc2
Using mysql dialect

Here is my failing mocha unit test:

```
var Sequelize = require('sequelize');

var USER = 'root';
var PASSWD = 'mysqlrootpass2';
var DB_NAME = 'sequelize_test';

describe('ordering on nested include', function() {

	var sequalize;
	var Model1, Model2, Model3;

	before(function(done) {
		sequelize = new Sequelize(DB_NAME, USER, PASSWD, {});

		Model1 = sequelize.define('Model1', { name: Sequelize.STRING }, { timestamps: false });
		Model2 = sequelize.define('Model2', { name: Sequelize.STRING }, { timestamps: false });
		Model3 = sequelize.define('Model3', { name: Sequelize.STRING }, { timestamps: false });
		Model1.hasOne(Model2);
		Model2.hasOne(Model3);

		sequelize.sync({ force: true })
			.then(function() { done(); });
	});

	it('should (BUT DOES NOT) support ordering based on nested model', function(done) {
		Model1.findAll({ 
			include: [{ model: Model2, include: [ Model3 ] }],
			order: [ [ Model2, Model3, 'name' ] ] 
		})
		.catch(function(err) {
			done(err);
		});
	});
});
```

Here is the error I'm getting:
```
     TypeError: Cannot read property 'model' of undefined
      at Object.module.exports.QueryGenerator.quote (E:\Projects\_Personal\finances1\finances1\node_modules\sequelize\lib\dialects\abstract\query-generator.js:556:68)
      at Object.<anonymous> (E:\Projects\_Personal\finances1\finances1\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1081:38)
      at Array.forEach (native)
      at Object.module.exports.QueryGenerator.selectQuery (E:\Projects\_Personal\finances1\finances1\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1077:25)
      at module.exports.QueryInterface.select (E:\Projects\_Personal\finances1\finances1\node_modules\sequelize\lib\query-interface.js:579:35)
      at null.<anonymous> (E:\Projects\_Personal\finances1\finances1\node_modules\sequelize\lib\model.js:749:34)
      at tryCatch1 (E:\Projects\_Personal\finances1\finances1\node_modules\sequelize\node_modules\bluebird\js\main\util.js:43:21)
      at Promise$_callHandler [as _callHandler] (E:\Projects\_Personal\finances1\finances1\node_modules\sequelize\node_modules\bluebird\js\main\promise.js:649:13)
      at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (E:\Projects\_Personal\finances1\finances1\node_modules\sequelize\node_modules\bluebird\js\main\promise.js:663:18)
      at Promise$_settlePromiseAt (E:\Projects\_Personal\finances1\finances1\node_modules\sequelize\node_modules\bluebird\js\main\promise.js:826:14)
      at Promise._settlePromiseAt (E:\Projects\_Personal\finances1\finances1\node_modules\sequelize\lib\promise.js:66:18)
      at Promise$_settlePromises [as _settlePromises] (E:\Projects\_Personal\finances1\finances1\node_modules\sequelize\node_modules\bluebird\js\main\promise.js:969:14)
      at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (E:\Projects\_Personal\finances1\finances1\node_modules\sequelize\node_modules\bluebird\js\main\async.js:75:12)
      at Async$consumeFunctionBuffer (E:\Projects\_Personal\finances1\finances1\node_modules\sequelize\node_modules\bluebird\js\main\async.js:38:14)
      at process._tickCallback (node.js:419:13)
/
```

**Comment by mickhansen** [comment]
Have you tested on master?

**Comment by shaunerikson** [comment]
I gave it a shot, but being a relative noob, and developing on Windows, I unfortunately don't have time to fiddle with cygwin right now.

Here is the test that you could drop in test/include somewhere to see the issue:

```
 'use strict';

var chai = require('chai')
  , Sequelize = require('../../../index')
  , expect = chai.expect
  , Support = require(__dirname + '/../../support')
  , DataTypes = require(__dirname + '/../../../lib/data-types')
  , dialect = Support.getTestDialect()
  , config = require(__dirname + '/../../config/config')
  , datetime = require('chai-datetime')
  , _ = require('lodash')
  , moment = require('moment')
  , async = require('async')
  , current = Support.sequelize;

chai.use(datetime);
chai.config.includeStack = true;

describe(Support.getTestDialectTeaser('Include'), function() {
	describe('findAll', function () {
		describe('order', function () {
			describe('nested eagerly-loaded models with 1:1 association', function () {
				beforeEach(function(done) {
					this.Model1 = this.sequelize.define('Model1', { name: Sequelize.STRING }, { timestamps: false });
					this.Model2 = this.sequelize.define('Model2', { name: Sequelize.STRING }, { timestamps: false });
					this.Model3 = this.sequelize.define('Model3', { name: Sequelize.STRING }, { timestamps: false });
					this.Model1.hasOne(this.Model2);
					this.Model2.hasOne(this.Model3);
					return this.sequelize.sync({ force: true })
						.then(function() { done(); });
				});

				it('should be possible to order by attribute of nested model', function(done) {
					this.Model1.findAll({ 
						include: [{ model: this.Model2, include: [ this.Model3 ] }],
						order: [ [ this.Model2, this.Model3, 'name' ] ] 
					})
					.catch(function(err) {
						done(err);
					});
				});		
			});
 		});
 	});
});
```

**Comment by mickhansen** [comment]
Alright thanks, that still helps :)

**Comment by shaunerikson** [comment]
I moved the test into the test/include/findAll.test.js as you requested.

**Comment by sushantdhiman** [comment]
**SSCCE Template**
```js
/*
 * Copy this file to ./sscce.js
 * Add code from issue
 * npm run sscce-{dialect}
 */

var Sequelize = require('./index');
var sequelize = require('./test/support').createSequelizeInstance();


var Model1 = sequelize.define('Model1', { name: Sequelize.STRING }, { timestamps: false });
var Model2 = sequelize.define('Model2', { name: Sequelize.STRING }, { timestamps: false });
var Model3 = sequelize.define('Model3', { name: Sequelize.STRING }, { timestamps: false });
Model1.hasOne(Model2);
Model2.hasOne(Model3);

sequelize.sync({ force: true })
.then(() => {
  return Model1.findAll({
    include: [{ model: Model2, include: [ Model3 ] }],
    order: [ [ Model2, Model3, 'name' ] ],
    logging: console.log
  });
})
.then(console.log)
.catch(console.error);
```

**Output**
```bash
Using database:  sequelize-test-85
Executing (default): SELECT "Model1"."id", "Model1"."name", "Model2"."id" AS "Model2.id", "Model2"."name" AS "Model2.name", "Model2"."Model1Id" AS "Model2.Model1Id", "Model2.Model3"."id" AS "Model2.Model3.id", "Model2.Model3"."name" AS "Model2.Model3.name", "Model2.Model3"."Model2Id" AS "Model2.Model3.Model2Id" FROM "Model1s" AS "Model1" LEFT OUTER JOIN "Model2s" AS "Model2" ON "Model1"."id" = "Model2"."Model1Id" LEFT OUTER JOIN "Model3s" AS "Model2.Model3" ON "Model2"."id" = "Model2.Model3"."Model2Id" ORDER BY "Model2.Model3"."name";
[]

```
