### ISSUE TITLE
Sequelize does not work in io.js

### ISSUE THREAD

**Issue by yosuke-furukawa** [sequelize/sequelize#2966]
# Problem

I am trying to use io.js in my production.
I got a following error in a sequelize module.

```
TypeError: undefined is not a function
     at Promise.addListener (events.js:154:18)
     at Promise.on (/Users/yosuke/go/src/github.com/yosuke-furukawa/Hexi/node_modules/sequelize/lib/promise.js:118:31)
     at Promise.<anonymous> (/Users/yosuke/go/src/github.com/yosuke-furukawa/Hexi/node_modules/sequelize/lib/promise.js:268:10)
     at Array.forEach (native)
     at Promise.proxy (/Users/yosuke/go/src/github.com/yosuke-furukawa/Hexi/node_modules/sequelize/lib/promise.js:267:18)
     at Promise.proxySql (/Users/yosuke/go/src/github.com/yosuke-furukawa/Hexi/node_modules/sequelize/lib/promise.js:278:15)
     at Promise._then (/Users/yosuke/go/src/github.com/yosuke-furukawa/Hexi/node_modules/sequelize/lib/promise.js:57:10)
     at Promise$then [as then] (/Users/yosuke/go/src/github.com/yosuke-furukawa/Hexi/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:153:17)
     at Promise.error.Promise.failure.Promise.fail (/Users/yosuke/go/src/github.com/yosuke-furukawa/Hexi/node_modules/sequelize/lib/promise.js:200:15)
```

# cause

Sequelize/Promise calls EventEmitter.prototype.addEventListener directly. 
[https://github.com/sequelize/sequelize/blob/master/lib/promise.js#L127](https://github.com/sequelize/sequelize/blob/master/lib/promise.js#L127)

io.js has new method, `getMaxListeners` and the method is called in EventEmitter.prototype.addEventListener.
[https://github.com/iojs/io.js/blob/v1.x/lib/events.js#L154](https://github.com/iojs/io.js/blob/v1.x/lib/events.js#L154)

# solution

Sequelize/Promise need to inherit EventEmitter methods.

**Comment by timoxley** [comment]
https://github.com/iojs/io.js/issues/456

**Comment by ralphtheninja** [comment]
Brilliant report! :+1:

**Comment by sdepold** [comment]
I think there are actually some other tiny issues. First of all we cannot even install all dev dependencies with io.js as there is no compatible version of sqlite3.

**Comment by mickhansen** [comment]
Travis doesn't run io.js yet either.
We definitely want to support io.js but we are depending on a larger ecosystem (MSSQL, MYSQL, POSTGRES & SQLITE client libraries + travis support).

Ideally we don't want to extend from the event emitter since it's deprecated but will not removed untill 2.2+.

**Comment by mickhansen** [comment]
Perhaps we could mock `getMaxListeners` as a temporary fix untill we remove the event emitter completley?

**Comment by sdepold** [comment]
Adding the following line to promise.js will fix most of the issues:

```
Promise.prototype.getMaxListeners = EventEmitter.prototype.getMaxListeners;
``

**Comment by mickhansen** [comment]
@sdepold well that seems fine like a temporary fix.
@janmeier

**Comment by janmeier** [comment]
Yep, seems reasonable

**Comment by mickhansen** [comment]
@yosuke-furukawa could you test that fix and provide a PR?
The fix being: `Promise.prototype.getMaxListeners = EventEmitter.prototype.getMaxListeners;`

**Comment by yosuke-furukawa** [comment]
Sure. Currently I am busy, but I will check it later.  Thanks.

**Comment by yosuke-furukawa** [comment]
Oh, I reported the issue on io.js (https://github.com/iojs/io.js/issues/523), Ben solved the issue. https://github.com/iojs/io.js/pull/527

We had better to wait the next io.js release.

**Comment by sdepold** [comment]
Ah cool :)

**Comment by sdepold** [comment]
(We could try the nightly build?)

**Comment by mickhansen** [comment]
@yosuke-furukawa thank you :) in any case we will remove the deprecated event emitter code in 2.1 or 2.2

**Comment by mickhansen** [comment]
https://github.com/travis-ci/travis-ci/issues/3108

**Comment by sdepold** [comment]
oh nice! https://github.com/creationix/nvm/releases/tag/v0.23.0

**Comment by mickhansen** [comment]
@sdepold yep :) just waiting for travis to integrate it.

**Comment by sdepold** [comment]
1.0.3 has been released

**Comment by sdepold** [comment]
Mysql tests are still not working properly.

**Comment by ruimarinho** [comment]
The fix has been proposed for landing on 1.0.4. See https://github.com/iojs/io.js/issues/562.

**Comment by sdepold** [comment]
Ah ok!

**Comment by klaemo** [comment]
Has this been fixed with the release of 1.0.4? :)

**Comment by ralphtheninja** [comment]
I get this error

```
$ npm i
npm ERR! Linux 3.13.0-44-lowlatency
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "i"
npm ERR! node v1.0.4
npm ERR! npm  v2.3.0
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: sqlite3@'>=3.0.0 <3.1.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["2.0.0","2.0.1","2.0.2","2.0.3","2.0.4","2.0.5","2.0.6","2.0.7","2.0.8","2.0.9","2.0.10","2.0.11","2.0.12","2.0.13","2.0.14","2.0.15","2.0.16","2.0.17","2.0.18","2.1.0","2.1.1","2.1.2","2.1.3","2.1.4","2.1.5","2.1.7","2.1.8","2.1.9","2.1.10","2.1.11","2.1.12","2.1.13","2.1.14","2.1.15","2.1.16","2.1.17","2.1.18","2.1.19","2.2.0","2.2.1","2.2.2","2.2.3","2.2.4"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/lms/src/sequelize/npm-debug.log
```

**Comment by sdepold** [comment]
Yes. You won't be able to compile sqlite3 with iojs because of https://github.com/mapbox/node-sqlite3/blob/master/package.json#L50

**Comment by sdepold** [comment]
MariaDB is not compatible as well.

**Comment by sdepold** [comment]
Here is a related issue for sqlite3 https://github.com/mapbox/node-sqlite3/issues/385

**Comment by sdepold** [comment]
Current status on master for `make mysql`:

```
  1) [MYSQL] Configuration Connections problems should fail with a nice message when we don't have the correct server details:
     AssertionError: expected promise to be rejected with 'SequelizeInvalidConnectionError' but it was rejected with { Object (name, message, ...) }
      at /Users/sdepold/Projects/sequelize/sequelize/node_modules/chai-as-promised/lib/chai-as-promised.js:183:30
      at Promise._settlePromiseAt (/Users/sdepold/Projects/sequelize/sequelize/lib/promise.js:76:18)
      at /Users/sdepold/Projects/sequelize/sequelize/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
      at process._tickCallback (node.js:337:11)
  From previous event:
      at new SequelizePromise (/Users/sdepold/Projects/sequelize/sequelize/lib/promise.js:28:17)
      at ConnectionManager.getConnection (/Users/sdepold/Projects/sequelize/sequelize/lib/dialects/abstract/connection-manager.js:194:10)
      at module.exports.Sequelize.query (/Users/sdepold/Projects/sequelize/sequelize/lib/sequelize.js:675:85)
      at Context.<anonymous> (/Users/sdepold/Projects/sequelize/sequelize/test/integration/configuration.test.js:28:27)
      at callFn (/Users/sdepold/Projects/sequelize/sequelize/node_modules/mocha/lib/runnable.js:250:21)
      at Test.Runnable.run (/Users/sdepold/Projects/sequelize/sequelize/node_modules/mocha/lib/runnable.js:243:7)
      at Runner.runTest (/Users/sdepold/Projects/sequelize/sequelize/node_modules/mocha/lib/runner.js:373:10)
      at /Users/sdepold/Projects/sequelize/sequelize/node_modules/mocha/lib/runner.js:451:12
      at next (/Users/sdepold/Projects/sequelize/sequelize/node_modules/mocha/lib/runner.js:298:14)
      at /Users/sdepold/Projects/sequelize/sequelize/node_modules/mocha/lib/runner.js:308:7
      at next (/Users/sdepold/Projects/sequelize/sequelize/node_modules/mocha/lib/runner.js:246:23)
      at Immediate.<anonymous> (/Users/sdepold/Projects/sequelize/sequelize/node_modules/mocha/lib/runner.js:275:5)
      at Immediate._onImmediate (/Users/sdepold/Projects/sequelize/sequelize/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31)
      at processImmediate [as _immediateCallback] (timers.js:321:17)

  2) [MYSQL] Sequelize authenticate with an invalid connection triggers the actual adapter error:
     Uncaught AssertionError: expected 'RangeError: port should be > 0 and < 65536: 99999' to match /connect ECONNREFUSED/
      at null.<anonymous> (/Users/sdepold/Projects/sequelize/sequelize/node_modules/chai/lib/chai/core/assertions.js:892:10)
      at ctx.(anonymous function) (/Users/sdepold/Projects/sequelize/sequelize/node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at doAsserterAsyncAndAddThen (/Users/sdepold/Projects/sequelize/sequelize/node_modules/chai-as-promised/lib/chai-as-promised.js:293:33)
      at null.<anonymous> (/Users/sdepold/Projects/sequelize/sequelize/node_modules/chai-as-promised/lib/chai-as-promised.js:246:21)
      at ctx.(anonymous function) [as match] (/Users/sdepold/Projects/sequelize/sequelize/node_modules/chai/lib/chai/utils/overwriteMethod.js:48:33)
      at /Users/sdepold/Projects/sequelize/sequelize/test/integration/sequelize.test.js:130:40
      at Promise._settlePromiseAt (/Users/sdepold/Projects/sequelize/sequelize/lib/promise.js:76:18)
      at /Users/sdepold/Projects/sequelize/sequelize/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
      at process._tickCallback (node.js:337:11)
  From previous event:
      at new SequelizePromise (/Users/sdepold/Projects/sequelize/sequelize/lib/promise.js:28:17)
      at ConnectionManager.getConnection (/Users/sdepold/Projects/sequelize/sequelize/lib/dialects/abstract/connection-manager.js:194:10)
      at module.exports.Sequelize.query (/Users/sdepold/Projects/sequelize/sequelize/lib/sequelize.js:675:85)
      at module.exports.Sequelize.authenticate (/Users/sdepold/Projects/sequelize/sequelize/lib/sequelize.js:859:17)
      at Context.<anonymous> (/Users/sdepold/Projects/sequelize/sequelize/test/integration/sequelize.test.js:115:14)
      at Test.Runnable.run (/Users/sdepold/Projects/sequelize/sequelize/node_modules/mocha/lib/runnable.js:217:15)
      at Runner.runTest (/Users/sdepold/Projects/sequelize/sequelize/node_modules/mocha/lib/runner.js:373:10)
      at /Users/sdepold/Projects/sequelize/sequelize/node_modules/mocha/lib/runner.js:451:12
      at next (/Users/sdepold/Projects/sequelize/sequelize/node_modules/mocha/lib/runner.js:298:14)
      at /Users/sdepold/Projects/sequelize/sequelize/node_modules/mocha/lib/runner.js:308:7
      at next (/Users/sdepold/Projects/sequelize/sequelize/node_modules/mocha/lib/runner.js:246:23)
      at /Users/sdepold/Projects/sequelize/sequelize/node_modules/mocha/lib/runner.js:270:7
      at done (/Users/sdepold/Projects/sequelize/sequelize/node_modules/mocha/lib/runnable.js:206:5)
      at callFn (/Users/sdepold/Projects/sequelize/sequelize/node_modules/mocha/lib/runnable.js:261:7)
      at Hook.Runnable.run (/Users/sdepold/Projects/sequelize/sequelize/node_modules/mocha/lib/runnable.js:243:7)
      at next (/Users/sdepold/Projects/sequelize/sequelize/node_modules/mocha/lib/runner.js:258:10)
      at Immediate.<anonymous> (/Users/sdepold/Projects/sequelize/sequelize/node_modules/mocha/lib/runner.js:275:5)
      at Immediate._onImmediate (/Users/sdepold/Projects/sequelize/sequelize/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31)
      at processImmediate [as _immediateCallback] (timers.js:321:17)
```

**Comment by mickhansen** [comment]
@sdepold you can't really count on those tests locally though.

**Comment by sdepold** [comment]
OK!

**Comment by mickhansen** [comment]
#3090
