### ISSUE TITLE
Code error ?

### ISSUE THREAD

**Issue by skad** [sequelize/sequelize#2984]
Hi I'm trying to do a n:m relation

The two models are defining in another files

the relation :
```
module.exports = function (sequelize, DataTypes) {
    //Blade relations
    sequelize.models.blade.belongsToMany(sequelize.models.supplier, {
        through: sequelize.models.blade_has_supplier,
        foreignKey: 'id_blade',
        onDelete: 'cascade',
        onUpdate: 'cascade',
    });
    
    //supplier relations
    sequelize.models.supplier.belongsToMany(sequelize.models.blade, {
        through: sequelize.models.blade_has_supplier,
        foreignKey: 'id_supplier',
        onDelete: 'cascade',
        onUpdate: 'cascade',
    });
};
```

And after syn() having this error :
```
Executing (default): DROP TABLE IF EXISTS `blade_has_suppliers`;
Executing (default): CREATE TABLE IF NOT EXISTS `blade_has_suppliers` (`id_blade` INTEGER(10) NOT NULL , `id_supplier` INTEGER(10) NOT NULL , `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id_blade`, `id_supplier`), 
FOREIGN KEY (`id_blade`) REFERENCES `blades` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, 
FOREIGN KEY (`id_supplier`) REFERENCES `suppliers` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;

Possibly unhandled SequelizeDatabaseError: ER_CANT_CREATE_TABLE: Can't create table `test-nodejs`.`blade_has_suppliers` (errno: 150 "Foreign key constraint is incorrectly formed") at [object Object].module.exports.Query.formatError (/srv/http/test-nodejs/node_modules/sequelize/lib/dialects/mysql/query.js:158:16) at Query._callback (/srv/http/test-nodejs/node_modules/sequelize/lib/dialects/mysql/query.js:38:23) at Query.Sequence.end (/srv/http/test-nodejs/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24) at Query.ErrorPacket (/srv/http/test-nodejs/node_modules/mysql/lib/protocol/sequences/Query.js:93:8) at Protocol._parsePacket (/srv/http/test-nodejs/node_modules/mysql/lib/protocol/Protocol.js:271:23) at Parser.write (/srv/http/test-nodejs/node_modules/mysql/lib/protocol/Parser.js:77:12) at Protocol.write (/srv/http/test-nodejs/node_modules/mysql/lib/protocol/Protocol.js:39:16) at Socket.<anonymous> (/srv/http/test-nodejs/node_modules/mysql/lib/Connection.js:82:28) at Socket.emit (events.js:95:17) at Socket.global.__tracer.EventEmitter.emit (eval at createTracer (/usr/lib/node_modules/node-theseus/node-theseus.js:170:14), <anonymous>:1195:20)
```

Did I'm missing something ?

**Comment by mickhansen** [comment]
Can you show the through model aswell?
Are you using `force: true` with sync?

**Comment by skad** [comment]
Yes.

**Comment by mickhansen** [comment]
> Can you show the through model aswell?

**Comment by skad** [comment]
Yes shure :
```
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('blade_has_supplier', { 
    id_blade: {
      type: DataTypes.INTEGER(10),
      allowNull: false,
    },
    id_supplier: {
      type: DataTypes.INTEGER(10),
      allowNull: false,
    }
  });
};
```

**Comment by skad** [comment]
Finely i found the bug, my bad this is my fault:
i have missing
```
            autoIncrement: true,
            primaryKey: true,
```
into the supplier definition

sorry i close

**Comment by avtarnanrey** [comment]
@mickhansen removing `force: true` solved this issue for me. But can you please explain why this was causing the issue?
