### ISSUE TITLE
sequelize 2.0.0-rc8 breaks compatibility for PostgreSQL 9.1

### ISSUE THREAD

**Issue by marinewater** [sequelize/sequelize#2985]
`SequelizeDatabaseError: syntax error at or near "STACKED"`
This appears in a simple `findOne` query, which generates a query containing
```SQL
THEN GET STACKED DIAGNOSTICS
```
which is not supported by PostgreSQL 9.1.
Since 9.1 is the packaged version on debian, I feel it's worth supporting it.

I went back to sequelize 2.0.0-rc7 for now, which seems to work fine.

**Comment by mickhansen** [comment]
It should not appear in `findOne`, only in `findOrCreate`, are you sure it's happening in `findOne`?
We added `GET STACKED DIAGNOSTICS` to be able to return the error on unique violation constraints.

**Comment by mickhansen** [comment]
To support 9.1 we'll need to be able to do somekind of version check or pass in the version used.

**Comment by marinewater** [comment]
Yes, sorry, it is a `findOrCreate`.
Apparantly, this is an already known issue:
```javascript
      if (this._dialect.supports['EXCEPTION'] && options.exception) {
        // Mostly for internal use, so we expect the user to know what he's doing!
        // pg_temp functions are private per connection, so we never risk this function interfering with another one.

        // <= 9.1
        //options.exception = 'WHEN unique_violation THEN NULL;';
        //valueQuery = 'CREATE OR REPLACE FUNCTION pg_temp.testfunc() RETURNS SETOF <%= table %> AS $body$ BEGIN RETURN QUERY ' + valueQuery + '; EXCEPTION ' + options.exception + ' END; $body$ LANGUAGE plpgsql; SELECT * FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();';

        // >= 9.2
        options.exception = 'WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL;';
        valueQuery = 'CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response <%= table %>, OUT sequelize_caught_exception text) RETURNS RECORD AS $$ BEGIN ' + valueQuery + ' INTO response; EXCEPTION ' + options.exception + ' END $$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc()';
      }
```
(lib/dialects/abstract/query-generator.js)

Postgres version can be retrieved using `SELECT version();`

**Comment by mickhansen** [comment]
Yea i believe we've already implemented code for fetching version, but the user needs to call that code and then we need to save that on the dialect - Haven't gotten around to it yet.

**Comment by kmpm** [comment]
Still an issue in v2.0.1

**Comment by mickhansen** [comment]
@kmpm yep, haven't gotten around to a proper solution yet. A short term solution would be an option to turn off exception catching, however findOrCreate would no longer work under certain concurrency cases.

**Comment by kmpm** [comment]
I would be fine with forcing the pg version somehow as a database option or something.
Then it will now the version and can use it when checking for exception support.

**Comment by tiblu** [comment]
+1
```
[2015-03-09 16:50:41.786] [INFO] production - DB QUERY. Executing (63a137a7-0b54-4385-ac8c-d27645bc5e9e): CREATE OR REPLACE FUNCTION pg_temp.t
estfunc(OUT response "Sessions", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_d40d4e53f831414aa3502e67efc23e46$ BEGIN INSERT I
NTO "Sessions" ("sid","data","updatedAt","createdAt") VALUES ('44a5N1HCK7tIG9uzxX2xMFP02Dt2m-LK','{"cookie":{"originalMaxAge":1209600000,"expi
res":"2015-03-23T14:50:41.772Z","secure":false,"httpOnly":true,"path":"/"},"user":{"id":"b0e2e3d1-4b16-4656-a406-90866003c972","name":"Foo","
company":"Foo","email":"foo@foo.com"}}','2015-03-09 14:50:41.783 +00:00','2015-03-09 14:50:41.783 +00:00') RETURNING *
 INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_d40d4
e53f831414aa3502e67efc23e46$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP
 FUNCTION IF EXISTS pg_temp.testfunc();
[2015-03-09 16:50:41.790] [INFO] production - DB QUERY. Executing (63a137a7-0b54-4385-ac8c-d27645bc5e9e): COMMIT;
[2015-03-09 16:50:41.792] [INFO] production - Sequelize error handler middleware activated.
[2015-03-09 16:50:41.793] [ERROR] production - Endpoint POST "/api/auth/login" failed miserably. Status: undefined Stack: SequelizeDatabaseErr
or: syntax error at or near "STACKED"
    at module.exports.Query.formatError (/home/toru/apps/toru/node_modules/sequelize/lib/dialects/postgres/query.js:415:16)
    at null.<anonymous> (/home/toru/apps/toru/node_modules/sequelize/lib/dialects/postgres/query.js:110:21)
    at emit (events.js:95:17)
    at Query.handleError (/home/toru/apps/toru/node_modules/pg/lib/query.js:99:8)
    at null.<anonymous> (/home/toru/apps/toru/node_modules/pg/lib/client.js:166:26)
    at emit (events.js:95:17)
    at Socket.<anonymous> (/home/toru/apps/toru/node_modules/pg/lib/connection.js:109:12)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:748:14)
    at Socket.emit (events.js:92:17)
```

**Comment by BridgeAR** [comment]
@janmeier @mickhansen The idea from @kmpm is quite nice in my opinion and solves the issue in appropriate way, if documented properly. If you like the idea, I'll implement that for you.

**Comment by mickhansen** [comment]
@BridgeAR That would be great. Something like if the user runs `sequelize.verison()` to tag the version or passes it with the dialect we can toggle the findOrCreate query.

**Comment by mickhansen** [comment]
Should be fixed now.
