### ISSUE TITLE
Model.build().then() causes [TypeError: Object [object SequelizeInstance] has no method 'then']

### ISSUE THREAD

**Issue by radoslavpetranov** [sequelize/sequelize#2986]
Something seems to be broken with the model.build function - it looks like the return value is not a promise.

To reproduce just run YourModel.build({..}).then(function() {});

Here's the stack trace:

2015-01-21T21:42:49.558Z [error]  Error building object [TypeError: Object [object SequelizeInstance] has no method 'then'] TypeError: Object [object SequelizeI
nstance] has no method 'then'
    at Object.helper.test (c:\whatever\server\blah.js:2355:115)
    at c:\whatever\routes\bleh.js:415:17
    at callbacks (c:\whatever\node_modules\express\lib\router\index.js:161:37)
    at param (c:\whatever\node_modules\express\lib\router\index.js:135:11)
    at pass (c:\whatever\node_modules\express\lib\router\index.js:142:5)
    at Router._dispatch (c:\whatever\node_modules\express\lib\router\index.js:170:5)
    at Object.router (c:\whatever\node_modules\express\lib\router\index.js:33:10)
    at next (c:\whatever\node_modules\express\node_modules\connect\lib\proto.js:190:15)
    at Object.expressInit [as handle] (c:\whatever\node_modules\express\lib\middleware.js:31:5)
    at next (c:\whatever\node_modules\express\node_modules\connect\lib\proto.js:190:15)

I'm running 2.0.0-rc7

P.S.

Oh didn't realize there's an rc8 now - I'll test there in a moment ..

P.S.2

No change - broken in rc8 aswell

**Comment by janmeier** [comment]
Build only creates the instance in javascript, it does not hit the db. This means the instance is returned directly. 

To save to the db use create or build + save

**Comment by radoslavpetranov** [comment]
I just saw the doc and was about to say I'm an idiot but you beat me to it :)

**Comment by janmeier** [comment]
You're welcome ;-). We all need to start somewhere. 

For future reference, the API reference at sequelize.readthedocs.org should be able to show you the return values for each function

**Comment by radoslavpetranov** [comment]
Yeah I have no idea why when I read instance I was thinking promise. I don't wanna open another issue in case it's something stupid again but the reason I was messing around with this is that when I have a definition like so:

A hasMany B as 'entries'

and then do

var b = B.build({ name : 'blah' });
b.getEntries();

I end up with [TypeError: Cannot read property '_isSequelizeMethod' of null]

Is it normal that objects that haven't been saved to the DB yet don't have the normal hasMany association getters? I think I can work around this by adding an additional check and only run the getter for instances where isNew is false but I was curious if this behavior is normal.

Cheers and thanks for the awesomely quick replies you guys have been giving - you rock!

**Comment by janmeier** [comment]
Since a does not have a primary key yet we can't query the b table for related entries. 

The error might be a bit confusing though.... But yes you should check for isNewRecord

**Comment by radoslavpetranov** [comment]
Gotcha - thanks for the help!
