### ISSUE TITLE
Upsert not working with models that have custom getters

### ISSUE THREAD

**Issue by grahamb** [sequelize/sequelize#2987]
This might be a duplicate of #2946.

I have a [model](https://github.com/grahamb/pj-express-app/blob/master/models/oos.js) that has a few "virtual" fields implemented as getters. When I try to do an upsert on this model, it is attempting to set values on the getters, which causes Sequelize to get all sorts of cranky:

```
> Executing (default): CREATE OR REPLACE FUNCTION pg_temp.sequelize_upsert() 
RETURNS integer AS $$ BEGIN INSERT INTO "OOS" 
("certifications_na","previous_experience_na","recruited_by_na","oos_number","first_name","last_name",
"email","address","city","province","country","postal_code","phone","cell_phone","pre_recruited",
"recruited_by","previous_experience","certifications","dob","created_at","updated_at") VALUES (...); 
RETURN 1; EXCEPTION WHEN unique_violation THEN UPDATE "OOS" SET ... WHERE 
("oos_number"=173); RETURN 2; END; $$ LANGUAGE plpgsql; SELECT * FROM 
pg_temp.sequelize_upsert();

Possibly unhandled SequelizeDatabaseError: column "certifications_na" of relation "OOS" does not exist
    at module.exports.Query.formatError (/Users/grahamb/Dropbox/code/personal/pj/selection-app/node_modules/sequelize/lib/dialects/postgres/query.js:309:16)
    at null.<anonymous> (/Users/grahamb/Dropbox/code/personal/pj/selection-app/node_modules/sequelize/lib/dialects/postgres/query.js:64:21)
    at emit (events.js:95:17)
    at Query.handleError (/Users/grahamb/Dropbox/code/personal/pj/selection-app/node_modules/pg/lib/query.js:99:8)
    at null.<anonymous> (/Users/grahamb/Dropbox/code/personal/pj/selection-app/node_modules/pg/lib/client.js:166:26)
    at emit (events.js:95:17)
    at Socket.<anonymous> (/Users/grahamb/Dropbox/code/personal/pj/selection-app/node_modules/pg/lib/connection.js:109:12)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
```

Sequelize 2.0.0rc8

**Comment by eduardrock** [comment]
Is there any solution?
I got the same problem
