### ISSUE TITLE
Using lowercase model names gives an errer

### ISSUE THREAD

**Issue by igittGit** [sequelize/sequelize#2997]
I have defined my models like this with models/index.js generated by the CLI and it gave the error shown below.

user.js:
```javascript
"use strict";

module.exports = function(sequelize, DataTypes) {
  var User = sequelize.define("user", {


  }, {
    classMethods: {
      associate: function(models) {
      }
    },
    tableName: 'Users'
  });

  return User;
};
```

post.js:
```javascript
"use strict";

module.exports = function(sequelize, DataTypes) {
  var Post = sequelize.define("post", {


  }, {
    classMethods: {
      associate: function(models) {
      	Post.belongsTo(models.User, {as: 'user'})
      }
    },
    tableName: 'Posts'
  });

  return Post;
};

```

```
/home/ich/express/test/node_modules/sequelize/lib/associations/mixin.js:101
      throw new Error(this.name + "." + Utils.lowercaseFirst(Type.toString()) 
            ^
Error: post.function (source, target, options) {
    Association.call(this);

    this.associationType = 'BelongsTo';
    this.source = source;
    this.target = target;
    this.options = options;
    this.scope = options.scope;
    this.isSingleAssociation = true;
    this.isSelfAssociation = (this.source === this.target);
    this.as = this.options.as;

    if (Utils._.isObject(this.options.foreignKey)) {
      this.foreignKeyAttribute = this.options.foreignKey;
      this.foreignKey = this.foreignKeyAttribute.name || this.foreignKeyAttribute.fieldName;
    } else {
      this.foreignKeyAttribute = {};
      this.foreignKey = this.options.foreignKey;
    }

    if (this.as) {
      this.isAliased = true;
      this.options.name = {
        singular: this.as
      };
    } else {
      this.as = this.target.options.name.singular;
      this.options.name = this.target.options.name;
    }

    if (!this.options.foreignKey) {
      this.options.foreignKey = Utils._.camelizeIf(
        [
          Utils._.underscoredIf(this.as, this.source.options.underscored),
          this.target.primaryKeyAttribute
        ].join('_'),
        !this.source.options.underscored
      );
    }

    this.identifier = this.foreignKey || Utils._.camelizeIf(
      [
        Utils._.underscoredIf(this.options.name.singular, this.target.options.underscored),
        this.target.primaryKeyAttribute
      ].join('_'),
      !this.target.options.underscored
    );

    this.targetIdentifier = this.target.primaryKeyAttribute;
    this.associationAccessor = this.as;
    this.options.useHooks = options.useHooks;

    // Get singular name, trying to uppercase the first letter, unless the model forbids it
    var singular = Utils.uppercaseFirst(this.options.name.singular);

    this.accessors = {
      get: 'get' + singular,
      set: 'set' + singular,
      create: 'create' + singular
    };
  } called with something that's not an instance of Sequelize.Model
    at null.belongsTo (/home/ich/express/test/node_modules/sequelize/lib/associations/mixin.js:101:13)
    at sequelize.define.classMethods.associate (/home/ich/express/test/models/post.js:10:13)
    at db.sequelize (/home/ich/express/test/models/index.js:24:19)
    at Array.forEach (native)
    at Object.<anonymous> (/home/ich/express/test/models/index.js:22:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

```
node v0.10.35
sequelize@2.0.0-rc8 
mariasql@0.1.21

**Comment by mickhansen** [comment]
Lowercase model names has nothing to do with this.
Somewhere you are calling `Model.belongsTo(Something)` where `Something` is not actually a model.

**Comment by mickhansen** [comment]
Not sure how `models` looks but you might want to inspect that and make sure that the correct keys are in there.

**Comment by igittGit** [comment]
Inspecting ```models``` was a brilliant idea ;)

 ```Post.belongsTo(models.user)``` works fine, thanks!

**Comment by mickhansen** [comment]
@igittGit great, the code you're using seems to use the name to attach :) you could double up and do both if you wanted to.

**Comment by jbarros35** [comment]
called with something that's not an instance of Sequelize.Model
I have the same problem as reported.

**Comment by jbarros35** [comment]
please upgrade the error message because it really sux we can't understand what is going out.

**Comment by janmeier** [comment]
@jbarros35 have you actually read through the issue and tried anything? 

Somewhere you are calling an association function and passing something that is not a model (probably undefined).

**Comment by cesiya23** [comment]
@janmeier I do really have this problem .

I found that when I place my associations declaration in the same file, everything would be ok.
But when I place it in different files, ` throw new Error(this.name + '.belongsToMany called with something that\'s not an instance of Sequelize.Model');` would come up.

Is there anything to do with syntax order which can leading to a model undefined yet? 

How can I avoid this problem but still put them in different files?

```typescript
// org.model.ts

import {db, Sequelize, foreignKeyType} from '../../shared/db'
import {User, UserAttributes, UserInstance, UserOrg, UserOrgAttributes} from '../auth/auth.model'

export interface OrgAttributes {
    // ...
}

export interface OrgInstance extends Sequelize.Instance<OrgAttributes>, OrgAttributes {
    createUser: Sequelize.BelongsToManyCreateAssociationMixin<UserAttributes, UserOrgAttributes>;
    addUser: Sequelize.BelongsToManyAddAssociationMixin<UserInstance, foreignKeyType, UserOrgAttributes>;
    addUsers: Sequelize.BelongsToManyAddAssociationsMixin<UserInstance, foreignKeyType, UserOrgAttributes>;
}

export interface OrgModel extends Sequelize.Model<OrgInstance, OrgAttributes> {}

export const Org: OrgModel = db.define<OrgInstance, OrgAttributes>('org', {
    // ...
});

Org.belongsToMany(User, {as: 'User', through: 'userOrg', foreignKey: 'orgId'});


// user.model.ts

import {db, Sequelize, foreignKeyType} from '../../shared/db'
import {UserProfile, UserProfileAttributes, UserProfileInstance} from '../user-profile/user-profile.model'
import {Org, OrgAttributes, OrgInstance} from '../org/org.model'

export interface UserAttributes {
    // ...
}

export interface UserOrgAttributes {
    orgId: string;
    userId: string;
}

export const UserOrg = db.define('userOrg', {
    id: {
        type: Sequelize.INTEGER,
        primaryKey: true,
        autoIncrement: true,
        unique: true,
        allowNull: false
    },
    userId: Sequelize.STRING,
    orgId: Sequelize.STRING
});

export interface UserInstance extends Sequelize.Instance<UserAttributes>, UserAttributes {
    setOrgs: Sequelize.BelongsToManySetAssociationsMixin<OrgInstance, foreignKeyType, UserOrgAttributes>;
    getOrgs: Sequelize.BelongsToManyGetAssociationsMixin<OrgInstance>;
    createOrg: Sequelize.BelongsToManyCreateAssociationMixin<OrgAttributes, UserOrgAttributes>;
    addOrg: Sequelize.BelongsToManyAddAssociationMixin<OrgInstance, foreignKeyType, UserOrgAttributes>;
    addOrgs: Sequelize.BelongsToManyAddAssociationsMixin<OrgInstance, foreignKeyType, UserOrgAttributes>;
    removeOrg: Sequelize.BelongsToManyRemoveAssociationMixin<OrgInstance, foreignKeyType>;
    removeOrgs: Sequelize.BelongsToManyRemoveAssociationsMixin<OrgInstance, foreignKeyType>;
    hasOrg: Sequelize.BelongsToManyHasAssociationMixin<OrgInstance, foreignKeyType>;
    hasOrgs: Sequelize.BelongsToManyHasAssociationsMixin<OrgInstance, foreignKeyType>;
    countOrgs: Sequelize.BelongsToManyCountAssociationsMixin;
}

export interface UserModel extends Sequelize.Model<UserInstance, UserAttributes> {}

export const User: UserModel = db.define<UserInstance, UserAttributes>('user', {
    // ...
});

User.belongsToMany(Org, {as: 'Org', through: 'userOrg', foreignKey: 'userId'});

// sync.ts

import {db} from './shared/db';
import {User, UserOrg} from './api/auth/auth.model';
import {Org} from './api/org/org.model';

// User.belongsToMany(Org, {as: 'Org', through: 'userOrg', foreignKey: 'userId'});
// Org.belongsToMany(User, {as: 'User', through: 'userOrg', foreignKey: 'orgId'});

(async() => {
    try {
        await User.sync({force: true});
        await Org.sync({force: true});
        await UserOrg.sync();

        let user1 = await User.create({
            username: 'aaa',
            password: '123'
        });

        let user2 = await User.create({
            username: 'bbb',
            password: '123'
        });

        let org1 = await Org.create({
            fullname: '111'
        });

        let org2 = await Org.create({
            fullname: '222'
        });

        await user1.addOrg(org1);
        await user1.addOrg(org2);
        await org2.addUser(user2);

    }
    catch (e) {
        console.log(e.stack);
    }
})();

```

**Comment by janmeier** [comment]
@cesiya23 I can't really answer that without the actual code that is loading the models and saving them etc. 

Have a look at https://github.com/sequelize/express-example/blob/master/models/index.js - This file is exporting an object which contains all models - You'll probably want something similar. It just saves the model under the same name as given to `sequelize.define` - But its up to you how you want to do it in your code

**Comment by cesiya23** [comment]
@janmeier 

```
Object.keys(db).forEach(function(modelName) {
  if ("associate" in db[modelName]) {
    db[modelName].associate(db);
  }
});
```
I think this is the step to actually generate `belongsToMany` association for models , they are all in one file.  🤔  😭 

My project is quite 'big' so we divide categories by feature, it will be quite difficult to maintain putting all models in one file.😭😭😭

I've asked a question on SO, waiting for answer...
[link to SO](http://stackoverflow.com/questions/39033046/sequelize-belongstomany-throw-new-errorthis-name-belongstomany-called-with)

**Comment by janmeier** [comment]
They don't have to be in one file - The file I linked shows how you can import your models from different files, and then export all those definitinos from one file

**Comment by illumimari** [comment]
An obvious error in hindsight, but this may help someone else in the future...

I was receiving this error due to the fact that my model file names were _lowercase_, i.e:
`api/models/user.js`
`api/models/transaction.js`

but I was associating via the conventional uppercase convention:
```
classMethods: {
  associate: function(models) {
    Transaction.belongsTo(models.User, { through: 'UserTransaction' });
  }
}
```

I corrected by simply importing the models as such:
```
// Load Models
  const models = {};
  const modelNamesArray = ['transaction', 'user'];
  modelNamesArray.forEach((modelName) => {
    const name = capitalizeFirstLetter(modelName);
    models[name] = sequelize.import(path.join(__dirname, '../models', modelName));
  });

// Associate Models
  Object.keys(models).forEach((modelName) => {
    if (models[modelName].associate) {
      models[modelName].associate(models);
    }
  });
```

**Comment by kodekracker** [comment]
@illumimari instead of capitalizing first letter conversion, you can do this. No need to handling any type of conversion.
```javascript
// Load Models
  const models = {};
  const modelFileNamesArray = ['transaction', 'user'];
  modelFileNamesArray.forEach((modelFileName) => {
    const Model = sequelize.import(path.join(__dirname, '../models', modelFileName));
    models[Model.name] = Model;
  });

// Associate Models
  Object.keys(models).forEach((modelName) => {
    if (models[modelName].associate) {
      models[modelName].associate(models);
    }
  });
```

**Comment by illumimari** [comment]
Yup, that's quite a bit more elegant. Thanks, @kodekracker.

**Comment by raghavgrover21** [comment]
I am very new to nodejs but..can this error also come up because of two tables referring to each other since that may create a cycle...
