### ISSUE TITLE
hasMany foreignKey allowNull error

### ISSUE THREAD

**Issue by jspizziri** [sequelize/sequelize#3010]
As per the docs here: http://sequelize.readthedocs.org/en/latest/api/associations/ and here: http://sequelize.readthedocs.org/en/latest/docs/associations/#enforcing-a-foreign-key-reference-without-constraints

I am unable to explicitly define any of my foreign key constraints as NOT NULL. I get an error when the database is created:

```
Possibly unhandled SequelizeDatabaseError: ER_CANT_CREATE_TABLE: Can't create table 'totalgain.claim' (errno: 150)
    at module.exports.Query.formatError (/Users/Jacob/Documents/Projects/totalgain/node_modules/sequelize/lib/dialects/mysql/query.js:159:16)
    at Query._callback (/Users/Jacob/Documents/Projects/totalgain/node_modules/sequelize/lib/dialects/mysql/query.js:38:23)
    at Query.Sequence.end (/Users/Jacob/Documents/Projects/totalgain/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query.ErrorPacket (/Users/Jacob/Documents/Projects/totalgain/node_modules/mysql/lib/protocol/sequences/Query.js:93:8)
    at Protocol._parsePacket (/Users/Jacob/Documents/Projects/totalgain/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/Users/Jacob/Documents/Projects/totalgain/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/Users/Jacob/Documents/Projects/totalgain/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/Jacob/Documents/Projects/totalgain/node_modules/mysql/lib/Connection.js:82:28)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
```

This occurs after the CREATE TABLE sql is logged to bash.

**Comment by mickhansen** [comment]
There's a bug with using `NOT NULL` foreign keys and the default constraints.
The default DELETE constriant is `SET NULL` which obviously doesn't work with NOT NULL.
You should add `onDelete: 'CASCADE'` to your association options,

**Comment by jspizziri** [comment]
:+1: Thank you. I added ```onDelete: 'CASCADE'``` and got it working.

I'm guessing this is a duplicate issue then? If so I'd be happy to reference it here and close this issue in favor of the preexisting one.

**Comment by mickhansen** [comment]
https://github.com/sequelize/sequelize/issues/2831

**Comment by jspizziri** [comment]
Booyah
