### ISSUE TITLE
String is given as arguments to getDAO which accepts object type

### ISSUE THREAD

**Issue by phanect** [sequelize/sequelize#3024]
In [`QueryInterface.prototype.dropTable()`, `ModelManager.prototype.getDAO` is called](https://github.com/sequelize/sequelize/blob/master/lib/query-interface.js#L190) and `'tableName'` is given as second argument.
However, according to [`getDAO` definition](https://github.com/sequelize/sequelize/blob/master/lib/model-manager.js#L27), second argument of `getDAO` should be `object` type, not `string`.

This causes following error.

```
     TypeError: Cannot assign to read only property 'attribute' of tableName
      at module.exports.ModelManager.getDAO (/home/phanect/dev/notel-api/node_modules/sequelize/lib/model-manager.js:29:23)                                                                                          
      at /home/phanect/dev/notel-api/node_modules/sequelize/lib/query-interface.js:190:57                                                                                                                            
      at tryCatch1 (/home/phanect/dev/notel-api/node_modules/sequelize/node_modules/bluebird/js/main/util.js:45:21)                                                                                                  
      at Promise._callHandler (/home/phanect/dev/notel-api/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:571:13)                                                                                   
      at Promise._settlePromiseFromHandler (/home/phanect/dev/notel-api/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:581:18)                                                                      
      at Promise._settlePromiseAt (/home/phanect/dev/notel-api/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:713:18)                                                                               
      at Promise._settlePromiseAt (/home/phanect/dev/notel-api/node_modules/sequelize/lib/promise.js:76:18)                                                                                                          
      at Promise._settlePromises (/home/phanect/dev/notel-api/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:854:14)                                                                                
      at Async._consumeFunctionBuffer (/home/phanect/dev/notel-api/node_modules/sequelize/node_modules/bluebird/js/main/async.js:85:12)                                                                              
      at Async.consumeFunctionBuffer (/home/phanect/dev/notel-api/node_modules/sequelize/node_modules/bluebird/js/main/async.js:40:14)   
```

This occurs on current `master`.

**Comment by phanect** [comment]
Maybe fixed in 46211dcc65094d089a5dd4fc5808f5b0d5806f9a?
