### ISSUE TITLE
TypeError: Object #<Object> has no method 'split' during migration

### ISSUE THREAD

**Issue by tcoulter** [sequelize/sequelize#3040]
I'm just now getting this error on a production machine while running migrations. It's confusing because

1. It just started happening.
1. I have the same version of node, sequelize-cli, and sequelize on both the production machine and my development machine, and things work fine on development.
1. The migrations haven't changed since the last successful run. 

Oddly enough, the line there makes it seem like it's just generating help information and has nothing to do with my code (wouldn't be surprised if I'm wrong, here). 

The server checks out sequelize and sequelize-cli from npm during each deploy, so the it's up-to-date with npm at the time of this writing. Will investigate further and see if I can find anything.

```
deploy@data:/var/www/bitcoinindex.es/current# ./node_modules/.bin/sequelize db:migrate --coffee --env production

Sequelize [Node: 0.10.33, CLI: 1.0.7, ORM: 2.0.0-rc8, mysql: *]

Loaded configuration file 'config/config.json'.
Using environment 'production'.

/var/www/bitcoinindex.es/releases/20150131212405/node_modules/sequelize-cli/lib/tasks/model.js:46
          }).split("\n")
             ^
TypeError: Object #<Object> has no method 'split'
  at module.exports.model:create.descriptions.long (/var/www/bitcoinindex.es/releases/20150131212405/node_modules/sequelize-cli/lib/tasks/model.js:46:14)
  at Object.<anonymous> (/var/www/bitcoinindex.es/releases/20150131212405/node_modules/sequelize-cli/lib/tasks/model.js:63:9)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at /var/www/bitcoinindex.es/releases/20150131212405/node_modules/sequelize-cli/lib/gulpfile.js:19:12
  at Array.map (native)
  at Object.<anonymous> (/var/www/bitcoinindex.es/releases/20150131212405/node_modules/sequelize-cli/lib/gulpfile.js:18:4)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Liftoff.handleArguments (/var/www/bitcoinindex.es/releases/20150131212405/node_modules/sequelize-cli/node_modules/gulp/bin/gulp.js:70:18)
  at Liftoff.launch (/var/www/bitcoinindex.es/releases/20150131212405/node_modules/sequelize-cli/node_modules/gulp/node_modules/liftoff/index.js:144:6)
  at Object.<anonymous> (/var/www/bitcoinindex.es/releases/20150131212405/node_modules/sequelize-cli/node_modules/gulp/bin/gulp.js:26:5)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:906:3
```

**Comment by tcoulter** [comment]
Alright, so `split` is being called on an object, not an array, which is why it's failing. Here's what the object looks like:

```javascript
{ 
  code: '\'use strict\'\n\nmodule.exports = (sequelize, DataTypes) ->\n  User = sequelize.define(\'User\', {\n    first_name: DataTypes.STRING\n    last_name: DataTypes.STRING\n    bio: DataTypes.TEXT\n  }, classMethods: associate: (models) ->\n    # associations can be defined here\n    return\n  )\n  User\n',
  ast: 
   { type: 'Program',
     body: [ [Object], [Object] ],
     range: [ 0, 339 ],
     loc: { start: [Object], end: [Object] },
     comments: [ [Object] ] },
  map: 
   { _file: null,
     _sourceRoot: null,
     _skipValidation: false,
     _sources: { _array: [Object], _set: [Object] },
     _names: { _array: [], _set: {} },
     _mappings: { _array: [Object], _sorted: true, _last: [Object] },
     _sourcesContents: null },
  warnings: [] 
}
```

This should be an easy fix. If I have time I'll submit a PR.

**Comment by tcoulter** [comment]
Closing because I submitted to the wrong repro. Moved here: https://github.com/sequelize/cli/issues/89
