### ISSUE TITLE
TypeError with forced sync

### ISSUE THREAD

**Issue by ColCh** [sequelize/sequelize#3057]
Running Mocha test:
```js
var models = require('../../models');

describe('Option sequelize model', function () {

  var Option = models.Option;

  before(function() {
    return models.Option.sync({force: true});
  });

  it('should exist', function () {
    Option.should.exist;
  });
});

```
Throws an exception:
```
  Option sequelize model
Executing (default): DROP TABLE IF EXISTS "Options" CASCADE;
    1) "before all" hook


  0 passing (15ms)
  1 failing

  1) Option sequelize model "before all" hook:
     TypeError: Cannot assign to read only property 'attribute' of tableName
      at module.exports.ModelManager.getDAO (/srv/node_modules/sequelize/lib/model-manager.js:29:23)
      at /srv/node_modules/sequelize/lib/query-interface.js:190:57
      at Promise._settlePromiseAt (/srv/node_modules/sequelize/lib/promise.js:76:18)
  From previous event:
      at new SequelizePromise (/srv/node_modules/sequelize/lib/promise.js:28:17)
      at ConnectionManager.getConnection (/srv/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:194:10)
      at module.exports.Sequelize.query (/srv/node_modules/sequelize/lib/sequelize.js:675:85)
      at module.exports.QueryInterface.dropTable (/srv/node_modules/sequelize/lib/query-interface.js:183:27)
      at module.exports.Model.drop (/srv/node_modules/sequelize/lib/model.js:418:32)
      at /srv/node_modules/sequelize/lib/model.js:389:21
      at Promise._settlePromiseAt (/srv/node_modules/sequelize/lib/promise.js:76:18)
      at process._tickCallback (node.js:355:11)
  From previous event:
      at module.exports.Model.sync (/srv/node_modules/sequelize/lib/model.js:387:20)
      at Context.<anonymous> (/srv/test/models/option.js:18:26)
      at callFn (/usr/local/lib/node_modules/mocha/lib/runnable.js:251:21)
      at Hook.Runnable.run (/usr/local/lib/node_modules/mocha/lib/runnable.js:244:7)
      at next (/usr/local/lib/node_modules/mocha/lib/runner.js:259:10)
      at Immediate._onImmediate (/usr/local/lib/node_modules/mocha/lib/runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:349:17)

```
`Option` model definition:
```js
"use strict";

module.exports = function(sequelize, DataTypes) {
  var Option = sequelize.define("Option", {
    name: DataTypes.STRING,
    label: DataTypes.STRING,
    value: DataTypes.STRING
  }, {
    classMethods: {
      associate: function(models) {
        // associations can be defined here
      }
    }
  });

  return Option;
};

```

Running postgres **9.4.0**.
Module versions:
```
pg-hstore@2.3.1
pg@4.1.1
sequelize@2.0.0-rc8
```

It's an error or just my fault?

**Comment by janmeier** [comment]
Should be fixed on latest master

**Comment by ColCh** [comment]
Reinstalled using ` npm i -S git+https://git@github.com/sequelize/sequelize.git`.
Yes it works! Thanks! Closing issue now.

Any ETA for next release?
