### ISSUE TITLE
Problem using node 0.12

### ISSUE THREAD

**Issue by BridgeAR** [sequelize/sequelize#3115]
Hey, I'm a bit confused trying to use node 0.12, since all your tests pass travis using 0.12.
I can't sync the tables and I have absolutly no clue what the problem is.

While syncing with force: true I get the following error and no table is created:

Executing (default): DROP TABLE IF EXISTS "Sessions" CASCADE;
[TypeError: Cannot assign to read only property 'attribute' of tableName]

When using force: false the tables are created.

My code:

```javascript
var sequelize = new Sequelize(...);

fs.readdirSync(config.modelsDir).filter(function(file) {
    return file.indexOf('.') !== 0;
})
// import model files
.forEach(function(file) {
    sequelize.import(path.join(config.modelsDir, file));
});

// invoke associations on each of the models
Object.keys(sequelize.models).forEach(function(modelName) {
    if (sequelize.models[modelName].options.hasOwnProperty('associate')) {
        sequelize.models[modelName].options.associate(sequelize.models);
    }
});

return sequelize.sync({
    force: true
});
```

**Comment by mickhansen** [comment]
What line exactly is the error from?

**Comment by BridgeAR** [comment]
I got to check later when switching back to 0.12

**Comment by BridgeAR** [comment]
```javascript
Trace: [TypeError: Cannot assign to read only property 'attribute' of tableName]
    at /test/mocha/syncDbBefore.js:16:17
    at tryCatch1 (/node_modules/sequelize/node_modules/bluebird/js/main/util.js:45:21)
    at Promise._callHandler (/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:571:13)
    at Promise._settlePromiseFromHandler (/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAt (/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:713:18)
    at Promise._settlePromiseAt (/node_modules/sequelize/lib/promise.js:76:18)
    at Promise._settlePromises (/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:854:14)
    at bound (domain.js:254:14)
    at Promise.runBound (domain.js:267:12)
    at Async._consumeFunctionBuffer (/node_modules/sequelize/node_modules/bluebird/js/main/async.js:85:12)
    at Async.consumeFunctionBuffer (/node_modules/sequelize/node_modules/bluebird/js/main/async.js:40:14)
    at process._tickDomainCallback (node.js:381:11)
```

**Comment by mickhansen** [comment]
That errors seems to originate in your own file?

**Comment by BridgeAR** [comment]
The called line is:

sequelize.sync({
    force: true
});

**Comment by BridgeAR** [comment]
The called line is:
```javascript
sequelize.sync({
    force: true
});
```

**Comment by mickhansen** [comment]
That trace is very weird

**Comment by BridgeAR** [comment]
That's why I thought :D

**Comment by janmeier** [comment]
I seem to recall we've had this bug before - Are you testing with latest master?

**Comment by mickhansen** [comment]
@BridgeAR can you enable long stack traces and post the stack again?

```js
Sequelize.Promise.longStackTraces();
```

**Comment by BridgeAR** [comment]
They are already enabled :/

**Comment by mickhansen** [comment]
@BridgeAR there's no sequelize code in the stack trace ;p Stack doesn't even mention the sync call in sequelize, which it usually does.

**Comment by BridgeAR** [comment]
I'm quite busy right now but as soon as I'll find some spare time I'll have a closer look at this. The trace right now is weird and useless as it is.

**Comment by Thomathan** [comment]
Hi, I believe I'm getting the exact same issue right now. Below is my stack trace. This occurs during the first Sequelize sync in my grunt tests.

	TypeError: Cannot assign to read only property 'attribute' of tableName
	    at module.exports.ModelManager.getDAO (/usr/home/tuangru/repo/services/node_modules/sequelize/lib/model-manager.js:29:23)
	    at /usr/home/tuangru/repo/services/node_modules/sequelize/lib/query-interface.js:191:57
	    at Promise._settlePromiseAt (/usr/home/tuangru/repo/services/node_modules/sequelize/lib/promise.js:66:18)
	    at process._tickDomainCallback (node.js:381:11)
	From previous event:
	    at new Promise (/usr/home/tuangru/repo/services/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:84:37)
	    at new SequelizePromise (/usr/home/tuangru/repo/services/node_modules/sequelize/lib/promise.js:28:17)
	    at ConnectionManager.getConnection (/usr/home/tuangru/repo/services/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:195:10)
	    at module.exports.Sequelize.query (/usr/home/tuangru/repo/services/node_modules/sequelize/lib/sequelize.js:668:85)
	    at module.exports.QueryInterface.dropTable (/usr/home/tuangru/repo/services/node_modules/sequelize/lib/query-interface.js:184:27)
	    at module.exports.Model.drop (/usr/home/tuangru/repo/services/node_modules/sequelize/lib/model.js:418:32)
	    at /usr/home/tuangru/repo/services/node_modules/sequelize/lib/model.js:389:21
	    at Promise._settlePromiseAt (/usr/home/tuangru/repo/services/node_modules/sequelize/lib/promise.js:66:18)

**Comment by Thomathan** [comment]
My bad, I was using an older version of sequelize. With Sequelize 2.0.3, it works fine with node 0.12

**Comment by BridgeAR** [comment]
Hm, using the newest version works without any problems.
