### ISSUE TITLE
Error running  migrations in 2.0.2

### ISSUE THREAD

**Issue by fernandoneto** [sequelize/sequelize#3126]
When i run migrations under sequelize 2.0.2 i get the error below.
But if i run it under sequelize 2.0.0-rc8 everything goes ok.

```
Possibly unhandled SequelizeDatabaseError: ER_DUP_FIELDNAME: Duplicate column name 'timezone'
    at module.exports.Query.formatError (/home/fernando/GitHub/fernandoneto/findhit/node_modules/sequelize/lib/dialects/mysql/query.js:160:16)
    at Query._callback (/home/fernando/GitHub/fernandoneto/findhit/node_modules/sequelize/lib/dialects/mysql/query.js:38:23)
    at Query.Sequence.end (/home/fernando/GitHub/fernandoneto/findhit/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query.ErrorPacket (/home/fernando/GitHub/fernandoneto/findhit/node_modules/mysql/lib/protocol/sequences/Query.js:93:8)
    at Protocol._parsePacket (/home/fernando/GitHub/fernandoneto/findhit/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/home/fernando/GitHub/fernandoneto/findhit/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/home/fernando/GitHub/fernandoneto/findhit/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/fernando/GitHub/fernandoneto/findhit/node_modules/mysql/lib/Connection.js:82:28)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:526:21)

```

**Comment by mickhansen** [comment]
Hi @fernandoneto, we'll need a bit more information to help you work this out :)

**Comment by fernandoneto** [comment]
@mickhansen tell me what information you need?

**Comment by mickhansen** [comment]
Well atleast the migrations you are running, the state of the tables before the migrations being run, the logged sql.

**Comment by cusspvz** [comment]
```
migration.addColumn( 'User', 'timezone', {
  type: DT.STRING( 40 ),
  allowNull: false,
  defaultValue: "Europe/Lisbon",
})
```

Maybe broken at #3014 ?

![captura de ecra 2015-02-14 as 01 51 58](https://cloud.githubusercontent.com/assets/3604053/6204378/fa310b92-b540-11e4-861e-87f27437ad59.png)

**Comment by mickhansen** [comment]
@cusspvz very possible :) error would suggest column already exists, hence why i asked author for more information like the sql log etc.

**Comment by cusspvz** [comment]
@fernandoneto is my co-worker, so if you need more info you could ask me.
Unfortunately on our tests, seems that `2.0.0-rc8` is more stable than latest release. We will use `2.0.0-rc8` on our future release and as soon we enter on a new development stage i will search for more bugs on sequelize latest release.

**Comment by mickhansen** [comment]
@cusspvz would still like to see the generated sql.

**Comment by sushantdhiman** [comment]
**SSCCE Template**
```js
/*
 * Copy this file to ./sscce.js
 * Add code from issue
 * npm run sscce-{dialect}
 */

var Sequelize = require('./index');
var sequelize = require('./test/support').createSequelizeInstance();

var Q = sequelize.getQueryInterface();

Q.createTable('U', {
  name: Sequelize.STRING
})
.then(() => Q.addColumn('U', 'timezone', {
  type: Sequelize.STRING( 40 ),
  allowNull: false,
  defaultValue: "Europe/Lisbon"
}))
.then(console.log)
.catch(console.error);
```

**Output**
```bash
Using database:  sequelize-test-88
[ [],
  { command: 'ALTER',
    rowCount: NaN,
    oid: null,
    rows: [],
    fields: [],
    _parsers: [],
    RowCtor: null,
    rowAsArray: false,
    _getTypeParser: [Function: bound ] } ]
```
