### ISSUE TITLE
BelongsToMany w/ through options -> Cannot call method 'replace' of undefined

### ISSUE THREAD

**Issue by arcanis** [sequelize/sequelize#3133]
The following code doesn't work, sequelize throw. Am I doing something wrong ? It seems to work when belongsToMany is replaced by hasMany (but I get a deprecation warning)

```js
var Sequelize = require('sequelize')
  , sequelize = new Sequelize('database', 'username', 'password', { dialect: 'postgres' });

var Foo = sequelize.define('Foo', {});
var Bar = sequelize.define('Bar', {});

Foo.hasMany(Bar, { through : 'Test' });
Bar.belongsToMany(Foo, { through : 'Test' });

sequelize.sync().then(function() {

    return Foo.create().then(function(foo){
        return Bar.create().then(function(bar){
            return foo.setBars([bar]);
        });
    });

}).catch(function(error){

    console.log(error.stack);

});
```

```
TypeError: Cannot call method 'replace' of undefined
    at Object.module.exports.removeTicks (/tmp/foo/node_modules/sequelize/lib/utils.js:580:14)
    at Object.module.exports.addTicks (/tmp/foo/node_modules/sequelize/lib/utils.js:576:29)
    at Object.module.exports.QueryGenerator.quoteIdentifier (/tmp/foo/node_modules/sequelize/lib/dialects/postgres/query-generator.js:856:22)
    at generateJoinQueries (/tmp/foo/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1149:72)
    at Object.<anonymous> (/tmp/foo/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1217:29)
    at Array.forEach (native)
    at Object.module.exports.QueryGenerator.selectQuery (/tmp/foo/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1216:25)
    at module.exports.QueryInterface.select (/tmp/foo/node_modules/sequelize/lib/query-interface.js:721:35)
    at null.<anonymous> (/tmp/foo/node_modules/sequelize/lib/model.js:731:34)
    at tryCatch1 (/tmp/foo/node_modules/sequelize/node_modules/bluebird/js/main/util.js:45:21)
```

**Comment by arcanis** [comment]
The solution, given by @mickhansen on irc, was to use belongsToMany on **both** ends of the association.
