### ISSUE TITLE
SQLITE_LOCKED while running `db:migrate:undo`

### ISSUE THREAD

**Issue by dantman** [sequelize/sequelize#3191]
I tried running `db:migrate:undo` for the first time. The first down migration worked fine but the second one gives me a SQLITE_LOCKED. This is true even after shutting off my daemon, running undo several times, and trying to migrate up and then back down.

The first undo was a removeIndex, the second is a removeColumn.

```
$ sequelize db:migrate:undo

Sequelize [Node: 0.12.0, CLI: 1.3.0, ORM: 2.0.0-rc8]

Loaded configuration file 'sequelize-config.js'.
Using environment 'development'.
== 20150220163749-create-user-avatar-id-column: reverting =======
Possibly unhandled SequelizeDatabaseError: SQLITE_LOCKED: database table is locked
    at module.exports.Query.formatError (/Users/daniel/Workspace/otaku/otakuseek/otakucore/node_modules/sequelize/lib/dialects/sqlite/query.js:243:16)
    at Statement.<anonymous> (/Users/daniel/Workspace/otaku/otakuseek/otakucore/node_modules/sequelize/lib/dialects/sqlite/query.js:53:31)
    at Statement.replacement (/Users/daniel/Workspace/otaku/otakuseek/otakucore/node_modules/sqlite3/lib/trace.js:20:31)
    at Statement.replacement (/Users/daniel/Workspace/otaku/otakuseek/otakucore/node_modules/sqlite3/lib/trace.js:20:31)
```

**Comment by janmeier** [comment]
This issue / PR needs more information. 

Please see [CONTRIBUTING.md](https://github.com/sequelize/sequelize/blob/master/CONTRIBUTING.md) for details 

Also, this probably belongs in sequelize/umzug
