### ISSUE TITLE
Error when running transaction (managed CLS) 

### ISSUE THREAD

**Issue by vinkaga** [sequelize/sequelize#3245]
Running the following code
```JavaScript
var cls = require('continuation-local-storage');
var Sequelize = require('sequelize');
Sequelize.cls = cls.createNamespace('my-very-own-namespace');
var sequelize = new Sequelize('seqex', 'root', 'mysql', {logging: false});

var User = sequelize.define('user', { name: Sequelize.STRING });

sequelize.sync({force: true}).then(function () {
    sequelize.transaction(function(t) {
        User.create({name: 'John Doe'}).then(function(user) {
            console.log('created user', user.dataValues);
        }).catch(function(e) { console.log (e); });
    });
}).catch(function(e) { console.log (e); });
```
results in the following output.
```
Note: When passing a callback to a transaction a promise chain is expected in return, the transaction will be committed or rejected based on the promise chain returned to the callback.
Possibly unhandled Error: You need to return a promise chain to the sequelize.transaction() callback
    at /Users/vagarwal/dev/seqex/node_modules/sequelize/lib/sequelize.js:1115:38
    at /Users/vagarwal/dev/seqex/node_modules/continuation-local-storage/context.js:74:17
    at tryCatch1 (/Users/vagarwal/dev/seqex/node_modules/sequelize/node_modules/bluebird/js/main/util.js:45:21)
    at Promise._callHandler (/Users/vagarwal/dev/seqex/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:571:13)
    at Promise._settlePromiseFromHandler (/Users/vagarwal/dev/seqex/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAt (/Users/vagarwal/dev/seqex/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:713:18)
    at Promise._settlePromiseAt (/Users/vagarwal/dev/seqex/node_modules/sequelize/lib/promise.js:76:18)
    at Promise._settlePromises (/Users/vagarwal/dev/seqex/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:854:14)
    at Async._consumeFunctionBuffer (/Users/vagarwal/dev/seqex/node_modules/sequelize/node_modules/bluebird/js/main/async.js:85:12)
    at Async.consumeFunctionBuffer (/Users/vagarwal/dev/seqex/node_modules/sequelize/node_modules/bluebird/js/main/async.js:40:14)
created user { id: 1,
  name: 'John Doe',
  updatedAt: Sun Mar 01 2015 09:47:07 GMT-0800 (PST),
  createdAt: Sun Mar 01 2015 09:47:07 GMT-0800 (PST) }
```
How can fix this "Possibly unhandled Error?"
Uses node version 0.12.0 and sequelize version 2.0.3.

**Comment by janmeier** [comment]
As the error says, you need to `return User.create `

**Comment by vinkaga** [comment]
I updated the code to include 'return' as follows
```JavaScript
var cls = require('continuation-local-storage');
var Sequelize = require('sequelize');
Sequelize.cls = cls.createNamespace('my-very-own-namespace');
var sequelize = new Sequelize('seqex', 'root', 'mysql', {logging: false});

var User = sequelize.define('user', { name: Sequelize.STRING });

sequelize.sync({force: true}).then(function () {
    return sequelize.transaction(function(t) {
        return User.create({name: 'John Doe'}).then(function(user) {
            console.log('created user', user.dataValues);
        }).catch(function(e) { console.log (e); });
    });
}).catch(function(e) { console.log (e); });
```
This results in the following output
```
Note: When passing a callback to a transaction a promise chain is expected in return, the transaction will be committed or rejected based on the promise chain returned to the callback.
created user { id: 1,
  name: 'John Doe',
  updatedAt: Sun Mar 01 2015 12:42:23 GMT-0800 (PST),
  createdAt: Sun Mar 01 2015 12:42:23 GMT-0800 (PST) }
```
Is 'Note' a warning? How do I get rid of that?

**Comment by janmeier** [comment]
There is no way to escape the notice, but it has been removed in latest master https://github.com/sequelize/sequelize/commit/5bc2d11c4e34adb708d4cbb028f612c7eee30f9a

**Comment by RichardBoyewa** [comment]
You need to pass in the transaction as the second parameter in the create method. I edited your code below
```
var cls = require('continuation-local-storage');
var Sequelize = require('sequelize');
Sequelize.cls = cls.createNamespace('my-very-own-namespace');
var sequelize = new Sequelize('seqex', 'root', 'mysql', {logging: false});

var User = sequelize.define('user', { name: Sequelize.STRING });

sequelize.sync({force: true}).then(function () {
    return sequelize.transaction(function(t) {
        return User.create({name: 'John Doe'}, {transaction:t}).then(function(user) {
            console.log('created user', user.dataValues);
        }).catch(function(e) { console.log (e); });
    });
}).catch(function(e) { console.log (e); });
```
