### ISSUE TITLE
Upsert fails to provide a default id on Postgresql

### ISSUE THREAD

**Issue by Couto** [sequelize/sequelize#3247]
While using Postgresql (I can't replicate using sqlite) trying to insert a value using upsert always fails with error.

The following is the minimum usable case, tested on OSX 10.9.5, node v0.10.36 and sequelize 2.0.3, to replicate the bug.

```javascript
var Sequelize = require('sequelize'),
    sequelize = new Sequelize('testdb', 'postgres', '', {
        'username': 'postgres',
        'password': '',
        'database': 'testdb',
        'host': 'localhost',
        'dialect': 'postgresql'
    });

var User = sequelize.define('User', {

    id: {
        primaryKey: true,
        allowNull: false,
        unique: true,
        type: Sequelize.UUID,
        defaultValue: Sequelize.UUIDV4
    },

    name: {
        type: Sequelize.STRING,
    }

});

sequelize
    .sync({ force: true })
    .then(function () {
        User.upsert({ name: 'John Doe' });
    });
```

```
Executing (default): DROP TABLE IF EXISTS "Users" CASCADE;
Executing (default): DROP TABLE IF EXISTS "Users" CASCADE;
Executing (default): CREATE TABLE IF NOT EXISTS "Users" ("id" UUID NOT NULL UNIQUE , "name" VARCHAR(255), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i,
 pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND a.attnum = ANY(ix.indkey) AND t.relkind = 'r' and t.relname = 'Users' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relna
me;
Executing (default): CREATE OR REPLACE FUNCTION pg_temp.sequelize_upsert() RETURNS integer AS $$ BEGIN INSERT INTO "Users" ("name","createdAt","updatedAt") VALUES ('John Doe','2015-03-02 12:42:06.533 +00:00','2015-03-02 12:42:06.533 +00:00'); RETURN 1; EXCEPTION WHEN uniq
ue_violation THEN UPDATE "Users" SET "name"='John Doe',"updatedAt"='2015-03-02 12:42:06.533 +00:00'; RETURN 2; END; $$ LANGUAGE plpgsql; SELECT * FROM pg_temp.sequelize_upsert();
Possibly unhandled SequelizeDatabaseError: null value in column "id" violates not-null constraint
    at module.exports.Query.formatError (/private/tmp/upsert/node_modules/sequelize/lib/dialects/postgres/query.js:361:16)
    at null.<anonymous> (/private/tmp/upsert/node_modules/sequelize/lib/dialects/postgres/query.js:79:21)
    at emit (events.js:95:17)
    at Query.handleError (/private/tmp/upsert/node_modules/pg/lib/query.js:99:8)
    at null.<anonymous> (/private/tmp/upsert/node_modules/pg/lib/client.js:166:26)
    at emit (events.js:95:17)
    at Socket.<anonymous> (/private/tmp/upsert/node_modules/pg/lib/connection.js:109:12)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
```

**Comment by mickhansen** [comment]
@janmeier looks like upsert is not accurately using default values for the insert.

**Comment by janmeier** [comment]
@mickhansen it's applying default values for all other fields, just not for the primary key. For auto-generated ids we leave out the column completely, to get the default value.

This line https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1247 should check if the primary key has a default value

**Comment by mickhansen** [comment]
@janmeier ah yeah, looks like that's it.

**Comment by Americas** [comment]
I'm having this problem as well. The problem I have is when I upsert some data that already exists (a unique key with the same value). The UPDATE statement does not have a WHERE clause, thus it tries to update the whole table, as you can see from the example's output above.

**Comment by mindo** [comment]
+1
