### ISSUE TITLE
Replace 2 x hasMany with belongsToMany fails

### ISSUE THREAD

**Issue by warmsea** [sequelize/sequelize#3295]
It seems `belongsToMany` fails for a M:N relationship between one model and itself. For example, one user follows another one.

```javascript
var Sequelize = require('sequelize');
var sequelize = new Sequelize('testa', 'testa', 'testa', { dialect: 'mysql' });

var User = sequelize.define('User', {
  // some properties
});

var Follow = sequelize.define('Follow', {
  // some properties
}, {
  indexes: [
    {
      unique: true,
      fields: ['UserId', 'FanId']
    }
  ]
});

User.hasMany(User, { through: Follow, as: 'User' });
User.hasMany(User, { through: Follow, as: 'Fan' });

sequelize.sync({ force: true }).complete(function(err) { console.log(err); });
```

This works but says `Using 2 x hasMany to represent N:M relations has been deprecated. Please use belongsToMany instead`. So I replaced `hasMany` with `belongsToMany`.

```javascript
User.belongsToMany(User, { through: Follow, as: 'User' });
User.belongsToMany(User, { through: Follow, as: 'Fan' });
```

This fails with the message `ER_KEY_COLUMN_DOES_NOT_EXITS: Key column 'FanId' doesn't exist in table`.

Is this a BUG? Or did I miss something?

**Comment by warmsea** [comment]
I am using node v0.12.0 and sequalize v2.0.3.

**Comment by mickhansen** [comment]
Possibly a bug with self references.
There's a related fix on master, can you test that please?

**Comment by warmsea** [comment]
Great. I'll test it.

**Comment by warmsea** [comment]
The master throws the same error.

**Comment by juliocanares** [comment]
@warmsea  you can try with  this
 ```javascript
User.belongsToMany(models.User, {as: 'Followers', foreignKey: 'FollowingId', through: 'Followers'});
User.belongsToMany(models.User, {as: 'Followings', foreignKey: 'FollowerId', through: 'Followers'});
```
but I have error in self reference with this is more than 2 references , in this caso when I want get all following of one user , 

```javascript
User.belongsToMany(models.User, {as: 'Followers', foreignKey: 'FollowingId', through: 'Followers'});
User.belongsToMany(models.User, {as: 'Followings', foreignKey: 'FollowerId', through: 'Followers'});
User.belongsToMany(models.User, {as: 'UserViewers', foreignKey: 'UserViewingId', through: 'UserViewers'});
User.belongsToMany(models.User, {as: 'UserViewings', foreignKey: 'UserViewerId', through: 'UserViewers'});
```

```javascript
Possibly unhandled SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'Followers.UserViewingId' in 'on clause'
```

any solution for this in this time ? , I think that the solution would will execute raw query but not is the ideal.

**Comment by juliocanares** [comment]
@mickhansen  this bug is in the roadmap ?

**Comment by warmsea** [comment]
@juliocanares I'm still using hasMany(). There's a warning. But it works.

**Comment by janmeier** [comment]
@juliocanares It is still a TODO yes :)

Your case is interresting - if you could provide a PR with a failing test case for it that'd be great, and speed things up

@warmsea It works for now, but n:m hasMany won't get any new features (scopes for example)

**Comment by mickhansen** [comment]
@juliocanares All bugs are on the roadmap.

**Comment by juliocanares** [comment]
good :D , in my case building the table structure with self belongstomany is good , the bug is only when I'm using getters associations

**Comment by jagged3dge** [comment]
I just hit the same issue as @juliocanares with sequelize v3.4.1 (latest npm package version).

I think in v3.x.x the _warning_ for n:m hasMany has been converted to a full-blown error. It just doesn't proceed any more. So, using 2x hasMany to work around this is not feasible. Unless I downgrade to v2.x.x (or whichever version precedes the merge that introduced warning-to-error commit).

Not worried about scopes for n:m hasMany associations, but multiple self-referential associations shouldn't break like this.

**Comment by mickhansen** [comment]
@jagged3dge Can you show a small sample that fails for you?

**Comment by jagged3dge** [comment]
Here goes a small test case:

```javascript
var Sequelize = require('sequelize')

var config = {
  dbName: 'seq_test',
  dbUser: 'sequelize',
  dbPass: '123',
  dbPort: 3306,
  dbLog : console.log,
  dbForce: true,
}

var sequelize = new Sequelize (
  config.dbName,
  config.dbUser,
  config.dbPass,
  {
    dialect: 'mysql',
    post: config.dbPort,
    logging: config.dbLog
  }
)

var User = sequelize.define('User', {
  name: {
    type: Sequelize.STRING,
    allowNull: true
  }

}, {
  paranoid: true
})

var UserFollowers = sequelize.define('UserFollowers', {
  id: {
    type: Sequelize.BIGINT.UNSIGNED,
    autoIncrement: true,
    primaryKey: true
  }

}, {
  paranoid: true,
  freezeTableNames: true,
  tableName: 'UserFollowers'
})


User.belongsToMany (User, {
  as: {
    singular: 'Follower',
    plural: 'Followers'
  },
  through: UserFollowers
})

User.belongsToMany (User, {
  as: {
    singular: 'Invitee',
    plural: 'Invitees'
  },
  foreignKey: 'InviteeId',
  through: 'Invites'
})

sequelize
  .sync({ force: config.dbForce })
  .then (function() {

    var User1 = User.build ({ name: 'John' })
    var User2 = User.build ({ name: 'Bob' })

    sequelize.Promise.all ([
      User1.save(),
      User2.save()
    ])
    .then (function (users) {
      User1.addFollower(User2)
      User2.addFollower(User1)

      User1.addInvitee(User2)
      User2.addInvitee(User1)
    })

  })
```

The terminal output:
```
20 Jul 14:32:00 - [33m[nodemon] v1.3.7[39m
20 Jul 14:32:00 - [33m[nodemon] to restart at any time, enter `rs`[39m
20 Jul 14:32:00 - [33m[nodemon] watching: D:\WampDeveloper\Websites\www.example.com\webroot\sequelize-test\models/**/*[39m
20 Jul 14:32:01 - [32m[nodemon] starting `node app.js`[39m
Executing (default): DROP TABLE IF EXISTS `Invites`;
Executing (default): DROP TABLE IF EXISTS `UserFollowers`;
Executing (default): DROP TABLE IF EXISTS `Users`;
Executing (default): DROP TABLE IF EXISTS `Users`;
Executing (default): CREATE TABLE IF NOT EXISTS `Users` (`id` INTEGER NOT NULL auto_increment , `name` VARCHAR(255), `address` TEXT, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `deletedAt` DATETIME, PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `Users`
Executing (default): DROP TABLE IF EXISTS `UserFollowers`;
Executing (default): CREATE TABLE IF NOT EXISTS `UserFollowers` (`id` BIGINT UNSIGNED auto_increment , `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `deletedAt` DATETIME, `UserId` INTEGER, `FollowerId` INTEGER, UNIQUE `UserFollowers_UserId_FollowerId_unique` (`UserId`, `FollowerId`), PRIMARY KEY (`id`), FOREIGN KEY (`UserId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`FollowerId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `UserFollowers`
Executing (default): DROP TABLE IF EXISTS `Invites`;
Executing (default): CREATE TABLE IF NOT EXISTS `Invites` (`createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `InviteeId` INTEGER , `UserId` INTEGER , PRIMARY KEY (`InviteeId`, `UserId`), FOREIGN KEY (`InviteeId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, FOREIGN KEY (`UserId`) REFERENCES `Users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `Invites`
Executing (default): INSERT INTO `Users` (`id`,`name`,`address`,`updatedAt`,`createdAt`) VALUES (DEFAULT,'John','1st Street','2015-07-20 09:02:02','2015-07-20 09:02:02');
Executing (default): INSERT INTO `Users` (`id`,`name`,`address`,`updatedAt`,`createdAt`) VALUES (DEFAULT,'Bob','2nd Street','2015-07-20 09:02:02','2015-07-20 09:02:02');
Executing (default): SELECT `id`, `createdAt`, `updatedAt`, `deletedAt`, `UserId`, `FollowerId` FROM `UserFollowers` AS `UserFollowers` WHERE (`UserFollowers`.`deletedAt` IS NULL AND (`UserFollowers`.`UserId` = 1 AND `UserFollowers`.`InviteeId` IN (2)));
Executing (default): SELECT `id`, `createdAt`, `updatedAt`, `deletedAt`, `UserId`, `FollowerId` FROM `UserFollowers` AS `UserFollowers` WHERE (`UserFollowers`.`deletedAt` IS NULL AND (`UserFollowers`.`UserId` = 2 AND `UserFollowers`.`InviteeId` IN (1)));
Executing (default): SELECT `createdAt`, `updatedAt`, `InviteeId`, `UserId` FROM `Invites` AS `Invites` WHERE `Invites`.`InviteeId` = 1 AND `Invites`.`UserId` IN (2);
Executing (default): SELECT `createdAt`, `updatedAt`, `InviteeId`, `UserId` FROM `Invites` AS `Invites` WHERE `Invites`.`InviteeId` = 2 AND `Invites`.`UserId` IN (1);
Unhandled rejection SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'UserFollowers.InviteeId' in 'where clause'
    at Query.formatError (D:\WampDeveloper\Websites\www.example.com\webroot\sequelize-test\node_modules\sequelize\lib\dialects\mysql\query.js:159:14)
    at Query._callback (D:\WampDeveloper\Websites\www.example.com\webroot\sequelize-test\node_modules\sequelize\lib\dialects\mysql\query.js:35:21)
    at Query.Sequence.end (D:\WampDeveloper\Websites\www.example.com\webroot\sequelize-test\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query.ErrorPacket (D:\WampDeveloper\Websites\www.example.com\webroot\sequelize-test\node_modules\mysql\lib\protocol\sequences\Query.js:94:8)
    at Protocol._parsePacket (D:\WampDeveloper\Websites\www.example.com\webroot\sequelize-test\node_modules\mysql\lib\protocol\Protocol.js:274:23)
    at Parser.write (D:\WampDeveloper\Websites\www.example.com\webroot\sequelize-test\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\WampDeveloper\Websites\www.example.com\webroot\sequelize-test\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\WampDeveloper\Websites\www.example.com\webroot\sequelize-test\node_modules\mysql\lib\Connection.js:96:28)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
From previous event:
    at Query.run (D:\WampDeveloper\Websites\www.example.com\webroot\sequelize-test\node_modules\sequelize\lib\dialects\mysql\query.js:30:17)
    at D:\WampDeveloper\Websites\www.example.com\webroot\sequelize-test\node_modules\sequelize\lib\sequelize.js:713:18
From previous event:
    at Promise.then (D:\WampDeveloper\Websites\www.example.com\webroot\sequelize-test\node_modules\sequelize\lib\promise.js:21:17)
    at Object.<anonymous> (D:\WampDeveloper\Websites\www.example.com\webroot\sequelize-test\app.js:89:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
Unhandled rejection SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'UserFollowers.InviteeId' in 'where clause'
    at Query.formatError (D:\WampDeveloper\Websites\www.example.com\webroot\sequelize-test\node_modules\sequelize\lib\dialects\mysql\query.js:159:14)
    at Query._callback (D:\WampDeveloper\Websites\www.example.com\webroot\sequelize-test\node_modules\sequelize\lib\dialects\mysql\query.js:35:21)
    at Query.Sequence.end (D:\WampDeveloper\Websites\www.example.com\webroot\sequelize-test\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query.ErrorPacket (D:\WampDeveloper\Websites\www.example.com\webroot\sequelize-test\node_modules\mysql\lib\protocol\sequences\Query.js:94:8)
    at Protocol._parsePacket (D:\WampDeveloper\Websites\www.example.com\webroot\sequelize-test\node_modules\mysql\lib\protocol\Protocol.js:274:23)
    at Parser.write (D:\WampDeveloper\Websites\www.example.com\webroot\sequelize-test\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (D:\WampDeveloper\Websites\www.example.com\webroot\sequelize-test\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\WampDeveloper\Websites\www.example.com\webroot\sequelize-test\node_modules\mysql\lib\Connection.js:96:28)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
From previous event:
    at Query.run (D:\WampDeveloper\Websites\www.example.com\webroot\sequelize-test\node_modules\sequelize\lib\dialects\mysql\query.js:30:17)
    at D:\WampDeveloper\Websites\www.example.com\webroot\sequelize-test\node_modules\sequelize\lib\sequelize.js:713:18
From previous event:
    at Promise.then (D:\WampDeveloper\Websites\www.example.com\webroot\sequelize-test\node_modules\sequelize\lib\promise.js:21:17)
    at Object.<anonymous> (D:\WampDeveloper\Websites\www.example.com\webroot\sequelize-test\app.js:89:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
Executing (default): INSERT INTO `Invites` (`InviteeId`,`UserId`,`createdAt`,`up
datedAt`) VALUES (1,2,'2015-07-20 08:50:42','2015-07-20 08:50:42');
Executing (default): INSERT INTO `Invites` (`InviteeId`,`UserId`,`createdAt`,`up
datedAt`) VALUES (2,1,'2015-07-20 08:50:42','2015-07-20 08:50:42');
```

**Comment by mickhansen** [comment]
Are both belongsToMany relations needed to produce this error?
Please make the code as minimal as possible, makes it faster for us to track down a bug.

**Comment by jagged3dge** [comment]
Apologies for the verbose code. It's just the way I write >.<

Yes, both belongsToMany relations are required to reproduce this error. With just one belongsToMany relation, it works just perfect. When another is added to the mix, it throws this error.

I'm unfortunately having to use more than 2 self-referential belongsToMany relations in my project. Cause of this error, I'm having to manually define the *through* model with an auto-increment `id` column as primary key then manually create the association data in the table via the *through* model.

**Comment by mickhansen** [comment]
@jagged3dge Great, should help us debug it.
Looks like the `foreignKey` from the one association is leaking into the other, which should obviously not be happening.

**Comment by mickhansen** [comment]
@jagged3dge https://github.com/sequelize/sequelize/pull/4151 will likely fix this, please test and verify in other issue (probably not related to original)

**Comment by jagged3dge** [comment]
@mickhansen I just incorporated the commit from #4151 PR into my local instance of sequelize. 

There's no error thrown any more, which is great!

However, the `Invites` table now has only 1 reference column called `InviteeId`. It's missing the other reference column `UserId`. The MySQL INSERT happens with only one value going to `InviteeId`. Is this a side-effect? Or intended?

**Comment by mickhansen** [comment]
@jagged3dge Hmm that's not intended, but please comment on the PR since your current issue is unrelated to the one originally opened here.
