### ISSUE TITLE
"Error: Please install postgres package manually" after updating node and npm

### ISSUE THREAD

**Issue by jakemmarsh** [sequelize/sequelize#3302]
I updated my local versions of Node (now v0.12.0) and npm (now v2.7.0). I also updated all my globally-installed packages accordingly.

My project is using `sequelize` v2.0.4, `pg` v4.3.0, `pg-hstore` v2.3.1, and `pg-native` v1.8.0. None of my previously working Sequelize/connection logic has been changed. Now when starting my server I get the following error/stacktrace:

```
Starting child process with 'node server.js'
Error: Please install postgres package manually
    at new ConnectionManager (/Users/jakemarsh/Repos/monolist-api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:16:11)
    at new PostgresDialect (/Users/jakemarsh/Repos/monolist-api/node_modules/sequelize/lib/dialects/postgres/index.js:12:28)
    at new module.exports.Sequelize (/Users/jakemarsh/Repos/monolist-api/node_modules/sequelize/lib/sequelize.js:185:22)
    at Object.<anonymous> (/Users/jakemarsh/Repos/monolist-api/api/models/index.js:18:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
/Users/jakemarsh/Repos/monolist-api/node_modules/sequelize/lib/sequelize.js:188
      throw new Error('The dialect ' + this.getDialect() + ' is not supported.
            ^
Error: The dialect postgres is not supported. (Error: Please install postgres package manually)
    at new module.exports.Sequelize (/Users/jakemarsh/Repos/monolist-api/node_modules/sequelize/lib/sequelize.js:188:13)
    at Object.<anonymous> (/Users/jakemarsh/Repos/monolist-api/api/models/index.js:18:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/jakemarsh/Repos/monolist-api/api/routes/auth.js:7:16)
    at Module._compile (module.js:460:26)
Program node server.js exited with code 1
```

**Comment by mickhansen** [comment]
Can you add a `console.log(err)` statement in the catch here https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/connection-manager.js#L16 to see what happens?

**Comment by jakemmarsh** [comment]
Sure, the error resulting from a `console.log` there is: `[Error: Module did not self-register.]`

**Comment by mickhansen** [comment]
@jakemmarsh and the stack? Sounds like a issue with the pg module maybe.

**Comment by jakemmarsh** [comment]
Sorry, here's the full trace again:

```
Starting child process with 'node server.js'
error in connection manager: [Error: Module did not self-register.]
Error: Please install postgres package manually
    at new ConnectionManager (/Users/jakemarsh/Repos/monolist-api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:17:11)
    at new PostgresDialect (/Users/jakemarsh/Repos/monolist-api/node_modules/sequelize/lib/dialects/postgres/index.js:12:28)
    at new module.exports.Sequelize (/Users/jakemarsh/Repos/monolist-api/node_modules/sequelize/lib/sequelize.js:185:22)
    at Object.<anonymous> (/Users/jakemarsh/Repos/monolist-api/api/models/index.js:18:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
/Users/jakemarsh/Repos/monolist-api/node_modules/sequelize/lib/sequelize.js:188
      throw new Error('The dialect ' + this.getDialect() + ' is not supported.
            ^
Error: The dialect postgres is not supported. (Error: Please install postgres package manually)
    at new module.exports.Sequelize (/Users/jakemarsh/Repos/monolist-api/node_modules/sequelize/lib/sequelize.js:188:13)
    at Object.<anonymous> (/Users/jakemarsh/Repos/monolist-api/api/models/index.js:18:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/jakemarsh/Repos/monolist-api/server.js:13:22)
    at Module._compile (module.js:460:26)
Program node server.js exited with code 1
```

**Comment by mickhansen** [comment]
Hmm can you show that logging code? That stack looks weird.

**Comment by jakemmarsh** [comment]
Sorry, what logging code are you referring to?

**Comment by mickhansen** [comment]
@jakemmarsh The specific console.log statement and surrounding code.
But not sure it matters, it looks like it's an issue with compiled packages and node 0.12.
Can you remove pg-native and the native: true setting and see if it works?

**Comment by cusspvz** [comment]
I updated my local versions of Node (now v0.12.0) and npm (now v2.7.0). I also updated all my globally-installed packages accordingly.

You also need to remove `node_modules` and run again `npm install` just because there are a lot of modules that are compiled from C directly, and they need to be compiled again on major.minor changes.

**Comment by jakemmarsh** [comment]
Wow. Could've swore I had already deleted `node_modules` and re-ran `npm install`, but just did it again and it fixed the issue. Thanks for the help!

**Comment by cusspvz** [comment]
You're welcome! ;)

**Comment by fixe** [comment]
@mickhansen shouldn't we output the error in https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/connection-manager.js#L20?

**Comment by mickhansen** [comment]
@fixe Yeah the error is kind of dump since a lot of the time it has nothing to do with the dialect missing. Ideally we should match for the correct require error and rethrow original error otherwise.
