### ISSUE TITLE
io.js failing to load Sequelize

### ISSUE THREAD

**Issue by Junikorn** [sequelize/sequelize#3318]
Can't initialize sequelize 2.0.4 on io.js environment:

TypeError: Cannot set property 'options' of undefined
    at module.exports.Sequelize (D:\javascript\mgr\node_modules\sequelize\lib\sequelize.js:133:18)
    at module.exports (D:\javascript\mgr\model\index.js:4:30)
    at Object.<anonymous> (D:\javascript\mgr\index.js:12:25)
    at Module._compile (module.js:444:26)
    at Object.Module._extensions..js (module.js:462:10)
    at Module.load (module.js:339:32)
    at Function.Module._load (module.js:294:12)
    at Function.Module.runMain (module.js:485:10)
    at startup (node.js:111:16)
    at node.js:799:3

**Comment by mickhansen** [comment]
We test against io.js on Travis.
What version of io.js specifically?

**Comment by janmeier** [comment]
Remember to call `new Sequelize()`, not just `Sequelize()`. This is not an io.js specific problem

**Comment by Junikorn** [comment]
got sloppy while reading documentation, sorry for raising the issue and thanks for help
