### ISSUE TITLE
hasMany eager loading

### ISSUE THREAD

**Issue by hfar** [sequelize/sequelize#3331]
I am using sequelize latest version,and simply i need to eager load the model "VenueAddress" when finding a "Venue" model, but i get the below error:

i appreciate your help .. great work.

```
TypeError: Cannot read property 'replace' of undefined
    at Object.module.exports.removeTicks (d:\GitProjects\bashed\node_modules\sequelize\lib\utils.js:595:13)
    at Object.module.exports.addTicks (d:\GitProjects\bashed\node_modules\sequelize\lib\utils.js:591:29)
    at Object.module.exports.QueryGenerator.quoteIdentifier (d:\GitProjects\bashed\node_modules\sequelize\lib\dialects\mysql\query-generator.js:344:20)
    at generateJoinQueries (d:\GitProjects\bashed\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1014:74)
    at Object.<anonymous> (d:\GitProjects\bashed\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1230:29)
    at Array.forEach (native)
    at Object.module.exports.QueryGenerator.selectQuery (d:\GitProjects\bashed\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1229:25)
    at module.exports.QueryInterface.select (d:\GitProjects\bashed\node_modules\sequelize\lib\query-interface.js:721:35)
    at null.<anonymous> (d:\GitProjects\bashed\node_modules\sequelize\lib\model.js:743:34)
From previous event:
    at module.exports.Model.findAll (d:\GitProjects\bashed\node_modules\sequelize\lib\model.js:701:20)
    at module.exports.Model.findOne (d:\GitProjects\bashed\node_modules\sequelize\lib\model.js:794:36)
    at exports.venueByID (d:\GitProjects\bashed\app\controllers\venues.server.controller.js:149:14)
    at paramCallback (d:\GitProjects\bashed\node_modules\express\lib\router\index.js:384:7)
    at param (d:\GitProjects\bashed\node_modules\express\lib\router\index.js:364:5)
    at Function.proto.process_params (d:\GitProjects\bashed\node_modules\express\lib\router\index.js:390:3)
    at d:\GitProjects\bashed\node_modules\express\lib\router\index.js:227:12
    at Function.match_layer (d:\GitProjects\bashed\node_modules\express\lib\router\index.js:294:3)
```

//find method:

```
db.Venue.find({ where: {venueId: id},include: [{model: db.VenueAddress}]}).then(function(venue){
        if(!venue) {
            return next(new Error('Failed to load venue ' + id));
        } else {
                req.venue = venue;
                return next();
        }
    }).catch(function(err){
        return next(err);
    });
```

//models

```
var Venue = sequelize.define('Venue', {
            venueId: {
                type: DataTypes.INTEGER,
                allowNull: false,
                primaryKey: true,
                autoIncrement: true
            },
            name: {type: DataTypes.STRING, allowNull: false}
        },
        {
            timestamps: true,
            paranoid: true,
            freezeTableName: true,
            associate: function (models) {
                Venue.hasMany(models.VenueAddress, {through: models.VenueAddress,foreignKey: 'venueId'});
            }
        }
    );


 var VenueAddress = sequelize.define('VenueAddress', {
            addressId: {
                type: DataTypes.INTEGER,
                allowNull: false,
                primaryKey: true,
                autoIncrement: true
            },
            street: {type: DataTypes.STRING, allowNull: false},
            zipCode: {type: DataTypes.STRING, allowNull: false}
        },
        {
            timestamps: true,
            paranoid: true,
            freezeTableName: true,
            associate: function (models) {
                VenueAddress.belongsTo(models.Venue, {through: models.VenueAddress,foreignKey: 'venueId'});
            }
        }
    );
```

**Comment by mickhansen** [comment]
Please make the effort to properly format code in issues.
Looks like you need to remove the `through` propery from your `Venue.hasMany` association since it's not a N:M association.

**Comment by hfar** [comment]
Many thanks Mick..you are correct removing the 'through solved the issue.

and I am very sorry about formatting the code .. code is formatted now.

**Comment by mickhansen** [comment]
@hfar glad it solved your issue :)
