### ISSUE TITLE
[Migrations] Error changing a single column (fix included)

### ISSUE THREAD

**Issue by ameensol** [sequelize/sequelize#3334]
I was getting an error changing columns in migrations. 

```
Possibly unhandled TypeError: Cannot call method 'push' of undefined
    at Object.module.exports.QueryGenerator.dataTypeMapping (/home/ameen/Desktop/filter/overlord/node_modules/sequelize/lib/dialects/postgres/query-generator.js:826:32)
    at Object.module.exports.QueryGenerator.pgDataTypeMapping (/home/ameen/Desktop/filter/overlord/node_modules/sequelize/lib/dialects/postgres/query-generator.js:821:19)
    at Object.module.exports.QueryGenerator.changeColumnQuery (/home/ameen/Desktop/filter/overlord/node_modules/sequelize/lib/dialects/postgres/query-generator.js:231:31)
    at module.exports.QueryInterface.changeColumn (/home/ameen/Desktop/filter/overlord/node_modules/sequelize/lib/query-interface.js:382:37)
```

The error comes from the `primaryKeys` object not having the `tableName` attribute of the current table.

I fixed it by adding a single line at the beginning of the `changeColumnQuery`

``` js
    changeColumnQuery: function(tableName, attributes) {
      var query = 'ALTER TABLE <%= tableName %> ALTER COLUMN <%= query %>;'
        , sql = [];

      primaryKeys[tableName] = [];
```

**Comment by mickhansen** [comment]
What call are you making that produces the bug?
A PR with a unit test + the fix would be greatly appreciated.

**Comment by kytwb** [comment]
Just had this as well:
```
migration.addColumn('stocks', 'id', {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      allowNull: false,
      unique: true,
      primaryKey: true
    }).then(function () {
      done();
    });
```
