### ISSUE TITLE
Empty objects in WHERE clause result in error

### ISSUE THREAD

**Issue by purepear** [sequelize/sequelize#3341]
I'm using postgres and have a query like this:

```
Property.findAll({where: {
  title: {}
}}).then(function(){})
```

which fails: Possibly unhandled SequelizeDatabaseError: syntax error at or near ";"

I think i'll be better to add this validation inside Sequelize rather than dealing with outside..
Here's an example of what i want to do

```
app.get('/filter', function(req, res, next){
    var where = {
      category: req.query.category,
      isActive: true,
      price: {}
    }

    if(req.query.min_price)  where.price['$gte'] = req.query.min_price
    if(req.query.max_price) where.price['$lte'] = req.query.max_price

    Property.findAll({where: where}).then(function(properties){
      res.send('sadasda')
    })
  })
```

In order for this to work i have to check and cast both prices (because express js body-parser converts everything to string).. So convert the string into integer, check if it's not NaN (because if NaN we got error) then check if at least one of both prices is existing and not NaN otherwise delete where.price... ot in other words sth like this:

```
app.get('/filter', function(req, res, next){
    var where = {
      category: req.query.category,
      isActive: true
    }

    var min_price = parseInt(req.query.min_price)
    var max_price = parseInt(req.query.max_price)

    if(!isNaN(min_price) || !isNaN(max_price)){
      where.price = {}
      if(!isNaN(min_price)){
        where.price['$gte'] = min_price
      }
      if(!isNaN(max_price)){
        where.price['$lte'] = max_price
      }
    }

    Property.findAll({where: where}).then(function(properties){
      res.send('sadasda')
    })
  })
```

I know this can be optimised or written another way... but wouldn't it be better if Sequelize cast those types and handle the NaN(for example) situation on it's own... i use a lot of forms and converting objects from req.query/req.body and validating them according to my model fields is not very pleasant job.
I used Mongoose in my last project and all kinda worked ok just merging the req.body to the instance.

**Comment by mickhansen** [comment]
I agree that

```js
Property.findAll({where: {
  title: {}
}}).then(function(){})
```

Should not result in an error.

As for validating parameters to where, the question then arises whether it should be silent or explicit fail.

**Comment by BridgeAR** [comment]
I suggest to let it fail explicitly. This would probably be solved by #3472.

**Comment by xdvarpunen** [comment]
Any change on this?

**Comment by sushantdhiman** [comment]
This will now fail explicitly https://github.com/sequelize/sequelize/pull/6915 

```js
Using database:  sequelize-test-36
Error: Invalid value [object Object]
    at Object.escape (/var/www/github/sequelize/lib/sql-string.js:59:11)
    at Object.escape (/var/www/github/sequelize/lib/dialects/abstract/query-generator.js:736:22)
    at Object.whereItemQuery (/var/www/github/sequelize/lib/dialects/abstract/query-generator.js:2114:22)
    at _.forOwn (/var/www/github/sequelize/lib/dialects/abstract/query-generator.js:1763:25)
    at /var/www/github/sequelize/node_modules/lodash/lodash.js:4970:15
    at baseForOwn (/var/www/github/sequelize/node_modules/lodash/lodash.js:3020:24)
    at Function.forOwn (/var/www/github/sequelize/node_modules/lodash/lodash.js:12985:24)
    at Object.whereItemsQuery (/var/www/github/sequelize/lib/dialects/abstract/query-generator.js:1762:9)
    at Object.getWhereConditions (/var/www/github/sequelize/lib/dialects/abstract/query-generator.js:2180:19)
    at Object.selectQuery (/var/www/github/sequelize/lib/dialects/abstract/query-generator.js:942:28)
    at QueryInterface.select (/var/www/github/sequelize/lib/query-interface.js:635:27)
    at Promise.try.then.then.then (/var/www/github/sequelize/lib/model.js:1480:34)
```
