### ISSUE TITLE
Possibly unhandled TypeError: Cannot call method 'push' of undefined

### ISSUE THREAD

**Issue by mmahalwy** [sequelize/sequelize#3524]
Getting error:

```
Possibly unhandled TypeError: Cannot call method 'push' of undefined
    at [object Object].obj.(anonymous function) [as getMyProducts] (/Users/mmahalwy/Desktop/Code/startups/workplace/workplace/node_modules/sequelize/lib/associations/belongs-to-many.js:342:25)
    at [object Object].<anonymous> (/Users/mmahalwy/Desktop/Code/startups/workplace/workplace/server/routes.js:218:14)
    at tryCatch1 (/Users/mmahalwy/Desktop/Code/startups/workplace/workplace/node_modules/sequelize/node_modules/bluebird/js/main/util.js:45:21)
    at Promise._callHandler (/Users/mmahalwy/Desktop/Code/startups/workplace/workplace/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:571:13)
    at Promise._settlePromiseFromHandler (/Users/mmahalwy/Desktop/Code/startups/workplace/workplace/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAt (/Users/mmahalwy/Desktop/Code/startups/workplace/workplace/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:713:18)
    at Promise._settlePromiseAt (/Users/mmahalwy/Desktop/Code/startups/workplace/workplace/node_modules/sequelize/lib/promise.js:76:18)
    at Promise._settlePromises (/Users/mmahalwy/Desktop/Code/startups/workplace/workplace/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:854:14)
    at Async._consumeFunctionBuffer (/Users/mmahalwy/Desktop/Code/startups/workplace/workplace/node_modules/sequelize/node_modules/bluebird/js/main/async.js:85:12)
    at Async.consumeFunctionBuffer (/Users/mmahalwy/Desktop/Code/startups/workplace/workplace/node_modules/sequelize/node_modules/bluebird/js/main/async.js:40:14)
```

When doing:
```
app.delete('/api/my-products/:id', ensureAuthenticated, function (req, res) {
    models.User.find(req.user).then(function(user) {
        user.getMyProducts(req.params.id).then(function(p) {
          console.log(p)
          res.sendStatus(200)
        });
    });
  });
```

My models:
```
module.exports = function (sequelize, DataTypes) {
  var User = sequelize.define("User", {
    displayName: { type: DataTypes.STRING, allowNull: false},
    password: { type: DataTypes.STRING, allowNull: false},
    email: { type: DataTypes.STRING, allowNull: false, unique: true},
    cart: { type: DataTypes.JSON, allowNull: true, unique: false},
    admin: { type: DataTypes.BOOLEAN, defaultValue: false, allowNull: true, unique: false}
  }, {
    classMethods: {
      associate: function(models) {
        User.hasMany(models.Budget)
        User.belongsToMany(models.Product, {as: 'MyProducts', through: 'ProductsUsers'})
      }
    },
...
```

Product:
```
module.exports = function (sequelize, DataTypes) {
  var Product = sequelize.define("Product", {
    name: { type: DataTypes.STRING, allowNull: false},
    description: { type: DataTypes.STRING, allowNull: false},
    image: { type: DataTypes.STRING, allowNull: false},
    unit: { type: DataTypes.STRING, allowNull: false},
    quantity: { type: DataTypes.INTEGER, allowNull: false},
    price: { type: DataTypes.FLOAT, allowNull: false},
    visibleToAll: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false}
  }, {
    classMethods: {
      associate: function(models) {
        Product.belongsToMany(models.Microcategory, {through: 'MicrocategoriesProducts'})
        Product.belongsToMany(models.User, {as: 'Owners', through: 'ProductsUsers'})
...
```

**Comment by janmeier** [comment]
Use `getProducts({ where: { id: req.params.id }})` Passing an id directly is only allowed in `findAll`

**Comment by janmeier** [comment]
Closing this issue, since it is neither a bug report nor a feature request.

For general sequelize questions, please use [StackOverflow](https://stackoverflow.com/questions/tagged/sequelize.js) or [Google groups](https://groups.google.com/forum/#!forum/sequelize).
