### ISSUE TITLE
Update examples

### ISSUE THREAD

**Issue by chanakyap** [sequelize/sequelize#3537]
The example for associations is 2 years old. Will there be any updates? I would like an example on belongsTo for latest version.

**Comment by janmeier** [comment]
I'm not sure it even makes sense to have an examples directory, I think we should stick to having examples in the docs

**Comment by mickhansen** [comment]
@janmeier I think it's great for more full flegded examples and usecases. But they would have to be more real-world case like, a few of the ones we have now are rather contrived.

**Comment by janmeier** [comment]
Perhaps they could be integrated into a section on docs.sequelizejs.com then? If we want real world examples I think it makes more sense to write them in md so it's easier to explain about the reasoning for the example instead of just cod

**Comment by mickhansen** [comment]
http://runnable.com/ is also still an option

**Comment by chanakyap** [comment]
var User = this.sequelize.define('User', {/* attributes */})
  , Company  = this.sequelize.define('Company', {/* attributes */});

User.belongsTo(Company, {foreignKey: 'fk_company'}); // Adds fk_company to User


This is the example provided for belongsTO 
Will there be any getter/setter methods on user instance like getCompany and setCompay ?

**Comment by chanakyap** [comment]
var User = sequelize.define('User', { organizationId: {type: DataTypes.INTEGER, field: 'organization_id'})
, Organization = sequelize.define('Organization', {type: DataTypes.INTEGER, autoIncrement: true, primaryKey: true});
User.belongsTo(Organization, {foreignKey: 'organization_id'});

And User.findAll({include: {model: 'Organization'}}); throws this error

Possibly unhandled TypeError: undefined is not a function
    at module.exports.validateIncludedElement (/home/chanakya/Projects/gro-api/node_modules/hapi-sequelized/node_modules/sequelize/lib/model.js:1969:30)
    at module.exports.validateIncludedElements (/home/chanakya/Projects/gro-api/node_modules/hapi-sequelized/node_modules/sequelize/lib/model.js:1932:63)
    at null.<anonymous> (/home/chanakya/Projects/gro-api/node_modules/hapi-sequelized/node_modules/sequelize/lib/model.js:718:36)
    at tryCatch1 (/home/chanakya/Projects/gro-api/node_modules/hapi-sequelized/node_modules/sequelize/node_modules/bluebird/js/main/util.js:45:21)
    at Promise._callHandler (/home/chanakya/Projects/gro-api/node_modules/hapi-sequelized/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:571:13)
    at Promise._settlePromiseFromHandler (/home/chanakya/Projects/gro-api/node_modules/hapi-sequelized/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAt (/home/chanakya/Projects/gro-api/node_modules/hapi-sequelized/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:713:18)
    at Promise._settlePromiseAt (/home/chanakya/Projects/gro-api/node_modules/hapi-sequelized/node_modules/sequelize/lib/promise.js:76:18)
    at Promise._settlePromises (/home/chanakya/Projects/gro-api/node_modules/hapi-sequelized/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:854:14).


Also User.findAll({},{include: {model: 'Organization'}}) or User.findAll({},{include: [{model: 'Organization'}]}) does not throw any errors but i can find the organization in user , tried user.Organization //null
user.organization //null

Can any one help me with my code ? where i am going wrong ?

**Comment by janmeier** [comment]
`Organization should be a model instance, not a string

**Comment by chanakyap** [comment]
thanks, that worked.
