### ISSUE TITLE
bulkCreate unique constraint violation crashing application (sqlite)

### ISSUE THREAD

**Issue by cdmcnamara** [sequelize/sequelize#3546]
Hi, I'm writing a negative test case for my application and it appears that when attempting to perform a bulkCreate on an array of records in which one of those records purposely violates a unique constraint (SubPayments.due), the application crashes as oppose to gracefully handling that constraint violation. Here is an example:

```javascript
return sequelize.transaction(function(t) {
  return Promise.props({
    payment: models.Payments.create(payment, {transaction: t})
  }).then(function(result) {
    subPayments = this.addPaymentIdToSubPayments(subPayments, result.payment.id);
    return models.SubPayments.bulkCreate(subPayments, {transaction: t});
  });
}).then(function() {
  return Promise.resolve();
}).catch(function(error) {
  return Promise.reject(new Error('Error persisting payment'));
});

var Payments = db.define('payments', {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true
  }
  state: {
    type: Sequelize.STRING,
    allowNull: false
  }
}, {
  underscored: true,
  timestamps: true,
  createdAt: 'created_at',
  updatedAt: 'updated_at'
});

var SubPayments = db.define('sub_payments', {
  id: {
    type: Sequelize.INTEGER,
    autoIncrement: true,
    primaryKey: true
  },
  type: {
    type: Sequelize.STRING,
    allowNull: false
  },
  amount_value: {
    type: Sequelize.DECIMAL
  },
  due: {
    type: Sequelize.DATE,
    allowNull: false
  }
}, {
  underscored: true,
  timestamps: true,
  createdAt: 'created_at',
  updatedAt: 'updated_at',
});

Payments.hasMany(SubPayments, {
  as: 'SubPayments',
  foreign_key: 'payment_id'
});
SubPayments.belongsTo(Payments);
```
Produces the following stack trace:
```
 stack: 
   [ 'TypeError: Cannot read property \'__options\' of null',
     '    at [object Object].module.exports.Query.formatError (/Users/conner/workspace/example/node_modules/sequelize/lib/dialects/sqlite/query.js:227:35)',
     '    at Statement.<anonymous> (/Users/conner/workspace/example/node_modules/sequelize/lib/dialects/sqlite/query.js:53:31)',
     '--> in Statement#run([Function])',
     '    at Database.<anonymous> (/Users/conner/workspace/example/node_modules/sqlite3/lib/sqlite3.js:74:19)',
     '    at Database.<anonymous> (/Users/conner/workspace/example/node_modules/sqlite3/lib/sqlite3.js:21:19)',
     '    at /Users/conner/workspace/example/node_modules/sequelize/lib/dialects/sqlite/query.js:48:54',
     '    at sequelizeResolver (/Users/conner/workspace/example/node_modules/sequelize/lib/promise.js:32:12)',
     '    at tryCatch2 (/Users/conner/workspace/example/node_modules/sequelize/node_modules/bluebird/js/main/util.js:53:21)',
     '    at Promise._resolveFromResolver (/Users/conner/workspace/example/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:544:13)',
     '    at new Promise (/Users/conner/workspace/example/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:84:37)',
     '    at new SequelizePromise (/Users/conner/workspace/example/node_modules/sequelize/lib/promise.js:28:17)',
     '    at executeSql (/Users/conner/workspace/example/node_modules/sequelize/lib/dialects/sqlite/query.js:47:21)',
     '    at Database.<anonymous> (/Users/conner/workspace/example/node_modules/sequelize/lib/dialects/sqlite/query.js:181:18)',
     '    at /Users/conner/workspace/example/node_modules/sequelize/lib/dialects/sqlite/query.js:38:21',
     '    at sequelizeResolver (/Users/conner/workspace/example/node_modules/sequelize/lib/promise.js:32:12)',
     '    at tryCatch2 (/Users/conner/workspace/example/node_modules/sequelize/node_modules/bluebird/js/main/util.js:53:21)',
     '    at Promise._resolveFromResolver (/Users/conner/workspace/example/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:544:13)',
     '    at new Promise (/Users/conner/workspace/example/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:84:37)',
     '    at new SequelizePromise (/Users/conner/workspace/example/node_modules/sequelize/lib/promise.js:28:17)',
     '    at [object Object].module.exports.Query.run (/Users/conner/workspace/example/node_modules/sequelize/lib/dialects/sqlite/query.js:35:15)',
     '    at /Users/conner/workspace/example/node_modules/sequelize/lib/sequelize.js:753:20',
     '    at tryCatch1 (/Users/conner/workspace/example/node_modules/sequelize/node_modules/bluebird/js/main/util.js:45:21)',
     '    at Promise._callHandler (/Users/conner/workspace/example/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:571:13)',
     '    at Promise._settlePromiseFromHandler (/Users/conner/workspace/example/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:581:18)',
     '    at Promise._settlePromiseAt (/Users/conner/workspace/example/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:713:18)',
     '    at Promise._settlePromiseAt (/Users/conner/workspace/example/node_modules/sequelize/lib/promise.js:76:18)',
     '    at Promise._settlePromiseAtPostResolution (/Users/conner/workspace/example/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:335:10)',
     '    at Async._consumeFunctionBuffer (/Users/conner/workspace/example/node_modules/sequelize/node_modules/bluebird/js/main/async.js:85:12)',
     '    at Async.consumeFunctionBuffer (/Users/conner/workspace/example/node_modules/sequelize/node_modules/bluebird/js/main/async.js:40:14)',
     '    at process._tickCallback (node.js:419:13)' ] }
```
I'm using sqlite as my dialect and v2.0.5 of Sequelize.

It looks like this issue is related: https://github.com/sequelize/sequelize/issues/2844 (but mysql dialect)

Thanks in advanced for your help.

**Comment by 5an1ty** [comment]
Experiencing the same issue with sqlite. I'm violating a pkConstraint but the application crashes instead of showing the pkConstraint error.

Also why don't we have a bulkUpsert?

**Comment by mickhansen** [comment]
@5an1ty No way to implement bulkUpsert across all dialects, upsert on its own uses a few tricks.

**Comment by Kevin-A** [comment]
Same issue here. Using `2.1.0` and `sqlite`.

**Comment by BridgeAR** [comment]
Could you please insert your real test case. Your example uses functions that do not exist and it does not seem to fit to your explanation (due is not unique).
