### ISSUE TITLE
sqlite3 happen 'unable to open database file' error sometimes

### ISSUE THREAD

**Issue by elover** [sequelize/sequelize#3551]
error log
```
{ [SequelizeDatabaseError: SQLITE_CANTOPEN: unable to open database file]
  name: 'SequelizeDatabaseError',
  message: 'SQLITE_CANTOPEN: unable to open database file',
  parent: 
   { [Error: SQLITE_CANTOPEN: unable to open database file]
     errno: 14,
     code: 'SQLITE_CANTOPEN',
     sql: 'SELECT `id`, `name`, `owner`, `templateConfig`, `des`, `time`, `status`, `createdAt`, `updatedAt` FROM `Pages` AS `Page` ORDER BY time DESC LIMIT 20;' },
  original: 
   { [Error: SQLITE_CANTOPEN: unable to open database file]
     errno: 14,
     code: 'SQLITE_CANTOPEN',
     sql: 'SELECT `id`, `name`, `owner`, `templateConfig`, `des`, `time`, `status`, `createdAt`, `updatedAt` FROM `Pages` AS `Page` ORDER BY time DESC LIMIT 20;' },
  sql: 'SELECT `id`, `name`, `owner`, `templateConfig`, `des`, `time`, `status`, `createdAt`, `updatedAt` FROM `Pages` AS `Page` ORDER BY time DESC LIMIT 20;' }
SequelizeDatabaseError: SQLITE_CANTOPEN: unable to open database file
    at module.exports.Query.formatError (/root/fed/quick/trunk/node_modules/sequelize/lib/dialects/sqlite/query.js:245:16)
    at Statement.<anonymous> (/root/fed/quick/trunk/node_modules/sequelize/lib/dialects/sqlite/query.js:53:31)
    at Statement.replacement (/root/fed/quick/trunk/node_modules/sqlite3/lib/trace.js:20:31)
    at Statement.replacement (/root/fed/quick/trunk/node_modules/sqlite3/lib/trace.js:20:31)

```
this is happend sometimes,i can not find why?

**Comment by janmeier** [comment]
It's impossible to debug without more information. I've run sqlite thousands of times and never seen that error, so :-) 

You need to give some more details: which options are you passing to the sequelize constructor? Which os are you on, which version of the sqlite library are you using? 

My guess is very much that this is an issue with file permissions or the sqlite lib, not with sequelize

**Comment by elover** [comment]
my db file permissions is: 
-rw-r--r--. 1 root root 24345600 Apr 17 15:09 quick.db

json options:
```
{
  "production": {
    "dialect": "sqlite",
    "storage": "./db/quick.db",
    "logging": false
  }
}
```
page module
```
"use strict";
module.exports = function(sequelize, DataTypes) {
  var Page = sequelize.define("Page", {
    name: DataTypes.STRING,
    owner: DataTypes.STRING,
    templateConfig: DataTypes.TEXT,
    des: DataTypes.STRING,
    time: DataTypes.STRING,
    status: DataTypes.STRING
  }, {
    classMethods: {
      associate: function(models) {
        // associations can be defined here
      }
    }
  });
  return Page;
};
```
select
```
function getAllPage(limit,offset,filter,callback) {
    models.Page
        .findAndCountAll({limit:limit,offset:offset,where:filter,order:'time DESC'},{raw: true})
        .then(function (pages) {
            callback(null, pages);
        }).catch(function (err) {
            callback(err);
        })
};
```
sqlite3 version: 3.0.5
sequelize version: 2.0.4
system: CentOS release 6.5

most time is ok,it happen error sometimes;

**Comment by janmeier** [comment]
Are you running your scripts as root, since only root has permission to modify that file?

**Comment by elover** [comment]
yes,this error is happended sometime （about ten thousandth）. 
most time is ok. 
maybe trigger by other uncaughtException error.
i use forerver run node app ,this error can make forever exit，i must restart app.

**Comment by janmeier** [comment]
Without more information we cannot debug this further. Perhaps ask if someone has had similar problems in mapbox/node-sqlite3

**Comment by SebastianGuerreroCardenas** [comment]
Currently having an issue similar to this. I think it is something to do with permissions but I dont know how to fix it

**Comment by tresayle** [comment]
I have the same issue

**Comment by dozieogbo** [comment]
So. I realized this can happen when the parent folder doesn't exist, in this case **db**.
Create the folder and it works fine.
