### ISSUE TITLE
sequelize.sync() with lots of .then()s triggers possible memory leak warning re sql listeners

### ISSUE THREAD

**Issue by MichaelJCole** [sequelize/sequelize#3559]
Hi, I'm getting this warning: 
```
warning: possible EventEmitter memory leak detected. 11 sql listeners added. Use emitter.setMaxListeners() to increase limit.
```

Which seems weird when I'm just Promising things around.  It happens the second time I include helper.js below.

```
(node) warning: possible EventEmitter memory leak detected. 11 sql listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Promise.addListener (events.js:179:15)
    at Promise.on (/home/michael/bigSmall/big_www/node_modules/sequelize/lib/promise.js:127:31)
    at Promise.<anonymous> (/home/michael/bigSmall/big_www/node_modules/sequelize/lib/promise.js:277:10)
    at Array.forEach (native)
    at Promise.proxy (/home/michael/bigSmall/big_www/node_modules/sequelize/lib/promise.js:276:18)
    at Promise.proxySql (/home/michael/bigSmall/big_www/node_modules/sequelize/lib/promise.js:287:15)
    at Promise._then (/home/michael/bigSmall/big_www/node_modules/sequelize/lib/promise.js:67:10)
    at Promise.then (/home/michael/bigSmall/big_www/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:140:17)
    at Object.helper.agentP (/home/michael/bigSmall/big_www/src/server/routes/auth.helper.js:34:6)
    at Context.helper.newSignUp (/home/michael/bigSmall/big_www/src/server/routes/auth.helper.js:55:6)
    at Hook.Runnable.run (/home/michael/.nvm/versions/v0.12.0/lib/node_modules/mocha/lib/runnable.js:233:15)
    at next (/home/michael/.nvm/versions/v0.12.0/lib/node_modules/mocha/lib/runner.js:271:10)
    at Immediate._onImmediate (/home/michael/.nvm/versions/v0.12.0/lib/node_modules/mocha/lib/runner.js:292:5)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

I'm chaining .then()'s from sequelize.sync() as a way to see if my app is ready to serve, like this:

```
// server.js
var Promise = require('bluebird');
var appP = sequelize.sync()
  // Promise a sync'd version of the database
  .then(function(lastTable) {
    return Promise.resolve(sequelize);
  })
.then(function (db) {
  // Promise a configured and ready version of my app server
  var app = express()
  app.use(the.world);
  ...
  return app;
})
then(function(app) {
  // Promise a started app if !testing
  if (!testing) app.listen(port);               
  return app;
})
```

That promise to the ready app (appP below), is sent to mocha for testing with supertest agent's...

```
// auth.helper.js  
  // Agent Promise, from App Promise
  var appP = require('../server');

  helper.agentP = function() {
    return appP
    .then(function(app) {      // auth.helper.js:34 in stack below
      // Suppress memory leak warnings
      helper.app = app;
      helper.agent = supertest.agent(app);
      return helper.agent;
    });
  };

 // make new 'signed up' agent
  helper.newSignUp = function(done) {
    helper
    .agentP()
    .then(function(agent) {                     // /auth.helper.js:55
      return helper.signUp(agent, null);
    })
    .then(function(user) {
      done();
    });
  };
```

This get's used in supertests beforeEach for each test.
```
  // make new 'clean' agent
  helper.newAgent = function(done) {
    helper.agentP().then(function(agent) {
      done();
    });
  };
```

**Comment by MichaelJCole** [comment]
Putting this in my server.js was a workaround on node 0.12:

```
require('events').EventEmitter.defaultMaxListeners = 10000;
```

**Comment by mickhansen** [comment]
We're completely removing the event emitter code as soon as possible (reworking a lot of tests currently).
That should take care of this issue.

**Comment by MichaelJCole** [comment]
Awesome!  Thanks!

**Comment by clarkie** [comment]
@mickhansen have you managed to make any progress on this? Thanks

For now I'm using @MichaelJCole's workaround.

**Comment by mickhansen** [comment]
@clarkie Sequelize doesn't use event emitters anymore.
