### ISSUE TITLE
models/index.js incorrectly loads all models

### ISSUE THREAD

**Issue by jez** [sequelize/sequelize#3638]
The `models/index.js` file incorrectly loads models from the `models/` directory. It assumes that every file included in this directory is a `.js` file.

When my `models/` folder looks like this:

```plain
models
├── index.js
├── queue.js
├── spot.js
└── tags

0 directories, 4 files
```

I get the following error:

```plain
1 May 22:27:18 - [nodemon] v1.3.7
1 May 22:27:18 - [nodemon] to restart at any time, enter `rs`
1 May 22:27:18 - [nodemon] watching: *.*
1 May 22:27:18 - [nodemon] starting `node ./bin/www`
/<path omitted>/models/tags:1
xports, require, module, __filename, __dirname) { !_TAG_FILE_SORTED	2	/0=unsor
                                                                   	^
SyntaxError: Unexpected number
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at module.exports.Sequelize.import (/<path omitted>/node_modules/sequelize/lib/sequelize.js:624:63)
    at /<path omitted>/models/index.js:18:36
    at Array.forEach (native)
    at Object.<anonymous> (/<path omitted>/models/index.js:17:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
1 May 22:27:19 - [nodemon] app crashed - waiting for file changes before starting...
```

This is because `models/index.js` tries to load the `tags` file as a JavaScript file. The fix is simply to check for file extensions in `models/index.js`.

**Comment by mickhansen** [comment]
What are you referring to exactly? https://github.com/sequelize/express-example? If so please open an issue there.

Sequelize doesn't do auto loading on it's own.

**Comment by jez** [comment]
Oh, I was talking about the file `models/index.js`. It looks like this is created by `sequelize-cli`, so I'll open it there.
