### ISSUE TITLE
belongsToMany giving TypeError: undefined is not a function

### ISSUE THREAD

**Issue by akshay194** [sequelize/sequelize#3639]
I am using sequelize with express, I have defined my model like this

```javascript
"use strict";

var Sequelize = require('sequelize');
module.exports = function(sequelize, DataTypes) {
    var Order = sequelize.define("Order",
        {
            status: {
                type: Sequelize.INTEGER
            },
            notes: {
                type: Sequelize.STRING
            }
        },
        {
            classMethods: {
                associate: function(models) {
                    Order.belongsTo(models.User);
                    Order.belongsTo(models.Address);

                    Order.belongsToMany(models.Items);
                }
            }
        }

    );
    return Order;
}
```

I am getting following error message when trying to run my app

Order.belongsToMany(models.Items );
          ^
TypeError: undefined is not a function
    at sequelize.define.classMethods.associate (models/order.js:18:7)
    at models/index.js:24:19
    at Array.forEach (native)
    at Object.<anonymous> (models/index.js:22:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

My index.js file is same as one given is express example.

I have also tried giving belongsToMany in app.js but it does not work. All other associations are working correctly.
Please help.

**Comment by mickhansen** [comment]
Please make the effort to properly format your code if you want us to take the effort to debug your issue.
What version are you using? Can try logging `Order.belongsToMany` and `Object.keys(Order)`?

**Comment by akshay194** [comment]
Version is sequelize@2.0.0-rc1

Following is the output of console.log(db['Order']);
```
{ options: 
   { timestamps: true,
     createdAt: 'createdAt',
     updatedAt: 'updatedAt',
     deletedAt: 'deletedAt',
     instanceMethods: {},
     classMethods: { associate: [Function] },
     validate: {},
     freezeTableName: false,
     underscored: false,
     underscoredAll: false,
     paranoid: false,
     whereCollection: null,
     schema: null,
     schemaDelimiter: '',
     defaultScope: null,
     scopes: null,
     hooks: { beforeCreate: [], afterCreate: [] },
     name: { plural: 'Orders', singular: 'Order' },
     indexes: [],
     omitNull: false,
     sequelize: 
      { options: [Object],
        config: [Object],
        dialect: [Object],
        models: [Object],
        daoFactoryManager: [Object],
        modelManager: [Object],
        connectionManager: [Object],
        importCache: [Object],
        queryInterface: [Object] },
     uniqueKeys: {},
     hasPrimaryKeys: true },
  associations: {},
  daoFactoryManager: 
   { daos: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Circular],
        [Object],
        [Object] ],
     sequelize: 
      { options: [Object],
        config: [Object],
        dialect: [Object],
        models: [Object],
        daoFactoryManager: [Circular],
        modelManager: [Circular],
        connectionManager: [Object],
        importCache: [Object],
        queryInterface: [Object] } },
  modelManager: 
   { daos: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Circular],
        [Object],
        [Object] ],
     sequelize: 
      { options: [Object],
        config: [Object],
        dialect: [Object],
        models: [Object],
        daoFactoryManager: [Circular],
        modelManager: [Circular],
        connectionManager: [Object],
        importCache: [Object],
        queryInterface: [Object] } },
  name: 'Order',
  scopeObj: {},
  sequelize: 
   { options: 
      { dialect: 'postgres',
        dialectModulePath: null,
        host: '127.0.0.1',
        protocol: 'tcp',
        define: {},
        query: {},
        sync: {},
        timezone: '+00:00',
        logging: [Function],
        omitNull: false,
        native: false,
        replication: false,
        ssl: undefined,
        pool: {},
        quoteIdentifiers: true,
        username: 'postgres',
        password: '******',
        database: '*****' },
     config: 
      { database: '******',
        username: '********',
        password: '********',
        host: '127.0.0.1',
        port: 5432,
        pool: [Object],
        protocol: 'tcp',
        queue: undefined,
        native: false,
        ssl: undefined,
        replication: false,
        dialectModulePath: null,
        maxConcurrentQueries: undefined,
        dialectOptions: undefined },
     dialect: { sequelize: [Circular], connectionManager: [Object] },
     models: 
      { Address: [Object],
        Category: [Object],
        City: [Object],
        Item: [Object],
        Locality: [Object],
        Merchant: [Object],
        MerchantCategoryMap: [Object],
        Order: [Circular],
        Tile: [Object],
        User: [Object] },
     daoFactoryManager: { daos: [Object], sequelize: [Circular] },
     modelManager: { daos: [Object], sequelize: [Circular] },
     connectionManager: 
      { sequelize: [Circular],
        config: [Object],
        dialect: [Object],
        onProcessExit: [Function],
        lib: [Object],
        pool: [Object] },
     importCache: 
      { '/models/address.js': [Object],
        '/models/category.js': [Object],
        '/models/city.js': [Object],
        '/models/item.js': [Object],
        '/models/locality.js': [Object],
        '/models/merchant.js': [Object],
        '/models/merchantCategoryMap.js': [Object],
        '/models/order.js': [Circular],
        '/models/tile.js': [Object],
        '/models/user.js': [Object] },
     queryInterface: { sequelize: [Circular], QueryGenerator: [Object] } },
  underscored: undefined,
  tableName: 'Orders',
  rawAttributes: 
   { id: 
      { type: [Object],
        allowNull: false,
        primaryKey: true,
        autoIncrement: true,
        _autoGenerated: true,
        Model: [Circular],
        fieldName: 'id',
        _modelAttribute: true },
     status: 
      { type: [Object],
        Model: [Circular],
        fieldName: 'status',
        _modelAttribute: true },
     notes: 
      { type: [Object],
        Model: [Circular],
        fieldName: 'notes',
        _modelAttribute: true },
     createdAt: 
      { type: 'DATETIME',
        allowNull: false,
        _autoGenerated: true,
        Model: [Circular],
        fieldName: 'createdAt',
        _modelAttribute: true },
     updatedAt: 
      { type: 'DATETIME',
        allowNull: false,
        _autoGenerated: true,
        Model: [Circular],
        fieldName: 'updatedAt',
        _modelAttribute: true } },
  attributes: 
   { id: 
      { type: [Object],
        allowNull: false,
        primaryKey: true,
        autoIncrement: true,
        _autoGenerated: true,
        Model: [Circular],
        fieldName: 'id',
        _modelAttribute: true },
     status: 
      { type: [Object],
        Model: [Circular],
        fieldName: 'status',
        _modelAttribute: true },
     notes: 
      { type: [Object],
        Model: [Circular],
        fieldName: 'notes',
        _modelAttribute: true },
     createdAt: 
      { type: 'DATETIME',
        allowNull: false,
        _autoGenerated: true,
        Model: [Circular],
        fieldName: 'createdAt',
        _modelAttribute: true },
     updatedAt: 
      { type: 'DATETIME',
        allowNull: false,
        _autoGenerated: true,
        Model: [Circular],
        fieldName: 'updatedAt',
        _modelAttribute: true } },
  primaryKeys: 
   { id: 
      { type: [Object],
        allowNull: false,
        primaryKey: true,
        autoIncrement: true,
        _autoGenerated: true,
        Model: [Circular],
        fieldName: 'id',
        _modelAttribute: true } },
  _timestampAttributes: { createdAt: 'createdAt', updatedAt: 'updatedAt' },
  associate: [Function],
  primaryKeyAttributes: [ 'id' ],
  primaryKeyAttribute: 'id',
  primaryKeyCount: 1,
  hasPrimaryKeys: true,
  _hasPrimaryKeys: true,
  _isPrimaryKey: { [Function] cache: {} },
  DAO: { [Function] super_: [Function] },
  Instance: { [Function] super_: [Function] },
  _readOnlyAttributes: [ 'createdAt', 'updatedAt' ],
  _hasReadOnlyAttributes: 2,
  _isReadOnlyAttribute: { [Function] cache: {} },
  tableAttributes: 
   { id: 
      { type: [Object],
        allowNull: false,
        primaryKey: true,
        autoIncrement: true,
        _autoGenerated: true,
        Model: [Circular],
        fieldName: 'id',
        _modelAttribute: true },
     status: 
      { type: [Object],
        Model: [Circular],
        fieldName: 'status',
        _modelAttribute: true },
     notes: 
      { type: [Object],
        Model: [Circular],
        fieldName: 'notes',
        _modelAttribute: true },
     createdAt: 
      { type: 'DATETIME',
        allowNull: false,
        _autoGenerated: true,
        Model: [Circular],
        fieldName: 'createdAt',
        _modelAttribute: true },
     updatedAt: 
      { type: 'DATETIME',
        allowNull: false,
        _autoGenerated: true,
        Model: [Circular],
        fieldName: 'updatedAt',
        _modelAttribute: true } },
  autoIncrementField: 'id',
  _booleanAttributes: [],
  _dateAttributes: [ 'createdAt', 'updatedAt' ],
  _hstoreAttributes: [],
  _virtualAttributes: [],
  _defaultValues: {},
  _hasBooleanAttributes: false,
  _isBooleanAttribute: { [Function] cache: {} },
  _hasDateAttributes: true,
  _isDateAttribute: { [Function] cache: {} },
  _hasHstoreAttributes: false,
  _isHstoreAttribute: { [Function] cache: {} },
  _hasVirtualAttributes: false,
  _isVirtualAttribute: { [Function] cache: {} },
  _hasDefaultValues: false }

```

**Comment by mickhansen** [comment]
Well that version is likely before we introduced belongsToMany then. You should upgrade or if you dont want to upgrade you should use the deprecated 2 x hasMany.

**Comment by akshay194** [comment]
Thanks it worked after upgrading
