### ISSUE TITLE
2.0.6? utcOffset?

### ISSUE THREAD

**Issue by streetkid** [sequelize/sequelize#3647]
Hi 

I updated to 2.0.6 and a create function is now saying [TypeError: Object Tue May 05 2015 15:42:19 GMT+1000 has no method 'utcOffset']

Not sure where it comes from i don't call the method utcOffset anywhere in my code.

Possibly coming from one of the default fields createdAt / updatedAt?

**Comment by janmeier** [comment]
The only time we call `utcOffset` is here https://github.com/sequelize/sequelize/blob/master/lib/sql-string.js#L167. Could you try re-installing seqeulize's dependencies?

**Comment by janmeier** [comment]
No response, closing

**Comment by Lcfvs** [comment]
Hi,

Similar problem @3.19.2 :

```js
void function() {
    'use strict';
    
    var
    Sequelize,
    sequelize,
    User;
    
    Sequelize = require('sequelize');
    
    sequelize = new Sequelize('mysql://root:pass@localhost:2000/db');
    
    User = sequelize.define('User', {
        firstName: {
            type: Sequelize.STRING
        },
        lastName: {
            type: Sequelize.STRING
        }
    }, {
        freezeTableName: true
    });

    User.create({
        firstName: 'John',
        lastName: 'Hancock'
    })
    .then(function(user) {
        console.log(user);
    });
}();
```
```
Unhandled rejection TypeError: date.utcOffset is not a function
    at DATE.$applyTimezone (D:\projects\js\tests\node_modules\sequelize\lib\data-types.js:457:19)
    at DATE.$stringify (D:\projects\js\tests\node_modules\sequelize\lib\dialects\mysql\data-types.js:38:37)
    at ABSTRACT.stringify (D:\projects\js\tests\node_modules\sequelize\lib\data-types.js:76:17)
    at Object.QueryGenerator.escape (D:\projects\js\tests\node_modules\sequelize\lib\dialects\abstract\query-generator.js:972:32)
    at Object.QueryGenerator.insertQuery (D:\projects\js\tests\node_modules\sequelize\lib\dialects\abstract\query-generator.js:298:28)
    at QueryInterface.insert (D:\projects\js\tests\node_modules\sequelize\lib\query-interface.js:492:33)
    at null.<anonymous> (D:\projects\js\tests\node_modules\sequelize\lib\instance.js:665:56)
    at tryCatcher (D:\projects\js\tests\node_modules\sequelize\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\projects\js\tests\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:497:31)
    at Promise._settlePromise (D:\projects\js\tests\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:555:18)
    at Promise._settlePromise0 (D:\projects\js\tests\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:600:10)
    at Promise._settlePromises (D:\projects\js\tests\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:683:18)
    at Async._drainQueue (D:\projects\js\tests\node_modules\sequelize\node_modules\bluebird\js\release\async.js:125:16)
    at Async._drainQueues (D:\projects\js\tests\node_modules\sequelize\node_modules\bluebird\js\release\async.js:135:10)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\projects\js\tests\node_modules\sequelize\node_modules\bluebird\js\release\async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by janmeier** [comment]
@Lcfvs Works fine for me - `utcOffset` is a moment.js function, so perhaps there was a problem with moment on windows? Can you create a [SSCCE](HTTP://SSCCE.ORG/)?

**Comment by Lcfvs** [comment]
I tried many times, before my post and after yours : bug, each time.

Strangely, I installed moment to test your explanation and, since, my code runs fine. o_O

I don't understand, sorry...

**Comment by janmeier** [comment]
Seems there was a problem with the installation when moment was installed together with sequelize then :)

**Comment by Lcfvs** [comment]
It's a really strange bug... but thanks for your tool :)
