### ISSUE TITLE
Unhandled rejection error for first migration

### ISSUE THREAD

**Issue by jlamberg** [sequelize/sequelize#3666]
We found that running `sequelize db:migrate` failed for the first migration on a clean application install.

The error message was this:

    Loaded configuration file "config/config.json".
    Using environment "production".
    == 20150127172246-create-employee: migrating =======
    Unhandled rejection Error: [object Object],[object Object]
       at Object.ensureErrorObject (/tmp/****/common/node_modules/sequelize/node_modules/bluebird/js/main/util.js:228:20)
       at Promise._rejectUncheckedCheckError (/tmp/****/common/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:606:22)
       at Promise._settlePromiseAt (/home/****/****/node-v0.12.2-linux-x64/lib/node_modules/sequelize-cli/node_modules/bluebird/js/main/promise.js:528:21)
       at Promise._settlePromises (/home/****/****/node-v0.12.2-linux-x64/lib/node_modules/sequelize-cli/node_modules/bluebird/js/main/promise.js:646:14)
       at Async._drainQueue (/home/****/****/node-v0.12.2-linux-x64/lib/node_modules/sequelize-cli/node_modules/bluebird/js/main/async.js:175:16)
       at Async._drainQueues (/home/****/****/node-v0.12.2-linux-x64/lib/node_modules/sequelize-cli/node_modules/bluebird/js/main/async.js:185:10)
       at Immediate.Async.drainQueues [as _onImmediate] (/home/****/****/node-v0.12.2-linux-x64/lib/node_modules/sequelize-cli/node_modules/bluebird/js/main/async.js:15:14)
       at processImmediate [as _immediateCallback] (timers.js:358:17)

The `up` function of our first migration looks like this:

    function(migration, DataTypes, done) {
      migration.createTable("Employees", {
        id: {
          allowNull: false,
          autoIncrement: true,
          primaryKey: true,
          type: DataTypes.INTEGER
        },
        first_name: {
          type: DataTypes.STRING
        },
        last_name: {
          type: DataTypes.STRING
        },
        createdAt: {
          allowNull: false,
          type: DataTypes.DATE
        },
        updatedAt: {
          allowNull: false,
          type: DataTypes.DATE
        }
      }).done(done);
    }

We used the following relevant versions:

Sequelize [Node: 0.12.2, CLI: 1.7.0, ORM: 2.1.0, mysql: ^2.5.5]

We got around this by degrading the versions to these:

Sequelize [Node: 0.10.35, CLI: 1.4.0, ORM: 2.0.4, mysql: ^2.5.5

where the ORM version mattered.

Sorry we didn't have time to investigate it further apart from testing it with another version.

**Comment by janmeier** [comment]
`.done` is called with the results from sequelize.query but the done callback see it as error objects.

Try either removing the done callback from the function and returning the promise chain or using `.nodeify(done)`

**Comment by tadman** [comment]
In the [Migration documentation](http://docs.sequelizejs.com/en/latest/docs/migrations/) it's recommended to use `complete`. Is that the correct way or is `nodeify` a better plan?

**Comment by mickhansen** [comment]
@tadman That documentation needs to be updated it seems. umzug (the migration library we recommend these days) support just returning a promise.

**Comment by jlamberg** [comment]
@janmeier Thanks, changing every place using `.done(done)` to `.nodeify(done)` worked. 

@tadman Where did you find a recommendation for using `complete`? I could not find anything related to calling the `done` callback from the link you provided, unless the docs have changed regarding that since I created this issue.

**Comment by tadman** [comment]
@jlamberg It was in the previous version of the documentation which has now been updated to use the promise-driven approach which is much cleaner.

Thanks to whomever made this change to clarify what's possible.
