### ISSUE TITLE
Weird cls transaction error

### ISSUE THREAD

**Issue by BridgeAR** [sequelize/sequelize#3674]
Hey, I can't explain this error, maybe you might have an idea:

```
Executing (3d49ccf5-3e2f-4db2-a6c0-a87012e8ad56): START TRANSACTION;
Executing (3d49ccf5-3e2f-4db2-a6c0-a87012e8ad56): UPDATE "User" SET "misc"='"lastLogin"=>"Fri May 08 2015 01:44:01 GMT+0200 (CEST)"',"updatedAt"='2015-05-07 23:44:01.245 +00:00' WHERE "id" = '58384c31-1f0d-40ef-80f1-be9ce614a158'
Executing (3d49ccf5-3e2f-4db2-a6c0-a87012e8ad56): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (3dc3e9eb-1746-4fe1-a10b-e5ee654c80eb): COMMIT;
SequelizeDatabaseError: ERROR:  SET TRANSACTION ISOLATION LEVEL must be called before any query
    at module.exports.Query.formatError (/node_modules/sequelize/lib/dialects/postgres/query.js:421:16)
    at null.<anonymous> (/node_modules/sequelize/lib/dialects/postgres/query.js:105:21)
    at emit (events.js:107:17)
    at NativeQuery.handleError (/node_modules/pg/lib/native/query.js:41:10)
    at after (/node_modules/pg/lib/native/query.js:59:19)
    at bound (domain.js:254:14)
    at runBound (domain.js:267:12)
    at onError (/node_modules/pg-native/index.js:160:5)
    at g (events.js:199:16)
    at emit (events.js:129:20)
    at Client._readError (/node_modules/pg-native/index.js:81:8)
    at Client._read (/node_modules/pg-native/index.js:121:19)
    at PQ.emit (events.js:104:17)
From previous event:
    at module.exports.Query.run (/node_modules/sequelize/lib/dialects/postgres/query.js:97:19)
    at /node_modules/sequelize/lib/sequelize.js:744:20
From previous event:
    at Promise._then (/node_modules/sequelize/lib/promise.js:14:16)
    at transactionResolver (/node_modules/sequelize/lib/sequelize.js:1137:42)
    at /node_modules/continuation-local-storage/context.js:74:17
From previous event:
    at module.exports.Sequelize.transaction (/node_modules/sequelize/lib/sequelize.js:1161:14)
    at Strategy._verify (/server/config/passport.js:53:19)
    at Strategy.authenticate (/node_modules/passport-local/lib/strategy.js:90:12)
    at attempt (/node_modules/passport/lib/middleware/authenticate.js:341:16)
    at authenticate (/node_modules/passport/lib/middleware/authenticate.js:342:7)
    at /server/api/routes/auth.js:73:11
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:82:5)
    at next (/node_modules/express/lib/router/route.js:110:13)
    at /server/middlewares/authorization.js:460:13
    at /node_modules/continuation-local-storage/context.js:74:17
    at bound (domain.js:254:14)
    at Promise.runBound (domain.js:267:12)
```

I'm using passport and it's only happening inside the passport callback while deserialising users and using the local strategy. Explicit transactions work just fine.

**Comment by janmeier** [comment]
Can you show some code that reproduces the error?

**Comment by mickhansen** [comment]
Looks like a transaction is leaking somehow.
It also looks like we set the transaction in CLS before it's fully ready @janmeier ?

**Comment by mickhansen** [comment]
Maybe https://github.com/sequelize/sequelize/blob/master/lib/transaction.js#L126 this line should be moved down a bit.

**Comment by janmeier** [comment]
Hmm maybe, but the callback will never be invoked before `prepareEnvironment` is done

**Comment by BridgeAR** [comment]
I'll try to extract the error case tomorrow and I'll check if moving line 126 down solved the issue.

**Comment by mark-tussock** [comment]
Any progress with this? I seem to be getting a similar issue and not really sure why.

**Comment by mickhansen** [comment]
Yeah i'm pretty certain it might be a race since the transaction is set before its ready, it might leak, not sure :p

**Comment by Americas** [comment]
changing the prepareEnvironment does nothing for me, I'm not using cls. But I get the same error every so often and from the logs, there isn't even a query being done between starting the transaction and setting the isolation level.

```
Executing (996dfdc9-2c24-4a12-9fd3-febade6a5cd2): START TRANSACTION;
Executing (996dfdc9-2c24-4a12-9fd3-febade6a5cd2): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Unhandled rejection SequelizeDatabaseError: SET TRANSACTION ISOLATION LEVEL must be called before any query
    at Query.formatError (/workrepos/phoenix/store/node_modules/sequelize/lib/dialects/postgres/query.js:420:14)
    at null.<anonymous> (/workrepos/phoenix/store/node_modules/sequelize/lib/dialects/postgres/query.js:104:19)
    at emitOne (events.js:77:13)
    at emit (events.js:166:7)
    at Query.handleError (/workrepos/phoenix/store/node_modules/pg/lib/query.js:99:8)
    at null.<anonymous> (/workrepos/phoenix/store/node_modules/pg/lib/client.js:166:26)
    at emitOne (events.js:77:13)
    at emit (events.js:166:7)
    at Socket.<anonymous> (/workrepos/phoenix/store/node_modules/pg/lib/connection.js:109:12)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:166:7)
    at readableAddChunk (_stream_readable.js:145:16)
    at Socket.Readable.push (_stream_readable.js:109:10)
    at TCP.onread (net.js:509:20)
```

**Comment by janmeier** [comment]
@Americas its hard for us to debug without any code :). Even if you can just provide some code that fails _sometimes_ we can try to work from there

**Comment by Americas** [comment]
@janmeier it is hard for me as well! But with further research, we concluded that this seems to be a problem with mocha that for some reason affects sequelize when testing. I believe we were able solve this issue :smiley:

**Comment by janmeier** [comment]
@Americas glad to hear it :)

**Comment by cwhatley** [comment]
@Americas any tips on what you did to deal with the mocha effects? I am running into this as well.

**Comment by Americas** [comment]
@cwhatley what fixed it for us was adding the `--globals hasCert` to our mocha configuration.

In case of a gulpfile:
```javascript
$.mocha({
            ...
            globals     : ["hasCert"],
            ...
})
```

**Comment by Ghirro** [comment]
We weren't using under mocha and were getting the same issue. Seemed to occur when we were running the same transaction on a timer that was shorter than the time the execution of the query took. The earlier posted fix worked as a workaround to preventing the race condition.

I can't post our code (proprietary) but will try and put together a test case.

Issued a PR under https://github.com/sequelize/sequelize/pull/4113

**Comment by janmeier** [comment]
CLS is now being set as late as possible, and removed as early as possible
