### ISSUE TITLE
Include all in defaultScope

### ISSUE THREAD

**Issue by RSSGergelyMunkacsy** [sequelize/sequelize#3690]
We have a User - Image association: a user has a profile and a cover image. I would like to set an automatically association with defaultScope.

(The project is created with `sails.js` and `waterline` but we decide to replace `waterline` with `sequelize`. The code base is huge, we want to keep as many as possible, so this is why the model definition is look strange.)

User model:
```
module.exports = {
  attributes: {
    userId: {
      type: Sequelize.INTEGER,
      primaryKey: true
    },
    'username': {
      type: Sequelize.STRING,
      size: 128
    },
    'fullName': {
      type: Sequelize.STRING,
      size: 256,
      required: true
    },
    'description': {
      type: Sequelize.STRING
    },
    'role': {
      type: Sequelize.STRING
    },
    'email': {
      type: Sequelize.STRING,
      size: 256,
      email: true
    }
  },
  associations: function () {
    User.belongsTo(Image, {as: 'iconImage', foreignKey: 'iconImageId'});
    User.belongsTo(Image, {as: 'coverImage', foreignKey: 'coverImageId'});
  },
  options: {
    freezeTableName: false,
    tableName: 'user',
    defaultScope: {
      include: [{ all: true }]
    }    
  }
};
```

Image model:
```
module.exports = {
  attributes: {
    imageId: {
      type: Sequelize.INTEGER,
      primaryKey: true
    },
    small: {
      type: Sequelize.STRING,
      size: 36
    },
    medium: {
      type: Sequelize.STRING,
      size: 36
    },
    large: {
      type: Sequelize.STRING,
      size: 36
    },
    'ownerUserId': {
      type: Sequelize.INTEGER,
      required: true
    }
  },
  options: {
    freezeTableName: false,
    tableName: 'image',
    getterMethods: {}
  }
};
```

When I fetch a record from the db with a following query everything is ok and I get the user instance with the images: (Of course, without the User `defaultScope` definition)
```
User.findOne({where: {'userId': params.userId, role: 'User'}, include: [{ all: true }]}).then(function (user) {
});
```

When I set the `defaultScope` and remove the `include` from the query, I get a following error:
```
Unhandled rejection TypeError: Object Image has no method 'getTableName'
    at module.exports.validateIncludedElement (/Users/festo/Projects/****/node_modules/sequelize/lib/model.js:2036:30)
    at module.exports.validateIncludedElements (/Users/festo/Projects/****/node_modules/sequelize/lib/model.js:1999:63)
    at null.<anonymous> (/Users/festo/Projects/****/node_modules/sequelize/lib/model.js:717:36)
    at null.<anonymous> (/Users/festo/Projects/****/node_modules/continuation-local-storage/context.js:74:17)
    at tryCatcher (/Users/festo/Projects/****/node_modules/sequelize/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/festo/Projects/****/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/Users/festo/Projects/****/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:530:18)
    at Async._drainQueue (/Users/festo/Projects/****/node_modules/sequelize/node_modules/bluebird/js/main/async.js:182:12)
    at Async._drainQueues (/Users/festo/Projects/****/node_modules/sequelize/node_modules/bluebird/js/main/async.js:187:10)
    at Async.drainQueues (/Users/festo/Projects/****/node_modules/sequelize/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickDomainCallback [as _tickCallback] (node.js:463:13)
```

**Comment by janmeier** [comment]
Hmm yeah, there seems to be a problem with include all for default scope - when i test it it errors at a different point than yours, but no, it doesn't work :)

**Comment by RSSGergelyMunkacsy** [comment]
I know it is a different bug, but I think this is connected to my previous one:
If you set multiple include in a default scope for the same model, in set just one of them.
For example in the User model:
```
defaultScope: {
    include: [
        {model: Image, as: 'iconImage'},
        {model: Image, as: 'coverImage'}
    ]
}
```
If the request don't contain the include part, the response only contain the `coverImage` (the second association).

If I set then include parameter in the findOne query, it is working:
```
User.findOne({
      where: {'userId': currentUser}, 
      include: [
        {model: Image, as: 'iconImage'},
        {model: Image, as: 'coverImage'}
      ]
    }).then(function (user) {
        ...
    })
```

I think the problem is in the `Model.$injectScope`:
https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1807

**Comment by mickhansen** [comment]
@RSSGergelyMunkacsy Yeah it's doing a bit of naive matching by the looks of it :)
