### ISSUE TITLE
Using a n:m junction table to join an additionnal table

### ISSUE THREAD

**Issue by sgaestel** [sequelize/sequelize#3711]
Hi,

I have an issue trying to perform a request including a model from a n:m junction table with sequelize 2.1.3.
Here is a simple schema of what I am trying to request
```
user --- userMovies --- movies
              |
              |
            storage
```

Here are my model definitions :

USER
```javascript
var user = sequelize.define('user', {
    uid: {
        type: Sequelize.STRING(32),
        primaryKey: true
    },
    email: {
        type: Sequelize.STRING(50),
        allowNull: false,
        unique: true
    },
    login: {
        type: Sequelize.STRING(50),
        allowNull: false,
        unique: true
    },
    password: {
        type: Sequelize.STRING(60),
        allowNull: false
    },
    is_admin: {
        type: Sequelize.BOOLEAN,
        defaultValue: false
    },
    public_collection: {
        type: Sequelize.BOOLEAN,
        allowNull: false,
        defaultValue: false
    }
}, {
    classMethods: {
        associate: function(models) {
            user.belongsToMany(models.movie, {
                through: models.userMovies
            });
        }
    }
});
```

MOVIE
```javascript
var movie = sequelize.define("movie", {
    uid: {
        type: Sequelize.STRING(32),
        primaryKey: true
    },
    tmdb_id: {
        type: Sequelize.STRING(8),
        allowNull: false,
        unique: true
    },
    title: {
        type: Sequelize.STRING,
        allowNull: false
    },
    poster: {
        type: Sequelize.STRING(35)
    }
}, {
    classMethods: {
        associate: function(models) {
            movie.belongsToMany(models.user, {
                through: models.userMovies
            });
            movie.hasMany(models.userMovies, {
                as: "flags"
            });
            movie.belongsToMany(models.genre, {
                through: "movieGenres"
            });
            movie.belongsToMany(models.actor, {
                through: "movieActors"
            });
        }
    }
});
```

USERMOVIES
```javascript
var userMovies = sequelize.define('userMovies', {
    seen: {
        type: Sequelize.BOOLEAN,
        defaultValue: false,
    },
    liked: {
        type: Sequelize.BOOLEAN,
        defaultValue: false
    },
    storageUid: {
        type: Sequelize.STRING(32),
        defaultValue: '32f48abce93b405a8003a44995389255'
    }
}, {
    classMethods: {
        associate: function(models) {
            userMovies.belongsTo(models.storage, {
                through: 'storageUid'
            });
        }
    }
});
```
STORAGE
```javascript
var storage = sequelize.define('storage', {
    uid: {
        type: Sequelize.STRING(32),
        primaryKey: true
    },
    name: {
        type: Sequelize.STRING(50),
        allowNull: false
    }
}, {
    classMethods: {
        associate: function(models) {
            storage.hasMany(models.userMovies, {
                through: 'uid'
            });
        }
    }
});
```

And this is the request I try to perform :
```javascript
user.find({
    include: [{
        model: db.movie,
        required: false,
        through: {
            as: "flags",
            include: [{
                model: db.storage
            }]
        }
    }],
    order: "title"
});
```

And this is the error I get :
```
/home/sgaestel/Documents/perso/github/gestion_films/node_modules/mysql/lib/protocol/Parser.js:82
        throw err;
              ^
TypeError: Cannot call method 'indexOf' of undefined
    at module.exports.Instance.set (/home/sgaestel/Documents/perso/github/gestion_films/node_modules/sequelize/lib/instance.js:337:79)
    at module.exports.Instance.set (/home/sgaestel/Documents/perso/github/gestion_films/node_modules/sequelize/lib/instance.js:315:18)
    at module.exports.initValues (/home/sgaestel/Documents/perso/github/gestion_films/node_modules/sequelize/lib/instance.js:1124:10)
    at module.exports.Instance (/home/sgaestel/Documents/perso/github/gestion_films/node_modules/sequelize/lib/instance.js:63:16)
    at new Instance.DAO (/home/sgaestel/Documents/perso/github/gestion_films/node_modules/sequelize/lib/model.js:204:16)
    at module.exports.Model.build (/home/sgaestel/Documents/perso/github/gestion_films/node_modules/sequelize/lib/model.js:1015:12)
    at module.exports.Instance._setInclude (/home/sgaestel/Documents/perso/github/gestion_films/node_modules/sequelize/lib/instance.js:472:85)
    at module.exports.Instance.set (/home/sgaestel/Documents/perso/github/gestion_films/node_modules/sequelize/lib/instance.js:339:16)
    at module.exports.Instance.set (/home/sgaestel/Documents/perso/github/gestion_films/node_modules/sequelize/lib/instance.js:315:18)
    at module.exports.initValues (/home/sgaestel/Documents/perso/github/gestion_films/node_modules/sequelize/lib/instance.js:1124:10)
    at module.exports.Instance (/home/sgaestel/Documents/perso/github/gestion_films/node_modules/sequelize/lib/instance.js:63:16)
    at new Instance.DAO (/home/sgaestel/Documents/perso/github/gestion_films/node_modules/sequelize/lib/model.js:204:16)
    at module.exports.Model.build (/home/sgaestel/Documents/perso/github/gestion_films/node_modules/sequelize/lib/model.js:1015:12)
    at null.<anonymous> (/home/sgaestel/Documents/perso/github/gestion_films/node_modules/sequelize/lib/model.js:1040:19)
    at Array.map (native)
    at module.exports.Model.bulkBuild (/home/sgaestel/Documents/perso/github/gestion_films/node_modules/sequelize/lib/model.js:1039:22)
    at module.exports.Instance._setInclude (/home/sgaestel/Documents/perso/github/gestion_films/node_modules/sequelize/lib/instance.js:475:83)
    at module.exports.Instance.set (/home/sgaestel/Documents/perso/github/gestion_films/node_modules/sequelize/lib/instance.js:339:16)
    at module.exports.Instance.set (/home/sgaestel/Documents/perso/github/gestion_films/node_modules/sequelize/lib/instance.js:310:20)
    at module.exports.initValues (/home/sgaestel/Documents/perso/github/gestion_films/node_modules/sequelize/lib/instance.js:1124:10)
    at module.exports.Instance (/home/sgaestel/Documents/perso/github/gestion_films/node_modules/sequelize/lib/instance.js:63:16)
    at new Instance.DAO (/home/sgaestel/Documents/perso/github/gestion_films/node_modules/sequelize/lib/model.js:204:16)
    at module.exports.Model.build (/home/sgaestel/Documents/perso/github/gestion_films/node_modules/sequelize/lib/model.js:1015:12)
    at null.<anonymous> (/home/sgaestel/Documents/perso/github/gestion_films/node_modules/sequelize/lib/model.js:1040:19)
    at Array.map (native)
    at module.exports.Model.bulkBuild (/home/sgaestel/Documents/perso/github/gestion_films/node_modules/sequelize/lib/model.js:1039:22)
    at module.exports.AbstractQuery.handleSelectQuery (/home/sgaestel/Documents/perso/github/gestion_films/node_modules/sequelize/lib/dialects/abstract/query.js:200:28)
    at module.exports.Query.formatResults (/home/sgaestel/Documents/perso/github/gestion_films/node_modules/sequelize/lib/dialects/mysql/query.js:73:21)
```

Could you tell me if I'm doing something wrong ?

Thanks in advance

**Comment by mickhansen** [comment]
We don't support adding associations to the through table of a N:M.
You'll have to manually include the join table (via hasMany/belongsTo on both sides) for this to work.

**Comment by sgaestel** [comment]
Thanks for the answer.
By talking about manually include, do you mean I have to transform the N:M relation between user and movie into separated 1:N user <-> userMovies and movie <-> userMovies relations ?
That would prevent me from using user.addMovie, which I currently use. Any plan to support associations on through table ?
Thanks

**Comment by mickhansen** [comment]
That's what i mean yes.
But you could do both, to still support user.addMovie but have the other for includes.

No plans currently, but it's a feature request that's come up more than once

**Comment by sgaestel** [comment]
Ok, thanks a lot for your help.
