### ISSUE TITLE
Sequelize 3.0 - getDataValue returns undefined when used in bulk update

### ISSUE THREAD

**Issue by szantner** [sequelize/sequelize#3746]
Hey,

Calling this:

```
    return Task.update(
        {
            resultCount: 0,
            handedOutCount: 0,
            result: null,
            minorityReport: null,
            votes: null,
            isSolved: false,
            reliability: null
        },
        {
            where: { resultCount: { $ne: 20 } }
        }
    );
```

Throws an error below because at model definition JSON.parse cannot parse undefined. The value returned by getDataValue should be null. This appeared after upgrading to 3.0.0

Model definition:

```
    solution:  {
        type: DataTypes.TEXT,
        get: function () {
            return JSON.parse(this.getDataValue('solution'));
        },
        set: function (value) {
            if (value) {
                this.setDataValue('solution', JSON.stringify(value));
            } else {
                this.setDataValue('solution', null);
            }
        }
    }
```

Error:

Unhandled rejection SyntaxError: Unexpected token u
    at Object.parse (native)
    at sequelize.define.solution.get (/Users/szantner/projects/mmapi/models/task.js:78:18)
    at module.exports.Instance.get (/Users/szantner/projects/mmapi/node_modules/sequelize/lib/instance.js:136:41)
    at module.exports.Instance.get (/Users/szantner/projects/mmapi/node_modules/sequelize/lib/instance.js:159:33)
    at /Users/szantner/projects/mmapi/node_modules/sequelize/lib/model.js:1644:62
    at tryCatcher (/Users/szantner/projects/mmapi/node_modules/sequelize/node_modules/bluebird/js/main/util.js:24:31)
    at Function.Promise.attempt.Promise.try (/Users/szantner/projects/mmapi/node_modules/sequelize/node_modules/bluebird/js/main/method.js:31:24)
    at module.exports.Model.update (/Users/szantner/projects/mmapi/node_modules/sequelize/lib/model.js:1637:23)
    at /Users/szantner/projects/mmapi/test/lib/tools.js:22:17
    at tryCatcher (/Users/szantner/projects/mmapi/node_modules/sequelize/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/szantner/projects/mmapi/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/Users/szantner/projects/mmapi/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (/Users/szantner/projects/mmapi/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/Users/szantner/projects/mmapi/node_modules/sequelize/node_modules/bluebird/js/main/async.js:177:16)
    at Async._drainQueues (/Users/szantner/projects/mmapi/node_modules/sequelize/node_modules/bluebird/js/main/async.js:187:10)
    at Immediate.Async.drainQueues [as _onImmediate](/Users/szantner/projects/mmapi/node_modules/sequelize/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback](timers.js:358:17)

**Comment by szantner** [comment]
A small note: it only happens to the field which is not among the fields to be updated.

**Comment by shakvaal** [comment]
I have the same problem:

    Organization.update({ambulatoryDetailedRating:"smth"}, {where: {humanId: 'state10'}})

throws `SyntaxError: Unexpected token u`, while

    Organization.update({ambulatoryDetailedRating:"smth"}, {where: {humanId: 'state10'}})

throws `SyntaxError: Unexpected end of input`

I don't get it!

**Comment by mickhansen** [comment]
Looks like a bug, custom getters should obviously not be capable of failing a bulk update.

**Comment by razvanilin** [comment]
I encountered the same problem.

I updated the fields with `setDataValue` and then used `save()` instead.

**Comment by manyeung** [comment]
same problem here.

I used `findAll` to get all instances first, then used `update` for each instance to solve this problem.
