### ISSUE TITLE
Returned instances from bulkCreate contain values with field keys rather than attribute keys

### ISSUE THREAD

**Issue by mickhansen** [sequelize/sequelize#3764]

**Comment by JSteunou** [comment]
I have some tests on my apps that are broken with the last v3 when using `bulkCreate` on model having `timestamp: true` and 

```js
        createdAt: {
            type: DataTypes.DATE,
            field: 'created_at'
        },
        updatedAt: {
            type: DataTypes.DATE,
            field: 'updated_at'
        },
        deletedAt: {
            type: DataTypes.DATE,
            field: 'deleted_at'
        }
```

logs are

```
Unhandled rejection SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'createdAt' in 'field list'
    at module.exports.Query.formatError (/home/jerome/my_project/node_modules/sequelize/lib/dialects/mysql/query.js:158:16)
    at Query._callback (/home/jerome/my_project/node_modules/sequelize/lib/dialects/mysql/query.js:36:23)
    at Query.Sequence.end (/home/jerome/my_project/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query.ErrorPacket (/home/jerome/my_project/node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
    at Protocol._parsePacket (/home/jerome/my_project/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/home/jerome/my_project/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/home/jerome/my_project/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/jerome/my_project/node_modules/mysql/lib/Connection.js:96:28)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

could this be related or should I open another issue?

**Comment by rfink** [comment]
I have this problem with all fields on bulkCreate

**Comment by yonjah** [comment]
:+1:

**Comment by JSteunou** [comment]
see #4646
