### ISSUE TITLE
PostgreSQL: sequelize sync hangs within transaction when ENUM field exists

### ISSUE THREAD

**Issue by tornillo** [sequelize/sequelize#3782]
TYPE queries are executed outside of the transaction.

```javascript
var User = sequelize.define('User', {
	type: Sequelize.ENUM('a', 'b')
});

sequelize.transaction()
.then(function (tx) {
	return sequelize.sync({
		force: true,
		transaction: tx
	})
})
.then(function () {
	tx.commit();
});
```

SQL log:
```SQL
Executing (814aa406-47f7-405e-be52-620304464fdc): START TRANSACTION;
Executing (814aa406-47f7-405e-be52-620304464fdc): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (814aa406-47f7-405e-be52-620304464fdc): SET autocommit = 1;
Executing (814aa406-47f7-405e-be52-620304464fdc): DROP TABLE IF EXISTS "Users" CASCADE;
Executing (default): DROP TYPE IF EXISTS "enum_Users_type";
<-- hangs here with "default"
```

**Comment by ns3777k** [comment]
https://github.com/sequelize/sequelize/blob/master/lib/query-interface.js#L221
only logging & raw params are passed to the query method to drop enum. transaction's missing.
i tried to to pass the transaction either and it went ok but then the error popped up while recreating the table:

```
Executing (b5a9a593-d462-4b4d-8a8c-2cc180325f3e): START TRANSACTION;
Executing (b5a9a593-d462-4b4d-8a8c-2cc180325f3e): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (b5a9a593-d462-4b4d-8a8c-2cc180325f3e): SET autocommit = 1;
Executing (b5a9a593-d462-4b4d-8a8c-2cc180325f3e): DROP TABLE IF EXISTS "test" CASCADE;
Executing (b5a9a593-d462-4b4d-8a8c-2cc180325f3e): DROP TYPE IF EXISTS "enum_test_type";
Executing (b5a9a593-d462-4b4d-8a8c-2cc180325f3e): DROP TABLE IF EXISTS "test" CASCADE;
Executing (b5a9a593-d462-4b4d-8a8c-2cc180325f3e): DROP TYPE IF EXISTS "enum_test_type";
Executing (default): SELECT t.typname enum_name, array_agg(e.enumlabel) enum_value FROM pg_type t JOIN pg_enum e ON t.oid = e.enumtypid JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public'  AND t.typname='enum_test_type'  GROUP BY 1
Executing (b5a9a593-d462-4b4d-8a8c-2cc180325f3e): CREATE TABLE IF NOT EXISTS "test" ("id"   SERIAL , "title" TEXT, "rank" INTEGER, "type" "enum_test_type", PRIMARY KEY ("id"));
Executing (b5a9a593-d462-4b4d-8a8c-2cc180325f3e): ROLLBACK;
Unhandled rejection SequelizeDatabaseError: type "enum_test_type" does not exist
    at Query.formatError (/Users/nikita/Desktop/nodejs-test/node_modules/sequelize/lib/dialects/postgres/query.js:420:14)
    at null.<anonymous> (/Users/nikita/Desktop/nodejs-test/node_modules/sequelize/lib/dialects/postgres/query.js:104:19)
    at emit (events.js:95:17)
    at Query.handleError (/Users/nikita/Desktop/nodejs-test/node_modules/pg/lib/query.js:99:8)
    at null.<anonymous> (/Users/nikita/Desktop/nodejs-test/node_modules/pg/lib/client.js:166:26)
    at emit (events.js:95:17)
    at Socket.<anonymous> (/Users/nikita/Desktop/nodejs-test/node_modules/pg/lib/connection.js:109:12)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)

Process finished with exit code 0
```

**Comment by ns3777k** [comment]
well. i got it working. summary - transaction param's missing in these lines:

https://github.com/sequelize/sequelize/blob/master/lib/query-interface.js#L221
https://github.com/sequelize/sequelize/blob/master/lib/query-interface.js#L122
https://github.com/sequelize/sequelize/blob/master/lib/query-interface.js#L138

**Comment by mickhansen** [comment]
Should be fixed by the PR from @ns3777k
