### ISSUE TITLE
Unmanaged transaction, CLS enabled, No context available.

### ISSUE THREAD

**Issue by kirill-zhirnov** [sequelize/sequelize#3888]
Hi :)

```coffeescript
	trx = null
	db.transaction({autocommit : false})
	.then (t) ->
		trx = t

		return db.model('person').find()
	.then (row) ->
		console.log row.toJSON()

		trx.rollback()
	.done()
```

Error:
```
Error: No context available. ns.run() or ns.bind() must be called first.
  at Namespace.set (/Users/kirillzirnov/Projects/babylon/repo/htdocs/node_modules/continuation-local-storage/context.js:27:11)
  at /Users/kirillzirnov/Projects/babylon/repo/htdocs/node_modules/sequelize/lib/transaction.js:156:38
  ...
```

What do I do wrong?

It is simple example. Main reason, why I want to use it - mocha tests: beforeEach/afterEach

```coffeescript
	beforeEach (done) ->
		db.transaction({autocommit : false})
		.then (t) ->
			trx = t
			sequelizeFixtures.loadFile fixturePath, models
		.then (rows) ->
			fixtures = rows
			done()
		.done()

	afterEach (done) ->
		trx.rollback()
		.then () ->
			done()
		.done()
```
May be there are another way to do it? :)

Thank you!

**Comment by janmeier** [comment]
Cls only works with managed transactions because we need access to the callback in order to bind it

**Comment by kirill-zhirnov** [comment]
Sorry, but how can I use with unit tests?

**Comment by janmeier** [comment]
What do you mean? If you need to rollback a managed transaction, you can just return a rejected promise

**Comment by kirill-zhirnov** [comment]
Firstly I want to load fixtures to db inside transaction. I am using 'sequelize-fixtures' to do it. Unfortunately, all queries run outside the transaction:

```coffeescript
	beforeEach (done) ->
		db.constructor.cls.run ->
			db.transaction (t) ->
				trx = t
				return sequelizeFixtures.loadFile fixturePath, models
			.then (rows) ->
				fixtures = rows
				done()
			.done()
```

What do I do wrong?

Thank you for your help!

**Comment by janmeier** [comment]
That's not a sequelize question, you'll have to ask in sequelize fixtures about that
