### ISSUE TITLE
Node Webkit + SQLite3

### ISSUE THREAD

**Issue by fjcero** [sequelize/sequelize#3889]
I have commented also here https://github.com/sequelize/sequelize/issues/2642, but to have a better context I will explain and show my examples here. The packages versions I'm using are:

```
├── node-webkit-builder@1.0.12
├── sequelize@3.1.1
├── sequelize-cli@1.7.0
└── sqlite3@3.0.8
```

I compiler `node-sqlite3` as specified here https://github.com/mapbox/node-sqlite3#building-for-node-webkit. So far, everything goes well inside Node Webkit. Here are the commands that works:

The next code works as expected:

```js
models.sequelize.sync().then(function () {
  var server = app.listen(app.get('port'), function() {

    console.log("App listening: " + server.address().port);
  });
});

// In some part of the code
// If I do a console.log I see the object created in memory
var client = models.client.build(req.body);
```

And next the code which fails:

```js
models.client.save().then(function(client){
    // this fails successfully
});

models.client.findAll().then(function(clients){
    // also this fails successfully
})
```

I both cases the throwed error is:

```js
/Users/fjcero/project/node_modules/sequelize/node_modules/bluebird/js/main/captured_trace.js:478 Unhandled rejection Error: TypeError: Illegal invocation
  at Object.ensureErrorObject (/Users/fjcero/project/node_modules/sequelize/node_modules/bluebird/js/main/util.js:228:20)
  at Promise._rejectCallback (/Users/fjcero/project/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:416:22)
  at Promise._settlePromiseFromHandler (/Users/fjcero/project/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:460:17)
  at Promise._settlePromiseAt (/Users/fjcero/project/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:530:18)
  at Promise._settlePromises (/Users/fjcero/project/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:646:14)
  at Async._drainQueue (/Users/fjcero/project/node_modules/sequelize/node_modules/bluebird/js/main/async.js:177:16)
  at Async._drainQueues (/Users/fjcero/project/node_modules/sequelize/node_modules/bluebird/js/main/async.js:187:10)
  at Immediate.Async.drainQueues [as _onImmediate] (/Users/fjcero/project/node_modules/sequelize/node_modules/bluebird/js/main/async.js:15:14)
  at processImmediate [as _immediateCallback] (timers.js:321:17)
```

I will be pleased to debug Sequelize inside Node Webkit if its necessary, but I need to understand how to do it first!

**Comment by janmeier** [comment]
Seems to be an error that's happening in bluebird (our promise library). Csn

**Comment by fjcero** [comment]
@janmeier how I could do that? Could you lead me a little bit in the process?

**Comment by janmeier** [comment]
Does 

```js
var promise = require('bluebird');

promise.resolve().then(function () {

});
```

Does this throw an error as well?

**Comment by fjcero** [comment]
I executed the next inside the Node Webkit console:

```js
Sequelize.Promise.resolve().then(function(a){});
Promise {_bitField: 0, _fulfillmentHandler0: undefined, _rejectionHandler0: undefined, _progressHandler0: undefined, _promise0: undefined…}_bitField: 268435456_fulfillmentHandler0: undefined_progressHandler0: undefined_promise0: undefined_receiver0: undefined_rejectionHandler0: undefined_settledValue: undefined__proto__: Promise
```

I used the Promise object defined in Sequelize, since `require()` was throwing `MODULE NOT FOUND`

**Comment by janmeier** [comment]
Hmm ... In my bluebird version if tries to call console.warn at that line - is it the same for you?

But anyway, this is definitely an error deep in the bluebird internals so you'll probably have to take the issue up with them

**Comment by fjcero** [comment]
@janmeier perfectly clear. I will check with them, if it's necessary I will continue from here! Thanks!
