### ISSUE TITLE
_.cloneDeep with sequelize object

### ISSUE THREAD

**Issue by PavelPolyakov** [sequelize/sequelize#3913]
Hi,

I'm trying to ```_.cloneDeep``` the sequelize object and receive the next:
```
Unhandled rejection Error: Cannot find module 'pg-native'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/pavelp/Sites/xxx/node_modules/pg/lib/native/index.js:1:76)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at null.<anonymous> (/Users/pavelp/Sites/xxx/node_modules/pg/lib/index.js:78:36)
    at forOwn (/Users/pavelp/Sites/xxx/node_modules/lodash/dist/lodash.js:2105:32)
    at baseClone (/Users/pavelp/Sites/xxx/node_modules/lodash/dist/lodash.js:816:33)
    at /Users/pavelp/Sites/xxx/node_modules/lodash/dist/lodash.js:817:23
    at forOwn (/Users/pavelp/Sites/xxx/node_modules/lodash/dist/lodash.js:2105:15)
```

Thought it has something in common with https://github.com/sequelize/sequelize/issues/3781 , but I've updated the sequelize to 3.2.0 and the issue is still there.

Any hint if it is something I can fix?

Regards,

**Comment by janmeier** [comment]
That's because #3781 uses a custom comparator for cloneDeep, which avoids cloning the offending props. See the referenced commit.

You'll have to use something similar to https://github.com/sequelize/sequelize/commit/4f9b502e410614edfe863a7a7c3006ae4a495d1a

**Comment by PavelPolyakov** [comment]
@janmeier 
Could you, please, clarify where should I put that to?

I'm trying to do a _.cloneDeep of the object which has Sequelize model object as one of the property.

**Comment by mickhansen** [comment]
@PavelPolyakov You need to apply a callback that copies special sequelize objects as is, or use Model.prototype.__optClone, which is not public at all (so could change at any time)

**Comment by PavelPolyakov** [comment]
@mickhansen 

Thanks,

**Comment by PavelPolyakov** [comment]
For those who might me interested.

for me it was enough to do the next:

```javascript
        // clone, so we don't tounch the original values
        data = _.cloneDeep(data, function (value) {
            // specially for the sequelize instances
            if (value && value.toJSON) {
                return value.toJSON();
            }
        });
```
