### ISSUE TITLE
Error: can't clone

### ISSUE THREAD

**Issue by GeoffreyPlitt** [sequelize/sequelize#3925]
In the latest version, lib/utils.js has this code around line 100:
```javascript
if (&& !!Utils._.get(elem, 'clone') && typeof elem.clone === 'function') {return elem.clone(); }
```

It was failing because Utils._.get was null. I tried to fix it with:
```javascript
if (Utils._ && Utils._.get && !!Utils._.get(elem, 'clone') && typeof elem.clone === 'function') {return elem.clone(); }
```

Now I get this error:
```
Error: Can't clone [object SequelizeModel:Expos]
    at Function.Object.clone (/vagrant/node_modules/q-io/node_modules/collections/shim-object.js:509:27)
    at Function.Object.clone (/vagrant/node_modules/q-io/node_modules/collections/shim-object.js:506:45)
    at Array.<anonymous> (/vagrant/node_modules/q-io/node_modules/collections/shim-array.js:249:31)
    at /vagrant/node_modules/sequelize/lib/utils.js:99:116
    at baseClone (/vagrant/node_modules/sequelize/node_modules/lodash/index.js:1693:27)
    at /vagrant/node_modules/sequelize/node_modules/lodash/index.js:1738:23
    at /vagrant/node_modules/sequelize/node_modules/lodash/index.js:3106:15
    at baseForOwn (/vagrant/node_modules/sequelize/node_modules/lodash/index.js:2053:14)
    at baseClone (/vagrant/node_modules/sequelize/node_modules/lodash/index.js:1737:39)
    at Function.cloneDeep (/vagrant/node_modules/sequelize/node_modules/lodash/index.js:8345:11)
    at Object.module.exports.cloneDeep (/vagrant/node_modules/sequelize/lib/utils.js:97:19)
    at Model.__optClone (/vagrant/node_modules/sequelize/lib/model.js:306:16)
    at Model.findAll (/vagrant/node_modules/sequelize/lib/model.js:1157:13)
```

This is some crazy logic for just doing some cloning.

**Comment by janmeier** [comment]
Let's address this in your PR instead - I agree there seems to be a lot of logic just for checking if the object has a clone function :P
