### ISSUE TITLE
Error when adding pagination/limiting to nested queries

### ISSUE THREAD

**Issue by pfirpfel** [sequelize/sequelize#3962]
**Working (without paging)**

``` javascript
var queryParams = {
  include: [
    { model: models.AnswerOption },
    { model: models.Tag, where: { name: ['moep', 'blubb'] } }
  ]
};

models.Question.findAndCountAll(queryParams).then(function(result) {
//...
});
```

``` sql
SELECT `Question`.`uuid`,
       `Question`.`type`,
       `Question`.`title`,
       `Question`.`difficulty`,
       `Question`.`questionText`,
       `Question`.`solutionText`,
       `Question`.`solutionNumber`,
       `Question`.`infoText`,
       `Question`.`rateQuestion`,
       `Question`.`createdAt`,
       `Question`.`updatedAt`,
       `Question`.`TagId`,
       `AnswerOptions`.`id` AS `AnswerOptions.id`,
       `AnswerOptions`.`answerText` AS `AnswerOptions.answerText`,
       `AnswerOptions`.`isCorrect` AS `AnswerOptions.isCorrect`,
       `AnswerOptions`.`createdAt` AS `AnswerOptions.createdAt`,
       `AnswerOptions`.`updatedAt` AS `AnswerOptions.updatedAt`,
       `AnswerOptions`.`QuestionUuid` AS `AnswerOptions.QuestionUuid`,
       `Tags`.`id` AS `Tags.id`,
       `Tags`.`name` AS `Tags.name`,
       `Tags`.`createdAt` AS `Tags.createdAt`,
       `Tags`.`updatedAt` AS `Tags.updatedAt`,
       `Tags.QuestionTags`.`createdAt` AS `Tags.QuestionTags.createdAt`,
       `Tags.QuestionTags`.`updatedAt` AS `Tags.QuestionTags.updatedAt`,
       `Tags.QuestionTags`.`QuestionUuid` AS `Tags.QuestionTags.QuestionUuid`,
       `Tags.QuestionTags`.`TagId` AS `Tags.QuestionTags.TagId`
FROM `Questions` AS `Question`
LEFT OUTER JOIN `AnswerOptions` AS `AnswerOptions` ON `Question`.`uuid` = `AnswerOptions`.`QuestionUuid`
INNER JOIN (`QuestionTags` AS `Tags.QuestionTags`
            INNER JOIN `Tags` AS `Tags` ON `Tags`.`id` = `Tags.QuestionTags`.`TagId`) ON `Question`.`uuid` = `Tags.QuestionTags`.`QuestionUuid`
AND `Tags`.`name` IN ('moep',
                      'blubb');
```

**Broken**
If we only add _offset_, no error occurs. But if we add _limit_ sequelize crashes.

``` js
var queryParams = {
  include: [
    { model: models.AnswerOption },
    { model: models.Tag, where: { name: ['moep', 'blubb'] } }
  ],
  offset: 0,
  limit: 10
};

models.Question.findAndCountAll(queryParams).then(function(result) {
//...
});
```

``` sql
SELECT `Question`.*,
       `AnswerOptions`.`id` AS `AnswerOptions.id`,
       `AnswerOptions`.`answerText` AS `AnswerOptions.answerText`,
       `AnswerOptions`.`isCorrect` AS `AnswerOptions.isCorrect`,
       `AnswerOptions`.`createdAt` AS `AnswerOptions.createdAt`,
       `AnswerOptions`.`updatedAt` AS `AnswerOptions.updatedAt`,
       `AnswerOptions`.`QuestionUuid` AS `AnswerOptions.QuestionUuid`,
       `Tags`.`id` AS `Tags.id`,
       `Tags`.`name` AS `Tags.name`,
       `Tags`.`createdAt` AS `Tags.createdAt`,
       `Tags`.`updatedAt` AS `Tags.updatedAt`,
       `Tags.QuestionTags`.`createdAt` AS `Tags.QuestionTags.createdAt`,
       `Tags.QuestionTags`.`updatedAt` AS `Tags.QuestionTags.updatedAt`,
       `Tags.QuestionTags`.`QuestionUuid` AS `Tags.QuestionTags.QuestionUuid`,
       `Tags.QuestionTags`.`TagId` AS `Tags.QuestionTags.TagId`
FROM
  (SELECT `Question`.`uuid`,
          `Question`.`type`,
          `Question`.`title`,
          `Question`.`difficulty`,
          `Question`.`questionText`,
          `Question`.`solutionText`,
          `Question`.`solutionNumber`,
          `Question`.`infoText`,
          `Question`.`rateQuestion`,
          `Question`.`createdAt`,
          `Question`.`updatedAt`,
          `Question`.`TagId`
   FROM `Questions` AS `Question`
   WHERE
       (SELECT `QuestionTags`.`QuestionUuid`
        FROM `QuestionTags` AS `QuestionTags`
        INNER JOIN `Tags` AS `Tag` ON `QuestionTags`.`TagId` = `Tag`.`uuid`
        WHERE (`Question`.`uuid` = `QuestionTags`.`QuestionUuid`) LIMIT 1) IS NOT NULL LIMIT 1,
                                                                                             15) AS `Question`
LEFT OUTER JOIN `AnswerOptions` AS `AnswerOptions` ON `Question`.`uuid` = `AnswerOptions`.`QuestionUuid`
INNER JOIN (`QuestionTags` AS `Tags.QuestionTags`
            INNER JOIN `Tags` AS `Tags` ON `Tags`.`id` = `Tags.QuestionTags`.`TagId`) ON `Question`.`uuid` = `Tags.QuestionTags`.`QuestionUuid`
AND `Tags`.`name` IN ('moep',
                      'blubb');
```

**Error**

```
Unhandled rejection SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'Tag.uuid' in 'on clause'
    at module.exports.Query.formatError (d:\dev\sisr\node-server\node_modules\sequelize\lib\dialects\mysql\query.js:158:16)
    at Query._callback (d:\dev\sisr\node-server\node_modules\sequelize\lib\dialects\mysql\query.js:36:23)
    at Query.Sequence.end (d:\dev\sisr\node-server\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query.ErrorPacket (d:\dev\sisr\node-server\node_modules\mysql\lib\protocol\sequences\Query.js:94:8)
    at Protocol._parsePacket (d:\dev\sisr\node-server\node_modules\mysql\lib\protocol\Protocol.js:271:23)
    at Parser.write (d:\dev\sisr\node-server\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (d:\dev\sisr\node-server\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (d:\dev\sisr\node-server\node_modules\mysql\lib\Connection.js:92:28)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:528:21)
```

Is there a workaround for this?

**Comment by janmeier** [comment]
Can you post model definitions and associations as well?

**Comment by pfirpfel** [comment]
Of course!

**Question**
```javascript
module.exports = function(sequelize, DataTypes) {
  questionSchema = {
    uuid: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true
    },
    type: {
      type: DataTypes.ENUM(questionTypes), // questionTypes is an array of strings
      allowNull: false
    },
    title: {
      type: DataTypes.STRING,
      allowNull: false
    },
    difficulty: {
      type: DataTypes.INTEGER,
      defaultValue: 0,
      validate: {
        min: 0,
        max: 3
      }
    },
    questionText: {
      type: DataTypes.TEXT
    },
    solutionText: {
      type: DataTypes.TEXT
    },
    solutionNumber: {
      type: DataTypes.FLOAT
    },
    infoText: {
      type: DataTypes.TEXT
    }, 
    rateQuestion: {
      type: DataTypes.BOOLEAN,
      defaultValue: false
    }
  };
  var Question = sequelize.define("Question", questionSchema, {
    classMethods: {
      associate: function(models){
        Question.belongsToMany(models.Level, { through: models.QuestionInstance });
        Question.belongsToMany(models.Tag, { through: 'QuestionTags' });
        Question.hasMany(models.AnswerOption, { onDelete: 'CASCADE' });
      }
    }
  });

  return Question;
};
```

**Tag**
```javascript
module.exports = function(sequelize, DataTypes) {
  var Tag = sequelize.define("Tag", {
    name: {
      type: DataTypes.STRING,
      allowNull: false,
      unique: true
    }
  },
  {
    classMethods: {
      associate: function(models){
        Tag.hasMany(models.Question);
      }
    },
    instanceMethods: {}
  });

  return Tag;
};
```


**AnswerOption**
```javascript
module.exports = function(sequelize, DataTypes) {
  var AnswerOption = sequelize.define("AnswerOption", {
    answerText: {
      type: DataTypes.TEXT,
      allowNull: false
    },
    isCorrect: {
      type: DataTypes.BOOLEAN,
      allowNull: false,
      defaultValue: false
    }
  },
  {
    classMethods: {
      associate: function(models){
        AnswerOption.belongsToMany(models.Answer,  { through: models.SelectedAnswerOption, onDelete: 'CASCADE' });
      }
    },
    instanceMethods: {}
  });

  return AnswerOption;
};
```
(SelectedAnswerOption is basically an empty model)

**Comment by pfirpfel** [comment]
Could be my fault. May be I'm using Sequelize the wrong way.

I wrote [this test](https://github.com/pfirpfel/sequelize/blob/test-findAndCountAll-many-to-many-pagination/test/integration/include/findAndCountAll.test.js#L184-L219), which does more or less the same thing and runs smoothly.

**Comment by mickhansen** [comment]
So the error appears to be in

```sql
INNER JOIN `Tags` AS `Tag` ON `QuestionTags`.`TagId` = `Tag`.`uuid`
```

Since tag does not appear to have a uuid column it's erroring, not sure why it's making that assumption, does the query run if you run it manually at change `uuid` to `id`?
