### ISSUE TITLE
Passing in data length in migration `changeColumn` method throws error

### ISSUE THREAD

**Issue by andrewhassan** [sequelize/sequelize#3999]
In a migration script, when I tried to do something like:
```javascript
    queryInterface.changeColumn(
      'my_table',
      'my_column',
      Sequelize.STRING(4096)
    );
```

I get the following error:
```
Unhandled rejection TypeError: Cannot read property 'key' of undefined
    at Sequelize.normalizeDataType (/Users/andrew/git/project_folder/node_modules/sequelize/lib/sequelize.js:1205:24)
    at QueryInterface.changeColumn (/Users/andrew/git/project_folder/node_modules/sequelize/lib/query-interface.js:379:51)
    at Object.module.exports.up (/Users/andrew/git/project_folder/migrations/20150624172349-nodered-change-entity-column.js:5:20)
    at module.exports.redefine.Class._exec (/Users/andrew/git/project_folder/node_modules/sequelize-cli/node_modules/umzug/lib/migration.js:49:23)
    at module.exports.redefine.Class.up (/Users/andrew/git/project_folder/node_modules/sequelize-cli/node_modules/umzug/lib/migration.js:33:17)
    at null.<anonymous> (/Users/andrew/git/project_folder/node_modules/sequelize-cli/node_modules/umzug/index.js:78:28)
    at Object.tapHandler (/Users/andrew/git/project_folder/node_modules/sequelize-cli/node_modules/bluebird/js/main/finally.js:64:43)
    at Object.tryCatcher (/Users/andrew/git/project_folder/node_modules/sequelize-cli/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/andrew/git/project_folder/node_modules/sequelize-cli/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/Users/andrew/git/project_folder/node_modules/sequelize-cli/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (/Users/andrew/git/project_folder/node_modules/sequelize-cli/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/Users/andrew/git/project_folder/node_modules/sequelize-cli/node_modules/bluebird/js/main/async.js:177:16)
    at Async._drainQueues (/Users/andrew/git/project_folder/node_modules/sequelize-cli/node_modules/bluebird/js/main/async.js:187:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/andrew/git/project_folder/node_modules/sequelize-cli/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:371:17)
```

When I investigated, it seems that the result of `Sequelize.STRING(4096)` doesn't have a `type` property, which is why the `normalizeDataType` method throws an error. Using `Sequelize.STRING` without the length, however, works just fine.

**Comment by mickhansen** [comment]
Does:

```js
queryInterface.changeColumn(
  'my_table',
  'my_column',
  {type: Sequelize.STRING(4096)}
);
```

work?

**Comment by andrewhassan** [comment]
Yes, that seems to work! Thanks!

**Comment by mickhansen** [comment]
So as i suspected the 3rd argument to `changeColumn` should be an object like you use in `define` :)

**Comment by andrewhassan** [comment]
That makes sense. It might be worth mentioning that on [this page](http://sequelize.readthedocs.org/en/latest/docs/migrations/#changecolumntablename-attributename-datatypeoroptions-options). When I read that page, I assumed that the data type could be set as described on [this page](http://sequelize.readthedocs.org/en/latest/docs/models-definition/#data-types).
