### ISSUE TITLE
UUIDV4 causes incorrect SQL to be generated for MySQL

### ISSUE THREAD

**Issue by slang800** [sequelize/sequelize#4004]
I have this code:
```coffee
Sequelize = require 'sequelize'

newDb = new Sequelize('xxxx', 'xxxx', 'xxxx',
  host: 'localhost'
  dialect: 'mysql'
)

postModelFields = {
  id:
    primaryKey: true
    field: 'id'
    type: Sequelize.UUIDV4
}

PostModel = newDb.define('post', postModelFields,
  freezeTableName: true
  timestamps: false
)

PostModel.sync(
  force: true
)
```

And running it causes this error:

```
Executing (default): DROP TABLE IF EXISTS `post`;
Executing (default): CREATE TABLE IF NOT EXISTS `post` (`id` UUIDV4 , PRIMARY KEY (`id`)) ENGINE=InnoDB;
Unhandled rejection SequelizeDatabaseError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'UUIDV4 , PRIMARY KEY (`id`)) ENGINE=InnoDB' at line 1
  at [object Object].Query.formatError (/usrdata/web/speakeasy-migration/node_modules/sequelize/lib/dialects/mysql/query.js:159:14)
  at Query._callback (/usrdata/web/speakeasy-migration/node_modules/sequelize/lib/dialects/mysql/query.js:35:21)
  at Query.Sequence.end (/usrdata/web/speakeasy-migration/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
  at Query.ErrorPacket (/usrdata/web/speakeasy-migration/node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
  at Protocol._parsePacket (/usrdata/web/speakeasy-migration/node_modules/mysql/lib/protocol/Protocol.js:271:23)
  at Parser.write (/usrdata/web/speakeasy-migration/node_modules/mysql/lib/protocol/Parser.js:77:12)
  at Protocol.write (/usrdata/web/speakeasy-migration/node_modules/mysql/lib/protocol/Protocol.js:39:16)
  at Socket.<anonymous> (/usrdata/web/speakeasy-migration/node_modules/mysql/lib/Connection.js:96:28)
  at Socket.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:163:16)
  at Socket.Readable.push (_stream_readable.js:126:10)
  at TCP.onread (net.js:538:20)
```

I'm pretty sure UUIDs should be stored as `char(36)` in MySQL

**Comment by janmeier** [comment]
You should set `UUID` as the type, and `UUIDv4/1` as `defaultValue` (unless you want to generate them yourself)

**Comment by slang800** [comment]
Ah, thanks!

On Wed, Jun 24, 2015 at 2:54 PM, Jan Aagaard Meier <notifications@github.com

**Comment by saurabhschauhan** [comment]
thanks @janmeier

**Comment by milpatel11** [comment]
@janmeier  Thanks you're right,

Just for further clarification or in other words 

`//imports should be like this 
const { DataTypes, Model, sequelize, Sequelize, UUIDV4 } = require("sequelize");
//defination should be  this
id: {
                    type: Sequelize.UUID,
                    primaryKey: true,
                    defaultValue: UUIDV4,
                },
`
