### ISSUE TITLE
Getting TypeError with passportjs/sequelize

### ISSUE THREAD

**Issue by rahul1346** [sequelize/sequelize#4025]
I am trying to authenticate using passportjs/sequelize but keep getting a typeError here :

'''TypeError: undefined is not a function
   at module.exports.getUser (/Users/ra/Desktop/jb/controllers/users.js:44:12)
   at Layer.handle [as handle_request] (/Users/ra/Desktop/jb/node_modules/express/lib/router/layer.js:95:5)
   at next (/Users/ra/Desktop/jb/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/Users/ra/Desktop/jb/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/Users/ra/Desktop/jb/node_modules/express/lib/router/layer.js:95:5)
   at /Users/ra/Desktop/jb/node_modules/express/lib/router/index.js:277:22
   at param (/Users/ra/Desktop/jb/node_modules/express/lib/router/index.js:349:14)
   at param (/Users/ra/Desktop/jb/node_modules/express/lib/router/index.js:365:14)
   at Function.process_params (/Users/ra/Desktop/jb/node_modules/express/lib/router/index.js:410:3)
   at next (/Users/ra/Desktop/jb/node_modules/express/lib/router/index.js:271:10)
   at Function.handle (/Users/ra/Desktop/jb/node_modules/express/lib/router/index.js:176:3)
   at router (/Users/ra/Desktop/jb/node_modules/express/lib/router/index.js:46:12)
   at Layer.handle [as handle_request] (/Users/raDesktop/jb/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/Users/ra/Desktop/jb/node_modules/express/lib/router/index.js:312:13)
   at /Users/ra/Desktop/jb/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/Users/ra/Desktop/jb/node_modules/express/lib/router'''

Here is what the controller fxn looks like:
'''
getUser: function(req, res) {
    User.find({
          where: {
            username: req.params.id,
            displayName: req.user.displayName
          }
        }).success(function(User) {
          res.send(User);
        });
  },
'''

And the get request from passportjs
```
app.get('/auth/facebook/callback',
    passport.authenticate('facebook', {
      failureRedirect: '/login'
    }),
    function(req, res) {
      console.log(req.user.username)
      res.cookie('signIn', 'true');
      res.redirect('/api/users/' + req.user.username);
    }
  );
```

Any idea whats going on? I am trying to just get username and displayName from the user that was authenticated and created.

**Comment by janmeier** [comment]
What is at `users.js:44:12`?  You are trying to call something that is undefined at that line, char

**Comment by rahul1346** [comment]
Its getUser function I posted above. Here is user.js and the corresponding repo:

https://github.com/rahul1346/jb/blob/master/controllers/users.js#L44

**Comment by janmeier** [comment]
`success` has been removed in 2.1 - use `then` instead https://github.com/sequelize/sequelize/blob/master/changelog.md#210

**Comment by rahul1346** [comment]
Thanks jan
