### ISSUE TITLE
Unhandled rejection SequelizeConnectionError: read ECONNRESET

### ISSUE THREAD

**Issue by xi3** [sequelize/sequelize#4058]
When test the default express js example, I got this error, what's the problem, please help.

Sequelize [Node: 0.10.21, CLI: 1.7.0, ORM: 3.3.2, mysql: ~2.7.0]

```
{ username: 'user',
  password: 'pass',
  database: 'huadian_dev',
  host: 'mysql56.xx.com',
  dialect: 'mysql',
  port: 3306 }
```

```
Executing (default): CREATE TABLE IF NOT EXISTS `Users` (`id` INTEGER NOT NULL auto_increment , `username` VARCHAR(255),
 `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `Users` FROM `huadian_dev`
Executing (default): CREATE TABLE IF NOT EXISTS `Tasks` (`id` INTEGER NOT NULL auto_increment , `title` VARCHAR(255), `c
reatedAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `UserId` INTEGER, PRIMARY KEY (`id`), FOREIGN KEY (`UserId`)
 REFERENCES `Users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `Tasks` FROM `huadian_dev`
Unhandled rejection SequelizeConnectionError: read ECONNRESET
    at Quit._callback (C:\git\huadian\node_modules\sequelize\lib\dialects\mysql\connection-manager.js:104:30)
    at Quit.Sequence.end (C:\git\huadian\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Protocol.handleNetworkError (C:\git\huadian\node_modules\mysql\lib\protocol\Protocol.js:355:14)
    at Connection._handleNetworkError (C:\git\huadian\node_modules\mysql\lib\Connection.js:371:18)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)

```

**Comment by mickhansen** [comment]
Your mysql server is abruptly terminating the connection.
Not exactly a sequelize issue, you'll have to debug your connection manually first.

**Comment by xi3** [comment]
Thanks.

add pool setting and change mysql server stting "wait_timeout" fixed this problem

```
"development": {
		"username": "huadian_dev",
		"password": "lovexiaofushen",
		"database": "huadian_dev",
		"host": "mysql56.rdsmnkteuqiz3c5.rds.bj.baidubce.com",
		"dialect": "mysql",
		"port": 3306,
		"pool":{
			"maxConnections":30,
			"minConnections":10,
			"maxIdleTime":800000
		}
	}

```

**Comment by MRLuowen** [comment]
hello，i met the same question , i also add pool and ,mysql server setting is "wait_timeout"= 28800.so，the same problem is also exist.
