### ISSUE TITLE
Upsert not working properly with MySql

### ISSUE THREAD

**Issue by ciberyo16** [sequelize/sequelize#4059]
Hi, I think since the last version upsert method is not working properly.

I have the object 
    var Device = sequelize.define('Device', {
        type: {type: DataTypes.ENUM('ios', 'android')},
        uuid: {type: DataTypes.STRING(255), allowNull: false, unique: true},
        token: {type: DataTypes.STRING(255), allowNull: true, unique: true}
    }... 
with "uuid" and "token" as unique keys
And then I have 2 entries, the first one with the token "x" and the other one with the uuid "y".

Then when I try to execute:
Device.upsert({type: 1, token:"x", uuid: "y"})
            .then(function (result) {
                   return result;
               })
            .catch(function (err) {
                    console.log(err);
                    return err;
               );
I get a MySQL error "error: uncaughtException: Cannot read property 'uniqueKeys' of undefined"
when sequelize try to execute "ON DUPLICATE KEY UPDATE".

Thank you very much and sorry for my english.

**Comment by janmeier** [comment]
I believe I fixed something like this recently. Can you try latest master?

**Comment by ciberyo16** [comment]
Thank you for your answer, I will try it on Monday morning.

**Comment by janmeier** [comment]
Ping @ciberyo16

**Comment by janmeier** [comment]
Closing, no response

**Comment by warapitiya** [comment]
I'm getting the same behavior.

```js
Unhandled rejection TypeError: Cannot read property 'upsert' of undefined
    at Model.<anonymous> (/home/cooper/Development/express-example/routes/index.js:20:20)
    at Model.tryCatcher (/home/cooper/Development/express-example/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/cooper/Development/express-example/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/cooper/Development/express-example/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/cooper/Development/express-example/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/cooper/Development/express-example/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/cooper/Development/express-example/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/cooper/Development/express-example/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/cooper/Development/express-example/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

Using **_sequelize - 3.29.0_**

**## CODE:**

```js
models.User.upsert({
	username: 'jamesbond'
  }, {
  	include: [ models.Task ]
  }).then(function(user) {
  	return user.Task.upsert({
  		title: 'Awesoomi!'
  	});
  }).then(function(task){
  	console.log(task.get({plain: true}));
  });
```

**Comment by warapitiya** [comment]
Ok my bad. Looks like **_upsert_** is returning a boolean.
