### ISSUE TITLE
many2many with getters through attributes

### ISSUE THREAD

**Issue by ns3777k** [sequelize/sequelize#4120]
Code:
```js
'use strict';

var SEQUELIZE = require('sequelize'),
	db = new SEQUELIZE('postgres', 'postgres', '123456', {
		dialect : 'postgres',
		host    : 'localhost'
	});

var ConnectionPlan = db.define('ConnectionPlan', {
	title : SEQUELIZE.TEXT,
	price : SEQUELIZE.INTEGER
}, {
	tableName : 'connection_plan',
	createdAt : false,
	updatedAt : false,
	deletedAt : false
});

var ConnectionOption = db.define('ConnectionOption', {
	title     : SEQUELIZE.TEXT,
	price     : {
		type  : SEQUELIZE.INTEGER,
		field : 'price',
		get   : function () {
			return this.getDataValue('price');
		},
		set   : function (val) {
			this.setDataValue('price', val);
		}
	}
}, {
	tableName : 'connection_option',
	createdAt : false,
	updatedAt : false,
	deletedAt : false
});

var PlanOption = db.define('PlanOption', {
	planid    : SEQUELIZE.INTEGER,
	optionid  : SEQUELIZE.INTEGER,
	recommend : SEQUELIZE.BOOLEAN,
	weight    : SEQUELIZE.INTEGER
}, {
	tableName : 'plan2option',
	createdAt : false,
	updatedAt : false,
	deletedAt : false
});

ConnectionPlan.belongsToMany(ConnectionOption, {
	through    : { model : PlanOption },
	foreignKey : 'planid',
	as         : 'compatible_options'
});

ConnectionOption.belongsToMany(ConnectionPlan, {
	through    : { model : PlanOption },
	foreignKey : 'optionid',
	as         : 'compatible_plans'
});
```

Then I create a plan and an option"

```js
db.sync({ force : true })
	.then(function () {
		return ConnectionPlan.create({
			title : 'Lite Plan',
			price : 100
		});
	})
	.then(function (plan) {
		return ConnectionOption.create({
			title : 'Additional 100GB to your storage',
			price : 10
		});
	});
```

Then I add a link between those (Strange I couldn't do that with plan.addOption) in database:

```sql
insert into plan2option (planid, optionid, recommend, weight) values (1, 1, true, 100);
```

And then I try to retrieve a plan with the options in include:

```js
ConnectionPlan.findAll({
	include : [
		{
			model      : ConnectionOption,
			through    : { attributes : [ 'recommend', 'weight' ], as : 'attributes' },
			as         : 'compatible_options',
			attributes : ['id', 'title'],
			required   : false
		}
	]
}).then(function (plans) {
	plans.forEach(function (plan) {
		var plainedPlan = plan.get({ plain : true });
		console.log(plainedPlan.compatible_options);
	});
});
```

It all works, but the problem is caused by custom getter in Option model. I expect to get this printed:

```
[ { id: 1,
    title: 'Additional 100GB to your storage',
    attributes: { recommend: true, weight: 100 } } ]
```

But actually I get this:

```
[ { price: undefined,
    id: 1,
    title: 'Additional 100GB to your storage',
    attributes: { recommend: true, weight: 100 } } ]
```

I get price that's undefined. This is unwanted result isn't it? Or am I missing something here?
My packages:
```json
"pg": "^4.4.0",
"pg-hstore": "^2.3.2",
"sequelize": "^3.3.2"
```

**Comment by janmeier** [comment]
Yeah that looks like a bug to me

**Comment by ns3777k** [comment]
Did some research. The issue itself appears to happen in `Instance.prototype.get` [around 208 line](https://github.com/sequelize/sequelize/blob/master/lib/instance.js#L208). There's a loop over custom getters but it doesn't check whether I passed any attributes. Hope to make a PR today

**Comment by janmeier** [comment]
@ns3777k Cool! :)

There might be a problem with virtual getters though, getters that are not linked to a specific attribute:

```js
define('user', attributes, {
  getterMethods: ..

});
```

Should be solveable by marking those which match a property name, and not calling those though :) - at least when they are defined as part of the column (as opposed to as part of the options

**Comment by ns3777k** [comment]
@janmeier Thanks for the tip! For now (plain sequelize 3.3.2) if I pass a virtual field to the attributes array an error popups up:

```js
var ConnectionOption = db.define('ConnectionOption', {
	title     : SEQUELIZE.TEXT,
	price     : {
		type  : SEQUELIZE.INTEGER,
		field : 'price',
		get   : function () {
			return this.getDataValue('price');
		},
		set   : function (val) {
			this.setDataValue('price', val);
		}
	},
	formattedPrice : {
		type : SEQUELIZE.VIRTUAL,
		get   : function () {
			return '$' + this.getDataValue('price');
		}
	}
}, {
	tableName : 'connection_option',
	createdAt : false,
	updatedAt : false,
	deletedAt : false
});

// ...

ConnectionPlan.findAll({
	include : [
		{
			model      : ConnectionOption,
			through    : { attributes : [ 'recommend', 'weight' ], as : 'attributes' },
			as         : 'compatible_options',
			attributes : ['id', 'title', 'formattedPrice'],
			required   : false
		}
	]
});

Unhandled rejection SequelizeDatabaseError: column compatible_options.formattedPrice does not exist
    at Query.formatError (/home/nsafonov/Desktop/sequelize_tests/node_modules/sequelize/lib/dialects/postgres/query.js:423:14)
    at null.<anonymous> (/home/nsafonov/Desktop/sequelize_tests/node_modules/sequelize/lib/dialects/postgres/query.js:104:19)
    at emit (events.js:107:17)
    at Query.handleError (/home/nsafonov/Desktop/sequelize_tests/node_modules/pg/lib/query.js:99:8)
    at null.<anonymous> (/home/nsafonov/Desktop/sequelize_tests/node_modules/pg/lib/client.js:166:26)
    at emit (events.js:107:17)
    at Socket.<anonymous> (/home/nsafonov/Desktop/sequelize_tests/node_modules/pg/lib/connection.js:109:12)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

I guess that's another issue?

**Comment by janmeier** [comment]
I don't really think thats an issue - you are telling sequelize to select something that doesn't exist, so :P

We remove other non-existent attributes, so I guess we could say we should exclude virtuals as well - You are welcome to PR a fix

**Comment by mickhansen** [comment]
We exclude virtuals from select now.
