### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'key' of undefined.

### ISSUE THREAD

**Issue by sdroadie** [sequelize/sequelize#4123]
I have a migration set up that worked previously. When I go to run `sequelize db:migrate`. I get the following error output.

```
Unhandled rejection TypeError: Cannot read property 'key' of undefined
    at Sequelize.normalizeDataType (/Users/jneal2/Projects/brick-gardens/central-server-api/node_modules/sequelize/lib/sequelize.js:1209:64)
    at /Users/jneal2/Projects/brick-gardens/central-server-api/node_modules/sequelize/lib/query-interface.js:88:37
    at /Users/jneal2/Projects/brick-gardens/central-server-api/node_modules/sequelize/node_modules/lodash/index.js:3395:24
    at /Users/jneal2/Projects/brick-gardens/central-server-api/node_modules/sequelize/node_modules/lodash/index.js:3073:15
    at baseForOwn (/Users/jneal2/Projects/brick-gardens/central-server-api/node_modules/sequelize/node_modules/lodash/index.js:2046:14)
    at Function.<anonymous> (/Users/jneal2/Projects/brick-gardens/central-server-api/node_modules/sequelize/node_modules/lodash/index.js:3394:9)
    at QueryInterface.createTable (/Users/jneal2/Projects/brick-gardens/central-server-api/node_modules/sequelize/lib/query-interface.js:83:24)
    at Object.module.exports.up (/Users/jneal2/Projects/brick-gardens/central-server-api/migrations/.20150714145903-create-satchel.js:7:27)
    at module.exports.redefine.Class._exec (/Users/jneal2/.nvm/versions/node/v0.12.7/lib/node_modules/sequelize-cli/node_modules/umzug/lib/migration.js:49:23)
    at module.exports.redefine.Class.up (/Users/jneal2/.nvm/versions/node/v0.12.7/lib/node_modules/sequelize-cli/node_modules/umzug/lib/migration.js:33:17)
    at null.<anonymous> (/Users/jneal2/.nvm/versions/node/v0.12.7/lib/node_modules/sequelize-cli/node_modules/umzug/index.js:78:28)
    at Object.tapHandler (/Users/jneal2/.nvm/versions/node/v0.12.7/lib/node_modules/sequelize-cli/node_modules/bluebird/js/main/finally.js:63:43)
    at Object.tryCatcher (/Users/jneal2/.nvm/versions/node/v0.12.7/lib/node_modules/sequelize-cli/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/jneal2/.nvm/versions/node/v0.12.7/lib/node_modules/sequelize-cli/node_modules/bluebird/js/main/promise.js:489:31)
    at Promise._settlePromiseAt (/Users/jneal2/.nvm/versions/node/v0.12.7/lib/node_modules/sequelize-cli/node_modules/bluebird/js/main/promise.js:565:18)
    at Promise._settlePromises (/Users/jneal2/.nvm/versions/node/v0.12.7/lib/node_modules/sequelize-cli/node_modules/bluebird/js/main/promise.js:681:14)
    at Async._drainQueue (/Users/jneal2/.nvm/versions/node/v0.12.7/lib/node_modules/sequelize-cli/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/jneal2/.nvm/versions/node/v0.12.7/lib/node_modules/sequelize-cli/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/jneal2/.nvm/versions/node/v0.12.7/lib/node_modules/sequelize-cli/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

I'm using Sequelize 3.3.2, and the CLI version is 3.9.0.

**Comment by janmeier** [comment]
Please show the code for the migration

**Comment by jrjuniorsp** [comment]
Same problem here. When I was using Sequelize 3.2.0 and Sequelize-CLI 1.7.0 was working fine. Now, I am using the latest Sequelize (3.3.2) and Sequelize-CLI (1.7.1) and I get the same problem.

Model:
```javascript
'use strict';
module.exports = function(sequelize, DataTypes) {
  var Products = sequelize.define('Products', {
    sku: DataTypes.STRING,
    name: DataTypes.STRING,
    stock: DataTypes.INT,
    price: DataTypes.DOUBLE
  }, {
    classMethods: {
      associate: function(models) {
        // associations can be defined here
      }
    }
  });
  return Products;
};
```
Migration file
```javascript
'use strict';
module.exports = {
  up: function(queryInterface, Sequelize) {
    return queryInterface.createTable('Products', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
      },
      sku: {
        type: Sequelize.STRING
      },
      name: {
        type: Sequelize.STRING
      },
      stock: {
        type: Sequelize.INT
      },
      price: {
        type: Sequelize.DOUBLE
      },
      createdAt: {
        allowNull: false,
        type: Sequelize.DATE
      },
      updatedAt: {
        allowNull: false,
        type: Sequelize.DATE
      }
    });
  },
  down: function(queryInterface, Sequelize) {
    return queryInterface.dropTable('Products');
  }
};
```

**Comment by sdroadie** [comment]
Here are my migration files. They are relatively similar to those above. Also, they were generated with the CLI, so I don't know what could be wrong with them.

```
"use strict";

module.exports = {
  up: function(queryInterface, Sequelize) {
    return queryInterface.createTable("Satchels", {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
      },
      tags: {
        type: Sequelize.ARRAY
      },
      createdAt: {
        allowNull: false,
        type: Sequelize.DATE
      },
      updatedAt: {
        allowNull: false,
        type: Sequelize.DATE
      }
    });
  },
  down: function(queryInterface, Sequelize) {
    return queryInterface.dropTable("Satchels");
  }
};
```

```
"use strict";

module.exports = {
  up: function (queryInterface, Sequelize) {
    return queryInterface.createTable("Users", {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
      },
      username: {
        type: Sequelize.STRING,
        unique: true
      },
      first_name: {
        type: Sequelize.STRING
      },
      last_name: {
        type: Sequelize.STRING
      },
      email: {
        type: Sequelize.STRING,
        unique: true
      },
      password: {
        type: Sequelize.STRING
      },
      organizations: {
        type: Sequelize.ARRAY(Sequelize.STRING)
      },
      role: {
        type: Sequelize.ENUM("guest", "user", "curator", "admin"),
        default: "user"
      },
      createdAt: {
        allowNull: false,
        type: Sequelize.DATE
      },
      updatedAt: {
        allowNull: false,
        type: Sequelize.DATE
      }
    });
  },

  down: function (queryInterface, Sequelize) {
    return queryInterface.dropTable("Users");
  }
};
```

In my case, an error gets thrown at `return queryInterface.createTable(...)`.

**Comment by janmeier** [comment]
@jrjuniorsp `DataTypes.INT` is not defined - use `INTEGER`

@sdroadie Nothing looks off to me, but make sure that all types are actually defined - try removing columns till the error goes away to see what is causing the isseu

**Comment by jrjuniorsp** [comment]
Thanks @janmeier. It worked now!!

**Comment by sdroadie** [comment]
Figured it out. I wasn't specifying a type for an array.

**Comment by DesignByOnyx** [comment]
This bit me too. I was wanting to change a column to allow NULL values. I was using the following code:

```js
    queryInterface.changeColumn(
      'myTable',
      'someColumn',
      {
        allowNull: true
      }
    );
```

... but things did not start working until I specified a `type`:

```js
    queryInterface.changeColumn(
      'myTable',
      'someColumn',
      {
        type: Sequelize.STRING,
        allowNull: true
      }
    );
```

**Comment by golergka** [comment]
Bit by the same problem. Here's my migration file:

```
'use strict';

module.exports = {
  up: function (queryInterface, Sequelize) {
    return [queryInterface.changeColumn('users', 'action_count', {
      defaultValue: 0
    })];
  },

  down: function (queryInterface, Sequelize) {
    return [queryInterface.changeColumn('users', 'action_count', {
      defaultValue: null
    })];
  }
}
```

**Comment by golergka** [comment]
[Created new issue in the CLI repo.](https://github.com/sequelize/cli/issues/427)

**Comment by alexdrans** [comment]
Not sure if you ever figured this out @golergka, but the answer was right above you from @DesignByOnyx

**Comment by johnny-dash** [comment]
The same problem.
`TypeError: Cannot read property 'set' of undefined
    at results.forEach (/Users/mzd/Desktop/Shroogal/shroogal-dev/node_modules/sequelize/lib/model.js:2357:27)
    at Array.forEach (<anonymous>)
    at QueryInterface.bulkInsert.then.results (/Users/mzd/Desktop/Shroogal/shroogal-dev/node_modules/sequelize/lib/model.js:2356:21)
    at tryCatcher (/Users/mzd/Desktop/Shroogal/shroogal-dev/node_modules/sequelize/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/mzd/Desktop/Shroogal/shroogal-dev/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/mzd/Desktop/Shroogal/shroogal-dev/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/mzd/Desktop/Shroogal/shroogal-dev/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/mzd/Desktop/Shroogal/shroogal-dev/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/mzd/Desktop/Shroogal/shroogal-dev/node_modules/sequelize/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/mzd/Desktop/Shroogal/shroogal-dev/node_modules/sequelize/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/mzd/Desktop/Shroogal/shroogal-dev/node_modules/sequelize/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
/static/list-of-products/12/undefined`

Here is migration file
`
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('documentsInstruments', {
    docid: {
      type: DataTypes.INTEGER(11),
      allowNull: false,
      primaryKey: true,
      autoIncrement: true,
      field: 'docid'
    },
    iid: {
      type: DataTypes.BIGINT,
      allowNull: true,
      references: {
        model: 'EntityInstruments',
        key: 'IID'
      },
      field: 'IID'
    },
    docType: {
      type: DataTypes.STRING(45),
      allowNull: true,
      field: 'docType'
    },
    docPath: {
      type: DataTypes.STRING(200),
      allowNull: true,
      field: 'docPath'
    },
    creationDate: {
      type: DataTypes.DATE,
      allowNull: true,
      field: 'creationDate'
    },
    addlInfo: {
      type: DataTypes.STRING(500),
      allowNull: true,
      field: 'addlInfo'
    },
    posLabel: {
      type: DataTypes.STRING(45),
      allowNull: true,
      field: 'posLabel'
    },
    active: {
      type: DataTypes.STRING(3),
      allowNull: true,
      defaultValue: 'Y',
      field: 'active'
    },
    origFileName: {
      type: DataTypes.STRING(400),
      allowNull: true,
      field: 'origFileName'
    }
  }, {
    tableName: 'Documents_Instruments'
  });
};
`

**Comment by rsshilli** [comment]
I also had this problem but had a slightly different solution.  I started with this migration:
```
module.exports.up = function (queryInterface, DataTypes) {
  return queryInterface.changeColumn(
    "UserActivities",
    "action",
    DataTypes.ENUM( "View", "Add", "Edit", "Delete", "Login", "Accept Terms", "View List", "View Dashboard", "View Report", "Propose for Approval", "Propose for Archival", "Propose for Restore", "Reject Approval", "Reject Archival", "Reject Restore", "Approve", "Approve Archival", "Approve Restore", "Withdraw",  "")
  )
};
```

But for some reason had to change it to this:
```
module.exports.up = function (queryInterface, DataTypes) {
  return queryInterface.changeColumn(
    "UserActivities",
    "action",
    {
      type: DataTypes.ENUM( "View", "Add", "Edit", "Delete", "Login", "Accept Terms", "View List", "View Dashboard", "View Report", "Propose for Approval", "Propose for Archival", "Propose for Restore", "Reject Approval", "Reject Archival", "Reject Restore", "Approve", "Approve Archival", "Approve Restore", "Withdraw",  "")
    }
  )
};
```

Basically I just had to put my ENUM inside of an object with a `type:` field.

**Comment by ketavchotaliya** [comment]
@DesignByOnyx I have same issue, I tried with type but getting error `type "enum_users_userType" already exists`

`
    return queryInterface.changeColumn(
        'users',
          'userType',
          {
            type: Sequelize.ENUM('Admin','User'),
            allowNull: false
     });
`

Dialect : "postgres",
pg : "^7.4.3",

**Comment by donovanhiland** [comment]
@ketavchotaliya there's an issue with replacing/changing enums in sequelize. Try this out: https://www.npmjs.com/package/sequelize-replace-enum-postgres
