### ISSUE TITLE
Issue using defaultValue when separating models into their own files.

### ISSUE THREAD

**Issue by hayesmg** [sequelize/sequelize#4137]
I have, for sanity's sake, separated my models into individual files.  Each file exports a function that accepts the sequelize instance I used to connect to the database.

I initialize my `sequelize` instance in an `index.js` file like so:
```js
var Sequelize = require('sequelize');
var sequelize = new Sequelize(config.database.name,
    config.database.username, config.database.password, {
    host: config.database.server,
    dialect: 'mssql'
});

// ... require each file passing the sequelize variable to their exports.
```

Each model file would export a function that accepted that `sequelize` variable like so:
```js
var Sequelize = require('sequelize');

module.exports = function(sequelize) {

    var Document = sequelize.define('Document', {
        ID: { type: Sequelize.UUID, primaryKey: true, defaultValue: Sequelize.UUIDV4 },
        DocumentTypeName: { type: Sequelize.STRING, allowNull: false },
        Filename: { type: Sequelize.STRING, allowNull: false },
        CreatedOn: { type: Sequelize.DATE, allowNull: false, defaultValue: Sequelize.NOW }
    }, { tableName: 'Document', createdAt: false, updatedAt: false });

    return Document;
};
```

I encountered the following error when attempting to insert into the Document table using the model.  This error occurs in a similar fashion when using Sequelize.NOW.  I resolved the issue by including the `Sequelize` variable that was used in the `index.js` file as part of each exported function's arguments.

```
Executing (default): INSERT INTO [Document] ([ID],[DocumentTypeName],[Filename],[CreatedOn]) OUTPUT INSERTED.* VALUES (`key` = 'UUIDV4', `dialectType
s` = '','Uncategorized','OMITTED.FILE',`key` = 'NOW', `dialectTypes` = '');
{ [SequelizeDatabaseError: Incorrect syntax near '`'.]
  name: 'SequelizeDatabaseError',
  message: 'Incorrect syntax near \'`\'.',
  parent:
   { [RequestError: Incorrect syntax near '`'.]
     name: 'RequestError',
     message: 'Incorrect syntax near \'`\'.',
     code: 'EREQUEST',
     number: 102,
     state: 1,
     class: 15,
     serverName: 'OMITTED',
     procName: '',
     lineNumber: 1,
     sql: 'INSERT INTO [Document] ([ID],[DocumentTypeName],[Filename],[CreatedOn]) OUTPUT INSERTED.* VALUES (`key` = \'UUIDV4\', `dialectTypes` = \'\
',\'Uncategorized\',\'OMITTED.FILE\',`key` = \'NOW\', `dialectTypes` = \'\');' },
  original:
   { [RequestError: Incorrect syntax near '`'.]
     name: 'RequestError',
     message: 'Incorrect syntax near \'`\'.',
     code: 'EREQUEST',
     number: 102,
     state: 1,
     class: 15,
     serverName: 'OMITTED',
     procName: '',
     lineNumber: 1,
     sql: 'INSERT INTO [Document] ([ID],[DocumentTypeName],[Filename],[CreatedOn]) OUTPUT INSERTED.* VALUES (`key` = \'UUIDV4\', `dialectTypes` = \'\
',\'Uncategorized\',\'OMITTED.FILE\',`key` = \'NOW\', `dialectTypes` = \'\');' },
  sql: 'INSERT INTO [Document] ([ID],[DocumentTypeName],[Filename],[CreatedOn]) OUTPUT INSERTED.* VALUES (`key` = \'UUIDV4\', `dialectTypes` = \'\',\
'Uncategorized\',\'OMITTED.FILE\',`key` = \'NOW\', `dialectTypes` = \'\');' }
SequelizeDatabaseError: Incorrect syntax near '`'.
    at Query.formatError (OMITTED\node_modules\sequelize\lib\dialects\mssql\query.js:217:10)
    at Request.userCallback (OMITTED\node_modules\sequelize\lib\dialects\mssql\query.js:66:25)
    at Request.callback (OMITTED\node_modules\tedious\lib\request.js:30:27)
    at Connection.STATE.SENT_CLIENT_REQUEST.events.message (OMITTED\node_modules\tedious\lib\connection.js:283:2
9)
    at Connection.dispatchEvent (OMITTED\node_modules\tedious\lib\connection.js:752:59)
    at MessageIO.<anonymous> (OMITTED\node_modules\tedious\lib\connection.js:685:22)
    at emitNone (events.js:67:13)
    at MessageIO.emit (events.js:166:7)
    at MessageIO.eventData (OMITTED\node_modules\tedious\lib\message-io.js:58:21)
    at Socket.<anonymous> (OMITTED\node_modules\tedious\lib\message-io.js:3:59)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:521:20)
```

**Comment by mickhansen** [comment]
Importing sequelize directly should work unless they are two seperate instances of sequelize (node_modules wise).

**Comment by hayesmg** [comment]
I can confirm there is only a single install of sequelize in my node_modules folder.

**Comment by mickhansen** [comment]
Odd, does `new Sequelize.NOW()` work?

**Comment by janmeier** [comment]
Closing, no response
