### ISSUE TITLE
Cannot use sqlite dialect

### ISSUE THREAD

**Issue by lilorox** [sequelize/sequelize#4141]
Hi,

I just installed node on a new machine using node v0.10.49 from nodesource (on Debian Wheezy) and after having installed sequelize + sqlite3, a simple test  fails.

Here what I did (started from an empty directory):
```
$ npm install sequelize sqlite3
/
> sqlite3@3.0.9 install /data/home/lilo/dev/test/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build
[sqlite3] Success: "/data/home/lilo/dev/test/node_modules/sqlite3/lib/binding/node-v11-linux-x64/node_sqlite3.node" is installed via remote
sequelize@3.4.1 node_modules/sequelize
├── shimmer@1.0.0
├── depd@1.0.1
├── toposort-class@0.3.1
├── dottie@0.3.1
├── generic-pool@2.2.0
├── inflection@1.7.1
├── node-uuid@1.4.3
├── validator@3.41.2
├── wkx@0.0.7
├── bluebird@2.9.34
├── wellknown@0.3.1 (minimist@0.0.2, concat-stream@1.4.10)
├── moment-timezone@0.4.0
├── lodash@3.10.0
└── moment@2.10.3
sqlite3@3.0.9 node_modules/sqlite3
└── nan@1.8.4

$ node
> var Sequelize = require('sequelize');
undefined
> var sequelize = new Sequelize('test', null, null, {dialect: "sqlite"});
Error: The dialect sqlite is not supported. (Error: Please install sqlite3 package manually)
    at new Sequelize (/data/home/lilo/dev/test/node_modules/sequelize/lib/sequelize.js:182:11)
    at repl:1:17
    at REPLServer.self.eval (repl.js:110:21)
    at repl.js:249:20
    at REPLServer.self.eval (repl.js:122:7)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:203:10)
    at Interface._line (readline.js:532:8)
    at Interface._ttyWrite (readline.js:761:14)
    at ReadStream.onkeypress (readline.js:100:10)
    at ReadStream.emit (events.js:98:17)
    at emitKey (readline.js:1096:12)
    at ReadStream.onData (readline.js:841:14)
    at ReadStream.emit (events.js:95:17)
    at ReadStream.<anonymous> (_stream_readable.js:765:14)
> %

$ which npm
/usr/bin/npm

$ which node
/usr/bin/node

$ node --version
v0.10.40

$ npm --version
1.4.28
```

Any idea what I'm missing?

Thanks!

**Comment by janmeier** [comment]
Can you manually require sqlite3`

**Comment by mickhansen** [comment]
Make sure the node binary used for npm install and for running your program is the same.

**Comment by lilorox** [comment]
@mickhansen that is the case, npm's shebang is pointing to the node executable I'm using. I have only one installed anyway.

@janmeier the problem was here!
```
$ node
> var sqlite3 = require('sqlite3'),
... Sequelize = require('sequelize');
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /data/home/lilo/dev/test/node_modules/sqlite3/lib/binding/node-v11-linux-x64/node_sqlite3.node)
```

sqlite3 v3.0.9 is broken for debian wheezy because it requires Glibc 2.14 (2.13.1 on my system).
I reverted to 3.0.8 and it's all good.

Thanks!
