### ISSUE TITLE
Getting Sequelize Errors when trying to deploy to Heroku

### ISSUE THREAD

**Issue by rahul1346** [sequelize/sequelize#4142]
Im trying to deploy to heroku and and have done the standard heroku create and push commands and get the following log

```
$ heroku logs --tail
2015-07-17T05:52:12.914883+00:00 app[web.1]:     at /app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:61:20
2015-07-17T05:52:12.914885+00:00 app[web.1]:     at null.<anonymous> (/app/node_modules/pg/lib/client.js:171:5)
2015-07-17T05:52:12.914887+00:00 app[web.1]:     at emit (events.js:107:17)
2015-07-17T05:52:12.914888+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:59:10)
2015-07-17T05:52:12.914890+00:00 app[web.1]:     at Socket.emit (events.js:107:17)
2015-07-17T05:52:12.914891+00:00 app[web.1]:     at net.js:459:14
2015-07-17T05:52:12.914893+00:00 app[web.1]:     at process._tickCallback (node.js:355:11)
2015-07-17T05:52:13.764130+00:00 heroku[web.1]: Process exited with status 0
2015-07-17T05:52:13.776036+00:00 heroku[web.1]: State changed from starting to crashed
2015-07-17T08:40:55.185290+00:00 heroku[web.1]: State changed from crashed to starting
2015-07-17T08:41:00.454693+00:00 heroku[web.1]: Starting process with command `node server.js`
2015-07-17T08:41:02.287641+00:00 app[web.1]: Detected 512 MB available memory, 512 MB limit per process (WEB_MEMORY)
2015-07-17T08:41:02.287670+00:00 app[web.1]: Recommending WEB_CONCURRENCY=1
2015-07-17T08:41:03.722456+00:00 app[web.1]: Unhandled rejection SequelizeConnectionRefusedError: connect ECONNREFUSED
2015-07-17T08:41:03.722465+00:00 app[web.1]:     at null.<anonymous> (/app/node_modules/pg/lib/client.js:171:5)
2015-07-17T08:41:03.722463+00:00 app[web.1]:     at /app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:61:20
2015-07-17T08:41:03.722467+00:00 app[web.1]:     at emit (events.js:107:17)
2015-07-17T08:41:03.722468+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:59:10)
2015-07-17T08:41:03.722470+00:00 app[web.1]:     at Socket.emit (events.js:107:17)
2015-07-17T08:41:03.722471+00:00 app[web.1]:     at net.js:459:14
2015-07-17T08:41:03.722472+00:00 app[web.1]:     at process._tickCallback (node.js:355:11)
2015-07-17T08:41:04.589456+00:00 heroku[web.1]: Process exited with status 0
2015-07-17T08:41:04.606837+00:00 heroku[web.1]: State changed from starting to crashed
2015-07-17T10:43:13.146023+00:00 heroku[web.1]: State changed from crashed to starting
2015-07-17T10:43:17.738695+00:00 heroku[web.1]: Starting process with command `node server.js`
2015-07-17T10:43:20.563395+00:00 app[web.1]: Detected 512 MB available memory, 512 MB limit per process (WEB_MEMORY)
2015-07-17T10:43:20.563417+00:00 app[web.1]: Recommending WEB_CONCURRENCY=1
2015-07-17T10:43:23.187284+00:00 app[web.1]: Unhandled rejection SequelizeConnectionRefusedError: connect ECONNREFUSED
2015-07-17T10:43:23.187289+00:00 app[web.1]:     at /app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:61:20
2015-07-17T10:43:23.187291+00:00 app[web.1]:     at null.<anonymous> (/app/node_modules/pg/lib/client.js:171:5)
2015-07-17T10:43:23.187293+00:00 app[web.1]:     at emit (events.js:107:17)
2015-07-17T10:43:23.187294+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:59:10)
2015-07-17T10:43:23.187296+00:00 app[web.1]:     at Socket.emit (events.js:107:17)
2015-07-17T10:43:23.187299+00:00 app[web.1]:     at process._tickCallback (node.js:355:11)
2015-07-17T10:43:23.187297+00:00 app[web.1]:     at net.js:459:14
2015-07-17T10:43:24.101779+00:00 heroku[web.1]: Process exited with status 0
2015-07-17T10:43:24.111661+00:00 heroku[web.1]: State changed from starting to crashed
2015-07-17T14:55:48.345314+00:00 heroku[api]: Attach DATABASE resource by rahul@jobletics.com
2015-07-17T14:55:48.345314+00:00 heroku[api]: Release v4 created by rahul@jobletics.com
2015-07-17T14:55:48.505225+00:00 heroku[web.1]: State changed from crashed to starting
2015-07-17T14:55:53.199095+00:00 heroku[web.1]: Starting process with command `node server.js`
2015-07-17T14:55:55.143255+00:00 app[web.1]: Detected 512 MB available memory, 512 MB limit per process (WEB_MEMORY)
2015-07-17T14:55:55.143320+00:00 app[web.1]: Recommending WEB_CONCURRENCY=1
2015-07-17T14:55:56.136056+00:00 app[web.1]: Unhandled rejection SequelizeConnectionRefusedError: connect ECONNREFUSED
2015-07-17T14:55:56.136061+00:00 app[web.1]:     at /app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:61:20
2015-07-17T14:55:56.136063+00:00 app[web.1]:     at null.<anonymous> (/app/node_modules/pg/lib/client.js:171:5)
2015-07-17T14:55:56.136065+00:00 app[web.1]:     at emit (events.js:107:17)
2015-07-17T14:55:56.136066+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:59:10)
2015-07-17T14:55:56.136068+00:00 app[web.1]:     at Socket.emit (events.js:107:17)
2015-07-17T14:55:56.136070+00:00 app[web.1]:     at net.js:459:14
2015-07-17T14:55:56.136071+00:00 app[web.1]:     at process._tickCallback (node.js:355:11)
2015-07-17T14:55:57.166962+00:00 heroku[web.1]: State changed from starting to crashed
2015-07-17T14:55:57.168288+00:00 heroku[web.1]: State changed from crashed to starting
2015-07-17T14:55:57.154470+00:00 heroku[web.1]: Process exited with status 0
2015-07-17T14:56:01.094451+00:00 heroku[web.1]: Starting process with command `node server.js`
2015-07-17T14:56:03.331534+00:00 app[web.1]: Detected 512 MB available memory, 512 MB limit per process (WEB_MEMORY)
2015-07-17T14:56:03.331565+00:00 app[web.1]: Recommending WEB_CONCURRENCY=1
2015-07-17T14:56:04.559552+00:00 app[web.1]: Unhandled rejection SequelizeConnectionRefusedError: connect ECONNREFUSED
2015-07-17T14:56:04.559556+00:00 app[web.1]:     at /app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:61:20
2015-07-17T14:56:04.559561+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:59:10)
2015-07-17T14:56:04.559560+00:00 app[web.1]:     at emit (events.js:107:17)
2015-07-17T14:56:04.559563+00:00 app[web.1]:     at Socket.emit (events.js:107:17)
2015-07-17T14:56:04.559558+00:00 app[web.1]:     at null.<anonymous> (/app/node_modules/pg/lib/client.js:171:5)
2015-07-17T14:56:04.559566+00:00 app[web.1]:     at process._tickCallback (node.js:355:11)
2015-07-17T14:56:04.559564+00:00 app[web.1]:     at net.js:459:14
2015-07-17T14:56:05.608314+00:00 heroku[web.1]: State changed from starting to crashed
2015-07-17T14:56:05.590100+00:00 heroku[web.1]: Process exited with status 0
2015-07-17T15:15:20.324314+00:00 heroku[api]: Deploy 708589b by rahul@jobletics.com
2015-07-17T15:15:20.324314+00:00 heroku[api]: Release v5 created by rahul@jobletics.com
2015-07-17T15:15:20.395896+00:00 heroku[slug-compiler]: Slug compilation started
2015-07-17T15:15:20.395926+00:00 heroku[slug-compiler]: Slug compilation finished
2015-07-17T15:15:28.127060+00:00 heroku[web.1]: Starting process with command `node server.js`
2015-07-17T15:15:30.647548+00:00 app[web.1]: Recommending WEB_CONCURRENCY=1
2015-07-17T15:15:30.647460+00:00 app[web.1]: Detected 512 MB available memory, 512 MB limit per process (WEB_MEMORY)
2015-07-17T15:15:32.297969+00:00 app[web.1]: Unhandled rejection SequelizeConnectionRefusedError: connect ECONNREFUSED
2015-07-17T15:15:32.297978+00:00 app[web.1]:     at /app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:61:20
2015-07-17T15:15:32.297981+00:00 app[web.1]:     at null.<anonymous> (/app/node_modules/pg/lib/client.js:171:5)
2015-07-17T15:15:32.297984+00:00 app[web.1]:     at emit (events.js:107:17)
2015-07-17T15:15:32.297990+00:00 app[web.1]:     at net.js:459:14
2015-07-17T15:15:32.297986+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:59:10)
2015-07-17T15:15:32.297992+00:00 app[web.1]:     at process._tickCallback (node.js:355:11)
2015-07-17T15:15:32.297988+00:00 app[web.1]:     at Socket.emit (events.js:107:17)
2015-07-17T15:15:33.403335+00:00 heroku[web.1]: Process exited with status 0
2015-07-17T15:15:43.603603+00:00 heroku[web.1]: Starting process with command `node server.js`
2015-07-17T15:15:47.126463+00:00 app[web.1]: Detected 512 MB available memory, 512 MB limit per process (WEB_MEMORY)
2015-07-17T15:15:47.126494+00:00 app[web.1]: Recommending WEB_CONCURRENCY=1
2015-07-17T15:15:48.207736+00:00 app[web.1]: Unhandled rejection SequelizeConnectionRefusedError: connect ECONNREFUSED
2015-07-17T15:15:48.207744+00:00 app[web.1]:     at null.<anonymous> (/app/node_modules/pg/lib/client.js:171:5)
2015-07-17T15:15:48.207742+00:00 app[web.1]:     at /app/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:61:20
2015-07-17T15:15:48.207746+00:00 app[web.1]:     at emit (events.js:107:17)
2015-07-17T15:15:48.207747+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:59:10)
2015-07-17T15:15:48.207749+00:00 app[web.1]:     at Socket.emit (events.js:107:17)
2015-07-17T15:15:48.207750+00:00 app[web.1]:     at net.js:459:14
2015-07-17T15:15:48.207752+00:00 app[web.1]:     at process._tickCallback (node.js:355:11)
2015-07-17T15:15:49.050609+00:00 heroku[web.1]: Process exited with status 0
2015-07-17T15:15:21.765636+00:00 heroku[web.1]: State changed from crashed to starting
2015-07-17T15:15:33.421267+00:00 heroku[web.1]: State changed from starting to crashed
2015-07-17T15:15:33.422265+00:00 heroku[web.1]: State changed from crashed to starting
2015-07-17T15:15:51.434243+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=thawing-sierra-7836.herokuapp.com request_id=4fdf0c7d-5713-4eac-bfb7-1a20f5031fd3 fwd="50.177.220.150" dyno= connect= service= status=503 bytes=
2015-07-17T15:15:51.766589+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=thawing-sierra-7836.herokuapp.com request_id=e775bcaa-6e21-4bc3-9587-8a249a8e54eb fwd="50.177.220.150" dyno= connect= service= status=503 bytes=
2015-07-17T15:15:49.072186+00:00 heroku[web.1]: State changed from starting to crashed
```

I created Heroku postres addon and added the db details to my config.js file. My model/index.js file looks like this:

```
"use strict";

var fs        = require("fs");
var path      = require("path");
var Sequelize = require("sequelize");
var basename  = path.basename(module.filename);
// Use env variable for our project.
var env       = process.env.NODE_ENV || "development";
// Read config from `config/config.js`;
// `node_modules/.bin/sequelize -c config/config.js cmd`
var config    = require(__dirname + '/../config/config.js')[env];
var sequelize = new Sequelize(config.database, config.username, config.password, config);
// Store the models.
var db        = {};

fs
  .readdirSync(__dirname)
  .filter(function(file) {
    return (file.indexOf(".") !== 0) && (file !== basename);
  })
  .forEach(function(file) {
    var model = sequelize["import"](path.join(__dirname, file));
    db[model.name] = model;
  });

Object.keys(db).forEach(function(modelName) {
  if ("associate" in db[modelName]) {
    db[modelName].associate(db);
  }
});

// Adds `sequelize` instance to db object.
db.sequelize = sequelize;

// Adds `Sequelize` class to db object.
db.Sequelize = Sequelize;

// Expose the db object.
module.exports = db;
```
My server.js looks like this:

```
// app dependencies
var morgan = require('morgan');
var methodOverride = require('method-override');
var bodyParser = require('body-parser');
var session = require('express-session');
var cookieParser = require('cookie-parser');
var express = require("express");
var isProduction = process.env.NODE_ENV === 'production';
var app = express();

//middleware
app.use(bodyParser.urlencoded({
  extended: true
}));
app.use(bodyParser.json({
    strict: false
}));
app.use(morgan(isProduction || 'dev'));
// static resources
app.use(express.static("./public"));
app.use(methodOverride());

// Use cookie middleware
app.use(cookieParser());
// Enable session management by express
app.use(session({
  secret: 'changethis!',
  resave: false,
  saveUninitialized: false
}));

// Init the models
var db = require("./models");

db.sequelize
  //You can set `force` to `true` in development mode.
  .sync({
        //force: true
    })
  //.sync()
  .then(function() {
    console.log('Express server listening on port 5000');
    app.listen(5000);
});


var auth_handler = require('./lib/auth/passport.js')(app, db.User);

// resources routes
// app.use('/', require('./routes/web'));
//app.use('/api', auth_handler, require('./routes/api'));
app.use('/api', require('./routes/api'));

// default route for website
app.use( function(request, response) {
  response.sendFile('./public/index.html', {root: __dirname});
});

```

Any idea whats going on?

**Comment by mickhansen** [comment]
Looks like it can't connect. Credentials must be off, or you might have to enable SSL.

**Comment by rahul1346** [comment]
Got it to work. Thanks

**Comment by RobertAKARobin** [comment]
Simply because I know I'm going to run into this again:

```js
if (process.env.DATABASE_URL) {
  // the application is executed on Heroku ... use the postgres database
  sequelize = new Sequelize(process.env.DATABASE_URL, {
    dialect:  'postgres',
    protocol: 'postgres',
    logging:  true //false
  });
} else {
  // the application is executed on the local machine
  sequelize = new Sequelize("postgres:///my_db");
}
```

**Comment by jsharonk** [comment]
hello, does anyone have any other suggestions? i have tried @RobertAKARobin 's recommendation to no avail, unfortunately

**Comment by RobertAKARobin** [comment]
@jsharonk Can you let us know specifically what errors you're getting?

**Comment by jsharonk** [comment]
oh hello! thanks for your prompt reply
--

2017-01-18T21:37:50.975109+00:00 app[api]: Starting process with command `bash` by user jsharonkim@gmail.com
2017-01-18T21:37:53.890189+00:00 heroku[run.3975]: Awaiting client
2017-01-18T21:37:53.941164+00:00 heroku[run.3975]: Starting process with command `bash`
2017-01-18T21:37:54.060432+00:00 heroku[run.3975]: State changed from starting to up
2017-01-18T21:38:18.267374+00:00 heroku[run.3975]: State changed from up to complete
2017-01-18T21:38:18.253459+00:00 heroku[run.3975]: Process exited with status 130
2017-01-18T21:38:59.687140+00:00 heroku[slug-compiler]: Slug compilation started
2017-01-18T21:38:59.687151+00:00 heroku[slug-compiler]: Slug compilation finished
2017-01-18T21:38:59.532452+00:00 app[api]: Deploy fe33313 by user jsharonkim@gmail.com
2017-01-18T21:38:59.532452+00:00 app[api]: Release v22 created by user jsharonkim@gmail.com
2017-01-18T21:38:59.798253+00:00 heroku[web.1]: State changed from crashed to starting
2017-01-18T21:39:01.797112+00:00 heroku[web.1]: Starting process with command `node index.js`
2017-01-18T21:39:03.731139+00:00 app[web.1]: /app/db/models.js:16
2017-01-18T21:39:03.731153+00:00 app[web.1]:       port: match[4],
2017-01-18T21:39:03.731154+00:00 app[web.1]:             ^
2017-01-18T21:39:03.731155+00:00 app[web.1]: 
2017-01-18T21:39:03.731156+00:00 app[web.1]: ReferenceError: match is not defined
2017-01-18T21:39:03.731157+00:00 app[web.1]:     at Object.<anonymous> (/app/db/models.js:16:17)
2017-01-18T21:39:03.731157+00:00 app[web.1]:     at Module._compile (module.js:541:32)
2017-01-18T21:39:03.731158+00:00 app[web.1]:     at loader (/app/node_modules/babel-register/lib/node.js:144:5)
2017-01-18T21:39:03.731159+00:00 app[web.1]:     at Object.require.extensions.(anonymous function) [as .js] (/app/node_modules/babel-register/lib/node.js:154:7)
2017-01-18T21:39:03.731160+00:00 app[web.1]:     at Module.load (module.js:458:32)
2017-01-18T21:39:03.731161+00:00 app[web.1]:     at tryModuleLoad (module.js:417:12)
2017-01-18T21:39:03.731162+00:00 app[web.1]:     at Function.Module._load (module.js:409:3)
2017-01-18T21:39:03.731162+00:00 app[web.1]:     at Module.require (module.js:468:17)
2017-01-18T21:39:03.731163+00:00 app[web.1]:     at require (internal/module.js:20:19)
2017-01-18T21:39:03.731163+00:00 app[web.1]:     at Object.<anonymous> (/app/index.js:10:16)
2017-01-18T21:39:03.731164+00:00 app[web.1]:     at Module._compile (module.js:541:32)
2017-01-18T21:39:03.731164+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:550:10)
2017-01-18T21:39:03.731165+00:00 app[web.1]:     at Module.load (module.js:458:32)
2017-01-18T21:39:03.731165+00:00 app[web.1]:     at tryModuleLoad (module.js:417:12)
2017-01-18T21:39:03.731166+00:00 app[web.1]:     at Function.Module._load (module.js:409:3)
2017-01-18T21:39:03.731166+00:00 app[web.1]:     at Module.runMain (module.js:575:10)
2017-01-18T21:39:03.793985+00:00 heroku[web.1]: State changed from starting to crashed
2017-01-18T21:39:03.773887+00:00 heroku[web.1]: Process exited with status 1
2017-01-18T21:39:13.041959+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=analogy-alley.herokuapp.com request_id=43ea20b0-ef8a-4cbf-9bfb-aecd257033df fwd="207.251.103.46" dyno= connect= service= status=503 bytes=
2017-01-18T21:39:13.215236+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=analogy-alley.herokuapp.com request_id=2f974bbc-4729-486f-82f8-20d513bdd4d4 fwd="207.251.103.46" dyno= connect= service= status=503 bytes=
2017-01-18T21:40:31.634731+00:00 heroku[slug-compiler]: Slug compilation started
2017-01-18T21:40:31.634736+00:00 heroku[slug-compiler]: Slug compilation finished
2017-01-18T21:40:31.463849+00:00 app[api]: Deploy 0f1d1c5 by user jsharonkim@gmail.com
2017-01-18T21:40:31.463849+00:00 app[api]: Release v23 created by user jsharonkim@gmail.com
2017-01-18T21:40:32.776154+00:00 heroku[web.1]: State changed from crashed to starting
2017-01-18T21:40:35.575451+00:00 heroku[web.1]: Starting process with command `node index.js`
2017-01-18T21:40:38.996810+00:00 app[web.1]: DEPRECATION WARNING: The logging-option should be either a function or false. Default: console.log
2017-01-18T21:40:39.061620+00:00 app[web.1]: /app/db/models.js:43
2017-01-18T21:40:39.061623+00:00 app[web.1]: var Analogy = db.define('analogy', {
2017-01-18T21:40:39.061624+00:00 app[web.1]:               ^
2017-01-18T21:40:39.061624+00:00 app[web.1]: 
2017-01-18T21:40:39.061625+00:00 app[web.1]: ReferenceError: db is not defined
2017-01-18T21:40:39.061626+00:00 app[web.1]:     at Object.<anonymous> (/app/db/models.js:46:17)
2017-01-18T21:40:39.061626+00:00 app[web.1]:     at Module._compile (module.js:541:32)
2017-01-18T21:40:39.061627+00:00 app[web.1]:     at loader (/app/node_modules/babel-register/lib/node.js:144:5)
2017-01-18T21:40:39.061631+00:00 app[web.1]:     at Object.require.extensions.(anonymous function) [as .js] (/app/node_modules/babel-register/lib/node.js:154:7)
2017-01-18T21:40:39.061632+00:00 app[web.1]:     at Module.load (module.js:458:32)
2017-01-18T21:40:39.061633+00:00 app[web.1]:     at tryModuleLoad (module.js:417:12)
2017-01-18T21:40:39.061634+00:00 app[web.1]:     at Function.Module._load (module.js:409:3)
2017-01-18T21:40:39.061634+00:00 app[web.1]:     at Module.require (module.js:468:17)
2017-01-18T21:40:39.061635+00:00 app[web.1]:     at require (internal/module.js:20:19)
2017-01-18T21:40:39.061636+00:00 app[web.1]:     at Object.<anonymous> (/app/index.js:10:16)
2017-01-18T21:40:39.061636+00:00 app[web.1]:     at Module._compile (module.js:541:32)
2017-01-18T21:40:39.061637+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:550:10)
2017-01-18T21:40:39.061638+00:00 app[web.1]:     at Module.load (module.js:458:32)
2017-01-18T21:40:39.061638+00:00 app[web.1]:     at tryModuleLoad (module.js:417:12)
2017-01-18T21:40:39.061639+00:00 app[web.1]:     at Function.Module._load (module.js:409:3)
2017-01-18T21:40:39.061640+00:00 app[web.1]:     at Module.runMain (module.js:575:10)
2017-01-18T21:40:39.151011+00:00 heroku[web.1]: Process exited with status 1
2017-01-18T21:40:39.173729+00:00 heroku[web.1]: State changed from starting to crashed
2017-01-18T21:40:46.734226+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=analogy-alley.herokuapp.com request_id=2c3edd31-0da0-4035-a602-17d57e5bff0f fwd="207.251.103.46" dyno= connect= service= status=503 bytes=
2017-01-18T21:40:46.862275+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=analogy-alley.herokuapp.com request_id=db7b7945-0f00-47ed-b447-9ddad1a18857 fwd="207.251.103.46" dyno= connect= service= status=503 bytes=
2017-01-18T21:41:45.922260+00:00 app[api]: Deploy 426cefc by user jsharonkim@gmail.com
2017-01-18T21:41:45.922260+00:00 app[api]: Release v24 created by user jsharonkim@gmail.com
2017-01-18T21:41:46.085068+00:00 heroku[slug-compiler]: Slug compilation started
2017-01-18T21:41:46.085074+00:00 heroku[slug-compiler]: Slug compilation finished
2017-01-18T21:41:46.323615+00:00 heroku[web.1]: State changed from crashed to starting
2017-01-18T21:41:49.084754+00:00 heroku[web.1]: Starting process with command `node index.js`
2017-01-18T21:41:51.915589+00:00 app[web.1]: DEPRECATION WARNING: The logging-option should be either a function or false. Default: console.log
2017-01-18T21:41:51.975188+00:00 app[web.1]: /app/db/models.js:43
2017-01-18T21:41:51.975191+00:00 app[web.1]: var Analogy = db.define('analogy', {
2017-01-18T21:41:51.975192+00:00 app[web.1]:               ^
2017-01-18T21:41:51.975193+00:00 app[web.1]: 
2017-01-18T21:41:51.975193+00:00 app[web.1]: ReferenceError: db is not defined
2017-01-18T21:41:51.975194+00:00 app[web.1]:     at Object.<anonymous> (/app/db/models.js:46:17)
2017-01-18T21:41:51.975195+00:00 app[web.1]:     at Module._compile (module.js:541:32)
2017-01-18T21:41:51.975196+00:00 app[web.1]:     at loader (/app/node_modules/babel-register/lib/node.js:144:5)
2017-01-18T21:41:51.975197+00:00 app[web.1]:     at Object.require.extensions.(anonymous function) [as .js] (/app/node_modules/babel-register/lib/node.js:154:7)
2017-01-18T21:41:51.975197+00:00 app[web.1]:     at Module.load (module.js:458:32)
2017-01-18T21:41:51.975198+00:00 app[web.1]:     at tryModuleLoad (module.js:417:12)
2017-01-18T21:41:51.975198+00:00 app[web.1]:     at Function.Module._load (module.js:409:3)
2017-01-18T21:41:51.975199+00:00 app[web.1]:     at Module.require (module.js:468:17)
2017-01-18T21:41:51.975200+00:00 app[web.1]:     at require (internal/module.js:20:19)
2017-01-18T21:41:51.975200+00:00 app[web.1]:     at Object.<anonymous> (/app/index.js:10:16)
2017-01-18T21:41:51.975201+00:00 app[web.1]:     at Module._compile (module.js:541:32)
2017-01-18T21:41:51.975202+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:550:10)
2017-01-18T21:41:51.975202+00:00 app[web.1]:     at Module.load (module.js:458:32)
2017-01-18T21:41:51.975203+00:00 app[web.1]:     at tryModuleLoad (module.js:417:12)
2017-01-18T21:41:51.975203+00:00 app[web.1]:     at Function.Module._load (module.js:409:3)
2017-01-18T21:41:51.975204+00:00 app[web.1]:     at Module.runMain (module.js:575:10)
2017-01-18T21:41:52.074396+00:00 heroku[web.1]: Process exited with status 1
2017-01-18T21:41:52.084923+00:00 heroku[web.1]: State changed from starting to crashed
2017-01-18T21:42:01.062458+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=analogy-alley.herokuapp.com request_id=955ed08f-6034-4e17-a38f-3a2ceac7f6b0 fwd="207.251.103.46" dyno= connect= service= status=503 bytes=
2017-01-18T21:42:01.191022+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=analogy-alley.herokuapp.com request_id=a91a19af-8447-4c66-b6cc-41c3c848f026 fwd="207.251.103.46" dyno= connect= service= status=503 bytes=

...but i do define db...i think...

'use strict';

// const Sequelize = require('sequelize');

// const DATABASE_URI = require(path.join(__dirname, '../env')).DATABASE_URI;

if (!global.hasOwnProperty('db')) {
  var Sequelize = require('sequelize')
    , sequelize = null

  if (process.env.HEROKU_POSTGRESQL_RED_URL) {
    // the application is executed on Heroku ... use the postgres database
    const db = new Sequelize(process.env.HEROKU_POSTGRESQL_RED_URL, {
      dialect:  'postgres',
      protocol: 'postgres',
      // port:     match[4],
      // host:     match[3],
      logging:  true //false
    })
  } else {
     const db = new Sequelize(
      'postgres://localhost:5432/analogies', {
        logging: false
      }
   );
  }

  // global.db = {
  //   Sequelize: Sequelize,
  //   sequelize: sequelize,
  //   User:      sequelize.import(__dirname + '/user') 
    
    // add your other models here
  }

  /*
    Associations can be defined here. E.g. like this:
    global.db.User.hasMany(global.db.SomethingElse)
  */
// }

// module.exports = global.db



const Analogy = db.define('analogy', {
  name: {
    type: Sequelize.STRING,
    allowNull: false 
  },
  content: {
    type: Sequelize.TEXT,
    allowNull: false
  }
});


module.exports = {
  Analogy 
}

**Comment by jsharonk** [comment]
@RobertAKARobin got it to work, thanks again for your help—your suggestion is essentially what did it. my problem was that i was using 'const' to save my 'db' variable; i just changed that to 'global.db'

**Comment by leonardocintra** [comment]
```
        var database = process.env.DATABASE_URL || 'campeonatodb'
        var sequelize = ""

        if (process.env.DATABASE_URL) {
            sequelize = new Sequelize(database)
        }
        else {
            sequelize = new Sequelize(database, 'postgres', '', {
                dialect: 'postgres'
            });
        }
```

**Comment by deepakmani** [comment]
Good day. I'm seeking advice for a similar issue.

I have a worker process that is deployed using the Proc file and enabled Papertrail logging.

The message from the log is this:
**Apr 28 02:19:23 enigmatic-fortress-43601 heroku/worker.1: Starting process with command `node app/worker/twitter_streams.js`** 
Apr 28 02:19:24 enigmatic-fortress-43601 heroku/worker.1: State changed from starting to up 
Apr 28 02:19:26 enigmatic-fortress-43601 app/worker.1: Sat, 28 Apr 2018 09:19:26 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:242:13 
**Apr 28 02:19:36 enigmatic-fortress-43601 heroku/worker.1: State changed from up to crashed** 


There doesn't seem to be any errors, only a Warning.

Can someone suggest what could be the issue.

Regards,
Deepak

**Comment by LordLazarus** [comment]
> For Heroku
> 
> ```
>         var database = process.env.DATABASE_URL || 'campeonatodb'
>         var sequelize = ""
> 
>         if (process.env.DATABASE_URL) {
>             sequelize = new Sequelize(database)
>         }
>         else {
>             sequelize = new Sequelize(database, 'postgres', '', {
>                 dialect: 'postgres'
>             });
>         }
> ```
@leonardocintra 
which file would I put that into?

**Comment by leonardocintra** [comment]
> > For Heroku
> > ```
> >         var database = process.env.DATABASE_URL || 'campeonatodb'
> >         var sequelize = ""
> > 
> >         if (process.env.DATABASE_URL) {
> >             sequelize = new Sequelize(database)
> >         }
> >         else {
> >             sequelize = new Sequelize(database, 'postgres', '', {
> >                 dialect: 'postgres'
> >             });
> >         }
> > ```
> 
> @leonardocintra
> which file would I put that into?

try `config.js` 

will depend on your project. I deleted my project that had this setting

**Comment by jpcmf** [comment]
Guys, I am really stucked for three days and I can't solve.

```
backend on  master took 10s
> heroku run sequelize db:migrate
Running sequelize db:migrate on ⬢ frozen-woodland-76492... up, run.7827 (Free)

Sequelize CLI [Node: 10.17.0, CLI: 5.5.1, ORM: 5.19.7]

Loaded configuration file "src/config/database.js".

ERROR: getaddrinfo ENOTFOUND ec2-174-129-33-88.compute-1.amazonaws.com:5432
 ec2-174-129-33-88.compute-1.amazonaws.com:5432
:5432
```

**Comment by jpcmf** [comment]
Guys, I am really stuck for three days and I can't solve. Any tip? Thank you 

```
backend on  master took 10s
> heroku run sequelize db:migrate
Running sequelize db:migrate on ⬢ frozen-woodland-76492... up, run.7827 (Free)

Sequelize CLI [Node: 10.17.0, CLI: 5.5.1, ORM: 5.19.7]

Loaded configuration file "src/config/database.js".

ERROR: getaddrinfo ENOTFOUND xxx-xxx-xxx-xx-xx.compute-1.amazonaws.com:5432
 xxx-xxx-xxx-xx-xx.compute-1.amazonaws.com:5432
:5432
```

**Comment by jpcmf** [comment]
Guys, I am really stuck here for three days and I can't solve. Any tip? Thank you.

```
backend on  master took 10s
> heroku run sequelize db:migrate
Running sequelize db:migrate on ⬢ frozen-woodland-76492... up, run.7827 (Free)

Sequelize CLI [Node: 10.17.0, CLI: 5.5.1, ORM: 5.19.7]

Loaded configuration file "src/config/database.js".

ERROR: getaddrinfo ENOTFOUND xxx-xxx-xxx-xx-xx.compute-1.amazonaws.com:5432
 xxx-xxx-xxx-xx-xx.compute-1.amazonaws.com:5432
:5432
```

**Comment by mickhansen** [comment]
@jpcmf looks like the host doesn't exist, what does your database.js look like? (remove username and password)

**Comment by jpcmf** [comment]
@mickhansen I'm still facing this error. This is the Release log
```internal/modules/cjs/loader.js:638
    throw err;
    ^
Error: Cannot find module '/app/node_modules/.bin/sequelize'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)```

**Comment by cashenvic** [comment]
I ran into a similar issue when trying to apply migration on Heroku.
`Sequelize CLI [Node: 10.22.0, CLI: 5.5.1, ORM: 5.22.3]

Loaded configuration file "config/config.json".
Using environment "production".

ERROR: Error parsing url: undefined`
I solved it by setting a `.sequelizerc` file on project root and a `url` field representing prostgre connexion url on config.json

**Comment by ruan-almeidaa** [comment]
for me, it worked:
`const Sequelize = require("sequelize");
let connection = 'string de conexão';

if (process.env.DATABASE_URL) {
    connection = new Sequelize(process.env.DATABASE_URL,{
        dialect:'postgres',
        protocol:'postgres',
        dialectOptions:{
            ssl: {
                require: true,
                rejectUnauthorized: false
            }
        }
    });
}else {
    connection = sequelize = new Sequelize('perguntaserespostas', 'postgres', 'postgres',{
        host:'localhost',
        dialect:'postgres'
    });
  }

module.exports = connection;`
