### ISSUE TITLE
Save function no work in version 3.4.1.

### ISSUE THREAD

**Issue by sinpaout** [sequelize/sequelize#4162]
I've updated to sequelize@3.4.1 at this morning.
Then my test fail with below error. I am testing with sqlite db.

here is error
```
D:\apps\node\graphed>node db/db.js
Unhandled rejection TypeError: Object.keys called on non-object
    at Function.keys (native)
    at null.<anonymous> (D:\apps\node\graphed\node_modules\sequelize\lib\instance.js:639:56)
    at tryCatcher (D:\apps\node\graphed\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (D:\apps\node\graphed\node_modules\bluebird\js\main\promise.js:503:31)
    at Promise._settlePromiseAt (D:\apps\node\graphed\node_modules\bluebird\js\main\promise.js:577:18)
    at Promise._settlePromises (D:\apps\node\graphed\node_modules\bluebird\js\main\promise.js:693:14)
    at Async._drainQueue (D:\apps\node\graphed\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (D:\apps\node\graphed\node_modules\bluebird\js\main\async.js:133:10)
    at Async.drainQueues (D:\apps\node\graphed\node_modules\bluebird\js\main\async.js:15:14)
    at process._tickCallback (node.js:419:13)
```

here is test code

``` javascript
var path = require('path');
var _s = require('underscore.string');
var APP_DIR = _s.trim(process.env.APP_DIR || __dirname);
var Models = require(path.join(APP_DIR, './models'))({env: 'test'});
var User = Models.User;

User.create({
    userName: 'bbbb'
}).then(function(newRow) {

    User.find({
        userName: 'bbbb'
    }).then(function(foundUser) {
        foundUser.userName = 'cccc';

        foundUser.save().then(function() {
            console.log('saved');
        });
    });
});
```

here is model
``` javascript
module.exports = function(sequelize, DataTypes) {
    return sequelize.define('User', {
        id: {
            autoIncrement: true,
            type: DataTypes.INTEGER,
            field: 'rowid'
        },
        userName: {
            type: DataTypes.STRING,
            field: 'name'
        }
    }, {
        freezeTableName: true,
        tableName: 'users',
        timestamps: false
    });
};
```

I've debug into `instance.js` and found that `Object.keys` function failed because `where` object is null.
[problem code][1].

  [1]: 
https://github.com/sequelize/sequelize/blob/f678009d7514b81a6f87e12b86360e9a597e3ca8/lib/instance.js#L639

**Comment by janmeier** [comment]
You need to mark the id field with `primaryKey: true`
