### ISSUE TITLE
password authentication failed for user "user"

### ISSUE THREAD

**Issue by haikyuu** [sequelize/sequelize#4165]
I can authenticate to postgres using 
```
$ psql -h localhost -U user database
Password for user user: 
psql (9.4.4, server 9.1.15)
SSL connection (protocol: TLSv1.2, cipher: DHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

database=# 
```
but using sequelize
```js
var sequelize = new Sequelize("postgres://user:user@127.0.0.1:5434/project",{});
```
I get the following error
```
{ [SequelizeConnectionError: password authentication failed for user "user"]
  name: 'SequelizeConnectionError',
  message: 'password authentication failed for user "user"',
  parent: 
   { [error: password authentication failed for user "user"]
     name: 'error',
     length: 96,
     severity: 'FATAL',
     code: '28P01',
     detail: undefined,
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'auth.c',
     line: '285',
     routine: 'auth_failed' },
  original: 
   { [error: password authentication failed for user "user"]
     name: 'error',
     length: 96,
     severity: 'FATAL',
     code: '28P01',
     detail: undefined,
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'auth.c',
     line: '285',
     routine: 'auth_failed' } }
SequelizeConnectionError: password authentication failed for user "user"
    at /home/user/workspace/playspace/project.v2/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:73:20
    at null.<anonymous> (/home/user/.npm-packages/lib/node_modules/pg/lib/client.js:171:5)
    at emit (events.js:95:17)
    at Socket.<anonymous> (/home/user/.npm-packages/lib/node_modules/pg/lib/connection.js:109:12)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:748:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:410:10)
    at emitReadable (_stream_readable.js:406:5)
    at readableAddChunk (_stream_readable.js:168:9)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:528:21)
```

**Comment by mickhansen** [comment]
Is your pg authentication settings set to md5?
I'm not sure node-pg will work with the user based one.

**Comment by haikyuu** [comment]
when i changed pg settings to md5 
```
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
```
i now get this error (after a while)
```
{ [SequelizeConnectionError: Connection lost: The server closed the connection.]
  name: 'SequelizeConnectionError',
  message: 'Connection lost: The server closed the connection.',
  parent: { [Error: Connection lost: The server closed the connection.] fatal: true, code: 'PROTOCOL_CONNECTION_LOST' },
  original: { [Error: Connection lost: The server closed the connection.] fatal: true, code: 'PROTOCOL_CONNECTION_LOST' } }
SequelizeConnectionError: Connection lost: The server closed the connection.
    at Handshake._callback (/home/lelouch/workspace/playspace/logis.v2/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:63:20)
    at Handshake.Sequence.end (/home/lelouch/workspace/playspace/logis.v2/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at /home/lelouch/workspace/playspace/logis.v2/node_modules/mysql/lib/protocol/Protocol.js:393:18
    at Array.forEach (native)
    at /home/lelouch/workspace/playspace/logis.v2/node_modules/mysql/lib/protocol/Protocol.js:392:13
    at process._tickCallback (node.js:419:13)

```

**Comment by mickhansen** [comment]
Well i'm not a postgres expert but this is not a sequelize issue persay.
See if you can connect with the basic node pg library and all and work from there.

**Comment by haikyuu** [comment]
I had to remove the port from the connection string 
postgres://user:user@127.0.0.1**~~:5434~~**/project
Thanks @mickhansen for pointing me to [node-pg](https://github.com/brianc/node-postgres), they didn't specify the port in their example :)

**Comment by jfbahamondes** [comment]
respondan bien po ch=onchatuemare ijosdelaperro
