### ISSUE TITLE
updated from 3.0.1 to 3.4.1, problems, hint needed

### ISSUE THREAD

**Issue by PavelPolyakov** [sequelize/sequelize#4172]
Hi,

I've updated the library to the latest one and met some issues.
All the relations are throwing the error.

The relation is declared in the next way:
```
	models.Application.hasMany(models.Payment, {foreignKey : 'application_id'});
	models.Application.hasOne(models.ClientData, {foreignKey : 'application_id'});
```

The error is the next:
```
TypeError: Cannot read property 'type' of undefined
    at BelongsTo.injectAttributes (/Users/pavelp/Sites/xxx/node_modules/sequelize/lib/associations/belongs-to.js:110:153)
    at null.belongsTo (/Users/pavelp/Sites/xxx/node_modules/sequelize/lib/associations/mixin.js:106:77)
    at module.exports (/Users/pavelp/Sites/xxx/app/models/models/_relations.js:17:21)
```

Could someone point me to the change which was done, and what should I adjust?
Haven't found anything in http://sequelize.readthedocs.org/en/latest/changelog/ .

If I commented out the belongsTo relation, I met the error with the hasMany:
```
TypeError: Cannot read property 'type' of undefined
    at HasMany.injectAttributes (/Users/pavelp/Sites/xxx/node_modules/sequelize/lib/associations/has-many.js:193:163)
    at Mixin.hasMany (/Users/pavelp/Sites/xxx/node_modules/sequelize/lib/associations/mixin.js:224:75)
    at module.exports (/Users/pavelp/Sites/xxx/app/models/models/_relations.js:18:21)
```

Regards,

**Comment by PavelPolyakov** [comment]
That was the correct answer, updated all the models with ```primaryKey``` everything works again.
Thank you.

Both of you are the best maintainers ever :) I'm always happy with your responses and help.

Thanks!!!

**Comment by janmeier** [comment]
@PavelPolyakov You're very welcome, thanks for the praise :)

**Comment by sarangnx** [comment]
> Have you manually defined the id fields on the models? In that case you might be missing primaryKey true
> 
> Posting your model definitions always makes it easier for us to help you :-)

In case of non-primary keys what should I do.

**Comment by sarangnx** [comment]
> > Have you manually defined the id fields on the models? In that case you might be missing primaryKey true
> > Posting your model definitions always makes it easier for us to help you :-)
> 
> In case of non-primary keys what should I do.

never mind. fixed it.
sourceKey and targetKey was swapped. :duck:
