### ISSUE TITLE
Issue with setting defaultValue on enum after 3.5.0

### ISSUE THREAD

**Issue by shiboe** [sequelize/sequelize#4196]
We have a migration that creates a table with an enum column. After 3.5.0, the migration fails with the following error:
```
== 20150608103440-create-timeline-invite: migrating =======
Unhandled rejection SequelizeValidationError: "pending" is not a valid choice in []
    at ENUM.validate (./node_modules/sequelize/lib/data-types.js:692:11)
    at Object.QueryGenerator.escape (./node_modules/sequelize/lib/dialects/postgres/query-generator.js:894:20)
    at Object.QueryGenerator.attributeToSQL (./node_modules/sequelize/lib/dialects/postgres/query-generator.js:504:40)
    at Object.QueryGenerator.attributesToSQL (./node_modules/sequelize/lib/dialects/postgres/query-generator.js:576:45)
    at ./node_modules/sequelize/lib/query-interface.js:165:40
    at tryCatcher (./node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (./node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (./node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (./node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (./node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (./node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (./node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)

```

Setting Sequelize to v3.4.1 runs fine with no errors.

For reference, the relevant bits of the model:
```
...
    },
    status: {
      type: DataTypes.ENUM('pending', 'accepted', 'cancelled', 'rejected'),
      defaultValue: 'pending'
    },
...
```
and migration:
```
...
      },
      status: {
        type: Sequelize.ENUM,
        values: ['pending', 'accepted', 'cancelled', 'rejected'],
        defaultValue: 'pending'
      },
...
```

**Comment by janmeier** [comment]
Should be fixed by https://github.com/sequelize/sequelize/pull/4186 - normalizeAttribute has been refactored to make sure type.values will always be set

**Comment by janmeier** [comment]
Works on latest master - [tests](https://github.com/sequelize/sequelize/blob/6c8802043272fdf9e20a731995ce7a54bbd14093/test/integration/query-interface.test.js#l221-L244)
