### ISSUE TITLE
Bug with include query on many to many relationship

### ISSUE THREAD

**Issue by peterjwest** [sequelize/sequelize#4222]
When you make a query on a table with a many to many relationship (i.e. belongs to many through), including the related model, using `attributes: []` causes an error.

We were using this feature to make queries based on conditions in the related model and previously this would prevent the related model from being hydrated.

Introduced between 3.0.0. and 3.1.1

Test case for the bug here:

```
sequelize.define('Cat', { name: Sequelize.STRING });
sequelize.define('Food', { title: Sequelize.STRING });
sequelize.define('CatFood', { type: Sequelize.STRING });

var db = sequelize.models;

db.Cat.belongsToMany(db.Food, { as: 'meals', foreignKey: { name: 'catId' }, through: 'CatFood' });

db.Cat.sync()
  .then(function() { return db.Food.sync(); })
  .then(function() { return db.CatFood.sync(); })
  .then(function() {
    return db.Food.create({ title: 'Miaow Mix' })
  })
  .then(function(food) {
    return db.Cat.create({ name: 'Fluffy' })
    .then(function(cat) {
      return cat.addMeal(food, { type: 'snack' });
    });
  })
  .then(function() {
    db.Cat.findAll({
      include: {
        model: db.Food,
        as: 'meals',
        attributes: []
      }
    });
  }).then(function(cats) {
    console.log(cats);
  });
```

Error is:

```
TypeError: Cannot set property 'CatFood' of undefined
    at groupJoinData (/.../node_modules/sequelize/lib/dialects/abstract/query.js:329:37)
    at AbstractQuery.handleSelectQuery (/.../node_modules/sequelize/lib/dialects/abstract/query.js:537:15)
    at Statement.<anonymous> (/.../node_modules/sequelize/lib/dialects/sqlite/query.js:93:33)
```

**Comment by janmeier** [comment]
Hmm, yeah I guess that if `include.attributes is `[]`, so should `include.through.attributes`

**Comment by markdboyd** [comment]
I'm experiencing this bug as well. And I think this bug is the same one as 5078 and 5958. Would you be able to point me towards which part of the code you think is causing the problem?
