### ISSUE TITLE
Error with pg and sequelize 'this.position >= this.source.length'

### ISSUE THREAD

**Issue by gh0st76** [sequelize/sequelize#4232]
Hi,
After Migrating from Sequelize v1.7.10 to v3.5.x, i have a little problem for inserting Arrays in postgres:
```javascript
....
....
2015-07-31T09:13:20.514Z - debug: Executing (default): INSERT INTO "recurent_time_event" ("id","week_days") VALUES (DEFAULT,ARRAY['sunday','saturday']::VARCHAR[]) RETURNING *;
2015-07-31T09:13:20.514Z - debug: Executing (default): INSERT INTO "recurent_time_event" ("id","week_days") VALUES (DEFAULT,ARRAY['sunday','monday','tuesday','wednesday','thursday','friday','saturday']::VARCHAR[]) RETURNING *;
2015-07-31T09:13:20.514Z - debug: Executing (default): INSERT INTO "recurent_time_event" ("id","week_days") VALUES (DEFAULT,ARRAY['monday','tuesday','wednesday','thursday','friday']::VARCHAR[]) RETURNING *;

/opt/unibox-core/node_modules/pg/node_modules/pg-types/node_modules/postgres-array/index.js:17
  return this.position >= this.source.length
                                     ^
TypeError: Cannot read property 'length' of undefined
    at ArrayParser.isEof (/opt/unibox-core/node_modules/pg/node_modules/pg-types/node_modules/postgres-array/index.js:17:38)
    at ArrayParser.parse (/opt/unibox-core/node_modules/pg/node_modules/pg-types/node_modules/postgres-array/index.js:53:16)
    at Object.exports.parse (/opt/unibox-core/node_modules/pg/node_modules/pg-types/node_modules/postgres-array/index.js:4:45)
    at Array.parseStringArray [as 1] (/opt/unibox-core/node_modules/pg/node_modules/pg-types/lib/textParsers.js:53:12)
    at new eval (eval at <anonymous> (/opt/unibox-core/node_modules/pg/lib/result.js:98:20), <anonymous>:4:59)
    at Result.parseRow (/opt/unibox-core/node_modules/pg/lib/result.js:61:10)
    at Query.handleDataRow (/opt/unibox-core/node_modules/pg/lib/query.js:58:26)
    at null.<anonymous> (/opt/unibox-core/node_modules/pg/lib/client.js:108:24)
    at emit (events.js:95:17)
    at Socket.<anonymous> (/opt/unibox-core/node_modules/pg/lib/connection.js:109:12)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
```

It insert the data into database but I have an error just after that, my model look like this:
```javascript
sequelize.define('recurentTimeEvent', {
		id: {
			type: DataTypes.INTEGER,
			field: 'id',
			autoIncrement: true,
			primaryKey: true
		},
		weekDays: {
			type: DataTypes.ARRAY(DataTypes.STRING),
			field: 'week_days',
			allowNull: false,
			defaultValue: [
				'sunday',
				'monday',
				'tuesday',
				'wednesday',
				'thursday',
				'friday',
				'saturday'
			]
		}
	}, {
		freezeTableName: true,
		tableName: 'recurent_time_event',
		classMethods: {
			insertData: function (days, callback) {
				this.build({
					weekDays: days
				})
					.save()
					.catch(function (e) {
						callback(e);
					})
					.then(function (res) {
						console.log(res);
						callback(null, JSON.parse(JSON.stringify(res) || 'null'));
					});
			}
		}
	});
```
and the insertion code look like this:
```javascript
databaseModel.recurentTimeEvent.insertData([ 'sunday', 'saturday' ], function (dbErrRecurentTimeEvent, dbResRecurentTimeEvent) {
		if (dbErrRecurentTimeEvent) {
			callback(dbErrRecurentTimeEvent);
			return;
		}
                
                ...
                ...
});
```

I can't tell if it's an error in my code or if it's a bug, thanks for your help.

**Comment by BridgeAR** [comment]
It's not your code and the issue is already fixed: https://github.com/brianc/node-pg-types/commit/3f7b06a9ea3b3e257cedfc7b313ebf5ea9d24e5b.

**Comment by gh0st76** [comment]
@BridgeAR thanks for the help.
