### ISSUE TITLE
Limit query does not work for n:m relations

### ISSUE THREAD

**Issue by dgurkaynak** [sequelize/sequelize#4249]
I'm using postgres dialect and sequelize 3.5.1.

I have 3 models: Article, Media and Label. Both articles and medias can have multiple labels. This is very similiar to `Tag` example in the docs. (See n:m part in http://sequelize.readthedocs.org/en/latest/docs/associations/)

My model definitions and relations:
```javascript
/**
 * Model definitions.
 */
var Article = db.define('Article', {
    id: {
        type: Sequelize.INTEGER,
        primaryKey: true,
        autoIncrement: true,
        unique: true,
        allowNull: false
    },
    title: Sequelize.STRING,
    text: Sequelize.TEXT
});

var Media = db.define('Media', {
    id: {
        type: Sequelize.INTEGER,
        primaryKey: true,
        autoIncrement: true,
        unique: true,
        allowNull: false
    },
    name: Sequelize.STRING,
    url: Sequelize.STRING
});

var Label = db.define('Label', {
    id: {
        type: Sequelize.INTEGER,
        primaryKey: true,
        autoIncrement: true,
        unique: true,
        allowNull: false
    },
    name: Sequelize.STRING
});

var ItemLabel = db.define('ItemLabel', {
    labelId: {
        type: Sequelize.INTEGER,
        primaryKey: 'itemLabelPrimaryKey'
    },
    entityType: {
        type: Sequelize.STRING,
        primaryKey: 'itemLabelPrimaryKey'
    },
    entityId: {
        type: Sequelize.INTEGER,
        primaryKey: 'itemLabelPrimaryKey',
        references: null
    }
});

/**
 * Relations
 */
 Article.belongsToMany(Label, {
     as: 'Labels',
     through: {
         model: ItemLabel,
         unique: false,
         scope: {
             entityType: 'article'
         }
     },
     foreignKey: 'entityId',
     constraints: false
 });

 Media.belongsToMany(Label, {
     as: 'Labels',
     through: {
         model: ItemLabel,
         unique: false,
         scope: {
             entityType: 'media'
         }
     },
     foreignKey: 'entityId',
     constraints: false
 });

 Label.belongsToMany(Article, {
    as: 'Articles',
    through: {
        model: ItemLabel,
        unique: false,
        scope: {
            entityType: 'article'
        }
    },
    foreignKey: 'labelId',
    constraints: false
});

 Label.belongsToMany(Media, {
    as: 'Medias',
    through: {
        model: ItemLabel,
        unique: false,
        scope: {
            entityType: 'media'
        }
    },
    foreignKey: 'labelId',
    constraints: false
});
```

I'm trying to get articles with some labels. Here is my query:
```javascript
Article
    .findAll({
        include: [
            {
                model: Label,
                as: 'Labels',
                where: {
                    id: {
                        $in: [1, 2]
                    }
                }
            }
        ],
        limit: 25
    })
    .then(function(results) {
        console.log(results);
    })
    .catch(function(err) {
        console.log('Error!');
        console.log(err.stack);
    });
```

But I get this error:
```
TypeError: Cannot read property '_isSequelizeMethod' of undefined
    at /Users/dgurkaynak/Projects/sequelize-bug/node_modules/sequelize/lib/dialects/abstract/query-generator.js:997:15
    at Array.map (native)
    at Object.QueryGenerator.selectQuery (/Users/dgurkaynak/Projects/sequelize-bug/node_modules/sequelize/lib/dialects/abstract/query-generator.js:994:55)
    at /Users/dgurkaynak/Projects/sequelize-bug/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1218:33
    at generateJoinQueries (/Users/dgurkaynak/Projects/sequelize-bug/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1259:17)
    at Object.<anonymous> (/Users/dgurkaynak/Projects/sequelize-bug/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1340:27)
    at Array.forEach (native)
    at Object.QueryGenerator.selectQuery (/Users/dgurkaynak/Projects/sequelize-bug/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1339:10)
    at QueryInterface.select (/Users/dgurkaynak/Projects/sequelize-bug/node_modules/sequelize/lib/query-interface.js:674:25)
    at null.<anonymous> (/Users/dgurkaynak/Projects/sequelize-bug/node_modules/sequelize/lib/model.js:1324:32)
    at tryCatcher (/Users/dgurkaynak/Projects/sequelize-bug/node_modules/sequelize/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/dgurkaynak/Projects/sequelize-bug/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/Users/dgurkaynak/Projects/sequelize-bug/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:577:18)
    at Async._drainQueue (/Users/dgurkaynak/Projects/sequelize-bug/node_modules/sequelize/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/dgurkaynak/Projects/sequelize-bug/node_modules/sequelize/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/dgurkaynak/Projects/sequelize-bug/node_modules/sequelize/node_modules/bluebird/js/main/async.js:15:14)
```

If I remove `limit` from the query or `where` part from `Labels` relations, everything works perfectly as expected.

**Comment by janmeier** [comment]
The `primaryKey` property should be a boolean http://docs.sequelizejs.com/en/latest/api/sequelize/#definemodelname-attributes-options-model

Changing it fixes the issue in my tests.

The join is not guaranteed to work with composite primary keys however, generally the support is not perfect

**Comment by dgurkaynak** [comment]
Thanks!
