### ISSUE TITLE
bug when try to insert integer value in string field.

### ISSUE THREAD

**Issue by sushantdhiman** [sequelize/sequelize#4255]
My `Model.js` contains a field with type `type: DataTypes.STRING(5)`.

Under Node `0.12` I can insert a integer value to this field without any issue. But under Node `0.10` it gives me error like this -

`error:  SequelizeValidationError: 2 is not a valid string
    at STRING.validate (/var/www/test/test/node_modules/sequelize/lib/data-types.js:92:11)
    at Object.QueryGenerator.escape (/var/www/test/test/node_modules/sequelize/lib/dialects/mysql/query-generator.js:363:22)
    at Object.QueryGenerator.whereItemQuery (/var/www/test/test/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2130:20)
    at /var/www/test/test/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1804:25
    at /var/www/test/test/node_modules/lodash/index.js:3073:15
    at baseForOwn (/var/www/test/test/node_modules/lodash/index.js:2046:14)
    at Function.forOwn (/var/www/test/test/node_modules/lodash/index.js:3378:16)
    at Object.QueryGenerator.whereItemsQuery (/var/www/test/test/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1803:9)
    at Object.QueryGenerator.getWhereConditions (/var/www/test/test/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2180:19)
    at Object.QueryGenerator.selectQuery (/var/www/test/test/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1393:28)
    at QueryInterface.select (/var/www/test/test/node_modules/sequelize/lib/query-interface.js:674:25)`

I am using `Sequelize 3.3.2`.

**Comment by sushantdhiman** [comment]
Additional details 

Database : `mysql`

`sequelize: ^3.3.2`
`sequelize-cli: ^1.3.0`
`mysql: ~2.5.4`

I have to convert the data to string then it will work with both Node `.12` and `.10` , It appears to be an issue with validator.

I am using the `bulkCreate` to create the records.

**Comment by promentol** [comment]
The same problem with us, need implicitly convert to string

**Comment by promentol** [comment]
But I see if we have integer field and we assign string value, it converts.

**Comment by sushantdhiman** [comment]
I am currently using this patch @promentol 

After model setup

```//Fix datatype level validation errors introduced in #3472```
```Sequelize.STRING.prototype.validate = function() { return true; };```
```Sequelize.INTEGER.prototype.validate = function() { return true; };```
```Sequelize.DECIMAL.prototype.validate = function() { return true; };```
```Sequelize.TEXT.prototype.validate = function() { return true; };```
```Sequelize.BOOLEAN.prototype.validate = function() { return true; };```

I don't know why there is no option to turn this off using some configuration. This update it breaking all Insert / Update queries.

**Comment by janmeier** [comment]
@sushantdhiman Because noone thought of implemening that, and noone commented on the PR that it would be a good idea :)

A PR with that feature would be welcomed. 
I'm going to loosen up some of the validations as well (e.g. a `'2'` should be a valid string), when I get around to it - but I'm tied up with finishing my thesis right now

**Comment by janmeier** [comment]
Merged into https://github.com/sequelize/sequelize/issues/4314
