### ISSUE TITLE
Model.findAll with includes breaks in version 3.5.x - Not unique table/alias

### ISSUE THREAD

**Issue by barmatz** [sequelize/sequelize#4285]
Forgive me if this has already been addressed.
I have been developing a project on version 3.3.x, but when I upgraded it to 3.5.x it broke.

A `findAll` query on my Transaction model that has includes returns a SQL error: `Error Code: 1066. Not unique table/alias: 'destinationAccount.currency'`.

The `findAll` call:
```
Transaction.findAll({
  where: where,
  attributes: [ 'id', 'status', 'quantity', 'createdAt', 'exchangeRate' ],
  order: [ [ 'createdAt', 'DESC' ] ],
  include: [{
    model: Account,
    as: 'sourceAccount',
    attributes: [ 'id', 'balance', 'sortCode', 'number' ],
    include: [{ 
      model: Currency,
      as: 'currency',
      attributes: [ 'id', 'code' ]
    }]
  }, {
    model: Account,
    as: 'destinationAccount',
    attributes: [ 'id', 'balance', 'sortCode', 'number' ],
    include: [{ 
      model: Currency,
      as: 'currency',
      attributes: [ 'id', 'code' ]
    }]
  }]
})
```

Relevant associations:
```
Transaction.belongsTo(Account, { foreignKey: 'sourceAccountId', as: 'sourceAccount' });
Transaction.belongsTo(Account, { foreignKey: 'destinationAccountId', as: 'destinationAccount' });
```

The query generated is different depending on the version even though the options provided to the method are the same.
In v3.3.x line 26 is
    '`Currencies` AS `sourceAccount.currency` ON `sourceAccount`.`currencyId` = `sourceAccount.currency`.`id`'
In v3.5.x line 26 is
    ``Currencies` AS `destinationAccount.currency` ON `destinationAccount`.`currencyId` = `destinationAccount.currency`.`id``

3.3.x query:
```
SELECT 
    `Transaction`.`id`,
    `Transaction`.`status`,
    `Transaction`.`quantity`,
    `Transaction`.`createdAt`,
    `Transaction`.`exchangeRate`,
    `sourceAccount`.`id` AS `sourceAccount.id`,
    `sourceAccount`.`balance` AS `sourceAccount.balance`,
    `sourceAccount`.`sortCode` AS `sourceAccount.sortCode`,
    `sourceAccount`.`number` AS `sourceAccount.number`,
    `sourceAccount.currency`.`id` AS `sourceAccount.currency.id`,
    `sourceAccount.currency`.`code` AS `sourceAccount.currency.code`,
    `destinationAccount`.`id` AS `destinationAccount.id`,
    `destinationAccount`.`balance` AS `destinationAccount.balance`,
    `destinationAccount`.`sortCode` AS `destinationAccount.sortCode`,
    `destinationAccount`.`number` AS `destinationAccount.number`,
    `destinationAccount.currency`.`id` AS `destinationAccount.currency.id`,
    `destinationAccount.currency`.`code` AS `destinationAccount.currency.code`
FROM
    `Transactions` AS `Transaction`
        LEFT OUTER JOIN
    `Accounts` AS `sourceAccount` ON `Transaction`.`sourceAccountId` = `sourceAccount`.`id`
        LEFT OUTER JOIN
    `Currencies` AS `sourceAccount.currency` ON `sourceAccount`.`currencyId` = `sourceAccount.currency`.`id`
        LEFT OUTER JOIN
    `Accounts` AS `destinationAccount` ON `Transaction`.`destinationAccountId` = `destinationAccount`.`id`
        LEFT OUTER JOIN
    `Currencies` AS `destinationAccount.currency` ON `destinationAccount`.`currencyId` = `destinationAccount.currency`.`id`
ORDER BY `Transaction`.`createdAt` DESC;
```

3.5.x query:
```
SELECT 
    `Transaction`.`id`,
    `Transaction`.`status`,
    `Transaction`.`quantity`,
    `Transaction`.`createdAt`,
    `Transaction`.`exchangeRate`,
    `Transaction`.`btcBuyRate`,
    `Transaction`.`btcSellRate`,
    `sourceAccount`.`id` AS `sourceAccount.id`,
    `sourceAccount`.`balance` AS `sourceAccount.balance`,
    `sourceAccount`.`sortCode` AS `sourceAccount.sortCode`,
    `sourceAccount`.`number` AS `sourceAccount.number`,
    `sourceAccount.currency`.`id` AS `sourceAccount.currency.id`,
    `sourceAccount.currency`.`code` AS `sourceAccount.currency.code`,
    `destinationAccount`.`id` AS `destinationAccount.id`,
    `destinationAccount`.`balance` AS `destinationAccount.balance`,
    `destinationAccount`.`sortCode` AS `destinationAccount.sortCode`,
    `destinationAccount`.`number` AS `destinationAccount.number`,
    `destinationAccount.currency`.`id` AS `destinationAccount.currency.id`,
    `destinationAccount.currency`.`code` AS `destinationAccount.currency.code`
FROM
    `Transactions` AS `Transaction`
        LEFT OUTER JOIN
    `Accounts` AS `sourceAccount` ON `Transaction`.`sourceAccountId` = `sourceAccount`.`id`
        LEFT OUTER JOIN
    `Currencies` AS `destinationAccount.currency` ON `destinationAccount`.`currencyId` = `destinationAccount.currency`.`id`
        LEFT OUTER JOIN
    `Accounts` AS `destinationAccount` ON `Transaction`.`destinationAccountId` = `destinationAccount`.`id`
        LEFT OUTER JOIN
    `Currencies` AS `destinationAccount.currency` ON `destinationAccount`.`currencyId` = `destinationAccount.currency`.`id`
ORDER BY `Transaction`.`createdAt` DESC;
```

**Comment by janmeier** [comment]
Hmm, the query looks correct for me (with destination and source account referenced correctly) on latest master. Can you test on latest master, and if the problem persist, try creating a full, self-contained testcase, with model definitions.

**Comment by newUserOfGit** [comment]
It is not a random bug. I have the same problem with long query and many includes.

**Comment by janmeier** [comment]
@newUserOfGit post a reproducible test case and I'll be happy to take a look

**Comment by newUserOfGit** [comment]
My code is: 

```javascript
.findAll({
    attributes: ['attr', 'attr', 'attr', 'attr', 'attr'],

    where: {
      $and: [{
        id: var ? {
          $lt: var,
        } : {
          $not: null, // Always true
        },

        attr: var ? var : {
          $not: null, // Always true
        },

        attr: var ? var : {
          $not: null, // Always true
        },
      }, {

        $or: [{
          attr: var,
          attr: {
            $ne: 1,
          },
        }, {
          attr: var,
          attr: var,
        }],
      }],
    },

    include: [{
      model: model,
      attributes: ['attr', 'attr', 'attr'],
    }, {
      model: MODEL,
      attributes: ['attr', 'attr', 'attr', 'attr'],

      include: [{
        model: model,
        attributes: ['attr', 'attr', 'attr', 'attr'],

        where: {
          id: var,
        },

        include:  [{
          model: model,
          as: 'modelName',
          attributes: ['attr'],
        }],

      }, {
        required: true,
        model: model,
        attributes: ['attr'],
      }],
    }],

    limit: count + 1, // Add one to detect the end
    order: [['attr', 'attr']],
  })
```

If I set a sequelize version 3.5.1 or 3.5.0, take an error:

```
SequelizeDatabaseError: column "MODEL.ATTR" does not exist
  SequelizeDatabaseError: column "MODEL.ATTR" does not exist
      at Query.formatError (node_modules/sequelize/lib/dialects/postgres/query.js:429:14)
      at null.<anonymous> (node_modules/sequelize/lib/dialects/postgres/query.js:108:19)
      at emit (events.js:107:17)
      at Query.handleError (node_modules/pg/lib/query.js:108:8)
      at null.<anonymous> (node_modules/pg/lib/client.js:171:26)
      at emit (events.js:107:17)
      at Socket.<anonymous> (node_modules/pg/lib/connection.js:109:12)
      at Socket.emit (events.js:107:17)
      at readableAddChunk (_stream_readable.js:163:16)
      at Socket.Readable.push (_stream_readable.js:126:10)
      at TCP.onread (net.js:538:20)
```

In 3.4.1 all ok.

I mark the corresponded MODEL in the JS code. ATTR is a foreign key for next include model.

**Comment by janmeier** [comment]
@newUserOfGit Please show the models and assocations as well, since they may be important to the problem

**Comment by newUserOfGit** [comment]
```javascript
sequelize.define('ModelName', {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
      allowNull: false
    },
    field1: {
      type: DataTypes.TEXT,
      allowNull: false
    },
    field2: {
      type: DataTypes.TEXT,
      allowNull: false
    },
    field3: {
      type: DataTypes.TEXT,
      allowNull: true,
    },
    field4: {
      type: DataTypes.BOOLEAN,
      defaultValue: false,
      allowNull: false,
    },
    field5: {
      type: DataTypes.BOOLEAN,
      defaultValue: false,
      allowNull: false,
    },
    field6: {
      type: DataTypes.ENUM,
      values: [...],
      allowNull: true // auto approved
    },
    field7: {
      type: DataTypes.DATE,
      allowNull: true
    },
    deletedAt: {
      type: DataTypes.DATE,
      allowNull: true
    },
  }, {
    indexes: [{
      fields: ['ForeignKeyField'],
    }],

    hooks: {
      afterCreate: 
      afterUpdate: 
      afterDestroy: 
      beforeBulkCreate: 
      beforeBulkUpdate: 
      beforeBulDestroy: 
    },

    associate: function(models) {
      models.ModelName.belongsTo(models.ModelName2);
      models.ModelName.belongsTo(models.THIS_MODEL); // INVISIBLE ASSOCIATION
      models.ModelName.belongsTo(models.ModelName3);
      models.ModelName.hasOne(models.ModelName, {
        as: 'Parent',
        foreignKey: 'ParentId',
      });
      models.ModelName.hasMany(models.ModelName4);
    },
  });
```

**Comment by janmeier** [comment]
@newUserOfGit How does that snippet relate to the one you posted before? You need to create a self-contained example with all the models, attributes, assocations and calls needed to reproduce the issue. And please make it as small as possible while still showing the error.

I realize this might seem like a PITA, but it is so much easier for me to find the bug when you give me a self-contained example that I can just copy-paste and run. See http://stackoverflow.com/help/mcve

**Comment by newUserOfGit** [comment]
In our code we have a complex primary key from the foreign keys:

```javascript

sequelize.define('Ban', {

    UserId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
    },

    AppId: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      allowNull: false,
    },

    endTime: {
      type: DataTypes.DATE,
      allowNull: true, // null for unlimited ban
    },

    reason: {
      type: DataTypes.STRING,
    },
  }, {
    indexes: [{
      fields: ['endTime'],
    }],

    associate: function(db) {
      db.Ban.belongsTo(db.User, { foreignKey: 'UserId', });
      db.Ban.belongsTo(db.App, { foreignKey: 'AppId' });
      db.Ban.belongsTo(db.User, { foreignKey: 'AdminId' });
      db.Ban.belongsTo(db.Comment);
    },
});
```

In association with User table we have:

```javascript
      models.User.hasMany(models.Ban, { foreignKey: 'UserId', });
      models.User.hasMany(models.Ban, { foreignKey: 'AdminId', });
```

Is it a correct definition? It works correctly in the 3.4.1 version.

**Comment by janmeier** [comment]
@newUserOfGit Well that looks correct to me, but there might be some issues with composite primary keys.

I still can't test this since you haven't posted a full example. There's a lot  of `attr` and `model` in the `findAll` code you posted but its not related to the models you just showed.


@barmatz Any update?

**Comment by newUserOfGit** [comment]
### Main part of a problem query:

```javascript
   embed.db.Log.findAll({

    include: [{
      model: embed.db.User,
    }, {
      model: embed.db.Comment,

      include: [{
        model: embed.db.User,
        },

        // IF I DELETE THE NEXT INCLUDE, ERROR DISAPPEARS.
        include:  [{
          model: embed.db.Ban,
          attributes: [...],
        }],

      }, 

    order: [['id', 'DESC']],
  })
```

### Associations:

Log:
```javascript
      models.Log.belongsTo(models.User, {
        foreignKey: 'AdminId',
      });
      models.Log.belongsTo(models.Comment);
```

User:
```javascript
      models.User.hasMany(models.Ban, { foreignKey: 'UserId', });
      models.User.hasMany(models.Ban, { foreignKey: 'AdminId', });
      models.User.hasMany(models.Comment);
```

Comment:
```javascript
      models.Comment.belongsTo(models.User);
      models.Comment.hasOne(models.Comment, {
        as: 'Parent',
        foreignKey: 'ParentId',
      });
      models.Comment.hasMany(models.Ban);
```

**Comment by janmeier** [comment]
@newUserOfGit Seems to work fine for me -  I assume Ban is a sub-include of User?

I'm not sure we're getting anywhere by you posting small snippets, I'm sorry. Everything I've seen so far on this issue has been working fine for me. 

If you have time, please fork the project and submit a pull request with a failing test, then we can work from there

**Comment by janmeier** [comment]
Closing, no response
