### ISSUE TITLE
Transaction has been started twice

### ISSUE THREAD

**Issue by bossqone** [sequelize/sequelize#4342]
Hello, I'm storing tweets from twitter with their authors and sometimes transaction run twice as you can see below. Problem is only with saving "owner's info" (table `FeedOwners`) - handled in `.getOwnerInfo()`, duplicity in `Feed` table is okay (different `eid`).

Thanks for every response.

```sql
Executing (630caa2b-0b52-4bdd-80dd-27d9c707a256): START TRANSACTION;
Executing (e928bd92-4407-4623-b851-2003d1222719): START TRANSACTION;
Executing (630caa2b-0b52-4bdd-80dd-27d9c707a256): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (e928bd92-4407-4623-b851-2003d1222719): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (630caa2b-0b52-4bdd-80dd-27d9c707a256): SET autocommit = 1;
Executing (e928bd92-4407-4623-b851-2003d1222719): SET autocommit = 1;
Executing (630caa2b-0b52-4bdd-80dd-27d9c707a256): SELECT `id`, `accountId`, `facebookId`, `facebookToken`, `twitterId`, `twitterToken   `, `twitterSecret`, `googleId`, `googleToken`, `eventbriteId`, `eventbriteToken`, `instagramId`, `instagramToken` FROM `AccountTokens   ` AS `AccountTokens` WHERE `AccountTokens`.`twitterId` = '24596994' LIMIT 1;
Executing (e928bd92-4407-4623-b851-2003d1222719): SELECT `id`, `accountId`, `facebookId`, `facebookToken`, `twitterId`, `twitterToken   `, `twitterSecret`, `googleId`, `googleToken`, `eventbriteId`, `eventbriteToken`, `instagramId`, `instagramToken` FROM `AccountTokens   ` AS `AccountTokens` WHERE `AccountTokens`.`twitterId` = '24596994' LIMIT 1;
Executing (630caa2b-0b52-4bdd-80dd-27d9c707a256): SAVEPOINT `630caa2b-0b52-4bdd-80dd-27d9c707a256-savepoint-1`;
Executing (e928bd92-4407-4623-b851-2003d1222719): SAVEPOINT `e928bd92-4407-4623-b851-2003d1222719-savepoint-1`;
Executing (630caa2b-0b52-4bdd-80dd-27d9c707a256): SELECT `id`, `type`, `originId`, `name`, `picture` FROM `FeedOwners` AS `FeedOwners   ` WHERE `FeedOwners`.`type` = 0 AND `FeedOwners`.`originId` = '24596994' LIMIT 1;
Executing (e928bd92-4407-4623-b851-2003d1222719): SELECT `id`, `type`, `originId`, `name`, `picture` FROM `FeedOwners` AS `FeedOwners   ` WHERE `FeedOwners`.`type` = 0 AND `FeedOwners`.`originId` = '24596994' LIMIT 1;
Executing (630caa2b-0b52-4bdd-80dd-27d9c707a256): INSERT INTO `FeedOwners` (`id`,`type`,`originId`,`name`,`picture`) VALUES (DEFAULT,   0,'24596994','JolitaBrilliant','http://pbs.twimg.com/profile_images/619310070745182209/RksZCOKb.jpg');
Executing (e928bd92-4407-4623-b851-2003d1222719): INSERT INTO `FeedOwners` (`id`,`type`,`originId`,`name`,`picture`) VALUES (DEFAULT,   0,'24596994','JolitaBrilliant','http://pbs.twimg.com/profile_images/619310070745182209/RksZCOKb.jpg');
Executing (630caa2b-0b52-4bdd-80dd-27d9c707a256): INSERT INTO `Feed` (`id`,`originId`,`aid`,`oid`,`eid`,`type`,`text`,`created`,`link   `) VALUES (DEFAULT,'633301305830809600',NULL,1142,1,0,'#test #driving #jaguar #2015 #red #thats a #test #car! #auto #sweet #smooth #s   ports #engine #damn it… https://t.co/ZlcNDYnlF1','2015-08-17 15:36:12','https://twitter.com/statuses/633301305830809600');
Executing (630caa2b-0b52-4bdd-80dd-27d9c707a256): INSERT INTO `Feed` (`id`,`originId`,`aid`,`oid`,`eid`,`type`,`text`,`created`,`link   `) VALUES (DEFAULT,'633301305830809600',NULL,1142,2,0,'#test #driving #jaguar #2015 #red #thats a #test #car! #auto #sweet #smooth #s   ports #engine #damn it… https://t.co/ZlcNDYnlF1','2015-08-17 15:36:12','https://twitter.com/statuses/633301305830809600');
Executing (630caa2b-0b52-4bdd-80dd-27d9c707a256): SELECT `Feed`.*, `FeedContents`.`id` AS `FeedContents.id`, `FeedContents`.`fid` AS    `FeedContents.fid`, `FeedContents`.`type` AS `FeedContents.type`, `FeedContents`.`content` AS `FeedContents.content`, `FeedLikes`.`id   ` AS `FeedLikes.id`, `FeedLikes`.`fid` AS `FeedLikes.fid`, `FeedLikes`.`aid` AS `FeedLikes.aid`, `FeedLikes`.`created` AS `FeedLikes.   created`, `FeedComments`.`id` AS `FeedComments.id`, `FeedComments`.`fid` AS `FeedComments.fid`, `FeedComments`.`aid` AS `FeedComments   .aid`, `FeedComments`.`text` AS `FeedComments.text`, `FeedComments`.`created` AS `FeedComments.created`, `FeedOwner`.`id` AS `FeedOwn   er.id`, `FeedOwner`.`type` AS `FeedOwner.type`, `FeedOwner`.`originId` AS `FeedOwner.originId`, `FeedOwner`.`name` AS `FeedOwner.name   `, `FeedOwner`.`picture` AS `FeedOwner.picture` FROM (SELECT `Feed`.`id`, `Feed`.`originId`, `Feed`.`aid`, `Feed`.`oid`, `Feed`.`eid`   , `Feed`.`type`, `Feed`.`text`, `Feed`.`created`, `Feed`.`link` FROM `Feed` AS `Feed` WHERE `Feed`.`eid` = 1 AND `Feed`.`type` = 0 AN   D `Feed`.`originId` = '633301305830809600' LIMIT 1) AS `Feed` LEFT OUTER JOIN `FeedContent` AS `FeedContents` ON `Feed`.`id` = `FeedC   ontents`.`fid` LEFT OUTER JOIN `FeedLikes` AS `FeedLikes` ON `Feed`.`id` = `FeedLikes`.`fid` LEFT OUTER JOIN `FeedComments` AS `FeedC   omments` ON `Feed`.`id` = `FeedComments`.`fid` LEFT OUTER JOIN `FeedOwners` AS `FeedOwner` ON `Feed`.`oid` = `FeedOwner`.`id`;
Executing (630caa2b-0b52-4bdd-80dd-27d9c707a256): SELECT `Feed`.*, `FeedContents`.`id` AS `FeedContents.id`, `FeedContents`.`fid` AS    `FeedContents.fid`, `FeedContents`.`type` AS `FeedContents.type`, `FeedContents`.`content` AS `FeedContents.content`, `FeedLikes`.`id   ` AS `FeedLikes.id`, `FeedLikes`.`fid` AS `FeedLikes.fid`, `FeedLikes`.`aid` AS `FeedLikes.aid`, `FeedLikes`.`created` AS `FeedLikes.   created`, `FeedComments`.`id` AS `FeedComments.id`, `FeedComments`.`fid` AS `FeedComments.fid`, `FeedComments`.`aid` AS `FeedComments   .aid`, `FeedComments`.`text` AS `FeedComments.text`, `FeedComments`.`created` AS `FeedComments.created`, `FeedOwner`.`id` AS `FeedOwn   er.id`, `FeedOwner`.`type` AS `FeedOwner.type`, `FeedOwner`.`originId` AS `FeedOwner.originId`, `FeedOwner`.`name` AS `FeedOwner.name   `, `FeedOwner`.`picture` AS `FeedOwner.picture` FROM (SELECT `Feed`.`id`, `Feed`.`originId`, `Feed`.`aid`, `Feed`.`oid`, `Feed`.`eid`   , `Feed`.`type`, `Feed`.`text`, `Feed`.`created`, `Feed`.`link` FROM `Feed` AS `Feed` WHERE `Feed`.`eid` = 2 AND `Feed`.`type` = 0 AN   D `Feed`.`originId` = '633301305830809600' LIMIT 1) AS `Feed` LEFT OUTER JOIN `FeedContent` AS `FeedContents` ON `Feed`.`id` = `FeedC   ontents`.`fid` LEFT OUTER JOIN `FeedLikes` AS `FeedLikes` ON `Feed`.`id` = `FeedLikes`.`fid` LEFT OUTER JOIN `FeedComments` AS `FeedC   omments` ON `Feed`.`id` = `FeedComments`.`fid` LEFT OUTER JOIN `FeedOwners` AS `FeedOwner` ON `Feed`.`oid` = `FeedOwner`.`id`;
Executing (630caa2b-0b52-4bdd-80dd-27d9c707a256): COMMIT;
Executing (e928bd92-4407-4623-b851-2003d1222719): SELECT `id`, `type`, `originId`, `name`, `picture` FROM `FeedOwners` AS `FeedOwners   ` WHERE `FeedOwners`.`type` = 0 AND `FeedOwners`.`originId` = '24596994' LIMIT 1;
Executing (e928bd92-4407-4623-b851-2003d1222719): ROLLBACK;
Unhandled rejection SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/opt/pribe/node_modules/sequelize/lib/dialects/mysql/query.js:134:14)
    at Query._callback (/opt/pribe/node_modules/sequelize/lib/dialects/mysql/query.js:35:21)
    at Query.Sequence.end (/opt/pribe/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query.ErrorPacket (/opt/pribe/node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
    at Protocol._parsePacket (/opt/pribe/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/opt/pribe/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/opt/pribe/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/opt/pribe/node_modules/mysql/lib/Connection.js:96:28)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

Code block with .transaction:
```js
return this.db.Sequelize.transaction(function (transaction) {
    return _this.getOwnerInfo(tweet.user, transaction).then(function (ownerInfo) {
        return Promise.all(_this.subscribers[tag].map(function (eventId) {
            return _this.handleTweetPerEvent(eventId, tag, tweet, ownerInfo, transaction);
        }));
    });
});
```

Code block with .getOwnerInfo():
```js
Twitter.prototype.getOwnerInfo = function (owner, transaction) {
    var _this = this;

    return this.db.AccountTokens.findOne({
        where: {
            twitterId: owner.id_str
        },
        raw: true,
        transaction: transaction
    }).then(function (tokens) {
        if (!tokens) {
            return _this.db.FeedOwners.findOrCreate({
                where: {
                    type: _this.config.feedEnum.twitter,
                    originId: owner.id_str
                },
                defaults: {
                    name: owner.name,
                    picture: owner.profile_image_url.replace('_normal', '')
                },
                transaction: transaction
            }).spread(function (ownerObj, created) {
                return {
                    accountId: null,
                    ownerId: ownerObj.id
                }
            });
        }

        return {
            accountId: tokens.accountId,
            ownerId: null
        };
    });
};
```

**Comment by janmeier** [comment]
`findOrCreate` will create a its own transaction if none is passed - are you sure the transaction is being passed correctly?

I can't seem to replicate the issue with the code you posted

**Comment by bossqone** [comment]
I'm using exactly same code as above. Most of time it works great, but sometimes it just fails.

**Comment by janmeier** [comment]
I've run the code a couple of times, but it works fine for me. Without a reliable test case its hard for me to debug this further. 

Can you try to see if the transaction is pased properly when it fails?

**Comment by bossqone** [comment]
I've added `console.log(transaction.id)` right after `Sequelize.transaction()` and into `getOwnerInfo()`. I hope it will fail as soon as possible, because yesterday it did just 2 times (~450 transactions).

**Comment by bossqone** [comment]
Ouch, finally found it. It's not a problem with Sequelize, it's my fault. Code with transaction run twice, because tweet has multiple identical hashtags (e.g. ```#test #test```).

Thanks for your help.
