### ISSUE TITLE
Issue using with Postgres 9.3beta2

### ISSUE THREAD

**Issue by bringking** [sequelize/sequelize#4368]
I am receiving the following error when I try and sync the models--

```
Unhandled rejection TypeError: Invalid Version: 9.3beta2
    at new SemVer (/Users/charlesking/insights-admin/node_modules/sequelize/node_modules/semver/semver.js:293:11)
    at compare (/Users/charlesking/insights-admin/node_modules/sequelize/node_modules/semver/semver.js:569:10)
    at Function.gte (/Users/charlesking/insights-admin/node_modules/sequelize/node_modules/semver/semver.js:618:10)
    at /Users/charlesking/insights-admin/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:101:64
    at Object.tapHandler (/Users/charlesking/insights-admin/node_modules/sequelize/node_modules/bluebird/js/main/finally.js:64:23)
    at Object.tryCatcher (/Users/charlesking/insights-admin/node_modules/sequelize/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/charlesking/insights-admin/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/Users/charlesking/insights-admin/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/Users/charlesking/insights-admin/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/Users/charlesking/insights-admin/node_modules/sequelize/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/charlesking/insights-admin/node_modules/sequelize/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/charlesking/insights-admin/node_modules/sequelize/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)

```

**Comment by mickhansen** [comment]
@janmeier semver would expect `-beta2` in this case, we probably can't expect semver to be able to handle all database versions.

**Comment by mickhansen** [comment]
In cases where we can't detect the version we should probably silently fail and just set null.

**Comment by janmeier** [comment]
Hmm, but which version should we asume the user has if the semver check fails?

Perhaps we should do an `if semver.valid` check [here](https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/connection-manager.js#L199), and throw an error telling users to set `databaseVersion` manually if that fails?

**Comment by mickhansen** [comment]
@janmeier latest version, currently that'd be 9.2
I don't like the idea of forcing people to maintain a databaseVersion if they don't really care.
