### ISSUE TITLE
Getting Unhandled rejection when validating isEmail with ES7 async functions and class methods.

### ISSUE THREAD

**Issue by kevin-wolf** [sequelize/sequelize#4370]
Hello guys, I am having an `Unhandled rejection` when running my tests trying to call a class methods which creates a new register using an invalid email.

This is the model code:

```javascript
import { encrypt } from '../utils/crypto';

function encryptPassword (customer) {
  customer.PwdHash = encrypt(customer.PwdHash);
}

export default (sequelize, DataTypes) => {
  const Customer = sequelize.define('Customer', {
    CustomerId : {
      type          : DataTypes.INTEGER,
      primaryKey    : true,
      autoIncrement : true,
    },
    Login : {
      type     : DataTypes.STRING,
      validate : {
        isEmail : {
          msg : 'The Login is not a valid email',
        },
      },
    },
    PwdHash : {
      type : DataTypes.STRING,
    },
    ChatAlias : {
      type : DataTypes.STRING,
    },
    LanguageId : {
      type : DataTypes.INTEGER,
    },
    SiteId : {
      type : DataTypes.INTEGER,
    },
    AgentId : {
      type : DataTypes.INTEGER,
    },
    PartnerId : {
      type : DataTypes.INTEGER,
    },
    CreditTypeId : {
      type : DataTypes.INTEGER,
    },
    StatusId : {
      type : DataTypes.INTEGER,
    },
  }, {
    tableName    : 'Customer',
    createdAt    : 'Created_Date',
    updatedAt    : 'Updated_Date',
    classMethods : {
      associate (models) {
        Customer.hasMany(models.CustomerLogin, { foreignKey : 'CustomerId' });
        Customer.hasOne(models.CustomerAccount, { foreignKey : 'CustomerId' });
      },
      async processLogin (body) {
        const customerBody = {
          Login        : body.Login,
          PwdHash      : body.PwdHash,
          ChatAlias    : body.ChatAlias,
          LanguageId   : body.LanguageId,
          SiteId       : body.SiteId,
          AgentId      : body.AgentId,
          PartnerId    : body.PartnerId,
          CreditTypeId : body.CreditTypeId,
          StatusId     : body.StatusId,
        };

        const accountBody = {
          Balance : parseFloat(body.Balance),
        };

        let customer = await Customer.findOne({ where : { Login : customerBody.Login }});
        if (customer) {
          const customerAccount = await customer.getCustomerAccount();
          await customerAccount.update(accountBody);
        } else {
          customer = await Customer.create(customerBody);
          await customer.createCustomerAccount(accountBody);
        }

        return encrypt(`${encrypt('CUSTOMER')}|${encrypt(customerBody.Login)}|${encrypt(customerBody.PwdHash)}`);
      },
    },
  });

  // Encrypt password before saving to the DB.
  Customer.beforeCreate(encryptPassword);
  Customer.beforeUpdate(encryptPassword);

  return Customer;
};
```

Controller file:

```javascript
export default async (req, res) => {
  try {
    res.json({ token : await Customer.processLogin(req.body) });
  } catch (err) {
    const message = {
      Login : err.errors.map(error => error.message),
    };
    res.status(400).json({ error : 'ValidationFailed', message : message });
  }
};
```

Test file:

```javascript
it('Should return ValidationFailed when the Login is not a valid email', async () => {
  try {
    await request(app).post('/api/customers').send(Object.assign({}, body, { Login : 'invalidMail' }));
  } catch (err) {
    err.status.should.equal(400);
    err.response.body.error.should.equal('ValidationFailed');
    err.response.body.message.should.have.keys('Login');
    err.response.body.message.Login.should.containEql('The Login is not a valid email');
  }
});
```

And this is the error received:

```
Unhandled rejection SequelizeValidationError: Validation error: The Login is not a valid email
    at /home/kevinwolf/projects/server/api/node_modules/sequelize/lib/instance-validator.js:72:14
    at tryCatcher (/home/kevinwolf/projects/server/api/node_modules/sequelize/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/kevinwolf/projects/server/api/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/home/kevinwolf/projects/server/api/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/home/kevinwolf/projects/server/api/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/home/kevinwolf/projects/server/api/node_modules/sequelize/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/kevinwolf/projects/server/api/node_modules/sequelize/node_modules/bluebird/js/main/async.js:133:10)
    at Async.drainQueues (/home/kevinwolf/projects/server/api/node_modules/sequelize/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:415:13)
```

**Comment by mickhansen** [comment]
Not sure we can help you here. Unhandled rejections are because the promise chain never had a error or catch callback attached to it, i'm not aware how ES7/Babel handle promise errors internally.

**Comment by janmeier** [comment]
No response, closing
