### ISSUE TITLE
SequelizeValidationError: "046416" is not a valid integer

### ISSUE THREAD

**Issue by pinoyyid** [sequelize/sequelize#4394]
I'm getting the error/stack trace below. The scenario is:-
 * This is running my unit tests which reset the database to a know position and then run my suite of tests
 * The error is intermittent. Just to emphasise, the database always starts in the same state and I run the same test suite.
 * The stack trace doesn't seem to refer to any of my code
 * At no point in my code do I assign 046416 to any int variables. The number 046416 changes from run to run, but is always 6 digits.
 * afaik, 046416 is a valid integer

At the very least I'd like to catch this exception, but given it's not being thrown by my code, I'm not sure what I need to wrap in try/catch.

Unhandled rejection SequelizeValidationError: "046416" is not a valid integer
   at INTEGER.validate (/shared2/eclipse_workspaces/GITREPOS/sendit/sas/node_modules/sequelize/lib/data-types.js:233:11)
   at Object.QueryGenerator.escape (/shared2/eclipse_workspaces/GITREPOS/sendit/sas/node_modules/sequelize/lib/dialects/postgres/query-generator.js:894:20)
   at Object.QueryGenerator.updateQuery (/shared2/eclipse_workspaces/GITREPOS/sendit/sas/node_modules/sequelize/lib/dialects/abstract/query-generator.js:414:58)
   at QueryInterface.update (/shared2/eclipse_workspaces/GITREPOS/sendit/sas/node_modules/sequelize/lib/query-interface.js:586:33)
   at null.<anonymous> (/shared2/eclipse_workspaces/GITREPOS/sendit/sas/node_modules/sequelize/lib/instance.js:651:56)
   at tryCatcher (/shared2/eclipse_workspaces/GITREPOS/sendit/sas/node_modules/sequelize/node_modules/bluebird/js/main/util.js:26:23)
   at Promise._settlePromiseFromHandler (/shared2/eclipse_workspaces/GITREPOS/sendit/sas/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:503:31)
   at Promise._settlePromiseAt (/shared2/eclipse_workspaces/GITREPOS/sendit/sas/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:577:18)
   at Promise._settlePromises (/shared2/eclipse_workspaces/GITREPOS/sendit/sas/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:693:14)
   at Async._drainQueue (/shared2/eclipse_workspaces/GITREPOS/sendit/sas/node_modules/sequelize/node_modules/bluebird/js/main/async.js:123:16)
   at Async._drainQueues (/shared2/eclipse_workspaces/GITREPOS/sendit/sas/node_modules/sequelize/node_modules/bluebird/js/main/async.js:133:10)
   at Immediate.Async.drainQueues [as _onImmediate] (/shared2/eclipse_workspaces/GITREPOS/sendit/sas/node_modules/sequelize/node_modules/bluebird/js/main/async.js:15:14)
   at processImmediate [as _immediateCallback] (timers.js:367:17)

**Comment by janmeier** [comment]
See https://github.com/sequelize/sequelize/issues/4314

**Comment by pinoyyid** [comment]
Thanks for the link, but I'm more interested in why this exception is intermittent and how do I catch it. Relaxing the validation as described in #4314 may well prevent the exception, but I'm still left with the concern that there is an intermittent scenario that I can't catch.

**Comment by janmeier** [comment]
Without more information or a way to recreate the issue we can't really say more about why you're getting this number. We know even less about what's happening in your code than you :)

Perhaps try cutting down the test suite to the smallest sample that still reproduces the error, then we can look at it

**Comment by pinoyyid** [comment]
The error isn't coming from my code (see stack trace), and the error is
intermittent.

**Comment by janmeier** [comment]
I know, but the error is caused by code you wrote - so something you are doing must be indirectly triggering it. I've never seen or heard about something like that before, so I have no idea where it could be coming from.

Don't get me wrong - I'm not saying you're doing something wrong :). I'm just saying that with the amount of information I have right now, I cannot say what's going on

**Comment by pinoyyid** [comment]
sure. If I could isolate the code, or if the error was repeatable, I would
be more than happy to do so.

Looking at the stack trace, can you suggest what I should wrap in try/catch
?

**Comment by janmeier** [comment]
The line (instance:651) is inside `.save` so anything that updates or creates instances. 

You could also try calling `require('bluebird').longStackTraces()` before requiring sequelize, perhaps that will give you more information
