### ISSUE TITLE
Deleting instance using different column name and field name causes issue on Postgres

### ISSUE THREAD

**Issue by mikealeonetti** [sequelize/sequelize#4398]
My model:
```javascript
var schedule = sequelize.define( 'schedule', {
	'id': {
		type: Sequelize.BIGINT.UNSIGNED,
		field: 'schedule_id',
		autoIncrement: true,
		primaryKey: true
	},
	'receiverID': {
		type: Sequelize.BIGINT.UNSIGNED,
		field: 'receiver_id',
		allowNull: false
	},
	'recordingID': {
		type: Sequelize.BIGINT.UNSIGNED,
		field: 'recording_id',
		allowNull: false
	},
	'minute' : {
		type:  Sequelize.STRING( 32 ),
		field: 'minute',
		allowNull: true
	},
	'hour' : {
		type:  Sequelize.STRING( 32 ),
		field: 'hour',
		allowNull: true
	},
	'day' : {
		type:  Sequelize.STRING( 32 ),
		field: 'day',
		allowNull: true
	},
	'month' : {
		type:  Sequelize.STRING( 32 ),
		field: 'month',
		allowNull: true
	},
	'wday' : {
		type:  Sequelize.STRING( 32 ),
		field: 'wday',
		allowNull: true
	},
	'time' : {
		type:  Sequelize.DATE,
		field: 'time',
		allowNull: true
	},
	'deleteAfter' : {
		type:  Sequelize.BOOLEAN,
		field: 'delete_after',
		defaultValue: true
	},
	'playCount' : {
		type: Sequelize.BIGINT.UNSIGNED,
		field: 'play_count',
		allowNull: false,
		defaultValue: 0
	}
}, {
	'createdAt' : 'created',
	'updatedAt' : 'modified',
	'tableName' : 'schedules',
	'underscored' : true
} );
```
Deleting code:
```javascript
	db.schedule.find( {
		'where' : {
			'id' : params.scheduleID,
			'receiverID' : this.receiverID
		}
	} )
	.then( function( schedule ) {
			schedule.destroy()
			.error( function( error ) {
				log.client.error( "[%s] Speak error deleting finished schedule.",
					that.remoteAddress,
					params,
					error
				);
			} );
	} )
	.error( function( error ) {
		log.client.error( "[%s] Speak error finding schedule to increment.",
			that.remoteAddress,
			params,
			error
		);
	} );
```
The error:
```
info: Executing (default): DELETE FROM "schedules" WHERE "id" IN (SELECT "id" FROM "schedules" WHERE "schedule_id" = '1' LIMIT 1)
error: [127.0.0.1] Speak error deleting finished schedule. { action: 'runTask',
  scheduleID: 1,
  command: 'report',
  seq: 3,
  _sendMessage: [Function],
  _sendData: [Function] } SequelizeDatabaseError: column "id" does not exist
    at module.exports.Query.formatError (/home/mike/dev/node/soundwave/node_modules/sequelize/lib/dialects/postgres/query.js:421:16)
    at null.<anonymous> (/home/mike/dev/node/soundwave/node_modules/sequelize/lib/dialects/postgres/query.js:105:21)
    at emit (events.js:95:17)
    at Query.handleError (/home/mike/dev/node/soundwave/node_modules/pg/lib/query.js:99:8)
    at null.<anonymous> (/home/mike/dev/node/soundwave/node_modules/pg/lib/client.js:166:26)
    at emit (events.js:95:17)
    at Socket.<anonymous> (/home/mike/dev/node/soundwave/node_modules/pg/lib/connection.js:109:12)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:528:21)
```

Looks like it doesn't like that I am using "id" but the column is actually "schedule_id".

**Comment by janmeier** [comment]
`DELETE FROM "schedules" WHERE "schedule_id" IN (SELECT "schedule_id" FROM "schedules" WHERE "schedule_id" = '12' LIMIT 1)` is what I get

Can you  test on latest master?

**Comment by janmeier** [comment]
Closing, no response
