### ISSUE TITLE
Don't call catch when upsert fails

### ISSUE THREAD

**Issue by fabriciocs** [sequelize/sequelize#4435]
I have an express application, and the method below.
```javascript
router.post('/', app.checkAuthentication, function(req, res, next) {
        service.save(req.body)
            .then(function(result){
                   res.json(result);
            }).catch(function (err) {
                throw err;
            })
    });

```

In my service the method save is

```javascript
 save: function (grupoPermissao) {
            return model.Sequelize().transaction(function (t) {
                return model.upsert(grupoPermissao, {transaction: t});
            });
        },
````

when some validation fails, i have in console:

```javascript
Executing (427fae74-8395-43b9-844a-fb5d7b24c76c): START TRANSACTION;
Executing (427fae74-8395-43b9-844a-fb5d7b24c76c): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (427fae74-8395-43b9-844a-fb5d7b24c76c): SET autocommit = 1;
Executing (427fae74-8395-43b9-844a-fb5d7b24c76c): ROLLBACK;
Unhandled rejection SequelizeValidationError: notNull Violation: grp_nome cannot be null
    at D:\PhD\Projetos\Gerenciamento de Risco\gr-admin\node_modules\sequelize\lib\instance-validator.js:72:14
    at tryCatcher (D:\PhD\Projetos\Gerenciamento de Risco\gr-admin\node_modules\sequelize\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (D:\PhD\Projetos\Gerenciamento de Risco\gr-admin\node_modules\sequelize\node_modules\bluebird\js\main\promise.js:503:31)
    at Promise._settlePromiseAt (D:\PhD\Projetos\Gerenciamento de Risco\gr-admin\node_modules\sequelize\node_modules\bluebird\js\main\promise.js:577:18)
    at Promise._settlePromiseAtPostResolution (D:\PhD\Projetos\Gerenciamento de Risco\gr-admin\node_modules\sequelize\node_modules\bluebird\js\main\promise.js:244:10)
    at Async._drainQueue (D:\PhD\Projetos\Gerenciamento de Risco\gr-admin\node_modules\sequelize\node_modules\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (D:\PhD\Projetos\Gerenciamento de Risco\gr-admin\node_modules\sequelize\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\PhD\Projetos\Gerenciamento de Risco\gr-admin\node_modules\sequelize\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

but, the catch block in my express route, is never called.

How can i solve this?

**Comment by mickhansen** [comment]
It's likely the code in your router that's triggering it, bluebird expects ALL errors to be handled by a catch/error callback, not rethrowed.

**Comment by fabriciocs** [comment]
thank you, i changed to 
```javascript
 service.save(req.body)
            .then(function(result){
                res.json(result);
            }).catch(function (err) {
                next(err);
            })
```

And it works.
