### ISSUE TITLE
TypeError: Cannot assign to read only property 'isDefined' of [object Object] when requiring sequelize

### ISSUE THREAD

**Issue by tolgaek** [sequelize/sequelize#4504]
This is happening when requiring sequelize. I'm using node v0.10.29 and latest sequelize v3.8.0
```
/Users/tekmen/projects/muzooka/api/node_modules/sequelize/lib/sequelize.js:581
Sequelize.prototype.isDefined = function(modelName) {
                              ^
TypeError: Cannot assign to read only property 'isDefined' of [object Object]
    at Object.<anonymous> (/Users/tekmen/projects/muzooka/api/node_modules/sequelize/lib/sequelize.js:581:31)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/tekmen/projects/muzooka/api/node_modules/sequelize/index.js:5:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/tekmen/projects/muzooka/api/app/models/index.js:15:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/tekmen/projects/muzooka/api/server.js:133:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by janmeier** [comment]
Never heard about that - do you have some other library which modifies `Object.prototype` to protect an `isDefined` function?

**Comment by tolgaek** [comment]
@janmeier Yeah just noticed the same thing!,= Our legacy code has a `isDefined` defined on Object.prototype
