### ISSUE TITLE
Create/Save ignoreDuplicates Option

### ISSUE THREAD

**Issue by bookercodes** [sequelize/sequelize#4513]
[`bulkCreate`](https://sequelize.readthedocs.org/en/latest/api/model/#bulkcreaterecords-options-promisearrayinstance) got an `ignoreDuplicates` option based on [this](https://github.com/sequelize/sequelize/issues/1311) issue.

I can see there is no `ignoreDuplicates` option for [`create`](https://sequelize.readthedocs.org/en/latest/api/model/#createvalues-options-promiseinstance) or [`save`](https://sequelize.readthedocs.org/en/latest/api/instance/#saveoptions-promisethiserrorsvalidationerror) but is there a way to [`INSERT IGNORE`](https://dev.mysql.com/doc/refman/5.5/en/insert.html) when inserting one row?

**Use Case:**

I am in the process of refactoring [Community Casts]() to use sequelize. 

I want to port [this](https://github.com/alexbooker/communitycasts.co/blob/59a00a73fb44b842ae4162ae27d539d147bde317/source/server/controllers/screencastsController.js#L49) line of code:

``` javascript
return connection.queryAsync('INSERT IGNORE INTO tags VALUES ?', values);
```

Here is a an example:

``` javascript
var Tag = sequelize.define('Tag', {
  name: {
    type: Sequelize.STRING,
    primaryKey: true
  }
});

sequelize.sync({ force: true }).then(function () {
  Tag.create({
    name: 'Hello'
  }).then(function () {
    // boom!
    Tag.create({
      name: 'Hello'
    });
  });
});

```

And the exception:

```
Executing (default): INSERT INTO `Tags` (`name`,`updatedAt`,`createdAt`) VALUES ('Hello','2015-09-15 08:51:44','2015-09-15 08:51:44');
Unhandled rejection SequelizeUniqueConstraintError: Validation error
    at Query.formatError (c:\Users\alexb\Documents\Code\demo\node_modules\sequelize\lib\dialects\mysql\query.js:134:14)
    at Query._callback (c:\Users\alexb\Documents\Code\demo\node_modules\sequelize\lib\dialects\mysql\query.js:35:21)
    at Query.Sequence.end (c:\Users\alexb\Documents\Code\demo\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query.ErrorPacket (c:\Users\alexb\Documents\Code\demo\node_modules\mysql\lib\protocol\sequences\Query.js:94:8)
    at Protocol._parsePacket (c:\Users\alexb\Documents\Code\demo\node_modules\mysql\lib\protocol\Protocol.js:274:23)
    at Parser.write (c:\Users\alexb\Documents\Code\demo\node_modules\mysql\lib\protocol\Parser.js:77:12)
    at Protocol.write (c:\Users\alexb\Documents\Code\demo\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (c:\Users\alexb\Documents\Code\demo\node_modules\mysql\lib\Connection.js:96:28)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

Ideally I would be able to use the nested syntax:

``` javascript
Screencast.create({
  id: '123',
  title: 'Sequelize video.',
  Tags: [{ name:'Sequelize' }, { name:'Node' }]
}, {
  include: [Tag]
}
```

**Comment by mickhansen** [comment]
Regular create might not support insert duplicate at the moment. Probably a little bit of work to make it happen since we rely on the auto incremented foreign key being returned and what not.

**Comment by alexbooker** [comment]
@mickhansen Ah. I thought that might be the case. Can you please suggest a work around to use in the mean time?

**Comment by mickhansen** [comment]
@alexbooker Can't think of any that would work with nested create.

**Comment by alexbooker** [comment]
@mickhansen Yeah. I kind of figured I wouldn't be able to do this with nested create. What about with a normal `create` inside a transaction?

**Comment by mickhansen** [comment]
@alexbooker should be possible, you could then just ignore a unique constraint error with `.catch(Sequelize.UniqueConstraintError, noop)`

**Comment by adams-family** [comment]
+1

I would be very happy to see the `ignoreDuplicates` option for a single create if anyone finds a solution.

**Comment by Mouradif** [comment]
+1 Would be pretty useful and doesn't feel like a ton of work to add. The only workaround for now is to use raw SQL when I need it
