### ISSUE TITLE
Error: <Table> is not associated to <Table>!

### ISSUE THREAD

**Issue by alexbooker** [sequelize/sequelize#4514]
Hello,

I am trying to emulate [this](https://github.com/alexbooker/communitycasts.co/blob/59a00a73fb44b842ae4162ae27d539d147bde317/source/server/controllers/tagsController.js#L9) query:

```javascript
var sql = squel.select()
  .from('tags')
  .field('tags.tagName')
  .field('count(*) as count')
  .join('screencastTags', null, 'screencastTags.tagName = tags.tagName')
  .join('screencasts', null, 'screencasts.screencastId = screencastTags.screencastId')
  .where('screencasts.approved = 1')
  .group('tags.tagName')
  .order('count', false)
  .limit(20)
  .toString();
connection.queryAsync(sql).spread(function(tags) {
})
```

Here is what I tried in Sequelize:

```javascript
models.ScreencastTag.findAll({
  group: ['tagName'],
  attributes: ['tagName', [Sequelize.fn('count', 'tagName'), 'count']],
  limit: 20,
  include: [{
    model: models.Screencast,
    where: { approved: true }
  }]
}).then(function (tags) {
  res.json({tags: tags});
});
```

But I get this error:

```
Unhandled rejection Error: Screencast is not associated to ScreencastTag!
    at validateIncludedElement (c:\Users\alexb\Documents\Code\communitycasts.co\source\server\node_modules\sequelize\lib\model.js:559:11)
    at c:\Users\alexb\Documents\Code\communitycasts.co\source\server\node_modules\sequelize\lib\model.js:445:29
    at Array.map (native)
    at validateIncludedElements (c:\Users\alexb\Documents\Code\communitycasts.co\source\server\node_modules\sequelize\lib\model.js:441:37)
    at null.<anonymous> (c:\Users\alexb\Documents\Code\communitycasts.co\source\server\node_modules\sequelize\lib\model.js:1315:34)
    at tryCatcher (c:\Users\alexb\Documents\Code\communitycasts.co\source\server\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (c:\Users\alexb\Documents\Code\communitycasts.co\source\server\node_modules\bluebird\js\main\promise.js:503:31)
    at Promise._settlePromiseAt (c:\Users\alexb\Documents\Code\communitycasts.co\source\server\node_modules\bluebird\js\main\promise.js:577:18)
    at Async._drainQueue (c:\Users\alexb\Documents\Code\communitycasts.co\source\server\node_modules\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (c:\Users\alexb\Documents\Code\communitycasts.co\source\server\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (c:\Users\alexb\Documents\Code\communitycasts.co\source\server\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

Am I doing something wrong or is this a bug?

-------------

Here are my model definitions:

#### `screencastTag.js`

```javascript
'use strict';
module.exports = function(sequelize, DataTypes) {
  var ScreencastTag = sequelize.define('ScreencastTag', {
    screencastId: {
      type: DataTypes.STRING,
      primaryKey: true
    },
    tagName: {
      type: DataTypes.STRING,
      primaryKey: true
    }
  }, {
    timestamps: false
  });
  return ScreencastTag;
};
```

#### `tag.js`

```javascript
'use strict';

module.exports = function(sequelize, DataTypes) {
  var Tag = sequelize.define('Tag', {
    tagName: {
      type: DataTypes.STRING,
      primaryKey: true
    }
  }, {
    timestamps: false,
    classMethods: {
      associate: function (models) {
        Tag.belongsToMany(models.Screencast, { through: models.ScreencastTag });
      }
    }
  });
  return Tag;
};
```
#### `screencast.js`

```javascript
'use strict';
module.exports = function(sequelize, DataTypes) {
  var Screencast = sequelize.define('Screencast', {
    screencastId: {
      type: DataTypes.STRING,
      primaryKey: true
    },
    title: {
      type: DataTypes.STRING,
    },
    durationInSeconds: {
      type: DataTypes.INTEGER(11),
    },
    description: {
      type: DataTypes.STRING,
    },
    submissionDate: {
      type: DataTypes.DATE,
    },
    referralCount: {
      type: DataTypes.INTEGER(11),
    },
    channelId: {
      type: DataTypes.STRING,
    },
    approved: {
      type: DataTypes.BOOLEAN,
    },
    featured: {
      type: DataTypes.BOOLEAN,
    }
  }, {
    timestamps: false,
    classMethods: {
      associate: function (models) {
        Screencast.belongsToMany(models.Tag, {through: models.ScreencastTag});
      }
    }
  });
  return Screencast;
};
```

#### `index.js`

```javascript
'use strict';

var config = require('config');
var fs = require('fs');
var path = require('path');
var Sequelize = require('sequelize');

var db = { };
var sequelize = new Sequelize('demo', 'root', config.databasePassword, {
  host: 'localhost'
});

fs.readdirSync(__dirname)
  .filter(function(file) {
    return (file.indexOf('.') !== 0) && (file !== 'index.js');
  })
  .forEach(function(file) {
    var model = sequelize.import(path.join(__dirname, file));
    db[model.name] = model;
  });

Object.keys(db).forEach(function(modelName) {
  if ('associate' in db[modelName]) {
    db[modelName].associate(db);
  }
});

db.sequelize = sequelize;
db.Sequelize = Sequelize;
sequelize.sync({force: true});
module.exports = db;
```

Thank you.

**Comment by mickhansen** [comment]
`belongsToMany` does not setup public associatons between the through model and the source/target models. You'll have to do extra associations to and from the through model aswlel.

**Comment by alexbooker** [comment]
@mickhansen What should I use instead then...? Thanks.

**Comment by mickhansen** [comment]
For this specific query you'll want `ScreencastTag.belongsTo(Screencast)`. You can still keep your `belongsToMany` associations.

**Comment by alexbooker** [comment]
Thanks @mickhansen. I'll try this shortly.

**Comment by alexbooker** [comment]
Ah. Thanks @mickhansen. That did the trick.

**Comment by alexbooker** [comment]
Can you please point me in the direction of the documentation that explains why this is necessary? Thanks.

**Comment by mickhansen** [comment]
@alexbooker i don't think we say anywhere explicitely one way or the other i'm afraid. But it's a good place for improvement since it's a question we get once in a while.

**Comment by alexbooker** [comment]
@mickhansen I would love to help out but I do not understand why it is necessary myself I am afraid.

**Comment by mickhansen** [comment]
@alexbooker It's simply a legacy thing, the codebase has never done it previously and at this point we're a bit worried about introducing magic that might break existing codebases in weird ways.
