### ISSUE TITLE
[Postgresql] Unhandled rejection SequelizeDatabaseError: terminating connection due to administrator command

### ISSUE THREAD

**Issue by kimthangatm** [sequelize/sequelize#4556]
Hi, My API no response (freezing) with this log:
How to fix it with use try reconnect db, try catch or other solution

```
2015-09-21 22:21:00: Unhandled rejection SequelizeDatabaseError: terminating connection due to administrator command
at module.exports.Query.formatError (/home/public_html/node_modules/sequelize/lib/dialects/postgres/query.js:422:16)
at null.<anonymous> (/home/public_html/node_modules/sequelize/lib/dialects/postgres/query.js:106:21)
at emitOne (events.js:77:13)
at emit (events.js:169:7)
at Query.handleError (/home/public_html/node_modules/pg/lib/query.js:108:8)
at null.<anonymous> (/home/public_html/node_modules/pg/lib/client.js:171:26)
at emitOne (events.js:77:13)
at emit (events.js:169:7)
at Socket.<anonymous> (/home/public_html/node_modules/pg/lib/connection.js:109:12)
at emitOne (events.js:77:13)
at Socket.emit (events.js:169:7)
at readableAddChunk (_stream_readable.js:146:16)
at Socket.Readable.push (_stream_readable.js:110:10)
at TCP.onread (net.js:521:20)
```

I use: 
```
let sequelize = new Sequelize(config.db.database, config.db.username, config.db.password, config.db);
```

**Comment by janmeier** [comment]
Is this error happening at startup or intermittently? You can attach a `.catch` handler to the query if only a specific query fails - otherwise you should use `process.uncaugthexception` or domains to catch these type of unrecoverable errors and restart the worker - I dont' believe there is any way to recover from these types of fatal errors

**Comment by janmeier** [comment]
Closing, no response

**Comment by kimthangatm** [comment]
@janmeier Thanks for suport, I find error because System auto backup db and disconnect all connect to database and Sequelize not reconnect => Freeze API.
