### ISSUE TITLE
this.setDataValue is not a function

### ISSUE THREAD

**Issue by jaulz** [sequelize/sequelize#4590]
I get an error when I try to create an entity in version 3.9.0 that has a custom setter. The strange thing about it is that it works on my Mac but on an ubuntu machine it does not. Though I already tried to debug the call stack I could not find the exact reason what's going wrong here.

The call stack is as follows:
```
TypeError: Uncaught error: this.setDataValue is not a function
    at sequelize.define.password.set (/home/ubuntu/workspace/api/Models/User.js:24:16)
    at Instance.set (/home/ubuntu/workspace/api/node_modules/hapi-sequelized/node_modules/sequelize/lib/instance.js:311:32)
    at Instance.set (/home/ubuntu/workspace/api/node_modules/hapi-sequelized/node_modules/sequelize/lib/instance.js:293:16)
    at initValues (/home/ubuntu/workspace/api/node_modules/hapi-sequelized/node_modules/sequelize/lib/instance.js:63:8)
    at Instance (/home/ubuntu/workspace/api/node_modules/hapi-sequelized/node_modules/sequelize/lib/instance.js:107:14)
    at new Instance (/home/ubuntu/workspace/api/node_modules/hapi-sequelized/node_modules/sequelize/lib/model.js:696:14)
    at Model.build (/home/ubuntu/workspace/api/node_modules/hapi-sequelized/node_modules/sequelize/lib/model.js:1712:10)
    at Model.create (/home/ubuntu/workspace/api/node_modules/hapi-sequelized/node_modules/sequelize/lib/model.js:1761:15)
```

The model is defined as:
```
  var Model = sequelize.define(
    MODEL_CONSTANTS.ENTITY.USER,
    {
      email: {
        type: DataTypes.STRING,
        unique: true,
        allowNull: false,
        isEmail: true
      },

      passwordHashed: DataTypes.STRING,
      password: {
        type: DataTypes.VIRTUAL,
        set: (value) => {
          this.setDataValue('password', value) // Remember to set the data value, otherwise it won't be validated
          this.setDataValue('passwordHashed', bcrypt.hashSync(value, SECURITY_CONFIG.salts.password))
        }
      },

      plan: {
        type: DataTypes.STRING,
        defaultValue: 'Basic',
        isIn: {
          args: [['Basic', 'Agency']],
          msg: 'Not a correct plan'
        }
      },

      isLocked: {
        type: DataTypes.BOOLEAN,
        defaultValue: true,
      },

      unlockKey: {
        type: DataTypes.UUID,
        defaultValue: DataTypes.UUIDV1
      }
    },
    {
      instanceMethods: {
        toJSON: () => {
          var values = this.get()

          // Protect fields and hide them
          var hideKeys = ['password', 'passwordHashed', 'unlockKey']
          hideKeys.forEach((key) => {
            delete values[key]
          })

          return values
        },

        verifyPassword: (password) => {
          return new Promise((resolve, reject) => {
            bcrypt.compare(password, this.passwordHashed, ((error, result) => {
              if (error || !result) return reject(Boom.forbidden('Invalid Credentials'))
              return resolve(this)
            }).bind(this))
          })
        }
      }
    }
  )
```

And here is the create:
```
models[MODEL_CONSTANTS.ENTITY.USER].create({
        email: request.payload.email,
        password: request.payload.password
      })
```

**Comment by mickhansen** [comment]
It should work: https://github.com/sequelize/sequelize/blob/master/lib/instance.js#L160
What is `this` inside the method?

**Comment by janmeier** [comment]
You are using an arrow function, which binds `this` at the time the function is defined - this means its bound the context where the model is defined. It cannot later be overriden with call, since call cannot ovveride this for arrows, [see](https://www.nczonline.net/blog/2013/09/10/understanding-ecmascript-6-arrow-functions/)

**Comment by jontelm** [comment]
Is it some way around this problem @janmeier?

**Comment by mickhansen** [comment]
@jontelm Don't misuse arrow functions.
