### ISSUE TITLE
running tests using docker fails because DOCKER_HOST gets lost by sudo command.

### ISSUE THREAD

**Issue by jonnolen** [sequelize/sequelize#4626]
- On Mac OS X El Capitan, 
- using Docker Toolbox (because boot2docker is deprecated).
- Using the Docker Quickstart Terminal.

running `npm run test-docker`  fails with: 

```
sequelize[master]$ npm run test-docker

> sequelize@3.11.0 test-docker /Users/jon/src/sequelize
> sudo docker-compose run sequelize /bin/sh -c "make all"

Password:
Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```

This is fixed if I change package.json:
```
diff --git a/package.json b/package.json
index 9514983..173aae8 100644
--- a/package.json
+++ b/package.json
@@ -85,7 +85,7 @@
   "main": "index",
   "scripts": {
     "test": "make all",
-    "test-docker": "sudo docker-compose run sequelize /bin/sh -c \"make all\"",
+    "test-docker": "sudo -E docker-compose run sequelize /bin/sh -c \"make all\"",
     "build-docker": "sudo docker-compose build",
     "docs": "node docs/docs-generator.js"
   },
```

Anyone else running into this?  Would this be an acceptable PR against 3.11?

**Comment by mickhansen** [comment]
`sudo` needs to be removed from package.json entirely actually (for both test-docker & build-docker), if the user needs to he should call `sudo npm run [script]` instead. PR welcome, it's been on my list.

**Comment by jonnolen** [comment]
actually, now i'm seeing this: 

```
/node_modules/.bin/mocha --globals setImmediate,clearImmediate --ui tdd --check-leaks --colors -t 15000 --reporter spec ./test/unit/*.js ./test/unit/**/*.js
An unhandled exception occured:
/sequelize/test/support.js:23
  throw e;
        ^
Error: The dialect sqlite is not supported. (Error: Please install sqlite3 package manually)
    at new Sequelize (/sequelize/lib/sequelize.js:203:11)
    at Object.Support.getSequelizeInstance (/sequelize/test/support.js:116:12)
    at Object.Support.createSequelizeInstance (/sequelize/test/support.js:110:17)
    at Object.<anonymous> (/sequelize/test/support.js:224:29)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:428:10)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
    at Module.require (module.js:345:17)
    at require (module.js:364:17)
    at Object.<anonymous> (/sequelize/test/unit/support.js:1:80)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:428:10)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
    at Module.require (module.js:345:17)
    at require (module.js:364:17)
    at Object.<anonymous> (/sequelize/test/unit/hooks.test.js:7:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:428:10)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
    at Module.require (module.js:345:17)
    at require (module.js:364:17)
    at /node_modules/mocha/lib/mocha.js:216:27
    at Array.forEach (native)
    at Mocha.loadFiles (/node_modules/mocha/lib/mocha.js:213:14)
    at Mocha.run (/node_modules/mocha/lib/mocha.js:453:10)
    at Object.<anonymous> (/node_modules/mocha/bin/_mocha:393:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:428:10)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
    at Function.Module.runMain (module.js:451:10)
    at startup (node.js:124:18)
    at node.js:868:3
Makefile:25: recipe for target 'test-unit' failed
make[2]: *** [test-unit] Error 7
make[2]: Leaving directory '/sequelize'
Makefile:20: recipe for target 'test' failed
make[1]: *** [test] Error 2
make[1]: Leaving directory '/sequelize'
Makefile:72: recipe for target 'sqlite' failed
make: *** [sqlite] Error 2
```

**Comment by mickhansen** [comment]
That's odd, inside the docker container?

**Comment by jonnolen** [comment]
this is after running npm run test-docker.. so yeah inside the container.

**Comment by mickhansen** [comment]
Hmm, so we use docker-compose with volume mapping, can you check if node_modules is empty?
If not try using `sudo docker-compose run sequelize /bin/sh -c "npm install"` (although i didn't think that would be necessary)

**Comment by jonnolen** [comment]
i think i figured it out.

If I do npm install from my machine before trying to run the tests it fails. If, instead, I just run the test-docker command with no local node modules then I'm good to go.

**Comment by jonnolen** [comment]
well, i guess that's only partially true.  I'm getting 1 failing mysql test: 

```
1) [MYSQL] Sequelize sync fails with incorrect database credentials (1):
     AssertionError: expected 'connect ECONNREFUSED 127.0.0.1:3306' to match /.*Access\ denied.*/
      at assertMatch (/node_modules/chai/lib/chai/core/assertions.js:1031:10)
      at ctx.(anonymous function) (/node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at doAsserterAsyncAndAddThen (/node_modules/chai-as-promised/lib/chai-as-promised.js:292:33)
      at null.<anonymous> (/node_modules/chai-as-promised/lib/chai-as-promised.js:251:21)
      at ctx.(anonymous function) [as match] (/node_modules/chai/lib/chai/utils/overwriteMethod.js:48:33)
      at test/integration/sequelize.test.js:767:47
  From previous event:
      at Promise.catch (lib/promise.js:21:17)
      at Context.<anonymous> (test/integration/sequelize.test.js:756:34)
```

**Comment by mickhansen** [comment]
That test fails for me with docker aswell, so just ignore that one.
