### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined on hasMany on model without primary key.

### ISSUE THREAD

**Issue by mirek** [sequelize/sequelize#4628]
sequelize 3.11.0 when using hasMany relation to model that is without an id (removed via `Foo.removeAttribute('id')` and without primary key) when I do `bar.countFoos()` it throws (tries to perform select with _undefined_ attribute (should be `*` I guess):

```
TypeError: Cannot read property 'indexOf' of undefined,
    at Object.QueryGenerator.handleSequelizeMethod ($MY_APP/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1755:21),
    at Object.QueryGenerator.handleSequelizeMethod ($MY_APP/node_modules/sequelize/lib/dialects/postgres/query-generator.js:176:59),
    at $MY_APP/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1743:23,
    at Array.map (native),
    at Object.QueryGenerator.handleSequelizeMethod ($MY_APP/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1741:42),
    at Object.QueryGenerator.handleSequelizeMethod ($MY_APP/node_modules/sequelize/lib/dialects/postgres/query-generator.js:176:59),
    at $MY_APP/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1011:26,
    at Array.map (native),
    at Object.QueryGenerator.selectQuery ($MY_APP/node_modules/sequelize/lib/dialects/abstract/query-generator.js:996:55),
    at [object Object].QueryInterface.select ($MY_APP/node_modules/sequelize/lib/query-interface.js:677:25),
    at [object Object].<anonymous> ($MY_APP/node_modules/sequelize/lib/model.js:1367:32),
    at bound (domain.js:254:14),
    at [object Object].runBound (domain.js:267:12),
From previous event:,
    at Promise.then ($MY_APP/node_modules/sequelize/lib/promise.js:21:17),
    at [object Object].Model.findAll ($MY_APP/node_modules/sequelize/lib/model.js:1363:6),
    at [object Object].HasMany.get ($MY_APP/node_modules/sequelize/lib/associations/has-many.js:315:16),
    at [object Object].HasMany.count ($MY_APP/node_modules/sequelize/lib/associations/has-many.js:343:15),
    at [object Object].obj.(anonymous function) [as countHistoryParticipations] ($MY_APP/node_modules/sequelize/lib/associations/has-many.js:237:26),
    ...
```

**Comment by mirek** [comment]
More specifically this fails https://github.com/sequelize/sequelize/blob/9fb479443fef104e4764887c91ff82ead666d9c9/lib/dialects/abstract/query-generator.js#L1753 because `smth.col` is _undefined_.

**Comment by janmeier** [comment]
Can you create a selfcontained test case?

**Comment by schaitanya** [comment]
I'm facing a similar problem. Not sure if this is a bug, but if I don't have the `foreign_key` in the attributes  array when using `limit` in include, I'm getting an error.

#### What you are doing?
I'm trying to get all hasMany with `limit` 
#### Version
3.11.0
#### Dialect
mysql
#### Code
```javascript
var Sequelize, co, sequelize;

co = require('co');

Sequelize = require('sequelize');

sequelize = new Sequelize('test', 'test', 'test', {
  logging: console.log
});

co(function*() {
  var A, B, a, data;
  A = sequelize.define('A', {
    id: {
      primaryKey: true,
      type: Sequelize.INTEGER.UNSIGNED,
      autoIncrement: true
    },
    state: {
      type: Sequelize.STRING(100),
      allowNull: false
    },
    code: {
      type: Sequelize.STRING(100),
      allowNull: true
    }
  }, {
    paranoid: true,
    underscored: true
  });
  B = sequelize.define('B', {
    id: {
      primaryKey: true,
      type: Sequelize.INTEGER.UNSIGNED,
      autoIncrement: true
    },
    email: {
      type: Sequelize.STRING(100),
      allowNull: true
    }
  }, {
    paranoid: true,
    underscored: true
  });
  B.belongsTo(A, {
    onUpdate: 'cascade',
    onDelete: 'cascade'
  });
  A.hasMany(B, {
    as: 'RawB'
  });
  (yield sequelize.sync({
    force: true
  }));
  a = (yield A.create({
    state: 'done',
    code: '123'
  }));
  a = (yield A.findById(1));
  (yield a.createRawB({
    email: 'stest@example.com'
  }));

  /*
  data = yield A.findAll
    where:
      state: 'done'
    include: [
      model: B
      as: 'RawB'
    ]
    attributes: ['id']
  
  for d in data
    console.log d.get plain: true
   */

  /* This works fine */
  data = (yield A.find({
    where: {
      id: 1
    },
    include: [
      {
        model: B,
        as: 'RawB'
      }
    ]
  }));
  
  /*This works if its either limit or attributes in include */
  data = (yield A.find({
    where: {
      id: 1
    },
    include: [
      {
        model: B,
        as: 'RawB',
        /* attributes: ['email'] */
        /* limit: 1 */
      }
    ]
  }));
  
  /* This works only if I specify the foreign_key */
  data = (yield A.find({
    where: {
      id: 1
    },
    include: [
      {
        model: B,
        as: 'RawB',
        attributes: ['email', 'a_id'],
        limit: 1
      }
    ]
  }));
  
  return console.log(data.get({
    plain: true
  }));
})();

```

Generated SQL statements respectively, 
```sql
SELECT `A`.`id`, `A`.`state`, `A`.`code`, `A`.`created_at`, `A`.`updated_at`, `A`.`deleted_at`, `RawB`.`id` AS `RawB.id`, `RawB`.`email` AS `RawB.email`, `RawB`.`type` AS `RawB.type`, `RawB`.`created_at` AS `RawB.created_at`, `RawB`.`updated_at` AS `RawB.updated_at`, `RawB`.`deleted_at` AS `RawB.deleted_at`, `RawB`.`a_id` AS `RawB.a_id` FROM `As` AS `A` LEFT OUTER JOIN `Bs` AS `RawB` ON `A`.`id` = `RawB`.`a_id` AND `RawB`.`deleted_at` IS NULL WHERE (`A`.`deleted_at` IS NULL AND `A`.`id` = 1);

SELECT `A`.`id`, `A`.`state`, `A`.`code`, `A`.`created_at`, `A`.`updated_at`, `A`.`deleted_at` FROM `As` AS `A` WHERE (`A`.`deleted_at` IS NULL AND `A`.`id` = 1);
SELECT `B`.* FROM ((SELECT `id`, `email`, `type`, `created_at`, `updated_at`, `deleted_at`, `a_id` FROM `Bs` AS `B` WHERE (`B`.`deleted_at` IS NULL AND (`B`.`deleted_at` IS NULL)) AND `B`.`a_id` = 1 LIMIT 1)) AS `B`;

SELECT `A`.`id`, `A`.`state`, `A`.`code`, `A`.`created_at`, `A`.`updated_at`, `A`.`deleted_at` FROM `As` AS `A` WHERE (`A`.`deleted_at` IS NULL AND `A`.`id` = 1);
SELECT `B`.* FROM ((SELECT `id`, `email` FROM `Bs` AS `B` WHERE (`B`.`deleted_at` IS NULL AND (`B`.`deleted_at` IS NULL)) AND `B`.`a_id` = 1 LIMIT 1)) AS `B`;
```

```error
TypeError: Cannot read property 'push' of undefined
  at node_modules/sequelize/lib/associations/has-many.js:324:64

**Comment by janmeier** [comment]
@schaitanya Please open a separate test case

**Comment by molerat619** [comment]
I have the same problem.

```
Page.find({
      where: {
        state: req.params.state,
        active: 1
      },
      include: [{
        model: PageContent, 
        as: 'content', 
        limit: 1, 
        where: {language: req.params.lang, active: 1}, 
        attributes: ['title', 'subtitle', 'meta_description', 'meta_title', 'html']
      }],
      attributes: ['background']
    })
```

When I run my test, I get the same error.

```
it('should return the english about page', function (done) {
      request(app)
        .get('/api/pages/about/en')
        .expect(200)
        .expect('Content-Type', /json/)
        .expect(englishAboutPage, done);
    });
```

Error Message: `[TypeError: Cannot read property 'push' of undefined]`

**Comment by janmeier** [comment]
@molerat619 please create a complete test case with models and associations

**Comment by molerat619** [comment]
Sorry, I have solved the issue because I needed to do some restructuring anyway. Can't reproduce right now.
