### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined (when using limit without order or primary key)

### ISSUE THREAD

**Issue by rocketmonkeys** [sequelize/sequelize#4629]
This is not necessarily a bug, just a request for better error messages.

Example: You have a model with no primary key, and you use findAll() with "limit" but no "order":

```
sequalize.table.findAll({
    limit: 100
})
```

You get this error:

```
TypeError: Cannot read property 'replace' of undefined
    at Object.QueryGenerator.quoteIdentifier (PROJECT_ROOT\node_modules\sequelize\lib\dialects\mssql\query-generator.js:494:30)
    at Object.QueryGenerator.addLimitAndOffset (PROJECT_ROOT\node_modules\sequelize\lib\dialects\mssql\query-generator.js:592:26)
    at Object.QueryGenerator.selectQuery (PROJECT_ROOT\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1473:27)
    at QueryInterface.select (PROJECT_ROOT\node_modules\sequelize\lib\query-interface.js:674:25)
    at null.<anonymous> (PROJECT_ROOT\node_modules\sequelize\lib\model.js:1330:32)
    at tryCatcher (PROJECT_ROOT\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (PROJECT_ROOT\node_modules\bluebird\js\main\promise.js:503:31)
    at Promise._settlePromiseAt (PROJECT_ROOT\node_modules\bluebird\js\main\promise.js:577:18)
    at Async._drainQueue (PROJECT_ROOT\node_modules\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (PROJECT_ROOT\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (PROJECT_ROOT\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

The code is here:

```
if (options.limit || options.offset) {
  if (!options.order || (options.include && !subQueryOrder.length)) {
    fragment += (options.order && !isSubQuery) ? ', ' : ' ORDER BY ';
    fragment += this.quoteIdentifier(model.primaryKeyAttribute);
  }
  ...
```

It would be nicer to have an error that you need to specify either order or have a primary key.  A simple assert or "if () throw new Error()" would be fine.

Again - not necessarily a bug, since you need to have order-by in order to use limit, but a confusing error message.

**Comment by janmeier** [comment]
God dammit, I don't think we are ever going to get over issues for models without primary keys. They just keep popping up :D. I guess it's because it's so ingrained to us that everything has a primary key that we forget these cases .. :)

Anyhow, since you've already identified the place the error occurs, it should be a quick PR ;)

**Comment by riemannzeta** [comment]
+1

**Comment by Naoto-Ida** [comment]
@janmeier Is this resolved? I'm still learning about the library and would love to fix this if it isn't.

I did the same thing as @rocketmonkeys with the code below.

> define.js

```
export default Article = db.define(`article`, {
	// id: {
	// 	type: Sequelize.INTEGER,
	// 	field: 'ID',
	// 	// primaryKey: true
	// },
       name: {
              type: Sequelize.STRING,
              
       }
```

> index.js

```
import Article from './define'
import ArticleType from './type' // Omitting. Just a GraphQLObjectType

const articles = {
	type: new GraphQLList(ArticleType),
	args: {
		limit: {
			type: GraphQLInt,
			description: 'Number of results.',
			defaultValue: 10,
		},
		offset: {
		  type: GraphQLInt,
		  description: 'Number of articles to offset in result.',
		  defaultValue: 0,
		},
		order: {
			type: OrderType,
			description: 'Sorting order',
			defaultValue: 'DESC',
		},
	},
	resolve(_, args, { rootValue }) {
		const {
			limit,
			offset,
			order
		} = args
		return Model.Article.findAll({
			limit: limit,
			offset: offset,
			// order: [
			// 	['ID', order]
			// ]
		})
	}
}
```

This displays no errors. Am I misunderstanding the issue?

**Comment by nguyennb9** [comment]
It still not resolve yet, why close it man?

**Comment by sushantdhiman** [comment]
Works in `5.0.0-beta.11`

```js
const Sequelize = require('./index');
const sequelize = require('./test/support').createSequelizeInstance();

const History = sequelize.define('history', {
  amount: Sequelize.INTEGER
});

History.removeAttribute('id');


(async () => {
  await sequelize.sync({ force: true });

  const r = await History.findAll({
    limit: 100
  });

  console.log(r);
})()
```

```sql
Executing (default): DROP TABLE IF EXISTS `histories`;
Executing (default): DROP TABLE IF EXISTS `histories`;
Executing (default): CREATE TABLE IF NOT EXISTS `histories` (`amount` INTEGER, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `histories`
Executing (default): SELECT `amount`, `createdAt`, `updatedAt` FROM `histories` AS `history` LIMIT 100;
[]
```

**Comment by manast-apsis** [comment]
If you get an unhandled exception it is a bug... Seems like in current versions this error is still possible, unfortunately on a big codebase with many models, finding which one causes this exception is like finding a needle in a haystack.
