### ISSUE TITLE
Upgrading to Node 4.2.0 Causes Unhandled Connection Error

### ISSUE THREAD

**Issue by Reanmachine** [sequelize/sequelize#4640]
This may be in the hands of the `mysql` maintainers but I figured I'd start here because sequelize was the one throwing a fit.

I recently updated to nodejs 4.2.0 and now when I start up my project I get the following error:

    worker-0 (err): Unhandled rejection SequelizeConnectionError: Handshake inactivity timeout
    worker-0 (err):     at Handshake._callback (/vagrant/server/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:63:20)
    worker-0 (err):     at Handshake.Sequence.end (/vagrant/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    worker-0 (err):     at /vagrant/server/node_modules/mysql/lib/protocol/Protocol.js:393:18
    worker-0 (err):     at Array.forEach (native)
    worker-0 (err):     at /vagrant/server/node_modules/mysql/lib/protocol/Protocol.js:392:13
    worker-0 (err):     at doNTCallback0 (node.js:417:9)
    worker-0 (err):     at process._tickDomainCallback (node.js:387:13)

I did some digging, it's getting a `PROTOCOL_SEQUENCE_TIMEOUT` from mysql and rejecting the connection.

Downgrading to Node 4.1.x fixes the problem.

**Comment by Reanmachine** [comment]
Sorry, Please Ignore, just found a reference from the `node-mysql' issues, either a problem with `node` or `node-mysql` directly.
