### ISSUE TITLE
mysql connect wrong at lastest version

### ISSUE THREAD

**Issue by zhfish** [sequelize/sequelize#4641]
mysql connect wrong at lastest version

a new env
mysql 2.9.0
sequelize 3.11.0 

```
var sequelize = new Sequelize('mariadb://root:toor@127.0.0.1:6033/dev', {
    define: {
        timestamps: true,
        freezeTableName : true
  }
});

and 

User.findAll()
```

it's ok last time  in sequelize 3.8.0

```
Unhandled rejection SequelizeConnectionError: Handshake inactivity timeout
    at Handshake._callback (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:63:20)
    at Handshake.Sequence.end (/usr/local/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at /usr/local/lib/node_modules/mysql/lib/protocol/Protocol.js:393:18
    at Array.forEach (native)
    at /usr/local/lib/node_modules/mysql/lib/protocol/Protocol.js:392:13
    at doNTCallback0 (node.js:417:9)
    at process._tickCallback (node.js:346:13)
```

**Comment by zhfish** [comment]
the same to #4640
