### ISSUE TITLE
Why sequelize doesn't connect to DB when system is offline?

### ISSUE THREAD

**Issue by moslemezzati** [sequelize/sequelize#4664]
I try to run my project when my computer is offline but it showed me this error:
```javascript
Unhandled rejection SequelizeConnectionError: getaddrinfo ENOENT
    at C:\Users\moslem\WebstormProjects\exchange\node_modules\sequelize\lib\dial
ects\postgres\connection-manager.js:74:20
    at null.<anonymous> (C:\Users\moslem\WebstormProjects\exchange\node_modules\
pg\lib\client.js:176:5)
    at emit (events.js:107:17)
    at Socket.<anonymous> (C:\Users\moslem\WebstormProjects\exchange\node_module
s\pg\lib\connection.js:59:10)
    at Socket.emit (events.js:107:17)
    at net.js:923:16
    at process._tickCallback (node.js:355:11)
```
after that I connected to internet then everything works as expected

**Comment by janmeier** [comment]
You'll have to give some more context than that... What code have you tried, what do you expect to happen, and what actually happens?

**Comment by moslemezzati** [comment]
in run sequelize cli init to build my models folder and so forth, as I said everything works as expect but in offline state sequelize  dos't connect to postgres, here is my code:
```javascript
'use strict';

var fs        = require('fs');
var path      = require('path');
var Sequelize = require('sequelize');
var basename  = path.basename(module.filename);
var env       = process.env.NODE_ENV || 'development';
var config    = require(__dirname + '/../config/config.json')[env];
var db        = {};

if (config.use_env_variable) {
  var sequelize = new Sequelize(process.env[config.use_env_variable]);
} else {
  var sequelize = new Sequelize(config.database, config.username, config.password, config);
}

fs
  .readdirSync(__dirname)
  .filter(function(file) {
    return (file.indexOf('.') !== 0) && (file !== basename);
  })
  .forEach(function(file) {
    if (file.slice(-3) !== '.js') return;
    var model = sequelize['import'](path.join(__dirname, file));
    db[model.name] = model;
  });

Object.keys(db).forEach(function(modelName) {
  if (db[modelName].associate) {
    db[modelName].associate(db);
  }
});

db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;
```

**Comment by moslemezzati** [comment]
I found out where is issue my config file is set like this:
```javascript
 "development": {
    "username": "postgres",
    "password": "1",
    "database": "exchange",
    "host": "localhost",
    "dialect": "postgres",
    "port": "5432"
  },
```
and I changed it to this:
```javascript
 "development": {
    "username": "postgres",
    "password": "1",
    "database": "exchange",
    "host": "127.0.0.1",
    "dialect": "postgres",
    "port": "5432"
  },
```
And then everything worked fine.
Did you have this experience before?

**Comment by moslemezzati** [comment]
I found out where is issue my config file is set like this:
```javascript
 "development": {
    "username": "postgres",
    "password": "1",
    "database": "exchange",
    "host": "localhost",
    "dialect": "postgres",
    "port": "5432"
  },
```
and I changed it to this:
```javascript
 "development": {
    "username": "postgres",
    "password": "1",
    "database": "exchange",
    "host": "127.0.0.1",
    "dialect": "postgres",
    "port": "5432"
  },
```
And then everything worked fine.
Did you have this experience before?

**Comment by moslemezzati** [comment]
I found out where is issue my config file is set like this:
```javascript
 "development": {
    "username": "postgres",
    "password": "1",
    "database": "exchange",
    "host": "localhost",
    "dialect": "postgres",
    "port": "5432"
  },
```
and I changed it to this:
```javascript
 "development": {
    "username": "postgres",
    "password": "1",
    "database": "exchange",
    "host": "127.0.0.1",
    "dialect": "postgres",
    "port": "5432"
  },
```
And then everything worked fine.
Thanks

**Comment by jxnuzhangwen** [comment]
Hello mosle,

I met your problem also, and I changed host to "127.0.0.1" and the problem is solved. thank you very much.

**Comment by tope-olajide** [comment]
same here, worked for me too

**Comment by EddyLeon** [comment]
i met with this problem, this worked for me too

**Comment by Jandsonn** [comment]
Deu certo aqui também, eu estava com o mesmo problema coloquei o endereço host local e e deu certo. Obrigado irmãozinho
