### ISSUE TITLE
Include `hasMany` must have the `foreign_key` in attributes array when used along with `limi`

### ISSUE THREAD

**Issue by schaitanya** [sequelize/sequelize#4694]
Not sure if this is a bug, but if I don't have the `foreign_key` in the attributes array when using `limit` in include, I'm getting an error.
#### What you are doing?

I'm trying to get all hasMany with `limit` 
#### Version

3.11.0
#### Dialect

mysql
#### Code

``` javascript
var Sequelize, co, sequelize;

co = require('co');

Sequelize = require('sequelize');

sequelize = new Sequelize('test', 'test', 'test', {
  logging: console.log
});

co(function*() {
  var A, B, a, data;
  A = sequelize.define('A', {
    id: {
      primaryKey: true,
      type: Sequelize.INTEGER.UNSIGNED,
      autoIncrement: true
    },
    state: {
      type: Sequelize.STRING(100),
      allowNull: false
    },
    code: {
      type: Sequelize.STRING(100),
      allowNull: true
    }
  }, {
    paranoid: true,
    underscored: true
  });
  B = sequelize.define('B', {
    id: {
      primaryKey: true,
      type: Sequelize.INTEGER.UNSIGNED,
      autoIncrement: true
    },
    email: {
      type: Sequelize.STRING(100),
      allowNull: true
    }
  }, {
    paranoid: true,
    underscored: true
  });
  B.belongsTo(A, {
    onUpdate: 'cascade',
    onDelete: 'cascade'
  });
  A.hasMany(B, {
    as: 'RawB'
  });
  (yield sequelize.sync({
    force: true
  }));
  a = (yield A.create({
    state: 'done',
    code: '123'
  }));
  a = (yield A.findById(1));
  (yield a.createRawB({
    email: 'stest@example.com'
  }));

  /*
  data = yield A.findAll
    where:
      state: 'done'
    include: [
      model: B
      as: 'RawB'
    ]
    attributes: ['id']

  for d in data
    console.log d.get plain: true
   */

  /* This works fine */
  data = (yield A.find({
    where: {
      id: 1
    },
    include: [
      {
        model: B,
        as: 'RawB'
      }
    ]
  }));

  /*This works if its either limit or attributes in include */
  data = (yield A.find({
    where: {
      id: 1
    },
    include: [
      {
        model: B,
        as: 'RawB',
        /* attributes: ['email'] */
        /* limit: 1 */
      }
    ]
  }));

  /* This works only if I specify the foreign_key */
  data = (yield A.find({
    where: {
      id: 1
    },
    include: [
      {
        model: B,
        as: 'RawB',
        attributes: ['email', 'a_id'],
        limit: 1
      }
    ]
  }));

  return console.log(data.get({
    plain: true
  }));
})();

```

Generated SQL statements respectively, 

``` sql
SELECT `A`.`id`, `A`.`state`, `A`.`code`, `A`.`created_at`, `A`.`updated_at`, `A`.`deleted_at`, `RawB`.`id` AS `RawB.id`, `RawB`.`email` AS `RawB.email`, `RawB`.`type` AS `RawB.type`, `RawB`.`created_at` AS `RawB.created_at`, `RawB`.`updated_at` AS `RawB.updated_at`, `RawB`.`deleted_at` AS `RawB.deleted_at`, `RawB`.`a_id` AS `RawB.a_id` FROM `As` AS `A` LEFT OUTER JOIN `Bs` AS `RawB` ON `A`.`id` = `RawB`.`a_id` AND `RawB`.`deleted_at` IS NULL WHERE (`A`.`deleted_at` IS NULL AND `A`.`id` = 1);

SELECT `A`.`id`, `A`.`state`, `A`.`code`, `A`.`created_at`, `A`.`updated_at`, `A`.`deleted_at` FROM `As` AS `A` WHERE (`A`.`deleted_at` IS NULL AND `A`.`id` = 1);
SELECT `B`.* FROM ((SELECT `id`, `email`, `type`, `created_at`, `updated_at`, `deleted_at`, `a_id` FROM `Bs` AS `B` WHERE (`B`.`deleted_at` IS NULL AND (`B`.`deleted_at` IS NULL)) AND `B`.`a_id` = 1 LIMIT 1)) AS `B`;

SELECT `A`.`id`, `A`.`state`, `A`.`code`, `A`.`created_at`, `A`.`updated_at`, `A`.`deleted_at` FROM `As` AS `A` WHERE (`A`.`deleted_at` IS NULL AND `A`.`id` = 1);
SELECT `B`.* FROM ((SELECT `id`, `email` FROM `Bs` AS `B` WHERE (`B`.`deleted_at` IS NULL AND (`B`.`deleted_at` IS NULL)) AND `B`.`a_id` = 1 LIMIT 1)) AS `B`;
```

``` error
TypeError: Cannot read property 'push' of undefined
  at node_modules/sequelize/lib/associations/has-many.js:324:64
```

**Comment by janmeier** [comment]
`limit` triggers `include.separate` which again assumes that the foreign key is set https://github.com/sequelize/sequelize/blob/v3.11.0/lib/associations/has-many.js#L324

We should inject the foreign key into attributes if `.separate`

**Comment by OKNoah** [comment]
I get a very similar error when I use

    include: [
      // ...
      {
        model: Version,
        limit: 1,
        order: [['id', 'DESC']],
        attributes: ['createdAt', 'body', 'title']
      }
    ]

But if I remove `attributes`, it works. The version is `3.22.0` and the error is lightly different (different line number):

    at /Users/noah/Documents/dev/celsus-api-pgsql/node_modules/sequelize/lib/associations/has-many.js:331:64

**Comment by OKNoah** [comment]
This is pretty weird, would love it fixed. @schaitanya solution did help, thanks.
