### ISSUE TITLE
Model.update with postgres fails with object has not method 'map' error

### ISSUE THREAD

**Issue by ajsharp** [sequelize/sequelize#4697]
I'm using sequelize 3.12.0. Here's my code:

```js
MyModel.update(req.body.object, {where: {id: req.params.id}, fields: ['one', 'two', 'three']})
  .then(function (instance) {
    res.send({obj: instance});
  });
```

`req.body.object` is an object.

And here's the error I get: 

```
Unhandled rejection TypeError: Object function (values) { return Array.prototype.some.call(Array.isArray(values)? values : arguments, function(i){ return this.valueOf()===i.toString(); }, this) } has no method 'map'
    at Object.QueryGenerator.whereItemQuery (/Users/ajsharp/code/PROJECT/api.goPROJECT.com/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2140:49)
    at /Users/ajsharp/code/PROJECT/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1852:25
    at /Users/ajsharp/code/PROJECT/node_modules/sequelize/node_modules/lodash/index.js:3073:15
    at baseForOwn (/Users/ajsharp/code/PROJECT/node_modules/sequelize/node_modules/lodash/index.js:2046:14)
    at Function.forOwn (/Users/ajsharp/code/PROJECT/node_modules/sequelize/node_modules/lodash/index.js:3378:16)
    at Object.QueryGenerator.whereItemsQuery (/Users/ajsharp/code/PROJECT/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1851:9)
    at Object.QueryGenerator.whereQuery (/Users/ajsharp/code/PROJECT/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1823:22)
    at Object.QueryGenerator.updateQuery (/Users/ajsharp/code/PROJECT/node_modules/sequelize/lib/dialects/abstract/query-generator.js:470:19)
    at QueryInterface.bulkUpdate (/Users/ajsharp/code/PROJECT/node_modules/sequelize/lib/query-interface.js:613:33)
    at Promise.try.then.then.then.tap.Promise.map.then.result.(anonymous function) (/Users/ajsharp/code/PROJECT/node_modules/sequelize/lib/model.js:2546:32)
    at tryCatcher (/Users/ajsharp/code/PROJECT/node_modules/sequelize/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/ajsharp/code/PROJECT/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/ajsharp/code/PROJECT/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/Users/ajsharp/code/PROJECT/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/ajsharp/code/PROJECT/node_modules/sequelize/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/ajsharp/code/PROJECT/node_modules/sequelize/node_modules/bluebird/js/main/async.js:133:10)
```

**Comment by janmeier** [comment]
Hmm, that line does something related to `$in` and `$notIn` - are you sure `params.id` is an int and not something else? 

Please show the actual contents of `req.params`, I can't reproduce the issue with the info youve given here

**Comment by janmeier** [comment]
Closing, no response
