### ISSUE TITLE
Attribute exclusion crashes when specified in defaultScope

### ISSUE THREAD

**Issue by curiousdannii** [sequelize/sequelize#4735]
If I try to exclude an attribute (#4074) by default using defaultScope:

```
		defaultScope: {
			attributes: { exclude: [ 'documentation' ] },
		},
```

An error is thrown:

```
/home/dannii/i7el/node_modules/sequelize/lib/model.js:2592
    var attributes = Object.keys(this.tableAttributes);
                            ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at Model.$expandAttributes (/home/dannii/i7el/node_modules/sequelize/lib/model.js:2592:29)
    at conformOptions (/home/dannii/i7el/node_modules/sequelize/lib/model.js:245:10)
    at Model.init (/home/dannii/i7el/node_modules/sequelize/lib/model.js:698:5)
    at Sequelize.define (/home/dannii/i7el/node_modules/sequelize/lib/sequelize.js:582:17)
    at module.exports (/home/dannii/i7el/db/Extension.js:7:19)
```

**Comment by phuvo** [comment]
+1

**Comment by matomesc** [comment]
Getting this as well on:

```
node@4.2.2
npm@2.14.7
sequelize@3.14.2
```
