### ISSUE TITLE
Unhandled rejection SequelizeConnectionError: Quit inactivity timeout with Node 4.2.1

### ISSUE THREAD

**Issue by mhoanghold** [sequelize/sequelize#4750]
Here is the whole error trace:
```
Unhandled rejection SequelizeConnectionError: Quit inactivity timeout
  at Quit._callback (/Users/holdings/Apps/opticon/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:104:30)
  at Quit.Sequence.end (/Users/holdings/Apps/opticon/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
  at /Users/holdings/Apps/opticon/node_modules/mysql/lib/protocol/Protocol.js:393:18
  at Array.forEach (native)
  at /Users/holdings/Apps/opticon/node_modules/mysql/lib/protocol/Protocol.js:392:13
  at doNTCallback0 (node.js:417:9)
  at process._tickCallback (node.js:346:13)
```
And node --version renders: v4.2.1

I am on Heroku trying to connect to a ClearDB. And here is my instantiation:
```
db = new Sequelize(config.mysql.database, config.mysql.username, config.mysql.password, {
  host: config.mysql.host,
  dialect: config.mysql.dialect,
  dialectOptions: {
    timeout: 30
  },
  pool: {
    max: 5,
    min: 0,
    idle: 30000
  },
});
```

**Comment by mickhansen** [comment]
Your connections are being killed because they are idle.
Find out what the server is configured to and set your pool.idle to less than that.

**Comment by mansa-dev** [comment]
@mhoanghold  Did you find solution to this issue. Even with `pool: false` my connections are failing with same errors.

**Comment by mickhansen** [comment]
@mansa-dev `pool: false` does not exist anymore.

**Comment by mansa-dev** [comment]
@mickhansen You are correct. I was trying everything to resolve the issue, even when I was aware pool option expects `Object`,

I resolved the issue by downgrading to `node-mysql` to `2.5` , this issue appears with `2.7`. So it appears to be a `node-mysql` issue.

**Comment by pdostal** [comment]
Thanks you @mansa-dev, it helps for me :+1:

**Comment by aybmab** [comment]
What was the ultimate solution here? I'm running to the same issue with heroku/cleardb.

Thanks in advanced!

**Comment by mansa-dev** [comment]
> I resolved the issue by downgrading to node-mysql to 2.5 , this issue appears with 2.7. So it appears to be a node-mysql issue.

@aybmab  May be it can help.

Also for `cleardb` ensure your `pool : max` are less maximum allowed connections by your `cleardb` plan.

**Comment by aybmab** [comment]
@mansa-dev thanks for the response! I actually fixed it by using the options:
{pool: {maxIdleTime: 120000}}

**Comment by aybmab** [comment]
Spoke too soon.... @mansa-dev any ideas?

`

heroku[router]: http_error="Invalid HTTP status line" at=error code=H17 desc="Poorly formatted HTTP response" method=GET path="/new" host=({REDACTED}).herokuapp.com request_id={REDACTED} fwd="{REDACTED}" dyno=web.1 connect=1ms service=113ms status=503 bytes=319
 Unhandled rejection SequelizeConnectionError: Quit inactivity timeout
     at /app/node_modules/mysql/lib/protocol/Protocol.js:399:18
     at Quit._callback (/app/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:132:30)
     at Quit.Sequence.end (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
     at Array.forEach (native)
     at nextTickCallbackWith0Args (node.js:456:9)
     at process._tickCallback (node.js:385:13)
     at /app/node_modules/mysql/lib/protocol/Protocol.js:398:13`

**Comment by mansa-dev** [comment]
@aybmab try these settings

```
pool: {
    max: 5,
    min: 0,
    idle: 10000
  },
```

**Comment by aybmab** [comment]
@mansa-dev That didn't work either  :/

**Comment by mansa-dev** [comment]
your `node-mysql` version is `2.5`  ? @aybmab

**Comment by aybmab** [comment]
I'm using     "mysql": "^2.5.0",

**Comment by aybmab** [comment]
This might be my problem:
https://github.com/felixge/node-mysql/issues/1334

**Comment by sushantdhiman** [comment]
`npm ls --depth=0` and check if `node-mysql` is still `2.5` , @aybmab

**Comment by aybmab** [comment]
Reinstalled and tried, but still got the error:

├── mysql@2.5.5

I'm able to make a dumb query and print the result using mysql, but then sequelize seems to fail to connect.

Logs:
```2016-01-30T06:09:01.797231+00:00 app[web.1]: The solution is:  2
2016-01-30T06:09:02.025267+00:00 heroku[web.1]: State changed from starting to up
2016-01-30T06:09:02.046081+00:00 app[web.1]: Executing (default): CREATE TABLE IF NOT EXISTS `Sessions` (`sid` VARCHAR(255) , `expires` DATETIME, `data` TEXT, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`sid`)) ENGINE=InnoDB;
2016-01-30T06:09:02.055942+00:00 app[web.1]: Executing (default): SHOW INDEX FROM `Sessions`
2016-01-30T06:09:31.833253+00:00 app[web.1]: Unhandled rejection SequelizeConnectionError: Quit inactivity timeout
2016-01-30T06:09:31.833257+00:00 app[web.1]:     at Quit._callback (/app/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:132:30)
2016-01-30T06:09:31.833259+00:00 app[web.1]:     at Quit.Sequence.end (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
2016-01-30T06:09:31.833261+00:00 app[web.1]:     at Array.forEach (native)
2016-01-30T06:09:31.833260+00:00 app[web.1]:     at /app/node_modules/mysql/lib/protocol/Protocol.js:399:18
2016-01-30T06:09:31.833261+00:00 app[web.1]:     at /app/node_modules/mysql/lib/protocol/Protocol.js:398:13
2016-01-30T06:09:31.833262+00:00 app[web.1]:     at nextTickCallbackWith0Args (node.js:456:9)
2016-01-30T06:09:31.833263+00:00 app[web.1]:     at process._tickCallback (node.js:385:13)
2016-01-30T06:09:42.091377+00:00 app[web.1]: Unhandled rejection SequelizeConnectionError: Quit inactivity timeout
2016-01-30T06:09:42.091386+00:00 app[web.1]:     at process._tickCallback (node.js:385:13)
2016-01-30T06:09:42.091380+00:00 app[web.1]:     at Quit._callback (/app/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:132:30)
2016-01-30T06:09:42.091382+00:00 app[web.1]:     at Quit.Sequence.end (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
2016-01-30T06:09:42.091382+00:00 app[web.1]:     at /app/node_modules/mysql/lib/protocol/Protocol.js:399:18
2016-01-30T06:09:42.091384+00:00 app[web.1]:     at /app/node_modules/mysql/lib/protocol/Protocol.js:398:13
2016-01-30T06:09:42.091383+00:00 app[web.1]:     at Array.forEach (native)
2016-01-30T06:09:42.091385+00:00 app[web.1]:     at nextTickCallbackWith0Args (node.js:456:9)```

Maybe I'm not feeding the right params/options?

**Comment by aybmab** [comment]
Does this make any sense?

`var sequelize = new Sequelize(config.mysqlParams.dbUrl, config.mysqlParams.options)`

where config.mysqlParams.dbUrl = "mysql://{some_user}:{some_pw}@{host}/{db}"
and
```config.mysqlParams.options = {
   dialect: 'mysql',
   pool: { maxIdleTime: 10000, maxConnections: 5, minConnections: 0}
}```

**Comment by mansa-dev** [comment]
@aybmab , In the `mysql-url` try adding `?reconnect=true`

**Comment by aybmab** [comment]
@mansa-dev unfortunately it still didn't work

**Comment by mansa-dev** [comment]
@aybmab You are having these errors on local setup as well?

**Comment by aybmab** [comment]
@mansa-dev  It works locally! It messes up only on heroku.

**Comment by mansa-dev** [comment]
@aybmab Try using `cleardb url` on local

**Comment by aybmab** [comment]
@mansa-dev  hmm...I can't connect to it from my local machine for some reason.

Though, it's definitely something to do with the sequelize configuration...I can make queries to the database using node-mysql, but then sequelize throws the error. I'm guessing something is timing out? Is there a way to read up on the errors? Perhaps it's an issue with creating two pools? Should I be setting certain options?

Thanks for all the help by the way!

**Comment by mansa-dev** [comment]
Which version  of sequelize you are using @aybmab ?

**Comment by aybmab** [comment]
@mansa-dev : `"sequelize": "^3.18.0",`

**Comment by armin-github** [comment]
I was facing the same error (Quit inactivity timeout) with the mysql module (version 2.10.2). I tried various node versions including 4.2.2 where some people had reported to be running fine, but that did not solve the issue for me. Here is what did: I used a connection pool instead of using single connections and calling the annoying connection.end(). The nice thing about using a connection pool is that the Mysql server both removes the connection after its default timeout and creates new connections and put them into the pool whenever needed. Here is the general idea as to how to use the pool:
`var mysql = require('mysql');
var pool  = mysql.createPool({
  connectionLimit : 5,
  host            : 'the_host',
  user            : 'username',
  password        : 'pass'
});

pool.getConnection(function(err, connection) {
  // Use the connection
  connection.query( 'SELECT columnX FROM tableX', function(err, rows) {
    // Always release the connection back to the pool after the (last) query.
    connection.release();

    // Don't use the connection here, it has been returned to the pool.
  });
});`
However, if you already have several connection.query(...) calls in your code, as I did, you might want to use Adam Yost's wrapper posted on:
[https://stackoverflow.com/questions/17015590/node-js-mysql-needing-persistent-connection/30914967#30914967?newreg=df8cfe8f06a04593acac50a200c6fd71](url)
. Adma's code creates and uses the connection pool while no changes are needed to be made to the code that already exists. I used it myself and was quite pleased about it!

**Comment by sushantdhiman** [comment]
Last week I did deployed my code with `mysql: 2.10` and it worked for me as well. One point to note that I was always using pools but old `mysql` never worked for me
