### ISSUE TITLE
Bluebird "settle" is deprecated

### ISSUE THREAD

**Issue by faceleg** [sequelize/sequelize#4814]
```
Warning: .settle() is deprecated and will be removed in a future version. Use .reflect() instead.
    at InstanceValidator.validate (/Users/faceleg/Sync/faceleg/Work/services/module-models/node_modules/sequelize/lib/instance-validator.js:67:18)
    at Instance.validate (/Users/faceleg/Sync/faceleg/Work/services/module-models/node_modules/sequelize/lib/instance.js:766:47)
    at /Users/faceleg/Sync/faceleg/Work/services/module-models/node_modules/sequelize/lib/model.js:2122:27
From previous event:
    at Function.map (/Users/faceleg/Sync/faceleg/Work/services/module-models/node_modules/sequelize/lib/promise.js:21:17)
    at /Users/faceleg/Sync/faceleg/Work/services/module-models/node_modules/sequelize/lib/model.js:2113:22
From previous event:
    at Promise.then (/Users/faceleg/Sync/faceleg/Work/services/module-models/node_modules/sequelize/lib/promise.js:21:17)
    at obj.(anonymous function).obj.(anonymous function) (/Users/faceleg/Sync/faceleg/Work/services/module-models/node_modules/sequelize/lib/associations/belongs-to-many.js:656:18)
    at /Users/faceleg/Sync/faceleg/Work/services/module-models/test/fixtures.js:50:34
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by faceleg** [comment]
I can fix this if you give me an overview of what settle actually does.

**Comment by mickhansen** [comment]
https://github.com/petkaantonov/bluebird/blob/2.x/API.md#settle---promise

It's used to wait for a set of promises that might resolve or reject. `all/join` would not work since they fail on the first rejection.

Looks like replacing it with Promise.map over promise.settle should do the same: http://bluebirdjs.com/docs/api/reflect.html

**Comment by faceleg** [comment]
Ok thanks. It wasn't clear to me, especially since the only thing I could find said `settle` should be replaced with a combination of `map` and `reflect`.

**Comment by faceleg** [comment]
So this:

 > Using .reflect() to implement settleAll (wait until all promises in an array are either rejected or fulfilled) functionality

```JS
var promises = [getPromise(), getPromise(), getPromise()];
Promise.all(promises.map(function(promise) {
    return promise.reflect();
})).each(function(inspection) {
    if (inspection.isFulfilled()) {
        console.log("A promise in the array was fulfilled with", inspection.value());
    } else {
        console.error("A promise in the array was rejected with", inspection.reason());
    }
});
```

**Comment by faceleg** [comment]
Please see 27d4757

**Comment by faceleg** [comment]
```
Warning: a promise was created in a  handler but was not returned from it
    at ConnectionManager.disconnect (/srv/www/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:119:10)
    at ConnectionManager.$disconnect (/srv/www/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:239:41)
    at /srv/www/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:205:16
```

**Comment by mickhansen** [comment]
@faceleg Hmm actually never seen that error before.

**Comment by faceleg** [comment]
I've found it can be finicky and difficult to figure where it's being thrown from.

I've tried to fix as many of these newfangled warnings as part of #4796. Any chance you would be able to merge it?

**Comment by faceleg** [comment]
Closing as #4796 is close to being merged. Most (not all) of these warnings are fixed in that PR.
