### ISSUE TITLE
Missing where attribute in the options parameter passed to update

### ISSUE THREAD

**Issue by dm67x** [sequelize/sequelize#4865]
I have used recently Sequelize and when i want to update my mysql database i see : 

> Unhandled rejection Error: Missing where attribute in the options parameter passed to update.
    at Model.update (E:\Sites\GeoQuizz\node_modules\sequelize\lib\model.js:2396:11)
    at null.<anonymous> (E:\Sites\GeoQuizz\routes\users.js:182:22)
    at tryCatcher (E:\Sites\GeoQuizz\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (E:\Sites\GeoQuizz\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (E:\Sites\GeoQuizz\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromises (E:\Sites\GeoQuizz\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (E:\Sites\GeoQuizz\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (E:\Sites\GeoQuizz\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\Sites\GeoQuizz\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

I use this code : 

```javascript
User.update({ nom: req.body.nom }, { id: user.id });
```

**Comment by mickhansen** [comment]
`User.update({ nom: req.body.nom }, { where: {id: user.id} });`

**Comment by dm67x** [comment]
Thanks so much.

**Comment by damianobarbati** [comment]
@mickhansen how to update every row then? `where` is mandatory but there's no where when you want to update every row.

```
const values = { notes: 'yo' };
const result = await database.models.User.update(values);
```
=>
`Missing where attribute in the options parameter`

**Comment by apmcodes** [comment]
You can try passing empty where: {}

**Comment by Emyboy** [comment]
i tried this User.update({ nom: req.body.nom }, { where: {id: user.id} });

**Comment by Emyboy** [comment]
and i got this error  ()=>  next is not defined
