### ISSUE TITLE
Long error stacks

### ISSUE THREAD

**Issue by tinganho** [sequelize/sequelize#4871]
I have some hard time developing with Sequelize, because I cannot see a error stack originating from my own source files. Sequelize throws a very long error stack, so I cannot see where the error originated from.

Here is one example:

```
    at [object Object].Query.formatError (/home/tingan/dev/badd/node_modules/sequelize/lib/dialects/postgres/query.js:443:14)
    at [object Object].<anonymous> (/home/tingan/dev/badd/node_modules/sequelize/lib/dialects/postgres/query.js:118:19)
    at emitOne (events.js:77:13)
    at [object Object].emit (events.js:169:7)
    at [object Object].Query.handleError (/home/tingan/dev/badd/node_modules/pg/lib/query.js:108:8)
    at [object Object].<anonymous> (/home/tingan/dev/badd/node_modules/pg/lib/client.js:171:26)
    at emitOne (events.js:77:13)
    at [object Object].emit (events.js:169:7)
    at Socket.<anonymous> (/home/tingan/dev/badd/node_modules/pg/lib/connection.js:109:12)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

None of the above files originates from one of my source files. And ALL error stacks seems to be not showing any of my source files. I have been using sequelize in 2 weeks now and I haven't seem one error stack that shows where the error originated from in my source file.

Even though there are some options for running node with prolonged error stack(I have tried them all, and none seem to work for me though). Don't you think you can fix this problem somehow? I don't have any idea how. But it is a huge problem, I'm losing nearly 2 hours per day guessing where the wrong is.

**Comment by janmeier** [comment]
Have you tried setting `BLUEBIRD_DEBUG` or `BLUEBIRD_LONG_STACK_TRACES` (should also be set automagically if `NODE_ENV==development`)

http://bluebirdjs.com/docs/api/environment-variables.html

**Comment by cfogelberg** [comment]
Sequelize uses Bluebird for its promise chains. To enable long stacks set BLUEBIRD_DEBUG=1

**Comment by tinganho** [comment]
Ok thanks It worked now.
