### ISSUE TITLE
Sequelize::sync causes warning: "a promise was created in a  handler but was not returned from it"

### ISSUE THREAD

**Issue by cfogelberg** [sequelize/sequelize#4883]
Calling Sequelize::sync for a pg DB or a mysql DB in 3.14.0 causes a warning log message, apart from the different dialect files the stack trace is the same:

    Warning: a promise was created in a  handler but was not returned from it
        at ConnectionManager.disconnect (/home/christo/repos/sequelize/playground/tests/10-sync-warning-repro/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:162:10)
        at ConnectionManager.$disconnect (/home/christo/repos/sequelize/playground/tests/10-sync-warning-repro/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:257:41)
        at /home/christo/repos/sequelize/playground/tests/10-sync-warning-repro/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:223:16
    From previous event:
        ...

This warning occurs for me in 3.14 but not in 3.13 (but that might just be because bluebird was updated to ^3.0.5 from ^2.10.1 between those two versions) with both pg and mysql. I haven't tried any other DB's. It doesn't matter whether `force: true` is passed as an option to sync or not.

Looking at the code referred to by the call stack there isn't an obvious place where a Promise is created without being returned. Reading around about this problem though ([link1](https://github.com/petkaantonov/bluebird/issues/854), [link2](https://github.com/Automattic/mongoose/issues/3570)) it might be that the stack trace is misleading.

There is a repro [here](https://github.com/cfogelberg/sequelize-playground/tree/master/tests/10-sync-warning-repro), ([permanent link to this commit](https://github.com/cfogelberg/sequelize-playground/tree/32377a33974712ab48735571e761cf94857406fa/tests/10-sync-warning-repro)).

**Comment by mickhansen** [comment]
@faceleg is working on cleaning that up here: https://github.com/sequelize/sequelize/pull/4862
It doesn't affect anything, simply a warning.

**Comment by faceleg** [comment]
Note I'm cleaning up postgres, the same thing will need to be fixed across dialects likely.

**Comment by adrianmacneil** [comment]
I'm seeing this warning a lot, not directly in sequelize directly, but due to how I've set up express. 

Let's say I have a simple authentication middleware, which looks like this (`Session` is a sequelize model):

```js
function auth(req, res, next) {
  Session.findById(req.headers.sessionid).then((session) => {
    req.currentSession = session;
    next();
  }).catch(next);
}
```

Now if I make any sequelize calls later on in the request lifecycle, I get the error:

    Warning: a promise was created in a  handler but was not returned from it

(also, for some reason with no stacktrace, which is annoying)

I fixed this for now by adding `return null` right below my `next()` call, but this seems like a problem that many people will run into, with a fairly non-intuitive solution. I'm not sure whether there is a "more-correct" way to be pre-loading models in express, although I suppose you folks aren't the right people to ask. But is there a way to silence these bluebird warnings altogether for sequelize? They don't seem like a useful feature for library code that I am not working with directly.

**Comment by faceleg** [comment]
Personally I think it *is* a useful feature, especially since it helped me find a bug lurking in my code that I would never have noticed before.

I do agree that the solution is not intuitive and that it is often difficult (read: impossible for mortals) to understand exactly where the **&^ this naughty handler is.

Your example almost exactly matches the example given in the bluebird docs:

```JS
getUser().then(function(user) {
    // Perform this in the "background" and don't care about it's result at all
    saveAnalytics(user);
    // return a non-undefined value to signal that we didn't forget to return
    return null;
});
```

**Comment by adrianmacneil** [comment]
I think it would be useful as explicitly opt-in behavior (during testing maybe). I think though that as someone who is fairly new to sequelize (and using es6 promises in my own code), I should really not have to understand peculiarities of bluebird (e.g. inserting `return null` in random places) to use sequelize.

It would be different of course if I had chosen to use bluebird in my own code, then I would expect possible implementation quirks or to have to read their docs when I see a warning.

Are there any thoughts on moving a future version of sequelize to native es6 promises, and either ship with a polyfill, or ask people to bring their own polyfill if they are using node < v4.0?

**Comment by faceleg** [comment]
It is probably worth taking the opt-in questions to bluebird as sequelize has no control over what the bluebird devs may or may not include

**Comment by mickhansen** [comment]
Sequelize currently relies on a great deal of features that native es6 promises don't support.
There are also performance issues to consider (although different benchmarks report different things).

**Comment by faceleg** [comment]
My opinion is that the correct approach is to 

1. Fix issues in sequelize highlighted by the new bluebird warnings
2. Fix issues in userland 
3. Enjoy coding in a more predictable environment.

**Comment by theptrk** [comment]
@faceleg How are you going about fixing just the postgres dialect? I'm trying to trace the error but it seems like all the promise returns are covered.

**Comment by faceleg** [comment]
I've done nothing more than what has been committed here - the fixes in this PR reduced the output such that my builds would pass (CircleCi kills a build if it generates too much output). 

The current output is annoying but doesn't break my builds, which drops the priority for me.

**Comment by citium** [comment]
Placing `return null` after /sequelize/lib/dialects/abstract/connection-manager.js:223:16 seem to resolve the disconnect with `Warning: a promise was created in a  handler but was not returned from it`

**Comment by faceleg** [comment]
PR! PR! PR please for the love of no warnings

**Comment by theptrk** [comment]
Haha, looks like you PR'd it into master so.... soon? Not sure how versioning works. 
https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/connection-manager.js#L227

**Comment by faceleg** [comment]
Oh, right. I know for a fact that I've missed some - all this PR did was stop my CircleCi builds from failing :+1:

**Comment by mbmccoy** [comment]
FWIW, this issue is breaking my server tests when I test Sequelize creation following the [example](https://github.com/sequelize/express-example/blob/master/test/unit/task.test.js).  (Mocha aborts due to warnings.)

I can work around this, but I want to emphasize that this issue impacts to my workflow to encourage a fix (and thank you for the work).

**Comment by theptrk** [comment]
Oh yeah, I've had to move to testing locally.

**Comment by mickhansen** [comment]
The latest version has the fixes we've applied so far.
Please provide file location or PR's with fixes.

**Comment by tremby** [comment]
I have one of these too.

Sequelize 3.19.3, using Mysql.

```
Warning: a promise was created in a handler but was not returned from it
  at [object Object].Instance.save (/home/tremby/myproject/node_modules/sequelize/lib/instance.js:567:18)
  at [object Object].Model.create (/home/tremby/myproject/node_modules/sequelize/lib/model.js:1824:6)
  at [object Object].HasMany.create (/home/tremby/myproject/node_modules/sequelize/lib/associations/has-many.js:533:29)
  at [object Object].obj.(anonymous function) [as createGameSession] (/home/tremby/myproject/node_modules/sequelize/lib/associations/has-many.js:259:24)
  at done (/home/tremby/myproject/src/app/routes/myroute.coffee:43:10)
  at [object Object].<anonymous> (/home/tremby/myproject/src/app/routes/myroute.coffee:58:7)
  at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
  at Promise.then (/home/tremby/myproject/node_modules/sequelize/lib/promise.js:21:17)
  at /home/tremby/myproject/src/app/routes/myroute.coffee:56:6
  at Layer.handle [as handle_request] (/home/tremby/myproject/node_modules/express/lib/router/layer.js:95:5)
  at next (/home/tremby/myproject/node_modules/express/lib/router/route.js:131:13)
  at Route.dispatch (/home/tremby/myproject/node_modules/express/lib/router/route.js:112:3)
  at Layer.handle [as handle_request] (/home/tremby/myproject/node_modules/express/lib/router/layer.js:95:5)
  at /home/tremby/myproject/node_modules/express/lib/router/index.js:277:22
  at Function.process_params (/home/tremby/myproject/node_modules/express/lib/router/index.js:330:12)
  at next (/home/tremby/myproject/node_modules/express/lib/router/index.js:271:10)
  at Function.handle (/home/tremby/myproject/node_modules/express/lib/router/index.js:176:3)
  at router (/home/tremby/myproject/node_modules/express/lib/router/index.js:46:12)
  at Layer.handle [as handle_request] (/home/tremby/myproject/node_modules/express/lib/router/layer.js:95:5)
  at trim_prefix (/home/tremby/myproject/node_modules/express/lib/router/index.js:312:13)
  at /home/tremby/myproject/node_modules/express/lib/router/index.js:280:7
  at Function.process_params (/home/tremby/myproject/node_modules/express/lib/router/index.js:330:12)
  at next (/home/tremby/myproject/node_modules/express/lib/router/index.js:271:10)
  at /home/tremby/myproject/node_modules/express/lib/router/index.js:618:15
  at next (/home/tremby/myproject/node_modules/express/lib/router/index.js:256:14)
  at Function.handle (/home/tremby/myproject/node_modules/express/lib/router/index.js:176:3)
  at router (/home/tremby/myproject/node_modules/express/lib/router/index.js:46:12)
  at Layer.handle [as handle_request] (/home/tremby/myproject/node_modules/express/lib/router/layer.js:95:5)
  at trim_prefix (/home/tremby/myproject/node_modules/express/lib/router/index.js:312:13)
  at /home/tremby/myproject/node_modules/express/lib/router/index.js:280:7
  at Function.process_params (/home/tremby/myproject/node_modules/express/lib/router/index.js:330:12)
  at next (/home/tremby/myproject/node_modules/express/lib/router/index.js:271:10)
  at /home/tremby/myproject/node_modules/express/lib/application.js:232:9
  at /home/tremby/myproject/node_modules/express/lib/router/index.js:618:15
  at next (/home/tremby/myproject/node_modules/express/lib/router/index.js:256:14)
  at expressInit (/home/tremby/myproject/node_modules/express/lib/middleware/init.js:33:5)
  at Layer.handle [as handle_request] (/home/tremby/myproject/node_modules/express/lib/router/layer.js:95:5)
  at trim_prefix (/home/tremby/myproject/node_modules/express/lib/router/index.js:312:13)
  at /home/tremby/myproject/node_modules/express/lib/router/index.js:280:7
  at Function.process_params (/home/tremby/myproject/node_modules/express/lib/router/index.js:330:12)
  at next (/home/tremby/myproject/node_modules/express/lib/router/index.js:271:10)
  at query (/home/tremby/myproject/node_modules/express/lib/middleware/query.js:49:5)
  at Layer.handle [as handle_request] (/home/tremby/myproject/node_modules/express/lib/router/layer.js:95:5)
  at trim_prefix (/home/tremby/myproject/node_modules/express/lib/router/index.js:312:13)
  at /home/tremby/myproject/node_modules/express/lib/router/index.js:280:7
  at Function.process_params (/home/tremby/myproject/node_modules/express/lib/router/index.js:330:12)
  at next (/home/tremby/myproject/node_modules/express/lib/router/index.js:271:10)
  at Function.handle (/home/tremby/myproject/node_modules/express/lib/router/index.js:176:3)
  at EventEmitter.handle (/home/tremby/myproject/node_modules/express/lib/application.js:173:10)
  at mounted_app (/home/tremby/myproject/node_modules/express/lib/application.js:229:10)
  at Layer.handle [as handle_request] (/home/tremby/myproject/node_modules/express/lib/router/layer.js:95:5)
  at trim_prefix (/home/tremby/myproject/node_modules/express/lib/router/index.js:312:13)
  at /home/tremby/myproject/node_modules/express/lib/router/index.js:280:7
  at Function.process_params (/home/tremby/myproject/node_modules/express/lib/router/index.js:330:12)
  at next (/home/tremby/myproject/node_modules/express/lib/router/index.js:271:10)
  at session (/home/tremby/myproject/node_modules/express-session/index.js:397:7)
  at Layer.handle [as handle_request] (/home/tremby/myproject/node_modules/express/lib/router/layer.js:95:5)
  at trim_prefix (/home/tremby/myproject/node_modules/express/lib/router/index.js:312:13)
  at /home/tremby/myproject/node_modules/express/lib/router/index.js:280:7
  at Function.process_params (/home/tremby/myproject/node_modules/express/lib/router/index.js:330:12)
  at next (/home/tremby/myproject/node_modules/express/lib/router/index.js:271:10)
  at serveStatic (/home/tremby/myproject/node_modules/serve-static/index.js:74:16)
  at Layer.handle [as handle_request] (/home/tremby/myproject/node_modules/express/lib/router/layer.js:95:5)
  at trim_prefix (/home/tremby/myproject/node_modules/express/lib/router/index.js:312:13)
  at /home/tremby/myproject/node_modules/express/lib/router/index.js:280:7
  at Function.process_params (/home/tremby/myproject/node_modules/express/lib/router/index.js:330:12)
  at next (/home/tremby/myproject/node_modules/express/lib/router/index.js:271:10)
  at cacheResponseDirectiveMiddleware (/home/tremby/myproject/node_modules/express-cache-response-directive/index.js:218:3)
  at Layer.handle [as handle_request] (/home/tremby/myproject/node_modules/express/lib/router/layer.js:95:5)
  at trim_prefix (/home/tremby/myproject/node_modules/express/lib/router/index.js:312:13)
  at /home/tremby/myproject/node_modules/express/lib/router/index.js:280:7
  at Function.process_params (/home/tremby/myproject/node_modules/express/lib/router/index.js:330:12)
  at next (/home/tremby/myproject/node_modules/express/lib/router/index.js:271:10)
  at cookieParser (/home/tremby/myproject/node_modules/cookie-parser/index.js:56:14)
  at Layer.handle [as handle_request] (/home/tremby/myproject/node_modules/express/lib/router/layer.js:95:5)
  at trim_prefix (/home/tremby/myproject/node_modules/express/lib/router/index.js:312:13)
  at /home/tremby/myproject/node_modules/express/lib/router/index.js:280:7
  at Function.process_params (/home/tremby/myproject/node_modules/express/lib/router/index.js:330:12)
  at next (/home/tremby/myproject/node_modules/express/lib/router/index.js:271:10)
  at /home/tremby/myproject/node_modules/body-parser/lib/read.js:129:5
  at invokeCallback (/home/tremby/myproject/node_modules/raw-body/index.js:262:16)
  at done (/home/tremby/myproject/node_modules/raw-body/index.js:251:7)
  at IncomingMessage.onEnd (/home/tremby/myproject/node_modules/raw-body/index.js:308:7)
  at emitNone (events.js:67:13)
  at IncomingMessage.emit (events.js:166:7)
  at endReadableNT (_stream_readable.js:905:12)
  at nextTickCallbackWith2Args (node.js:474:9)
  at process._tickCallback (node.js:388:17)
```

**Comment by Bondifrench** [comment]
I have got the same problem in Postgres and Sequelize 3.19.3:

Warning: a promise was created in a handler but was not returned from it                                                 
    at processImmediate [as _immediateCallback] (timers.js:383:17)                                                       
From previous event:                                                                                                     
    at Model.findAll (c:\Users\London\Apps\FinviewsApp\node_modules\Sequelize\lib\model.js:1343:18)                      
    at c:\Users\London\Apps\FinviewsApp\routes\api.js:486:16                                                             
    at Layer.handle [as handle_request] (c:\Users\London\Apps\FinviewsApp\node_modules\express\lib\router\layer.js:76:5) 
    at next (c:\Users\London\Apps\FinviewsApp\node_modules\express\lib\router\route.js:100:13)                           
    at Route.dispatch (c:\Users\London\Apps\FinviewsApp\node_modules\express\lib\router\route.js:81:3)                   
    at Layer.handle [as handle_request] (c:\Users\London\Apps\FinviewsApp\node_modules\express\lib\router\layer.js:76:5) 
    at c:\Users\London\Apps\FinviewsApp\node_modules\express\lib\router\index.js:234:24                                  
    at Function.proto.process_params (c:\Users\London\Apps\FinviewsApp\node_modules\express\lib\router\index.js:312:12)  
    at c:\Users\London\Apps\FinviewsApp\node_modules\express\lib\router\index.js:228:12                                  
    at Function.match_layer (c:\Users\London\Apps\FinviewsApp\node_modules\express\lib\router\index.js:295:3)            
    at next (c:\Users\London\Apps\FinviewsApp\node_modules\express\lib\router\index.js:189:10)                           
    at c:\Users\London\Apps\FinviewsApp\node_modules\express\lib\router\index.js:191:16                                  
    at Function.match_layer (c:\Users\London\Apps\FinviewsApp\node_modules\express\lib\router\index.js:295:3)            
    at next (c:\Users\London\Apps\FinviewsApp\node_modules\express\lib\router\index.js:189:10)                           
    at c:\Users\London\Apps\FinviewsApp\node_modules\express\lib\router\index.js:191:16                                  
    at Function.match_layer (c:\Users\London\Apps\FinviewsApp\node_modules\express\lib\router\index.js:295:3)            
    at next (c:\Users\London\Apps\FinviewsApp\node_modules\express\lib\router\index.js:189:10)                           
    at c:\Users\London\Apps\FinviewsApp\node_modules\express\lib\router\index.js:191:16                                  
From previous event:                                                                                                     
    at Promise.then (c:\Users\London\Apps\FinviewsApp\node_modules\Sequelize\lib\promise.js:21:17)                       
    at c:\Users\London\Apps\FinviewsApp\config\passport.js:21:5                                                          
    at pass (c:\Users\London\Apps\FinviewsApp\node_modules\passport\lib\authenticator.js:353:9)                          
    at Authenticator.deserializeUser (c:\Users\London\Apps\FinviewsApp\node_modules\passport\lib\authenticator.js:358:5) 
    at SessionStrategy.authenticate (c:\Users\London\Apps\FinviewsApp\node_modules\passport\lib\strategies\session.js:49:
    at attempt (c:\Users\London\Apps\FinviewsApp\node_modules\passport\lib\middleware\authenticate.js:341:16)            
    at authenticate (c:\Users\London\Apps\FinviewsApp\node_modules\passport\lib\middleware\authenticate.js:342:7)        
    at Layer.handle [as handle_request] (c:\Users\London\Apps\FinviewsApp\node_modules\express\lib\router\layer.js:76:5) 
    at trim_prefix (c:\Users\London\Apps\FinviewsApp\node_modules\express\lib\router\index.js:270:13)                    
    at c:\Users\London\Apps\FinviewsApp\node_modules\express\lib\router\index.js:237:9                                   
    at Function.proto.process_params (c:\Users\London\Apps\FinviewsApp\node_modules\express\lib\router\index.js:312:12)  
    at c:\Users\London\Apps\FinviewsApp\node_modules\express\lib\router\index.js:228:12                                  
    at Function.match_layer (c:\Users\London\Apps\FinviewsApp\node_modules\express\lib\router\index.js:295:3)            
    at next (c:\Users\London\Apps\FinviewsApp\node_modules\express\lib\router\index.js:189:10)                           
    at initialize (c:\Users\London\Apps\FinviewsApp\node_modules\passport\lib\middleware\initialize.js:62:5)             
    at Layer.handle [as handle_request] (c:\Users\London\Apps\FinviewsApp\node_modules\express\lib\router\layer.js:76:5) 
    at trim_prefix (c:\Users\London\Apps\FinviewsApp\node_modules\express\lib\router\index.js:270:13)                    
    at c:\Users\London\Apps\FinviewsApp\node_modules\express\lib\router\index.js:237:9                                   
    at Function.proto.process_params (c:\Users\London\Apps\FinviewsApp\node_modules\express\lib\router\index.js:312:12)

**Comment by faceleg** [comment]
Cursory glances through https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1345 don't reveal a reason.

Are you sure you're returning from any `then` you're using in your code?

**Comment by tremby** [comment]
Not sure if you're talking to one or the other of us, or both, but I'm afraid I have no recollection what I was doing at the time to get the message I did, so I'll bow out of this.

**Comment by faceleg** [comment]
@mickhansen recommend this thread is locked with a comment sending people to the Bluebird 3.0 docs regarding this new warning.

**Comment by amacneil** [comment]
@faceleg agree that it's turning into a bit of a general support thread, but I still view this as something that should be fixed in sequelize, because an implementation detail is exposing hard-to-diagnose errors which we would not otherwise see (and has forced me to put pointless `return null` statements in my code to avoid it).

I think it would be best if sequelize could either disable this error, or not depend on a promise library which throws warnings for perfectly valid code.

**Comment by faceleg** [comment]
I disagree. The warning was added to Bluebird to save us from wasting time debugging issues caused when we *forget* to return from a promise.

If Bluebird adds an option to disable it, it should be up to the end-developers to decide if they want it off.

We have done our best to resolve this issue in sequelize, if a programmer using sequelize is getting this warning, it is very likely that the issue is with their code, not this library.

**Comment by amacneil** [comment]
Right, but as my example further up pointed out, this warning is triggered very easily if you ever use Sequelize inside an express middleware (very common scenario). In this case it's not programmer error or an issue with their code, and many people using Sequelize may not even be aware that they are using Bluebird underneath. Hence why they are googling the error and landing here.

If we're not going to disable the warnings, then it might be worth at least adding a page to the Sequelize docs explaining that using Sequelize inside express middleware will cause Bluebird warnings, and explain how to work around it. Just forwarding people to the Bluebird docs will only lead to more confusion.

**Comment by faceleg** [comment]
> using Sequelize inside express middleware will cause Bluebird warnings

Not returning null from the final `.then` callback is what will cause warnings, nothing to do with middleware.

> many people using Sequelize may not even be aware that it's using Bluebird underneath

When incorporating libs into code that is intended to be used in production, it is my opinion that it is the responsibility of the lead developer to ensure they understand at least the first-level dependencies of said libs.

Agree the docs could be updated to point to http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-none-were-returned-from-it

Also the no stack trace was a bug and should have been fixed: https://github.com/petkaantonov/bluebird/issues/846

**Comment by amacneil** [comment]
> Not returning null from the final .then callback is what will cause warnings, nothing to do with middleware.

Sure, but that's not something I would normally do inside express middleware.

Honestly it doesn't sound like I'm going to be able to convince you that this is confusing and hard to debug for people. I think this is a leaky abstraction - people shouldn't need to spend time understanding implementation details of libraries before they can use them. Even that page you linked to does nothing to explain why Bluebird would interact badly with non-promise aware libraries like express.

---

Anyway, in case it gets locked, hopefully there is enough detail in this thread to help future googlers:

All of the warnings being generated from within Sequelize have now been fixed. To avoid the error, try just putting `return null` anywhere you are using Sequelize promises (especially when mixing them with callbacks):

Before:

```
function auth(req, res, next) {
  Session.findById(req.headers.sessionid).then((session) => {
    req.currentSession = session;
    next();
  }).catch(next);
}
```

After:

```
function auth(req, res, next) {
  Session.findById(req.headers.sessionid).then((session) => {
    req.currentSession = session;
    next();
    return null;
  }).catch(next);
}
```

**Comment by mickhansen** [comment]
@amacneil I agree it's hard to debug, but disabling the warnings is out of our control.
We'll have to make an effort to get the "answer" high up there when people search for it.

**Comment by mickhansen** [comment]
Environment variables for disabling warnings: http://bluebirdjs.com/docs/api/environment-variables.html
