### ISSUE TITLE
npm run test-docker fails on sqlite3 tests

### ISSUE THREAD

**Issue by alexschneider** [sequelize/sequelize#4887]
I'm trying to fix an issue and I'm finding that doing `npm run test-docker` fails with the following:

```

> sequelize@3.14.0 test-docker /home/alex/git/sequelize
> docker-compose run sequelize /bin/sh -c "make all"

make[1]: Entering directory '/sequelize'
make jshint && make teaser && make test-unit && make test-integration
make[2]: Entering directory '/sequelize'
/node_modules/.bin/jshint lib test
make[2]: Leaving directory '/sequelize'
make[2]: Entering directory '/sequelize'

############################
# Running tests for sqlite #
############################

make[2]: Leaving directory '/sequelize'
make[2]: Entering directory '/sequelize'
/node_modules/.bin/mocha --globals setImmediate,clearImmediate --ui tdd --check-leaks --colors -t 15000 --reporter spec ./test/unit/*.js ./test/unit/**/*.js
An unhandled exception occured:
/sequelize/test/support.js:23
  throw e;
        ^
Error: The dialect sqlite is not supported. Supported dialects: mariadb, mssql, mysql, postgres, and sqlite. (Error: Please install sqlite3 package manually)
    at new Sequelize (/sequelize/lib/sequelize.js:205:11)
    at Object.Support.getSequelizeInstance (/sequelize/test/support.js:116:12)
    at Object.Support.createSequelizeInstance (/sequelize/test/support.js:110:17)
    at Object.<anonymous> (/sequelize/test/support.js:224:29)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:428:10)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
    at Module.require (module.js:345:17)
    at require (module.js:364:17)
    at Object.<anonymous> (/sequelize/test/unit/support.js:1:80)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:428:10)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
    at Module.require (module.js:345:17)
    at require (module.js:364:17)
    at Object.<anonymous> (/sequelize/test/unit/hooks.test.js:7:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:428:10)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
    at Module.require (module.js:345:17)
    at require (module.js:364:17)
    at /node_modules/mocha/lib/mocha.js:216:27
    at Array.forEach (native)
    at Mocha.loadFiles (/node_modules/mocha/lib/mocha.js:213:14)
    at Mocha.run (/node_modules/mocha/lib/mocha.js:453:10)
    at Object.<anonymous> (/node_modules/mocha/bin/_mocha:393:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:428:10)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
    at Function.Module.runMain (module.js:451:10)
    at startup (node.js:124:18)
    at node.js:868:3
Makefile:25: recipe for target 'test-unit' failed
make[2]: *** [test-unit] Error 7
make[2]: Leaving directory '/sequelize'
Makefile:20: recipe for target 'test' failed
make[1]: *** [test] Error 2
make[1]: Leaving directory '/sequelize'
Makefile:72: recipe for target 'sqlite' failed
make: *** [sqlite] Error 2

npm ERR! Linux 4.2.5-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "test-docker"
npm ERR! node v5.1.0
npm ERR! npm  v3.4.0
npm ERR! code ELIFECYCLE
npm ERR! sequelize@3.14.0 test-docker: `docker-compose run sequelize /bin/sh -c "make all"`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the sequelize@3.14.0 test-docker script 'docker-compose run sequelize /bin/sh -c "make all"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sequelize package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     docker-compose run sequelize /bin/sh -c "make all"
npm ERR! You can get their info via:
npm ERR!     npm owner ls sequelize
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/alex/git/sequelize/npm-debug.log
```

Running npm test seems to work properly, but doesn't test mysql/postgres as expected. 

I've tried running `npm install sqlite3` in the sequelize directory, but that doesn't have any effect

**Comment by mickhansen** [comment]
You either need to npm install in docker, or npm install user side and make sure the node versions inside and out of docker are the same.
