### ISSUE TITLE
A promise warning is always printed out in the server log file.

### ISSUE THREAD

**Issue by stuartZhang** [sequelize/sequelize#4921]
Hello experts,

After I upgrade the Sequelize from 3.13.0 to 3.14.1, the below warning is outputted into the server log file. However, all my promises have been returned in my program.

Do you know how to disable the warning?

Warning: a promise was created in a  handler but was not returned from it
    at ConnectionManager.disconnect (/home/stzhang/var/webapps/connect/main/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:126:10)
    at ConnectionManager.$disconnect (/home/stzhang/var/webapps/connect/main/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:257:41)
    at /home/stzhang/var/webapps/connect/main/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:223:16
From previous event:
    at Promise.then (/home/stzhang/var/webapps/connect/main/node_modules/sequelize/lib/promise.js:21:17)
    at ConnectionManager.getConnection (/home/stzhang/var/webapps/connect/main/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:212:66)
    at Transaction.prepareEnvironment (/home/stzhang/var/webapps/connect/main/node_modules/sequelize/lib/transaction.js:182:103)
    at transactionResolver (/home/stzhang/var/webapps/connect/main/node_modules/sequelize/lib/sequelize.js:1221:19)
    at /home/stzhang/var/webapps/connect/main/node_modules/continuation-local-storage/context.js:74:17
From previous event:
    at Sequelize.transaction (/home/stzhang/var/webapps/connect/main/node_modules/sequelize/lib/sequelize.js:1250:12)
    at null.<anonymous> (/home/stzhang/var/webapps/connect/main/controller/subcontroller/device_user_controller.js:29:26)
    at Function.<anonymous> (/home/stzhang/var/webapps/connect/main/lib/q.js:134:52)
    at registerDevice (/home/stzhang/var/webapps/connect/main/controller/subcontroller/device_user_controller.js:28:18)
    at module.exports.Object.create.handleMessage.value [as handleMessage] (/home/stzhang/var/webapps/connect/main/controller/subcontroller/device_user_controller.js:504:37)
    at handleMessage (/home/stzhang/var/webapps/connect/main/controller/index.js:73:42)
    at Socket.onMessage (/home/stzhang/var/webapps/connect/main/routes/socket/index.js:38:15)
    at Socket.emit (events.js:110:17)
    at Socket.onevent (/home/stzhang/var/webapps/connect/main/node_modules/socket.io/lib/socket.js:330:8)
    at Socket.onpacket (/home/stzhang/var/webapps/connect/main/node_modules/socket.io/lib/socket.js:290:12)
    at Client.ondecoded (/home/stzhang/var/webapps/connect/main/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/home/stzhang/var/webapps/connect/main/node_modules/socket.io/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/home/stzhang/var/webapps/connect/main/node_modules/socket.io/node_modules/socket.io-parser/index.js:247:12)
    at Client.ondata (/home/stzhang/var/webapps/connect/main/node_modules/socket.io/lib/client.js:175:18)
    at Socket.emit (events.js:107:17)
    at Socket.onPacket (/home/stzhang/var/webapps/connect/main/node_modules/socket.io/node_modules/engine.io/lib/socket.js:99:14)
    at XHR.emit (events.js:107:17)
    at XHR.Transport.onPacket (/home/stzhang/var/webapps/connect/main/node_modules/socket.io/node_modules/engine.io/lib/transport.js:91:8)
    at callback (/home/stzhang/var/webapps/connect/main/node_modules/socket.io/node_modules/engine.io/lib/transports/polling.js:202:10)
    at Object.exports.decodePayload (/home/stzhang/var/webapps/connect/main/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js:320:19)
    at XHR.Polling.onData (/home/stzhang/var/webapps/connect/main/node_modules/socket.io/node_modules/engine.io/lib/transports/polling.js:205:10)
    at IncomingMessage.onEnd (/home/stzhang/var/webapps/connect/main/node_modules/socket.io/node_modules/engine.io/lib/transports/polling.js:158:10)
    at IncomingMessage.emit (events.js:104:17)
    at _stream_readable.js:908:16
    at /home/stzhang/var/webapps/connect/main/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31

**Comment by stuartZhang** [comment]
I have just discovered where the warnings come from:

An anonymous function from 218 to 225 lines in ${project_base}/lib/dialects/abstract/connection-manager.js 
      A statement "return null;" is omitted.

According to the BlueBird documentation (https://github.com/petkaantonov/bluebird/blob/master/docs/docs/warning-explanations.md#warning-a-promise-was-created-in-a-handler-but-none-were-returned-from-it), a NULL is returned manually to avoid the warning.

**Comment by mickhansen** [comment]
Known issue with bluebird upgrade. PR for fixes welcome :)

**Comment by lumberj** [comment]
Was there a PR to fix this?

**Comment by mickhansen** [comment]
@lumberj The easy ones yes, are still a few left.

**Comment by renak** [comment]
The .getAssociations function is still causing this warning. 
http://docs.sequelizejs.com/en/latest/api/associations/has-many/

**Comment by tony-gutierrez** [comment]
Think there is one around has-many as well. See this stack trace a lot:
```
    at Model.findAll (/node_modules/sequelize/lib/model.js:1347:18)
    at HasMany.get (/node_modules/sequelize/lib/associations/has-many.js:322:16)
    at obj.(anonymous function) [as getInvites] (/node_modules/sequelize/lib/associations/has-many.js:233:24)
```

**Comment by tybro0103** [comment]
In case someone else runs into the thing that led me here...

I ran into this message by doing `return next();` inside a sequelize promise inside an express middleware:

```
app.use((req, res, next) => {
  User.findById(req.session.userId).then((user) => {
    res.locals.currentUser = user;
    if (foo) return next();
    bar();
  });
});
```

Wasn't super obvious because it is valid code, but easy enough to fix:
```
next();
return null;
// or
const nullify = () => null;
return nullify(next());
```
