### ISSUE TITLE
a promise was created in a  handler but was not returned from it

### ISSUE THREAD

**Issue by nikolay211** [sequelize/sequelize#4926]
Hi, 

I'm using sequelize in mean stack project started from generator-angular-fullstack. 
In seed.js, I found a warning in module when I run Product.sync().then(function() { ... });
Can someone please check it ?

Warning: a promise was created in a  handler but was not returned from it
    at [object Object].ConnectionManager.disconnect (/Volumes/DATA/projects/groupselz_app/groupselz/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:162:10)
    at [object Object].ConnectionManager.$disconnect (/Volumes/DATA/projects/groupselz_app/groupselz/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:257:41)
    at /Volumes/DATA/projects/groupselz_app/groupselz/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:223:16
From previous event:
    at Promise.then (/Volumes/DATA/projects/groupselz_app/groupselz/node_modules/sequelize/lib/promise.js:21:17)
    at [object Object].Model.sync (/Volumes/DATA/projects/groupselz_app/groupselz/node_modules/sequelize/lib/model.js:976:6)
    at Object.<anonymous> (/Volumes/DATA/projects/groupselz_app/groupselz/server/config/seed.js:13:6)
    at Module._compile (module.js:425:26)
    at normalLoader (/Volumes/DATA/projects/groupselz_app/groupselz/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Volumes/DATA/projects/groupselz_app/groupselz/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Volumes/DATA/projects/groupselz_app/groupselz/server/app.js:14:22)
    at Module._compile (module.js:425:26)
    at normalLoader (/Volumes/DATA/projects/groupselz_app/groupselz/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Volumes/DATA/projects/groupselz_app/groupselz/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Volumes/DATA/projects/groupselz_app/groupselz/server/index.js:12:28)

**Comment by janmeier** [comment]
Yes, we are aware of it - please check for existing issues before opening new ones https://github.com/sequelize/sequelize/issues/4883 https://github.com/sequelize/sequelize/issues/4921
