### ISSUE TITLE
How to reference other models in model?

### ISSUE THREAD

**Issue by poyannabati** [sequelize/sequelize#4941]
Hi, 

In my previous projects, a common pattern we've used has been to use instances of a model to hold data, and class methods of the same model to retreive instances of that model. 

Now, I'm trying to apply the same pattern to my Sequelize models, but I've run into some issues. My guess is that it's got something to do with how the other models are referenced. Any ideas on how to solve this?

In my Poll.js I have 

    var Sequelize = require('sequelize');
    var models = require('./index.js');
    var Poll = function (sequelize) {
        var Poll = sequelize.define('poll', {
                id: {
                    type: Sequelize.UUID,
                    defaultValue: Sequelize.UUIDV4,
                    primaryKey: true
                }
            }, {
                underscored: true,
                classMethods: {
                    getPollWithStatistics: function(pollId) {
                        return Poll.find({
                            where: {
                                id: pollId
                            },
                            include: [
                                {
                                    model: 'User',
                                },
                                {
                                    model: models.Image,
                                    where: {
                                        poll_id: pollId
                                    },
                                    include: [
                                        {
                                            model: models.Vote,
                                        }
                                    ]
                                }
                            ]
                        });
                    }
                }
            }
        );
        return Poll;
    };
    module.exports = Poll;

This doesn't seem to be working, as a I get something along the lines of; 

    Unhandled rejection TypeError: self.$expandAttributes is not a function
    at conformOptions (/Users/poyan/IdeaProjects/tha_node/node_modules/sequelize/lib/model.js:245:10)
    at conformInclude (/Users/poyan/IdeaProjects/tha_node/node_modules/sequelize/lib/model.js:300:5)
    at /Users/poyan/IdeaProjects/tha_node/node_modules/sequelize/lib/model.js:261:15
    at Array.map (native)
    at conformOptions (/Users/poyan/IdeaProjects/tha_node/node_modules/sequelize/lib/model.js:260:37)
    at null.<anonymous> (/Users/poyan/IdeaProjects/tha_node/node_modules/sequelize/lib/model.js:1343:5)
    at tryCatcher (/Users/poyan/IdeaProjects/tha_node/node_modules/sequelize/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/poyan/IdeaProjects/tha_node/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/poyan/IdeaProjects/tha_node/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAtPostResolution (/Users/poyan/IdeaProjects/tha_node/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:245:10)
    at Async._drainQueue (/Users/poyan/IdeaProjects/tha_node/node_modules/sequelize/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/poyan/IdeaProjects/tha_node/node_modules/sequelize/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/poyan/IdeaProjects/tha_node/node_modules/sequelize/node_modules/bluebird/js/main/async.js:15:14)

On a broader note; any suggestions on where I should look for an idea on how to move some of the retrieval / manipulation code to the models (aka fat model)?

**Comment by mickhansen** [comment]
`getPollWithStatistics` could probably be implemented as a model scope instead.
What type of object is `models`? Is it a object passed by reference that you add all models to after they are defined?
Does index.js include the poll model? (is there a circular reference)

**Comment by poyannabati** [comment]
From my understanding, scopes seem to be a less flexible way of doing what I'm looking to do, or I have misunderstood their use, which was essentially to encapsulate and abstract some of the DB-manipulation logic in separate methods. 

This ticket can be closed. For future Googlers, I chose to go the path of defining a separate class PollRepository for which I define my common methods.

**Comment by mickhansen** [comment]
A primary usecase of scopes is to have a shorthand for common cases.
