### ISSUE TITLE
Deprecation warning: moment construction falls back to js Date.

### ISSUE THREAD

**Issue by alexbeletsky** [sequelize/sequelize#4954]
Moment.js constuctor function now gives a warning about depricated constuction, resulted in such log message,

```
Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
Error
    at Function.createFromInputFallback (/Users/alexanderbeletsky/Development/Projects/blogfoster/api/node_modules/moment/moment.js:746:36)
    at configFromString (/Users/alexanderbeletsky/Development/Projects/blogfoster/api/node_modules/moment/moment.js:826:32)
    at configFromInput (/Users/alexanderbeletsky/Development/Projects/blogfoster/api/node_modules/moment/moment.js:1353:13)
    at prepareConfig (/Users/alexanderbeletsky/Development/Projects/blogfoster/api/node_modules/moment/moment.js:1340:13)
    at createFromConfig (/Users/alexanderbeletsky/Development/Projects/blogfoster/api/node_modules/moment/moment.js:1307:44)
    at createLocalOrUTC (/Users/alexanderbeletsky/Development/Projects/blogfoster/api/node_modules/moment/moment.js:1385:16)
    at local__createLocal (/Users/alexanderbeletsky/Development/Projects/blogfoster/api/node_modules/moment/moment.js:1389:16)
    at utils_hooks__hooks (/Users/alexanderbeletsky/Development/Projects/blogfoster/api/node_modules/moment/moment.js:16:29)
    at [object Object].DATE.$applyTimezone (/Users/alexanderbeletsky/Development/Projects/blogfoster/api/node_modules/sequelize/lib/data-types.js:437:10)
    at [object Object].DATE.$stringify (/Users/alexanderbeletsky/Development/Projects/blogfoster/api/node_modules/sequelize/lib/dialects/mysql/data-types.js:38:37)
    at [object Object].ABSTRACT.stringify (/Users/alexanderbeletsky/Development/Projects/blogfoster/api/node_modules/sequelize/lib/data-types.js:62:17)
    at Object.QueryGenerator.escape (/Users/alexanderbeletsky/Development/Projects/blogfoster/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:972:32)
    at Object.QueryGenerator.whereItemQuery (/Users/alexanderbeletsky/Development/Projects/blogfoster/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2228:22)
    at /Users/alexanderbeletsky/Development/Projects/blogfoster/api/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1875:25
```

It comes from that function,

```js
DATE.prototype.$applyTimezone = function (date, options) {
  date = moment(date);

  if (options.timezone) {
    if (moment.tz.zone(options.timezone)) {
      date = date.tz(options.timezone);
    } else {
      date = date.utcOffset(options.timezone);
    }
  }

  return date;
};
```

I've placed a log there, and can see that values like `Tue Dec 01 2015 11:56:32 GMT+0100 (CET)` come as input and `moment` is complaining about.

It's applicable for all fields with `DataTypes.DATE`. 

Package.json

```json
    "moment": "^2.10.6",
    "mysql": "^2.9.0",
    "sequelize": "^3.14.2",
```

Are any way to fix that issue, by pre-formating dates to ISO format as moment currenly expects?

**Comment by alexbeletsky** [comment]
UPD: The issue came from the test data we loaded in fixtures, 

Changing it to ISO string eliminated the problem,

![screenshot 2015-12-01 12 42 40](https://cloud.githubusercontent.com/assets/304929/11499812/1d5c4872-9829-11e5-90a6-c5190cc4c67e.png)

**Comment by pietrovismara** [comment]
+1 I have the same issue actually with sequelize 3.14.2. But i can't find any test folder on the npm sequelizer package i installed.

**Comment by mickhansen** [comment]
@pietrovismara we don't publish the tests to npm, would just be cruft. You can clone or git repo though.

**Comment by Name-less** [comment]
+1 with sequelize 3.20.0 ... is that normal ?
