### ISSUE TITLE
Sequelize promises swallowing/suppressing Errors

### ISSUE THREAD

**Issue by Znarkus** [sequelize/sequelize#5009]
Hi! I have a problem with Sequelize promises swallowing/suppressing Errors in latest. This seems to be a regression from 3.2 (or later). Please see test code below.

sequelize-promise-error.js:

``` js
'use strict';

var Sequelize = require('sequelize');
var sequelize = new Sequelize('mysql://root@127.0.0.1/test');
var Promise = require('bluebird');
var _ = require('lodash');
var Company;

init().then(function() {
    Company.findAll().then(function() {
        throw new Error('Test error');
    });
});



function init() {
    Company = sequelize.define('company', {
        name: Sequelize.STRING
    });

    return sequelize.sync({ force: true })
}
```

```
$ npm i sequelize@3.2.* --save
$ node sequelize-promise-error.js
Executing (default): DROP TABLE IF EXISTS `companies`;
Executing (default): DROP TABLE IF EXISTS `companies`;
Executing (default): CREATE TABLE IF NOT EXISTS `companies` (`id` INTEGER NOT NULL auto_increment , `name` VARCHAR(255), `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `companies`
Executing (default): SELECT `id`, `name`, `createdAt`, `updatedAt` FROM `companies` AS `company`;
Unhandled rejection Error: Test error
    at null.<anonymous> (/Users/markus/www/require-test/sequelize-promise-error.js:11:15)
    at tryCatcher (/Users/markus/www/require-test/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/markus/www/require-test/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/Users/markus/www/require-test/node_modules/bluebird/js/main/promise.js:530:18)
    at Async._drainQueue (/Users/markus/www/require-test/node_modules/bluebird/js/main/async.js:182:12)
    at Async._drainQueues (/Users/markus/www/require-test/node_modules/bluebird/js/main/async.js:187:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/markus/www/require-test/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

```
$ npm i sequelize@latest --save
sequelize@3.14.2 node_modules/sequelize
$ node sequelize-promise-error.js
Executing (a958e7e4-baaa-4ac3-9d3a-2401dc41eb2f): START TRANSACTION;
Executing (a958e7e4-baaa-4ac3-9d3a-2401dc41eb2f): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (a958e7e4-baaa-4ac3-9d3a-2401dc41eb2f): SET autocommit = 1;
Executing (a958e7e4-baaa-4ac3-9d3a-2401dc41eb2f): SET FOREIGN_KEY_CHECKS = 0
Executing (a958e7e4-baaa-4ac3-9d3a-2401dc41eb2f): show tables
Executing (a958e7e4-baaa-4ac3-9d3a-2401dc41eb2f): DROP TABLE companies
Executing (a958e7e4-baaa-4ac3-9d3a-2401dc41eb2f): SET FOREIGN_KEY_CHECKS = 1
Executing (a958e7e4-baaa-4ac3-9d3a-2401dc41eb2f): COMMIT;
```

**Comment by mickhansen** [comment]
Might be related to bluebird upgrade. There's this: http://bluebirdjs.com/docs/api/suppressunhandledrejections.html but it shouldn't be enabled by default.

Can you post the bluebird version used by the two versions of Sequelize?
Eitherway i don't think you should rely on unhandled rejections.

**Comment by Znarkus** [comment]
Sequelize 3.2.0 – Bluebird ~2.9.24
Sequelize 3.14.2 – Bluebird 3.0.6

I noticed the problem in one of our test suites, which did timeout instead of failing with an error.

**Comment by mickhansen** [comment]
Your test wouldn't fail with an error even if it logs the unhandled rejection.
Your best bet is probably to have proper error handling.
Not sure why it's being supressed though.

**Comment by sushantdhiman** [comment]
It works with latest master (currently beyond `v4-02-alpha`)

**SSCCE Test**

```js
const Sequelize = require('./index');
const sequelize = require('./test/support').createSequelizeInstance();

var Company;

init().then(function() {
  Company.findAll().then(function() {
    throw new Error('Test error');
  });
});

function init() {
  Company = sequelize.define('company', {
    name: Sequelize.STRING
  });

  return sequelize.sync({ force: true });
}
```

**Output**
```js
Using database:  sequelize-test-58
An unhandled rejection occured:
An unhandled exception occured:
/var/www/github/sequelize/test/support.js:23
  throw e;
  ^

Error: Test error
    at /var/www/github/sequelize/sscce_template.js:16:11
From previous event:
    at /var/www/github/sequelize/sscce_template.js:15:21
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at Object.<anonymous> (/var/www/github/sequelize/sscce_template.js:14:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

```
