### ISSUE TITLE
ER_DUP_ENTRY will not always match `/Duplicate entry '(.*)' for key '?((.|\s)*?)'?$/`

### ISSUE THREAD

**Issue by vhain** [sequelize/sequelize#5064]
Query.prototype.formatError in lib/dialects/mysql/query.js

`err.code == 1062` ER_DUP_ENTRY will not always match `/Duplicate entry '(.*)' for key '?((.|\s)*?)'?$/`

I just got error below:

```
ER_DUP_ENTRY: ALTER TABLE causes auto_increment resequencing, resulting in duplicate entry '1' for key 'PRIMARY'
```

and

> This will happen if the table contains an existing record with an id of 0 (or negative). Updating all existing records to use positive values will allow auto_increment to be set on that column.

from http://stackoverflow.com/questions/5402949/mysql-cant-make-column-auto-increment

but with current code, following error occurs:

```
TypeError: Cannot read property '2' of null
    at Query.formatError (/dine-at-server/node_modules/sequelize/lib/dialects/mysql/query.js:125:21)
    at Query._callback (/dine-at-server/node_modules/sequelize/lib/dialects/mysql/query.js:36:21)
    at Query.Sequence.end (/dine-at-server/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query.ErrorPacket (/dine-at-server/node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
    at Protocol._parsePacket (/dine-at-server/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/dine-at-server/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/dine-at-server/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at TLSSocket.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at TLSSocket.Readable.push (_stream_readable.js:110:10)
    at TLSWrap.onread (net.js:523:20)
```

**Comment by ssteffl** [comment]
im getting the same issue, but err.message for me is just: `'ER_DUP_ENTRY: '`

**Comment by sregmip** [comment]
I am also getting the same error, err.message:<code> 'ER_DUP_ENTRY: '</code>.

**Comment by zhangshichun** [comment]
this is because that:
you save a data like 'cccc\r',so the err.message is ''Duplicate entry 'cccc\r' for key ...",then,the method match return null.
please replace('\r','') before you create()
