### ISSUE TITLE
json array error

### ISSUE THREAD

**Issue by struCoder** [sequelize/sequelize#5082]
Hi there:

In postgres i have a column and the type is json[]
 
#### this is my migration(postgres)
```javascript
...
node_info: {
  type: Sequelize.ARRAY(Sequelize.JSON)
},
token: {
   type: Sequelize.STRING(28)
}

...
```

#### and my function
```javascript

function demo(name, uuid, status) {
  const nodeInfo = {
    node_info:
      [
        JSON.stringify({
          uuid: uuid,
          status: status || 1
        })
      ]
  }

  const updateWhereQuery = {
    where: {
      name: name
    },
    raw: true
  }
  return db.Config.update(nodeInfo, updateWhereQuery);
}

```

#### but i got this error:
```
Unhandled rejection SequelizeDatabaseError: column "node_info" is of type json[] but expression is of type text[]
```

#### sequelize version
```
"pg-hstore": "^2.3.2",
"sequelize": "^3.14.2",
```

can you help me?

**Comment by janmeier** [comment]
There is no need to json stringify the data - sequelize will handle that for you.

Please show some actual sequelize code that procudes the error

**Comment by struCoder** [comment]
okay :）

when i remove stringify()


```javascript

  const nodeInfo = {
    node_info:
      [
        {
          uuid: uuid,
          status: status || 1 
        }
      ]
  }

```


sequelize will give the errors
```javascript
Unhandled rejection TypeError: val.replace is not a function
    at Object.SqlString.escape (/Users/strucoder/worker/smartstudy/project/config_server/node_modules/sequelize/lib/sql-string.js:56:15)
    at Object.wrapper [as escape] (/Users/strucoder/worker/smartstudy/project/config_server/node_modules/sequelize/node_modules/lodash/index.js:3533:19)
    at null.<anonymous> (/Users/strucoder/worker/smartstudy/project/config_server/node_modules/sequelize/lib/dialects/postgres/data-types.js:352:22)
    at Array.map (native)
    at BaseTypes.ARRAY.$stringify (/Users/strucoder/worker/smartstudy/project/config_server/node_modules/sequelize/lib/dialects/postgres/data-types.js:344:33)
    at ABSTRACT.stringify (/Users/strucoder/worker/smartstudy/project/config_server/node_modules/sequelize/lib/data-types.js:62:17)
    at Object.SqlString.escape (/Users/strucoder/worker/smartstudy/project/config_server/node_modules/sequelize/lib/sql-string.js:47:40)
    at Object.QueryGenerator.escape (/Users/strucoder/worker/smartstudy/project/config_server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:983:22)
    at Object.QueryGenerator.updateQuery (/Users/strucoder/worker/smartstudy/project/config_server/node_modules/sequelize/lib/dialects/abstract/query-generator.js:473:58)
    at QueryInterface.bulkUpdate (/Users/strucoder/worker/smartstudy/project/config_server/node_modules/sequelize/lib/query-interface.js:594:33)
    at /Users/strucoder/worker/smartstudy/project/config_server/node_modules/sequelize/lib/model.js:2537:32
    at tryCatcher (/Users/strucoder/worker/smartstudy/project/config_server/node_modules/sequelize/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/Users/strucoder/worker/smartstudy/project/config_server/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:489:31)
    at Promise._settlePromise (/Users/strucoder/worker/smartstudy/project/config_server/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:546:18)
    at Promise._settlePromise0 (/Users/strucoder/worker/smartstudy/project/config_server/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:591:10)
    at Promise._settlePromises (/Users/strucoder/worker/smartstudy/project/config_server/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:674:18)

```


#### this sql was succes

```sql
 UPDATE "ss_config" SET "node_info"=array['{"test": 1}'::json],"updated_at"='2015-12-21 10:40:28.778 +00:00' WHERE "name" = '1234'
```

**Comment by janmeier** [comment]
Please show the model definition and the code that calls update, so we can replicate the issue

**Comment by struCoder** [comment]
okay

```javascript

'use strict';

module.exports = {
  up: function (queryInterface, Sequelize) {
    return queryInterface.createTable('ss_config', {
      id: {
        type: Sequelize.INTEGER,
        allowNull: false,
        autoIncrement: true,
        primaryKey: true
      },
      config: {
        type: Sequelize.JSON,
        defaultValue: {}
      },
      name: {
        type: Sequelize.STRING(100)
      },
      node_info: {
        type: Sequelize.ARRAY(Sequelize.JSON)
      },
      token: {
        type: Sequelize.STRING(28)
      },
      created_at: {
        type: Sequelize.DATE
      },
      updated_at: {
        type: Sequelize.DATE
      }
    })
  },

  down: function (queryInterface, Sequelize) {
    return queryInterface.dropTable('ss_config');
  }
};
```
connectionHandle.prototype.dealNode = function(name, uuid, status) {
  const nodeInfo = {
    node_info:
      [
        {
          uuid: uuid,
          status: status || 1  //1存活 0: 停止
        }
      ]
  }
// nodeInfo.node_info = JSON.stringify(nodeInfo.node_info)
  const updateWhereQuery = {
    where: {
      name: name
    },
    raw: true
  }
  return db.Config.update(nodeInfo, updateWhereQuery);
}

connectionHandle.prototype.conn = function(io) {
  const self = this;
  io.on('connection', function(socket) {
    let socketInfo = {
      uuid: socket.request.uuid,
      socket: socket
    }
    self.socketStack.push(socketInfo);

    socket.on('data', function(data) {
      data = self._decrypt(data);
      if(data.type === 'subscribe' && data.project) {
        self.dealNode(data.project, socket.request.uuid);   // save node into to where they subscribed
        self._getDbDatas(data.project)
            .then(function(data) {
              data.type = 'init';
              socket.emit('data', self._encrypt(data))
            })
            .catch(function(err) {
              console.log(err.stack)
            })
      }
    });

    socket.on('disconnect', function(d) {
      self.handleDisconnect(socketInfo.uuid);
    });
  })
}

**Comment by janmeier** [comment]
@struCoder We still haven't seen the model definition for config (only the migration).

Please read up on [SSCCE](http://sscce.org/)

**Comment by struCoder** [comment]
@janmeier
Are you a developer of sequelize ?

**Comment by janmeier** [comment]
@struCoder Yes I am - We'd like to help you, but we can't if we can't reproduce the issue :=
