### ISSUE TITLE
The process can't execute the sql sometimes

### ISSUE THREAD

**Issue by boshido** [sequelize/sequelize#5146]
In my project environment below are the dependencies list
- express
- express-session
- passport
- passport-http
- sequelize
- connect-session-sequelize

Here are the logs before node process can't execute sql anymore.

```
Executing (3a4b64e8-b09f-485a-9431-7580ee653bf4): START TRANSACTION;
Executing (3a4b64e8-b09f-485a-9431-7580ee653bf4): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (3a4b64e8-b09f-485a-9431-7580ee653bf4): SET autocommit = 1;
Executing (3a4b64e8-b09f-485a-9431-7580ee653bf4): SELECT "sid", "expires", "data", "createdAt", "updatedAt" FROM "Sessions" AS "Session" WHERE "Session"."sid" = 'jmm3E8ZXCbdYYyob1VNzpo38JK70Yqrf';
Executing (3a4b64e8-b09f-485a-9431-7580ee653bf4): CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response "Sessions", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_eed27a271e9d440fbb5ba0ccae26ec44$ BEGIN INSERT INTO "Sessions" ("sid","expires","data","updatedAt","createdAt") VALUES ('jmm3E8ZXCbdYYyob1VNzpo38JK70Yqrf','2016-01-06 12:01:56.315 +00:00','{"cookie":{"originalMaxAge":null,"expires":null,"httpOnly":true,"path":"/"},"passport":{"user":{"userId":4,"key":"watchrapong.ag@windowslive.com","secret":"5571807a584c6c0a626364bfd59f3e00aa1f1e88","roles":[1],"type":null,"createdAt":"2016-01-04T09:34:04.907Z","updatedAt":"2016-01-04T09:34:04.907Z","deletedAt":null},"customerId":4,"role":"customer"}}','2016-01-05 12:01:56.362 +00:00','2016-01-05 12:01:56.362 +00:00') RETURNING * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_eed27a271e9d440fbb5ba0ccae26ec44$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();
Executing (3a4b64e8-b09f-485a-9431-7580ee653bf4): COMMIT;
Executing (b353bd50-b6b9-45cb-91c3-64abd69e800c): ROLLBACK TO SAVEPOINT "b353bd50-b6b9-45cb-91c3-64abd69e800c-savepoint-1";
Executing (b353bd50-b6b9-45cb-91c3-64abd69e800c): SAVEPOINT "b353bd50-b6b9-45cb-91c3-64abd69e800c-savepoint-2";
Executing (b353bd50-b6b9-45cb-91c3-64abd69e800c): SAVEPOINT "b353bd50-b6b9-45cb-91c3-64abd69e800c-savepoint-3";
Executing (b353bd50-b6b9-45cb-91c3-64abd69e800c): SAVEPOINT "b353bd50-b6b9-45cb-91c3-64abd69e800c-savepoint-4";
Executing (b353bd50-b6b9-45cb-91c3-64abd69e800c): SAVEPOINT "b353bd50-b6b9-45cb-91c3-64abd69e800c-savepoint-5";
Executing (b353bd50-b6b9-45cb-91c3-64abd69e800c): SAVEPOINT "b353bd50-b6b9-45cb-91c3-64abd69e800c-savepoint-6";
Executing (b353bd50-b6b9-45cb-91c3-64abd69e800c): SAVEPOINT "b353bd50-b6b9-45cb-91c3-64abd69e800c-savepoint-7"; 
```

After that logs 
Every request that I tried to call from postman it's stuck in loading state
while node was trying to get session from the database but it couldn't get it at all.

```
Executing (b353bd50-b6b9-45cb-91c3-64abd69e800c): SELECT "sid", "expires", "data", "createdAt", "updatedAt" FROM "Sessions" AS "Session" WHERE "Session"."sid" = 'mZ-0OireUCrVWGqjl4laYW8B1QRmVeuo';
Executing (b353bd50-b6b9-45cb-91c3-64abd69e800c): SELECT "sid", "expires", "data", "createdAt", "updatedAt" FROM "Sessions" AS "Session" WHERE "Session"."sid" = 'mZ-0OireUCrVWGqjl4laYW8B1QRmVeuo';
Executing (b353bd50-b6b9-45cb-91c3-64abd69e800c): SELECT "sid", "expires", "data", "createdAt", "updatedAt" FROM "Sessions" AS "Session" WHERE "Session"."sid" = 'mZ-0OireUCrVWGqjl4laYW8B1QRmVeuo';
Executing (b353bd50-b6b9-45cb-91c3-64abd69e800c): SELECT "sid", "expires", "data", "createdAt", "updatedAt" FROM "Sessions" AS "Session" WHERE "Session"."sid" = '0G9CQOBmWNKPGPkSbLWfgcUb0iL8RRNZ';
Executing (b353bd50-b6b9-45cb-91c3-64abd69e800c): SELECT "sid", "expires", "data", "createdAt", "updatedAt" FROM "Sessions" AS "Session" WHERE "Session"."sid" = 'mZ-0OireUCrVWGqjl4laYW8B1QRmVeuo';
Executing (b353bd50-b6b9-45cb-91c3-64abd69e800c): SELECT "sid", "expires", "data", "createdAt", "updatedAt" FROM "Sessions" AS "Session" WHERE "Session"."sid" = 'mZ-0OireUCrVWGqjl4laYW8B1QRmVeuo';
Executing (b353bd50-b6b9-45cb-91c3-64abd69e800c): SELECT "sid", "expires", "data", "createdAt", "updatedAt" FROM "Sessions" AS "Session" WHERE "Session"."sid" = 'mZ-0OireUCrVWGqjl4laYW8B1QRmVeuo';
Executing (b353bd50-b6b9-45cb-91c3-64abd69e800c): SELECT "sid", "expires", "data", "createdAt", "updatedAt" FROM "Sessions" AS "Session" WHERE "Session"."sid" = '0G9CQOBmWNKPGPkSbLWfgcUb0iL8RRNZ';
Executing (b353bd50-b6b9-45cb-91c3-64abd69e800c): SELECT "sid", "expires", "data", "createdAt", "updatedAt" FROM "Sessions" AS "Session" WHERE "Session"."sid" = '0G9CQOBmWNKPGPkSbLWfgcUb0iL8RRNZ';
Executing (default): DELETE FROM "Sessions" WHERE "expires" < '2016-01-05 12:12:02.344 +00:00'
Executing (b353bd50-b6b9-45cb-91c3-64abd69e800c): SELECT "sid", "expires", "data", "createdAt", "updatedAt" FROM "Sessions" AS "Session" WHERE "Session"."sid" = 'mZ-0OireUCrVWGqjl4laYW8B1QRmVeuo';
Executing (b353bd50-b6b9-45cb-91c3-64abd69e800c): SELECT "sid", "expires", "data", "createdAt", "updatedAt" FROM "Sessions" AS "Session" WHERE "Session"."sid" = 'mZ-0OireUCrVWGqjl4laYW8B1QRmVeuo'; 
```

The curious thing is 'b353bd50-b6b9-45cb-91c3-64abd69e800c' uuid that I don't know where did it come from.

This problem randomly appears to me and I don't know why 
And It can temporary fix this by restarting the node process.

Do you think this is the problem of sequelize ?
Or could you give me an advice for this if it not ?

Thank you

**Comment by mickhansen** [comment]
Absolutely no idea what the issue might be from the information given, maybe you're running out of sql connections, however that should remedy itself after a bit.
The ID after Executing is simply a uuid to identify the transaction connection that query is being run on.

**Comment by boshido** [comment]
First sorry for my english
Thank you @mickhansen  
I meant that 'b353bd50-b6b9-45cb-91c3-64abd69e800c' that I have checked from logs 
and found that It has never been executed but It has been rollbacked anyway

I have tried to open the new application without closing the old one and it worked without any problems
If the problem is sql connections limitation in my opinion it should affect all application that's connecting the database (I'm not sure anyway)

**Comment by mickhansen** [comment]
We pool connections client side, so if that pool is exhausted a new query needs to wait for a connection from the pool to become available again.

There have been known issues in the past where the application stolls when the amount of concurrenct findOrCreate calls is greater than the amount of allowed connections in the pool.

**Comment by boshido** [comment]
I have waited for the pool to become available since I posted this issue 
(The application's still running with the problem)
Can you tell me why it took so long to become available again ?

And can please you explain me more about "findOrCreate calls is greater than the amount of allowed connections in the pool" ?
I lack working experience with database pool, I'm so sorry to disturb you.

**Comment by mickhansen** [comment]
Not sure i can explain more about findOrCreate, it's a previous issue where if there's more concurrenct calls than the max allowed in the pool it will stall.

I can't speak to why it specifically took however much time in your case. As a temporary workaround you should tweak your sequelize pool settings to allow more connections:

```
new Sequelize(...., {
  pool: {
    min: 0,
    max: 15
  }
});

**Comment by boshido** [comment]
Thank you for explaining
I will temporary close this issue
I'm going to try that config and if the problem still appears I will reopen this issue

**Comment by boshido** [comment]
Now I found an error and it randomly appear.

```
TypeError: Cannot read property '_invalid' of undefined
    at ConnectionManager.validate (/var/source/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:126:20)
    at ConnectionManager.$validate (/var/source/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:240:41)
    at dispense (/var/source/node_modules/sequelize/node_modules/generic-pool/lib/generic-pool.js:244:22)
    at Object.me.acquire (/var/source/node_modules/sequelize/node_modules/generic-pool/lib/generic-pool.js:319:5)
    at /var/source/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:214:17
    at tryCatcher (/var/source/node_modules/sequelize/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/var/source/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (/var/source/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:70:37)
    at /var/source/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:213:12
    at /var/source/node_modules/continuation-local-storage/context.js:76:17
    at tryCatcher (/var/source/node_modules/sequelize/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/var/source/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/var/source/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAtPostResolution (/var/source/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:245:10)
    at Async._drainQueue (/var/source/node_modules/sequelize/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/var/source/node_modules/sequelize/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/var/source/node_modules/sequelize/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by boshido** [comment]
Any helps ?
I'm facing this problem and I have no idea why

**Comment by mickhansen** [comment]
That error is from the connection validation method of the connection pool. Nothing should ever be undefiend in there.

So no, i have no idea what you are facing, it seems to be environment specific.
