### ISSUE TITLE
Promise error emitted

### ISSUE THREAD

**Issue by startupthekid** [sequelize/sequelize#5181]
Similar to [this issue](https://github.com/sequelize/cli/issues/242), `Model.findAll` emits:

```
Warning: a promise was created in a handler but was not returned from it
```

Full call stack:

```
Warning: a promise was created in a handler but was not returned from it
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at [object Object].Model.findAll (/Users/whitewolf/Github/busy.cm/node_modules/sequelize/lib/model.js:1333:18)
    at Object.find (/Users/whitewolf/Github/busy.cm/node_modules/feathers-sequelize/lib/index.js:98:25)
    at Object.wrapper (/Users/whitewolf/Github/busy.cm/node_modules/feathers/lib/mixins/promise.js:6:28)
    at Object.<anonymous> (/Users/whitewolf/Github/busy.cm/node_modules/uberproto/lib/proto.js:30:17)
    at Object.<anonymous> (/Users/whitewolf/Github/busy.cm/node_modules/feathers-hooks/lib/before.js:17:21)
    at Object.<anonymous> (/Users/whitewolf/Github/busy.cm/node_modules/uberproto/lib/proto.js:30:17)
    at Object.<anonymous> (/Users/whitewolf/Github/busy.cm/node_modules/feathers-hooks/lib/after.js:18:21)
    at Object.<anonymous> (/Users/whitewolf/Github/busy.cm/node_modules/uberproto/lib/proto.js:30:17)
    at Object.mixin.(anonymous function) (/Users/whitewolf/Github/busy.cm/node_modules/feathers/lib/mixins/normalizer.js:12:30)
    at Object.find (/Users/whitewolf/Github/busy.cm/node_modules/uberproto/lib/proto.js:30:17)
    at Object.create (.:37:19)
    at Object.<anonymous> (/Users/whitewolf/Github/busy.cm/node_modules/feathers-hooks/lib/commons.js:28:24)
    at Object.<anonymous> (/Users/whitewolf/Github/busy.cm/node_modules/feathers-hooks/lib/after.js:46:17)
    at callbackWrapper (/Users/whitewolf/Github/busy.cm/node_modules/rubberduck/lib/rubberduck.js:50:20)
    at [object Object].<anonymous> (/Users/whitewolf/Github/busy.cm/node_modules/feathers/lib/mixins/promise.js:11:7)
From previous event:
    at Promise.then (/Users/whitewolf/Github/busy.cm/node_modules/sequelize/lib/promise.js:21:17)
    at Object.wrapper (/Users/whitewolf/Github/busy.cm/node_modules/feathers/lib/mixins/promise.js:10:12)
    at Object.<anonymous> (/Users/whitewolf/Github/busy.cm/node_modules/uberproto/lib/proto.js:30:17)
    at Object.wrapped (/Users/whitewolf/Github/busy.cm/node_modules/rubberduck/lib/rubberduck.js:63:19)
    at Object.fn (/Users/whitewolf/Github/busy.cm/node_modules/feathers-hooks/lib/before.js:24:21)
    at Object.<anonymous> (/Users/whitewolf/Github/busy.cm/node_modules/feathers-hooks/lib/commons.js:25:12)
    at /Users/whitewolf/Github/busy.cm/node_modules/feathers-hooks/lib/commons.js:32:9
    at run (/Users/whitewolf/Github/busy.cm/node_modules/core-js/modules/es6.promise.js:104:47)
    at /Users/whitewolf/Github/busy.cm/node_modules/core-js/modules/es6.promise.js:115:28
    at flush (/Users/whitewolf/Github/busy.cm/node_modules/core-js/modules/$.microtask.js:19:5)
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickCallback (node.js:362:13)
```

I'm using release 3.17.1.

**Comment by mickhansen** [comment]
A general known issue (the warnings in general), if you can track down the code triggering it specifically that would be helpfull.
