### ISSUE TITLE
TypeError: Cannot read property 'sequelize' of undefined

### ISSUE THREAD

**Issue by ThomasHambach** [sequelize/sequelize#5218]
Only occurring on version 3.17.1. 3.16.0 is fine. Using MSSQL dialect.

    TypeError: Cannot read property 'sequelize' of undefined

    ~/Sites/datamodel/node_modules/sequelize/lib/model.js:82
    attribute = this.sequelize.normalizeAttribute(attribute);
                    ^

    TypeError: Cannot read property 'sequelize' of undefined
    at ~/Sites/datamodel/node_modules/sequelize/lib/model.js:82:21
    at ~/Sites/datamodel/node_modules/lodash/lodash.js:11109:23
    at ~/Sites/datamodel/node_modules/lodash/lodash.js:3925:15
    at baseForOwn (~/Sites/datamodel/node_modules/lodash/lodash.js:2521:24)
    at Function.mapValues (~/Sites/datamodel/node_modules/lodash/lodash.js:11108:7)
    at new Model (~/Sites/datamodel/node_modules/sequelize/lib/model.js:77:50)
    at Sequelize.define (~/Sites/datamodel/node_modules/sequelize/lib/sequelize.js:588:15)
    at module.exports (~/Sites/datamodel/models/apikeys.js:4:26)
    at Sequelize.import (~/Sites/datamodel/node_modules/sequelize/lib/sequelize.js:648:30)
    at ~/Sites/datamodel/models/index.js:166:29
    at Array.forEach (native)
    at module.exports (~/Sites/datamodel/models/index.js:164:6)
    at Object.<anonymous> (~/Sites/datamodel/test.js:12:33)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)`

**Comment by mickhansen** [comment]
Not sure why this s failing, we haven't upgraded lodash yet.

**Comment by StyleT** [comment]
Same with `3.19.0` & MSSQL

**Comment by janmeier** [comment]
In 3.19 we upgrade lodash https://github.com/sequelize/sequelize/pull/5336

**Comment by aristidesfl** [comment]
3.19.1 with postgresql. How is this related to lodash?

**Comment by mickhansen** [comment]
@aristidesfl Fixed in 3.19.1

**Comment by aristidesfl** [comment]
I get `TypeError: Cannot set property 'options' of undefined at Sequelize (.../node_modules/sequelize/lib/sequelize.js:135:16)`
