### ISSUE TITLE
LIMIT clause for mysql not generated properly when values are strings

### ISSUE THREAD

**Issue by jghowe** [sequelize/sequelize#5259]
The following snippet will produce the error with version 3.17.3:

``` javascript
var Sequelize = require('sequelize');
var sequelize = new Sequelize('database', 'username', 'password');

var User = sequelize.define('user', {
  username: Sequelize.STRING,
  birthday: Sequelize.DATE
});

sequelize.sync().then(function() {
  return User.create({
    username: 'janedoe',
    birthday: new Date(1980, 6, 20)
  });
}).then(function() {
  return User.findAll({
    limit: '10',
    offset: '0'
  });
}).then(function(jane) {
  console.log(jane.get({
    plain: true
  }));
});
```

```
Executing (default): INSERT INTO `users` (`id`,`username`,`birthday`,`updatedAt`,`createdAt`) VALUES (DEFAULT,'janedoe','1980-07-20 07:00:00','2016-01-19 20:36:24','2016-01-19 20:36:24');
Executing (default): SELECT `id`, `username`, `birthday`, `createdAt`, `updatedAt` FROM `users` AS `user` LIMIT '0', '10';
Unhandled rejection SequelizeDatabaseError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''0', '10'' at line 1
    at Query.formatError (/Users/jhowe/src/tssherpa/gamma-datalayer/node_modules/sequelize/lib/dialects/mysql/query.js:174:14)
    at Query._callback (/Users/jhowe/src/tssherpa/gamma-datalayer/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
    at Query.Sequence.end (/Users/jhowe/src/tssherpa/gamma-datalayer/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query.ErrorPacket (/Users/jhowe/src/tssherpa/gamma-datalayer/node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
    at Protocol._parsePacket (/Users/jhowe/src/tssherpa/gamma-datalayer/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/Users/jhowe/src/tssherpa/gamma-datalayer/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/Users/jhowe/src/tssherpa/gamma-datalayer/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/jhowe/src/tssherpa/gamma-datalayer/node_modules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

When the `limit` and `offset` properties are numeric, this is not an issue.  This appears to be a regression as this problem does not occur in version 3.16.

**Comment by janmeier** [comment]
The problem did not occur in 3.16 because the limit and offset parameters were not escaped at all, see https://github.com/sequelize/sequelize/commit/d198d78182cbf1ea3ef1706740b35813a6aa0838

API docs (http://docs.sequelizejs.com/en/latest/api/model/) state that the datatype should be a number, so I'm not sure I'd call this a regression, more that the code was wrong before

**Comment by jghowe** [comment]
Should it not be expected for the library to coerce strings to numbers?  For example: `Math.pow('2','2')` returns `4`.

**Comment by nazar** [comment]
Just upgraded from `3.15.0` and seeing this issue as well: `ORDER BY `Report`.`id` DESC LIMIT '20';`

**Comment by VarunBatraIT** [comment]
+1

**Comment by Songkeys** [comment]
Version 4.x so far. Same issue here. Any progress or why not relax the restriction?

**Comment by harveyappleton** [comment]
Same issue here. If you try the SQL in a querier with LIMIT fields as numbers rather than strings, its happy (on MySQL dialect) - eg LIMIT '2', '5' fails, but LIMIT 2, 5 is fine
