### ISSUE TITLE
Model with belongsTo relationship and targetKey fails to load

### ISSUE THREAD

**Issue by dzuluaga** [sequelize/sequelize#5287]
I get this error when belongsTo relationship is used. Am I missing anything? Thanks!

```javascript
var OrgApi = sequelize.define(
      "OrgApi",
      { "id": {"type": DataTypes.STRING, primaryKey: true }, "api_name": DataTypes.STRING, "org_name": DataTypes.STRING,},
      {
        freezeTableName: true,
        timestamps: false,
        tableName: options.table,
        schema: options.schema,
        classMethods: {
          associate: function(models) {
                OrgApi.BelongsTo( OrgApiRevisionVersion, { foreignKey: 'api_name', targetKey: 'api_name' } );
          }
      });

```

```javascript
/Users/ApigeeCorporation/Documents/tools/git/nucleus/nucleus-edge-api/node/node_modules/sequelize/lib/associations/belongs-to.js:67
  this.targetKeyField = this.target.rawAttributes[this.targetKey].field || this.targetKey;
                                                                 ^

TypeError: Cannot read property 'field' of undefined
    at new BelongsTo (/Users/ApigeeCorporation/Documents/tools/git/nucleus/nucleus-edge-api/node/node_modules/sequelize/lib/associations/belongs-to.js:67:66)
    at null.belongsTo (/Users/ApigeeCorporation/Documents/tools/git/nucleus/nucleus-edge-api/node/node_modules/sequelize/lib/associations/mixin.js:106:23)
    at /Users/ApigeeCorporation/Documents/tools/git/nucleus/nucleus-edge-api/node/helpers/modelFactory.js:67:27
    at Array.forEach (native)
    at associate (/Users/ApigeeCorporation/Documents/tools/git/nucleus/nucleus-edge-api/node/helpers/modelFactory.js:65:14)
    at /Users/ApigeeCorporation/Documents/tools/git/nucleus/nucleus-edge-api/node/models/index.js:32:19
```

**Comment by mickhansen** [comment]
targetKey referes to the key on the target model.
Do you have a `api_name` attribute on your OrgApiReveisionVersion?

**Comment by dzuluaga** [comment]
I was establishing the relationship the other way around. But your comment made me realize that. Long day :-) Thanks!

**Comment by satya9125** [comment]
hi @dzuluaga Please share what is other way to fix this problem. Thanks!
