### ISSUE TITLE
Nested creating N:M elements with join table attributes

### ISSUE THREAD

**Issue by almini** [sequelize/sequelize#5335]
I have the following model:

``` javascript
var Video = sequelize.define('video', {
    transcoderStatus: Database.ENUM('PROGRESSING', 'COMPLETED', 'WARNING', 'ERROR'),
    transcoderJobId: Database.STRING
})

var File = sequelize.define('file', {
    key: Database.STRING,
    public: Database.BOOLEAN,
})

var VideoFile = sequelize.define('videofile', {
    duration: Database.INTEGER.UNSIGNED,
    resolution: Database.STRING
})

Video.belongsToMany(File, { through: VideoFile })
File.belongsToMany(Video, { through: VideoFile })
```

Now when I try to to create a new video like so:

``` javascript
Video.create({
    transcoderStatus: 'PROGRESSING',
    transcoderJobId: 'sdfadf134',
    files: [{
        key: 'abcd',
        public: true,
        videofile: {
            duration: 12,
            resolution: '360p'
        }
    }]
}, { include: [ File ] })
```

I get the following error:

``` javascript
Executing (default): INSERT INTO `videos` (`id`,`transcoderStatus`,`transcoderJobId`,`updatedAt`,`createdAt`) VALUES (DEFAULT,'PROGRESSING','sdfadf134','2016-01-29 18:03:44','2016-01-29 18:03:44');
Executing (default): INSERT INTO `files` (`id`,`key`,`public`,`updatedAt`,`createdAt`) VALUES (DEFAULT,'abcd',true,'2016-01-29 18:03:45','2016-01-29 18:03:45');
TypeError: Cannot read property 'indexOf' of undefined
    at [object Object].Instance.set (.../node_modules/sequelize/lib/instance.js:329:20)
    at .../node_modules/sequelize/lib/instance.js:725:26
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
From previous event:
    at Function.map (.../node_modules/sequelize/lib/promise.js:21:17)
    at .../node_modules/sequelize/lib/instance.js:706:26
    at bound (domain.js:287:14)
    at PassThroughHandlerContext.runBound (domain.js:300:12)
From previous event:
    at Promise.tap (.../node_modules/sequelize/lib/promise.js:21:17)
    at [object Object].<anonymous> (.../node_modules/sequelize/lib/instance.js:701:10)
From previous event:
    at Promise.then (.../node_modules/sequelize/lib/promise.js:21:17)
    at [object Object].Instance.save (.../node_modules/sequelize/lib/instance.js:575:6)
    at [object Object].Model.create (.../node_modules/sequelize/lib/model.js:1823:6)
    at Object.<anonymous> (test.js:25:7)
    at Module._compile (module.js:397:26)
    at loader (.../node_modules/babel-register/lib/node.js:130:5)
    at Object.require.extensions.(anonymous function) [as .js] (.../node_modules/babel-register/lib/node.js:140:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at repl:3:1
    at module.exports.defaultEval (.../node_modules/babel-repl/index.js:29:25)
    at defaults.eval (.../node_modules/babel-repl/index.js:55:34)
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at Promise.apply (.../node_modules/repl-promised/node_modules/q/q.js:1122:26)
    at Promise.promise.promiseDispatch (.../node_modules/repl-promised/node_modules/q/q.js:752:41)
    at .../node_modules/repl-promised/node_modules/q/q.js:1337:14
    at flush (.../node_modules/repl-promised/node_modules/q/q.js:108:17)
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickDomainCallback (node.js:422:13)
```

Find works using the same structure and inserting without trying to set the join table attributes (videofile: {...}) also works.
Could you please look into it?

Thanks

**Comment by mickhansen** [comment]
We don't currently have explicit support (i.e. no tests) for this case (nested create with attributes for join table) at the moment

**Comment by almini** [comment]
Jh
