### ISSUE TITLE
sequelize@3.19.0 breaks findAndCount with eagerly loaded model using pg

### ISSUE THREAD

**Issue by yjwong** [sequelize/sequelize#5344]
## How to reproduce:

Install sequelize@3.19.0 and pg@4.4.4.

```javascript
'use strict';
let Sequelize = require('sequelize');
let sequelize = new Sequelize('database', 'username', 'password', {
	dialect: 'postgres',
	host: 'localhost',
	port: 5432
});

let Company = sequelize.define('Company', {
	id: {
		type: Sequelize.INTEGER,
		primaryKey: true,
		autoIncrement: true
	}
});

let Score = sequelize.define('Score', {
	id: {
		type: Sequelize.INTEGER,
		primaryKey: true,
		autoIncrement: true
	}
});

Company.hasOne(Score);
sequelize.sync()
	.then(() => Company.findAndCountAll({ include: [{ model: Score }] })
	.then(result => console.log(result));
```

## Output

```
module.js:328
    throw err;
    ^

Error: Cannot find module 'pg-native'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/tmp/test/node_modules/pg/lib/native/index.js:1:76)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at null.<anonymous> (/tmp/test/node_modules/pg/lib/index.js:78:36)
    at /tmp/test/node_modules/lodash/lodash.js:4015:32
    at baseForOwn (/tmp/test/node_modules/lodash/lodash.js:2567:24)
    at baseClone (/tmp/test/node_modules/lodash/lodash.js:2277:39)
    at /tmp/test/node_modules/lodash/lodash.js:2278:34
    at /tmp/test/node_modules/lodash/lodash.js:4015:15
    at baseForOwn (/tmp/test/node_modules/lodash/lodash.js:2567:24)
    at baseClone (/tmp/test/node_modules/lodash/lodash.js:2277:39)
    at /tmp/test/node_modules/lodash/lodash.js:2278:34
    at /tmp/test/node_modules/lodash/lodash.js:4015:15
    at baseForOwn (/tmp/test/node_modules/lodash/lodash.js:2567:24)
```

## Explanation

This does not happen with sequelize@3.18.0, and is most likely due to the upgrade from lodash 3.x to 4.x. Commit e739d816 is the one that breaks.

**Comment by gorangajic** [comment]
I am having the same error also

**Comment by yjwong** [comment]
It appears that _.cloneDeep has been replaced with _.cloneDeepWith. The former does not accept a customizer function. See [lib/model.js#1652](../blob/v3.19.0/lib/model.js#1652).

**Comment by mickhansen** [comment]
Please do submit a PR @yjwong.
Very odd none of our tests have failed though.

**Comment by yjwong** [comment]
PR submitted as #5345.

**Comment by yjwong** [comment]
Closing since PR was merged already :smile:

**Comment by danconnell** [comment]
@mickhansen Any chance you can tag a release soon-ish because of this? Getting this error everytime I boot up in production. Thanks!

**Comment by mickhansen** [comment]
v3.19.1
