### ISSUE TITLE
Column names with '

### ISSUE THREAD

**Issue by jkgeyti** [sequelize/sequelize#5383]
Calling `.query()` fails in `Result.addFields` (line 98, `this.RowCtor = Function("parsers", "rowData", ctorBody);`) fails, if a column name contains `'`.

Example, where I'm querying a table with a column named `{u'geometry': {u'type': u'MultiPolygon', u'coordinates': [[[` (actually using this as a column name is caused by a bug on my part, but that's irrelevant to this bug report.):

```
Executing (default): SELECT * FROM usgeo LIMIT 1
undefined:6
this['{u\'geometry': {u'type': u'MultiPolygon', u'coordinates': [[['] = rowData[2] == null ? null : parsers[2](rowData[2]);
                   ^

SyntaxError: Unexpected token :
    at Function (native)
    at Result.addFields ([REDACTED...]/node_modules/pg/lib/result.js:98:20)
    at Query.handleRowDescription ([REDACTED...]/node_modules/pg/lib/query.js:54:16)
    at null.<anonymous> ([REDACTED...]/node_modules/pg/lib/client.js:103:24)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at Socket.<anonymous> ([REDACTED...]/node_modules/pg/lib/connection.js:109:12)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

**Comment by janmeier** [comment]
Can you show a [SSCCE](HTTP://SSCCE.ORG/)? - this seems to actually fail in the node-pg lib, not  in sequelize

**Comment by jkgeyti** [comment]
You're right. I'll create a bug report over there.

The problem is with multiple apostrophes by the way, not a single.

```javascript
var conn = new Sequelize("postgres://...");

// Create table
//conn.query("CREATE TABLE atable ( \"''\" TEXT )");

// Query table
conn.query("SELECT * FROM atable");
```

```
$ node bug.js
Executing (default): SELECT * FROM atable
undefined:4
this['\'''] = rowData[0] == null ? null : parsers[0](rowData[0]);
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected token ILLEGAL
    at Function (native)
    at Result.addFields (/Users/jgeyti/tmp/sequelizebug/node_modules/pg/lib/result.js:98:20)
    at Query.handleRowDescription (/Users/jgeyti/tmp/sequelizebug/node_modules/pg/lib/query.js:54:16)
    at null.<anonymous> (/Users/jgeyti/tmp/sequelizebug/node_modules/pg/lib/client.js:103:24)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at Socket.<anonymous> (/Users/jgeyti/tmp/sequelizebug/node_modules/pg/lib/connection.js:109:12)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

**Comment by jkgeyti** [comment]
The node-postgres says this is by design, and any escaping should be done by high-level libraries, so I'll open this issue here. 

See https://github.com/brianc/node-postgres/issues/934 for reference.
