### ISSUE TITLE
Postgres error when using mysql dialect..

### ISSUE THREAD

**Issue by dlepaux** [sequelize/sequelize#5400]
I'm new with Sequelize and i have successfully tried to SELECT some data in my MySQL database.

But after my request, something happen and i got this error :

```
$ node server
Server is now running on port 80
Executing (default): SELECT `id`, `i18n_type_id` AS `i18nTypeId`, `key` FROM `i18n` AS `i18n` WHERE `i18n`.`id` = 10;
Error: Cannot find module 'pg-hstore' from 'C:\project.dev\mithril-isomorphic-starterkit\node_modules\sequelize\lib\dialects\postgres'
    at C:\project.dev\mithril-isomorphic-starterkit\node_modules\browserify-middleware\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:46:17
    at process (C:\project.dev\mithril-isomorphic-starterkit\node_modules\browserify-middleware\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\project.dev\mithril-isomorphic-starterkit\node_modules\browserify-middleware\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:188:17)
    at load (C:\project.dev\mithril-isomorphic-starterkit\node_modules\browserify-middleware\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\project.dev\mithril-isomorphic-starterkit\node_modules\browserify-middleware\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
    at C:\project.dev\mithril-isomorphic-starterkit\node_modules\browserify-middleware\node_modules\browserify\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

My config for connexion is :
```
{
  "development": {
    "database": "homestead",
    "username": "homestead",
    "password": "secret",
    "chained": "mysql://homestead:secret@localhost:33060/homestead",
    "config": {
      "host": "localhost",
      "dialect": "mysql",
      "pool": {
        "max": 5,
        "min": 0,
        "idle": 10000
      }
    }
  }
}
```

I call my model like this and it works !
```
db.i18n.findById(10).then( function (i18n) {
  scope.i18n = i18n.key;
});
```

I have added the `pg-hstore` in my devDependencies, it fix the issue but it's not at all optimized... My main JS file without 'pg-hstore' from 56Ko to 1,3Mo...

Do you have an idea ?

Thank you

**Comment by mickhansen** [comment]
That error is usually because of an incorrect clone somewhere.
