### ISSUE TITLE
When mistakenly putting the `include` within the `where`, the error is difficult to understand.

### ISSUE THREAD

**Issue by manchicken** [sequelize/sequelize#5435]
So, I recognize I'm reporting an issue with the error handling, but bear with me.

If you do something silly, and forget your braces, you could accidentally stick `include` array inside of the `where` object for your query. This results in some really confusing error messages, something like this:

```
Unhandled rejection TypeError: val.replace is not a function
  at Object.SqlString.escape (/Users/mstemle/Documents/Devel/ProjectFolder/node_modules/sequelize/lib/sql-string.js:63:15)
  at Object.QueryGenerator.escape (/Users/mstemle/Documents/Devel/ProjectFolder/node_modules/sequelize/lib/dialects/abstract/query-generator.js:983:22)
  at /Users/mstemle/Documents/Devel/ProjectFolder/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2164:23
  at Array.map (native)
  at Object.QueryGenerator.whereItemQuery (/Users/mstemle/Documents/Devel/ProjectFolder/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2163:49)
  at /Users/mstemle/Documents/Devel/ProjectFolder/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1875:25
  at /Users/mstemle/Documents/Devel/ProjectFolder/node_modules/sequelize/node_modules/lodash/lodash.js:4095:15
  at baseForOwn (/Users/mstemle/Documents/Devel/ProjectFolder/node_modules/sequelize/node_modules/lodash/lodash.js:2617:24)
  at Function.forOwn (/Users/mstemle/Documents/Devel/ProjectFolder/node_modules/sequelize/node_modules/lodash/lodash.js:11173:24)
  at Object.QueryGenerator.whereItemsQuery (/Users/mstemle/Documents/Devel/ProjectFolder/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1874:9)
  at Object.QueryGenerator.getWhereConditions (/Users/mstemle/Documents/Devel/ProjectFolder/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2288:19)
  at Object.QueryGenerator.selectQuery (/Users/mstemle/Documents/Devel/ProjectFolder/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1464:28)
  at [object Object].QueryInterface.select (/Users/mstemle/Documents/Devel/ProjectFolder/node_modules/sequelize/lib/query-interface.js:656:25)
  at [object Object].<anonymous> (/Users/mstemle/Documents/Devel/ProjectFolder/node_modules/sequelize/lib/model.js:1388:32)
From previous event:
  at Promise.then (/Users/mstemle/Documents/Devel/ProjectFolder/node_modules/sequelize/lib/promise.js:21:17)
  at [object Object].Model.findAll (/Users/mstemle/Documents/Devel/ProjectFolder/node_modules/sequelize/lib/model.js:1385:6)
  at [object Object].Model.findOne (/Users/mstemle/Documents/Devel/ProjectFolder/node_modules/sequelize/lib/model.js:1505:34)
  at /Users/mstemle/Documents/Devel/ProjectFolder/lib/components/temp-user.js:5:29
  at Context.<anonymous> (/Users/mstemle/Documents/Devel/ProjectFolder/test/unit/lib/components/temp-user.js:89:5)
  at Test.Runnable.run (/Users/mstemle/Documents/Devel/ProjectFolder/node_modules/grunt-mocha-cli/node_modules/mocha/lib/runnable.js:233:15)
  at Runner.runTest (/Users/mstemle/Documents/Devel/ProjectFolder/node_modules/grunt-mocha-cli/node_modules/mocha/lib/runner.js:390:10)
... truncated ...
```

Again, I get that this is a code error on the caller's part, but I'm wondering if it would be possible to stick a warning somewhere if you notice that you have an `include` property in your `where` object which of a type `Array` where the 0th element is an `Object` or something. I'm not certain if this will end up being the best solution here, but it's just a thought.

This ORM will still be lovely even without this, but I think it would be helpful to have more "I don't think you meant to do that" detection and reporting.

Much thanks, let me know if you need any more information.

**Comment by mickhansen** [comment]
We definitely want "I don't think you meant to do that" detection in there as long as it doesn't yield false positives.

In this case we should simply check if the model has an attribute called include and if not throw/log a warning.

**Comment by sbai** [comment]
+1 This bit me today and I was scratching my head trying to figure out what I did wrong.

**Comment by sushantdhiman** [comment]
We should include this one to #5322 @mickhansen

**Comment by mickhansen** [comment]
@sushantdhiman I think it's okay as a seperate issue. We can't throw directly on a key called include in where since a column could be called that.

**Comment by sushantdhiman** [comment]
@mickhansen Yes, make sense.
