### ISSUE TITLE
Columns of join table are always selected, which breaks aggregation in PostgresSQL

### ISSUE THREAD

**Issue by MrOrz** [sequelize/sequelize#5481]
Dialect: PostgresSql
Sequelize version: 3.19.3

I have two tables that are n:m associated with a joining table. Whenever I use `.findAll` and include the other table, all fields in the joining table would also be selected in the generated SQL queries.  The fields in the joining table would cause problems when I try to use the aggregate functions.

`include[].through.attributes: []` does not stops the columns from going into the SQL query.

The example below is modified from the one in #3938.

Setup:
```js
// MODELS
var Group = sequelize.define('Group', {
  name: sequelize.Sequelize.STRING
});

var Person = sequelize.define('Person', {
  name: sequelize.Sequelize.STRING
});

var GroupPerson = sequelize.define('GroupPerson', {
  status: sequelize.Sequelize.STRING
});

// RELATIONS
Group.belongsToMany(Person, {through: GroupPerson, as: 'Persons'});
Person.belongsToMany(Group, {through: GroupPerson, as: 'Groups'});

sequelize.sync({force: true}).then(function(){
  // EXAMPLE
  Person.findAll({
    attributes: [[sequelize.fn('ARRAY_AGG', sequelize.col('Groups.id')), 'groupIds']],
    include: [{
      model: Group,
      as: 'Groups',
      through:{
        attributes: [],
        where: {status: 'done'}
      },
      attributes: []
    }],
    group: [sequelize.col('Person.id')]
  });
})
```

**Expected** SQL generated:
```sql
SELECT ARRAY_AGG("Groups"."id") AS "groupIds"
FROM "People" AS "Person"
LEFT OUTER JOIN (
  "GroupPeople" AS "Groups.GroupPerson" 
  INNER JOIN 
    "Groups" AS "Groups" ON "Groups"."id" = "Groups.GroupPerson"."GroupId" AND "Groups.GroupPerson"."status" = 'done'
) ON "Person"."id" = "Groups.GroupPerson"."PersonId"
GROUP BY "Person"."id";
```

**Actual** SQL generated:
```sql
SELECT "Person"."id", ARRAY_AGG("Groups"."id") AS "groupIds",
  "Groups.GroupPerson"."status" AS "Groups.GroupPerson.status", "Groups.GroupPerson"."createdAt" AS "Groups.GroupPerson.createdAt", 
  "Groups.GroupPerson"."updatedAt" AS "Groups.GroupPerson.updatedAt", "Groups.GroupPerson"."PersonId" AS "Groups.GroupPerson.PersonId",
  "Groups.GroupPerson"."GroupId" AS "Groups.GroupPerson.GroupId"
FROM "People" AS "Person"
LEFT OUTER JOIN (
  "GroupPeople" AS "Groups.GroupPerson"
  INNER JOIN
    "Groups" AS "Groups" ON "Groups"."id" = "Groups.GroupPerson"."GroupId" AND "Groups.GroupPerson"."status" = 'done'
) ON "Person"."id" = "Groups.GroupPerson"."PersonId"
GROUP BY "Person"."id";
```

...which gives the following error:

```
Unhandled rejection SequelizeDatabaseError: column "Groups.GroupPerson.status" must appear in the GROUP BY clause or be used in an aggregate function
    at Query.formatError (/Users/mrorz/workspace/gis-inner/node_modules/sequelize/lib/dialects/postgres/query.js:443:14)
    at null.<anonymous> (/Users/mrorz/workspace/gis-inner/node_modules/sequelize/lib/dialects/postgres/query.js:118:19)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at Query.handleError (/Users/mrorz/workspace/gis-inner/node_modules/pg/lib/query.js:108:8)
    at null.<anonymous> (/Users/mrorz/workspace/gis-inner/node_modules/pg/lib/client.js:171:26)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at Socket.<anonymous> (/Users/mrorz/workspace/gis-inner/node_modules/pg/lib/connection.js:109:12)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

**Comment by mickhansen** [comment]
Odd, that should simply work.

**Comment by joewood** [comment]
I'm seeing something similar with the MSSQL provider.  When any associations are used with an aggregate function all the fields seem to be included in the query, irrespective of the attributes/include/exclude list.

**Comment by dojiboy9** [comment]
ditto for mysql

**Comment by chillichicken** [comment]
can confirm this too for mysql

**Comment by mickhansen** [comment]
There's a confirmed issue with `through.attributes`

**Comment by contra** [comment]
Can also confirm this for postgres...

**Comment by dongseok0** [comment]
Any workaround or updates there?
It was fine with MySQL but I getting this error after I changed to MSSQL.

**Comment by saudpunjwani101** [comment]
Any solutions so far? the problem is a big pain

**Comment by doublerebel** [comment]
Count query generates the expected SQL, while min/max do not.  v3.30.4:

*This is an actual example only user id has been anonymized.*

#### Count
##### Query
```coffee
query =
  include: [
    {model: UserModel, as: "users", where: {id: user.id}, attributes: []}
  ]
  group: "users.id"
```
##### SQL generated
```sql
SELECT count("Lead"."id") AS "count" FROM "Leads" AS "Lead"
  INNER JOIN ("user_leads" AS "users.user_lead"
    INNER JOIN "Users" AS "users"
    ON "users"."id" = "users.user_lead"."UserId")
  ON "Lead"."id" = "users.user_lead"."LeadId" AND "users"."id" = 'sadlkjfsaljsl1234'
  GROUP BY users.id;
```
##### Result
```coffee
[ { count: '22' } ]
```

#### Min
##### Query
```coffee
query =
  include: [
    {model: UserModel, as: "users", where: {id: user.id}, attributes: []}
  ]
  group: "users.id"
```
##### SQL generated
```sql
SELECT min("LastModifiedDate") AS "min", "users.user_lead"."userId" AS "users.user_lead.userId", "users.user_lead"."leadId" AS "users.user_lead.leadId", "users.user_lead"."createdAt" AS "users.user_lead.createdAt", "users.user_lead"."updatedAt" AS "users.user_lead.updatedAt", "users.user_lead"."UserId" AS "users.user_lead.UserId", "users.user_lead"."LeadId" AS "users.user_lead.LeadId"
  FROM "Leads" AS "Lead"
  INNER JOIN ("user_leads" AS "users.user_lead"
    INNER JOIN "Users" AS "users"
    ON "users"."id" = "users.user_lead"."UserId")
  ON "Lead"."id" = "users.user_lead"."LeadId" AND "users"."id" = 'sadlkjfsaljsl1234'
  GROUP BY users.id;
```
##### Result
`SequelizeDatabaseError: column "users.user_lead.userId" must appear in the GROUP BY clause or be used in an aggregate function`

**Comment by doublerebel** [comment]
### Found a Fix!

By changing the query to add `{includeIgnoreAttributes: false}`, I now get the correct result:
```coffee
query =
  includeIgnoreAttributes: false
  include: [
    {model: UserModel, as: "users", where: {id: user.id}, attributes: []}
  ]
  group: "users.id"
```
LeadModel.min("LastModifiedDate", query)
```
##### SQL generated
```sql
SELECT min("LastModifiedDate") AS "min"
  FROM "Leads" AS "Lead"
  INNER JOIN ("user_leads" AS "users.user_lead"
    INNER JOIN "Users" AS "users"
    ON "users"."id" = "users.user_lead"."UserId")
  ON "Lead"."id" = "users.user_lead"."LeadId" AND "users"."id" = 'sadlkjfsaljsl1234'
  GROUP BY users.id;
```
##### Result
`2017-03-14T00:28:11.000Z`

Hope this helps someone else!  I found the clue to `includeIgnoreAttributes` in #6711, grepped the source and found [it was being set to `false` in Model.count](https://github.com/sequelize/sequelize/blob/688dd002b486b77ebd1de5d902c94ab53c70317a/lib/model.js#L1798).

**Comment by contra** [comment]
Still an issue, so yes keep it open.

**Comment by eikaramba** [comment]
glad that my research help someone. and yes +1, this issue is still there.

**Comment by catalsdevelop** [comment]
this problem still stands there in Sequelize V4.2.1

**Comment by contra** [comment]
Keep it open.

**Comment by abeMedia** [comment]
Is there any ETA on this? Pulling my hair out trying to include aggregated data...

**Comment by rich171** [comment]
It seems that includeIgnoreAttributes: false removes all attributes from nested includes that you may be using, so it's only a solution if you don't need those fields returned to you.

**Comment by sovietspaceship** [comment]
same issue here, sequelize 4

**Comment by carloshmm** [comment]
Same issue here, sequelize 4.26 + postgresql.
@doublerebel solution apparently worked: ```includeIgnoreAttributes: false``` 
Where is the documentation for this option? I searched but I didn't find it.

**Comment by Kyderman** [comment]
I can confirm the flag of `includeIgnoreAttributes: false` works.

If you have a User table Team table both linked with a belongsToMany and thus a join table. Doing...

`teams = await currentUser.getTeams({raw: true, includeIgnoreAttributes: false});`

will return you the flat array teams that belong to that user.

Easy as pie.... however, its not documented!

**Comment by idrisadetunmbi** [comment]
It works (not totally sure yet though) but takes out the attributes of the other included models which is not a desired effect.

```
const user = await models.User.findOne({
        where: { id: 1 },
        includeIgnoreAttributes: false,
        group: ['User.id'],
        attributes: {
          include: [
            [models.sequelize.fn('sum', models.sequelize.col('articles.likes')), 'count_likes']
          ]
        },
        include: [{
          model: models.article,
          as: 'articles',
          attributes: [],
        }, {
          model: models.interest
          as: 'interests',
          attributes: ['id', 'title'],
          through: { attributes: [] }
        }]
      });
```
`models.interest` above are never included on the user object.

**Comment by Kyderman** [comment]
That's because of

through: { attributes: [] }

**Comment by papigers** [comment]
Having the same problem as @idrisadetunmbi

**Comment by rodrigoclp** [comment]
includeIgnoreAttributes: false, solves the problem in sequelize 4.

**Comment by abdullahshahin** [comment]
had to spend some time to get here. +1 for keeping this issue open, v4.42

**Comment by giovanimdelcol** [comment]
Today I just spent a lot of hours until find this issue, so commenting just to keep it open. Also, if you do sequelize in typescript, it will not recognize the includeIgnoreAttributes, this I believe is a related issue.

**Comment by roubouen** [comment]
+

**Comment by sassanh** [comment]
I wish I didn't have to notify all subscribed people with this comment, but I saw few unresolved sequelize issues closed just because of inactivity, so... sorry guys. Maybe auto-closing inactive issues should be disabled, sometimes an issue is not active because no one is fixing it and people have nothing to add, not just because it's fixed.

**Comment by papb** [comment]
> Maybe auto-closing inactive issues should be disabled, sometimes an issue is not active because no one is fixing it and people have nothing to add, not just because it's fixed.

Hi @sassanh, I have this concern on my radar, hopefully in the near future I will be reopening all these wrongfully closed issues!

**Comment by sassanh** [comment]
Thanks @papb, It's really heartwarming to see this level of responsibility.

**Comment by papb** [comment]
@sassanh Feel free to ping me on any issue that you believe that needs more attention (although I am just another maintenance, not a magician...)

**Comment by sassanh** [comment]
`thorugh: { attributes: [] }` is ignored because of this line: https://github.com/sequelize/sequelize/blob/master/lib/model.js#L613

And this line which sets `_pseudo` for `through`:
https://github.com/sequelize/sequelize/blob/master/lib/model.js#L635

For those who reach to this thread and think there's a hope that they can do a maneuver over the sequelize API to make `thorugh: { attributes: [] }` work, I wanna state clearly that:

Based on above referenced two lines we know that sequelize doesn't support `thorugh: { attributes: [] }`

Seeing this comment: https://github.com/sequelize/sequelize/issues/5590#issuecomment-197414013 and https://github.com/sequelize/sequelize/issues/5590#issuecomment-197731027 and considering that thread is closed and some other false claims in other threads I had this delusion that sequelize supports it and I just have to find how, It took me hours so I'm writing here to avoid this waste for others.

**Comment by lschnoller** [comment]
This is an issue that MUST be addressed! It's insane not to be able to select a table with a count on associated tables. A very simple query like the one below cannot be achieved with sequelize:
SELECT s.id, s.name, cc.id, cc.name, bu.id, bu.name, COUNT(sc."customerId") FROM subscriptions s LEFT OUTER JOIN "subscriptionsCustomers" sc ON s.id = sc."subscriptionId" AND sc.status = 1 LEFT OUTER JOIN "costCenters" AS cc ON s."costCenterId" = cc."id" AND cc."deletedAt" IS NULL LEFT OUTER JOIN "businessUnits" AS bu ON s."businessUnitId" = bu."id" AND bu."deletedAt" IS NULL WHERE s."deletedAt" IS NULL group by s.id, cc.id, bu.id order by s.id;

**Comment by harrywhitehouse** [comment]
Still a problem. I hope it can be fixed.

**Comment by Relequestual** [comment]
I found this previously merged PR which appeared to fix it in the event you use `raw:true` https://github.com/sequelize/sequelize/pull/4029

However, at a guess, the test is bad because it didn't define the joining table to have a primary column in the definition. =/

**Comment by carlosingles** [comment]
This is still an issue for me, however I have found a workaround if you are using a Model definition for your join table.

Using: **sequelize@5.21.7**

The following is a stripped down example of what I have (using Typescript):

```ts
const User = sequelize.define('User', {
  active: sequelize.Sequelize.BOOLEAN
});

const Tenancy = sequelize.define('Tenancy', {
  name: sequelize.Sequelize.STRING
});

const TenancyUser = sequelize.define('TenancyUser', {
  isAdmin: sequelize.Sequelize.BOOLEAN
})

User.belongsToMany(Tenancy, through: { model: TenancyUser })
Tenancy.belongsToMany(User, through: { model: TenancyUser })

TenancyUser.belongsTo(User)
TenancyUser.belongsTo(Tenancy)

// Find how many active users for a Tenancy.id
const id = 'someid'
TenancyUser.findOne({
  attributes: [
    [
      sequelize.Sequelize.fn(
        'count',
        sequelize.Sequelize.col('User.id')
      ),
      'activeUsers'
    ]
  ],
  include: [
    {
      model: Models.Tenancy,
      where: {
        id: id
      },
      attributes: ['id'],
    },
    {
      model: Models.User,
      where: {
        active: true
      },
      attributes: [],
      required: false
    }
  ],
  group: [
    'Tenancy.id'
  ],
  // bypasses loading this into a Model and gives you a raw row
  // if you don't use this, `activeUsers` is bypassed since there's no attribute to map it to
  raw: true
}) as unknown as {
  // activeUsers is returned as a string NOT a number
  activeUsers: string;
  'Tenancy.id': string;
}
```

This ends up generating the following SQL:

```sql
SELECT
    count("User"."id") AS "activeUsers"
    "Tenancy"."id" AS "Tenancy.id"
FROM
    "TenancyUsers" AS "TenancyUsers"
    INNER JOIN "Tenancies" AS "Tenancy" ON "TenancyUsers"."TenancyId" = "Tenancy"."id"
        AND("Tenancy"."id" = 'someid')
    LEFT OUTER JOIN "Users" AS "User" ON "TenancyUsers"."UserId" = "User"."id"
    AND("User"."active" = TRUE)
GROUP BY
    "Tenancy"."id"
LIMIT 1;
``` 

Which gives me a single row only with 'Tenancy.id' and 'activeUsers'.

**Comment by EinfachHans** [comment]
It's 2021, i use Version `6.5.0` and this is still an issue

**Comment by laurelgr** [comment]
Same problem, got saved by the above workaround of `includeIgnoreAttributes: false`. I too believe this workaround should be documented until the issue is resolved!
Between root `attributes`, include `attributes` and `through` attributes (plus trying out `exclude` magic) on top of group/aggregate it was a pain to debug and search a correct workaround.

**Comment by cirosantilli** [comment]
Here's a more directly runnable repro with some assertions:

```
const assert = require('assert');
const { DataTypes, Sequelize } = require('sequelize');
const sequelize = new Sequelize('tmp', undefined, undefined, Object.assign({
  dialect: 'postgres',
  host: '/var/run/postgresql',
}));
;(async () => {
const User = sequelize.define('User', {
  name: { type: DataTypes.STRING },
}, {});
const Post = sequelize.define('Post', {
  body: { type: DataTypes.STRING },
}, {});
User.belongsToMany(Post, {through: 'UserLikesPost'});
Post.belongsToMany(User, {through: 'UserLikesPost'});
await sequelize.sync({force: true});
const user0 = await User.create({name: 'user0'})
const user1 = await User.create({name: 'user1'})
const user2 = await User.create({name: 'user2'})
const post0 = await Post.create({body: 'post0'})
const post1 = await Post.create({body: 'post1'})
const post2 = await Post.create({body: 'post2'})
// user0 likes post0.
await user0.addPost(post0)
// user1 likes post0 and post2
await post1.addUsers([user0, user2])

// Count how many posts each user has liked.
let rows;
rows = await User.findAll({
  attributes: [
    'name',
    [sequelize.fn('COUNT', sequelize.col('Posts.id')), 'count'],
  ],
  include: [
    {
      model: Post,
      attributes: [],
      required: false,
      through: {attributes: []},
    },
  ],
  group: ['User.name'],
  order: [[sequelize.col('count'), 'DESC']],
})
assert.strictEqual(rows[0].name, 'user0')
assert.strictEqual(rows[0].get('count'), 2)
assert.strictEqual(rows[1].name, 'user2')
assert.strictEqual(rows[1].get('count'), 1)
assert.strictEqual(rows[2].name, 'user1')
assert.strictEqual(rows[2].get('count'), 0)
assert.strictEqual(rows.length, 3)
})().finally(() => { return sequelize.close() });
```

package.json

```
{
  "name": "tmp",
  "private": true,
  "version": "1.0.0",
  "dependencies": {
    "pg": "8.5.1",
    "pg-hstore": "2.3.3",
    "sequelize": "6.5.1",
    "sqlite3": "5.0.2"
  }
}
```

on PostgreSQL 13.4 Ubuntu 21.10 Node.js v14.17.0.

Indented generated query:

```
SELECT
  "User"."id",
  "User"."name",
  COUNT("Posts"."id") AS "count"
FROM
  "Users" AS "User"
  LEFT OUTER JOIN (
    "UserLikesPost" AS "Posts->UserLikesPost"
    INNER JOIN "Posts" AS "Posts" ON "Posts"."id" = "Posts->UserLikesPost"."PostId"
  ) ON "User"."id" = "Posts->UserLikesPost"."UserId"
GROUP BY
  "User"."name"
ORDER BY
  "count" DESC;
```

PostgreSQL disallows the `Users.id` from `SELECT` as it is not grouped by, and could lead to a random value being selected if there were different possible values. Some databases like SQLite allow that though, so it doesn't blow up there.

**Comment by liorsion** [comment]
I can try to help solve this, the issue is with this line, but it's not clear why it's needed:

      if (options.attributes && !options.raw && this.primaryKeyAttribute && !options.attributes.includes(this.primaryKeyAttribute) && (!options.group || !options.hasSingleAssociation || options.hasMultiAssociation)) {

**Comment by moda20** [comment]
Hey, This is 2022 and i am getting an error where sequelize will add an 'id' out of nowhere and break my group query. 
here is the query : 
```
const truncWithIntervalLiteral = Sequelize.literal("CONCAT ( week(checkDate, 0), '_', year(checkDate) )")
        const averagePrice = Sequelize.literal("AVG (COALESCE(price, minPrice))")
        return item
            .findAndCountAll({
                include: [
                    {
                        model: price,
                        as: "prices",
                        attributes: [
                            [truncWithIntervalLiteral, "weekly"],
                            [averagePrice, "AveragePricePerWeek"],
                        ],
                        separate: true,
                        group: ["weekly", "product_id"],
                    },
                ],
            })
```
the resulting sql query is : 

```
SELECT **`id`,** CONCAT ( week(checkDate, 0), '_', year(checkDate) ) AS `weekly`, AVG (COALESCE(price, minPrice)) AS `AveragePricePerWeek`, `product_id` FROM `price` AS `price` WHERE `price`.`product_id` IN ('30133', '35526', '35040') GROUP BY `weekly`, `product_id`;
```
That bold id is not supposed to be there. I tried all the solutions above and it still creates the same sql query with an extra id
Why is this an issue are we doing it the """wrong""" way ?

**Comment by laurelgr** [comment]
@moda20 you are using `findAndCountAll` instead of `findAll` so that may be why the previous solutions don't work for you. I'm not familiar enough with it to tell if there is any relevant difference, so you should first try with a `findAll` to make sure the problem is not unrelated. And I am even less familiar with the **separate** option.

Also, your resulting query only uses one table `price` without any join, and you only have 1 undesired column `id` instead of **all** the existing columns of your table, so I believe your issue might be related specifically to the use of **separate**.

This issue is about generated **join** queries selecting **all** columns. If you run **separate** queries, there is no JOIN in the database query itself since Sequelize will do the join instead.

I see you created your own issue though so I won't go further here. :)
