### ISSUE TITLE
The dialect mssql is not supported error in sequelize version 2.0.0-rc1

### ISSUE THREAD

**Issue by Bigguy34** [sequelize/sequelize#5483]
I am currently running into an issue when I try and run my express app with sequelize, I am using the syncing when the app first starts up. Here is my error message, when I try and run the app.

```
"C:\Program Files (x86)\JetBrains\WebStorm 11.0.2\bin\runnerw.exe" "C:\Program Files (x86)\nodejs\node.exe" bin\www
c:\Users\thofl\Documents\GitHub\SGMTool\node_modules\sequelize\lib\sequelize.js:176
      throw new Error('The dialect ' + this.getDialect() + ' is not supported. ('+err+')');
      ^

Error: The dialect mssql is not supported. (Error: Cannot find module './dialects/mssql')
    at new module.exports.Sequelize (c:\Users\thofl\Documents\GitHub\SGMTool\node_modules\sequelize\lib\sequelize.js:176:13)
    at Object.<anonymous> (c:\Users\thofl\Documents\GitHub\SGMTool\models\index.js:14:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (c:\Users\thofl\Documents\GitHub\SGMTool\bin\www:10:14)
    at Module._compile (module.js:413:34)

Process finished with exit code 1
```
Currently this is what my package.json looks like

```
{
  "name": "test",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "node ./bin/www"
  },
  "dependencies": {
    "body-parser": "~1.13.2",
    "cookie-parser": "~1.3.5",
    "debug": "~2.2.0",
    "express": "~4.13.1",
    "jade": "~1.11.0",
    "morgan": "~1.6.1",
    "sequelize": "^2.0.0-rc1",
    "sequelize-cli": "^2.3.1",
    "serve-favicon": "~2.3.0",
    "tedious": "^1.13.2"
  }
}
```
Notice I have tedious installed, and I am using 2.0.0-rc1. Any suggestions? Is this a bug with 2.0.0-rc1. Do I need to install something else to support mssql dialect?

**Comment by MrOrz** [comment]
```
$ npm install --save mysql // For both mysql and mariadb dialects
```

Ref: http://docs.sequelizejs.com/en/latest/docs/getting-started/

**Comment by janmeier** [comment]
Mssql is not supported I have that version, try a more recent one - the newest version is 3. 19.3

**Comment by Bigguy34** [comment]
I see the problem now, I am using the old documentation, from 1.7.0. Sorry.
