### ISSUE TITLE
Working with BelongTo self relations cannot read property 'getTableName'

### ISSUE THREAD

**Issue by WalterC87** [sequelize/sequelize#5497]
Hello I've created a model with self reference create the table also create the self relation, but when I tried to get info with my "Query", I get this error

### Error
```JavaScript
Unhandled rejection TypeError: Cannot read property 'getTableName' of undefined
    at validateIncludedElement (C:\Users\walte\Documents\GitHub\mvp_probns\node_modules\sequelize\lib\model.js:519:27)
    at C:\Users\walte\Documents\GitHub\mvp_probns\node_modules\sequelize\lib\model.js:447:29
    at Array.map (native)
    at validateIncludedElements (C:\Users\walte\Documents\GitHub\mvp_probns\node_modules\sequelize\lib\model.js:443:37)
    at null.<anonymous> (C:\Users\walte\Documents\GitHub\mvp_probns\node_modules\sequelize\lib\model.js:1346:32)
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at tryCatcher (C:\Users\walte\Documents\GitHub\mvp_probns\node_modules\sequelize\node_modules\bluebird\js\release\util.js:11:23)
    at Promise._settlePromiseFromHandler (C:\Users\walte\Documents\GitHub\mvp_probns\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:489:31)
    at Promise._settlePromise (C:\Users\walte\Documents\GitHub\mvp_probns\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:546:18)
    at Promise._settlePromise0 (C:\Users\walte\Documents\GitHub\mvp_probns\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:591:10)
    at Promise._settlePromises (C:\Users\walte\Documents\GitHub\mvp_probns\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:674:18)
    at Async._drainQueue (C:\Users\walte\Documents\GitHub\mvp_probns\node_modules\sequelize\node_modules\bluebird\js\release\async.js:125:16)
    at Async._drainQueues (C:\Users\walte\Documents\GitHub\mvp_probns\node_modules\sequelize\node_modules\bluebird\js\release\async.js:135:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\walte\Documents\GitHub\mvp_probns\node_modules\sequelize\node_modules\bluebird\js\release\async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

### Sequelize Instruction

```JavaScript
exports.getVendedoresByPadre = function (req, res, next){
	models.Usuario.findAll({
		where: {
			status: 1,
			padreId: req.params.padreId
		},
		attributes: ['id','padreId','userLogin','firstName','lastName','email','telefono1','telefono2','direccion',
					 'website','descripcion','createdAt','status', 'tipoUsuarioId', 'PaiId','estadoUsuarioId',
					 'avatar'],
		include: [
			{
				model: models.tipoUsuario,
				attributes: ['id','descripcion'],
				where:{
					status: 1
				}
			},
			{
				model: models.Pais,
				attributes: ['id', 'descripcion','flag'],
				where: {
					status: 1
				}
			},
			{
				model: models.estadoUsuario,
				attributes: ['id','descripcion'],
				where: {
					status: 1
				}
			},
			{
				model: models.Usuario,
				as: 'Padre',
				attributes: ['id', 'firstName', 'userLogin'],
				where: {
					status: 1,
					padreId: req.params.padreId
				}
			}
		]
	}).then(function (clientes){
		if(!clientes){
			res.status(500);
			res.json({
				type: false,
				data: "Error al obtener los clientes" + clientes
			});
		}else{
			res.status(200);
			res.json({
				type: true,
				data: clientes
			});
		};
	});
};
```

### My Model

```JavaScript
module.exports = function (sequelize, DataTypes){
	var Usuario = sequelize.define('Usuario', {
		userLogin: {
			type: DataTypes.STRING,
			allowNull: false,
			unique: true,
			validate: {
				len: [2,150]
			}
		},
		firstName: {
			type: DataTypes.STRING,
			allowNull: false,
			validate: {
				len: [5,150]
			}
		},
		lastName: {
			type: DataTypes.STRING,
			allowNull: true,
			defaultValue: null,
			validate: {
				len: [5,150]
			}
		},
		password: {
			type: DataTypes.STRING,
			allowNull: false,
			validate: {
				len: [4, 150]
			}
		},
		email: {
			type: DataTypes.STRING,
			allowNull: false,
			validate: {
				isEmail: true
			}
		},
		token:{
			type: DataTypes.STRING,
			allowNull: true,
			defaultValue: null
		},
		telefono1: {
			type: DataTypes.STRING,
			allowNull: true,
			defaultValue: null,
			validate: {
				len: [8,15]
			}
		},
		telefono2: {
			type: DataTypes.STRING,
			allowNull: true,
			defaultValue: null,
			validate: {
				len: [8,15]
			}
		},
		direccion: {
			type: DataTypes.STRING,
			allowNull: true,
			defaultValue: null
		},
		website: {
			type: DataTypes.STRING,
			allowNull: true,
			defaultValue: null
		},
		descripcion: {
			type: DataTypes.STRING,
			allowNull: true,
			defaultValue: null
		},
		avatar: {
			type: DataTypes.STRING,
			allowNull: true,
			defaultValue: null
		},
		verificadoEmail: {
			type: DataTypes.BOOLEAN,
			allowNull: true,
			defaultValue: false
		},
		status: {
			type: DataTypes.BOOLEAN,
			defaultValue: true
		}
	},{
		classMethods: {
			associate: function(models){
				Usuario.belongsTo(models.tipoUsuario, {foreignKey: {allowNull: false}});
				Usuario.belongsTo(models.Pais, {foreignKey: {allowNull: false }});
				Usuario.belongsTo(models.estadoUsuario, {foreignKey: {allowNull: true}});
				Usuario.belongsToMany(models.Inmueble, {through: models.inmuebleUsuario, foreignKey: 'usuarioId'});
				Usuario.belongsToMany(models.tipoAccion, {through: models.accionesBuscador, foreignKey: 'usuarioId'});
				Usuario.hasMany(models.Buscador);
				Usuario.hasMany(models.Agenda);
				Usuario.belongsTo(models.Usuario, {as: 'Padre', foreignKey: {name: 'padreId',field: 'padreId', allowNull: true}});

			}
		},
		freezeTableName: true,
		tableName: 'usuario'
	})

	return Usuario;
}
```

My real problem is when I try to get Info where, the self relation is involved.

Regards.

**Comment by janmeier** [comment]
Please try to trim the issue down - Does it only happen when you have those four includes, or can you show a smaller sample - a smaller sample makes it a lot easier for us to debug

**Comment by WalterC87** [comment]
@janmeier thanks for your help, I found the problem and resolved, I make a mistake when tried to make the comparation in where clause. Regards.
