### ISSUE TITLE
Unable to perform basic query: Unhandled rejection TypeError: (0 , _componentsDate2.default) is not a function

### ISSUE THREAD

**Issue by MaximilianLloyd** [sequelize/sequelize#5523]
I cannot for the life of me figure out why this is not working. Any help would be nice. 

code: 
`User.findAll({
      where: {
        Mobile: "90407931"
      }
    })
    .then((users) => {
...
}`

stack:
`Unhandled rejection TypeError: (0 , _componentsDate2.default) is not a function
    at [object Object].<anonymous> (C:/Users/maxll/Desktop/Projects/poker.no-mobile/server/api/user/user.controller.js:68:26)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Promise.then (C:\Users\maxll\Desktop\Projects\poker.no-mobile\node_modules\sequelize\lib\promise.js:21:17)
    at create (C:/Users/maxll/Desktop/Projects/poker.no-mobile/server/api/user/user.controller.js:52:6)
    at Layer.handle [as handle_request] (C:\Users\maxll\Desktop\Projects\poker.no-mobile\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\maxll\Desktop\Projects\poker.no-mobile\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (C:\Users\maxll\Desktop\Projects\poker.no-mobile\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\maxll\Desktop\Projects\poker.no-mobile\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\maxll\Desktop\Projects\poker.no-mobile\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (C:\Users\maxll\Desktop\Projects\poker.no-mobile\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Users\maxll\Desktop\Projects\poker.no-mobile\node_modules\express\lib\router\index.js:271:10)
    at Function.handle (C:\Users\maxll\Desktop\Projects\poker.no-mobile\node_modules\express\lib\router\index.js:176:3)
    at router (C:\Users\maxll\Desktop\Projects\poker.no-mobile\node_modules\express\lib\router\index.js:46:12)
    at Layer.handle [as handle_request] (C:\Users\maxll\Desktop\Projects\poker.no-mobile\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\maxll\Desktop\Projects\poker.no-mobile\node_modules\express\lib\router\index.js:312:13)
    at C:\Users\maxll\Desktop\Projects\poker.no-mobile\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\Users\maxll\Desktop\Projects\poker.no-mobile\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Users\maxll\Desktop\Projects\poker.no-mobile\node_modules\express\lib\router\index.js:271:10)
    at Layer.handle [as handle_request] (C:\Users\maxll\Desktop\Projects\poker.no-mobile\node_modules\express\lib\router\layer.js:91:12)
    at trim_prefix (C:\Users\maxll\Desktop\Projects\poker.no-mobile\node_modules\express\lib\router\index.js:312:13)
    at C:\Users\maxll\Desktop\Projects\poker.no-mobile\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\Users\maxll\Desktop\Projects\poker.no-mobile\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Users\maxll\Desktop\Projects\poker.no-mobile\node_modules\express\lib\router\index.js:271:10)
    at logger (C:\Users\maxll\Desktop\Projects\poker.no-mobile\node_modules\morgan\index.js:144:5)
    at Layer.handle [as handle_request] (C:\Users\maxll\Desktop\Projects\poker.no-mobile\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\maxll\Desktop\Projects\poker.no-mobile\node_modules\express\lib\router\index.js:312:13)
    at C:\Users\maxll\Desktop\Projects\poker.no-mobile\node_modules\express\lib\router\index.js:280:7`

Screenshot: 
![capture](https://cloud.githubusercontent.com/assets/10583205/13479633/a29455e6-e0d8-11e5-92cc-718d3f0d334e.PNG)

**Comment by MaximilianLloyd** [comment]
Turns out it is the creation and not the retrival that is the problem.

**Comment by MaximilianLloyd** [comment]
Solved it.

**Comment by dmead** [comment]
thanks for that great summary.
