### ISSUE TITLE
SQLITE_ERROR: cannot start a transaction within a transaction

### ISSUE THREAD

**Issue by swege** [sequelize/sequelize#5535]
When using sqlite with `storage: ':memory:'`, it is not possible to execute two or more `findOrCreate` queries.

    db.User.findOrCreate({where: {name: 'foo'}});
    db.User.findOrCreate({where: {name: 'bar'}});

Results in:

    Unhandled rejection SequelizeDatabaseError: SQLITE_ERROR: cannot start a transaction within a transaction
        at Query.formatError (/home/soeren/Projects/my-project/node_modules/sequelize/lib/dialects/sqlite/query.js:348:14)
        at Statement.afterExecute (/home/soeren/Projects/my-project/node_modules/sequelize/lib/dialects/sqlite/query.js:112:29)
        at Statement.replacement (/home/soeren/Projects/my-project/node_modules/sqlite3/lib/trace.js:20:31)
        at Statement.replacement (/home/soeren/Projects/my-project/node_modules/sqlite3/lib/trace.js:20:31)

Sequelize version `3.19.2`

I suppose that this guy had the same issue: http://stackoverflow.com/questions/31926599/sequelize-transactions-conflict

**Comment by swege** [comment]
Just found out about [sequelize transactions](http://docs.sequelizejs.com/en/latest/docs/transactions/).

This works for me, so I guess this issue can be closed:

    db.sequelize.transaction(t => {
        return Promise.all([
            db.User.findOrCreate({where: {name: 'foo'}, transaction: t}),
            db.User.findOrCreate({where: {name: 'bar'}, transaction: t})
        ]);
    });

**Comment by mickhansen** [comment]
`findOrCreate` will create a transaction internally, however this does not work well with two concurrent calls on a sqlite memory setup.
