### ISSUE TITLE
SQLite query interface misses transations

### ISSUE THREAD

**Issue by davidrapin** [sequelize/sequelize#5626]
Sequelize version I use: 3.19.3.

I am using the sequelize to perform table/column updates using the query-interface like this:
```JavaScript
function test() {
  var Sequelize = require('sequelize');
  var fs = require('fs');
  var dbFile = './test_sqlite.db';
  fs.unlinkSync(dbFile);
  var sequelize = new Sequelize('test_schema', null, null, {dialect: 'sqlite', storage: dbFile});
  
  // create table
  sequelize.define('table3', {
    'colA': {
      type: Sequelize.STRING,
      allowNull: true
    }
  }, {timestamps: false});
  return sequelize.sync().then(function() {
    var q = sequelize.getQueryInterface();

    // start transaction
    return sequelize.transaction(function(transaction) {
      var options = {transaction: transaction};
      return q.renameColumn('table3s', 'colA', 'colB', options);
    });
    // end transaction
  });
}
```

This fails, here is the SQL log:
````
Executing (b7b00719-e529-4e4b-8340-a8c278c0d4a2): BEGIN DEFERRED TRANSACTION;
Executing (b7b00719-e529-4e4b-8340-a8c278c0d4a2): -- SQLite is not able to choose the isolation level REPEATABLE READ.
Executing (b7b00719-e529-4e4b-8340-a8c278c0d4a2): -- SQLite does not support SET autocommit.
Executing (b7b00719-e529-4e4b-8340-a8c278c0d4a2): PRAGMA TABLE_INFO(`table3s`);
Executing (b7b00719-e529-4e4b-8340-a8c278c0d4a2): PRAGMA TABLE_INFO(`table3s`);
Executing (default): CREATE TEMPORARY TABLE IF NOT EXISTS `table3s_backup` (`id` INTEGER PRIMARY KEY, `colB` VARCHAR(255));
Executing (default): INSERT INTO `table3s_backup` SELECT `id`, `colA` AS `colB` FROM `table3s`;
Executing (default): DROP TABLE `table3s`;
Executing (default): DROP TABLE `table3s`;
Executing (default): DROP TABLE `table3s`;
Executing (default): DROP TABLE `table3s`;
Executing (default): DROP TABLE `table3s`;
Executing (b7b00719-e529-4e4b-8340-a8c278c0d4a2): ROLLBACK;
Unhandled rejection SequelizeTimeoutError: SQLITE_BUSY: database is locked
    at Query.formatError (/Users/david/Code/linkurious-server/node_modules/sequelize/lib/dialects/sqlite/query.js:345:14)
    at Statement.afterExecute (/Users/david/Code/linkurious-server/node_modules/sequelize/lib/dialects/sqlite/query.js:112:29)
    at Statement.replacement (/Users/david/Code/linkurious-server/node_modules/sqlite3/lib/trace.js:20:31)
    at Statement.replacement (/Users/david/Code/linkurious-server/node_modules/sqlite3/lib/trace.js:20:31)
```

The reason this fails is because the transaction is not used to `CREATE table3s_backup`,  and `DROP TABLE table3s` etc. You can notice that the transaction used for these actions is "default", whoch should not be the case.
**Source of the error**:  none of the call to `sequelize.query()` in https://github.com/sequelize/sequelize/blob/master/lib/dialects/sqlite/query-interface.js use the passed ` options.transaction`.

**Comment by mickhansen** [comment]
PR welcome

**Comment by mickhansen** [comment]
I didn't think that sqlite supported DDL in transactions.

**Comment by davidrapin** [comment]
https://github.com/sequelize/sequelize/pull/5627

**Comment by davidrapin** [comment]
@mickhansen for a reason I don't understand the unit tests have failed with postgres while none of the lines of code are run when using postgres. Any ideas?

**Comment by mickhansen** [comment]
@davidrapin Better to comment on the PR. We have some intermittent errors, not related to your PR in this case.
