### ISSUE TITLE
MariaDB limit error

### ISSUE THREAD

**Issue by cdupetit** [sequelize/sequelize#5640]
I have this error :
```
kipunji-0 (out): Executing (default): SELECT DISTINCT(ID) AS `id` FROM `FILES` AS `File` WHERE `File`.`ID` LIKE 'something%' LIMIT '10';
kipunji-0 (err): SequelizeDatabaseError: MariaDB error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''10'' at line 1
kipunji-0 (err):     at Query.formatError (/opt/ina/Kipunji/node_modules/sequelize/lib/dialects/mysql/query.js:175:14)
kipunji-0 (err):     at Query._callback (/opt/ina/Kipunji/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
kipunji-0 (err):     at Query.Sequence.end (/opt/ina/Kipunji/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
kipunji-0 (err):     at Query.ErrorPacket (/opt/ina/Kipunji/node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
kipunji-0 (err):     at Protocol._parsePacket (/opt/ina/Kipunji/node_modules/mysql/lib/protocol/Protocol.js:280:23)
kipunji-0 (err):     at Parser.write (/opt/ina/Kipunji/node_modules/mysql/lib/protocol/Parser.js:73:12)
kipunji-0 (err):     at Protocol.write (/opt/ina/Kipunji/node_modules/mysql/lib/protocol/Protocol.js:39:16)
kipunji-0 (err):     at Socket.<anonymous> (/opt/ina/Kipunji/node_modules/mysql/lib/Connection.js:96:28)
kipunji-0 (err):     at emitOne (events.js:90:13)
kipunji-0 (err):     at Socket.emit (events.js:182:7)
kipunji-0 (err):     at readableAddChunk (_stream_readable.js:153:18)
kipunji-0 (err):     at Socket.Readable.push (_stream_readable.js:111:10)
kipunji-0 (err):     at TCP.onread (net.js:533:20)
```
I guess it is related to this evolution : 'escape limit and order by arguments to counter possible injection attack' v3.17.0. Did I do something wrong ?
Can you help me.
Thanks in advance.
Cyril

**Comment by mickhansen** [comment]
You need to pass a number to limit/offset, use `parseInt` if using query variables (a good idea in any case to validate your input).
