### ISSUE TITLE
Please help me turn off these warnings

### ISSUE THREAD

**Issue by ORESoftware** [sequelize/sequelize#5650]
```js
Warning: a promise was created in a handler but was not returned from it
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Model.findAll (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/sequelize/lib/model.js:1343:18)
    at /Users/amills001c/WebstormProjects/baymax/AdminUI/routes/mapping-type.js:40:22
    at Layer.handle [as handle_request] (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/layer.js:95:5)
    at /Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/index.js:176:3)
    at router (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/index.js:46:12)
    at /Users/amills001c/WebstormProjects/baymax/AdminUI/app.js:205:33
    at Layer.handle [as handle_request] (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/index.js:312:13)
    at /Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/index.js:271:10)
    at /Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/index.js:618:15
    at next (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/index.js:256:14)
From previous event:
    at Promise.then (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/sequelize/lib/promise.js:21:17)
    at /Users/amills001c/WebstormProjects/baymax/AdminUI/lib/passport/passport-setup.js:96:52
    at pass (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/passport/lib/authenticator.js:353:9)
    at Authenticator.deserializeUser (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/passport/lib/authenticator.js:358:5)
    at SessionStrategy.authenticate (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/passport/lib/strategies/session.js:49:28)
    at attempt (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/passport/lib/middleware/authenticate.js:341:16)
    at authenticate (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/passport/lib/middleware/authenticate.js:342:7)
    at Layer.handle [as handle_request] (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/index.js:312:13)
    at /Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/index.js:271:10)
    at initialize (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/passport/lib/middleware/initialize.js:62:5)
    at Layer.handle [as handle_request] (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/index.js:312:13)
    at /Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/index.js:271:10)
    at _cookieSession (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/cookie-session/index.js:124:5)

Warning: a promise was created in a handler but was not returned from it
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Model.findAll (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/sequelize/lib/model.js:1343:18)
    at /Users/amills001c/WebstormProjects/baymax/AdminUI/routes/mapping-upload.js:50:24
    at Layer.handle [as handle_request] (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/layer.js:95:5)
    at /Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/index.js:271:10)
    at Function.handle (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/index.js:176:3)
    at router (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/index.js:46:12)
    at /Users/amills001c/WebstormProjects/baymax/AdminUI/app.js:205:33
    at Layer.handle [as handle_request] (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/index.js:312:13)
    at /Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/index.js:271:10)
    at /Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/index.js:618:15
    at next (/Users/amills001c/WebstormProjects/baymax/AdminUI/node_modules/express/lib/router/index.js:256:14)
```

according to the author of Bluebird, the warnings are not internal to Bluebird, so I believe they are added by Sequelize somehow?

**Comment by sushantdhiman** [comment]
From Bluebird website [docs](http://bluebirdjs.com/docs/api/environment-variables.html)

> BLUEBIRD_DEBUG - If set this will enable long stack traces and warnings, unless those are explicitly disabled. Setting this to exactly 0 can be used to override NODE_ENV=development enabling long stack traces and warnings.
> BLUEBIRD_WARNINGS - if set exactly to 0 it will explicitly disable warnings and this overrides any other setting that might enable warnings. If set to any truthy value, it will explicitly enable warnings.
> BLUEBIRD_LONG_STACK_TRACES - if set exactly to 0 it will explicitly disable long stack traces and this overrides any other setting that might enable long stack traces. If set to any truthy value, it will explicitly enable long stack traces.

You can set `BLUEBIRD_WARNINGS` to  `0`

**Comment by mickhansen** [comment]
Most of the time it's on the user side

**Comment by ORESoftware** [comment]
Ok I think I need your help

as per
https://github.com/petkaantonov/bluebird/issues/832

and this:
http://bluebirdjs.com/docs/api/promise.config.html

can you PLEASE expose the bluebird Promise object that your lib uses so I can configure it in my app? Importing bluebird myself and configuring that probably won't work at all, (I tried).

**Comment by mickhansen** [comment]
It's exposed via `Sequelize.Promise`

**Comment by mickhansen** [comment]
You can also configure those things with ENV tho.

**Comment by ORESoftware** [comment]
yeah thanks, I tried with BLUEBIRD_WARNINGS=0 or whatever, but that didn't work, starting to get desperate

**Comment by ORESoftware** [comment]
using this worked for me, thank goodness

```
const Promise = require('sequelize').Promise;
//bluebird promises
Promise.config({
    // Enable warnings
    warnings: false,
    // Enable long stack traces
    longStackTraces: true,
    // Enable cancellation
    cancellation: true,
    // Enable monitoring
    monitoring: true
});
```

however, it is my belief that sequelize has some internal problem. Because no matter what I did with my code, the warning would still appear. I was returning everything inside and outside the promises, yet still the warning would show, so it must be some internal code inside sequelize.

**Comment by mickhansen** [comment]
@ORESoftware It's definitely possible that there's still some lingering issues inside Sequelize. However none of my projects have these warnings (and i've never disabled them either).

I do only use postgres though.

**Comment by ORESoftware** [comment]
well, we have a hint, and it's right in front of our eyes

"Warning: a promise was created in a handler but was not returned from it
    at processImmediate [as _immediateCallback] (timers.js:383:17)"

my guess is that there is some code that looks like this:

```js
someCall().then(function(){
   setImmediate(function(){
       return new Promise();
   })
});
```
something like that is probably happening.

**Comment by mickhansen** [comment]
@ORESoftware processImmediate is part of node core, bluebird uses that code itself, so that's not the root cause, it's just part of the stack.
