### ISSUE TITLE
Using options.attributes as Object in beforeFind hook is failling.

### ISSUE THREAD

**Issue by ppinel** [sequelize/sequelize#5675]
Hi,

Before getting into the issue, thank you for your hard work!

Based on this issue https://github.com/sequelize/sequelize/issues/4074#issuecomment-172314249 I added some code to exclude attributes.

I am using sequelize ```3.19.3```.

```
let connection = _.extend( {},  config.get( 'databases.mysql.default' ) );

connection.define = {
    hooks: {
        beforeFind: function( options ){
            if( _.isUndefined( options.attributes ) ){
                options.attributes = {};
                options.attributes.exclude = [ 'created_at', 'updated_at', 'deleted_at' ];
            }

            return options;
        }
    }
};

const sequelize = new Sequelize( connection.database, connection.username, connection.password, connection );
```

The object connection is define in a config file and looks like: 

```
{
  "username": "plop",
   "password": "plap_plip_ploup",
   "database": "dev",
   "host":     "127.0.0.1",
   "sync": {
     "force": false
   }
}
````

A model looks like: 
```
'use strict';

module.exports = function( sequelize, DataTypes ){
    var Consumer = sequelize.define( 'consumer', {
        id: {
            type:          DataTypes.INTEGER,
            primaryKey:    true,
            autoIncrement: true,
            unique:        true
        },
        name: {
            type:      DataTypes.STRING( 64 ),
            allowNull: false,
            validate:  {
                notEmpty: true,
                is:       /^[a-zA-ZÀ-ÿ0-9\- ]{2,64}$/
            }
        },
        key: {
            type:      DataTypes.STRING( 128 ),
            unique:    true,
            allowNull: false,
            validate:  {
                notEmpty: true,
                is:       /^[a-zA-ZÀ-ÿ0-9\-]{2,128}$/
            }
        },
        secret: {
            type:      DataTypes.STRING( 64 ),
            allowNull: false,
            validate:  {
                notEmpty: true,
                is:       /^[a-zA-ZÀ-ÿ0-9\+=\./\$&\*\\]{2,64}$/
            }
        },
        email: {
            type:      DataTypes.STRING( 128 ),
            allowNull: true,
            unique:    true,
            validate:  {
                notEmpty: true,
                isEmail:  true
            }
        }
    }, {
        classMethods: {
            associate: function( models ){
            }
        },
        paranoid: true
    });

    return Consumer;
};
```

and they are loaded this way:
```
var walker = function( dir ){
    fs
        .readdirSync( dir )
        .forEach( ( file ) => {
            file = path.resolve( dir, file );
            var stat = fs.statSync( file );
            if( stat && stat.isDirectory() ){
                walker( file );
            }
            else if( stat && file.slice( -9 ) == '.model.js' ){
                const model = sequelize[ 'import' ]( file );
                console.log( '[Sequelize] Model found: ' + model.name );
                db[ model.name ] = model;
            }
        });
};

walker( __dirname + '/../app' );

Object.keys( db ).forEach( ( modelName ) => {
    if ( db[ modelName ].associate ){
        db[ modelName ].associate( db );
    }
});
```

My issue is that Sequelize throw an error on queries because option.attributes is not an array but an object as initialize in the hook.
Therefore, slice is not a fonction on Object.

Where the error come from: https://github.com/sequelize/sequelize/blob/master/lib/dialects/abstract/query-generator.js#L1026

Full error:
```
Debug: error, database, create 
    TypeError: options.attributes.slice is not a function
    at Object.QueryGenerator.selectQuery (/home/ppinel/pickit/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1026:67)
    at QueryInterface.select (/home/ppinel/pickit/node_modules/sequelize/lib/query-interface.js:661:25)
    at null.<anonymous> (/home/ppinel/pickit/node_modules/sequelize/lib/model.js:1408:32)
    at tryCatcher (/home/ppinel/pickit/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ppinel/pickit/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/home/ppinel/pickit/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/home/ppinel/pickit/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/home/ppinel/pickit/node_modules/bluebird/js/release/promise.js:684:18)
    at Async._drainQueue (/home/ppinel/pickit/node_modules/bluebird/js/release/async.js:126:16)
    at Async._drainQueues (/home/ppinel/pickit/node_modules/bluebird/js/release/async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/ppinel/pickit/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

It might be an error on my side. Can you help me please?

Pierre-Antoine

**Comment by ppinel** [comment]
I also tried this way:
```
sequelize.addHook( 'beforeFind', ( options ) => {
    if( _.isUndefined( options.attributes ) ){
        options.attributes = {};
        options.attributes.exclude = [ 'created_at', 'updated_at', 'deleted_at' ];
    }

    return options;
//});
```

**Comment by sushantdhiman** [comment]
**SSCCE Test**

```js
/*
 * Copy this file to ./sscce.js
 * Add code from issue
 * npm run sscce-{dialect}
 */

var Sequelize = require('./index');
var sequelize = require('./test/support').createSequelizeInstance();

sequelize.addHook('beforeFind', (options) => {
  if (!options.attributes) {
      options.attributes = {};
      options.attributes.exclude = [ 'createdAt', 'updatedAt' ];
  }
});

var U = sequelize.define('U', {
  name: Sequelize.STRING
}, { timestamps: true });

sequelize.sync({ force: true })
.then(() => U.findAll())
.then(console.log)
.catch(console.error);
```

**Output**

```js
Using database:  sequelize-test-26
TypeError: options.attributes.slice is not a function
    at Object.selectQuery (/var/www/sequelize/lib/dialects/abstract/query-generator.js:1003:67)
    at QueryInterface.select (/var/www/sequelize/lib/query-interface.js:634:27)
    at Promise.try.then.then.then (/var/www/sequelize/lib/model.js:1343:34)
From previous event:
    at Promise.then (/var/www/sequelize/lib/promise.js:21:17)
    at Object.<anonymous> (/var/www/sequelize/sscce_template.js:22:2)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3

```

**Comment by daniloas80** [comment]
Hi guys, 
I will share with you how I solved this issue.
Below is part of my User model

`const User = sequelize.define('users', {
  name: DataTypes.STRING,
  email: DataTypes.STRING,
  password: DataTypes.STRING
}, {
  hooks: {   
    beforeFind: (users, options) => {
      if (!users.attributes) {
        users.attributes = {}
        users.attributes.exclude = ['password', 'created_at', 'updated_at']
      }
    }
  },
  sequelize
})

module.exports = User`
