### ISSUE TITLE
validator.extend error 

### ISSUE THREAD

**Issue by cevallosmanzano** [sequelize/sequelize#5782]
I created a Node.js. I installed Sequelize with Postgres.  When I want to run my project, console show me next error 

> c:\Users\Carlos\WebstormProjects\testsqlz\node_modules\sequelize\lib\utils\validator-extras.js:78
  validator.extend(key);
            ^
TypeError: Object  has no method 'extend'
    at module.exports.extensions (c:\Users\Carlos\WebstormProjects\testsqlz\node_modules\sequelize\lib\utils\validator-extras.js:78:13)
    at c:\Users\Carlos\WebstormProjects\testsqlz\node_modules\sequelize\node_modules\lodash\lodash.js:4040:15
    at baseForOwn (c:\Users\Carlos\WebstormProjects\testsqlz\node_modules\sequelize\node_modules\lodash\lodash.js:2573:24)
    at c:\Users\Carlos\WebstormProjects\testsqlz\node_modules\sequelize\node_modules\lodash\lodash.js:4009:18
    at Function.forEach (c:\Users\Carlos\WebstormProjects\testsqlz\node_modules\sequelize\node_modules\lodash\lodash.js:7634:11)
    at Object.<anonymous> (c:\Users\Carlos\WebstormProjects\testsqlz\node_modules\sequelize\lib\utils\validator-extras.js:77:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (c:\Users\Carlos\WebstormProjects\testsqlz\node_modules\sequelize\lib\instance-validator.js:3:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

I don't know how to solve this issue. If I delete the next code in line 78-80 and my project work. 

> _.forEach(extensions, function(extend, key) {
  validator.extend(key, extend);
});   

How I can solve correctly this problem? 
Thank you so much

**Comment by janmeier** [comment]
Seems the `extend` method has been removed in 5.0 - https://github.com/chriso/validator.js/blob/master/CHANGELOG.md

However, our dependencies list 4.6, so I don't know why its installing 5...
