### ISSUE TITLE
Updating record with plain object in where clause for json/jsonb field doesn't work

### ISSUE THREAD

**Issue by pmckinnon** [sequelize/sequelize#5811]
When you try to update a record using a plain javascript object for a json field in the where clause, an attempt to escape it as if it were a string results in a traceback. The withItemQuery doesn't include the model in the options so the escape function doesn't know how to escape it as a json literal.

``` javascript
var Sequelize = require('sequelize');

var db = new Sequelize("postgresql://postgres:postgres@localhost/sequelize");

var model = db.define('test', {
  json: { type: Sequelize.JSONB, allowNull: false, defaultValue: {} }
});

db.sync({force: true}).then(function() {
  // Executing (default): SELECT "id", "json", "createdAt", "updatedAt" FROM "tests" AS "test" WHERE ("test"."json"#>>'{key}') = 'value' LIMIT 1;
  model.findOne({
    where: {
      json: {
        key: 'value'
      }
    }
  });


  // Unhandled rejection TypeError: val.replace is not a function
  //     at Object.SqlString.escape (node_modules/sequelize/lib/sql-string.js:61:15)
  //     at Object.QueryGenerator.escape (node_modules/sequelize/lib/dialects/abstract/query-generator.js:977:22)
  //     at Object.QueryGenerator.whereItemQuery (node_modules/sequelize/lib/dialects/abstract/query-generator.js:2242:22)
  //     at node_modules/sequelize/lib/dialects/abstract/query-generator.js:1873:25
  //     at node_modules/lodash/lodash.js:4332:15
  //     at baseForOwn (node_modules/lodash/lodash.js:2731:24)
  //     at Function.forOwn (node_modules/lodash/lodash.js:12042:24)
  //     at Object.QueryGenerator.whereItemsQuery (node_modules/sequelize/lib/dialects/abstract/query-generator.js:1872:9)
  //     at Object.QueryGenerator.whereQuery (node_modules/sequelize/lib/dialects/abstract/query-generator.js:1844:22)
  //     at Object.QueryGenerator.updateQuery (node_modules/sequelize/lib/dialects/abstract/query-generator.js:480:19)
  //     at QueryInterface.bulkUpdate (node_modules/sequelize/lib/query-interface.js:599:33)
  //     at node_modules/sequelize/lib/model.js:2636:32
  //     at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
  //     at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:502:31)
  //     at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:559:18)
  //     at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:604:10)
  model.update({}, {
    where: {
      json: {
        key: 'value'
      }
    }
  });
});
```

**Comment by pmckinnon** [comment]
Because of this, it's also possible to hack around the bug by stringifying the json field value in the where clauses because it doesn't escape double quotes like a normal string.

```javascript
var Sequelize = require('sequelize');

var db = new Sequelize("postgresql://postgres:postgres@localhost/sequelize");

var model = db.define('test', {
  json: { type: Sequelize.JSONB, allowNull: false, defaultValue: {} }
});

db.sync({force: true}).then(function() {

  const json = JSON.stringify({
    key: 'value'
  });

  // Executing (default): SELECT "id", "json", "createdAt", "updatedAt" FROM "tests" AS "test" WHERE "test"."json" @> '"{\"key\":\"value\"}"' LIMIT 1;
  model.findOne({
    where: {
      json: {
        $contains: json
      }
    }
  });

  // Executing (default): UPDATE "tests" SET "updatedAt"='2016-04-27 23:15:36.682 +00:00' WHERE "json" @> '{"key":"value"}'
  model.update({}, {
    where: {
      json: {
        $contains: json
      }
    }
  });
});
```

**Comment by ilaipi** [comment]
It works, thanks
@pmckinnon
