### ISSUE TITLE
"TypeError: val.replace is not a function" using add{Model} method with Object as param

### ISSUE THREAD

**Issue by exos** [sequelize/sequelize#5813]
```
     TypeError: val.replace is not a function
      at Object.SqlString.escape (node_modules/sequelize/lib/sql-string.js:61:15)
      at Object.QueryGenerator.escape (node_modules/sequelize/lib/dialects/abstract/query-generator.js:973:22)
      at node_modules/sequelize/lib/dialects/abstract/query-generator.js:2165:23
      at Array.map (native)
      at Object.QueryGenerator.whereItemQuery (node_modules/sequelize/lib/dialects/abstract/query-generator.js:2164:49)
      at node_modules/sequelize/lib/dialects/abstract/query-generator.js:1865:25
      at node_modules/sequelize/node_modules/lodash/lodash.js:4040:15
      at baseForOwn (node_modules/sequelize/node_modules/lodash/lodash.js:2573:24)
      at Function.forOwn (node_modules/sequelize/node_modules/lodash/lodash.js:11030:24)
      at Object.QueryGenerator.whereItemsQuery (node_modules/sequelize/lib/dialects/abstract/query-generator.js:1864:9)
      at Object.QueryGenerator.whereQuery (node_modules/sequelize/lib/dialects/abstract/query-generator.js:1836:22)
      at Object.QueryGenerator.updateQuery (node_modules/sequelize/lib/dialects/sqlite/query-generator.js:151:19)
      at QueryInterface.bulkUpdate (node_modules/sequelize/lib/query-interface.js:599:33)
      at node_modules/sequelize/lib/model.js:2630:32
      at bound (domain.js:287:14)
      at runBound (domain.js:300:12)
```

MailPool model: https://paste.kde.org/p3y3kmx44
Attach model: https://paste.kde.org/plpfw70cv

Test code:
```
        describe("~addAttach", () => {
        
            it("Add an attach", (done) => {
            
                models.MailPool.create({
                    to: 'mail@host.com',
                    subject: 'Subject',
                    content: 'Content'
                }).then((mail) => {
                
                    mail.addAttach({
                        name: "readme.txt",
                        path: "/tmp/readme"
                    }).then(() => {
                        console.log(arguments);
                    }).catch(done);
                
                }).catch(done);

            });

        });
```

__Dialect:__ sqlite
__Database version:__ (sqlite3) 3.1.2
__Sequelize version:__ 3.20.0

**Comment by janmeier** [comment]
`add` expects a sequelize instance or the primary key - To create a new row, use `create`  http://docs.sequelizejs.com/en/latest/api/associations/has-many/
