### ISSUE TITLE
Cannot read property 'hasNotification' of undefined?

### ISSUE THREAD

**Issue by jack-fraser** [sequelize/sequelize#5895]
## What you are doing?

I am attempting to initialize my tables by using `sequelize.sync({force:true});` and then dynamically load the tables for use in my web app.

```js
// index.js ... syncs db and loads tables

"use strict";

var fs = require("fs");
var path = require("path");
var Sequelize = require("sequelize");
var sequelize = new Sequelize("connection string here", {
    logging: false
});
var db = {};

sequelize.sync({
    force: true
});

fs
    .readdirSync(__dirname)
    .filter(function(file) {
        return (file.indexOf(".") !== 0) && (file !== "index.js");
    })
    .forEach(function(file) {
        var model = sequelize.import(path.join(__dirname, file));
        db[model.name] = model;
    });

Object.keys(db).forEach(function(modelName) {
    if ("associate" in db[modelName]) {
        db[modelName].associate(db);
    }
});

db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;
```

```js
// user.js where the problem arises

module.exports = function(sequelize, DataTypes) {
    var User = sequelize.define('User', {
        user_id: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true
        },
        username: {
            type: DataTypes.STRING,
            unique: true
        },
        password: DataTypes.STRING,
        hasNotification: {
            type: DataTypes.BOOLEAN,
            defaultValue: false,
        }
    }, {
        timestamps: false,
        tableName: 'User',
        classMethods: {
            associate: function(models) {
                User.hasMany(models.Notification, {
                    foreignKey: 'userId'
                });
            }
        }
    });

    return User;
}

```

```js

//notification.js

module.exports = function(sequelize, DataTypes) {
    var Notification = sequelize.define('Notification', {
        notification_id: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true
        },
        userId: DataTypes.INTEGER
    }, {
        timestamps: false,
        tableName: 'Notification',
        classMethods: {
            associate: function(models) {
                Notification.belongsTo(models.User, {
                    foreignKey: 'userId',
                    as: 'User'
                });
            }
        }
    });

    return Notification;
}

```
## What do you expect to happen?
I expected to be able to run this code without any error. Everything seems to be valid javascript and when I run the code without the 'hasNotification' property everything runs as I would expect it to.

## What is actually happening?
I get an error... TypeError: cannot read property 'hasNotification' of undefined.

```
TypeError: Cannot read property 'hasNotification' of undefined
    at Instance.set (C:\dummy\node_modules\sequelize\lib\instance.js:306:38)
    at funcs.(anonymous function) (C:\dummy\node_modules\sequelize\lib\model.js:772:23)
    at HasMany.mixin (C:\dummy\node_modules\sequelize\lib\associations\has-many.js:242:33)
    at Mixin.hasMany (C:\dummy\node_modules\sequelize\lib\associations\mixin.js:189:15)
    at sequelize.define.classMethods.associate (C:\dummy\db\user.js:22:22)
    at C:\dummy\db\index.js:29:23
    at Array.forEach (native)
    at Object.<anonymous> (C:\dummy\db\index.js:27:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\dummy\server.js:8:11)
    at Module._compile (module.js:460:26)
```

If all I change is the name of the property (e.g. hasNotification -> notification) it runs like I would expect. Is there some collision with hasNotification?

Thanks.

__Dialect:__ postgres
__Database version:__ 9.4
__Sequelize version:__ 3.23.2

**Comment by janmeier** [comment]
Yep, there is a name clash with the `hasAssociation` method http://docs.sequelizejs.com/en/latest/api/associations/has-many/#hasassociationinstance-options-promise, which allows you to check if a user is associated to a notification.
