### ISSUE TITLE
Cannot read property 'getTableName' of undefined

### ISSUE THREAD

**Issue by cody-c-lewis** [sequelize/sequelize#5910]
## What you are doing?
The following code throws an error:

```js
var Sequelize = require('sequelize');
var sequelize = new Sequelize('postgres://user:pass@example.com:5432/dbname');

var User = sequelize.define('user', {
  firstName: {
    type: Sequelize.STRING,
    field: 'first_name' // Will result in an attribute that is firstName when user facing but first_name in the database
  },
  lastName: {
    type: Sequelize.STRING
  }
}, {
  freezeTableName: true // Model tableName will be the same as the model name
});

User.sync({force: true})
.then(function () {
  // Table created
  return User.create({
    firstName: 'John',
    lastName: 'Hancock'
  });
})
.then(function(){
	return User.findAll({});
})
.then(function(){
	var searchFunc = User.findAll;
	searchFunc({}); // This will fail
});
```

## What do you expect to happen?
There should be no error.

## What is actually happening?
```
Executing (default): DROP TABLE IF EXISTS "user" CASCADE;
Executing (default): CREATE TABLE IF NOT EXISTS "user" ("id"   SERIAL , "first_name" VARCHAR(255), "lastName" VARCHAR(255), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'user' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
Executing (default): INSERT INTO "user" ("id","first_name","lastName","createdAt","updatedAt") VALUES (DEFAULT,'John','Hancock','2016-05-17 20:13:29.927 +00:00','2016-05-17 20:13:29.927 +00:00') RETURNING *;
Executing (default): SELECT "id", "first_name" AS "firstName", "lastName", "createdAt", "updatedAt" FROM "user" AS "user";
Unhandled rejection TypeError: Cannot read property 'getTableName' of undefined
    at Model.findAll (/opt/server/node_modules/sequelize/lib/model.js:1344:18)
    at /opt/server/demo.js:29:2
    at tryCatcher (/opt/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/server/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/opt/server/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/opt/server/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/opt/server/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (/opt/server/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/opt/server/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/opt/server/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

The problem seems to be that when you put `User.findAll` in a variable it messes up `this`, which becomes `undefined`.

__Dialect:__ postgres
__Sequelize version:__ 3.23.2

**Comment by janmeier** [comment]
That's just how javascript works - theres not really anything we can do about that. Our code relies strongly on being able to use this (otherwise it would have to be insanely convoluted ;)

Use you can `bind / call`, make a wrapper function (`searchFunc = function () { return User.findAll.apply(User, arguments); }`)
