### ISSUE TITLE
dropTable not working for simple up/down migration

### ISSUE THREAD

**Issue by twler** [sequelize/sequelize#5922]
## What you are doing?
Simple migration to create or drop a table.

```coffeescript
    "use strict"
    module.exports =
      up: (queryInterface, Sequelize) ->
        queryInterface.createTable 'MyTable',
          {
            id:           type: Sequelize.INTEGER, primaryKey: true, autoIncrement: true
            other_field:  type: Sequelize.STRING
          }

      down: (queryInterface, Sequelize) ->
        queryInterface.dropTable 'MyTable'
```

## What do you expect to happen?
I expect it to create the table on `sequelize db:migrate --coffee` and drop the table on `sequelize db:migrate:undo --coffee`

## What is actually happening?
It creates the table correctly on `sequelize db:migrate --coffee`, but throws an error on `sequelize db:migrate:undo --coffee`.  The table is actually dropped, but subsequent call to `sequelize db:migrate --coffee` to recreate the table does not work because `No migrations were executed, database schema was already up to date.`

```
$ sequelize db:migrate --coffee

Sequelize [Node: 5.8.0, CLI: 2.3.1, ORM: 2.0.0-rc4, pg: ^4.3.0]

Loaded configuration file "config/config.json".
Using environment "development".
Using gulpfile /usr/local/lib/node_modules/sequelize-cli/lib/gulpfile.js
Starting 'db:migrate'...
Finished 'db:migrate' after 130 ms
== 20160518144735-create-mytable: migrating =======
== 20160518144735-create-mytable: migrated (0.121s)

$ sequelize db:migrate:undo --coffee

Sequelize [Node: 5.8.0, CLI: 2.3.1, ORM: 2.0.0-rc4, pg: ^4.3.0]

Loaded configuration file "config/config.json".
Using environment "development".
Using gulpfile /usr/local/lib/node_modules/sequelize-cli/lib/gulpfile.js
Starting 'db:migrate:undo'...
Finished 'db:migrate:undo' after 87 ms
== 20160518144735-create-mytable: reverting =======
Possibly unhandled TypeError: Cannot assign to read only property 'attribute' of tableName
  at [object Object].module.exports.ModelManager.getDAO (/usr/local/lib/node_modules/sequelize/lib/model-manager.js:29:23)
  at /usr/local/lib/node_modules/sequelize/lib/query-interface.js:191:57
  at tryCatch1 (/usr/local/lib/node_modules/sequelize/node_modules/bluebird/js/main/util.js:45:21)
  at Promise$_callHandler [as _callHandler] (/usr/local/lib/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:660:13)
  at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/usr/local/lib/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:675:18)
  at Promise$_settlePromiseAt (/usr/local/lib/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:845:14)
  at Promise._settlePromiseAt (/usr/local/lib/node_modules/sequelize/lib/promise.js:66:18)
  at Promise$_settlePromises [as _settlePromises] (/usr/local/lib/node_modules/sequelize/node_modules/bluebird/js/main/promise.js:988:14)
  at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/usr/local/lib/node_modules/sequelize/node_modules/bluebird/js/main/async.js:77:12)
  at Async$consumeFunctionBuffer (/usr/local/lib/node_modules/sequelize/node_modules/bluebird/js/main/async.js:40:14)
  at _combinedTickCallback (node.js:370:9)
  at process._tickCallback (node.js:401:11)
```

__Dialect:__ postgres
__Database version:__ 9.4.0.1
__Sequelize version:__ 2.0.0-rc4

**Comment by sushantdhiman** [comment]
Your `Sequelize` version is way old, I have some `dropTable` migrations and they work find in `v3` and `master`.

Does this issue just started to happen or this is the first time you have tried to do `dropTable` in current code?

**Comment by twler** [comment]
We upgraded from 1.7 and fixed all breaking changes a couple months ago.  We had run these commands successfully under the old API, but probably not with 2.0.

This feels like pretty basic functionality.  Is the only suggested solution to upgrade to 3.0 and deal with the next batch of API and breaking changes?

**Comment by janmeier** [comment]
Our team is unfortunately too small to commit to maintaining any form of LTS for older releases. I'm sorry, but we only have limited amounts of time :(

You are however welcome to look into the issue yourself and make a PR, then I'll guide you along and publish a new version once the bug is fixed

**Comment by twler** [comment]
I can look into it, but any ideas on where to start?

**Comment by janmeier** [comment]
https://github.com/sequelize/sequelize/blob/d47a702f47c1f57c87607e32c00c367e41593c22/lib/query-interface.js#L198

**Comment by sushantdhiman** [comment]
Closing because issue is related to fairly outdated version of Sequelize ( i.e `2.0.0-rc4`). Please use latest version or `v3@latest` where this issue has been fixed.
