### ISSUE TITLE
Lodash Dependency Error

### ISSUE THREAD

**Issue by NewETown** [sequelize/sequelize#5972]
## What you are doing?
Running Sequelize on Node 6.1.0 in a Windows environment (Azure Websites)

## What do you expect to happen?
This builds correctly on my Mac, I can't see into the server well enough to know what the difference is.

Edit: this is running with the --harmony flag

```js
D:\home\site\wwwroot\node_modules\sequelize\node_modules\lodash\lodash.js:1143
    set.forEach(function(value) {
        ^
TypeError: Object #<Set> has no method 'forEach'
    at setToArray (D:\home\site\wwwroot\node_modules\sequelize\node_modules\lodash\lodash.js:1143:9)
    at runInContext (D:\home\site\wwwroot\node_modules\sequelize\node_modules\lodash\lodash.js:4914:35)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\sequelize\node_modules\lodash\lodash.js:16212:11)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\sequelize\node_modules\lodash\lodash.js:16242:3)
```

__Dialect:__ postgres
__Database version:__ Not related to DB
__Sequelize version:__ Latest (updated 2 days ago from NPM)

**Comment by janmeier** [comment]
Please show some code that reproduces the error - We are running our complete test suite against node 6 without errors

**Comment by NewETown** [comment]
It's on startup in an Azure Websites VM, I'm not really sure what code I can show you that would help. Have you successfully deployed in a Windows environment?

This is the full output I have to work with:

```js
D:\home\site\repository>node --harmony --use_strict D:\home\site\wwwroot\app.js 

D:\home\site\wwwroot\node_modules\sequelize\node_modules\lodash\lodash.js:1143
    set.forEach(function(value) {
        ^
TypeError: Object #<Set> has no method 'forEach'
    at setToArray (D:\home\site\wwwroot\node_modules\sequelize\node_modules\lodash\lodash.js:1143:9)
    at runInContext (D:\home\site\wwwroot\node_modules\sequelize\node_modules\lodash\lodash.js:4914:35)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\sequelize\node_modules\lodash\lodash.js:16212:11)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\sequelize\node_modules\lodash\lodash.js:16242:3)
```

From my package.json - "sequelize": "^3.23.2"

**Comment by janmeier** [comment]
Hmm, there must be a longer stack-trace somewhere - lodash must be called from somewhere :)

None of the core devs are on windows, and we can't test against windows on travis (And if there is a platform related error, its most likely in a dependency or in node, not in sequelize itself

**Comment by NewETown** [comment]
I brought the version down to 5.9.1 and it deployed with some kind of other error... Going to keep investigating and will report back. I'm sure this is just a weird Windows thing.

**Comment by NewETown** [comment]
Apparently changing to a different version and back again is Windows for "fixing things"... Thanks for the quick response, closing this out.
