### ISSUE TITLE
UUIDV4 results in "val.replace is not a function"

### ISSUE THREAD

**Issue by taoeffect** [sequelize/sequelize#6016]
## What you are doing?

```js
var Sequelize = require('Sequelize')

db.Income = db.define('Model', {
  id: {type: Sequelize.UUID, primaryKey: true, defaultValue: Sequelize.UUIDV4},
```

Elsewhere:

```js
      var [instance, created] = await db.Model.findOrCreate({
        where: {userId: userId, month: currentMonth}, defaults: {value: value}
      })
```

## What do you expect to happen?

For it to work.

## What is actually happening?

Bizarre error related to `"val.replace is not a function"` which I've seen elsewhere in these issues, that appears to crop up under various **different** circumstances.

**EDIT:** the stack trace goes through the call to `findOrCreate`.

## Solution

This appears to be a bug in either the documentation on UUIDV4 usage, or in the implementation.

This is fixed simply by doing:

```js
var uuid = require('node-uuid')
var Sequelize = require('Sequelize')

db.Income = db.define('Model', {
  id: {type: Sequelize.UUID, primaryKey: true, defaultValue: uuid.v4},
```

__Dialect:__ `:memory:` (using sqlite)
__Database version:__ N/A
__Sequelize version:__ `3.23.3`

**Comment by janmeier** [comment]
Seems to work fine for me, can you provide a full [SSCCE](HTTP://SSCCE.ORG/) (and perhaps test against latest master)

**Comment by janmeier** [comment]
```js

var User = sequelize.define('user', {
  id: {type: Sequelize.UUID, primaryKey: true, defaultValue: Sequelize.UUIDV4}
});


return sequelize.sync({
  force: true,
  logging: console.log
})
  .then(() =>  User.findOrCreate({
    where: {id: '1f053c2f-d012-48b2-8cab-c490d20166f2'}, defaults: {}
  }))
  .finally(() => sequelize.close());
```
```sql
Executing (e26094e5-439a-4bc5-a8c8-34ad20a42647): BEGIN DEFERRED TRANSACTION;
Executing (e26094e5-439a-4bc5-a8c8-34ad20a42647): SELECT `id` FROM `users` AS `user` WHERE `user`.`id` = '1f053c2f-d012-48b2-8cab-c490d20166f2';
Executing (e26094e5-439a-4bc5-a8c8-34ad20a42647): INSERT INTO `users` (`id`) VALUES ('1f053c2f-d012-48b2-8cab-c490d20166f2');
Executing (e26094e5-439a-4bc5-a8c8-34ad20a42647): COMMIT;
```

**Comment by guseinovmg** [comment]
I am using postgres and get same error
Unhandled rejection TypeError: val.replace is not a function
    at Object.SqlString.escape (/home/hacker/adnet/node_modules/sequelize/lib/sql-string.js:61:15)
    at Object.QueryGenerator.escape (/home/hacker/adnet/node_modules/sequelize/lib/dialects/abstract/query-generator.js:977:22)
    at Object.<anonymous> (/home/hacker/adnet/node_modules/sequelize/lib/dialects/abstract/query-generator.js:356:23)
    at Array.map (native)
    at Object.<anonymous> (/home/hacker/adnet/node_modules/sequelize/lib/dialects/abstract/query-generator.js:352:23)
    at Array.forEach (native)
    at Object.QueryGenerator.bulkInsertQuery (/home/hacker/adnet/node_modules/sequelize/lib/dialects/abstract/query-generator.js:350:21)
    at QueryInterface.bulkInsert (/home/hacker/adnet/node_modules/sequelize/lib/query-interface.js:568:33)
    at /home/hacker/adnet/node_modules/sequelize/lib/model.js:2227:34
    at tryCatcher (/home/hacker/adnet/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/hacker/adnet/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/home/hacker/adnet/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/home/hacker/adnet/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/home/hacker/adnet/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (/home/hacker/adnet/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/hacker/adnet/node_modules/bluebird/js/release/async.js:148:10)
