### ISSUE TITLE
Error with named scope

### ISSUE THREAD

**Issue by akaNightmare** [sequelize/sequelize#6032]
Hi, my route(controller)
```js
return this.model.scope([
             'withCategories', 'withPricingPlans', 'withAssets',
            {method: ['withApps', qparams.user]}
        ]).findAndCountAll(params);
```
my product scopes
```js
scopes: {
            active: {where: {is_active: true}},
            /**
             * @param {String|null=} username
             * @returns {{include: *[]}}
             */
            withApps: function (username) {
                const appRelation = {association: product.associations.applications};

                if (username !== undefined && username !== null) {
                    appRelation.where = {username: username};
                    appRelation.required = false;
                }

                return {include: [appRelation]};
            },
            withAssets: () => {
                return {
                    include: [{association: product.associations.assets}]
                };
            },
            withPricingPlans: () => {
                return {
                    include: [{association: product.associations.pricingPlans}]
                };
            },
            withCategories: () => {
                return {
                    include: [{association: product.associations.categories}]
                };
            }
        },
```
Class methods
```js
classMethods: {
            associate: models => {
                product.belongsTo(models.User, {foreignKey: 'id', as: 'user'});
                product.hasMany(models.ProductAssets, {foreignKey: 'product_id', as: 'assets'});

                product.hasMany(models.Application, {foreignKey: 'product_id', as: 'applications'});

                product.hasMany(models.PricingPlan, {foreignKey: 'product_id', as: 'pricingPlans'});
                product.belongsToMany(models.Category, {
                    through: models.ProductCategory,
                    foreignKey: 'product_id',
                    as: 'categories'
                });
            }
        },
```

## Error
```
Cannot read property 'name' of undefined\n at matchesModelAndAlias (/codebase/backend/node_modules/sequelize/lib/model.js:2710:79)\n at Array.some (native)\n at /codebase/backend/node_modules/sequelize/lib/model.js:2709:48\n at Array.forEach (native)\n at Model.$injectScope (/codebase/backend/node_modules/sequelize/lib/model.js:2708:29)\n at Model.aggregate (/codebase/backend/node_modules/sequelize/lib/model.js:1563:8)\n at .<anonymous> (/codebase/backend/node_modules/sequelize/lib/model.js:1645:17)\n at bound (domain.js:280:14)\n

## version of seuqelize - 3.20.0

**Comment by akaNightmare** [comment]
@janmeier all works when I remove
```
{method: ['withApps', qparams.user]}

**Comment by janmeier** [comment]
Try checking if `associations.applications` is defined

**Comment by akaNightmare** [comment]
@janmeier defined, when I include relation via `findAndCountAll({include: [...]})` - everything is ok.

**Comment by janmeier** [comment]
Please provide an [SSCCE](HTTP://SSCCE.ORG/) then
