### ISSUE TITLE
Error: ER_UNKNOWN_TIME_ZONE: Unknown or incorrect time zone

### ISSUE THREAD

**Issue by jontelm** [sequelize/sequelize#6120]
Error: ER_UNKNOWN_TIME_ZONE: Unknown or incorrect time zone: 'Europe/Stockholm'

This error is hard to get.

I was able to add a console.log here https://github.com/sequelize/sequelize/blob/master/lib/dialects/mysql/connection-manager.js#L111 and then I got it.

Should not this error got pushed out somewhere?

The problem is that my database not have the timezone table, but it took some time to get that.

Version: 3.23.3

**Comment by janmeier** [comment]
Hmm, is the code `PROTOCOL_CONNECTION_LOST`? We should probably add a throw there

**Comment by jontelm** [comment]
{ Error: ER_UNKNOWN_TIME_ZONE: Unknown or incorrect time zone: 'Europe/Stockholm'
    at Query.Sequence._packetToError (/home/ubuntu/x_node/node_modules/mysql/lib/protocol/sequences/Sequence.js:51:14)
    at Query.ErrorPacket (/home/ubuntu/x_node/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
    at Protocol._parsePacket (/home/ubuntu/x_node/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/home/ubuntu/x_node/node_modules/mysql/lib/protocol/Parser.js:74:12)
    at Protocol.write (/home/ubuntu/x_node/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/ubuntu/x_node/node_modules/mysql/lib/Connection.js:109:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)
    --------------------
    at Protocol._enqueue (/home/ubuntu/x_node/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Connection.query (/home/ubuntu/x_node/node_modules/mysql/lib/Connection.js:214:25)
    at /home/ubuntu/x_node/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:123:16
    at PassThroughHandlerContext.finallyHandler (/home/ubuntu/x_node/node_modules/bluebird/js/release/finally.js:56:23)
    at bound (domain.js:280:14)
    at PassThroughHandlerContext.runBound (domain.js:293:12)
    at PassThroughHandlerContext.tryCatcher (/home/ubuntu/x_node/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/x_node/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/home/ubuntu/x_node/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/home/ubuntu/x_node/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/home/ubuntu/x_node/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (/home/ubuntu/x_node/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/ubuntu/x_node/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/ubuntu/x_node/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
  code: 'ER_UNKNOWN_TIME_ZONE',
  errno: 1298,
  sqlState: 'HY000',
  index: 0 }

**Comment by janmeier** [comment]
Alright, should be pretty easy to identify with an else that rethrows the error
