### ISSUE TITLE
TypeError: _.trimLeft is not a function

### ISSUE THREAD

**Issue by ihorfito** [sequelize/sequelize#6125]
When I try to run migrations I've got an error.

> ./node_modules/sequelize-cli/bin/sequelize db:migrate --env=development

```
[4mSequelize [Node: 4.3.0, CLI: 1.9.2, ORM: 3.21.0, mysql: ^2.9.0][24m

/var/app/current/node_modules/sequelize-cli/lib/helpers/migration-helper.js:20
    return _.trimLeft(_.kebabCase('create-' + args.name), '-');
             ^

TypeError: _.trimLeft is not a function
    at Object.module.exports.generateMigrationName (/var/app/current/node_modules/sequelize-cli/lib/helpers/migration-helper.js:20:14)
    at /var/app/current/node_modules/sequelize-cli/lib/tasks/model.js:19:29
    at Object.<anonymous> (/var/app/current/node_modules/sequelize-cli/lib/tasks/model.js:64:9)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /var/app/current/node_modules/sequelize-cli/lib/gulpfile.js:19:12
    at Array.map (native)
    at Object.<anonymous> (/var/app/current/node_modules/sequelize-cli/lib/gulpfile.js:18:4)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Liftoff.handleArguments (/var/app/current/node_modules/sequelize-cli/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/var/app/current/node_modules/sequelize-cli/node_modules/gulp/node_modules/liftoff/index.js:193:16)
    at module.exports (/var/app/current/node_modules/sequelize-cli/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/var/app/current/node_modules/sequelize-cli/node_modules/gulp/node_modules/liftoff/index.js:185:9)
    at /var/app/current/node_modules/sequelize-cli/node_modules/gulp/node_modules/liftoff/index.js:159:9
    at /var/app/current/node_modules/sequelize-cli/node_modules/gulp/node_modules/v8flags/index.js:108:14
    at /var/app/current/node_modules/sequelize-cli/node_modules/gulp/node_modules/v8flags/index.js:36:12
    at /var/app/current/node_modules/sequelize-cli/node_modules/gulp/node_modules/v8flags/index.js:47:7
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)

npm ERR! Linux 4.4.5-15.26.amzn1.x86_64
npm ERR! argv "/opt/elasticbeanstalk/node-install/node-v4.3.0-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v4.3.0-linux-x64/bin/npm" "run" "migrate"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.12
```

**Comment by sushantdhiman** [comment]
From lodash change log

> 
Renamed _.trimLeft & _.trimRight to _.trimStart & _.trimEnd

**Comment by sushantdhiman** [comment]
@ihorfito Please reopen this issue at https://github.com/sequelize/cli because these changes belongs to cli project.
