### ISSUE TITLE
TypeError: Cannot read property 'getTableName' of undefined

### ISSUE THREAD

**Issue by KieronWiltshire** [sequelize/sequelize#6127]
## What you are doing?
I'm attempting to create an association via an api interface that I have created.

## What do you expect to happen?
It should've just found the user and continued on, but it seems the include is causing an issue, however just calling the "find" method from other tests appears to work just fine, so I'm not really sure what is going on.

## What is actually happening?
I'm getting a Sequelize error that looks like to be failing when the table name is retrieved from the included models.

```
  sentinel:api:user TypeError: Cannot read property 'getTableName' of undefined
    at validateIncludedElement (C:\Users\Kieron\Dracade\web\sentinel\node_modules\sequelize\lib\model.js:505:27)
    at C:\Users\Kieron\Dracade\web\sentinel\node_modules\sequelize\lib\model.js:432:29
    at Array.map (native)
    at validateIncludedElements (C:\Users\Kieron\Dracade\web\sentinel\node_modules\sequelize\lib\model.js:428:37)
    at null.<anonymous> (C:\Users\Kieron\Dracade\web\sentinel\node_modules\sequelize\lib\model.js:1364:32)
    at tryCatcher (C:\Users\Kieron\Dracade\web\sentinel\node_modules\sequelize\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Kieron\Dracade\web\sentinel\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:502:31)
    at Promise._settlePromise (C:\Users\Kieron\Dracade\web\sentinel\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:559:18)
    at Promise._settlePromise0 (C:\Users\Kieron\Dracade\web\sentinel\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:604:10)
    at Promise._settlePromises (C:\Users\Kieron\Dracade\web\sentinel\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:683:18)
    at Async._drainQueue (C:\Users\Kieron\Dracade\web\sentinel\node_modules\sequelize\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (C:\Users\Kieron\Dracade\web\sentinel\node_modules\sequelize\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Kieron\Dracade\web\sentinel\node_modules\sequelize\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17) +86ms
```

The error originates from this [test](https://github.com/KieronWiltshire/sentinel/blob/master/test/sentinel.test.js#L163), however it's actually thrown [here](https://github.com/KieronWiltshire/sentinel/blob/master/api/user.js#L56) from [here](https://github.com/KieronWiltshire/sentinel/blob/master/api/user.js#L107).

__Dialect:__ mysql
__Database version:__ 10.1.8-MariaDB
__Sequelize version:__ 3.23.3

**Comment by janmeier** [comment]
Most likely the model you are trying to include is undefined. Please add some code that reproduces the issue

**Comment by KieronWiltshire** [comment]
@janmeier I doubt it, I added `console.log(options.include.AuthorizationPolicy.getTableName());` [here](https://github.com/KieronWiltshire/sentinel/blob/master/api/user.js#L55) and it showed the table name as expected, however the query still failed to getTableName.

It's either an issue with Sequelize or it has something to do with the way my application is currently loading models.

**Comment by KieronWiltshire** [comment]
Okay, so after a little debugging of my own, I think it has something to do with the way my associations are setup, but I'm not 100% sure.

So what I did was add this line `include = include[Object.keys(include)[0]];` [here](https://github.com/sequelize/sequelize/blob/master/lib/model.js#L191), and it then gave me this error:

```
  sentinel:api:user Error: authorization_user_policies is not associated to AuthorizationPolicy!
    at validateIncludedElement (C:\Users\Kieron\Dracade\web\sentinel\node_modules\sequelize\lib\model.js:552:11)
    at C:\Users\Kieron\Dracade\web\sentinel\node_modules\sequelize\lib\model.js:434:29
    at Array.map (native)
    at validateIncludedElements (C:\Users\Kieron\Dracade\web\sentinel\node_modules\sequelize\lib\model.js:430:37)
    at validateIncludedElement (C:\Users\Kieron\Dracade\web\sentinel\node_modules\sequelize\lib\model.js:627:30)
    at C:\Users\Kieron\Dracade\web\sentinel\node_modules\sequelize\lib\model.js:434:29
    at Array.map (native)
    at validateIncludedElements (C:\Users\Kieron\Dracade\web\sentinel\node_modules\sequelize\lib\model.js:430:37)
    at null.<anonymous> (C:\Users\Kieron\Dracade\web\sentinel\node_modules\sequelize\lib\model.js:1366:32)
    at tryCatcher (C:\Users\Kieron\Dracade\web\sentinel\node_modules\sequelize\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Kieron\Dracade\web\sentinel\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:504:31)
    at Promise._settlePromise (C:\Users\Kieron\Dracade\web\sentinel\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:561:18)
    at Promise._settlePromise0 (C:\Users\Kieron\Dracade\web\sentinel\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise._settlePromises (C:\Users\Kieron\Dracade\web\sentinel\node_modules\sequelize\node_modules\bluebird\js\release\promise.js:685:18)
    at Async._drainQueue (C:\Users\Kieron\Dracade\web\sentinel\node_modules\sequelize\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (C:\Users\Kieron\Dracade\web\sentinel\node_modules\sequelize\node_modules\bluebird\js\release\async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Kieron\Dracade\web\sentinel\node_modules\sequelize\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17) +96ms
```

**Comment by KieronWiltshire** [comment]
Okay, after some more debugging, it seems that the association for the `authorization_user_policy` table is `AuthorizationPolicies` and not `AuthorizationPolicy`.

**Comment by KieronWiltshire** [comment]
## Solved
The issue was that I was passing 'include' through as an object and not an array.

**Comment by justechn** [comment]
I just ran into this myself. This could really use a better error message, the one provided makes no sense.

**Comment by janmeier** [comment]
@justechn I understand your sentiment, but having to monkeypatch type checking of all arguments ( and their arbitrarily nested children) is not feasible in my mind

**Comment by trevorh2007** [comment]
To add on to this I ran into this similar situation. Same error, same console logging results. My issue was ```      include: [{
        model: Scholarship,
        as: 'scholarships',
        required: false,
        through: {
          attributes: []
        }
      }]``` that there was no join table that 'through' could use, so just getting rid of 'through' like this: ```      include: [{
        model: Scholarship,
        as: 'scholarships',
        required: false
      }]``` Solved my issue

**Comment by heisian** [comment]
Howcome there is no visibility into what Sequelize is actually trying to call here?
Why doesn't it say something like `call to <Model>.getTableName() failed`?

**Comment by calintamas** [comment]
In the `associate` function, make sure to add the through model using a simple string and **not the model object**. That was the issue in my case.

```javascript
User.belongsToMany(models.project, { through: 'user_project', foreignKey: 'user_id' });
```

**Comment by camilodelvasto** [comment]
I was getting the error with this line:
```javascript
include: [{ all: true}]
```
When I set it to `false`, the error went away. Is that error expected or is it something in my setup? Also, I couldn't find it documented... just leaving it here in case it helps someone, but it seems the error message is indeed misleading.

**Comment by mahsan3** [comment]
Had the same error message, but it turns out it was because the model I was trying to include had multiple associations to the model I was searching on. Adding an alias to the associations fixed the issue.

**Comment by davicente** [comment]
> To add on to this I ran into this similar situation. Same error, same console logging results. My issue was
> 
> ```
> include: [{
>     model: Scholarship,
>     as: 'scholarships',
>     required: false,
>     through: {
>         attributes: []
>     }
> }]
> ```
> 
> that there was no join table that 'through' could use, so just getting rid of 'through' like this:
> 
> ```
> include: [{
>     model: Scholarship,
>     as: 'scholarships',
>     required: false
> }]
> ```
> 
> Solved my issue

You made my day man, thanks a lot. This solved my issue ;)

**Comment by michcio1234** [comment]
I just ran into it because I misspelled `association`.
This error message really could be a bit more useful. ;/

**Comment by LWanjiru** [comment]
Hope this helps. I was stuck too long trying to figure it out after I got major bugs on a project. Here's the link to how I solved it ==> https://github.com/sequelize/sequelize/issues/11285#issuecomment-1729660886
