### ISSUE TITLE
Issue with targetKey on belongsTo relationship

### ISSUE THREAD

**Issue by spawnius** [sequelize/sequelize#6210]
I am trying to set up a belongs-to relationship in SailsJS using Sequelize and the [sails-hook-sequelize-blueprints](sails-hook-sequelize-blueprints), but I get an error when I try to start the app.
The error comes from the belongs-to definition of Sequelize library, so I am guessing the issue is coming from there. Anyone else facing the same problem?

I am defining the relationship as follows:
```js
Event.belongsTo(Venue, {
  onDelete: 'cascade',
  as: 'venue',
  foreignKey: {
      name: 'vid',
      as: 'venue',
      allowNull: false
  },
  targetKey: 'pid'
});
```

The error I am getting is:
```
error: A hook (`sequelize`) failed to load!
error: TypeError: Cannot read property 'field' of undefined
    at new BelongsTo (C:\dev\kartweel\api_sails\node_modules\sails-hook-sequelize\node_modules\sequelize\lib\associations\belongs-to.js:64:66)
    at null.belongsTo (C:\dev\kartweel\api_sails\node_modules\sails-hook-sequelize\node_modules\sequelize\lib\associations\mixin.js:106:23)
    at Object.module.exports.associations (C:\dev\kartweel\api_sails\api\models\Event.js:41:15)
    at Hook.setAssociation (C:\dev\kartweel\api_sails\node_modules\sails-hook-sequelize\index.js:72:20)
    at Hook.wrapper [as setAssociation] (C:\dev\kartweel\api_sails\node_modules\sails\node_modules\lodash\index.js:3095:19)
    at C:\dev\kartweel\api_sails\node_modules\sails-hook-sequelize\index.js:41:16
    at C:\dev\kartweel\api_sails\node_modules\sails\lib\hooks\moduleloader\index.js:359:18
    at C:\dev\kartweel\api_sails\node_modules\sails\lib\hooks\moduleloader\index.js:612:14
    at buildDictionary (C:\dev\kartweel\api_sails\node_modules\sails\node_modules\sails-build-dictionary\index.js:134:9)
    at Function.module.exports.optional (C:\dev\kartweel\api_sails\node_modules\sails\node_modules\sails-build-dictionary\index.js:160:9)
    at C:\dev\kartweel\api_sails\node_modules\sails\lib\hooks\moduleloader\index.js:352:25
    at buildDictionary (C:\dev\kartweel\api_sails\node_modules\sails\node_modules\sails-build-dictionary\index.js:134:9)
    at Function.module.exports.optional (C:\dev\kartweel\api_sails\node_modules\sails\node_modules\sails-build-dictionary\index.js:160:9)
    at Hook.loadModels (C:\dev\kartweel\api_sails\node_modules\sails\lib\hooks\moduleloader\index.js:344:23)
    at Hook.wrapper [as loadModels] (C:\dev\kartweel\api_sails\node_modules\sails\node_modules\lodash\index.js:3095:19)
    at Hook.initialize (C:\dev\kartweel\api_sails\node_modules\sails-hook-sequelize\index.js:26:28)
    at Hook.wrapper [as initialize] (C:\dev\kartweel\api_sails\node_modules\sails\node_modules\lodash\index.js:3095:19)
    at C:\dev\kartweel\api_sails\node_modules\sails\lib\hooks\index.js:74:16
    at C:\dev\kartweel\api_sails\node_modules\sails\node_modules\async\lib\async.js:52:16
    at C:\dev\kartweel\api_sails\node_modules\sails\node_modules\async\lib\async.js:548:17
    at C:\dev\kartweel\api_sails\node_modules\sails\node_modules\async\lib\async.js:542:17
    at _arrayEach (C:\dev\kartweel\api_sails\node_modules\sails\node_modules\async\lib\async.js:85:13) [TypeError: Cannot read property 'field' of undefined]
```
__Dialect:__ mysql
__Database version__: 5.7
__Sequelize version:__: 3.23.4

**Comment by janmeier** [comment]
You are missing the `pid` column on  `Venue`

**Comment by spawnius** [comment]
If I add the pid column then I get a SequelizeDatabaseError (tried it before):
```
Unhandled rejection SequelizeDatabaseError: ER_CANNOT_ADD_FOREIGN: Cannot add foreign key constraint
    at Query.formatError (C:\dev\kartweel\api_sails\node_modules\sails-hook-sequelize\node_modules\sequelize\lib\dialects\mysql\query.js:175:14)
    at Query._callback (C:\dev\kartweel\api_sails\node_modules\sails-hook-sequelize\node_modules\sequelize\lib\dialects\mysql\query.js:49:21)
    at Query.Sequence.end (C:\dev\kartweel\api_sails\node_modules\mysql\lib\protocol\sequences\Sequence.js:85:24)
    at Query.ErrorPacket (C:\dev\kartweel\api_sails\node_modules\mysql\lib\protocol\sequences\Query.js:94:8)
    at Protocol._parsePacket (C:\dev\kartweel\api_sails\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (C:\dev\kartweel\api_sails\node_modules\mysql\lib\protocol\Parser.js:74:12)
    at Protocol.write (C:\dev\kartweel\api_sails\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (C:\dev\kartweel\api_sails\node_modules\mysql\lib\Connection.js:109:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:531:20)
    at TCP.onread (C:\dev\kartweel\api_sails\node_modules\sails-hook-sequelize\node_modules\continuation-local-storage\node_modules\async-listener\glue.js:188:31)
From previous event:
    at Query.run (C:\dev\kartweel\api_sails\node_modules\sails-hook-sequelize\node_modules\sequelize\lib\dialects\mysql\query.js:39:17)
    at C:\dev\kartweel\api_sails\node_modules\sails-hook-sequelize\node_modules\sequelize\lib\sequelize.js:843:20
    at C:\dev\kartweel\api_sails\node_modules\sails-hook-sequelize\node_modules\sequelize\node_modules\retry-as-promised\index.js:38:21
From previous event:
    at retryAsPromised (C:\dev\kartweel\api_sails\node_modules\sails-hook-sequelize\node_modules\sequelize\node_modules\retry-as-promised\index.js:27:10)
    at C:\dev\kartweel\api_sails\node_modules\sails-hook-sequelize\node_modules\sequelize\lib\sequelize.js:842:12
From previous event:
    at Promise.then (C:\dev\kartweel\api_sails\node_modules\sails-hook-sequelize\node_modules\sequelize\lib\promise.js:21:17)
    at Model.sync (C:\dev\kartweel\api_sails\node_modules\sails-hook-sequelize\node_modules\sequelize\lib\model.js:985:6)
    at C:\dev\kartweel\api_sails\node_modules\sails-hook-sequelize\node_modules\sequelize\lib\sequelize.js:1008:20
From previous event:
    at Function.each (C:\dev\kartweel\api_sails\node_modules\sails-hook-sequelize\node_modules\sequelize\lib\promise.js:21:17)
    at C:\dev\kartweel\api_sails\node_modules\sails-hook-sequelize\node_modules\sequelize\lib\sequelize.js:1007:20
    at C:\dev\kartweel\api_sails\node_modules\sails-hook-sequelize\node_modules\continuation-local-storage\context.js:76:17
From previous event:
    at Promise.then (C:\dev\kartweel\api_sails\node_modules\sails-hook-sequelize\node_modules\sequelize\lib\promise.js:21:17)
    at Sequelize.sync (C:\dev\kartweel\api_sails\node_modules\sails-hook-sequelize\node_modules\sequelize\lib\sequelize.js:994:6)
    at C:\dev\kartweel\api_sails\node_modules\sails-hook-sequelize\index.js:49:21
    at C:\dev\kartweel\api_sails\node_modules\sails\lib\hooks\moduleloader\index.js:359:18
    at C:\dev\kartweel\api_sails\node_modules\sails\lib\hooks\moduleloader\index.js:612:14
    at buildDictionary (C:\dev\kartweel\api_sails\node_modules\sails\node_modules\sails-build-dictionary\index.js:134:9)
    at Function.module.exports.optional (C:\dev\kartweel\api_sails\node_modules\sails\node_modules\sails-build-dictionary\index.js:160:9)
    at C:\dev\kartweel\api_sails\node_modules\sails\lib\hooks\moduleloader\index.js:352:25
    at buildDictionary (C:\dev\kartweel\api_sails\node_modules\sails\node_modules\sails-build-dictionary\index.js:134:9)
    at Function.module.exports.optional (C:\dev\kartweel\api_sails\node_modules\sails\node_modules\sails-build-dictionary\index.js:160:9)
    at Hook.loadModels (C:\dev\kartweel\api_sails\node_modules\sails\lib\hooks\moduleloader\index.js:344:23)
    at Hook.wrapper [as loadModels] (C:\dev\kartweel\api_sails\node_modules\sails\node_modules\lodash\index.js:3095:19)
    at Hook.initialize (C:\dev\kartweel\api_sails\node_modules\sails-hook-sequelize\index.js:26:28)
    at Hook.wrapper [as initialize] (C:\dev\kartweel\api_sails\node_modules\sails\node_modules\lodash\index.js:3095:19)
    at C:\dev\kartweel\api_sails\node_modules\sails\lib\hooks\index.js:74:16
    at C:\dev\kartweel\api_sails\node_modules\sails\node_modules\async\lib\async.js:52:16
    at C:\dev\kartweel\api_sails\node_modules\sails\node_modules\async\lib\async.js:548:17
    at C:\dev\kartweel\api_sails\node_modules\sails\node_modules\async\lib\async.js:542:17
    at _arrayEach (C:\dev\kartweel\api_sails\node_modules\sails\node_modules\async\lib\async.js:85:13)
    at Immediate.taskComplete (C:\dev\kartweel\api_sails\node_modules\sails\node_modules\async\lib\async.js:541:13)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by janmeier** [comment]
Whats the type of pid - maybe mysql doesnt support foreign key on that type of column, or maybe it isn't unique? 

Please provide a [SSCCE](HTTP://SSCCE.ORG/), or at least show the SQL output

**Comment by spawnius** [comment]
Setting the pid column to unique fixed the issue. I should have paid more attentionto the docs

Here is a simplified gist that shows what it did in case someone else faces this issue:
https://gist.github.com/spawnius/3c8fe8a9b7c161bd8ba29a7d91aa2227

Thank you very much for the support!
