### ISSUE TITLE
Can't include model with where if I find zero results.

### ISSUE THREAD

**Issue by kristoffernolgren** [sequelize/sequelize#6244]
I'm trying to do this query:

```
User.findOrCreate(
	{
		where: {fbid: fbid},
		defaults: {
			guid: chance.guid()
		},
		include: [
			{
				model: sequelize.models.hail,
				where: { driverId: 25}
			}
		]

	})
```

if the where: { driverId: 25} is added and no results are returned, I get this error:

```
Unhandled rejection SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/Users/kristoffer/web/fitch/node_modules/sequelize/lib/dialects/sqlite/query.js:337:14)
    at Statement.afterExecute (/Users/kristoffer/web/fitch/node_modules/sequelize/lib/dialects/sqlite/query.js:112:29)
    at Statement.replacement (/Users/kristoffer/web/fitch/node_modules/sqlite3/lib/trace.js:20:31)
```

It seems to be caused specifically if where is included, because if it's not, I don't get an error, even if the hail table doesn't have any records.

If I set driverId to something that is matched in the database, it doesn't throw an error either.

**Comment by janmeier** [comment]
Please provide a [SSCCE](HTTP://SSCCE.ORG/) so we can actually replicate your issue
