### ISSUE TITLE
Warning: a promise was created in a handler but was not returned from it

### ISSUE THREAD

**Issue by danielsalles** [sequelize/sequelize#6248]
It is returning this warning:
Warning: a promise was created in a handler but was not returned from it
    at Model.findAll (/home/daniel/Documentos/blogdanieldev/we-project-blog-blog-daniel-dev/node_modules/we-core/node_modules/sequelize/lib/model.js:1347:18)
    at PluginManager.loadPluginsSettingsFromDB (/home/daniel/Documentos/blogdanieldev/we-project-blog-blog-daniel-dev/node_modules/we-core/lib/PluginManager/index.js:258:23)
    at /home/daniel/Documentos/blogdanieldev/we-project-blog-blog-daniel-dev/node_modules/we-core/lib/bootstrapFunctions.js:24:24
    at /home/daniel/Documentos/blogdanieldev/we-project-blog-blog-daniel-dev/node_modules/we-core/lib/Database/index.js:243:5
    at processImmediate [as _immediateCallback] (timers.js:384:17)
From previous event:
    at Promise.then (/home/daniel/Documentos/blogdanieldev/we-project-blog-blog-daniel-dev/node_modules/we-core/node_modules/sequelize/lib/promise.js:21:17)
    at Database.loadCoreModels (/home/daniel/Documentos/blogdanieldev/we-project-blog-blog-daniel-dev/node_modules/we-core/lib/Database/index.js:242:27)
    at Array.loadCoreFeatures (/home/daniel/Documentos/blogdanieldev/we-project-blog-blog-daniel-dev/node_modules/we-core/lib/bootstrapFunctions.js:21:11)
    at runHookFunctions (/home/daniel/Documentos/blogdanieldev/we-project-blog-blog-daniel-dev/node_modules/simple-hooks-callback/lib/index.js:59:15)
    at HooksPrototype.weTriggerEvent (/home/daniel/Documentos/blogdanieldev/we-project-blog-blog-daniel-dev/node_modules/simple-hooks-callback/lib/index.js:52:3)
    at We.bootstrap (/home/daniel/Documentos/blogdanieldev/we-project-blog-blog-daniel-dev/node_modules/we-core/lib/index.js:230:12)
    at We.go (/home/daniel/Documentos/blogdanieldev/we-project-blog-blog-daniel-dev/node_modules/we-core/lib/index.js:394:8)
    at Object.<anonymous> (/home/daniel/Documentos/blogdanieldev/we-project-blog-blog-daniel-dev/app.js:8:4)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Command.run (/home/daniel/.nvm/v5.2.0/lib/node_modules/we/lib/commands/run.js:26:7)
    at Command.listener (/home/daniel/.nvm/v5.2.0/lib/node_modules/we/node_modules/commander/index.js:287:8)
    at emitTwo (events.js:88:13)
    at Command.emit (events.js:173:7)
    at Command.parseArgs (/home/daniel/.nvm/v5.2.0/lib/node_modules/we/node_modules/commander/index.js:541:12)

According to what I researched the bluebird, it solves:
https://github.com/petkaantonov/bluebird/blob/master/docs/docs/warning-explanations.md#warning-a-promise-was-created-in-a-handler-but-was-not-returned-from-it

I think the warning is at the core sequelizejs.
__Dialect:__ postgres
__Database version:__ 9.3
__Sequelize version:__ 3.23.3 or 4.0.0

**Comment by mickhansen** [comment]
Most likely your own code is the culprit.
Otherwise you'll need to show a SSCCE showing how Sequelize is the trigger.

**Comment by tony-gutierrez** [comment]
There are a lot of these as soon as you start using association methods. I have spent a lot of time on them and believe most to be internal to sequelize.
