### ISSUE TITLE
Emoji insert exception

### ISSUE THREAD

**Issue by huzhenjie** [sequelize/sequelize#6258]
My code is 

```
var sql = "INSERT IGNORE INTO cs SET " +
            "cs_title=?," +
            ...
        conn.query(sql, {
            replacements: [course.name, ...],
            type: sequelize.QueryTypes.INSERT
        }).then(function (courseId) {
...
```

when insert 我的心😘😉😘'

case this exception

```
UPDATE cs SET cs_title='我的心😘😉😘',....
```

```
Unhandled rejection SequelizeDatabaseError: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF0\x9F\x98\x98\xF0\x9F...' for column 'cs_title' at row 1
    at Query.formatError (/home/Tinstone-Course-Server/node_modules/sequelize/lib/dialects/mysql/query.js:175:14)
    at Query._callback (/home/Tinstone-Course-Server/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
    at Query.Sequence.end (/home/Tinstone-Course-Server/node_modules/mysql/lib/protocol/sequences/Sequence.js:85:24)
    at Query.ErrorPacket (/home/Tinstone-Course-Server/node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
    at Protocol._parsePacket (/home/Tinstone-Course-Server/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/home/Tinstone-Course-Server/node_modules/mysql/lib/protocol/Parser.js:74:12)
    at Protocol.write (/home/Tinstone-Course-Server/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/Tinstone-Course-Server/node_modules/mysql/lib/Connection.js:109:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)
```

**Comment by sushantdhiman** [comment]
You will need to set `CHARACTER SET` to `utf8mb4`, [Model.options.charset ](http://docs.sequelizejs.com/en/latest/api/sequelize/?highlight=charset)

**Comment by dongtong** [comment]
Hi @sushantdhiman 

I have set charset as utf8mb4, but still reports:

`Unhandled rejection SequelizeDatabaseError: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value`

```
'use strict';
module.exports = function(sequelize, DataTypes) {
  var Website = sequelize.define('Website', {
    name: DataTypes.STRING,
    url: DataTypes.STRING,
    cron_interval: DataTypes.STRING,
    status: DataTypes.STRING
  }, {
    underscored: true,
    tableName: 'websites',
    charset: 'utf8mb4',
    classMethods: {
      associate: function(models) {
        // associations can be defined here
        Website.hasMany(models.PagePerf)
      }
    }
  });
  return Website;
};
```

**Comment by sushantdhiman** [comment]
Hi @dongtong , Did you created the table first then set the it to `utf8mb4` ? Please re-create the table with charset `utf8mb4` and see if you can insert strings properly after that.

**Comment by huzhenjie** [comment]
Hi @dongtong , Can you show your statement？

```
show create table your_table;
```

**Comment by DzmitryU** [comment]
Hi @sunshinewyin 
I have the same problem with Emoji. All requests from WorkBench are done successfully, but there are still problems with utf8mb4 in sequelize. Is it possible not to recreate table? It's full of data that I don't want to lose.
P.S. I've configured charset for whole schema (not only single model):
```
host: dbConfig.host,
            port: dbConfig.port,
            dialect: dbConfig.protocol,
            define: {
                charset: 'utf8mb4',
                freezeTableName: true,
                underscored: true,
                underscoredAll: true,
                timestamps: false
            }
```

**Comment by npke** [comment]
Hi @DzmitryU DZ
This configuration works for me [config database charset](https://github.com/sequelize/sequelize/issues/1220) You should give it a try.
