### ISSUE TITLE
Promise was created in a handler but was not returned from it

### ISSUE THREAD

**Issue by l0oky** [sequelize/sequelize#6339]
Hi, executing a simple query `select now()` for postgres is throwing this error for some reason.

```bash
Executing (default): SELECT NOW()
Warning: a promise was created in a handler but was not returned from it
    at ConnectionManager.getConnection (/home/myproject/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:223:23)
    at Sequelize.query (/home/myproject/node_modules/sequelize/lib/sequelize.js:838:83)
    at checkMetaOldSchema (/home/myproject/node_modules/ah-sequelize-plugin/initializers/sequelize.js:139:34)
    at Object.api.sequelize.autoMigrate (/home/myproject/node_modules/ah-sequelize-plugin/initializers/sequelize.js:91:11)
    at /home/myproject/node_modules/ah-sequelize-plugin/initializers/sequelize.js:130:21
    at null.<anonymous> (/home/myproject/node_modules/ah-sequelize-plugin/initializers/sequelize.js:112:11)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Promise.then (/home/myproject/node_modules/sequelize/lib/promise.js:21:17)
    at Object.api.sequelize.test (/home/myproject/node_modules/ah-sequelize-plugin/initializers/sequelize.js:111:46)
    at Object.api.sequelize.connect (/home/myproject/node_modules/ah-sequelize-plugin/initializers/sequelize.js:75:23)
    at Object.module.exports.start (/home/myproject/node_modules/ah-sequelize-plugin/initializers/sequelize.js:125:19)
    at startFunction (/home/myproject/node_modules/actionhero/actionhero.js:157:44)
    at /home/myproject/node_modules/async/dist/async.js:3671:13
    at replenish (/home/myproject/node_modules/async/dist/async.js:884:21)
    at iterateeCallback (/home/myproject/node_modules/async/dist/async.js:869:21)
    at /home/myproject/node_modules/async/dist/async.js:847:20
    at /home/myproject/node_modules/async/dist/async.js:3676:17
    at /home/myproject/node_modules/async/dist/async.js:339:31
    at /home/myproject/node_modules/actionhero/actionhero.js:159:15
    at Object.module.exports.start (/home/myproject/node_modules/actionhero/initializers/redis.js:171:5)
    at startFunction (/home/myproject/node_modules/actionhero/actionhero.js:157:44)
    at /home/myproject/node_modules/async/dist/async.js:3671:13
    at replenish (/home/myproject/node_modules/async/dist/async.js:884:21)
    at iterateeCallback (/home/myproject/node_modules/async/dist/async.js:869:21)
    at /home/myproject/node_modules/async/dist/async.js:847:20
    at /home/myproject/node_modules/async/dist/async.js:3676:17

Executing (default): SELECT * FROM "SequelizeMeta"
Executing (default): CREATE TABLE IF NOT EXISTS "SequelizeMeta" ("name" VARCHAR(255) NOT NULL UNIQUE , UNIQUE ("name"), PRIMARY KEY ("name"));
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'SequelizeMeta' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
Executing (default): SELECT "name" FROM "SequelizeMeta" AS "SequelizeMeta" ORDER BY "SequelizeMeta"."name" ASC;
```

My configuration file I am using looks like this:

```javascript
exports.default = {
  sequelize: function(api) {
    return {
      autoMigrate: true,
      loadFixtures: false,
      database: "prati_dev",
      dialect: "postgres",
      port: 5432,
      host: "127.0.0.1",
      username: "postgres",
      password: "master"
    };
  }
};
/*
exports.test = {
  sequelize: function(api) {
    return {
      autoMigrate: true,
      loadFixtures: false,
      database: "prati_test",
      dialect: "postgres",
      port: 5432,
      host: "127.0.0.1",
      username: "postgres",
      password: "master"
    };
  }
};
*/

exports.development = exports.default.sequelize();
```

I can't query anything via sequelize now. What could this error mean?

I noticed that it loads `connection-manager.js` from `dialects/abstract` instead of `dialects/postgres`, does that provide a clue to this issue?

**Comment by sushantdhiman** [comment]
It looks more like `ah-sequelize-plugin`'s fault than `sequelize`. Can you reproduce this issue without using any plugin, with just `sequelize`

**Comment by mickhansen** [comment]
Almost always userland error these days, the stack doesn't necessarily tell you where the issue started.
If you can find a specific issue in the Sequelize codebase feel free to post it.
