### ISSUE TITLE
Failing tests with MySQL 5.7

### ISSUE THREAD

**Issue by Naoto-Ida** [sequelize/sequelize#6345]
I am currently trying to solve #6307 and familiarize myself with the innards of the library, and have started to look into the code.

This is the first time I am dealing with tests, so would like to ask the contributors directly. I followed the instructions for contributing and ran `npm run test-mysql` in the sequelize directory.

I have the following errors without any editing done to the current code.
```
1366 passing (2m)
  2 pending
  4 failing

  1) [MYSQL] DataTypes allows me to return values from a custom parse function:
     SequelizeDatabaseError: ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '2011-10-30 15:00:00 +00:00' for column 'dateField' at row 1
      at Query.formatError (lib/dialects/mysql/query.js:204:16)
      at Query.connection.query [as _callback] (lib/dialects/mysql/query.js:56:23)
      at Query.Sequence.end (node_modules/mysql/lib/protocol/sequences/Sequence.js:85:24)
      at Query.ErrorPacket (node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:280:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:74:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:109:28)
      at readableAddChunk (_stream_readable.js:172:18)
      at Socket.Readable.push (_stream_readable.js:130:10)
      at TCP.onread (net.js:542:20)
  From previous event:
      at Query.run (lib/dialects/mysql/query.js:44:12)
      at retry (lib/sequelize.js:635:32)
      at node_modules/retry-as-promised/index.js:38:21
      at retryAsPromised (node_modules/retry-as-promised/index.js:27:10)
      at Promise.resolve.then.connection (lib/sequelize.js:635:14)
  From previous event:
      at Promise.then (lib/promise.js:21:17)
      at Context.<anonymous> (test/integration/data-types.test.js:65:42)

  2) [MYSQL] DataTypes should parse an empty GEOMETRY field:
     SequelizeDatabaseError: UNKNOWN_CODE_PLEASE_REPORT: Invalid GIS data provided to function st_geometryfromtext.
      at Query.formatError (lib/dialects/mysql/query.js:204:16)
      at Query.connection.query [as _callback] (lib/dialects/mysql/query.js:56:23)
      at Query.Sequence.end (node_modules/mysql/lib/protocol/sequences/Sequence.js:85:24)
      at Query.ErrorPacket (node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:280:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:74:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:109:28)
      at readableAddChunk (_stream_readable.js:172:18)
      at Socket.Readable.push (_stream_readable.js:130:10)
      at TCP.onread (net.js:542:20)
  From previous event:
      at Query.run (lib/dialects/mysql/query.js:44:12)
      at retry (lib/sequelize.js:635:32)
      at node_modules/retry-as-promised/index.js:38:21
      at retryAsPromised (node_modules/retry-as-promised/index.js:27:10)
      at Promise.resolve.then.connection (lib/sequelize.js:635:14)
  From previous event:
      at Promise.then (lib/promise.js:21:17)
      at Context.<anonymous> (test/integration/data-types.test.js:286:43)

  3) [MYSQL] Model sql injection attacks should properly escape the single quotes in coordinates:
     SequelizeDatabaseError: UNKNOWN_CODE_PLEASE_REPORT: Invalid GIS data provided to function st_geometryfromtext.
      at Query.formatError (lib/dialects/mysql/query.js:204:16)
      at Query.connection.query [as _callback] (lib/dialects/mysql/query.js:56:23)
      at Query.Sequence.end (node_modules/mysql/lib/protocol/sequences/Sequence.js:85:24)
      at Query.ErrorPacket (node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:280:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:74:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:109:28)
      at readableAddChunk (_stream_readable.js:172:18)
      at Socket.Readable.push (_stream_readable.js:130:10)
      at TCP.onread (net.js:542:20)
  From previous event:
      at Query.run (lib/dialects/mysql/query.js:44:12)
      at retry (lib/sequelize.js:635:32)
      at node_modules/retry-as-promised/index.js:38:21
      at retryAsPromised (node_modules/retry-as-promised/index.js:27:10)
      at Promise.resolve.then.connection (lib/sequelize.js:635:14)
  From previous event:
      at Promise.then (lib/promise.js:21:17)

  4) [MYSQL] Sequelize query logging logs warnings when there are warnings:
     SequelizeDatabaseError: ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: 'HORSE' for column 'createdAt' at row 1
      at Query.formatError (lib/dialects/mysql/query.js:204:16)
      at Query.connection.query [as _callback] (lib/dialects/mysql/query.js:56:23)
      at Query.Sequence.end (node_modules/mysql/lib/protocol/sequences/Sequence.js:85:24)
      at Query.ErrorPacket (node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
      at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:280:23)
      at Parser.write (node_modules/mysql/lib/protocol/Parser.js:74:12)
      at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)
      at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:109:28)
      at readableAddChunk (_stream_readable.js:172:18)
      at Socket.Readable.push (_stream_readable.js:130:10)
      at TCP.onread (net.js:542:20)
      at TCP.onread (node_modules/async-listener/glue.js:188:31)
  From previous event:
      at Query.run (lib/dialects/mysql/query.js:44:12)
      at retry (lib/sequelize.js:635:32)
      at node_modules/retry-as-promised/index.js:38:21
      at retryAsPromised (node_modules/retry-as-promised/index.js:27:10)
      at Promise.resolve.then.connection (lib/sequelize.js:635:14)
  From previous event:
      at Promise.then (lib/promise.js:21:17)
      at Sequelize.query (lib/sequelize.js:632:7)
      at Context.<anonymous> (test/integration/sequelize.test.js:281:28)
```

Is this expected? I want to progress with figuring out how to solve the aforementioned issue, but not sure if I should progress from here.

**Comment by sushantdhiman** [comment]
Some of these are `GEOMETRY` related errors, which can be ignored, CI test must pass though. But `ER_TRUNCATED_WRONG_VALUE` seems to be related with #6326

@Naoto-Ida Are you using `MySQL 5.7` ? Can you tell me more about your machine configuration, It seems we might have some issue with `5.7`

**Comment by Naoto-Ida** [comment]
@sushantdhiman Thank you for the fast response.

I've installed `Server version: 5.7.13 Homebrew` on my Mac via Homebrew.

**Comment by sushantdhiman** [comment]
@SkamDart was also using `5.7.13`. This indicate possibility of bug with `5.7.13` :) 

@Naoto-Ida Right now our CI use `5.6`, So you can open PR with your fix. If CI passes and everything looks fine, we will accept.

**Comment by Naoto-Ida** [comment]
@sushantdhiman Ok, thanks. How can I simply `console.log` certain values? Should I just chuck the `lib` directory in my GraphQL project and import via relative path instead of `import Sequelize from 'sequelize'`?

**Comment by sushantdhiman** [comment]
What values you want to `console.log`

**Comment by Naoto-Ida** [comment]
I'll reopen #6307 and reply there since this is sort of out of the scope of this issue.
