### ISSUE TITLE
Creating with associations as transactional

### ISSUE THREAD

**Issue by mozk91** [sequelize/sequelize#6376]
Hi,

Is that possible creating with associations as transactional? When an error occurs on associated model creating, rollback entire transaction?

Models: 

```js
module.exports = function(sequelize, DataTypes) {
  var User = sequelize.define("User", {
    username: DataTypes.STRING
  }, {
    classMethods: {
      associate: function(models) {
        User.hasMany(models.Task)
      }
    }
  });

  return User;
};

module.exports = function(sequelize, DataTypes) {
  var Task = sequelize.define("Task", {
    title: DataTypes.STRING(1)
  }, {
    classMethods: {
      associate: function(models) {
        Task.belongsTo(models.User, {
          onDelete: "CASCADE",
          foreignKey: {
            allowNull: false
          }
        });
      }
    }
  });

  return Task;
};
```

When called the create with association as below, throws SequelizeDatabaseError: ER_DATA_TOO_LONG: Data too long for column 'title' at row 1

```js
  models.User.create({
    username: "username",
    Tasks: [{
      title: "Too long data for column"
    }]
  }, {
    include: [models.Task]
  }).then(function() {
    console.log('success');
  }).catch(function(err) {
   console.log(err);
  })
```

And then MySQL query results: 

```
mysql> select * from users;
+----+----------+---------------------+---------------------+
| id | username | createdAt           | updatedAt           |
+----+----------+---------------------+---------------------+
|  1 | username   | 2016-08-04 13:35:41 | 2016-08-04 13:35:41 |
+----+----------+---------------------+---------------------+
1 row in set (0.00 sec)

mysql> select * from tasks;
Empty set (0.00 sec)
```

**Comment by drunkhacker** [comment]
I tried but it wasn't successful. Dependent model is firstly created w/o transaction.. any help?

**Comment by felixfbecker** [comment]
I don't see any `transaction()` call in your code. Please try this:
```js
sequelize.transaction(transaction =>
  models.User.create({
    username: "username",
    Tasks: [{
      title: "Too long data for column"
    }]
  }, {
    include: [models.Task],
    transaction
  }).then(function() {
    console.log('success');
  }).catch(function(err) {
   console.log(err);
  })
})
```

**Comment by mozk91** [comment]
I tried as your code but it is not working.

Logs:

```
Executing (d6f12494-d60f-499a-bf64-2c51f23c6a8a): START TRANSACTION;
Executing (d6f12494-d60f-499a-bf64-2c51f23c6a8a): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (d6f12494-d60f-499a-bf64-2c51f23c6a8a): SET autocommit = 1;
Executing (d6f12494-d60f-499a-bf64-2c51f23c6a8a): INSERT INTO `Users` (`id`,`username`,`createdAt`,`updatedAt`) VALUES (DEFAULT,'username','2016-08-26 12:44:52','2016-08-26 12:44:52');
Executing (d6f12494-d60f-499a-bf64-2c51f23c6a8a): INSERT INTO `Tasks` (`id`,`title`,`createdAt`,`updatedAt`,`UserId`) VALUES (DEFAULT,'Too long data for column','2016-08-26 12:44:52','2016-08-26 12:44:52',1);
Executing (d6f12494-d60f-499a-bf64-2c51f23c6a8a): COMMIT;
```

After `COMMIT` it throws an error as below.

```
{
  "err": {
    "name": "SequelizeDatabaseError",
    "message": "ER_DATA_TOO_LONG: Data too long for column 'title' at row 1",
    "parent": {
      "code": "ER_DATA_TOO_LONG",
      "errno": 1406,
      "sqlState": "22001",
      "index": 0,
      "sql": "INSERT INTO `Tasks` (`id`,`title`,`createdAt`,`updatedAt`,`UserId`) VALUES (DEFAULT,'Too long data for column','2016-08-26 12:44:52','2016-08-26 12:44:52',1);"
    },
    "original": {
      "code": "ER_DATA_TOO_LONG",
      "errno": 1406,
      "sqlState": "22001",
      "index": 0,
      "sql": "INSERT INTO `Tasks` (`id`,`title`,`createdAt`,`updatedAt`,`UserId`) VALUES (DEFAULT,'Too long data for column','2016-08-26 12:44:52','2016-08-26 12:44:52',1);"
    },
    "sql": "INSERT INTO `Tasks` (`id`,`title`,`createdAt`,`updatedAt`,`UserId`) VALUES (DEFAULT,'Too long data for column','2016-08-26 12:44:52','2016-08-26 12:44:52',1);"
  }
}
```

And database queries:

```
mysql> select * from users;
+----+----------+---------------------+---------------------+
| id | username | createdAt           | updatedAt           |
+----+----------+---------------------+---------------------+
|  1 | username | 2016-08-26 12:44:52 | 2016-08-26 12:44:52 |
+----+----------+---------------------+---------------------+
1 row in set (0.00 sec)

mysql> select * from tasks;
Empty set (0.01 sec)
```

**Comment by felixfbecker** [comment]
But the logs indicate that both queries were executed inside the transaction. Im only confused by `SET AUTOCOMMIT = 1`.

Can you please tell me what mysql version, sequelize and mysql driver version you are using?

**Comment by mozk91** [comment]
I'm using

mysql@2.11.1
sequelize@3.23.6
MySQL Server version: 5.7.14

**Comment by felixfbecker** [comment]
Could you provide an [SSCCE](http://www.sscce.org/)? See template [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js)

**Comment by mozk91** [comment]
I updated to sequelize@3.24.1 but I can not running SSCCE :(

```
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "sscce-mysql"
npm ERR! node v6.3.0
npm ERR! nam  v3.10.7
npm ERR! code ELIFECYCLE
npm ERR! sequelize@3.24.1 sscce-mysql: `DIALECT=mysql npm run soccer
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sequelize@3.24.1 sscce-mysql script 'DIALECT=mysql npm run soccer'

```

From npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'sscce-mysql' ]
2 info using npm@3.10.7
3 info using node@v6.3.0
4 verbose run-script [ 'presscce-mysql', 'sscce-mysql', 'postsscce-mysql' ]
5 info lifecycle sequelize@3.24.1~presscce-mysql: sequelize@3.24.1
6 silly lifecycle sequelize@3.24.1~presscce-mysql: no script for presscce-mysql, continuing
7 info lifecycle sequelize@3.24.1~sscce-mysql: sequelize@3.24.1
8 verbose lifecycle sequelize@3.24.1~sscce-mysql: unsafe-perm in lifecycle true
9 verbose lifecycle sequelize@3.24.1~sscce-mysql: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/............
10 verbose lifecycle sequelize@3.24.1~sscce-mysql: CWD: /Users/............
11 silly lifecycle sequelize@3.24.1~sscce-mysql: Args: [ '-c', 'DIALECT=mysql npm run sscce' ]
12 silly lifecycle sequelize@3.24.1~sscce-mysql: Returned: code: 1  signal: null
13 info lifecycle sequelize@3.24.1~sscce-mysql: Failed to exec sscce-mysql script
14 verbose stack Error: sequelize@3.24.1 sscce-mysql: `DIALECT=mysql npm run soccer
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
````

**Comment by felixfbecker** [comment]
Just post the sscce.

**Comment by mozk91** [comment]
```
/*
 * Copy this file to ./sscce.js
 * Add code from issue
 * npm run sscce-{dialect}
 */
var Sequelize = require('./index');
var sequelize = require('./test/support').createSequelizeInstance();

var User = sequelize.define("User", {
    username: DataTypes.STRING
});
var Task = sequelize.define("Task", {
    title: DataTypes.STRING(1)
});

User.hasMany(Task);
Task.belongsTo(User);

sequelize.sync({
        force: true
    })
    .then(() => sequelize.transaction(transaction => User.create({
            username: "username",
            Tasks: [{
                title: "Too long data for column"
            }]
        }, {
            include: [Task],
            transaction
        })
    }))
.then(console.log)
.catch(console.log);
```
