### ISSUE TITLE
DatabaseError: Column does not exist when querying with nested include and where

### ISSUE THREAD

**Issue by felixfbecker** [sequelize/sequelize#6400]
## What you are doing?

_Post a minimal code sample that reproduces the issue, including models and associations_

``` js
const Mail = sequelize.define('Mail', {
    subject: Sequelize.TEXT,
    content: Sequelize.TEXT
}, {
    paranoid: true
});

const MailboxEntry = sequelize.define('MailboxEntry', {
    movedToTrashAt: {
        type: Sequelize.DATE,
        allowNull: true
    },
    read: {
        type: Sequelize.BOOLEAN,
        allowNull: false,
        defaultValue: false
    }
}, {
    paranoid: true
});

const User = sequelize.define('User', {
    username: {
        type: Sequelize.TEXT,
        unique: true,
        allowNull: false,
    },
    firstName: {
        type: Sequelize.TEXT,
        allowNull: false
    },
    lastName: {
        type: Sequelize.TEXT,
        allowNull: false
    }
})

Mail.belongsTo(User, {
    as: 'sender',
    foreignKey: {
        name: 'senderId',
        allowNull: false
    }
});
Mail.belongsToMany(User, {
    as: 'recipients',
    through: 'MailRecipients',
    otherKey: {
        name: 'recipientId',
        allowNull: false
    },
    foreignKey: {
        name: 'mailId',
        allowNull: false
    }
});

Mail.hasMany(MailboxEntry, {
    as: 'mailboxEntries',
    foreignKey: {
        name: 'mailId',
        allowNull: false
    }
});

MailboxEntry.belongsTo(User, {
    as: 'owner',
    foreignKey: {
        name: 'ownerId',
        allowNull: false
    }
});

MailboxEntry.belongsTo(Mail, {
    as: 'mail',
    foreignKey: {
        name: 'mailId',
        allowNull: false
    }
});

const userId = 1;

sequelize.sync().then(() => MailboxEntry.findAndCount({
        offset: 0,
        limit: 10,
        order: [['createdAt', 'DESC']],
        include: [
            {
                association: MailboxEntry.associations.mail,
                attributes: { exclude: ['content'] },
                include: [
                    {
                        association: Mail.associations.recipients,
                        attributes: ['id', 'username', 'firstName', 'lastName'],
                        through: {
                            where: {
                                recipientId: userId
                            }
                        },
                        required: true
                    }
                ],
                required: true
            }
        ],
        where: {
            ownerId: userId,
            movedToTrashAt: null
        },
        attributes: { exclude: ['movedToTrashAt'] }
    }).then(result => console.log(result), err => console.error(err));
```
## What do you expect to happen?

Getting back a list of mailbox entries with included mail (content) with included recipients, that belong to a user (ownerId), where the user is the recipient and that are not moved to trash.
## What is actually happening?

`SequelizeDatabaseError: Column Mail.mailId does not exist`

Executed query:

``` sql
SELECT "MailboxEntry".*,
       "mail.recipients"."id" AS "mail.recipients.id",
       "mail.recipients"."username" AS "mail.recipients.username",
       "mail.recipients"."firstName" AS "mail.recipients.firstName",
       "mail.recipients"."lastName" AS "mail.recipients.lastName",
       "mail.recipients.MailRecipients"."createdAt" AS "mail.recipients.MailRecipients.createdAt",
       "mail.recipients.MailRecipients"."updatedAt" AS "mail.recipients.MailRecipients.updatedAt",
       "mail.recipients.MailRecipients"."mailId" AS "mail.recipients.MailRecipients.mailId",
       "mail.recipients.MailRecipients"."recipientId" AS "mail.recipients.MailRecipients.recipientId"
FROM
  (SELECT "MailboxEntry"."id",
          "MailboxEntry"."read",
          "MailboxEntry"."createdAt",
          "MailboxEntry"."updatedAt",
          "MailboxEntry"."deletedAt",
          "MailboxEntry"."ownerId",
          "MailboxEntry"."mailId",
          "mail"."id" AS "mail.id",
          "mail"."subject" AS "mail.subject",
          "mail"."createdAt" AS "mail.createdAt",
          "mail"."updatedAt" AS "mail.updatedAt",
          "mail"."deletedAt" AS "mail.deletedAt",
          "mail"."senderId" AS "mail.senderId"
   FROM "MailboxEntries" AS "MailboxEntry"
   INNER JOIN "Mails" AS "mail" ON "MailboxEntry"."mailId" = "mail"."id"
   AND "mail"."deletedAt" IS NULL
   WHERE ("MailboxEntry"."deletedAt" IS NULL
          AND ("MailboxEntry"."ownerId" = '1'
               AND "MailboxEntry"."movedToTrashAt" IS NULL))
     AND
       (SELECT "Mail"."id"
        FROM "Mails" AS "Mail"
        INNER JOIN ( "MailRecipients" AS "recipients.MailRecipients"
                    INNER JOIN "Users" AS "recipients" ON "recipients"."id" = "recipients.MailRecipients"."recipientId"
                    AND "recipients.MailRecipients"."recipientId" = '1') ON "Mail"."id" = "recipients.MailRecipients"."mailId"
        AND "recipients"."deletedAt" IS NULL
        WHERE "MailboxEntry"."id" = "Mail"."mailId" LIMIT 1) IS NOT NULL
   ORDER BY "MailboxEntry"."createdAt" DESC LIMIT 10
   OFFSET 0) AS "MailboxEntry"
INNER JOIN ("MailRecipients" AS "mail.recipients.MailRecipients"
            INNER JOIN "Users" AS "mail.recipients" ON "mail.recipients"."id" = "mail.recipients.MailRecipients"."recipientId"
            AND "mail.recipients.MailRecipients"."recipientId" = '1') ON "mail.id" = "mail.recipients.MailRecipients"."mailId"
AND "mail.recipients"."deletedAt" IS NULL
ORDER BY "MailboxEntry"."createdAt" DESC;
```

**Dialect:** postgres
**Database version:** 9.5.2
**Sequelize version:** 3.23.3

**Comment by felixfbecker** [comment]
Commenting out the `recipients` inclusion makes the query work, but it will of course return all mailbox entries, not only where the user  is the recipient

**Comment by felixfbecker** [comment]
Including just the `sender` works. But as soon as `recipients` is included, unknown column error occur

**Comment by felixfbecker** [comment]
@mickhansen help please 🆘

**Comment by felixfbecker** [comment]
The problem is here:
```sql
WHERE
"MailboxEntry"."id" =
"Mail"."mailId"
```
it should be the other way around. It seems like sequelize swappes the columns by mistake.

**Comment by felixfbecker** [comment]
Similar issue when querying all mailbox entries for mails the user has sent:
```js
MailboxEntry.findAndCount({
        offset, limit, order, include: [
            {
                association: MailboxEntry.associations.mail,
                attributes: { exclude: ['content'] },
                include: [
                    {
                        association: Mail.associations.recipients,
                        attributes: ['id', 'username', 'firstName', 'lastName']
                    },
                    {
                        association: Mail.associations.sender,
                        attributes: ['id', 'username', 'firstName', 'lastName'],
                        required: true,
                        where: {
                            senderId: req.params.userId
                        }
                    }
                ],
                required: true
            }
        ],
        where: {
            ownerId: req.params.userId,
            movedToTrashAt: null
        },
        attributes: { exclude: ['movedToTrashAt'] }
    });
```
```sql
SELECT count("MailboxEntry"."id") AS "count"
FROM "MailboxEntries" AS "MailboxEntry"
INNER JOIN "Mails" AS "mail" ON "MailboxEntry"."mailId" = "mail"."id"
AND "mail"."deletedAt" IS NULL
LEFT OUTER JOIN ("MailRecipients" AS "mail.recipients.MailRecipients"
                 INNER JOIN "Users" AS "mail.recipients" ON "mail.recipients"."id" = "mail.recipients.MailRecipients"."recipientId") ON "mail"."id" = "mail.recipients.MailRecipients"."mailId"
AND "mail.recipients"."deletedAt" IS NULL
INNER JOIN "Users" AS "mail.sender" ON "mail"."senderId" = "mail.sender"."id"
AND ("mail.sender"."deletedAt" IS NULL
     AND "mail.sender"."senderId" = '1')
WHERE ("MailboxEntry"."deletedAt" IS NULL
       AND ("MailboxEntry"."ownerId" = '1'
            AND "MailboxEntry"."movedToTrashAt" IS NULL));
```
```
ERROR:  Column mail.sender.senderId does not exist
LINE 10:      AND "mail.sender"."senderId" = '1')
                  ^
```

**Comment by mlegenhausen** [comment]
Same problem in combination of `belongsTo` and then referencing a `belongsToMany` relation.

**Comment by willdawsonme** [comment]
Problem seems to be in `lib/dialects/abstract/query-generator.js` around line `1285`. Only happens for me when using `limit` with a nested include where. Sequelize is assuming the top-level include is a `hasMany` association, when in fact it is a `belongsTo` association, hence why it is "swapping" the primary/foreign key WHERE clause.

**Comment by felixfbecker** [comment]
@willdawsonme I would applaud you if you could submit the fix in a PR.

**Comment by willdawsonme** [comment]
@felixfbecker Would that require probing the nature of the relation to determine which primary/foreignKey attributes to use where, or would it always be a `belongsTo` association? I can look into it further if you're unsure.

**Comment by felixfbecker** [comment]
I would start by adding a failing test case to experiment when the bug occurs and then fixing it

**Comment by jlevesque** [comment]
I still have the issue in v4.38...
@felixfbecker how is it possible? Or am I doing something wrong?

My association:
```
User.belongsTo(Role, {foreignKey: 'roleId', as: 'role'});
```

My query :
```
User.findById(req.params.id, {
        include: [{ model: Role, as: 'role' }]
    }).then(response => res.status(200).json({
        error: false,
        data: response,
    })).catch(error => res.json({
        error: true,
        data: error
    }));
```

I get :
`... LEFT OUTER JOIN Roles AS role ON User.id = role.roleId WHERE User.id = '1';"`

It's suppose to be :
`... LEFT OUTER JOIN Roles AS role ON User.roleId = role.id WHERE User.id = '1';"`

**Comment by vivekhabilelabs** [comment]
I am still having this issue on 5.5.0, any workaround?

**Comment by mienaikoe** [comment]
Still having this issue in 5.21.3.  ...

**Comment by artempokutnii** [comment]
The same problem guys!

**Comment by yusufkhan07** [comment]
Still have this issue

**Comment by manojkumar3692** [comment]
Same issue

**Comment by victorfariasoliveira** [comment]
When defining the search without specifying the attributes to be returned, the error is shown:
`
    await User.findAll({
      where: { provider: true },
      attributes: ['id', 'name', 'email'],
      include: [
        {
          model: File,
          as: 'avatar',
        },
      ],
    });
`
Error: 
`
Executing (default): SELECT "... ."updated_at" AS "avatar.updatedAt" FROM "users" AS "User" LEFT OUTER JOIN "files" AS "avatar" ON "User"."avatar_id" = "avatar"."id" WHERE "User"."provider" = true;      
(node:19224) UnhandledPromiseRejectionWarning: SequelizeDatabaseError: column avatar.email does not exist
`
When I defined the fields to be returned, no more errors are displayed
`
      include: [
        {
          model: File,
          as: 'avatar',
          attributes: ['name', 'path'],
        },
      ],
`

**Comment by kiaxseventh** [comment]
same issue on v5
on my localhost working wothout problem
but on server have problem
my db version on localhost and on my server is same

**Comment by superrandres** [comment]
Hello, I have the same problem. When I use the belongsTo relation directly in the Listing model it works, but when I use the relation in the Listing model that is the result of a belongsToMany relation, it mistakenly generates the JOIN between tables doing: listings->marca.marcaId instead of: listings->marca.id Which generates the following error:

> SequelizeDatabaseError: column listings->marca.marcaId does not exist
auto-rest_1  |     at Query.formatError (/app/general-persistence/node_modules/sequelize/lib/dialects/postgres/query.js:366:16)
auto-rest_1  |     at /app/general-persistence/node_modules/sequelize/lib/dialects/postgres/query.js:72:18
auto-rest_1  | From previous event:
auto-rest_1  |     at Query.run (/app/general-persistence/node_modules/sequelize/lib/dialects/postgres/query.js:64:23)
auto-rest_1  |     at /app/general-persistence/node_modules/sequelize/lib/sequelize.js:655:29
auto-rest_1  | From previous event:
auto-rest_1  |     at /app/general-persistence/node_modules/sequelize/lib/sequelize.js:655:12
auto-rest_1  | From previous event:
auto-rest_1  |     at /app/general-persistence/node_modules/sequelize/lib/sequelize.js:651:10
auto-rest_1  |     at /app/general-persistence/node_modules/retry-as-promised/index.js:70:21
auto-rest_1  |     at new Promise (<anonymous>)
auto-rest_1  |     at retryAsPromised (/app/general-persistence/node_modules/retry-as-promised/index.js:60:10)
auto-rest_1  |     at /app/general-persistence/node_modules/sequelize/lib/sequelize.js:641:30
auto-rest_1  | From previous event:
auto-rest_1  |     at Sequelize.query (/app/general-persistence/node_modules/sequelize/lib/sequelize.js:590:23)
auto-rest_1  |     at QueryInterface.select (/app/general-persistence/node_modules/sequelize/lib/query-interface.js:1126:27)
auto-rest_1  |     at /app/general-persistence/node_modules/sequelize/lib/model.js:1759:34
auto-rest_1  |     at processImmediate (internal/timers.js:456:21)
auto-rest_1  | From previous event:
auto-rest_1  |     at Function.findAll (/app/general-persistence/node_modules/sequelize/lib/model.js:1757:8)
auto-rest_1  |     at ItemController.getListas (/app/auto-rest/controladores/front/v1/private/listas-deseos.js:16:22)
auto-rest_1  | 2020-07-21T20:04:18.479Z micro:auto-rest:cookies-managment GET /front/v1/private/listas-deseos/getListas 500 323.625 ms - 158

**Comment by superrandres** [comment]
Hello, I just solved it by declaring one more relation (hasMarca) and specifying the foreignKey to id. Being as follows:
`Listing.hasOne(models.Marca, {
      as: 'hasMarca',
      foreignKey: 'id',
      constraints: false
    })
    Listing.belongsTo(models.Marca, {
      as: 'marca',
      foreignKey: 'marcaId',
      targetKey: 'id'
    })
`
If I use the belognsTo it will throw the error I mentioned ...

**Comment by MarcusAguiarURA** [comment]
I solved my problem removing the options (as/foreignKey) from the "has" side. Using it only on model that "belongs" to another...

**Comment by MaximoSucari** [comment]
Hi! Same problem, v6.6.4. Any news?

**Comment by fesaza** [comment]
> Seeing this issue as well, but only when passing the `limit` parameter.
> 
> Table foreign key setup: `Role` < `UserRole` > `User` `UserRole` table has no `id` property.
> 
> ```js
> User.hasMany(UserRole, { foreignKey: "UserId"});
> UserRole.belongsTo(User, { foreignKey: "UserId"});
> 
> UserRole.belongsTo(Role, { foreignKey: "RoleId"});
> Role.hasMany(UserRole, { foreignKey: "RoleId"});
> 
> User.belongsToMany(Role, { through: UserRole, foreignKey: 'UserId' })
> Role.belongsToMany(User, { through: UserRole, foreignKey: 'RoleId' })
> 
> UserRole.removeAttribute('id')
> 
> Role.addScope('owner', ownerId => ({
>   include: { model: Users, where: { Id: ownerId } }
> }))
> 
> // ...
> 
> Role.scope({ method: [ 'owner', 'some-id' ] }).findAndCountAll({ limit: 100 })
> ```
> 
> Produced query:
> 
> ```sql
> SELECT
>   [Role].*,
>   [Users].[Id] AS [Users.Id],
>   [Users->UserRole].[UserId] AS [Users.UserRole.UserId],
>   [Users->UserRole].[RoleId] AS [Users.UserRole.RoleId],
> FROM (
>   SELECT
>     [Role].[Id],
>     [Role].[Name],
>   FROM [dbo].[Role] AS [Role]
>   WHERE (
>     SELECT [UserRole].[id] -- <<< id column does not exist
>     FROM [dbo].[UserRole] AS [UserRole]
>     INNER JOIN [dbo].[User] AS [User]
>     ON [UserRole].[UserId] = [User].[Id]
>     AND [User].[Id] = N'some-id'
>     WHERE ([Role].[Id] = [UserRole].[RoleId])
>     ORDER BY [UserRole].[id] OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY -- <<< id column does not exist
>   ) IS NOT NULL
>   ORDER BY [Role].[Id] OFFSET 0 ROWS FETCH NEXT 100 ROWS ONLY
> ) AS [Role]
> INNER JOIN ( [dbo].[UserRole] AS [Users->UserRole]
> INNER JOIN [dbo].[User] AS [Users]
> ON [Users].[Id] = [Users->UserRole].[UserId])
> ON [Role].[Id] = [Users->UserRole].[RoleId]
> AND [Users].[Id] = N'some-id';
> ```
> 
> Produces this error:
> 
> ```
>  original: RequestError: Invalid column name 'id'.
>       at Parser.<anonymous> (/home/egeste/Source/redacted/node_modules/tedious/lib/connection.js:1175:27)
>       at Parser.emit (events.js:400:28)
>       at Readable.<anonymous> (/home/egeste/Source/redacted/node_modules/tedious/lib/token/token-stream-parser.js:27:14)
>       at Readable.emit (events.js:400:28)
>       at addChunk (internal/streams/readable.js:290:12)
>       at readableAddChunk (internal/streams/readable.js:265:9)
>       at Readable.push (internal/streams/readable.js:204:10)
>       at next (internal/streams/from.js:88:29)
>       at processTicksAndRejections (internal/process/task_queues.js:95:5)
> ```

I spent a lot of time trying to figure out why the nested column where was failing and the issue is when we passed the `limit` parameter

does anyone know why?

**Comment by eric-endsley** [comment]
+1 for this issue. I'm getting an invalid column error when trying to search by a deeply nested property in my where statement. After reading this thread I tried removing my limit clause and bizarrely it fixes the error, but unfortunately this is not a tenable fix for me. Any suggestions on a workaround which does not restrict my querying options would be extremely appreciated. 

I can provide more info if that's helpful, but it appears to be a match with the issues described above.

**Comment by ephys** [comment]
It's probably not the same issue. This issue is about `belongsTo` referencing the wrong column in its join. I'm pretty sure this has since been fixed. I'm keeping it open until we've investigated the other issue where belongsToMany tried to reference the non-existant 'id' column when in a subquery (although that should be its own issue).

Your issue seems to be https://github.com/sequelize/sequelize/issues/12971

**Comment by lssosa** [comment]
Same issue in v6.31.0 😫, only when passing `limit ` parameter 🥺

**Comment by mbkkong** [comment]
> Same issue in v6.31.0 😫, only when passing `limit ` parameter 🥺

Yes, it's a problem with `limit` filter. 

I resolved it by passing in nested includes reference column. Here is an example include:
```javascript
const include = [
  {
    model: Conversion,
    as: "conversions",
    limit: 25,
    offset: 0,
    where: {},
    attributes: [
      "id",
      "slug",
      "createdAt",
      // Required reference columns
      "metricToId",
      "metricFromId",
      "categoryId",
    ],
    include: [
      {
        model: Metric,
        as: "metricTo",
        attributes: [
          "id",
          "title",
          "ratio",
          // Required reference columns
          "categoryId",
        ],
      },
    ],
  },
];

```

If you want to get all columns from the model and filter out only those with a reference, you can do it like this:
```javascript
const attributes = Conversion.getAttributes()
const requiredAttributes = Object.keys(attributes)
  .filter((key) => attributes[key].references)
```

And this `requiredAttributes` you can push to attribute list.

**Comment by IonelLupu** [comment]
Same issue here. This looks important to fix. Our workaround is to use `subquery: false` in the find options.
