### ISSUE TITLE
"result.get is not a function" when querying with global raw: true and includes

### ISSUE THREAD

**Issue by KostiaGontarev** [sequelize/sequelize#6408]
Hi guys! I encountered a problem, when trying to do includes. I have already saw a couple of similar issues here, but not equal to mine. The case is simpliest - users and roles. 
Here are the models:

```
const UserScheme = require('server/dataAccess/schemes/userScheme');

module.exports = function (sequelize, DataTypes) {
    const UserDataModel = sequelize.define(UserScheme.tableName, UserScheme.columnsDescription, {
        schema: UserScheme.schema
    });

    return UserDataModel;
};
```

```
const UserScheme = require('server/dataAccess/schemes/userScheme');
const UserRoleScheme = require('server/dataAccess/schemes/userRoleScheme');
const UserRoleAssociationScheme = require('server/dataAccess/schemes/userRoleAssociationScheme');

module.exports = function (sequelize, DataTypes) {
    const UserRoleDataModel = sequelize.define(UserRoleScheme.tableName, UserRoleScheme.columnsDescription, {
        schema: UserRoleScheme.schema,
        classMethods: {
            associate: models => {
                models[UserRoleScheme.tableName].belongsToMany(models[UserScheme.tableName], {
                    as: 'Users',
                    through: UserRoleAssociationScheme.tableName,
                    foreignKey: {
                        name: UserRoleAssociationScheme.columnsDescription.userRoleId.field
                    }
                });
                models[UserScheme.tableName].belongsToMany(models[UserRoleScheme.tableName], {
                    as: 'Roles',
                    through: UserRoleAssociationScheme.tableName,
                    foreignKey: {
                        name: UserRoleAssociationScheme.columnsDescription.userInfoId.field
                    }
                });
            }
        }
    });

    return UserRoleDataModel;
};
```

And here are the schemas:

```
const Sequelize = require('sequelize');

class UserDataScheme extends BaseInternalScheme {
    constructor(dataTypes) {
        super(dataTypes);

        this.defineTable('userInfo');
        this.defineColumns({
            id: {
                type: Sequelize.UUID,
                field: 'id',
                allowNull: false,
                unique: true,
                primaryKey: true
            },
            createdAt: {
                type: Sequelize.DATE,
                field: 'createdAt'
            },
            updatedAt: {
                type: Sequelize.DATE,
                field: 'updatedAt'
            },
            fullName: {
                type: Sequelize.STRING,
                field: 'fullName',
                allowNull: false,
                validate: {
                    notEmpty: true,
                    len: [0, 255]
                }
            },
            firstName: {
                type: Sequelize.STRING,
                field: 'firstName',
                allowNull: false,
                validate: {
                    notEmpty: true,
                    len: [0, 255]
                }
            },
            lastName: {
                type: Sequelize.STRING,
                field: 'lastName',
                allowNull: false,
                validate: {
                    notEmpty: true,
                    len: [0, 255]
                }
            },
            phone: {
                type: Sequelize.STRING,
                field: 'phone',
                allowNull: false,
                validate: {
                    notEmpty: true,
                    len: [0, 255]
                }
            }
        });
    }
}

module.exports = new UserDataScheme();
```

```
const BaseInternalScheme = require('server/dataAccess/schemes/baseInternalScheme');
const Sequelize = require('sequelize');

class UserRoleScheme extends BaseInternalScheme {
    constructor() {
        super();

        this.defineTable('userRole');
        this.defineColumns({
           id: {
                type: Sequelize.UUID,
                field: 'id',
                allowNull: false,
                unique: true,
                primaryKey: true
            },
            createdAt: {
                type: Sequelize.DATE,
                field: 'createdAt'
            },
            updatedAt: {
                type: Sequelize.DATE,
                field: 'updatedAt'
            },
            name: {
                type: Sequelize.STRING,
                field: 'name',
                allowNull: false,
                validate: {
                    notEmpty: true,
                    len: [0, 255]
                }
            }
        });
    }
}

module.exports = new UserRoleScheme();
```

```
const BaseScheme = require('server/dataAccess/schemes/baseScheme');
const Sequelize = require('sequelize');

class UserRoleAssociationScheme extends BaseScheme {
    constructor() {
        super('public');

        this.defineTable('userRoleAssociation');
        this.defineColumns({
           id: {
                type: Sequelize.UUID,
                field: 'id',
                allowNull: false,
                unique: true,
                primaryKey: true
            },
            createdAt: {
                type: Sequelize.DATE,
                field: 'createdAt'
            },
            updatedAt: {
                type: Sequelize.DATE,
                field: 'updatedAt'
            },
            userInfoId: {
                type: Sequelize.UUID,
                allowNull: false,
                field: 'userInfoId'
            },
            userRoleId: {
                type: Sequelize.UUID,
                allowNull: false,
                field: 'userRoleId'
            },
            createdAt: {
                type: Sequelize.DATE,
                field: 'createdAt'
            },
            updatedAt: {
                type: Sequelize.DATE,
                field: 'updatedAt'
            }
        });
    }
}

module.exports = new UserRoleAssociationScheme();
```

The problem is in the code below:

```
return this._users.findOne({
            attributes: userAttributes, // Some list of attributes
            where: { id },
            include: {
                as: 'Roles',
                attributes: [UserRoleScheme.columnsDescription.id.field],
                model: this._roles, //this._roles is realy a userRole model
            }
        });
```
## What is expected?

I expect that code will query user with necessary id and join the information about his roles.
## What is actually happening?

Our logger shows the query generated, and when we execute it in the postgres it works fine, but in the application the sequelize throws an error and I haven't found any information about it.

```
error: TypeError: result.get is not a function
    at sequelize\lib\model.js:1424:37
    at Array.reduce (native)
    at sequelize\lib\model.js:1423:17
    at tryCatcher (\sequelize\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (sequelize\node_modules\bluebird\js\release\map.js:57:38)
    at MappingPromiseArray.PromiseArray._iterate (sequelize\node_modules\bluebird\js\release\promise_array.js:113:31)
    at MappingPromiseArray.init (\sequelize\node_modules\bluebird\js\release\promise_array.js:77:10)
    at new MappingPromiseArray (sequelize\node_modules\bluebird\js\release\map.js:25:10)
    at map (sequelize\node_modules\bluebird\js\release\map.js:152:12)
    at Function.Promise.map (sequelize\node_modules\bluebird\js\release\map.js:160:12)
```

This is the problematic code:

```
...
  return Model.$findSeparate(
        results.reduce(function (memo, result) {
          var associations = result.get(include.association.as); <- The error

          // Might be an empty belongsTo relation
          if (!associations) return memo;
...
```

I have already saw that message when we were trying to follow custom approach in model defining and in that case includes not worked at all, but we got rid of it and followed the approach described in the docs when working with Node and Express. 

Maybe I am misunderstood something or there is some error in the model definition, please help me to solve it :)

**Dialect:_ postgres 
__Database version:** 9.5
**Sequelize version:** "^3.23.3"

**Comment by janmeier** [comment]
Can you convert this to a [SSCCE](HTTP://SSCCE.ORG/)? (One where I don't have to have multiple files, just all model definitions and associations in one file) - Including some test data to replicate the problem.

One problem might be that you are using `through: UserRoleAssociationScheme.tableName` - try passing the sequelize model instead

**Comment by KostiaGontarev** [comment]
I found out that even simplest includes stopped working. Actually, it's not necessary, we have found out the root of the problem - the raw option.
When you create a sequelize instance and pass as the option raw: true (migrated from mongo for us), in all includes sequelize throw an error in the row:
...
  return Model.$findSeparate(
        results.reduce(function (memo, result) {
          var associations = result.get(include.association.as); <- The error

          // Might be an empty belongsTo relation
          if (!associations) return memo;
...

However, if you pass raw: true into the query itself, the result would be as expected - plain object. So we got rid of global raw: true and put it into our queries. 
Hope it will help you to improve sequelize :) Good luck!

**Comment by alcmoraes** [comment]
I'm having the same problem and IMO this can't be declared as "solved" since the use of the global raw still doesn't work. Is there any news in that subject?

**Comment by felixfbecker** [comment]
The issue is not clear to me without an SSCCE but `raw` means returning plain objects. Of course plain objects do not have a `get()` method.

**Comment by alcmoraes** [comment]
Yes, of course they don't.

But using a global `raw: true` on sequelize shouldn't crash a simple query using an include.

**Comment by felixfbecker** [comment]
Agree. Reopening, feel free to do a fix

**Comment by alcmoraes** [comment]
Thanks Felix!

Maybe it's a good idea to change the title in order to make it clear that `raw: true` should be set into global settings of sequelize to replicate the issue.

Using `raw: true` directly in the query works just fine.

**Comment by mubaidr** [comment]
Had the same issue recently, for now switching back to local level usage of {raw: true} until there is a solution.

**Comment by Innomalist** [comment]
Same issue. There should be a fix provided for this. There are hundreds of queries written in app and it doesn't look good to add raw on each query.

**Comment by Innomalist** [comment]
Also setting raw:true on query doesn't do the same for nested values. instead it makes the whole row one dimensional

**Comment by Pruxis** [comment]
This issue is still relative today.

**Comment by rsicher1** [comment]
I'm having this issue as well. Not stale at all.

**Comment by jslok** [comment]
Same issue here

**Comment by papb** [comment]
I will reopen this, but we maintainers need a [SSCCE](http://sscce.org/) (also known as [MCVE/reprex](https://stackoverflow.com/help/minimal-reproducible-example)) to be able to work on it.

As janmeier said a long time ago:

> Can you convert this to a [SSCCE](HTTP://SSCCE.ORG/)? (One where I don't have to have multiple files, just all model definitions and associations in one file) - Including some test data to replicate the problem.

When someone provides one, we shall look into it. Thanks!

**Comment by PicusViridis** [comment]
Hello,
Please find here a SSCCE for this issue: https://github.com/PicusViridis/sequelize-6408
As mentioned in this thread, adding `query: { raw: true }` option in sequelize constructor generates an error when using `include` in a query.
Removing either the `include` from the query or the `query: { raw: true }` option removes the error.

**Comment by obernardovieira** [comment]
Hi, is there any progress on this? I'm very interested. I've just confirmed the issue described here. But I have recently cleaned all the queries to use `query: { raw: true }` globally.

> Hello,
> Please find here a SSCCE for this issue: https://github.com/PicusViridis/sequelize-6408
> As mentioned in this thread, adding `query: { raw: true }` option in sequelize constructor generates an error when using `include` in a query.
> Removing either the `include` from the query or the `query: { raw: true }` option removes the error.

If it's still the same, I may have to spend a considerable amount of time to do what @luisfrocha said

> It's April 2, 2020, and the issue is still present. Gonna have to set the raw on each query instead of globally.

Thanks.

**Comment by obernardovieira** [comment]
Decided to not move forward regarding removing the `query: { raw: true }` from global config.

How can I help moving forward with this?

**Comment by nichita-pasecinic** [comment]
6 years later

**Comment by obernardovieira** [comment]
Hi,
ever since my last post, I tried some different things and as of today, I have many includes working. [Here's an example](https://github.com/impactMarket/backend/blob/main/packages/core/src/services/ubi/community.ts#L784). I think there's a very specific issue when doing M:N, but can't remember anymore. For most cases, it's really a question of getting the associations right. I remember I've spent a good amount of time on that.

**Comment by ephys** [comment]
A PR that adds an integration test & resolve this issue would be welcomed
