### ISSUE TITLE
Query on associated entity fails: self.$expandAttributes is not a function

### ISSUE THREAD

**Issue by adamryvola** [sequelize/sequelize#6452]
I want to create query based on associated entity:

```
const User = sequelize.define('user', {
    username: Sequelize.STRING,
    firstname: Sequelize.STRING,
    lastname: Sequelize.STRING,
    password: Sequelize.STRING,
    salt: Sequelize.STRING,
});

const Account = sequelize.define('account', {
    provider: Sequelize.STRING,
    accessToken: Sequelize.STRING,
    refreshToken: Sequelize.STRING,
    email: Sequelize.STRING,
    subject: Sequelize.STRING
});

var googleAcc = User.belongsTo(Account, {as: 'google_account'});

export function getUserByGoogleId(googleId) {
    return User.find({include: [{model:googleAcc, where: {subject: googleId}}]});
}
```
Tables and another queries are ok.
Function getUserById(googleId) fails with this error:

`[1] Unhandled rejection TypeError: self.$expandAttributes is not a function
[1]     at conformOptions (C:\Users\Adam Ryvola\Desktop\SHARING PORTAL\node_modules\sequelize\lib\model.js:242:10)
[1]     at conformInclude (C:\Users\Adam Ryvola\Desktop\SHARING PORTAL\node_modules\sequelize\lib\model.js:299:5)
[1]     at C:\Users\Adam Ryvola\Desktop\SHARING PORTAL\node_modules\sequelize\lib\model.js:258:15
[1]     at Array.map (native)
[1]     at conformOptions (C:\Users\Adam Ryvola\Desktop\SHARING PORTAL\node_modules\sequelize\lib\model.js:257:37)
[1]     at .<anonymous> (C:\Users\Adam Ryvola\Desktop\SHARING PORTAL\node_modules\sequelize\lib\model.js:1348:5)
[1]     at tryOnImmediate (timers.js:543:15)
[1]     at processImmediate [as _immediateCallback] (timers.js:523:5)
[1] From previous event:
[1]     at Promise.then (C:\Users\Adam Ryvola\Desktop\SHARING PORTAL\node_modules\sequelize\lib\promise.js:21:17)
[1]     at Model.findAll (C:\Users\Adam Ryvola\Desktop\SHARING PORTAL\node_modules\sequelize\lib\model.js:1347:29)
[1]     at Model.findOne (C:\Users\Adam Ryvola\Desktop\SHARING PORTAL\node_modules\sequelize\lib\model.js:1519:34)
[1]     at getUserByGoogleId (User.js:40:17)
[1]     at UserRouter.js:27:5
[1]     at Layer.handle [as handle_request] (C:\Users\Adam Ryvola\Desktop\SHARING PORTAL\node_modules\express\lib\router\layer.js:95:5)
[1]     at next (C:\Users\Adam Ryvola\Desktop\SHARING PORTAL\node_modules\express\lib\router\route.js:131:13)
[1]     at Route.dispatch (C:\Users\Adam Ryvola\Desktop\SHARING PORTAL\node_modules\express\lib\router\route.js:112:3)
[1]     at Layer.handle [as handle_request] (C:\Users\Adam Ryvola\Desktop\SHARING PORTAL\node_modules\express\lib\router\layer.js:95:5)
[1]     at C:\Users\Adam Ryvola\Desktop\SHARING PORTAL\node_modules\express\lib\router\index.js:277:22
[1]     at param (C:\Users\Adam Ryvola\Desktop\SHARING PORTAL\node_modules\express\lib\router\index.js:349:14)
[1]     at param (C:\Users\Adam Ryvola\Desktop\SHARING PORTAL\node_modules\express\lib\router\index.js:365:14)
[1]     at Function.process_params (C:\Users\Adam Ryvola\Desktop\SHARING PORTAL\node_modules\express\lib\router\index.js:410:3)
[1]     at next (C:\Users\Adam Ryvola\Desktop\SHARING PORTAL\node_modules\express\lib\router\index.js:271:10)
[1]     at Function.handle (C:\Users\Adam Ryvola\Desktop\SHARING PORTAL\node_modules\express\lib\router\index.js:176:3)
[1]     at router (C:\Users\Adam Ryvola\Desktop\SHARING PORTAL\node_modules\express\lib\router\index.js:46:12)
[1]     at Layer.handle [as handle_request] (C:\Users\Adam Ryvola\Desktop\SHARING PORTAL\node_modules\express\lib\router\layer.js:95:5)
[1]     at trim_prefix (C:\Users\Adam Ryvola\Desktop\SHARING PORTAL\node_modules\express\lib\router\index.js:312:13)
[1]     at C:\Users\Adam Ryvola\Desktop\SHARING PORTAL\node_modules\express\lib\router\index.js:280:7
[1]     at Function.process_params (C:\Users\Adam Ryvola\Desktop\SHARING PORTAL\node_modules\express\lib\router\index.js:330:12)
[1]     at next (C:\Users\Adam Ryvola\Desktop\SHARING PORTAL\node_modules\express\lib\router\index.js:271:10)
[1]     at urlencodedParser (C:\Users\Adam Ryvola\Desktop\SHARING PORTAL\node_modules\body-parser\lib\types\urlencoded.js:91:7)
[1]     at Layer.handle [as handle_request] (C:\Users\Adam Ryvola\Desktop\SHARING PORTAL\node_modules\express\lib\router\layer.js:95:5)
[1]     at trim_prefix (C:\Users\Adam Ryvola\Desktop\SHARING PORTAL\node_modules\express\lib\router\index.js:312:13)
[1]     at C:\Users\Adam Ryvola\Desktop\SHARING PORTAL\node_modules\express\lib\router\index.js:280:7`

__Dialect:__ postgres
__Database version: 9.5
__Sequelize version: 3.24.0

**Comment by janmeier** [comment]
It should be `association: googleAcc`

Model is for when you pass a reference to a model

**Comment by hytromo** [comment]
The last example here: http://docs.sequelizejs.com/manual/tutorial/associations.html#creating-with-associations 
```js
const Categories = Product.hasMany(Tag, {as: 'categories'});

Product.create({
  id: 1,
  title: 'Chair',
  categories: [
    {id: 1, name: 'Alpha'},
    {id: 2, name: 'Beta'}
  ]
}, {
  include: [{
    model: Categories,
    as: 'categories'
  }]
})
```
Passes an association but says `model`.

**Comment by fowlplay** [comment]
> The last example here: http://docs.sequelizejs.com/manual/tutorial/associations.html#creating-with-associations
> 
> ```js
> const Categories = Product.hasMany(Tag, {as: 'categories'});
> 
> Product.create({
>   id: 1,
>   title: 'Chair',
>   categories: [
>     {id: 1, name: 'Alpha'},
>     {id: 2, name: 'Beta'}
>   ]
> }, {
>   include: [{
>     model: Categories,
>     as: 'categories'
>   }]
> })
> ```
> 
> Passes an association but says `model`.

as should be changed to association, not the model.
