### ISSUE TITLE
Cannot find module Terraformer-wkt-parser

### ISSUE THREAD

**Issue by johnmurphy01** [sequelize/sequelize#6456]
## What you are doing?
Trying to run my node server after torching my node_modules folder

## What do you expect to happen?
When I run the node server, I expect node to initialize my SQL Server database and start the server.

## What is actually happening?
As soon as I run my node server, I get the following error:
Error: Cannot find module 'terraformer-wkt-parser'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/johnmurphy1/nucorscheduling/NYS.Scheduling/scheduling-node/node_modules/sequelize/lib/data-types.js:6:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/johnmurphy1/nucorscheduling/NYS.Scheduling/scheduling-node/node_modules/sequelize/lib/utils.js:3:17)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)

__Dialect:__ mssql
__Database version:__ MSSQL 11.0.5343.0
__Sequelize version:__ 3.23.3

**Comment by cbinners** [comment]
It seems that `terraformer-wkt-parser` pushed a new (and broken) version about an hour ago, and  correspondingly broke sequelize. I wonder if we could lock down the dependency to version `1.1.0` instead of `^1.1.0`. This might resolve the issue? I'm not sure who here is responsible for doing this.

**Comment by ltegman** [comment]
The issue was fixed by `terraformer-wkt-parser` in https://github.com/Esri/terraformer-wkt-parser/pull/24 a couple of minutes ago, so it should be published correctly very shortly.

**Comment by devops-scimo** [comment]
I can confirm our builds are working again.  Thanks to those who contributed on this!

**Comment by trriplejay** [comment]
terraformer-wkt-parser@1.1.2 has been published and seems to correct this problem.

**Comment by jgravois** [comment]
sorry about that. :smiling_imp:

**Comment by trriplejay** [comment]
@jgravois thanks for the quick fix!

**Comment by johnmurphy01** [comment]
fixed! thanks all!

**Comment by sushantdhiman** [comment]
``terraformer-wkt-parser@1.1.2`` merged to `master` too https://github.com/sequelize/sequelize/pull/6457
