### ISSUE TITLE
Trying to create new row with many-to-many associations to existing row in database

### ISSUE THREAD

**Issue by suricactus** [sequelize/sequelize#6458]
## What you are doing?
I am trying to create associations to existing rows in a single Sequelize call. In my case I have  

```js
Category.create({
  "parentCategory": [4],
  "name":"Capitals",
  "localeId":1
}, { include: [Category] })
.then(function() {
  // Expect successful creation of Category with parent category with id 1
});
```
OR
```js
Category.create({
  "parentCategory": [ { "id": 4 }],
  "name":"Capitals",
  "localeId":1
}, { include: [Category] })
.then(function() {
  // Expect successful creation of Category with parent category with id 1
});
```

## What do you expect to happen?
Expect successful creation of new Category with name "Capitals" and associate it with another already existing Category with id=4.

## What is actually happening?
In first case Sequelize dies with TypeError, because it expects object.
```
TypeError: key.indexOf is not a function
    at Instance.set (/home/app/api/node_modules/sequelize/lib/instance.js:324:21)
    at initValues (/home/app/api/node_modules/sequelize/lib/instance.js:63:8)
    at Instance (/home/app/api/node_modules/sequelize/lib/instance.js:107:14)
    at new Instance (/home/app/api/node_modules/sequelize/lib/model.js:678:14)
    at Model.build (/home/app/api/node_modules/sequelize/lib/model.js:1756:10)
    at .<anonymous> (/home/app/api/node_modules/sequelize/lib/model.js:1780:17)
    at Array.map (native)
    at Model.bulkBuild (/home/app/api/node_modules/sequelize/lib/model.js:1779:20)
    at Instance._setInclude (/home/app/api/node_modules/sequelize/lib/instance.js:472:81)
    at Instance.set (/home/app/api/node_modules/sequelize/lib/instance.js:317:14)
    at Instance.set (/home/app/api/node_modules/sequelize/lib/instance.js:293:16)
    at initValues (/home/app/api/node_modules/sequelize/lib/instance.js:63:8)
    at Instance (/home/app/api/node_modules/sequelize/lib/instance.js:107:14)
    at new Instance (/home/app/api/node_modules/sequelize/lib/model.js:678:14)
    at Model.build (/home/app/api/node_modules/sequelize/lib/model.js:1756:10)
    at Model.create (/home/app/api/node_modules/sequelize/lib/model.js:1807:15)
    at Object.createGen (/home/app/api/src/lib/koa-rest-sequelize.js:100:34)
    at next (native)
    at onFulfilled (/home/app/api/node_modules/co/index.js:65:19)
    at /home/app/api/node_modules/co/index.js:54:5
    at new wrappedPromise (/home/app/api/node_modules/async-listener/index.js:372:16)
    at co (/home/app/api/node_modules/co/index.js:50:10)
```
In second cas Sequelize tries to create **new** Category with id 1 and validators fail, because the "name" property of Category model is not null but not set for "ParentCategory" object.
```
SequelizeValidationError: notNull Violation: name cannot be null
   at /home/app/api/node_modules/sequelize/lib/instance-validator.js:74:14
   at /home/app/api/node_modules/continuation-local-storage/context.js:76:17
   at tryCatcher (/home/app/api/node_modules/bluebird/js/release/util.js:16:23)
   at Promise._settlePromiseFromHandler (/home/app/api/node_modules/bluebird/js/release/promise.js:504:31)
   at Promise._settlePromise (/home/app/api/node_modules/bluebird/js/release/promise.js:561:18)
   at Promise._settlePromise0 (/home/app/api/node_modules/bluebird/js/release/promise.js:606:10)
   at Promise._settlePromises (/home/app/api/node_modules/bluebird/js/release/promise.js:685:18)
   at Promise._fulfill (/home/app/api/node_modules/bluebird/js/release/promise.js:630:18)
   at PromiseArray._resolve (/home/app/api/node_modules/bluebird/js/release/promise_array.js:125:19)
   at PromiseArray._promiseFulfilled (/home/app/api/node_modules/bluebird/js/release/promise_array.js:143:14)
   at Promise._settlePromise (/home/app/api/node_modules/bluebird/js/release/promise.js:566:26)
   at Promise._settlePromise0 (/home/app/api/node_modules/bluebird/js/release/promise.js:606:10)
   at Promise._settlePromises (/home/app/api/node_modules/bluebird/js/release/promise.js:685:18)
   at Async._drainQueue (/home/app/api/node_modules/bluebird/js/release/async.js:138:16)
   at Async._drainQueues (/home/app/api/node_modules/bluebird/js/release/async.js:148:10)
   at Immediate.Async.drainQueues [as _onImmediate] (/home/app/api/node_modules/bluebird/js/release/async.js:17:14)
   at tryOnImmediate (timers.js:543:15)
   at processImmediate [as _immediateCallback] (timers.js:523:5)
```

__Dialect:__ postgres
__Database version:__ 9.5
__Sequelize version:__ 3.24.0

**Comment by janmeier** [comment]
https://github.com/sequelize/sequelize/issues/5325
