### ISSUE TITLE
Cannot set property 'model variable' of undefined

### ISSUE THREAD

**Issue by TitaneBoy** [sequelize/sequelize#6472]
## What you are doing?
I'm trying to make a request through 4 related tables.

Here is the model definition of table ***group_privilege***:
```
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('group_privilege', {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true
    },
    group_id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      references: {
        model: 'group_user',
        key: 'id'
      }
    },
    privilege_id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      references: {
        model: 'privilege',
        key: 'id'
      }
    }
  }, {
    tableName: 'group_privilege',
    underscored: true,
    freezeTableName: true,
  });
};
```
Here is the model definition of table ***group_user***:

```
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('group_user', {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true
    },
    name: {
      type: DataTypes.TEXT,
      allowNull: true
    },
    description: {
      type: DataTypes.TEXT,
      allowNull: true
    }
  }, {
    tableName: 'group_user',
    underscored: true,
    freezeTableName: true,
  });
};
```

Here is the model definition of table ***privilege***:
```
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('privilege', {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true
    },
    description: {
      type: DataTypes.TEXT,
      allowNull: true
    },
    code: {
      type: DataTypes.TEXT,
      allowNull: false,
      defaultValue: 'N/D'
    }
  }, {
    tableName: 'privilege',
    underscored: true,
    freezeTableName: true,
  });
};
```

And finally, here the model definition of the table ***user***
```
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('user', {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true
    },
    username: {
      type: DataTypes.TEXT,
      allowNull: true,
      unique: true
    },
    password: {
      type: DataTypes.TEXT,
      allowNull: true
    },
    group_id: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: '1',
      references: {
        model: 'group_user',
        key: 'id'
      }
    }
  }, {
    tableName: 'user',
    underscored: true,
    freezeTableName: true,
  });
};
```
Here is my initialization of sequelize:
```
var sequelize = require("sequelize");
var PostgresqlDatabaseUrl = 'postgres://postgres:postgres@localhost:5432/mydatabase';
var Mysequelize= new sequelize(PostgresqlDatabaseUrl, {logging:false, define: {
                               timestamps: false,
                           }});
```

Here is my code
```js
Mysequelize.authenticate().then(function(err){
    if (err){
      return next("Error while authenticating: " + err);
    }
    var user = Mysequelize.import(path.join(process.cwd() + "/models/user.js"));
    var group_user = Mysequelize.import(path.join(process.cwd() + "/models/group_user.js"));
    var privilege = Mysequelize.import(path.join(process.cwd() + "/models/privilege.js"));
    var group_privilege = Mysequelize.import(path.join(process.cwd() + "/models/group_privilege.js"));

    user.belongsTo(group_privilege, {foreignKey:'group_id', targetKey:'group_id'});
    group_privilege.belongsTo(privilege, {foreignKey:'privilege_id', targetKey:"id"});
       //privilege.hasOne(group_privilege, {foreignKey:'privilege_id'});  (<===  tryied to put this too)
    group_privilege.belongsTo(group_user, {foreignKey:'group_id', targetKey:"id"});
       //group_user.hasOne(group_privilege, {foreignKey:'group_id'}); (<===  tryied to put this too)

user_id = 15;    
var conditions = {id: user_id};
var userList = [];

    Mysequelize.sync().then(function(){
       user.findAll({logging:true, attributes:['username'], include:{model:group_privilege, attributes:[], include:[{model:group_user, attributes:['name']}, {model:privilege, attributes:['description']}]} where:conditions}).then(function(users){
           for (var key in users){
              userList.push({username:users[key].dataValues.username,   group_name:users[key].dataValues.group_user.dataValues.name});
           }
           return next(undefined, userList);
       }).catch(function(err){
          var errMsg = "Error while finding users in database: " + err;
          return next(errMsg);
         });
      }).catch(function(err){
         var errMsg = "Error while synchronizing with database to get users: " + err; 
         return next(errMsg);
      });
  }).catch(function(err){
    return next('Unable to connect to the database:' + err);
  });
```

As soon I'm calling ***user.findAll()***, I'm getting the error described below.

For debugging purpose, I've enabled the logging option to see the final request. This is what I got:

```
SELECT "user"."id", "user"."username", "group_privilege.group_user"."id" AS "group_privilege.group_user.id", "group_privilege.group_user"."name" AS "group_privilege.group_user.name", "group_privilege.privilege"."id" AS "group_privilege.privilege.id", "group_privilege.privilege"."description" AS "group_privilege.privilege.description" FROM "user" AS "user" LEFT OUTER JOIN "group_privilege" AS "group_privilege" ON "user"."group_id" = "group_privilege"."group_id" LEFT OUTER JOIN "group_user" AS "group_privilege.group_user" ON "group_privilege"."group_id" = "group_privilege.group_user"."id" LEFT OUTER JOIN "privilege" AS "group_privilege.privilege" ON "group_privilege"."privilege_id" = "group_privilege.privilege"."id" WHERE "user"."id" = 15;
 ```
Which, once executed in the postgres database (with pgAdminIII), gives me the results I'm looking for:

***Columns***
```
id;     username;      group_privilege.group_user.id;      group_privilege.group_user.name;     group_privilege.privilege.id;       group_privilege.privilege.description
```

***Datas***
```
15;        "UserOne";      3;       "group_2";      1;     "Privilege 1"
15;        "UserOne";      3;       "group_2";      5;     "Privilege 2"
15;        "UserOne";      3;       "group_2";      7;     "Privilege 3"
15;        "UserOne";      3;       "group_2";      8;     "Privilege 4"
```

## What do you expect to happen?
A **users** object which contains the data of my request

## What is actually happening?
***TypeError: Cannot set property 'group_user' of undefined***

Here is the callstack one I got the error:
```
"TypeError: Cannot set property 'group_user' of undefined\n    
    at groupJoinData (c:\MyProject\node_modules\sequelize\lib\dialects\abstract\query.js:298:50)\n    
    at AbstractQuery.handleSelectQuery (c:\MyProject\node_modules\sequelize\lib\dialects\abstract\query.js:658:15)\n    
    at c:\MyProject\node_modules\sequelize\lib\dialects\postgres\query.js:202:19\nFrom previous event:\n    
    at Promise.spread (c:\MyProject\node_modules\sequelize\lib\promise.js:21:17)\n    
    at Query.run (c:\MyProject\node_modules\sequelize\lib\dialects\postgres\query.js:103:6)\n    
    at c:\MyProject\node_modules\sequelize\lib\sequelize.js:843:20\n    
    at c:\MyProject\node_modules\retry-as-promised\index.js:38:21\nFrom previous event:\n    
    at retryAsPromised (c:\MyProject\node_modules\retry-as-promised\index.js:27:10)\n    
    at c:\MyProject\node_modules\sequelize\lib\sequelize.js:842:12\nFrom previous event:\n    
    at Promise.then (c:\MyProject\node_modules\sequelize\lib\promise.js:21:17)\n    
    at Object.exports.getUserGroupPrivileges (c:\MyProject\scripts\users.js:215:30)\n    
    at exports.getUserGroupPrivileges (c:\MyProject\scripts\api-demo.js:798:9)\n    
    at Layer.handle [as handle_request] (c:\MyProject\node_modules\express\lib\router\layer.js:95:5)\n    
    at next (c:\MyProject\node_modules\express\lib\router\route.js:131:13)\n    
    at Route.dispatch (c:\MyProject\node_modules\express\lib\router\route.js:112:3)\n    
    at Layer.handle [as handle_request] (c:\MyProject\node_modules\express\lib\router\layer.js:95:5)\n    
    at c:\MyProject\node_modules\express\lib\router\index.js:277:22\n    
    at Function.process_params (c:\MyProject\node_modules\express\lib\router\index.js:330:12)\n    
    at next (c:\MyProject\node_modules\express\lib\router\index.js:271:10)\n    
    at SendStream.error (c:\MyProject\node_modules\serve-static\index.js:121:7)\n    
    at emitOne (events.js:96:13)\n    
    at SendStream.emit (events.js:188:7)\n    
    at SendStream.error (c:\MyProject\node_modules\serve-static\node_modules\send\index.js:275:17)\n    
    at SendStream.onStatError (c:\MyProject\node_modules\serve-static\node_modules\send\index.js:392:12)\n    
    at next (c:\MyProject\node_modules\serve-static\node_modules\send\index.js:683:16)\n    
    at onstat (c:\MyProject\node_modules\serve-static\node_modules\send\index.js:672:14)\n    
    at FSReqWrap.oncomplete (fs.js:123:15)"
```
__Dialect:__ postgres
__Database version:__ 9.4.4
__Sequelize version:__ 3.24.1

Can you help me please ?  Thank you.

PS: I noticed that if I remove an "include" option in the findAll function, the query has no error, but I have of course one missing data information.

**Comment by TitaneBoy** [comment]
Hello everyone.

Any news about this issue ?

Thank you.

**Comment by felixfbecker** [comment]
Instead of `references` with a model string name, could you try using `belongsTo()`?

**Comment by TitaneBoy** [comment]
Hi @felixfbecker . I guess you have noticed that "belongsTo()" calls are already present in my script/code: `user.belongsTo`, and `group_privilege.belongsTo`.

If I understand well, do you suggest me just to remove the "references" key/value in models ?

Thank you.

**Comment by felixfbecker** [comment]
Yes, you don't need it. I would also recommend you to
- setup your association both ways
- don't use `for in` to loop over an array, use `for of` or `forEach()`
- not use `dataValues` directly, access directly or use `get()`

**Comment by TitaneBoy** [comment]
Thank you for your precious advices.

I've done what you suggested me but I have the same issue and the same error message.

**Comment by felixfbecker** [comment]
Can you please post your updated code?

**Comment by TitaneBoy** [comment]
Yes, of course... Here is the code...
The error occurs before the `for (var user_value of users){` call

```
Mysequelize.authenticate().then(function(err){
    if (err){
      return next("Error while authenticating: " + err);
    }
    var user = Mysequelize.import(path.join(process.cwd() + "/models/user.js"));
    var group_user = Mysequelize.import(path.join(process.cwd() + "/models/group_user.js"));
    var privilege = Mysequelize.import(path.join(process.cwd() + "/models/privilege.js"));
    var group_privilege = Mysequelize.import(path.join(process.cwd() + "/models/group_privilege.js"));

    user.belongsTo(group_privilege, {foreignKey:'group_id', targetKey:'group_id'});
    group_privilege.hasMany(user, {foreignKey:'group_id'});
    group_privilege.belongsTo(privilege, {foreignKey:'privilege_id', targetKey:"id"});
    privilege.hasMany(group_privilege, {foreignKey:'privilege_id'});
    group_privilege.belongsTo(group_user, {foreignKey:'group_id', targetKey:"id"});
    group_user.hasMany(group_privilege, {foreignKey:'group_id'});

user_id = 15;    
var conditions = {id: user_id};
var userList = [];

    Mysequelize.sync().then(function(){
       user.findAll({logging:true, attributes:['username'], include:{model:group_privilege, attributes:[], include:[{model:group_user, attributes:['name']}, {model:privilege, attributes:['description']}]} where:conditions}).then(function(users){
           for (var user_value of users){
              userList.push({username:user_value.dataValues.username,   group_name:user_value.dataValues.group_user.dataValues.name});
           }
           return next(undefined, userList);
       }).catch(function(err){
          var errMsg = "Error while finding users in database: " + err;
          return next(errMsg);
         });
      }).catch(function(err){
         var errMsg = "Error while synchronizing with database to get users: " + err; 
         return next(errMsg);
      });
  }).catch(function(err){
    return next('Unable to connect to the database:' + err);
  });
```
Here is the result I got in the console:

```
Executing (default): SELECT "user"."id", "user"."username", "group_privilege.group_user"."id" AS "group_privilege.group_user.id", "group_privilege.group_user"."name" AS "group_privilege.group_user.name", "group_privilege.privilege"."id" AS "group_privilege.privilege.id", "group_privilege.privilege"."description" AS "group_privilege.privilege.description" FROM "user" AS "user" LEFT OUTER JOIN "group_privilege" AS "group_privilege" ON "user"."group_id" = "group_privilege"."group_id" LEFT OUTER JOIN "group_user" AS "group_privilege.group_user" ON "group_privilege"."group_id" = "group_privilege.group_user"."id" LEFT OUTER JOIN "privilege" AS "group_privilege.privilege" ON "group_privilege"."privilege_id" = "group_privilege.privilege"."id";
Error while finding users in database: TypeError: Cannot set property 'group_user' of undefined
```

In another way, can you tell me please where I can find the API of the function "get()" I am supposed to use instead of  `dataValues` (the one you suggested me to use in your previous message) ?

Thank you.

**Comment by felixfbecker** [comment]
> ```js
> Mysequelize.authenticate().then(function(err){
> ```

`then()` doesn't get an error as first argument

> ```js
> privilege.hasMany(group_privilege, {foreignKey:'privilege_id'});
> group_privilege.belongsTo(group_user, {foreignKey:'group_id', targetKey:"id"});
> ```
> 

`foreignKey` must be the same.

> In another way, can you tell me please where I can find the API of the function "get()" I am supposed to use instead of dataValues (the one you suggested me to use in your previous message) ?

API docs, Instance, get(). But you can also just do `user.whatever` instead of `user.dataValues.whatever`.

**Comment by TitaneBoy** [comment]
I am not sure to understand when you are saying:
> foreignKey must be the same.
Can you explain me please ?

foreignKey must be the same as what exactly ?

In `privilege.hasMany(group_privilege, {foreignKey:'privilege_id'});`
We have 2 tables: **privilege** and **group_privilege**

And in ` group_privilege.belongsTo(group_user, {foreignKey:'group_id', targetKey:"id"});`, 
we have 2 other tables: **group_privilege** and **group_user**

So for me, it's normal that the foreignKey of the first line (privilege.hasMany...) is not the same as the one in the second line (group_privilege.belongsTo...)

**Comment by felixfbecker** [comment]
Sorry, it's very late here and the code wasn't very readable. I don't really know a solution. But it seems to me that what you have is actually not a 1:n, but an n:m with a through model. Is that correct? You could simplify your code then.

**Comment by willdawsonme** [comment]
I'm experiencing something similar. When you include the `group_privilege` model, discard all it's attributes, then try and nest the `group_user` model, the error will throw. In my case, I'm trying to query a many-to-many relation `Service - RegionService('channels') - Region` but discard all attributes from the result. When Sequelize tries to attach the through model to it's parent `Region`, which has no attributes in the result, I get a similar error: `Error: Cannot set property 'regionService' of undefined`. Example below.

```
Service.findAll({
    include: [{
        model: Region,
        as: 'channels',
        where: {
            state: 'NSW'
        },
        attributes: [],
        through: {
            attributes: []
        }
    }]
})
```

I'd be happy to include my model definitions, expected outputs etc if that's necessary.

**Comment by felixfbecker** [comment]
I think the issue comes from not including any attributes. Fix would be an if statement somewhere.

**Comment by TitaneBoy** [comment]
Hi @felixfbecker.  I'm trying to understand your suggestion about the fix. You are talking about an "if statement". I'm not sure to understand that...We can add "if" statement in sequelize ? If we can, where can I find the documentation about it ? I've tryid to find it in the docs but without any results.

Thank you.

**Comment by felixfbecker** [comment]
@TitaneBoy No, this clearly is a bug in Sequelize. You can add an if statement to sequelize by doing a PR 😄

**Comment by FoxMcCloudDX** [comment]
Hello! I'm having a similar issue to the one @willdawsonme has. Is there any update on it?

**Comment by felixfbecker** [comment]
@FoxMcCloudDX The workaround is to include the IDs and foreignKeys that are needed for the query explicitely through `attributes`

**Comment by FoxMcCloudDX** [comment]
Hello @felixfbecker.First of all, Thank you for answering! Let me pick up @willdawsonme example:

```
Service.findAll({
    include: [{
        model: Region,
        as: 'channels',
        where: {
            state: 'NSW'
        },
        attributes: [],
        through: {
            attributes: []
        }
    }]
})
```

Assuming that the relation between `Service` and `Region` is a many-to-many one, the idea of this query is to get all the services where `region.state = 'NSW'` but not include the `Region` data in each `Service` result. For this purpose, the empty `attributes` field works on most types of relations(without the need of the `through` clause) but on many-to-many relations we get the aforementioned error because Sequelize tries to set the `RegionService` property into a non-existing `Region` property of a `Service`.

Assuming that I want the `Service` results without the `Region` data inside, your workaround suggestion does not quite fit that case because it will still include some region properties in the result correct? Or am i not understanding what you suggested?

**Comment by felixfbecker** [comment]
@FoxMcCloudDX I would try to fiddle around with `attributes` by trying to add the ID and foreign key attributes.

**Comment by FoxMcCloudDX** [comment]
@felixfbecker I tried to add them and the closest i got was with the following query:

```
Service.findAll({
    include: [{
        model: Region,
        as: 'channels',
        where: {
            state: 'NSW'
        },
        attributes: [],
        through: {
            attributes: []
        }
    }]
})
```

But that still gets me the `Regions` in each 'Service' even if its just with the `id` property. The idea is not to show the Regions of each Service in the result.

**Comment by marol-hadidjaja** [comment]
is this issue fixed? because I still got this error, eventhough I use version `3.30.1`
