### ISSUE TITLE
Has any way intergration by webpack

### ISSUE THREAD

**Issue by keyiis** [sequelize/sequelize#6542]
I want use webpack to package my app,
somebody may ask:why use webpack to package third modules?
because sequelize has many dependency,i won't manual copy its to publishing directory.
in my code already define "import Sequelize = require("sequelize");",but when run webpack,i get error:
```
  ERROR in d:\work\nodejs\angular\angular2-electron\output\electron\dist\myTestApp-win32-x64\resources\app\node_modules\.npminstall\node_modules\sequelize\node_modules\terraformer-wkt-parser\node_modules\terraformer\typings\globals\geojson\index.d.ts
    (127,9): error TS2300: Duplicate identifier 'properties'.

    ERROR in d:\work\nodejs\angular\angular2-electron\output\electron\dist\myTestApp-win32-x64\resources\app\node_modules\.npminstall\node_modules\sequelize\node_modules\terraformer-wkt-parser\node_modules\terraformer\terraformer.d.ts
    (39,9): error TS7010: 'forEach', which lacks return-type annotation, implicitly has an 'any' return type.

    ERROR in d:\work\nodejs\angular\angular2-electron\output\electron\dist\myTestApp-win32-x64\resources\app\node_modules\.npminstall\node_modules\sequelize\node_modules\terraformer-wkt-parser\node_modules\terraformer\terraformer.d.ts
    (62,9): error TS7010: 'forEach', which lacks return-type annotation, implicitly has an 'any' return type.

    ERROR in d:\work\nodejs\angular\angular2-electron\output\electron\dist\myTestApp-win32-x64\resources\app\node_modules\.npminstall\node_modules\sequelize\node_modules\terraformer-wkt-parser\node_modules\terraformer\terraformer.d.ts
    (91,9): error TS7010: 'forEach', which lacks return-type annotation, implicitly has an 'any' return type.

    ERROR in d:\work\nodejs\angular\angular2-electron\output\electron\dist\myTestApp-win32-x64\resources\app\node_modules\.npminstall\node_modules\sequelize\node_modules\terraformer-wkt-parser\node_modules\terraformer\terraformer.d.ts
    (108,9): error TS7010: 'forEach', which lacks return-type annotation, implicitly has an 'any' return type.

    ERROR in d:\work\nodejs\angular\angular2-electron\output\electron\dist\myTestApp-win32-x64\resources\app\node_modules\.npminstall\node_modules\sequelize\node_modules\terraformer-wkt-parser\node_modules\terraformer\terraformer.d.ts
    (118,9): error TS7010: 'forEach', which lacks return-type annotation, implicitly has an 'any' return type.

    ERROR in d:\work\nodejs\angular\angular2-electron\output\electron\dist\myTestApp-win32-x64\resources\app\node_modules\.npminstall\node_modules\sequelize\node_modules\terraformer-wkt-parser\node_modules\terraformer\terraformer.d.ts
    (128,9): error TS7010: 'steps', which lacks return-type annotation, implicitly has an 'any' return type.

    ERROR in d:\work\nodejs\angular\angular2-electron\output\electron\dist\myTestApp-win32-x64\resources\app\node_modules\.npminstall\node_modules\sequelize\node_modules\terraformer-wkt-parser\node_modules\terraformer\terraformer.d.ts
    (129,9): error TS7010: 'radius', which lacks return-type annotation, implicitly has an 'any' return type.

    ERROR in d:\work\nodejs\angular\angular2-electron\output\electron\dist\myTestApp-win32-x64\resources\app\node_modules\.npminstall\node_modules\sequelize\node_modules\terraformer-wkt-parser\node_modules\terraformer\terraformer.d.ts
    (130,9): error TS7010: 'center', which lacks return-type annotation, implicitly has an 'any' return type.
```

**Comment by felixfbecker** [comment]
- These are all TypeScript related errors, Sequelize has nothing to do with TypeScript
- They come from the typings in the terraformer-wkt-parser typings, which apparently do not use `noImplicitAny`, but you do.

**Comment by keyiis** [comment]
@felixfbecker thks reply!this is my miss.i should exclude "output",i used sqlite3,but below error still:
```
ERROR in ./~/.npminstall/sequelize/3.23.4/sequelize/lib/dialects/postgres/hstore.js
Module not found: Error: Can't resolve 'pg-hstore' in 'd:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\sequelize\3.23.4\sequelize\lib\dialects\postgres'
resolve 'pg-hstore' in 'd:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\sequelize\3.23.4\sequelize\lib\dialects\postgres'
  Parsed request is a module
  using description file: d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\sequelize\3.23.4\sequelize\package.json (relative path: ./lib/dialects/postgres)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\sequelize\3.23.4\sequelize\package.json (relative path: ./lib/dialects/postgres)
    resolve as module
      d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\sequelize\3.23.4\sequelize\lib\dialects\postgres\node_modules doesn't exist or is not a directory
      d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\sequelize\3.23.4\sequelize\lib\dialects\node_modules doesn't exist or is not a directory
```

**Comment by keyiis** [comment]
@felixfbecker  with some warning:
```
WARNING in ./~/.npminstall/sequelize/3.23.4/sequelize/lib/dialects/postgres/connection-manager.js
20:14 Critical dependency: the request of a dependency is an expression
CriticalDependencyWarning: Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\webpack\2.1.0-beta.15\webpack\lib\dependencies\CommonJsRequireContextDependency.js:22:4)
    at d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\webpack\2.1.0-beta.15\webpack\lib\Compilation.js:594:21
    at Array.forEach (native)
    at d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\webpack\2.1.0-beta.15\webpack\lib\Compilation.js:593:22
    at Array.forEach (native)
    at Compilation.reportDependencyWarnings (d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\webpack\2.1.0-beta.15\webpack\lib\Compilation.js:592:9)
    at Compilation.<anonymous> (d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\webpack\2.1.0-beta.15\webpack\lib\Compilation.js:483:8)
    at Array.forEach (native)
    at Compilation.seal (d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\webpack\2.1.0-beta.15\webpack\lib\Compilation.js:482:15)
    at Compiler.<anonymous> (d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\webpack\2.1.0-beta.15\webpack\lib\Compiler.js:431:15)
    at d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\tapable\0.2.4\tapable\lib\Tapable.js:152:11
    at Compilation.<anonymous> (d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\webpack\2.1.0-beta.15\webpack\lib\Compilation.js:430:10)
    at d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\webpack\2.1.0-beta.15\webpack\lib\Compilation.js:405:12
    at d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\webpack\2.1.0-beta.15\webpack\lib\Compilation.js:320:10
    at d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\async\1.5.2\async\lib\async.js:52:16
    at done (d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\async\1.5.2\async\lib\async.js:246:17)
    at d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\async\1.5.2\async\lib\async.js:44:16
    at d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\webpack\2.1.0-beta.15\webpack\lib\Compilation.js:320:10
    at d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\async\1.5.2\async\lib\async.js:52:16
    at done (d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\async\1.5.2\async\lib\async.js:246:17)
    at d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\async\1.5.2\async\lib\async.js:44:16
    at d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\webpack\2.1.0-beta.15\webpack\lib\Compilation.js:320:10
    at d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\async\1.5.2\async\lib\async.js:52:16
    at done (d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\async\1.5.2\async\lib\async.js:246:17)
    at d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\async\1.5.2\async\lib\async.js:44:16
    at d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\webpack\2.1.0-beta.15\webpack\lib\Compilation.js:320:10
    at d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\async\1.5.2\async\lib\async.js:52:16
    at done (d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\async\1.5.2\async\lib\async.js:246:17)
    at d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\async\1.5.2\async\lib\async.js:44:16
    at d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\webpack\2.1.0-beta.15\webpack\lib\Compilation.js:320:10

WARNING in ./~/.npminstall/sequelize/3.23.4/sequelize/lib/dialects/sqlite/connection-manager.js
22:15 Critical dependency: the request of a dependency is an expression
CriticalDependencyWarning: Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\webpack\2.1.0-beta.15\webpack\lib\dependencies\CommonJsRequireContextDependency.js:22:4)
    at d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\webpack\2.1.0-beta.15\webpack\lib\Compilation.js:594:21
    at Array.forEach (native)
    at d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\webpack\2.1.0-beta.15\webpack\lib\Compilation.js:593:22
    at Array.forEach (native)
    at Compilation.reportDependencyWarnings (d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\webpack\2.1.0-beta.15\webpack\lib\Compilation.js:592:9)
    at Compilation.<anonymous> (d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\webpack\2.1.0-beta.15\webpack\lib\Compilation.js:483:8)
    at Array.forEach (native)
    at Compilation.seal (d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\webpack\2.1.0-beta.15\webpack\lib\Compilation.js:482:15)
    at Compiler.<anonymous> (d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\webpack\2.1.0-beta.15\webpack\lib\Compiler.js:431:15)
    at d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\tapable\0.2.4\tapable\lib\Tapable.js:152:11
    at Compilation.<anonymous> (d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\webpack\2.1.0-beta.15\webpack\lib\Compilation.js:430:10)
    at d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\webpack\2.1.0-beta.15\webpack\lib\Compilation.js:405:12
    at d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\webpack\2.1.0-beta.15\webpack\lib\Compilation.js:320:10
    at d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\async\1.5.2\async\lib\async.js:52:16
    at done (d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\async\1.5.2\async\lib\async.js:246:17)
    at d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\async\1.5.2\async\lib\async.js:44:16
    at d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\webpack\2.1.0-beta.15\webpack\lib\Compilation.js:320:10
    at d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\async\1.5.2\async\lib\async.js:52:16
    at done (d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\async\1.5.2\async\lib\async.js:246:17)
    at d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\async\1.5.2\async\lib\async.js:44:16
    at d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\webpack\2.1.0-beta.15\webpack\lib\Compilation.js:320:10
    at d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\async\1.5.2\async\lib\async.js:52:16
    at done (d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\async\1.5.2\async\lib\async.js:246:17)
    at d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\async\1.5.2\async\lib\async.js:44:16
    at d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\webpack\2.1.0-beta.15\webpack\lib\Compilation.js:320:10
    at d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\async\1.5.2\async\lib\async.js:52:16
    at done (d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\async\1.5.2\async\lib\async.js:246:17)
    at d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\async\1.5.2\async\lib\async.js:44:16
    at d:\work\nodejs\angular\angular2-electron\node_modules\.npminstall\webpack\2.1.0-beta.15\webpack\lib\Compilation.js:320:10
```

**Comment by keyiis** [comment]
@felixfbecker if i set sequelize as externals in webpack,all work fine,as below:
```
 externals: {
    "sequelize": "require('sequelize')"
}
```
so,webpack can't package sequelize?

**Comment by felixfbecker** [comment]
I don't know. Sequelize loads dialects lazily, maybe that's the problem. I don't know the fix though because we will not add all dialects as direct dependencies.
