### ISSUE TITLE
how is $in operator supposed to work?

### ISSUE THREAD

**Issue by manast** [sequelize/sequelize#6559]
I have a super simple case where I cannot make $in operator work, not sure if I am doing something wrong or if it is a bug in sequelize:

```
var User = sequelize.define('user', {
    username: Sequelize.STRING,
    emails: Sequelize.ARRAY(Sequelize.STRING)
  });
```

Trying to do a findOrCreate fails with an error:
```
var defaultUser = {
  username: 'default',
  emails: ['default@example.com']
}

User.findOrCreate({
  where: {
    emails: {$in: defaultUser.emails}
  },
  defaults: defaultUser
});
```

Error:
```
Unhandled rejection SequelizeDatabaseError: malformed array literal: "default@example.com"
    at Query.formatError (/backend/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)
    at null.<anonymous> (/backend/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
...
```

**Comment by mickhansen** [comment]
`$in` maps to 'IN` which is not supported by arrays, you want to use `$overlaps` or `$contains`
