### ISSUE TITLE
Using Savepoints in MSSQL fails because identifier is too long

### ISSUE THREAD

**Issue by lumaxis** [sequelize/sequelize#6573]
## What you are doing?

I'm trying to use transactions on MSSQL with a longer running transaction.

```js
'use strict';

const User = sequelize.define('User', {
  id: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV4,
    allowNull: false,
    primaryKey: true,
    validate: { isUUID: 4 }
  },
  name: {
    type: DataTypes.STRING,
    allowNull: false,
    validate: { notEmpty: true }
  },
  created_at: { type: DataTypes.DATE },
  updated_at: { type: DataTypes.DATE }
},
{
  timestamps: true,
  createdAt: "created_at",
  updatedAt: "updated_at",
});

return User.create({ name: 'username' })
.then(function(user) {
  return db.sequelize.transaction(function (transaction) {
    return db.User.findOne({ where: { name: 'username' }, transaction: transaction })
    .then((user) => {
      return user.update({ name: 'bar' }, { transaction: transaction })
      .then((updatedUser) => {
        return db.User.findOrCreate({ where: { name: 'bar' }, defaults: { name: 'beep' }, transaction: transaction })
        .then(function (user) {
          user.destroy({ transaction: transaction });
        })
      })
    });
  });
});
```

## What do you expect to happen?

Transaction works and goes through with no problem.

## What is actually happening?

The query fails when trying to save the Savepoint because the name generated by Sequelize is longer than the [allowed 32 characters](https://msdn.microsoft.com/en-us/library/ms188378.aspx):
>savepoint_name
>Is the name assigned to the savepoint. Savepoint names must conform to the rules for identifiers, but are limited to 32 characters. transaction_name is always case sensitive, even when the instance of SQL Server is not case sensitive.

SQL Output:
```sql
Executing (default): INSERT INTO [Users] ([id],[name],[created_at],[updated_at]) OUTPUT INSERTED.* VALUES (N'b2d16b4d-e1cf-499b-97a7-f666569d2025',N'username',N'2016-09-08 21:08:39.000',N'2016-09-08 21:08:39.000');
Executing (default): BEGIN TRANSACTION;
Executing (default): SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (default): SELECT [id], [name], [created_at], [updated_at] FROM [Users] AS [User] WHERE [User].[name] = N'username' ORDER BY [id] OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY;
Executing (default): UPDATE [Users] SET [name]=N'bar',[updated_at]=N'2016-09-08 21:08:40.000' OUTPUT INSERTED.* WHERE [id] = N'07fd5fd6-0d2c-4315-b443-15a542f0c5c4'
Executing (default): SAVE TRANSACTION [5caa7121-18d9-4a26-b6ba-b3aadafed3e7-savepoint-1];
Executing (default): ROLLBACK TRANSACTION [5caa7121-18d9-4a26-b6ba-b3aadafed3e7-savepoint-1];
Executing (default): ROLLBACK TRANSACTION;
```
Stack trace:
```
Unhandled rejection SequelizeDatabaseError: The identifier that starts with '5caa7121-18d9-4a26-b6ba-b3aadafed3e7-savepoint-1' is too long. Maximum length is 32.
    at Query.formatError (/Users/lukas/Work/Sequelize-Demo/node_modules/sequelize/lib/dialects/mssql/query.js:250:10)
    at Request.userCallback (/Users/lukas/Work/Sequelize-Demo/node_modules/sequelize/lib/dialects/mssql/query.js:82:25)
    at Request.callback (/Users/lukas/Work/Sequelize-Demo/node_modules/tedious/lib/request.js:33:27)
    at Connection.message (/Users/lukas/Work/Sequelize-Demo/node_modules/tedious/lib/connection.js:1179:27)
    at Connection.dispatchEvent (/Users/lukas/Work/Sequelize-Demo/node_modules/tedious/lib/connection.js:519:45)
    at MessageIO.<anonymous> (/Users/lukas/Work/Sequelize-Demo/node_modules/tedious/lib/connection.js:439:23)
    at emitNone (events.js:86:13)
    at MessageIO.emit (events.js:185:7)
    at ReadablePacketStream.<anonymous> (/Users/lukas/Work/Sequelize-Demo/node_modules/tedious/lib/message-io.js:92:15)
    at emitOne (events.js:96:13)
    at ReadablePacketStream.emit (events.js:188:7)
    at readableAddChunk (/Users/lukas/Work/Sequelize-Demo/node_modules/tedious/node_modules/readable-stream/lib/_stream_readable.js:213:18)
```

__Dialect:__ mssql
__Database version:__ 12.0.2000.8
__Sequelize version:__ 3.24.2

**Comment by janmeier** [comment]
https://github.com/sequelize/sequelize/issues/3950
