### ISSUE TITLE
[TypeError: Cannot read property 'getTableName' of undefined] Nested include doesn't work on build/create?

### ISSUE THREAD

**Issue by wzup** [sequelize/sequelize#6585]
I get this error:
```
  tableNames[include.model.getTableName()] = true;
                          ^
TypeError: Cannot read property 'getTableName' of undefined
```

The code.
Models and associations:
```
let Company = this.sequelize.define('Company', {/* attributes */})
let Department  = this.sequelize.define('Department', {/* attributes */});
let DepartmentOffice = this.sequelize.define('DepartmentOffice', {/* attributes */});

Company.belongsToMany(Department, {through: 'CompanyDepartment'});
Department.belongsToMany(Company, {through: 'CompanyDepartment'});
Department.hasMany(DepartmentOffice);
```

Tables:
```
Company

    id  name
------  ------
     1  Foo


Department

    id  name 
------  ------
     1  Dep1
     2  Dep2
     3  Dep3


CompanyDepartment

    id  CompanyId    DepartmentId
------  ----------  --------------
     1        1       1
     2        1       2
     3        1       3


DepartmentOffice

    id   DepartmentId    name
------   -------------   ------
    1       1            "Office1"
    2       1            "Office2"
    3       1            "Office3"
    4       1            "Office4"
```

Insert.
`DepartmentOffice` array is nested for `Department` model.
Sequelize works correctly only for the first include `module: Department`. That is if I do not pass `Company` the second include `include: [DepartmentOffice]`

And throws an error if I pass `Company` the second nested `include: [DepartmentOffice]`.
```
let aDepartment = [
    {
        name: 'Dep1',
 
        // For some reason Sequelize doesn't see this nested array and throws error. Why?
        DepartmentOffice: [{
            name: 'Office1',
            name: 'Office2',
            name: 'Office3',
            name: 'Office4'
        }]
    },
    { name: 'Dep2', DepartmentOffice: [] },
    { name: 'Dep3', DepartmentOffice: [] }
]

let company = Company.build({
    name: 'Foo',
    Department: aDepartment
}, {
    include: [{
        module: Department,
        include: [DepartmentOffice] // Error. Sequelize doesn't see this nested array that belongs to Department
    }]
})
```

Why the error is throw? Doesn't Sequelize support such a build/create? [Here ](http://sequelize.readthedocs.io/en/v3/docs/models-usage/#nested-eager-loading)it is written it should.

Full error:
```
C:\Users\user\node\app\node_modules\sequelize\lib\model.js:505
  tableNames[include.model.getTableName()] = true;
                          ^

TypeError: Cannot read property 'getTableName' of undefined
    at validateIncludedElement (C:\Users\user\node\app\node_modules\sequelize\lib\model.js:505:27)
    at C:\Users\user\node\app\node_modules\sequelize\lib\model.js:432:29
    at Array.map (native)
    at validateIncludedElements (C:\Users\user\node\app\node_modules\sequelize\lib\model.js:428:37)
    at Model.build (C:\Users\user\node\app\node_modules\sequelize\lib\model.js:1789:32)
    at Object.<anonymous> (C:\Users\user\node\app\db\drafts\bulkCreate_w_associations.js:44:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
```

**Comment by felixfbecker** [comment]
Could you try `include: [{model: DepartmentOffice}]`?

**Comment by wzup** [comment]
No, it doesn't help.

**Comment by felixfbecker** [comment]
Found the error, you do `module: Department`, not `model: Department`

**Comment by wzup** [comment]
Yes! I have just noticed it too. Thanks.

It works now, but it doesn't populate `DepartmentOffice` table. Only `Company`, `Department` and `CompanyDepartment` are populated.

**Comment by felixfbecker** [comment]
> When using set with associations you need to make sure the property key matches the alias of the association 

For n:m relations, the inferred alias is a plural, so it should be `DepartmentOffices`.

**Comment by wzup** [comment]
Who said that problematic association is `n:m`? 
It is `1:m` - `Department.hasMany(DepartmentOffice)`.

And it doesn't matter if I make it plural for the nested include. It is not included into built instance.
```
let aDepartments = [
    {
        name: 'Dep1',
        // Doesn't matter if I make it plural here. It is ignored
        DepartmentOffice(S): [{
            name: 'Office1',
        }]
    },
    { name: 'Dep2', DepartmentOffice(S): [] }, // plural
    { name: 'Dep3', DepartmentOffice(S): [] } // plural
]


let company = Company.build({
    name: 'Foo',
    // I agree, it must be plural here. 
    // And it is the only include layer that works correctly. The plural rule doesn't apply to the second include
    Department(S): aDepartments
}, {
    include: [{
        module: Department,
        include: [ { model: DepartmentOffice } ] // This include is ignored
    }]
})

// No DepartmentOffice(S) in result:
console.log( company.get({palin: true}).DepartmentOffices[0].get({palin: true}) );
 { id: null,
  name: 'Dep1' } 

// And the result has to be:
{ id: null,
  name:  'Dep1',
  DepartmentOffice(S): [ Object, Object, ... ] // <== it is missing
}
```

So is it really so that Sequelize doesn't support nested includes on build/save? 

I want to know, because I've spent a day for this issue now and want to know whether I should manually make bulk inserts because the operation is not supported.

**Comment by wzup** [comment]
Ok, false alarm. 
**The operation IS supported**.

I found the cause. And it was indeed **about plural naming**.

My real model's name is `WCLF`. The array for bulk insert looks like this:
```
let aWCs = [{
    name: 'wc1',

    // I pluralized it simply by adding "S"
    WCLFs: [
        {name: 'wclf1'},
        {name: 'wclf2'}
    ],
  }, { }, { }, ... 
}]
```

And this is what actually Sequelize transforms the name to :)

![bulkcreate_w_associations js - google chrome 2016-09-11 14 04 30](https://cloud.githubusercontent.com/assets/3880497/18415558/11e8129c-7829-11e6-9cf9-7d9af0eb47a9.png)
