### ISSUE TITLE
TypeError - Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by bryan** [sequelize/sequelize#6602]
## What you are doing?

I'm running Red Hat Enterprise Linux Server 7.2 (Maipo) and can't seem to get my models to sync. Strangely, it used to sync up before, but after deleting the models (and also the cascaded objects), I can't seem to get sync working anymore. It works locally on my OS X using the exact same code.

Edit: **It stopped working locally after I cleared my npm cache and reinstalled all my node modules.**

One of my models looks like this, with its syntax correct - verified and checked: 

``` js
var Pizza = sequelize.define('pizza', {
    translated:     Sequelize.JSON,
    related:        Sequelize.ARRAY(Sequelize.STRING),
    native:         Sequelize.STRING,
    stripped:       Sequelize.STRING
});
```
## What do you expect to happen?

My database should sync the new models up.
## What is actually happening?

I keep getting this error (n number of times the amount I call sync() on my models) and the error message doesn't really help me resolve or debug. 

```
Unhandled rejection TypeError: Cannot read property 'on' of undefined
    at /home/path/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:158:9
    at Promise._execute (/home/path/node_modules/bluebird/js/release/debuggability.js:299:9)
    at Promise._resolveFromExecutor (/home/path/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/home/path/node_modules/bluebird/js/release/promise.js:77:14)
    at /home/path/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:155:12
    at PassThroughHandlerContext.finallyHandler (/home/path/node_modules/bluebird/js/release/finally.js:56:23)
    at PassThroughHandlerContext.tryCatcher (/home/path/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/path/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/path/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/path/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/path/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/path/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/path/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/home/path/node_modules/bluebird/js/release/async.js:17:14)
    at ZoneDelegate.invokeTask (/home/path/node_modules/zone.js/dist/zone-node.js:225:37)
    at Zone.runTask (/home/path/node_modules/zone.js/dist/zone-node.js:125:47)
```

What is `on` referring to and how can I resolve this problem? Bug?

**Dialect:** postgres
**Database version:** 9.2.15
**Sequelize version:** 3.24.3

**Comment by janmeier** [comment]
Hmm, very weird - That would seem to suggest we have problems attaching a handler to  `connection.query`

Which version of pg are you using? Native or js version?

**Comment by bryan** [comment]
@janmeier pg : "^6.1.0" through npm

**Comment by janmeier** [comment]
The error is [here](https://github.com/sequelize/sequelize/blob/v3/lib/dialects/postgres/connection-manager.js#L158) where we attach a handler - Attaching the error handler is fine, but the row handler fails - Seems something broke chaining of eventhandlers ...

**Comment by bryan** [comment]
I'm not sure why it's working locally but refuses to work on the server. Befuddles me. If you need anything to help fix it, let me know, I can post some code or logs.

**Comment by janmeier** [comment]
Must be a discrepancy between versions then, either in a package, or your node version

**Comment by bryan** [comment]
Node version on both are v6.2.2 and packages are both the same since I'm just cloning one straight from GitHub.

**Comment by bryan** [comment]
@janmeier It has something to do with my node_modules / npm install. When using an old version of my node_modules that I had, the error doesn't come up. But upon deleting that old node_modules and then npm installing, the error comes up. When I diff check both the folders, they're identical. Might need to search deeper in diffing both folders since I used OS X built in `diff -rq` - will test WinMerge tomorrow and will report back.

**Comment by jvbianchi** [comment]
it might be related with https://github.com/angular/zone.js/issues/448 and https://github.com/angular/universal-starter/issues/164

**Comment by davidthor** [comment]
@jvbianchi: thanks for diving into that. Downgraded to that version and the issue is resolved. Looks like we'll have to watch that zone.js issue you cited for an update.

**Comment by JiaLiPassion** [comment]
zone.js has fixed the issue, you can try the newest zone.js.
