### ISSUE TITLE
migration and renameColumn: "TypeError" if column doesn't exist

### ISSUE THREAD

**Issue by lludol** [sequelize/sequelize#6606]
## What you are doing?

I am using "umzug" to handle mysql migrations.
I am working on the API with others developpers which are working on web and mobile applications. They need to run the API in local, that's why I have made migrations script to edit automatically their database.

For example, if I want to rename a column I will use this code:

``` js
module.exports = {
    up: function (migration, DataTypes) {
        return migration.renameColumn('myTable', 'oldName', 'newName').then(() => {
            return Promise.resolve();
        }).catch((error) => {
            console.log(error);
            return Promise.reject(error);
        });
    },

    down: function (migration, DataTypes) {
        return migration.renameColumn('myTable', 'newName', 'oldName').then(() => {
            return Promise.resolve();
        }).catch((error) => {
            console.log(error);
            return Promise.reject(error);
        });
    }
};
```
## What do you expect to happen?

I want the code works in two situations:
- when the column has already been modified
- when the column need to be modified
## What is actually happening?

When the column doesn't exist (for example if we have already modified the name or if we start from a new clean database), there is an error:

``` js
TypeError: Cannot read property 'toString' of undefined
    at Object.attributeToSQL (/myProject/node_modules/sequelize/lib/dialects/mysql/query-generator.js:240:34)
    at Object.attributesToSQL (/myProject/node_modules/sequelize/lib/dialects/mysql/query-generator.js:306:45)
    at QueryInterface.<anonymous> (/myProject/node_modules/sequelize/lib/query-interface.js:425:29)
    at ConnectionManager.tryCatcher (/myProject/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.module.exports.Promise._settlePromiseFromHandler (/myProject/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise.module.exports.Promise._settlePromise (/myProject/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise.module.exports.Promise._settlePromise0 (/myProject/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise.module.exports.Promise._settlePromises (/myProject/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/myProject/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/myProject/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.e.Async.drainQueues (/myProject/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

I think "renameColumn" must return a real SequelizeError to say "the column doesn't exist".

**Dialect:** mysql (percona)
**Database version:** 3.23.4
**Sequelize version:** 5.5.48-37.8 - Percona Server (GPL), Release 37.8, Revision c8ae1b6

**Comment by felixfbecker** [comment]
Just a side note, you don't need to return promises in promise handlers, you can just `return` a value or `throw` an error.

**Comment by jukkah** [comment]
> I think "renameColumn" must return a real SequelizeError to say "the column doesn't exist".

:+1:

**Comment by Noiwex** [comment]
Switch to bookshelf or knex
