### ISSUE TITLE
 SQLITE_CONSTRAINT: FOREIGN KEY constraint failed

### ISSUE THREAD

**Issue by keyiis** [sequelize/sequelize#6620]
When i use sequelize+sqlite3,below sql can manual execute, but still get error,why?
```sql
Executing (default): INSERT INTO `kpos_cat` (`id`,`fname`,`fdesc`,`created_at`,`updated_at`,`fparent`) VALUES (NULL,'ssss','ssss','2016-09-22 09:41:30.965 +00:00','2016-09-22 09:41:30.965 +00:00','');

Unhandled rejection SequelizeForeignKeyConstraintError: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed
    at Query.formatError (D:\work\nodejs\angular\angular2-electron\output\electron\build\node_modules\sequelize\lib\dialects\sqlite\query.js:296:16)
    at Statement.afterExecute (D:\work\nodejs\angular\angular2-electron\output\electron\build\node_modules\sequelize\lib\dialects\sqlite\query.js:112:29)
    at Statement.replacement (D:\work\nodejs\angular\angular2-electron\output\electron\build\node_modules\sqlite3\lib\trace.js:20:31)
```
**model define**
```js
this.Cat = sequelize.define('cat', {
    name: { type: Sequelize.STRING, allowNull: false, field: 'fname' },
    pic: {
        type: Sequelize.STRING, field: 'fpic',
        set: function (v: string[] | string) {
            let _pic: string;
            if (v instanceof Array) _pic = (<[]>v).join();
            if (typeof (v) == "string") _pic = <string>v;
            this.setDataValue('fpic', _pic);
        },
        get: function () {
            var pics: string = this.getDataValue('fpic');
            return pics ? pics.split(',') : [];
        }
    },
    desc: { type: Sequelize.TEXT, field: 'fdesc' }
});
this.Cat.belongsTo(this.Cat, {
            foreignKey: 'fparent',
            onDelete: 'cascade',
            constraints: false
        });
this.Cat.belongsTo(this.User,{foreignKey: 'foperator',constraints: false});
```
**sequelize generate sql**
```sql
CREATE TABLE `kpos_cat` (
`id` INTEGER PRIMARY KEY AUTOINCREMENT,
 `fname` VARCHAR(255) NOT NULL,
 `fpic` VARCHAR(255), 
`fdesc` TEXT,
 `created_at` DATETIME NOT NULL, 
`updated_at` DATETIME NOT NULL, 
`fparent` INTEGER REFERENCES `kpos_cat` (`id`) ON DELETE CASCADE, 
`foperator` INTEGER
);
```

**Comment by felixfbecker** [comment]
You only posted model definition and generated SQL, not your model usage

**Comment by keyiis** [comment]
@felixfbecker It's my mistake,already solves,thks reply!
