### ISSUE TITLE
attributes is not working with findAll where group and having is used.

### ISSUE THREAD

**Issue by billxinli** [sequelize/sequelize#6658]
## What you are doing?
I am trying to get this query, which gives me all duplicated tags where it appears more than once.
```
SELECT name
FROM tags
GROUP BY name
HAVING count(name) > 1;
```

```js
var db = require('./../api/models')
var Tag = db.tag
var sequelize = db.sequelize

Tag.findAll({
  attributes: {include: ['name']},
  group: ['name'],
  having: ['count(name) > 1']
}).then(function (tags) {
  console.log(tags)
})

```

## What do you expect to happen?
I am expecting the above SQL to be executed. And get

## What is actually happening?
Seeing the following in the console:
```
{"name":"sequelize","hostname":"snip","pid":37755,"level":30,"msg":"Executing (default): SELECT \"id\", \"name\", \"createdAt\", \"updatedAt\", \"name\" FROM \"tags\" AS \"tag\" GROUP BY \"name\" HAVING count(name) > 0;","time":"2016-10-01T17:33:50.374Z","v":0}
Unhandled rejection SequelizeDatabaseError: ERROR:  column "tag.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT "id", "name", "createdAt", "updatedAt", "name" FROM "...
               ^

    at Query.formatError (/path/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)
    at null.<anonymous> (/path/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
    at emit (events.js:95:17)
    at NativeQuery.handleError (/path/node_modules/pg/lib/native/query.js:41:10)
    at after (/path/node_modules/pg/lib/native/query.js:59:19)
    at onError (/path/node_modules/pg-native/index.js:160:5)
    at g (events.js:180:16)
    at emit (events.js:117:20)
    at Client._readError (/path/node_modules/pg-native/index.js:81:8)
    at Client._read (/path/node_modules/pg-native/index.js:121:19)
    at PQ.emit (events.js:92:17)
```

__Dialect:__ postgres 
__Database version:__ 9.3
__Sequelize version:__ 
```
    "sequelize": "^3.14.2",
    "sequelize-cli": "^1.7.4",
```

**Comment by janmeier** [comment]
`attributes.include` means - select all the attributes on the model, + these ones - That's why you are seeing name twice as well http://docs.sequelizejs.com/en/v3/api/model/#findalloptions-promisearrayinstance

`attributes: ['name']` does what you want
