### ISSUE TITLE
 info: SequelizeDatabaseError: relation "public.ProyectUsers" does not exist

### ISSUE THREAD

**Issue by fedevela** [sequelize/sequelize#6661]
This just bit me on the butt in a very strange way. 

https://github.com/sequelize/sequelize/issues/6131

WHAT AM I DOING?

I have a working version of sequelize on postgresql in my local ubuntu (first 14.04 now 16.04), postgresql ( 9.5.4) machine, worked fine. Uploaded to ubuntu (14.04), postgresql ( 9.3.14) in cloud 9 and the error began happening. 

WHAT DO I EXPECT TO HAPPEN?

For the application to behave the same, maybe a difference in postgresql?

WHAT IS ACTUALLY HAPPENING?

```
Feathers application started on 0.0.0.0:8080
Executing (default): INSERT INTO "public"."ProyectUsers" ("id","email","password","domain","createdAt","updatedAt") VALUES ('506cc5ab-c6b4-4d49-acb2-b00b22769e59','test1709@test.com','$2a$10$YUXdXOAl5cK1V5Q4VA.1FOocquUHQOcwwbO5oKMYXAHeR9p7X2pMi',1,'2016-10-03 22:09:32.560 +00:00','2016-10-03 22:09:32.560 +00:00') RETURNING *;
error: Route: /signup - relation "public.ProyectUsers" does not exist
info: SequelizeDatabaseError: relation "public.ProyectUsers" does not exist
    at Query.formatError (/home/ubuntu/workspace/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)
    at null.<anonymous> (/home/ubuntu/workspace/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at Query.handleError (/home/ubuntu/workspace/node_modules/pg/lib/query.js:133:8)
    at null.<anonymous> (/home/ubuntu/workspace/node_modules/pg/lib/client.js:180:26)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at Socket.<anonymous> (/home/ubuntu/workspace/node_modules/pg/lib/connection.js:121:12)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:536:20)
```

The strange thing is that I was able to execute the code just fine into postgresql, 

```
fedevela:~/workspace (master) $ psql
psql (9.3.14)
Type "help" for help.
ubuntu=# INSERT INTO "public"."ProyectUsers" ("id","email","password","domain","createdAt","updatedAt") VALUES ('d9b47f01-8eec-4e66-803d-640a775e71a8','test@test.com','$2a$10$ytNxjaLpV1PejeiItMqOoOZCt7WmMT8JxUTD/RKSlKmEquyqi03i2',1,'2016-10-03 21:46:35.155 +00:00','2016-10-03 21:46:35.155 +00:00') RETURNING *;
INSERT 0 1
```
but also at some point was also unable to select. So it might be an issue with postgres or my ignorance of it.

for now i am going to change all my object names to this_case_format so maybe i can work around the error.

thanks for reading this far!

**Comment by felixfbecker** [comment]
If you can execute the SQL manually just fine the only reason can be wrong connection options (wrong database?)

**Comment by janmeier** [comment]
Proyect?

**Comment by fedevela** [comment]
thank you!!!!

:">
