### ISSUE TITLE
n:m findOrCreate with include-where

### ISSUE THREAD

**Issue by liuxue0905** [sequelize/sequelize#6698]
Record : Artist = n : m
RecordArtist = RecordId + ArtistId

```js
    Record.findOrCreate({
        where: {
            title: 'record-10-1'
        },
        include: [
            {
                model: Artist,
                where: {
                    name: 'artist-name-no-exist'
                }
            }
        ]
    }).spread(function (record, created) {
        res.json({record: record, created: created})
    });
```

## What do you expect to happen?
I wanted:
Record.findOrCreate() should return null record & null created.
(Record.findOne() is working well.)  

## What is actually happening?
```
Unhandled rejection SequelizeValidationError: notNull Violation: type cannot be null,
notNull Violation: format cannot be null,
notNull Violation: release cannot be null
    at /Users/liuxue/WebstormProjects/GoldenTimes/node_modules/sequelize/lib/instance-validator.js:74:14
    at tryCatcher (/Users/liuxue/WebstormProjects/GoldenTimes/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/liuxue/WebstormProjects/GoldenTimes/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/liuxue/WebstormProjects/GoldenTimes/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/liuxue/WebstormProjects/GoldenTimes/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/liuxue/WebstormProjects/GoldenTimes/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/liuxue/WebstormProjects/GoldenTimes/node_modules/bluebird/js/release/promise.js:636:18)
    at PromiseArray._resolve (/Users/liuxue/WebstormProjects/GoldenTimes/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/Users/liuxue/WebstormProjects/GoldenTimes/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/Users/liuxue/WebstormProjects/GoldenTimes/node_modules/bluebird/js/release/promise.js:572:26)
    at Promise._settlePromise0 (/Users/liuxue/WebstormProjects/GoldenTimes/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/liuxue/WebstormProjects/GoldenTimes/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/liuxue/WebstormProjects/GoldenTimes/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/liuxue/WebstormProjects/GoldenTimes/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/liuxue/WebstormProjects/GoldenTimes/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
```

__Dialect:__ mysql
__Database version:__ 5.7.10
__Sequelize version:__ 3.24.3

**Comment by janmeier** [comment]
When does this happen? Does it happen if a row already exist, or when creating a new row? Does it only happen with includes, or can you reproduce with a smaller test case?

Please include a [SSCCE](HTTP://SSCCE.ORG/)
