### ISSUE TITLE
Remove hookValidate. Make validate reject on validation errors

### ISSUE THREAD

**Issue by diosney** [sequelize/sequelize#6740]
## What you are doing?

Running `.validate()` on a data instance returned by `.findById()`.
## What do you expect to happen?

If there is a validation error, the `.validate()` method should mark the promise as failed and throw an error that can be captured by `.catch()`.  
## What is actually happening?

Is marking the promise as resolved with an error object, that is passing to `.then()`, which enforces me to rethrow the error and wonder why is not consistent with the rest of the Sequelize API :)

Maybe this is on purpose, I'm reporting it just to make sure that you are aware of this. 

That is the code I've to end up:

``` js
return models[options.fkModel]
            .findById(req[options.fkObjectId].id)
            .then(function (data) {
              data.set(req.body);
              return data.validate();
            })
            .then(function (validationError) {
              if (validationError) {
                throw validationError;
              }
            });
```

**Sequelize version:** 3.24.3

**Comment by janmeier** [comment]
This is intentional (but confusing indeed!) http://docs.sequelizejs.com/en/v3/api/instance/#validateoptions-promiseerrorsvalidationerrorundefined

If you want a rejection, use `hookValidate`

This will most likely be rewritten in v4, so `hookValidate` is removed, and `validate`  rejects

**Comment by felixfbecker** [comment]
@janmeier we should leave this open then. I think this piece of API is an artifact from the callback API that was not converted to promises the right way

**Comment by janmeier** [comment]
You are probably correct

**Comment by sushantdhiman** [comment]
It appears `validate` throw errors properly as it should in `master`

**SSCCE Test**

```js
const Sequelize = require('./index');
const sequelize = require('./test/support').createSequelizeInstance();

const U = sequelize.define('U', {
  name: Sequelize.STRING,
  roll: {
    type: Sequelize.INTEGER,
    validate: {
      min: 1000,
      max: 20000
    }
  }
});

sequelize
  .sync({ force: true })
  .then(() => U.create({ name: 'Mustfa' }))
  .then(() => U.findById(1))
  .then((u) => {
    u.set({roll: 23});
    return u.validate();
  });
```

**Output**
```js
SequelizeValidationError: Validation error: Validation min on roll failed
    at Promise.all.then (/var/www/github/sequelize/lib/instance-validator.js:76:15)
From previous event:
    at InstanceValidator._validate (/var/www/github/sequelize/lib/instance-validator.js:74:7)
    at InstanceValidator.validate (/var/www/github/sequelize/lib/instance-validator.js:104:17)
    at model.validate (/var/www/github/sequelize/lib/model.js:3522:49)
    at sequelize.sync.then.then.then (/var/www/github/sequelize/sscce_template.js:29:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at Object.<anonymous> (/var/www/github/sequelize/sscce_template.js:27:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

```
