### ISSUE TITLE
`this`  is an empty object when invoking an instanceMethod

### ISSUE THREAD

**Issue by LaurentVB** [sequelize/sequelize#6743]
Hello,

Running into an odd issue when trying to call an instance method.
I added a `findUser` instance method in my `Organization` model. It uses the `getUsers` method generated by the one-to-many association. But when `findUser` is invoked, `this` is an empty object.

## What you are doing?

```js
module.exports = (sequelize, DataTypes) => {
  const Organization = sequelize.define('organization', {
    id: {
      type: DataTypes.UUID,
      primaryKey: true,
      defaultValue: DataTypes.UUIDV4
    },
    key: {
      type: DataTypes.STRING,
      unique: true,
      allowNull: false
    }
  }, {
      classMethods: {
        associate: (models) => {
          Organization.hasMany(models.user);
        }
      },
      instanceMethods: {
        findUser: (username) => {
          if (!username) {
            return Promise.resolve(null);
          }
          return this.getUsers({ where: { username: username } })
            .then((users) => {
              if (!user.length) {
                return null;
              }
              return users[0];
            });
        }
      }
    });

  return Organization;
};
```
In my test (run with jest), I then write this:

```js
describe('#findUser', () => {
  let foobar;

  beforeEach(() => {
    return Organization
      .create({ key: 'foobar' })
      .then((org) => {
        foobar = org;
        return foobar.createUser({ username: 'foo', email: 'foo@foobar.com', organizationId: foobar.id });
      })
  });

  it('returns the user if it exists in the organization', () => {
    return foobar.findUser('foo').then((user) => {
      expect(user).toBeDefined();
      expect(user).not.toBeNull();
      expect(user.username).toBe('foo');
    });
  });
});
```
## What do you expect to happen?
The user is returned and the test passes.

## What is actually happening?
The test fails and throws an exception because the `this` reference in the `findUser` method is an empty object and has no `getUsers` method.

```
 FAIL  test/models/organization.integration.test.js
  ● Organization › #findUser › returns the user if it exists in the organization

    TypeError: _this.getUsers is not a function
      
      at findUser (app/models/organization.js:37:49)
      at Object.it (test/models/organization.integration.test.js:51:21)
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:510:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:567:18)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:612:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:691:18)
      at Async.Object.<anonymous>.Async._drainQueue (node_modules/bluebird/js/release/async.js:138:16)
      at Async.Object.<anonymous>.Async._drainQueues (node_modules/bluebird/js/release/async.js:148:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)
      at runCallback (timers.js:637:20)
      at tryOnImmediate (timers.js:610:5)
      at processImmediate [as _immediateCallback] (timers.js:582:5)
```

Dialect: any
Sequelize version: 3.24.4

**Comment by felixfbecker** [comment]
You are using an arrow functions, arrow function have a lexically bound `this` value

**Comment by LaurentVB** [comment]
Stupid me.
Thanks for the quick reply.
