### ISSUE TITLE
Missing project: https://github.com/sequelize/sequelize-sqlite

### ISSUE THREAD

**Issue by ajmas** [sequelize/sequelize#6748]
I am running into an issue installing sequelize-sqlite, since I would like to use sqlite with Sequelize.

```
npm install sequelize-sqlite --save
npm WARN deprecated sequelize@1.7.11: security/injection issue with limit/offset fixed in 3.17.0

> sqlite3@2.1.19 install /Users/myuser/Development/customers/projectx/node_modules/sequelize-sqlite/node_modules/sqlite3
> node build.js

[sqlite3]: Checking for http://node-sqlite3.s3.amazonaws.com/Release/node_sqlite3-v2.1.a-node-v48-darwin-x64.tar.gz
[sqlite3]: http://node-sqlite3.s3.amazonaws.com/Release/node_sqlite3-v2.1.a-node-v48-darwin-x64.tar.gz not found, falling back to source compile (Error: Server returned 404)
(node:39291) DeprecationWarning: child_process: options.customFds option is deprecated. Use options.stdio instead.
gyp: sequelize-sqlite not found (cwd: /Users/myuser/Development/customers/projectx/node_modules/sequelize-sqlite/node_modules/sqlite3) while trying to load sequelize-sqlite
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/opt/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.0.0
gyp ERR! command "/opt/local/bin/node" "/opt/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "sequelize-sqlite" "--save"
gyp ERR! cwd /Users/myuser/Development/customers/projectx/node_modules/sequelize-sqlite/node_modules/sqlite3
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
[sqlite3]: Error: Failed to execute 'node-gyp rebuild sequelize-sqlite --save' (1)
my-api-server@0.0.1 /Users/myuser/Development/customers/projectx
└── (empty)
```

In trying to analyse the issue I visited https://www.npmjs.com/package/sequelize-sqlite and then clicked on the GitHub project link, but get a 404. I am using nodejs 6.7.0 on MacOS X 10.12.

Is something not up to date? Is sequelize-sqlite still the right way to get sqlite support for Sequelize?

**Comment by janmeier** [comment]
We decided it was too much work to keep the `sequelize-X` packages up to date - You should install both sequelize and sqlite3 in your project
