### ISSUE TITLE
Sequelize non-functional with Node v7.0.0

### ISSUE THREAD

**Issue by awitherspoon** [sequelize/sequelize#6773]
Using sequelize with the latest version of node throws the following error:

```
Sequelize [Node: 7.0.0, CLI: 2.4.0, ORM: 3.24.6]

module.js:474
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:17:20
    at Object.<anonymous> (/usr/local/lib/node_modules/sequelize-cli/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
```

This seems to be related to a bad version of graceful-fs, as noted in this [npm issue](https://github.com/npm/npm/issues/14438)

Needless to say, the expected behavior was that updating the package would allow for it to work inside node7.0.0.  It seems that the graceful-fs package being used by sequelize needs to be updated.

**Sequelize version:** 3.24.6

**Comment by janmeier** [comment]
Sequelize itself doesn't have a dependency on graceful-fs, please post this in http://github.com/sequelize/cli

**Comment by idris** [comment]
CLI issue: https://github.com/sequelize/cli/issues/383
