### ISSUE TITLE
instance.save() fails if eagerly loaded properties

### ISSUE THREAD

**Issue by olalonde** [sequelize/sequelize#678]
``` javascript
User.find({where: {'user.id': 1}}, include: [ Company ]).success(function (user) {
  user.name = 'new name';
  user.save().success();
});
```

I am loading an instance with an eagerly loaded property (many-to-many association) and later try to save it and I get the following error:

``` javascript
TypeError: Object [object Object] has no method 'replace'
    at Object.module.exports.QueryGenerator.pgEscape (/.../node_modules/sequelize/lib/dialects/postgres/query-generator.js:594:17)
    at /.../node_modules/sequelize/lib/dialects/postgres/query-generator.js:585:75
    at Array.map (native)
    at Object.module.exports.QueryGenerator.pgEscape (/.../node_modules/sequelize/lib/dialects/postgres/query-generator.js:585:34)
    at Object.module.exports.QueryGenerator.updateQuery (/.../node_modules/sequelize/lib/dialects/postgres/query-generator.js:304:74)
    at module.exports.QueryInterface.update (/.../node_modules/sequelize/lib/query-interface.js:206:35)
    at module.exports.DAO.save (/.../node_modules/sequelize/lib/dao.js:148:44)
```

**Comment by uchsarath** [comment]
Why don't you try to chain another complete() method to check the error?

.findOne().save().complete(err, Object);
