### ISSUE TITLE
Alpha Numeric Bind Parameter PostgreSQL syntax error at or near $1 

### ISSUE THREAD

**Issue by patrickcorrigan** [sequelize/sequelize#6888]
function buildCreateTableQuery()
    {
    var query = 'CREATE TABLE $name'
    query +=  'id INT PRIMARY KEY NOT NULL);'
    return query
    }

    function createModel(name, attributes)
    {
        var query = buildCreateTableQuery(name, attributes)
        return db.sequelize.query(query, { bind: {name:'dogs'},  type: db.Sequelize.QueryTypes.CREATE})
    }

When createModel is called I get the following error

    [grunt-develop] > Executing (default): CREATE TABLE $1 (id INT PRIMARY KEY NOT NULL);

    [grunt-develop] > Unhandled rejection SequelizeBaseError: syntax error at or near "$1"
        at Query.formatError (/home/patrick/code/backify/machine-    api/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)
        at Query.<anonymous> (/home/patrick/code/backify/machine-api/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
        at emitOne (events.js:96:13)
        at Query.emit (events.js:188:7)
        at Query.handleError (/home/patrick/code/backify/machine-api/node_modules/pg/lib/query.js:133:8)
        at Connection.<anonymous> (/home/patrick/code/backify/machine-api/node_modules/pg/lib/client.js:180:26)
        at emitOne (events.js:96:13)
        at Connection.emit (events.js:188:7)
        at Socket.<anonymous> (/home/patrick/code/backify/machine-api/node_modules/pg/lib/connection.js:121:12)
        at emitOne (events.js:96:13)
        at Socket.emit (events.js:188:7)
        at readableAddChunk (_stream_readable.js:176:18)
        at Socket.Readable.push (_stream_readable.js:134:10)
        at TCP.onread (net.js:551:20)

Thank you very much :)

**Comment by janmeier** [comment]
DDL comands don't support parameter bind (unless you want to get fancy and wrap it in a function - https://stackoverflow.com/questions/17648861/can-we-use-ddl-commands-in-a-prepared-statement-postgresql)

**Comment by patrickcorrigan** [comment]
Aha thank you very much. Such a quick response. Any advice as to how to best created dynamic ddl commands safely? Using replacements causes the parameter to become quoted which results in a syntax error for PSQL  CREATE TABLE 'dogs' (id INT PRIMARY KEY NOT NULL);

**Comment by janmeier** [comment]
You can use `sequelize.getQueryInterface().quoteIdentifier` to escape with `"`
