### ISSUE TITLE
 SequelizeDatabaseError: ER_ROW_IS_REFERENCED: Cannot delete or update a parent row: a foreign key constraint fails

### ISSUE THREAD

**Issue by wzup** [sequelize/sequelize#6894]
Does Sequelize controls/tracks FKs sequences in tables? So that I don't need to care about FKs, because Sequelize will destroy or recreate table automatically however many or complicated FKs my tables have?
Or do I manually have to control all FKs in my tables when I want to delete, truncate or sync operations?

This use case fails. Testing with `mocha` reveals that  Sequelize cannot track FKs :

```
before(function(done) {
    mysql.dropAllSchemas()
    .then(() => {
        return mysql.sync();
    })
    .then(res => {
        done();
    })
    .catch(err => {
        done(err);
    });
});
```

Output:

```
$ mocha

Executing (default): DROP TABLE IF EXISTS `Order`;
Executing (default): DROP TABLE IF EXISTS `Product`;
Executing (default): DROP TABLE IF EXISTS `Animal`;
Executing (default): DROP TABLE IF EXISTS `User`;

 C:\Users\user\app\test\create_product.js [ERROR dropAllSchemas]:
 { SequelizeDatabaseError: ER_ROW_IS_REFERENCED: Cannot delete or update a parent row: a foreign key constraint fails
    at Query.formatError (C:\Users\user\app\node_modules\sequelize\lib\dialects\mysql\query.js:175:14)
    at Query._callback (C:\Users\user\app\node_modules\sequelize\lib\dialects\mysql\query.js:49:21)
    at Query.Sequence.end (C:\Users\user\app\node_modules\mysql\lib\protocol\sequences\Sequence.js:85:24)
    at Query.ErrorPacket (C:\Users\user\app\node_modules\mysql\lib\protocol\sequences\Query.js:94:8)
    at Protocol._parsePacket (C:\Users\user\app\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (C:\Users\user\app\node_modules\mysql\lib\protocol\Parser.js:74:12)
    at Protocol.write (C:\Users\user\app\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (C:\Users\user\app\node_modules\mysql\lib\Connection.js:109:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)
  name: 'SequelizeDatabaseError',
  message: 'ER_ROW_IS_REFERENCED: Cannot delete or update a parent row: a foreign key constraint fails',

... and it continues ...
```

**Comment by janmeier** [comment]
Sequelize will try to create and drop tables in the correct order, based on the associations it knows about - But if you have existing foreign keys in the database that sequelize does not know about, we cannot take those into account, which is why you might see ER_ROW_IS_REFERENCED
