### ISSUE TITLE
transaction stack traces unhelpful

### ISSUE THREAD

**Issue by m3l7** [sequelize/sequelize#6983]
I'm using bluebird with long stack trace option on.
However, when a transaction is rejected, I have no idea where the wrong query is run.

      error:  SequelizeForeignKeyConstraintError: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`enrev`.`Devices`, CONSTRAINT `distributorId_foreign_idx_device` FOREIGN KEY (`distributorId`) REFERENCES `Users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE)
          at Query.formatError (/home/phil/Sorgenti/blackbox/node_modules/sequelize/lib/dialects/mysql/query.js:168:14)
          at Query._callback (/home/phil/Sorgenti/blackbox/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
          at Query.Sequence.end (/home/phil/Sorgenti/blackbox/node_modules/mysql/lib/protocol/sequences/Sequence.js:85:24)
          at Query.ErrorPacket (/home/phil/Sorgenti/blackbox/node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
          at Protocol._parsePacket (/home/phil/Sorgenti/blackbox/node_modules/mysql/lib/protocol/Protocol.js:280:23)
          at Parser.write (/home/phil/Sorgenti/blackbox/node_modules/mysql/lib/protocol/Parser.js:74:12)
          at Protocol.write (/home/phil/Sorgenti/blackbox/node_modules/mysql/lib/protocol/Protocol.js:39:16)
          at Socket.<anonymous> (/home/phil/Sorgenti/blackbox/node_modules/mysql/lib/Connection.js:109:28)
          at emitOne (events.js:96:13)
          at Socket.emit (events.js:188:7)
          at readableAddChunk (_stream_readable.js:176:18)
          at Socket.Readable.push (_stream_readable.js:134:10)
          at TCP.onread (net.js:551:20)
      From previous event:
          at Query.run (/home/phil/Sorgenti/blackbox/node_modules/sequelize/lib/dialects/mysql/query.js:39:17)
          at /home/phil/Sorgenti/blackbox/node_modules/sequelize/lib/sequelize.js:849:20
          at /home/phil/Sorgenti/blackbox/node_modules/retry-as-promised/index.js:40:21
      From previous event:
          at retryAsPromised (/home/phil/Sorgenti/blackbox/node_modules/retry-as-promised/index.js:30:10)
          at /home/phil/Sorgenti/blackbox/node_modules/sequelize/lib/sequelize.js:848:12
      From previous event:
          at Promise.then (/home/phil/Sorgenti/blackbox/node_modules/sequelize/lib/promise.js:21:17)
          at transactionResolver (/home/phil/Sorgenti/blackbox/node_modules/sequelize/lib/sequelize.js:1284:40)
      From previous event:
          at Sequelize.transaction (/home/phil/Sorgenti/blackbox/node_modules/sequelize/lib/sequelize.js:1313:12)
          at User.updateAsAdmin (/home/phil/Sorgenti/blackbox/release/js/api/controller/user.js:239:27)
          at User.update (/home/phil/Sorgenti/blackbox/release/js/api/controller/user.js:182:18)
          at Layer.handle [as handle_request] (/home/phil/Sorgenti/blackbox/node_modules/express/lib/router/layer.js:95:5)
          at next (/home/phil/Sorgenti/blackbox/node_modules/express/lib/router/route.js:131:13)
          at passport.authenticate (/home/phil/Sorgenti/blackbox/release/js/api/config/policies.js:58:24)
          at complete (/home/phil/Sorgenti/blackbox/node_modules/passport/lib/middleware/authenticate.js:250:13)
          at /home/phil/Sorgenti/blackbox/node_modules/passport/lib/middleware/authenticate.js:257:15
          at pass (/home/phil/Sorgenti/blackbox/node_modules/passport/lib/authenticator.js:421:14)
          at Authenticator.transformAuthInfo (/home/phil/Sorgenti/blackbox/node_modules/passport/lib/authenticator.js:443:5)
          at /home/phil/Sorgenti/blackbox/node_modules/passport/lib/middleware/authenticate.js:254:22
          at /home/phil/Sorgenti/blackbox/node_modules/passport/lib/http/request.js:60:7
          at pass (/home/phil/Sorgenti/blackbox/node_modules/passport/lib/authenticator.js:267:43)
          at serialized (/home/phil/Sorgenti/blackbox/node_modules/passport/lib/authenticator.js:276:7)
          at /home/phil/Sorgenti/blackbox/release/js/api/config/passport.js:14:13
          at pass (/home/phil/Sorgenti/blackbox/node_modules/passport/lib/authenticator.js:284:9)
          at Authenticator.serializeUser (/home/phil/Sorgenti/blackbox/node_modules/passport/lib/authenticator.js:289:5)
          at IncomingMessage.req.login.req.logIn (/home/phil/Sorgenti/blackbox/node_modules/passport/lib/http/request.js:50:29)
          at Strategy.strategy.success (/home/phil/Sorgenti/blackbox/node_modules/passport/lib/middleware/authenticate.js:235:13)
          at verified (/home/phil/Sorgenti/blackbox/node_modules/passport-http-bearer/lib/strategy.js:126:10)
          at Model.db.models.Token.findOne.then (/home/phil/Sorgenti/blackbox/release/js/api/config/passport.js:73:21)
     
the relevant lines are

      at Sequelize.transaction (/home/phil/Sorgenti/blackbox/node_modules/sequelize/lib/sequelize.js:1313:12)
      at User.updateAsAdmin (/home/phil/Sorgenti/blackbox/release/js/api/controller/user.js:239:27)
      at User.update (/home/phil/Sorgenti/blackbox/release/js/api/controller/user.js:182:18)

user.js:239 is where the transaction begins, but there's no mention on where the actual query is located.

**Comment by janmeier** [comment]
I'm not sure there's much we can do about that - Stacktraces in node are inherently hard with the jumps back and forth in async code, but I don't think there is anything sequelize can do about that.

If you can point to a specific point in sequelize code where the stack context is lost we can look at that, but other than that I don't know what to do :)

**Comment by m3l7** [comment]
this is my code:

      this.db.sequelize.transaction((t) => {
          return this.db.models.Device.update({ distributorId: 102 }, { where: { id: 7 }, transaction: t });
      })
      .catch(next)

I'm not very expert in node error management, so I'm quite confused.

The update query should throw an error or return a promise.reject. I'm not sure why the transaction method can't propagate the error

**Comment by felixfbecker** [comment]
I don't get your question - if you look at the stack trace, there is exactly the location of where you call `update()`. What do you expect?

**Comment by m3l7** [comment]
the User.update and User.updateAsAdmin are the functions in which the transaction is located.

the stack trace has only the line in which the transaction is defined (sequelize.transaction() ), not the update() query.

**Comment by felixfbecker** [comment]
Ah okay. But that is totally correct - the (database) error is thrown at the time the transaction is commited, not at the time you do the update. The error has information about why the error occured on the DB level, but we cannot know which JavaScript function call caused the error.
