### ISSUE TITLE
Update with angularjs

### ISSUE THREAD

**Issue by borellaster** [sequelize/sequelize#7000]
Hello everyone

I have been trying to work with sequelize+angular+postgresql.

I have a method in my service.

```js
    function update(countries) {
      return resource.update({'id': countries.id}, countries).$promise;          
    }  
```

Resource.js

```js
  function CountriesResource($resource) {

    var rest = $resource(
      'rest/countries/:id',
      {
        'id': ''
      },
      {
        'update': { 'method': 'PUT' }
      }
    );

    return rest;

  }
```

Controller.js

```js
      dataService.update($scope.countries).then(function success(data) {

      })
      .catch(function error(msg) {
       
      });
```

Node method

```js
  update(req, res) {    
    Country.update(req.body, {
      where: {
        id: req.params.id
      }
    })
    .then(function (updatedRecords) {
      res.status(200).json(updatedRecords);
    })
    .catch(function (error){
      res.status(500).json(error);
    });
  }
```

Error

```js
TypeError: Cannot convert undefined or null to object
   at Function.keys (native)
   at Model.update (C:\cptec\node_modules\sequelize\lib\model.js:2468:44)
   at update (C:\cptec\server\controllers\countries.js:38:13)
   at Layer.handle [as handle_request] (C:\cptec\node_modules\express\lib\router\layer.js:95:5)
   at next (C:\cptec\node_modules\express\lib\router\route.js:131:13)
   at Route.dispatch (C:\cptec\node_modules\express\lib\router\route.js:112:3)
   at Layer.handle [as handle_request] (C:\cptec\node_modules\express\lib\router\layer.js:95:5)
   at C:\cptec\node_modules\express\lib\router\index.js:277:22
   at param (C:\cptec\node_modules\express\lib\router\index.js:349:14)
   at param (C:\cptec\node_modules\express\lib\router\index.js:365:14)
   at Function.process_params (C:\cptec\node_modules\express\lib\router\index.js:410:3)
   at next (C:\cptec\node_modules\express\lib\router\index.js:271:10)
   at expressInit (C:\cptec\node_modules\express\lib\middleware\init.js:33:5)
   at Layer.handle [as handle_request] (C:\cptec\node_modules\express\lib\router\layer.js:95:5)
   at trim_prefix (C:\cptec\node_modules\express\lib\router\index.js:312:13)
   at C:\cptec\node_modules\express\lib\router\index.js:280:7
```

Someone have any idea what problem could happen here?

__Dialect:__ postgres
__Database version:__ 9.2
__Sequelize version:__ 3.27.0

**Comment by janmeier** [comment]
Have you checked that req.body is not empty?

On Dec 17, 2016 12:49, "Felipe Borella" <notifications@github.com> wrote:

Hello everyone

I have been trying to work with sequelize+angular+postgresql.

I have a method in my service.

    function update(countries) {
      return resource.update({'id': countries.id},
countries).$promise;
    }

Resource.js

  function CountriesResource($resource) {

    var rest = $resource(
      'rest/countries/:id',
      {
        'id': ''
      },
      {
        'update': { 'method': 'PUT' }
      }
    );

    return rest;

  }

Controller.js

      dataService.update($scope.countries).then(function success(data) {

      })
      .catch(function error(msg) {

      });

Node method

  update(req, res) {
    Country.update(req.body, {
      where: {
        id: req.params.id
      }
    })
    .then(function (updatedRecords) {
      res.status(200).json(updatedRecords);
    })
    .catch(function (error){
      res.status(500).json(error);
    });
  }

Error

TypeError: Cannot convert undefined or null to object
   at Function.keys (native)
   at Model.update (C:\cptec\node_modules\sequelize\lib\model.js:2468:44)
   at update (C:\cptec\server\controllers\countries.js:38:13)
   at Layer.handle [as handle_request]
(C:\cptec\node_modules\express\lib\router\layer.js:95:5)
   at next (C:\cptec\node_modules\express\lib\router\route.js:131:13)
   at Route.dispatch (C:\cptec\node_modules\express\lib\router\route.js:112:3)
   at Layer.handle [as handle_request]
(C:\cptec\node_modules\express\lib\router\layer.js:95:5)
   at C:\cptec\node_modules\express\lib\router\index.js:277:22
   at param (C:\cptec\node_modules\express\lib\router\index.js:349:14)
   at param (C:\cptec\node_modules\express\lib\router\index.js:365:14)
   at Function.process_params
(C:\cptec\node_modules\express\lib\router\index.js:410:3)
   at next (C:\cptec\node_modules\express\lib\router\index.js:271:10)
   at expressInit (C:\cptec\node_modules\express\lib\middleware\init.js:33:5)
   at Layer.handle [as handle_request]
(C:\cptec\node_modules\express\lib\router\layer.js:95:5)
   at trim_prefix (C:\cptec\node_modules\express\lib\router\index.js:312:13)
   at C:\cptec\node_modules\express\lib\router\index.js:280:7

Someone have any idea what problem could happen here?

*Dialect:* postgres
*Database version:* 9.2
*Sequelize version:* 3.27.0

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/sequelize/sequelize/issues/7000>, or mute the thread

**Comment by borellaster** [comment]
Hello

Yes, and the object is "undefined", but I don't understand why.

Here is my Request Payload

```js
{"id":2,"name":"ARGENTINA","abbreviation":"AR","created_at":"2016-11-25T17:43:54.921Z","updated_at":"2016-11-25T17:43:54.921Z"}
```
```js
  update(req, res) {    
    console.log(req.body);
    Country.update(req.body, {
      where: {
        id: req.params.id
      }
    })
    .then(function (updatedRecords) {
      res.status(200).json(updatedRecords);
    })
    .catch(function (error){
      res.status(500).json(error);
    });
  },
```

**Comment by felixfbecker** [comment]
You probably have not used the body parser middleware. If you need further help, you should post a question on StackOverflow or Gitter in the appropriate channel (I assume express).

**Comment by borellaster** [comment]
Hello

Thanks a lot! You were completely right about it.
