### ISSUE TITLE
Bug when including another model with certain "as" property names

### ISSUE THREAD

**Issue by etinin** [sequelize/sequelize#7036]
I've found a pretty interesting behavior which appears to be a bug:

When attempting to merely include a model named Materia, it works fine (and gets singularized as Materium). However, when I try to named the property as "Materia", Sequelize claims that "Materia is not associated to Topico!".

Working use case:
db.Topico.findAll({include: [{model: db.Materia}]})

Non-working use case:
db.Topico.findAll({include: [{model: db.Materia, as: "Materia"}]})

Error:
`Unhandled rejection Error: Materia is not associated to Topico!
[2]     at Model.validateIncludedElement (/Users/etinin/effy/concours/node_modules/sequelize/lib/model.js:558:11)
[2]     at /Users/etinin/effy/concours/node_modules/sequelize/lib/model.js:440:29
[2]     at Array.map (native)
[2]     at Model.validateIncludedElements (/Users/etinin/effy/concours/node_modules/sequelize/lib/model.js:436:37)
[2]     at Model.<anonymous> (/Users/etinin/effy/concours/node_modules/sequelize/lib/model.js:1372:32)
[2]     at runCallback (timers.js:637:20)
[2]     at tryOnImmediate (timers.js:610:5)
[2]     at processImmediate [as _immediateCallback] (timers.js:582:5)
[2] From previous event:
[2]     at Promise.then (/Users/etinin/effy/concours/node_modules/sequelize/lib/promise.js:21:17)
[2]     at Model.findAll (/Users/etinin/effy/concours/node_modules/sequelize/lib/model.js:1368:6)
[2]     at /Users/etinin/effy/concours/api/actions/topicos.js:29:80
[2]     at _default (/Users/etinin/effy/concours/api/actions/topicos.js:29:18)
[2]     at /Users/etinin/effy/concours/api/api.js:175:7
[2]     at Layer.handle [as handle_request] (/Users/etinin/effy/concours/node_modules/express/lib/router/layer.js:95:5)
[2]     at trim_prefix (/Users/etinin/effy/concours/node_modules/express/lib/router/index.js:312:13)
[2]     at /Users/etinin/effy/concours/node_modules/express/lib/router/index.js:280:7
[2]     at Function.process_params (/Users/etinin/effy/concours/node_modules/express/lib/router/index.js:330:12)
[2]     at next (/Users/etinin/effy/concours/node_modules/express/lib/router/index.js:271:10)
[2]     at jsonParser (/Users/etinin/effy/concours/node_modules/body-parser/lib/types/json.js:103:7)
[2]     at Layer.handle [as handle_request] (/Users/etinin/effy/concours/node_modules/express/lib/router/layer.js:95:5)
[2]     at trim_prefix (/Users/etinin/effy/concours/node_modules/express/lib/router/index.js:312:13)
[2]     at /Users/etinin/effy/concours/node_modules/express/lib/router/index.js:280:7
[2]     at Function.process_params (/Users/etinin/effy/concours/node_modules/express/lib/router/index.js:330:12)
[2]     at next (/Users/etinin/effy/concours/node_modules/express/lib/router/index.js:271:10)
[2]     at compression (/Users/etinin/effy/concours/node_modules/compression/index.js:219:5)
[2]     at Layer.handle [as handle_request] (/Users/etinin/effy/concours/node_modules/express/lib/router/layer.js:95:5)
[2]     at trim_prefix (/Users/etinin/effy/concours/node_modules/express/lib/router/index.js:312:13)
[2]     at /Users/etinin/effy/concours/node_modules/express/lib/router/index.js:280:7
[2]     at Function.process_params (/Users/etinin/effy/concours/node_modules/express/lib/router/index.js:330:12)
[2]     at next (/Users/etinin/effy/concours/node_modules/express/lib/router/index.js:271:10)
[2]     at cors (/Users/etinin/effy/concours/node_modules/cors/lib/index.js:179:7)
[2]     at /Users/etinin/effy/concours/node_modules/cors/lib/index.js:229:17
[2]     at originCallback (/Users/etinin/effy/concours/node_modules/cors/lib/index.js:218:15)`

Output (with the working use case):
`[{"Id":1,"Nome":"morte","MateriaId":1,"Importancia":null,"createdAt":"2016-12-25T00:24:11.632Z","updatedAt":"2016-12-25T00:24:11.632Z","Materium":{"Id":1,"Nome":"Teste","ProvaId":2,"createdAt":"2016-12-24T18:28:00.674Z","updatedAt":"2016-12-24T18:28:00.674Z"}}]`

I've attached the relevant source code. If anyone needs further help replicating this, feel free to ask. If I have some time, I may try to further debug this apparent issue, but this is all I have for now.

Sequelize 3.28.0. Node v6.9.2. PostgreSQL database.

[sourceCode.zip](https://github.com/sequelize/sequelize/files/672009/sourceCode.zip)

**Comment by felixfbecker** [comment]
The alias you pass when including must be the same alias you pass when setting up the relationship. I recommend you to just use `Topico.associations.Materium` instead of duplicating the `model, as` pair.
