### ISSUE TITLE
Mysql Timeout on Openstack NFV Enrollment

### ISSUE THREAD

**Issue by jaliph** [sequelize/sequelize#7057]
Hi,

Currently we are getting a Timeout Request when COnnecting to MYSQL. 

If we use IP @ mysql host, we are able to connect but in case of hostname, our DNS in Openstack is taking sometime and there is a connection timeout. Is there a way we can pass the TIMEOUT to the mysql lib from Sequelizer constructor?

Default value is **10sec** in MYSQL ConnectionConfig.  

If yes, what is the parameter passed or how can we achieve this.

Unhandled rejection SequelizeConnectionError: connect ETIMEDOUT
    at Handshake._callback (/prd/ecp/ecosystem/authserver/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:94:20)
    at Handshake.Sequence.end (/prd/ecp/ecosystem/authserver/node_modules/mysql/lib/protocol/sequences/Sequence.js:85:24)
    at Protocol.handleNetworkError (/prd/ecp/ecosystem/authserver/node_modules/mysql/lib/protocol/Protocol.js:364:14)
    at Connection._handleNetworkError (/prd/ecp/ecosystem/authserver/node_modules/mysql/lib/Connection.js:434:18)
    at Connection._handleConnectTimeout (/prd/ecp/ecosystem/authserver/node_modules/mysql/lib/Connection.js:430:8)
    at Socket.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:334:8)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)

Sorry for not following your template.
Versions:
"sequelize": "^3.23.4"
"mysql": "^2.11.1"
Server version: 5.5.44-MariaDB

Thanks a lot in Advance.

**Comment by jaliph** [comment]
Please close this. Found it in Dialect Options
