### ISSUE TITLE
defineCall is not a function while importing models from an index.js file.

### ISSUE THREAD

**Issue by luispcosta** [sequelize/sequelize#7059]
## What you are doing?
I'm trying to integrate mocha.js in my project, and test my models while I do it.
This is my folder current folder structure:
```
- /
    - config/
        - config.json
    - server/
        - config/
            - routes.js
        - migrations/
        - models/
            - comment.js
            - index.js
        - test/
            - test.js
        - app.js
```

Here's my `comment.js`

```javascript
module.exports = function (sequelize, DataTypes) {
  const Comment = sequelize.define('Comment', {
    content: {
      type: DataTypes.TEXT,
      allowNull: false
    },
    upvotes: {
      type: DataTypes.INTEGER,
      defaultValue: 0
    },
    downvotes: {
      type: DataTypes.INTEGER,
      defaultValue: 0
    }
  })

  return Comment
}
```
Here's my `index.js` inside the `models` folder:

```javascript
import fs from 'fs'

import path from 'path'

import Sequelize from 'sequelize'

const env = process.env.NODE_ENV || 'development'

const config = require(path.join(__dirname, '../..', 'config', 'config.json'))[env]

let sequelize = null
if (process.env.DATABASE_URL) {
  sequelize = new Sequelize(process.env.DATABASE_URL)
} else {
  sequelize = new Sequelize(config.database, config.username, config.password, config)
}

const db = {}

fs
  .readdirSync(__dirname)
  .filter(file => {
    return (file.indexOf('.') !== 0) && (file !== 'index.js')
  })
  .forEach(file => {
    const model = sequelize['import'](path.join(__dirname, file))
    db[model.name] = model
  })

Object.keys(db).forEach(modelName => {
  if ('associate' in db[modelName]) {
    db[modelName].associate(db)
  }
})

db.sequelize = sequelize
db.Sequelize = Sequelize

module.exports = db
```

Here's my `test.js` inside the `test` folder:

```js
import server from './../app'
import assert from 'assert'
import chai from 'chai'
import chaiHttp from 'chai-http'
const should = chai.should()
chai.use(chaiHttp)
import envConfig from './../../config/config.json'

import models from './../models'
console.log(models.Comment) // => This works ok!

describe('Comments', () => {

  describe('/GET test', () => {
    it('test', (done) => {
      done()
    })
  })
})
```

## What do you expect to happen?
The line `console.log(models.Comment)` works fine, so that models is being safely exported. I expected that everything would work ok, since the model is being correctly exported.

## What is actually happening?
However, every time I run the test, no matter what I do, I _always_ get this error:

```
Unhandled rejection TypeError: defineCall is not a function
    at Sequelize.import (/home/lpec/projects/reddit_clone/node_modules/sequelize/lib/sequelize.js:691:30)
    at /home/lpec/projects/reddit_clone/node_modules/sequelize-connect/dist/lib/Connection.js:61:22
    at tryCatcher (/home/lpec/projects/reddit_clone/node_modules/sequelize-connect/node_modules/bluebird/js/main/util.js:26:23)
    at ReductionPromiseArray._promiseFulfilled (/home/lpec/projects/reddit_clone/node_modules/sequelize-connect/node_modules/bluebird/js/main/reduce.js:105:38)
    at ReductionPromiseArray.init (/home/lpec/projects/reddit_clone/node_modules/sequelize-connect/node_modules/bluebird/js/main/promise_array.js:92:18)
    at Promise._settlePromiseAt (/home/lpec/projects/reddit_clone/node_modules/sequelize-connect/node_modules/bluebird/js/main/promise.js:582:21)
    at Promise._settlePromises (/home/lpec/projects/reddit_clone/node_modules/sequelize-connect/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/lpec/projects/reddit_clone/node_modules/sequelize-connect/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/lpec/projects/reddit_clone/node_modules/sequelize-connect/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/lpec/projects/reddit_clone/node_modules/sequelize-connect/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

The error seems to be here:

```js
// sequelize.js

if (!this.importCache[path]) {
    var defineCall = (arguments.length > 1 ? arguments[1] : require(path));
    if (typeof defineCall === 'object') {
      // Babel/ES6 module compatability
      defineCall = defineCall.default;
    }
    this.importCache[path] = defineCall(this, DataTypes);
  }
```

Here's my `package.json`:

```json
{
  "scripts": {
    "start": "node ./bin/www",
    "dev": "NODE_ENV=development nodemon -w ./ -x npm run start",
    "test-server": "NODE_ENV=test ./node_modules/.bin/mocha --timeout 10000 --compilers js:babel-core/register server/test"
  },
  "dependencies": {
    "babel-preset-node5": "^12.0.0",
    "babel-register": "^6.18.0",
    "bcrypt-nodejs": "0.0.3",
    "body-parser": "^1.15.2",
    "config": "^1.24.0",
    "cookie-parser": "^1.4.3",
    "express": "^4.14.0",
    "express-session": "^1.14.2",
    "mysql": "^2.12.0",
    "nodemon": "^1.11.0",
    "passport": "^0.3.2",
    "passport-local": "^1.0.0",
    "react": "^15.4.1",
    "react-dom": "^15.4.1",
    "react-router": "^3.0.0",
    "sequelize": "^3.28.0",
    "sequelize-connect": "^2.0.0"
  },
  "babel": {
    "presets": [
      "node5"
    ]
  },
  "devDependencies": {
    "babel-loader": "^6.2.10",
    "babel-preset-es2015": "^6.18.0",
    "babel-preset-react": "^6.16.0",
    "chai": "^3.5.0",
    "chai-http": "^3.0.0",
    "eslint": "^3.12.2",
    "eslint-config-standard": "^6.2.1",
    "eslint-plugin-promise": "^3.4.0",
    "eslint-plugin-standard": "^2.0.1",
    "html-webpack-plugin": "^2.24.1",
    "mocha": "^3.2.0",
    "webpack": "^1.14.0",
    "webpack-dev-middleware": "^1.9.0",
    "webpack-hot-middleware": "^2.14.0"
  }
}
```

Is this a known bug? Is there a know solution for this?

Thank you so much for helping, and thanks for building this awesome tool :)

**Comment by felixfbecker** [comment]
Maybe because you are mixing module.exports with ES6 imports/exports?

**Comment by luispcosta** [comment]
Got it working! My `app.js` was not correct. This was my last lines in `app.js`:

```js
 async function connect () {
   const discover = path.join(__dirname, 'models')
   const matcher = function (file) {
       return true
   }
   new Connect(
     envConfig[envMode].database,
     envConfig[envMode].username,
     envConfig[envMode].password,
     {
          dialect: ...
     }
    discover,
    matcher
   )
 }

(async function () {
  try {
    await connect()
  } catch (err) {
    console.warn(`Error trying to connect: ${err}`)
  }

  const app = express()
  app.use(bodyParser.json())
  app.use(bodyParser.urlencoded({ extended: true }))
  app.use(cookieParser())
  app.use(middleware)
  app.use(webpackHotMiddleware(compiler))
  app.use(session({ secret: 'keyboard cat', resave: false, saveUninitialized: false }))
  routes(app)

  app.listen(3000, () => console.log('running'))
})()
```

I changed it to:

```js
async function connect () {
  const discover = path.join(__dirname, 'models')
  new Connect(
    envConfig[envMode].database,
    envConfig[envMode].username,
    envConfig[envMode].password,
    {
      dialect: 'mysql',
      port: 3306
    },
    discover
  )
}
```

I guess the `matcher` was not needed.
