### ISSUE TITLE
SequelizeBaseError: null thrown when attempting to insert an empty array into a text field

### ISSUE THREAD

**Issue by Xythus** [sequelize/sequelize#7129]
## What you are doing?
I was unintentionally attempting to insert an empty array into a text field. This should obviously throw an error, but the error thrown was too vague to be usable.

```js
var text = [];
var LogEntry = connection.define('logEntry', {
     text: DataTypes.TEXT
 };

LogEntry.create({
	text: text
}).then(function(logEntry) {
	if (callback) callback(logEntry);
});
```

## What do you expect to happen?
An error gets thrown describing the issue.

## What is actually happening?
The error thrown was 'SequelizeBaseError: null' and the stacktrace was not useful for debugging.

```js
Unhandled rejection SequelizeBaseError: null
    at C:\Users\xxxx\Documents\Git\xxxx\node_modules\sequelize\lib\
instance-validator.js:74:14
    at tryCatcher (C:\Users\xxxx\Documents\Git\xxxx\node_modules\bl
uebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\xxxx\Documents\Git\xxxx\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\xxxx\Documents\Git\xxxx\nod
e_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\xxxx\Documents\Git\xxxx\no
de_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\xxxx\Documents\Git\xxxx\no
de_modules\bluebird\js\release\promise.js:691:18)
    at Promise._fulfill (C:\Users\xxxx\Documents\Git\xxxx\node_modu
les\bluebird\js\release\promise.js:636:18)
    at PromiseArray._resolve (C:\Users\xxxx\Documents\Git\xxxx\node
_modules\bluebird\js\release\promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (C:\Users\xxxx\Documents\Git\xxxx\node_modules\bluebird\js\release\promise_array.js:143:14)
    at Promise._settlePromise (C:\Users\xxxx\Documents\Git\xxxx\nod
e_modules\bluebird\js\release\promise.js:572:26)
    at Promise._settlePromise0 (C:\Users\xxxx\Documents\Git\xxxx\no
de_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\xxxx\Documents\Git\xxxx\no
de_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\xxxx\Documents\Git\xxxx\node_mod
ules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\xxxx\Documents\Git\xxxx\node_mo
dules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\xxxx\Documents\Git\xxxx\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:637:20)
```

__Dialect:__ MariaDB (MySQL)
__Database version:__ 10.1.16-MariaDB
__Sequelize version:__ ^3.29.0

**Comment by sushantdhiman** [comment]
Could you try master?

**Comment by janmeier** [comment]
Closing, no response

**Comment by XiaoBin6666** [comment]
Was the issue solved

**Comment by JeffWong16** [comment]
Your table may have one or more fileds that is not allow null.Check it. I have the same problem today. 😄

**Comment by contra** [comment]
This stacktrace could use a lot of help - I'm getting this when throwing validation errors as the docs specify.

**Comment by sushantdhiman** [comment]
Can any one in this thread show me a reproducible code that throw same error with master branch. I will reopen this issue if some evidence is presented :)

**Comment by contra** [comment]
@sushantdhiman I'm able to produce this pretty easily actually - I think in my case the error is actually that a validation error is being wrapped in a BaseError with no message, so when toString is called on the error it produces this worthless "null" message. If you log the actual object the real error (and message) is in the `errors` attribute.

**Comment by YUFENGWANG** [comment]
same problem here.

**Comment by Xythus** [comment]
@sushantdhiman Could you try master?

**Comment by ajlal** [comment]
I have same issue please tell me what to do ?

**Comment by DoumanAsh** [comment]
Just wanted to let that such error happens for example when validation fails:
```
    email: {
        type: Sequelize.TEXT,
        validate: {
            isEmail: true
        }
    },
```

I tried to send some trash and got error.
But when i tried to send a proper mail everything was ok.

**Comment by textarcana** [comment]
Thank you @DoumanAsh. It is not obvious that I needed to read the `errors` field of the thrown error object.

```
...
.catch((e) => {
        console.log(e.errors);
      });
```
