### ISSUE TITLE
SequelizeDatabaseError: relation "users_email_unique" already exists

### ISSUE THREAD

**Issue by nstuyvesant** [sequelize/sequelize#7135]
## What you are doing?

```js
let User = sequelize.define('User', {
    _id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true
    },
    email: {
      type: DataTypes.STRING(80),
      validate: {
        isEmail: true
      }
    }
  }, {
    indexes: [
      { name: 'users_email_unique', unique: true, fields: ['email'] }
  });

User.sync()
  .then(() => User.destroy({
    where: {
      $or: [
        { email: {$eq: 'john.doe@bitbucket.com'} },
        { email: {$eq: 'jane.doe@bitbucket.com'} }
      ]
    }
  }))
  .then(() => User.bulkCreate(
      [
        {
          email: 'john.doe@bitbucket.com'
        }, {
          email: 'jane.doe@bitbucket.com'
        }
    ]
  )
}
```

## What do you expect to happen?
That my table would be created with an index and populated with two records (without errors). If the table already exists, delete the old records first.

## What is actually happening?
Throwing an error...

> SequelizeDatabaseError: relation "users_email_unique" already exists

which causes my server not to start. **But**... the table was created successfully and populated with the records. If I restart my server, everything works.

If I comment out the index creation, I do not get the error (or the index that I need).

_Output, either JSON or SQL_

> Executing (default): SELECT t.typname enum_name, array_agg(e.enumlabel ORDER BY enumsortorder) enum_value FROM pg_type t JOIN pg_enum e ON t.oid = e.enumtypid JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname='enum_Users_role' GROUP BY 1
> Executing (default): SELECT t.typname enum_name, array_agg(e.enumlabel ORDER BY enumsortorder) enum_value FROM pg_type t JOIN pg_enum e ON t.oid = e.enumtypid JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname='enum_Users_provider' GROUP BY 1
> Executing (default): CREATE TABLE IF NOT EXISTS "Users" ("_id"  SERIAL, "email" VARCHAR(80), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("_id"));
> Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'Users' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
> Executing (default): CREATE UNIQUE INDEX "users_email_unique" ON "Users" ("email")
> Executing (default): DELETE FROM "Users" WHERE ("email" = 'john.doe@bitbucket.com' OR "email" = 'jane.doe@bitbucket.com')

The error occurs here then the inserts begin:

> INSERT INTO "Users" ("_id","email") VALUES (DEFAULT, 'john.doe@bitbucket.com'),  (DEFAULT, 'jane.doe@bitbucket.com')

__Dialect:__ postgres
__Database version:__ 9.6.1
__Sequelize version:__ 3.29.0

**Comment by sushantdhiman** [comment]
I see no problem on `3.29.0` on `Postgres 9.6` at least

```
Executing (default): DROP TABLE IF EXISTS "Users" CASCADE;
Executing (default): CREATE TABLE IF NOT EXISTS "Users" ("_id"  SERIAL , "email" VARCHAR(80), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("_id"));
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'Users' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
Executing (default): CREATE UNIQUE INDEX "users_email_unique" ON "Users" ("email")
Executing (default): DELETE FROM "Users" WHERE ("email" = 'john.doe@bitbucket.com' OR "email" = 'jane.doe@bitbucket.com')
Executing (default): INSERT INTO "Users" ("_id","email","createdAt","updatedAt") VALUES (DEFAULT,'john.doe@bitbucket.com','2017-01-22 10:05:13.090 +00:00','2017-01-22 10:05:13.090 +00:00'),(DEFAULT,'jane.doe@bitbucket.com','2017-01-22 10:05:13.090 +00:00','2017-01-22 10:05:13.090 +00:00');
[ Instance {
    dataValues: 
     { _id: null,
       email: 'john.doe@bitbucket.com',
       createdAt: 2017-01-22T10:05:13.090Z,
       updatedAt: 2017-01-22T10:05:13.090Z },
    _previousDataValues: { email: undefined },
    _changed: { email: true },
    '$modelOptions': 
     { timestamps: true,
       instanceMethods: {},
       classMethods: {},
       validate: {},
       freezeTableName: false,
       underscored: false,
       underscoredAll: false,
       paranoid: false,
       rejectOnEmpty: false,
       whereCollection: null,
       schema: null,
       schemaDelimiter: '',
       defaultScope: {},
       scopes: [],
       hooks: {},
       indexes: [Object],
       name: [Object],
       omitNul: false,
       sequelize: [Object],
       uniqueKeys: {},
       hasPrimaryKeys: true },
    '$options': { isNewRecord: true, '$schema': null, '$schemaDelimiter': '' },
    hasPrimaryKeys: true,
    __eagerlyLoadedAssociations: [],
    isNewRecord: true },
  Instance {
    dataValues: 
     { _id: null,
       email: 'jane.doe@bitbucket.com',
       createdAt: 2017-01-22T10:05:13.090Z,
       updatedAt: 2017-01-22T10:05:13.090Z },
    _previousDataValues: { email: undefined },
    _changed: { email: true },
    '$modelOptions': 
     { timestamps: true,
       instanceMethods: {},
       classMethods: {},
       validate: {},
       freezeTableName: false,
       underscored: false,
       underscoredAll: false,
       paranoid: false,
       rejectOnEmpty: false,
       whereCollection: null,
       schema: null,
       schemaDelimiter: '',
       defaultScope: {},
       scopes: [],
       hooks: {},
       indexes: [Object],
       name: [Object],
       omitNul: false,
       sequelize: [Object],
       uniqueKeys: {},
       hasPrimaryKeys: true },
    '$options': { isNewRecord: true, '$schema': null, '$schemaDelimiter': '' },
    hasPrimaryKeys: true,
    __eagerlyLoadedAssociations: [],
    isNewRecord: true } ]
```

Are you sure this index was not present before running the query ?

**Comment by nstuyvesant** [comment]
The error occurs on line 34 of [app.js](https://github.com/nstuyvesant/shy/blob/master/server/app.js) when there are no tables or indexes in the database. Here's my code that seeds the database: [seed.js](https://github.com/nstuyvesant/shy/blob/master/server/config/seed.js).

My connection options are:
```
  sequelize: {
    uri: process.env.DATABASE_URL,
    options: {
      logging: false,
      dialect: 'postgres',
      protocol: 'postgres',
      native: true,
      language: 'en'
    }
  } 
```
Here's the [User model: ](https://github.com/nstuyvesant/shy/blob/master/server/api/user/user.model.js)
The tables and index get created and seeded. If I restart the server, it works fine.

**Comment by sushantdhiman** [comment]
Show me full set of queries that execute from server start to this error

**Comment by nstuyvesant** [comment]
OK... I deleted all the tables then fired up the app so we're starting from scratch...

```
CREATE TABLE IF NOT EXISTS "Things" ("_id"   SERIAL , "name" VARCHAR(255), "info" VARCHAR(255), "active" BOOLEAN, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("_id"));
CREATE TABLE IF NOT EXISTS "Users" ("_id"   SERIAL , "name" VARCHAR(255), "email" VARCHAR(255), "role" VARCHAR(255) DEFAULT 'user', "password" VARCHAR(255), "provider" VARCHAR(255), "salt" VARCHAR(255), "facebook" JSON, "twitter" JSON, "google" JSON, "github" JSON, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, UNIQUE ("email"), PRIMARY KEY ("_id"));
SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'Things' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'Users' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
```

Getting a SequelizeUniqueConstraintError. Here's the .errors array:
```
{ SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/Users/nates/Documents/Development/test/node_modules/sequelize/lib/dialects/postgres/query.js:326:16)
    at .<anonymous> (/Users/nates/Documents/Development/test/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at NativeQuery.handleError (/Users/nates/Documents/Development/test/node_modules/pg/lib/native/query.js:66:10)
    at after (/Users/nates/Documents/Development/test/node_modules/pg/lib/native/query.js:84:19)
    at onError (/Users/nates/Documents/Development/test/node_modules/pg-native/index.js:160:5)
    at g (events.js:291:16)
    at emitOne (events.js:101:20)
    at emit (events.js:188:7)
    at Client._readError (/Users/nates/Documents/Development/test/node_modules/pg-native/index.js:81:8)
    at Client._read (/Users/nates/Documents/Development/test/node_modules/pg-native/index.js:121:19)
    at emitNone (events.js:86:13)
    at PQ.emit (events.js:185:7)
From previous event:
    at Query.run (/Users/nates/Documents/Development/test/node_modules/sequelize/lib/dialects/postgres/query.js:74:17)
    at /Users/nates/Documents/Development/test/node_modules/sequelize/lib/sequelize.js:849:20
    at /Users/nates/Documents/Development/test/node_modules/retry-as-promised/index.js:40:21
From previous event:
    at retryAsPromised (/Users/nates/Documents/Development/test/node_modules/retry-as-promised/index.js:30:10)
    at ConnectionManager.<anonymous> (/Users/nates/Documents/Development/test/node_modules/sequelize/lib/sequelize.js:848:12)
From previous event:
    at Promise.then (/Users/nates/Documents/Development/test/node_modules/sequelize/lib/promise.js:21:17)
    at Model.sync (/Users/nates/Documents/Development/test/node_modules/sequelize/lib/model.js:993:6)
    at /Users/nates/Documents/Development/test/node_modules/sequelize/lib/sequelize.js:1014:20
From previous event:
    at Function.each (/Users/nates/Documents/Development/test/node_modules/sequelize/lib/promise.js:21:17)
    at /Users/nates/Documents/Development/test/node_modules/sequelize/lib/sequelize.js:1013:20
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
From previous event:
    at Promise.then (/Users/nates/Documents/Development/test/node_modules/sequelize/lib/promise.js:21:17)
    at Sequelize.sync (/Users/nates/Documents/Development/test/node_modules/sequelize/lib/sequelize.js:1000:6)
    at Object.<anonymous> (/Users/nates/Documents/Development/test/server/app.js:30:17)
    at Module._compile (module.js:570:32)
    at loader (/Users/nates/Documents/Development/test/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/nates/Documents/Development/test/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/nates/Documents/Development/test/server/index.js:12:28)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
  name: 'SequelizeUniqueConstraintError',
  message: 'Validation error',
  errors: 
   [ { message: 'typname must be unique',
       type: 'unique violation',
       path: 'typname',
       value: 'Things__id_seq' },
     { message: 'typnamespace must be unique',
       type: 'unique violation',
       path: 'typnamespace',
       value: '2200' } ],
  fields: { typname: 'Things__id_seq', typnamespace: '2200' },
  parent: 
   { Error: ERROR:  duplicate key value violates unique constraint "pg_type_typname_nsp_index"
   DETAIL:  Key (typname, typnamespace)=(Things__id_seq, 2200) already exists.
   
       at Client._readError (/Users/nates/Documents/Development/test/node_modules/pg-native/index.js:80:13)
       at Client._read (/Users/nates/Documents/Development/test/node_modules/pg-native/index.js:121:19)
       at emitNone (events.js:86:13)
       at PQ.emit (events.js:185:7)
     severity: 'ERROR',
     sqlState: '23505',
     messagePrimary: 'duplicate key value violates unique constraint "pg_type_typname_nsp_index"',
     messageDetail: 'Key (typname, typnamespace)=(Things__id_seq, 2200) already exists.',
     sourceFile: 'nbtinsert.c',
     sourceLine: '433',
     sourceFunction: '_bt_check_unique',
     sql: 'CREATE TABLE IF NOT EXISTS "Things" ("_id"   SERIAL , "name" VARCHAR(255), "info" VARCHAR(255), "active" BOOLEAN, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("_id"));' },
  original: 
   { Error: ERROR:  duplicate key value violates unique constraint "pg_type_typname_nsp_index"
   DETAIL:  Key (typname, typnamespace)=(Things__id_seq, 2200) already exists.
   
       at Client._readError (/Users/nates/Documents/Development/test/node_modules/pg-native/index.js:80:13)
       at Client._read (/Users/nates/Documents/Development/test/node_modules/pg-native/index.js:121:19)
       at emitNone (events.js:86:13)
       at PQ.emit (events.js:185:7)
     severity: 'ERROR',
     sqlState: '23505',
     messagePrimary: 'duplicate key value violates unique constraint "pg_type_typname_nsp_index"',
     messageDetail: 'Key (typname, typnamespace)=(Things__id_seq, 2200) already exists.',
     sourceFile: 'nbtinsert.c',
     sourceLine: '433',
     sourceFunction: '_bt_check_unique',
     sql: 'CREATE TABLE IF NOT EXISTS "Things" ("_id"   SERIAL , "name" VARCHAR(255), "info" VARCHAR(255), "active" BOOLEAN, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("_id"));' },
  sql: 'CREATE TABLE IF NOT EXISTS "Things" ("_id"   SERIAL , "name" VARCHAR(255), "info" VARCHAR(255), "active" BOOLEAN, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("_id"));' }
```

**Comment by nstuyvesant** [comment]
By, the way... I tried with both 3.30.0 and 4.0.0-2. An odd behavior of 4.0.0-2 is that it ran:
```
CREATE TABLE IF NOT EXISTS "Things" ("_id"   SERIAL , "name" VARCHAR(255), "info" VARCHAR(255), "active" BOOLEAN, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("_id"));
```
twice.

**Comment by nstuyvesant** [comment]
Sorry... false alarm. There was more than one call to .sync().
