### ISSUE TITLE
Tests Fail and test/integration/assets/es6project.js gets deleted

### ISSUE THREAD

**Issue by LoneWolfPR** [sequelize/sequelize#7143]
I'm trying to solve another issue I reported so I got the repo pulled down and set up. When I run `DIALECT=postgres npm test` though it runs for a file and ends with the following:
```
  1) [POSTGRES] DataTypes should parse an empty GEOMETRY field:
     SequelizeDatabaseError: Too few ordinates in GeoJSON
      at Query.formatError (lib/dialects/postgres/query.js:357:14)
      at Query.<anonymous> (lib/dialects/postgres/query.js:88:19)
      at Query.handleError (node_modules/pg/lib/query.js:108:8)
      at Connection.<anonymous> (node_modules/pg/lib/client.js:171:26)
      at Socket.<anonymous> (node_modules/pg/lib/connection.js:109:12)
      at readableAddChunk (_stream_readable.js:176:18)
      at Socket.Readable.push (_stream_readable.js:134:10)
      at TCP.onread (net.js:548:20)
  From previous event:
      at Query.run (lib/dialects/postgres/query.js:74:17)
      at lib/sequelize.js:849:20
      at node_modules/retry-as-promised/index.js:40:21
  From previous event:
      at retryAsPromised (node_modules/retry-as-promised/index.js:30:10)
      at lib/sequelize.js:848:12
  From previous event:
      at Promise.then (lib/promise.js:21:17)
      at Context.<anonymous> (test/integration/data-types.test.js:286:43)

  2) [POSTGRES] Sequelize authenticate with an invalid connection triggers the actual adapter error:
     AssertionError: expected null to be truthy
      at .<anonymous> (node_modules/chai/lib/chai/core/assertions.js:258:10)
      at addProperty (node_modules/chai/lib/chai/utils/addProperty.js:43:29)
      at doAsserterAsyncAndAddThen (node_modules/chai-as-promised/lib/chai-as-promised.js:296:33)
      at .<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:286:25)
      at get (node_modules/chai/lib/chai/utils/overwriteProperty.js:50:37)
      at test/integration/sequelize.test.js:134:22
  From previous event:
      at Promise.then (lib/promise.js:21:17)
      at Promise.catch (lib/promise.js:21:17)
      at Context.<anonymous> (test/integration/sequelize.test.js:126:19)
```

Then, if I run again it fails, but this time because it can't find `test/integration/assets/es6project.js`. A quick `git status` shows that, that file is now flagged for deletion. So, if a test fails I have to make sure the discard changes on that file to bring it back. I'd really like to fix the other issue I discovered, but I can't get passing tests until this is resolved.

postgres v9.6.1
sequelize v 3.30.0

**Comment by sushantdhiman** [comment]
This happens when you switch between `v3` and `master` branch and run tests.

I remember fixing this for `master` https://github.com/sequelize/sequelize/commit/5497f35a36fcd73e64da8d9ed4a7bd7ac5238131#diff-23797c4f52e452f7c44f18458cc223edL1185

You can submit PR for`v3` where you can remove `after` hook

**Comment by LoneWolfPR** [comment]
@sushantdhiman does this address just the issue of the file disappearing? If so, do you have any answer as to why the two tests are failing even before I add any code?

**Comment by LoneWolfPR** [comment]
Ok. I've fixed this in V3. The problem is I still get the errors I mentioned above. These were present before any code change. Is there something I should do about them or just issue the PR and mention that they are there?

**Comment by sushantdhiman** [comment]
@LoneWolfPR just send the PR, if CI pass we will merge
