### ISSUE TITLE
A query fails with "TypeError: val.replace is not a function" on column of type DATE

### ISSUE THREAD

**Issue by jraut** [sequelize/sequelize#7158]
## What you are doing?

I have a system of 20-or-so models which are associated to each other. The environment is duplicated for development and production and run the same software. 
 
No differences in current non-deleted data but different history on both databases. 

I run the following code:
```js
const byLastLogin = () => db.User.findAll({
  where: {
    last_login: { $and: [{ $ne: null }, { $gt: moment().subtract({ months: 1 }) }] },
  },
});
```

The column last_login is of type DATE.

## What do you expect to happen?
There ought to be a list of users. 

## What is actually happening?
The query on another environment returns a promise with an array of instances.
On another environment it returns the following error:
```
Unhandled rejection TypeError: val.replace is not a function
    at Object.SqlString.escape (/directory/node_modules/sequelize/lib/sql-string.js:61:15)
    at Object.escape (/directory/node_modules/sequelize/lib/dialects/abstract/query-generator.js:978:22)
    at Object.whereItemQuery (/directory/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2362:22)
    at /directory/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1993:25
    at /directory/node_modules/sequelize/node_modules/lodash/lodash.js:4389:15
    at baseForOwn (/directory/node_modules/sequelize/node_modules/lodash/lodash.js:2652:24)
    at Function.forOwn (/directory/node_modules/sequelize/node_modules/lodash/lodash.js:12254:24)
    at Object.whereItemsQuery (/directory/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1992:9)
    at /directory/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2116:32
    at Array.map (native)
    at Object.whereItemQuery (/directory/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2115:23)
    at /directory/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1993:25
    at /directory/node_modules/sequelize/node_modules/lodash/lodash.js:4389:15
    at baseForOwn (/directory/node_modules/sequelize/node_modules/lodash/lodash.js:2652:24)
    at Function.forOwn (/directory/node_modules/sequelize/node_modules/lodash/lodash.js:12254:24)
    at Object.whereItemsQuery (/directory/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1992:9)
    at Object.getWhereConditions (/directory/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2427:19)
    at Object.selectQuery (/directory/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1529:28)
    at QueryInterface.select (/directory/node_modules/sequelize/lib/query-interface.js:669:25)
    at Model.<anonymous> (/directory/node_modules/sequelize/lib/model.js:1398:32)
    at bound (domain.js:280:14)
    at Model.runBound (domain.js:293:12)
```

The query works on both environments if 

```js
moment().subtract({ months: 1 })
``` 
is replaced with either of the following: 
```js
moment().subtract({ months: 1 }).format()
``` 
```js
new Date()
```

- Postgres 9.5.4
- Sequelize 3.30.0
- momentjs 2.15.2

**Comment by Aukhan** [comment]
Im not sure if this can be counted as a bug, have seen this situation and been using `.format()` or in other words stringified dates for any such comparisons. To be more specific you should mention your date format e.g `YYYY-MM-DD` in the format method based on your date column type for an accurate comparison.
You can see from the stack trace that the query generator expects a string there and is trying to escape values from there whereas it gets an Object or instance of Moment which does not have a `.replace` method in its prototype.

**Comment by jraut** [comment]
This was double-verified with identical code on identical environments. The db contents are identical and so is the schema. The db history differs.

```js
const User = sequelize.define('User', { last_login: DataTypes.DATE}, { tableName: 'usertable', underscored: true });

const moment = require('moment');
User.findAll({ where: { last_login: { $lt: moment().subtract({ months: 1 }) } } }).then(u => cosole.log(u)));
```

The code returns the expected content on the other server but fails with the error message in the original post. This is probably not a bug but reporting since the behaviour differs. I guess it could be due to differences in dependencies which I will verify more dilligently at some time.

**Comment by Aukhan** [comment]
Can you turn on logging and find out the SQL that is created on each environment, that should help clear out the confusion.

**Comment by jraut** [comment]
This was due to memory errors, it seems. 

The query was a part of wide promise chain of functions (parallel, nested), which resulted in exceeding the memory resources on the server. After modifying the code, nodejs started throwing errors like `Promise.then is not a function` and similar and the error message changed in form (Object and it's method were different at times). Nesting was done in reduce-pattern.

The server had 1Gb of virtual physical memory which does get filled quite fast with a db engine and nodejs/express running some nested asynchronous queries. 

Sorry for the confusion!

**Comment by Aukhan** [comment]
That does sound ambiguous but glad it was resolved for you.
I've found myself raising issues in Sequelize while the problem would lie elsewhere, please close this issue at your convenience.
Thanks.
