### ISSUE TITLE
Regression when using attributes as part of scope

### ISSUE THREAD

**Issue by buffpojken** [sequelize/sequelize#7216]
When using `{attributes: {include: [...]}` as part of a scope, the query crashes with ```Unhandled rejection TypeError: include.attributes.map is not a function``` resulting from the expectation that attributes is an array on #1129 of query-generator.js. 

This used to work just fine.

## What you are doing?
Setting the following as a scope. 
```js
          return {
            attributes: {
              include: [
                [sequelize.literal('(select "organisation_participation_id" from "participations" where "session_id" = "'+session_referencer+'.Session"."id" and "role" = \'owner\')'), 'owner']
              ]
            }
          };
```

## What do you expect to happen?
I expect the attributes specified to be included. 

## What is actually happening?
```
Unhandled rejection TypeError: include.attributes.map is not a function
    at generateJoinQueries (/Users/buffpojken/Projects/javascript/pr2-core/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1130:43)
    at /Users/buffpojken/Projects/javascript/pr2-core/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1390:36
    at Array.forEach (native)
    at generateJoinQueries (/Users/buffpojken/Projects/javascript/pr2-core/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1388:14)
    at Object.<anonymous> (/Users/buffpojken/Projects/javascript/pr2-core/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1409:27)
    at Array.forEach (native)
    at Object.selectQuery (/Users/buffpojken/Projects/javascript/pr2-core/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1408:10)
    at QueryInterface.select (/Users/buffpojken/Projects/javascript/pr2-core/node_modules/sequelize/lib/query-interface.js:669:25)
    at Model.<anonymous> (/Users/buffpojken/Projects/javascript/pr2-core/node_modules/sequelize/lib/model.js:1398:32)
    at Model.tryCatcher (/Users/buffpojken/Projects/javascript/pr2-core/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/buffpojken/Projects/javascript/pr2-core/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/Users/buffpojken/Projects/javascript/pr2-core/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/buffpojken/Projects/javascript/pr2-core/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/buffpojken/Projects/javascript/pr2-core/node_modules/bluebird/js/release/promise.js:684:18)
    at Async._drainQueue (/Users/buffpojken/Projects/javascript/pr2-core/node_modules/bluebird/js/release/async.js:126:16)
    at Async._drainQueues (/Users/buffpojken/Projects/javascript/pr2-core/node_modules/bluebird/js/release/async.js:136:10)
    at Immediate.Async.drainQueues (/Users/buffpojken/Projects/javascript/pr2-core/node_modules/bluebird/js/release/async.js:16:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

__Dialect:__ postgres
__Sequelize version:__ 3.30.1

**Comment by sushantdhiman** [comment]
Is `master` affected by this issue ?

**Comment by buffpojken** [comment]
Currently, we're unable to run 4.0-pre due to the changes but I'll check once we've upgraded!
