### ISSUE TITLE
Sequelize.BOOLEAN throws TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by dinusuresh** [sequelize/sequelize#7231]
Trying to create a table with a boolean field.

Here is the respective migration file:
```
'use strict';

module.exports = {
  up: function (queryInterface, Sequelize) {
    return queryInterface.createTable('sample_table', {
      id: {
        allowNull: false,
        primaryKey: true,
        type: Sequelize.UUID
      },
      heading: {
        type: Sequelize.STRING
      },
      description: {
        allowNull: false,
        type: Sequelize.TEXT
      },
      options: {
        allowNull: false,
        type: Sequelize.JSON
      },
      verified: {
        allowNull: false,
        defaultValue: false,
        type: Sequelize.BOOLEAN,
      },
      createdAt: {
        allowNull: false,
        defaultValue: Sequelize.literal('CURRENT_TIMESTAMP'),
        type: Sequelize.DATE
      },
      updatedAt: {
        allowNull: false,
        defaultValue: Sequelize.literal('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
        type: Sequelize.DATE
      },
      deletedAt: {
        type: Sequelize.DATE
      }
    });
  },

  down: function (queryInterface, Sequelize) {
    return queryInterface.dropTable('sample_table');
  }
};

```

Below is the error faced when the migrating using cli.

```
Sequelize [Node: 6.9.2, CLI: 2.5.1, ORM: 3.30.1, mysql: ^2.13.0]

Loaded configuration file "config/config.json".
Using environment "development".
== 20170210113549-create_sample_table: migrating =======
TypeError: Cannot read property 'toString' of undefined
    at Object.attributeToSQL (/home/user/sample-api/node_modules/sequelize/lib/dialects/mysql/query-generator.js:240:34)
    at Object.attributesToSQL (/home/user/sample-api/node_modules/sequelize/lib/dialects/mysql/query-generator.js:306:45)
    at QueryInterface.createTable (/home/user/sample-api/node_modules/sequelize/lib/query-interface.js:171:38)
    at Object.up (/home/user/sample-api/migrations/20170210113549-create_sample_table.js:12:27)
    at constructor._exec (/home/user/sample-api/node_modules/umzug/lib/migration.js:103:23)
    at constructor.up (/home/user/sample-api/node_modules/umzug/lib/migration.js:69:17)
    at constructor.<anonymous> (/home/user/sample-api/node_modules/umzug/index.js:124:28)
From previous event:
    at Promise.tap (/home/user/sample-api/node_modules/sequelize/lib/promise.js:21:17)
    at /home/user/sample-api/node_modules/umzug/index.js:105:14
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at Function.each (/home/user/sample-api/node_modules/sequelize/lib/promise.js:21:17)
    at /home/user/sample-api/node_modules/umzug/index.js:94:25
From previous event:
    at Promise.then (/home/user/sample-api/node_modules/sequelize/lib/promise.js:21:17)
    at Object.task (/home/user/sample-api/node_modules/sequelize-cli/lib/tasks/db.js:24:39)
    at Gulp.gulp.task.aliases (/home/user/sample-api/node_modules/sequelize-cli/lib/helpers/gulp-helper.js:14:14)
    at module.exports (/home/user/sample-api/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/user/sample-api/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/user/sample-api/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/user/sample-api/node_modules/orchestrator/index.js:134:8)
    at /home/user/sample-api/node_modules/gulp/bin/gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

Removing the boolean field (verified), runs the migration successfully.

**_Mysql version: 5.7_**
**_Node: 6.9.2, CLI: 2.5.1
ORM: 3.30.1
mysql: ^2.13.0_**

OS: Elementary OS 0.4 Loki - (Ubuntu 16.04)

**Comment by dinusuresh** [comment]
The migration ran successfully. Though I cannot pinpoint the error root,

 - Deleted old migration and created new file.
 - Ran migration from new terminal.

_-- closing issue. --_
