### ISSUE TITLE
Adding a Foreign key relation to multiple tables

### ISSUE THREAD

**Issue by shivambarsaley** [sequelize/sequelize#7267]
## Trying to add a foreign key relationship from a table to multiple tables via migrations
_Below is a demo of the problem on a simple School Application_

### Student Model
```js
  const Student = sequelize.define('Student', {
    name: { allowNull: false, type: DataTypes.STRING },
    description: DataTypes.STRING,
    status: { allowNull: false, type: DataTypes.STRING, defaultValue: 'Active' }
  }, {
    classMethods: {
      associate: function (models) {
        Student.hasMany(models.Subject);
      }
    }
  });
```

### Subject Model

```js
const Subject = sequelize.define('Student', {
    name: { allowNull: false, type: DataTypes.STRING },
    description: DataTypes.STRING,
    status: { allowNull: false, type: DataTypes.STRING, defaultValue: 'Active' }
  }, {
    classMethods: {
      associate: function (models) {
        Subject.hasMany(models.student);
      }
    }
  });
```

### Teachers Model

```js
const Teacher = sequelize.define('Teacher', {
    name: { allowNull: false, type: DataTypes.STRING },
    description: DataTypes.STRING,
    status: { allowNull: false, type: DataTypes.STRING, defaultValue: 'Active' }
  }, {
    classMethods: {
      associate: function (models) {
         Teacher.hasMany(models.subject);
      }
    }
  });
```

Also I have created migrations to add the foreign key relationships

### Adding subjectId in students

```js
module.exports = {
  up: function (queryInterface, Sequelize) {

    return queryInterface.addColumn('Students',
      'SubjectId',
      {
        type: Sequelize.INTEGER,
        allowNull: false,
        defaultValue: 0,
        references: { model: 'Subjects', key: 'id' }
      }
    )
  },

  down: function (queryInterface, Sequelize) {

    return queryInterface.removeColumn('Students', 'SubjectId')
  }
```

### Adding subjectId in Teachers

```js
'use strict';

module.exports = {
  up: function (queryInterface, Sequelize) {

    return queryInterface.addColumn('Teachers',
      'SubjectId',
      {
        type: Sequelize.INTEGER,
        allowNull: false,
        defaultValue: 0,
        references: { model: 'Subjects', key: 'id' }
      }
    )
  },

  down: function (queryInterface, Sequelize) {

    return queryInterface.removeColumn('Teachers', 'SubjectId')
  }
};
```

## Upon running the migrations

The migrations for adding the subjectId in Student table goes well but fails for the teachers table with the error as
```js

== 20170216125853-AddingSubjectRelationToStudent: migrating =======
== 20170216125853-AddingSubjectRelationToStudent: migrated (0.033s)
== 20170216125855-AddingSubjectRelationToTeacher: migrating =======
{ SequelizeDatabaseError: ER_DUP_KEY: Can't write; duplicate key in table '#sql-d52_1e69'
    at Query.formatError (/Users/shivambarsaley/Desktop/Spikes/StudentSample/node_modules/sequelize/lib/dialects/mysql/query.js:175:14)
    at Query._callback (/Users/shivambarsaley/Desktop/Spikes/StudentSample/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
    at Query.Sequence.end (/Users/shivambarsaley/Desktop/Spikes/StudentSample/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at Query.ErrorPacket (/Users/shivambarsaley/Desktop/Spikes/StudentSample/node_modules/mysql/lib/protocol/sequences/Query.js:88:8)
    at Protocol._parsePacket (/Users/shivambarsaley/Desktop/Spikes/StudentSample/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/Users/shivambarsaley/Desktop/Spikes/StudentSample/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/Users/shivambarsaley/Desktop/Spikes/StudentSample/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/shivambarsaley/Desktop/Spikes/StudentSample/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
  name: 'SequelizeDatabaseError',
  message: 'ER_DUP_KEY: Can\'t write; duplicate key in table \'#sql-d52_1e69\'',
  parent:
   { Error: ER_DUP_KEY: Can't write; duplicate key in table '#sql-d52_1e69'
       at Query.Sequence._packetToError (/Users/shivambarsaley/Desktop/Spikes/StudentSample/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
       at Query.ErrorPacket (/Users/shivambarsaley/Desktop/Spikes/StudentSample/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
       at Protocol._parsePacket (/Users/shivambarsaley/Desktop/Spikes/StudentSample/node_modules/mysql/lib/protocol/Protocol.js:280:23)
       at Parser.write (/Users/shivambarsaley/Desktop/Spikes/StudentSample/node_modules/mysql/lib/protocol/Parser.js:75:12)
       at Protocol.write (/Users/shivambarsaley/Desktop/Spikes/StudentSample/node_modules/mysql/lib/protocol/Protocol.js:39:16)
       at Socket.<anonymous> (/Users/shivambarsaley/Desktop/Spikes/StudentSample/node_modules/mysql/lib/Connection.js:103:28)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:188:7)
       at readableAddChunk (_stream_readable.js:176:18)
       at Socket.Readable.push (_stream_readable.js:134:10)
       at TCP.onread (net.js:543:20)
       --------------------
       at Protocol._enqueue (/Users/shivambarsaley/Desktop/Spikes/StudentSample/node_modules/mysql/lib/protocol/Protocol.js:141:48)
       at Connection.query (/Users/shivambarsaley/Desktop/Spikes/StudentSample/node_modules/mysql/lib/Connection.js:208:25)
       at /Users/shivambarsaley/Desktop/Spikes/StudentSample/node_modules/sequelize/lib/dialects/mysql/query.js:40:21
       at Promise._execute (/Users/shivambarsaley/Desktop/Spikes/StudentSample/node_modules/bluebird/js/release/debuggability.js:300:9)
       at Promise._resolveFromExecutor (/Users/shivambarsaley/Desktop/Spikes/StudentSample/node_modules/bluebird/js/release/promise.js:481:18)
       at new Promise (/Users/shivambarsaley/Desktop/Spikes/StudentSample/node_modules/bluebird/js/release/promise.js:77:14)
       at Query.run (/Users/shivambarsaley/Desktop/Spikes/StudentSample/node_modules/sequelize/lib/dialects/mysql/query.js:39:17)
       at /Users/shivambarsaley/Desktop/Spikes/StudentSample/node_modules/sequelize/lib/sequelize.js:849:20
       at /Users/shivambarsaley/Desktop/Spikes/StudentSample/node_modules/retry-as-promised/index.js:40:21
       at Promise._execute (/Users/shivambarsaley/Desktop/Spikes/StudentSample/node_modules/bluebird/js/release/debuggability.js:300:9)
       at Promise._resolveFromExecutor (/Users/shivambarsaley/Desktop/Spikes/StudentSample/node_modules/bluebird/js/release/promise.js:481:18)
       at new Promise (/Users/shivambarsaley/Desktop/Spikes/StudentSample/node_modules/bluebird/js/release/promise.js:77:14)
       at retryAsPromised (/Users/shivambarsaley/Desktop/Spikes/StudentSample/node_modules/retry-as-promised/index.js:30:10)
       at /Users/shivambarsaley/Desktop/Spikes/StudentSample/node_modules/sequelize/lib/sequelize.js:848:12
       at tryCatcher (/Users/shivambarsaley/Desktop/Spikes/StudentSample/node_modules/bluebird/js/release/util.js:16:23)
       at Promise._settlePromiseFromHandler (/Users/shivambarsaley/Desktop/Spikes/StudentSample/node_modules/bluebird/js/release/promise.js:510:31)
     code: 'ER_DUP_KEY',
     errno: 1022,
     sqlState: '23000',
     index: 0,
     sql: 'ALTER TABLE `Teachers` ADD `SubjectId` INTEGER NOT NULL DEFAULT 0, ADD CONSTRAINT `SubjectId_foreign_idx` FOREIGN KEY (`SubjectId`) REFERENCES `Subjects` (`id`);' },
```

Is there something I am doing wrong or missing out ??

__Dialect:__ mysql 
__Database version: 5.7.15
__Sequelize version: Node: 6.5.0, CLI: 2.5.1, ORM: 3.30.2, mysql: ^2.13.0

**Comment by sushantdhiman** [comment]
Seuquelize generate foreignKey name from `model_attr_idx`, this is resulting in naming collisions. This will be fixed by https://github.com/sequelize/sequelize/issues/5212

**Comment by aboveyou00** [comment]
Is there a workaround until then? I really don't want to rename my columns...

**Comment by sushantdhiman** [comment]
This is fixed by addConstraint method that will be available in `v4` (master) https://github.com/sequelize/sequelize/issues/5212
