### ISSUE TITLE
A proposal for more friendly error stacks

### ISSUE THREAD

**Issue by luin** [sequelize/sequelize#7273]
Currently, the error stacks are not much helpful because of the jumps back and forth in the async code. For instance the following code in "myapp.js`:

```javascript
'use strict';

const db = require('./models');

function getUserById(id) {
  // ** I misspelled the field name here...
  return db.User.findOne({ where: { idd: id } });
}

function main() {
  getUserById(process.argv[2]).then(console.log);
}

main();
```

When I ran `node myapp.js 9965`, I got the following error stack:

```
Unhandled rejection SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'User.idd' in 'where clause'
    at Query.formatError (/Users/luin/api/node_modules/sequelize/lib/dialects/mysql/query.js:175:14)
    at Query._callback (/Users/luin/api/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
    at Query.Sequence.end (/Users/luin/api/node_modules/mysql/lib/protocol/sequences/Sequence.js:85:24)
    at Query.ErrorPacket (/Users/luin/api/node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
    at Protocol._parsePacket (/Users/luin/api/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/Users/luin/api/node_modules/mysql/lib/protocol/Parser.js:74:12)
    at Protocol.write (/Users/luin/api/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/luin/api/node_modules/mysql/lib/Connection.js:109:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

Nothing helpful here for further debugging. In this case, the program is dead simple so it's not hard to point out where is the issue (by searching `User.idd`). However, if we are dealing with a complex application, it would be a disaster to debug with such error stacks.

To solve the problem, we can simply capture the current stack and replace the actual error with it. Here are some changes I have made on the sequelize v3:

```javascript
Model.prototype.findOne = function(options) {
  if (options !== undefined && !_.isPlainObject(options)) {
    throw new Error('The argument passed to findOne must be an options object, use findById if you wish to pass a single primary key value');
  }
  // ** change 1
  const localerror = new Error()
  options = Utils.cloneDeep(options);

  if (options.limit === undefined) {
    var pkVal = options.where && options.where[this.primaryKeyAttribute];

    // Don't add limit if querying directly on the pk
    if (!options.where || !(Utils.isPrimitive(pkVal) || Buffer.isBuffer(pkVal))) {
      options.limit = 1;
    }
  }

  // Bypass a possible overloaded findAll.
  return Model.prototype.findAll.call(this, _.defaults(options, {
    plain: true,
    rejectOnEmpty: false
  }))
  // * change 2
  .catch(function (err) {
      throw optimizeErrorStack(err, localerror.stack, __dirname);
  })
};

function optimizeErrorStack(error, friendlyStack, filterPath) {
  var stacks = friendlyStack.split('\n');
  var lines = '';
  var i;
  for (i = 1; i < stacks.length; ++i) {
    if (stacks[i].indexOf(filterPath) === -1) {
      break;
    }
  }
  for (var j = i; j < stacks.length; ++j) {
    lines += '\n' + stacks[j];
  }
  var pos = error.stack.indexOf('\n');
  error.stack = error.stack.slice(0, pos) + lines;
  return error;
};

```

And then restart myapp.js, the error stacks will be:

```
Unhandled rejection SequelizeDatabaseError: ER_BAD_FIELD_ERROR: Unknown column 'User.idd' in 'where clause'
    at getUserById (/Users/luin/api/myapp.js:6:18)
    at main (/Users/luin/api/myapp.js:10:3)
    at Object.<anonymous> (/Users/luin/api/myapp.js:13:1)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by jeremybradbury** [comment]
this needs a reopen and PR

**Comment by luin** [comment]
Any thoughts on this proposal? @sushantdhiman @janmeier
