### ISSUE TITLE
Unhandled rejection SequelizeForeignKeyConstraintError: ER_NO_REFERENCED_ROW_2:

### ISSUE THREAD

**Issue by Adiii717** [sequelize/sequelize#7293]
not able to catch the above error. it's crash my apps.
Although I use express handler but not work
`model.bulkCreate(helpers, {individualHooks: true})
                        .then(function (helper) {
                            res.status(200).json({"message":"done"});
                        })
                        .catch(function (err) {
                            res.status(500).json(err)
                        })`

here is my connection
`models.sequelize
        .authenticate()
        .then(function () {
            console.log('Connection successful');
        })
        .catch(function(error) {
            res.status(500).json(error);
            console.log("Error creating connection:", error);
        });`

Here is the error
```

Unhandled rejection SequelizeForeignKeyConstraintError: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`cg_taskview`.`tasks`, CONSTRAINT `fk_userid` FOREIGN KEY (`userId`) REFERENCES `users` (`id`))
    at Query.formatError (D:\CG\schema change 22-2\CG_Taskview\app\node_modules\sequelize\lib\dialects\mysql\query.js:168:14)
    at Query._callback (D:\CG\schema change 22-2\CG_Taskview\app\node_modules\sequelize\lib\dialects\mysql\query.js:49:21)
    at Query.Sequence.end (D:\CG\schema change 22-2\CG_Taskview\app\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Query.ErrorPacket (D:\CG\schema change 22-2\CG_Taskview\app\node_modules\mysql\lib\protocol\sequences\Query.js:88:8)
    at Protocol._parsePacket (D:\CG\schema change 22-2\CG_Taskview\app\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (D:\CG\schema change 22-2\CG_Taskview\app\node_modules\mysql\lib\protocol\Parser.js:75:12)
    at Protocol.write (D:\CG\schema change 22-2\CG_Taskview\app\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (D:\CG\schema change 22-2\CG_Taskview\app\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)

```

**Comment by janmeier** [comment]
That sounds very weird - I've never heard of being unable to catch an error on a promise. Probably something else is at play

If you still experience this issue, try to create a [SSCCE](HTTP://SSCCE.ORG/)
