### ISSUE TITLE
Invalid value UUIDV1

### ISSUE THREAD

**Issue by airyland** [sequelize/sequelize#7295]
Can't set default value for UUID type field, also I cannot use NOW as default value for TIME type field.

```js
const Sms = sequelize.define('sms', {
  sms_id: {
    type: Sequelize.UUID,
    defaultValue: Sequelize.UUIDV1
  }
})
```

``` bash
Error: Invalid value UUIDV1
    at Object.escape (/Users/lizheng/workspace/vux-design/trade/node_modules/Sequelize/lib/sql-string.js:59:11)
    at Object.escape (/Users/lizheng/workspace/vux-design/trade/node_modules/Sequelize/lib/dialects/abstract/query-generator.js:949:22)
    at Object.insertQuery (/Users/lizheng/workspace/vux-design/trade/node_modules/Sequelize/lib/dialects/abstract/query-generator.js:284:28)
    at QueryInterface.insert (/Users/lizheng/workspace/vux-design/trade/node_modules/Sequelize/lib/query-interface.js:467:37)
    at Promise.try.then.then.then (/Users/lizheng/workspace/vux-design/trade/node_modules/Sequelize/lib/model.js:3385:56)
    at tryCatcher (/Users/lizheng/workspace/vux-design/trade/node_modules/Sequelize/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/lizheng/workspace/vux-design/trade/node_modules/Sequelize/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/lizheng/workspace/vux-design/trade/node_modules/Sequelize/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/lizheng/workspace/vux-design/trade/node_modules/Sequelize/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/lizheng/workspace/vux-design/trade/node_modules/Sequelize/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/lizheng/workspace/vux-design/trade/node_modules/Sequelize/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/lizheng/workspace/vux-design/trade/node_modules/Sequelize/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/lizheng/workspace/vux-design/trade/node_modules/Sequelize/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```
Dialect: postgres 
Database version: 9.6
Sequelize version: 4.0.0-2

**Comment by janmeier** [comment]
Seems to work fine for me on latest master

```js
const Sms = sequelize.define('sms', {
  sms_id: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV1
  },
  now: {
    type: DataTypes.DATE,
    defaultValue: Sequelize.NOW
  }
});

return sequelize.sync({
  force: true,
  logging: console.log
})
  .then(() => {
    return Sms.create({});
  })
  // .then(result => console.log(result))
  .finally(() => {
    sequelize.close();
  });
```
```
Executing (default): DROP TABLE IF EXISTS "sms" CASCADE;
Executing (default): DROP TABLE IF EXISTS "sms" CASCADE;
Executing (default): CREATE TABLE IF NOT EXISTS "sms" ("id"   SERIAL , "sms_id" UUID, "now" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'sms' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
Executing (default): INSERT INTO "sms" ("id","sms_id","now","createdAt","updatedAt") VALUES (DEFAULT,'f08cb860-fe7d-11e6-b989-e1716ded6438','2017-03-01 12:52:34.000 +00:00','2017-03-01 12:52:34.151 +00:00','2017-03-01 12:52:34.151 +00:00') RETURNING *;
```

We also have several integration tests using this https://github.com/sequelize/sequelize/blob/7029d2d6ba82c20af529c42f71eadc1615921851/test/integration/instance/update.test.js.

Please reopen if you can create a complete [SSCCE](HTTP://SSCCE.ORG/)
