### ISSUE TITLE
Missing where attribute in the options parameter passed to findOrInitialize.

### ISSUE THREAD

**Issue by wzup** [sequelize/sequelize#7300]
Why does the error happen? What does the error mean? I don't need `where` attribute  in my query params, I query with `include`.

The code that throws:
```
User.findOrInitialize({
    include: [
        { model: ExtUser, where: { id: req.body.userId } }
    ]
})
.spread((user, initialized) => {
    res.status(200).json({error: null, user: user, initialized: initialized});
})
.catch(e => {
    res.status(500).json({error: e, message: e.message});
});
```

The error:
```
C:\Users\user\app\app.js [ERROR env=dev] err: Error: Missing where attribute in the options parameter passed to findOrInitialize. Please note that the API has changed, and is now options only (an object with where, defaults keys, transaction etc.)
    at Model.findOrInitialize.Model.findOrBuild (C:\Users\user\app\node_modules\sequelize\lib\model.js:1840:11)
    at router.post (C:\Users\user\app\routes\routes.js:465:17)
    at Layer.handle [as handle_request] (C:\Users\user\app\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\user\app\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (C:\Users\user\app\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\user\app\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\user\app\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (C:\Users\user\app\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Users\user\app\node_modules\express\lib\router\index.js:271:10)
    at router.use (C:\Users\user\app\routes\routes.js:405:5)
    at Layer.handle [as handle_request] (C:\Users\user\app\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\user\app\node_modules\express\lib\router\index.js:312:13)
    at C:\Users\user\app\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\Users\user\app\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Users\user\app\node_modules\express\lib\router\index.js:271:10)
    at Function.handle (C:\Users\user\app\node_modules\express\lib\router\index.js:176:3)
```

**Comment by sushantdhiman** [comment]
> Find a row that matches the query, or build (but don't save) the row if none is found. The successful result of the promise will be (instance, initialized) - Make sure to use .spread()

How will it find something without where ?

I dont understand what are you even trying to do here, are you using `findOrInitialize` to prepare an response object of certain shape. Because I doubt that `findOrInitialize` not supposed to work with includes
