### ISSUE TITLE
Deadlock found when trying to get lock; try restarting transaction

### ISSUE THREAD

**Issue by vixa2012** [sequelize/sequelize#7313]
Hello. We has two the same servers. Each server get requests and each 5 minutes run script to export data from redis to mysql. Export script use bulkInsert and update

Some time we can see the problem. First server run export script and it lock table, then second script can't work with table.

We use mysql 5.7 version and
 "sequelize": "~4.0.0-2",
  "sequelize-cli": "~2.5.1",

Can you help me repait this bug?

```
{ Error: Deadlock found when trying to get lock; try restarting transaction
       at Packet.asError (www/server/node_modules/mysql2/lib/packets/packet.js:667:13)
       at Query.Command.execute (www/server/node_modules/mysql2/lib/commands/command.js:29:22)
       at Connection.handlePacket (www/server/node_modules/mysql2/lib/connection.js:417:28)
       at PacketParser.onPacket (www/server/node_modules/mysql2/lib/connection.js:93:16)
       at PacketParser.executeStart (www/server/node_modules/mysql2/lib/packet_parser.js:73:14)
       at Socket.<anonymous> (www/server/node_modules/mysql2/lib/connection.js:101:29)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:188:7)
       at readableAddChunk (_stream_readable.js:176:18)
       at Socket.Readable.push (_stream_readable.js:134:10)
       at TCP.onread (net.js:548:20)
     code: 'ER_LOCK_DEADLOCK',
     errno: 1213,
     sqlState: '#40001',
     sql: 'stats SET start = start + 0, firstquartile = firstquartile + 0, midpoint = midpoint + 0, thirdquartile = thirdquartile + 0, complete = complete + 0, close = close + 0, pause = pause + 0, resume = resume + 0, acceptinvitationlinear = acceptinvitationlinear + 0, timespentviewin = timespentviewin + 0, otheradinteraction = otheradinteraction + 0, progress = progress + 0, creativeview = creativeview + 0, mute = mute + 0, unmute = unmute + 0, fullscreen = fullscreen + 0, impression = impression + 0, error = error + 3, click = click + 0, nonlinearclickthrough = nonlinearclickthrough + 0, companionclickthrough = companionclickthrough + 0, requests = requests + 3, bad_requests = bad_requests + 0, empty_body = empty_body + 0, bad_vast = bad_vast + 0, exceptions = exceptions + 0 WHERE statKey = \'0e54a6d334e13c4952bbee373f2b652d\'' },
  sql: 'UPDATE stats SET start = start + 0, firstquartile = firstquartile + 0, midpoint = midpoint + 0, thirdquartile = thirdquartile + 0, complete = complete + 0, close = close + 0, pause = pause + 0, resume = resume + 0, acceptinvitationlinear = acceptinvitationlinear + 0, timespentviewin = timespentviewin + 0, otheradinteraction = otheradinteraction + 0, progress = progress + 0, creativeview = creativeview + 0, mute = mute + 0, unmute = unmute + 0, fullscreen = fullscreen + 0, impression = impression + 0, error = error + 3, click = click + 0, nonlinearclickthrough = nonlinearclickthrough + 0, companionclickthrough = companionclickthrough + 0, requests = requests + 3, bad_requests = bad_requests + 0, empty_body = empty_body + 0, bad_vast = bad_vast + 0, exceptions = exceptions + 0 WHERE statKey = \'0e54a6d334e13c4952bbee373f2b652d\'' }
    at www/server/bin/export:350:25
    at tryCatcher (www/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (www/server/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (www/server/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (www/server/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (www/server/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (www/server/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (www/server/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (www/server/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

**Comment by sushantdhiman** [comment]
I dont think Sequelize or even dialect drivers have anything to do with this. Something like this is happening, A transaction want to modify a row, which is being locked by another transaction, which itself waiting for row locked by first transaction.

You will have to time you scripts so they don't work against each other's data set, or modify them so row locks they created aren't mutually shared, or execute them one after other once first script is over then start next one.

May be these will hep you 

1) http://stackoverflow.com/questions/2596005/working-around-mysql-error-deadlock-found-when-trying-to-get-lock-try-restarti
2) http://stackoverflow.com/questions/2332768/how-to-avoid-mysql-deadlock-found-when-trying-to-get-lock-try-restarting-trans?rq=1
