### ISSUE TITLE
Cannot read property 'association' When using QueryGenerator

### ISSUE THREAD

**Issue by jasonbodily** [sequelize/sequelize#7355]
## What you are doing?

```js
sequelize.dialect.QueryGenerator
          .selectQuery('Post', {
            include: [{
              model: Comments,
              as: 'comments',
              where: { type: 'active' }
            },
            {
              model: Thread,
              where: { id: thread_id }
            }],
          }, this).slice(0,-1);
```

## What do you expect to happen?
Generate SQL that gets all posts that have active comments and that belong to a thread

## What is actually happening?
The following error is thrown: `Cannot read property 'association' of undefined(…)`
on line 1117 (don't know if that's helpful) because there's no such thing as parent:  
 
```   
 if (options.include) {
      var generateJoinQueries = function(include, parentTable) {
        var table = include.model.getTableName()
          , as = include.as
          , joinQueryItem = ''
          , joinQueries = {
            mainQuery: [],
            subQuery: []
          }
          , attributes
          , association = include.association
          , through = include.through
          , joinType = include.required ? ' INNER JOIN ' : ' LEFT OUTER JOIN '
          , parentIsTop = !include.parent.association && include.parent.model.name === options.model.name //<-- This line throws error
          , whereOptions = Utils._.clone(options)
          , targetWhere;
```

__Dialect:__ postgres 
__Sequelize version: 3.30.2

**Comment by harshithkashyap** [comment]
`QueryGenerator` methods are used by sequelize internally and not for public usage. `Model.findAll` processes the options before calling selectQuery and you are likely running into error there.

**Comment by jasonbodily** [comment]
Thanks @harshithkashyap. With I knew how to help get subqueries in place!

**Comment by Deathangel908** [comment]
```
const Model = require('sequelize/lib/model')
 let options = {
          include: [
            {model: Comments}
          ],
        };

Model.validateIncludedElements.bind(Post)(options) // for es5 you can use call
// You can also add `options.model = Post` so you can use it w/o this Model.validateIncludedElements(options)
```

**Comment by ron-liu** [comment]
@Deathangel908 thanks for your hints. I just changed a little bit and got work. 
`Model._validateIncludedElements.bind(Post)(options) // should add underline before validateIncludedElements` on sequelize 4+

**Comment by webmobiles** [comment]
@Deathangel908 @ron-liu  , thanks for your help, all is working but not with where, my prolems i'ts that sequelize does not support advanced query native for jsonb like postgres does, so i must to execute  the sql by hand. I'm getting an error if add where:


```


Payment list {} Error: Support for `{where: 'raw query'}` has been removed.
    at Object.whereItemsQuery (/Users/cherdave/projects/myapp/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1933:13)
    at Object.getWhereConditions (/Users/cherdave/projects/myapp/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2431:19)
    at Object.selectQuery (/Users/cherdave/projects/myapp/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1130:28)
    at QueryInterface.select (/Users/cherdave/projects/myapp/node_modules/sequelize/lib/query-interface.js:1018:27)
    at Promise.try.then.then.then (/Users/cherdave/projects/myapp/node_modules/sequelize/lib/model.js:1561:34)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Function.findAll (/Users/cherdave/projects/myapp/node_modules/sequelize/lib/model.js:1558:8)
    at _callee5$ (/Users/cherdave/projects/myapp/src/graphqlResolvers.js:627:51)
    at tryCatch (/Users/cherdave/projects/myapp/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/cherdave/projects/myapp/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/cherdave/projects/myapp/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/cherdave/projects/myapp/src/graphqlResolvers.js:52:191)
    at /Users/cherdave/projects/myapp/src/graphqlResolvers.js:52:361
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
Customer list { name: null } Error: Support for `{where: 'raw query'}` has been removed.
```

**Comment by webmobiles** [comment]
I made a mistake, now have no errors
