### ISSUE TITLE
Error "val.replace is not a function" when querying JSONB fields

### ISSUE THREAD

**Issue by dzuluaga** [sequelize/sequelize#7400]
Hey folks, any clue what I'm missing here?

## What you are doing?
I'm trying to query JSONB field in Postgres 9.5 DB using Sequelize syntax from here: http://docs.sequelizejs.com/en/latest/docs/querying/#jsonb.

## What do you expect to happen?
Be able to query JSONB fields using Sequelize syntax.
```json
{
  "entity_json": {
    "Hippa_or_PCI__c": {
      "$eq": "HIPAA"
    }
  }
}
```

## What is actually happening?
The following error is produced `TypeError: val.replace is not a function`. See stacktrace below.

Output generated:
```
TypeError: val.replace is not a function\n    at Object.SqlString.escape (/Users/diegozuluaga/tools/git/nucleus/nucleus-edge-api/apiproxy/resources/node/node_modules/sequelize/lib/sql-string.js:61:15)\n    at Object.escape (/Users/diegozuluaga/tools/git/nucleus/nucleus-edge-api/apiproxy/resources/node/node_modules/sequelize/lib/dialects/abstract/query-generator.js:978:22)\n    at Object.whereItemQuery (/Users/diegozuluaga/tools/git/nucleus/nucleus-edge-api/apiproxy/resources/node/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2362:22)\n    at /Users/diegozuluaga/tools/git/nucleus/nucleus-edge-api/apiproxy/resources/node/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1993:25\n    at /Users/diegozuluaga/tools/git/nucleus/nucleus-edge-api/apiproxy/resources/node/node_modules/sequelize/node_modules/lodash/lodash.js:4389:15\n    at baseForOwn (/Users/diegozuluaga/tools/git/nucleus/nucleus-edge-api/apiproxy/resources/node/node_modules/sequelize/node_modules/lodash/lodash.js:2652:24)\n    at Function.forOwn (/Users/diegozuluaga/tools/git/nucleus/nucleus-edge-api/apiproxy/resources/node/node_modules/sequelize/node_modules/lodash/lodash.js:12254:24)\n    at Object.whereItemsQuery (/Users/diegozuluaga/tools/git/nucleus/nucleus-edge-api/apiproxy/resources/node/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1992:9)\n    at Object.getWhereConditions (/Users/diegozuluaga/tools/git/nucleus/nucleus-edge-api/apiproxy/resources/node/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2427:19)\n    at Object.selectQuery (/Users/diegozuluaga/tools/git/nucleus/nucleus-edge-api/apiproxy/resources/node/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1529:28)\n    at QueryInterface.select (/Users/diegozuluaga/tools/git/nucleus/nucleus-edge-api/apiproxy/resources/node/node_modules/sequelize/lib/query-interface.js:669:25)\n    at Model.<anonymous> (/Users/diegozuluaga/tools/git/nucleus/nucleus-edge-api/apiproxy/resources/node/node_modules/sequelize/lib/model.js:1398:32)\n    at Model.tryCatcher (/Users/diegozuluaga/tools/git/nucleus/nucleus-edge-api/apiproxy/resources/node/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/Users/diegozuluaga/tools/git/nucleus/nucleus-edge-api/apiproxy/resources/node/node_modules/bluebird/js/release/promise.js:510:31)\n    at Promise._settlePromise (/Users/diegozuluaga/tools/git/nucleus/nucleus-edge-api/apiproxy/resources/node/node_modules/bluebird/js/release/promise.js:567:18)\n    at Promise._settlePromise0 (/Users/diegozuluaga/tools/git/nucleus/nucleus-edge-api/apiproxy/resources/node/node_modules/bluebird/js/release/promise.js:612:10)\n    at Promise._settlePromises (/Users/diegozuluaga/tools/git/nucleus/nucleus-edge-api/apiproxy/resources/node/node_modules/bluebird/js/release/promise.js:691:18)\n    at Async._drainQueue (/Users/diegozuluaga/tools/git/nucleus/nucleus-edge-api/apiproxy/resources/node/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/Users/diegozuluaga/tools/git/nucleus/nucleus-edge-api/apiproxy/resources/node/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/Users/diegozuluaga/tools/git/nucleus/nucleus-edge-api/apiproxy/resources/node/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:651:20)\n    at tryOnImmediate (timers.js:624:5)
```

Dialect: postgres
Database version: 9.4
Sequelize version: 3.30.2

**Comment by sushantdhiman** [comment]
I dont know if this is due to same problem as faced in https://github.com/sequelize/sequelize/issues/7444 but linking it

**Comment by sushantdhiman** [comment]
Also https://github.com/sequelize/sequelize/issues/7376
