### ISSUE TITLE
SequelizeBaseError: Could not begin transaction on data node.

### ISSUE THREAD

**Issue by dreamstu** [sequelize/sequelize#7409]
## What you are doing?
insert

## What is actually happening?
SequelizeBaseError: Could not begin transaction on data node.

```
Unhandled rejection SequelizeBaseError: Could not begin transaction on data node.
    at Query.formatError (/Users/test/node_modules/.3.30.2@sequelize/lib/dialects/postgres/query.js:357:14)
    at Query.<anonymous> (/Users/test/node_modules/.3.30.2@sequelize/lib/dialects/postgres/query.js:88:19)
    at emitOne (events.js:96:13)
    at Query.emit (events.js:191:7)
    at Query.handleError (/Users/test/node_modules/.6.1.5@pg/lib/query.js:143:8)
    at Connection.<anonymous> (/Users/test/node_modules/.6.1.5@pg/lib/client.js:180:26)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/Users/test/node_modules/.6.1.5@pg/lib/connection.js:136:12)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:554:20)
```

__Dialect:__  postgres xl
__Database version:__ PGXL 9.5r1.3, based on PG 9.5.4 (Postgres-XL 9.5r1.3)
__Sequelize version:__ 3.30.2

I use `node-orm2`, it works fine

**Comment by janmeier** [comment]
Please read up on how to create a [SSCCE](HTTP://SSCCE.ORG/) - There is no way we can help you if we cannot replicate the issue

Furthermore, it seems it might be an issue with postgresxl, not sequelize https://stackoverflow.com/questions/38037716/issue-with-datanodes-on-postgres-xl-cluster
