### ISSUE TITLE
sequelize CLI 'models/index.js' var config not supported (MS Win 10)

### ISSUE THREAD

**Issue by lfurzewaddock** [sequelize/sequelize#7418]
sequelize CLI generated 'models/index.js' file includes;

```
var config    = require(__dirname + '/..\config\config.json')[env];
```

## _resolveFilename Error Raised

```
[nodemon] starting `node ./bin/www`
module.js:471
    throw err;
    ^

Error: Cannot find module 'D:\Users\User1\Projects\Dev\server\models/..configconfig.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Users\User1\Projects\Dev\server\models\index.js:8:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Users\User1\Projects\Dev\server\controllers\todos.js:3:32)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
[nodemon] app crashed - waiting for file changes before starting...
```

## Workaround

Replace var config declaration with example found in the docs;

[http://sequelize.readthedocs.io/en/1.7.0/articles/express/#modelsindexjs](http://sequelize.readthedocs.io/en/1.7.0/articles/express/#modelsindexjs)

```
var config    = require(path.join(__dirname, '..', 'config', 'config.json'))[env];
```

__Dialect:__  mssql
__Database version:__ MS SQL Server 2012 R2 (11.1.3000.0)
__Sequelize version:__ 3.30.2
__Tedious version:__ 1.15.0
__OS version:__ MS Win 10 Pro (1607 Build: 14393.953)
__Node.js version:__ 6.9.5
__npm version:__ 3.10.10
__JS version:__ ES5

**Comment by janmeier** [comment]
https://github.com/sequelize/cli
