### ISSUE TITLE
Scopes docs inadequately explain including associated models.

### ISSUE THREAD

**Issue by Christophin** [sequelize/sequelize#7420]
## Proposed Fix

I'm preparing a pull request with a docs fix that modifies the "Scopes" page with an example of how to use `addScope` in the associate classMethod. This seems like a best practice for scopes that include other models as it prevents the user from having to remember that including other models is dependent upon the (current) alphabetical load order of model files.

It would be interesting to update scopes to be processed lazily after all models have been loaded
so that we don't need to manually attach them with `addScope` in the associate method. This would definitely involve more wide ranging changes to the sequelize codebase though and is probably not high priority. I haven't dug into the source to get a feel for how difficult that would be yet.

## What you are doing?

I've been trying to figure out the best practice for adding scopes that include an associated model.
The documentation has an example that produced a traceback if the scope is used as-is.
`addScope` is suggested as an often helpful tool for associated scopes but an example of how/where to use it is missing.

## What do you expect to happen?

I expect to be able to define scopes in the model file that include associated models, as indicated by the docs.

## What is actually happening?

This is the traceback I got when I tried to follow the example from your scopes
docs in a sample repo with user and project models defined.

```
TypeError: Cannot read property 'getTableName' of undefined
    at Model.validateIncludedElement (/Users/chriscoralli/dev/projects/ironyard/sequelize-test/node_modules/sequelize/lib/model.js:513:27)
    at /Users/chriscoralli/dev/projects/ironyard/sequelize-test/node_modules/sequelize/lib/model.js:440:29
    at Array.map (native)
    at Model.validateIncludedElements (/Users/chriscoralli/dev/projects/ironyard/sequelize-test/node_modules/sequelize/lib/model.js:436:37)
    at Model.<anonymous> (/Users/chriscoralli/dev/projects/ironyard/sequelize-test/node_modules/sequelize/lib/model.js:1372:32)
    at Model.tryCatcher (/Users/chriscoralli/dev/projects/ironyard/sequelize-test/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/chriscoralli/dev/projects/ironyard/sequelize-test/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/chriscoralli/dev/projects/ironyard/sequelize-test/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/chriscoralli/dev/projects/ironyard/sequelize-test/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/chriscoralli/dev/projects/ironyard/sequelize-test/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/chriscoralli/dev/projects/ironyard/sequelize-test/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/chriscoralli/dev/projects/ironyard/sequelize-test/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/chriscoralli/dev/projects/ironyard/sequelize-test/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

__Dialect:__ sqlite
__Database version:__ 3.14.0
__Sequelize version:__ 3.30.2

**Comment by sushantdhiman** [comment]
Any kind of improvement is always welcomed, You can open PR with docs update. We may refine them in PR itself

We can first work on docs around adding scope for related models, When you are more familiar with code we can think about lazy loading scopes, currently scope is only prepared when its called with `Model.scope` and saved under `this._scope`

I have personally not used scopes in my projects, certainly not with association so I am bit unfamiliar about features that users might expect
