### ISSUE TITLE
Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by pc3b3r** [sequelize/sequelize#7450]
I'm trying to do a n:m relation between 2 tables in MySQL 5.7.17 with v. 3.30.2 using express.

My models are like so:

```js
module.exports = function(sequelize, DataTypes) {
  const User = sequelize.define('user', {
    id: {
      type: DataTypes.INTEGER(12),
      allowNull: false,
      autoIncrement: true,
      primaryKey: 'true'
    },
    username: {
      type: DataTypes.STRING.BINARY,
      unique: true,
      allowNull: false
    },
    password: {
      type: DataTypes.STRING,
      allowNull: false
    },
  },
  {
    classMethods: {
      associate: function(models) {
        User.belongsToMany(models.shared, {
          through: 'sharedwith'
        });
      }
    },
    tableName : 'user',
    timestamps: true
  });
  return User;
};

```

```js
module.exports = function(sequelize, DataTypes) {
  const Shared = sequelize.define('shared', {
    id: {
      type: DataTypes.INTEGER(12),
      allowNull: false,
      autoIncrement: true,
      primaryKey: 'true'
    },
    name: {
      type: DataTypes.TEXT,
      unique: false,
      allowNull: false
    }
  }, {
    classMethods: {
      associate: function(models) {
        Shared.belongsToMany(models.user, {
          through: 'sharedwith'
        });
      }
    },
    tableName: 'shared',
    timestamps: true
  });
  return Shared;
};
```

```sh
TypeError: Cannot read property 'toUpperCase' of undefined
    at /home/doc/back/node_modules/sequelize/lib/utils.js:79:75
    at RegExp.[Symbol.replace] (native)
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at Object.camelize (/home/doc/back/node_modules/sequelize/lib/utils.js:79:23)
    at Object.camelizeIf (/home/doc/back/node_modules/sequelize/lib/utils.js:19:22)
    at new BelongsToMany (/home/doc/back/node_modules/sequelize/lib/associations/belongs-to-many.js:114:56)
    at Model.Mixin.belongsToMany (/home/doc/back/node_modules/sequelize/lib/associations/mixin.js:265:21)
    at Model.associate (/home/doc/back/app/models/development/shared.js:36:16)
```

The problem comes from [this.source.primaryKeyAttribute](https://github.com/sequelize/sequelize/blob/master/lib/associations/belongs-to-many.js#L112) that is undefined.

Any suggestions?

**Comment by harshithkashyap** [comment]
@pc3b3r The primaryKey property in model definition is a boolean value. Looks like you are using `primaryKey: 'true'` string value. Could you try it without the quotes?

**Comment by pc3b3r** [comment]
@harshithkashyap Many thanks, now it's working. 
It's strange because it was working without relations and with quotes.
