### ISSUE TITLE
bulkCreate generating wrong SQL

### ISSUE THREAD

**Issue by HoneyryderChuck** [sequelize/sequelize#7482]
## What you are doing?

I have an association table in between users which sets the belongs-to-many relation, as a follow-up to a previous bug report #7427 . The suggested solution which closed the ticket is suboptimal in my use case, as I'm setting loads of relations. So this is the proper case for a bulk-Create, so I went ahead.

```js
# context
const User = db.define('users', {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: true,
  },
  email: {
    type: Sequelize.STRING,
    unique: true,
    allowNull: false,
    isEmail: true,
    field: 'email',
  }, ...
const Friendships = db.define('friendships', {})
User.belongsToMany(User, {as: "Friends", through: Friendships})
...
# after setting some users
let friendships = []
friends.forEach(friend => {
	friendships.push({userId: user.id, friendId: friend.id})
	friendships.push({userId: friend.id, friendId: user.id})
})
console.log(friendships)
Friendships.bulkCreate(friendships)
```

## What do you expect to happen?

I'd expected the friendships to be created, bidirectionally and for every user. The data I'm provided from the console log suggests me that there's nothing wrong with my input data:

```
# as context
CREATE TABLE IF NOT EXISTS `friendships` (`userId` INTEGER NOT NULL REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, `FriendId` INTEGER NOT NULL REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY (`userId`, `FriendId`));

# data is
[ { userId: 4, friendId: 3 },
  { userId: 3, friendId: 4 },
  { userId: 4, friendId: 2 },
  { userId: 2, friendId: 4 },
  { userId: 4, friendId: 1 },
  { userId: 1, friendId: 4 } ]
```

## What is actually happening?

SQL generated is just wrong:

```SQL
Executing (default): INSERT INTO `friendships` (`userId`) VALUES (4),(3),(4),(2),(4),(1);
{ SequelizeBaseError: Validation error
    at Query.formatError (/Users/tiagocardoso/Projects/gpool/node_modules/sequelize/lib/dialects/sqlite/query.js:337:14)
    at Statement.afterExecute (/Users/tiagocardoso/Projects/gpool/node_modules/sequelize/lib/dialects/sqlite/query.js:112:29)
    at Statement.replacement (/Users/tiagocardoso/Projects/gpool/node_modules/sqlite3/lib/trace.js:19:31)
  name: 'SequelizeUniqueConstraintError',
  message: 'Validation error',
  errors: [],
  fields: [],
  parent: 
   { Error: SQLITE_CONSTRAINT: NOT NULL constraint failed: friendships.FriendId
     errno: 19,
     code: 'SQLITE_CONSTRAINT',
     sql: 'INSERT INTO `friendships` (`userId`) VALUES (4),(3),(4),(2),(4),(1);' },
  original: 
   { Error: SQLITE_CONSTRAINT: NOT NULL constraint failed: friendships.FriendId
     errno: 19,
     code: 'SQLITE_CONSTRAINT',
     sql: 'INSERT INTO `friendships` (`userId`) VALUES (4),(3),(4),(2),(4),(1);' },
  sql: 'INSERT INTO `friendships` (`userId`) VALUES (4),(3),(4),(2),(4),(1);' }
```

__Dialect:__ sqlite
__Database version:__ 3.16.0
__Sequelize version:__ 4.0.0-2

**Comment by janmeier** [comment]
```sql
`FriendId` INTEGER NOT NULL REFERENCES `users` (`id`)
```
Notice the capital F.

This is because you say `as: 'Friends`. You could change it to `as: 'friends'` or use `foreignKey: 'friendId'`

**Comment by HoneyryderChuck** [comment]
I've changed to "friends", it worked exactly as you said. Thanks a lot! I think I was misled by the documentation found, but it might be that it's for a previous version of sequelize (4.0.0 is beta still, right?)
