### ISSUE TITLE
relation "xxx" does not exist during migration

### ISSUE THREAD

**Issue by dj-hedgehog** [sequelize/sequelize#7487]
## What you are doing?
I am only trying to run a migration against a clean PostgreSQL 9.6 database.

```js
sequelize db:migrate
```

*server.js*
```js
models.sequelize.sync().then(function () {
    var server = http.createServer(app);
    ...
})
```

*migrations/20170221050002-assignment-migration.js*
```js
module.exports = {
  up: function (queryInterface, Sequelize) {
    queryInterface.addColumn({
      tableName: 'Alignments'
    },
    'type',
      {
        type: Sequelize.STRING,
        allowNull: true,
        defaultValue: 'NFC'
      }
  )
    queryInterface.addColumn(
      {
        tableName: 'Alignments'
      },
    'assignmentType',
      {
        type: Sequelize.STRING,
        allowNull: true,
        defaultValue: 'Major'
      }
  )
  },

  down: function (queryInterface, Sequelize) {
    queryInterface.removeColumn({
      tableName: 'Alignments'
    }, 'type')
    queryInterface.removeColumn({
      tableName: 'Alignments'
    }, 'assignmentType')
  }
}
```

*models/alignment.js*
```js
module.exports = function (sequelize, DataTypes) {
  var Alignment = sequelize.define('Alignment', {
    tag: { type: DataTypes.STRING, allowNull: false, unique: true },
    type: { type: DataTypes.STRING, allowNull: true },
    assignmentType: { type: DataTypes.STRING, allowNull: true }
  }, {
    classMethods: {
      associate: function (models) {
        Alignment.belongsTo(models.Product, { foreignKey: 'product' })
      }
    }
  })
  return Alignment
}
```

## What do you expect to happen?
*Adding the `type` and `assignmentType` attributes works but I want to get rid of the errors below*

## What is actually happening?

```
== 20170221050002-assignment-migration: migrating =======
Unhandled rejection SequelizeBaseError: relation "public.Alignments" does not exist
    at Query.formatError (/Users/ali/project/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)
    at Query.<anonymous> (/Users/ali/project/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
```

**Comment by sushantdhiman** [comment]
Can you show me full stack trace, it looks like something else.

Also you need to chain those promises in `up` function, current code call them like they are sync functions, but `addColumn` (`removeColumn` too) both return promises. 

I think one of your migration file depend upon relations inside a promise which was not properly chained and next migration got executed.

**Comment by philfrasty** [comment]
@dj-hedgehog did you ever figure out what caused the problem?

**Comment by Chuckatron** [comment]
I'd also be interested in finding out whether this was ever solved as I'm facing the same problem!
