### ISSUE TITLE
"attrValueHashes.forEach is not a function" on bulkInsert

### ISSUE THREAD

**Issue by dj-hedgehog** [sequelize/sequelize#7488]
## What you are doing?
I am trying to add a user as seed data to an existing PostgreSQL v9.6 database. 
Sequelize [Node: 7.7.4, CLI: 2.7.0, ORM: 3.20.0]

```js
sequelize db:migrate
```

*server.js*
```js
models.sequelize.sync().then(function () {
    var server = http.createServer(app);
    ...
})
```

*migrations/20170221050003-add-superuser.js*
```js
module.exports = {
  up: function (queryInterface, Sequelize) {
    return queryInterface.bulkInsert(
      {
        tableName: 'Users'
      },
      {
        'id': 2,
        'name': 'radmin',
        'password': 'xxxxhashxxxx'
      },
  {}
  )
  },

  down: function (queryInterface, Sequelize) {
    return queryInterface.bulkDelete(
      {
        tableName: 'Users'
      },
  null,
  {}
  )
  }
}
```

*models/user.js*
```js
module.exports = function (sequelize, DataTypes) {
  var User = sequelize.define('User', {
    name: {type: DataTypes.STRING, allowNull: false, unique: true},
    password: {type: DataTypes.STRING, allowNull: false}
  })

  return User
}
```

## What do you expect to happen?
**The user is added to to the database upon launching the server**

## What is actually happening?

```
== 20170404050003-add-superuser: migrating =======
TypeError: attrValueHashes.forEach is not a function
    at Object.bulkInsertQuery (/Users/ali/project/node_modules/sequelize/lib/dialects/abstract/query-generator.js:338:21)
    at QueryInterface.bulkInsert (/Users/ali/project/node_modules/sequelize/lib/query-interface.js:566:33)
```

**Comment by sushantdhiman** [comment]
`bulkInsert` accept array of records, you are passing object. Try this

```js
return queryInterface.bulkInsert('Users', [{
  'id': 2,
  'name': 'radmin',
  'password': 'xxxxhashxxxx'
}])
```
