### ISSUE TITLE
include same(auto) table work in find... but not in addScope

### ISSUE THREAD

**Issue by apapacy** [sequelize/sequelize#7502]
It's work great
```js
Client. find...({
      where,
      order: [['createdAt', 'desc']],
      limit: config.paginationLimit,
      include: [{model: Client, as: 'referral'}],
    });
```

But same include in addScope generate error
```js
    Client.addScope('defaultScope', {
                  include: [
                    {model: Client, as: 'referral'},
                    {model: Exchanger, as: 'exchanger'},
                  ],
                }, {override: true});
```

## Error:
```
RangeError: Maximum call stack size exceeded
    at Function.isPlainObject (/home/roma/projects/obmen24/node_modules/sequelize/node_modules/lodash/lodash.js:11285:14)
    at /home/roma/projects/obmen24/node_modules/sequelize/lib/utils.js:94:36
    at baseClone (/home/roma/projects/obmen24/node_modules/sequelize/node_modules/lodash/lodash.js:2298:27)
    at /home/roma/projects/obmen24/node_modules/sequelize/node_modules/lodash/lodash.js:2351:34
    at arrayEach (/home/roma/projects/obmen24/node_modules/sequelize/node_modules/lodash/lodash.js:473:11)
    at baseClone (/home/roma/projects/obmen24/node_modules/sequelize/node_modules/lodash/lodash.js:2346:7)
    at /home/roma/projects/obmen24/node_modules/sequelize/node_modules/lodash/lodash.js:2351:34
    at arrayEach (/home/roma/projects/obmen24/node_modules/sequelize/node_modules/lodash/lodash.js:473:11)
    at baseClone (/home/roma/projects/obmen24/node_modules/sequelize/node_modules/lodash/lodash.js:2346:7)
    at /home/roma/projects/obmen24/node_modules/sequelize/node_modules/lodash/lodash.js:2351:34
    at arrayEach (/home/roma/projects/obmen24/node_modules/sequelize/node_modules/lodash/lodash.js:473:11)
    at baseClone (/home/roma/projects/obmen24/node_modules/sequelize/node_modules/lodash/lodash.js:2346:7)
    at Function.cloneDeepWith (/home/roma/projects/obmen24/node_modules/sequelize/node_modules/lodash/lodash.js:10381:14)
    at Object.cloneDeep (/home/roma/projects/obmen24/node_modules/sequelize/lib/utils.js:92:14)
    at Model.$injectScope (/home/roma/projects/obmen24/node_modules/sequelize/lib/model.js:2667:21)
    at Model.validateIncludedElement (/home/roma/projects/obmen24/node_modules/sequelize/lib/model.js:598:9)
    at /home/roma/projects/obmen24/node_modules/sequelize/lib/model.js:440:29
    at Array.map (native)
    at Model.validateIncludedElements (/home/roma/projects/obmen24/node_modules/sequelize/lib/model.js:436:37)
    at Model.validateIncludedElement (/home/roma/projects/obmen24/node_modules/sequelize/lib/model.js:633:30)
    at /home/roma/projects/obmen24/node_modules/sequelize/lib/model.js:440:29
    at Array.map (native)

```

__Dialect:__ postgres
__Sequelize version: ^3.15.0

**Comment by sushantdhiman** [comment]
Please report if you face this issue with master branch as well
