### ISSUE TITLE
Separate: true — Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by andrew-polyansky** [sequelize/sequelize#7514]
```js
Model.hasMany(AnotherMmodelWithHasManyAssociations, { onDelete: 'CASCADE', as: 'test' });
```

```js
Model.findAll({
        include: [
            {
                model: AnotherMmodelWithHasManyAssociations,
                as: 'test',
                separate: true,
            },
        ],
    })
```
After that Sequelize falls with error:
```js
TypeError: Cannot read property 'push' of undefined
     at /usr/src/app/node_modules/sequelize/lib/associations/has-many.js:331:64
     at Array.forEach (native)
     at .<anonymous> (/usr/src/app/node_modules/sequelize/lib/associations/has-many.js:330:13)
 From previous event:
     at Promise.then (/usr/src/app/node_modules/sequelize/lib/promise.js:21:17)
     at HasMany.get (/usr/src/app/node_modules/sequelize/lib/associations/has-many.js:322:33)
     at /usr/src/app/node_modules/sequelize/lib/model.js:1442:32
 From previous event:
     at Function.map (/usr/src/app/node_modules/sequelize/lib/promise.js:21:17)
     at Function.Model.$findSeparate (/usr/src/app/node_modules/sequelize/lib/model.js:1420:18)
     at .<anonymous> (/usr/src/app/node_modules/sequelize/lib/model.js:1408:18)
 From previous event:
     at Promise.then (/usr/src/app/node_modules/sequelize/lib/promise.js:21:17)
     at Promise.all.then (/usr/src/app/src/modules/transaction/limits.service.js:139:10)

```

__Dialect:__ mariaDb
__Database version:__ 10.1
__Sequelize version:__ 3.30.4

**Comment by xdroidx** [comment]
I have just forced with same problem. In my case:

`db.Outfits.hasMany(db.Likes, { foreignKey: 'outfit', as: 'likes' });`
`Outfits.findAll({ include: [ { model: Likes, attributes: [ 'user' ], as: 'likes', separate: true } ]})`
So in my case same error appeared because the foreignKey 'outfit' lacking in attributes.

@andrew-polyansky The problematic part of code looks like below. So did you try to add 'foreignKey' to associations?
`for (const instance of results) {
    result[instance.get(association.foreignKey, {raw: true})].push(instance);
}`

Anyway it's good to have some warnings on this case or at least to document it somehow.

**Comment by jrcrawfo** [comment]
Still an issue

**Comment by edwinvanrijkom** [comment]
Running into this as well (v.4.6.0).

**Comment by elhoyos** [comment]
I got to make it work on my side by specifying the `foreignKey` in the included attributes.

```js
Foo.hasMany(Bar, { as: 'bars', foreignKey: 'special_id' });
Bar.belongsTo(Foo, { as: 'special', foreignKey: 'special_id' });

Foo
  .findAll({
    attributes: ['id', 'name'],
    where: {
      is_valid: true
    },
    order: [['name', 'DESC']],
    include: [{
      model: Bar,
      as: 'bars',
      attributes: ['special_id', 'name'], // error appears if special_id is not provided here
      where: {
        is_active: true
      },
      limit: 10, // causes the separate=true
      required: true
    }]
  })
```

I'm using sequelize@3.30.4 on postgres.

**Comment by zeing** [comment]
@elhoyos omg , you help me <3

**Comment by andrew-polyansky** [comment]
For resolve this issue need:

1. Explicitly indicate foreignKey:  
```
Account.hasMany(AccountRoles, { onDelete: 'CASCADE', foreignKey: 'accountId', as: 'rolesIds' });
```
2. Explicitly indicate this foreignKey to attributes.

**Comment by antonioasmoura** [comment]
Using Sequelize 4.19.0 and this not solved.

**Comment by flamewow** [comment]
got same issue

**Comment by narin** [comment]
Having this issue as well.  Including the foreign key in attributes as @elhoyos suggested did not solve the issue for me.   Using 4.22.7.

**Comment by fareshan** [comment]
this is not resolved yet

**Comment by sushantdhiman** [comment]
@fareshan You tried with which version?

**Comment by fareshan** [comment]
@sushantdhiman v4.37.7

**Comment by sushantdhiman** [comment]
@fareshan It's fixed in latest v5 beta

**Comment by fareshan** [comment]
@sushantdhiman ok thanks
Is there a workaround for v4 ?

**Comment by ebaynaud** [comment]
no workaround available for v4?

**Comment by rogyvoje** [comment]
Still an issue! @elhoyos thanks a lot!

**Comment by matamune94** [comment]
```
const Film_types = sequelize.define('film_types', {
  film_id: {type: Sequelize.BIGINT(20).UNSIGNED, primaryKey: true},
  slug: Sequelize.STRING,
});

const Episodes = sequelize.define('episodes', {
  ep_id: {type: Sequelize.BIGINT(20).UNSIGNED, primaryKey: true, autoIncrement: true},
  film_id: Sequelize.BIGINT(20).UNSIGNED,
  stt: Sequelize.INTEGER,
  ep_num: Sequelize.STRING,
  ep_name: Sequelize.TEXT('tiny'),
  ep_des: Sequelize.TEXT,
  ep_thumb: Sequelize.TEXT('tiny'),
  ep_data: Sequelize.TEXT('long')
});
Films.hasMany(Episodes, {foreignKey: 'film_id'})
Episodes.belongsTo(Films, {foreignKey: 'film_id'})

Film_types.hasMany(Episodes, {foreignKey: 'film_id'})
Episodes.belongsTo(Film_types, {foreignKey: 'film_id'})

Films.findAll({ include: [{ model: Film_types, include: [{ model: Episodes, attributes:['stt','ep_num'], limit: 1, order:[ ['stt','DESC'] ], where:{ ep_num: { [Op.notLike]: '%OVA%' } }, separate: true }], where: { slug: items } }], attributes, limit, order:[ ['film_id','DESC'] ], where, raw: false})
```
Hi @sushantdhiman ,I make error Cannot read property 'push' of undefined, maybe can help ?

**Comment by kanwarmanish** [comment]
sequelize: 5.21.2 - still an issue. Could any body resolve it?

**Comment by caseyt** [comment]
Still an issue as of v 7.0. This repo is terrible about closing issues that still exist.
