### ISSUE TITLE
"Unhandled rejection TypeError: val.replace is not a function" when try to set association data

### ISSUE THREAD

**Issue by hebbian** [sequelize/sequelize#7520]
Hi, thanks for the awesome ORM.

I was trying to add association by doing this:

```js
// talent
var talent = sequelize.define("tms_talent_data",  ...

// skill
var skill = sequelize.define("skill", { ...
models.tms_talent_data.hasMany(skill)
```

And add skill by doing this:
```js
// req.body contain JSON as follow:
[
	{"skill":"Singing","skill_level":"Advance"},
	{"skill":"Dancing","skill_level":"Intermediate"},
	{"skill":"Acting","skill_level":"Beginner"}
]

// add association data
let c = []
_.each(req.body, (v,k) => {
     let u = result.createSkill(v) //result is models.tms_talent_data instance
     c.push(u)
})
result.setSkills(c).then((a) => {
    res.json(a) // this callback never called due to error "var.replace is not a function"
})
```
This code works fine, and it replace skills data in the table. But there is an annoying error says __Unhandled rejection TypeError: val.replace is not a function__ which causes the callback from __setSkills__ function does not called. What did I do wrong?

```
Unhandled rejection TypeError: val.replace is not a function
    at Object.SqlString.escape (/Users/hebbian/Developments/et/awesome-project/node_modules/sequelize/lib/sql-string.js:61:15)
    at Object.escape (/Users/hebbian/Developments/et/awesome-project/node_modules/sequelize/lib/dialects/abstract/query-generator.js:978:22)
    at /Users/hebbian/Developments/et/awesome-project/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2293:23
    at Array.map (native)
    at Object.whereItemQuery (/Users/hebbian/Developments/et/awesome-project/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2292:49)
    at /Users/hebbian/Developments/et/awesome-project/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1993:25
    at /Users/hebbian/Developments/et/awesome-project/node_modules/sequelize/node_modules/lodash/lodash.js:4389:15
    at baseForOwn (/Users/hebbian/Developments/et/awesome-project/node_modules/sequelize/node_modules/lodash/lodash.js:2652:24)
    at Function.forOwn (/Users/hebbian/Developments/et/awesome-project/node_modules/sequelize/node_modules/lodash/lodash.js:12254:24)
    at Object.whereItemsQuery (/Users/hebbian/Developments/et/awesome-project/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1992:9)
    at Object.whereQuery (/Users/hebbian/Developments/et/awesome-project/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1964:22)
    at Object.updateQuery (/Users/hebbian/Developments/et/awesome-project/node_modules/sequelize/lib/dialects/abstract/query-generator.js:481:19)
    at QueryInterface.bulkUpdate (/Users/hebbian/Developments/et/awesome-project/node_modules/sequelize/lib/query-interface.js:604:33)
    at /Users/hebbian/Developments/et/awesome-project/node_modules/sequelize/lib/model.js:2601:32
    at tryCatcher (/Users/hebbian/Developments/et/awesome-project/node_modules/sequelize/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/hebbian/Developments/et/awesome-project/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/hebbian/Developments/et/awesome-project/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/hebbian/Developments/et/awesome-project/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/hebbian/Developments/et/awesome-project/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/hebbian/Developments/et/awesome-project/node_modules/sequelize/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/hebbian/Developments/et/awesome-project/node_modules/sequelize/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/hebbian/Developments/et/awesome-project/node_modules/sequelize/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

Thanks

__Dialect__: PostgreSQL
__Sequelize Version__: 3.30.4
__Node Version__: v6.9.5

**Comment by hebbian** [comment]
I think __setSkill(c)__ command is buggy, I ended up using __setSkill([])__ to clear all skills data and run __addSkill(u)__ on each iteration. 

Any explanation to this?

**Comment by sushantdhiman** [comment]
Hi There,

`createSkill` creates promise, so here you are trying to set array of promises so `result` (Model instance I assume), which require array of instances or Ids

```js
// add association data
let c = []
_.each(req.body, (v,k) => {
     let u = result.createSkill(v) //result is models.tms_talent_data instance
     c.push(u)
})
result.setSkills(c).then((a) => {
    res.json(a) // this callback never called due to error "var.replace is not a function"
})
```

If you are calling `createSkills` then you dont need to use `setSkills`, it will automatically link with result (instance). Please read more about how to use relationships [here](http://docs.sequelizejs.com/en/v3/docs/associations/) (Its very important as I think you are still confused about setters / getter usage)
