### ISSUE TITLE
TypeError: val.replace is not a function

### ISSUE THREAD

**Issue by dhagge** [sequelize/sequelize#7548]
I have a query with this where clause: 
```
{
  "account_id": "110ec58a-a0f2-4ac4-8393-c866d813b8d1",
  "user_id": "110ec58a-a0f2-4ac4-8393-c866d813b8d1",
  "name": {
    "$iLike:": "%billing%"
  }
}
```

and it generates the following error:
```
2017-04-21T17:31:09.542Z - error: Error TypeError: val.replace is not a function
    at Object.SqlString.escape (/Users/damianhagge/freelance/prospectify/code/app/node_modules/sequelize/lib/sql-string.js:61:15)
    at Object.escape (/Users/damianhagge/freelance/prospectify/code/app/node_modules/sequelize/lib/dialects/abstract/query-generator.js:978:22)
    at Object.whereItemQuery (/Users/damianhagge/freelance/prospectify/code/app/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2362:22)
    at /Users/damianhagge/freelance/prospectify/code/app/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1993:25
    at /Users/damianhagge/freelance/prospectify/code/app/node_modules/sequelize/node_modules/lodash/lodash.js:4389:15
    at baseForOwn (/Users/damianhagge/freelance/prospectify/code/app/node_modules/sequelize/node_modules/lodash/lodash.js:2652:24)
    at Function.forOwn (/Users/damianhagge/freelance/prospectify/code/app/node_modules/sequelize/node_modules/lodash/lodash.js:12254:24)
    at Object.whereItemsQuery (/Users/damianhagge/freelance/prospectify/code/app/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1992:9)
    at Object.getWhereConditions (/Users/damianhagge/freelance/prospectify/code/app/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2427:19)
    at Object.selectQuery (/Users/damianhagge/freelance/prospectify/code/app/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1529:28)
    at QueryInterface.select (/Users/damianhagge/freelance/prospectify/code/app/node_modules/sequelize/lib/query-interface.js:669:25)
    at Model.<anonymous> (/Users/damianhagge/freelance/prospectify/code/app/node_modules/sequelize/lib/model.js:1398:32)
    at Model.tryCatcher (/Users/damianhagge/freelance/prospectify/code/app/node_modules/sequelize/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/damianhagge/freelance/prospectify/code/app/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/damianhagge/freelance/prospectify/code/app/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/damianhagge/freelance/prospectify/code/app/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/damianhagge/freelance/prospectify/code/app/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/damianhagge/freelance/prospectify/code/app/node_modules/sequelize/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/damianhagge/freelance/prospectify/code/app/node_modules/sequelize/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/damianhagge/freelance/prospectify/code/app/node_modules/sequelize/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

and the sequelize model:
```
module.exports = function(sequelize, DataTypes) {
  var CompanyListV2 = sequelize.define('CompanyListV2', {

    id: {
      type: DataTypes.UUID,
      primaryKey: true,
      allowNull: false,
      defaultValue: DataTypes.UUIDV4
    },
    account_id: {
      type: DataTypes.UUID,
      references: {
        model: 'accounts',
        key: 'id'
      }
    },
    user_id: {
      type: DataTypes.UUID,
      references: {
        model: 'users',
        key: 'id'
      }
    },

    name: DataTypes.STRING,
    notify_on_change: {
      type: DataTypes.BOOLEAN,
      defaultValue: false
    },

    updated_at: DataTypes.DATE(6),
    created_at: DataTypes.DATE(6),
  }, {
    underscored: true,
    tableName: 'company_lists_v2',
    indexes: [
      //{unique: false, fields: ['account_id', 'user_id']}
    ],
    classMethods: {
      associate: function(models) {
        CompanyListV2.belongsTo(models.Account, {foreignKey: 'account_id'});
        CompanyListV2.belongsTo(models.User, {foreignKey: 'user_id'});
        CompanyListV2.hasMany(models.CompanyListCompanyV2, {foreignKey: 'company_list_id'});
        CompanyListV2.hasMany(models.CampaignV2, {foreignKey: 'campaign_id'});
      }
    },
    instanceMethods: {
      pretty: function(){
        return this.toJSON();
      }
    }
  });
  return CompanyListV2;
};
```

Full code calling the query:
```
  var where = {
    account_id: user.account_id,
    user_id: user.id,
    name: {
      '$iLike:': '%billing%'
    }
  };

  var order = [['created_at', 'DESC']];
  var promise = this.model.findAll({
    limit: 100, offset: 0, where, order
  });
...etc...
```

I can use the exact same where clause successfully on a different table, and in addition, if I change name to a literal it works correctly:
```
var where = {
    account_id: user.account_id,
    user_id: user.id,
    name: sequelize.literal(`"CompanyListV2"."name" ILIKE '%${options.search}%'`);
  };
```

Dialect: postgres
Sequelize version:3.30.4

**Comment by felixfbecker** [comment]
Does it happen in v4?

**Comment by ruanjiayou** [comment]
I don't know why ocurred error when i update.
`   //method one error
    await p.update({ content: 'fuck!' });
    
    //method two error
    await Article.update({ content: 'fuck!' }, { where: { id: p.id } });
    
    //method three error
    p.content = 'fuck!';
    await p.save();`
I thought maybe chinese cause ,but ...
there pictures there:
[https://segmentfault.com/q/1010000010968686](url)
