### ISSUE TITLE
How do I set the name of the foreign key on queryInterface.addColumn()?

### ISSUE THREAD

**Issue by jukkah** [sequelize/sequelize#7549]
_From @rsshilli on January 30, 2017 23:56_

I'm trying to add new columns to multiple tables called "projectId", which as you may have guessed, refers back to the id column in the Project table.   The first table that I alter with addColumn() works fine, but the second table's addColumn() seems to fail because the FK name is not unique.

Here' s the code I'm running:

    queryInterface.addColumn(
        { tableName: "CriticalProcessParameters" },

        "ProjectId",
        {
            type: DataTypes.INTEGER,
            references: {
                model: "Projects",
                key: 'id'
            },
        }
    );

and here's the error I get:

    Executing (default): ALTER TABLE `CriticalProcessParameters` ADD `ProjectId` INTEGER, ADD CONSTRAINT `ProjectId_foreign_idx` FOREIGN KEY (`ProjectId`) REFERENCES `Projects` (`id`);   Unhandled rejection SequelizeDatabaseError: ER_DUP_KEY: Can't write; duplicate key in table '#sql-1d44_502'
        at Query.formatError (C:\projects\cherrycircle\node_modules\sequelize\lib\dialects\mysql\query.js:175:14)
        at Query._callback (C:\projects\cherrycircle\node_modules\sequelize\lib\dialects\mysql\query.js:49:21)
        at Query.Sequence.end (C:\projects\cherrycircle\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
        at Query.ErrorPacket (C:\projects\cherrycircle\node_modules\mysql\lib\protocol\sequences\Query.js:94:8)
        at Protocol._parsePacket (C:\projects\cherrycircle\node_modules\mysql\lib\protocol\Protocol.js:280:23)
        at Parser.write (C:\projects\cherrycircle\node_modules\mysql\lib\protocol\Parser.js:74:12)
        at Protocol.write (C:\projects\cherrycircle\node_modules\mysql\lib\protocol\Protocol.js:39:16)
        at Socket.<anonymous> (C:\projects\cherrycircle\node_modules\mysql\lib\Connection.js:109:28)
        at emitOne (events.js:77:13)
        at Socket.emit (events.js:169:7)
        at readableAddChunk (_stream_readable.js:153:18)
        at Socket.Readable.push (_stream_readable.js:111:10)
        at TCP.onread (net.js:536:20)

How do I set name of the foreign key to be something other than 'ProjectId'?

_Copied from original issue: sequelize/umzug#111_

**Comment by jukkah** [comment]
_From @rsshilli on January 31, 2017 3:19_

Also, I tried passing in a foreignKey in for the options, but that didn't help.  The code makes it look like that might be possible but it didn't work.  For example:

    queryInterface.addColumn(
        { tableName: "CriticalMaterialAttributes" },

        "ProjectId",
        {
            type: DataTypes.INTEGER,
            references: {
                model: "Projects",
                key: 'id'
            },
            foreignKey: "CriticalMaterialAttribute_ProjectId",
        },
        { foreignKey: "CriticalMaterialAttribute_ProjectId"}
    );

**Comment by jukkah** [comment]
Well, it seems to be restriction of MySQL that you can't have multiple foreign keys with the same name in the same DB. I think you are trying to fix it correctly by specifying foreign key name exactly.

There are still one solution what we can do better: ensure that every foreign key (or indexes) have an unique name. But it is an issue of Sequelize not Umzug. Moving.

**Comment by sushantdhiman** [comment]
Create column normally, then use [addConstraint ](https://github.com/sequelize/sequelize/blob/master/docs/migrations.md#addconstrainttablename-attributes-options) (in v4)
