### ISSUE TITLE
use sequelize with host:localhost to connect mysql throw error 

### ISSUE THREAD

**Issue by Tseian** [sequelize/sequelize#7552]
`module.exports = {
    port: "3030",
    appSecret: '38b5e45908a64c6c94615f4371d348bf',
    sequelize: {
      #   host: '127.0.0.1',
        userName: 'root',
        password: '1234',
        database: 'youme_dev',
        port: '3306',
        dialect: 'mysql',
        pool: {
            max: 10,
            min: 0,
            idle: 10000
        }
    }
};`

this is my sequlize config ,when I use host:127.0.0.1 to connect mysql is ok but when I use  host :localhost just  throw an error as follow:

`
{#  SequelizeHostNotFoundError: getaddrinfo ENOTFOUND localhost localhost:3306
Unhandled rejection SequelizeHostNotFoundError: getaddrinfo ENOTFOUND localhost localhost:3306 at Handshake._callback(/Users/tseian/Downloads/node/youme/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:86:20)
    at Handshake._callback (/Users/tseian/Downloads/node/youme/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:86:20)
    at Handshake.Sequence.end (/Users/tseian/Downloads/node/youme/node_modules/mysql/lib/protocol/sequences/Sequence.js:78:24)
    at Handshake.Sequence.end (/Users/tseian/Downloads/node/youme/node_modules/mysql/lib/protocol/sequences/Sequence.js:78:24)
    at Protocol.handleNetworkError (/Users/tseian/Downloads/node/youme/node_modules/mysql/lib/protocol/Protocol.js:282:14)
    at Connection._handleNetworkError (/Users/tseian/Downloads/node/youme/node_modules/mysql/lib/Connection.js:303:18)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at connectErrorNT (net.js:1022:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Protocol.handleNetworkError (/Users/tseian/Downloads/node/youme/node_modules/mysql/lib/protocol/Protocol.js:282:14)
From previous event:
    at Connection._handleNetworkError (/Users/tseian/Downloads/node/youme/node_modules/mysql/lib/Connection.js:303:18)
    at ConnectionManager.connect (/Users/tseian/Downloads/node/youme/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:55:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at ConnectionManager.<anonymous> (/Users/tseian/Downloads/node/youme/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:247:43)
    at connectErrorNT (net.js:1022:8)`

THX!

**Comment by kjatti** [comment]
mysql clients treat localhost and 127.0.0.1 differently, [see](http://stackoverflow.com/questions/19712307/mysql-localhost-127-0-0-1)

**Comment by Tseian** [comment]
thank you for your help
