### ISSUE TITLE
Eager include in one-to-many not working from the "many" side

### ISSUE THREAD

**Issue by atheros** [sequelize/sequelize#7561]
```js
let db = new Sequelize(DB_NAME, DB_USER, DB_PASS, {
            host: DB_HOST,
            dialect: DB_TYPE,
        });

let City = db.define('cities', {
    name: {
        type: Sequelize.STRING
    }
});


let Building = db.define('buildings', {
    name: {
        type: Sequelize.STRING
    }
});


City.hasMany(Building, { as: 'buildings'});


async function main() {
    await db.sync();
    
    let result = await Building.findAll({
        include: [City]
    });

    console.log(result);
}

main().then(() => {}, (e) => { console.error(e.stack); });
```

## What do you expect to happen?
I would expect the result to contain buildings with loaded cities.

## What is actually happening?
```
Error: cities is not associated to buildings!
    at Function._validateIncludedElement (/Users/przemyslawgrzywacz/PycharmProjects/cicos/maps/node_modules/sequelize/lib/model.js:478:13)
    at options.include.options.include.map.include (/Users/przemyslawgrzywacz/PycharmProjects/cicos/maps/node_modules/sequelize/lib/model.js:363:37)
    at Array.map (native)
    at Function._validateIncludedElements (/Users/przemyslawgrzywacz/PycharmProjects/cicos/maps/node_modules/sequelize/lib/model.js:359:39)
    at Promise.try.then.then (/Users/przemyslawgrzywacz/PycharmProjects/cicos/maps/node_modules/sequelize/lib/model.js:1458:14)
    at tryCatcher (/Users/przemyslawgrzywacz/PycharmProjects/cicos/maps/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/przemyslawgrzywacz/PycharmProjects/cicos/maps/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/przemyslawgrzywacz/PycharmProjects/cicos/maps/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/przemyslawgrzywacz/PycharmProjects/cicos/maps/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/przemyslawgrzywacz/PycharmProjects/cicos/maps/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/przemyslawgrzywacz/PycharmProjects/cicos/maps/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/przemyslawgrzywacz/PycharmProjects/cicos/maps/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/przemyslawgrzywacz/PycharmProjects/cicos/maps/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
```

__Dialect:__ mysql
__Database version:__ latest
__Sequelize version:__ 4.0.0-2

**Comment by janmeier** [comment]
You need to add the other side of the relation (`Building.belongsTo(City)`)
