### ISSUE TITLE
isUrl validation seems to fail with underscores

### ISSUE THREAD

**Issue by fredguile** [sequelize/sequelize#7563]
Hi team (and sorry for the dup if I did miss it),

I've just noticed something bad with the isUrl validation on fields of type STRING: they apparently don't validate url containing underscores. I discovered that while using a docker hostname.

That's basically what I get when I use the value "http://coffeecircle_lamp_1/api":

```
nodejs_1    | [14:14:34] SequelizeValidationError: Validation error: Validation isUrl failed
nodejs_1    |     at /opt/app/node_modules/sequelize/lib/instance-validator.js:74:14
nodejs_1    |     at runCallback (timers.js:672:20)
nodejs_1    | From previous event:
nodejs_1    |     at Promise.then (/opt/app/node_modules/sequelize/lib/promise.js:21:17)
nodejs_1    |     at transactionResolver (/opt/app/node_modules/sequelize/lib/sequelize.js:1284:40)
nodejs_1    | From previous event:
nodejs_1    |     at Sequelize.transaction (/opt/app/node_modules/sequelize/lib/sequelize.js:1313:12)
nodejs_1    |     at up (/opt/app/src/database/migrations/001-init.js:87:20)
nodejs_1    |     at Object.<anonymous> (/opt/app/src/helpers/umzugFactory.js:18:20)
nodejs_1    |     at constructor._exec (/opt/app/node_modules/umzug/lib/migration.js:103:23)
nodejs_1    |     at constructor.up (/opt/app/node_modules/umzug/lib/migration.js:69:17)
nodejs_1    |     at constructor.<anonymous> (/opt/app/node_modules/umzug/index.js:124:28)
nodejs_1    | From previous event:
nodejs_1    |     at Promise.tap (/opt/app/node_modules/sequelize/lib/promise.js:21:17)
nodejs_1    |     at /opt/app/node_modules/umzug/index.js:105:14
nodejs_1    |     at runCallback (timers.js:672:20)
nodejs_1    |     at tryOnImmediate (timers.js:645:5)
nodejs_1    |     at processImmediate [as _immediateCallback] (timers.js:617:5)
nodejs_1    | From previous event:
nodejs_1    |     at Function.each (/opt/app/node_modules/sequelize/lib/promise.js:21:17)
nodejs_1    |     at /opt/app/node_modules/umzug/index.js:94:25
nodejs_1    | From previous event:
nodejs_1    |     at Promise.then (/opt/app/node_modules/sequelize/lib/promise.js:21:17)
nodejs_1    |     at constructor.execute (/opt/app/node_modules/umzug/index.js:93:8)
nodejs_1    |     at _bluebird2.default.join.spread (/opt/app/tasks/gulp.database.js:67:12)
nodejs_1    | From previous event:
nodejs_1    |     at Promise.spread (/opt/app/node_modules/sequelize/lib/promise.js:21:17)
nodejs_1    |     at Gulp.gulp.task (/opt/app/tasks/gulp.database.js:65:8)
nodejs_1    |     at module.exports (/opt/app/node_modules/orchestrator/lib/runTask.js:34:7)
nodejs_1    |     at Gulp.Orchestrator._runTask (/opt/app/node_modules/orchestrator/index.js:273:3)
nodejs_1    |     at Gulp.Orchestrator._runStep (/opt/app/node_modules/orchestrator/index.js:214:10)
nodejs_1    |     at Gulp.Orchestrator.start (/opt/app/node_modules/orchestrator/index.js:134:8)
nodejs_1    |     at /opt/app/node_modules/gulp/bin/gulp.js:129:20
nodejs_1    |     at _combinedTickCallback (internal/process/next_tick.js:73:7)
nodejs_1    |     at process._tickCallback (internal/process/next_tick.js:104:9)
nodejs_1    |     at Module.runMain (module.js:607:11)
nodejs_1    |     at run (bootstrap_node.js:423:7)
nodejs_1    |     at startup (bootstrap_node.js:147:9)
nodejs_1    |     at bootstrap_node.js:538:3
nodejs_1    | npm ERR! code ELIFECYCLE
nodejs_1    | npm ERR! errno 1
```

I would have expected that the validation passes with underscores they are considered as valid for RFC 3986 URIs.

__Dialect:__  postgres
__Database version:__ not sure, that's a docker image
__Sequelize version:__ 3.30.4

**Comment by janmeier** [comment]
We defer validations to validator.js  https://github.com/chriso/validator.js - You need to explicitly allow underscores

```js
validate: {
  isUrl: { allow_underscores: true },
  isUrl: [{ allow_underscores: true }]
}
``` 
I don't recall which is the correct syntax, but soething like that

**Comment by fredguile** [comment]
Thanks, found it from `validator:js`doc:

- isFQDN(str [, options]) - check if the string is a fully qualified domain name (e.g. domain.com). options is an object which defaults to { require_tld: true, allow_underscores: false, allow_trailing_dot: false }.

Hope that this can be useful for everybody.
