### ISSUE TITLE
Optimistic Locking (version) does not work on MySQL

### ISSUE THREAD

**Issue by bcowgill** [sequelize/sequelize#7576]
## What you are doing?
Trying to test that optimistic locking works. I've configured it but I don't see the version attribute being created nor do stale models get prevented from saving their data.

```json5
// default api config values
{
	database: {
		host: "mysql",
		database: "my_test",
		username : "root",
		password : "pasword",
		dialect: "mysql",
		pool: {
			max: 5,
			min: 0,
			idle: 10000,
		},
		// http://sequelize.readthedocs.io/en/latest/docs/models-definition/
		define: {
		    timestamps: true,
		    paranoid: false,  // actually delete models instead of using deletedAt field
		    underscored: false,
		    freezeTableName: true,  // prevent pluralization of table names
		    version: true, // optimistic locking on model records to avoid overwrite by stale data
		},
	}
}
```

```typescript
/// <reference path="../typings/index.d.ts" />

// database.ts
// handle the details of database access

const config = require("config");
//import * as Sequelize from "sequelize";
const Sequelize = require("sequelize");
import { DBConfig } from "../app-config";

const forceDrop : boolean = true;
const dbConfig : DBConfig = config.get("database");

console.error("creds", dbConfig);
const sequelize = new Sequelize(
    dbConfig.database
    , dbConfig.username
    , dbConfig.password
    , dbConfig
);

void sequelize; //tslint:disable-line:no-unused-expression

// A test model for experimenting with Sequelize
var Xyzzy = sequelize.define("xyzzy", {
        title: { type: Sequelize.STRING },
        heads: { type: Sequelize.INTEGER, defaultValue: 1 },
        arms: { type: Sequelize.INTEGER, defaultValue: 2 },
        description: {
            type: Sequelize.STRING
            , defaultValue: "Just this guy, you know."
        }
    }, {
        comment: "test of model synchronization with database schema"
    });

function playWithXyzzy () {
    const thing /*: Sequelize.Model*/ = Xyzzy.build({
        title: "Lord Coder of the Realm"
        , description: "With great power comes great responsibility"
    });

    thing.save()
        .then(() => {
            console.log(`thing has been saved: ${thing.id} : ${thing.title}  @ ${thing.updatedAt}`);

            // get another ref to the thing to test optimistic locking
            Xyzzy.findById(thing.id)
                .then((thingLocked : typeof thing) => {
                    console.log(`laid hands on the thing again ${thingLocked === thing} ${thingLocked.id}`
                        + ` : ${thingLocked.title} @ ${thing.updatedAt}`);
                    setTimeout(() => {
                        thingLocked.update({ title: "Fallen from Grace" })
                            .then(() => {
                                console.log(`thing has been disgraced ${thingLocked.id} : ${thingLocked.title} @ ${thingLocked.updatedAt}`);
                                setTimeout(() => {
                                    console.log(`about to update stale thing: ${thing.id} : ${thing.title} @ ${thing.updatedAt}`);
                                    thing.update({ title: "Restored to Honour" })
                                        .then(() => {
                                            console.error(`was not expecting stale thing to be saved. ${thingLocked.title} `
                                                + `${thing.title} @ ${thingLocked.updatedAt} ${thing.updatedAt}`);
                                        })
                                        .catch((error : any) => {
                                            console.log("stale thing could not be saved, excellent!", error);
                                            thingLocked.destroy({ force: true })
                                                .then(() => {
                                                    console.log("thing has been utterly destroyed");
                                                })
                                                .catch((error : any) => {
                                                    console.error("thing resisted destruction! inconceivable", error);
                                                });
                                        });
                                }, 2000);
                            })
                            .catch((error : any) => {
                                console.error("thing resisted disgrace", error);
                            });

                    }, 2000);
                })
                .catch((error : any) => {
                    console.error("couldn't lay hands on the thing again.", error);
                });
        })
        .catch((error : any) => {
            console.error("thing was not saved", error);
        });
}

console.log("about to sync the model");
// Create all tables defined from models
sequelize.sync({
    force: forceDrop
    , match: /_test$/
})
    .then(() => {
        console.log("sequelize has synchronized all models");
        playWithXyzzy();
    })
    .catch((error : any) => {
        console.error("sequelize unable to synchronize models", error);
    });

```

## What do you expect to happen?
The Xyzzy model should have a version attribute and when I try to save a stale model it should return an OptimisticLockingError and the stale data should not be saved.

## What is actually happening?
There is no version attribute on the model table and the stale data is saved to the database.

The sequelize created table is as follows
```sql
CREATE TABLE `xyzzy` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) DEFAULT NULL,
  `heads` int(11) DEFAULT '1',
  `arms` int(11) DEFAULT '2',
  `description` varchar(255) DEFAULT 'Just this guy, you know.',
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COMMENT='test of model synchronization with database schema';
```

```
node_1   | creds { host: 'mysql',
node_1   |   database: 'my_test',
node_1   |   username: 'root',
node_1   |   password: 'pasword',
node_1   |   dialect: 'mysql',
node_1   |   pool: { max: 5, min: 0, idle: 10000 },
node_1   |   define: 
node_1   |    { timestamps: true,
node_1   |      paranoid: false,
node_1   |      underscored: false,
node_1   |      freezeTableName: true,
node_1   |      version: true } }
node_1   | about to sync the model
node_1   | GET /my/status 200 217.989 ms - 43
node_1   | EVENT LOOP BLOCKED FOR 188ms
node_1   | sequelize has synchronized all models
node_1   | (node:118) Warning: a promise was created in a handler at app/build/helpers/database.js:77:5 but was not returned from it, see http://goo.gl/rRqMUw
node_1   |     at Function.Promise.bind (/app/node_modules/bluebird/js/release/bind.js:65:20)
node_1   | Executing (default): INSERT INTO `xyzzy` (`id`,`title`,`heads`,`arms`,`description`,`createdAt`,`updatedAt`) VALUES (DEFAULT,'Lord Coder of the Realm',1,2,'With great power comes great responsibility','2017-04-27 13:09:48','2017-04-27 13:09:48');
node_1   | thing has been saved: 1 : Lord Coder of the Realm  @ Thu Apr 27 2017 13:09:48 GMT+0000 (UTC)
node_1   | (node:118) Warning: a promise was created in a handler at anonymous> (/app/build/helpers/database.js:30:15 but was not returned from it, see http://goo.gl/rRqMUw
node_1   |     at Function.Promise.bind (/app/node_modules/bluebird/js/release/bind.js:65:20)
node_1   | Executing (default): SELECT `id`, `title`, `heads`, `arms`, `description`, `createdAt`, `updatedAt` FROM `xyzzy` AS `xyzzy` WHERE `xyzzy`.`id` = 1;
node_1   | laid hands on the thing again false 1 : Lord Coder of the Realm @ Thu Apr 27 2017 13:09:48 GMT+0000 (UTC)
node_1   | Executing (default): UPDATE `xyzzy` SET `title`='Fallen from Grace',`updatedAt`='2017-04-27 13:09:50' WHERE `id` = 1
node_1   | thing has been disgraced 1 : Fallen from Grace @ Thu Apr 27 2017 13:09:50 GMT+0000 (UTC)
node_1   | about to update stale thing: 1 : Lord Coder of the Realm @ Thu Apr 27 2017 13:09:48 GMT+0000 (UTC)
node_1   | Executing (default): UPDATE `xyzzy` SET `title`='Restored to Honour',`updatedAt`='2017-04-27 13:09:52' WHERE `id` = 1
node_1   | was not expecting stale thing to be saved. Fallen from Grace Restored to Honour @ Thu Apr 27 2017 13:09:50 GMT+0000 (UTC) Thu Apr 27 2017 13:09:52 GMT+0000 (UTC)
```

__Dialect:__ mysql
__Database version:__ mysql  Ver 14.14 Distrib 5.6.35, for Linux (x86_64) using  EditLine wrapper
__Sequelize version:__ sequelize@3.30.4

**Comment by mjcmatrix** [comment]
I am trying to enable optimistic locking too, on sqlite3, following the documentation ( http://docs.sequelizejs.com/en/latest/docs/models-definition/#optimistic-locking ) and I don't get any version column either.

**Comment by mjcmatrix** [comment]
Reference PR:  https://github.com/sequelize/sequelize/pull/6637

**Comment by mjcmatrix** [comment]
@bcowgill 
The optimistic locking feature seems to be pre-release currently.

https://github.com/sequelize/sequelize/blob/master/changelog.md
https://www.npmjs.com/package/sequelize

**Comment by mjcmatrix** [comment]
Is there any chance you could cut a v4.0.0-3 pre-release that contains optimistic locking please?

**Comment by buccfer** [comment]
sqlite doesn't support concurrence, so I don't get the point to use optimistic locking with it.
