### ISSUE TITLE
Cannot have 'Model' property in attributes. 

### ISSUE THREAD

**Issue by noahprince22** [sequelize/sequelize#7591]
## What you are doing?
I'm defining a sequelize model that has a 'Model' attribute. 

```js
sequelize.define('favorite_cars', { Model: { type: DataTypes.TEXT } })
```

## What do you expect to happen?
I shouldn't get an error. 

## What is actually happening?
```js
TypeError: Cannot read property 'Model' of undefined
    at Instance.set (/Users/nprince/apps/nacho/app/node_modules/sequelize/lib/instance.js:306:38)
    at Instance.funcs.(anonymous function) (/Users/nprince/apps/nacho/app/node_modules/sequelize/lib/model.js:780:23)
    at Model.init (/Users/nprince/apps/nacho/app/node_modules/sequelize/lib/model.js:723:33)
    at Sequelize.define (/Users/nprince/apps/nacho/app/node_modules/sequelize/lib/sequelize.js:632:17)
```

__Dialect:__ postgres
__Database version:__ 9.6
__Sequelize version:__ 3.30.2

Are there any other keywords like 'Model' that cannot be used as attributes?

**Comment by sushantdhiman** [comment]
Its fixed in master atleast

```js
'use strict';

/*
 * Copy this file to ./sscce.js
 * Add code from issue
 * npm run sscce-{dialect}
 */

const Sequelize = require('./index');
const sequelize = require('./test/support').createSequelizeInstance();

const M = sequelize.define('M', {
  status: Sequelize.STRING,
  Model: Sequelize.STRING
});

const N = sequelize.define('N', {
  status: Sequelize.STRING
});

M.belongsTo(N);
N.hasOne(M);

sequelize.sync({ force: true })
  .then(() => M.create({ status: 1, Model: 'Tata' }))
  .then(m => console.log(m.toJSON()));



{ id: 1,
  status: 1,
  Model: 'Tata',
  updatedAt: 2017-05-12T08:59:08.225Z,
  createdAt: 2017-05-12T08:59:08.225Z }

```
