### ISSUE TITLE
ER_PARSE_ERROR: You have an error in your SQL syntax. Using sequelize.fn

### ISSUE THREAD

**Issue by Drakehawk** [sequelize/sequelize#7594]
Hi. I'm having issues using sequelize.fn('max'). Code below
```js
var query = this.app.orm.Reportes.find({
			attributes: [sequelize.fn('max', sequelize.col('ReDateTime')), 'ReDateTime'],
			where: {ReMovil: id, ReEmpresa: emp, ReEstadoGps: 1},
		}).catch(function(error){
			console.log(error);
		});
```
And I'm getting the following error:

```js
Executing (default): SELECT [object Object], `ReDateTime` FROM `reportes` AS `Reportes` WHERE `Reportes`.`ReMovil` = '2500' AND `Reportes`.`ReEmpresa` = '1' AND `Reportes`.`ReEstadoGps` = 1 LIMIT 1;
{ SequelizeDatabaseError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[object Object], `ReDateTime` FROM `reportes` AS `Reportes` WHERE `Reportes`.`Re' at line 1
    at Query.formatError (/media/data/evolsoa/node_modules/trailpack-sequelize/node_modules/sequelize/lib/dialects/mysql/query.js:175:14)
    at Query.<anonymous> (/media/data/evolsoa/node_modules/trailpack-sequelize/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
    at bound (domain.js:280:14)
    at Query.runBound [as _callback] (domain.js:293:12)
    at Query.Sequence.end (/media/data/evolsoa/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at Query.ErrorPacket (/media/data/evolsoa/node_modules/mysql/lib/protocol/sequences/Query.js:88:8)
    at Protocol._parsePacket (/media/data/evolsoa/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/media/data/evolsoa/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/media/data/evolsoa/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/media/data/evolsoa/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)
From previous event:
    at Query.run (/media/data/evolsoa/node_modules/trailpack-sequelize/node_modules/sequelize/lib/dialects/mysql/query.js:39:17)
    at /media/data/evolsoa/node_modules/trailpack-sequelize/node_modules/sequelize/lib/sequelize.js:849:20
    at /media/data/evolsoa/node_modules/retry-as-promised/index.js:40:21
    at retryAsPromised (/media/data/evolsoa/node_modules/retry-as-promised/index.js:30:10)
    at .<anonymous> (/media/data/evolsoa/node_modules/trailpack-sequelize/node_modules/sequelize/lib/sequelize.js:848:12)
From previous event:
    at Promise.<anonymous> (/media/data/evolsoa/node_modules/trailpack-sequelize/node_modules/sequelize/lib/promise.js:21:17)
    at Promise.then (/media/data/evolsoa/node_modules/sequelize/lib/promise.js:21:17)
    at Model.findAll (/media/data/evolsoa/node_modules/trailpack-sequelize/node_modules/sequelize/lib/model.js:1395:6)
    at Model.findOne (/media/data/evolsoa/node_modules/trailpack-sequelize/node_modules/sequelize/lib/model.js:1527:34)
    at ReportesService.interval (/media/data/evolsoa/api/services/ReportesService.js:387:37)
    at ReportesController.getInterval (/media/data/evolsoa/api/controllers/ReportesController.js:45:43)
    at Object.internals.handler (/media/data/evolsoa/node_modules/hapi/lib/handler.js:96:36)
    at request._protect.run (/media/data/evolsoa/node_modules/hapi/lib/handler.js:30:23)
    at internals.Protect.run (/media/data/evolsoa/node_modules/hapi/lib/protect.js:62:12)
    at exports.execute (/media/data/evolsoa/node_modules/hapi/lib/handler.js:24:22)
    at each (/media/data/evolsoa/node_modules/hapi/lib/request.js:380:16)
    at iterate (/media/data/evolsoa/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at done (/media/data/evolsoa/node_modules/hapi/node_modules/items/lib/index.js:28:25)
    at request.connection.states.parse (/media/data/evolsoa/node_modules/hapi/lib/route.js:384:20)
    at Items.serial (/media/data/evolsoa/node_modules/hapi/node_modules/statehood/lib/index.js:244:16)
    at done (/media/data/evolsoa/node_modules/hapi/node_modules/items/lib/index.js:31:25)
    at Items.serial (/media/data/evolsoa/node_modules/hapi/node_modules/statehood/lib/index.js:184:20)
    at iterate (/media/data/evolsoa/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at done (/media/data/evolsoa/node_modules/hapi/node_modules/items/lib/index.js:28:25)
    at Items.serial (/media/data/evolsoa/node_modules/hapi/node_modules/statehood/lib/index.js:184:20)
    at iterate (/media/data/evolsoa/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at done (/media/data/evolsoa/node_modules/hapi/node_modules/items/lib/index.js:28:25)
    at Items.serial (/media/data/evolsoa/node_modules/hapi/node_modules/statehood/lib/index.js:184:20)
    at iterate (/media/data/evolsoa/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at Object.exports.serial (/media/data/evolsoa/node_modules/hapi/node_modules/items/lib/index.js:39:9)
  name: 'SequelizeDatabaseError',
```

I checked my model and everything works fine. But when I use functions I got the error.

__Dialect:__ mysql 
__Database version:__ 5.6
__Sequelize version:__ 3.3.0

**Comment by janmeier** [comment]
`attributes: [[sequelize.fn('max', sequelize.col('ReDateTime')), 'ReDateTime']],`

The function + its alias needs to be wrapped in an array

**Comment by Drakehawk** [comment]
Wrapped in array but still have the same issue:

``
var query = this.app.orm.Reportes.find({
			attributes: [[sequelize.fn('max', sequelize.col('ReDateTime')), 'ReDateTime']],
			where: {ReMovil: id, ReEmpresa: emp, ReEstadoGps: 1},
		}).catch(function(error){
			console.log(error);
		});
``

``
Executing (default): SELECT [object Object] AS `ReDateTime` FROM `reportes` AS `Reportes` WHERE `Reportes`.`ReMovil` = '1633012167' AND `Reportes`.`ReEmpresa` = '350' AND `Reportes`.`ReEstadoGps` = 1 LIMIT 1;
``

**Comment by fab-1** [comment]
@Drakehawk did you find a solution? I have the same issue : 
`attributes: ['id', 'name', [sequelize.fn('COUNT', sequelize.col('id')) , 'count'], 'image'],`

**Comment by dskvr** [comment]
Ded repo.
