### ISSUE TITLE
Sync fails with VIRTUAL column type

### ISSUE THREAD

**Issue by cmorford** [sequelize/sequelize#7599]
## What you are doing?
Trying to use a model with a VIRTUAL field

```js
orm = Sequelize connect here.....
Employees = orm.define('Employees', {
      id: {
        type: Sequelize.INTEGER,
        primaryKey: true,
        autoIncrement: true
      },
      account_id: Sequelize.INTEGER,
      first_name: Sequelize.STRING(45),
      last_name: Sequelize.STRING(45),
      base_rate: Sequelize.DECIMAL(7, 2),
      default_location_id: Sequelize.INTEGER,
      person: {
        type: Sequelize.VIRTUAL,
        get: function() {
          var first_name, last_name, person;
          first_name = this.get('first_name');
          last_name = this.get('last_name');
          person = {
            first_name: first_name,
            last_name: last_name
          };
          return person;
        }
      }
    }
```

## What do you expect to happen?
Run model.sync() to create database table

## What is actually happening?
When I try to sync, i get an SQL error.  It appears sequelize is trying to create a virtual column, which isn't a valid type:
```
Executing (default): SELECT `id`, `account_id`, `first_name`, `last_name`, `base_rate`, `default_location_id`, `person`, `created_at`, `updated_at`, `deleted_at` FROM `Employees` AS `Employees` WHERE `Employees`.`deleted_at` IS NULL ORDER BY `Employees`.`last_name` ASC, `Employees`.`first_name` ASC;
{ SequelizeBaseError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'VIRTUAL, `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, `delete' at line 1
  at Query.formatError (/Users/cmorford/Development/BigBlueSwimSchool/Services/employee-service/node_modules/sequelize/lib/dialects/mysql/query.js:175:14)
  at Query._callback (/Users/cmorford/Development/BigBlueSwimSchool/Services/employee-service/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
  at Query.Sequence.end (/Users/cmorford/Development/BigBlueSwimSchool/Services/employee-service/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
  at Query.ErrorPacket (/Users/cmorford/Development/BigBlueSwimSchool/Services/employee-service/node_modules/mysql/lib/protocol/sequences/Query.js:88:8)
  at Protocol._parsePacket (/Users/cmorford/Development/BigBlueSwimSchool/Services/employee-service/node_modules/mysql/lib/protocol/Protocol.js:280:23)
  at Parser.write (/Users/cmorford/Development/BigBlueSwimSchool/Services/employee-service/node_modules/mysql/lib/protocol/Parser.js:75:12)
  at Protocol.write (/Users/cmorford/Development/BigBlueSwimSchool/Services/employee-service/node_modules/mysql/lib/protocol/Protocol.js:39:16)
  at Socket.<anonymous> (/Users/cmorford/Development/BigBlueSwimSchool/Services/employee-service/node_modules/mysql/lib/Connection.js:103:28)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:189:7)
  at readableAddChunk (_stream_readable.js:176:18)
  at Socket.Readable.push (_stream_readable.js:134:10)
  at TCP.onread (net.js:551:20)

  name: 'SequelizeDatabaseError',
  message: 'ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'VIRTUAL, `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, `delete\' at line 1',```

__Dialect:__ mariadb
__Database version:__ 5.6.10
__Sequelize version:__ 3.30.4

**Comment by balexandre** [comment]
just tried your example in my model and I do get everything correctly...

what query are you invoking for throwing that error?

**Comment by cmorford** [comment]
OK, it looks like one of my dependencies was using sequelize 3.30.3 so I had the incorrect version reported.  3.30.3 does exhibit this error, but it appears the issue was resolved in 3.30.4.

**Comment by jedwards1211** [comment]
@balexandre I'm getting this error with sequelize 3.30.4 when I use `queryInterface.addColumn`.

**Comment by roni-frantchi** [comment]
Getting the exact same error on the same database version (MySQL 5.6) with the latest Sequelize `5.9.4`

**Comment by papb** [comment]
@roni-frantchi Can you provide a MCVE?

**Comment by wachukxs** [comment]
@papb I hope this documentation in this issue helps https://github.com/sequelize/sequelize/issues/12451
