### ISSUE TITLE
attributes has no effect in include

### ISSUE THREAD

**Issue by naveenkonduru** [sequelize/sequelize#7604]
Here is the code, Im getting error when I include attributes for models.User. below is the sample code. I haven't find any working solution on stackoverflow. Any help would be much appreciated.

```ruby
models.Project.findAndCountAll({
      include: [
         {
           model: models.User,
           attributes: ['first_name', 'last_name'],
           separate: true,
           order:[['updatedAt','DESC']]
          }
      ],
      attributes: ['project_name'],
      where: {
        UserSlug:'someuserid'
      }
    })
```
Here is the User model

```ruby
module.exports = (sequelize, DataTypes) => {

  var User = sequelize.define("User", {
    slug:{
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
    },
    username:{
      type: DataTypes.STRING,
    },
    email:{
      type: DataTypes.STRING,
      field: 'email'
    },
    firstName:{
      type: DataTypes.STRING,
    },
    lastName:{
      type: DataTypes.STRING,
    }
  }, {
    classMethods:{
      associate: (models) => {
        User.belongsTo(models.Project, {
          onDelete: "CASCADE",
          foreignKey: {
            allowNull: false
          }
        });
      }
    }
  });

  return User;
};
```

Here is the Project model

```ruby
module.exports = (sequelize, DataTypes) => {

  var Project = sequelize.define("Project", {
    slug:{
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
    },
    project_name:{
      type: DataTypes.STRING,
    }
  }, {
    classMethods:{
      associate: (models) => {
      Project.hasMany(models.User,{
          foreignKey: {
            allowNull: false
          }
        });
      }
    }
  });

  return Project;
};

```

Here is the error:
```ruby
Unhandled rejection TypeError: Cannot read property 'push' of undefined
    at /konduru/server/node_modules/sequelize/lib/associations/has-many.js:344:64
    at Array.forEach (native)
    at .<anonymous> (/konduru/server/node_modules/sequelize/lib/associations/has-many.js:343:13)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at tryCatcher (/konduru/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/konduru/server/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/konduru/server/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/konduru/server/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/konduru/server/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/konduru/server/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/konduru/server/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/konduru/server/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:566:20)
    at tryOnImmediate (timers.js:546:5)
    at processImmediate [as _immediateCallback] (timers.js:525:5)
```

**Comment by naveenkonduru** [comment]
this is the way to go:
include: [
        {
          model: models.User,
          attributes:{ include: ['firstName','lastName'], exclude:['updatedAt','createdAt'] },
          separate: true,
          offset: 0,
          limit: 1,
          order:[['updatedAt','DESC']],
  }
]

**Comment by isTravis** [comment]
Any idea why this is the case though? 

It feels verbose and fragile to specify all the fields I want excluded, when my goal is to use `attributes` to only include a single value. For example: `attributes: ['id']`
