### ISSUE TITLE
Error on using references in model

### ISSUE THREAD

**Issue by aburkes** [sequelize/sequelize#7654]
## What you are doing?

```js
module.exports = db.define("customItems", {
//snip
    customItemID: {
        type: Sequelize.INTEGER,
        references: {
            model: "customItemLibrary",
            key: "customItemID"
        }
    }
//snip
});
```
I'm in the early stages of building this application. There is one other field similar in structure in my source that gives the exact same error. The `customItemLibrary` model is already defined by this point, of course.

## What do you expect to happen?
Sequelize should build the model. 

## What is actually happening?

Node spits out an error in Sequelize:

`/home/ubuntu/workspace/node_modules/sequelize/lib/utils.js:532
    return s.replace(new RegExp(tickChar, 'g'), "")
             ^

TypeError: s.replace is not a function
    at Object.removeTicks (/home/ubuntu/workspace/node_modules/sequelize/lib/utils.js:532:14)
    at Object.addTicks (/home/ubuntu/workspace/node_modules/sequelize/lib/utils.js:528:29)
    at Object.quoteIdentifier (/home/ubuntu/workspace/node_modules/sequelize/lib/dialects/sqlite/query-generator.js:424:20)
    at Object.attributesToSQL (/home/ubuntu/workspace/node_modules/sequelize/lib/dialects/sqlite/query-generator.js:282:49)
    at DAOFactory.get (/home/ubuntu/workspace/node_modules/sequelize/lib/dao-factory.js:67:34)
    at DAOFactory.module.exports.DAOFactory.init (/home/ubuntu/workspace/node_modules/sequelize/lib/dao-factory.js:137:22)
    at Sequelize.module.exports.Sequelize.define (/home/ubuntu/workspace/node_modules/sequelize/lib/sequelize.js:262:43)
    at Object.<anonymous> (/home/ubuntu/workspace/database/models/CustomItems.js:4:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)`

__Dialect:__ sqlite 
__Database version:__ 3.8.2
__Sequelize version:__ 1.7.11

**Comment by sushantdhiman** [comment]
Sorry we no longer support `1.7.11` that is just too old. Please update to latest `v3` or may be upcoming `v4`. You said you are in early stages of building your application, you should definitely use at least `v3`.

**Comment by aburkes** [comment]
I am so sorry. I thought npm had given me the latest version. It turns out I accidentally typed in "sequelizer" by mistake and it pulled the old version as a requirement.
