### ISSUE TITLE
Disable ROLLBACK TO SAVEPOINT on Postgresql RDS

### ISSUE THREAD

**Issue by fstn** [sequelize/sequelize#7662]
Error:

SequelizeDatabaseError: SAVEPOINT can only be used in transaction blocks,SequelizeDatabaseError: SAVEPOINT can only be used in transaction blocks.

`at Query.formatError (/usr/src/app/node_modules/sequelize/lib/dialects/postgres/query.js:347:16)
at Query.query.on.err (/usr/src/app/node_modules/sequelize/lib/dialects/postgres/query.js:92:21)
at emitOne (events.js:101:20)
at Query.emit (events.js:188:7)
at Query.handleError (/usr/src/app/node_modules/pg/lib/query.js:143:8)
at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:181:26)
at emitOne (events.js:96:13)
at Connection.emit (events.js:188:7)
at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:136:12)`

When trying to do : 
` return Model.SequelizeUtils.get().query('DELETE FROM "userCronActions" WHERE "executionDate"::date=?::date and "userId"=?',`

Version:
`
    "pg": "^6.1.0",
    "pg-hstore": "^2.3.2",
"sequelize": "^4.0.0-2",
`

Thank you

**Comment by fstn** [comment]
ok, so ROLLBACK TO SAVEPOINT is not available on PostGres RDS databases :( How can I disable it on Sequelize?

**Comment by janmeier** [comment]
Savepoints are only used in transactions, and i don't see any mention of transactions in your code. Are you sure this is the code that produces the error?
