### ISSUE TITLE
Feature request: Better error message on unsupported NUMBER field type

### ISSUE THREAD

**Issue by AJamesPhillips** [sequelize/sequelize#7691]
## What you are doing?

migrations/0003_create_oz_user_grant.js
```js
export = {
    up: function(queryInterface, Sequelize) {
        const FIELDS = {
            exp: {
                type: Sequelize.NUMBER,  // <- made a mistake here, postgres does not support NUMBER
                allowNull: false,
            },
        };
        return queryInterface.createTable("oz_user_grant", FIELDS);
    },

    down: function(queryInterface) {
        return queryInterface.dropTable("oz_user_grant");
    }
};
```

    node ./node_modules/.bin/sequelize db:migrate --env development

## What do you expect to happen?

Receive an error like: "NUMBER not a valid type for postgresql dialect".

## What is actually happening?

    TypeError: Cannot read property 'length' of undefined

```
Sequelize [Node: 6.10.2, CLI: 2.7.0, ORM: 3.30.4]

Loaded configuration file "build/server/server/utils/sequelize_cli_config.js".
Using environment "development".
== 0003_create_oz_user_grant: migrating =======
TypeError: Cannot read property 'length' of undefined
    at new <anonymous> (/example_app/node_modules/sequelize/lib/data-types.js:203:25)
    at Sequelize.normalizeDataType (/example_app/node_modules/sequelize/lib/sequelize.js:1359:43)
    at Sequelize.normalizeAttribute (/example_app/node_modules/sequelize/lib/sequelize.js:1378:25)
    at /example_app/node_modules/sequelize/lib/query-interface.js:87:32
    at /example_app/node_modules/sequelize/node_modules/lodash/lodash.js:12666:23
    at /example_app/node_modules/sequelize/node_modules/lodash/lodash.js:4389:15
    at baseForOwn (/example_app/node_modules/sequelize/node_modules/lodash/lodash.js:2652:24)
    at Function.mapValues (/example_app/node_modules/sequelize/node_modules/lodash/lodash.js:12665:7)
    at QueryInterface.createTable (/example_app/node_modules/sequelize/lib/query-interface.js:82:24)
    at Object.up (/example_app/build/server/server/migrations/0003_create_oz_user_grant.js:18:31)
    at constructor._exec (/example_app/node_modules/umzug/lib/migration.js:104:23)
    at constructor.up (/example_app/node_modules/umzug/lib/migration.js:69:17)
    at constructor.<anonymous> (/example_app/node_modules/umzug/index.js:124:28)
    at PassThroughHandlerContext.finallyHandler (/example_app/node_modules/bluebird/js/release/finally.js:57:23)
    at PassThroughHandlerContext.tryCatcher (/example_app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/example_app/node_modules/bluebird/js/release/promise.js:512:31)
```

__Dialect:__ postgres
__Database version:__ PostgreSQL 9.6.3
__Sequelize version:__ 3.30.4

**Comment by AJamesPhillips** [comment]
(Thanks for the amazing library by the way! :D  Really excellent work.  And I'd really like to contribute towards getting migration diffs one day but alas I can't help any time soon.).

**Comment by AJamesPhillips** [comment]
Still an issue :)
