### ISSUE TITLE
cannot save chinese  charater to database.

### ISSUE THREAD

**Issue by YUFENGWANG** [sequelize/sequelize#7781]
## What you are doing?
I am trying to save some chinese character to the database, 

```js
var Word = models.Word
    Word
      .findOrCreate({where: {ori_word: data.ori_word}, defaults: {cut_word: result}})
      .spread((word, created) => {
        console.log(word.get({
          plain: true
        }))
        console.log(created)
      })
	res.send(result)
module.exports = {
    up: function(queryInterface, Sequelize) {
        return queryInterface.createTable(
            'Words', {
                id: {
                    type: Sequelize.INTEGER,
                    primaryKey: true,
                    autoIncrement: true
                },
                createdAt: {
                    type: Sequelize.DATE
                },
                updatedAt: {
                    type: Sequelize.DATE
                },
                ori_word: Sequelize.STRING,
                cut_word: Sequelize.STRING,
            },
            {
              charset: 'utf8',
            }
        )
    },

    down: function(queryInterface, Sequelize) {
        return queryInterface.dropTable('Words');
    }

};
module.exports = function(sequelize, DataTypes) {

    var Word = sequelize.define("Word", {
        ori_word: DataTypes.STRING,
        cut_word: DataTypes.STRING,
    });
    return Word;

};




```

## What do you expect to happen?
I want the characer to be saved into  database.

## What is actually happening?
```bash
{ ori_word: '带上飞机啊甲方的我们是阿德啊阿飞阿斯蒂芬' }
Executing (3f4a3e2a-e35c-4d17-8e61-b9f7c8286747): START TRANSACTION;
Executing (3f4a3e2a-e35c-4d17-8e61-b9f7c8286747): SELECT `id`, `ori_word`, `cut_word`, `createdAt`, `updatedAt` FROM `Words` AS `Word` WHERE `Word`.`ori_word` = '带上飞机啊甲方的我们是阿德啊阿飞阿斯蒂芬' LIMIT 1;
Executing (3f4a3e2a-e35c-4d17-8e61-b9f7c8286747): COMMIT;
Unhandled rejection SequelizeBaseError: null
    at Promise.all.then (/mnt/h/flk/vue_chat_backend/node_modules/sequelize/lib/instance-validator.js:77:15)
    at tryCatcher (/mnt/h/flk/vue_chat_backend/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/mnt/h/flk/vue_chat_backend/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/mnt/h/flk/vue_chat_backend/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/mnt/h/flk/vue_chat_backend/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/mnt/h/flk/vue_chat_backend/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/mnt/h/flk/vue_chat_backend/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/mnt/h/flk/vue_chat_backend/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/mnt/h/flk/vue_chat_backend/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/mnt/h/flk/vue_chat_backend/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/mnt/h/flk/vue_chat_backend/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/mnt/h/flk/vue_chat_backend/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/mnt/h/flk/vue_chat_backend/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/mnt/h/flk/vue_chat_backend/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/mnt/h/flk/vue_chat_backend/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
```

__Dialect: mysql 
__Database version: 5.7.18
__Sequelize version: 4.0.0

**Comment by everthis** [comment]
[#395 (comment)](https://github.com/sequelize/sequelize/issues/395#issuecomment-29132224)

**Comment by didibao7** [comment]
I also want some solutions
