### ISSUE TITLE
SequelizeDatabaseError: SQLITE_ERROR: no such column: NaN

### ISSUE THREAD

**Issue by thom-nic** [sequelize/sequelize#7791]
I'm inserting a model and in this case I think not providing a value for one of the attributes caused `NaN` to be used as the value.   So here sqlite is interpreting `NaN` as a column name.

```
Wed, 14 Jun 2017 13:26:03 GMT app:db Executing (default): INSERT INTO `fault_records` (`timestamp`,`type`,`faultCode`) VALUES ('2017-06-14 13:25:59.000 +00:00',2,NaN);
Wed, 14 Jun 2017 13:26:03 GMT app:worker:faultrecord Error: SequelizeDatabaseError: SQLITE_ERROR: no such column: NaN
Wed, 14 Jun 2017 13:26:03 GMT app:workers:Supervisor FaultRecordWorker.run() error { SequelizeDatabaseError: SQLITE_ERROR: no such column: NaN
     at Query.formatError (/opt/etx8-web/node_modules/sequelize/lib/dialects/sqlite/query.js:348:14)
     at afterExecute (/opt/etx8-web/node_modules/sequelize/lib/dialects/sqlite/query.js:112:29)
     at Statement.errBack (/opt/etx8-web/node_modules/sqlite3/lib/sqlite3.js:16:21)
   name: 'SequelizeDatabaseError',
   message: 'SQLITE_ERROR: no such column: NaN',
   parent:
    { Error: SQLITE_ERROR: no such column: NaN
        at Error (native)
      errno: 1,
      code: 'SQLITE_ERROR',
      sql: 'INSERT INTO `fault_records` (`timestamp`,`type`,`faultCode`) VALUES (\'2017-06-14 13:25:59.000 +00:00\',2,NaN);' },
   original:
    { Error: SQLITE_ERROR: no such column: NaN
        at Error (native)
      errno: 1,
      code: 'SQLITE_ERROR',
      sql: 'INSERT INTO `fault_records` (`timestamp`,`type`,`faultCode`) VALUES (\'2017-06-14 13:25:59.000 +00:00\',2,NaN);' },
   sql: 'INSERT INTO `fault_records` (`timestamp`,`type`,`faultCode`) VALUES (\'2017-06-14 13:25:59.000 +00:00\',2,NaN);' }
```

And then I have code that was doing this:
```
FaultRecord.create({
      type: FaultTypes.foo,
      faultCode,
    });  // note the missing componentID, see model below
```

My model:
```javascript
const attributes = {
  timestamp: {
    type: Sequelize.DATE,
    allowNull: false,
    defaultValue: Sequelize.NOW,
  },
  componentId: {  // note this is not an actual FK despite the use of '--ID'
    type: Sequelize.INTEGER,
    allowNull: true,
    validate: {min: 0},
  },
  type: {
    type: Sequelize.ENUM(FaultTypeValues),
    allowNull: false,
    validate: {isIn: [FaultTypeValues]},
  },
  faultCode: {
    type: Sequelize.INTEGER,
    allowNull: false,
    validate: {min: 0},
    defaultValue: 0,
  },
};

const FaultRecord = db.define('fault_record', attributes, {timestamps: false});
```

I came across [this SO post](https://stackoverflow.com/questions/15569745/store-nan-values-in-sqlite-database) - not sure about other DBs but for the sqlite dialect it would seem `'NaN'` as a string would be appropriate behavior, esp since `Number('NaN')` will get you back the correct value on readout from sqlite -> JS.

This is easy enough for us to work around but was surprising enough that I thought it was worth reporting.  Thanks!

**Comment by dhawkinson** [comment]
I just discovered the problem today. Error message:
