### ISSUE TITLE
Error performing raw query using Sequelize 4.1.0 based on example

### ISSUE THREAD

**Issue by nstuyvesant** [sequelize/sequelize#7794]
## What you are doing?
Trying out the sample provided on [the documentation page](http://docs.sequelizejs.com/manual/tutorial/raw-queries.html)
Created a table called users with columns: id, name and added a record with name = 'ben'

```
sequelize.query('SELECT * FROM users WHERE name LIKE :search_name ',
  { replacements: { search_name: 'ben%'  }, type: sequelize.QueryTypes.SELECT }
).
  then(users => console.log(users));
```

## What do you expect to happen?
Expected an array of users with one element.

## What is actually happening?
Got an error.

_Output, either JSON or SQL_
```
TypeError: _sequelize2.default.query is not a function
    at index (/Users/nates/dev/shy/server/api/user/user.controller.js:106:13)
    at Layer.handle [as handle_request] (/Users/nates/dev/shy/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/nates/dev/shy/node_modules/express/lib/router/route.js:137:13)
    at next (/Users/nates/dev/shy/node_modules/composable-middleware/lib/composable-middleware.js:40:9)
    at Middleware_Common_Object.meetsRequirements (/Users/nates/dev/shy/server/auth/auth.service.js:61:16)
    at next (/Users/nates/dev/shy/node_modules/composable-middleware/lib/composable-middleware.js:59:18)
    at next (/Users/nates/dev/shy/node_modules/composable-middleware/lib/composable-middleware.js:40:9)
    at _sqldb.User.find.then.user (/Users/nates/dev/shy/server/auth/auth.service.js:42:11)
    at tryCatcher (/Users/nates/dev/shy/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/nates/dev/shy/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/nates/dev/shy/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/nates/dev/shy/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/nates/dev/shy/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/nates/dev/shy/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/nates/dev/shy/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/nates/dev/shy/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

__Dialect:__ postgres
__Database version:__ 9.6.3
__Sequelize version:__ 4.1.0

**Comment by nstuyvesant** [comment]
Sorry - figured it out.

**Comment by panda6412** [comment]
@nstuyvesant how do you fix it, I still stuck inside

**Comment by nstuyvesant** [comment]
Sorry, been a long time since this occurred. I don't recall the fix but I have since dropped using sequelize (for performance reasons). Now, I just use pg-native.
