### ISSUE TITLE
'id' attribute is always selected when performing model.findAll, whether it exists or not

### ISSUE THREAD

**Issue by HowWeRollingham** [sequelize/sequelize#7800]
## What you are doing?
_Post a minimal code sample that reproduces the issue, including models and associations_

```js
model.findAll({
        where: {
            StaffRoleId: roleId,
            ObjectId: { $in: [1, 2, 3] }
        },
        raw: true
    });

//"model" model:
sequelize.define('model', {
        ObjectId: {
            type: DataTypes.INTEGER,
            defaultValue: -1
        }
    }, {
        classMethods: {
            associate: function() {
                // associations can be defined here
            }
        }
    });
```
"model" Table:
```
   Column    |           Type           |           Modifiers
-------------+--------------------------+--------------------------------
 ObjectId    | integer                  | not null default '-1'::integer
 createdAt   | timestamp with time zone | not null
 updatedAt   | timestamp with time zone | not null
 StaffId     | integer                  | not null
 StaffRoleId | integer                  | not null
```

## What do you expect to happen?
Successful query generated, i.e.
```sql
SELECT "ObjectId", "createdAt", "updatedAt", "StaffId", "StaffRoleId" FROM "model" AS "SRL" WHERE "StaffRoleLink"."StaffRoleId" = 10 AND "StaffRoleLink"."ObjectId" IN (1, 2, 3);
```

## What is actually happening?
Failing query generated (as "id" column does not exist), i.e.
```sql
SELECT "id", "ObjectId", "createdAt", "updatedAt" FROM "model" AS "SRL" WHERE "StaffRoleLink"."StaffRoleId" = 10 AND "StaffRoleLink"."ObjectId" IN (1, 2, 3);
```

_Output, either JSON or SQL_

```
SequelizeBaseError: column "id" does not exist
    at Query.formatError (.../node_modules/sequelize/lib/dialects/postgres/query.js:350:16)
    at Query.query.on.err (.../node_modules/sequelize/lib/dialects/postgres/query.js:93:21)
    at emitOne (events.js:96:13)
    at Query.emit (events.js:191:7)
    at Query.handleError (.../node_modules/pg/lib/query.js:143:8)
    at Client.<anonymous> (.../node_modules/pg/lib/client.js:186:26)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:191:7)
    at TLSSocket.<anonymous> (.../pg/lib/connection.js:133:12)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at TLSSocket.Readable.push (_stream_readable.js:136:10)
    at TLSWrap.onread (net.js:560:20)
```

__Dialect:__ postgres
__Database version:__ 9.5.3
__Sequelize version:__ 4.1.0

**Comment by janmeier** [comment]
If `ObjectId` is the primary key, mark it as such with `primaryKey: true`

Sequelize expects a table to always have a primary key

**Comment by HowWeRollingham** [comment]
Thank you - actually the table (effectively) has a compound primary key in (ObjectId, StaffId, StaffRoleId).

However this might work for me as a workaround - will update after trying it.

**Comment by felixfbecker** [comment]
Sequelize does not support compound primary keys for models

**Comment by maitraiya** [comment]
> If `ObjectId` is the primary key, mark it as such with `primaryKey: true`
> 
> Sequelize expects a table to always have a primary key

It Works!

**Comment by VijayakumarBalakrishnan** [comment]
const express =require("express");
const router=express.Router();

const db=require("../config/database");
const Gig=require("../models/Gig");
router.get('/', (req, res)=>
Gig.findAll()
.then(gigs=>{
	console.log(gigs)
	res.sendStatus(200);
})
.catch(err=>console.log(err)))

module.exports=router;

this is my code 
but i am getting this error how to solve
server started on port 5001
Executing (default): SELECT 1+1 AS result
Database connected
Executing (default): SELECT "Id", "code", "description", "createdAt", "updatedAt" FROM "mealplans" AS "mealplans";
{ SequelizeDatabaseError: column "Id" does not exist
    at Query.formatError (/home/algolitics/Desktop/MyLearning/RateMetricsNew/node_modules/sequelize/lib/dialects/postgres/query.js:366:16)
    at query.catch.err (/home/algolitics/Desktop/MyLearning/RateMetricsNew/node_modules/sequelize/lib/dialects/postgres/query.js:72:18)
    at tryCatcher (/home/algolitics/Desktop/MyLearning/RateMetricsNew/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/algolitics/Desktop/MyLearning/RateMetricsNew/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/algolitics/Desktop/MyLearning/RateMetricsNew/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/algolitics/Desktop/MyLearning/RateMetricsNew/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/algolitics/Desktop/MyLearning/RateMetricsNew/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/algolitics/Desktop/MyLearning/RateMetricsNew/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/algolitics/Desktop/MyLearning/RateMetricsNew/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/algolitics/Desktop/MyLearning/RateMetricsNew/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues (/home/algolitics/Desktop/MyLearning/RateMetricsNew/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
  name: 'SequelizeDatabaseError',
  parent: 
   { error: column "Id" does not exist
    at Connection.parseE (/home/algolitics/Desktop/MyLearning/RateMetricsNew/node_modules/pg/lib/connection.js:604:13)
    at Connection.parseMessage (/home/algolitics/Desktop/MyLearning/RateMetricsNew/node_modules/pg/lib/connection.js:403:19)
    at Socket.<anonymous> (/home/algolitics/Desktop/MyLearning/RateMetricsNew/node_modules/pg/lib/connection.js:123:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)
     name: 'error',
     length: 101,
     severity: 'ERROR',
     code: '42703',
     detail: undefined,
     hint: undefined,
     position: '8',
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'parse_relation.c',
     line: '3293',
     routine: 'errorMissingColumn',
     sql: 'SELECT "Id", "code", "description", "createdAt", "updatedAt" FROM "mealplans" AS "mealplans";',
     parameters: undefined },
  original: 
   { error: column "Id" does not exist
    at Connection.parseE (/home/algolitics/Desktop/MyLearning/RateMetricsNew/node_modules/pg/lib/connection.js:604:13)
    at Connection.parseMessage (/home/algolitics/Desktop/MyLearning/RateMetricsNew/node_modules/pg/lib/connection.js:403:19)
    at Socket.<anonymous> (/home/algolitics/Desktop/MyLearning/RateMetricsNew/node_modules/pg/lib/connection.js:123:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)
     name: 'error',
     length: 101,
     severity: 'ERROR',
     code: '42703',
     detail: undefined,
     hint: undefined,
     position: '8',
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'parse_relation.c',
     line: '3293',
     routine: 'errorMissingColumn',
     sql: 'SELECT "Id", "code", "description", "createdAt", "updatedAt" FROM "mealplans" AS "mealplans";',
     parameters: undefined },
  sql: 'SELECT "Id", "code", "description", "createdAt", "updatedAt" FROM "mealplans" AS "mealplans";',
  parameters: undefined }
