### ISSUE TITLE
Postgres sync({force: true}) ignores enum field name, tries to edit non-existent enum

### ISSUE THREAD

**Issue by ox** [sequelize/sequelize#7812]
## What you are doing?

```js
const Sequelize = require('sequelize');

const {ENUM} = Sequelize;
const {POSTGRES_HOST, POSTGRES_PORT, POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB} = process.env;
const sequelize = new Sequelize(POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD, {
  host: POSTGRES_HOST,
  port: POSTGRES_PORT,
  dialect: 'postgres',
  pool: {
    max: 1,
    min: 1,
  },
});

sequelize.define('Media', {
  vrFormat: {
    type: ENUM('equirectangular', 'cube map'),
    field: 'vr_format',
  },
}, {
  timestamps: true,
  underscored: true,
  paranoid: true, // deletedAt columns
  freezeTableName: true, // do not pluralize
  tableName: 'media',
});

sequelize.sync({force: true, match: /_dev$/})
  .then(() => sequelize.sync({force: true, match: /_dev$/}))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
```

## What do you expect to happen?
I want the script to run repeatedly without fail

## What is actually happening?
Sequelize tries to add the enum values to a mis-named type `"enum_media_vrFormat"`, though the correctly named enum exists.

console output:
```
root@a0e83f661204:/srv$ node test/test.js 
Executing (default): DROP TABLE IF EXISTS "media" CASCADE;
Executing (default): DROP TYPE IF EXISTS "public"."enum_media_vrFormat";
Executing (default): DROP TABLE IF EXISTS "media" CASCADE;
Executing (default): DROP TYPE IF EXISTS "public"."enum_media_vrFormat";
Executing (default): SELECT t.typname enum_name, array_agg(e.enumlabel ORDER BY enumsortorder) enum_value FROM pg_type t JOIN pg_enum e ON t.oid = e.enumtypid JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname='enum_media_vr_format' GROUP BY 1
Executing (default): DROP TYPE IF EXISTS "public"."enum_media_vr_format"; CREATE TYPE "public"."enum_media_vr_format" AS ENUM('equirectangular', 'cube map');
Executing (default): CREATE TABLE IF NOT EXISTS "media" ("id"   SERIAL , "vr_format" "public"."enum_media_vr_format", "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, "deleted_at" TIMESTAMP WITH TIME ZONE, PRIMARY KEY ("id"));
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'media' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
Executing (default): DROP TABLE IF EXISTS "media" CASCADE;
Executing (default): DROP TYPE IF EXISTS "public"."enum_media_vrFormat";
Executing (default): DROP TABLE IF EXISTS "media" CASCADE;
Executing (default): DROP TYPE IF EXISTS "public"."enum_media_vrFormat";
Executing (default): SELECT t.typname enum_name, array_agg(e.enumlabel ORDER BY enumsortorder) enum_value FROM pg_type t JOIN pg_enum e ON t.oid = e.enumtypid JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace WHERE n.nspname = 'public' AND t.typname='enum_media_vr_format' GROUP BY 1
Executing (default): ALTER TYPE "public"."enum_media_vrFormat" ADD VALUE IF NOT EXISTS 'cube map' AFTER 'equirectangular'
{ SequelizeDatabaseError: type "public.enum_media_vrFormat" does not exist
    at Query.formatError (/srv/node_modules/sequelize/lib/dialects/postgres/query.js:350:16)
    at Query.query.on.err (/srv/node_modules/sequelize/lib/dialects/postgres/query.js:93:21)
    at emitOne (events.js:96:13)
    at Query.emit (events.js:188:7)
    at Query.handleError (/srv/node_modules/pg/lib/query.js:143:8)
    at Client.<anonymous> (/srv/node_modules/pg/lib/client.js:186:26)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at Socket.<anonymous> (/srv/node_modules/pg/lib/connection.js:133:12)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
  name: 'SequelizeDatabaseError',
  parent: 
   { error: type "public.enum_media_vrFormat" does not exist
       at Connection.parseE (/srv/node_modules/pg/lib/connection.js:567:11)
       at Connection.parseMessage (/srv/node_modules/pg/lib/connection.js:391:17)
       at Socket.<anonymous> (/srv/node_modules/pg/lib/connection.js:129:22)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:188:7)
       at readableAddChunk (_stream_readable.js:176:18)
       at Socket.Readable.push (_stream_readable.js:134:10)
       at TCP.onread (net.js:548:20)
     name: 'error',
     length: 109,
     severity: 'ERROR',
     code: '42704',
     detail: undefined,
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'parse_type.c',
     line: '257',
     routine: 'typenameType',
     sql: 'ALTER TYPE "public"."enum_media_vrFormat" ADD VALUE IF NOT EXISTS \'cube map\' AFTER \'equirectangular\'' },
  original: 
   { error: type "public.enum_media_vrFormat" does not exist
       at Connection.parseE (/srv/node_modules/pg/lib/connection.js:567:11)
       at Connection.parseMessage (/srv/node_modules/pg/lib/connection.js:391:17)
       at Socket.<anonymous> (/srv/node_modules/pg/lib/connection.js:129:22)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:188:7)
       at readableAddChunk (_stream_readable.js:176:18)
       at Socket.Readable.push (_stream_readable.js:134:10)
       at TCP.onread (net.js:548:20)
     name: 'error',
     length: 109,
     severity: 'ERROR',
     code: '42704',
     detail: undefined,
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'parse_type.c',
     line: '257',
     routine: 'typenameType',
     sql: 'ALTER TYPE "public"."enum_media_vrFormat" ADD VALUE IF NOT EXISTS \'cube map\' AFTER \'equirectangular\'' },
  sql: 'ALTER TYPE "public"."enum_media_vrFormat" ADD VALUE IF NOT EXISTS \'cube map\' AFTER \'equirectangular\'' }
```

inspecting the DB, there is no "media" table, but there is an `"enum_media_vr_format"` type:

```
psql (9.6.3, server 9.6.2)
Type "help" for help.

svrf_dev=# \d 
No relations found.
svrf_dev=# \dT+
                                                     List of data types
 Schema |         Name         |    Internal name     | Size |    Elements     |  Owner   | Access privileges | Description 
--------+----------------------+----------------------+------+-----------------+----------+-------------------+-------------
 public | enum_media_vr_format | enum_media_vr_format | 4    | equirectangular+| postgres |                   | 
        |                      |                      |      | cube map        |          |                   | 
(1 row)
```

I think this could be related to #7799; a missed call to convert the field to the right name in the query builder.

__Dialect:__ postgre
__Database version:__ 9.6.3
__Sequelize version:__ 4.1.0

__note__: this also breaks for sequelize@3.30.4

**Comment by ox** [comment]
An interesting development: in the original model, which includes many enums with custom `fields`, changing this attribute to type TEXT results in no errors. I am very, very confused.

**Comment by ctpstudy** [comment]
I have the same problem

**Comment by max0d41** [comment]
In newer sequelize versions the ENUM data type ignored the `underscore = false` options.
When migrating an existing database, the enum key `public.enum_foobar_type` exists, but not `public.enum_foobarType`

I'm addressing the same bug.
