### ISSUE TITLE
setMaxListener() error on raw queries

### ISSUE THREAD

**Issue by erayalakese** [sequelize/sequelize#7817]
While executing a raw query like this:

```js
var db = new Sequelize('dbname', 'user', 'pass', {host: 'localhost'});
db.query("SELECT ...", { type: 'SELECT'}
      ).then(function(result) {...})
      .catch(function(err) {...});
```

It's executing the query but also I'm getting this error:

```bash
Unhandled rejection TypeError: Cannot read property 'setMaxListeners' of undefined
    at PROJECTDIR/node_modules/sequelize/lib/dialects/mysql/query.js:54:7
    at Promise._execute (PROJECTDIR/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (PROJECTDIR/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (PROJECTDIR/node_modules/bluebird/js/release/promise.js:79:10)
    at Query.run (PROJECTDIR/node_modules/sequelize/lib/dialects/mysql/query.js:39:17)
    at PROJECTDIR/node_modules/sequelize/lib/sequelize.js:849:20
    at PROJECTDIR/node_modules/retry-as-promised/index.js:40:21
    at Promise._execute (PROJECTDIR/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (PROJECTDIR/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (PROJECTDIR/node_modules/bluebird/js/release/promise.js:79:10)
    at retryAsPromised (PROJECTDIR/node_modules/retry-as-promised/index.js:30:10)
    at PROJECTDIR/node_modules/sequelize/lib/sequelize.js:848:12
    at tryCatcher (PROJECTDIR/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (PROJECTDIR/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (PROJECTDIR/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (PROJECTDIR/node_modules/bluebird/js/release/promise.js:606:10)
```

This is `query.js`'s problematic part:

```js
var promise = new Utils.Promise(function(resolve, reject) {
    self.connection.query(self.sql, function(err, results) {

      if (benchmark) {
        self.sequelize.log('Executed (' + (self.connection.uuid || 'default') + '): ' + self.sql, (Date.now() - queryBegin), self.options);
      }

      if (err) {
        err.sql = sql;

        reject(self.formatError(err));
      } else {
        resolve(self.formatResults(results));
      }
    }).setMaxListeners(100);
  });
```
`self.connection.query()` is `undefined` because of that `self.connection.query.setMaxListener()` firing an error. If I modify this block like this, it's working:

```js
var promise = new Utils.Promise(function(resolve, reject) {
    self.connection.query(self.sql, function(err, results) {

      if (benchmark) {
        self.sequelize.log('Executed (' + (self.connection.uuid || 'default') + '): ' + self.sql, (Date.now() - queryBegin), self.options);
      }

      if (err) {
        err.sql = sql;

        reject(self.formatError(err));
      } else {
        resolve(self.formatResults(results));
      }
    }); //<---- setMaxListener() removed
  });
```

It's not possible to track this error, there is no helpful error message. 

__Dialect:__ mysql
__Database version:__ mysql  Ver 14.14 Distrib 5.7.18, for Linux (x86_64) using  EditLine wrapper
__Sequelize version:__ 3.30.2

**Comment by felixfbecker** [comment]
What dialect version are you using? Raw queries are covered by tests

**Comment by erayalakese** [comment]
@felixfbecker "mysql": "^2.13.0"

I've updated `sequelize` package to v4 and start using `mysql2` package. My problem solved. Probably there was a kind of conflict with other packages. After upgrading problem solved. But if you still maintain v3 I can provide more information.

Thank you for the answer.
