### ISSUE TITLE
Support for pg 7.0

### ISSUE THREAD

**Issue by luandapipi** [sequelize/sequelize#7818]
When I use pg ,I got an error (node:23704) DeprecationWarning: Using the automatically created return value from client.query as an event emitter is deprecated and will be removed in pg@7.0. Please see the upgrade guide at https://node-postgres.com/guides/upgrading.

**Comment by nstuyvesant** [comment]
I am using sequelize@4.2.0, pg@6.3.1, pg-native@1.10.1, node 8.1.2, and am getting the same deprecation warning. Here's the stack trace:
```
DeprecationWarning: Using the automatically created return value from client.query as an event emitter is deprecated and will be removed in pg@7.0. Please see the upgrade guide at https://node-postgres.com/guides/upgrading
    at Promise (/Users/nates/dev/shy/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:155:12)
    at Promise._execute (/Users/nates/dev/shy/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/nates/dev/shy/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/nates/dev/shy/node_modules/bluebird/js/release/promise.js:79:10)
    at Promise.tap.connection (/Users/nates/dev/shy/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:153:14)
    at PassThroughHandlerContext.finallyHandler (/Users/nates/dev/shy/node_modules/bluebird/js/release/finally.js:57:23)
    at PassThroughHandlerContext.tryCatcher (/Users/nates/dev/shy/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/nates/dev/shy/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/nates/dev/shy/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/nates/dev/shy/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/nates/dev/shy/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/nates/dev/shy/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/nates/dev/shy/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/nates/dev/shy/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
```

Seems to be [this query](https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/connection-manager.js#L155).

Here's [the article](https://node-postgres.com/guides/upgrading) on how to prepare for pg@7.0.

**Comment by donut** [comment]
I received this as well with sequelize@4.1.0, pg@6.3.0, and node 8.1.2.

> (node:69139) DeprecationWarning: Using the automatically created return value from client.query as an event emitter is deprecated. Please see the upgrade guide at https://node-postgres.com/guides/upgrading
Executing (default): `CREATE TABLE IF NOT EXISTS "channels" ("id" VARCHAR(255) NOT NULL , "name" VARCHAR(255) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'channels' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;`

**Comment by delveintechnolabs** [comment]
I also seem to face the same issue. Please provide a quick fix

**Comment by caioflores** [comment]
Same issue here with sequelize@3.24.3 and pg@6.4.0

**Comment by lironess** [comment]
same with sequelize@4.0.2 and pg@6.4.0

**Comment by Kumagor0** [comment]
same with sequelize@4.2.0 and pg@6.4.0

**Comment by felixfbecker** [comment]
It is just a deprecation warning. Sequelize does not yet support pg 7, PRs welcome.

**Comment by ikrum** [comment]
Looking forward to have **Support for pg 7.0** in prod

**Comment by xcambar** [comment]
Thanks for working on this @felixfbecker and @alitaheri (#7888), even though there's no rush as pg@7.0 is not ready yet (see https://github.com/brianc/node-postgres/milestone/3).
