### ISSUE TITLE
findAll(): Promise created in handler but not returned from it

### ISSUE THREAD

**Issue by nstuyvesant** [sequelize/sequelize#7828]
## What you are doing?
Calling findAll()

```js
export function index(req, res) {
  let flat = req.query.flat;
  return Announcement.findAll({
    attributes: ['_id', 'section', 'title', 'description', 'expires'],
    order: ['section', 'expires'],
    where: { expires: { $gt: new Date() } }
  })
    .then(function(announcements) {
      return flat ? res.status(200).json(announcements) : res.status(200).json(nest(announcements));
    })
    .catch(handleError(res));
}
```

## What do you expect to happen?
Returns array of announcements with no error warning

## What is actually happening?
Works fine but gives a warning that a Promise created in handler but not returned from it

The **return Announcement.findAll()** line above is announcement.controller.js:19:23 in the trace below...
```
(node:10257) Warning: a promise was created in a handler at /Users/nates/dev/shy/node_modules/express/lib/router/index.js:317:13 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.attempt.Promise.try (/Users/nates/dev/shy/node_modules/bluebird/js/release/method.js:29:9)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Function.findAll (/Users/nates/dev/shy/node_modules/sequelize/lib/model.js:1508:23)
    at index (/Users/nates/dev/shy/server/api/announcement/announcement.controller.js:19:23)
    at Layer.handle [as handle_request] (/Users/nates/dev/shy/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/nates/dev/shy/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/nates/dev/shy/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/nates/dev/shy/node_modules/express/lib/router/layer.js:95:5)
    at /Users/nates/dev/shy/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/Users/nates/dev/shy/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:317:13)
    at /Users/nates/dev/shy/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle [as handle_request] (/Users/nates/dev/shy/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:317:13)
    at /Users/nates/dev/shy/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:275:10)
    at checkCsrf (/Users/nates/dev/shy/node_modules/lusca/lib/csrf.js:74:20)
    at /Users/nates/dev/shy/node_modules/lusca/index.js:48:21
    at hsts (/Users/nates/dev/shy/node_modules/lusca/lib/hsts.js:25:9)
    at /Users/nates/dev/shy/node_modules/lusca/index.js:48:21
    at xframe (/Users/nates/dev/shy/node_modules/lusca/lib/xframes.js:12:9)
    at /Users/nates/dev/shy/node_modules/lusca/index.js:48:21
    at xssProtection (/Users/nates/dev/shy/node_modules/lusca/lib/xssprotection.js:16:9)
    at /Users/nates/dev/shy/node_modules/lusca/index.js:48:21
    at lusca (/Users/nates/dev/shy/node_modules/lusca/index.js:53:9)
From previous event:
    at E4Store.get (/Users/nates/dev/shy/node_modules/express-sequelize-session/lib/e4store.js:56:12)
    at session (/Users/nates/dev/shy/node_modules/express-session/index.js:460:11)
    at Layer.handle [as handle_request] (/Users/nates/dev/shy/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:317:13)
    at /Users/nates/dev/shy/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:275:10)
    at initialize (/Users/nates/dev/shy/node_modules/passport/lib/middleware/initialize.js:53:5)
    at Layer.handle [as handle_request] (/Users/nates/dev/shy/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:317:13)
    at /Users/nates/dev/shy/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:275:10)
    at cookieParser (/Users/nates/dev/shy/node_modules/cookie-parser/index.js:70:5)
    at Layer.handle [as handle_request] (/Users/nates/dev/shy/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:317:13)
    at /Users/nates/dev/shy/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:275:10)
    at methodOverride (/Users/nates/dev/shy/node_modules/method-override/index.js:65:14)
    at Layer.handle [as handle_request] (/Users/nates/dev/shy/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:317:13)
    at /Users/nates/dev/shy/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/Users/nates/dev/shy/node_modules/body-parser/lib/types/json.js:103:7)
    at Layer.handle [as handle_request] (/Users/nates/dev/shy/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:317:13)
    at /Users/nates/dev/shy/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/nates/dev/shy/node_modules/express/lib/router/index.js:275:10)
```

Looking at [findAll()'s return Promise.try()](https://github.com/sequelize/sequelize/blob/master/lib/model.js#L1508), it seems like there are paths that could end up not returning a value or a null (such as !options.hooks).

Am I off-base on that?

__Dialect:__ postgres
__Database version:__ 9.6.3
__Sequelize version:__ 4.2.0

**Comment by janmeier** [comment]
Could you point to the specific line? (press y to get a permalink to the current SHA) - I don't see it

**Comment by nstuyvesant** [comment]
BTW... Node.js 8.3.0, express-session 1.15.5, express 4.15.4, express-sequelize-session 0.4.0, generator-angular-fullstack 4.2.2.

My full project is at [https://github.com/nstuyvesant/shy](https://github.com/nstuyvesant/shy). When the project is started using gulp serve, the warning seems to be related to express-sequelize-session (which uses a promise) calling express-session.

E4Store.get (/Users/nates/dev/shy/node_modules/express-sequelize-session/lib/e4store.js:56:12) is the .then() line below...
```
      E4Store.prototype.get = function(sid, callback) {
        return this.Session.findOne({
          where: {
            sid: sid
          },
          attributes: ['data']
        }).then(function(session) {
          if (session != null) {
            return typeof callback === "function" ? callback(null, JSON.parse(session.data)) : void 0;
          } else {
            return typeof callback === "function" ? callback(null, null) : void 0;
          }
        })["catch"](function(err) {
          return typeof callback === "function" ? callback(err, null) : void 0;
        });
      };
```
The two paths within then() do a return but make a callback (more on this below).

Here's session (/Users/nates/dev/shy/node_modules/express-session/index.js:460:11)
```
    store.get(req.sessionID, function(err, sess){
      // error handling
      if (err) {
        debug('error %j', err);

        if (err.code !== 'ENOENT') {
          next(err);
          return;
        }

        generate();
      // no session
      } else if (!sess) {
        debug('no session found');
        generate();
      // populate req.session
      } else {
        debug('session found');
        store.createSession(req, sess);
        originalId = req.sessionID;
        originalHash = hash(sess);

        if (!resaveSession) {
          savedHash = originalHash
        }

        wrapmethods(req.session);
      }

      next(); // suppresses warning if changed to next(); return null;
    });
```

One awkward case when dealing with Express 4 is within a route context, as you want to start your chain with Promise.try() but at the same time you can't return this promise chain from the route (as it's a callback). This is usually the situation where we see this warning using express and what I suspect may be happening here in express-sequelize-session calling express-session.

Adding` return null;` below the `next();` in express-session suppresses the warning.

So it seems like the issue is really within express-sequelize-session but let me know what your thoughts are as well.

**Comment by nstuyvesant** [comment]
The problem was with express-sequelize-session. As it's no longer maintained, I switched to connect-session-sequelize (minor changes needed). This eliminated the warnings.
