### ISSUE TITLE
Unique not Working

### ISSUE THREAD

**Issue by edlobox** [sequelize/sequelize#7829]
## What you are doing?
_I need a Unique values  for strings like colors for example._

```
  text: {
    type: db.Sequelize.STRING,
    allowNull: false,
    unique: true,
}
```
## What do you expect to happen?
_I wanted unique value and not duplicated_

## What is actually happening?
_Can create the same value over and over..._

_Output: JSON_
__Dialect:__ postgres
__Database version:__ 9.6.0
__Sequelize version:__ 4.2.0

**Comment by janmeier** [comment]
```js
const User = sequelize.define('user', {
  text: {
    type: db.Sequelize.STRING,
    allowNull: false,
    unique: true,
  }
});

return sequelize.sync({
  force: true,
  logging: console.log
})
  .then(() => {
    return User.create({ text: 'foo '});
  })
  .then((user) => {
    return User.create({ text: 'foo '});
  })
  .then(console.log)
  .finally(() => sequelize.close());
```

```
Unhandled rejection SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/home/jan/src/sequelize/lib/dialects/postgres/query.js:325:18)
    at Query.query.on.err (/home/jan/src/sequelize/lib/dialects/postgres/query.js:93:21)
    at emitOne (events.js:96:13)
    at Query.emit (events.js:188:7)
    at Query.handleError (/home/jan/src/sequelize/node_modules/pg/lib/query.js:143:8)
    at Connection.<anonymous> (/home/jan/src/sequelize/node_modules/pg/lib/client.js:180:26)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at Socket.<anonymous> (/home/jan/src/sequelize/node_modules/pg/lib/connection.js:136:12)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
```

Are you calling `sync` - This will only work if you let sequelize create the table, since it depends on a unique constaint
