### ISSUE TITLE
Unhandled rejection SequelizeBaseError: type "hstore" does not exist

### ISSUE THREAD

**Issue by zusamann** [sequelize/sequelize#7848]
According to the documentation here Sequelize supports HSTORE.
http://docs.sequelizejs.com/variable/index.html#static-variable-DataTypes

Here is my model:
```js
import uid from 'uid-safe';

export default (sequelize, DataTypes) => {
  const Model = sequelize.define(
    'job',
    {
      id: {
        type: DataTypes.STRING,
        defaultValue: () => `job_${uid.sync(6)}`,
        primaryKey: true
      },
      tags: {
        type: DataTypes.HSTORE
      },
      _meta: {
        type: DataTypes.STRING
      }
    }
  );
  return Model;
};
```
Getting this error upon usage:
```
Unhandled rejection SequelizeBaseError: type "hstore" does not exist
    at Query.formatError (...\node_modules\sequelize\lib\dialects\postgres\query.js:357:14)
    at Query.<anonymous> (...\node_modules\sequelize\lib\dialects\postgres\query.js:88:19)
    at emitOne (events.js:115:13)
    at Query.emit (events.js:210:7)
    at Query.handleError (...\node_modules\pg\lib\query.js:143:8)
    at Client.<anonymous> (...\node_modules\pg\lib\client.js:186:26)
    at emitOne (events.js:115:13)
    at Connection.emit (events.js:210:7)
    at Socket.<anonymous> (...\node_modules\pg\lib\connection.js:133:12)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:250:12)
    at readableAddChunk (_stream_readable.js:237:11)
    at Socket.Readable.push (_stream_readable.js:195:10)
    at TCP.onread (net.js:586:20)
```

What is the correct way to use HSTORE if not this? Every other data type in that list I've used works so far.

```js
{
    "pg": "^6.1.5",
    "pg-hstore": "^2.3.2",
    "sequelize": "^3.30.4",
}
```

**Comment by ox** [comment]
Did you install the `hstore` extension in the database?

```sql
CREATE EXTENSION hstore;
```

You can enable it for future databases by adding it to the `template1` database [like so](https://zaiste.net/posts/enable_postgresql_hstore_by_default/);

**Comment by zusamann** [comment]
thanks @ox it works now!
