### ISSUE TITLE
Unable to pass scope to association when include has separate: true

### ISSUE THREAD

**Issue by 604bpierce** [sequelize/sequelize#7859]
## What you are doing?
In a simplified explanation of what I'm attempting: ssociating one table "checkins" with the parent "tasks" table. I'm using a tasks.hasMany(checkins). When I attempt to call:
`{as: 'checkins', model: db.models.checkin.scope('public') ] ,separate: true}`

I get the following error:

> TypeError: Cannot read property 'push' of undefined
    at /node_modules/sequelize/lib/associations/has-many.js:344:64
    at Array.forEach (native)
    at Model.<anonymous> (/node_modules/sequelize/lib/associations/has-many.js:343:13)

However the following does work:
`{as: 'checkins', model: db.models.task_checkin, include:[{as: 'user', model: db.models.user.scope('public')}], separate: true}`

This lets me get around the bug, however it makes keeping these consistent across the application difficult.

#### Example Models

```js
module.exports = (sequelize, Sq) => {
  return sequelize.define('task', {
    id: {
      type: Sq.INTEGER,
      autoIncrement: true,
      primaryKey: true
    },
    name: {
      type: Sq.STRING,
      allowNull: false,
    },
    slug: {
      type: Sq.STRING,
      allowNull: false,
      validate: {
        is: {
          args: ["^[A-z0-9_-]+$", 'i'],
          msg: 'Only alphanumeric and underscores are allowed in the task slug'
        },
        len: {
          args: [3,50],
          msg: 'Task slug must be between 3 and 50 characters long'
        }
      }
    },
    description: {
      type: Sq.TEXT,
      allowNull: true
    },
    ordinal: {
      type: Sq.INTEGER,
      allowNull: false
    },
    status: {
      type: Sq.STRING,
      defaultValue: null,
      validate: {
        isIn: {
          args: [['pending', 'active', 'complete', 'hold', 'failed']],
          msg: 'The specified task status is not valid. Allowed values: pending, active, complete, pause, blocked'
        }
      }
    },
    checkInsTarget: {
      type: Sq.INTEGER,
      defaultValue: 1,
      allowNull: false
    },
    startedAt: {
      type: Sq.DATE
    },
    completedAt: {
      type: Sq.DATE
    }
  },
  {
    tableName: 'tasks',
    // Automatically create createdAt, updatedAt, deletedAt
    timestamps: true,
    // Use soft-deletes!
    paranoid: true,
    scopes: {
      pblc: {
        order:  [['ordinal', 'ASC']],
        attributes: {
          exclude: ['deletedAt', 'id',]
        }
      }
    }
  });
};


module.exports = (sequelize, Sq) => {
  return sequelize.define('task_checkin', {
      id: {
        type: Sq.INTEGER,
        autoIncrement: true,
        primaryKey: true
      },
      task_id: {
        type: Sq.INTEGER,
        references: {
          model: 'tasks',
          key: 'id',
        }
      },
      outcome: {
        type: Sq.TEXT,
        allowNull: true,
      },
      user_id: {
        type: Sq.INTEGER,
        references: {
          model: 'users',
          key: 'id',
        }
      }
    },
    {
      tableName: 'task_checkins',
      // Automatically create createdAt, updatedAt, deletedAt
      timestamps: true,
      // Use soft-deletes!
      paranoid: true,
      scopes: {
        pblc: {
          order:  [['createdAt', 'ASC']],
          attributes: {
            exclude: ['deletedAt', 'id', 'task_id', 'user_id']
          },
          include: [
            { as: 'user', model: sequelize.models.user.scope('public') }
          ]
        }
      }
    });
};

let tracking = {};

tracking.checkins = sequelize.import(__dirname + '/state_task_checkins');
tracking.task = sequelize.import(__dirname + '/state_task');
tracking.task.hasMany(tracking.checkins, {as: 'checkins', foreignKey: 'task_id', onDelete: 'CASCADE', constraints: true});
tracking.task.belongsTo(sequelize.models.user, {as: 'assignedTo', foreignKey: 'assignedTo_id', onDelete: 'SET NULL', constraints: true});



```

#### Example Call

```js

let opts = {};

opts.include = [
  {as: 'checkins', model: db.models.tracking_state_task_checkin.scope('pblc') ,separate: true}
];

sequelize.models.tracking_state_task.findOne(opts).then(
  (result) => {
    ...
  }
  (err) => {
    ...
  }
);
```

## What do you expect to happen?
I expect the the associated table to be called using the provided scope.

## What is actually happening?
Error thrown.

> TypeError: Cannot read property 'push' of undefined at  node_modules/sequelize/lib/associations/has-many.js:344:64
at Array.forEach (native)
at Model. (/node_modules/sequelize/lib/associations/has-many.js:343:13)

__Dialect:__  postgres
__Database version:__ 9.4.x & 9.6.x
__Sequelize version:__ 3.30.4

**Comment by 604bpierce** [comment]
I just noticed that if I attempt:

```js
{as: 'checkins', model: db.models.task_checkin, include:[{as: 'user', model: db.models.user.scope('public')}], attributes: {exclude: ['id', 'user_id', 'task_id', 'deletedAt']}, separate: true}
```

I get the same error:
> TypeError: Cannot read property 'push' of undefined at node_modules/sequelize/lib/associations/has-many.js:344:64
at Array.forEach (native)
at Model. (/node_modules/sequelize/lib/associations/has-many.js:343:13)

It would seem the issue may revolve around passing in attributes to the included association when `separate: true`.

**Comment by PatrickGeyer** [comment]
I'm trying to include models as separate. 
However when I fetch the parent model with a given scope, it tries to call the same scope on the child model as well, which doesn't exist so sequelize throws an error. Is there a way to include a child model but ALWAYS use defaultScope? Is this by design?

**Comment by TakanashiOuken** [comment]
> I'm trying to include models as separate.
> However when I fetch the parent model with a given scope, it tries to call the same scope on the child model as well, which doesn't exist so sequelize throws an error. Is there a way to include a child model but ALWAYS use defaultScope? Is this by design?

Having the same issue here. 
Seems like if we do something like 
`{ model: patent, include: [ model: child.scope(["defaultScope", "otherScope"]) ] }`
defaultScope will run twice on child model

**Comment by hgbao** [comment]
Running into this issue

**Comment by hgbao** [comment]
To be more specific, if we use
```js
include: {
  model: Foo.scope('bar'),
  separate: true,
  ...
}
```
The default scope of `Foo` won't be ignored. Default scope is always included even though we have our own scope `bar`

**Comment by tttaisgt** [comment]
I am facing similar problem. 😕
