### ISSUE TITLE
SequelizeHostNotFoundError on Cloud functions

### ISSUE THREAD

**Issue by perrosnk** [sequelize/sequelize#7868]
I am trying to run sequelize on google cloud functions and connect to a postgres db hosted on compose.com, but I am getting this error

```
SequelizeHostNotFoundError: getaddrinfo ENOTFOUND gcp-us-east1-cpu.2.dblayer.com gcp-us-east1-cpu.2.dblayer.com:16070
    at connection.connect.err (/user_code/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:95:24)
    at Client.<anonymous> (/user_code/node_modules/pg/lib/client.js:203:5)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at Socket.<anonymous> (/user_code/node_modules/pg/lib/connection.js:86:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at connectErrorNT (net.js:1020:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

```

__Dialect: postgres
__Database version: 9.6
__Sequelize version: 4.2.1

**Comment by felixfbecker** [comment]
The error is pretty self-explanatory, Sequelize is unable to connect to the given address.

**Comment by mavrick** [comment]
@perrosnk - did you solve this issue?

**Comment by perrosnk** [comment]
@mavrick In my case, I wasn't using the paid version of google cloud function, so I found out that I wasn't allowed to connect to an external db.

**Comment by mavrick** [comment]
@perrosnk - thanks for that. did you just switch over to the blaze 'pay-as-you-go' plan? Have you had any other issues with cloud functions? I'd love to start using them more.

**Comment by perrosnk** [comment]
yes I switched to blaze and it worked great!
No, I didn't have any other issues, but I needed some services to run all the time, for example websockets, or an online clock, so I moved most of the server services to https://zeit.co/. Have a look and see what fits you best!
