### ISSUE TITLE
call person.setPost error: Unhandled rejection Error: Invalid value

### ISSUE THREAD

**Issue by pangz1** [sequelize/sequelize#7869]
This is my code:

```js
'use strict'

require('dotenv').config({
    path: __dirname + '/.env'
})

const { DBNAME, DBUSER, DBPASS, DBHOST } = process.env

const Sequelize = require('sequelize')

const client = new Sequelize(DBNAME, DBUSER, DBPASS, {
    host: DBHOST,
    dialect: 'mysql',
    pool: {
        max: 30,
        min: 0,
        idle: 10000
    }
})

const Post = client.define('Post', {
    title: Sequelize.STRING,
    content: Sequelize.TEXT
})

const Person = client.define('Person', {
    name: Sequelize.STRING,
})

Post.belongsTo(Person)
Person.hasMany(Post)

Post.sync()
Person.sync()

Person.create({
    name: 'walle'
}).then(person => {

    person.setPosts({
        title: 'my first post',
        content: 'hello world'
    })
})
```

I wanted to create a user, and add a post for the user,
but I get this error:

Unhandled rejection Error: Invalid value [object Object]
    at Object.escape (/Users/pangzi/dc-main/diascubes.com/node_modules/sequelize/lib/sql-string.js:50:11)
    at Object.escape (/Users/pangzi/dc-main/diascubes.com/node_modules/sequelize/lib/dialects/abstract/query-generator.js:917:22)
    at value.(.map.item (/Users/pangzi/dc-main/diascubes.com/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2219:66)
    at Array.map (native)
    at Object.whereItemQuery (/Users/pangzi/dc-main/diascubes.com/node_modules/sequelize/lib/dialects/abstract/query-generator.js:221
9:49)
    at _.forOwn (/Users/pangzi/dc-main/diascubes.com/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1936:25)
    at /Users/pangzi/dc-main/diascubes.com/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/Users/pangzi/dc-main/diascubes.com/node_modules/lodash/lodash.js:3001:24)
    at Function.forOwn (/Users/pangzi/dc-main/diascubes.com/node_modules/lodash/lodash.js:13002:24)
    at Object.whereItemsQuery (/Users/pangzi/dc-main/diascubes.com/node_modules/sequelize/lib/dialects/abstract/query-generator.js:19
35:9)
    at Object.whereQuery (/Users/pangzi/dc-main/diascubes.com/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1907:24
)
    at Object.updateQuery (/Users/pangzi/dc-main/diascubes.com/node_modules/sequelize/lib/dialects/abstract/query-generator.js:365:19
)
    at QueryInterface.bulkUpdate (/Users/pangzi/dc-main/diascubes.com/node_modules/sequelize/lib/query-interface.js:610:37)
    at Promise.try.then.then.then.results (/Users/pangzi/dc-main/diascubes.com/node_modules/sequelize/lib/model.js:2752:34)
From previous event: 
at Function.update (/Users/pangzi/dc-main/diascubes.com/node_modules/sequelize/lib/model.js:2741:8)
    at association.get.then.oldAssociations (/Users/pangzi/dc-main/diascubes.com/node_modules/sequelize/lib/associations/has-many.js:
361:53)
From previous event:
    at HasMany.set (/Users/pangzi/dc-main/diascubes.com/node_modules/sequelize/lib/associations/has-many.js:317:92)
    at model.obj.(anonymous function) [as setPosts] (/Users/pangzi/dc-main/diascubes.com/node_modules/sequelize/lib/associations/help
ers.js:69:40)
    at Person.create.then.person (/Users/pangzi/dc-main/diascubes.com/demo.js:40:12)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Object.<anonymous> (/Users/pangzi/dc-main/diascubes.com/demo.js:38:4)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

I am not sure if I did any thing wrong, pls help!

I am using sequelize 4.2.1 with mysql

**Comment by janmeier** [comment]
Set accepts an already saved instance. If you want to create a new instance, use `createPost` http://docs.sequelizejs.com/class/lib/associations/has-many.js~HasMany.html#instance-method-set
