### ISSUE TITLE
empty validation message for notNull Violation

### ISSUE THREAD

**Issue by tomfun** [sequelize/sequelize#7890]
## What you are doing?
I migrated to sequelize v4 from v3. I have some model, part of definition with property and validation:

**v3**:
```js
    const application = sequelize.define('Application', {
// ......
        sso_url: {
            type: DataTypes.STRING(2083),
            allowNull: false, // cant be null
            validate: { // other validation, it doesn't matter
                isUrl: {
                    msg: 'SSO URL must be a valid url.'
                }
            }
        },
    }
// ......
    );
```
**v4**:
```js
    class Application extends sequelize.Model { /* ... */ }

    Application.init({
// ......
        sso_url: {
            type: DataTypes.STRING(2083),
            allowNull: false,
            validate: {
                isUrl: {
                    msg: 'SSO URL must be a valid url.'
                },
            }
        },
// ......
    }, {
        sequelize,
// ......
    });
```

And I have some API endpoint for application creation.
I covered this part by tests before updating to v4. The test check validation message when I don't pass *sso_url* field for creation.

I dumped validation error object to console.

## What do you expect to happen?
_To see validation error object with old fields (messages) and values, because there is no changes in [upgrade to v4 guide](http://docs.sequelizejs.com/manual/tutorial/upgrade-to-v4.html)._ And it is **breaking changes**.

## What is actually happening?
_Error object has incorrect message field._

_Output_

v3:
```js
{ SequelizeValidationError: notNull Violation: sso_url cannot be null // <- this explain the error
    at /home/stripped/node_modules/sequelize/lib/instance-validator.js:74:14
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at tryCatcher (/home/stripped/node_modules/bluebird/js/release/util.js:16:23)
// ....
    at Immediate.Async.drainQueues (/home/stripped/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
  name: 'SequelizeValidationError',
  message: 'notNull Violation: sso_url cannot be null',
  errors: 
   [ { message: 'sso_url cannot be null', // <- this field is not empty!
       type: 'notNull Violation',
       path: 'sso_url',
       value: null } ] }
```

v4:
```js
{ SequelizeValidationError: Validation Error // <- not the same
    at Promise.all.then (/home/stripped/node_modules/sequelize/lib/instance-validator.js:77:15)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at tryCatcher (/home/stripped/node_modules/bluebird/js/release/util.js:16:23)
// .......
    at Immediate.Async.drainQueues (/home/stripped/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
  name: 'SequelizeValidationError',
  errors: 
   [ ValidationErrorItem {
       message: '', // <- not the same **EMPTY**
       type: 'notNull Violation',
       path: 'sso_url',
       value: null } ] }
```

__Dialect:__ mysql
__Database version:__ 5.6.33-0ubuntu0.14.04.1
__Sequelize version:__ 3.30.4 -> **4.2.1**

**Comment by tomfun** [comment]
I can't use *notNull* like this:
```js
        sso_url: {
            type: DataTypes.STRING(2083),
            allowNull: false,
            validate: {
                isUrl: {
                    msg: 'SSO URL must be a valid url.'
                },
                notNull: {
                    msg: 'message that I expect',
                }
            }
        },
```

Because when I give this required field, [validation fails because of this](https://github.com/sequelize/sequelize/blob/master/lib/utils/validator-extras.js#L81)

**Comment by bensaufley** [comment]
FWIW this worked in 4.0.0-2 but broke when I (accidentally) upgraded to 4.2.1 and also still breaks today at 4.3.0

**Comment by pola88** [comment]
Any news about this?

**Comment by stevematdavies** [comment]
```
const EN_Translation = db.define('EN_Translation', {
    key: {
       type: Sequelize.STRING,
       allowNull: false,
       unique: true
    },
    val: {
       type: Sequelize.STRING,
       allowNull: false
    }
});
```
`EN_Translation.create("key", "value").....`

```
Unhandled rejection SequelizeValidationError: notNull Violation: EN_Translation.key cannot be null,
notNull Violation: EN_Translation.val cannot be null
```

**Comment by ozombo** [comment]
Who has a fix for this?

**Comment by tchaye59** [comment]
A faced the same problem.
The problem in my case was because I was defining my model with a constructor.
`class User extends Sequelize.Model {

    constructor() {
        super();
        this.UserStatus = {
            NEW: 0,
            ACTIVE: 1,
            BLOCKED: 2,
        };
    }
    static associate(models) {…}
    static init(sequelize) {…}
};`

After I fix the error by removing the constructor.

`class User extends Sequelize.Model {

    static associate(models) {…}

    static init(sequelize) {…}
};

User.UserStatus = {…}`

Check again how you create you model classes.
