### ISSUE TITLE
SequelizeBaseError: read ECONNRESET

### ISSUE THREAD

**Issue by hvaexlove** [sequelize/sequelize#7920]
```
{ SequelizeBaseError: read ECONNRESET
    at Query.formatError (/root/WebstormProjects/dataProject/node_modules/sequelize/lib/dialects/mysql/query.js:175:14)
    at Query._callback (/root/WebstormProjects/dataProject/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
    at Query.Sequence.end (/root/WebstormProjects/dataProject/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at Protocol.handleNetworkError (/root/WebstormProjects/dataProject/node_modules/mysql/lib/protocol/Protocol.js:364:14)
    at Connection._handleNetworkError (/root/WebstormProjects/dataProject/node_modules/mysql/lib/Connection.js:428:18)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at emitErrorNT (net.js:1279:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'SequelizeDatabaseError',
  message: 'read ECONNRESET',
  parent: 
   { Error: read ECONNRESET
       at exports._errnoException (util.js:1050:11)
       at TCP.onread (net.js:582:26)
       --------------------
       at Protocol._enqueue (/root/WebstormProjects/dataProject/node_modules/mysql/lib/protocol/Protocol.js:141:48)
       at Connection.query (/root/WebstormProjects/dataProject/node_modules/mysql/lib/Connection.js:208:25)
       at /root/WebstormProjects/dataProject/node_modules/sequelize/lib/dialects/mysql/query.js:40:21
       at Promise._execute (/root/WebstormProjects/dataProject/node_modules/bluebird/js/release/debuggability.js:300:9)
       at Promise._resolveFromExecutor (/root/WebstormProjects/dataProject/node_modules/bluebird/js/release/promise.js:483:18)
       at new Promise (/root/WebstormProjects/dataProject/node_modules/bluebird/js/release/promise.js:79:10)
       at Query.run (/root/WebstormProjects/dataProject/node_modules/sequelize/lib/dialects/mysql/query.js:39:17)
       at /root/WebstormProjects/dataProject/node_modules/sequelize/lib/sequelize.js:849:20
       at /root/WebstormProjects/dataProject/node_modules/retry-as-promised/index.js:40:21
       at Promise._execute (/root/WebstormProjects/dataProject/node_modules/bluebird/js/release/debuggability.js:300:9)
       at Promise._resolveFromExecutor (/root/WebstormProjects/dataProject/node_modules/bluebird/js/release/promise.js:483:18)
       at new Promise (/root/WebstormProjects/dataProject/node_modules/bluebird/js/release/promise.js:79:10)
       at retryAsPromised (/root/WebstormProjects/dataProject/node_modules/retry-as-promised/index.js:30:10)
       at /root/WebstormProjects/dataProject/node_modules/sequelize/lib/sequelize.js:848:12
       at tryCatcher (/root/WebstormProjects/dataProject/node_modules/bluebird/js/release/util.js:16:23)
       at Promise._settlePromiseFromHandler (/root/WebstormProjects/dataProject/node_modules/bluebird/js/release/promise.js:512:31)
     code: 'ECONNRESET',
     errno: 'ECONNRESET',
     syscall: 'read',
     fatal: true,
     sql: 'SELECT 1' },
  original: 
   { Error: read ECONNRESET
       at exports._errnoException (util.js:1050:11)
       at TCP.onread (net.js:582:26)
       --------------------
       at Protocol._enqueue (/root/WebstormProjects/dataProject/node_modules/mysql/lib/protocol/Protocol.js:141:48)
       at Connection.query (/root/WebstormProjects/dataProject/node_modules/mysql/lib/Connection.js:208:25)
       at /root/WebstormProjects/dataProject/node_modules/sequelize/lib/dialects/mysql/query.js:40:21
       at Promise._execute (/root/WebstormProjects/dataProject/node_modules/bluebird/js/release/debuggability.js:300:9)
       at Promise._resolveFromExecutor (/root/WebstormProjects/dataProject/node_modules/bluebird/js/release/promise.js:483:18)
       at new Promise (/root/WebstormProjects/dataProject/node_modules/bluebird/js/release/promise.js:79:10)
       at Query.run (/root/WebstormProjects/dataProject/node_modules/sequelize/lib/dialects/mysql/query.js:39:17)
       at /root/WebstormProjects/dataProject/node_modules/sequelize/lib/sequelize.js:849:20
       at /root/WebstormProjects/dataProject/node_modules/retry-as-promised/index.js:40:21
       at Promise._execute (/root/WebstormProjects/dataProject/node_modules/bluebird/js/release/debuggability.js:300:9)
       at Promise._resolveFromExecutor (/root/WebstormProjects/dataProject/node_modules/bluebird/js/release/promise.js:483:18)
       at new Promise (/root/WebstormProjects/dataProject/node_modules/bluebird/js/release/promise.js:79:10)
       at retryAsPromised (/root/WebstormProjects/dataProject/node_modules/retry-as-promised/index.js:30:10)
       at /root/WebstormProjects/dataProject/node_modules/sequelize/lib/sequelize.js:848:12
       at tryCatcher (/root/WebstormProjects/dataProject/node_modules/bluebird/js/release/util.js:16:23)
       at Promise._settlePromiseFromHandler (/root/WebstormProjects/dataProject/node_modules/bluebird/js/release/promise.js:512:31)
     code: 'ECONNRESET',
     errno: 'ECONNRESET',
     syscall: 'read',
     fatal: true,
     sql: 'SELECT 1' },
  sql: 'SELECT 1' }
```

```js
var sequelize;

// init db
exports.getDB = function () {

    if (sequelize != null) return sequelize;
    sequelize = new Sequelize('data_project','root','root',{
        host : '127.0.0.1',
        port : '3306',
        dialect: 'mysql',
        define :{
            'underscored': true
        },
        pool: {
            max: 2000,
            min: 20,
            maxIdleTime: 800000
        }
    });
    return sequelize;
}
```
The above are complete error information and database configuration information. The moments when errors happen are unpredictable, sometimes exceptions occur after 2 hours of operation, and sometimes after 1 day. Could you possibly tell me what's the meaning of those errors and how to solve the problem?

**Comment by hyiso** [comment]
Unlucky to have the same problem.
I guess it was because too many connection was created but after I change pool to: 
```
pool: {
    max: 1,
    min: 1,
    idel: 10000
}
```
the error still exists.
waiting for a clear indicator for the `pool` option

**Comment by onweer** [comment]
+1  `sequelize` version `3.30.4` with closing the `pool` option

**Comment by hvaexlove** [comment]
The problem has been solved, Use `mysql` module solved.

**Comment by onweer** [comment]
I used dockerlize to solve this problem , quarantine java process. @hvaexlove

**Comment by ChanMQ** [comment]
@hvaexlove  I try to uodate mysql module to 2.14.0. But it doesn't work. Do you use the same as me? https://github.com/mysqljs/mysql

**Comment by hvaexlove** [comment]
@ChanMQ We use the same module` mysql` version 2.14.0,MySQL Server Version  5.7.x.
