### ISSUE TITLE
connect sql server 2000 error:Unknown type: 0

### ISSUE THREAD

**Issue by 253936563** [sequelize/sequelize#7925]
```
const sequelize = new Sequelize(config.db_name, config.db_username, config.db_password, {
    host: "host",
    dialect: "mssql",
    port: config.db_port,
    // pool: {
    //     max: config.db_pool_max,
    //     min: config.db_pool_min,
    //     idle: config.db_pool_idle
    // },
    // define: {
    //     freezeTableName: true,
    //     updatedAt: 'updated_time',
    //     createdAt: 'created_time',
    // }
});
sequelize.authenticate().then(() => console.log("success")).catch(err => console.log(err));
```

I want to connect sql server 2000, but have error: unknown type: 0， how should i solve

**Comment by eseliger** [comment]
Can you provide a full stack?

**Comment by 253936563** [comment]
` "sequelize": "^3.30.2",`
`tedious: ^2.0.1,`

This my dependencies version

`const sequelize = new Sequelize(config.db_name, config.db_username, config.db_password, {
    host: "host",
    dialect: "mssql",
    port: config.db_port,
});
sequelize.authenticate().then(() => console.log("success")).catch(err => console.log(err));`

This is all.
I only test connect sql server 2000

**Comment by 253936563** [comment]
`Error: Unknown type: 0
    at Parser.parseTokens (D:\wjh\qixiu\qixiu-new-backage\trunk\node_modules\tedious\lib\token\stream-parser.js:114:30)
    at Parser._transform (D:\wjh\qixiu\qixiu-new-backage\trunk\node_modules\tedious\lib\token\stream-parser.js:87:14)
    at Parser.Transform._read (D:\wjh\qixiu\qixiu-new-backage\trunk\node_modules\tedious\node_modules\readable-stream\lib\_stream_transform.js:182:10)
    at Parser.Transform._write (D:\wjh\qixiu\qixiu-new-backage\trunk\node_modules\tedious\node_modules\readable-stream\lib\_stream_transform.js:170:83)
    at doWrite (D:\wjh\qixiu\qixiu-new-backage\trunk\node_modules\tedious\node_modules\readable-stream\lib\_stream_writable.js:406:64)
    at writeOrBuffer (D:\wjh\qixiu\qixiu-new-backage\trunk\node_modules\tedious\node_modules\readable-stream\lib\_stream_writable.js:395:5)
    at Parser.Writable.write (D:\wjh\qixiu\qixiu-new-backage\trunk\node_modules\tedious\node_modules\readable-stream\lib\_stream_writable.js:322:11)
    at Parser.addBuffer (D:\wjh\qixiu\qixiu-new-backage\trunk\node_modules\tedious\lib\token\token-stream-parser.js:63:26)
    at Connection.sendDataToTokenStreamParser (D:\wjh\qixiu\qixiu-new-backage\trunk\node_modules\tedious\lib\connection.js:817:37)
    at Connection.data (D:\wjh\qixiu\qixiu-new-backage\trunk\node_modules\tedious\lib\connection.js:1286:21)
    at Connection.dispatchEvent (D:\wjh\qixiu\qixiu-new-backage\trunk\node_modules\tedious\lib\connection.js:687:45)
    at MessageIO.<anonymous> (D:\wjh\qixiu\qixiu-new-backage\trunk\node_modules\tedious\lib\connection.js:599:18)
    at emitOne (events.js:96:13)
    at MessageIO.emit (events.js:188:7)
    at ReadablePacketStream.<anonymous> (D:\wjh\qixiu\qixiu-new-backage\trunk\node_modules\tedious\lib\message-io.js:100:14)
    at emitOne (events.js:96:13)`

This is error

**Comment by 253936563** [comment]
@eseliger

**Comment by eseliger** [comment]
Probably a bug in tedious: https://github.com/tediousjs/tedious/issues/368

SQL Server 2000 is veery old. There seem to be some compatibility issues in the protocol.

**Comment by 253936563** [comment]
OK Thanks

**Comment by 253936563** [comment]
I find a way can solve that.We can set  node_modules/tedious/lib/track-buffer/connection.js DEFAULT_TDS_VERSION = '7_1'.But I can‘t set this by Sequelize.

**Comment by 253936563** [comment]
I can set this in Sequelize options?

**Comment by 253936563** [comment]
@eseliger

**Comment by nappalm** [comment]
Has a solution to this problem been found?
