### ISSUE TITLE
 Can't write; duplicate key in table '#sql-42b_c9c'

### ISSUE THREAD

**Issue by miles-collier** [sequelize/sequelize#7959]
models/sources.js
```
'use strict';
module.exports = function(sequelize, DataTypes) {
  var Prices = sequelize.define('prices', {
    sku: DataTypes.STRING(40),
    price: DataTypes.DECIMAL(13,2)
  });

  Prices.associate = function(models) {
    Prices.belongsTo(models.sources);
  }

  return Prices;
};
```

prices.js
```
'use strict';
module.exports = function(sequelize, DataTypes) {
  var Sources = sequelize.define('sources', {
    name: DataTypes.STRING
  });

  Sources.associate = function(models) {
    Sources.hasMany(models.prices);
  }

  return Sources;
};
```

The initial insert works, but if it's reran/synced it throws this error:

```
Unhandled rejection SequelizeDatabaseError: Can't write; duplicate key in table '#sql-42b_c9c'
    at Query.formatError (/opt/node/aperture/node_modules/sequelize/lib/dialects/mysql/query.js:222:16)
    at Query.connection.query [as onResult] (/opt/node/aperture/node_modules/sequelize/lib/dialects/mysql/query.js:55:23)
    at Query.Command.execute (/opt/node/aperture/node_modules/mysql2/lib/commands/command.js:30:12)
    at Connection.handlePacket (/opt/node/aperture/node_modules/mysql2/lib/connection.js:515:28)
    at PacketParser.onPacket (/opt/node/aperture/node_modules/mysql2/lib/connection.js:94:16)
    at PacketParser.executeStart (/opt/node/aperture/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.<anonymous> (/opt/node/aperture/node_modules/mysql2/lib/connection.js:102:29)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:561:20)
```

Using the latest 4.3.2 version.

**Comment by aradnom** [comment]
Same issue using 4.13.8.  Only happens for me when alter: true is used with db.sync().

**Comment by pedroprcgm** [comment]
Someone found a solution for this?

**Comment by miles-collier** [comment]
@aradnom @pedroprcgm  Checkout issue #7606, I've been stalking it. Same issue
