### ISSUE TITLE
Postgres Dialect (pg) - TypeError: connection.query(...).on is not a function 

### ISSUE THREAD

**Issue by sgehly** [sequelize/sequelize#7981]
## What you are doing?

```js
var Sequelize = require('sequelize');

var options = {
	logging: false,
	dialect: 'postgres',
        port = process.env.DB_PORT;
}

var sequelize = new Sequelize(process.env.DB_DATABASE || '', process.env.DB_USER || '', process.env.DB_PASS || '', options)

sequelize.authenticate().then(function(test){console.log(test)}); //Errors out
```

## What do you expect to happen?
Expected it to successfully authenticate, this errors out on every database call.

## What is actually happening?
`TypeError: connection.query(...).on is not a function

 at Promise (sequelize/lib/dialects/postgres/connection-manager.js:158:12)

 at Promise._execute (bluebird/js/release/debuggability.js:300:9)

 at Promise._resolveFromExecutor (bluebird/js/release/promise.js:483:18)

 at new Promise (bluebird/js/release/promise.js:79:10)

 at Promise.tap.connection (sequelize/lib/dialects/postgres/connection-manager.js:156:14)

 at PassThroughHandlerContext.finallyHandler (bluebird/js/release/finally.js:57:23)

 at PassThroughHandlerContext.tryCatcher (bluebird/js/release/util.js:16:23)

 at Promise._settlePromiseFromHandler (bluebird/js/release/promise.js:512:31)

 at Promise._settlePromise (bluebird/js/release/promise.js:569:18)

 at Promise._settlePromise0 (bluebird/js/release/promise.js:614:10)

 at Promise._settlePromises (bluebird/js/release/promise.js:693:18)

 at Async._drainQueue (bluebird/js/release/async.js:133:16)

 at Async._drainQueues (bluebird/js/release/async.js:143:10)

 at Immediate.Async.drainQueues (bluebird/js/release/async.js:17:14)

 at runCallback (timers.js:574:20)

 at tryOnImmediate (timers.js:554:5)

 at processImmediate [as _immediateCallback] (timers.js:533:5)`

__Dialect:__ postgres
__Database version:__ 9.6.1
__Sequelize version:__ ^4.3.2

**Comment by sgehly** [comment]
Just saw #7977 -- Closing this.
