### ISSUE TITLE
Table.sync causes unhandled rejection with pg 7

### ISSUE THREAD

**Issue by tapz** [sequelize/sequelize#7987]
## What you are doing?

Create tables.

```js
MyTable.sync({force: true, logging: console.log});
```

## What do you expect to happen?
Table created, no errors.

## What is actually happening?

```js
Unhandled rejection TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Promise.then.result (/Users/tapani/projects/Cool/myapp-backend/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:157:31)
From previous event:
    at Promise.tap.connection (/Users/tapani/projects/Cool/myapp-backend/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:156:132)
From previous event:
    at ConnectionManager.connect (/Users/tapani/projects/Cool/myapp-backend/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:133:8)
    at sequelize.runHooks.then (/Users/tapani/projects/Cool/myapp-backend/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:295:50)
From previous event:
    at ConnectionManager._connect (/Users/tapani/projects/Cool/myapp-backend/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:295:8)
    at ConnectionManager.getConnection (/Users/tapani/projects/Cool/myapp-backend/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:247:46)
    at Promise.try (/Users/tapani/projects/Cool/myapp-backend/node_modules/sequelize/lib/sequelize.js:525:92)
From previous event:
    at Sequelize.query (/Users/tapani/projects/Cool/myapp-backend/node_modules/sequelize/lib/sequelize.js:432:23)
    at QueryInterface.dropTable (/Users/tapani/projects/Cool/myapp-backend/node_modules/sequelize/lib/query-interface.js:180:27)
    at Function.drop (/Users/tapani/projects/Cool/myapp-backend/node_modules/sequelize/lib/model.js:1165:32)
    at Promise.try.then (/Users/tapani/projects/Cool/myapp-backend/node_modules/sequelize/lib/model.js:1098:21)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Function.sync (/Users/tapani/projects/Cool/myapp-backend/node_modules/sequelize/lib/model.js:1096:8)
    at module.exports (/Users/tapani/projects/Cool/myapp-backend/config/express.js:95:11)
    at Object.<anonymous> (/Users/tapani/projects/Cool/myapp-backend/app.js:7:28)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.nodeDevHook [as .js] (/Users/tapani/.config/yarn/global/node_modules/node-dev/lib/hook.js:61:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/tapani/projects/Cool/myapp-backend/bin/www.js:10:13)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.nodeDevHook [as .js] (/Users/tapani/.config/yarn/global/node_modules/node-dev/lib/hook.js:61:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/tapani/.config/yarn/global/node_modules/node-dev/lib/wrap.js:73:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
```

__Dialect:__ postgres
__Database version:__ 9.6.2 (node-posgres: 7.0.1)
__Sequelize version:__ 4.4.0

**Comment by scttcper** [comment]
Same as #7985
