### ISSUE TITLE
undefined options in Sequelize.NUMBER type

### ISSUE THREAD

**Issue by axetroy** [sequelize/sequelize#7997]
## What you are doing?

define an field type with NUMBER and write

```typescript
import * as Sequelize from 'sequelize';
import sequelize from '../service/postgres';

const Test = sequelize.define('test', {
  firstName: {
    type: Sequelize.STRING
  },
  lastName: {
    type: Sequelize.STRING
  },
  age: {
    type: Sequelize.NUMBER,
    required: false
  }
});

export default Test;
```

```typescript
export async function create(id: string, val: string) {
  console.log('write');
  await TestModal.sync();
  const data = await TestModal.create({
    firstName: 'John',
    lastName: 'Hancock',
    age: 10
  });
  console.log(data.dataValues);
  return data.dataValues;
}
```

## What do you expect to happen?

It should be success

## What is actually happening?

```bash
C:\Users\axetroy\gpm\yichui.net\axetroy\duomi-nodejs\node_modules\sequelize\lib\data-types.js:114
  this._length = options.length;
                        ^
TypeError: Cannot read property 'length' of undefined
    at new NUMBER (C:\Users\axetroy\gpm\yichui.net\axetroy\duomi-nodejs\node_modules\sequelize\lib\data-types.js:114:25)
    at Sequelize.normalizeDataType (C:\Users\axetroy\gpm\yichui.net\axetroy\duomi-nodejs\node_modules\sequelize\lib\sequelize.js:1064:45)
    at Sequelize.normalizeAttribute (C:\Users\axetroy\gpm\yichui.net\axetroy\duomi-nodejs\node_modules\sequelize\lib\sequelize.js:1083:27)
    at attributes.rawAttributes._.mapValues (C:\Users\axetroy\gpm\yichui.net\axetroy\duomi-nodejs\node_modules\sequelize\lib\model.js:786:34)
    at C:\Users\axetroy\gpm\yichui.net\axetroy\duomi-nodejs\node_modules\lodash\lodash.js:13379:38
    at C:\Users\axetroy\gpm\yichui.net\axetroy\duomi-nodejs\node_modules\lodash\lodash.js:4944:15
    at baseForOwn (C:\Users\axetroy\gpm\yichui.net\axetroy\duomi-nodejs\node_modules\lodash\lodash.js:3001:24)
    at Function.mapValues (C:\Users\axetroy\gpm\yichui.net\axetroy\duomi-nodejs\node_modules\lodash\lodash.js:13378:7)
    at Function.init (C:\Users\axetroy\gpm\yichui.net\axetroy\duomi-nodejs\node_modules\sequelize\lib\model.js:784:46)
    at Sequelize.define (C:\Users\axetroy\gpm\yichui.net\axetroy\duomi-nodejs\node_modules\sequelize\lib\sequelize.js:322:11)
    at Object.<anonymous> (C:\Users\axetroy\gpm\yichui.net\axetroy\duomi-nodejs\app\postgres\test.modal.ts:7:24)
    at Module._compile (module.js:570:32)
    at Module.m._compile (C:\Users\axetroy\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:392:23)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\Users\axetroy\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:395:12)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\axetroy\gpm\yichui.net\axetroy\duomi-nodejs\app\controllers\concurrent-test.ts:4:1)
    at Module._compile (module.js:570:32)
    at Module.m._compile (C:\Users\axetroy\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:392:23)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\Users\axetroy\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:395:12)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

__Dialect:__ postgres
__Database version:__ 9.6
__Sequelize version:__ 4.4.1

**Comment by felixfbecker** [comment]
I don't know where you have that type from, but it's not documented
http://docs.sequelizejs.com/variable/index.html#static-variable-DataTypes

**Comment by poode** [comment]
hello guys, I faced same issue and after reading in docs I found that there is no type called NUMBER @axetroy please use INTEGER  with `
 age: {
    type: Sequelize.NUMBER, //  should be Sequelize.INTEGER
    required: false
  }
`
