### ISSUE TITLE
There is a problem when removing primary key constraints in mssql

### ISSUE THREAD

**Issue by felpin** [sequelize/sequelize#8012]
## What you are doing?

I am trying to apply a migration that removes a primary key constraint from a table:
![image](https://user-images.githubusercontent.com/22778265/28629666-77dfda92-71fe-11e7-9d69-767e43032bb3.png)

The content of my migration file is:
```js
module.exports = {
  up: queryInterface => queryInterface.removeConstraint('status', 'pk__id__status'),
// down code ommited
}
```

## What do you expect to happen?
I expect the primary key constraint to be removed

## What is actually happening?
I've got a SequelizeUnknownConstraintError error
```
{ SequelizeBaseError
    at Query.formatError (D:\Projetos\SEP\Manifestação Pública\api\node_modules\sequelize\lib\dialects\mssql\query.js:275:14)
    at Request.connection.lib.Request [as userCallback] (D:\Projetos\SEP\Manifestação Pública\api\node_modules\sequelize\lib\dialects\mssql\query.js:91:25)
    at Request._this.callback (D:\Projetos\SEP\Manifestação Pública\api\node_modules\tedious\lib\request.js:47:27)
    at Connection.message (D:\Projetos\SEP\Manifestação Pública\api\node_modules\tedious\lib\connection.js:1401:27)
    at Connection.dispatchEvent (D:\Projetos\SEP\Manifestação Pública\api\node_modules\tedious\lib\connection.js:687:45)
    at MessageIO.<anonymous> (D:\Projetos\SEP\Manifestação Pública\api\node_modules\tedious\lib\connection.js:602:18)
    at emitNone (events.js:105:13)
    at MessageIO.emit (events.js:207:7)
    at ReadablePacketStream.<anonymous> (D:\Projetos\SEP\Manifestação Pública\api\node_modules\tedious\lib\message-io.js:102:16)
    at emitOne (events.js:115:13)
    at ReadablePacketStream.emit (events.js:210:7)
    at readableAddChunk (D:\Projetos\SEP\Manifestação Pública\api\node_modules\readable-stream\lib\_stream_readable.js:212:18)
    at ReadablePacketStream.Readable.push (D:\Projetos\SEP\Manifestação Pública\api\node_modules\readable-stream\lib\_stream_readable.js:171:10)
    at ReadablePacketStream.Transform.push (D:\Projetos\SEP\Manifestação Pública\api\node_modules\readable-stream\lib\_stream_transform.js:123:32)
    at ReadablePacketStream._transform (D:\Projetos\SEP\Manifestação Pública\api\node_modules\tedious\lib\message-io.js:70:16)
    at ReadablePacketStream.Transform._read (D:\Projetos\SEP\Manifestação Pública\api\node_modules\readable-stream\lib\_stream_transform.js:159:10)
    at ReadablePacketStream.Transform._write (D:\Projetos\SEP\Manifestação Pública\api\node_modules\readable-stream\lib\_stream_transform.js:147:83)
    at doWrite (D:\Projetos\SEP\Manifestação Pública\api\node_modules\readable-stream\lib\_stream_writable.js:338:64)
    at writeOrBuffer (D:\Projetos\SEP\Manifestação Pública\api\node_modules\readable-stream\lib\_stream_writable.js:327:5)
    at ReadablePacketStream.Writable.write (D:\Projetos\SEP\Manifestação Pública\api\node_modules\readable-stream\lib\_stream_writable.js:264:11)
    at Socket.ondata (_stream_readable.js:628:20)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at TCP.onread (net.js:589:20)
  name: 'SequelizeUnknownConstraintError',
  message: 'The specified constraint does not exist',
  parent: { message: undefined },
  original: { message: undefined },
  sql: undefined }
```

__Dialect:__ mssql
__Database version:__ SQL Server 2012
__Sequelize version:__ Sequelize [Node: 8.2.1, CLI: 2.7.0, ORM: 4.0.0]

**Comment by felpin** [comment]
Ok... There was a foreign key referencing the status table and that was the reason I couldn't remove the primary key...

Well... I think that the error could be different, because SequelizeUnknownConstraintError with message 'The specified constraint does not exist' do not reflect the correct error.
