### ISSUE TITLE
problem when upsert using with pg@7.0

### ISSUE THREAD

**Issue by kukoo1** [sequelize/sequelize#8026]
## What you are doing?
```js
try {
 await NewsSubscriber.insertOrUpdate(data);
} catch (e) {
 console.log(e);
}
```

## What do you expect to happen?
Not been caught by try-catch block.

## What is actually happening?
Data was inserted into db successfully.
But it's caught by try-catch and console.log output this
`
TypeError: Cannot read property '0' of undefined
    at query.catch.then.then.queryResult (C:\Website\node_modules\sequelize\lib\dialects\postgres\query.js:112:17)
    at tryCatcher (C:\Website\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Website\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Website\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Website\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Website\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Website\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Website\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Website\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
`

__Dialect:__ postgres
__Database version:__ pg@7.0.2
__Sequelize version:__ 4.4.2

It used to work as expected on pg@6.4.1.

**Comment by alitaheri** [comment]
This is the reason: #7998 

Please downgrade for now until we find a solution for this.

**Comment by kukoo1** [comment]
Thanks, alitaheri
look forward to the fix
