### ISSUE TITLE
momentjs deprecation warning on dateonly

### ISSUE THREAD

**Issue by dustintenney** [sequelize/sequelize#8035]
## What you are doing?

    var test = sequelize.define('test', {
        id: { type: DataTypes.UUID, primaryKey: true },
        my_date: DataTypes.DATEONLY,
    });

    var start = '2017-1-1';
    var end = '2017-12-31;
    models.test.findAll({ attributes: ['id'], where: { my_date: {$gte: start, $lte: end} } })

## What do you expect to happen?

This should not produce a deprecation warning.

## What is actually happening?

Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 2016-1-1, _f: undefined, _strict: undefined, _locale: [object Object]

Error
    at Function.createFromInputFallback (/var/www/html/node_modules/moment/moment.js:320:94)
    at configFromString (/var/www/html/node_modules/moment/moment.js:2178:11)
    at configFromInput (/var/www/html/node_modules/moment/moment.js:2547:9)
    at prepareConfig (/var/www/html/node_modules/moment/moment.js:2530:9)
    at createFromConfig (/var/www/html/node_modules/moment/moment.js:2497:40)
    at createLocalOrUTC (/var/www/html/node_modules/moment/moment.js:2584:12)
    at createLocal (/var/www/html/node_modules/moment/moment.js:2588:12)
    at hooks (/var/www/html/node_modules/moment/moment.js:16:25)
    at DATEONLY._stringify (/var/www/html/node_modules/sequelize/lib/data-types.js:354:10)
    at DATEONLY.stringify (/var/www/html/node_modules/sequelize/lib/data-types.js:32:17)
    at Object.escape (/var/www/html/node_modules/sequelize/lib/dialects/abstract/query-generator.js:906:32)
    at Object.whereItemQuery (/var/www/html/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2308:22)
    at /var/www/html/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2192:25
    at /var/www/html/node_modules/sequelize/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/var/www/html/node_modules/sequelize/node_modules/lodash/lodash.js:3001:24)
    at Function.forOwn (/var/www/html/node_modules/sequelize/node_modules/lodash/lodash.js:13002:24)
    at Object.whereItemQuery (/var/www/html/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2189:9)
    at /var/www/html/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1939:25
    at /var/www/html/node_modules/sequelize/node_modules/lodash/lodash.js:4944:15
    at baseForOwn (/var/www/html/node_modules/sequelize/node_modules/lodash/lodash.js:3001:24)
    at Function.forOwn (/var/www/html/node_modules/sequelize/node_modules/lodash/lodash.js:13002:24)
    at Object.whereItemsQuery (/var/www/html/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1938:9)
    at Object.getWhereConditions (/var/www/html/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2379:19)
    at Object.selectQuery (/var/www/html/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1123:28)
    at QueryInterface.select (/var/www/html/node_modules/sequelize/lib/query-interface.js:672:27)
    at /var/www/html/node_modules/sequelize/lib/model.js:1538:34
    at tryCatcher (/var/www/html/node_modules/sequelize/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/html/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/www/html/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/www/html/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/www/html/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/var/www/html/node_modules/sequelize/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/var/www/html/node_modules/sequelize/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/var/www/html/node_modules/sequelize/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:396:17)

This was happening with sequelize 3.30.4 and still happens after upgrading to 4.4.2.

It seems to be a result of trying to use moment on the input dates in this function.

DATEONLY.prototype._stringify = function _stringify(date) {
  return moment(date).format('YYYY-MM-DD');
};

_Output, either JSON or SQL_

__Dialect:__ postgres
__Database version:__ 9.6
__Sequelize version:__ 4.4.2

**Comment by mygnu** [comment]
similar issue here

**Comment by spathon** [comment]
Should been solved in [v4.7.3](https://github.com/sequelize/sequelize/releases/tag/v4.7.3) with this PR #8179

**Comment by dustintenney** [comment]
I upgraded to v4.7.5 and still have the issue.

**Comment by morphesus** [comment]
Don't get the error anymore with version 4.8.0

**Comment by Boelensman1** [comment]
I am on 4.38.1 and also have this issue

**Comment by d0ruk** [comment]
4.41.2, same issue.

**Comment by CrypticWoodWhite** [comment]
I just started getting this issue today too. Changing from .DATE to .DATEONLY or vice versa did not fix the problem. 

v.5.8.6

**Comment by StevenWung** [comment]
Not resolved, why issue closed?

**Comment by omricohen** [comment]
For those stumbling here, here was my solution, convert to date object before building the model. For example:

`dateOfBirth = moment(rawUser.dateOfBirth,"MM/DD/YYYY").toDate();`

**Comment by papb** [comment]
Hello, may I ask why you all think this deprecation warning is incorrect? It appears correct to me, dates should follow [ISO8601 stardard](https://en.wikipedia.org/wiki/ISO_8601), so a warning for not following it seems correct.

This reminded me of this [XKCD](https://xkcd.com/1179/)

**Comment by SamIAmHarris** [comment]
I had the same issue and was able to get it to go away by changing how I enter single digit dates/months. 

I needed the leading 0. 

For example: '2017-1-1' should be '2017-01-01'

**Comment by papb** [comment]
I will close this for now, considering that a warning is acceptable if [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) is not being followed. If someone disagrees let me know and I will reopen.

**Comment by juanruben** [comment]
I have this issue with the 6.6.2 version

**Comment by ephys** [comment]
You need to wrap that in `literal()` or moment will try to parse that string as a date
