### ISSUE TITLE
Errors in setter

### ISSUE THREAD

**Issue by atralice** [sequelize/sequelize#8073]
## What you are doing?
Hi, I was using setter in one of my models and found out that errors that are thrown in the set() function are not being catch.

I made a small example to reproduce the behavior.

```js
// code here
const Sequelize = require('sequelize'); 
const sequelize = require('./db.js'); 
     
  const Employee = sequelize.define('employee', { 
    name: { 
      type: Sequelize.STRING, 
      allowNull: false, 
      set(name) {
        console.log(name); 
        throw new Error('Who catches this error??'); 
      }, 
    }, 
  }); 
     
  sequelize.sync({ force: false }).then(() => { 
    Employee 
      .create({ name: 'John Doe' }) 
        .then(employee => { 
        console.log(employee.get('name')); // John Doe (SENIOR ENGINEER) 
     }).catch( (error) => { console.log(error) }) 
  });

 ```

## What do you expect to happen?
I expected the error to be catch and logged in the console.log.

## What is actually happening?
The error in bubbling up and no ones catches it.

Output:

```bash
John Doe
Unhandled rejection Error: Who catches this error??
    at model.set (/home/atralice/Projects/Misc/sequelizeBug/index.js:10:13)
    at model.set (/home/atralice/Projects/Misc/sequelizeBug/node_modules/sequelize/lib/model.js:3230:34)
    at model.set (/home/atralice/Projects/Misc/sequelizeBug/node_modules/sequelize/lib/model.js:3212:18)
    at model._initValues (/home/atralice/Projects/Misc/sequelizeBug/node_modules/sequelize/lib/model.js:3027:10)
    at model.Model (/home/atralice/Projects/Misc/sequelizeBug/node_modules/sequelize/lib/model.js:2976:10)
    at employee (/home/atralice/Projects/Misc/sequelizeBug/node_modules/sequelize/lib/sequelize.js:320:19)
    at Function.build (/home/atralice/Projects/Misc/sequelizeBug/node_modules/sequelize/lib/model.js:1914:12)
    at Function.create (/home/atralice/Projects/Misc/sequelizeBug/node_modules/sequelize/lib/model.js:1965:17)
    at sequelize.sync.then (/home/atralice/Projects/Misc/sequelizeBug/index.js:17:6)
    at tryCatcher (/home/atralice/Projects/Misc/sequelizeBug/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/atralice/Projects/Misc/sequelizeBug/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/atralice/Projects/Misc/sequelizeBug/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/atralice/Projects/Misc/sequelizeBug/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/atralice/Projects/Misc/sequelizeBug/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/atralice/Projects/Misc/sequelizeBug/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/atralice/Projects/Misc/sequelizeBug/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/atralice/Projects/Misc/sequelizeBug/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

```

__Dialect:__ postgres
__Database version:__ PostgreSQL 9.6.3 on x86_64-pc-linux-musl, compiled by gcc (Alpine 6.2.1) 6.2.1 20160822, 64-bit
__Sequelize version:__ ^4.4.2

**Comment by Cyberuben** [comment]
No update on this?

**Comment by papb** [comment]
You forgot to return the Promise in your example above.
