### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'query' of undefined

### ISSUE THREAD

**Issue by ryanSN** [sequelize/sequelize#8087]
## What you are doing?

```js
    return sequelize.transaction((tx) => {
      return Topping.destroy({where: {pizza_id: request.params.id}, transaction: tx})
        .then((res) => {
          return Pizza.destroy({
            where: {id: request.params.id},
            transaction: tx
          })
        })
    }).then((res) => reply('Pizza removed'))
      .catch((err) => reply(err)
  })

```

## What do you expect to happen?
A Transaction!

## What is actually happening?
```
Unhandled rejection TypeError: Cannot read property 'query' of undefined
at parameters.length.Promise (/Users/me/projects/pizza-api/node_modules/sequelize/lib/dialects/postgres/query.js:65:53)
    at Promise._execute (/Users/me/projects/pizza-api/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/me/projects/pizza-api/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/me/projects/pizza-api/node_modules/bluebird/js/release/promise.js:79:10)
    at Query.run (/Users/me/projects/pizza-api/node_modules/sequelize/lib/dialects/postgres/query.js:65:9)
    at retry (/Users/me/projects/pizza-api/node_modules/sequelize/lib/sequelize.js:529:32)
    at /Users/me/projects/pizza-api/node_modules/retry-as-promised/index.js:40:21
    at Promise._execute (/Users/me/projects/pizza-api/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/me/projects/pizza-api/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/me/projects/pizza-api/node_modules/bluebird/js/release/promise.js:79:10)
    at retryAsPromised (/Users/me/projects/pizza-api/node_modules/retry-as-promised/index.js:30:10)
    at Promise.try.then.connection (/Users/me/projects/pizza-api/node_modules/sequelize/lib/sequelize.js:529:14)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at tryCatcher (/Users/me/projects/pizza-api/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/me/projects/pizza-api/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/me/projects/pizza-api/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/Users/me/projects/pizza-api/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/Users/me/projects/pizza-api/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Users/me/projects/pizza-api/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/me/projects/pizza-api/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:666:20)
```

__Dialect:__ postgres
__Database version:__ 9.4.5.0
__Sequelize version:__ 4.4.2
__Bluebird version:__ 3.5.0

To note I downgraded to version __Sequelize version:__ 3.29.0, code above goes through fine as expected as a transaction

**Comment by axetroy** [comment]
I got same problem.

**Comment by prokopsimek** [comment]
same problem

**Comment by mhuggins** [comment]
I'm also encountering this on sequelize 4.6.0.

**Comment by mhuggins** [comment]
Downgrading to sequelize 3.29.0 fixed the problem for me as well.

**Comment by ddura** [comment]
What version of pg module are you using? I am getting the same error but downgrading to 3.29.0 did not fix the problem for me.

**Comment by mhuggins** [comment]
I'm using pg 6.4.1 with sequelize 3.30.4.

**Comment by ryanSN** [comment]
@ddura pg 6.4.1

**Comment by santiagodoldan** [comment]
We're also having this issue in production

**pg** 6.4.0 and **sequelize** 4.10.0

**Comment by knowtheory** [comment]
Hey i bumped into this issue while using sequelize in an AWS Lambda function.

The issue ended up being the fact that i was initially instantiating a `sequelize` object & database connections in a `db.js` file i was requiring at the top of my lambda function, rather than actually initializing the database connections w/in the lambda function itself.

Why does that matter?  Well if you're declaring stuff outside of your lambda function, AWS may keep your code hot, and reuse objects you've already declared (and just rerun your lambda function).

So, my lambda function was running fine on first run, and then happily closed down the db connection.  All subsequent attempts to connect to the DB would toss the error that folks are seeing above.

I ended up wrapping all of my database code in a class which i could use to instantiate and then close down connections to my DB, and only instantiated that class from w/in the body of the lambda function.

Not positive that this is everybody's issue, but maybe this'll help some of you.

**Comment by dskvr** [comment]
🤦‍♂️

**Comment by santiagodoldan** [comment]
I was able to stop getting this issue increasing the pool of connections and setting a higher value to the new `acquire` config.

```
  pool: {
    max: 15,
    min: 0,
    idle: 10000,
    acquire: 10000
  }
```

**Comment by nutheory** [comment]
santiagodoldan's solution worked perfectly for me... i was running seeds that choked after a certain amount....

**Comment by shanmarkus** [comment]
Any update on this ? 

i'm using sequelize 4.13.5 and pg 6.2.0

**Comment by ahlwong** [comment]
Just upgraded sequelize 4.22.8 and ran into this issue

**Comment by gabegorelick** [comment]
Still seeing this on Sequelize v4.32.7 and pg v7.4.1. Set acquire to `20000` and still see it.

**Comment by gabegorelick** [comment]
By the way, here's the stack trace for latest Sequelize. For us, it's not consistently reproducible.

```
Unhandled rejection TypeError: Cannot read property 'query' of undefined
    at parameters.length.Promise (/root/node_modules/sequelize/lib/dialects/postgres/query.js:65:53)
    at Query.run (/root/node_modules/sequelize/lib/dialects/postgres/query.js:65:9)
    at Promise.try.then.connection (/root/node_modules/sequelize/lib/sequelize.js:558:20)
From previous event:
    at retryParameters (/root/node_modules/sequelize/lib/sequelize.js:555:8)
    at /root/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/root/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/root/node_modules/sequelize/lib/sequelize.js:454:12)
    at QueryInterface.rollbackTransaction (/root/node_modules/sequelize/lib/query-interface.js:1449:36)
    at Transaction.rollback (/root/node_modules/sequelize/lib/transaction.js:93:8)
    at connectionPromise.then.then.then.then.then.catch.setupErr (/root/node_modules/sequelize/lib/transaction.js:128:31)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Transaction.prepareEnvironment (/root/node_modules/sequelize/lib/transaction.js:128:13)
    at Sequelize._clsRun (/root/node_modules/sequelize/lib/sequelize.js:997:26)
    at Function._clsRun (/root/node_modules/sequelize/lib/sequelize.js:1042:21)
    at Sequelize.transaction (/root/node_modules/sequelize/lib/sequelize.js:996:22)
```

**Comment by contra** [comment]
I've had this happen one time (showed up in sentry) and never since. Really hard to reproduce, but it does happen. Running latest master sequelize.

**Comment by contra** [comment]
Nevermind, this happened 106 times today - here is some more info:

![screen shot 2018-02-12 at 3 48 30 pm](https://user-images.githubusercontent.com/425716/36118818-3f1df980-100c-11e8-9218-ba22e5f2b439.png)
![screen shot 2018-02-12 at 3 48 08 pm](https://user-images.githubusercontent.com/425716/36118826-43d0f810-100c-11e8-89bc-feaca48e4b5c.png)

**Comment by papandreou** [comment]
I've run into this problem once in production as well after upgrading to sequelize 4. It seemed to happen right after the process had lost all its connections to postgres, and I've managed to reproduce it locally by simulating an error from the pg module (and configuring sequelize not to use the native driver):

```diff
diff --git a/node_modules/pg/lib/connection.js b/node_modules/pg/lib/connection.js
index 94deef88a..40801f3df 100644
--- a/node_modules/pg/lib/connection.js
+++ b/node_modules/pg/lib/connection.js
@@ -73,6 +73,9 @@ Connection.prototype.connect = function(port, host) {
     if (self._keepAlive) {
       self.stream.setKeepAlive(true);
     }
+    setTimeout(() => {
+      self.stream.emit('error', new Error('ETIMEDOUT'));
+    }, 1);
     self.emit('connect');
   });
```

This makes sequelize 4.32.8 fail with `Cannot read property 'query' of undefined` and that same stack trace as others have reported.

**Comment by papandreou** [comment]
I've tried single-stepping through the code starting from where the synthetic `ETIMEDOUT` error is emitted.

The error first makes it into sequelize here: https://github.com/sequelize/sequelize/blob/e92dc6f5a7d63da028e06e0597531d16aa77f059/lib/dialects/postgres/connection-manager.js#L111

And is passed on here: https://github.com/sequelize/sequelize/blob/e92dc6f5a7d63da028e06e0597531d16aa77f059/lib/dialects/postgres/connection-manager.js#L132

But despite that the promise ends up being fulfilled with `undefined` here: https://github.com/sequelize/sequelize/blob/e92dc6f5a7d63da028e06e0597531d16aa77f059/lib/sequelize.js#L555

**Comment by sushantdhiman** [comment]
So connect is called atleast two times, once with error other time with undefined? Promise can't resolve when we reject it :p

**Comment by papandreou** [comment]
@sushantdhiman, in the experiment I'm running, the `connection.connect` callback gets called twice, but only once per connection instance, both times with an artificial `ETIMEDOUT` error. In other words, it doesn't seem like the `pg` module does anything weird here.

The function starting at https://github.com/sequelize/sequelize/blob/196a381d3a9b9011b92a6a8484f9bcbb2dfa2ff8/lib/sequelize.js#L455 only gets run once and when
https://github.com/sequelize/sequelize/blob/196a381d3a9b9011b92a6a8484f9bcbb2dfa2ff8/lib/sequelize.js#L552
is executed, `options.transaction` is there, but `options.transaction.connection` is undefined. That explains why the promise is fulfilled with `undefined`.

Are you able to reproduce it by patching the `pg` module and trying to running a query in a transaction?

**Comment by holm** [comment]
I added a PR at https://github.com/sequelize/sequelize/pull/9051 which I believe fixes the issue

**Comment by sushantdhiman** [comment]
This testcase is able to reproduce this issue with same stack as most have reported with. I think application is running out of connections as defined by pool configuration thus unable to acquire new connection because all other open connections are busy right now.

@holm fix doesn't seems to work for my testcase, does it work for your testcase @papandreou ?

I think we can throw a special error like `SequelizeConnectionTimeout` or something which tells you pool is full or connection was not acquired, rather than a cryptic error like this. For MySQL aleast it fails with `ResourceRequestTimeout`

```js
'use strict';

const Sequelize = require('./index');
const sequelize = require('./test/support').createSequelizeInstance({
  pool: {
    max: 1,
    acquire: 1000
  }
});

function createAndHold(timeout) {
  return sequelize.transaction(transaction => {
    return M.create({ name: 'A' }, { transaction }).then(() => {
      return Sequelize.Promise.delay(timeout);
    });
  });
}

const M = sequelize.define('M', {
  name: Sequelize.STRING
});

sequelize
  .sync({ force: true })
  .then(() => {
    return Sequelize.Promise.all([
      createAndHold(5000),
      createAndHold(100)
    ]);
  })
  .then(() => {
    return M.findAll({ raw: true });
  })
  .then(results => {
    console.log(results);
  });
```

```js
TypeError: Cannot read property 'query' of undefined
    at parameters.length.Promise (/var/www/github/sequelize/lib/dialects/postgres/query.js:65:53)
    at Query.run (/var/www/github/sequelize/lib/dialects/postgres/query.js:65:9)
    at Promise.try.then.connection (/var/www/github/sequelize/lib/sequelize.js:558:20)
From previous event:
    at retryParameters (/var/www/github/sequelize/lib/sequelize.js:555:8)
    at /var/www/github/sequelize/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/var/www/github/sequelize/node_modules/retry-as-promised/index.js:29:10)
    at Sequelize.query (/var/www/github/sequelize/lib/sequelize.js:454:12)
    at QueryInterface.rollbackTransaction (/var/www/github/sequelize/lib/query-interface.js:1449:36)
    at Transaction.rollback (/var/www/github/sequelize/lib/transaction.js:93:8)
    at connectionPromise.then.then.then.then.then.catch.setupErr (/var/www/github/sequelize/lib/transaction.js:128:31)
From previous event:
    at Transaction.prepareEnvironment (/var/www/github/sequelize/lib/transaction.js:128:13)
    at Sequelize._clsRun (/var/www/github/sequelize/lib/sequelize.js:997:26)
    at Function._clsRun (/var/www/github/sequelize/lib/sequelize.js:1042:21)
    at Sequelize.transaction (/var/www/github/sequelize/lib/sequelize.js:996:22)
    at createAndHold (/var/www/github/sequelize/sscce.js:12:20)
    at sequelize.sync.then (/var/www/github/sequelize/sscce.js:28:7)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Object.<anonymous> (/var/www/github/sequelize/sscce.js:25:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3

```

**Comment by papandreou** [comment]
@sushantdhiman, yes, @holm's fix does prevent the error in my test case.

**Comment by holm** [comment]
Just to clarify. My PR will avoid the unhandled rejection, but the underlying reason for the connection not being established will not be fixed. However that rejection cause should still be returned directly from the main transaction promise.

I think it is likely that there is no one reason for that across all the problems reported here, but it does remove the noise of the unhandled rejection. I guess for the timeout case it could be an option to catch the error from the pool and rethrow some other error. I am not sure how much that actually helps though.

**Comment by gabegorelick** [comment]
> I think application is running out of connections as defined by pool configuration thus unable to acquire new connection because all other open connections are busy right now.

@sushantdhiman In this case, does Sequelize not retry the request? How should application code deal with full connection pools?

**Comment by sushantdhiman** [comment]
> In this case, does Sequelize not retry the request? How should application code deal with full connection pools?

@gabegorelick Sorry for really late reply, but here goes

This is handled by `acquire` timeout, if application is fully utilizing pool and new connection is demanded then `node-pool` decide as maximum number of resources are being used let wait till `acquire` timeout. If any resource get released before first `Resource Timeout` is triggered that resource is allocated to next waiting client.

As you can see when pool is already full there is no need for creating new connection, pool is already at its limits. Only thing pool can do is to wait for any resource to get released.

In your application you can deal with this situation by setting `acquire` above your average transaction runtime

**Comment by gabegorelick** [comment]
Still seeing this error for other cases. I filed https://github.com/sequelize/sequelize/issues/9218 to track.

**Comment by PaulMest** [comment]
My team was getting this error, but it was due to our own misuse -- we accidentally nested a transaction inside an object.

Here's a sample:
```
sequelize.transaction(async (transaction) => {
    models.File.create(fileInfo, {transaction: {transaction}});
}
```

Note that the transaction is inside an unnecessary object. It should look like this:
```
sequelize.transaction(async (transaction) => {
    models.File.create(fileInfo, {transaction: transaction});
}
```

**Comment by marcogrcr** [comment]
For people experiencing issues in AWS Lambda, I have created a pull request that documents how to properly configure `sequelize` for Lambda. Hopefully you'll be able to see it in <https://sequelize.org/master/manual/aws-lambda.html> once it gets merged. In the meantime, please check #12642 out and provide feedback if you find any inaccuracies or space for improvement.

**Comment by Almorisson** [comment]
> ```js
> // GOOD
> sequelize.transaction(async (transaction) => {
>   models.File.create(fileInfo, {transaction: transaction});
> }
> ```

Work well for me. Thanks man.

**Comment by vatsalpatel68** [comment]
```
//Use Managed Transaction instead of Unmanaged transaction.
sequelize.transaction(async t => {})
```

**Comment by mauro-n** [comment]
after being stuck on this for 1 hour i found that i forgot to add await before sequelize.transaction() and was passing a promise bogos
