### ISSUE TITLE
hasMany association doesn't work has expected

### ISSUE THREAD

**Issue by jun-thong** [sequelize/sequelize#8114]
## What you are doing?
Trying to declare association after models are imported. But Model.hasMany() throw an exception when accessing dataValues.

```js
// models are loaded correctly
db.Topic.belongsTo(db.Channel, { foreignKey: 'channelId', targetKey: 'id' });
db.Channel.hasMany(db.Topic, { sourceKey: 'id', foreignKey: 'channelId' });
```

## What do you expect to happen?
Achieving 1:m association.

## What is actually happening?
Output :
/node_modules/sequelize/lib/model.js:3123
      return this.dataValues[key];
                            ^

TypeError: Cannot read property 'countTopics' of undefined
    at Model.get (/node_modules/sequelize/lib/model.js:3123:29)
    at Model.funcs.(anonymous function) (/node_modules/sequelize/lib/model.js:901:25)
    at Object.mixinMethods (/node_modules/sequelize/lib/associations/helpers.js:62:36)
    at HasMany.mixin (/node_modules/sequelize/lib/associations/has-many.js:151:13)
    at Function.hasMany (/node_modules/sequelize/lib/associations/mixin.js:30:17)

"countTopics" is correctly defined on Channel's model.

Thanks for any help.

Dialect: postgres
Database version: 9.6
Sequelize version: 4.4.10

**Comment by jun-thong** [comment]
hasMany seems to create a countModelname hook on the source model. In my case, this was colliding with an existing field. This isn't cleary explained in the doc.
