### ISSUE TITLE
TypeError: Cannot read property 'uuid' of undefined

### ISSUE THREAD

**Issue by axetroy** [sequelize/sequelize#8125]
## What you are doing?

```typescript
    const t1: any = await sequelize.transaction();
    try {
      const row: any = await SpendingModel.create(
        {
          uid,
          accession: '00000000-0000-0000-0000-000000000000',
          fromCurrency: 'aa',
          toCurrency: 'bb',
          fromAmount,
          toAmount,
          fee: 0,
          fromFeeAmount,
          toFeeAmount,
          bank: {},
          method: 0,
          type: 0,
          status: 0,
          note: '',
          active: true
        },
        {
          transaction: t
        }
      );

      if (!row) {
        throw new Error(`create fail.`);
      }

      const data: Spending$ = row.dataValues;
      await t1.commit();
      return <Spending$>RFC3339NanoMaper(data);
    } catch (err) {
      await t1.rollback();
      console.error(err);
      throw err;
    }
```

## What do you expect to happen?

It should be created success!

## What is actually happening?

```bash

Executing (5ee57014-bd5a-452a-a1bb-477c0f5a5675): START TRANSACTION;
Executing (5ee57014-bd5a-452a-a1bb-477c0f5a5675): ROLLBACK;

TypeError: Cannot read property 'uuid' of undefined
    at Query.run (/home/axetroy/gpm/github.com/axetroy/duomi-nodejs/node_modules/sequelize/lib/dialects/postgres/query.js:74:54)
    at retry (/home/axetroy/gpm/github.com/axetroy/duomi-nodejs/node_modules/sequelize/lib/sequelize.js:530:32)
    at /home/axetroy/gpm/github.com/axetroy/duomi-nodejs/node_modules/retry-as-promised/index.js:40:21
    at Promise._execute (/home/axetroy/gpm/github.com/axetroy/duomi-nodejs/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/home/axetroy/gpm/github.com/axetroy/duomi-nodejs/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/home/axetroy/gpm/github.com/axetroy/duomi-nodejs/node_modules/bluebird/js/release/promise.js:79:10)
    at retryAsPromised (/home/axetroy/gpm/github.com/axetroy/duomi-nodejs/node_modules/retry-as-promised/index.js:30:10)
    at Promise.try.then.connection (/home/axetroy/gpm/github.com/axetroy/duomi-nodejs/node_modules/sequelize/lib/sequelize.js:530:14)
    at tryCatcher (/home/axetroy/gpm/github.com/axetroy/duomi-nodejs/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/axetroy/gpm/github.com/axetroy/duomi-nodejs/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/axetroy/gpm/github.com/axetroy/duomi-nodejs/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/home/axetroy/gpm/github.com/axetroy/duomi-nodejs/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/home/axetroy/gpm/github.com/axetroy/duomi-nodejs/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/home/axetroy/gpm/github.com/axetroy/duomi-nodejs/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/axetroy/gpm/github.com/axetroy/duomi-nodejs/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

__Dialect:__ postgres
__Database version:__ 9.4
__Sequelize version:__ 4.4.x

**Comment by darxtrix** [comment]
If the transaction passed is `undefined` its happens like this, you are passing `undefined` transaction. The transaction variable is `t1` not `t`

**Comment by spmartin823** [comment]
Just wanted to add that this often happens to me when I forget to await the transaction. 
```
// Causes error:
const transaction = sequelize.transaction()
await db.User.findByPk(1, {transaction})

// Doesn't cause error: 
const transaction = await sequelize.transaction()
await db.User.findByPk(1, {transaction})
```

**Comment by Qarun-Qadir-Bissoondial** [comment]
@spmartin823's answer worked for me

**Comment by Taqiarzoo** [comment]
> Just wanted to add that this often happens to me when I forget to await the transaction.
> 
> ```
> // Causes error:
> const transaction = sequelize.transaction()
> await User.findByPk(1, {transaction})
> 
> // Doesn't cause error: 
> const transaction = await sequelize.transaction()
> await User.findByPk(1, {transaction})
> ```

Thank You @spmartin823
