### ISSUE TITLE
`underscored: true` is invalid

### ISSUE THREAD

**Issue by i-pale** [sequelize/sequelize#8144]
Sequelize instance is configured with：
```
module.exports={
  dialect: 'mysql', // support: mysql, mariadb, postgres, mssql
  database: 'thinkcmf',
  host: '36.110.131.133',
  port: '3306',
  username: 'root',
  password: 'Jn597912',
  define: {
    timestamps: false,
    underscored: true,
    underscoredAll:true
    
  }
}
```

**The hump name has not been converted to underscore**

**error**

```
2017-08-17 09:55:20,879 INFO 3100 [model] SELECT `id`, `userLogin`, `userPass`, `userNicename`, `userEmail`, `userUrl`, `avatar`, `sex`, `birthday`, `signature`, `lastLoginIp`, `lastLoginTime`,
 `createTime`, `userActivationKey`, `userStatus`, `score`, `userType`, `coin`, `mobile` FROM `pl_users` AS `pl_users` WHERE `pl_users`.`id` = 1; (37ms)
2017-08-17 09:55:20,901 ERROR 3100 [-/127.0.0.1/-/64ms GET /] nodejs.SequelizeDatabaseError: Unknown column 'userLogin' in 'field list'
    at Query.formatError (D:\前端\newCms1\node_modules\sequelize\lib\dialects\mysql\query.js:222:16)
    at Query.connection.query [as onResult] (D:\前端\newCms1\node_modules\sequelize\lib\dialects\mysql\query.js:55:23)
    at Query.Command.execute (D:\前端\newCms1\node_modules\mysql2\lib\commands\command.js:30:12)
    at Connection.handlePacket (D:\前端\newCms1\node_modules\mysql2\lib\connection.js:515:28)
    at PacketParser.onPacket (D:\前端\newCms1\node_modules\mysql2\lib\connection.js:94:16)
    at PacketParser.executeStart (D:\前端\newCms1\node_modules\mysql2\lib\packet_parser.js:77:14)
    at Socket.<anonymous> (D:\前端\newCms1\node_modules\mysql2\lib\connection.js:102:29)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)
From previous event:
    at Query.run (D:\前端\newCms1\node_modules\sequelize\lib\dialects\mysql\query.js:44:12)
    at retry (D:\前端\newCms1\node_modules\sequelize\lib\sequelize.js:530:32)
    at D:\前端\newCms1\node_modules\retry-as-promised\index.js:40:21
    at retryAsPromised (D:\前端\newCms1\node_modules\retry-as-promised\index.js:30:10)
    at Promise.try.then.connection (D:\前端\newCms1\node_modules\sequelize\lib\sequelize.js:530:14)
From previous event:
    at Sequelize.query (D:\前端\newCms1\node_modules\sequelize\lib\sequelize.js:527:8)
    at QueryInterface.select (D:\前端\newCms1\node_modules\sequelize\lib\query-interface.js:671:27)
    at Promise.try.then.then.then (D:\前端\newCms1\node_modules\sequelize\lib\model.js:1539:34)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at Function.findAll (D:\前端\newCms1\node_modules\sequelize\lib\model.js:1536:8)
    at Function.findOne (D:\前端\newCms1\node_modules\sequelize\lib\model.js:1692:17)
    at user.getByid (D:\前端\newCms1\app\service\user.js:11:42)
    at next (native)
    at onFulfilled (D:\前端\newCms1\node_modules\co\index.js:65:19)
    at D:\前端\newCms1\node_modules\co\index.js:54:5
    at co (D:\前端\newCms1\node_modules\co\index.js:50:10)
    at toPromise (D:\前端\newCms1\node_modules\co\index.js:118:63)
    at next (D:\前端\newCms1\node_modules\co\index.js:99:29)
    at onFulfilled (D:\前端\newCms1\node_modules\co\index.js:69:7)
    at D:\前端\newCms1\node_modules\co\index.js:54:5
    at co (D:\前端\newCms1\node_modules\co\index.js:50:10)
    at toPromise (D:\前端\newCms1\node_modules\co\index.js:118:63)
    at next (D:\前端\newCms1\node_modules\co\index.js:99:29)
    at onFulfilled (D:\前端\newCms1\node_modules\co\index.js:69:7)
    at D:\前端\newCms1\node_modules\co\index.js:54:5
    at co (D:\前端\newCms1\node_modules\co\index.js:50:10)
    at toPromise (D:\前端\newCms1\node_modules\co\index.js:118:63)
    at next (D:\前端\newCms1\node_modules\co\index.js:99:29)
    at onFulfilled (D:\前端\newCms1\node_modules\co\index.js:69:7)
    at D:\前端\newCms1\node_modules\co\index.js:54:5
    at co (D:\前端\newCms1\node_modules\co\index.js:50:10)
    at toPromise (D:\前端\newCms1\node_modules\co\index.js:118:63)
    at next (D:\前端\newCms1\node_modules\co\index.js:99:29)
    at onFulfilled (D:\前端\newCms1\node_modules\co\index.js:69:7)
name: 'SequelizeDatabaseError'
parent: { Error: Unknown column 'userLogin' in 'field list' at Packet.asError (D:\前端\newCms1\node_modules\mysql2\lib\packets\packet.js:703:13) at Query.Command.execute (D:\前端\newCms1\node_m
odules\mysql2\lib\commands\command.js:28:22) at Connection.handlePacket (D:\前端\newCms1\node_modules\mysql2\lib\connection.js:515:28) at PacketParser.onPacket (D:\前端\newCms1\node_modules\mys
ql2\lib\connection.js:94:16) at PacketParser.executeStart (D:\前端\newCms1\node_modules\mysql2\lib\packet_parser.js:77:14) at Socket.<anonymous> (D:\前端\newCms1\node_modules\mysql2\lib\connect
ion.js:102:29) at emitOne (events.js:96:13) at Socket.emit (events.js:188:7) at readableAddChunk (_stream_readable.js:177:18) at Socket.Readable.push (_stream_readable.js:135:10) at TCP.onread
sql: 'SELECT `id`, `userLogin`, `userPass`, `userNicename`, `userEmail`, `userUrl`, `avatar`, `sex`, `birthday`, `signature`, `lastLoginIp`, `lastLoginTime`, `createTime`, `userActivationKey`,
`userStatus`, `score`, `userType`, `coin`, `mobile` FROM `pl_users` AS `pl_users` WHERE `pl_users`.`id` = 1;' }
original: { Error: Unknown column 'userLogin' in 'field list' at Packet.asError (D:\前端\newCms1\node_modules\mysql2\lib\packets\packet.js:703:13) at Query.Command.execute (D:\前端\newCms1\node
_modules\mysql2\lib\commands\command.js:28:22) at Connection.handlePacket (D:\前端\newCms1\node_modules\mysql2\lib\connection.js:515:28) at PacketParser.onPacket (D:\前端\newCms1\node_modules\m
ysql2\lib\connection.js:94:16) at PacketParser.executeStart (D:\前端\newCms1\node_modules\mysql2\lib\packet_parser.js:77:14) at Socket.<anonymous> (D:\前端\newCms1\node_modules\mysql2\lib\conne
ction.js:102:29) at emitOne (events.js:96:13) at Socket.emit (events.js:188:7) at readableAddChunk (_stream_readable.js:177:18) at Socket.Readable.push (_stream_readable.js:135:10) at TCP.onrea
sql: 'SELECT `id`, `userLogin`, `userPass`, `userNicename`, `userEmail`, `userUrl`, `avatar`, `sex`, `birthday`, `signature`, `lastLoginIp`, `lastLoginTime`, `createTime`, `userActivationKey`,
`userStatus`, `score`, `userType`, `coin`, `mobile` FROM `pl_users` AS `pl_users` WHERE `pl_users`.`id` = 1;' }
sql: 'SELECT `id`, `userLogin`, `userPass`, `userNicename`, `userEmail`, `userUrl`, `avatar`, `sex`, `birthday`, `signature`, `lastLoginIp`, `lastLoginTime`, `createTime`, `userActivationKey`,
`userStatus`, `score`, `userType`, `coin`, `mobile` FROM `pl_users` AS `pl_users` WHERE `pl_users`.`id` = 1;'
```

**Comment by i-pale** [comment]
**Model is configured with**

```
const users = app.model.define('pl_users', {
    id: {
      type: sequelize.BIGINT,
      allowNull: false,
      primaryKey: true,
      autoIncrement: true
    },
    userLogin: {
      type: sequelize.STRING(60),
      allowNull: false,
      defaultValue: ''
    },
    userPass: {
      type: sequelize.STRING(64),
      allowNull: false,
      defaultValue: ''
    },
    userNicename: {
      type: sequelize.STRING(50),
      allowNull: false,
      defaultValue: ''
    },
    userEmail: {
      type: sequelize.STRING(100),
      allowNull: false,
      defaultValue: ''
    },
    userUrl: {
      type: sequelize.STRING(100),
      allowNull: false,
      defaultValue: ''
    },
    avatar: {
      type: sequelize.STRING(255),
      allowNull: true
    },
    sex: {
      type: sequelize.INTEGER(1),
      allowNull: true,
      defaultValue: '0'
    },
    birthday: {
      type: sequelize.DATE,
      allowNull: true,
      defaultValue: '2000-01-01'
    },
    signature: {
      type: sequelize.STRING(255),
      allowNull: true
    },
    lastLoginIp: {
      type: sequelize.STRING(16),
      allowNull: true
    },
    lastLoginTime: {
      type: sequelize.DATE,
      allowNull: false,
      defaultValue: '2000-01-01 00:00:00'
    },
    createTime: {
      type: sequelize.DATE,
      allowNull: false,
      defaultValue: '2000-01-01 00:00:00'
    },
    userActivationKey: {
      type: sequelize.STRING(60),
      allowNull: false,
      defaultValue: ''
    },
    userStatus: {
      type: sequelize.INTEGER(11),
      allowNull: false,
      defaultValue: '1'
    },
    score: {
      type: sequelize.INTEGER(11),
      allowNull: false,
      defaultValue: '0'
    },
    userType: {
      type: sequelize.INTEGER(1),
      allowNull: true,
      defaultValue: '1'
    },
    coin: {
      type: sequelize.INTEGER(11),
      allowNull: false,
      defaultValue: '0'
    },
    mobile: {
      type: sequelize.STRING(20),
      allowNull: false,
      defaultValue: ''
    }
  }, {
    tableName: 'pl_users'
  });
```

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/issues/6423
