### ISSUE TITLE
Development environment npm install yields "401 Unauthorized: semantic-release/error@^1.0.0"

### ISSUE THREAD

**Issue by tadman** [sequelize/sequelize#8153]
## What you are doing?

Trying to install the dependencies to test Sequelize locally.

## What do you expect to happen?

That `npm install` would successfully install the dependencies.

## What is actually happening?

When attempting this, most dependencies seem to succeed but then:

```
$ npm install
npm WARN deprecated validate-commit-msg@2.14.0: Check out CommitLint which provides the same functionality with a more user-focused experience.
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm ERR! code E401
npm ERR! 401 Unauthorized: @semantic-release/error@^1.0.0

```
```
2366 http fetch GET 401 https://registry.npmjs.org/@semantic-release%2ferror 371ms
2367 silly fetchPackageMetaData error for @semantic-release/error@^1.0.0 401 Unauthorized: @semantic-release/error@^1.0.0
2368 http fetch GET 401 https://registry.npmjs.org/@semantic-release%2fcondition-travis 417ms
2369 silly fetchPackageMetaData error for @semantic-release/condition-travis@^5.0.2 401 Unauthorized: @semantic-release/condition-travis@^5.0.2
2370 http fetch GET 401 https://registry.npmjs.org/@semantic-release%2frelease-notes-generator 420ms
2371 silly fetchPackageMetaData error for @semantic-release/release-notes-generator@^2.0.0 401 Unauthorized: @semantic-release/release-notes-generator@^2.0.0
2372 http fetch GET 401 https://registry.npmjs.org/@semantic-release%2fcommit-analyzer 425ms
2373 silly fetchPackageMetaData error for @semantic-release/commit-analyzer@^2.0.0 401 Unauthorized: @semantic-release/commit-analyzer@^2.0.0
2374 http fetch GET 401 https://registry.npmjs.org/@semantic-release%2flast-release-npm 435ms
2375 silly fetchPackageMetaData error for @semantic-release/last-release-npm@^1.2.1 401 Unauthorized: @semantic-release/last-release-npm@^1.2.1
2376 verbose stack Error: 401 Unauthorized: @semantic-release/error@^1.0.0
2376 verbose stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:41:19)
2376 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
2376 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
2376 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
2376 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
2376 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
2376 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
2376 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
2376 verbose stack     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
2376 verbose stack     at runCallback (timers.js:781:20)
2376 verbose stack     at tryOnImmediate (timers.js:743:5)
2376 verbose stack     at processImmediate [as _immediateCallback] (timers.js:714:5)

```

__Sequelize version:__ master branch
__Node.js version:__ 8.4.0

**Comment by MarcoPasqualini** [comment]
@tadman 
I have tried this today, and I had no problem with `npm install`

**Comment by tadman** [comment]
It looks like there was problems with Node 8.3.0 but upgrading to 8.4.0 resolves this.

@MarcoPasqualini Thanks for testing.
