### ISSUE TITLE
Error in 4.7.0

### ISSUE THREAD

**Issue by limingv5** [sequelize/sequelize#8173]
when I use 4.7.0, it goes wrong with the information below:
![](https://img.alicdn.com/tfs/TB1xBGrXgMPMeJjy1XcXXXpppXa-842-339.png)

version < 4.7.0 is OK, only occurs in 4.7.0

**Comment by ezze** [comment]
The same thing happens to me with 4.7.1 (`postgres` dialect) when declaring an association with `hasMany`:

    /home/ezze/Development/geobase/node_modules/sequelize/lib/associations/helpers.js:30
              model: source.sequelize.queryInterface.QueryGenerator.addSchema({
                                                    ^

    TypeError: Cannot read property 'QueryGenerator' of undefined
        at Object.addForeignKeyConstraints 
    (/home/ezze/Development/geobase/node_modules/sequelize/lib/associations/helpers.js:30:49)
        at HasMany.injectAttributes 
    (/home/ezze/Development/geobase/node_modules/sequelize/lib/associations/has-many.js:128:13)
        at Function.hasMany 
    (/home/ezze/Development/geobase/node_modules/sequelize/lib/associations/mixin.js:29:17)
        at Object.defineProperty.value (/home/ezze/Development/geobase/dist/cli.js:1505:26)
        at __webpack_require__ (/home/ezze/Development/geobase/dist/cli.js:20:30)
        at Object.<anonymous> (/home/ezze/Development/geobase/dist/cli.js:6511:1)
        at __webpack_require__ (/home/ezze/Development/geobase/dist/cli.js:20:30)
        at Object.defineProperty.value (/home/ezze/Development/geobase/dist/cli.js:6421:14)
        at __webpack_require__ (/home/ezze/Development/geobase/dist/cli.js:20:30)
        at Object.<anonymous> (/home/ezze/Development/geobase/dist/cli.js:6248:15)
        at __webpack_require__ (/home/ezze/Development/geobase/dist/cli.js:20:30)
        at Object.<anonymous> (/home/ezze/Development/geobase/dist/cli.js:6230:18)
        at __webpack_require__ (/home/ezze/Development/geobase/dist/cli.js:20:30)
        at /home/ezze/Development/geobase/dist/cli.js:63:18
        at Object.<anonymous> (/home/ezze/Development/geobase/dist/cli.js:66:10)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.runMain (module.js:604:10)
        at run (bootstrap_node.js:389:7)

**Comment by sushantdhiman** [comment]
Fixed and will be released as `4.7.2` after CI passes at https://travis-ci.org/sequelize/sequelize/builds/267672168

Let me know if its still an issue

**Comment by ezze** [comment]
@sushantdhiman, version `4.7.2` solved the issue for me. Thank you for a quick fix! :)
