### ISSUE TITLE
Error: Cannot find module 'wkx'

### ISSUE THREAD

**Issue by nstuyvesant** [sequelize/sequelize#8187]
## What you are doing?
Using an angular-fullstack project, upgraded pg-native from 2.0.1 to 2.2.0 then got errors that appear to be in sequelize. Reverting to pg-native@2.0.1 again resolved the issue but wondering if the issue is in sequelize 4.7.1 as pg-native does not use wkx.

_Output_
```
2017-08-24T12:10:40.580797+00:00 app[web.1]: Error: Cannot find module 'wkx'
2017-08-24T12:10:40.580798+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:489:15)
2017-08-24T12:10:40.580799+00:00 app[web.1]:     at Function.Module._load (module.js:439:25)
2017-08-24T12:10:40.580799+00:00 app[web.1]:     at Module.require (module.js:517:17)
2017-08-24T12:10:40.580800+00:00 app[web.1]:     at require (internal/module.js:11:18)
2017-08-24T12:10:40.580801+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/sequelize/lib/dialects/postgres/data-types.js:4:13)
2017-08-24T12:10:40.580801+00:00 app[web.1]:     at Module._compile (module.js:573:30)
2017-08-24T12:10:40.580802+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:584:10)
2017-08-24T12:10:40.580803+00:00 app[web.1]:     at Module.load (module.js:507:32)
2017-08-24T12:10:40.580803+00:00 app[web.1]:     at tryModuleLoad (module.js:470:12)
2017-08-24T12:10:40.580804+00:00 app[web.1]:     at Function.Module._load (module.js:462:3)
2017-08-24T12:10:40.580804+00:00 app[web.1]:     at Module.require (module.js:517:17)
2017-08-24T12:10:40.580805+00:00 app[web.1]:     at require (internal/module.js:11:18)
2017-08-24T12:10:40.580806+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/sequelize/lib/data-types.js:842:22)
2017-08-24T12:10:40.580807+00:00 app[web.1]:     at Module._compile (module.js:573:30)
2017-08-24T12:10:40.580807+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:584:10)
2017-08-24T12:10:40.580820+00:00 app[web.1]:     at Module.load (module.js:507:32)
```

__Dialect:__ postgres
__Database version:__ 9.6.4
__Sequelize version:__ 4.7.1
__pg version:__ 7.2.0
__pg-native version:__ 2.2.0
__node version:__ 8.4.0

**Comment by sushantdhiman** [comment]
This could mean pg-native introduced a breaking change going from 2.0.1 to 2.2.0, Can you check

**Comment by nstuyvesant** [comment]
Looks like something got corrupted on Heroku. Did a rebuild and all was ok.
