### ISSUE TITLE
findOrCreate bug on create

### ISSUE THREAD

**Issue by jeromequeyrou** [sequelize/sequelize#8197]
## What you are doing?

```js
router.post("/:listId", function(req, res, next) {
  return listAccount
    .findOrCreate({
      where: {
        username: req.body.username,
        full_name: req.body.full_name,
        network: req.body.network,
        thumb: req.body.thumb,
        network_account_id: req.body.network_account_id
      },
      defaults: {
        username: req.body.username,
        full_name: req.body.full_name,
        network: req.body.network,
        thumb: req.body.thumb,
        network_account_id: req.body.network_account_id
      }
    })
    .spread((responses, created) => {
      console.log(responses, created);
      res.json({ responses });
});
```

## What do you expect to happen?
when a new listAccount is created, i would can get the response in spread

## What is actually happening?
After the creation of listAccount .spread can't get the response and i have this Error:

```
Unhandled rejection TypeError: Cannot read property '0' of undefined
    at query.catch.then.then.queryResult (/home/janken/lists/node_modules/sequelize/lib/dialects/postgres/query.js:112:17)
    at tryCatcher (/home/janken/lists/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/janken/lists/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/janken/lists/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/janken/lists/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/janken/lists/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/janken/lists/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/janken/lists/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/janken/lists/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

__Dialect:__ postgres

__Database version:__ 9.6.3
__Sequelize version:__ 4.7.1

**Comment by sushantdhiman** [comment]
pg version ? try with latest 6, NOT 7

**Comment by jackycute** [comment]
Same here.

**Comment by jackycute** [comment]
Should take a look at https://github.com/sequelize/sequelize/issues/7998
