### ISSUE TITLE
importing a model yields undefined?

### ISSUE THREAD

**Issue by aprilmintacpineda** [sequelize/sequelize#8198]
# The problem

When I import my model (loan model) to another model (penalty model), the imported models yields `undefined`. I imported the model (loan) because I need to associate it with the other model (penalty) using `belongsTo` association. Doing this will result to an error (below) because the other model (loan) is `undefined`.

```
App threw an error during load
TypeError: Cannot read property 'prototype' of undefined
    at Function.<anonymous> (C:\Users\aprilpineda\Documents\projects\desktop\experiments\1-lendingInfoSys\node_modules\sequelize\lib\associations\mixin.js:80:16)
    at Object.<anonymous> (C:/Users/aprilpineda/Documents/projects/desktop/experiments/1-lendingInfoSys/models/penalty.js:59:14)
    at Object.<anonymous> (C:\Users\aprilpineda\Documents\projects\desktop\experiments\1-lendingInfoSys\models\penalty.js:88:3)
    at Module._compile (module.js:571:32)
    at loader (C:\Users\aprilpineda\Documents\projects\desktop\experiments\1-lendingInfoSys\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\aprilpineda\Documents\projects\desktop\experiments\1-lendingInfoSys\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:/Users/aprilpineda/Documents/projects/desktop/experiments/1-lendingInfoSys/models/loan.js:6:1)
    at Object.<anonymous> (C:\Users\aprilpineda\Documents\projects\desktop\experiments\1-lendingInfoSys\models\loan.js:116:3)
    at Module._compile (module.js:571:32)
    at loader (C:\Users\aprilpineda\Documents\projects\desktop\experiments\1-lendingInfoSys\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\aprilpineda\Documents\projects\desktop\experiments\1-lendingInfoSys\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:/Users/aprilpineda/Documents/projects/desktop/experiments/1-lendingInfoSys/models/borrower.js:4:1)
```

Now I was wondering why importing the other model (loan) yields undefined, but on when I imported it with my other model (borrower) it wasn't `undefined` and I was able to associate the borrower model to loan model using `hasMany` association.

### Loan model (loan.js; root/models/loan.js)

```
import path from 'path';
import Sequelize from 'sequelize';
import Database from '../main_process/Database';
import borrower from './borrower';
import loan_payment from './loan_payment';
import penalty from './penalty';

const DB = new Database;

let loan = DB.createModel('loan', {
  id: {
    type: Sequelize.INTEGER,
    autoIncrement: false,
    primaryKey: true
  },
  borrower_id: {
    type: Sequelize.INTEGER,
    allowNull: false
  },
  loan_date: {
    type: Sequelize.DATE,
    allowNull: false
  },
  amount: {
    type: Sequelize.BIGINT,
    allowNull: false
  },
  interest: {
    type: Sequelize.INTEGER,
    allowNull: false
  },
  interest_type: {
    type: Sequelize.STRING,
    allowNull: false
  },
  profit: {
    type: Sequelize.INTEGER,
    allowNull: false
  },
  interest_rate: {
    type: Sequelize.INTEGER,
    allowNull: false
  },
  months_to_pay: {
    type: Sequelize.INTEGER
  },
  payment_method: {
    type: Sequelize.INTEGER
  },
  per_month: {
    type: Sequelize.INTEGER,
    allowNull: false
  },
  per_semi_month: {
    type: Sequelize.INTEGER,
    allowNull: false
  },
  per_day: {
    type: Sequelize.INTEGER,
    allowNull: false
  },
  condition_applied: {
    type: Sequelize.STRING(50),
    allowNull: false
  },
  created_at: {
    type: Sequelize.DATE,
    allowNull: false
  },
  updated_at: {
    type: Sequelize.DATE,
    allowNull: false
  }
}, {
  charset: 'latin1',
  timestamps: false
});

loan.hasMany(loan_payment, {
  foreignKey: 'loan_id',
  localKey: 'id'
});

loan.hasMany(penalty, {
  foreignKey: 'loan_id',
  localKey: 'id'
});

export default loan;
```

# Example that works

I imported my loan model to my borrower model and the import was fine, it fact, I can `console.log()` the loan model and it will not yield `undefined`.

### Borrower model (borrower.js; root/models/borrower.js)

```
import path from 'path';
import Sequelize from 'sequelize';
import contactNumber from './contact_number';
import loan from './loan';
import Database from '../main_process/Database';

const DB = new Database;

let borrower = DB.createModel('borrowers', {
  id: {
    type: Sequelize.INTEGER,
    autoIncrement: false,
    primaryKey: true
  },
  firstname: {
    type: Sequelize.STRING(50),
    allowNull: false
  },
  middlename: {
    type: Sequelize.STRING(50),
    allowNull: false
  },
  surname: {
    type: Sequelize.STRING(50),
    allowNull: false
  },
  gender: {
    type: Sequelize.BOOLEAN,
    allowNull: false
  },
  created_at: {
    type: Sequelize.DATE,
    allowNull: false
  },
  updated_at: {
    type: Sequelize.DATE,
    allowNull: false
  }
}, {
  charset: 'latin1',
  timestamps: false
});

// one to many association to contact numbers
borrower.hasMany(contactNumber, {
  foreignKey: 'borrower_id',
  localKey: 'id'
});

// one to many association to loans
borrower.hasMany(loan, {
  foreignKey: 'borrower_id',
  localKey: 'id'
});

console.log(loan); // loan

export default borrower;
```

###### screenshot

The screenshot below shows that `console.log(loan)` yields **NOT** `undefined`

![image](https://user-images.githubusercontent.com/21032419/29711305-ca95a2c8-89c6-11e7-843b-004553768c68.png)

# Example that doesn't work

I imported my loan model to my penalty model then I associated my loan model to my penalty model using `belongsTo` association. This yields the error I mentioned above because the loan model is `undefined`.

### Penalty model (penalty.js; root/models/penalty.js)

```
import path from 'path';
import Sequelize from 'sequelize';
import Database from '../main_process/Database';
import loan from './loan';
import penalty_payment from './penalty_payment';

const DB = new Database;

let penaltyModel = DB.createModel('penalty', {
  id: {
    type: Sequelize.INTEGER,
    autoIncrement: false,
    primaryKey: true
  },
  loan_id: {
    type: Sequelize.INTEGER,
    allowNull: false
  },
  amount: {
    type: Sequelize.FLOAT,
    allowNull: false
  },
  remarks: {
    type: Sequelize.STRING(255),
    allowNull: false
  },
  was_waved: {
    type: Sequelize.BOOLEAN,
    allowNull: false,
    defaultValue: false
  },
  date_waved: {
    type: Sequelize.DATE,
    defaultValue: null
  },
  date_given: {
    type: Sequelize.DATE,
    allowNull: false
  },
  created_at: {
    type: Sequelize.DATE,
    allowNull: false
  },
  updated_at: {
    type: Sequelize.DATE,
    allowNull: false
  }
}, {
  charset: 'latin1',
  timestamps: false,
  tableName: 'penalties'
});

penaltyModel.hasMany(penalty_payment, {
  foreignKey: 'penalty_id',
  localKey: 'id'
});

console.log(loan); // undefined

penaltyModel.belongsTo(loan, {
  foreignKey: 'penalty_id',
  localKey: 'id'
});

export default penaltyModel;
```

###### Screenshot

The screenshot below shows that `console.log(loan)` yields `undefined`.

![image](https://user-images.githubusercontent.com/21032419/29711505-be3dd6ac-89c7-11e7-981b-e42be45954fb.png)

# Notes

I am using `sequelize@4.2.0` with `electron@1.6.11`, `react@15.6.1`, and `react-redux@5.0.5`

# PS

Thank you in advance for helping me with this issue.

**Comment by aprilmintacpineda** [comment]
# Update:

I have another model called `loan_payment`. I tried to import `loan` model on the `loan_payment` model and the same thing happened, `loan` is undefined and the same error occured.

### loan_payment model (loan_payment.js; root/models/loan_payment.js)

```
import path from 'path';
import Sequelize from 'sequelize';
import Database from '../main_process/Database';
import loan from './loan';

const DB = new Database;

let loan_payment = DB.createModel('loan_payment', {
  id: {
    type: Sequelize.INTEGER,
    autoIncrement: false,
    primaryKey: true
  },
  loan_id: {
    type: Sequelize.INTEGER,
    allowNull: false
  },
  amount: {
    type: Sequelize.INTEGER,
    allowNull: false
  },
  period_paid: {
    type: Sequelize.DATE,
    allowNull: false
  },
  payment_coverage: {
    type: Sequelize.STRING,
    allowNull: false
  },
  quarter: {
    type: Sequelize.STRING,
    defaultValue: null
  },
  date_paid: {
    type: Sequelize.DATE,
    allowNull: false
  },
  created_at: {
    type: Sequelize.DATE,
    allowNull: false
  },
  updated_at: {
    type: Sequelize.DATE,
    allowNull: false
  }
}, {
  charset: 'latin1',
  timestamps: false,
  tableName: 'loan_payments'
});

console.log(loan); // undefined

loan_payment.belongsTo(loan, {
  foreignKey: 'loan_id',
  localKey: 'id'
});

export default loan_payment;
```

I also have another model I call `penalty_payment`, I imported it on my other model called `penalty`. The same thing happened and the same error was thrown.

### penalty_payment model (penalty_payment.js; root/models/penalty_payment.js)

```
import path from 'path';
import Sequelize from 'sequelize';
import Database from '../main_process/Database';
import penalty from './penalty';

const DB = new Database;

let penalty_payment = DB.createModel('penalty_payment', {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true,
    autoIncrement: false
  },
  penalty_id: {
    type: Sequelize.INTEGER,
    allowNull: false
  },
  amount: {
    type: Sequelize.FLOAT,
    allowNull: false
  },
  date_paid: {
    type: Sequelize.DATE,
    allowNull: false
  },
  created_at: {
    type: Sequelize.DATE,
    allowNull: false
  },
  updated_at: {
    type: Sequelize.DATE,
    allowNull: false
  }
}, {
  charset: 'latin1',
  timestamps: false,
  tableName: 'penalty_payments'
});

console.log(penalty); // undefined

penalty_payment.belongsTo(penalty, {
  foreignKey: 'penalty_id',
  localKey: 'id'
});

export default penalty_payment;
```

**Comment by sushantdhiman** [comment]
I suggest you follow https://github.com/sequelize/express-example/blob/master/models/index.js Express example.

What you are facing is a classical example of cyclic reference and not an issue with Sequelize

**Comment by aprilmintacpineda** [comment]
@sushantdhiman I still don't understand why it works on some models and doesn't work on other models. Can you please further elaborate this `cyclic reference`? I have never experienced that before. Is there any other workaround because I don't want to rewrite my models

**Comment by sushantdhiman** [comment]
Cyclic Reference occurs when two module want to load each other, in such cases one module get imported as `undefined` in other module.

A few ways to handle this situtation

- Refactor, don't have module depending on each other
- Dynamic require, In some cases you just need other module in one or two specific methods, you can just do `require` for other module in that method
- Third module, have a global or third module which load all modules, then you can use it to get other modules

More help here 

- https://stackoverflow.com/questions/10869276/how-to-deal-with-cyclic-dependencies-in-node-js

I suggest refactor your code, it doesn't looks good.

Btw, all models are available under `sequelize.models` may be rather than requiring each model independently, use this reference
