### ISSUE TITLE
Support for enabling long stack traces

### ISSUE THREAD

**Issue by manast** [sequelize/sequelize#8199]
I think it would be nice to be able to activate long stack traces for debug purposes, similar to what Bluebird does: http://bluebirdjs.com/docs/api/promise.longstacktraces.html
Currently, in a complex application, getting an error like this is really not very helpful:
```
TypeError: Cannot read property 'field' of undefined
        at options.defaults.Object.keys.map.name (/Users/manuel/dev/raviteq/adrapid-backend/node_modules/sequelize/lib/model.js:2078:117)
        at Array.map (native)
        at create.then.catch.err (/Users/manuel/dev/raviteq/adrapid-backend/node_modules/sequelize/lib/model.js:2078:81)
        at tryCatcher (/Users/manuel/dev/raviteq/adrapid-backend/node_modules/bluebird/js/release/util.js:16:23)
        at /Users/manuel/dev/raviteq/adrapid-backend/node_modules/bluebird/js/release/catch_filter.js:17:41
        at tryCatcher (/Users/manuel/dev/raviteq/adrapid-backend/node_modules/bluebird/js/release/util.js:16:23)
        at Promise._settlePromiseFromHandler (/Users/manuel/dev/raviteq/adrapid-backend/node_modules/bluebird/js/release/promise.js:512:31)
        at Promise._settlePromise (/Users/manuel/dev/raviteq/adrapid-backend/node_modules/bluebird/js/release/promise.js:569:18)
        at Promise._settlePromise0 (/Users/manuel/dev/raviteq/adrapid-backend/node_modules/bluebird/js/release/promise.js:614:10)
        at Promise._settlePromises (/Users/manuel/dev/raviteq/adrapid-backend/node_modules/bluebird/js/release/promise.js:689:18)
        at Async._drainQueue (/Users/manuel/dev/raviteq/adrapid-backend/node_modules/bluebird/js/release/async.js:133:16)
        at Async._drainQueues (/Users/manuel/dev/raviteq/adrapid-backend/node_modules/bluebird/js/release/async.js:143:10)
        at Immediate.Async.drainQueues (/Users/manuel/dev/raviteq/adrapid-backend/node_modules/bluebird/js/release/async.js:17:14)
        at runCallback (timers.js:672:20)
        at tryOnImmediate (timers.js:645:5)
        at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by sushantdhiman** [comment]
follow issue template

**Comment by manast** [comment]
where is the template for feature requests?

**Comment by sushantdhiman** [comment]
Right, there is no feature request template to follow :). Need to work on Code of conduct / Contributing docs.

**Comment by sushantdhiman** [comment]
Could you propose a way to tackle this, I dont have any experience with extracting call sites or stacks.

How you propose Sequelize should extract proper stack traces (potentially removing non related stuff, like call to Promise lib etc )

**Comment by manast** [comment]
It seems like Sequelize uses bluebird as promise library. At least according to the package.json dependencies. I tried to active long stack traces in my code, before requiring the sequelize package, but unfortunately it did not work. In theory it should work since bluebird's configuration is global.
```
var Promise = require('bluebird');

Promise.config({
  longStackTraces: true
});
```

**Comment by sushantdhiman** [comment]
Sequelize use its independent instance of Bluebird. You can try this

```js
var Sequelize= require('sequelize');

Sequelize.Promise.config({
  longStackTraces: true
});
```

**Comment by manast** [comment]
oh, that worked :D. Is this documented somewhere?

**Comment by sushantdhiman** [comment]
We can explain that

- Sequelize use independent instance of Bluebird
- How to access it 

Here http://docs.sequelizejs.com/manual/installation/getting-started.html#promises 

by editing https://github.com/sequelize/sequelize/blob/master/docs/getting-started.md#promises markdown file

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/commit/28c6574da9e899be1e049a627fe637f3cac3639b

**Comment by zaggino** [comment]
@sushantdhiman latest updates to native promises seems to have removed the feature and right now, I'm getting a call stack like this:
```
SequelizeDatabaseError: invalid input syntax for integer: "[object Object]"
     at Query.formatError (D:\dev\pureprofile\auth-api\node_modules\sequelize\lib\dialects\postgres\query.js:386:16)
     at Query.run (D:\dev\pureprofile\auth-api\node_modules\sequelize\lib\dialects\postgres\query.js:87:18)
     at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
There's no indication whatsoever about my code that invoked the error query, anything I can do about this?
I'm using sequelize@6.1.0

**Comment by sushantdhiman** [comment]
This is a bug with Node.js, We are tracking this in https://github.com/sequelize/sequelize/issues/12044

**Comment by cirosantilli** [comment]
I'm on sequelize 6.5.1 node v14.17.0 and I couldn't see full traces. I tried following some of the closed links, but most threads were closed suggesting resolution. Any clues? Mini repo:

tmp.js

```
#!/usr/bin/env node

const path = require('path');

function myfunc() {
}

const { Sequelize, DataTypes } = require('sequelize');

const sequelize = new Sequelize({
  dialect: 'sqlite',
  storage: 'tmp.' + path.basename(__filename) + '.sqlite',
});

(async () => {
await sequelize.authenticate();

const IntegerNames = sequelize.define('IntegerNames', {
  value: {
    type: DataTypes.INTEGER,
    allowNull: false,
    unique: true,
  },
  name: {
    type: DataTypes.STRING,
  },
});
await IntegerNames.sync({force: true})
await IntegerNames.create({value: 5, name: 'five'});
await IntegerNames.findAll({where: {lolol: 3}})
await sequelize.close();
})();
```

outputs:

```
(node:211054) UnhandledPromiseRejectionWarning: SequelizeDatabaseError: SQLITE_ERROR: no such column: IntegerNames.lolol
    at Query.formatError (/home/ciro/bak/git/linux-kernel-module-cheat/rootfs_overlay/lkmc/nodejs/node_modules/sequelize/lib/dialects/sqlite/query.js:415:16)
    at Query._handleQueryResponse (/home/ciro/bak/git/linux-kernel-module-cheat/rootfs_overlay/lkmc/nodejs/node_modules/sequelize/lib/dialects/sqlite/query.js:72:18)
    at afterExecute (/home/ciro/bak/git/linux-kernel-module-cheat/rootfs_overlay/lkmc/nodejs/node_modules/sequelize/lib/dialects/sqlite/query.js:246:27)
    at Statement.errBack (/home/ciro/bak/git/linux-kernel-module-cheat/rootfs_overlay/lkmc/nodejs/node_modules/sqlite3/lib/sqlite3.js:14:21)
```

so no mention of `tmp.js`.

But if I use the call `await myfunc()` instead, it does show the line, not sure why. So I don't really have an amazing minimal reproduction. But in my express app I don't see the traces once again, but trace is similar and ends in `Statement.errBack`.

Tried:

```
  Sequelize.Promise.config({
    longStackTraces: true
  });
````

but `.Promise` is gone.
