### ISSUE TITLE
Through tables without ID column triggering "Unhandled rejection"

### ISSUE THREAD

**Issue by cuckoopt** [sequelize/sequelize#8200]
I have a through table with just 2 `foreignKey` which are also the `primaryKey` is giving me an error since `4.4.0`.

This is my model:
```js
const ProductAttributeValue = sequelize.define("ProductAttributeValue", {}, {
    tableName  : "catalog_product_attributevalues",
    paranoid   : false,
    timestamps : false,
});
ProductAttributeValue.associate = (models) => {
    models.Product.belongsToMany(models.AttributeValue, {
        as          : "values",
        through     : ProductAttributeValue,
        foreignKey  : "pro_id",
        primaryKey  : true,
    });
    models.AttributeValue.belongsToMany(models.Product, {
        through    : ProductAttributeValue,
        foreignKey : "atrv_id",
        primaryKey : true,
    });
};
ProductAttributeValue.removeAttribute("id");
```

And this this the output:
```bash
Unhandled rejection SequelizeDatabaseError: column ProductAttributeValue.id does not exist
    at Query.formatError (~/Repo/node_modules/sequelize/lib/dialects/postgres/query.js:350:16)
    at Result.query.on.err (~/Repo/node_modules/sequelize/lib/dialects/postgres/query.js:93:21)
    at emitOne (events.js:115:13)
    at Result.emit (events.js:210:7)
    at Result.Query.handleError (~/Repo/node_modules/pg/lib/query.js:163:8)
    at Client.<anonymous> (~/Repo/node_modules/pg/lib/client.js:188:26)
    at emitOne (events.js:115:13)
    at Connection.emit (events.js:210:7)
    at Socket.<anonymous> (~/Repo/node_modules/pg/lib/connection.js:133:12)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:585:20)
```

__Dialect:__ postgres
__Database version:__ 9.4.7
__Sequelize version:__ 4.7.5

**Comment by sushantdhiman** [comment]
I am afraid we have very thin support for tables without any single column primary key.

I suggest you to keep `id` primaryKey and just add a unique / not null constraint on other two fields

**Comment by cuckoopt** [comment]
@mickhansen @janmeier can I get an opinion from you guys?
