### ISSUE TITLE
Error thrown when trying to sync an ENUM to a postgres database

### ISSUE THREAD

**Issue by dancrumb** [sequelize/sequelize#8203]
## What you are doing?

I'm trying to sync my models to the database with the `force` property set to true and I'm getting a failure.

```js
require('dotenv').config({path: `${__dirname}/../.env`});

const Sequelize = require('sequelize');

const sequelize = new Sequelize(
  process.env.SQL_DATABASE,
  process.env.SQL_USER,
  process.env.SQL_PASS,
  {
    host: process.env.SQL_HOST,
    dialect: process.env.SQL_DIALECT,
  }
);

sequelize.define('example', {
  type: {
    type: Sequelize.ENUM('these', 'are', 'values'),
  },
});

sequelize.sync({force: true}).catch(e => {
  console.error('Hit the bug');
  console.error(e.stack);
  sequelize.close();
});
```

## What do you expect to happen?
I expect the sync to complete cleanly

## What is actually happening?
While trying to create the ENUM, I get:

```
TypeError: Cannot read property '0' of undefined
    at query.catch.then.then.queryResult (/Users/danrumney/Ohana/ohp/node_modules/sequelize/lib/dialects/postgres/query.js:112:17)
From previous event:
    at Query.run (/Users/danrumney/Ohana/ohp/node_modules/sequelize/lib/dialects/postgres/query.js:97:8)
    at retry (/Users/danrumney/Ohana/ohp/node_modules/sequelize/lib/sequelize.js:530:32)
    at /Users/danrumney/Ohana/ohp/node_modules/retry-as-promised/index.js:40:21
    at retryAsPromised (/Users/danrumney/Ohana/ohp/node_modules/retry-as-promised/index.js:30:10)
    at Promise.try.then.connection (/Users/danrumney/Ohana/ohp/node_modules/sequelize/lib/sequelize.js:530:14)
From previous event:
    at Sequelize.query (/Users/danrumney/Ohana/ohp/node_modules/sequelize/lib/sequelize.js:527:8)
    at Promise.all.then.results (/Users/danrumney/Ohana/ohp/node_modules/sequelize/lib/query-interface.js:108:44)
From previous event:
    at QueryInterface.createTable (/Users/danrumney/Ohana/ohp/node_modules/sequelize/lib/query-interface.js:99:36)
    at Promise.try.then.then (/Users/danrumney/Ohana/ohp/node_modules/sequelize/lib/model.js:1102:39)
From previous event:
    at Function.sync (/Users/danrumney/Ohana/ohp/node_modules/sequelize/lib/model.js:1102:8)
    at Promise.each.model (/Users/danrumney/Ohana/ohp/node_modules/sequelize/lib/sequelize.js:691:50)
From previous event:
    at Promise.try.then.then (/Users/danrumney/Ohana/ohp/node_modules/sequelize/lib/sequelize.js:691:22)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Sequelize.sync (/Users/danrumney/Ohana/ohp/node_modules/sequelize/lib/sequelize.js:678:8)
    at Object.<anonymous> (/Users/danrumney/Ohana/ohp/debug/sscce.js:21:11)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

__Dialect:__ postgres
__Database version:__ 9.6 (DB), 7.2.0 (pg client)
__Sequelize version:__ 4.6.0

**Comment by dancrumb** [comment]
I've actually been able to debug the failure mode here.

What happens is that sequelize creates the ENUM with the `force` property set to true, it builds a compound statement:

```sql
DROP TYPE IF EXISTS "public"."enum_examples_type"; CREATE TYPE "public"."enum_examples_type" AS ENUM('these', 'are', 'values');
```

When this is processed by the `run` method in the `dialects/postgres/query.js` file, the `queryResult` ends up being an array of results (one for each statement). However, the code treats it like a single `queryResult`. Thus, at line 112, the expression `row[0]` throws an error, because `row` is not defined on the array of results.

It's unclear what the failing change here is... I'm _guessing_ it may be a change in how the postgres client handles compound statements. They recently had a major security bug and, perhaps that's whats in play.

**Comment by dancrumb** [comment]
OK... I've confirmed that this issue is *not* present with `pg@6.4.2`, so this is probably a compatibility issue with the latest `pg` module.

**Comment by dancrumb** [comment]
So, I've been mulling this over and I see two possible approaches.

1. Don't use multiple statements in a single query. This would require a bunch of refactoring just for the enum stuff alone. In addition, I don't know if there are multiple statements passed elsewhere now and it could also happen in the future (although sensible testing could mitigate this).
2. Handle multiple statements correctly. This seems the more robust solution, but "correctly" is not well defined. For instance, what's the current behaviour? Should we propagate that? How should errors be handled and reported?

My gut says that we go with (2). I'm guessing that the behaviour right now is that the results from all but the final statement are effectively thrown away. I'd suggest that we default to that and allow callers to 'request' that they get all the results via some option parameter.

What do you think?

**Comment by dancrumb** [comment]
Closing as duplicate of #7998
