### ISSUE TITLE
Sequelize does not support Windows token for local auth?

### ISSUE THREAD

**Issue by georgeedwards** [sequelize/sequelize#8229]
## What you are doing?
I am trying to connect to a local SQl Server (2016) instance locally using SSPI / Windows Auth.

```js
export var sequelize = new Sequelize({     dialect: 'mssql',     dialectModulePath: 'sequelize-msnodesqlv8',     dialectOptions: {       connectionString: 'Server=localhost\MSSQLSERVER01;Database=DB-demo; Integrated Security=SSPI;'     },   });
```

## What do you expect to happen?
Connection to succeed like it does with SQL Auth, or like SSMS can connect.

## What is actually happening?

> Unhandled rejection SequelizeConnectionError: [Microsoft][SQL Server Native Client 11.0][SQL Server]Login failed for user ''.
    at Connection.<anonymous> (C:\Users\George\Source\Repos\Demo-Proj\node_modules\sequelize\lib\dialects\mssql\connection-manager.js:109:16)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at mssql.open (C:\Users\George\Source\Repos\Demo-Proj\node_modules\sequelize-msnodesqlv8\lib\connection.js:107:9)
    at Immediate.<anonymous> (C:\Users\George\Source\Repos\Demo-Proj\node_modules\msnodesqlv8\lib\ConnectionWrapper.js:336:11)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

No User token seems to be being passed? See [StackOverflow](https://stackoverflow.com/questions/45940406/logging-into-local-sql-server-instance-with-windows-auth) for the full troubleshooting process.

__Dialect:__ mssql
__Database version:__ 13.0.4001 SP1
__Sequelize version:__ 3.30.3

**Comment by georgeedwards** [comment]
NB: this also happens with the `tedious` driver as well as the `sequelize-msnodesqlv8` one.
