### ISSUE TITLE
Model sync generates broken statement

### ISSUE THREAD

**Issue by axelrindle** [sequelize/sequelize#8231]
## What you are doing?
I define my `User` model like this:

```js
// connect to the database
var sequelize = new Sequelize("mysql://user:pass@localhost:3306/mydatabase")

// define the schema
var UserSchema = {
  username: {
    type: Sequelize.STRING,
    unique: true,
    primaryKey: true
  },
  password: Sequelize.STRING,
  realName: {
    type: Sequelize.STRING,
    defaultValue: ""
  },
  group: {
    type: Sequelize.STRING,
    defaultValue: "User"
  }
}

// define the model
var User = sequelize.define('User', UserSchema)

// sync the model to the database
await User.sync()
```

## What do you expect to happen?
The database table is created properly.

## What is actually happening?
I receive the following error:

```
Executing (default): CREATE TABLE IF NOT EXISTS `Users` (`username` VARCHAR(255) UNIQUE , `password` VARCHAR(255), `realName` VARCHAR(255) DEFAULT '', `group` VARCHAR(255) DEFAULT '
User', `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `size` [object Object], UNIQUE `Users_username_unique` (`username`), PRIMARY KEY (`username`)) ENGINE=InnoDB;
[CRITICAL] 18:27:12 > SequelizeDatabaseError: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '
[object Object], UNIQUE `Users_username_unique` (`username`), PRIMARY KEY (`user' at line 1
SequelizeDatabaseError: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[object Object], UNIQU
E `Users_username_unique` (`username`), PRIMARY KEY (`user' at line 1
    at Query.formatError (/home/axel/Projekte/coffeedesk/node_modules/sequelize/lib/dialects/mysql/query.js:222:16)
    at Query.connection.query [as onResult] (/home/axel/Projekte/coffeedesk/node_modules/sequelize/lib/dialects/mysql/query.js:55:23)
    at Query.Command.execute (/home/axel/Projekte/coffeedesk/node_modules/mysql2/lib/commands/command.js:30:12)
    at Connection.handlePacket (/home/axel/Projekte/coffeedesk/node_modules/mysql2/lib/connection.js:515:28)
    at PacketParser.onPacket (/home/axel/Projekte/coffeedesk/node_modules/mysql2/lib/connection.js:94:16)
    at PacketParser.executeStart (/home/axel/Projekte/coffeedesk/node_modules/mysql2/lib/packet_parser.js:77:14)

    at Socket.<anonymous> (/home/axel/Projekte/coffeedesk/node_modules/mysql2/lib/connection.js:102:29)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:585:20)
```

The problem is the ` 'size' [object Object]` statement part. Why is there an object in the statement?

----

__Dialect:__ mysql
__Database version:__ 5.7.19-0ubuntu0.16.04.1 - (Ubuntu)
__Sequelize version:__ 4.7.5

**Comment by axelrindle** [comment]
Fixed it by adding the following to the schema:

```javascript
size: Sequelize.INTEGER
```
