### ISSUE TITLE
what's resolved way?

### ISSUE THREAD

**Issue by Robert-lihouyi** [sequelize/sequelize#8251]
## What you are doing?

```js
// code here
Unhandled rejection SequelizeDatabaseError: read ETIMEDOUT
    at Query.formatError (/Users/lihouyi/WebstormProjects/Credit-Project/Node-Rest/node_modules/sequelize/lib/dialects/mysql/query.js:222:16)
    at Query.connection.query [as onResult] (/Users/lihouyi/WebstormProjects/Credit-Project/Node-Rest/node_modules/sequelize/lib/dialects/mysql/query.js:55:23)
    at Connection._notifyError (/Users/lihouyi/WebstormProjects/Credit-Project/Node-Rest/node_modules/mysql2/lib/connection.js:218:25)
    at Connection._handleFatalError (/Users/lihouyi/WebstormProjects/Credit-Project/Node-Rest/node_modules/mysql2/lib/connection.js:178:14)
    at Connection._handleNetworkError (/Users/lihouyi/WebstormProjects/Credit-Project/Node-Rest/node_modules/mysql2/lib/connection.js:183:8)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:62:8)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickDomainCallback (internal/process/next_tick.js:198:9)
From previous event:
    at Query.run (/Users/lihouyi/WebstormProjects/Credit-Project/Node-Rest/node_modules/sequelize/lib/dialects/mysql/query.js:44:12)
    at retry (/Users/lihouyi/WebstormProjects/Credit-Project/Node-Rest/node_modules/sequelize/lib/sequelize.js:532:32)
    at /Users/lihouyi/WebstormProjects/Credit-Project/Node-Rest/node_modules/retry-as-promised/index.js:40:21
    at retryAsPromised (/Users/lihouyi/WebstormProjects/Credit-Project/Node-Rest/node_modules/retry-as-promised/index.js:30:10)
    at Promise.try.then.connection (/Users/lihouyi/WebstormProjects/Credit-Project/Node-Rest/node_modules/sequelize/lib/sequelize.js:532:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:

```

## What do you expect to happen?
_I wanted Foo!_

## What is actually happening?
_But the output was bar!_

_Output, either JSON or SQL_

__Dialect:__ mysql / postgres / sqlite / mssql / any
__Database version:__ XXX
__Sequelize version:__ XXX

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/issues/7884
