### ISSUE TITLE
Sequelize4 throw ValidationError even with catch

### ISSUE THREAD

**Issue by blanchma** [sequelize/sequelize#8256]
```
const User = sequelize.define('User', {
    password: { type: DataTypes.STRING, allowNull: false,
                validate: {
                            len: { args: [ 8, Infinity ], msg: "Password must be at least 8 characters." },
                            not: { args: [/\s+/ig], msg: "Password must not have blank spaces." }
                          }
              }
```

```
     currentUser.updateAttributes({password: attributes.new_password})
          .then( () => {
            return res.renderJson( { password: 'Password Updated' }, 200);
          }).catch(error => {
            let errorMessage = { error: Utils.formatError(error) };
            return res.renderJson(errorMessage, 422);
          });
```
Running in Node6, Postgres7 and Sequelize 4.7.3.

The catch works collecting the error but in the console I can still see:

```

Unhandled rejection SequelizeValidationError: Validation error: Password must be at least 8 characters.
    at Promise.all.then (/Users/blanchma/workspace/backend/node_modules/sequelize/lib/instance-validator.js:77:15)
    at tryCatcher (/Users/blanchma/workspace/backend/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/blanchma/workspace/backend/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/blanchma/workspace/backend/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/blanchma/workspace/backend/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/blanchma/workspace/backend/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/blanchma/workspace/backend/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/Users/blanchma/workspace/backend/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/Users/blanchma/workspace/backend/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/Users/blanchma/workspace/backend/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/Users/blanchma/workspace/backend/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/blanchma/workspace/backend/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/blanchma/workspace/backend/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/blanchma/workspace/backend/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/blanchma/workspace/backend/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by tomergev** [comment]
This is 100% still an issue!

**Comment by tomergev** [comment]
Hee's my code from the user's model
`
module.exports = function (sequelize, DataTypes) {
	const { models } = sequelize

	const user = sequelize.define('user', {
		first_name: {
			type: DataTypes.STRING,
			validate: {
				is: ["^[a-z]+$", 'i'] // only allows letters
			}
		},
		last_name: {
			type: DataTypes.STRING,
			validate: {
				is: ["^[a-z]+$", 'i'] // only allows letters
			}
		},
		phone: {
			type: DataTypes.STRING,
			unique: true
		},
		email: {
			type: DataTypes.STRING,
			validate: {
				isEmail: true
			}
		},
		languages_spoken: {
			// If sync({force:true}), then I cannot use an ENUM. If force is set to false, then I can use an enum
			type: DataTypes.ARRAY(DataTypes.STRING),
			defaultValue: ['en']
		},
		country: {
			type: DataTypes.STRING,
			defaultValue: 'United States of America'
		},
		country_code: {
			type: DataTypes.STRING
		},
		passcode: {
			type: DataTypes.STRING
		},
		passcode_expiration: {
			type: DataTypes.DATE
		},
		verified: {
			type: DataTypes.BOOLEAN,
			defaultValue: false
		},
		profile_picture_string: {
			type: DataTypes.STRING
		},
		avatar: {
			type: new DataTypes.VIRTUAL(DataTypes.STRING, ['profile_picture_string']),
			get: function () {
				if (this.get('profile_picture_string')) {
					return `${env.AWS_PREFIX}${this.get('profile_picture_string')}`
				} else {
					return null
				}
			}
		},
		position: {
			type: DataTypes.GEOMETRY('POINT'),
			defaultValue: null
		},
		facebook_token: {
			type: DataTypes.STRING
		},
		socket_id: {
			type: DataTypes.STRING
		},
		stripe_customer_id: {
			type: DataTypes.STRING
		},
		stripe_customer: {
			type: DataTypes.JSON
		},
		stripe_connect_account_id: {
			type: DataTypes.STRING
		},
		ephemeral_key: {
			type: DataTypes.JSON
		},
		read_receipt: {
			type: DataTypes.BOOLEAN,
			defaultValue: false
		},
		translation_services: {
			type: DataTypes.BOOLEAN,
			defaultValue: true
		}
	},
		{
			validate: {
				notACelebrityName() {
					const fullName = `${this.first_name}${this.last_name}`
						.toLowerCase()
						.trim()

					if (celebHashMap[fullName])
						throw new Error(`The name ${this.first_name} ${this.last_name} is a celebrity's name and cannot be a user's name unless approved by 8`)
				}
			},

			scopes: {
				verified: {
					where: {
						verified: true
					}
				},
				unverified: {
					where: {
						verified: false
					}
				}
			},

		},
		{
			paranoid: true
		},
	)
`

**Comment by tomergev** [comment]
Here's my code from the user's controller:
`
editUser: async (req, res) => {
		const { userId } = req.params
		let { mediaId, languages_spoken } = req.body
		let update = {}
		let media

		if (languages_spoken) languages_spoken = languages_spoken.toLowerCase()

		switch (languages_spoken) {
			case 'arabic':
				languages_spoken = 'ar'
				break
			case 'english':
				languages_spoken = 'en'
				break
			case 'spanish':
				languages_spoken = 'es'
				break
			case 'portuguese':
				languages_spoken = 'pt'
				break
			case 'french':
				languages_spoken = 'fr'
				break
		}

		User.findById(userId)
			.then(async user => {
				if (!user)
					return res.status(400).send({ message: `User ${userId} does not exist` })

				if (languages_spoken && user.languages_spoken[0] != languages_spoken) {
					update.languages_spoken = [languages_spoken]

					const query = {
						where: {
							participantsId: { $contains: [+userId] }
						}
					}
					const rooms = await Room.findAll(query)

					if (rooms.length > 0) {
						const roomIds = rooms.map(room => room.id)

						const queryOldSubRooms = {
							where: {
								room_id: { $in: roomIds },
								participantsId: { $contains: [+userId] }
							}
						}
						let queryNewSubRooms = {
							where: {
								room_id: { $in: roomIds },
								language: [languages_spoken]
							}
						}

						const oldSubRooms = await models.subRoom.findAll(queryOldSubRooms)
						const newSubRooms = await models.subRoom.findAll(queryNewSubRooms)

						const checkSubRoomUpdate = await roomLogic.updateSubRooms(userId, oldSubRooms, newSubRooms)
						if (!checkSubRoomUpdate)
							return res.status(400).send({ message: `There was an issue with updating the subRooms user ${userId} was a part of. Contact Tomer` })
					}
				}



				if (mediaId) {
					media = await models.media.findById(mediaId)
					update.profile_picture_string = media.media_file_string
				}

				const options = ['first_name', 'last_name', 'phone', 'country_code', 'email', 'country', 'translation_services']
				options.forEach(el => { req.body[el] ? update[el] = req.body[el] : '' })

				return user.update(update)
			})
			.then(user => {
				res.json({ success: true, user })
			})
			.catch(err => {
				req.errorHandler(err, res)
			})
	},
`

**Comment by tomergev** [comment]
I catch the error, but I still get this error message: Unhandled rejection SequelizeValidationError: Validation error: The name Taylor Swift is a celebrity's name and cannot be a user's name unless approved by 8
    at Promise.all.then (c:\PhD-Labs\eight-8\node_modules\sequelize\lib\instance-validator.js:77:15)
    at tryCatcher (c:\PhD-Labs\eight-8\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (c:\PhD-Labs\eight-8\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (c:\PhD-Labs\eight-8\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (c:\PhD-Labs\eight-8\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (c:\PhD-Labs\eight-8\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (c:\PhD-Labs\eight-8\node_modules\bluebird\js\release\promise.js:638:18)
    at PromiseArray._resolve (c:\PhD-Labs\eight-8\node_modules\bluebird\js\release\promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (c:\PhD-Labs\eight-8\node_modules\bluebird\js\release\promise_array.js:144:14)

**Comment by sabina-a3logics** [comment]
Hi @tomergev ,
I'm facing the same issue did you get any solution for it. If yes please help me for the same.

**Comment by bachstatter** [comment]
This is very weird. Same thing happening to me!

**Comment by Aukhan** [comment]
I don't think this is an unhandled error as everyone is saying that the catch works but they still see the error stack logged to the console

**Comment by bachstatter** [comment]
> I don't think this is an unhandled error as everyone is saying that the catch works but they still see the error stack logged to the 

I ended up in an `unhandled-rejection` listener, so it's not just a log

**Comment by Aukhan** [comment]
@bachstatter @blanchma @tomergev here's a test repo trying to reproduce the issue with no luck
[sequelize-8256](https://github.com/Aukhan/sequelize-8256)
let's first start with reproducing the issue here so we can get to the bottom of whats happening
it's on a postgres-9 image though and latest sequelize, feel free to play with the versioning if that helps reproducing the issue. Thanks

**Comment by 5amfung** [comment]
I'm seeing the same issue.  I have the `catch` but it doesn't really catch the error and I'm seeing the exact same error `SequelizeValidationError: notNull Violation:...`

**Comment by acidos** [comment]
I have the same problem.

```
registerUser: async (_, args, { User }) => {

    try {
        const user = await User.register(args.username, args.email, args.password, uuidv4());
            if(user) {
                     ...					
                     return user;
	     } else {
		     return { message: 'unknown_registration_error_1' };
	     }
	 } catch (e) {
		 console.log(e);
	 }
 }
```

This catches error with promise exception:

```
{ SequelizeValidationError: Validation error: min_max_password
    at Promise.all.then (/Doza/node_modules/sequelize/lib/instance-validator.js:74:15)
    at tryCatcher (/Doza/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Doza/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Doza/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Doza/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Doza/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Doza/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/Doza/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/Doza/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/Doza/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/Doza/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Doza/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Doza/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Doza/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Doza/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)
  name: 'SequelizeValidationError',
  errors:
   [ ValidationErrorItem {
       message: 'min_max_password',
       type: 'Validation error',
       path: 'password',
       value: 'ah',
       origin: 'FUNCTION',
       instance: [User],
       validatorKey: 'len',
       validatorName: 'len',
       validatorArgs: [Array],
       original: [Error] } ] }
[ 'min_max_password' ]
```

version 5.2.12

**Comment by acidos** [comment]
@sushantdhiman 
`JSON.stringify` is successfully swallowing Promise exception. Try `console.log`. Alternatively, exception is caused when using console.log.

**Comment by sassanh** [comment]
For everyone reaches here, I think this issue happens when you incorrectly overload a sequelize function in your model, for example if you're inheriting `Car` from `sequelize.Model` and you're overloading `create` method, your create method may look like this:

```typescript
class Car extends Model {
    public static create(
        this: { new (): M } & typeof Model,
        values?: object,
        options?: CreateOptions,
    ): Bluebird<M> {
        const create = super.create.bind(this);
        return new Bluebird<M>(async (
            resolve: (instance: Bluebird<M>) => void,
        ): Promise<void> => {
            create(...);
            resolve();
        });
    }
}
```

It's ignoring any exception that happens in `create(...);` the correct form would be:

```typescript
class Car extends Model {
    public static create(
        this: { new (): M } & typeof Model,
        values?: object,
        options?: CreateOptions,
    ): Bluebird<M> {
        const create = super.create.bind(this);
        return new Bluebird<M>(async (
            resolve: (instance: Bluebird<M>) => void,
            reject: (error: Error) => void,
        ): Promise<void> => {
            try {
                create(...);
                resolve();
            }
            catch(exception) {
                reject(exception);
            }
        });
    }
}
```
