### ISSUE TITLE
SequelizeForeignKeyConstraintError when bulk creating

### ISSUE THREAD

**Issue by tiagomsmagalhaes** [sequelize/sequelize#8268]
## What you are doing?

I'm setting up a demo database where I sync the model and insert some data. We need to have two models with where ModelA.hasMany(ModelB). I create 1 instance on ModelA and bulkCreate 3 results on ModelB.

To overcome this I have to use create.

```js

// Model Definition


"use strict";

var fs = require("fs");
var path = require("path");
var Sequelize = require("sequelize");
var env = process.env.NODE_ENV || "development";
var config = require(path.join(__dirname, '..', 'config', 'config.json'))[env];
var sequelize = new Sequelize(config.database, config.username, config.password, config);


var models = [
  'Metafruit',
  'Fruits',
]


models.forEach((model) => {
  module.exports[model] = sequelize.import([__dirname, '/', model].join(''))
});

(function(m) {
  m.Metafruit.hasMany(m.Fruit, {foreignKey: 'meta_fruit_id'});

}(module.exports));

module.exports.sequelize = sequelize;
module.exports.Sequelize = Sequelize;



//syncronize
models.sequelize.sync()
.then(() => {
  async.waterfall([
    function (callback) {
      models.Metafruit.create({
        name: 'Berries',
      })
      return callback(null)
    },
    function (callback) {
      models.Fruit.bulkCreate([
        {designation: 'Strawberries', meta_fruit_id: 1},
        {designation: 'Raspberries', meta_fruit_id: 1},
        {designation: 'Blueberries',  meta_fruit_id: 1},
        {designation: 'Cranberries', meta_fruit_id: 1}
      ])
      return callback(null)
    },
  ], (err, result) => {
    console.log(err);
  })

})
```

## What do you expect to happen?
MetaFruits

id | name
------------ | -------------
1 | Berries

Fruits

id | designation | meta_fruit_id
------------ | ------------- | -------------
1 | Strawberries | 1
2 | Raspberries | 1
3 | Blueberries | 1
4 | Cranberries | 1

## What is actually happening?

I only have meta_fruit
```
Unhandled rejection SequelizeForeignKeyConstraintError: Cannot add or update a child row: a foreign key constraint fails (`fruit_orm`.`fruits`, CONSTRAINT `Fruits_ibfk_1` FOREIGN KEY (`meta_fruit_id`) REFERENCES `meta_fruits` (`id`) ON DELETE SET NULL ON UPDATE CASCADE)
    at Query.formatError (/Users/tiago/Development/fruit-app/node_modules/sequelize/lib/dialects/mysql/query.js:215:16)
    at Query.connection.query [as onResult] (/Users/tiago/Development/fruit-app/node_modules/sequelize/lib/dialects/mysql/query.js:55:23)
    at Query.Command.execute (/Users/tiago/Development/fruit-app/node_modules/mysql2/lib/commands/command.js:30:12)
    at Connection.handlePacket (/Users/tiago/Development/fruit-app/node_modules/mysql2/lib/connection.js:515:28)
    at PacketParser.onPacket (/Users/tiago/Development/fruit-app/node_modules/mysql2/lib/connection.js:94:16)
    at PacketParser.executeStart (/Users/tiago/Development/fruit-app/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.<anonymous> (/Users/tiago/Development/fruit-app/node_modules/mysql2/lib/connection.js:102:29)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:585:20)
From previous event:
    at Query.run (/Users/tiago/Development/fruit-app/node_modules/sequelize/lib/dialects/mysql/query.js:44:12)
    at retry (/Users/tiago/Development/fruit-app/node_modules/sequelize/lib/sequelize.js:532:32)
    at /Users/tiago/Development/fruit-app/node_modules/retry-as-promised/index.js:40:21
    at retryAsPromised (/Users/tiago/Development/fruit-app/node_modules/retry-as-promised/index.js:30:10)
    at Promise.try.then.connection (/Users/tiago/Development/fruit-app/node_modules/sequelize/lib/sequelize.js:532:14)
From previous event:
    at Sequelize.query (/Users/tiago/Development/fruit-app/node_modules/sequelize/lib/sequelize.js:529:8)
    at QueryInterface.bulkInsert (/Users/tiago/Development/fruit-app/node_modules/sequelize/lib/query-interface.js:591:27)
    at Promise.try.then.then (/Users/tiago/Development/fruit-app/node_modules/sequelize/lib/model.js:2355:36)
From previous event:
    at Function.bulkCreate (/Users/tiago/Development/fruit-app/node_modules/sequelize/lib/model.js:2311:8)
    at /Users/tiago/Development/fruit-app/dist/server.js:63:17
    at nextTask (/Users/tiago/Development/fruit-app/node_modules/async/dist/async.js:5297:14)
    at next (/Users/tiago/Development/fruit-app/node_modules/async/dist/async.js:5304:9)
    at /Users/tiago/Development/fruit-app/node_modules/async/dist/async.js:906:16
    at async.waterfall.models.Fruit.bulkCreate.designation (/Users/tiago/Development/fruit-app/dist/server.js:61:12)
    at nextTask (/Users/tiago/Development/fruit-app/node_modules/async/dist/async.js:5297:14)
    at next (/Users/tiago/Development/fruit-app/node_modules/async/dist/async.js:5304:9)
    at /Users/tiago/Development/fruit-app/node_modules/async/dist/async.js:906:16
    at async.waterfall.models.User.create.first_name (/Users/tiago/Development/fruit-app/dist/server.js:52:12)
    at nextTask (/Users/tiago/Development/fruit-app/node_modules/async/dist/async.js:5297:14)
    at Object.waterfall (/Users/tiago/Development/fruit-app/node_modules/async/dist/async.js:5307:5)
    at /Users/tiago/Development/fruit-app/dist/server.js:40:9
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at Object.<anonymous> (/Users/tiago/Development/fruit-app/dist/server.js:39:25)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
```

_Output, either JSON or SQL_

__Dialect:__ mysql
__Database version:__ 5.7.19
__Sequelize version:__ 4.8

**Comment by semy** [comment]
same for me

**Comment by sushantdhiman** [comment]
```js
models.sequelize.sync()
.then(() => {
  async.waterfall([
    function (callback) {
      models.Metafruit.create({
        name: 'Berries',
      })
      return callback(null)
    },
    function (callback) {
      models.Fruit.bulkCreate([
        {designation: 'Strawberries', meta_fruit_id: 1},
        {designation: 'Raspberries', meta_fruit_id: 1},
        {designation: 'Blueberries',  meta_fruit_id: 1},
        {designation: 'Cranberries', meta_fruit_id: 1}
      ])
      return callback(null)
    },
  ], (err, result) => {
    console.log(err);
  })
})
```

This is incorrect `models.Metafruit.create` returns a Promise, you are calling callback without waiting for promise to resolve.

By the time you are creating records with `Fruit.bulkCreate` , `models.Metafruit.create` is not finished.

This is also evident as Foreign key constraint is broken, which clearly indicate `meta_fruit_id: 1` (fruit with id 1) doesn't exist yet.

Try something like this

```js
 models.Metafruit.create({
   name: 'Berries',
}).then(() => callback(null))
```

**Comment by rvyasedh** [comment]
I am bulk inserting and I may have ForeignKey violations. I want a way to ignore the insertion of failed records and insert the good ones. Any way to do this with bulkCreate?
