### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by wildtang** [sequelize/sequelize#8276]
I am using TypeScript 2.4 and SQLite to develop a node app, today I want to use sequelize,
but I got error, below is my TypeScript code. Please help me, thanks.

```js  
  const Sequelize = require('sequelize');

    export async function testItOne(dbPath:string, forceUpdate:boolean=false) {
        let sqlidb = new Sequelize('sqlite:', {
            storage: dbPath // SQLite only
        });

    await sqlidb
        .authenticate()
        .then(() => {
            console.log('Connection has been established successfully.');
        })
        .catch(err => {
            console.error('Unable to connect to the database:', err);
        });

    let Phylum = sqlidb.define(
        'phylum',
        {
            phylumCn : Sequelize.STRING,
            phylumLt : Sequelize.STRING,
            pinyin   : Sequelize.STRING,
            origin   : Sequelize.TEXT
        });

    Phylum.findAll().then(phylums => {
        console.log(phylums)
    })
    }
```

the exception is below:
```
    Debugger listening on [::]:65353
    Executing (default): SELECT 1+1 AS result
    Connection has been established successfully.
    Unhandled rejection TypeError: Cannot read property 'indexOf' of undefined
        at attributes.map.attr (/mycode/node_modules/_sequelize@4.8.2@sequelize/lib/dialects/abstract/query-generator.js:1222:27)
        at Array.map (native)
        at Object.escapeAttributes (/mycode/node_modules/_sequelize@4.8.2@sequelize/lib/dialects/abstract/query-generator.js:1207:37)
        at Object.selectQuery (/mycode/node_modules/_sequelize@4.8.2@sequelize/lib/dialects/abstract/query-generator.js:979:28)
        at QueryInterface.select (/mycode/node_modules/_sequelize@4.8.2@sequelize/lib/query-interface.js:672:27)
        at Promise.try.then.then.then (/mycode/node_modules/_sequelize@4.8.2@sequelize/lib/model.js:1540:34)
        at tryCatcher (/mycode/node_modules/_bluebird@3.5.0@bluebird/js/release/util.js:16:23)
        at Promise._settlePromiseFromHandler (/mycode/node_modules/_bluebird@3.5.0@bluebird/js/release/promise.js:512:31)
        at Promise._settlePromise (/mycode/node_modules/_bluebird@3.5.0@bluebird/js/release/promise.js:569:18)
        at Promise._settlePromise0 (/mycode/node_modules/_bluebird@3.5.0@bluebird/js/release/promise.js:614:10)
        at Promise._settlePromises (/mycode/node_modules/_bluebird@3.5.0@bluebird/js/release/promise.js:693:18)
        at Async._drainQueue (/mycode/node_modules/_bluebird@3.5.0@bluebird/js/release/async.js:133:16)
        at Async._drainQueues (/mycode/node_modules/_bluebird@3.5.0@bluebird/js/release/async.js:143:10)
        at Immediate.Async.drainQueues (/mycode/node_modules/_bluebird@3.5.0@bluebird/js/release/async.js:17:14)
        at runCallback (timers.js:672:20)
        at tryOnImmediate (timers.js:645:5)
        at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by alexanderjsx** [comment]
I'm having the same issue. FindAll/findOne throws this error, however create work as expected.

**Comment by powderham** [comment]
I am having the same issue with FindAll. Did you find a solution @alexanderjsx ?

**Comment by alexanderjsx** [comment]
Yes, I found the issue. In my case models were amended by a library that I used. Check that your models are the same at the point of creation and at the point of use. It might be that some code uses and amend the models in between (like in my case).

**Comment by powderham** [comment]
Thanks.
