### ISSUE TITLE
{createdAt: new Date()} in Model.findOrCreate() throws a Moment.js deprecation warning

### ISSUE THREAD

**Issue by manuel-di-iorio** [sequelize/sequelize#8277]
```js
sequelize.transaction((t) => {
    const query = {
        createdAt: {
            $gt: new Date(new Date() - 24 * 60 * 60 * 1000)
        }
    };

    const values = {
        createdAt: new Date()
    };

    return Model.findOrCreate({ where: query, defaults: values, transaction: t })
})

/**
Deprecation warning: value provided is not in a recognized ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments:
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: Fri Sep 08 2017 19:10:22 GMT+0200 (ora legale Europa occidentale), _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (c:\Users\PC\Desktop\project\node_modules\moment\moment.js:318:94)
    at configFromString (c:\Users\PC\Desktop\project\node_modules\moment\moment.js:2080:15)
    at configFromInput (c:\Users\PC\Desktop\project\node_modules\moment\moment.js:2444:9)
    at prepareConfig (c:\Users\PC\Desktop\project\node_modules\moment\moment.js:2427:9)
    at createFromConfig (c:\Users\PC\Desktop\project\node_modules\moment\moment.js:2394:40)
    at createLocalOrUTC (c:\Users\PC\Desktop\project\node_modules\moment\moment.js:2481:12)
    at createLocal (c:\Users\PC\Desktop\project\node_modules\moment\moment.js:2485:12)
    at hooks (c:\Users\PC\Desktop\project\node_modules\moment\moment.js:16:25)
    at ABSTRACT._applyTimezone (c:\Users\PC\Desktop\project\node_modules\sequelize\lib\data-types.js:323:14)
    at DATE._stringify (c:\Users\PC\Desktop\project\node_modules\sequelize\lib\dialects\mysql\data-types.js:76:37)
    at DATE.stringify (c:\Users\PC\Desktop\project\node_modules\sequelize\lib\data-types.js:32:17)
    at Object.escape (c:\Users\PC\Desktop\project\node_modules\sequelize\lib\dialects\abstract\query-generator.js:906:32)
    at Object.whereItemQuery (c:\Users\PC\Desktop\project\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2306:22)
    at _.forOwn (c:\Users\PC\Desktop\project\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1937:25)
    at c:\Users\PC\Desktop\project\node_modules\lodash\lodash.js:4944:15
    at baseForOwn (c:\Users\PC\Desktop\project\node_modules\lodash\lodash.js:3001:24)
    at Function.forOwn (c:\Users\PC\Desktop\project\node_modules\lodash\lodash.js:13002:24)
    at Object.whereItemsQuery (c:\Users\PC\Desktop\project\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1936:9)
    at Object.getWhereConditions (c:\Users\PC\Desktop\project\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2377:19)
    at Object.selectQuery (c:\Users\PC\Desktop\project\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1123:28)
    at QueryInterface.select (c:\Users\PC\Desktop\project\node_modules\sequelize\lib\query-interface.js:672:27)
    at Promise.try.then.then.then (c:\Users\PC\Desktop\project\node_modules\sequelize\lib\model.js:1540:34) 
*/
```

## What do you expect to happen?
Should not throw a warning when using `{createdAt: new Date()}`
PS: I tried even with `new Date().toISOString()`, same warning

## What is actually happening?
A deprecation warning raises, even if the query still works

__Dialect:__ mysql
__Database version:__ 5.7
__Sequelize version:__ 4.8.2

**Comment by perrosnk** [comment]
Any updates on this?

**Comment by atulmy** [comment]
Facing same issue when displaying date using:`moment(item.createdAt).format('dddd, MMMM Do YYYY')`

Warning: `Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date()...`

**Comment by perrosnk** [comment]
It's still a problem

**Comment by Silviu-Marian** [comment]
still a problem
sqlite on date columns

```js
const reports = await Reports.findAll({
    where: {
      released: { lte: userDetails.currentDate },
    },
  });
```


```
Deprecation warning: value provided is not in a recognized ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments:
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 2005-01-01 00:00:00.000 +00:00, _f: undefined, _strict: undefined, _locale: [object Object]
  Error:

  - moment.js:318 Function.createFromInputFallback
    [server]/[sequelize]/[moment]/moment.js:318:94

  - moment.js:2080 configFromString
    [server]/[sequelize]/[moment]/moment.js:2080:15

  - moment.js:2444 configFromInput
    [server]/[sequelize]/[moment]/moment.js:2444:9

  - moment.js:2427 prepareConfig
    [server]/[sequelize]/[moment]/moment.js:2427:9

  - moment.js:2394 createFromConfig
    [server]/[sequelize]/[moment]/moment.js:2394:40

  - moment.js:2481 createLocalOrUTC
    [server]/[sequelize]/[moment]/moment.js:2481:12

  - moment.js:2485 createLocal
    [server]/[sequelize]/[moment]/moment.js:2485:12

  - moment.js:16 hooks
    [server]/[sequelize]/[moment]/moment.js:16:25

  - data-types.js:473 Constructor.DATE.$applyTimezone
    [server]/[sequelize]/lib/data-types.js:473:14

  - data-types.js:483 Constructor.DATE.$stringify
    [server]/[sequelize]/lib/data-types.js:483:15

  - data-types.js:77 Constructor.ABSTRACT.stringify
    [server]/[sequelize]/lib/data-types.js:77:17

  - query-generator.js:967 Object.escape
    [server]/[sequelize]/lib/dialects/abstract/query-generator.js:967:32

  - query-generator.js:2358 Object.whereItemQuery
    [server]/[sequelize]/lib/dialects/abstract/query-generator.js:2358:22

  - query-generator.js:1989
    [server]/[sequelize]/lib/dialects/abstract/query-generator.js:1989:25

  - lodash.js:4389
    [server]/[sequelize]/[lodash]/lodash.js:4389:15

  - lodash.js:2652 baseForOwn
    [server]/[sequelize]/[lodash]/lodash.js:2652:24
```

**Comment by Toxicable** [comment]
facing this aswell, the date should be iso formatted

**Comment by ephys** [comment]
`moment` was fully removed from our codebase
