### ISSUE TITLE
QueryGenerator.createTrigger  throws error when is executed with correct arguments  (Postgres dialect)

### ISSUE THREAD

**Issue by madoos** [sequelize/sequelize#8280]
## What you are doing?

```javascript
const QueryGenerator = sequelize.queryInterface.QueryGenerator
const createTriggerQuery = QueryGenerator.createTrigger('myTable', 'myTrigger', 'after', ['insert', 'update'],  'myFunction', [], ['FOR EACH ROW'])
```

## What do you expect to happen?

_QueryGenerator.createTrigger should return a string with query:_

```sql
CREATE TRIGGER myTrigger
AFTER INSERT OR UPDATE
ON myTable
FOR EACH ROW
EXECUTE PROCEDURE myFunction();
```
## What is actually happening?

_QueryGenerator.createTrigger throw an error:_

`Error: parseTriggerEventSpec: undefined trigger event 0`

```bash
Error: parseTriggerEventSpec: undefined trigger event 0
    at Utils._.map (/home/maurice/git/js/modules/sequelize-count-performance/node_modules/sequelize/lib/dialects/postgres/query-generator.js:717:15)
    at arrayMap (/home/maurice/git/js/modules/sequelize-count-performance/node_modules/lodash/lodash.js:660:23)
    at Function.map (/home/maurice/git/js/modules/sequelize-count-performance/node_modules/lodash/lodash.js:9571:14)
    at Object.expandTriggerEventSpec (/home/maurice/git/js/modules/sequelize-count-performance/node_modules/sequelize/lib/dialects/postgres/query-generator.js:708:20)
    at Object.createTrigger (/home/maurice/git/js/modules/sequelize-count-performance/node_modules/sequelize/lib/dialects/postgres/query-generator.js:593:28)
    at example (/home/maurice/git/js/modules/sequelize-count-performance/example/wrap.js:33:46)
    at Object.<anonymous> (/home/maurice/git/js/modules/sequelize-count-performance/example/wrap.js:24:1)
    at Module._compile (module.js:566:14)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```
__Dialect:__ postgres
__Sequelize version:__ ^4.8.0

**Comment by sushantdhiman** [comment]
Fixed https://github.com/sequelize/sequelize/commit/bde6d501a6106e83972680c728f197c2426e3840
