### ISSUE TITLE
findOrCreate does not work on MSSQL server 2014

### ISSUE THREAD

**Issue by nengine** [sequelize/sequelize#8304]
## What you are doing?

```js
const Account = sequelize.define('account', {
  user_id: Sequelize.INTEGER,
  currency: Sequelize.INTEGER,
  balance: Sequelize.DECIMAL(12, 8),
  createdAt: {
    type: Sequelize.DATE,
    field: 'created_at'
  },
  updatedAt: {
    type: Sequelize.DATE,
    field: 'updated_at'
  }
});

function create(req, res) {
  Account
    .findOrCreate({
      where: {currency: 3},      
      defaults: {currency: 3, user_id: 1}})
    .spread((account, created) => {
      res.json(account);
    })
}
```

## What do you expect to happen?
New account to be created.

## What is actually happening?
New account record was not created and got the error show below.

_Output, either JSON or SQL_
```js
POST /api/wallet/stellar - - ms - -
Executing (a17eb1afab49082d9333): BEGIN TRANSACTION;
Executing (a17eb1afab49082d9333): SELECT [id], [user_id], [currency], [balance], [created_at] AS [createdAt], [updated_at] AS [updatedAt] FROM [accounts] AS [account] WHERE [account].[currency] = 3 ORDER BY [account].[id] OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY;
Executing (a17eb1afab49082d9333): INSERT INTO [accounts] ([user_id],[currency],[created_at],[updated_at]) OUTPUT INSERTED.* VALUES (1,3,N'2017-09-14 00:22:25.000 +00:00',N'2017-09-14 00:22:25.000 +00:00');
Executing (a17eb1afab49082d9333): COMMIT TRANSACTION;
Unhandled rejection SequelizeDatabaseError: The COMMIT TRANSACTION request has no corresponding BEGIN TRANSACTION.
    at Query.formatError (C:\Users\nash\wallet-api\node_modules\sequelize\lib\dialects\mssql\query.js:322:12)
    at Request.connection.commitTransaction.err [as userCallback] (C:\Users\nash\wallet-api\node_modules\sequelize\lib\dialects\mssql\query.js:74:25)
    at Request._this.callback (C:\Users\nash\wallet-api\node_modules\tedious\lib\request.js:47:27)
    at Connection.message (C:\Users\nash\wallet-api\node_modules\tedious\lib\connection.js:1401:27)
    at Connection.dispatchEvent (C:\Users\nash\wallet-api\node_modules\tedious\lib\connection.js:687:45)
    at MessageIO.<anonymous> (C:\Users\nash\wallet-api\node_modules\tedious\lib\connection.js:602:18)
    at emitNone (events.js:86:13)
    at MessageIO.emit (events.js:185:7)
    at ReadablePacketStream.<anonymous> (C:\Users\nash\wallet-api\node_modules\tedious\lib\message-io.js:102:16)
    at emitOne (events.js:96:13)
    at ReadablePacketStream.emit (events.js:188:7)
    at addChunk (C:\Users\nash\wallet-api\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:284:12)
    at readableAddChunk (C:\Users\nash\wallet-api\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:271:11)
    at ReadablePacketStream.Readable.push (C:\Users\nash\wallet-api\node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:238:10)
    at ReadablePacketStream.Transform.push (C:\Users\nash\wallet-api\node_modules\tedious\node_modules\readable-stream\lib\_stream_transform.js:146:32)
    at ReadablePacketStream._transform (C:\Users\nash\wallet-api\node_modules\tedious\lib\message-io.js:70:16)
    at ReadablePacketStream.Transform._read (C:\Users\nash\wallet-api\node_modules\tedious\node_modules\readable-stream\lib\_stream_transform.js:182:10)
    at ReadablePacketStream.Transform._write (C:\Users\nash\wallet-api\node_modules\tedious\node_modules\readable-stream\lib\_stream_transform.js:170:83)
    at doWrite (C:\Users\nash\wallet-api\node_modules\tedious\node_modules\readable-stream\lib\_stream_writable.js:406:64)
    at writeOrBuffer (C:\Users\nash\wallet-api\node_modules\tedious\node_modules\readable-stream\lib\_stream_writable.js:395:5)
    at ReadablePacketStream.Writable.write (C:\Users\nash\wallet-api\node_modules\tedious\node_modules\readable-stream\lib\_stream_writable.js:322:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
From previous event:
    at Query._run (C:\Users\nash\wallet-api\node_modules\sequelize\lib\dialects\mssql\query.js:61:12)
    at Promise.using.connection (C:\Users\nash\wallet-api\node_modules\sequelize\lib\dialects\mssql\query.js:142:69)
From previous event:
    at Query.run (C:\Users\nash\wallet-api\node_modules\sequelize\lib\dialects\mssql\query.js:142:20)
    at retry (C:\Users\nash\wallet-api\node_modules\sequelize\lib\sequelize.js:533:32)
    at C:\Users\nash\wallet-api\node_modules\retry-as-promised\index.js:40:21
    at retryAsPromised (C:\Users\nash\wallet-api\node_modules\retry-as-promised\index.js:30:10)
    at Promise.try.then.connection (C:\Users\nash\wallet-api\node_modules\sequelize\lib\sequelize.js:533:14)
From previous event:
    at Sequelize.query (C:\Users\nash\wallet-api\node_modules\sequelize\lib\sequelize.js:529:8)
    at QueryInterface.commitTransaction (C:\Users\nash\wallet-api\node_modules\sequelize\lib\query-interface.js:934:36)
    at Transaction.commit (C:\Users\nash\wallet-api\node_modules\sequelize\lib\transaction.js:66:8)
    at sequelize.transaction.then.then.finally (C:\Users\nash\wallet-api\node_modules\sequelize\lib\model.js:2112:28)
    at runCallback (timers.js:574:20)
From previous event:
    at Function.findOrCreate (C:\Users\nash\wallet-api\node_modules\sequelize\lib\model.js:2109:15)
    at create (C:\Users\nash\wallet-api\dist\server\controllers\stellar.controller.js:37:21)
    at Layer.handle [as handle_request] (C:\Users\nash\wallet-api\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\nash\wallet-api\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (C:\Users\nash\wallet-api\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\nash\wallet-api\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\nash\wallet-api\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (C:\Users\nash\wallet-api\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Users\nash\wallet-api\node_modules\express\lib\router\index.js:271:10)
    at Function.handle (C:\Users\nash\wallet-api\node_modules\express\lib\router\index.js:176:3)
    at router (C:\Users\nash\wallet-api\node_modules\express\lib\router\index.js:46:12)
    at Layer.handle [as handle_request] (C:\Users\nash\wallet-api\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\nash\wallet-api\node_modules\express\lib\router\index.js:312:13)
    at C:\Users\nash\wallet-api\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\Users\nash\wallet-api\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Users\nash\wallet-api\node_modules\express\lib\router\index.js:271:10)
    at Function.handle (C:\Users\nash\wallet-api\node_modules\express\lib\router\index.js:176:3)
    at router (C:\Users\nash\wallet-api\node_modules\express\lib\router\index.js:46:12)
    at Layer.handle [as handle_request] (C:\Users\nash\wallet-api\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\nash\wallet-api\node_modules\express\lib\router\index.js:312:13)
    at C:\Users\nash\wallet-api\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\Users\nash\wallet-api\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Users\nash\wallet-api\node_modules\express\lib\router\index.js:271:10)
    at C:\Users\nash\wallet-api\node_modules\express-winston\index.js:306:9
    at Layer.handle [as handle_request] (C:\Users\nash\wallet-api\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\nash\wallet-api\node_modules\express\lib\router\index.js:312:13)
    at C:\Users\nash\wallet-api\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\Users\nash\wallet-api\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Users\nash\wallet-api\node_modules\express\lib\router\index.js:271:10)
    at cors (C:\Users\nash\wallet-api\node_modules\cors\lib\index.js:179:7)
    at C:\Users\nash\wallet-api\node_modules\cors\lib\index.js:229:17
    at originCallback (C:\Users\nash\wallet-api\node_modules\cors\lib\index.js:218:15)
    at C:\Users\nash\wallet-api\node_modules\cors\lib\index.js:223:13
    at optionsCallback (C:\Users\nash\wallet-api\node_modules\cors\lib\index.js:204:9)
    at corsMiddleware (C:\Users\nash\wallet-api\node_modules\cors\lib\index.js:209:7)
    at Layer.handle [as handle_request] (C:\Users\nash\wallet-api\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\nash\wallet-api\node_modules\express\lib\router\index.js:312:13)
    at C:\Users\nash\wallet-api\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\Users\nash\wallet-api\node_modules\express\lib\router\index.js:330:12)
    at Immediate.next (C:\Users\nash\wallet-api\node_modules\express\lib\router\index.js:271:10)
    at runCallback (timers.js:576:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

__Dialect:__ mssql
__Database version: SQL Server 2014 Express
__Sequelize version: 4.8.3

**Comment by sushantdhiman** [comment]
Looks like your are trying `findOrCreate` inside another transaction. `findOrCreate` use an implicit transaction to ensure record is find and created in sync to db. Just pass `transaction` option to this method as well and it should work

**Comment by nengine** [comment]
Hi Thanks.  I replaced datetime to datetime2 date type in mssql server 2012 and don't see an error anymore.  Apparently mssql server cannot accept datetime values with timezone like extra +00:00, but strangely works with datatime2 data type.  But not so sure why it was not giving such error findOrCreate, but on Create method alone, it would give error about column data type.
