### ISSUE TITLE
New connection "Logging" give error when setting value from config.json

### ISSUE THREAD

**Issue by Ev1dentFir3** [sequelize/sequelize#8309]
## What are you doing?
I'm using Sequelize in my discord.js bot, and I'm saving the db login information in a config.json file. When I set "logging" to the value of "debug" (true/false) it produces an error `options.logging.apply is not a function.` If I set the logging value to true/false directly in the code it works perfectly fine.

core.js
```javascript
var Discord = require('discord.js');
var path = require('path');
var fs = require('fs');
var sequelize = require('sequelize');
var config = require('./config')

// Create a global client so all our plugins have access to it.
global.client = new Discord.Client({ autoReconnect: true });

// Let's give all the plugins access to the config incase they need any thing from it, or want to add to it.
client.config = config;
client.Logo = 'http://i.imgur.com/aDiphof.png';
console.log("Debug is set to: " + client.config.BotSettings.Debug);

// Database Setup

// Connection
client.mysql = new sequelize(client.config.MySql.dbName, client.config.MySql.dbUserName, client.config.MySql.dbPassword, {
  host: client.config.MySql.dbHost,
  dialect: client.config.MySql.dbType,
  logging: client.config.BotSettings.Debug,
  pool: {
    max: 5,
    min: 0,
    idle: 10000
  },
});
```
config.json
```json
{
    "BotSettings": {
        "BotToken": "Mjg2NjQ4OTg0OTgwNjg0ODAw.DJSdeQ.n8Yr7eqtXIHBcC90srrNcr6wKkE",
        "Debug": "false",
        "IgnoreBots": "true"
    },
    "MySql": {
        "dbName": "firebotdev",
        "dbUserName": "Firebot",
        "dbPassword": "FireDB123",
        "dbHost": "Localhost",
        "dbType": "mysql" 
    },
    "__Notes": "Don't change the 'dbType' option for now, we will be supporting other dbTypes in the near future!"
}
```
## What do you expect to happen?
What I want to happen is for the logging property to be set to true/false when the setting is changed in my config.json

## What is actually happening?
error produced instead (see above)

Console Output w/ Error
```
    node --inspect=6145 --debug-brk core.js 
Debugger listening on ws://127.0.0.1:6145/5d7b05f3-7b35-4c13-9b42-65eb95b740bf
Debug is set to: false
Firebot Loading
Looking for plugin files...
| Loading plugin: -coreCommands
Loading Fire Bot Core Commands are loading.
| Loading plugin: FireMusic
Loading Fire Music Alpha V1
2 plugins loaded: -coreCommands.js,FireMusic.js
Unhandled rejection TypeError: options.logging.apply is not a function
    at Sequelize.log (c:\Users\ajste\source\repos\Firebot\node_modules\sequelize\lib\sequelize.js:1052:23)
    at Query.run (c:\Users\ajste\source\repos\Firebot\node_modules\sequelize\lib\dialects\mysql\query.js:39:22)
    at retry (c:\Users\ajste\source\repos\Firebot\node_modules\sequelize\lib\sequelize.js:532:32)
    at c:\Users\ajste\source\repos\Firebot\node_modules\retry-as-promised\index.js:40:21
    at Promise._execute (c:\Users\ajste\source\repos\Firebot\node_modules\bluebird\js\release\debuggability.js:300:9)
    at Promise._resolveFromExecutor (c:\Users\ajste\source\repos\Firebot\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (c:\Users\ajste\source\repos\Firebot\node_modules\bluebird\js\release\promise.js:79:10)
    at retryAsPromised (c:\Users\ajste\source\repos\Firebot\node_modules\retry-as-promised\index.js:30:10)
    at Promise.try.then.connection (c:\Users\ajste\source\repos\Firebot\node_modules\sequelize\lib\sequelize.js:532:14)
    at tryCatcher (c:\Users\ajste\source\repos\Firebot\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (c:\Users\ajste\source\repos\Firebot\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (c:\Users\ajste\source\repos\Firebot\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (c:\Users\ajste\source\repos\Firebot\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (c:\Users\ajste\source\repos\Firebot\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (c:\Users\ajste\source\repos\Firebot\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (c:\Users\ajste\source\repos\Firebot\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (c:\Users\ajste\source\repos\Firebot\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
Unhandled rejection TypeError: options.logging.apply is not a function
    at Sequelize.log (c:\Users\ajste\source\repos\Firebot\node_modules\sequelize\lib\sequelize.js:1052:23)
    at Query.run (c:\Users\ajste\source\repos\Firebot\node_modules\sequelize\lib\dialects\mysql\query.js:39:22)
    at retry (c:\Users\ajste\source\repos\Firebot\node_modules\sequelize\lib\sequelize.js:532:32)
    at c:\Users\ajste\source\repos\Firebot\node_modules\retry-as-promised\index.js:40:21
    at Promise._execute (c:\Users\ajste\source\repos\Firebot\node_modules\bluebird\js\release\debuggability.js:300:9)
    at Promise._resolveFromExecutor (c:\Users\ajste\source\repos\Firebot\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (c:\Users\ajste\source\repos\Firebot\node_modules\bluebird\js\release\promise.js:79:10)
    at retryAsPromised (c:\Users\ajste\source\repos\Firebot\node_modules\retry-as-promised\index.js:30:10)
    at Promise.try.then.connection (c:\Users\ajste\source\repos\Firebot\node_modules\sequelize\lib\sequelize.js:532:14)
    at tryCatcher (c:\Users\ajste\source\repos\Firebot\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (c:\Users\ajste\source\repos\Firebot\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (c:\Users\ajste\source\repos\Firebot\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromiseCtx (c:\Users\ajste\source\repos\Firebot\node_modules\bluebird\js\release\promise.js:606:10)
    at Async._drainQueue (c:\Users\ajste\source\repos\Firebot\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (c:\Users\ajste\source\repos\Firebot\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (c:\Users\ajste\source\repos\Firebot\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
Firebot has connected to 1 server(s).
```

__Dialect: mysql
__Dialect version: 5.7.19-log MySQL Community Server (GPL)
__Sequelize version: 4.8.2
__Tested with master branch: Yes

**Comment by Ev1dentFir3** [comment]
Never mind, I found a stupid mistake in my own code.

**Comment by benpingilley** [comment]
@Ev1dentFir3 I'm seeing the same error. Do you remember what your mistake was?

**Comment by gabrielpasche** [comment]
let database = new Sequelize(config.db, {logging: config.logging});
logging: needs to be boolean

**Comment by Yuri-Lima** [comment]
> needs to be typeof boolean

actually, it could work however would be better to type a console transport or just put console.log 

``` js
logging: console.log || false
```

**Comment by fzn0x** [comment]
> > needs to be typeof boolean
> 
> actually, it could work however would be better to type a console transport or just put console.log
> 
> ```js
> logging: console.log || false
> ```

Yes, just for note, default value for logging is `console.log`, check out our newest version of Sequelize https://sequelize.org/docs/v6/getting-started/#logging
