### ISSUE TITLE
Error: Resource not currently part of this pool

### ISSUE THREAD

**Issue by caseyduquettesc** [sequelize/sequelize#8322]
## What are you doing?
Running against Google Cloud SQL and today I think they did some rolling restarts and sequelize continued to throw these errors (417 of them over an hour) and did not recover. Application had to be shutdown and restarted.

## What do you expect to happen?
Errors to go away when database comes back.

## What is actually happening?
Errors continually get thrown until restart, unable to recover on its own.

```
Unhandled rejection Error: Resource not currently part of this pool
    at Pool.release (/app/node_modules/generic-pool/lib/Pool.js:422:35)
    at ConnectionManager.releaseConnection (/app/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:292:22)
    at Transaction.cleanup (/app/node_modules/sequelize/lib/transaction.js:165:50)
    at sequelize.getQueryInterface.rollbackTransaction.finally (/app/node_modules/sequelize/lib/transaction.js:95:23)
    at PassThroughHandlerContext.finallyHandler (/app/node_modules/bluebird/js/release/finally.js:56:23)
    at bound (domain.js:280:14)
    at PassThroughHandlerContext.runBound (domain.js:293:12)
    at PassThroughHandlerContext.tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

__Dialect:__ mysql
__Dialect version:__ 
__Database version:__ 5.7
__Sequelize version:__ 4.8.3
__Tested with master branch:__ No

**Note :** _Your issue may be ignored by maintainers if its not tested against `master` branch OR does not follow issue template._

**Comment by caseyduquettesc** [comment]
Possibly related, as I saw some of these errors in the log too, https://github.com/sequelize/sequelize/issues/7884
