### ISSUE TITLE
Support for Infinity and -Infinity Dates in PostgreSQL

### ISSUE THREAD

**Issue by mkaufmaner** [sequelize/sequelize#8336]
## What are you doing?
Trying to insert infinity and -infinity into a PostgreSQL column where the attribute has a type of Date.

Definition:
```js
'deletedAt': {
    type: DataTypes.DATE,
    field: 'deleted_at',
    allowNull: false,
    defaultValue: Infinity
}
```

## What do you expect to happen?
For the record to be inserted correctly.

## What is actually happening?
```sh
{ SequelizeValidationError: null is not a valid date
    at DATE.validate (node_modules/sequelize/lib/data-types.js:312:11)
    at Object.escape (node_modules/sequelize/lib/dialects/abstract/query-generator.js:898:26)
    at Object.insertQuery (node_modules/sequelize/lib/dialects/abstract/query-generator.js:187:28)
    at QueryInterface.insert (node_modules/sequelize/lib/query-interface.js:519:37)
    at Promise.try.then.then.then (node_modules/sequelize/lib/model.js:3591:56)
    at tryCatcher (node_modules/sequelize/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (node_modules/sequelize/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (node_modules/sequelize/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (node_modules/sequelize/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (node_modules/sequelize/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (node_modules/sequelize/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (node_modules/sequelize/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (node_modules/sequelize/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5) name: 'SequelizeValidationError', errors: [] }
```

__Dialect:__ postgres
__Dialect version:__ Stable???
__Database version:__ 9.6 (Current)
__Sequelize version:__ 4.8.4
__Tested with master branch:__ Yes

**Comment by gabegorelick** [comment]
While #8357 is definitely a huge leap, this is still an issue for soft deletes. See https://github.com/sequelize/sequelize/issues/8382.
