### ISSUE TITLE
Query w/ multiple one to many includes fails w/ limit

### ISSUE THREAD

**Issue by robert-armstrong** [sequelize/sequelize#8360]
## What are you doing?

To run:

```
npm install sequelize
npm install sqlite3
```

```js

'use strict';

const Sequelize = require('sequelize')
const sequelize = new Sequelize({ dialect: 'sqlite', storage: 'test.sqlite' });

const Product = sequelize.define('products', {
  id: {
    type: Sequelize.INTEGER,
    primaryKey: true
  },
  name: {
    type: Sequelize.STRING
  }
});

const Tag = sequelize.define('tags', {
  id: {
      type: Sequelize.INTEGER,
      primaryKey: true,
      autoIncrement: true
  },
  name: {
      type: Sequelize.STRING,
  }
});

const ProductTag = sequelize.define('products_tags', {
}, {
  createdAt: false,
  updatedAt: false
} );

var ProductAttribute = sequelize.define('product_attributes', {
  product_id: {
    type: Sequelize.INTEGER,
    primaryKey: true
  },
  value: {
    type: Sequelize.STRING
  }
});

Product.hasMany(ProductAttribute, { foreignKey: 'product_id', sourceKey: 'id' });
ProductAttribute.belongsTo(Product, { foreignKey: 'id' });

Product.belongsToMany(Tag, { through: ProductTag, foreignKey: 'product_id' });
Tag.belongsToMany(Product, { through: ProductTag, foreignKey: 'tag_id' });

sequelize.sync({ force: true }).then(() => {
  Product.findAll({
    offset: 0,
    limit: 100,
    include:
     [ { model: Tag,
         where: { name: { in: [ 'red' ] } },
         duplicating: false },
       { model: ProductAttribute } ],
    })
    .then(results => {
       console.log(results);
    });
});

```

## What do you expect to happen?

Return the top 100 Product records that match the Tag equal to 'red', and all ProductAttributes associated with those Products.

## What is actually happening?

```
Unhandled rejection SequelizeDatabaseError: SQLITE_ERROR: no such column: tags->products_tags.product_id
    at Query.formatError (/Users/robert/node_modules/sequelize/lib/dialects/sqlite/query.js:418:16)
    at afterExecute (/Users/robert/node_modules/sequelize/lib/dialects/sqlite/query.js:119:32)
    at replacement (/Users/robert/node_modules/sqlite3/lib/trace.js:19:31)
    at Statement.errBack (/Users/robert/node_modules/sqlite3/lib/sqlite3.js:16:21)
```

Query works if the limit and offset are removed. Query also works if only one include is used.

__Dialect:__ mysql /  sqlite
__Dialect version:__ MySQL 5.5 and SQLite3
__Sequelize version:__ 4.10.0
__Tested with master branch:__ Yes

**Note :** _Your issue may be ignored by maintainers if its not tested against `master` branch OR does not follow issue template._

**Comment by rarmstrong-netflix** [comment]
Discovered I can fix this by using 

```
{ model: ProductAttribute, separate: true }
```

**Comment by robert-armstrong** [comment]
Discovered I can work around this by using separate: true

```
{ model: ProductAttribute, separate: true }
```

**Comment by pauloddr** [comment]
`separate: true` also seems to fix issues with nested associations in queries with limit/order.

**Comment by jongear** [comment]
@robert-armstrong how did you manage to get sqlite to accept autoincrement?

I receive this on every start attempt

`Unhandled rejection SequelizeDatabaseError: SQLITE_ERROR: near "AUTOINCREMENT": syntax error`

**Comment by jongear** [comment]
If I remove `autoIncrement: true` from my primary key which is an integer it runs fine.
