### ISSUE TITLE
a foreign key field of N:M assocation can't define a property of `allowNull:false`

### ISSUE THREAD

**Issue by newbienewbie** [sequelize/sequelize#8372]
##  a N:M assocation

Assuming there are a `User` Model and a `Role`  Model :

```js
const User=sequelize.define(
    'user',
    { username:Sequelize.STRING, },
    { tableName:'user' }
);

const Role=sequelize.define(
    'role',
    { name: Sequelize.STRING, },
    { tableName:'role', }
);
```
The `Role` and `Model`  Model have a N:M assocation through `UserRole` :
```js
const UserRole = sequelize.define(
    'userRole', 
    {
        userId: {
            type: Sequelize.INTEGER,
            field: 'user_id',
            references: { model: User, key: 'id', },
        },
        roleId: {
            type: Sequelize.INTEGER,
            field: 'role_id',
            allowNull: false,   // here's where the AggregateError occours
            references: { model: Role, key: 'id', },
        },
        description: Sequelize.STRING,
    },
    {
        tableName: 'user_role',
        timestamps:false,
    }
);

User.belongsToMany(Role, { through: UserRole ,foreignKey:'user_id',otherKey:'role_id'});
Role.belongsToMany(User, { through: UserRole ,foreignKey:'role_id',otherKey:'user_id'});
```
Notice that we define a  `allowNull:false` property for the foreign key of `roleId` in the code above.

then execute a `User#addRoles()` query:
```js
User.create({username:'user_name'})
.then(user=>{
    return Role.create({ name: `role_name`})
        .then(function (role) {
            return user.addRoles([role],{ through:{ description:'shit', }, });
        });
});
```

## AggregateError Occours

if we add a `allowNull: false` to the `roleId` property of `UserRole` as above, the User#addRoles() query will throw a AggregateError Exception :
```
Unhandled rejection AggregateError: aggregate error
    at Promise.try.then (C:\Users\itminus\Desktop\bug-test\sequelizejs-test\node_modules\._sequelize@4.10.3@sequelize\lib\model.js:2300:24
)
    at tryCatcher (C:\Users\itminus\Desktop\bug-test\sequelizejs-test\node_modules\._bluebird@3.5.0@bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\itminus\Desktop\bug-test\sequelizejs-test\node_modules\._bluebird@3.5.0@bluebird\js\rel
ease\promise.js:512:31)
    at Promise._settlePromise (C:\Users\itminus\Desktop\bug-test\sequelizejs-test\node_modules\._bluebird@3.5.0@bluebird\js\release\promis
e.js:569:18)
    at Promise._settlePromise0 (C:\Users\itminus\Desktop\bug-test\sequelizejs-test\node_modules\._bluebird@3.5.0@bluebird\js\release\promi
se.js:614:10)
    at Promise._settlePromises (C:\Users\itminus\Desktop\bug-test\sequelizejs-test\node_modules\._bluebird@3.5.0@bluebird\js\release\promi
se.js:693:18)
    at Async._drainQueue (C:\Users\itminus\Desktop\bug-test\sequelizejs-test\node_modules\._bluebird@3.5.0@bluebird\js\release\async.js:13
3:16)
    at Async._drainQueues (C:\Users\itminus\Desktop\bug-test\sequelizejs-test\node_modules\._bluebird@3.5.0@bluebird\js\release\async.js:1
43:10)
    at Immediate.Async.drainQueues (C:\Users\itminus\Desktop\bug-test\sequelizejs-test\node_modules\._bluebird@3.5.0@bluebird\js\release\a
sync.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
```

however, if we remove the line `allowNull:false`，the query will execute as expected . 

## Env

__Dialect:__ mysql
__Dialect version:__ 1.4.2 (mysql2)
__Database version:__ 5.7.17
__Sequelize version:__ 4.10.3
__Tested with master branch:__ Yes

Just for convenience , here is the complete code  reproducing the Error:
```js
const Sequelize=require('sequelize');

const database={
    dialect:'mysql',
    host:'127.0.0.1',
    port:'3306',
    username:'***********',
    password:'***********',
    dbname:'************',
    charset:'utf-8',
};     

const sequelize=new Sequelize(
    database.dbname,
    database.username,
    database.password,
    {
        host:database.host,
        dialect:database.dialect,
        pool: {
            max: 5,
            min: 0,
            idle: 10000
        },
    }
);

const User=sequelize.define(
    'user',
    { username:Sequelize.STRING, },
    { tableName:'user' }
);

const Role=sequelize.define(
    'role',
    { name: Sequelize.STRING, },
    { tableName:'role', }
);


const UserRole = sequelize.define(
    'userRole', 
    {
        userId: {
            type: Sequelize.INTEGER,
            field: 'user_id',
            references: { model: User, key: 'id', },
        },
        roleId: {
            type: Sequelize.INTEGER,
            field: 'role_id',
            allowNull: false,   // here's where the AggregateError occours
            references: { model: Role, key: 'id', },
        },
        description: Sequelize.STRING,
    },
    {
        tableName: 'user_role',
        timestamps:false,
    }
);

User.belongsToMany(Role, { through: UserRole ,foreignKey:'user_id',otherKey:'role_id'});
Role.belongsToMany(User, { through: UserRole ,foreignKey:'role_id',otherKey:'user_id'});

sequelize.sync({force:true})
    .then(()=>{
        return User.create({username:'user_name'})
            .then(user=>{
                return Role.create({ name: `role_name`})
                    .then(function (role) {
                        return user.addRoles([role],{ through:{ description:'shit', }, });
                    });
            });
    });
```

**Comment by yss14** [comment]
I've got the same problem on `postgres`.

```
const LibrarySong = sequelize.define("LibrarySong", {
        ownerType: {
            type: Sequelize.ENUM(['owner', 'semi-owner', 'referencer']),
            allowNull: false,
            //defaultValue: 'owner',
            field: 'solType'
        }
    });
```

Everytime I insert a new entry, the `AggregateError` occurs, but the data is inserted correctly. 

```
libraryObjs[1].addSongs([//data], { through: { ownerType: 'owner' } });
```

**Comment by Yuiffy** [comment]
Thank you @newbienewbie !I meet the same issue and solve by your method.
This is still a issue, why it notNull make it AggregateError
