### ISSUE TITLE
Migration: removeColumn fails on unique contraints

### ISSUE THREAD

**Issue by austindebruyn** [sequelize/sequelize#8385]
## What are you doing?
Given a column defined like this:

```
      email: {
        type: Sequelize.STRING,
        unique: true
      },
```

I'd like to drop it like this

```
queryInterface.removeColumn('Users', 'email')
```

I have a repro case that shows the error here: https://github.com/austindebruyn/sequelize-err-on-rename-repro
I've seen this locally and on a trusty DO box.

```js
// code here
```

## What do you expect to happen?
Column to be dropped.

## What is actually happening?
A SequelizeDatabaseError error is thrown.

Before removing a column, the mysql dialect checks that there's no foreign keys attached to it with this query:
```
SELECT CONSTRAINT_NAME as constraint_name FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE (REFERENCED_TABLE_NAME = 'users' AND REFERENCED_COLUMN_NAME = 'email') OR (TABLE_NAME = 'users' AND COLUMN_NAME = 'email')
```

It looks to me like [KEY_COLUMN_USAGE](https://dev.mysql.com/doc/refman/5.7/en/key-column-usage-table.html) table stores not just foreign keys but all constraints. In my failing case, `email` is unique and present in this table, so sequelize aborts the removeColumn with the following error:

```
vagrant@vagrant-ubuntu-trusty-64:~/projects/sequelize-err-on-rename-repro$ ./node_modules/.bin/sequelize db:migrate

Sequelize CLI [Node: 8.6.0, CLI: 3.0.0, ORM: 4.11.1]

WARNING: This version of Sequelize CLI is not fully compatible with Sequelize v4. https://github.com/sequelize/cli#sequelize-support

Loaded configuration file "config/config.json".
Using environment "development".
== 20170928040207-remove-email-column: migrating =======
SELECT CONSTRAINT_NAME as constraint_name FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE (REFERENCED_TABLE_NAME = 'Users' AND REFERENCED_COLUMN_NAME = 'email') OR (TABLE_NAME = 'Users' AND COLUMN_NAME = 'email')
[ TextRow { constraint_name: 'email' },
  TextRow { constraint_name: 'email' } ]
Unhandled rejection SequelizeDatabaseError: Error on rename of './sequelize_err_on_rename_repro/Users' to './sequelize_err_on_rename_repro/#sql2-45c-1c4' (errno: 152)
    at Query.formatError (/home/vagrant/projects/sequelize-err-on-rename-repro/node_modules/sequelize/lib/dialects/mysql/query.js:222:16)
    at Query.connection.query [as onResult] (/home/vagrant/projects/sequelize-err-on-rename-repro/node_modules/sequelize/lib/dialects/mysql/query.js:55:23)
    at Query.Command.execute (/home/vagrant/projects/sequelize-err-on-rename-repro/node_modules/mysql2/lib/commands/command.js:30:12)
    at Connection.handlePacket (/home/vagrant/projects/sequelize-err-on-rename-repro/node_modules/mysql2/lib/connection.js:515:28)
    at PacketParser.onPacket (/home/vagrant/projects/sequelize-err-on-rename-repro/node_modules/mysql2/lib/connection.js:94:16)
    at PacketParser.executeStart (/home/vagrant/projects/sequelize-err-on-rename-repro/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.<anonymous> (/home/vagrant/projects/sequelize-err-on-rename-repro/node_modules/mysql2/lib/connection.js:102:29)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:587:20)

== 20170928040207-remove-email-column: migrated (0.031s)
```

I've opened a PR with my suggestion here: https://github.com/sequelize/sequelize/pull/8386

Similar to https://github.com/sequelize/sequelize/issues/5808

__Dialect:__ mysql 
__Dialect version:__ 57
__Database version:__ XXX
__Sequelize version:__ latest (seen this in 3 and 4)
__Tested with master branch:__ Yes

**Note :** _Your issue may be ignored by maintainers if its not tested against `master` branch OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Fixed https://github.com/sequelize/sequelize/commit/9ca86af20c72a4ae20544290a00e5a27695e860a
