### ISSUE TITLE
TypeError: Cannot read property 'types' of undefined

### ISSUE THREAD

**Issue by akhmadkresna** [sequelize/sequelize#8453]
## What are you doing?
i try to connect to aws postgres db 
here is my json conf:

```js
"username": "nexzcxsmkguemd",
			"password": "blablabal",
			"database": "dtd0fjhlket9p",
			"host": "ec2-23-23-227-188.compute-1.amazonaws.com",
			"dialect": "postgres",
			"logging": false,
			"native": true,
			"ssl": true,
			"port": 5432
```
package i use : 
sequelize v 4.13.8
pg-native v 2.2.0
pg v 6.4.2

## What do you expect to happen?
_success connection_

this is what i get
```js
TypeError: Cannot read property 'types' of undefined
    at Promise.then.results (/Users/jonn/git/schlr-nodejs-postgres/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:170:15)
From previous event:
    at Promise.tap.connection (/Users/jonn/git/schlr-nodejs-postgres/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:157:132)
From previous event:
    at ConnectionManager.connect (/Users/jonn/git/schlr-nodejs-postgres/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:134:8)
    at sequelize.runHooks.then (/Users/jonn/git/schlr-nodejs-postgres/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:324:50)
From previous event:
    at ConnectionManager._connect (/Users/jonn/git/schlr-nodejs-postgres/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:324:8)
    at ConnectionManager.getConnection (/Users/jonn/git/schlr-nodejs-postgres/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:254:46)
    at Promise.try (/Users/jonn/git/schlr-nodejs-postgres/node_modules/sequelize/lib/sequelize.js:538:92)
From previous event:
    at Sequelize.query (/Users/jonn/git/schlr-nodejs-postgres/node_modules/sequelize/lib/sequelize.js:445:23)
    at QueryInterface.select (/Users/jonn/git/schlr-nodejs-postgres/node_modules/sequelize/lib/query-interface.js:1013:27)
    at Promise.try.then.then.then (/Users/jonn/git/schlr-nodejs-postgres/node_modules/sequelize/lib/model.js:1556:34)
    at runCallback (timers.js:637:20)
From previous event:
    at Function.findAll (/Users/jonn/git/schlr-nodejs-postgres/node_modules/sequelize/lib/model.js:1553:8)
    at Function.findOne (/Users/jonn/git/schlr-nodejs-postgres/node_modules/sequelize/lib/model.js:1709:17)
    at Strategy._verify (/Users/jonn/git/schlr-nodejs-postgres/app/kernel/passport.js:69:25)
    at Strategy.authenticate (/Users/jonn/git/schlr-nodejs-postgres/node_modules/passport-local/lib/strategy.js:88:12)
    at attempt (/Users/jonn/git/schlr-nodejs-postgres/node_modules/passport/lib/middleware/authenticate.js:348:16)
    at authenticate (/Users/jonn/git/schlr-nodejs-postgres/node_modules/passport/lib/middleware/authenticate.js:349:7)
    at Layer.handle [as handle_request] (/Users/jonn/git/schlr-nodejs-postgres/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/jonn/git/schlr-nodejs-postgres/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/jonn/git/schlr-nodejs-postgres/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/jonn/git/schlr-nodejs-postgres/node_modules/express/lib/router/layer.js:95:5)
    at /Users/jonn/git/schlr-nodejs-postgres/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/jonn/git/schlr-nodejs-postgres/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/jonn/git/schlr-nodejs-postgres/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/jonn/git/schlr-nodejs-postgres/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/jonn/git/schlr-nodejs-postgres/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/Users/jonn/git/schlr-nodejs-postgres/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/jonn/git/schlr-nodejs-postgres/node_modules/express/lib/router/index.js:317:13)
    at /Users/jonn/git/schlr-nodejs-postgres/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/jonn/git/schlr-nodejs-postgres/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/jonn/git/schlr-nodejs-postgres/node_modules/express/lib/router/index.js:275:10)
    at /Users/jonn/git/schlr-nodejs-postgres/app/kernel/interceptor.js:30:10
    at Layer.handle [as handle_request] (/Users/jonn/git/schlr-nodejs-postgres/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/jonn/git/schlr-nodejs-postgres/node_modules/express/lib/router/index.js:317:13)
    at /Users/jonn/git/schlr-nodejs-postgres/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/jonn/git/schlr-nodejs-postgres/node_modules/express/lib/router/index.js:335:12)
    at Immediate.next (/Users/jonn/git/schlr-nodejs-postgres/node_modules/express/lib/router/index.js:275:10)
    at Immediate.<anonymous> (/Users/jonn/git/schlr-nodejs-postgres/node_modules/express/lib/router/index.js:635:15)
    at runCallback (timers.js:639:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

__Tested with master branch:__ Yes

**Comment by akhmadkresna** [comment]
turn out To activate SSL for PG connections you don't need native: true or ssl: true but "dialectOptions": {
				"ssl": true
			},
