### ISSUE TITLE
Adding operatorsAliases legacy configuration gives an Unhandled rejection error

### ISSUE THREAD

**Issue by nyur321** [sequelize/sequelize#8465]
The error occurs when Custom legacy operator aliases is set in the configuration which is described here:
[http://docs.sequelizejs.com/manual/tutorial/querying.html#operators-aliases](url)

`
const Op = Sequelize.Op;
const operatorsAliases = {
    $eq: Op.eq,
    $ne: Op.ne,
    $gte: Op.gte,
    $gt: Op.gt,
    $lte: Op.lte,
    $lt: Op.lt,
    $not: Op.not,
    $in: Op.in,
    $notIn: Op.notIn,
    $is: Op.is,
    $like: Op.like,
    $notLike: Op.notLike,
    $iLike: Op.iLike,
    $notILike: Op.notILike,
    $regexp: Op.regexp,
    $notRegexp: Op.notRegexp,
    $iRegexp: Op.iRegexp,
    $notIRegexp: Op.notIRegexp,
    $between: Op.between,
    $notBetween: Op.notBetween,
    $overlap: Op.overlap,
    $contains: Op.contains,
    $contained: Op.contained,
    $adjacent: Op.adjacent,
    $strictLeft: Op.strictLeft,
    $strictRight: Op.strictRight,
    $noExtendRight: Op.noExtendRight,
    $noExtendLeft: Op.noExtendLeft,
    $and: Op.and,
    $or: Op.or,
    $any: Op.any,
    $all: Op.all,
    $values: Op.values,
    $col: Op.col
};

return new Sequelize(config.name, config.username, config.password, {
                        host: config.host,
                        dialect: 'mysql',
                        logging: false,
                        operatorsAliases:operatorsAliases
                    });
`

Im using Node 8.6.0 and Sequelize 4.13.8

This error shows between a certain time interval upon starting your Nodejs app
```
Unhandled rejection Error: Invalid value [object Object]
    at Object.escape (node_modules\sequelize\lib\sql-string.js:50:11)
    at Object.escape (node_modules\sequelize\lib\dialects\abstract\query-generator.js:919:22)
    at Object._whereParseSingleValueObject (\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2373:41)
    at Object.whereItemQuery (node_modules\sequelize\lib\dialects\abstract\query-generator.js:2078:21)
    at Utils.getComplexKeys.forEach.prop (node_modules\sequelize\lib\dialects\abstract\query-generator.js:1939:25)
    at Array.forEach (<anonymous>)
    at Object.whereItemsQuery (node_modules\sequelize\lib\dialects\abstract\query-generator.js:1937:35)
    at Object.getWhereConditions (node_modules\sequelize\lib\dialects\abstract\query-generator.js:2400:19)
    at Object.deleteQuery (node_modules\sequelize\lib\dialects\mysql\query-generator.js:181:18)
    at QueryInterface.bulkDelete (C:\Users\silica\Desktop\nodenative\node_modules\sequelize\lib\query-interface.js:1004:37)
    at Promise.try.then.then (node_modules\sequelize\lib\model.js:2499:36)
    at tryCatcher (nodenative\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

**Comment by sushantdhiman** [comment]
Code fails with whereItemQuery which indicates you used string operator, show me what Symbol based query is failing
