### ISSUE TITLE
Helpful error messages

### ISSUE THREAD

**Issue by Enitoni** [sequelize/sequelize#8505]
Let me start off by saying that Sequelize is an amazing tool and so far I think it is far better than whatever else is available on the market (except for a few things I would have done differently)

But I find myself often ripping my hair out using it, because as soon as you encounter an error, they are 90% of the time errors that are unhelpful and vague. Internal errors within sequelize itself are often exposed in the console and to a person that hasn't read the source code will have no idea what is wrong.

as an example:
I recently experienced the `self.$expandAttributes is not a function` error, and spent an hour trying to figure out was wrong, before I eventually realized that inside an include, a model was an empty object because of a faulty import. So then I wonder, why isn't there checks within Sequelize that would tell you of such trivial errors? An error like `You must specify a Sequelize model` (can be phrased in any way) would be infinitely more helpful and would alleviate the pain quicker.

And this is just one example, there are many times when I encounter SQL errors because of a malformed query, and me not being good with SQL chose an ORM just for the purpose of avoiding having to deal with SQL, so this is kinda nonsense to me.

Error checking is not hard to implement, so I would really appreciate it if Sequelize was easier to use in that regard.

**Comment by spacem** [comment]
I also would like to see better error messages from sequelize. I use sql-server and I have an upsert failing. When I run the query myself I can see this:
Violation of UNIQUE KEY constraint 'UQ_Pref_userId_type'. Cannot insert duplicate key in object 'dbo.Prefs'. The duplicate key value is (690a83fab3f88451c0ea2922, hierarchy-expand).

^ this I could diagnose but in my log file the exception from sequalise is not so helpful:

error:  SequelizeUniqueConstraintError: Validation error
    at Query.formatError (c:\work\project1\node_modules\sequelize\lib\dialects\mssql\query.js:300:14)
    at Request.connection.lib.Request [as userCallback] (c:\work\project1\node_modules\sequelize\lib\dialects\mssql\query.js:107:25)
    at Request._this.callback (c:\work\project1\node_modules\tedious\lib\request.js:47:27)
    at Connection.message (c:\work\project1\node_modules\tedious\lib\connection.js:1401:27)
    at Connection.dispatchEvent (c:\work\project1\node_modules\tedious\lib\connection.js:687:45)
    at MessageIO.<anonymous> (c:\work\project1\node_modules\tedious\lib\connection.js:602:18)
    at emitNone (events.js:105:13)
    at MessageIO.emit (events.js:207:7)
    at ReadablePacketStream.<anonymous> (c:\work\project1\node_modules\tedious\lib\message-io.js:102:16)
    at emitOne (events.js:115:13)
    at ReadablePacketStream.emit (events.js:210:7)
    at readableAddChunk (c:\work\project1\node_modules\readable-stream\lib\_stream_readable.js:211:18)
    at ReadablePacketStream.Readable.push (c:\work\project1\node_modules\readable-stream\lib\_stream_readable.js:170:10)
    at ReadablePacketStream.Transform.push (c:\work\project1\node_modules\readable-stream\lib\_stream_transform.js:123:32)
    at ReadablePacketStream._transform (c:\work\project1\node_modules\tedious\lib\message-io.js:70:16)
    at ReadablePacketStream.Transform._read (c:\work\project1\node_modules\readable-stream\lib\_stream_transform.js:159:10)
    at ReadablePacketStream.Transform._write (c:\work\project1\node_modules\readable-stream\lib\_stream_transform.js:147:83)
    at doWrite (c:\work\project1\node_modules\readable-stream\lib\_stream_writable.js:337:64)
    at writeOrBuffer (c:\work\project1\node_modules\readable-stream\lib\_stream_writable.js:326:5)
    at ReadablePacketStream.Writable.write (c:\work\project1\node_modules\readable-stream\lib\_stream_writable.js:263:11)
    at Socket.ondata (_stream_readable.js:628:20)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
