### ISSUE TITLE
V4 associations on Postgres

### ISSUE THREAD

**Issue by rzorzal** [sequelize/sequelize#8506]
Hello guys I have a problem with associations. I over 20 tables in my databases and I trying to migrate from sequelize v3 to v4. Considering I am using this repository as a copy of my, https://github.com/sequelize/express-example. My database is Postgres and  when I try to sync (with or not alter: true), the sequelize is executing that query for exemple: 

```
ALTER TABLE 'Tasks' DROP UserId;
```

I don't know whats is happening, but sometimes it create all tables, and sometimes don't.

**Comment by rzorzal** [comment]
Now I changing nothing in my code, and it create correctly. But if I put the alter: true, it throws an error

```
Unhandled rejection TypeError: Cannot read property '0' of undefined
    at query.catch.then.then.queryResult (/home/ricardo/Repositorios/cesta/back/node_modules/sequelize/lib/dialects/postgres/query.js:112:17)
    at tryCatcher (/home/ricardo/Repositorios/cesta/back/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ricardo/Repositorios/cesta/back/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ricardo/Repositorios/cesta/back/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ricardo/Repositorios/cesta/back/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ricardo/Repositorios/cesta/back/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/ricardo/Repositorios/cesta/back/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/ricardo/Repositorios/cesta/back/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/ricardo/Repositorios/cesta/back/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
```

after executing this statement here:

```
Executing (default): ALTER TABLE "Bairro" ALTER COLUMN "nome" DROP NOT NULL;ALTER TABLE "Bairro" ALTER COLUMN "nome" DROP DEFAULT;ALTER TABLE "Bairro" ALTER COLUMN "nome" TYPE VARCHAR(255);
```

And, again I don't know why it is dropping some attributes of column 'nome'

**Comment by alitaheri** [comment]
@rzorzal Please use `pg@6` we're not compatible with `pg@7` at the moment.

**Comment by rzorzal** [comment]
@alitaheri you are right, thanks a lot. Is there a place that having this version issue documentated ?

**Comment by rzorzal** [comment]
I downgrade to 3.30.4 version. Other problems was come. This new version is unstable and don't security for production.
