### ISSUE TITLE
The new arrow alias for nested includes breaks loading attributes into parent level

### ISSUE THREAD

**Issue by Fryuni** [sequelize/sequelize#8521]
The new arrow alias for the nested includes prevents loading attributes into parent level
## What are you doing?
```js
A.findAll({
  include: [{
    model: B,
    attributes: {
      include: [
        [Sequelize.col('C.google_id'), 'googleId']
      ]
    },
    include: [{
      model: C,
      attributes: []
    }]
  }]
})
```

## What do you expect to happen?
```js
[ A {
  id: 1,
  mail: "l@exemple.com",
  B: [{
    id: 1,
    AId: 1,
    CId: 3,
    googleId: "rf99999" //From C
  }]
}]
```

## What is actually happening?
```
{ Error: Unknown column 'B.C.google_id' in 'field list'
    at Packet.asError (/home/lotus/Documents/seq-test/node_modules/mysql2/lib/packets/packet.js:703:13)
    at Query.Command.execute (/home/lotus/Documents/seq-test/node_modules/mysql2/lib/commands/command.js:28:22)
    at Connection.handlePacket (/home/lotus/Documents/seq-test/node_modules/mysql2/lib/connection.js:515:28)
    at PacketParser.onPacket (/home/lotus/Documents/seq-test/node_modules/mysql2/lib/connection.js:94:16)
    at PacketParser.executeStart (/home/lotus/Documents/seq-test/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.<anonymous> (/home/lotus/Documents/seq-test/node_modules/mysql2/lib/connection.js:102:29)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:264:12)
    at readableAddChunk (_stream_readable.js:251:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onread (net.js:587:20)
     code: 'ER_BAD_FIELD_ERROR',
     errno: 1054,
     sqlState: '#42S22',
     sql: 'SELECT `A`.`id`, `A`.`mail`, `B`.`id` AS `B.id`, `B`.`AId` AS `B.AId`, `B`.`CId` AS `B.CId`, `B`.`C.google_id` AS `B.googleId` FROM `A` AS `A` LEFT OUTER JOIN `B` AS `B` ON `A`.`id` = `B`.`AId` LEFT OUTER JOIN `C` AS `B->C` ON `B`.`CId` = `B->C`.`id`;' }
```

Dialect: mysql
Database version: 5.7.19-0ubuntu0.17.04.1
Sequelize version: 4.16.1
Tested with master branch: Yes

**Comment by pickfire** [comment]
This is still an issue in sequelize v5.

**Comment by lucasgouvea** [comment]
Having the same problem with v5.8.6

**Comment by ephys** [comment]
We don't support loading the attribute of one association inside of a different association
