### ISSUE TITLE
TypeError: Cannot read property 'createdAt' of undefined

### ISSUE THREAD

**Issue by pirmax** [sequelize/sequelize#8524]
## What are you doing?
I have a problem with Sequelize and CreatedAt column. When I want to insert data in MySQL database, I get this error...

> TypeError: Cannot read property 'createdAt' of undefined
    at Delivery._initValues (/app/node_modules/sequelize/lib/model.js:3033:48)
    at Delivery.Model (/app/node_modules/sequelize/lib/model.js:3007:10)
    at Model (/app/node_modules/sequelize-typescript/lib/models/v4/Model.js:8:9)
    at Delivery (/app/src/Common/Domain/Entity/Delivery.js:22:16)
    at DeliveryRepository.create (/app/src/Common/Infrastructure/Persistence/Sequelize/DeliveryRepository.js:21:16)
    at /app/src/Backend/Application/Function/apiWebhook.js:39:57
    at next (native)
    at fulfilled (/app/src/Backend/Application/Function/apiWebhook.js:4:58)

```js
import {
    BelongsTo,
    Column,
    CreatedAt,
    DataType,
    DeletedAt,
    ForeignKey,
    Model,
    Table,
    Unique,
    UpdatedAt
} from "sequelize-typescript";
import {Segment} from "./Segment";
import {SegmentInterface} from "./SegmentInterface";

@Table({
    timestamps: true,
    tableName: "delivery"
})
export class Delivery extends Model<Delivery> {
    @Column({primaryKey: true})
    public id: number;

    @Unique
    @Column(DataType.STRING)
    public uuid: string;

    @Column(DataType.TEXT)
    public parameters: string;

    @DeletedAt
    public deletedAt: Date;

    @CreatedAt
    public createdAt: Date;

    @UpdatedAt
    public updatedAt: Date;
}
```

**Comment by pirmax** [comment]
Issue resolved.
