### ISSUE TITLE
Unable to create indices with GIN or GIST

### ISSUE THREAD

**Issue by mkondel** [sequelize/sequelize#8553]
## What are you doing?

```js
const Sequelize = require('sequelize');
const sequelize = new Sequelize('postgres://DB_CONNECTION_STRING');

// Test model
const Test1 = sequelize.define('test1',
    {
        id: {
            type: Sequelize.STRING,
            unique: true,
            allowNull: false,
            primaryKey: true,
        },
        title: { type: Sequelize.TEXT },
        description: { type: Sequelize.TEXT },
    },{
        indexes: [{
            fields: ['description'],
            using: 'gin',
            operator: 'text_pattern_ops',
        }],
    });

sequelize
.sync({force:true})
.then(()=>{
    console.log('sync');
    return Test1.create({
        id: 'foo1',
        title: 'foo1-title',
        description: 'A paragraph consists of one or more sentences.',
    });
})
.then(item=>{ 
    console.dir(item.toJSON())
    process.exit();
})
.catch(error=>{
    console.error(error)
    process.exit();
})
```

## What do you expect to happen?
- Table and index get created during sync(). 
- Test instance gets created with id, title, description fields.
- New instance gets printed as JSON.

## What is actually happening?
```Executing (default): DROP TABLE IF EXISTS "test1s" CASCADE;
Executing (default): DROP TABLE IF EXISTS "test1s" CASCADE;
Executing (default): CREATE TABLE IF NOT EXISTS "test1s" ("id" VARCHAR(255) NOT NULL UNIQUE , "title" TEXT, "description" TEXT, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, UNIQUE ("id"), PRIMARY KEY ("id"));
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'test1s' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
Executing (default): CREATE INDEX "test1s_description" ON "test1s" USING gin ("description" text_pattern_ops)
{ SequelizeDatabaseError: operator class "text_pattern_ops" does not exist for access method "gin"
    at Query.formatError (/testing/pgtest/node_modules/sequelize/lib/dialects/postgres/query.js:338:16)
    at query.catch.err (/testing/pgtest/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)
    at tryCatcher (/testing/pgtest/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/testing/pgtest/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/testing/pgtest/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/testing/pgtest/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/testing/pgtest/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/testing/pgtest/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/testing/pgtest/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/testing/pgtest/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
  name: 'SequelizeDatabaseError',
  parent: 
   { error: operator class "text_pattern_ops" does not exist for access method "gin"
    at Connection.parseE (/testing/pgtest/node_modules/pg/lib/connection.js:546:11)
    at Connection.parseMessage (/testing/pgtest/node_modules/pg/lib/connection.js:371:19)
    at Socket.<anonymous> (/testing/pgtest/node_modules/pg/lib/connection.js:114:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:587:20)
     name: 'error',
     length: 136,
     severity: 'ERROR',
     code: '42704',
     detail: undefined,
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'indexcmds.c',
     line: '1336',
     routine: 'GetIndexOpClass',
     sql: 'CREATE INDEX "test1s_description" ON "test1s" USING gin ("description" text_pattern_ops)' },
  original: 
   { error: operator class "text_pattern_ops" does not exist for access method "gin"
    at Connection.parseE (/testing/pgtest/node_modules/pg/lib/connection.js:546:11)
    at Connection.parseMessage (/testing/pgtest/node_modules/pg/lib/connection.js:371:19)
    at Socket.<anonymous> (/testing/pgtest/node_modules/pg/lib/connection.js:114:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:587:20)
     name: 'error',
     length: 136,
     severity: 'ERROR',
     code: '42704',
     detail: undefined,
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'indexcmds.c',
     line: '1336',
     routine: 'GetIndexOpClass',
     sql: 'CREATE INDEX "test1s_description" ON "test1s" USING gin ("description" text_pattern_ops)' },
  sql: 'CREATE INDEX "test1s_description" ON "test1s" USING gin ("description" text_pattern_ops)' }
```

__Dialect:__ postgres
__Dialect version:__ 7.1.2
__Database version:__ 9.6.2
__Sequelize version:__ 4.18.0
__Tested with master branch:__ No

**Note :** _Your issue may be ignored by maintainers if it's not tested against `master` branch OR does not follow issue template._

**Comment by sushantdhiman** [comment]
IMO `operator class "text_pattern_ops" does not exist for access method "gin"` look related to database engine.

Are you sure this is sequelize related and you can create a `gin` index with similar conditions on psql?

**Comment by mkondel** [comment]
You are correct, I was trying to do something PostgreSQL does not support. It cannot build an full-text index on a TEXT field. Either use _ts_vector(text_field_name)_ or change TEXT type to _ARRAY(TEXT)_.

_So either this, and nothing needs to be done in SQL:_
```javascript
        description: {
            type: Sequelize.ARRAY(Sequelize.TEXT),
            set(new_val){
                this.setDataValue('description', new_val.split(','));
            }
        },
    },{
        indexes: [{
            fields: ['description'],
            using: 'gin',
        }],
    });
```

_Or this:_
```javascript
description: { type: Sequelize.TEXT },
// no index defined in model
```
Then in plain SQL this will work, but how can I do this same thing in the Sequelize model?
```SQL
CREATE INDEX test_index ON test1s USING GIN(to_tsvector('english', "description"))
```

**Comment by nabeards** [comment]
I would also like to know how specify the full-text index on a JSONB column in Sequelize, which is now supported in postgres 10+.

`CREATE INDEX ON test1s USING GIN(to_tsvector('english', jsondata))`

**Comment by sushantdhiman** [comment]
Ah, this is not supported, I am tagging this as a feature request. Can you suggest an API for this sort of index.

**Comment by nabeards** [comment]
@sushantdhiman something like this?

```
{
    jsondata: {
        type: Sequelize.JSONB
    }
},{
    indexes: [{
        fields: ['jsondata'],
        using: 'gin',
        operator: 'to_tsvector',
        language: 'english'
    }]
});
```

**Comment by saharshpruthi** [comment]
sequelize.define
  (
    ‘Table name’,
    {
      id :
      {
        type       : DataTypes.INTEGER(),
        primaryKey : true
      },
      loc       :
      {
        type      : DataTypes.GEOMETRY('POINT', '4326'),
        allowNull : false
      }
    },
    {
      indexes : [
        		     {
         				fields : ['loc'],
          			        using  : 'gist'
        		     }
      		     ]
    }
  );

**Comment by saharshpruthi** [comment]
sequelize.define
  (
    ‘Table name’,
    {
      id :
      {
        type       : DataTypes.INTEGER(),
        primaryKey : true
      },
      loc       :
      {
        type      : DataTypes.GEOMETRY('POINT', '4326'),
        allowNull : false
      }
    },
    {
      indexes : [
        	     {
         				fields : ['loc'],
          			        using  : 'gist'
        		     }
      		     ]
    }
  );`
`

**Comment by saharshpruthi** [comment]
`sequelize.define (
 ‘Table name’,
{
id :
      {
        type       : DataTypes.INTEGER(),
        primaryKey : true
      },
      loc       :
      {
        type      : DataTypes.GEOMETRY('POINT', '4326'),
        allowNull : false
      }
    },
    {
      indexes : [
        	     {fields : ['loc'],
          			        using  : 'gist'
        		     }
      		     ]
    }
  );`

**Comment by leonardorb** [comment]
@sushantdhiman any updates on this?

**Comment by nabeards** [comment]
Is this something that may still be happening?

**Comment by papb** [comment]
@nabeards The feature was not implemented yet. If you are willing to submit a PR that would be great!

**Comment by zbinlin** [comment]
> I would also like to know how specify the full-text index on a JSONB column in Sequelize, which is now supported in postgres 10+.
> 
> `CREATE INDEX ON test1s USING GIN(to_tsvector('english', jsondata))`

It look like you could use:

```js
        indexes: [{
          name: 'test1_description',
          fields: [fn('to_tsvector', 'english', col('description'))],
          using: 'gin',
        }],
```
to create an index.
The result:

```sql
CREATE INDEX "test1_description" ON "test1" USING gin (to_tsvector('english', "description"))
```
But in the typescript, the `fn` type is incompatible fields item type, but we can use `fn(...) as unknown as string` to temp fix it.

@nabeards @sushantdhiman
