### ISSUE TITLE
Error 'values.map is not a function' when using Op.like inside Op.contains

### ISSUE THREAD

**Issue by mkondel** [sequelize/sequelize#8564]
## What are you doing?

```js
const Sequelize = require('sequelize');
const sequelize = new Sequelize('postgres://DB_CONNECTION_STRING');

// Test model
const Test1 = sequelize.define('test1',
    {
        id: {
            type: Sequelize.STRING,
            unique: true,
            allowNull: false,
            primaryKey: true,
        },
        colors: { 
            type: Sequelize.ARRAY(Sequelize.TEXT),
            set(new_colors) {
                const colors_array = new_colors
                    // split on comma
                    .split(',')
                    // trim whitespace
                    .map(kw1=>kw1.trim())
                    // filter out empty strings
                    .filter(kw2=>kw2)
                // set colors to be the new multi valued string
                this.setDataValue('colors', colors_array);
            },
        },
    }
);

sequelize
.sync({force:true})
.then(()=>{
    console.log('sync');
    const colors1 = 'red, green,blue,red';

    return Test1.create({
        id: 'foo1',
        title: 'foo1-title',
        colors: colors1,
    })
})
.then(()=>Test1.find({
    where: {
        colors: {
            [sequelize.Op.contains]: {
                [sequelize.Op.like]: 're%'
            }
        }
    }
}))
.then(item2=>{ 
    console.dir(item2.toJSON())
    process.exit();
})
.catch(error=>{
    console.error(error)
    process.exit();
})

```

## What do you expect to happen?
A record 'foo1' gets created with colors=['red','green','blue','red']. A query for 'red%' should return this record.

## What is actually happening?
Executing (default): DROP TABLE IF EXISTS "test1s" CASCADE;
Executing (default): DROP TABLE IF EXISTS "test1s" CASCADE;
Executing (default): CREATE TABLE IF NOT EXISTS "test1s" ("id" VARCHAR(255) NOT NULL UNIQUE , "colors" TEXT[], "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, UNIQUE ("id"), PRIMARY KEY ("id"));
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'test1s' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
sync
Executing (default): INSERT INTO "test1s" ("id","colors","createdAt","updatedAt") VALUES ('foo1',ARRAY['red','green','blue','red']::TEXT[],'2017-10-30 15:17:34.127 +00:00','2017-10-30 15:17:34.127 +00:00') RETURNING *;
TypeError: values.map is not a function
    at ARRAY._stringify (/pgtest/node_modules/sequelize/lib/dialects/postgres/data-types.js:565:33)
    at ARRAY.stringify (/pgtest/node_modules/sequelize/lib/data-types.js:32:17)
    at Object.escape (/pgtest/node_modules/sequelize/lib/dialects/abstract/query-generator.js:913:32)
    at Object._whereParseSingleValueObject (/pgtest/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2383:41)
    at Object.whereItemQuery (/pgtest/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2081:21)
    at Utils.getComplexKeys.forEach.prop (/pgtest/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1944:25)
    at Array.forEach (<anonymous>)
    at Object.whereItemsQuery (/pgtest/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1942:35)
    at Object.getWhereConditions (/pgtest/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2410:19)
    at Object.selectQuery (/pgtest/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1130:28)
    at QueryInterface.select (/pgtest/node_modules/sequelize/lib/query-interface.js:1018:27)
    at Promise.try.then.then.then (/pgtest/node_modules/sequelize/lib/model.js:1563:34)
    at tryCatcher (/pgtest/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/pgtest/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/pgtest/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/pgtest/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/pgtest/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/pgtest/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/pgtest/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/pgtest/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)

__Dialect:__ postgres
__Dialect version:__ 7.1.2
__Database version:__ 9.6.2
__Sequelize version:__ 4.18.0
__Tested with master branch:__ No

**Note :** _Your issue may be ignored by maintainers if it's not tested against `master` branch OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Have you tried `pg@6`, there is a known issue with pg@7 where sequelize wont handle multiple results set properly.

**Comment by mkondel** [comment]
Removed pg, added pg@6, but still get the same error.

**Comment by LoganArnett** [comment]
Any updates on this? I am getting the same error when trying to update an Array value with additional items, if there is only one element added to the Array it is ok, as soon as I add an additional item it throws this same error

**Comment by iwaffles** [comment]
I'm seeing this error as well with `$contains: { tags: ['red'], ['blue'] }`

**Comment by jkruse14** [comment]
I'm seeing this as well with

```
    const innerSelect = sequelize.dialect.QueryGenerator.selectQuery('cdn', {
            attributes: ['id'],
            where: {
                hasDelay: true,
            },
        }).slice(0, -1);

        return this.model.count({
            where: {
                field1: {
                    [Op.eq]: null,
                },
                cdnId: {
                   [Op.in]: `(${innerSelect})`,
                },
            },
        });
```

**Comment by GuoYuebo** [comment]
I see
```
    where: {
        colors: {
            [sequelize.Op.contains]: {
                [sequelize.Op.like]: 're%'
            }
        }
    }
```
the value of [sequelize.Op.contains] should be an array, maybe you can change it to
```
    where: {
        colors: {
            [sequelize.Op.contains]: [{
                [sequelize.Op.like]: 're%'
            }]
        }
    }

```

**Comment by doron2402** [comment]
having a similar issue when trying to find `not contains` for now I'll use raw sql


```js
where['<COL_NAME>'][Op.and] = [Sequelize.literal(`'${JS_VARIABLE_ARRAY}' != all (<COL_NAME>)`)];
```

**Comment by codetelo** [comment]
I was experiencing the same problem. I had to do a work around and change the charvar[] to charvar and just did Op.iLike to look through the entire string.  Then later i can just pull it all down and split it by the comma. In summary, I look through the text for the query instead of through an array.

**Comment by doron2402** [comment]
There are numbers of advantages for using an array column type in Postgres. You shouldn't change your table data structure just because your ORM is not supporting it.

**Comment by codetelo** [comment]
Just providing a workaround until the issue is resolved, in a different way from you. While there are advantages to using the array column type in Postgres, for my specific problem, this was the solution that worked for me without having to do much work to change it. I'm pretty inexperienced with Sequelize, but I still wanted to leverage it if I could and this was the way that I could still use it.

**Comment by ImangazalievM** [comment]
@sushantdhiman @papb Hi! Are there any updates? I have the same bug.

**Dialect:** postgres
**PostgreSQL:** 12.1
**Sequelize version:** 5.21.3

Query sample:

```typescript
Articles.findAll({
   where:  { searchKeyWords: { [Op.like]: '%' + searchQuery + '%' } }
})
```

Stacktrace:

```
TypeError: values.map is not a function
    at ARRAY._value (D:\MyProject\node_modules\sequelize\lib\dialects\postgres\data-types.js:458:19)
    at ARRAY._stringify (D:\MyProject\node_modules\sequelize\lib\dialects\postgres\data-types.js:473:29)
    at ARRAY.stringify (D:\MyProject\Kalimat\node_modules\sequelize\lib\data-types.js:23:19)
    at PostgresQueryGenerator.escape (D:\MyProject\node_modules\sequelize\lib\dialects\abstract\query-generator.js:976:30)
    at PostgresQueryGenerator._whereParseSingleValueObject (D:\MyProject\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2556:41)
    at PostgresQueryGenerator.whereItemQuery (D:\MyProject\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2272:21)
    at Utils.getComplexKeys.forEach.prop (D:\MyProject\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2173:25)
    at Array.forEach (<anonymous>)
```

**Comment by papb** [comment]
@ImangazalievM Hello, no updates.

Also I was [not even able to reproduce](https://travis-ci.com/papb/sequelize-sscce/jobs/277234915).

Please only ping maintainers with clearly reproducible things, our time is very short

**Comment by IgorXVI** [comment]
Just try to do a raw insert with sequelize.query, like this:
```javascript
sequelize.query(`
	INSERT INTO pendency(
		party_survey_id, 
		kpi_survey_id,
		deadline,
		description,
		status,
		responsible_party_id, 
		created_by, 
		updated_by, 
		created_at, 
		updated_at
		)
	VALUES (
		1,
		20,
		NOW(),
		"oloco bicho",
		"pending",
		3,
		"email@email.com",
		"email@email.com",
		NOW(),
		NOW()
	)
`, {
	bind,
	transaction,
	type: sequelize.QueryTypes.SELECT,
	raw: true
})
```
with the follwoing configurations:
```javascript
module.exports = {
  development: {
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_NAME,
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    dialect: 'mysql',
    pool: {
      max: 5,
      min: 0,
      idle: 1000,
    },
    define: {
      underscored: true,
      freezeTableName: true,
      timestamps: true
    }
  }
}
```
i also receive a "TypeError: results.map is not a function" when the above code is executed

**Comment by thomasdissert** [comment]
> I see
> 
> ```
>     where: {
>         colors: {
>             [sequelize.Op.contains]: {
>                 [sequelize.Op.like]: 're%'
>             }
>         }
>     }
> ```
> 
> the value of [sequelize.Op.contains] should be an array, maybe you can change it to
> 
> ```
>     where: {
>         colors: {
>             [sequelize.Op.contains]: [{
>                 [sequelize.Op.like]: 're%'
>             }]
>         }
>     }
> ```

I think I've managed to achieve what you are looking for like that: 

```
Sequelize.where(Sequelize.fn('ARRAY_TO_STRING', Sequelize.col('colors'), ','), 'ILIKE', 're%')
```

**Comment by Zlkva** [comment]
> 
> I think I've managed to achieve what you are looking for like that:
> 
> ```
> Sequelize.where(Sequelize.fn('ARRAY_TO_STRING', Sequelize.col('colors'), ','), 'ILIKE', 're%')
> ```

Amazing job, this is a valid fix!
