### ISSUE TITLE
Configuration attribute `comment` throw error 

### ISSUE THREAD

**Issue by Aleksey-Danchin** [sequelize/sequelize#8568]
When define the sequelize model with a `comment` param exists error: `Unhandled rejection TypeError: Cannot read property '0' of undefined`.

Code example:
```javascript
const User = sequelize.define('user', {
	family: {
		type: Sequelize.STRING,
		allowNull: false
	}
}, {
	comment: "Пользователи системы"
});


User.sync({ force: true })
```

Error declaration

```
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators ../node_modules/sequelize/lib/sequelize.js:236:13
Executing (default): DROP TABLE IF EXISTS "users" CASCADE;
Executing (default): CREATE TABLE IF NOT EXISTS "users" ("id"   SERIAL , "family" VARCHAR(255) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id")); COMMENT ON TABLE "users" IS 'Пользователи системы';
Unhandled rejection TypeError: Cannot read property '0' of undefined
    at query.catch.then.then.queryResult (/home/old/Desktop/pro/node_modules/sequelize/lib/dialects/postgres/query.js:112:17)
    at tryCatcher (/home/old/Desktop/pro/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/old/Desktop/pro/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/old/Desktop/pro/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/old/Desktop/pro/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/old/Desktop/pro/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/old/Desktop/pro/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/old/Desktop/pro/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/old/Desktop/pro/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5
```

Environment state
node -v -> v8.5.0
npm -v -> 5.5.1
psql --version -> psql (PostgreSQL) 9.6.5

**Comment by sushantdhiman** [comment]
I dont think we support `comment` property

**Comment by iamjochem** [comment]
comment is supported, at least so far as the docs go:

http://sequelize.readthedocs.io/en/v3/docs/models-definition/#configuration

quote from the docs:
### Finally you can specify a comment for the table in MySQL and PG
```js
var Person = sequelize.define('person', { /* attributes */ }, {
  comment: "I'm a table comment!"
})
```

**Comment by sushantdhiman** [comment]
Looks like both PG and MySQL supports it

**Comment by zauberpony** [comment]
Same error here. This happens not only for "comments", but anytime when "queryResults" (https://github.com/sequelize/sequelize/blob/0047dca9dffe9133ae231d7e0de50bca5714634a/lib/dialects/postgres/query.js#L97) is an array.
This happens for sql-strings with multiple queries (separated by ";").

e.g., Alekseys sample yields "CREATE TABLE IF NOT EXISTS "…" (…); COMMENT ON TABLE "…" IS '…';

I have a migration that resolves to three ALTER queries, which triggers the same error.

**Comment by sushantdhiman** [comment]
Are you by chance using p@7 @zauberpony, we dont support it yet. Readme mentions this as well

**Comment by zauberpony** [comment]
@sushantdhiman correct, thanks. Just did an upgrade of all modules and ran tests.

This should also fix @Aleksey-Danchin initial comment-issue (at least downgrading to pg@6) fixed also the model with comment for me.

**Comment by sushantdhiman** [comment]
Yep seems like it
