### ISSUE TITLE
Sequelize cannot join two tables in an autoincrement many-to-many

### ISSUE THREAD

**Issue by NobleUplift** [sequelize/sequelize#8576]
## What are you doing?

I have a table that needs to be joined with another table through a man-to-many, but that many-to-many is based on a synthetic key, not a compound primary key. No matter what I have tried, the generated query always fails.

```sql
CREATE TABLE `asset_master` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL DEFAULT '',
  `md5sum` varchar(32) NOT NULL DEFAULT '',
  `width` smallint(6) unsigned NOT NULL DEFAULT '0',
  `height` smallint(6) unsigned NOT NULL DEFAULT '0',
  `size` int(11) unsigned NOT NULL DEFAULT '0',
  `dpi` varchar(50) NOT NULL DEFAULT '',
  `update_date` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `update_by` bigint(20) unsigned NOT NULL DEFAULT '1',
  `create_date` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `create_by` bigint(20) unsigned NOT NULL DEFAULT '1',
  `enabled` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `asset_type_id` smallint(6) unsigned NOT NULL,
  `process_status_id` bigint(20) NOT NULL DEFAULT '1',
  `process_status_modified_date` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `pipeline_status` varchar(255) DEFAULT NULL,
  `pipeline_guid` varchar(255) DEFAULT NULL,
  `pipeline_actions_json` longtext,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name_UNIQUE` (`name`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  UNIQUE KEY `md5sum_UNIQUE` (`md5sum`),
  KEY `account_asset_tags_account_asset_fk` (`asset_type_id`),
  CONSTRAINT `account_asset_tags_account_asset_fk` FOREIGN KEY (`asset_type_id`) REFERENCES `asset_types` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=50426 DEFAULT CHARSET=utf8;

CREATE TABLE `account_asset` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `account_id` bigint(20) unsigned NOT NULL,
  `asset_id` bigint(20) unsigned NOT NULL,
  `name` varchar(255) NOT NULL DEFAULT '',
  `thumbnail_name` varchar(255) NOT NULL DEFAULT '',
  `enabled` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `createdby` bigint(20) unsigned NOT NULL DEFAULT '1',
  `createdate` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `updateby` bigint(20) unsigned NOT NULL DEFAULT '1',
  `updatedate` datetime NOT NULL DEFAULT '0001-01-01 00:00:00',
  `content_type` varchar(45) DEFAULT NULL,
  `content_value` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `account_asset_asset_fk` (`asset_id`),
  KEY `account_asset_account_fk` (`account_id`),
  CONSTRAINT `account_asset_account_fk` FOREIGN KEY (`account_id`) REFERENCES `account` (`id`),
  CONSTRAINT `account_asset_asset_fk` FOREIGN KEY (`asset_id`) REFERENCES `asset_master` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=81991 DEFAULT CHARSET=utf8;

CREATE TABLE `account_asset_folder_assignment` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `account_asset_id` bigint(20) unsigned NOT NULL,
  `account_asset_folder_id` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `account_asset_folder_assignment_folder_fk` (`account_asset_folder_id`),
  KEY `account_asset_folder_assignment_account_asset_fk` (`account_asset_id`),
  CONSTRAINT `account_asset_folder_assignment_account_asset_fk` FOREIGN KEY (`account_asset_id`) REFERENCES `account_asset` (`id`),
  CONSTRAINT `account_asset_folder_assignment_folder_fk` FOREIGN KEY (`account_asset_folder_id`) REFERENCES `account_asset_folder` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=83039 DEFAULT CHARSET=utf8;

CREATE TABLE `account_asset_folder` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `account_id` bigint(20) unsigned NOT NULL,
  `name` varchar(100) NOT NULL DEFAULT '',
  `enabled` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `parent_folder_id` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `account_asset_folder_fk` (`account_id`),
  CONSTRAINT `account_asset_folder_fk` FOREIGN KEY (`account_id`) REFERENCES `account` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=10041 DEFAULT CHARSET=utf8;
```

```js
		account_asset.belongsToMany(account_asset_folder, {through: account_asset_folder_assignment});
		account_asset_folder.belongsToMany(account_asset, {through: account_asset_folder_assignment});

		var asset_master = Database.getInstance().getModel("asset_master");
		console.log(asset_master.getTableName());
		var account_asset_folder_assignment = Database.getInstance().getModel("account_asset_folder_assignment");
		console.log(account_asset_folder_assignment.getTableName());
		var account_asset_folder = Database.getInstance().getModel("account_asset_folder");
		console.log(account_asset_folder.getTableName());
		var queryParameters = { attributes: 
		   [ //[ 'id', 'id' ],
		     [ 'account_id', 'accountId' ],
		     [ 'asset_id', 'assetId' ],
		     [ 'name', 'name' ],
		     [ 'thumbnail_name', 'thumbnailName' ],
		     [ 'enabled', 'enabled' ],
		     [ 'createdby', 'createdby' ],
		     [ 'createdate', 'createdate' ],
		     [ 'updateby', 'updateby' ],
		     [ 'updatedate', 'updatedate' ],
		     [ 'content_type', 'contentType' ],
		     [ 'content_value', 'contentValue' ] ],
		  include: 
		   [ { model: asset_master },
		     { model: account_asset_folder_assignment, through: { attributes: [] } } ],
		  where: { account_id: '100' },
		  order: [ [ 'name', 'asc' ] ],
		  limit: 100,
		  offset: 0 };

		Database.getInstance().getModel('account_asset').findAll(queryParameters).then((databaseObjects) => {
			for (var databaseObject of databaseObject) {
				console.log(databaseObject);
				res.locals.retval.addData(databaseObject);
			}
		});
```

## What do you expect to happen?
I expected it to join the account_asset table to the account_asset_folder table through the account_asset_folder_assignment table, returning a row for each account_asset-account_asset_folder pair.

## What is actually happening?
```
Unhandled rejection TypeError: Cannot read property 'getTableName' of undefined
    at generateJoinQueries (/Library/WebServer/adstudio/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1176:43)
    at Object.<anonymous> (/Library/WebServer/adstudio/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1408:27)
    at Array.forEach (native)
    at Object.selectQuery (/Library/WebServer/adstudio/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1407:10)
    at QueryInterface.select (/Library/WebServer/adstudio/node_modules/sequelize/lib/query-interface.js:669:25)
    at Model.<anonymous> (/Library/WebServer/adstudio/node_modules/sequelize/lib/model.js:1398:32)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
From previous event:
    at Promise.then (/Library/WebServer/adstudio/node_modules/sequelize/lib/promise.js:21:17)
    at Model.findAll (/Library/WebServer/adstudio/node_modules/sequelize/lib/model.js:1395:6)
    at get (/Library/WebServer/adstudio/dist/routes/sandbox.js:41:69)
    at Layer.handle [as handle_request] (/Library/WebServer/adstudio/node_modules/express/lib/router/layer.js:95:5)
    at next (/Library/WebServer/adstudio/node_modules/express/lib/router/route.js:137:13)
    at isAuthorized (/Library/WebServer/adstudio/dist/server.js:345:20)
    at Layer.handle [as handle_request] (/Library/WebServer/adstudio/node_modules/express/lib/router/layer.js:95:5)
    at next (/Library/WebServer/adstudio/node_modules/express/lib/router/route.js:137:13)
    at isAuthenticated (/Library/WebServer/adstudio/dist/server.js:336:16)
    at Layer.handle [as handle_request] (/Library/WebServer/adstudio/node_modules/express/lib/router/layer.js:95:5)
    at next (/Library/WebServer/adstudio/node_modules/express/lib/router/route.js:137:13)
    at initialize (/Library/WebServer/adstudio/dist/server.js:321:16)
    at Layer.handle [as handle_request] (/Library/WebServer/adstudio/node_modules/express/lib/router/layer.js:95:5)
    at next (/Library/WebServer/adstudio/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Library/WebServer/adstudio/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Library/WebServer/adstudio/node_modules/express/lib/router/layer.js:95:5)
    at /Library/WebServer/adstudio/node_modules/express/lib/router/index.js:281:22
    at param (/Library/WebServer/adstudio/node_modules/express/lib/router/index.js:354:14)
    at param (/Library/WebServer/adstudio/node_modules/express/lib/router/index.js:365:14)
```

__Dialect:__ mysql
__Dialect version:__ 14.14
__Database version:__ 5.6.35
__Sequelize version:__ 3.30.4
__Tested with master branch:__ No

**Note :** _Your issue may be ignored by maintainers if it's not tested against `master` branch OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Sorry your example is too big to study and we dont support v3 any more. If you can distill your example to minimal case I might be able to help

**Comment by NobleUplift** [comment]
Upgrading to Sequelize 4.22.5 and adding aliases/foreign keys to my many-to-many fixed this issue:

			AccountAsset.belongsToMany(AccountAssetFolder, {as: 'AccountAssetFolders', foreignKey: 'account_asset_id', through: 'account_asset_folder_assignment'});
			console.log(AccountAsset + ' belongs to many ' + AccountAssetFolder + '.');
			AccountAssetFolder.belongsToMany(AccountAsset, {as: 'AccountAssets', foreignKey: 'account_asset_folder_id', through: 'account_asset_folder_assignment'});
			console.log(AccountAssetFolder + ' belongs to many ' + AccountAsset + '.');

Thanks for the help.
