### ISSUE TITLE
SequelizeValidationError: notNull Violation when removing created associations via set method

### ISSUE THREAD

**Issue by charlieargue** [sequelize/sequelize#8588]
## What are you doing?

Hi! Thanks in advance for any help you can provide!

Given model `user_account`:
```js
'user_account',
    {
      _id: {
        type: DataTypes.INTEGER,
        field: "_id",
        autoIncrement: !0,
        primaryKey: !0
      },
      email: {
        type: DataTypes.STRING,
        allowNull: false,
        validate: {
          isEmail: true
        },
        unique: true
      },
      firstName: {
        type: DataTypes.STRING,
        allowNull: true
      },
    }
```
that hasMany():
```
user_account.hasMany(models.user_activity_history,  { foreignKey: 'userAccountId', as: 'ActivityHistory'});
```
activity histories, defined as:
```js
'user_activity_history', {
      _id: {
        type: DataTypes.INTEGER,
        field: "_id",
        autoIncrement: !0,
        primaryKey: !0
      },
      userAccountId: {
        type: DataTypes.INTEGER,
        allowNull: false,
        references: {
          model: '_user_account',
          key: '_id'
        }
      },
      activity: {
        type: DataTypes.STRING,
        allowNull: false
      },
    }
```
I'm able to use **some prototype getter/setter** auto-generated functions, but now others? Assuming I've created a user:
```js
models._EXAMPLES.user_account.create({ email: _email }).then((newUser) => {
...
```
I **can successfully** make these calls:
```js
return newUser.createActivityHistory({ activity: 'new activity' });
...
return newUser.getActivityHistory();
...
return newUser.countActivityHistory();
...
return newUser.hasActivityHistory(_newActivity);
...
```
`However, when I call this one` I get a **SequelizeValidationError: notNull Violation: userAccountId cannot be null** ERROR:
```js
return newUser.setActivityHistory([]);
```

## What do you expect to happen?
I expected like the [tutorial says](http://docs.sequelizejs.com/manual/tutorial/associations.html) to:
```
To remove created associations you can just call the set method without a specific id:
// remove 'em all
project.setTasks([]).then(associatedTasks => {
  // you will get an empty array
})
```

## What is actually happening?
I get the `ERROR`:
```
Unhandled rejection SequelizeValidationError: notNull Violation: userAccountId cannot be null
    at Promise.all.then (/Users/kgolka/PROJECTS/examples-sequelize/node_modules/sequelize/lib/instance-validator.js:77:15)
    at tryCatcher (/Users/kgolka/PROJECTS/examples-sequelize/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/kgolka/PROJECTS/examples-sequelize/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/kgolka/PROJECTS/examples-sequelize/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/kgolka/PROJECTS/examples-sequelize/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/kgolka/PROJECTS/examples-sequelize/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/kgolka/PROJECTS/examples-sequelize/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/Users/kgolka/PROJECTS/examples-sequelize/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/Users/kgolka/PROJECTS/examples-sequelize/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/Users/kgolka/PROJECTS/examples-sequelize/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/Users/kgolka/PROJECTS/examples-sequelize/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/kgolka/PROJECTS/examples-sequelize/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/kgolka/PROJECTS/examples-sequelize/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/kgolka/PROJECTS/examples-sequelize/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/kgolka/PROJECTS/examples-sequelize/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

__Dialect:__ mssql
__Dialect version:__ ?
__Database version:__ SQL Server 2014
__Sequelize version:__ ORM: 4.7.5
__Tested with master branch:__ No

`BTW - this is also happening in another scenario:`
```
a belongsToMany() association, but the error there is the same as here AND often an aggregate error? I'll leave that for after this ticket... thx again!
```

**Note :** _Your issue may be ignored by maintainers if it's not tested against `master` branch OR does not follow issue template._

**Comment by charlieargue** [comment]
Update, I have tracked down the issue in more detail. 

When I remove the `allowNull: false` from *user_activity_history.userAccountId* it now works!

But I need that constraint... perhaps re-ordering, I've read some posts that order matters of these schema properties?...

**Comment by sushantdhiman** [comment]
Known issue https://github.com/sequelize/sequelize/issues/4708

**Comment by CynthiaWahome** [comment]
@charlieargue setting this to `allowNull: true` that has also worked for me.
Anyone with an idea of how to make this work with `allowNull: false`?
