### ISSUE TITLE
findOrCreate and PostgreSQL. SequelizeUniqueConstraintError with date and concurrence. +00 vs. Z

### ISSUE THREAD

**Issue by dayer3** [sequelize/sequelize#8628]
## What are you doing?

Model:
```js
const Pasada = sequelize.define('Pasada', {
	id_pasada: {
		type: DataTypes.BIGINT,
		allowNull: false,
		autoIncrement: true,
		primaryKey: true
	},
	fecha: {
		type: DataTypes.DATE,
		allowNull: false,
		unique: true
	}
});
```
Action (within a previously created transaction):
```js
let ts = "2017-11-13T09:50:00.000Z";
console.log(ts);
// 2017-11-13T09:50:00.000Z
dt = new Date(ts);
console.log(dt);
// 2017-11-13T09:50:00.000Z
Pasada.findOrCreate({
    where: { fecha: dt },
    defaults: { fecha: dt },
    attributes: ['id_pasada'],
    transaction: t
});
```

## What do you expect to happen?
I expect get an _id_pasada_ (found or created).

## What is actually happening?
But when there're two requests with the same _fecha_ (date) at once, one of them fails with:
```js
{
    "name": "SequelizeUniqueConstraintError",
    "data": [
        {
            "validatorName": null,
            "path": "fecha",
            "validatorArgs": [],
            "instance": {
                "id_pasada": null,
                "fecha": "2017-11-13T09:50:00.000Z"
            },
            "message": "fecha must be unique",
            "type": "unique violation",
            "value": "2017-11-13 09:50:00+00",
            "origin": "DB",
            "validatorKey": "not_unique"
        }
    ],
    "message": "Validation error",
    "stack": "SequelizeUniqueConstraintError: Validation error\n    at Query.formatError (/var/api/node_modules/sequelize/lib/dialects/postgres/query.js:318:18)\n    at query.catch.then.then.queryResult (/var/api/node_modules/sequelize/lib/dialects/postgres/query.js:114:24)\n    at tryCatcher (/var/api/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/api/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/var/api/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromise0 (/var/api/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/var/api/node_modules/bluebird/js/release/promise.js:693:18)\n    at Async._drainQueue (/var/api/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/var/api/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/var/api/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:672:20)\n    at tryOnImmediate (timers.js:645:5)\n    at processImmediate [as _immediateCallback] (timers.js:617:5)"
}
```
In previous Sequelize versions the error appeared similar:
```js
Error: Pasada#findOrCreate: value used for fecha was not equal for both the find and the create calls, '2017-11-10T02:20:00.000Z' vs '2017-11-10 02:20:00+00'
```
Is normal this format difference between Z and +00?

__Dialect:__ postgres
__Dialect version:__ pg@6.4.2
__Database version:__ 9.5.9
__Sequelize version:__ 4.22.5
__Tested with master branch:__ No

**Comment by dayer3** [comment]
I've been using `findCreateFind` and the result is the same. I just updated the title.

**Comment by prodrigestivill** [comment]
In our case looks like: `'2018-01-10 08:01:00.000 +00:00' !== '2018-01-10 08:01:00+00'`

We did a workaround by doing somthing similar to this:
``` javascript
function findOrCreate(options) {
  let instance;
  try {
    instance = await model.create(defaultValues);
  } catch (ex) {
    instance = await model.findeOne(
  
}
