### ISSUE TITLE
Seed Failing with error "Cannot Read Property 'autoIncrement' of Undefined.

### ISSUE THREAD

**Issue by cjrutherford** [sequelize/sequelize#8632]
## What are you doing?

Attempting to seed the database

```js
// 'use strict';
const cjson = require('cjson');
var outsiderData = cjson.load('server/seeders/Outsider.json');

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Outsiders', outsiderData);
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Outsiders', null, {});
  }
};

```

## What do you expect to happen?
I wanted to seed the database with the CLI, and have no errors when running the seed.

## What is actually happening?
Getting an error stating that the runtime cannot read an "undefined" value of "AutoIncrement"

_Output_

```
== 20171030160224-outsider: migrating =======
Seed file failed with error: Cannot read property 'autoIncrement' of undefined TypeError: Cannot read property 'autoIncr
ement' of undefined
    at C:\Users\rutherfordc.AA\Documents\GitHub\ccs-express\node_modules\sequelize\lib\dialects\mssql\query-generator.js
:264:48
    at C:\Users\rutherfordc.AA\Documents\GitHub\ccs-express\node_modules\lodash\lodash.js:4389:15
    at baseForOwn (C:\Users\rutherfordc.AA\Documents\GitHub\ccs-express\node_modules\lodash\lodash.js:2652:24)
    at Function.forOwn (C:\Users\rutherfordc.AA\Documents\GitHub\ccs-express\node_modules\lodash\lodash.js:12254:24)
    at C:\Users\rutherfordc.AA\Documents\GitHub\ccs-express\node_modules\sequelize\lib\dialects\mssql\query-generator.js
:258:15
    at arrayEach (C:\Users\rutherfordc.AA\Documents\GitHub\ccs-express\node_modules\lodash\lodash.js:473:11)
    at Function.forEach (C:\Users\rutherfordc.AA\Documents\GitHub\ccs-express\node_modules\lodash\lodash.js:8561:14)
    at Object.bulkInsertQuery (C:\Users\rutherfordc.AA\Documents\GitHub\ccs-express\node_modules\sequelize\lib\dialects\
mssql\query-generator.js:248:13)
    at QueryInterface.bulkInsert (C:\Users\rutherfordc.AA\Documents\GitHub\ccs-express\node_modules\sequelize\lib\query-
interface.js:568:33)
    at Object.up (C:\Users\rutherfordc.AA\Documents\GitHub\ccs-express\server\seeders\20171030160224-outsider.js:7:27)
    at Migration._callee$ (C:\Users\rutherfordc.AA\AppData\Roaming\npm\node_modules\sequelize-cli\node_modules\umzug\lib
\migration.js:178:35)
    at tryCatch (C:\Users\rutherfordc.AA\AppData\Roaming\npm\node_modules\sequelize-cli\node_modules\regenerator-runtime
\runtime.js:65:40)
    at Generator.invoke [as _invoke] (C:\Users\rutherfordc.AA\AppData\Roaming\npm\node_modules\sequelize-cli\node_module
s\regenerator-runtime\runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\rutherfordc.AA\AppData\Roaming\npm\node_modules\sequ
elize-cli\node_modules\regenerator-runtime\runtime.js:117:21)
    at step (C:\Users\rutherfordc.AA\AppData\Roaming\npm\node_modules\sequelize-cli\node_modules\babel-runtime\helpers\a
syncToGenerator.js:17:30)
    at C:\Users\rutherfordc.AA\AppData\Roaming\npm\node_modules\sequelize-cli\node_modules\babel-runtime\helpers\asyncTo
Generator.js:28:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

__Dialect:__ mssql
__Dialect version:__  Tedious V.2.0.0
__Database version:__ MS SQL Server 14.0.900.75
__Sequelize version:__ 3.0.0-3 (also tested with 4.x with same issue)
__Tested with master branch:__ YES

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/issues/8645
