### ISSUE TITLE
SequelizeForeignKeyConstraintError during creation with many to many relationship

### ISSUE THREAD

**Issue by IvanIvashchenko** [sequelize/sequelize#8641]
## What are you doing?
I have two models: sites and addresses with many to many relationship. 

```js
//site model
module.exports = (sequelize, DataTypes) => {
  const Site = sequelize.define('site', {
    name: {
      type: DataTypes.STRING,
      allowNull: false
    },
    browser: {
      type: DataTypes.STRING,
      defaultValue: 'chrome'
    }
  });

  Site.associate = (models) => {
    Site.belongsTo(models['user'], {
      foreignKey: {
        name: 'user_id'
      },
      onDelete: 'CASCADE'
    });
    Site.belongsToMany(models['address'], {
      foreignKey: {
        name: 'address_id'
      },
      through: 'sites_addresses'
    });
  };

  return Site;
};

//address model
module.exports = (sequelize, DataTypes) => {
  const Address = sequelize.define('address', {
    url: {
      type: DataTypes.STRING,
      allowNull: false
    }
  });

  Address.associate = (models) => {
    Address.belongsToMany(models['site'], {
      foreignKey: {
        name: 'site_id'
      },
      through: 'sites_addresses'
    });
  };

  return Address;
};
```
I also create 3 collections: sites, addresses and sites_addresses via migrations and set corresponded references for sites_addresses

```js
//sites
module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.createTable('sites', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
      },
      name: {
        type: Sequelize.STRING,
        allowNull: false
      },
      browser: {
        type: Sequelize.STRING,
        defaultValue: 'chrome',
      },
      user_id: {
        allowNull: false,
        type: Sequelize.INTEGER,
        references: { model: 'users', key: 'id' }
      }
    });
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.dropTable('sites');
  }
};

//addresses
module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.createTable('addresses', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
      },
      url: {
        type: Sequelize.STRING,
        allowNull: false
      }
    });
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.dropTable('addresses');
  }
};


//sites_addresses
module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.createTable('sites_addresses', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
      },
      site_id: {
        allowNull: false,
        type: Sequelize.INTEGER,
        references: {
          model: 'sites',
          key: 'id',
          deferrable: Sequelize.Deferrable.INITIALLY_DEFERRED
        }
      },
      address_id: {
        allowNull: false,
        type: Sequelize.INTEGER,
        references: {
          model: 'addresses',
          key: 'id',
          deferrable: Sequelize.Deferrable.INITIALLY_DEFERRED
        }
      }
    });
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.dropTable('sites_addresses');
  }
};
```
In my controller I try to create site with address into transaction

```js
  create(req, res) {
    let newSite;
    return sequelize.transaction({
      deferrable: sequelize.Deferrable.SET_DEFERRED
    }, t => {
      return Site.create({
          name: req.body.name,
          browser: req.body.browser,
          user_id: req.user.id
        },
        {
          transaction: t
        })
        .then(site => {
          newSite = site;
          return Address.create({
            url: req.body.url
          },
          {
            transaction: t
          });
        })
        .then(address => {
          return newSite.setAddresses([address], {
            transaction: t
          });
        })
        .then(address => {
          res.status(200).send(address);
        })
        .catch(error => res.status(400).send(error));
    });
  }
```
## What do you expect to happen?
I want to create 3 new entries into my db: site, address and sites_addresses.

## What is actually happening?
I get this error with foreign key constraint and transaction calls rollback:
```
Executing (65b73399-b7f0-4d3f-a1bc-a265834e46d8): START TRANSACTION;
Executing (65b73399-b7f0-4d3f-a1bc-a265834e46d8): SET CONSTRAINTS ALL DEFERRED
Executing (65b73399-b7f0-4d3f-a1bc-a265834e46d8): INSERT INTO "sites" ("id","name","browser","createdAt","updatedAt","user_id") VALUE
S (DEFAULT,'my second site','Chrome','2017-11-16 08:42:56.784 +00:00','2017-11-16 08:42:56.784 +00:00',1) RETURNING *;
Executing (65b73399-b7f0-4d3f-a1bc-a265834e46d8): INSERT INTO "addresses" ("id","url","createdAt","updatedAt") VALUES (DEFAULT,'http:
//google.com','2017-11-16 08:42:56.793 +00:00','2017-11-16 08:42:56.793 +00:00') RETURNING *;
Executing (65b73399-b7f0-4d3f-a1bc-a265834e46d8): SELECT "createdAt", "updatedAt", "site_id", "address_id" FROM "sites_addresses" AS 
"sites_addresses" WHERE "sites_addresses"."address_id" = 32;
Executing (65b73399-b7f0-4d3f-a1bc-a265834e46d8): INSERT INTO "sites_addresses" ("createdAt","updatedAt","site_id","address_id") VALU
ES ('2017-11-16 08:42:56.800 +00:00','2017-11-16 08:42:56.800 +00:00',29,32);
Executing (65b73399-b7f0-4d3f-a1bc-a265834e46d8): COMMIT;
POST /site/create 200 60.707 ms - 112
Unhandled rejection SequelizeForeignKeyConstraintError: insert or update on table "sites_addresses" violates foreign key constraint "sites_addresses_site_id_fkey"
    at Query.formatError (/home/iivashchenko/projects/nodejs/seralto/node_modules/sequelize/lib/dialects/postgres/query.js:289:16)
    at query.catch.err (/home/iivashchenko/projects/nodejs/seralto/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)
    at tryCatcher (/home/iivashchenko/projects/nodejs/seralto/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/iivashchenko/projects/nodejs/seralto/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/iivashchenko/projects/nodejs/seralto/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/iivashchenko/projects/nodejs/seralto/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/iivashchenko/projects/nodejs/seralto/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/home/iivashchenko/projects/nodejs/seralto/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/iivashchenko/projects/nodejs/seralto/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/iivashchenko/projects/nodejs/seralto/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

```

I've also tried to play with deferred settings and isolation levels but can't find solution of this. When I've tried to execute commands from output above into my database manually all works properly and sites_addresses entry has been created.

__Dialect:__ postgres
__Dialect version:__ 7.3.0
__Database version:__ 9.5
__Sequelize version:__ 4.22.6
__Tested with master branch:__ Yes

**Comment by IvanIvashchenko** [comment]
Ok, that was my bad. I've mixed up foreign keys for belongsToMany during model definition. So it should be
```js
  Address.associate = (models) => {
    Address.belongsToMany(models['site'], {
      foreignKey: {
        name: 'address_id'
      },
      through: 'sites_addresses'
    });
  };

  Site.associate = (models) => {
    Site.belongsTo(models['user'], {
      foreignKey: {
        name: 'user_id'
      },
      onDelete: 'CASCADE'
    });
    Site.belongsToMany(models['address'], {
      foreignKey: {
        name: 'site_id'
      },
      through: 'sites_addresses'
    });
  };
```
