### ISSUE TITLE
sequelize validator error

### ISSUE THREAD

**Issue by BaroqueCoding** [sequelize/sequelize#8642]
## What are you doing?

I was changing string based operators into symbol based operators. But one of them caused a problem.
```js
//  model
const users = sequelize.define('users', {
	email: {
		type: DataTypes.STRING({ length: 255 }),
		allowNull: true,
		validate: { isEmail: true }
	},
//   ....

//  actual querybuilder
 return db.mySequel.transaction(t => {
        return db.users.findOrCreate({
            where: { email: { [Op.eq]: p_email} },
            defaults: {
                password: p_password,
                username: p_username
            },
            transaction: t
        }).spread((rs, created) => {
            if (created == false) apiError("10005");
            return db.user_has_musician_type.bulkCreate([
                {
                    user_id: rs.id,
                    musician_type: 'G',
                    musician_type_id: p_genre
                },
                {
                    user_id: rs.id,
                    musician_type: 'I',
                    musician_type_id: p_instrument
                }
            ], {
                transaction: t,
                raw: true
            });
        })
    }).then(rs => {
        res.apiResponse(true);
    }).catch(err => {
        next(err);
    });
```

## What do you expect to happen?
I wanted that sequelize examine p_email(string) properly and create record.

## What is actually happening?
Two errors occurred. Both of them were ValidationError related with `isEmail`validation option and the value property was {Symbol(eq) : "tese211@ttest.com"} not "tese211@ttest.com".
The error messages were:
- email cannot be an array or an object
- Validation isEmail on email failed

It seems sequelize validator examine wrong value.

__Dialect:__ mysql
__Database version:__ 5.5.42
__Sequelize version:__ 4.22.6
__Tested with master branch:__ Yes

**Note :** _Your issue may be ignored by maintainers if it's not tested against `master` branch OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Can you full error thrown?

**Comment by BaroqueCoding** [comment]
```
{
name: "SequelizeValidationError"
message: "string violation: email cannot be an array or an object,↵Validation error: Validation isEmail on email failed"
stack:
`SequelizeValidationError:
    string violation: email cannot be an array or an object,
    Validation error: Validation isEmail on email failed
        at Promise.all.then (~/seq_node/node_modules/sequelize/lib/instance-validator.js:77:15)
        From previous event:
            at InstanceValidator._validate (~/seq_node/node_modules/sequelize/lib/instance-validator.js:75:7)
            at runHooks.then (~/seq_node/node_modules/sequelize/lib/instance-validator.js:110:14)
            From previous event:
                at InstanceValidator._validateAndRunHooks (~/seq_node/node_modules/sequelize/lib/instance-validator.js:109:8)
                at InstanceValidator.validate (~/seq_node/node_modules/sequelize/lib/instance-validator.js:93:38)
                at model.validate (~/seq_node/node_modules/sequelize/lib/model.js:3734:49)
                at Promise.try (~/seq_node/node_modules/sequelize/lib/model.js:3511:21)
                From previous event:
                    at model.save (~/seq_node/node_modules/sequelize/lib/model.js:3508:23)
                    at Function.create (~/seq_node/node_modules/sequelize/lib/model.js:1997:8)
                    at sequelize.transaction.then.then.instance (~/seq_node/node_modules/sequelize/lib/model.js:2095:19)
                    From previous event:
                        at Function.findOrCreate (~/seq_node/node_modules/sequelize/lib/model.js:2083:8)
                        at db.mySequel.transaction.t (~/seq_node/controllers/user.js:49:25)
                        at transaction.prepareEnvironment.then (~/seq_node/node_modules/sequelize/lib/sequelize.js:969:21)
                        at runCallback (timers.js:789:20)
                        at tryOnImmediate (timers.js:751:5)
                        at processImmediate [as _immediateCallback] (timers.js:722:5)
                        From previous event:
                            at Sequelize._clsRun (~/seq_node/node_modules/sequelize/lib/sequelize.js:969:10)
                            at Function._clsRun (~/seq_node/node_modules/sequelize/lib/sequelize.js:1013:21)
                            at Sequelize.transaction (~/seq_node/node_modules/sequelize/lib/sequelize.js:967:22)
                            at ~/seq_node/controllers/user.js:48:24
                            at Layer.handle [as handle_request] (~/seq_node/node_modules/express/lib/router/layer.js:95:5)
                            at next (~/seq_node/node_modules/express/lib/router/route.js:137:13)
                            at Route.dispatch (~/seq_node/node_modules/express/lib/router/route.js:112:3)
                            at Layer.handle [as handle_request] (~/seq_node/node_modules/express/lib/router/layer.js:95:5)
                            at ~/seq_node/node_modules/express/lib/router/index.js:281:22
                            at Function.process_params (~/seq_node/node_modules/express/lib/router/index.js:335:12)
                            at next (~/seq_node/node_modules/express/lib/router/index.js:275:10)
                            at Function.handle (~/seq_node/node_modules/express/lib/router/index.js:174:3)
                            at router (~/seq_node/node_modules/express/lib/router/index.js:47:12)
                            at Layer.handle [as handle_request] (~/seq_node/node_modules/express/lib/router/layer.js:95:5)
                            at trim_prefix (~/seq_node/node_modules/express/lib/router/index.js:317:13)
                            at ~/seq_node/node_modules/express/lib/router/index.js:284:7
                            at Function.process_params (~/seq_node/node_modules/express/lib/router/index.js:335:12)
                            at next (~/seq_node/node_modules/express/lib/router/index.js:275:10)
                            at exports.apiExtension (~/seq_node/helper/api_helper.js:171:2)
                            at Layer.handle [as handle_request] (~/seq_node/node_modules/express/lib/router/layer.js:95:5)
                            at trim_prefix (~/seq_node/node_modules/express/lib/router/index.js:317:13)
                            at ~/seq_node/node_modules/express/lib/router/index.js:284:7
                            at Function.process_params (~/seq_node/node_modules/express/lib/router/index.js:335:12)
                            at next (~/seq_node/node_modules/express/lib/router/index.js:275:10)
                            at exports.apiSet (~/seq_node/helper/api_helper.js:76:2)`
}
```

**Comment by BaroqueCoding** [comment]
```
errors: Array(2)
0 : ValidationErrorItem
instance:
model {dataValues: {…}, _previousDataValues: {…}, _changed: {…}, _modelOptions: {…}, _options: {…}, …}
message: "email cannot be an array or an object"
origin: "CORE"
path: "email"
type: "string violation"
validatorArgs: []
validatorKey: "not_a_string"
validatorName: null
value: {Symbol(eq): "tese211@ttest.com"}

1: ValidationErrorItem
instance :
model {dataValues: {…}, _previousDataValues: {…}, _changed: {…}, _modelOptions: {…}, _options: {…}, …}
message: "Validation isEmail on email failed"
origin: "FUNCTION"
path: "email"
type: "Validation error"
validatorArgs: [{…}]
validatorKey: "isEmail"
validatorName: "isEmail"
value: {Symbol(eq): "tese211@ttest.com"}
```

**Comment by BaroqueCoding** [comment]
need more detail?

**Comment by sushantdhiman** [comment]
`where: { email: { [Op.eq]: p_email} },` => `where: { email: p_email }`

**Comment by BaroqueCoding** [comment]
I know that works well. but I'm notified that string based operators like `where: { email: p_email }` is deprecated. Am I something misunderstand?

**Comment by sushantdhiman** [comment]
`{ email: p_email }` not a string operator. If you are using secure operators then you dont have to worry, usrers wont be able to inject arbitrary operators in `p_email`

**Comment by BaroqueCoding** [comment]
Thanks for your answer. Here are some questions. Sequelize document shows me an example.
```
Post.findAll({
  where: {
    [Op.or]: [{authorId: 12}, {authorId: 13}]
  }
});
```
This example makes me confused. If what I understand is correct, `Op.or` can go to the where clause, but` Op.eq` can not.
What's the difference? and Where is `Op.eq` intended to be used?

**Comment by sushantdhiman** [comment]
You have used `Op.eq` correctly, but `findOrCreate` merge `where` and `defaults` fields to create new record, `{ eq: p_email }` wont be a correct entry for `email` field.

Can you repeat this case with String operators? Let me know if `$eq` works but `Op.eq` doesn't, which will show a regression.

**Comment by BaroqueCoding** [comment]
I understood what you said. Using `{email : p_mail}` seems still works and so does `Op.eq`.
But the way of `findOrCreate` works looks strange. Anyway, your answer was helpful. thanks again.
