### ISSUE TITLE
mssql: Cannot read property 'autoIncrement' of undefined

### ISSUE THREAD

**Issue by sobiemir** [sequelize/sequelize#8645]
https://github.com/sequelize/sequelize/blob/ccb99daedb69e8750a241436415ccac8abef358d/lib/dialects/mssql/query-generator.js#L275

This condition should also checks for `attributes[key]`, like in condition in line 270:
https://github.com/sequelize/sequelize/blob/ccb99daedb69e8750a241436415ccac8abef358d/lib/dialects/mssql/query-generator.js#L270

So, it should look like this:
`if (value === null && attributes[key] && attributes[key].autoIncrement) `.

Without this, I'm getting error:
> Cannot read property 'autoIncrement' of undefined

Stacktrace:
```TypeError: Cannot read property 'autoIncrement' of undefined
    at _.forOwn (---\node_modules\sequelize\lib\dialects\mssql\query-generator.js:275:49)
    at ---\node_modules\lodash\lodash.js:4944:15
    at baseForOwn (---\node_modules\lodash\lodash.js:3001:24)
    at Function.forOwn (---\node_modules\lodash\lodash.js:13002:24)
    at _.forEach.attrValueHash (---\node_modules\sequelize\lib\dialects\mssql\query-generator.js:269:9)
    at arrayEach (---\node_modules\lodash\lodash.js:537:11)
    at Function.forEach (---\node_modules\lodash\lodash.js:9359:14)
    at Object.bulkInsertQuery (---\node_modules\sequelize\lib\dialects\mssql\query-generator.js:259:7)
    at QueryInterface.bulkInsert (---\node_modules\sequelize\lib\query-interface.js:928:37)
    at queryInterface.sequelize.query.then (---\Migrations\seeders\11171106132648-sample.js:36:39)
    at tryCatcher (---\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (---\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (---\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (---\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (---\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (---\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (---\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (---\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
```

**Comment by sushantdhiman** [comment]
How this error can be reproduced? Do you have any code that will trigger this issue. It will help writing a test that could prevent regression in future.

Looks like you haven't tested this with master. Could you try with latest release as well?

**Comment by sobiemir** [comment]
I will check on Monday what version it was.
I can't put here original code, but I will try to create sample and reproduce it.
Sorry that I didn't create issue from template, but somehow when I was creating it, template didn't appear... (or maybe I removed it by mistake...)

**Comment by sobiemir** [comment]
Ok, I checked it and updated sequelize:
**Version:** 4.22.8 _(latest from npm)_

Sample:
**Migration:**
```
'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.sequelize.transaction((t) => {
      return queryInterface.createTable("SampleTable", {
        IdUser: {
          type: Sequelize.STRING(128),
          primaryKey: true,
          allowNull: false
        },
        Email: {
          type: Sequelize.STRING(256),
          allowNull: true
        },
        SomeOption1: {
          type: Sequelize.BOOLEAN,
          allowNull: false
        },
        SomeOption2: {
          type: Sequelize.BOOLEAN,
          allowNull: false
        },
        TextDataWithNull: {
          type: Sequelize.TEXT,
          allowNull: true
        },
        CountOfData: {
          type: Sequelize.INTEGER,
          allowNull: false
        },
        SampleText: {
          type: Sequelize.STRING(256),
          allowNull: false
        }
      }, {
        transaction: t
      } );
    });
  },
  
  down: (queryInterface, Sequelize) => {
    return queryInterface.sequelize.transaction( (t) => {
      return queryInterface.dropTable( "SampleTable", { transaction: t });
    });
  }
};
```

**Seed:**
```
'use strict';

var samples = [{
  IdUser: 'a611e-d60b-431a-aad8-2ed19f1bb45a',
  Email: 'sample@sampl.com',
  SomeOption1: false,
  SomeOption2: false,
  TextDataWithNull: null,
  CountOfData: 0,
  SampleText: 'inode/empty'
}];

module.exports = {
  up: (queryInterface, Sequelize) => {
  return queryInterface.sequelize.transaction((t) => {
      let sql = queryInterface.QueryGenerator.selectQuery( "SampleTable" );
      return queryInterface.sequelize.query( sql, {
        type: Sequelize.QueryTypes.SELECT,
        raw: true,
        transaction: t
      } ).then( (data) => {
        if( data.length > 0 )
          throw "You can insert test data only to empty table."
  
        return queryInterface.bulkInsert( "SampleTable", samples, {
          transaction: t
        } );
      } );
    });
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.sequelize.transaction((t) => {
      let elems = [];

    elems = [];
    for( const sample of samples )
    elems.push( queryInterface.bulkDelete("SampleTable", {
      IdUser: sample.IdUser
    }, {
      transaction: t
    }) );
    return Promise.all(elems);
    });
  }
};
```

It gives me an error when I'm trying to run this seed without change that I made, described in first post:
**Error:**
`ERROR: Cannot read property 'autoIncrement' of undefined`
