### ISSUE TITLE
Uncatchable `Unhandled rejection` in sequelize transaction

### ISSUE THREAD

**Issue by adamkecskes** [sequelize/sequelize#8671]
## What are you doing?
I'm locking a table manually (`lock tables MyTable write;`), and trying to create a new record into that table by sequelize. I would expect to get a `ER_LOCK_WAIT_TIMEOUT` error, which I can catch but, I get an `Unhandled rejection` as well.

```js
const myInstance = new MyTable({
    field: 674,
});

sequelize.transaction((transaction) => {
    return myInstance.save({ transaction })
        .catch((err) => {
            console.log('-catch here-');
        });
})
    .catch((err) => {
        console.log('-catch here as well-');
    });
```

## What do you expect to happen?
I would expect to catch the error, and NOT get `Unhandled rejection SequelizeDatabaseError`

## What is actually happening?
Although I've put `.catch` anywhere I could, I get `Unhandled rejection SequelizeDatabaseError`
```
-catch here-
Unhandled rejection SequelizeDatabaseError: Lock wait timeout exceeded; try restarting transaction
    at Query.formatError (/opt/server/node_modules/sequelize/lib/dialects/mysql/query.js:228:16)
    at Query.connection.query [as onResult] (/opt/server/node_modules/sequelize/lib/dialects/mysql/query.js:55:23)
    at Query.Command.execute (/opt/server/node_modules/mysql2/lib/commands/command.js:30:12)
    at Connection.handlePacket (/opt/server/node_modules/mysql2/lib/connection.js:515:28)
    at PacketParser.onPacket (/opt/server/node_modules/mysql2/lib/connection.js:94:16)
    at PacketParser.executeStart (/opt/server/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.<anonymous> (/opt/server/node_modules/mysql2/lib/connection.js:102:29)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

```
SHOW VARIABLES LIKE "%version%";

innodb_version	5.7.19
protocol_version	10
slave_type_conversions	
version	10.2.8-MariaDB-10.2.8+maria~xenial-log
version_comment	mariadb.org binary distribution
version_compile_machine	x86_64
version_compile_os	debian-linux-gnu
version_malloc_library	system
version_ssl_library	OpenSSL 1.0.2g  1 Mar 2016
wsrep_patch_version	wsrep_25.19
```

__Sequelize version: 4.22.11
__Tested with master branch: yes

**PS.**
I know I could catch the error by `process.on('unhandledRejection')` but that's not a real solution.

**Comment by scream314** [comment]
I have the exact same issue, it is very annoying.

**Comment by sushantdhiman** [comment]
It seems to work, I can properly intercept error in catch block.

```js
const Test = sequelize.define('Test', {
  a: Sequelize.INTEGER,
  b: Sequelize.INTEGER,
  c: Sequelize.INTEGER
});

async function test() {
  await Test.sync({ force: true });

  const test1 = await Test.create({ a: 1 });

  await sequelize.transaction(async (t) => {
    await sequelize.query('SELECT * FROM Tests WHERE a = 1 FOR UPDATE;', { transaction: t });

    return await sequelize.transaction(async (t) => {
      return await test1.update({ a: 2 }, { where: { a: 1 }, transaction: t });
    })
  }).then(() => {
    console.log('Donz');
  })
  .catch(e => {
    console.log(e.message);
  })

  console.log(await Test.findAll({ raw: true }));
}

test();
```

```sql
Executing (default): DROP TABLE IF EXISTS `Tests`;
Executing (default): CREATE TABLE IF NOT EXISTS `Tests` (`id` INTEGER NOT NULL auto_increment , `a` INTEGER, `b` INTEGER, `c` INTEGER, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `Tests`
Executing (default): INSERT INTO `Tests` (`id`,`a`,`createdAt`,`updatedAt`) VALUES (DEFAULT,1,'2018-01-10 04:14:11','2018-01-10 04:14:11');
Executing (c284650c-8b8d-495f-9e04-2966aa24a2fe): START TRANSACTION;
Executing (c284650c-8b8d-495f-9e04-2966aa24a2fe): SELECT * FROM Tests WHERE a = 1 FOR UPDATE;
Executing (ecd69c7c-0861-4a48-9bc3-7d0269276578): START TRANSACTION;
Executing (ecd69c7c-0861-4a48-9bc3-7d0269276578): UPDATE `Tests` SET `a`=2,`updatedAt`='2018-01-10 04:14:11' WHERE `id` = 1
Executing (ecd69c7c-0861-4a48-9bc3-7d0269276578): ROLLBACK;
Executing (c284650c-8b8d-495f-9e04-2966aa24a2fe): ROLLBACK;
Lock wait timeout exceeded; try restarting transaction
Executing (default): SELECT `id`, `a`, `b`, `c`, `createdAt`, `updatedAt` FROM `Tests` AS `Test`;
[ { id: 1,
    a: 1,
    b: null,
    c: null,
    createdAt: 2018-01-10T04:14:11.000Z,
    updatedAt: 2018-01-10T04:14:11.000Z } ]
```
