### ISSUE TITLE
NULL Geometry value throws exception with Mysql2@1.5.1

### ISSUE THREAD

**Issue by doublesharp** [sequelize/sequelize#8679]
`Mysql2@1.5.1` returns `NULL` instead of an empty `Buffer` for GEOMETRY columns which is causing an exception in Sequelize. Sequelize works as expected with `Mysql2@1.5.0` which returned an empty `Buffer`.

This issue has been addressed in https://github.com/sequelize/sequelize/pull/8661 but is in need of test coverage, however in the meantime it is causing a problem for me on some production servers.

## What are you doing?
Querying a row with a null GEOMETRY column using `mysql` dialect and `Mysql2@1.5.1`.

```js
sequelize.define(
    'table',
    {
      location: {
        type: DataTypes.GEOMETRY('POINT'),
      },
    }
);

sequelize.models.table.create({ location: null })
.then(() => sequelize.models.table.findAll())
.then((rows) => console.log(rows));
```

## What do you expect to happen?
Results to be returned

## What is actually happening?
Exception is thrown
```error: uncaughtException: Cannot read property 'length' of null 
date=Tue Nov 21 2017 12:26:15 GMT-0800 (PST), 
pid=37117, 
uid=501, 
gid=20, 
cwd=/workspace, 
execPath=/home/.nvm/versions/node/v9.0.0/bin/node, 
version=v9.0.0, 
argv=[/home/.nvm/versions/node/v9.0.0/bin/node, /workspace/bin/server], 
rss=105488384, 
heapTotal=59039744, 
heapUsed=51240944, 
external=3997834, 
loadavg=[2.6982421875, 2.3056640625, 2.28271484375], 
uptime=81492, 
trace=[
  column=15, file=/workspace/node_modules/sequelize/lib/dialects/mysql/data-types.js, function=parse, line=153, method=null, native=false, 
  column=39, file=/workspace/node_modules/sequelize/lib/dialects/mysql/connection-manager.js, function=ConnectionManager._typecast, line=59, method=_typecast, native=false, 
  column=21, file=/workspace/node_modules/generate-function/index.js, function=new TextRow (eval at line.toFunction, line=55, method=toFunction, native=false, 
  column=13, file=/workspace/node_modules/mysql2/lib/commands/query.js, function=Query.row, line=231, method=row, native=false, 
  column=20, file=/workspace/node_modules/mysql2/lib/commands/command.js, function=Query.Command.execute, line=40, method=execute, native=false, 
  column=28, file=/workspace/node_modules/mysql2/lib/connection.js, function=Connection.handlePacket, line=515, method=handlePacket, native=false, 
  column=16, file=/workspace/node_modules/mysql2/lib/connection.js, function=PacketParser.onPacket, line=94, method=onPacket, native=false, 
  column=14, file=/workspace/node_modules/mysql2/lib/packet_parser.js, function=PacketParser.executeStart, line=77, method=executeStart, native=false, column=29, file=/workspace/node_modules/mysql2/lib/connection.js, function=null, line=102, method=null, native=false, 
  column=13, file=events.js, function=emitOne, line=125, method=null, native=false, 
  column=7, file=events.js, function=Socket.emit, line=221, method=emit, native=false, 
  column=12, file=_stream_readable.js, function=addChunk, line=265, method=null, native=false, 
  column=11, file=_stream_readable.js, function=readableAddChunk, line=252, method=null, native=false, 
  column=10, file=_stream_readable.js, function=Socket.Readable.push, line=209, method=push, native=false, 
  column=20, file=net.js, function=TCP.onread, line=598, method=onread, native=false
], 
stack=[
  TypeError: Cannot read property 'length' of null,
     at parse (/workspace/node_modules/sequelize/lib/dialects/mysql/data-types.js:153:15),     
     at ConnectionManager._typecast (/workspace/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:59:39),     
     at new TextRow (eval  at line.toFunction (/workspace/node_modules/generate-function/index.js:55:21), <anonymous>:41:32),     
     at Query.row (/workspace/node_modules/mysql2/lib/commands/query.js:231:13),     
     at Query.Command.execute (/workspace/node_modules/mysql2/lib/commands/command.js:40:20),     
     at Connection.handlePacket (/workspace/node_modules/mysql2/lib/connection.js:515:28),     
     at PacketParser.onPacket (/workspace/node_modules/mysql2/lib/connection.js:94:16),     
     at PacketParser.executeStart (/workspace/node_modules/mysql2/lib/packet_parser.js:77:14),     
     at Socket.<anonymous> (/workspace/node_modules/mysql2/lib/connection.js:102:29),     
     at emitOne (events.js:125:13),     
     at Socket.emit (events.js:221:7),     
     at addChunk (_stream_readable.js:265:12),     
     at readableAddChunk (_stream_readable.js:252:11),     
     at Socket.Readable.push (_stream_readable.js:209:10),     
     at TCP.onread (net.js:598:20)
]```

__Dialect:__ mysql
__Dialect version:__ Mysql2@1.5.1
__Database version:__ MariaDB 10
__Sequelize version:__ 4.22.11
__Tested with master branch:__ Yes

**Comment by sushantdhiman** [comment]
Yea https://github.com/sequelize/sequelize/pull/8678/files

**Comment by doublesharp** [comment]
@sushantdhiman Sweet, thanks! Just wanted to make sure it was documented in the right places.

**Comment by sushantdhiman** [comment]
https://github.com/sequelize/sequelize/commit/6931c795a89ff70722c6718e6b151121edad5c94

New version (v4.22.12) will be released automatically in a few minutes
