### ISSUE TITLE
query.js:113:17 Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by limulidae** [sequelize/sequelize#8699]
## What are you doing?

```js
findOrCreate()
```

## What do you expect to happen?
no exception

## What is actually happening?
  apis:email signup TypeError: Cannot read property '0' of undefined
    at query.catch.then.then.queryResult (/Users/santinowang/dev/bitbucket/bula/api/node_modules/sequelize/lib/dialects/postgres/query.js:113:17)
    at tryCatcher (/Users/santinowang/dev/bitbucket/bula/api/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/santinowang/dev/bitbucket/bula/api/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/santinowang/dev/bitbucket/bula/api/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/santinowang/dev/bitbucket/bula/api/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/santinowang/dev/bitbucket/bula/api/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/santinowang/dev/bitbucket/bula/api/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/santinowang/dev/bitbucket/bula/api/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/santinowang/dev/bitbucket/bula/api/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5) +71ms

if (rows[0] && rows[0].sequelize_caught_exception !== undefined) {

I print rows.
rows is undefined here.

_Output, either JSON or SQL_

__Dialect: postgres 
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ XXX
__Tested with master branch:__ No

**Note :** _Your issue may be ignored by maintainers if it's not tested against `master` branch OR does not follow issue template._

**Comment by limulidae** [comment]
├── pg@7.4.0
├── pg-hstore@2.3.2
├── sequelize@4.23.1

When will you support pg@7

**Comment by sushantdhiman** [comment]
pg@7.4.0 is not supported yet, its mentioned in Readme/Docs as well

**Comment by sushantdhiman** [comment]
Try with `pg@6.x`
