### ISSUE TITLE
addAssociation not working with primarykey with multiple columns

### ISSUE THREAD

**Issue by panitaxx** [sequelize/sequelize#8728]
Hello,

## What are you doing?

I am Trying to add an association. The association has 3 columns as a primary key

```js
const Sequelize = require('sequelize');

const sequelize = new Sequelize('testdb', 'root', null, {
  host: 'localhost',
  dialect: 'mysql',
  operatorsAliases: false
});


let Organization = sequelize.define('Organization', {
  name: { type: Sequelize.STRING, allowNull: false }
});



let OrganizationRole = sequelize.define('OrganizationRole', {
  organizationId: { type: Sequelize.INTEGER, allowNull: false, primaryKey: true },
  roleId: { type: Sequelize.STRING, allowNull: false, primaryKey: true },
  userId: { type: Sequelize.INTEGER, allowNull: false, primaryKey: true }
});

let User = sequelize.define('User', {
  name: { type: Sequelize.STRING, allowNull: false }
});

let Role = sequelize.define('Role', {
  name: { type: Sequelize.STRING, allowNull: false },
  id: { type: Sequelize.STRING, allowNull: false, primaryKey: true }
});


User.belongsToMany(Organization, { through: 'UserOrganization' });
User.hasMany(OrganizationRole, { as: 'roles', foreignKey: { allowNull: false, primaryKey: true, name: 'userId' } });
OrganizationRole.belongsTo(User, { foreignKey: 'userId' });
OrganizationRole.belongsTo(Role, { foreignKey: 'roleId' });
OrganizationRole.belongsTo(Organization, { foreignKey: 'organizationId' });
Organization.belongsToMany(User, { through: 'UserOrganization' });

sequelize.sync({ force: true }).then(() =>
Promise.all([
  Organization.create({ name: 'testOrg' }),
  User.create({name: 'testUser'}),
  Role.create({name:'test role',id:'testRole'})
])
).then(([org,user,role]) => 
  user.addRole({roleId:'testRole',organizationId:org.id})
);
```

## What do you expect to happen?

I expect to add it. 

## What is actually happening?

It says invalid value. 

```
Unhandled rejection Error: Invalid value { roleId: 'testRole', organizationId: 1 }
    at Object.escape (/Users/developer1/Documents/dev/proy1/proy1-vcc-backend/node_modules/sequelize/lib/sql-string.js:51:11)
    at Object.escape (/Users/developer1/Documents/dev/proy1/proy1-vcc-backend/node_modules/sequelize/lib/dialects/abstract/query-generator.js:924:22)
    at _joinKeyValue.value.map.item (/Users/developer1/Documents/dev/proy1/proy1-vcc-backend/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2314:69)
    at Array.map (<anonymous>)
    at Object._whereParseSingleValueObject (/Users/developer1/Documents/dev/proy1/proy1-vcc-backend/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2314:52)
    at Object.whereItemQuery (/Users/developer1/Documents/dev/proy1/proy1-vcc-backend/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2077:19)
    at Utils.getComplexKeys.forEach.prop (/Users/developer1/Documents/dev/proy1/proy1-vcc-backend/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1944:25)
    at Array.forEach (<anonymous>)
    at Object.whereItemsQuery (/Users/developer1/Documents/dev/proy1/proy1-vcc-backend/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1942:35)
    at Object.whereQuery (/Users/developer1/Documents/dev/proy1/proy1-vcc-backend/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1915:24)
    at Object.updateQuery (/Users/developer1/Documents/dev/proy1/proy1-vcc-backend/node_modules/sequelize/lib/dialects/abstract/query-generator.js:367:19)
    at QueryInterface.bulkUpdate (/Users/developer1/Documents/dev/proy1/proy1-vcc-backend/node_modules/sequelize/lib/query-interface.js:948:37)
    at Promise.try.then.then.then.results (/Users/developer1/Documents/dev/proy1/proy1-vcc-backend/node_modules/sequelize/lib/model.js:2768:34)
    at tryCatcher (/Users/developer1/Documents/dev/proy1/proy1-vcc-backend/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/developer1/Documents/dev/proy1/proy1-vcc-backend/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/developer1/Documents/dev/proy1/proy1-vcc-backend/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/developer1/Documents/dev/proy1/proy1-vcc-backend/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/developer1/Documents/dev/proy1/proy1-vcc-backend/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/developer1/Documents/dev/proy1/proy1-vcc-backend/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/developer1/Documents/dev/proy1/proy1-vcc-backend/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/developer1/Documents/dev/proy1/proy1-vcc-backend/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
```

__Dialect:__ mysql 
__Dialect version:__ 4.15.1
__Database version:__ 5.7.19
__Sequelize version:__ 4.15.1
__Tested with master branch:__  Yes

**Comment by sushantdhiman** [comment]
No where is API we say it supports passing object, It has to be an `Array<Instance>, Array<Pk>, Instance or PK`

You have to pass the instance you want to add

**Comment by panitaxx** [comment]
You are right.  Thanks.
