### ISSUE TITLE
Class constructor Model cannot be invoked without 'new'

### ISSUE THREAD

**Issue by eikebartels** [sequelize/sequelize#8757]
## What are you doing?

When I try to create a record for `User` I get the following issue. 
Im using flow for typeing and bable for converting 

```
const sequelize = new Sequelize(...




module.exports.models = models;

....




```

My babel config 

```
{
  "presets": ["flow","es2015-node5"],
  "plugins": ["transform-class-properties"]
}
```

My Model 
```js
import { Model, Sequelize } from 'sequelize';

export default class User extends Model {
  constructor(){super();}
  id: number;
  // toke: string;
  username: string;
  email: string;
  // isAdmin: bool;

  static fields() {
    return {
        id: {
          type: Sequelize.UUID,
          defaultValue: Sequelize.UUIDV4,
          primaryKey: true,
          allowNull: false,
        },
        email: {
          type: Sequelize.STRING,
          allowNull: false,
        },
        password: {
          type: Sequelize.STRING,
          allowNull: false,
        }
      };
    }
```

## What do you expect to happen?
Creating a database record

## What is actually happening?
Error see below

_Output, either JSON or SQL_

```
{
  "name": "TypeError",
  "message": "Class constructor Model cannot be invoked without 'new'",
  "stack": "TypeError: Class constructor Model cannot be invoked without 'new'\n    at new User (/lib/models/User.js:10:17)\n    at Function.build (/node_modules/sequelize/lib/model.js:1937:12)\n    at Function.create (/node_modules/sequelize/lib/model.js:1988:17)\n    at UserController.signup (/driveddy/lib/controllers/UserActionController.js:33:34)\n    at /lib/routes/userActions.js:36:32\n    at dispatch (/node_modules/koa-compose/index.js:44:32)\n    at next (/node_modules/koa-compose/index.js:45:18)\n    at /node_modules/koa-router/lib/router.js:345:16\n    at dispatch (/node_modules/koa-compose/index.js:44:32)\n    at /node_modules/koa-compose/index.js:36:12\n    at dispatch (/node_modules/koa-router/lib/router.js:350:31)\n    at dispatch (/node_modules/koa/node_modules/koa-compose/index.js:42:32)\n    at next (/node_modules/koa/node_modules/koa-compose/index.js:43:18)\n    at parseBody.then.body (/node_modules/koa-bodyparser/index.js:74:14)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)",
  "status": 500
}
```

__Dialect:__ postgres 
__Dialect version:__ "pg": "^7.4.0",
__Database version:__ ?
__Sequelize version:__ 4.26.0
__Tested with latest release:__ YES

**Note :** I have tried this: https://github.com/sequelize/sequelize/issues/7840 and this https://github.com/sequelize/sequelize/issues/7840

**Comment by sushantdhiman** [comment]
This is not how Model class should be used. Please check https://github.com/sequelize/sequelize/issues/6524#issuecomment-329664805

**Comment by sushantdhiman** [comment]
Also please note pg@7 is not supported https://github.com/sequelize/sequelize/issues/8043 , use pg@6 for now
