### ISSUE TITLE
sqlLite errors: "cannot start a transaction within a transaction" and "cannot commit - no transaction is active" 

### ISSUE THREAD

**Issue by usebaz** [sequelize/sequelize#8759]
## What are you doing?
I run API test with Sequelize. Dialect: `sqlite` and storage: `:memory:`. After update to node v8.9.1. I start receive errors in random cases where used `model.findOrCreate`. Before(with node v6.11.0) I not receive similar errors. Also I dont change version `sequelize` or `sqlite3`.

```js
const [userCard] = await models.userCard.findOrCreate({
        where: {
            card_id: card.get('card_id'),
            user_id: userId,
        },
        defaults: {
            card_id: card.get('card_id'),
            user_id: userId,
            status: 'active',
        },
    });
```

## What is actually happening?
Receive error:
```
{ SequelizeDatabaseError: SQLITE_ERROR: cannot commit - no transaction is active
    at Query.formatError (/home/project/node_modules/sequelize/lib/dialects/sqlite/query.js:423:16)
    at Statement.afterExecute (/home/project/node_modules/sequelize/lib/dialects/sqlite/query.js:119:32)
    at Statement.replacement (/home/project/node_modules/sqlite3/lib/trace.js:19:31)
    at Statement.replacement (/home/project/node_modules/sqlite3/lib/trace.js:19:31)
From previous event:
    at executeSql (/home/project/node_modules/sequelize/lib/dialects/sqlite/query.js:107:21)
    at Database.database.serialize (/home/project/node_modules/sequelize/lib/dialects/sqlite/query.js:278:20)
    at resolve (/home/project/node_modules/sequelize/lib/dialects/sqlite/query.js:102:21)
From previous event:
    at Query.run (/home/project/node_modules/sequelize/lib/dialects/sqlite/query.js:100:12)
    at retry (/home/project/node_modules/sequelize/lib/sequelize.js:543:32)
    at /home/project/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/home/project/node_modules/retry-as-promised/index.js:29:10)
    at Promise.try.then.connection (/home/project/node_modules/sequelize/lib/sequelize.js:543:14)
From previous event:
    at Sequelize.query (/home/project/node_modules/sequelize/lib/sequelize.js:539:8)
    at QueryInterface.commitTransaction (/home/project/node_modules/sequelize/lib/query-interface.js:1280:36)
    at Transaction.commit (/home/project/node_modules/sequelize/lib/transaction.js:67:8)
    at sequelize.transaction.then.then.finally (/home/project/node_modules/sequelize/lib/model.js:2136:28)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Function.findOrCreate (/home/project/node_modules/sequelize/lib/model.js:2133:15)
    at Object.exports.saveCard (/home/project/commons/file.js)
    at <anonymous>
  name: 'SequelizeDatabaseError',
  parent: { Error: SQLITE_ERROR: cannot commit - no transaction is active errno: 1, code: 'SQLITE_ERROR', sql: 'COMMIT;' },
  original: { Error: SQLITE_ERROR: cannot commit - no transaction is active errno: 1, code: 'SQLITE_ERROR', sql: 'COMMIT;' },
  sql: 'COMMIT;' }
```

OR

```
{ SequelizeDatabaseError: SQLITE_ERROR: cannot start a transaction within a transaction
    at Query.formatError (/home/project/node_modules/sequelize/lib/dialects/sqlite/query.js:423:16)
    at Statement.afterExecute (/home/project/node_modules/sequelize/lib/dialects/sqlite/query.js:119:32)
    at Statement.replacement (/home/project/node_modules/sqlite3/lib/trace.js:19:31)
    at Statement.replacement (/home/project/node_modules/sqlite3/lib/trace.js:19:31)
From previous event:
    at executeSql (/home/project/node_modules/sequelize/lib/dialects/sqlite/query.js:107:21)
    at Database.database.serialize (/home/project/node_modules/sequelize/lib/dialects/sqlite/query.js:278:20)
    at resolve (/home/project/node_modules/sequelize/lib/dialects/sqlite/query.js:102:21)
From previous event:
    at Query.run (/home/project/node_modules/sequelize/lib/dialects/sqlite/query.js:100:12)
    at retry (/home/project/node_modules/sequelize/lib/sequelize.js:543:32)
    at /home/project/node_modules/retry-as-promised/index.js:39:21
    at retryAsPromised (/home/project/node_modules/retry-as-promised/index.js:29:10)
    at Promise.try.then.connection (/home/project/node_modules/sequelize/lib/sequelize.js:543:14)
From previous event:
    at Sequelize.query (/home/project/node_modules/sequelize/lib/sequelize.js:539:8)
    at QueryInterface.startTransaction (/home/project/node_modules/sequelize/lib/query-interface.js:1248:27)
    at Transaction.begin (/home/project/node_modules/sequelize/lib/transaction.js:143:8)
    at connectionPromise.then.then (/home/project/node_modules/sequelize/lib/transaction.js:124:24)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Transaction.prepareEnvironment (/home/project/node_modules/sequelize/lib/transaction.js:124:8)
    at Sequelize.transaction (/home/project/node_modules/sequelize/lib/sequelize.js:964:43)
    at Function.findOrCreate (/home/project/node_modules/sequelize/lib/model.js:2078:27)
    at Object.exports.saveCard (/home/project/commons/file.js:102:53)
    at <anonymous>
  name: 'SequelizeDatabaseError',
  parent: 
   { Error: SQLITE_ERROR: cannot start a transaction within a transaction
     errno: 1,
     code: 'SQLITE_ERROR',
     sql: 'BEGIN DEFERRED TRANSACTION;' },
  original: 
   { Error: SQLITE_ERROR: cannot start a transaction within a transaction
     errno: 1,
     code: 'SQLITE_ERROR',
     sql: 'BEGIN DEFERRED TRANSACTION;' },
  sql: 'BEGIN DEFERRED TRANSACTION;' }
```

__Dialect:__ sqlite
__Dialect version:__ 3.1.6 and 3.1.13
__Database version:__ `:memory:`
__Sequelize version:__ 4.22.5 and 4.23.4
__Tested with latest release:__ Yes

This errors not stable reproduced and we API tests wery not stable.

Thanks!

**Comment by usebaz** [comment]
Can someone help?
@sushantdhiman @janmeier @sdepold

**Comment by sushantdhiman** [comment]
Are you using CLS?

**Comment by usebaz** [comment]
@sushantdhiman 
No, I don't use cls.
Also I not directly use transactions.

**Comment by usebaz** [comment]
But I call some DB operations, for not blocking request, in setTimeout calback.

**Comment by sushantdhiman** [comment]
> But I call some DB operations, for not blocking request, in setTimeout calback.

You have long running promises some where then, which are not resolved

**Comment by usebaz** [comment]
I did not understand

**Comment by usebaz** [comment]
@sushantdhiman can this problem be somehow resolved?

**Comment by witem** [comment]
@sushantdhiman ping

**Comment by usebaz** [comment]
@sushantdhiman can this problem be somehow resolved?

**Comment by sushantdhiman** [comment]
I will need a proper SSCCE so this can solved, looks like one or more segments of userland code are issuing transactions at same time, which SQLite is not designed for.

**Comment by goodniceweb** [comment]
@usebaz I've just faced the same issue and turned out it was related to an async loop.

```
const { mapLimit } = require('async')
...
  static async makeItWork (cards, userId) {
    return await mapLimit(cards, 5, async (card) => { // 5 is just an example, basically anything more than 1
      const [userCard] = await models.userCard.findOrCreate({
        where: {
            card_id: card.get('card_id'),
            user_id: userId,
        },
        defaults: {
            card_id: card.get('card_id'),
            user_id: userId,
            status: 'active',
        },
    });
    return userCard;
  }
}
```

For me, it was a bunch of open transactions at the same time, because of the async loop, which tries to create multiple records at the same time. SQLite doesn't support it as far as I'm concerned. Changing the amount of the same operations to 1 in test environment worked for me.
