### ISSUE TITLE
ConnectionManager._refreshDynamicOIDs crash

### ISSUE THREAD

**Issue by vlados** [sequelize/sequelize#8765]
## What are you doing?

```js
new Sequelize(envConfig('postgres_credentials'), {
        logging: logger.info,
        dialect: 'postgres',
        operatorsAliases: false,
        dialectOptions: {
            ssl: true
        },
        pool: {
            max: 1,
            min: 0,
            idle: 100
        }
    });

    global.sequelize
        .authenticate()
        .then(() => {
        })
        .catch((err) => {
            Raven.captureException(err, {tags: {foo: 'bar'}}, () => {
                logger.error(err)
                global.context.done(new Error(err))
            });
        }).done();
```

## What do you expect to happen?
Connect to the postgresql 

## What is actually happening?
```
14:26:15.19 <ERROR> TypeError: (connection || this.sequelize).query(...).then is not a function
    at ConnectionManager._refreshDynamicOIDs (/Users/futurist/code/lambda2/functions/pbz/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:191:7)
    at Promise.tap.tap.connection (/Users/futurist/code/lambda2/functions/pbz/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:161:21)
    at PassThroughHandlerContext.finallyHandler (/Users/futurist/code/lambda2/functions/pbz/node_modules/bluebird/js/release/finally.js:57:23)
    at PassThroughHandlerContext.tryCatcher (/Users/futurist/code/lambda2/functions/pbz/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/futurist/code/lambda2/functions/pbz/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/futurist/code/lambda2/functions/pbz/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/futurist/code/lambda2/functions/pbz/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/futurist/code/lambda2/functions/pbz/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/futurist/code/lambda2/functions/pbz/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/futurist/code/lambda2/functions/pbz/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/futurist/code/lambda2/functions/pbz/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5) (in index.js:163)
Call Stack:
    at Raven.captureException (/Users/futurist/code/lambda2/functions/pbz/index.js:163:24)
    at ClientRequest.<anonymous> (/Users/futurist/code/lambda2/functions/pbz/node_modules/raven/lib/transports.js:53:13)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:594:20)
error: Lambda failed in 3517ms.

```
_Output, either JSON or SQL_

__Dialect: postgres
__Dialect version: 4.5.7
__Database version:__ XXX
__Sequelize version:__.4.27.0
__Tested with latest release:__ Yes (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by ezelohar** [comment]
Hi @vlados 

I am not sure what is stored in globals.sequelize, but you need to use instance returned by `new Sequelize()`.

``` 
const sequelize = new Sequelize(envConfig('postgres_credentials'), {
        logging: logger.info,
        dialect: 'postgres',
        operatorsAliases: false,
        dialectOptions: {
            ssl: true
        },
        pool: {
            max: 1,
            min: 0,
            idle: 100
        }
    });

    sequelize
        .authenticate()
        .then(() => {})
        .catch((err) => {
            Raven.captureException(err, {tags: {foo: 'bar'}}, () => {
                logger.error(err)
                global.context.done(new Error(err))
            });
        }).done();
```

I hope this helps.

**Comment by vlados** [comment]
Its
global.sequalize = new Sequalize...
I just missed copying it

**Comment by sushantdhiman** [comment]
__Dialect version: 4.5.7 ? try using v6

**Comment by akoufatzis** [comment]
Hey guys I have the same issue. I am using: "pg": "7.7.1",
		"pg-hstore": "2.3.2",
