### ISSUE TITLE
SequelizeDatabaseError: Packets out of order. Got: 1 Expected: 7

### ISSUE THREAD

**Issue by LiuWeiMr** [sequelize/sequelize#8783]
The running process abruptly terminated.

2017-12-14 14:21:33: You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
SequelizeDatabaseError: Packets out of order. Got: 1 Expected: 7
    at Query.formatError (/data/migouService/node_modules/_@migou_release-bt-server@1.0.6@@migou/release-bt-server/node_modules/_sequelize@3.31.1@sequelize/lib/dialects/mysql/query.js:175:14)
    at Query._callback (/data/migouService/node_modules/_@migou_release-bt-server@1.0.6@@migou/release-bt-server/node_modules/_sequelize@3.31.1@sequelize/lib/dialects/mysql/query.js:49:21)
    at Query.Sequence.end (/data/migouService/node_modules/_@migou_release-bt-server@1.0.6@@migou/release-bt-server/node_modules/_mysql@2.15.0@mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Protocol.handleParserError (/data/migouService/node_modules/_@migou_release-bt-server@1.0.6@@migou/release-bt-server/node_modules/_mysql@2.15.0@mysql/lib/protocol/Protocol.js:372:14)
    at Parser.write (/data/migouService/node_modules/_@migou_release-bt-server@1.0.6@@migou/release-bt-server/node_modules/_mysql@2.15.0@mysql/lib/protocol/Parser.js:50:14)
    at Protocol.write (/data/migouService/node_modules/_@migou_release-bt-server@1.0.6@@migou/release-bt-server/node_modules/_mysql@2.15.0@mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/data/migouService/node_modules/_@migou_release-bt-server@1.0.6@@migou/release-bt-server/node_modules/_mysql@2.15.0@mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
2017-12-14 14:21:40: Process disconnected from parent !
2017-12-14 14:21:40: RangeError: Invalid string length
    at join (native)
    at Object.stringify (native)
    at stringify (/usr/local/src/node-v6.11.1-linux-x64/lib/node_modules/pm2/node_modules/json-stringify-safe/stringify.js:5:15)
    at ipcSend (/usr/local/src/node-v6.11.1-linux-x64/lib/node_modules/pm2/node_modules/pmx/lib/utils/transport.js:22:29)
    at Object.Transport.send (/usr/local/src/node-v6.11.1-linux-x64/lib/node_modules/pm2/node_modules/pmx/lib/utils/transport.js:33:3)
    at process.uncaughtListener (/usr/local/src/node-v6.11.1-linux-x64/lib/node_modules/pm2/node_modules/pmx/lib/notify.js:55:17)
    at process.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at methodName (/data/migouService/node_modules/_@migou_release-bt-server@1.0.6@@migou/release-bt-server/node_modules/_bluebird@3.5.1@bluebird/js/release/debuggability.js:189:33)
    at activeFireEvent (/data/migouService/node_modules/_@migou_release-bt-server@1.0.6@@migou/release-bt-server/node_modules/_bluebird@3.5.1@bluebird/js/release/debuggability.js:232:44)
    at fireRejectionEvent (/data/migouService/node_modules/_@migou_release-bt-server@1.0.6@@migou/release-bt-server/node_modules/_bluebird@3.5.1@bluebird/js/release/debuggability.js:617:14)
    at Promise._notifyUnhandledRejection (/data/migouService/node_modules/_@migou_release-bt-server@1.0.6@@migou/release-bt-server/node_modules/_bluebird@3.5.1@bluebird/js/release/debuggability.js:64:9)
    at Timeout._onTimeout (/data/migouService/node_modules/_@migou_release-bt-server@1.0.6@@migou/release-bt-server/node_modules/_bluebird@3.5.1@bluebird/js/release/debuggability.js:43:14)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

__Dialect:__ mysql
__Dialect version:__
__Database version:__ mysql  Ver 14.14 Distrib 5.6.36-82.0, for Linux (x86_64) using  6.2
__Sequelize version:__ 3.24.3
__Tested with latest release:__ No

**Comment by sushantdhiman** [comment]
Its not clear from error message what caused the issue, please isolate the issue and try to reproduce it against `sequelize@4`
