### ISSUE TITLE
Using previous() in `afterUpdate`-hook not working

### ISSUE THREAD

**Issue by weyert** [sequelize/sequelize#8803]
## What are you doing?
I am trying to use a `afterUpdate`-hook to check status changes on records so I can inform interested parties For this I am using the model for the hook listed below:

```js
{
      orderDate: {
        type: Sequelize.DATEONLY,
        field: 'date',
        allowNull: false,
      },
      partySize: {
        type: Sequelize.INTEGER,
        field: 'party_size',
        allowNull: false,
      },
      bookingReference: {
        type: Sequelize.STRING,
        field: 'booking_reference',
        allowNull: false,
      },
      status: {
        type: Sequelize.ENUM(
          StatusType.CONFIRMED,
          StatusType.CANCELLED,
          StatusType.NO_SHOW,
          StatusType.ARRIVED,
          StatusType.SEATED,
          StatusType.FINISHED
        ),
        allowNull: false,
      }
    }
```

```js
          afterUpdate: (order, options, fn) => {
            const oldOrderStatus = order.previous('status')
            const orderStatus = order.status
            app.log.debug('Order.afterUpdate() oldOrderStatus: %s orderStatus: %s', oldOrderStatus, orderStatus)
            fn(null, order)
          },
```

I am issuing the following `update`-call to update the record only 

```js
        this.app.orm.Order.update(sanitizedOrderData, {
          where: { id },
          individualHooks: true,
          returning: true,
          transaction: t,
        })
```

## What do you expect to happen?
I am expecting that I am getting the updated record data and that I can access previous value before I updated the order. Together, I am also receiving the new record data as part of the `resolve`-promise in the `Order.update`-call were the record data use field name such as `bookingReference` instead of `book_reference`.

## What is actually happening?
Instead of receiving the data I am getting a runtime error:

```
Error:  TypeError: order.previous is not a function
    at Model.afterUpdate (/Users/xxx/Development/Projects/batch/backend/api/models/Order.js:19:54)
    at Model.tryCatcher (/Users/xxx/Development/Projects/batch/backend/node_modules/bluebird/js/release/util.js:16:23)
```

If I am disable `returning` it works as expected. The `afterUpdate` hook is being called and I can use the `previous`-function.

The generated SQL code:
```
xecuting (31ac8a93-ae42-47aa-b68e-fa38de33879e): START TRANSACTION;
Executing (31ac8a93-ae42-47aa-b68e-fa38de33879e): SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
Executing (31ac8a93-ae42-47aa-b68e-fa38de33879e): SELECT "id", "date" AS "orderDate", "party_size" AS "partySize", "booking_reference" AS "bookingReference", "status", "created_at", "updated_at" FROM "order" AS "Order" WHERE "Order"."id" = '1';
Executing (31ac8a93-ae42-47aa-b68e-fa38de33879e): UPDATE "order" SET "date"='2017-12-06',"updated_at"='2017-12-19 21:52:14.775 +00:00' WHERE "id" = '1' RETURNING *
E
```

__Dialect:__ `postgres`
__Dialect version:__ `pg 6.4.2` 
__Database version:__ `PostgreSQL 9.6.3 on x86_64-pc-linux-gnu, compiled by gcc (Debian 4.9.2-10) 4.9.2, 64-bit`
__Sequelize version:__ `4.28.6`
__Tested with latest release:__ Yes,  (If yes, specify that version)

**Comment by weyert** [comment]
If I turn off `returning` the behaviour is as expected. Where should I look in the code base to find out how  enabling`returning` changes the behaviour of how hooks are being called?

**Comment by weyert** [comment]
Still having this issue

**Comment by ishan2208** [comment]
try `order._previousDataValue.status`

**Comment by TrurlMcByte** [comment]
in _previousDataValue same new data as in dataValues

**Comment by JackNeto** [comment]
This is still an issue. `_previousDataValues` only has correct value when `returning`  is turned off

**Comment by dorshay6** [comment]
Stil happening

**Comment by hdeekshith** [comment]
Is there a fix for this?
It always returns the updated values in both dataValues and _previousDataValues. 
Is there any way to get the old data(before getting updated) and new updated data(after getting updated)?

**Comment by ValheKouneli** [comment]
I use beforeUpdate hook to get the values before and after updating. The "before" values are in item._previousDataValues. However, when I'm logging new rows created to DB, I use afterCreate, because in beforeCreate the id of the newly created row is not known yet (because I use autoIncrement).

**Comment by quangtm210395** [comment]
still have this issue. When the returning: true is enable, the previous() function returning the currentDataValue, the _previousDataValues have the same values as dataValues

**Comment by ChadHelbling** [comment]
This is a bit old but we ran into this; our current work around is to persist the _previousDataValues in the beforeUpdate hook and pass it down to the afterUpdate hook. This is pretty janky solution though. I would expect the _previousDataValues to be maintained if individualHooks = true or returning = true but that doesn't seem to be the case. I have a potential fix that I will open a PR for. 

This is the line that is causing this issue:
https://github.com/sequelize/sequelize/blob/a729c4df41fa3a58fbecaf879265d2fb73d80e5f/src/model.js#L3389

**Comment by WikiRik** [comment]
Reopening now that #14120 will fix this issue

**Comment by kaliahinartem** [comment]
Having the same problem

**Comment by bijx** [comment]
> This is a bit old but we ran into this; our current work around is to persist the _previousDataValues in the beforeUpdate hook and pass it down to the afterUpdate hook. This is pretty janky solution though. I would expect the _previousDataValues to be maintained if individualHooks = true or returning = true but that doesn't seem to be the case. I have a potential fix that I will open a PR for.
> 
> This is the line that is causing this issue:
> 
> https://github.com/sequelize/sequelize/blob/a729c4df41fa3a58fbecaf879265d2fb73d80e5f/src/model.js#L3389

Did you pass the previous data values from the `beforeUpdate` to the `afterUpdate` via afterUpdate's options parameter?

**Comment by ChadHelbling** [comment]
yeah, it seemed like the cleanest way to go about it.

**Comment by charlie-s** [comment]
I commented over at https://github.com/sequelize/sequelize/pull/14120. I have time to commit to this issue.

For the time being, in my use case, I will load and iterate over model instances to have `afterUpdate` behave consistently across my codebase.
