### ISSUE TITLE
PostgreSQL: Changing a column DataType throws TypeError

### ISSUE THREAD

**Issue by pdunc** [sequelize/sequelize#8805]
## What are you doing?
Changing a column DataType in a `postgres` database - from an `INTEGER` to a `BIGINT`.

## What do you expect to happen?
The DataType to change and the command to return successfully.

## What is actually happening?

The SQL runs successfully (column DataType has changed) but the following exception is thrown:

```
ERROR: TypeError: Cannot read property '0' of undefined
    at query.catch.then.then.queryResult (C:\seq_example\node_modules\sequelize\lib\dialects\postgres\query.js:112:17)
    at tryCatcher (C:\seq_example\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\seq_example\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\seq_example\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\seq_example\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\seq_example\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\seq_example\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\seq_example\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\seq_example\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)
```

Looking at `query.js:112:17` the `queryResult` has an empty `rows` attribute, which throws the exceptions when `rows[0]` is executed.

__Dialect:__ postgres
__Dialect version:__ ?
__Database version:__ 10.1
__Sequelize version:__ 4.28.6
__Sequelize CLI version:__ 3.2.0
__Tested with latest release:__ Yes, latest `npm`

## Package.json

```json
{
  "name": "seq_example",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "pg": "^7.4.0",
    "sequelize": "^4.28.6",
    "sequelize-cli": "^3.2.0"
  }
}
```

## Models
```js
module.exports = (sequelize, DataTypes) => {
  var Simple = sequelize.define('Simple', {
    id: {
      type: DataType.INTEGER,
      primaryKey: true,
    },
  })
  return Simple;
};
```

## Migration
```js
'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    /*
      Add altering commands here.
      Return a promise to correctly handle asynchronicity.

      Example:
      return queryInterface.createTable('users', { id: Sequelize.INTEGER });
    */
    return queryInterface
    .changeColumn('Simples', 'id', {
      type: Sequelize.BIGINT(),
      allowNull: false
    });

  },

  down: (queryInterface, Sequelize) => {
    /*
      Add reverting commands here.
      Return a promise to correctly handle asynchronicity.

      Example:
      return queryInterface.dropTable('users');
    */
    return queryInterface
    .changeColumn('Simples', 'id', {
      type: Sequelize.INTEGER(),
      allowNull: false
    });
  }
};
```

**Comment by sushantdhiman** [comment]
> "pg": "^7.4.0",

Not supported, https://github.com/sequelize/sequelize/issues/8043

**Comment by pdunc** [comment]
Thanks, changed to 6.4.x and working correctly.

**Comment by SalmanSaleem1** [comment]
Not working correctly
