### ISSUE TITLE
chnageColumn throws an error for postgres

### ISSUE THREAD

**Issue by sergik** [sequelize/sequelize#8817]
try to change column in migration like this:
```
 migration.changeColumn(
                'userprofiles',
                'login',
                {
                    type      : DataTypes.STRING,
                    allowNull : false
                }
            )
```

got an error:

```
Unhandled rejection TypeError: Cannot read property '0' of undefined
    at query.catch.then.then.queryResult (D:\dev\workspaces\workspaces\node_modules\sequelize\lib\dialects\postgres\query.js:112:17)
    at tryCatcher (D:\dev\workspaces\workspaces\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\dev\workspaces\workspaces\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\dev\workspaces\workspaces\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\dev\workspaces\workspaces\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\dev\workspaces\workspaces\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (D:\dev\workspaces\workspaces\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (D:\dev\workspaces\workspaces\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (D:\dev\workspaces\workspaces\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

everything is changed in db but undefined returned in query method. So could not get first item of undefined.

**Comment by sushantdhiman** [comment]
pg@7 is not supported, Follow the issue template

**Comment by sergik** [comment]
we have pg 9.6 not 7

**Comment by ajbeach2** [comment]
I have this same issue. I am on postgres 10

**Comment by aakashmalhotra** [comment]
He means npm package pg (version 7) not the version of postgres
