### ISSUE TITLE
Cannot read property 'X' of undefined when defining a model using JSONB

### ISSUE THREAD

**Issue by ChristianTucker** [sequelize/sequelize#8824]
## What are you doing?
I'm attempting to construct a model (dialect: `postgres`) that uses the `JSONB` DataType.

```js
    var Profile = sequelize.define('Profile', {
        id: {
            type: DataTypes.STRING,
            primaryKey: true
        },
        lastLogin: {
            type: DataTypes.DATE,
            allowNull: false,
            defaultValue: sequelize.fn('NOW')
        },
        attributes: {
            type: DataTypes.JSONB,
            allowNull: false
        }
    }, { freezeTableName: true });
```
Here's my setup code, just incase..

```javascript
    var sequelize = new Sequelize('postgres://......j', {
        port: 5432,
        dialectOptions: { ssl: true },
        dialect: 'postgres',
        pool: { min: 1, max: 1, idle: 3000 }
    });

    var models = {
        Profile: sequelize.import('../models/Profile'),
    }
```
## What do you expect to happen?
For the Model to be successfully created.

## What is actually happening?
```
TypeError: Cannot read property 'attributes' of undefined     at model.set (/user_code/node_modules/sequelize/lib/model.js:3264:40)     at model.funcs.(anonymous function) (/user_code/node_modules/sequelize/lib/model.js:916:25)     at Function.refreshAttributes (/user_code/node_modules/sequelize/lib/model.js:1079:31)     at Function.init (/user_code/node_modules/sequelize/lib/model.js:841:10)     at Sequelize.define (/user_code/node_modules/sequelize/lib/sequelize.js:336:11)     at exports.default (/user_code/express/models/Profile.js:8:29)     at Sequelize.import (/user_code/node_modules/sequelize/lib/sequelize.js:392:32)     at exports.default (/user_code/express/middleware/connectSequelize.js:20:34)     at Layer.handle [as handle_request] (/user_code/node_modules/express/lib/router/layer.js:95:5)     at trim_prefix (/user_code/node_modules/express/lib/router/index.js:317:13)     at /user_code/node_modules/express/lib/router/index.js:284:7     at Function.process_params (/user_code/node_modules/express/lib/router/index.js:335:12)     at next (/user_code/node_modules/express/lib/router/index.js:275:10)     at cors (/user_code/node_modules/cors/lib/index.js:188:7)     at /user_code/node_modules/cors/lib/index.js:224:17     at originCallback (/user_code/node_modules/cors/lib/index.js:214:15)     at /user_code/node_modules/cors/lib/index.js:219:13     at optionsCallback (/user_code/node_modules/cors/lib/index.js:199:9)     at corsMiddleware (/user_code/node_modules/cors/lib/index.js:204:7)     at Layer.handle [as handle_request] (/user_code/node_modules/express/lib/router/layer.js:95:5)     at trim_prefix (/user_code/node_modules/express/lib/router/index.js:317:13)     at /user_code/node_modules/express/lib/router/index.js:284:7
```

--

__Dialect:__ postgres
__Dialect version:__ pg@6
__Database version:__ 10.1
__Sequelize version:__ ^4.28.6
__Tested with latest release:__ Yes

--

Additional Information:

I am not acting on the database other than calling `sync()` I am not trying to insert, find, or issue any query to the database.

**Comment by janmeier** [comment]
This might be because you don't allow nulls, but don't set a default value (if that is the case, the error message is not very informative though..)

**Comment by ChristianTucker** [comment]
@janmeier  Forgot to close this, it's actually because `attributes` is a keyword in postgres.
