### ISSUE TITLE
 TypeError: Class constructor model cannot be invoked without 'new'

### ISSUE THREAD

**Issue by Bondifrench** [sequelize/sequelize#8854]
## What are you doing?

Was trying to create a table.

```js
var Sequelize = require('Sequelize');
var config = require('../Config/config');
var sequelize = new Sequelize(config.database, config.username, config.password, {
	dialect: 'mssql',
	host: config.server,
	dialectOptions: {
		port: '1433',
		domain: config.domain,
		encrypt: true
	}
});

var ReportInfo = sequelize.define('reportInfo', {
	"report_type": {
		"type": Sequelize.STRING,
		"primaryKey": false
	},
	"analyst_id": {
		"type": Sequelize.INTEGER,
	},
	"title": {
		"type": Sequelize.STRING,
		"allowNull": true,
	},
	"issuer_id": {
		"type": Sequelize.INTEGER,
	}
}, {
	"freezeTableName": true,
	"tableName": "ReportInfo",
	"schema": "Forecast"
});

sequelize
	.sync()
	.then(function() {
		return ReportInfo(sequelize, Sequelize)
			.findAll({})
			.then(function(reports) {
				reports.forEach(function(report) {
					console.log(report.toJSON())
				})
				console.log('Number of rows: ', reports.length);
			})
	})
	.catch(function(error) {
		console.log('Error: ', error)
	})
```

## What do you expect to happen?
It did create the table `Forecast.ReportInfo` but with the following error message.

## What is actually happening?

_Output:  SQL_

```
sequelize deprecated String based operators are now deprecated. Please use Symbo
l based operators for better security, read more at http://docs.sequelizejs.com/
manual/tutorial/querying.html#operators ..\node_modules\Sequelize\lib\sequelize.
js:236:13                                                                       
Executing (default): IF OBJECT_ID('[Forecast].[ReportInfo]', 'U') IS NULL CREATE
 TABLE [Forecast].[ReportInfo] ([id] INTEGER NOT NULL IDENTITY(1,1) , [report_ty
pe] NVARCHAR(255) NULL, [analyst_id] INTEGER NULL, [title] NVARCHAR(255) NULL, [
issuer_id] INTEGER NULL, [createdAt] DATETIMEOFFSET NOT NULL, [updatedAt] DATETI
MEOFFSET NOT NULL, PRIMARY KEY ([id]));                                         
Executing (default): EXEC sys.sp_helpindex @objname = N'[Forecast].[ReportInfo]'
;                                                                               
Error:  TypeError: Class constructor model cannot be invoked without 'new'      
    at C:\Users\DMNDKA\OneDrive - AMP Services Ltd\TestApp\Tests\sqlQuery.js:124
:10                                                                             
    at tryCatcher (C:\Users\DMNDKA\OneDrive - AMP Services Ltd\TestApp\node_modu
les\bluebird\js\release\util.js:16:23)                                          
    at Promise._settlePromiseFromHandler (C:\Users\DMNDKA\OneDrive - AMP Service
s Ltd\TestApp\node_modules\bluebird\js\release\promise.js:512:31)               
    at Promise._settlePromise (C:\Users\DMNDKA\OneDrive - AMP Services Ltd\TestA
pp\node_modules\bluebird\js\release\promise.js:569:18)                          
    at Promise._settlePromise0 (C:\Users\DMNDKA\OneDrive - AMP Services Ltd\Test
App\node_modules\bluebird\js\release\promise.js:614:10)                         
    at Promise._settlePromises (C:\Users\DMNDKA\OneDrive - AMP Services Ltd\Test
App\node_modules\bluebird\js\release\promise.js:693:18)                         
    at Async._drainQueue (C:\Users\DMNDKA\OneDrive - AMP Services Ltd\TestApp\no
de_modules\bluebird\js\release\async.js:133:16)                                 
    at Async._drainQueues (C:\Users\DMNDKA\OneDrive - AMP Services Ltd\TestApp\n
ode_modules\bluebird\js\release\async.js:143:10)                                
    at Immediate.Async.drainQueues (C:\Users\DMNDKA\OneDrive - AMP Services Ltd\
TestApp\node_modules\bluebird\js\release\async.js:17:14)                        
    at runCallback (timers.js:672:20)                                           
    at tryOnImmediate (timers.js:645:5)                                         
    at processImmediate [as _immediateCallback] (timers.js:617:5)               
```
__Dialect:__ mssql
__Dialect version:__ node v6.11.1
__Database version:__ SQL Server 2012
__Sequelize version:__ 4.13.8
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by Bondifrench** [comment]
Was an issue on my side, closing

**Comment by clintonmedbery** [comment]
@Bondifrench Why not share your solution to help others?

**Comment by tebinumbiz** [comment]
What did you do to fix? I'm having the same issue. Please share!
