### ISSUE TITLE
findOrCreate provides invalid error value 

### ISSUE THREAD

**Issue by silksil** [sequelize/sequelize#8878]
## What are you doing?
I want to check if a entry is already created, if not created, associate it to the model that stands to the many to many relationship.

```
const Sequelize = require('sequelize');
const sequelize = new Sequelize('finalproject', 'postgres', 'jurgen', {
  host: 'localhost',
  dialect: "postgres"
})

  const Employee = sequelize.define('employees', {
    email: {
      type: Sequelize.STRING
    }
  })


const Skill = sequelize.define('skills', {
  skill: {
    type: Sequelize.STRING
  },
});

Skill.belongsToMany(Employee, {
  through: 
    'employee_skills'
})
Employee.belongsToMany(Skill, {
  through: 
    'employee_skills'
})

sequelize.sync({force: true}).then(() => {
  Employee.create({
    email: "test@user.com"
  })
  .then((foundEmployee)=>{
    return Promise.all([Skill.findOrCreate({where: {skill: "smelly"}})])
    .then((theSKills) => {
      return foundEmployee.setSkills(theSKills)
    })
  })
  .catch((e) => {
    throw e
  })
})


```
## What do you expect to happen?
I expect that a relation between the found or created skill is set to the user 'employee'. With create it does work with findOrCreate it does not work. 

## What is actually happening?

```
> Executing (default): DROP TABLE IF EXISTS "employee_skills" CASCADE;
> Executing (default): DROP TABLE IF EXISTS "skills" CASCADE;
> Executing (default): DROP TABLE IF EXISTS "employees" CASCADE;
> Executing (default): DROP TABLE IF EXISTS "employees" CASCADE;
> Executing (default): CREATE TABLE IF NOT EXISTS "employees" ("id"   SERIAL , "email" VARCHAR(255), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));
> Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'employees' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
> Executing (default): DROP TABLE IF EXISTS "skills" CASCADE;
> Executing (default): CREATE TABLE IF NOT EXISTS "skills" ("id"   SERIAL , "skill" VARCHAR(255), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));
> Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'skills' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
> Executing (default): DROP TABLE IF EXISTS "employee_skills" CASCADE;
> Executing (default): CREATE TABLE IF NOT EXISTS "employee_skills" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "skillId" INTEGER  REFERENCES "skills" ("id") ON DELETE CASCADE ON UPDATE CASCADE, "employeeId" INTEGER  REFERENCES "employees" ("id") ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY ("skillId","employeeId"));
> Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'employee_skills' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
> Executing (default): INSERT INTO "employees" ("id","email","createdAt","updatedAt") VALUES (DEFAULT,'test@user.com','2018-01-11 17:04:21.178 +00:00','2018-01-11 17:04:21.178 +00:00') RETURNING *;
> Executing (feb150e1-dd0e-4f81-9829-f81541b32b3d): START TRANSACTION;
> Executing (feb150e1-dd0e-4f81-9829-f81541b32b3d): SELECT "id", "skill", "createdAt", "updatedAt" FROM "skills" AS "skills" WHERE "skills"."skill" = 'smelly' LIMIT 1;
> Executing (feb150e1-dd0e-4f81-9829-f81541b32b3d): CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response "skills", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_e0a631f7f79b4a1585e5c62d1f41b669$ BEGIN INSERT INTO "skills" ("id","skill","createdAt","updatedAt") VALUES (DEFAULT,'smelly','2018-01-11 17:04:21.266 +00:00','2018-01-11 17:04:21.266 +00:00') RETURNING * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_e0a631f7f79b4a1585e5c62d1f41b669$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();
> Executing (feb150e1-dd0e-4f81-9829-f81541b32b3d): COMMIT;
> Executing (default): SELECT "createdAt", "updatedAt", "skillId", "employeeId" FROM "employee_skills" AS "employee_skills" WHERE "employee_skills"."employeeId" = 1;
```

Two errors: 
Error 1 when using version  pg 7.4.1:

```


Unhandled rejection TypeError: Cannot read property '0' of undefined
    at query.catch.then.then.queryResult (/Users/Silk/Desktop/Exercises/hand-ins/finalproject/node_modules/sequelize/lib/dialects/postgres/query.js:112:17)
    at tryCatcher (/Users/Silk/Desktop/Exercises/hand-ins/finalproject/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Silk/Desktop/Exercises/hand-ins/finalproject/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/Silk/Desktop/Exercises/hand-ins/finalproject/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/Silk/Desktop/Exercises/hand-ins/finalproject/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/Silk/Desktop/Exercises/hand-ins/finalproject/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/Silk/Desktop/Exercises/hand-ins/finalproject/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/Silk/Desktop/Exercises/hand-ins/finalproject/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/Silk/Desktop/Exercises/hand-ins/finalproject/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)


```
Error2 when using version 6.4.2:

```
Unhandled rejection Error: Invalid value skills {
  dataValues: 
   { id: 1,
     skill: 'smelly',
     updatedAt: 2018-01-11T17:04:21.266Z,
     createdAt: 2018-01-11T17:04:21.266Z },
  _previousDataValues: 
   { skill: 'smelly',
     id: 1,
     createdAt: 2018-01-11T17:04:21.266Z,
     updatedAt: 2018-01-11T17:04:21.266Z },
  _changed: { skill: false, id: false, createdAt: false, updatedAt: false },
  _modelOptions: 
   { timestamps: true,
     validate: {},
     freezeTableName: false,
     underscored: false,
     underscoredAll: false,
     paranoid: false,
     rejectOnEmpty: false,
     whereCollection: { skill: 'smelly' },
     schema: null,
     schemaDelimiter: '',
     defaultScope: {},
     scopes: [],
     indexes: [],
     name: { plural: 'skills', singular: 'skill' },
     omitNull: false,
     sequelize: 
      Sequelize {
        options: [Object],
        config: [Object],
        dialect: [Object],
        queryInterface: [Object],
        models: [Object],
        modelManager: [Object],
        connectionManager: [Object],
        importCache: {},
        test: [Object] },
     hooks: {},
     uniqueKeys: {} },
  _options: 
   { isNewRecord: true,
     _schema: null,
     _schemaDelimiter: '',
     attributes: undefined,
     include: undefined,
     raw: undefined,
     silent: undefined },
  __eagerlyLoadedAssociations: [],
  isNewRecord: false }
    at Object.escape (/Users/Silk/Desktop/Exercises/hand-ins/finalproject/node_modules/sequelize/lib/sql-string.js:51:11)
    at Object.wrapper [as escape] (/Users/Silk/Desktop/Exercises/hand-ins/finalproject/node_modules/lodash/lodash.js:5232:19)
    at ARRAY.str.ARRAY[.values.map.value (/Users/Silk/Desktop/Exercises/hand-ins/finalproject/node_modules/sequelize/lib/dialects/postgres/data-types.js:573:22)
    at Array.map (native)
    at ARRAY._stringify (/Users/Silk/Desktop/Exercises/hand-ins/finalproject/node_modules/sequelize/lib/dialects/postgres/data-types.js:565:33)
    at ARRAY.stringify (/Users/Silk/Desktop/Exercises/hand-ins/finalproject/node_modules/sequelize/lib/data-types.js:32:17)
    at Object.escape (/Users/Silk/Desktop/Exercises/hand-ins/finalproject/node_modules/sequelize/lib/sql-string.js:45:40)
    at Object.escape (/Users/Silk/Desktop/Exercises/hand-ins/finalproject/node_modules/sequelize/lib/dialects/abstract/query-generator.js:927:22)
    at tuples.push.(.allAttributes.map.key (/Users/Silk/Desktop/Exercises/hand-ins/finalproject/node_modules/sequelize/lib/dialects/abstract/query-generator.js:247:21)
    at Array.map (native)
    at Object.bulkInsertQuery (/Users/Silk/Desktop/Exercises/hand-ins/finalproject/node_modules/sequelize/lib/dialects/abstract/query-generator.js:243:39)
    at QueryInterface.bulkInsert (/Users/Silk/Desktop/Exercises/hand-ins/finalproject/node_modules/sequelize/lib/query-interface.js:987:37)
    at Promise.try.then.then (/Users/Silk/Desktop/Exercises/hand-ins/finalproject/node_modules/sequelize/lib/model.js:2416:36)
    at tryCatcher (/Users/Silk/Desktop/Exercises/hand-ins/finalproject/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Silk/Desktop/Exercises/hand-ins/finalproject/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/Silk/Desktop/Exercises/hand-ins/finalproject/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/Silk/Desktop/Exercises/hand-ins/finalproject/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/Silk/Desktop/Exercises/hand-ins/finalproject/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/Silk/Desktop/Exercises/hand-ins/finalproject/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/Silk/Desktop/Exercises/hand-ins/finalproject/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/Users/Silk/Desktop/Exercises/hand-ins/finalproject/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/Users/Silk/Desktop/Exercises/hand-ins/finalproject/node_modules/bluebird/js/release/promise.js:569:18)


```

__Dialect:__postgres
__Dialect version:__ pg 7.4.1, 6.4.2
__Database version:__ postgres(10.1)
__Sequelize version:__ 4.31.0
__Tested with latest release:__ Yes, 4.31.0

**Comment by Piepongwong** [comment]
I was able to reproduce the error and locate the issue in the sequelize module. I tried to use the findCreateFind method, a simplified version of findOrCreate. That gave me the same error.  It has to do with the fact that findOrCreate does not return an object, but an array with the found or created object and a boolean that indicates if the object was created.  In the "sql-string.js" file this kind of return value is not covered, probably rightfully so .

In the model.js file of the sequelize library I changed the findCreateFind method in such a way that it only returns only a simple instance instead of an array consisting of an instance and a boolean. Although this fixes the error, I do not think this is the desirable solution.

**Comment by Piepongwong** [comment]
Now I think of it, it might be a solution. The only reason I can think of to keep the array instead of the simple object, is that the array preserves information about the instance being created or found. However, the simple object keeps track of that info as well. Would that not mean that the array is not only causing issues, but is also redundant?

That said, I do not know the codebase of sequelize and I do not know what kind of consequenses this could have.

**Comment by sushantdhiman** [comment]
`Model.findOrCreate` returns `Promise<Mode, created>`

http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-findOrCreate

Also `pg@7` is not supported, its mentioned in Readme and Docs

**Comment by Piepongwong** [comment]
This is tested with pg7 AND pg6.4.2 as is mentioned in the issue description.

**Comment by sushantdhiman** [comment]
`findOrCreate` returns an array, you need to use `spread` instead of `then` if you want to use instance directly

**Comment by Piepongwong** [comment]
That is indeed a much better solution than changing the source code. ^^ Thanks!
