### ISSUE TITLE
Deadlocks MSSQL

### ISSUE THREAD

**Issue by SteveyPugs** [sequelize/sequelize#8956]
## What are you doing?

```js
{"level":"info","message":"SequelizeDatabaseError: Transaction (Process ID 66) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.\n    at Query.formatError (D:\\http\\tax-processing-services-bony\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:265:10)\n    at Request.userCallback (D:\\http\\tax-processing-services-bony\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:90:25)\n    at Request.callback (D:\\http\\tax-processing-services-bony\\node_modules\\tedious\\lib\\request.js:30:27)\n    at Connection.STATE.SENT_CLIENT_REQUEST.events.message (D:\\http\\tax-processing-services-bony\\node_modules\\tedious\\lib\\connection.js:281:29)\n    at Connection.dispatchEvent (D:\\http\\tax-processing-services-bony\\node_modules\\tedious\\lib\\connection.js:750:59)\n    at MessageIO.<anonymous> (D:\\http\\tax-processing-services-bony\\node_modules\\tedious\\lib\\connection.js:683:22)\n    at emitNone (events.js:67:13)\n    at MessageIO.emit (events.js:166:7)\n    at MessageIO.eventData (D:\\http\\tax-processing-services-bony\\node_modules\\tedious\\lib\\message-io.js:58:21)\n    at Socket.<anonymous> (D:\\http\\tax-processing-services-bony\\node_modules\\tedious\\lib\\message-io.js:3:57)\n    at emitOne (events.js:77:13)\n    at Socket.emit (events.js:169:7)\n    at readableAddChunk (_stream_readable.js:153:18)\n    at Socket.Readable.push (_stream_readable.js:111:10)\n    at TCP.onread (net.js:536:20)","timestamp":"2018-01-25 17:32:58"}
{"level":"info","message":"SequelizeDatabaseError: Transaction (Process ID 53) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.\n    at Query.formatError (D:\\http\\tax-processing-services-bony\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:265:10)\n    at Request.userCallback (D:\\http\\tax-processing-services-bony\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:90:25)\n    at Request.callback (D:\\http\\tax-processing-services-bony\\node_modules\\tedious\\lib\\request.js:30:27)\n    at Connection.STATE.SENT_CLIENT_REQUEST.events.message (D:\\http\\tax-processing-services-bony\\node_modules\\tedious\\lib\\connection.js:281:29)\n    at Connection.dispatchEvent (D:\\http\\tax-processing-services-bony\\node_modules\\tedious\\lib\\connection.js:750:59)\n    at MessageIO.<anonymous> (D:\\http\\tax-processing-services-bony\\node_modules\\tedious\\lib\\connection.js:683:22)\n    at emitNone (events.js:67:13)\n    at MessageIO.emit (events.js:166:7)\n    at MessageIO.eventData (D:\\http\\tax-processing-services-bony\\node_modules\\tedious\\lib\\message-io.js:58:21)\n    at Socket.<anonymous> (D:\\http\\tax-processing-services-bony\\node_modules\\tedious\\lib\\message-io.js:3:57)\n    at emitOne (events.js:77:13)\n    at Socket.emit (events.js:169:7)\n    at readableAddChunk (_stream_readable.js:153:18)\n    at Socket.Readable.push (_stream_readable.js:111:10)\n    at TCP.onread (net.js:536:20)","timestamp":"2018-01-26 12:29:53"}
{"level":"info","message":"SequelizeDatabaseError: Transaction (Process ID 59) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.\n    at Query.formatError (D:\\http\\tax-processing-services-bony\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:265:10)\n    at Request.userCallback (D:\\http\\tax-processing-services-bony\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:90:25)\n    at Request.callback (D:\\http\\tax-processing-services-bony\\node_modules\\tedious\\lib\\request.js:30:27)\n    at Connection.STATE.SENT_CLIENT_REQUEST.events.message (D:\\http\\tax-processing-services-bony\\node_modules\\tedious\\lib\\connection.js:281:29)\n    at Connection.dispatchEvent (D:\\http\\tax-processing-services-bony\\node_modules\\tedious\\lib\\connection.js:750:59)\n    at MessageIO.<anonymous> (D:\\http\\tax-processing-services-bony\\node_modules\\tedious\\lib\\connection.js:683:22)\n    at emitNone (events.js:67:13)\n    at MessageIO.emit (events.js:166:7)\n    at MessageIO.eventData (D:\\http\\tax-processing-services-bony\\node_modules\\tedious\\lib\\message-io.js:58:21)\n    at Socket.<anonymous> (D:\\http\\tax-processing-services-bony\\node_modules\\tedious\\lib\\message-io.js:3:57)\n    at emitOne (events.js:77:13)\n    at Socket.emit (events.js:169:7)\n    at readableAddChunk (_stream_readable.js:153:18)\n    at Socket.Readable.push (_stream_readable.js:111:10)\n    at TCP.onread (net.js:536:20)","timestamp":"2018-01-26 13:30:55"}
```

## What do you expect to happen?
We constantly get deadlocks on large sets of data that is running asynchronously. We have instituted retries which is does not help.

## What is actually happening?
Not get deadlocks.

__Dialect:__ mssql 
__Database version:__ 2008
__Sequelize version:__ 3.18-3.31
__Tested with latest release:__ No

**Comment by sushantdhiman** [comment]
Deadlock error are not caused by Sequelize, your are updating rows in different processes (at SQL server level) which block each other. There are two solutions to deallock

1. Analyze your updates and try to minimize dependencies between two different asynchronous update calls. So one update don't block other.
2. Try with more accommodating isolation level.

**Comment by SteveyPugs** [comment]
@sushantdhiman would you have any suggestions on how to do point 1? The isolation level concept won't work with our system

**Comment by sushantdhiman** [comment]
@SteveyPugs Deadlock conditions are highly specific to application, there is no general way to identify one other than profiling and checking queries which could have caused deadlock. I hope this [stackoverflow answer](https://stackoverflow.com/a/21438081/4021724) helps
