### ISSUE TITLE
belongsToMany associations break with global default scope

### ISSUE THREAD

**Issue by nwalters512** [sequelize/sequelize#8998]
## What are you doing?
Following the advice in #6229, I addeda `defaultScope` to exclude the created/updated timestamps from all queries by default. Below is a minimal case that reproduces the issue I'm seeing.

```js
const Sequelize = require('sequelize')

const sequelize = new Sequelize({
  dialect: 'sqlite',
  storage: './demo.sqlite',
  logging: true,
  define: {
    defaultScope: {
      attributes: {
        exclude: ['createdAt', 'updatedAt'],
      },
    },
  },
})

const User = sequelize.define('user', {
  name: Sequelize.STRING,
})

const Course = sequelize.define('course', {
  name: Sequelize.STRING,
})

User.belongsToMany(Course, { as: 'staffAssignments', through: 'staffAssignment' })
Course.belongsToMany(User, { as: 'staff', through: 'staffAssignment' })

sequelize.sync({ force: true }).then(() => {
  User.findOrCreate({ where: { name: 'test1' } }).spread((user) => {
    Course.findOrCreate({ where: { name: 'test2' } }).spread((course) => {
      // Fails with `Unhandled rejection SequelizeDatabaseError: SQLITE_ERROR: no such column: id`
      user.addStaffAssignment(course)
    })
  })
})
```

## What do you expect to happen?
An appropriate entry linking my `course` and `user` should be created in the `staffAssignment` table.

## What is actually happening?
Sequelize attempts to query the `staffAssignment` for the non-existent `id` column

```
Executing (default): SELECT `id` FROM `staffAssignment` AS `staffAssignment` WHERE `staffAssignment`.`userId` = 1 AND `staffAssignment`.`courseId` IN (1);
Unhandled rejection SequelizeDatabaseError: SQLITE_ERROR: no such column: id
    at Query.formatError (/Users/nathan/git/queue/node_modules/sequelize/lib/dialects/sqlite/query.js:423:16)
    at afterExecute (/Users/nathan/git/queue/node_modules/sequelize/lib/dialects/sqlite/query.js:119:32)
    at replacement (/Users/nathan/git/queue/node_modules/sqlite3/lib/trace.js:19:31)
    at Statement.errBack (/Users/nathan/git/queue/node_modules/sqlite3/lib/sqlite3.js:16:21)
```

When I remove the default scope, Sequelize goes back to querying `staffAssignment` correctly:

```
Executing (default): SELECT `createdAt`, `updatedAt`, `userId`, `courseId` FROM `staffAssignment` AS `staffAssignment` WHERE `staffAssignment`.`userId` = 1 AND `staffAssignment`.`courseId` IN (1);
Executing (default): INSERT INTO `staffAssignment` (`createdAt`,`updatedAt`,`userId`,`courseId`) VALUES ('2018-02-05 18:10:31.049 +00:00','2018-02-05 18:10:31.049 +00:00',1,1);
```

__Dialect:__ sqlite
__Dialect version:__ sqlite3@3.1.13
__Database version:__ 3.16.2
__Sequelize version:__ 4.32.6
__Tested with latest release:__ Yes

**Comment by sushantdhiman** [comment]
Two solutions

1. Assign a `primaryKey` to `staffAssignment` table, Sequelize assumes a primary key field.
2. Create a third model for `staffAssignment` and remove autogenerated `primaryKey` by `StaffAssignment.removeAttribute('id')`, that might work

**Comment by nwalters512** [comment]
How is this not a bug? Sequelize clearly doesn't assume a primary key when it's performing a query without a default scope set. This seems to be a problem with how Sequelize generates queries for many-to-many associations.

**Comment by sushantdhiman** [comment]
Sequelize does not support model without `primaryKey`, it automatically inject `id` as a primaryKey. I am afraid that is how it was built and model without primary key are sure to break at one point or another in Sequelize

**Comment by nwalters512** [comment]
The `staffAssignment` table schema was generated by Sequelize; it does contain a primary key but it isn't named `id`. If all tables require a primary key named `id`, then Sequelize should generate tables with that required column.

**Comment by sushantdhiman** [comment]
I tried your example, indeed `staffAssignment` is being created without any primary key. For now I will suggest defining a third model `StaffAssignment` and use it in `through` option.

I am tagging this as bug.
