### ISSUE TITLE
Generated query from sequelize is work in Toad, But the sequelize result is null array.

### ISSUE THREAD

**Issue by dogenius01** [sequelize/sequelize#9004]
## What are you doing?

<model>
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('tReportLog', {
    nReportLogSeq: {
      type: DataTypes.BIGINT,
      allowNull: false,
      primaryKey: true,
      autoIncrement: true
    },
    nUserId: {
      type: DataTypes.INTEGER(10).UNSIGNED,
      allowNull: false
    },
    nServiceType: {
      type: DataTypes.INTEGER(1).UNSIGNED,
      allowNull: false,
      defaultValue: '0'
    },
    sPeriodType: {
      type: DataTypes.CHAR(1),
      allowNull: false,
      defaultValue: 'M'
    },
    sPublisherType: {
      type: DataTypes.CHAR(1),
      allowNull: false,
      defaultValue: 'B'
    },
    sTitle: {
      type: DataTypes.STRING(255),
      allowNull: false
    },
    sContent: {
      type: DataTypes.TEXT,
      allowNull: true
    },
    dtCreateDate: {
      type: DataTypes.DATE,
      allowNull: false,
      defaultValue: '0000-00-00 00:00:00'
    },
    nStartDate: {
      type: DataTypes.INTEGER(11),
      allowNull: false
    },
    sMailList: {
      type: DataTypes.TEXT,
      allowNull: false
    },
    sDeleteYn: {
      type: DataTypes.CHAR(1),
      allowNull: false,
      defaultValue: 'N'
    }
  }, {
    tableName: 'tReportLog'
  });
};

```js
// code here
let readHistory = function (params) {
  // Make where condition
  if (params.endDate) {
    params.endDate = new Date(params.endDate);
    params.endDate = params.endDate.setDate(params.endDate.getDate() + 1);
  }

  let whereConditions = {
    dtCreateDate: {
      [Op.gte]: params.startDate ? params.startDate : '1111-01-01T00:00:00.000Z',
      [Op.lte]: params.endDate ? params.endDate : '9999-12-31T00:00:00.000Z'
    }
  };
  for (const prop in params) {
    if (['nUserId', 'nServiceType', 'sPeriodType', 'sPublisherType', 'sDeleteYn'].includes(prop)) {
      whereConditions[prop] = {[Op.eq]: params[prop]};
    } else if (prop === 'sTitle') {
      whereConditions[prop] = {[Op.like]: '%'+params[prop]+'%'};
    }
  }
  if (!['nReportLogSeq', 'sTitle ', 'dtCreateDate', 'nStartDate', 'sPublisherType'].includes(params.orderType)) {
    params.orderBy = 'nReportLogSeq';
  }

  return new Promise(function (resolve, reject) {
    models.tReportLog.findAll({
      where: whereConditions,
      order: [[(params.orderBy) ? params.orderBy : 'nReportLogSeq', (params.orderType) ? params.orderType : 'DESC']], // 정렬 기준 컬럼, 정렬타입(오름, 내림)
      offset: (params.page) ? (params.page - 1) * (params.limit ? params.limit : 9999) : 0, // row 시작 인덱스값
      limit: (params.limit) ? parseInt(params.limit) : 9999 // 페이지당 row수
    }).then(results => {
      if (results.length) {
        resolve(results);
      } else {
        // report history not found
        reject(null);
      }
    }).catch(function (err) {
      console.error(err);
      reject(null);
    });
  });
};

```

## What do you expect to happen?
Sequelize generated this query (copied from the log) >>
SELECT `nReportLogSeq`, `nUserId`, `nServiceType`, `sPeriodType`, `sPublisherType`, `sTitle`, `sContent`, `dtCreateDate`, `nStartDate`, `sMailList`, `sDeleteYn` FROM `tReportLog` AS `tReportLog` WHERE (`tReportLog`.`dtCreateDate` >= '1111-01-01 09:00:00' AND `tReportLog`.`dtCreateDate` <= '9999-12-31 09:00:00') AND `tReportLog`.`nUserId` = '107' AND `tReportLog`.`sDeleteYn` = 'N' AND `tReportLog`.`sTitle` LIKE '%주간%' ORDER BY `tReportLog`.`nReportLogSeq` DESC LIMIT 0, 9999;

## What is actually happening?

That query returns a record in Toad, But sequelize returns null.

SequelizeDatabaseError: Illegal mix of collations (utf8_general_ci,IMPLICIT) and (euckr_korean_ci,COERCIBLE) for operation 'like'

_Output, either JSON or SQL_

__Dialect:__ mysql 
__Dialect version:__ 
__Database version:__ 
__Sequelize version:__ 4.32.7
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by dogenius01** [comment]
Maybe ... because of the korean word. It works with english word.

**Comment by dogenius01** [comment]
Error: Illegal mix of collations (utf8_general_ci,IMPLICIT) and (euckr_korean_ci,COERCIBLE) for operation 'like'
    at Packet.asError (/usr/local/midibus/report_api/node_modules/mysql2/lib/packets/packet.js:713:13)
    at Query.Command.execute (/usr/local/midibus/report_api/node_modules/mysql2/lib/commands/command.js:28:22)
    at Connection.handlePacket (/usr/local/midibus/report_api/node_modules/mysql2/lib/connection.js:515:28)
    at PacketParser.onPacket (/usr/local/midibus/report_api/node_modules/mysql2/lib/connection.js:94:16)
    at PacketParser.executeStart (/usr/local/midibus/report_api/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.<anonymous> (/usr/local/midibus/report_api/node_modules/mysql2/lib/connection.js:102:29)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
     code: 'ER_CANT_AGGREGATE_2COLLATIONS',
     errno: 1267,
     sqlState: 'HY000',
     sqlMessage: 'Illegal mix of collations (utf8_general_ci,IMPLICIT) and (euckr_korean_ci,COERCIBLE) for operation \'like\'',
     sql: 'SELECT `nReportLogSeq`, `nUserId`, `nServiceType`, `sPeriodType`, `sPublisherType`, `sTitle`, `sContent`, `dtCreateDate`, `nStartDate`, `sMailList`, `sDeleteYn` FROM `tReportLog` AS `tReportLog` WHERE (`tReportLog`.`dtCreateDate` >= \'1111-01-01 09:00:00\' AND `tReportLog`.`dtCreateDate` <= \'9999-12-31 09:00:00\') AND `tReportLog`.`nUserId` = \'107\' AND `tReportLog`.`sDeleteYn` = \'Y\' AND `tReportLog`.`sTitle` LIKE \'%주%\' ORDER BY `tReportLog`.`nReportLogSeq` DESC LIMIT 0, 9999;'

**Comment by dogenius01** [comment]
The table charset and collation is utf8.
