### ISSUE TITLE
"RangeError: Array buffer allocation failed" error

### ISSUE THREAD

**Issue by ArturAralin** [sequelize/sequelize#9011]
Hi! I got error with content

```
[1] 0|api-serv | RangeError: Array buffer allocation failed
[1] 0|api-serv |     at new ArrayBuffer (<anonymous>)
[1] 0|api-serv |     at Buffer.Uint8Array (native)
[1] 0|api-serv |     at FastBuffer (buffer.js:34:5)
[1] 0|api-serv |     at Function.Buffer.alloc (buffer.js:239:10)
[1] 0|api-serv |     at new Buffer (buffer.js:152:19)
[1] 0|api-serv |     at module.exports.Reader.addChunk (/app/node_modules/packet-reader/index.js:35:21)
[1] 0|api-serv |     at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:126:18)
[1] 0|api-serv |     at emitOne (events.js:115:13)
[1] 0|api-serv |     at Socket.emit (events.js:210:7)
[1] 0|api-serv |     at addChunk (_stream_readable.js:252:12)
[1] 0|api-serv |     at readableAddChunk (_stream_readable.js:239:11)
[1] 0|api-serv |     at Socket.Readable.push (_stream_readable.js:197:10)
[1] 0|api-serv |     at TCP.onread (net.js:589:20)
```

This happens when i calls endpoint which calls this function 10 times

```typescript
export const getBusiness = async (params: GetBusinessParams | null, id: number): Promise<CompletePrivateBusinessUser | any> =>
  sequelize.query(`
    SELECT
      ${COMMON_USER_FIELDS}, /* just string like "User"."bla_bla_field" AS "any_bla_bla_field"*/
      ${BUSINESS_FIELDS},
      ${BUSINESS_HOURS_FIELDS},
      ${KITCHEN_HOURS_FIELDS},
      ${ADDRESS_JSON},
      ${params && params.showService ? `${COMMON_USER_SERVICE_FIELDS},` : ''}
      "reviews",
    -- Menu tags
      "mTags"."id" AS "menuTags.id",
      "mTags"."name" AS "menuTags.name",
    -- Business features
      "businessFeatures"."id" AS "businessFeatures.id",
      "businessFeatures"."name" AS "businessFeatures.name",
    -- Business cuisine
      "cuisine"."id" AS "cuisines.id",
      "cuisine"."name" AS "cuisines.name",
      -- Business subcategories
      "subcategories"."id" AS "subcategories.id",
      "subcategories"."name" AS "subcategories.name",
      "subcategories"."allowedCategories" AS "subcategories.allowedCategories",
      -- Business photo
      "businessPhoto"."id" AS "businessPhotos.id",
      "businessPhoto"."photoUrl" AS "businessPhotos.url",
      "businessPhoto"."index" AS "businessPhotos.index",
    -- Business PDF menu
      "businessPdfMenu"."id" AS "businessPdfMenus.id",
      "businessPdfMenu"."pdfMenuUrl" AS "businessPdfMenus.url",
    -- Email subscriptions
      "emailSubscription"."listId" AS "emailSubscriptions.listId"
    FROM "User" AS "user"
    LEFT JOIN "Business" AS "business" ON "business"."id" = "user"."internalId"
    LEFT JOIN "BusinessHours" AS "businessHours" ON "businessHours"."businessId" = "user"."internalId"
    LEFT JOIN "KitchenHours" AS "kitchenHours" ON "kitchenHours"."businessId" = "user"."internalId"
    LEFT JOIN "EmailSubscription" AS "emailSubscription" ON "emailSubscription"."userId" = "user"."id"
    LEFT JOIN "BusinessPhoto" AS "businessPhoto" ON "businessPhoto"."businessId" = "user"."internalId"
    LEFT JOIN "BusinessPdfMenu" AS "businessPdfMenu" ON "businessPdfMenu"."businessId" = "user"."internalId"
    LEFT JOIN LATERAL (
      SELECT json_agg(json_build_object('id', "userReviews"."id", 'userId', "userReviews"."foodEnthusiastId",
        'comment', "userReviews"."comment", 'businessComment', "userReviews"."businessComment", 'likes', "Likes")) AS "reviews"
      FROM "UserReviews" "userReviews"
        LEFT JOIN LATERAL (
          SELECT json_agg("userReviewsLikes"."userId") AS "Likes"
          FROM "UserReviewsLikes" "userReviewsLikes"
          WHERE  "userReviewsLikes"."reviewId" = "userReviews"."id"
          ) "userReviewsLikes" ON true
      WHERE  "userReviews"."businessId" = "user"."internalId"
      ) "userReviews" ON true
    LEFT JOIN (
      "PickedBusinessTags" AS "pTags"
      JOIN "MenuTags" AS "mTags"
      ON "pTags"."tagId" = "mTags"."id"
    ) ON "user"."internalId" = "pTags"."businessId"
    LEFT JOIN (
      "PickedBusinessFeatures" AS "pFeatures"
      JOIN "BusinessFeatures" AS "businessFeatures"
      ON "pFeatures"."featureId" = "businessFeatures"."id"
    ) ON "user"."internalId" = "pFeatures"."businessId"
    LEFT JOIN (
      "PickedBusinessCuisine" AS "pCuisine"
      JOIN "Cuisine" AS "cuisine"
      ON "pCuisine"."cuisineId" = "cuisine"."id"
    ) ON "user"."internalId" = "pCuisine"."businessId"
    LEFT JOIN (
      "BusinessPickedSubcategories" AS "pSubcategories"
      JOIN "Subcategories" AS "subcategories"
      ON "pSubcategories"."subcategoryId" = "subcategories"."id"
    ) ON "user"."internalId" = "pSubcategories"."businessId"
    LEFT JOIN "Address" AS "address" ON "address"."id" = "business"."address"
    WHERE "user"."id" = ${id} and "user"."type" = 'business'
    ORDER BY "businessHours.from" ASC, "kitchenHours.from" ASC;
  `, {
    type: sequelize.QueryTypes.SELECT,
  }).then(makeNested.bind(null, [
    'menuTags', 'businessHours', 'kitchenHours', 'cuisines', 'businessFeatures', 'subcategories', 'businessPhotos',
    'businessPdfMenus', 'emailSubscriptions',
  ], [
    'menuTags.id', 'businessHours.from', 'kitchenHours.from', 'cuisines.id', 'businessFeatures.id', 'subcategories.id',
    'businessPhotos.id', 'businessPdfMenus.id', 'emailSubscriptions.listId',
  ]))
```

__Dialect:__ postgres
__Database version:__ postgres 9.6
__Sequelize version:__ ^4.2.1

Maybe somebody know whats happening...

Thank you all in advantage

**Comment by sushantdhiman** [comment]
Try latest Sequelize
