### ISSUE TITLE
sequelize is selecting columns not specified in the model

### ISSUE THREAD

**Issue by aprilmintacpineda** [sequelize/sequelize#9021]
#### My model

```js
import Sequelize from 'sequelize';

export default (sequelize, DataTypes) => {
  let conversation = sequelize.define('Conversation', {
    conversation_id: {
      allowNull: false,
      autoIncrement: false,
      primaryKey: true,
      type: Sequelize.BIGINT(11)
    },
    recipient_user_id: {
      allowNull: false,
      type: Sequelize.BIGINT(11)
    },
    sender_user_id: {
      allowNull: false,
      type: Sequelize.BIGINT(11)
    },
    created_at: {
      allowNull: false,
      type: Sequelize.BIGINT(11),
    },
    updated_at: {
      allowNull: false,
      type: Sequelize.BIGINT(11)
    }
  }, {
    underscored: true,
    timestamps: false,
    tableName: 'conversation'
  });

  conversation.associate = models => {
    conversation.hasMany(models.Chat, {
      foreignKey: 'conversation_id',
      targetKey: 'conversation_id'
    });

    conversation.hasOne(models.User, {
      as: 'recipient',
      foreignKey: 'user_id',
      targetKey: 'recipient_user_id'
    });

    conversation.hasOne(models.User, {
      as: 'sender',
      foreignKey: 'user_id',
      targetKey: 'sender_user_id'
    });
  };

  return conversation;
};
```

#### select

```js
import { Op } from 'sequelize';

models.Conversation.findOne({
  where: {
    [ Op.or ]: [
      {
        recipient_user_id: request.signedinUser.id,
        sender_user_id: request.body.user_id
      },
      {
        sender_user_id: request.signedinUser.id,
        recipient_user_id: request.body.user_id
      }
    ]
  }
})
.then(conversation => {
  console.log(conversation);
});
```

## What do you expect to happen?

it should not select `user_id` since it was not specified in the model.

```sql
SELECT `conversation_id`, `recipient_user_id`, `sender_user_id`, `created_at`, `updated_at` FROM `conversation` AS `Conversation` WHERE ((`Conversation`.`recipient_user_id` = 64917217973 AND `Conversation`.`sender_user_id` = 40719802700) OR (`Conversation`.`sender_user_id` = 64917217973 AND `Conversation`.`recipient_user_id` = 40719802700)) LIMIT 1
```

## What is actually happening?

```sql
SELECT `conversation_id`, `recipient_user_id`, `sender_user_id`, `created_at`, `updated_at`, `user_id` FROM `conversation` AS `Conversation` WHERE ((`Conversation`.`recipient_user_id` = 64917217973 AND `Conversation`.`sender_user_id` = 40719802700) OR (`Conversation`.`sender_user_id` = 64917217973 AND `Conversation`.`recipient_user_id` = 40719802700)) LIMIT 1
```

__Dialect:__ mysql
__Dialect version:__ I am not sure what this is asking...
__Database version:__ mysql  Ver 14.14 Distrib 5.7.20, for macos10.12 (x86_64) using  EditLine wrapper
__Sequelize version:__ `"sequelize": "^4.31.2", "sequelize-cli": "^3.2.0"`
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

Is there any other files that sequelize relies on when selecting columns on a table? or is there any reason for sequelize to select a column that was not specified in the model?

**Comment by sushantdhiman** [comment]
Please read the documentation, http://docs.sequelizejs.com/manual/tutorial/associations.html

When you create an association Sequelize create `foreignKey` attribute in model if one does not exists. `user_id` was injected to Model because you specified it as `foreignKey`

**Comment by aprilmintacpineda** [comment]
@sushantdhiman I can't find the part of the documentation that talked about the `foreignKey` being injected to `select`, and also, is it really necessary to inject that? surely we can't expect the `foreignKey` and `targetKey` to be always the same right?

I switched my model like so:

```js
import Sequelize from 'sequelize';

export default (sequelize, DataTypes) => {
  let conversation = sequelize.define('Conversation', {
    conversation_id: {
      allowNull: false,
      autoIncrement: false,
      primaryKey: true,
      type: Sequelize.BIGINT(11)
    },
    recipient_user_id: {
      allowNull: false,
      type: Sequelize.BIGINT(11)
    },
    sender_user_id: {
      allowNull: false,
      type: Sequelize.BIGINT(11)
    },
    created_at: {
      allowNull: false,
      type: Sequelize.BIGINT(11),
    },
    updated_at: {
      allowNull: false,
      type: Sequelize.BIGINT(11)
    }
  }, {
    underscored: true,
    timestamps: false,
    tableName: 'conversation'
  });

  conversation.associate = models => {
    conversation.hasMany(models.Chat, {
      foreignKey: 'conversation_id',
      targetKey: 'conversation_id'
    });

    conversation.belongsTo(models.User, {
      as: 'recipient',
      foreignKey: 'recipient_user_id',
      targetKey: 'user_id'
    });

    conversation.belongsTo(models.User, {
      as: 'sender',
      foreignKey: 'sender_user_id',
      targetKey: 'user_id'
    });
  };

  return conversation;
};
```

now it uses `belongsTo` and the `user_id` is on the `targetKey` since as I understood it, `foreignKey` refers to the key in the source model that will be used to refer to a key on the associated table and `targetKey` is the key on the associated model that the `foreignKey` refers to. I'm pretty sure that my code makes sense based on what I understood. I'm open for corrections though.

The following query was generated:

```sql
SELECT `conversation_id`, `recipient_user_id`, `sender_user_id`, `created_at`, `updated_at`, `user_id` FROM `conversation` AS `Conversation` WHERE ((`Conversation`.`recipient_user_id` = 64917217973 AND `Conversation`.`sender_user_id` = 70532988210) OR (`Conversation`.`sender_user_id` = 64917217973 AND `Conversation`.`recipient_user_id` = 70532988210)) LIMIT 1;
```

it still injected `user_id` to the `field_list`.

**Comment by aprilmintacpineda** [comment]
@sushantdhiman I transformed my model like so:

```js
import Sequelize from 'sequelize';

export default (sequelize, DataTypes) => {
  let conversation = sequelize.define('Conversation', {
    conversation_id: {
      allowNull: false,
      autoIncrement: false,
      primaryKey: true,
      type: Sequelize.BIGINT(11)
    },
    recipient_user_id: {
      allowNull: false,
      type: Sequelize.BIGINT(11)
    },
    sender_user_id: {
      allowNull: false,
      type: Sequelize.BIGINT(11)
    },
    created_at: {
      allowNull: false,
      type: Sequelize.BIGINT(11),
    },
    updated_at: {
      allowNull: false,
      type: Sequelize.BIGINT(11)
    }
  }, {
    underscored: true,
    timestamps: false,
    tableName: 'conversation'
  });

  conversation.associate = models => {
    conversation.hasMany(models.Chat, {
      foreignKey: 'conversation_id',
      targetKey: 'conversation_id'
    });
  };

  return conversation;
};
```

did the same query

```js
import models from '../../../models';
import { Op } from 'sequelize';

models.Conversation.findOne({
  where: {
    [ Op.or ]: [
      {
        recipient_user_id: request.signedinUser.id,
        sender_user_id: request.body.user_id
      },
      {
        sender_user_id: request.signedinUser.id,
        recipient_user_id: request.body.user_id
      }
    ]
  }
})
.then(conversation => {
  console.log(conversation);
})
```

the same query was generated

```sql
SELECT `conversation_id`, `recipient_user_id`, `sender_user_id`, `created_at`, `updated_at`, `user_id` FROM `conversation` AS `Conversation` WHERE ((`Conversation`.`recipient_user_id` = 64917217973 AND `Conversation`.`sender_user_id` = 40719802700) OR (`Conversation`.`sender_user_id` = 64917217973 AND `Conversation`.`recipient_user_id` = 40719802700)) LIMIT 1
```

and the same error occurred

```
Unhandled rejection SequelizeDatabaseError: Unknown column 'user_id' in 'field list'
    at Query.formatError (/Users/april/Documents/projects/mobile-app/servcon-backend/node_modules/sequelize/lib/dialects/mysql/query.js:228:16)
    at Query.connection.query [as onResult] (/Users/april/Documents/projects/mobile-app/servcon-backend/node_modules/sequelize/lib/dialects/mysql/query.js:55:23)
    at Query.Command.execute (/Users/april/Documents/projects/mobile-app/servcon-backend/node_modules/mysql2/lib/commands/command.js:30:12)
    at Connection.handlePacket (/Users/april/Documents/projects/mobile-app/servcon-backend/node_modules/mysql2/lib/connection.js:515:28)
    at PacketParser.onPacket (/Users/april/Documents/projects/mobile-app/servcon-backend/node_modules/mysql2/lib/connection.js:94:16)
    at PacketParser.executeStart (/Users/april/Documents/projects/mobile-app/servcon-backend/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.<anonymous> (/Users/april/Documents/projects/mobile-app/servcon-backend/node_modules/mysql2/lib/connection.js:102:29)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

**Comment by sushantdhiman** [comment]
Are you sure there is no other relationship involved? Sequelize doesn't randomly inject columns, some association is specifying `user_id` on converstation model

**Comment by aprilmintacpineda** [comment]
@sushantdhiman 

the `Conversation` model is associated with `Chat` model, here's what it looks like:

```js
import Sequelize from 'sequelize';

export default (sequelize, DataTypes) => {
  let chat = sequelize.define('Chat', {
    chat_id: {
      allowNull: false,
      autoIncrement: false,
      primaryKey: true,
      type: Sequelize.BIGINT(11)
    },
    conversation_id: {
      allowNull: false,
      type: Sequelize.BIGINT(11)
    },
    sender_user_id: {
      allowNull: false,
      type: Sequelize.BIGINT(11)
    },
    message: {
      allowNull: false,
      type: Sequelize.STRING(5000)
    },
    seen: {
      allowNull: false,
      type: Sequelize.BOOLEAN,
      defaultValue: false
    },
    seen_at: {
      allowNull: true,
      type: Sequelize.DATE
    },
    created_at: {
      allowNull: false,
      type: Sequelize.BIGINT(11),
    },
    updated_at: {
      allowNull: false,
      type: Sequelize.BIGINT(11)
    }
  }, {
    underscored: true,
    timestamps: false,
    tableName: 'chat'
  });

  chat.associate = models => {
    chat.belongsTo(models.Conversation, {
      foreignKey: 'conversation_id',
      target_id: 'conversation_id'
    });

    chat.belongsTo(models.User, {
      foreignKey: 'user_id',
      target_id: 'user_id'
    });
  };

  return chat;
};
```

I assume that other model's association with other model does not affect the model I am currently dealing with.

All associations defined via the model file, right? so there would be no other associations aside from what I wrote on the model.
----

I got it, the reason was because of these likes on my user model:

```js
user.hasMany(models.Conversation, {
  as: 'received',
  foreignKey: 'user_id',
  targetKey: 'recipient_user_id'
});

user.hasMany(models.Conversation, {
  as: 'sent',
  foreignKey: 'user_id',
  targetKey: 'sender_user_id'
});
```

I changed it to:

```js
user.hasMany(models.Conversation, {
  as: 'received',
  foreignKey: 'recipient_user_id',
  targetKey: 'user_id'
});

user.hasMany(models.Conversation, {
  as: 'sent',
  foreignKey: 'sender_user_id',
  targetKey: 'user_id'
});
```

I don't know why I wrote it that way, also I didn't know that sequelize actually do check the relationships of other models associated with a model. I think it's worth mentioning these information in the docs, right? or is it and I just didn't come across it?

**Comment by sushantdhiman** [comment]
There just one model representation in application, so sequelize execute all association and finally comes up with model with all association attributes injected.

Just like your table, there is only one model and it has to take care of all foreignKeys referencing to it
