### ISSUE TITLE
spread does not work with create

### ISSUE THREAD

**Issue by aprilmintacpineda** [sequelize/sequelize#9043]
## What are you doing?

```js
models.Chat.create({
  chat_id: generateUID(),
  conversation_id: request.body.conversation_id,
  sender_user_id: request.signedinUser.id,
  message: request.body.message,
  created_at: now,
  updated_at: now
})
.spread(newMessage => {
  console.log(newMessage);
});
```

## What do you expect to happen?

newMessage will be the record that was created.

## What is actually happening?

```
Unhandled rejection TypeError: expecting an array or an iterable object but got [object Null]
    at apiRejection (/Users/april/Documents/projects/mobile-app/servcon-backend/node_modules/bluebird/js/release/promise.js:10:27)
    at PromiseArray.init [as _init] (/Users/april/Documents/projects/mobile-app/servcon-backend/node_modules/bluebird/js/release/promise_array.js:63:19)
    at Promise._settlePromise (/Users/april/Documents/projects/mobile-app/servcon-backend/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/Users/april/Documents/projects/mobile-app/servcon-backend/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/april/Documents/projects/mobile-app/servcon-backend/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/april/Documents/projects/mobile-app/servcon-backend/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/april/Documents/projects/mobile-app/servcon-backend/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/april/Documents/projects/mobile-app/servcon-backend/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

_Output_

```sql
Executing (default): INSERT INTO `chat` (`chat_id`,`conversation_id`,`sender_user_id`,`message`,`seen`,`created_at`,`updated_at`) VALUES (56387204137,19354653227,11737847872,'bbb',false,1518495850177,1518495850177);
```

This however works:

```js
models.Chat.create({
  chat_id: generateUID(),
  conversation_id: request.body.conversation_id,
  sender_user_id: request.signedinUser.id,
  message: request.body.message,
  created_at: now,
  updated_at: now
})
.then(newMessage => {
  console.log(newMessage);
});
```

__Dialect:__ mysq
__Dialect version:__ I don't know what this is asking for..
__Database version:__ mysql Ver 14.14 Distrib 5.7.20, for macos10.12 (x86_64) using EditLine wrapper
__Sequelize version:__ ^4.31.2
__Tested with latest release:__ No (If yes, specify that version)

**Comment by sushantdhiman** [comment]
Please read more about `spread` first :) spread expand array, how you suppose to expand instance which is an object

**Comment by aprilmintacpineda** [comment]
Aaa I see, so that create actually returns the object, sorry my bad.
