### ISSUE TITLE
TypeError: contract.setOrganizations is not a function

### ISSUE THREAD

**Issue by wl1711** [sequelize/sequelize#9045]
## What are you doing?

```js

Contract model:
module.exports = (sequelize, DataTypes) => {
    const Contract = sequelize.define('Contract', {
        id: {
            type: DataTypes.INTEGER,
            field: 'id',
            allowNull: false,
            primaryKey: true,
            autoIncrement: true
        },
        contractNumber: {
            type: DataTypes.STRING(255),
            field: 'contractNumber',
            allowNull: false
        },
        contractTitle: {
            type: DataTypes.STRING(255),
            field: 'contractTitle',
            allowNull: false
        },
        ......
    }, {
        schema: 'public',
        tableName: 'Contract',
        timestamps: true
    });

    Contract.associate = (models) => {
        .....
        Contract.hasMany(models.ContractOrganization, {
            foreignKey: 'contractId',
        });
        .....
    };
    return Contract;
};

ContractOrganization Model:
module.exports = (sequelize, DataTypes) => {
    const ContractOrganization = sequelize.define('ContractOrganization', {
        contractId: {
            type: DataTypes.INTEGER,
            field: 'contractId',
            allowNull: false,
            primaryKey: true,
            references: {
                model: 'Contract',
                key: 'id'
            },
            onUpdate: 'NO ACTION',
            onDelete: 'NO ACTION'
        },
        organizationId: {
            type: DataTypes.INTEGER,
            field: 'organizationId',
            allowNull: false,
            primaryKey: true,
            references: {
                model: 'Organization',
                key: 'id'
            },
            onUpdate: 'NO ACTION',
            onDelete: 'NO ACTION'
        }
    }, {
        schema: 'public',
        tableName: 'ContractOrganization',
        timestamps: false
    });

    ContractOrganization.associate = (models) => {

        ContractOrganization.belongsTo(models.Contract, {
            foreignKey: 'contractId',
        });

        ContractOrganization.belongsTo(models.Organization, {
            foreignKey: 'organizationId',
        });

    };
    return ContractOrganization;
};

contracts.js -- controller
        return sequelize.transaction(function (t) {
            var promises = [];

            var createContractPromise = contract
                .create({
                    contractNumber: contractData.contractNumber,
                    contractTitle: contractData.contractTitle,
					....
                }, {
                    transaction: t
                });

                promises.push(createContractPromise);

                return Promise.all(promises).then((contract) => {
                    var arrContractOrgPromises = [];

                    var contractOrgPromise = 
                        organization.findById(organizationId)
                        .then((organizations) => {
                            **contract.setOrganizations(**organizations, {
                                transaction: t
                            });
                        });

                        arrContractOrgPromises.push(contractOrgPromise);
                        return Promise.all(arrContractOrgPromises);
                })
```

## What do you expect to happen?
I expected data will be inserted into ContractOrganization table

## What is actually happening?
Transaction was rolled back. I am able to insert data into ContractOrganiztion table without transaction using same contract.setOrganizations..., can't figure out why it complains when makes it a transaction.

_Output, either JSON or SQL_
TypeError: contract.setOrganizations is not a function
    at organization.findById.then (C:\Supplier-Matrix-API\server\controllers\contracts.js:109:38)
    at tryCatcher (C:\Supplier-Matrix-API\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Supplier-Matrix-API\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Supplier-Matrix-API\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Supplier-Matrix-API\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Supplier-Matrix-API\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Supplier-Matrix-API\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Supplier-Matrix-API\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Supplier-Matrix-API\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
Executing (04476b7e-70be-4f64-9c2a-842ef0c2089d): ROLLBACK;

__Dialect:__ postgres
__Dialect version:__ not sure
__Database version:__ 9.4
__Sequelize version:__ 4.33.4
__Tested with latest release:__ yes, with sequelize 4.33.4

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Your model name is `ContractOrganization` so setter method will be `setContractOrganizations`

**Comment by wl1711** [comment]
I have two models, Contract and ContractOrganization. Even I try use setContractOrganizations, I got the same error.
TypeError: contract.setContractOrganizations is not a function
    at organization.findById.then (C:\Supplier-Matrix-API\server\controllers\contracts.js:110:38)
    at tryCatcher (C:\Supplier-Matrix-API\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Supplier-Matrix-API\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Supplier-Matrix-API\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Supplier-Matrix-API\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Supplier-Matrix-API\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Supplier-Matrix-API\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Supplier-Matrix-API\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Supplier-Matrix-API\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
Executing (964bc5f3-9f25-4f2a-8d2f-d3d18eb21dd8): ROLLBACK;

**Comment by wl1711** [comment]
Check out the code below, it works for me. Can you reopen the issue?   
     return contract
            .create({
                contractNumber: contractData.contractNumber,
                .....
            })
            .then((contract) => {
                organization.findAll({where: {id: organizationId}})
                    .then((organizations) =>{
                        for(var i=0; i<organizations.length; i++){
                            **contract.setOrganizations([organizations[i]]);**
                        }
                    })

**Comment by sushantdhiman** [comment]
Can you show output of `console.dir` for both models after association?

**Comment by wl1711** [comment]
I figured out why, contract is an Array  before I call contract.setOrganizations([organizations[i]]);
Thanks.
