### ISSUE TITLE
Alter queries generated by sequelize.sync with alter: true report syntax problems when columns use an explicit defaultValue

### ISSUE THREAD

**Issue by jsanta** [sequelize/sequelize#9058]
## What are you doing?
Syncing using alter: true for a table model using  a column with an explicit definiton for the defaultValue.

```js
// Model
const User = sequelize.define('User',
    {
        id: {
            type: Sequelize.INTEGER,
            autoIncrement: true,
            primaryKey: true,
            allowNull: false
        },
        email: {
            type: Sequelize.STRING,
            allowNull: false,
            unique: 'usr_email',
            set(val) {
                const email = (!val) ? this.getDataValue('username') : val;
                this.setDataValue('email', email.toLowerCase());
            },
            validate: {
                isEmail: true
            }
        },
        isValidated: {
            type: Sequelize.BOOLEAN,
            defaultValue: false
        }
    },
    {
        timestamps: true,
        freezeTableName:true,
        paranoid: true
    }
);

exports.User = User;
```

```
// DB Sync
var sequelize = db.sequelize;
    sequelize.sync({
        force: false,
        logging: dbLog,
        alter: true
    }).then(function () { /* ... */ });
```

## What do you expect to happen?
Alter queries executed without any syntax error

## What is actually happening?
Alter queries built with an invalid syntax.

_Output messages_
```
{
  SequelizeDatabaseError: Incorrect syntax near the keyword 'DEFAULT'. [...] ,
  sql: 'ALTER TABLE [User] ALTER COLUMN [isValidated] BIT DEFAULT 0;'
}
```

## Workaround
Modify the model definition to use a function that returns the default value the column instead of specifying the value itself:
```js
// Model
const User = sequelize.define('User',
    {
        id: {
            type: Sequelize.INTEGER,
            autoIncrement: true,
            primaryKey: true,
            allowNull: false
        },
        email: {
            type: Sequelize.STRING,
            allowNull: false,
            unique: 'usr_email',
            set(val) {
                const email = (!val) ? this.getDataValue('username') : val;
                this.setDataValue('email', email.toLowerCase());
            },
            validate: {
                isEmail: true
            }
        },
        isValidated: {
            type: Sequelize.BOOLEAN,
            defaultValue: () => false
        }
    },
    {
        timestamps: true,
        freezeTableName:true,
        paranoid: true
    }
);

exports.User = User;
```

__Dialect:__ mssql
__Dialect version:__ 4.29.2
__Database version:__ MS Sql 2017 running on Ubuntu Linux
__Sequelize version:__ 4.29.2
__Tested with latest release:__ No

**Comment by sushantdhiman** [comment]
Can you try with latest version

**Comment by sushantdhiman** [comment]
>    * @param {any}  [attributes.column.defaultValue=null] A literal default value, a JavaScript function, or an SQL function (see `sequelize.fn`)

http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-init

**Comment by luis-otvio** [comment]
Unfortunately I'm facing the same problem currently. SQL Server 2019. Apparently the syntax for setting a DEFAULT value to an existing column is different in SQL SERVER, causing this exception, exactly as explained by user @jsanta  :(
Any solution? I had to disable sync() to be able to work with my API.

**Comment by pn-andrej-zecevic** [comment]
I am still having this issue in 6.37.3 over 4 years later. The workaround of using a function instead of a literal value when using `changeColumn` worked for me. When using `addColumn` it worked better with a literal value.

**Comment by kieran-reportabl** [comment]
Still an issue. Cannot migrate modified models with a default value column. 

sequelize: 6.37.3
tedious: 18.2.0

```bash
...
Executing (bdb79bb2ea41f506432f): ALTER TABLE [Users] ALTER COLUMN [status] NVARCHAR(10) NOT NULL DEFAULT N'ACTIVE';
Executing (bdb79bb2ea41f506432f): ROLLBACK TRANSACTION;

ERROR: SequelizeDatabaseError: Incorrect syntax near the keyword 'DEFAULT'.
    at Query.run (W:\Projects\Reportabl\reportabl-backend\node_modules\sequelize\lib\dialects\mssql\query.js:107:25)
    at W:\Projects\Reportabl\reportabl-backend\node_modules\sequelize\lib\sequelize.js:315:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
