### ISSUE TITLE
Cannot read property 'toUpperCase' of undefined in association using 'as' as object

### ISSUE THREAD

**Issue by exos** [sequelize/sequelize#9072]
## What are you doing?

Adding associate to a model using `as` as a object _(singular, plural)_ :

```js
    ContentModel.associate = function(models) {
        UsersModel = models.users;
        CategoryModel = models.categories;

        ContentModel.belongsTo(UsersModel, {
            as: {
                singular: 'owner',
                plural: 'owners',
            },
            foreignKey: 'owner',
            targetKey: 'id',
            constraints: true,
        });
```

## What do you expect to happen?

Add association :P.

## What is actually happening?

    /src/node_modules/sequelize/lib/utils.js:98
      return s[0].toUpperCase() + s.slice(1);
                  ^
    TypeError: Cannot read property 'toUpperCase' of undefined
        at Object.uppercaseFirst (/src/node_modules/sequelize/lib/utils.js:98:15)
        at new BelongsTo (/src/node_modules/sequelize/lib/associations/belongs-to.js:68:28)
        at Function.<anonymous> (/src/node_modules/sequelize/lib/associations/mixin.js:92:25)
        at Function.ContentModel.associate (/src/src/models/contents.js:111:22)
        at Object.<anonymous> (/src/src/models/index.js:18:27)
        at Module._compile (module.js:643:30)
        at babelWatchLoader (/src/node_modules/babel-watch/runner.js:50:13)
        at Object.require.extensions.(anonymous function) [as .js] (/src/node_modules/babel-watch/runner.js:61:7)
        at Module.load (module.js:556:32)
        at tryModuleLoad (module.js:499:12)
        at Function.Module._load (module.js:491:3)
        at Module.require (module.js:587:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/src/src/services/categories.js:2:1)
        at Module._compile (module.js:643:30)
        at babelWatchLoader (/src/node_modules/babel-watch/runner.js:50:13)
        at Object.require.extensions.(anonymous function) [as .js] (/src/node_modules/babel-watch/runner.js:61:7)
        at Module.load (module.js:556:32)
        at tryModuleLoad (module.js:499:12)
        at Function.Module._load (module.js:491:3)
        at Module.require (module.js:587:17)
        at require (internal/module.js:11:18)

__Dialect:__ postgres
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ 4.32.2
__Tested with latest release:__ No

**Note**: I'm using `foreignKey` and `targetKey` to existent fields. The error is when method `associate` is called, before sync.

**Comment by sushantdhiman** [comment]
```
as: {
    singular: 'owner',
    plural: 'owners',
},
```

With `BelongsTo` there is only one row is associated, it does not support or rather need `singular / plural` alias definition

**Comment by exos** [comment]
And the issue is resolved? Really?

**Comment by sushantdhiman** [comment]
`BelongsTo` does not support singular, plural. Do you think it should?

**Comment by exos** [comment]
Show as an error or take the `as.singular`, but the error isn't descriptible
