### ISSUE TITLE
Using db:migrate results in ReferenceError: DataTypes is not defined

### ISSUE THREAD

**Issue by spyshower** [sequelize/sequelize#9137]
Hello,

I have been using sequelize with Postgres for the development of my app for a couple of months, so far no problems.

Now, I wanted to transfer a database from a server (manually) and all I want is basically to create a new table but I am having problems initializing and configuring the primary ID of the table using pgAdmin 4. I guess there is a simple way to do that which I am not aware of.

Meanwhile, I tried to use `sequelize model:create` and then `sequelize db:migrate`  in order to create the table automatically but I get the following error:

```
== 20180204185332-create-date: migrating =======
ReferenceError: DataTypes is not defined
    at Object.up (/Users/Creece/Dropbox/TwoNight/server/postgres/migrations/20180204185332-create-date.js:23:15)
    at Migration._callee$ (/usr/local/lib/node_modules/sequelize-cli/node_modules/umzug/lib/migration.js:178:35)
    at tryCatch (/usr/local/lib/node_modules/sequelize-cli/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/sequelize-cli/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/sequelize-cli/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/usr/local/lib/node_modules/sequelize-cli/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/lib/node_modules/sequelize-cli/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

I have no idea what to do about it, since it worked fine in the past. Any help?

**Comment by sushantdhiman** [comment]
>  DataTypes is not defined

a typo perhaps

**Comment by sushantdhiman** [comment]
Let me know if this was not a typo, in that case I will need to see the migration file

**Comment by spyshower** [comment]
@sushantdhiman It's not a typo I just pasted the command line output.

The migration file is this:

```
'use strict';
module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.createTable('DateItems', {
      id: {
        allowNull: false,
        autoIncrement: true,
        primaryKey: true,
        type: Sequelize.INTEGER
      },
      status: {
        type: Sequelize.STRING
      },
      createdAt: {
        allowNull: false,
        type: Sequelize.DATE
      },
      updatedAt: {
        allowNull: false,
        type: Sequelize.DATE
      }
    });
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.dropTable('DateItems');
  }
};
```

**Comment by sushantdhiman** [comment]
I dont think its the same file, error clearly states undefined object was on line 23 in `up` method. But in this code up method ends before 23rd line.

In any case `undefined` variable is userland problem not an issue with Sequelize itself
