### ISSUE TITLE
unexpected error when using raw:false with attributes:[]

### ISSUE THREAD

**Issue by FranckFreiburger** [sequelize/sequelize#9141]
## What are you doing?

Simple structure: a Shop has many Products, and a Manager manage many Shops.

```js

const Product = sequelize.define('product', {
    name: Sequelize.STRING,
});


const Shop = sequelize.define('shop', {
    name: Sequelize.STRING,
});

Shop.hasMany(Product);
Product.belongsTo(Shop);


const Manager = sequelize.define('manager', {
    name: Sequelize.STRING,
});

Manager.hasMany(Shop);
Shop.belongsTo(Manager);



await sequelize.drop({ force: true });
await sequelize.sync();


// create some data
await Manager.create({
    name: 'big boss',
    shops: [
        {
            name: 'shop1',
            products: [
                {
                    name: 'prouct1'
                }
            ]
        }
    ]
},{
    include: [{ all: true, nested: true }]
});

// here we just need the list of products and the manager's name who it belongs to,
// and ignore other attributes.
console.log('test:', await Product.findAll({
    attributes:[],
    include: [{
        model:Shop,
        attributes:[],
        include:[{
            model:Manager,
            attributes:['name']
        }]
    }],
    raw: true
}));

// ok: [ { 'shop.manager.id': 1, 'shop.manager.name': 'big boss' } ]


// now, same without raw
console.log('test:', await Product.findAll({
    attributes:[],
    include: [{
        model:Shop,
        attributes:[],
        include:[{
            model:Manager,
            attributes:['name']
        }]
    }],
}));

// nok: TypeError: Cannot set property 'manager' of undefined
```

## What do you expect to happen?
I expect to retrieve the same data regardless the `raw` attribute (obviously, not the same object structure)

## What is actually happening?
```
TypeError: Cannot set property 'manager' of undefined
    at Function._groupJoinData (...\node_modules\sequelize\lib\dialects\abstract\query.js:617:52)
    at Query.handleSelectQuery (...\node_modules\sequelize\lib\dialects\abstract\query.js:284:31)
    at query.catch.then.then.queryResult (...\node_modules\sequelize\lib\dialects\postgres\query.js:205:23)
    at tryCatcher (...\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (...\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (...\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (...\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (...\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (...\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (...\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (...\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
```

__Dialect:__ postgres
__Dialect version:__ ???
__Database version:__ psql (9.6.1)
__Sequelize version:__ 4.35.2
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by v3zir** [comment]
I get the same error in my project. It's a bug and it's been talked about solved, but it's still going on.

**Comment by sushantdhiman** [comment]
Fixed by https://github.com/sequelize/sequelize/commit/8e2517fb246a8306221b052d8aa4c20f741c3fec

**Comment by sushantdhiman** [comment]
I am only working with @FranckFreiburger case which does not throw any error after that commit, I have no idea about your case @v3zir 

Although there is no error still it wont populate deep nested includes if parent include is setting `attributes: []`

**Comment by hsallabas** [comment]
I have using Sequelize last version. When I am using findAll and include I get error “cannot read property ‘table_name’ of undefined” I try solve the problem a long time but I can’t. Please help me. Good day Thanks.




``router.get('/preRegClasses/test5', function (req, res) {
    console.log(db.pRegs)
    db.schools.findAll({
        attributes: ['id'],
        include: [{
            model: db.years,
            attributes: ['id'],
            include: [{
                model: db.pClasses,
                attributes: [],
                include: [{
                    model: db.pRegs,
                    attributes: ['reserve_order'],
                    include: [{
                        model: db.pStudents,
                        attributes: ['name', 'surname', 'id_number', 'call_priority'],
                        include: [{
                            model: db.pParents,
                            attributes: ['name', 'surname', 'parent_type'],
                        },
                        {
                            model: db.pSiblings,
                            attributes: [],
                        }]
                    }]
                }]
            }]
        }]
    }).then(function (result) {
        res.send(result);
        console.log(result);
    }).catch(function (error) {
        res.send(error)
        console.log(error);
    });
});



`TypeError: Cannot read property 'pRegs' of undefined
    at Function._groupJoinData (C:\Users\ASUS\Desktop\testproje\node_modules\sequelize\lib\dialects\abstract\query.js:598:31)
    at Query.handleSelectQuery (C:\Users\ASUS\Desktop\testproje\node_modules\sequelize\lib\dialects\abstract\query.js:284:31)
    at query.catch.then.then.queryResult (C:\Users\ASUS\Desktop\testproje\node_modules\sequelize\lib\dialects\postgres\query.js:205:23)
    at tryCatcher (C:\Users\ASUS\Desktop\testproje\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\ASUS\Desktop\testproje\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\ASUS\Desktop\testproje\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\ASUS\Desktop\testproje\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\ASUS\Desktop\testproje\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\ASUS\Desktop\testproje\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\ASUS\Desktop\testproje\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\ASUS\Desktop\testproje\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)`

**Comment by abdullah-abunada** [comment]
I have the same error!! are there any solutions??

**Comment by hsallabas** [comment]
Yes I solved this problem. you should add 'id' in all attributes tags, they should not be null.

attributes: ['id']
