### ISSUE TITLE
Return array of all failed validations in ValidationError errors object

### ISSUE THREAD

**Issue by pruhstal** [sequelize/sequelize#9249]
## What are you doing?

```js

module.exports = (Sequelize, DataTypes) => {
  const User = Sequelize.define(
    'user',
    {
      email: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: {
          args: true,
          msg: 'That email is not available.'
        },
        validate: {
          isEmail: {
            args: true,
            msg: 'Please enter a valid email.'
          }
        }
      },
      username: {
        type: DataTypes.STRING,
        allowNull: false,
        notEmpty: true,
        unique: {
          args: true,
          msg: 'That username is not available.'
        },
        validate: {
          min: {
            args: USER_USERNAME_MIN_LENGTH,
            msg: 'Please choose a longer username.'
          },
          max: {
            args: USER_USERNAME_MAX_LENGTH,
            msg: 'Please choose a shorter username.'
          },
          is: {
            args: /^[0-9a-zA-Z](\/?[a-zA-Z0-9-_])*\/?$/i,
            msg: 'Please enter a valid username.'
          }
        }
      }
    },
    {
      underscored: true,
    }
  );

  return User;
};

    try {
      const user = await User.findById(req.user.id);
      if (user) {
        const updatedUser = await user.update({
          username: username || req.user.username,
          email: email || req.user.email
        });

        res.status(200).end();
      }
    } catch (err) {
      console.log(err);
      return res.status(500).send(getMappedErrors(err));
    }
```

## What do you expect to happen?
In this case, since the username and email that I'm passing in are being used by another user in my database, I expect the validator to return an array with both validation errors in the array.

## What is actually happening?
The validation errors object is only returning one error at a time (instead of the validation failure for both the username and email).

_Output, either JSON or SQL_
```
{ SequelizeUniqueConstraintError: That username is not available.
    at Query.formatError (/site/node_modules/sequelize/lib/dialects/postgres/query.js:325:18)
    at query.catch.err (/site/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)
    at tryCatcher (/site/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/site/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/site/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/site/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/site/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/site/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/site/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/site/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
    at process.topLevelDomainCallback (domain.js:101:23)
  name: 'SequelizeUniqueConstraintError',
  errors:
   [ ValidationErrorItem {
       message: 'That username is not available.',
       type: 'unique violation',
       path: 'username',
       value: 'pkr',
       origin: 'DB',
       instance: [user],
       validatorKey: 'not_unique',
       validatorName: null,
       validatorArgs: [] } ],
  fields: { username: 'pkr' },
  parent:
   { error: duplicate key value violates unique constraint "users_username_key"
    at Connection.parseE (/site/node_modules/pg/lib/connection.js:545:11)
    at Connection.parseMessage (/site/node_modules/pg/lib/connection.js:370:19)
    at Socket.<anonymous> (/site/node_modules/pg/lib/connection.js:113:22)
    at Socket.emit (events.js:127:13)
    at Socket.emit (domain.js:421:20)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:598:20)
     name: 'error',
     length: 204,
     severity: 'ERROR',
     code: '23505',
     detail: 'Key (username)=(pkr) already exists.',
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: 'public',
     table: 'users',
     column: undefined,
     dataType: undefined,
     constraint: 'users_username_key',
     file: 'nbtinsert.c',
     line: '434',
     routine: '_bt_check_unique',
     sql: 'UPDATE "users" SET "username"=\'pkr\',"email"=\'me@aol.com\',"updated_at"=\'2018-03-28 19:26:27.341 +00:00\' WHERE "id" = 2' },
```

__Dialect:__ postgres
__Dialect version:__ 10.3
__Database version:__ 10.3
__Sequelize version:__ 4.37.2
__Tested with latest release:__ No

**Comment by sushantdhiman** [comment]
There are two type of validations in Sequelize

1. Engine level validations, `allowNull: true` or `unique: true`, these validation only occur when we actually insert / update / delete data from store.
2. Model level validations, `isEmail / isEmpty ...` these are under sequelize control and executed before any actual database operation.

Both (1) & (2) can't be covered using what you proposed here. But I am ok with returning all errors from (2) at same time, using `ValidationErrorItem` and `errors` sub array

**Comment by pruhstal** [comment]
@sushantdhiman That would be incredible. Thanks for taking a look.
