### ISSUE TITLE
Sync alter:true on error

### ISSUE THREAD

**Issue by denzw** [sequelize/sequelize#9256]
CODE:
``` javascript
const Sequelize = require('sequelize');

const sequelize = new Sequelize('example-dev', 'root', '***', {
    dialect: 'mysql', 
    host: 'localhost',
    port: '3306',
    benchmark: true, 
    pool: {
      max: 1,
    },
    define: {
      schema: 'ex', 
      schemaDelimiter: '_',
    },
    operatorsAliases: false,
  });
  const order = sequelize.define('Order', {  
    firstName: {
        type: Sequelize.STRING
      },
      lastName: {
        type: Sequelize.STRING
      }
  });

  order.sync({alter: true})
```

``` bash
PS C:\projects\nodejs\sequelize> node .\app.js
Executed (default): CREATE TABLE IF NOT EXISTS `ex_Orders` (`id` INTEGER NOT NULL auto_increment , `firstName` VARCHAR(255), `lastName` VARCHAR(255), `createdAt` DATETIME NOT NULL, `update
dAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB; Elapsed time: 1ms
Executed (default): DESCRIBE `ex.Orders`; Elapsed time: 2ms
Unhandled rejection SequelizeDatabaseError: Table 'example-dev.ex.Orders' doesn't exist
    at Query.formatError (C:\projects\nodejs\sequelize\node_modules\sequelize\lib\dialects\mysql\query.js:247:16)
    at Query.handler [as onResult] (C:\projects\nodejs\sequelize\node_modules\sequelize\lib\dialects\mysql\query.js:68:23)
    at Query.Command.execute (C:\projects\nodejs\sequelize\node_modules\mysql2\lib\commands\command.js:30:12)
    at Connection.handlePacket (C:\projects\nodejs\sequelize\node_modules\mysql2\lib\connection.js:502:28)
    at PacketParser.onPacket (C:\projects\nodejs\sequelize\node_modules\mysql2\lib\connection.js:81:16)
    at PacketParser.executeStart (C:\projects\nodejs\sequelize\node_modules\mysql2\lib\packet_parser.js:77:14)
    at Socket.<anonymous> (C:\projects\nodejs\sequelize\node_modules\mysql2\lib\connection.js:89:29)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)

Executed (default): SELECT CONSTRAINT_NAME as constraint_name,CONSTRAINT_NAME as constraintName,CONSTRAINT_SCHEMA as constraintSchema,CONSTRAINT_SCHEMA as constraintCatalog,TABLE_NAME as t
ableName,TABLE_SCHEMA as tableSchema,TABLE_SCHEMA as tableCatalog,COLUMN_NAME as columnName,REFERENCED_TABLE_SCHEMA as referencedTableSchema,REFERENCED_TABLE_SCHEMA as referencedTableCatal
og,REFERENCED_TABLE_NAME as referencedTableName,REFERENCED_COLUMN_NAME as referencedColumnName FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE where TABLE_NAME = '`ex_Orders`' AND CONSTRAINT_NAME
!='PRIMARY' AND CONSTRAINT_SCHEMA='example-dev' AND REFERENCED_TABLE_NAME IS NOT NULL; Elapsed time: 2ms

```

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
