### ISSUE TITLE
in pm2 how share mysql pool

### ISSUE THREAD

**Issue by buzai** [sequelize/sequelize#9282]
like this https://stackoverflow.com/questions/24339179/nodejs-cluster-with-mysql-connections 

i have 6 srever, in every server i use pm2 to start 8 instances. 
but every instances , i need 1000 mysql database to connect.
i set in every database pool is 50.
this will 6 * 8 * 1000 * 50 conections .
it is too many .

```
SequelizeConnectionError: connect ETIMEDOUT
    at Handshake._callback (/nas/bjproject/server_exam_new/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:95:20)
    at Handshake.Sequence.end (/nas/bjproject/server_exam_new/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Protocol.handleNetworkError (/nas/bjproject/server_exam_new/node_modules/mysql/lib/protocol/Protocol.js:363:14)
    at Connection._handleNetworkError (/nas/bjproject/server_exam_new/node_modules/mysql/lib/Connection.js:428:18)
    at Connection._handleConnectTimeout (/nas/bjproject/server_exam_new/node_modules/mysql/lib/Connection.js:424:8)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:407:8)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```

i want share mysql pool in every instances. how can i do this?

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
