### ISSUE TITLE
how generate Foreign key and see data JSON

### ISSUE THREAD

**Issue by HDCARDENAS2** [sequelize/sequelize#9321]
I have a problem, I not understand the documentation http://docs.sequelizejs.com/manual/tutorial/associations.html  for to do this....  associate a foreign key to an entity and be able to see the complete entity in the result of the query....

DB PostgreSQL: v 9.5

example 
```
{
    "total": 1,
    "limit": 1000,
    "skip": 0,
    "data": [
        {
            "core_function_id": "1",
            "description": "Ingresar solicitud",
            "core_url ": { "core_url_id": 1, "description": "data" },
            "json_logical": null,
            "json_update": null,
            "active": true,
            "created_at": "2018-04-09T20:01:34.491Z",
            "updated_at": "2018-04-09T20:01:34.491Z"
        }
    ]
}
```
code

im using feathersjs the new release

my models

core-url.model.js
```
// See http://docs.sequelizejs.com/en/latest/docs/models-definition/
// for more of what you can do here.
const Sequelize = require('sequelize');
const DataTypes = Sequelize.DataTypes;

module.exports = function (app) {
  const sequelizeClient = app.get('sequelizeClient');
  const coreUrl = sequelizeClient.define('core_url', {

    core_url_id: {
      fields: ['id'],
      type: DataTypes.INTEGER,
      primaryKey: true
    },
    description: {
      type: DataTypes.STRING,
      allowNull: false
    },
    path_url: {
      type: DataTypes.INTEGER,
      allowNull: false
    },
    active: {
      type: DataTypes.BOOLEAN,
      allowNull: true
    },
    created_at: {
      fields: ['created_at'],
      type: DataTypes.DATE,
      allowNull: true
    },
    updated_at: {
      fields: ['updated_at'],
      type: DataTypes.DATE,
      allowNull: true,
      defaultValue: Sequelize.NOW
    }

  }, {
    timestamps  : false,
    underscored : false,
    hooks: {
      beforeCount(options) {
        options.raw = true;
      }
    }
  });

  // eslint-disable-next-line no-unused-vars
  coreUrl.associate = function (models) {

  //  coreUrl.hasMany(models.core_function, {foreignKey: 'core_url_id', sourceKey: 'core_url_id'}); 
 
    


    // Define associations here
    // See http://docs.sequelizejs.com/en/latest/docs/associations/
  };

  return coreUrl;
};
```

core-function.model.js
```
// See http://docs.sequelizejs.com/en/latest/docs/models-definition/
// for more of what you can do here.
const Sequelize = require('sequelize');
const DataTypes = Sequelize.DataTypes;

module.exports = function (app) {
  const sequelizeClient = app.get('sequelizeClient');
  const core_function = sequelizeClient.define('core_function', {
    
    core_function_id: {
      fields: ['id'],
      type: DataTypes.INTEGER,
      primaryKey: true
    },
    description: {
      type: DataTypes.STRING,
      allowNull: false,
    },

    core_url_id: {
      type: DataTypes.INTEGER,
      references: {
        model: "core_url", // Can be both a string representing the table name, or a reference to the model
        key:   "id"
      }// set relationship (hasOne) with `Series`
    },

    json_logical: {
      type: DataTypes.JSON,
      allowNull: true
    },
    json_update: {
      type: DataTypes.JSON,
      allowNull: true
    },
    active: {
      type: DataTypes.BOOLEAN,
      allowNull: true
    },
    created_at: {
      fields: ['created_at'],
      type: DataTypes.DATE,
      allowNull: true
    },
    updated_at: {
      fields: ['updated_at'],
      type: DataTypes.DATE,
      allowNull: true,
      defaultValue: Sequelize.NOW
    }

  }, {
    timestamps  : false,
    underscored : false,
    hooks: {
      beforeCount(options) {
        options.raw = true;
      }
    }
  });

  // eslint-disable-next-line no-unused-vars
  core_function.associate = function (models) {
    // Define associations here
    //See http://docs.sequelizejs.com/en/latest/docs/associations/
     models.core_url.hasOne(core_function, { foreignKeyConstraint: true, foreignKey: 'core_url_id' })
     core_function.belongsTo(models.core_url, {foreignKeyConstraint: true, foreignKey: 'core_url_id'});
     
  };

  return core_function;
};
```
pls help im new

**Comment by heisian** [comment]
You need to use the `include` attribute in your query:
```node
const coreUrl = await models.core_url.findOne({
  where: { core_url_id: 1 },
  include: [
    models.core_function,
  ]
})
```

You can also define a scope for `core_function`:
```node
core_function.associate = function  (models) {
     core_function.belongsTo(models.core_url, { foreignKey: 'core_url_id' })
}

core_function.addScope('defaultScope', {
  include: [models.core_url]
}, { override: true })
```

This will tell Sequelize to "Eager Load" the `core_url` model anytime the `core_function` model is queried.

You should also define the `core_url` association in the `core_url` model defintion file:
```node
core_url.associate = function(models) {
  core_url.hasOne(models.core_function, { foreignKey: 'core_url_id' })
}

core_url.addScope('defaultScope', {
  include: [models.core_function]
}, { override: true })
```

**Comment by HDCARDENAS2** [comment]
now the show next error

```
info: Feathers application started on http://localhost:3030
error:  SequelizeEagerLoadingError: core_function is not associated to core_url!
    at Function._getIncludedAssociation (/home/siut/siut_back_02/node_modules/sequelize/lib/model.js:582:13)
    at Function._validateIncludedElement (/home/siut/siut_back_02/node_modules/sequelize/lib/model.js:498:53)
    at options.include.options.include.map.include (/home/siut/siut_back_02/node_modules/sequelize/lib/model.js:394:37)
    at Array.map (<anonymous>)
    at Function._validateIncludedElements (/home/siut/siut_back_02/node_modules/sequelize/lib/model.js:390:39)
    at Promise.try.then.then (/home/siut/siut_back_02/node_modules/sequelize/lib/model.js:1575:14)
    at tryCatcher (/home/siut/siut_back_02/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/siut/siut_back_02/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/siut/siut_back_02/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/siut/siut_back_02/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/siut/siut_back_02/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/siut/siut_back_02/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/siut/siut_back_02/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/siut/siut_back_02/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
```
core-function.model.js

```
// See http://docs.sequelizejs.com/en/latest/docs/models-definition/
// for more of what you can do here.
const Sequelize = require('sequelize');
const DataTypes = Sequelize.DataTypes;

module.exports = function (app) {
  const sequelizeClient = app.get('sequelizeClient');
  const core_function = sequelizeClient.define('core_function', {
    
    core_function_id: {
      fields: ['id'],
      type: DataTypes.INTEGER,
      primaryKey: true
    },
    description: {
      type: DataTypes.STRING,
      allowNull: false,
    },

    core_url_id: {
      type: DataTypes.INTEGER,
     
    },

    json_logical: {
      type: DataTypes.JSON,
      allowNull: true
    },
    json_update: {
      type: DataTypes.JSON,
      allowNull: true
    },
    active: {
      type: DataTypes.BOOLEAN,
      allowNull: true
    },
    created_at: {
      fields: ['created_at'],
      type: DataTypes.DATE,
      allowNull: true
    },
    updated_at: {
      fields: ['updated_at'],
      type: DataTypes.DATE,
      allowNull: true,
      defaultValue: Sequelize.NOW
    }

  }, {
    timestamps  : false,
    underscored : false,
    hooks: {
      beforeCount(options) {
        options.raw = true;
      }
    }
  });

  // eslint-disable-next-line no-unused-vars
  core_function.associate = function (models) {
    // Define associations here
    //See http://docs.sequelizejs.com/en/latest/docs/associations/
    
    core_function.belongsTo(models.core_url, { foreignKey: 'core_url_id' })

    core_function.addScope('defaultScope', {  include: [models.core_url] }, { override: true })
    
  };

  return core_function;
};
```

core-url.model.js

```
// See http://docs.sequelizejs.com/en/latest/docs/models-definition/
// for more of what you can do here.
const Sequelize = require('sequelize');
const DataTypes = Sequelize.DataTypes;

module.exports = function (app) {
  const sequelizeClient = app.get('sequelizeClient');
  const core_url = sequelizeClient.define('core_url', {

    core_url_id: {
      fields: ['id'],
      type: DataTypes.INTEGER,
      primaryKey: true
    },
    description: {
      type: DataTypes.STRING,
      allowNull: false
    },
    path_url: {
      type: DataTypes.INTEGER,
      allowNull: false
    },
    active: {
      type: DataTypes.BOOLEAN,
      allowNull: true
    },
    created_at: {
      fields: ['created_at'],
      type: DataTypes.DATE,
      allowNull: true
    },
    updated_at: {
      fields: ['updated_at'],
      type: DataTypes.DATE,
      allowNull: true,
      defaultValue: Sequelize.NOW
    }

  }, {
    timestamps  : false,
    underscored : false,
    hooks: {
      beforeCount(options) {
        options.raw = true;
      }
    }
  });

  // eslint-disable-next-line no-unused-vars
  core_url.associate = function (models) {
    
     core_url.hasOne(models.core_function, { foreignKey: 'core_url_id' })
    
     core_url.addScope('defaultScope', {
       include: [models.core_function]
     }, 
     { override: true }
    )
    // Define associations here
    // See http://docs.sequelizejs.com/en/latest/docs/associations/
  };
  

  return core_url;
};
```
consulta-funciones.class.js

```
/* eslint-disable no-unused-vars */
class Service {
  constructor (options) {
    this.options = options || {};
  }

  async find (params) {

    const app                   = this.options.app
    const core_url              = app.service('core-url').Model
    const core_function         = app.service('core-function').Model

    const coreUrl = await core_url.findOne({
      where: { core_url_id : 1 
      },
      include: [ core_function ]
    
    }).then(data => {
     
      console.log(JSON.stringify(data))

    })

    return [];
  }

  async get (id, params) {
    return {
      id, text: `A new message with ID: ${id}!`
    };
  }

}

module.exports = function (options) {
  return new Service(options);
};

module.exports.Service = Service;

```

**Comment by sushantdhiman** [comment]
@HDCARDENAS2 Not sure how feathers handle associate, where are you calling those `associate` methods defined, and what version of sequelize is this?

**Comment by HDCARDENAS2** [comment]
package.json
```
"dependencies": {
    "@feathersjs/authentication": "^2.1.3",
    "@feathersjs/authentication-jwt": "^2.0.0",
    "@feathersjs/authentication-local": "^1.1.1",
    "@feathersjs/configuration": "^1.0.2",
    "@feathersjs/errors": "^3.3.0",
    "@feathersjs/express": "^1.2.0",
    "@feathersjs/feathers": "^3.1.3",
    "@feathersjs/socketio": "^3.2.0",
    "compression": "^1.7.2",
    "cookie-parser": "^1.4.3",
    "cors": "^2.8.4",
    "dotenv": "^5.0.1",
    "feathers-memory": "^2.1.1",
    "feathers-mongoose": "^6.1.0",
    "feathers-sequelize": "^3.0.1",
    "helmet": "^3.12.0",
    "mongoose": "^5.0.12",
    "pg": "^7.4.1",
    "randexp": "^0.4.9",
    "sequelize": "^4.37.3",
    "serve-favicon": "^2.4.5",
    "winston": "^2.4.1"
  }
```
"sequelize": "^4.37.3"

sequelize.js
```
require('dotenv').config();
const Sequelize = require('sequelize');
const { Op } = Sequelize;
const operatorsAliases = {
  $eq: Op.eq,
  $ne: Op.ne,
  $gte: Op.gte,
  $gt: Op.gt,
  $lte: Op.lte,
  $lt: Op.lt,
  $not: Op.not,
  $in: Op.in,
  $notIn: Op.notIn,
  $is: Op.is,
  $like: Op.like,
  $notLike: Op.notLike,
  $iLike: Op.iLike,
  $notILike: Op.notILike,
  $regexp: Op.regexp,
  $notRegexp: Op.notRegexp,
  $iRegexp: Op.iRegexp,
  $notIRegexp: Op.notIRegexp,
  $between: Op.between,
  $notBetween: Op.notBetween,
  $overlap: Op.overlap,
  $contains: Op.contains,
  $contained: Op.contained,
  $adjacent: Op.adjacent,
  $strictLeft: Op.strictLeft,
  $strictRight: Op.strictRight,
  $noExtendRight: Op.noExtendRight,
  $noExtendLeft: Op.noExtendLeft,
  $and: Op.and,
  $or: Op.or,
  $any: Op.any,
  $all: Op.all,
  $values: Op.values,
  $col: Op.col
};

module.exports = function (app) {

  const connectionString = `postgres://${process.env.NAME}:${process.env.PASS}@${process.env.HOST}:${process.env.PORT}/${process.env.BD}`;

  const sequelize = new Sequelize(connectionString, {
    dialect: 'postgres',
    logging: false,
    operatorsAliases,
    define: {
      freezeTableName: true
    }
  });
  const oldSetup = app.setup;

  app.set('sequelizeClient', sequelize);

  app.setup = function (...args) {
    const result = oldSetup.apply(this, args);

    // Set up data relationships
    const models = sequelize.models;
    Object.keys(models).forEach(name => {
      if ('associate' in models[name]) {
        models[name].associate(models);
      }
    });

    // Sync to the database
    sequelize.sync();

    return result;
  };
};
```
i go shared this issus with feathers team to, thanks very much you help

**Comment by HDCARDENAS2** [comment]
this issue was solved in feathers
