### ISSUE TITLE
Something wrong when I set  option where

### ISSUE THREAD

**Issue by yijialee** [sequelize/sequelize#9322]
## I want to get a list of objects.

```js
Visitor.findAll({
    where: { 
        ip: {
            $in: ["141.8.142.131","141.8.142.132"]
        }
    }, limit: 2, offset: 10
}).then(visitors => {
    console.log(visitors);
})
```

## Something wrong
 ```
Unhandled rejection Error: Invalid value { '$in': [ '141.8.142.131', '141.8.142.132' ] }
    at Object.escape (I:\NodeJs\graphql\expressgraphql\demo\node_modules\sequelize\lib\sql-string.js:66:11)
    at Object.escape (I:\NodeJs\graphql\expressgraphql\demo\node_modules\sequelize\lib\dialects\abstract\query-generator.js:934:22)
    at Object._whereParseSingleValueObject (I:\NodeJs\graphql\expressgraphql\demo\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2433:41)
    at Object.whereItemQuery (I:\NodeJs\graphql\expressgraphql\demo\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2133:21)
    at Utils.getComplexKeys.forEach.prop (I:\NodeJs\graphql\expressgraphql\demo\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1994:25)
    at Array.forEach (<anonymous>)
    at Object.whereItemsQuery (I:\NodeJs\graphql\expressgraphql\demo\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1992:35)
    at Object.getWhereConditions (I:\NodeJs\graphql\expressgraphql\demo\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2460:19)
    at Object.selectQuery (I:\NodeJs\graphql\expressgraphql\demo\node_modules\sequelize\lib\dialects\abstract\query-generator.js:1140:28)
    at QueryInterface.select (I:\NodeJs\graphql\expressgraphql\demo\node_modules\sequelize\lib\query-interface.js:1105:27)
    at Promise.try.then.then.then (I:\NodeJs\graphql\expressgraphql\demo\node_modules\sequelize\lib\model.js:1604:34)
    at tryCatcher (I:\NodeJs\graphql\expressgraphql\demo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (I:\NodeJs\graphql\expressgraphql\demo\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (I:\NodeJs\graphql\expressgraphql\demo\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (I:\NodeJs\graphql\expressgraphql\demo\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (I:\NodeJs\graphql\expressgraphql\demo\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (I:\NodeJs\graphql\expressgraphql\demo\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (I:\NodeJs\graphql\expressgraphql\demo\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (I:\NodeJs\graphql\expressgraphql\demo\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

__Dialect:__ mysql 
__Dialect version:__ XXX
__Database version:--5.1.48
__Sequelize version:--4.37.6
__Tested with latest --release:__yes(--4.37.6)

**Comment by sushantdhiman** [comment]
It `Op.in` not `$in` that you should be using

**Comment by yijialee** [comment]
@sushantdhiman  Thanks. you are right. I get Op ,then it works. thank you
```
var Op = Sequelize.Op;
```
