### ISSUE TITLE
Connection closed before request completed.

### ISSUE THREAD

**Issue by FlandersBurger** [sequelize/sequelize#9333]
## What are you doing?
Running a select query
```js
  FileGroup.findAll({
    include: [{ model: File, as: 'Files' }, { model: Item, as: 'Items' }]
  })
  .then(function (groups) {
    res.json(groups.map(function (a) { return a.dataValues; }));
  }, function(err) {
    console.error(err);
  });
```

## What do you expect to happen?
the "groups" populated

## What is actually happening?
one in 10 request or so i get this error, all other times it works:
RequestError: Connection closed before request completed.

FULL ERROR:

 { RequestError: Connection closed before request completed.
       at RequestError (G:\Work\IPAdmin\node_modules\tedious\lib\errors.js:34:12)
       at Connection.cleanupConnection (G:\Work\IPAdmin\node_modules\tedious\lib\connection.js:450:21)
       at Connection.enter (G:\Work\IPAdmin\node_modules\tedious\lib\connection.js:1729:19)
       at Connection.transitionTo (G:\Work\IPAdmin\node_modules\tedious\lib\connection.js:846:33)
       at Connection.close (G:\Work\IPAdmin\node_modules\tedious\lib\connection.js:428:19)
       at resolve (G:\Work\IPAdmin\node_modules\sequelize\lib\dialects\mssql\connection-manager.js:143:18)
       at Promise._execute (G:\Work\IPAdmin\node_modules\bluebird\js\release\debuggability.js:303:9)
       at Promise._resolveFromExecutor (G:\Work\IPAdmin\node_modules\bluebird\js\release\promise.js:483:18)
       at new Promise (G:\Work\IPAdmin\node_modules\bluebird\js\release\promise.js:79:10)
       at ConnectionManager.disconnect (G:\Work\IPAdmin\node_modules\sequelize\lib\dialects\mssql\connection-manager.js:141:12)
       at ConnectionManager._disconnect (G:\Work\IPAdmin\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:339:43)
       at Object.destroy (G:\Work\IPAdmin\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:114:23)
       at Pool._destroy (G:\Work\IPAdmin\node_modules\generic-pool\lib\Pool.js:129:42)
       at Pool.destroy (G:\Work\IPAdmin\node_modules\generic-pool\lib\Pool.js:475:10)
       at Connection.connection.on.err (G:\Work\IPAdmin\node_modules\sequelize\lib\dialects\mssql\connection-manager.js:124:25)
       at emitOne (events.js:115:13)
       at Connection.emit (events.js:210:7)
       at Connection.socketError (G:\Work\IPAdmin\node_modules\tedious\lib\connection.js:873:14)
       at emitOne (events.js:115:13)
       at Socket.emit (events.js:210:7)
       at emitErrorNT (internal/streams/destroy.js:64:8)
       at _combinedTickCallback (internal/process/next_tick.js:138:11)
     message: 'Connection closed before request completed.',
     code: 'ECLOSE',
     sql: 'SELECT [FileGroups].[FileGroupID], [FileGroups].[GroupName], [FileGroups].[GroupAlias], [FileGroups].[CreationDate], [FileGroups].[BadgeSize], [Files].[FileID] AS [Files.FileID], [Files].[OriginalLocation] AS [Files.OriginalLocation], [Files].[OriginalName] AS [Files.OriginalName], [Files].[DownloadName] AS [Files.DownloadName], [Files].[Size] AS [Files.Size], [Files].[Enabled] AS [Files.Enabled], [Files].[FileType] AS [Files.FileType], [Files].[LastUpdateDate] AS [Files.LastUpdateDate], [Files].[CreationDate] AS [Files.CreationDate], [Files].[Base64String] AS [Files.Base64String], [Files].[FileGroupID] AS [Files.FileGroupID], [Items].[ItemNo] AS [Items.ItemNo], [Items].[ItemDesc] AS [Items.ItemDesc], [Items].[BadgeSize] AS [Items.BadgeSize], [Items].[FileGroupID] AS [Items.FileGroupID] FROM [FileGroups] AS [FileGroups] LEFT OUTER JOIN [Files] AS [Files] ON [FileGroups].[FileGroupID] = [Files].[FileGroupID] LEFT OUTER JOIN [Items] AS [Items] ON [FileGroups].[FileGroupID] = [Items].[FileGroupID];' },
  sql: 'SELECT [FileGroups].[FileGroupID], [FileGroups].[GroupName], [FileGroups].[GroupAlias], [FileGroups].[CreationDate], [FileGroups].[BadgeSize], [Files].[FileID] AS [Files.FileID], [Files].[OriginalLocation] AS [Files.OriginalLocation], [Files].[OriginalName] AS [Files.OriginalName], [Files].[DownloadName] AS [Files.DownloadName], [Files].[Size] AS [Files.Size], [Files].[Enabled] AS [Files.Enabled], [Files].[FileType] AS [Files.FileType], [Files].[LastUpdateDate] AS [Files.LastUpdateDate], [Files].[CreationDate] AS [Files.CreationDate], [Files].[Base64String] AS [Files.Base64String], [Files].[FileGroupID] AS [Files.FileGroupID], [Items].[ItemNo] AS [Items.ItemNo], [Items].[ItemDesc] AS [Items.ItemDesc], [Items].[BadgeSize] AS [Items.BadgeSize], [Items].[FileGroupID] AS [Items.FileGroupID] FROM [FileGroups] AS [FileGroups] LEFT OUTER JOIN [Files] AS [Files] ON [FileGroups].[FileGroupID] = [Files].[FileGroupID] LEFT OUTER JOIN [Items] AS [Items] ON [FileGroups].[FileGroupID] = [Items].[FileGroupID];' }

**Comment by sushantdhiman** [comment]
I think you are hitting your service provider's maximum connection limit, can you check if your pool settings have properly defined max connection limit as per your database provider's max allowed limit

**Comment by FlandersBurger** [comment]
Hi Sushantdhiman, That's what i thought too but it only hangs on this specific query for some reason. I call queries before and after it and they are fine for some reason. The only thing different with this one is that it joins 2 other tables

very strange, I'm so stumped by this that I just have it rerun the same query when this error happens and it works, A solution i do not like for obvious reasons

**Comment by pvanagtmaal** [comment]
@FlandersBurger Did you manage to find a solution? We are currently experiencing the exact same issue...

**Comment by FlandersBurger** [comment]
> @FlandersBurger Did you manage to find a solution? We are currently experiencing the exact same issue...

I added specific attributes and that seems to have done it. Must be something to do with a particular attribute I had. I never figured out which one.

```

  FileGroup.findAll({
    attributes: ['FileGroupID','GroupName','GroupAlias','BadgeSize'],
    include: [
      {
        model: File,
        as: 'Files',
        attributes: ['FileID','Size']
      },
      {
        model: WebItem,
        as: 'Items',
        attributes: ['ItemNo','ItemDesc']
      }
    ]
  })
```
