### ISSUE TITLE
Seeder - Wrong DB credentials in Promise

### ISSUE THREAD

**Issue by cedriccouret** [sequelize/sequelize#9346]
## What are you doing?

I'm trying to run my two seeders in production environment (--env=production)
My first seeder properly inserts roles in the "Roles" tables properly but the second one (as displayed below) throws an exception saying that it is unable to access the database with the provided credentials. The error message mentions dev database credentials.

I'm using Promises to make sure that I retrieve newly created user roles before trying to attach their respective ids to the users.

These are the commands I run from the "database" folder:

1. ../node_modules/.bin/sequelize db:migrate --env=production
2. ../node_modules/.bin/sequelize db:seed:all --env=production

It works just fine in dev environment.

```js
'use strict';

let models = require('../models/index');

const uuidv4 = require('uuid/v4');

module.exports = {
    up: (queryInterface, Sequelize) => {
        let adminRoleId, operatorRoleId;

        let adminRolePromise = new Promise(function (resolve, reject) {
            models.Role.findOne({ where: {name: 'administrator'} }).then(role => {
                adminRoleId = role.id;

                resolve();
            });
        });

        let operatorRolePromise = new Promise(function (resolve, reject) {
            models.Role.findOne({ where: {name: 'operator'} }).then(role => {
                operatorRoleId = role.id;

                resolve();
            });
        });

        return Promise.all([adminRolePromise, operatorRolePromise]).then(function(values) {
            return queryInterface.bulkInsert('Users', [
                {
                    id: uuidv4(),
                    firstName: 'Admin',
                    lastName: '',
                    userName: 'admin',
                    password: models.User.hashPassword('secret'),
                    roleId: adminRoleId
                },
                {
                    id: uuidv4(),
                    firstName: 'Cédric',
                    lastName: 'COURET',
                    userName: 'ccouret',
                    password: models.User.hashPassword('secret'),
                    roleId: operatorRoleId
                }
            ], {});
        });
    },

    down: (queryInterface, Sequelize) => {
        return queryInterface.bulkDelete('Users', null, {});
    }
};
```

## What do you expect to happen?
I expect that both seeders run with production credentials.

## What is actually happening?
Only the first one runs with production credentials, the second one seems to use dev credentials and then obviously fails.

_Output, either JSON or SQL_
ERROR: Access denied for user 'homestead'@'localhost' (using password: YES)

__Dialect:__ mysql
__Dialect version:__ XXX
__Database version:__ 5.7.21
__Sequelize version:__ 4.37.6
__Tested with latest release:__ Yes

here is the output of ../node_modules/.bin/sequelize --version
Sequelize CLI [Node: 8.10.0, CLI: 4.0.0, ORM: 4.37.6]

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
So you are saying migrate command is using credentials from production but seeder command is defaulting to development credentials?

**Comment by cedriccouret** [comment]
Hi,

the migration is running fine with prod credentials.
When I run all the seeders at once (I have 2) in prod, the first one uses prod and the second one uses dev credentials. Is it because I use Promises in the second one ?

**Comment by sushantdhiman** [comment]
> When I run all the seeders at once (I have 2) in prod

a seeder is one file, which can have multiple create(or any) database operations if promises are properly chained.

So it looks like you only have one seeder but improper promise chain. Can you post full error with stack. Pass ``--debug`` for stack trace

**Comment by cedriccouret** [comment]
I created one seeder file per table:
20180414195510-roles.js
20180414195512-users.js

I'm used to the Laravel world where migrations and seeders are (or can be anyway) per model/table.
Is that a bad practice when it comes to Sequelize ?

Here is the output in debug mode:
```
../node_modules/.bin/sequelize db:seed:all --env=production --debug

Sequelize CLI [Node: 8.10.0, CLI: 4.0.0, ORM: 4.37.6]

Loaded configuration file "config/config.json".
Using environment "production".
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators ../node_modules/sequelize/lib/sequelize.js:242:13
Executing (default): SELECT 1+1 AS result
== 20180414195510-roles: migrating =======
Executing (default): INSERT INTO `Roles` (`id`,`name`,`description`) VALUES ('8dbb9f54-4d8d-4774-988d-3b66233d6e04','tecnar','Super Administrator'),('b4f29ff0-5391-4ee9-8aa6-abedf4e9dda4','administrator','Administrator'),('0da1b392-e2a8-42d4-ac72-e0aba4b8f684','operator','Operator');
== 20180414195510-roles: migrated (0.013s)

== 20180414195512-users: migrating =======
Unhandled rejection SequelizeAccessDeniedError: Access denied for user 'tecsrv'@'localhost' (using password: YES)
    at Utils.Promise.tap.then.catch.err (/home/vagrant/Code/accura-ui/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:141:19)
    at tryCatcher (/home/vagrant/Code/accura-ui/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/vagrant/Code/accura-ui/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/vagrant/Code/accura-ui/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/vagrant/Code/accura-ui/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/vagrant/Code/accura-ui/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/home/vagrant/Code/accura-ui/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/vagrant/Code/accura-ui/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/vagrant/Code/accura-ui/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)

Unhandled rejection SequelizeAccessDeniedError: Access denied for user 'tecsrv'@'localhost' (using password: YES)
    at Utils.Promise.tap.then.catch.err (/home/vagrant/Code/accura-ui/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:141:19)
    at tryCatcher (/home/vagrant/Code/accura-ui/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/vagrant/Code/accura-ui/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/vagrant/Code/accura-ui/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/vagrant/Code/accura-ui/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/vagrant/Code/accura-ui/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/home/vagrant/Code/accura-ui/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/vagrant/Code/accura-ui/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/vagrant/Code/accura-ui/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)

Unhandled rejection SequelizeAccessDeniedError: Access denied for user 'tecsrv'@'localhost' (using password: YES)
    at Utils.Promise.tap.then.catch.err (/home/vagrant/Code/accura-ui/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:141:19)
    at tryCatcher (/home/vagrant/Code/accura-ui/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/vagrant/Code/accura-ui/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/vagrant/Code/accura-ui/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/vagrant/Code/accura-ui/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/vagrant/Code/accura-ui/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/home/vagrant/Code/accura-ui/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/vagrant/Code/accura-ui/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/vagrant/Code/accura-ui/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
```

**Comment by sushantdhiman** [comment]
Are you sure

```
let models = require('../models/index');
```

Is using correct environment, because models finder functions are failing not `queryInterface`. I suggest get `sequelize` instance from `queryInterface` and then use models from that
