### ISSUE TITLE
error hookTypes[hookType].proxies

### ISSUE THREAD

**Issue by zengwe** [sequelize/sequelize#9381]
A web project is work successful,but now  it is't working when I move to other folder with command of 'npm install'.
error:
/node_modules/sequelize/lib/hooks.js:64
  hookTypes[hookType].proxies
                      ^

TypeError: Cannot read property 'proxies' of undefined
    at getProxiedHooks (/home/server/gantt_demo/server/node_modules/sequelize/lib/hooks.js:64:23)
    at Function.addHook (/home/server/gantt_demo/server/node_modules/sequelize/lib/hooks.js:158:16)
    at hooksArray.forEach.hookFn (/home/server/gantt_demo/server/node_modules/sequelize/lib/hooks.js:87:41)
    at Array.forEach (<anonymous>)
    at _.map (/home/server/gantt_demo/server/node_modules/sequelize/lib/hooks.js:87:18)
    at /home/server/gantt_demo/server/node_modules/lodash/lodash.js:3563:27
    at /home/server/gantt_demo/server/node_modules/lodash/lodash.js:4925:15
    at baseForOwn (/home/server/gantt_demo/server/node_modules/lodash/lodash.js:3010:24)
    at /home/server/gantt_demo/server/node_modules/lodash/lodash.js:4894:18
    at baseMap (/home/server/gantt_demo/server/node_modules/lodash/lodash.js:3562:7)
    at Function.map (/home/server/gantt_demo/server/node_modules/lodash/lodash.js:9554:14)
    at Function._setupHooks (/home/server/gantt_demo/server/node_modules/sequelize/lib/hooks.js:85:7)
    at Function.init (/home/server/gantt_demo/server/node_modules/sequelize/lib/model.js:774:10)
    at Sequelize.define (/home/server/gantt_demo/server/node_modules/sequelize/lib/sequelize.js:336:11)
    at module.exports.app (/home/server/gantt_demo/server/app/model/test.js:3:24)
    at getExports (/home/server/gantt_demo/server/node_modules/egg-core/lib/loader/file_loader.js:220:15)
    at FileLoader.parse (/home/server/gantt_demo/server/node_modules/egg-core/lib/loader/file_loader.js:158:25)
    at FileLoader.load (/home/server/gantt_demo/server/node_modules/egg-core/lib/loader/file_loader.js:67:24)
    at AgentWorkerLoader.loadToApp (/home/server/gantt_demo/server/node_modules/egg-core/lib/loader/egg_loader.js:358:25)
    at loadModel (/home/server/gantt_demo/server/node_modules/egg-sequelize/lib/loader.js:49:14)
    at module.exports.app (/home/server/gantt_demo/server/node_modules/egg-sequelize/lib/loader.js:40:3)
    at module.exports.agent (/home/server/gantt_demo/server/node_modules/egg-sequelize/agent.js:4:26)
2018-05-02 16:45:45,695 ERROR 15769 nodejs.AgentWorkerDiedError: [master] agent_worker#1:15775 died (code: 1, signal: null)
    at Master.onAgentExit (/home/server/gantt_demo/server/node_modules/egg-cluster/lib/master.js:317:17)
    at emitOne (events.js:116:13)
    at Master.emit (events.js:211:7)
    at Messenger.sendToMaster (/home/server/gantt_demo/server/node_modules/egg-cluster/lib/utils/messenger.js:122:17)
    at Messenger.send (/home/server/gantt_demo/server/node_modules/egg-cluster/lib/utils/messenger.js:87:12)
    at ChildProcess.agentWorker.once (/home/server/gantt_demo/server/node_modules/egg-cluster/lib/master.js:216:22)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
name: 'AgentWorkerDiedError'

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396

**Comment by sushantdhiman** [comment]
Looks like your dependencies changed between two installations and which resulted in this error, can you show changed version of sequelize and how you are defining hooks

**Comment by fareshan** [comment]
@zengwe Could you solve this issue ?

**Comment by matthewbednarski** [comment]
Just ensure the names of your defined hooks are found in [hooks](https://sequelize.org/v5/manual/hooks.html).

In my case, it was because I had defined hooks for `beforeBulkDelete` and `afterDelete`, which are now named `beforeBulkDestroy` and `afterDestroy`.

**Comment by georgegoldman** [comment]
Good day guys having the same issue too $ node appkPad-X1-Carbon:~/Documents/application_j 
/home/lb/Documents/application_js/node_modules/sequelize/lib/hooks.js:65
  hookTypes[hookType].proxies
                      ^

TypeError: Cannot read property 'proxies' of undefined
    at getProxiedHooks (/home/lb/Documents/application_js/node_modules/sequelize/lib/hooks.js:65:23)
    at Function.addHook (/home/lb/Documents/application_js/node_modules/sequelize/lib/hooks.js:152:16)
    at /home/lb/Documents/application_js/node_modules/sequelize/lib/hooks.js:88:41
    at Array.forEach (<anonymous>)
    at /home/lb/Documents/application_js/node_modules/sequelize/lib/hooks.js:88:18
    at /home/lb/Documents/application_js/node_modules/lodash/lodash.js:3543:27
    at /home/lb/Documents/application_js/node_modules/lodash/lodash.js:4905:15
    at baseForOwn (/home/lb/Documents/application_js/node_modules/lodash/lodash.js:2990:24)
    at /home/lb/Documents/application_js/node_modules/lodash/lodash.js:4874:18
    at baseMap (/home/lb/Documents/application_js/node_modules/lodash/lodash.js:3542:7)
    at Function.map (/home/lb/Documents/application_js/node_modules/lodash/lodash.js:9554:14)
    at Function._setupHooks (/home/lb/Documents/application_js/node_modules/sequelize/lib/hooks.js:86:7)
    at Function.init (/home/lb/Documents/application_js/node_modules/sequelize/lib/model.js:977:10)
    at Sequelize.define (/home/lb/Documents/application_js/node_modules/sequelize/lib/sequelize.js:428:11)
    at Object.<anonymous> (/home/lb/Documents/application_js/models/user.js:6:22)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/lb/Documents/application_js/app.js:12:14)
