### ISSUE TITLE
SQLITE_BUSY?

### ISSUE THREAD

**Issue by homakov** [sequelize/sequelize#9398]
## What are you doing?

I keep getting `{ Error: SQLITE_BUSY: database is locked` during running benchmarks on the app, but when i use it not so heavily i don't have any problems. Apparently there's some concurrency bug. Clearly not doing or using any fancy features: the usage is a bunch of read and writes. No parallel app uses it. MacOS, sqlite 4.0.0

```
{ SequelizeTimeoutError: SQLITE_BUSY: database is locked
    at Query.formatError (/Users/homakov/work/fs/node_modules/sequelize/lib/dialects/sqlite/query.js:420:16)
    at afterExecute (/Users/homakov/work/fs/node_modules/sequelize/lib/dialects/sqlite/query.js:119:32)
    at replacement (/Users/homakov/work/fs/node_modules/sqlite3/lib/trace.js:19:31)
    at Statement.errBack (/Users/homakov/work/fs/node_modules/sqlite3/lib/sqlite3.js:16:21)
    at Statement.topLevelDomainCallback (domain.js:121:23)
```

Also this one:

```
{ Error: commit has been called on this transaction(7790b644-85fa-4c83-b2ca-19492540b6ae), you can no longer use it. (The rejected query is attached as the 'sql' property of this error)
    at Promise.try (/Users/homakov/work/fs/node_modules/sequelize/lib/sequelize.js:528:23)
    at tryCatcher (/Users/homakov/work/fs/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/homakov/work/fs/node_modules/bluebird/js/release/method.js:39:29)
    at retryParameters (/Users/homakov/work/fs/node_modules/sequelize/lib/sequelize.js:454:48)
    at /Users/homakov/work/fs/node_modules/retry-as-promised/index.js:39:21
    at Promise._execute (/Users/homakov/work/fs/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/Users/homakov/work/fs/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/homakov/work/fs/node_modules/bluebird/js/release/promise.js:79:10)
    at retryAsPromised (/Users/homakov/work/fs/node_modules/retry-as-promised/index.js:29:10)
    at Timeout._onTimeout (/Users/homakov/work/fs/node_modules/retry-as-promised/index.js:80:11)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10) sql: 'COMMIT;' }
```

If this doesn't sound familiar, i will try to get a self-contained demo, but it would take some time. I tried setting pool to min=0, max=1 and it has no impact.

**Comment by internalfx** [comment]
This is not uncommon with SQLite.

You might have some luck setting a retry..

```
sequelize: {
  dialect: 'sqlite',
  retry: {
    max: 10
  }
}
```

**Comment by homakov** [comment]
Doesn't seem to help. What is underlying reason - sometimes it works sometimes COMMIT error, am i making too many requests?

**Comment by internalfx** [comment]
> making too many requests?

Basically, SQLite locks the database for any writes. So parallel requests can time out if there are too many.

**Comment by sushantdhiman** [comment]
@internalfx said it, Its known behaviour of SQLite, thats why we defaults to https://github.com/sequelize/sequelize/blob/4fdb941dcc7f8c4122cf705ad21006d30c86ceb7/lib/sequelize.js#L166

If you are writing an application with high concurrency of writes I suggest use Postgres / MySQL etc

**Comment by homakov** [comment]
Thanks, @sushantdhiman i have tried to migrate to postgres and now it performs a lot better. However when i increase number of tx and run 10 bots interacting with each other i still receive `TimeoutError: ResourceRequest timed out` 

- I wonder, is that something i could fight with options like retry/pool? Or is it a real limitation of running test on my macbook dev machine?

**Comment by sushantdhiman** [comment]
`TimeoutError: ResourceRequest timed out` this happens when Sequelize is unable to acquire connection in given time, default is 20 sec I think. You will have to tweak your pool settings.

Please refer this this [thread](https://github.com/sequelize/sequelize/issues/7884) for more details
