### ISSUE TITLE
sequelize Raw Queries faliling

### ISSUE THREAD

**Issue by karankapur999** [sequelize/sequelize#9491]
## What are you doing?

```js
// code here



Executing (default): select g.*, gg.duration  from appointment_details as g join services gg on g.service_id = gg.id  where g.business_id =187  and g.line_type='Appointment' and CAST (local_start_time AS TIME) BETWEEN ('16:10'  - interval '1 hours' * gg.duration/60) and ('16:10'  + interval '1 hours')  and date in('2018-05-29 05:30:00.000 +05:30','2018-05-30 05:30:00.000 +05:30') and g.assigned_id = ('316') LIMIT 10000;

Query running fine on postgress 
Unhandled rejection SequelizeDatabaseError: syntax error at or near " "
    at Query.formatError (/Users/karankapur/Desktop/beagle-backend/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)
    at Query.<anonymous> (/Users/karankapur/Desktop/beagle-backend/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
    at Query.nrWrappedHandler (/Users/karankapur/Desktop/beagle-backend/node_modules/newrelic/lib/transaction/tracer/index.js:400:19)
    at Query.wrapped (/Users/karankapur/Desktop/beagle-backend/node_modules/newrelic/lib/transaction/tracer/index.js:184:28)
    at Query.wrappedCallback (/Users/karankapur/Desktop/beagle-backend/node_modules/newrelic/lib/transaction/tracer/index.js:452
```

## What do you expect to happen?
_I wanted Foo!_

## What is actually happening?
_But the output was bar!_

_Output, either JSON or SQL_

__Dialect:__ mysql / postgres / sqlite / mssql / any
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ XXX
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
This issue is not related to Sequelize as discussed in thread https://github.com/sequelize/sequelize/issues/9460 

As this issue is reproducible at `node-postgres` level I think its related to driver, but I can't say as query seems fine to me.
