### ISSUE TITLE
Support scope in include？

### ISSUE THREAD

**Issue by YeungKC** [sequelize/sequelize#9497]
## What are you doing?
I  want use scope in include, like that:

user scope
```JavaScript
    User.addScope('detail', function(option = {}, columnName = { user: 'user' }) {
      const attributes = {
        include: [
          [ model.literal(`(SELECT COUNT(*) FROM followerRelations WHERE followerId = ${columnName.user}.id)`), 'friendsCount' ],
          [ model.literal(`(SELECT COUNT(*) FROM followerRelations WHERE userId = ${columnName.user}.id)`), 'followersCount' ],
        ],
      };

      if (option.userId) {
        attributes.include.push(
          [ model.literal(`(SELECT COUNT(*) FROM followerRelations WHERE userId = ${columnName.user}.id and followerId = ${option.userId})`), 'isFollowing' ]
        );
      }

      const include = [{
        model: File,
        as: 'avatarFile',
      }, {
        model: UserOAuth,
        as: 'oauths',
      }];

      return {
        attributes,
        include,
        order: [[ 'createdAt', 'ASC' ]],
      };
    });
```
news
```JavaScript
    model.News.addScope('detail', function(option = {}, columnName) {
      columnName = Object.assign({ news: 'news', publisher: 'publisher' }, columnName);

      const attributes = {
        include: [
          [ model.literal(`(SELECT COUNT(*) FROM newsCollects WHERE newsId = ${columnName.news}.id)`), 'collectCount' ],
          [ model.literal(`(SELECT COUNT(*) FROM newsComments WHERE newsId = ${columnName.news}.id)`), 'commentCount' ],
        ],
      };

      if (option.userId) {
        attributes.include.push([ model.literal(`(SELECT COUNT(*) FROM newsCollects WHERE newsId = ${columnName.news}.id and userId = ${option.userId})`), 'isCollected' ]);
      }

      const include = [{
        model: model.NewsClassify,
        as: 'classify',
      }, {
        model: model.User.scopes({ method: [ 'detail', { userId: option.userId }, { user: columnName.publisher }] }),
        as: 'publisher',
      }];

      return {
        attributes,
        include,
      };
    });
```

## What do you expect to happen?
_I wanted Foo!_
I want work…but…

```js
TypeError: include.attributes.map is not a function
    at Object.generateInclude (/Users/YeungKC/WebStormProjects/ProjectName/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1287:52)
    at Object.generateInclude (/Users/YeungKC/WebStormProjects/ProjectName/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1355:39)
    at Object.selectQuery (/Users/YeungKC/WebStormProjects/ProjectName/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1011:34)
    at QueryInterface.select (/Users/YeungKC/WebStormProjects/ProjectName/node_modules/sequelize/lib/query-interface.js:1105:27)
    at Promise.try.then.then.then (/Users/YeungKC/WebStormProjects/ProjectName/node_modules/sequelize/lib/model.js:1604:34)
    at tryCatcher (/Users/YeungKC/WebStormProjects/ProjectName/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/YeungKC/WebStormProjects/ProjectName/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/YeungKC/WebStormProjects/ProjectName/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/YeungKC/WebStormProjects/ProjectName/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/YeungKC/WebStormProjects/ProjectName/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/YeungKC/WebStormProjects/ProjectName/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/YeungKC/WebStormProjects/ProjectName/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/YeungKC/WebStormProjects/ProjectName/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
```

## What is actually happening?
_But the output was bar!_
I want work…why not support？

_Output, either JSON or SQL_

__Dialect:__ mysql / postgres / sqlite / mssql / any
__Dialect version:__ XXX
__Database version:__ XXX
__Sequelize version:__ XXX
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by YeungKC** [comment]
I found that I mistyped method `scope` to `scopes`
