### ISSUE TITLE
`SequelizeDatabaseError: missing FROM-clause entry for table "mytablename"` when I use required

### ISSUE THREAD

**Issue by PsiXdev** [sequelize/sequelize#9507]
## What are you doing?

I have 3 tables:
```sql
create table "parents" ("_id" serial primary key);
create table "somethings" ("_id" serial primary key);
create table "children" ("_id" serial primary key, "parentId" integer not null, "somethingId" integer not null);
```

And I execute this code:
```js
const parents = await db.parents.findAll({
	include: [{
		model: db.children,
		as: 'children',
		required: true,
		include: [{
			model: db.somethings,
			as: 'something',
			required: true
		}]
	}],
	limit: 5,
	transaction,
	logging: console.log
});
```

Full code: https://gist.github.com/PsiXdev/09d35df41e8dc9702c4d9c85e3092b87

## What do you expect to happen?

I want to get
```js
[ { _id: 1,
    children:
     [ { _id: 1,
         parentId: 1,
         somethingId: 1,
         something: { _id: 1 } },
       { _id: 2,
         parentId: 1,
         somethingId: 1,
         something: { _id: 1 } } ] } ]
```

## What is actually happening?
```js
SequelizeDatabaseError: missing FROM-clause entry for table "children"
    at Query.formatError (.../node_modules/sequelize/lib/dialects/postgres/query.js:363:16)
    at query.catch.err (.../node_modules/sequelize/lib/dialects/postgres/query.js:86:18)
    at tryCatcher (.../node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (.../node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (.../node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (.../node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (.../node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (.../node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (.../node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (.../node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

This code generate such sql:
```sql
SELECT "Parent".*,
       "children"."_id" AS "children._id",
       "children"."parentId" AS "children.parentId",
       "children"."somethingId" AS "children.somethingId"
FROM
  (SELECT "Parent"."_id",
          "children->something"."_id" AS "children.something._id"
   FROM "parents" AS "Parent"
   INNER JOIN "somethings" AS "children->something" ON "children"."somethingId" = "children->something"."_id"
   WHERE
       (SELECT "children"."parentId"
        FROM "children" AS "children"
        INNER JOIN "somethings" AS "something" ON "children"."somethingId" = "something"."_id"
        WHERE ("children"."parentId" = "Parent"."_id")
        LIMIT 1) IS NOT NULL
   LIMIT 5) AS "Parent"
INNER JOIN "children" AS "children" ON "Parent"."_id" = "children"."parentId";
```

__Dialect__: postgres
__Database version__: 9.6
__Sequelize version__: 4.13.8 / 4.37.10

<hr>

<details>
  <summary>Examples of changed code with a successful result (click to expand)</summary>

1) add duplicating
```js
const parents = await db.parents.findAll({
	include: [{
		model: db.children,
		as: 'children',
		required: true,
		include: [{
			model: db.somethings,
			as: 'something',
			required: true,
			duplicating: true
		}]
	}],
	limit: 5,
	transaction,
	logging: console.log
});
```

```sql
SELECT "Parent".*,
       "children"."_id" AS "children._id",
       "children"."parentId" AS "children.parentId",
       "children"."somethingId" AS "children.somethingId",
       "children->something"."_id" AS "children.something._id"
FROM
  (SELECT "Parent"."_id"
   FROM "parents" AS "Parent"
   WHERE
       (SELECT "children"."parentId"
        FROM "children" AS "children"
        INNER JOIN "somethings" AS "something" ON "children"."somethingId" = "something"."_id"
        WHERE ("children"."parentId" = "Parent"."_id")
        LIMIT 1) IS NOT NULL
   LIMIT 5) AS "Parent"
INNER JOIN "children" AS "children" ON "Parent"."_id" = "children"."parentId"
INNER JOIN "somethings"AS "children->something" ON "children"."somethingId" = "children->something"."_id";
```

2) remove required
```js
const parents = await db.parents.findAll({
	include: [{
		model: db.children,
		as: 'children',
		required: true,
		include: [{
			model: db.somethings,
			as: 'something'
		}]
	}],
	limit: 5,
	transaction,
	logging: console.log
});
```

```sql
SELECT "Parent".*,
       "children"."_id" AS "children._id",
       "children"."parentId" AS "children.parentId",
       "children"."somethingId" AS "children.somethingId",
       "children->something"."_id" AS "children.something._id"
FROM
  (SELECT "Parent"."_id"
   FROM "parents" AS "Parent"
   WHERE
       (SELECT "parentId"
        FROM "children" AS "children"
        WHERE ("children"."parentId" = "Parent"."_id")
        LIMIT 1) IS NOT NULL
   LIMIT 5) AS "Parent"
INNER JOIN "children" AS "children" ON "Parent"."_id" = "children"."parentId"
LEFT OUTER JOIN "somethings" AS "children->something" ON "children"."somethingId" = "children->something"."_id";
```

3) remove limit
```js
const parents = await db.parents.findAll({
	include: [{
		model: db.children,
		as: 'children',
		required: true,
		include: [{
			model: db.somethings,
			as: 'something',
			required: true
		}]
	}],
	transaction,
	logging: console.log
});
```

```sql
SELECT "Parent"."_id",
       "children"."_id" AS "children._id",
       "children"."parentId" AS "children.parentId",
       "children"."somethingId" AS "children.somethingId",
       "children->something"."_id" AS "children.something._id"
FROM "parents" AS "Parent"
INNER JOIN "children" AS "children" ON "Parent"."_id" = "children"."parentId"
INNER JOIN "somethings" AS "children->something" ON "children"."somethingId" = "children->something"."_id";
```
I do not fully understand why all these changes work this way. In any case, it seems to me that there is a bug in the library.
</details>

**Comment by zxdvd** [comment]
Happens to me too.

**Comment by PsiXdev** [comment]
Today there was a similar problem, I did `findOne` with `where: {somefield: somevalue}` and I had nested include with `required: true`. I received a similar error. Although if I had `where: {_id: someId}`, there was no error. Also, the error disappeared when I added `duplicating: true` for all nesting levels except the first.
In the first case was generated just a crazy sql with triple `SELECT` instead single.

**Comment by PsiXdev** [comment]
Example for the second case: https://gist.github.com/PsiXdev/fe26a976bde0893ddeb2d7745ff4fa51
I want to get:
```js
{ _id: 1,
  somefield: 'somevalue',
  additionals:
   [ { parentId: 1,
       childId: 1,
       additional: 'some additional info',
       child: { _id: 1 } } ] }
```

but I get strange SQL query
```sql
SELECT "Parent".*,
       "additionals"."parentId" AS "additionals.parentId",
       "additionals"."childId" AS "additionals.childId",
       "additionals"."additional" AS "additionals.additional"
FROM
  (SELECT "Parent"."_id",
          "Parent"."somefield",
          "additionals->child"."_id" AS "additionals.child._id"
   FROM "parents" AS "Parent"
   INNER JOIN "children" AS "additionals->child" ON "additionals"."childId" = "additionals->child"."_id"
   WHERE "Parent"."somefield" = 'somevalue'
     AND
       (SELECT "parentId"
        FROM "parentToChild" AS "additionals"
        WHERE ("additionals"."parentId" = "Parent"."_id")
        LIMIT 1) IS NOT NULL
   LIMIT 1) AS "Parent"
INNER JOIN "parentToChild" AS "additionals" ON "Parent"."_id" = "additionals"."parentId";
-- What?!
```

and SequelizeDatabaseError
```js
SequelizeDatabaseError: missing FROM-clause entry for table "additionals"
```

The problem does not occur if I use `_id` in `where` instead `somefield`. In this case I get next SQL:
```sql
SELECT "Parent"."_id",
       "Parent"."somefield",
       "additionals"."parentId" AS "additionals.parentId",
       "additionals"."childId" AS "additionals.childId",
       "additionals"."additional" AS "additionals.additional",
       "additionals->child"."_id" AS "additionals.child._id"
FROM "parents" AS "Parent"
INNER JOIN "parentToChild" AS "additionals" ON "Parent"."_id" = "additionals"."parentId"
INNER JOIN "children" AS "additionals->child" ON "additionals"."childId" = "additionals->child"."_id"
WHERE "Parent"."_id" = 42;
```

The second way to avoid the problem is using `duplicating: true` for `child` include.
```sql
SELECT "Parent".*,
       "additionals"."parentId" AS "additionals.parentId",
       "additionals"."childId" AS "additionals.childId",
       "additionals"."additional" AS "additionals.additional",
       "additionals->child"."_id" AS "additionals.child._id"
FROM
  (SELECT "Parent"."_id",
          "Parent"."somefield"
   FROM "parents" AS "Parent"
   WHERE "Parent"."somefield" = 'somevalue'
     AND
       (SELECT "parentId"
        FROM "parentToChild" AS "additionals"
        WHERE ("additionals"."parentId" = "Parent"."_id")
        LIMIT 1) IS NOT NULL
   LIMIT 1) AS "Parent"
INNER JOIN "parentToChild" AS "additionals" ON "Parent"."_id" = "additionals"."parentId"
INNER JOIN "children" AS "additionals->child" ON "additionals"."childId" = "additionals->child"."_id";
```

**Comment by PsiXdev** [comment]
You do not consider this a bug?

**Comment by skray** [comment]
I am having this issue as well, using Sequelize 4.38.0 and Postgres 9.6. Adding 'duplicating: true' to the nested required include statement, thank you @PsiXdev for suggesting that workaround.

**Comment by sushantdhiman** [comment]
Thanks for various examples, they will eventually help me. Moved to #9869

**Comment by galihaulia** [comment]
I'm sorry, I've tried using duplicating: false. but, when the data is 8, and I put a limit of: 10.The data taken is only 3

**Comment by rawojtowicz** [comment]
Adding duplicating: false to the include breaks limit and offset.

**Comment by chrisbag** [comment]
@rawojtowicz I confirm that adding duplicating = false to the include breaks limit and offset. (It is because a single query is made instead of multiple and therefore the limit is computed before duplicates are removed by sequelize)
Therefore what is the way to go to prevent the missing from Clause entry error while still using limit and offset ?

**Comment by rawojtowicz** [comment]
@chrisbag I wish i knew that, haha. I gave up on using sequelize. Afaik this bug exists since almost 8 years. I'm a VERY happy knex user now. :-)

**Comment by hayksaryan** [comment]
Any updates on this?

**Comment by JacopoCrocetta** [comment]
any update?

**Comment by gauravrajpoot-wmp** [comment]
Adding duplicating: false was very helpful in resolving the error: 'missing FROM-clause entry for table'.
	const query = {
    where: {
        facility_type: 'SHARED_OFFICE',
        owner_id: ownerId
    },
    attributes: [
        'id', 'facility_type', 'customer_id', 'business_name', 'contact_name', 'contact_email',
        'area_or_seats', 'rental_start_date', 'rental_end_date', 'revenue', 'agent_contact',
        [Sequelize.col('shared_office.facility_name'), 'facility_name'],
        [Sequelize.fn('jsonb_extract_path_text', Sequelize.col('shared_office->location_details.address'), 'city_name'), 'city_name']
    ],
    include: [
        {
            model: SharedOffice.model,
            as: 'shared_office',
            attributes: [],
            include: [
                {
                    model: LocationDetails.model,
                    as: 'location_details',
                    attributes: [],
                    duplicating: false
                },
            ],
        },
    ],
    raw: true,
    limit: pageSize,
    offset: offset
}

**Comment by notAxion** [comment]
for my case adding `separate: true` fixed the problem
NOTE: this only works on include model which has a relation of hasMany
you will find the docs in
https://sequelize.org/docs/v6/advanced-association-concepts/eager-loading/#ordering-eager-loaded-associations
and
https://sequelize.org/api/v6/class/src/model.js~model#static-method-findAll
