### ISSUE TITLE
Including models inside through object throws an error.

### ISSUE THREAD

**Issue by VIMGAS** [sequelize/sequelize#9516]
## What are you doing?
Including a model in a through query is throwing a "cannot read as of undefined" error.

User model:
```js
  var User = sequelize.define(
    'User',
    {
      id: {
        primaryKey: true,
        type: DataTypes.UUID,
        defaultValue: DataTypes.UUIDV4
      },
      email: DataTypes.STRING,
      password: DataTypes.TEXT,
      firstName: DataTypes.STRING,
      lastName: DataTypes.STRING,
      blocked: DataTypes.BOOLEAN,
      deleted: DataTypes.BOOLEAN,
      deletedAt: DataTypes.DATE
    },
    {
      tableName: 'users',
      defaultScope: { where: { deleted: false } }
    }
  );
  User.associate = function(models) {
    User.belongsTo(models.AccessLevel, {
      as: 'level',
      foreignKey: 'levelId'
    });

    User.hasMany(models.Account, {
      as: 'ownedAccounts',
      foreignKey: 'userId'
    });

    User.hasMany(models.Account, {
      as: 'contactOf',
      foreignKey: 'contactId'
    });

    User.hasMany(models.Token, {
      as: 'tokens',
      foreignKey: 'userId'
    });

    User.hasMany(models.Group, {
      as: 'groups',
      foreignKey: 'userId'
    });

    User.belongsToMany(models.Company, {
      as: 'companies',
      foreignKey: 'userId',
      otherKey: 'companyId',
      through: models.UserCompaniesPermissionPackagesJoin
    });

    User.belongsToMany(models.PermissionPackage, {
      as: 'companyPermissions',
      foreignKey: 'userId',
      otherKey: 'permissionPackageId',
      through: models.UserCompaniesPermissionPackagesJoin
    });

    User.belongsToMany(models.PermissionPackage, {
      as: 'accountPermissions',
      foreignKey: 'userId',
      otherKey: 'permissionPackageId',
      through: models.UserAccountsPermissionPackagesJoin
    });

    User.belongsToMany(models.Account, {
      as: 'accounts',
      targetKey: 'accountId',
      foreignKey: 'userId',
      through: models.UserAccountsPermissionPackagesJoin
    });

    User.hasMany(models.PermissionPackage, {
      as: 'permissionPackages',
      foreignKey: 'userId'
    });

    User.hasMany(models.PermissionPackage.scope('account'), {
      as: 'accountPermissionPackages',
      foreignKey: 'userId'
    });

    User.hasMany(models.PermissionPackage.scope('company'), {
      as: 'companyPermissionPackages',
      foreignKey: 'userId'
    });
  };
```

Company model:
```js
  var Company = sequelize.define(
    'Company',
    {
      id: {
        primaryKey: true,
        type: DataTypes.UUID,
        defaultValue: DataTypes.UUIDV4
      },
      cnpj: DataTypes.CHAR(14),
      razaoSocial: DataTypes.STRING,
      nomeFantasia: DataTypes.STRING,
      estado: DataTypes.CHAR(2),
      accountId: DataTypes.UUID,
      deleted: DataTypes.BOOLEAN,
      deletedAt: DataTypes.DATE
    },
    {
      tableName: 'companies',
      defaultScope: { where: { deleted: false } }
    }
  );
  Company.associate = function(models) {
    Company.belongsTo(models.Account, {
      as: 'account',
      foreignKey: 'accountId'
    });

    Company.hasOne(models.DashboardLink, {
      as: 'dashboard',
      foreignKey: 'companyId'
    });

    Company.belongsToMany(models.Group, {
      as: 'groups',
      through: models.GroupCompaniesJoin,
      foreignKey: 'companyId',
      targetKey: 'groupId'
    });

    Company.belongsToMany(models.User, {
      as: 'associatedUsers',
      foreignKey: 'companyId',
      otherKey: 'userId',
      through: models.UserCompaniesPermissionPackagesJoin
    });
  };
```

PermissionPackage model:
```js
  var PermissionPackage = sequelize.define(
    'PermissionPackage',
    {
      id: {
        primaryKey: true,
        type: DataTypes.UUID,
        defaultValue: DataTypes.UUIDV4
      },
      userId: DataTypes.UUID,
      label: DataTypes.STRING,
      description: DataTypes.STRING,
      account: DataTypes.BOOLEAN,
      deleted: DataTypes.BOOLEAN,
      deletedAt: DataTypes.DATE
    },
    {
      tableName: 'permission_packages',
      defaultScope: { where: { deleted: false } },
      scopes: {
        account: { where: { account: true } },
        company: {
          where: { account: false }
        }
      }
    }
  );
  PermissionPackage.associate = function(models) {
    PermissionPackage.belongsToMany(models.Permission, {
      as: 'permissions',
      through: models.PermissionPackagePermissionsJoin,
      foreignKey: 'permissionPackageId',
      otherKey: 'permissionId'
    });

    PermissionPackage.belongsTo(models.User, {
      as: 'creator',
      foreignKey: 'userId'
    });

    PermissionPackage.belongsToMany(models.Company, {
      as: 'associatedCompanies',
      foreignKey: 'permissionPackageId',
      otherKey: 'companyId',
      through: models.UserCompaniesPermissionPackagesJoin
    });

    PermissionPackage.belongsToMany(models.User, {
      as: 'associatedUsers',
      foreignKey: 'permissionPackageId',
      otherKey: 'userId',
      through: models.UserCompaniesPermissionPackagesJoin
    });
  };
```

UserCompaniesPermissionPackagesJoin model:
```js
  var UserCompaniesPermissionPackagesJoin = sequelize.define(
    'UserCompaniesPermissionPackagesJoin',
    {
      id: {
        primaryKey: true,
        type: DataTypes.UUID,
        defaultValue: DataTypes.UUIDV4
      },
      accountId: DataTypes.UUID,
      userId: DataTypes.UUID,
      companyId: DataTypes.UUID,
      permissionPackageId: DataTypes.UUID,
      deleted: DataTypes.BOOLEAN,
      deletedAt: DataTypes.DATE
    },
    {
      tableName: 'user_companies_permission_packages_join',
      defaultScope: { where: { deleted: false } }
    }
  );
  UserCompaniesPermissionPackagesJoin.associate = function(models) {
    UserCompaniesPermissionPackagesJoin.belongsTo(models.Account, {
      as: 'account',
      foreignKey: 'accountId'
    });

    UserCompaniesPermissionPackagesJoin.belongsTo(models.User, {
      as: 'user',
      foreignKey: 'userId'
    });

    UserCompaniesPermissionPackagesJoin.belongsTo(models.Company, {
      as: 'company',
      foreignKey: 'companyId'
    });

    UserCompaniesPermissionPackagesJoin.belongsTo(models.PermissionPackage, {
      as: 'permissionPackage',
      foreignKey: 'permissionPackageId'
    });
  };
```

Query Building:
```js
User.findAll({
  attributes: ['id', 'email'],
  include: [
    {
      model: Models.Company,
      as: 'companies',
      attributes: ['id', 'cnpj', 'razaoSocial'],
      required: false,
      through: {
        attributes: [],
        include: [
          {
            model: Models.PermissionPackage,
            as: 'permissionPackage'
          }
        ]
      }
    }
  ]
})
```

## What do you expect to happen?

I expect the PermissionPackage model would be included in the response.

## What is actually happening?
An error.

Sequelize Executed Query:
```sql
SELECT `User`.`id`, `User`.`email`, `companies`.`id` AS `companies.id`, `companies`.`cnpj` AS `companies.cnpj`, `companies`.`razaoSocial` AS
`companies.razaoSocial`, `companies->UserCompaniesPermissionPackagesJoin`.`id` AS `companies.UserCompaniesPermissionPackagesJoin.id`, `companies->UserCompaniesPermissionPackagesJoin`.`accountId` AS `companies.UserCompaniesPermissionPackagesJoin.accountId`, `companies->UserCompaniesPermissionPackagesJoin`.`userId` AS `companies.UserCompaniesPermissionPackagesJoin.userId`, `companies->UserCompaniesPermissionPackagesJoin`.`companyId` AS `companies.UserCompaniesPermissionPackagesJoin.companyId`, `companies->UserCompaniesPermissionPackagesJoin`.`permissionPackageId` AS `companies.UserCompaniesPermissionPackagesJoin.permissionPackageId`, `companies->UserCompaniesPermissionPackagesJoin`.`deleted` AS `companies.UserCompaniesPermissionPackagesJoin.deleted`, `companies->UserCompaniesPermissionPackagesJoin`.`deletedAt` AS `companies.UserCompaniesPermissionPackagesJoin.deletedAt`, `companies->UserCompaniesPermissionPackagesJoin`.`createdAt` AS `companies.UserCompaniesPermissionPackagesJoin.createdAt`, `companies->UserCompaniesPermissionPackagesJoin`.`updatedAt` AS `companies.UserCompaniesPermissionPackagesJoin.updatedAt` FROM `users` AS `User` LEFT OUTER JOIN ( `user_companies_permission_packages_join` AS `companies->UserCompaniesPermissionPackagesJoin` INNER JOIN `companies` AS `companies` ON `companies`.`id` = `companies->UserCompaniesPermissionPackagesJoin`.`companyId`) ON `User`.`id` = `companies->UserCompaniesPermissionPackagesJoin`.`userId` AND `companies`.`deleted` = false WHERE `User`.`deleted` = false;
```

Error:
```
Unhandled rejection TypeError: Cannot read property 'as' of undefined
    at Model._findSeparate.results.reduce (c:\dev\projects\github\spendfy-backend\node_modules\sequelize\lib\model.js:1658:63)
    at Array.reduce (<anonymous>)
    at Promise.map.include (c:\dev\projects\github\spendfy-backend\node_modules\sequelize\lib\model.js:1657:19)
    at tryCatcher (c:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (c:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (c:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\promise_array.js:114:31)
    at MappingPromiseArray.init (c:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (c:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\map.js:30:10)
    at Async._drainQueue (c:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (c:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (c:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
```

__Dialect:__ mysql
__Dialect version:__ 5.7
__Database version:__ 5.7
__Sequelize version:__ 4.37.6

**Comment by sushantdhiman** [comment]
Can be fixed by passing `association` in `include` rather than `model / as` combination

**Comment by VIMGAS** [comment]
@sushantdhiman It didn't.

The used query:
```js
User.findAll({
  attributes: ['id', 'email'],
  include: [
    {
      model: Models.Company,
      as: 'companies',
      attributes: ['id', 'cnpj', 'razaoSocial'],
      required: false,
      through: {
        attributes: [],
        include: [
          {
            association: 'permissionPackage'
          }
        ]
      }
    }
  ]
})
```

The error stated is this:
```
Unhandled rejection TypeError: Cannot read property 'options' of undefined
    at Function._paranoidClause (C:\dev\projects\github\spendfy-backend\node_modules\sequelize\lib\model.js:72:16)
    at Function._paranoidClause (C:\dev\projects\github\spendfy-backend\node_modules\sequelize\lib\model.js:60:14)
    at Function._paranoidClause (C:\dev\projects\github\spendfy-backend\node_modules\sequelize\lib\model.js:60:14)
    at Function._paranoidClause (C:\dev\projects\github\spendfy-backend\node_modules\sequelize\lib\model.js:60:14)
    at Promise.try.then.then (C:\dev\projects\github\spendfy-backend\node_modules\sequelize\lib\model.js:1596:22)
    at tryCatcher (C:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
```
Also tried query
```js
User.findAll({
  attributes: ['id', 'email'],
  include: [
    {
      model: Models.Company,
      as: 'companies',
      attributes: ['id', 'cnpj', 'razaoSocial'],
      required: false,
      through: {
        attributes: [],
        include: ['permissionPackage']
      }
    }
  ]
})
```

The error:
```
Unhandled rejection TypeError: Cannot read property 'options' of undefined
    at Function._paranoidClause (C:\dev\projects\github\spendfy-backend\node_modules\sequelize\lib\model.js:72:16)
    at Function._paranoidClause (C:\dev\projects\github\spendfy-backend\node_modules\sequelize\lib\model.js:60:14)
    at Function._paranoidClause (C:\dev\projects\github\spendfy-backend\node_modules\sequelize\lib\model.js:60:14)
    at Function._paranoidClause (C:\dev\projects\github\spendfy-backend\node_modules\sequelize\lib\model.js:60:14)
    at Promise.try.then.then (C:\dev\projects\github\spendfy-backend\node_modules\sequelize\lib\model.js:1596:22)
    at tryCatcher (C:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
```

**Comment by sushantdhiman** [comment]
I meant `association` object, not the name of association @VIMGAS

**Comment by VIMGAS** [comment]
@sushantdhiman What is the association object? Usind model / as or association name is the only way I know of to include in query.

**Comment by sushantdhiman** [comment]
@VIMGAS when you do any kind of association it returns an association object, like

```js
const UserProjects = User.hasMany(Projects);
```

They are also available under `Model.associations`, with them you don't need to pass alias or model, just pass this object and Sequelize will include proper model automatically.

To manage these sort of associations in project, you can assign them to your model

```js
// user.js
const User = sequelize.define('user', { ... });

User.associate = function (models) {
   User.Projects = User.hasMany(models.Project);
}

// project.js
const Project = sequelize.define('project', { ... });

Project.associate = function (models) {
   Project.Owner = models.Project.belongsTo(models.User);
}

// some where in business logic

Project.findAll({
   include: [Project.Owner]
})
```

**Comment by LeandroDoldan** [comment]
@sunshinewyin do you think that `through` properties will be able to handle `include` properties eventually? It'd be really useful to query through the join tables as you want. For example, if you don't want to retrieve from the database every single association, but the ones you established in a scope.

**Comment by erikaperugachi** [comment]
> @sushantdhiman It didn't.
> 
> The used query:
> 
> ```js
> User.findAll({
>   attributes: ['id', 'email'],
>   include: [
>     {
>       model: Models.Company,
>       as: 'companies',
>       attributes: ['id', 'cnpj', 'razaoSocial'],
>       required: false,
>       through: {
>         attributes: [],
>         include: [
>           {
>             association: 'permissionPackage'
>           }
>         ]
>       }
>     }
>   ]
> })
> ```
> 
> The error stated is this:
> 
> ```
> Unhandled rejection TypeError: Cannot read property 'options' of undefined
>     at Function._paranoidClause (C:\dev\projects\github\spendfy-backend\node_modules\sequelize\lib\model.js:72:16)
>     at Function._paranoidClause (C:\dev\projects\github\spendfy-backend\node_modules\sequelize\lib\model.js:60:14)
>     at Function._paranoidClause (C:\dev\projects\github\spendfy-backend\node_modules\sequelize\lib\model.js:60:14)
>     at Function._paranoidClause (C:\dev\projects\github\spendfy-backend\node_modules\sequelize\lib\model.js:60:14)
>     at Promise.try.then.then (C:\dev\projects\github\spendfy-backend\node_modules\sequelize\lib\model.js:1596:22)
>     at tryCatcher (C:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\util.js:16:23)
>     at Promise._settlePromiseFromHandler (C:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\promise.js:512:31)
>     at Promise._settlePromise (C:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\promise.js:569:18)
>     at Promise._settlePromise0 (C:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\promise.js:614:10)
>     at Promise._settlePromises (C:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\promise.js:693:18)
>     at Async._drainQueue (C:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\async.js:133:16)
>     at Async._drainQueues (C:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\async.js:143:10)
>     at Immediate.Async.drainQueues (C:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\async.js:17:14)
>     at runCallback (timers.js:794:20)
>     at tryOnImmediate (timers.js:752:5)
>     at processImmediate [as _immediateCallback] (timers.js:729:5)
> ```
> 
> Also tried query
> 
> ```js
> User.findAll({
>   attributes: ['id', 'email'],
>   include: [
>     {
>       model: Models.Company,
>       as: 'companies',
>       attributes: ['id', 'cnpj', 'razaoSocial'],
>       required: false,
>       through: {
>         attributes: [],
>         include: ['permissionPackage']
>       }
>     }
>   ]
> })
> ```
> 
> The error:
> 
> ```
> Unhandled rejection TypeError: Cannot read property 'options' of undefined
>     at Function._paranoidClause (C:\dev\projects\github\spendfy-backend\node_modules\sequelize\lib\model.js:72:16)
>     at Function._paranoidClause (C:\dev\projects\github\spendfy-backend\node_modules\sequelize\lib\model.js:60:14)
>     at Function._paranoidClause (C:\dev\projects\github\spendfy-backend\node_modules\sequelize\lib\model.js:60:14)
>     at Function._paranoidClause (C:\dev\projects\github\spendfy-backend\node_modules\sequelize\lib\model.js:60:14)
>     at Promise.try.then.then (C:\dev\projects\github\spendfy-backend\node_modules\sequelize\lib\model.js:1596:22)
>     at tryCatcher (C:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\util.js:16:23)
>     at Promise._settlePromiseFromHandler (C:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\promise.js:512:31)
>     at Promise._settlePromise (C:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\promise.js:569:18)
>     at Promise._settlePromise0 (C:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\promise.js:614:10)
>     at Promise._settlePromises (C:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\promise.js:693:18)
>     at Async._drainQueue (C:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\async.js:133:16)
>     at Async._drainQueues (C:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\async.js:143:10)
>     at Immediate.Async.drainQueues (C:\dev\projects\github\spendfy-backend\node_modules\bluebird\js\release\async.js:17:14)
>     at runCallback (timers.js:794:20)
>     at tryOnImmediate (timers.js:752:5)
>     at processImmediate [as _immediateCallback] (timers.js:729:5)
> ```

I know the reason of this fix... maybe you are call any transaction where sequelize const is called twice in different files. This happens to me

**Comment by erfanio** [comment]
Is there a work around this issue until it gets fixed? @sushantdhiman suggested using the associations object instead of model/as but that still yields the same error.
