### ISSUE TITLE
Encoding not recognized: 'cesu8' (searched as: 'cesu8')

### ISSUE THREAD

**Issue by MrTreasure** [sequelize/sequelize#9526]
## What are you doing?

I followed the get start. The error happends（bad English）

```js
const sequelize = new Sequelize(config.database, config.username, config.password, {
  dialect: 'mysql',
  define: {
    underscored: false,
    freezeTableName: false,
    // syncOnAssociation: true,
    charset: 'utf8',
    timestamps: true,
  },
  dialectOptions: {
    collate: 'utf8_general_ci'
  }
})
const USER = sequelize.define('users', {
  id: { type: Sequelize.MEDIUMINT, primaryKey: true },
  user_id: Sequelize.STRING,
  last_active: Sequelize.DATE
})
```
```js
// test code
describe('Add user', async () => {
  const result = await USER.create({
    user_id: 1,
    last_active: new Date()
  })
  expect(result).not.toBeNull()
})
```

## What do you expect to happen?
I want create a instance and store it. But test not passed

## What is actually happening?
```bash
E:\Node\xiaoai\node_modules\iconv-lite\lib\index.js:106
                throw new Error("Encoding not recognized: '" + encoding + "' (searched as: '"+enc+"')");
                ^
Error: Encoding not recognized: 'cesu8' (searched as: 'cesu8')
    at Object.getCodec (E:\Node\xiaoai\node_modules\iconv-lite\lib\index.js:106:23)
    at Object.getDecoder (E:\Node\xiaoai\node_modules\iconv-lite\lib\index.js:122:23)
    at Object.<anonymous>.exports.decode (E:\Node\xiaoai\node_modules\mysql2\lib\parsers\string.js:9:23)
    at Packet.Object.<anonymous>.Packet.readNullTerminatedString (E:\Node\xiaoai\node_modules\mysql2\lib\packets\packet.js:385:23)
    at Function.Object.<anonymous>.Handshake.fromPacket (E:\Node\xiaoai\node_modules\mysql2\lib\packets\handshake.js:18:31)
    at ClientHandshake.Object.<anonymous>.ClientHandshake.handshakeInit (E:\Node\xiaoai\node_modules\mysql2\lib\commands\client_handshake.js:98:38)
    at ClientHandshake.Object.<anonymous>.Command.execute (E:\Node\xiaoai\node_modules\mysql2\lib\commands\command.js:40:20)
    at Connection.Object.<anonymous>.Connection.handlePacket (E:\Node\xiaoai\node_modules\mysql2\lib\connection.js:502:28)
    at PacketParser.onPacket (E:\Node\xiaoai\node_modules\mysql2\lib\connection.js:81:16)
```

__Dialect:__ mysql 
__Dialect version: "mysql2": "^1.5.3",
__Database version: mysql5.7.6
__Sequelize version:"sequelize": "^4.37.10"
__Tested with latest release:__ No (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
I can't reproduce this issue and I am sure `iconv-lite` supports `cesu-8` https://github.com/ashtuchkin/iconv-lite/issues/102

Can you show me `npm ls` and try reinstalling depedencies

```js
const sequelize = require('./test/support').createSequelizeInstance({
  dialectOptions: {
    collate: 'utf8_general_ci'
  }
});

const User = sequelize.define('user', {
  id: {
    type: Sequelize.MEDIUMINT,
    primaryKey: true,
    autoIncrement: true
  },
  user_id: Sequelize.STRING,
  last_active: Sequelize.DATE
}, {
  charset: 'utf8'
});

sequelize
  .sync({ force: true })
  .then(() => User.create({
    user_id: 1,
    last_active: new Date()
  }))
  .then(user => {
    console.log(user.toJSON());
  });
```

```SQL
{ id: 1,
  user_id: 1,
  last_active: 2018-06-12T06:46:28.304Z,
  updatedAt: 2018-06-12T06:46:28.306Z,
  createdAt: 2018-06-12T06:46:28.306Z }
```

**Comment by MrTreasure** [comment]
after reinstall the dependencies. The error was resolved, tks for ur help.

**Comment by pgun9476** [comment]
you need only this;
`npm install --save tedious`

**Comment by shivani22-18** [comment]
Hi, I am performing unit testing with Jest framework for NodeJs serverless. I am facing this issue after running "npm test" command in nodejs.
Below are the versions I am using:
1) NodeJs: 14.x
2) serverless: 
    Framework Core: 3.2.1
    Plugin: 6.1.0
    SDK: 4.3.1
3) jest: ^26.6.0
4) mysql: ^2.18.1
5) mysql2: ^2.3.3
6) sequelize: ^6.17.0
Error: Encoding not recognized: 'cesu8' (searched as: 'cesu8')
    at Object.getCodec (C:\Users\SPATI101\Desktop\user-mgmt-ms\node_modules\iconv-lite\lib\index.js:104:23) 
    at Object.getDecoder (C:\Users\SPATI101\Desktop\user-mgmt-ms\node_modules\iconv-lite\lib\index.js:125:23)
    at Object.<anonymous>.exports.decode (C:\Users\SPATI101\Desktop\user-mgmt-ms\node_modules\mysql2\lib\parsers\string.js:10:25)
    at Packet.readNullTerminatedString (C:\Users\SPATI101\Desktop\user-mgmt-ms\node_modules\mysql2\lib\packets\packet.js:412:25)
    at Function.fromPacket (C:\Users\SPATI101\Desktop\user-mgmt-ms\node_modules\mysql2\lib\packets\handshake.js:62:33)
    at ClientHandshake.handshakeInit (C:\Users\SPATI101\Desktop\user-mgmt-ms\node_modules\mysql2\lib\commands\client_handshake.js:98:40)
    at ClientHandshake.execute (C:\Users\SPATI101\Desktop\user-mgmt-ms\node_modules\mysql2\lib\commands\command.js:45:22)
    at Connection.handlePacket (C:\Users\SPATI101\Desktop\user-mgmt-ms\node_modules\mysql2\lib\connection.js:456:32)
    at PacketParser.onPacket (C:\Users\SPATI101\Desktop\user-mgmt-ms\node_modules\mysql2\lib\connection.js:85:12)
    at PacketParser.executeStart (C:\Users\SPATI101\Desktop\user-mgmt-ms\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\Users\SPATI101\Desktop\user-mgmt-ms\node_modules\mysql2\lib\connection.js:92:25)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:302:12)
    at readableAddChunk (_stream_readable.js:278:9)
    at Socket.Readable.push (_stream_readable.js:217:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
npm ERR! Test failed.  See above for more details.
