### ISSUE TITLE
"Validation error: Validation isEmail on email failed" on version 4.38.0 upgrade

### ISSUE THREAD

**Issue by willguitaradmfar** [sequelize/sequelize#9582]
` email: {
      type: DataTypes.STRING(50),
      unique: true,
      allowNull: false,
      validate: {
        isEmail: true,
        notEmpty: false
      }
    }`

`err.stack
"SequelizeValidationError: Validation error: Validation isEmail on email failed
    at Promise.all.then (/home/will/git/jsstore/node_modules/sequelize/lib/instance-validator.js:77:15)
    at tryCatcher (/home/will/git/jsstore/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/will/git/jsstore/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/will/git/jsstore/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/will/git/jsstore/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/will/git/jsstore/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/will/git/jsstore/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/home/will/git/jsstore/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/home/will/git/jsstore/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/home/will/git/jsstore/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/home/will/git/jsstore/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/will/git/jsstore/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/will/git/jsstore/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/will/git/jsstore/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/will/git/jsstore/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)"`

**Comment by sushantdhiman** [comment]
Follow the issue template
