### ISSUE TITLE
Incorrect SQL in 'REFERENCES' statement in custom table schemas

### ISSUE THREAD

**Issue by TK95** [sequelize/sequelize#9614]
## What are you doing?

I'm trying to create two tables in non-public table schema. There is a simple relation between those tables. (Please see the code below in order to get more details)

```js
const Sequelize = require('sequelize')

const schema = 'hollywood'

const sequelize = new Sequelize('postgres', 'postgres', 'postgres', {
  host: 'localhost',
  dialect: 'postgres',

  pool: {
    max: 5,
    min: 0,
    acquire: 30000,
    idle: 10000
  },
  schema
})

const Team = sequelize.define('Team', {}, { schema })

const User = sequelize.define('User', {
  teamId: {
    type: Sequelize.INTEGER,
    allowNull: false,
    references: {
      model: 'Teams',
      key: 'id',
      schema
    },
    onUpdate: 'cascade',
    onDelete: 'cascade'
  }
}, { schema })

const run = async () => {
  try {
    await sequelize.sync({ schema })
  } catch (e) {
    console.log('Sync error', e)
  }
}

run()
```

## What do you expect to happen?
I'm expecting that two tables will be created in 'hollywood' schema. The column 'Users.teamId' will be referencing 'Team.id' column.

## What is actually happening?
An error is thrown. Attaching the full output.

```
Executing (default): CREATE TABLE IF NOT EXISTS "hollywood"."Teams" ("id"   SERIAL , "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt"TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a, pg_namespace s WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'Teams' AND s.oid = t.relnamespace AND s.nspname = 'hollywood' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
Executing (default): CREATE TABLE IF NOT EXISTS "hollywood"."Users" ("id"   SERIAL , "teamId" INTEGER NOT NULL REFERENCES "Teams" ("id") ON DELETE CASCADE ON UPDATE CASCADE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));
Sync error { SequelizeDatabaseError: relation "Teams" does not exist
    at Query.formatError (/Users/denis/Projects/atlassian/bitbucket-chats-integration/server/node_modules/sequelize/lib/dialects/postgres/query.js:367:16)
    at query.catch.err (/Users/denis/Projects/atlassian/bitbucket-chats-integration/server/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)
    at tryCatcher (/Users/denis/Projects/atlassian/bitbucket-chats-integration/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/denis/Projects/atlassian/bitbucket-chats-integration/server/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/denis/Projects/atlassian/bitbucket-chats-integration/server/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/denis/Projects/atlassian/bitbucket-chats-integration/server/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/denis/Projects/atlassian/bitbucket-chats-integration/server/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Users/denis/Projects/atlassian/bitbucket-chats-integration/server/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/denis/Projects/atlassian/bitbucket-chats-integration/server/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/denis/Projects/atlassian/bitbucket-chats-integration/server/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
  name: 'SequelizeDatabaseError',
  parent:
   { error: relation "Teams" does not exist
    at Connection.parseE (/Users/denis/Projects/atlassian/bitbucket-chats-integration/server/node_modules/pg/lib/connection.js:567:11)
    at Connection.parseMessage (/Users/denis/Projects/atlassian/bitbucket-chats-integration/server/node_modules/pg/lib/connection.js:391:17)
    at Socket.<anonymous> (/Users/denis/Projects/atlassian/bitbucket-chats-integration/server/node_modules/pg/lib/connection.js:129:22)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:280:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onread (net.js:638:20)
     name: 'error',
     length: 103,
     severity: 'ERROR',
     code: '42P01',
     detail: undefined,
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'namespace.c',
     line: '420',
     routine: 'RangeVarGetRelidExtended',
     sql: 'CREATE TABLE IF NOT EXISTS "hollywood"."Users" ("id"   SERIAL , "teamId" INTEGER NOT NULL REFERENCES "Teams" ("id") ON DELETE CASCADE ON UPDATE CASCADE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));' },
  original:
   { error: relation "Teams" does not exist
    at Connection.parseE (/Users/denis/Projects/atlassian/bitbucket-chats-integration/server/node_modules/pg/lib/connection.js:567:11)
    at Connection.parseMessage (/Users/denis/Projects/atlassian/bitbucket-chats-integration/server/node_modules/pg/lib/connection.js:391:17)
    at Socket.<anonymous> (/Users/denis/Projects/atlassian/bitbucket-chats-integration/server/node_modules/pg/lib/connection.js:129:22)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:280:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onread (net.js:638:20)
     name: 'error',
     length: 103,
     severity: 'ERROR',
     code: '42P01',
     detail: undefined,
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'namespace.c',
     line: '420',
     routine: 'RangeVarGetRelidExtended',
     sql: 'CREATE TABLE IF NOT EXISTS "hollywood"."Users" ("id"   SERIAL , "teamId" INTEGER NOT NULL REFERENCES "Teams" ("id") ON DELETE CASCADE ON UPDATE CASCADE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));' },
  sql: 'CREATE TABLE IF NOT EXISTS "hollywood"."Users" ("id"   SERIAL , "teamId" INTEGER NOT NULL REFERENCES "Teams" ("id") ON DELETE CASCADE ON UPDATE CASCADE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));' }
```

Please pay attention to generated SQL. Apparently, It's incorrect. 
```sql
CREATE TABLE IF NOT EXISTS "hollywood"."Users" (
"id"   SERIAL , 
"teamId" INTEGER NOT NULL REFERENCES "Teams" ("id") ON DELETE CASCADE ON UPDATE CASCADE, 
"createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, 
"updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id")
);
```

Here is the correct SQL which works fine in DataGrip: (The difference in **REFERENCES** statement.)
```sql
CREATE TABLE IF NOT EXISTS "hollywood"."Users" (
  "id"        SERIAL,
  "teamId"    INTEGER  NOT NULL REFERENCES "hollywood"."Teams" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY ("id")
);
```

I have tested the generated code by Sequelize in Data Grip console and got the same error (relation "Teams" does not exist).
I assume if you didn't specify schema names before relation name it will pointing to 'public' schema by default.

**__Dialect:__**  postgres
**__Dialect version:__**  Sorry, I don't understand what should I specify here. (Don't ignore my issue, please)
**__Database version:__** PostgreSQL 9.6.8 on x86_64-apple-darwin14.5.0, compiled by Apple LLVM version 7.0.0 (clang-700.1.76), 64-bit.
**__Sequelize version:__** 4.37.3.
**__Tested with latest release:__** No.

In case of any questions, please let me know.

**Comment by paulmowat** [comment]
I'll take a stab at a pull request for this one tomorrow.

**Comment by paulmowat** [comment]
I've had a look at this now. 

Instead of 
`
 references: {
      model: 'Teams',
      key: 'id',
      schema
    },
`
Change it to 
`
 references: {
      model: Team,
      key: 'id',
      schema
    },
`
From the code it looks like you need to specify the actual Team model object. If you specify just the model name it has no way to link back to the model object as each one is standalone. 

At the moment if a name is specified rather than a object it's just passing that name through without the schema. Even though your passing the schema this means it can't accurately get the tablename of that model, so even if I changed it to use the schema as well, it wouldn't be 100%.

As I'm new to looking at sequelize code, someone with more experience might have more to add or know something I don't :)

**Comment by mirkojotic** [comment]
@TK95 
Tried @paulmowat suggestion and it indeed solves the problem of schema not being specified in query.

Query that gets created:
```
Executing (default): CREATE TABLE IF NOT EXISTS "hollywood"."Users" ("id"   SERIAL , "teamId" INTEGER NOT NULL REFERENCES "hollywood"."Teams" ("id") ON DELETE CASCADE ON UPDATE CASCADE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));
```
 @sushantdhiman

**Comment by TK95** [comment]
@paulmowat , @mirkojotic, sorry guys but I still can't get the code working.

So, I changed the `references`  property
from:
```js
  references: {
      model: 'Teams',
      key: 'id',
      schema
    }
```
to:
```js
  references: {
      model: Team,
      key: 'id',
      schema
    },
```

And I'm still getting the same error when running the code. 

@mirkojotic  Could you please elaborate how did you make this work? 

Also, this time I did tests with Sequelize  4.38.0,  and  did some quick debugging [here](https://github.com/sequelize/sequelize/blob/master/lib/dialects/postgres/query-generator.js#L526):
```js
...
console.log('attribute.references', attribute.references);
const referencesTable = this.quoteTable(attribute.references.model);
console.log('referencesTable', referencesTable);
...
```

 Have the following output in console:
```js
attribute.references { model: 'Teams', key: 'id', schema: 'hollywood' }
referencesTable "Teams"
```
As you can see `attribute.references` has been transformed to the same value what I specified in the first post.


Any ideas?

**Comment by paulmowat** [comment]
The issue is this code in model.js

In V4 it is still using the model https://github.com/sequelize/sequelize/blob/2c3a6e715d8684a489daac75ce588de3ef807689/lib/model.js#L808

But in the latest version v5 it has been changed to get the table name. Which returns the values required i.e. schema, tableName etc
https://github.com/sequelize/sequelize/blob/fea6db4a07d3a2ac39895afea03941582372ea8d/lib/model.js#L934

That's why it's just returning the model name no matter how you do it.  You'll need to upgrade to the V5 or back port the change into V4.

**Comment by mirkojotic** [comment]
@TK95 I just changed `'Teams'` to `Team` in `references.model` property. Is it possible for you to upgrade to v5 as per @paulmowat suggestion?

**Comment by TK95** [comment]
@paulmowat , @mirkojotic , thanks guys. After updating to v5 I don't see the bug.

**Comment by paulmowat** [comment]
@TK95 - Good stuff, can you please close the log if happy :)
