### ISSUE TITLE
The "url" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by GitStonic** [sequelize/sequelize#9622]
I'm trying to use a PostgreSQL URI to connect but i'm getting an error, 
```js
[1] url.js:150
[1]     throw new ERR_INVALID_ARG_TYPE('url', 'string', url);
[1]     ^
[1]
[1] TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined
[1]     at Url.parse (url.js:150:11)
[1]     at Object.urlParse [as parse] (url.js:144:13)
[1]     at new Sequelize (C:\Users\kidst.DESKTOP-47J20UJ\Documents\Projects\stonic-web-boilerplate\node_modules\sequelize\lib\sequelize.js:115:28)
[1]     at Object.<anonymous> (C:\Users\kidst.DESKTOP-47J20UJ\Documents\Projects\stonic-web-boilerplate\server\db\index.js:6:19)
[1]     at Module._compile (internal/modules/cjs/loader.js:702:30)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
[1]     at Module.load (internal/modules/cjs/loader.js:612:32)
[1]     at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:543:3)
[1]     at Module.require (internal/modules/cjs/loader.js:650:17)
[1]     at require (internal/modules/cjs/helpers.js:20:18)
[1]     at Object.<anonymous> (C:\Users\kidst.DESKTOP-47J20UJ\Documents\Projects\stonic-web-boilerplate\server\db\models\example.js:1:96)
[1]     at Module._compile (internal/modules/cjs/loader.js:702:30)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
[1]     at Module.load (internal/modules/cjs/loader.js:612:32)
[1]     at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:543:3)
[1]     at Module.require (internal/modules/cjs/loader.js:650:17)
[1]     at require (internal/modules/cjs/helpers.js:20:18)
[1]     at Object.<anonymous> (C:\Users\kidst.DESKTOP-47J20UJ\Documents\Projects\stonic-web-boilerplate\server\routes\index.js:2:22)
[1]     at Module._compile (internal/modules/cjs/loader.js:702:30)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
```
And my code is looking something like this, 
```js
const Sequelize = require('sequelize');

// Connecting by URI.
const connString = process.env.DB_URI;

const sequelize = new Sequelize(connString, {
	dialect: 'postgres'
});

sequelize
	.authenticate()
	.then(() => console.log('Connection has been established successfully.'))
	.catch(err => console.log(err));

module.exports = { sequelize, Sequelize };
```
The constant `connString` is returning a string of my URI... I'm wondering why it says it says that the URL parameter must be string which it is, says that it's not. I'm most likely doing something wrong but I don't see what though. So I just assume it's probably a bug. I'm not too sure tho...

**Comment by GitStonic** [comment]
Wait, never mind. I forgot to load my dotenv file that's why... sorry 😅 😅 😅 😅 😅

**Comment by freirart** [comment]
Hi, man! I didn't understand how did you get over this situation. I'm facing the same problem. Could you please enlighten my mind? Thanks!

**Comment by omryzw** [comment]
i have the same problem too

**Comment by freirart** [comment]
@omryzw I solved by doing this: 

In the `app.js`(main file) require the `dotenv` module as soon as possible.

```
require('dotenv').config()
```

To use .env files, you __must__ download the `dotenv` package, otherwise they won't work.
Install it using your favorite package manager.

```
npm install dotenv (or) yarn add dotenv
```

**Comment by whoastonic** [comment]
@freirart 
> Wait, never mind. I forgot to load my dotenv file that's why... sorry 😅 😅 😅 😅 😅
I've mentioned how I got over it?.. but yes I did the same mistake...

**Comment by josefo727** [comment]
normalmente esto suele suceder cuando no tenemos definido un .env
