### ISSUE TITLE
not support Unicode in string

### ISSUE THREAD

**Issue by LeePanda** [sequelize/sequelize#9630]
## When we give a Unicode contained string value in the query,it would be broken like this:
```js
{ error: invalid message format
       at Connection.parseE (/Users/lichen/apkpure/server/libs/nodejs-modules/node_modules/pg/lib/connection.js:567:11)
       at Connection.parseMessage (/Users/lichen/apkpure/server/libs/nodejs-modules/node_modules/pg/lib/connection.js:391:17)
       at Socket.<anonymous> (/Users/lichen/apkpure/server/libs/nodejs-modules/node_modules/pg/lib/connection.js:129:22)
       at emitOne (events.js:96:13)
       at Socket.emit (events.js:188:7)
       at readableAddChunk (_stream_readable.js:176:18)
       at Socket.Readable.push (_stream_readable.js:134:10)
       at TCP.onread (net.js:551:20)
     name: 'error',
     length: 81,
     severity: 'ERROR',
     code: '08P01',
     detail: undefined,
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: undefined,
     table: undefined,
     column: undefined,
     dataType: undefined,
     constraint: undefined,
     file: 'pqformat.c',
     line: '682',
     routine: 'pq_getmsgend',
     sql: 'SELECT "id", "name", "type", "language", "info", "create_date" FROM "apk_tag" AS "apk_tag" WHERE "apk_tag"."name" = \'\u0000\u0000\' LIMIT 1;' }
```
##here is my query

```js
tagModel.findOne({
        where: {
                name: '\u0000\u0000'
         },
         raw: true
}).then(function (ret) {
})
```
__Dialect:postgres 
__Sequelize version:4.0.0-2

**Comment by sushantdhiman** [comment]
This was fixed if I recall correctly, can you please test with latest stable version?

**Comment by LeePanda** [comment]
@sushantdhiman ok,thks
