### ISSUE TITLE
Test passing with jest when it is not supposed to

### ISSUE THREAD

**Issue by IvanMiIosevic** [sequelize/sequelize#9638]
## What are you doing?
Hi, i'm trying to write tests for a project with jest.

```js
test('has properties', () => {
  sequelize.models.zipcode.create()
    .then((createdZipcode) => {
      expect(createdZipcode.dataValues).not.toBeNull();
    })
    .catch((err) => {
      expect(err.errors).toBeNull();
      expect(err).toBeNull();
    });
});
```
The test always goes to catch and prints this : 
```
console.log test/sequelize.test.js:27
    { SequelizeValidationError: notNull Violation: zipcode.name cannot be null
        at Promise.all.then (/Applications/MAMP/htdocs/kist-api/node_modules/sequelize/lib/instance-validator.js:77:15)
        at tryCatcher (/Applications/MAMP/htdocs/kist-api/node_modules/bluebird/js/release/util.js:16:23)
        at Promise._settlePromiseFromHandler (/Applications/MAMP/htdocs/kist-api/node_modules/bluebird/js/release/promise.js:512:31)
        at Promise._settlePromise (/Applications/MAMP/htdocs/kist-api/node_modules/bluebird/js/release/promise.js:569:18)
        at Promise._settlePromise0 (/Applications/MAMP/htdocs/kist-api/node_modules/bluebird/js/release/promise.js:614:10)
        at Promise._settlePromises (/Applications/MAMP/htdocs/kist-api/node_modules/bluebird/js/release/promise.js:693:18)
        at Promise._fulfill (/Applications/MAMP/htdocs/kist-api/node_modules/bluebird/js/release/promise.js:638:18)
        at PromiseArray._resolve (/Applications/MAMP/htdocs/kist-api/node_modules/bluebird/js/release/promise_array.js:126:19)
        at PromiseArray._promiseFulfilled (/Applications/MAMP/htdocs/kist-api/node_modules/bluebird/js/release/promise_array.js:144:14)
        at Promise._settlePromise (/Applications/MAMP/htdocs/kist-api/node_modules/bluebird/js/release/promise.js:574:26)
        at Promise._settlePromise0 (/Applications/MAMP/htdocs/kist-api/node_modules/bluebird/js/release/promise.js:614:10)
        at Promise._settlePromises (/Applications/MAMP/htdocs/kist-api/node_modules/bluebird/js/release/promise.js:693:18)
        at Async.Object.<anonymous>.Async._drainQueue (/Applications/MAMP/htdocs/kist-api/node_modules/bluebird/js/release/async.js:133:16)
        at Async.Object.<anonymous>.Async._drainQueues (/Applications/MAMP/htdocs/kist-api/node_modules/bluebird/js/release/async.js:143:10)
        at Immediate.Async.drainQueues [as _onImmediate] (/Applications/MAMP/htdocs/kist-api/node_modules/bluebird/js/release/async.js:17:14)
        at runCallback (timers.js:696:18)
        at tryOnImmediate (timers.js:667:5)
        at processImmediate (timers.js:649:5)
      name: 'SequelizeValidationError',
      errors:
       [ ValidationErrorItem {
           message: 'zipcode.name cannot be null',
           type: 'notNull Violation',
           path: 'name',
           value: null,
           origin: 'CORE',
           instance: [zipcode],
           validatorKey: 'is_null',
           validatorName: null,
           validatorArgs: [] } ] }
```

## What do you expect to happen?
I expect the test to NOT pass because err is not null and err.errors is not null too.

## What is actually happening?
the test is passing every time

```
 PASS  test/sequelize.test.js
  ✓ Is sequelize define ? (3ms)
  ✓ sqsdq (1ms)
  ✓ Is this the test database ?
  ✓ has properties (3ms)
  ✓ empty test
Test Suites: 1 passed, 1 total
Tests:       5 passed, 5 total
Snapshots:   0 total
Time:        2.202s
Ran all test suites.
```
__Dialect:__  postgres
__Dialect version:__ (don't know how to check so i'll update later)
__Database version:__ (don't know how to check so i'll update later)
__Sequelize version:__ sequelize@4.38.0
__Tested with latest release:__ Yes , i just updated sequelize with npm and tried again but still the same issue

**Comment by sushantdhiman** [comment]
`return`
