### ISSUE TITLE
MS SQL Query Issue on every Query

### ISSUE THREAD

**Issue by deepaksharma2491** [sequelize/sequelize#9639]
Unhandled rejection TypeError: Catch filter must inherit from Error or be a simple predicate function

    See http://goo.gl/o84o68

    at Promise.caught.Promise.catch ({Project_Path}/node_modules/bluebird/js/main/promise.js:89:21)
    at ConnectionManager.releaseConnection ({Project_Path}/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:290:13)
    at query.run.finally ({Project_Path}/node_modules/sequelize/lib/sequelize.js:565:43)
    at Object.finallyHandler ({Project_Path}/node_modules/bluebird/js/main/finally.js:39:23)
    at bound (domain.js:280:14)
    at Object.runBound (domain.js:293:12)
    at Object.tryCatcher ({Project_Path}/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler ({Project_Path}/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt ({Project_Path}/node_modules/bluebird/js/main/promise.js:584:18)
    at Async._drainQueue ({Project_Path}/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues ({Project_Path}/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues ({Project_Path}/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396
