### ISSUE TITLE
Using limit and offset on findAll generates a syntax error

### ISSUE THREAD

**Issue by ljmerza** [sequelize/sequelize#9807]
I'm using sequelize-typescript but this seems to be a sequelize error.

"sequelize": "^4.37.4",
"sequelize-typescript": "^0.6.3",

DIALECT=mysql
mariadb 10.3 windows 64x

Trying to call this function:
```
export async function getData({limit=50, offset=0}){
	return await Data.findAll({limit, offset});
}
```

this works just fine with the defaults but if I try to pass in a offset=4 then I get a syntax error:

```
Executing (default): SELECT `id`, `log` FROM `Data` AS `Data` LIMIT '4', 50;

  SequelizeDatabaseError: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''4', 50' at line 1
      at Query.formatError (C:\Users\Leonardo\Documents\movie-website\node_modules\sequelize\lib\dialects\mysql\query.js:247:16)
      at Query.handler [as onResult] (C:\Users\Leonardo\Documents\movie-website\node_modules\sequelize\lib\dialects\mysql\query.js:68:23)
      at Query.Command.execute (C:\Users\Leonardo\Documents\movie-website\node_modules\mysql2\lib\commands\command.js:30:12)
      at Connection.handlePacket (C:\Users\Leonardo\Documents\movie-website\node_modules\mysql2\lib\connection.js:502:28)
      at PacketParser.onPacket (C:\Users\Leonardo\Documents\movie-website\node_modules\mysql2\lib\connection.js:81:16)
      at PacketParser.executeStart (C:\Users\Leonardo\Documents\movie-website\node_modules\mysql2\lib\packet_parser.js:77:14)
      at Socket.<anonymous> (C:\Users\Leonardo\Documents\movie-website\node_modules\mysql2\lib\connection.js:89:29)
      at Socket.emit (events.js:182:13)
      at addChunk (_stream_readable.js:283:12)
      at readableAddChunk (_stream_readable.js:264:11)
      at Socket.Readable.push (_stream_readable.js:219:10)
      at TCP.onread (net.js:635:20)

```

my internal dialect is set to mysql but it looks like the abstract addLimitAndOffset call is being made instead of the mysql version.

**Comment by ljmerza** [comment]
Looks like I was passing a string instead of a number. Using parseInt() made this work for anyone else running into this issue.

**Comment by nagpalkaran95** [comment]
@ljmerza you saved my day 😀
