### ISSUE TITLE
Model.create failing with returning: false for MSSQL

### ISSUE THREAD

**Issue by drdeath2609** [sequelize/sequelize#9823]
## What are you doing?

My Model
```js
   const Payment = sequelize.define('payments', {
      paymentId: {
        type: Sequelize.INTEGER,
        autoIncrement: true,
        allowNull: false,
        primaryKey: true
      },
      accessionNumber: {
        type: Sequelize.STRING,
        allowNull: false,
        references: {
          model: 'exams',
          key: 'accessionNumber'
        }
      },
      patientId: {
        type: Sequelize.STRING,
        allowNull: true,
        references: {
          model: 'patients',
          key: 'patientId'
        }
      },
      companyId: {
        type: Sequelize.INTEGER,
        allowNull: true,
        references: {
          model: 'insuranceCompanies',
          key: 'companyId'
        }
      },
      payerType: {
        type: Sequelize.ENUM('insurance', 'patient'),
        allowNull: false
      },
      amountPaid: {
        type: Sequelize['DOUBLE PRECISION'],
        allowNull: false
      },
      paymentMethod: {
        type: Sequelize.ENUM('EFT', 'CHECK', 'CREDIT_CARD', 'CASH'),
        allowNull: false
      },
      datePaid: {
        type: Sequelize.DATEONLY,
        allowNull: false
      },
      checkNumber: {
        type: Sequelize.INTEGER
      }
    });
```

**My Request**

```js
await PaymentModel.create({
    accessionNumber: 'A0001',
    patientId: '1',
    companyId: null,
    payerType: 'patient',
    amountPaid: 1018,
    paymentMethod: 'Cash',
    datePaid: '2012-12-31T00:00:00.000Z',
}, {
          returning: false,
          logging: true
});
```
_I'm setting the returning false because, I have trigger enabled on my payments table. Database throws following error_

```
The target table 'payments' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause
```

## What do you expect to happen?
_Expecting the command to execute properly and return nothing or the object provided as input._

## What is actually happening?
_On setting returning false, it is throws the following error_

```
{applicationPath}/node_modules/sequelize/lib/dialects/mssql/query.js:379
        id = id || results && results[0][this.getInsertIdField()];
                                        ^
TypeError: Cannot read property 'id' of undefined
    at Query.handleInsertQuery ({applicationPath}/node_modules/sequelize/lib/dialects/mssql/query.js:379:41)
    at Query.formatResults ({applicationPath}/node_modules/sequelize/lib/dialects/mssql/query.js:179:12)
    at Request.connection.lib.Request [as userCallback] ({applicationPath}/node_modules/sequelize/lib/dialects/mssql/query.js:109:26)
    at Request._this.callback ({applicationPath}/node_modules/tedious/lib/request.js:60:27)
    at Connection.endOfMessageMarkerReceived ({applicationPath}/node_modules/tedious/lib/connection.js:1922:20)
    at Connection.dispatchEvent ({applicationPath}/node_modules/tedious/lib/connection.js:1004:38)
    at Parser.<anonymous> ({applicationPath}/node_modules/tedious/lib/connection.js:805:18)
    at Parser.emit (events.js:180:13)
    at Parser.emit (domain.js:422:20)
    at Parser.<anonymous> ({applicationPath}/node_modules/tedious/lib/token/token-stream-parser.js:54:15)
    at Parser.emit (events.js:180:13)
    at Parser.emit (domain.js:422:20)
    at addChunk ({applicationPath}/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk ({applicationPath}/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at Parser.Readable.push ({applicationPath}/node_modules/readable-stream/lib/_stream_readable.js:245:10)
    at Parser.Transform.push ({applicationPath}/node_modules/readable-stream/lib/_stream_transform.js:148:32)
    at Parser.afterTransform ({applicationPath}/node_modules/readable-stream/lib/_stream_transform.js:91:10)
    at Parser._transform ({applicationPath}/node_modules/tedious/lib/token/stream-parser.js:69:9)
    at Parser.Transform._read ({applicationPath}/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Parser.Transform._write ({applicationPath}/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite ({applicationPath}/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer ({applicationPath}/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Parser.Writable.write ({applicationPath}/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Parser.addEndOfMessageMarker ({applicationPath}/node_modules/tedious/lib/token/token-stream-parser.js:80:26)
    at Connection.message ({applicationPath}/node_modules/tedious/lib/connection.js:1913:32)
    at Connection.dispatchEvent ({applicationPath}/node_modules/tedious/lib/connection.js:1004:38)
    at MessageIO.<anonymous> ({applicationPath}/node_modules/tedious/lib/connection.js:884:18)
    at MessageIO.emit (events.js:180:13)
    at MessageIO.emit (domain.js:422:20)
    at ReadablePacketStream.<anonymous> ({applicationPath}/node_modules/tedious/lib/message-io.js:104:16)
    at ReadablePacketStream.emit (events.js:180:13)
    at ReadablePacketStream.emit (domain.js:422:20)
    at addChunk ({applicationPath}/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk ({applicationPath}/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at ReadablePacketStream.Readable.push ({applicationPath}/node_modules/readable-stream/lib/_stream_readable.js:245:10)
    at ReadablePacketStream.Transform.push ({applicationPath}/node_modules/readable-stream/lib/_stream_transform.js:148:32)
    at ReadablePacketStream._transform ({applicationPath}/node_modules/tedious/lib/message-io.js:71:16)
    at ReadablePacketStream.Transform._read ({applicationPath}/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at ReadablePacketStream.Transform._write ({applicationPath}/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite ({applicationPath}/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer ({applicationPath}/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at ReadablePacketStream.Writable.write ({applicationPath}/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at TLSSocket.ondata (_stream_readable.js:651:20)
    at TLSSocket.emit (events.js:180:13)
    at TLSSocket.emit (domain.js:422:20)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
    at TLSSocket.Readable.push (_stream_readable.js:218:10)
    at TLSWrap.onread (net.js:581:20)
    at DuplexSocket.ondata (internal/wrap_js_stream.js:62:22)
    at DuplexSocket.emit (events.js:180:13)
    at DuplexSocket.emit (domain.js:422:20)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
    at DuplexSocket.Readable.push (_stream_readable.js:218:10)
    at DuplexSocket._write ({applicationPath}/node_modules/native-duplexpair/index.js:24:22)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:396:5)
    at DuplexSocket.Writable.write (_stream_writable.js:294:11)
    at Socket.ondata (_stream_readable.js:651:20)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:422:20)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at TCP.onread (net.js:581:20)
```

_SQL command getting executed_

```sql
INSERT INTO [payments] ([accessionNumber],[patientId],[payerType],[amountPaid],[paymentMethod],[datePaid],[createdAt],[updatedAt]) VALUES (N'A0001',N'1',N'patient',1018,N'EFT',N'2012-12-31',N'2018-08-22 03:00:57.990 +00:00',N'2018-08-22 03:00:57.990 +00:00');
```

__Dialect:__ mssql
__Dialect version:__ 
```
Microsoft SQL Server 2017 (RTM-CU9) (KB4341265) - 14.0.3030.27 (X64)
Jun 29 2018 18:02:47
Copyright (C) 2017 Microsoft Corporation
Developer Edition (64-bit) on Linux (Ubuntu 16.04.4 LTS)
```
__Database version:__ 869
__Sequelize version:__ 4.38.0
__Tested with latest release:__ Yes, 4.38.0

Issue is here - 
[https://github.com/sequelize/sequelize/blob/efef9f52680b8f4f01932107e9091d8aa68de5d7/lib/dialects/mssql/query.js#L391](https://github.com/sequelize/sequelize/blob/efef9f52680b8f4f01932107e9091d8aa68de5d7/lib/dialects/mssql/query.js#L391)

The code should have an if condition before trying to getInsertIdField

```js
if (results && results[0]) { // this is missing in the code
          id = id || results && results[0][this.getInsertIdField()];
          id = id || metaData && metaData[this.getInsertIdField()];
          id = id || results && results[0][autoIncrementAttribute];
          id = id || autoIncrementAttributeAlias && results && results[0][autoIncrementAttributeAlias];
    
          this.instance[autoIncrementAttribute] = id;
}
```

**So, if you want I can add the condition there and send you a pull request.**

**Also, if anyone has some workaround for having triggers enabled and calling create with returning true, then please help me out.**

**Comment by sushantdhiman** [comment]
Have you tried `hasTrigger` option

**Comment by drdeath2609** [comment]
Thanks Shushant, worked... didn't know there was such an options.
