### ISSUE TITLE
MSSQL Transaction failed randomly

### ISSUE THREAD

**Issue by fegauthier** [sequelize/sequelize#9825]
## What are you doing?
I call my API route /:id to do an update. 50% of the time the transaction failed and the other 50% it works. I saw some posts that transactions are very bad with MSSQL. Does someone know how to fix this problem? I need to have transaction rollbacked if somethings go wrong.

```js
router.put('/:id', function(req, res, next){
    let lafcoCode = req.params.id;
    let description = req.body.description;
    let vendorItemsData = req.body.vendorItemsData;

    return sequelize.transaction(t => {
        let vendorItemsUpdate = vendorItemsData.map(vendorItemData => {
            return VendorItemService.saveVendorInfo(lafcoCode, vendorItemData.vendorCode, vendorItemData.levels, vendorItemData.localVendor, vendorItemData.unitPrice, vendorItemData.beforeUofM, req.cookies.email, {
                transaction: t
            });
        })

        return Promise.all(vendorItemsUpdate)
        .then(() => {
            if(description){
                return ItemService.updateDescription(lafcoCode, description, {
                    transaction: t
                });
            }

            return true;
        })
    })
    .then(() => {
        return res.json({
            updated: true
        });
    })
    .catch(function (err) {
        console.log(err);
      });

});
```

## What do you expect to happen?
_I wanted Foo!_

## What is actually happening?
_But the output was bar!_

_Output, either JSON or SQL_

{ SequelizeDatabaseError: Timeout: Request failed to complete in 30000ms
    at Query.formatError (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\sequelize\lib\dialects\mssql\query.js:328:12)
    at Request.connection.lib.Request [as userCallback] (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\sequelize\lib\dialects\mssql\query.js:109:25)
    at Request._this.callback (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\tedious\lib\request.js:60:27)
    at Connection.message (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\tedious\lib\connection.js:1952:24)
    at Connection.dispatchEvent (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\tedious\lib\connection.js:1004:38)
    at MessageIO.<anonymous> (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\tedious\lib\connection.js:884:18)
    at emitNone (events.js:106:13)
    at MessageIO.emit (events.js:208:7)
    at ReadablePacketStream.<anonymous> (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\tedious\lib\message-io.js:104:16)
    at emitOne (events.js:116:13)
    at ReadablePacketStream.emit (events.js:211:7)
    at addChunk (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\readable-stream\lib\_stream_readable.js:291:12)
    at readableAddChunk (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\readable-stream\lib\_stream_readable.js:278:11)
    at ReadablePacketStream.Readable.push (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\readable-stream\lib\_stream_readable.js:245:10)
    at ReadablePacketStream.Transform.push (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\readable-stream\lib\_stream_transform.js:148:32)
    at ReadablePacketStream._transform (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\tedious\lib\message-io.js:71:16)
    at ReadablePacketStream.Transform._read (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at ReadablePacketStream.Transform._write (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at ReadablePacketStream.Writable.write (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at Socket.ondata (_stream_readable.js:639:20)
  name: 'SequelizeDatabaseError',
  parent:
   { RequestError: Timeout: Request failed to complete in 30000ms
    at RequestError (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\tedious\lib\errors.js:34:12)
    at Connection.message (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\tedious\lib\connection.js:1952:33)
    at Connection.dispatchEvent (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\tedious\lib\connection.js:1004:38)
    at MessageIO.<anonymous> (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\tedious\lib\connection.js:884:18)
    at emitNone (events.js:106:13)
    at MessageIO.emit (events.js:208:7)
    at ReadablePacketStream.<anonymous> (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\tedious\lib\message-io.js:104:16)
    at emitOne (events.js:116:13)
    at ReadablePacketStream.emit (events.js:211:7)
    at addChunk (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\readable-stream\lib\_stream_readable.js:291:12)
    at readableAddChunk (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\readable-stream\lib\_stream_readable.js:278:11)
    at ReadablePacketStream.Readable.push (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\readable-stream\lib\_stream_readable.js:245:10)
    at ReadablePacketStream.Transform.push (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\readable-stream\lib\_stream_transform.js:148:32)
    at ReadablePacketStream._transform (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\tedious\lib\message-io.js:71:16)
    at ReadablePacketStream.Transform._read (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at ReadablePacketStream.Transform._write (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at ReadablePacketStream.Writable.write (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
     message: 'Timeout: Request failed to complete in 30000ms',
     code: 'ETIMEOUT',
     sql: 'DELETE FROM [spCustomCost] WHERE [Item_Number] = N\'LAF-1381-000\' AND [Vendor_Num] = N\'100591\' AND [UOfM] = N\'PACK\'; SELECT @@ROWCOUNT AS AFFECTEDROWS;' },
  original:
   { RequestError: Timeout: Request failed to complete in 30000ms
    at RequestError (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\tedious\lib\errors.js:34:12)
    at Connection.message (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\tedious\lib\connection.js:1952:33)
    at Connection.dispatchEvent (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\tedious\lib\connection.js:1004:38)
    at MessageIO.<anonymous> (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\tedious\lib\connection.js:884:18)
    at emitNone (events.js:106:13)
    at MessageIO.emit (events.js:208:7)
    at ReadablePacketStream.<anonymous> (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\tedious\lib\message-io.js:104:16)
    at emitOne (events.js:116:13)
    at ReadablePacketStream.emit (events.js:211:7)
    at addChunk (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\readable-stream\lib\_stream_readable.js:291:12)
    at readableAddChunk (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\readable-stream\lib\_stream_readable.js:278:11)
    at ReadablePacketStream.Readable.push (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\readable-stream\lib\_stream_readable.js:245:10)
    at ReadablePacketStream.Transform.push (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\readable-stream\lib\_stream_transform.js:148:32)
    at ReadablePacketStream._transform (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\tedious\lib\message-io.js:71:16)
    at ReadablePacketStream.Transform._read (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at ReadablePacketStream.Transform._write (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at ReadablePacketStream.Writable.write (C:\Users\fegauthier\Documents\Projects\Lafco-Projects\UpdatePrice-BackEnd\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
     message: 'Timeout: Request failed to complete in 30000ms',
     code: 'ETIMEOUT',
     sql: 'DELETE FROM [spCustomCost] WHERE [Item_Number] = N\'LAF-1381-000\' AND [Vendor_Num] = N\'100591\' AND [UOfM] = N\'PACK\'; SELECT @@ROWCOUNT AS AFFECTEDROWS;' },
  sql: 'DELETE FROM [spCustomCost] WHERE [Item_Number] = N\'LAF-1381-000\' AND [Vendor_Num] = N\'100591\' AND [UOfM] = N\'PACK\'; SELECT @@ROWCOUNT AS AFFECTEDROWS;' }

__Dialect:__ mssql (tedious)
__Dialect version:__ 2.6.4
__Database version:__ SQL Server 2017
__Sequelize version:__ Latest
__Tested with latest release:__ Yes

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
`Request failed to complete in 30000ms`

Your query did not finished under 30 sec, either improve this query, use indexes or increase default timeout your have set at MSSQL engine level

**Comment by fegauthier** [comment]
Hi sushantdhiman,

It's not a problem of query... I mean this query does 3-4 INSERT into a table. If I remove the transaction, it works well. The query takes 0.01MS to run. But when I add transaction, 50% the transaction rollbacked.  

Look at https://github.com/tediousjs/node-mssql/issues/610

This guy have the same issue has mine. It seems to be a problem of node-mssql.

**Comment by fegauthier** [comment]
You can look at this issue https://github.com/sequelize/sequelize/issues/3311

Somebody seems to have the same issue in 2016
