### ISSUE TITLE
Update is not working for JSON type 

### ISSUE THREAD

**Issue by niluroy** [sequelize/sequelize#9862]
What are you doing?
Trying to update the JSON type column(which I am converting it to JSON by using setters() and gettsers() so that I can able to store it as JSON in DB). Issue is that,
1) If I am trying to update only single JSON datatype column by providing the value for that particular column only then its not getting updated.
2) But the same thing is working if I am sending values to all the JSON datatype columns for the model.

VisitorHealthModel.js

    var VisitorHealth = sequelize.define('visitor_health', {
        id: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true
        },
        allergies: {
            type: DataTypes.TEXT,
            get: function() {
                return JSON.parse(this.getDataValue('allergies'));
            },
            set: function(allergies) {
                this.setDataValue('allergies', JSON.stringify(allergies));
            }
        },
        foodHabits: {
            type: DataTypes.TEXT,
            get: function() {
                return JSON.parse(this.getDataValue('foodHabits'));
            },
            set: function(foodHabits) {
                this.setDataValue('foodHabits', JSON.stringify(foodHabits));
            }
        }
    });

Update method in service is:

     updateAllergy(visitor) {
        visitorService.readByVisitorIdHealth(visitor.userId, (result) => {
            visitorModel.visitor_health.update({
                    'allergies': visitor.allergies
                }, {
                    where: {
                        visitorId: visitor.userId
                    }
                }).then(() => {})
                .catch(err => {
                    console.log('error while updating visitor' + err.stack);
                });
        });
    }

What do you expect to happen?
It should update the table if I am not providing all the JSON data type columns values.

What is actually happening?
1) Throwing an error: "Unexpected token u at position 0".

Dialect: mysql
Dialect version: ^1.5.2
Database version: 10.1.28-MariaDB
Sequelize version: ^4.33.4

**Comment by mickhansen** [comment]
What's the full stack trace? What line of your own code is relevant in that stack trace?
To me it looks like the error is happening in your get/set code as you are using TEXT and not the JSON data type.

**Comment by niluroy** [comment]
I am updating only the allergies column value like: allergies: Dust,Peanuts
But it is showing the following stack trace:
`error while updating visitorSyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at model.get (D:\workspace\mm-node\dist\apis\visitor\visitor-health.model.js:25:29)
    at model.get (D:\workspace\mm-node\node_modules\sequelize\lib\model.js:3244:41)
    at model.get (D:\workspace\mm-node\node_modules\sequelize\lib\model.js:3265:33)
    at Promise.try (D:\workspace\mm-node\node_modules\sequelize\lib\model.js:2724:50)
    at tryCatcher (D:\workspace\mm-node\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.attempt.Promise.try (D:\workspace\mm-node\node_modules\bluebird\js\release\method.js:39:29)
    at Function.update (D:\workspace\mm-node\node_modules\sequelize\lib\model.js:2717:23)
    at D:\workspace\mm-node\dist\apis\user\user.service.js:643:48
    at D:\workspace\mm-node\dist\apis\visitor\visitor.service.js:109:17
    at D:\workspace\mm-node\dist\apis\visitor\visitor-health.dao.js:75:17
    at tryCatcher (D:\workspace\mm-node\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\workspace\mm-node\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\workspace\mm-node\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\workspace\mm-node\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\workspace\mm-node\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (D:\workspace\mm-node\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (D:\workspace\mm-node\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (D:\workspace\mm-node\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)`

**Comment by mickhansen** [comment]
It's your own `JSON.parse` call that's failing, you should debug as to find out why.

**Comment by arun-awnics** [comment]
@mickhansen You mean the issue is in the model?

**Comment by sushantdhiman** [comment]
Please use Github Issue Tracker only for reporting bugs, requesting new features or discussions. Ask questions on [Stackoverflow sequelize.js tag](https://stackoverflow.com/questions/tagged/sequelize.js) or [Slack](sequelize.slack.com). While I would like to help answer any questions but it still take too much time.

If you are reporting a bug please isolate it as SSCCE, present it nicely and follow issue template. This will help maintainers and contributors understand your issue quickly.

If you are requesting a feature spend some time to properly present your use case with some examples, current and expected outcome.

( [What is SSCCE ?](http://sscce.org) You can find template for Sequelize [here](https://github.com/sequelize/sequelize/blob/master/sscce_template.js) )

A few good example of SSCCE

1) https://github.com/sequelize/sequelize/issues/8014#issue-245907597
2) https://github.com/sequelize/sequelize/issues/7318#issuecomment-284136530
3) https://github.com/sequelize/sequelize/issues/8749#issuecomment-354734396

**Comment by mickhansen** [comment]
@arun-awnics as far as i can tell the stack trace leads to the users code yes, specifically the user defined JSON.parse inside `get()`
