### ISSUE TITLE
findOrCreate throws a TypeError, but successfully persists the record to the DB

### ISSUE THREAD

**Issue by ATLowther** [sequelize/sequelize#9866]
## What are you doing?

```js
createUser: function(username, salt, hash) {
    return new Promise((resolve, reject) => {
      Users.findOrCreate({
        where: { username: username },
        defaults: { salt: salt, hash: hash }
      })
        .spread((user, created) => {
          resolve([user, created]);
        })
        .catch(error => {
          reject(error);
        });
    });
  }
```

## What do you expect to happen?

The output I expect is pretty straightforward, just the return of the record with a variance in
if (usernameExists) created === false;
if (!usernameExists) created === true;

## What is actually happening?
If the record already exists, I get the expected output, however, if the record doesn't exist, I get:
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at create.then.catch.err (~/node_modules/sequelize/lib/model.js:2147:38)
    at tryCatcher (~/node_modules/bluebird/js/release/util.js:16:23)
    at ~/node_modules/bluebird/js/release/catch_filter.js:17:41
    at tryCatcher (~/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (~/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (~/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (~/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (~/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (~/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (~/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (~/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)

BUT the record still gets persisted to the DB, however, I have no access to it.

__Dialect:__ mysql
__Dialect version:__ 1.6.1
__Database version:__ MariaDB Ver 15.1 Distrib 10.3.9
__Sequelize version:__ 4.38.0
__Tested with latest release:__ 4.38.0 (If yes, specify that version)

**Note :** _Your issue may be ignored OR closed by maintainers if it's not tested against latest version OR does not follow issue template._

**Comment by sushantdhiman** [comment]
Can I get model definition and values for `username, salt, hash` ?

**Comment by zqannnnn** [comment]
same issue with me. Did you solve this problem?

**Comment by rin** [comment]
If you are having this problem, make sure that in the primary key of your model has `autoIncrement: true`.
