### ISSUE TITLE
findOrCreate not writing to database before afterCreate on Postgres

### ISSUE THREAD

**Issue by Azerothian** [sequelize/sequelize#9909]
## What are you doing?
I am attempting to generate rows in a related model in the afterCreate hook

```json
{
  "dependencies": {
    "sequelize": "^4.38.0",
    "pg": "^7.4.3",
  },
}
```

```js
import Sequelize from "sequelize";

const DATABASE_HOST = "localhost";
const DATABASE_PORT = 5432;
const DATABASE_USERNAME = "";
const DATABASE_PASSWORD = "";
const DATABASE_NAME = "test";

const sequelize = new Sequelize(DATABASE_NAME, DATABASE_USERNAME, DATABASE_PASSWORD, {
  host: DATABASE_HOST,
  port: DATABASE_PORT,
  dialect: "postgres",
});

const Task = sequelize.define("task", {
  name: { type: Sequelize.STRING, allowNull: false },
}, {
  hooks: {
    async afterCreate(task, options) {
      await Event.create({
        details: `Event ${task.name} Created`,
        taskId: task.id,
      });
    },
  },
});
const Event = sequelize.define("event", {
  details: { type: Sequelize.STRING, allowNull: false },
});

Task.hasMany(Event, {
  as: "events",
  foreignKey: "taskId",
});
Event.belongsTo(Task, {
  as: "task",
  foreignKey: "taskId",
});


(async () => {
  await sequelize.sync({force: true});
  try {
    //FAILS
    await Task.findOrCreate({
      where: {
        name: "blah",
      },
      defaults: {
        name: "blah"
      }
    });
  } catch(err) {
    console.log(err);
  }
  //WORKS
  await Task.create({
    name: "blah",
  });
  const events = await Event.findAll();
  //expect(events.length).toBe(2);
  console.log("events", events.length);
  return sequelize.close();
})();

```

## What do you expect to happen?
rows to be created in related model
this works fine with just Model.create but when i use Model.findOrCreate i get a foreign key exception. As the model has not been inserted into the database on afterCreate

## What is actually happening?
foreignKey constraint error occurs only when using findOrCreate

```
Executing (default): DROP TABLE IF EXISTS "events" CASCADE;
Executing (default): DROP TABLE IF EXISTS "tasks" CASCADE;
Executing (default): DROP TABLE IF EXISTS "tasks" CASCADE;
Executing (default): CREATE TABLE IF NOT EXISTS "tasks" ("id"   SERIAL , "name" VARCHAR(255) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'tasks' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
Executing (default): DROP TABLE IF EXISTS "events" CASCADE;
Executing (default): CREATE TABLE IF NOT EXISTS "events" ("id"   SERIAL , "details" VARCHAR(255) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIMEZONE NOT NULL, "taskId" INTEGER REFERENCES "tasks" ("id") ON DELETE SET NULL ON UPDATE CASCADE, PRIMARY KEY ("id"));
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'events' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
Executing (98ea155f-5988-4392-b986-f1994ebe978f): START TRANSACTION;
Executing (98ea155f-5988-4392-b986-f1994ebe978f): SELECT "id", "name", "createdAt", "updatedAt" FROM "tasks" AS "task" WHERE "task"."name" = 'blah' LIMIT 1;
Executing (98ea155f-5988-4392-b986-f1994ebe978f): CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response "tasks", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_ade30ec7c93747f7ac18e2f4792ab9a0$ BEGIN INSERT INTO "tasks" ("id","name","createdAt","updatedAt") VALUES (DEFAULT,'blah','2018-09-12 02:17:28.624 +00:00','2018-09-12 02:17:28.624 +00:00') RETURNING * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_ade30ec7c93747f7ac18e2f4792ab9a0$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();
Executing (default): INSERT INTO "events" ("id","details","createdAt","updatedAt","taskId") VALUES (DEFAULT,'Event blah Created','2018-09-12 02:17:28.634 +00:00','2018-09-12 02:17:28.634 +00:00',1) RETURNING *;
Executing (98ea155f-5988-4392-b986-f1994ebe978f): COMMIT;
{ SequelizeForeignKeyConstraintError: insert or update on table "events" violates foreign key constraint "events_taskId_fkey"
    at Query.formatError (*sanitized*/node_modules/sequelize/lib/dialects/postgres/query.js:296:16)
    at query.catch.err (*sanitized*/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)
    at tryCatcher (*sanitized*/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (*sanitized*/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (*sanitized*/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (*sanitized*/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (*sanitized*/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (*sanitized*/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (*sanitized*/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (*sanitized*/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
  name: 'SequelizeForeignKeyConstraintError',
  parent:
   { error: insert or update on table "events" violates foreign key constraint "events_taskId_fkey"
    at Connection.parseE (*sanitized*/node_modules/pg/lib/connection.js:553:11)
    at Connection.parseMessage (*sanitized*/node_modules/pg/lib/connection.js:378:19)
    at Socket.<anonymous> (*sanitized*/node_modules/pg/lib/connection.js:119:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
     name: 'error',
     length: 243,
     severity: 'ERROR',
     code: '23503',
     detail: 'Key (taskId)=(1) is not present in table "tasks".',
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: 'public',
     table: 'events',
     column: undefined,
     dataType: undefined,
     constraint: 'events_taskId_fkey',
     file: 'ri_triggers.c',
     line: '3269',
     routine: 'ri_ReportViolation',
     sql: 'INSERT INTO "events" ("id","details","createdAt","updatedAt","taskId") VALUES (DEFAULT,\'Event blah Created\',\'2018-09-12 02:17:28.634 +00:00\',\'2018-09-12 02:17:28.634 +00:00\',1) RETURNING *;' },
  original:
   { error: insert or update on table "events" violates foreign key constraint "events_taskId_fkey"
    at Connection.parseE (*sanitized*/node_modules/pg/lib/connection.js:553:11)
    at Connection.parseMessage (*sanitized*/node_modules/pg/lib/connection.js:378:19)
    at Socket.<anonymous> (*sanitized*/node_modules/pg/lib/connection.js:119:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
     name: 'error',
     length: 243,
     severity: 'ERROR',
     code: '23503',
     detail: 'Key (taskId)=(1) is not present in table "tasks".',
     hint: undefined,
     position: undefined,
     internalPosition: undefined,
     internalQuery: undefined,
     where: undefined,
     schema: 'public',
     table: 'events',
     column: undefined,
     dataType: undefined,
     constraint: 'events_taskId_fkey',
     file: 'ri_triggers.c',
     line: '3269',
     routine: 'ri_ReportViolation',
     sql: 'INSERT INTO "events" ("id","details","createdAt","updatedAt","taskId") VALUES (DEFAULT,\'Event blah Created\',\'2018-09-12 02:17:28.634 +00:00\',\'2018-09-12 02:17:28.634 +00:00\',1) RETURNING *;' },
  sql: 'INSERT INTO "events" ("id","details","createdAt","updatedAt","taskId") VALUES (DEFAULT,\'Event blah Created\',\'2018-09-12 02:17:28.634 +00:00\',\'2018-09-12 02:17:28.634 +00:00\',1) RETURNING *;',
  fields: null,
  table: 'events',
  value: undefined,
  index: 'events_taskId_fkey',
  reltype: undefined }
Executing (default): INSERT INTO "tasks" ("id","name","createdAt","updatedAt") VALUES (DEFAULT,'blah','2018-09-12 02:17:28.648 +00:00','2018-09-12 02:17:28.648 +00:00') RETURNING *;
Executing (default): INSERT INTO "events" ("id","details","createdAt","updatedAt","taskId") VALUES (DEFAULT,'Event blah Created','2018-09-12 02:17:28.652 +00:00','2018-09-12 02:17:28.652 +00:00',2) RETURNING *;
Executing (default): SELECT "id", "details", "createdAt", "updatedAt", "taskId" FROM "events" AS "event";
events 1
```

__Dialect:__ postgres
__Dialect version:__ ^7.4.3
__Database version:__ 
PostgreSQL 9.6.10 on x86_64-pc-linux-musl, compiled by gcc (Alpine 6.4.0) 6.4.0, 64-bit
PostgreSQL 10.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 6.4.0) 6.4.0, 64-bit
__Sequelize version:__ ^4.38.0
__Tested with latest release:__ 4.38.0

**Comment by sushantdhiman** [comment]
This is because `findOrCreate` run inside a transaction to avoid any race conditions. That `afterCreate` hook is trying to create event with `task.id` which is only available inside that transaction, which is not committed yet.

You can solve this issue by modifying your hook so it use `transaction` option when available

```js
hooks: {
    async afterCreate(task, options) {
      await Event.create({
        details: `Event ${task.name} Created`,
        taskId: task.id,
      }, {
        transaction: options.transaction
      });
    },
  }
```
