### ISSUE TITLE
Cannot create table and add constraint in same transaction

### ISSUE THREAD

**Issue by MatthiasKunnen** [sequelize/sequelize#9934]
## What are you doing?
I am creating a table and adding a constraint to the newly created table in the same transaction.

```js
'use strict';

module.exports = {
    up: async (queryInterface, Sequelize) => {
        await queryInterface.sequelize.transaction(async transaction => {
            await queryInterface.createTable('QuestionOption', {
                id: {
                    allowNull: false,
                    type: Sequelize.INTEGER,
                    primaryKey: true,
                    autoIncrement: true,
                },
                option: {
                    allowNull: false,
                    type: Sequelize.STRING,
                },
                q: {
                    allowNull: false,
                    type: Sequelize.STRING,
                },
            }, {transaction});

            await queryInterface.addConstraint('QuestionOption', ['option', 'q'], {
                type: 'unique',
                name: 'question_option_unique',
            }, {transaction});
        });
    },
};
```

## What do you expect to happen?
I expected the table and constraint to be created successfully.

## What is actually happening?
```
ERROR: SequelizeDatabaseError: relation "QuestionOption" does not exist
    at Query.formatError (/redacted/node_modules/sequelize/lib/dialects/postgres/query.js:363:16)
    at query.catch.err (/redacted/node_modules/sequelize/lib/dialects/postgres/query.js:86:18)
    at tryCatcher (/redacted/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/redacted/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/redacted/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/redacted/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/redacted/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/redacted/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/redacted/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/redacted/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
```

## Workaround
Strangely, executing the exact same SQL query generated by `addConstraint` seems to work.

`addConstraint` generates `ALTER TABLE "QuestionOption" ADD CONSTRAINT "question_option_unique" UNIQUE ("option", "q")`. Replacing the ` await queryInterface.addConstraint(...` statement with the following code works.
```js
await queryInterface.sequelize.query(`
    ALTER TABLE "QuestionOption"
    ADD CONSTRAINT "question_option_unique" UNIQUE ("option", "q")
`, {transaction});
```

I assume there is something awry with the transaction.

__sidenote__
Using the `unique` property in the AttributeColumnOptions would be the easiest solution however this doesn't work. See #8269. I might resort to https://github.com/sequelize/cli/issues/272#issuecomment-194754086.

__Dialect:__ postgres
__Dialect version:__ unsure how to check
__Database version:__ 10.4 (Ubuntu 10.4-2.pgdg14.04+1)
__Sequelize version:__ 4.38.1
__Tested with latest release:__ Yes (4.38.1)

**Comment by MatthiasKunnen** [comment]
Not addressed yet.

**Comment by sushantdhiman** [comment]
@MatthiasKunnen Please show SQL queries executed

**Comment by sushantdhiman** [comment]
An also try with latest and master version if you can

**Comment by MatthiasKunnen** [comment]
Still fails on both latest and next.

SQL executed:
```
SHOW SERVER_VERSION
SELECT 1+1 AS result
SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type LIKE '%TABLE' AND table_name != 'spatial_ref_sys';
SELECT pk.constraint_type as "Constraint", c.column_name as "Field", c.column_default as "Default", c.is_nullable as "Null", (CASE WHEN c.udt_name = 'hstore' THEN c.udt_name ELSE c.data_type END) || (CASE WHEN c.character_maximum_length IS NOT NULL THEN '(' || c.character_maximum_length || ')' ELSE '' END) as "Type", (SELECT array_agg(e.enumlabel) FROM pg_catalog.pg_type t JOIN pg_catalog.pg_enum e ON t.oid=e.enumtypid WHERE t.typname=c.udt_name) AS "special" FROM information_schema.columns c LEFT JOIN (SELECT tc.table_schema, tc.table_name, cu.column_name, tc.constraint_type FROM information_schema.TABLE_CONSTRAINTS tc JOIN information_schema.KEY_COLUMN_USAGE  cu ON tc.table_schema=cu.table_schema and tc.table_name=cu.table_name and tc.constraint_name=cu.constraint_name and tc.constraint_type='PRIMARY KEY') pk ON pk.table_schema=c.table_schema AND pk.table_name=c.table_name AND pk.column_name=c.column_name WHERE c.table_name = 'SequelizeMeta' AND c.table_schema = 'public'
CREATE TABLE IF NOT EXISTS "SequelizeMeta" ("name" VARCHAR(255) NOT NULL UNIQUE , PRIMARY KEY ("name"));
SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'SequelizeMeta' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
SELECT "name" FROM "SequelizeMeta" AS "SequelizeMeta" ORDER BY "SequelizeMeta"."name" ASC;
CREATE TABLE IF NOT EXISTS "SequelizeMeta" ("name" VARCHAR(255) NOT NULL UNIQUE , PRIMARY KEY ("name"));
SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'SequelizeMeta' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
SELECT "name" FROM "SequelizeMeta" AS "SequelizeMeta" ORDER BY "SequelizeMeta"."name" ASC;
CREATE TABLE IF NOT EXISTS "SequelizeMeta" ("name" VARCHAR(255) NOT NULL UNIQUE , PRIMARY KEY ("name"));
SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'SequelizeMeta' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;
SELECT "name" FROM "SequelizeMeta" AS "SequelizeMeta" ORDER BY "SequelizeMeta"."name" ASC;
== 20181219142345-test: migrating =======
START TRANSACTION;
CREATE TABLE IF NOT EXISTS "QuestionOption" ("id"   SERIAL , "option" VARCHAR(255) NOT NULL, "q" VARCHAR(255) NOT NULL, PRIMARY KEY ("id"));
ALTER TABLE "QuestionOption" ADD CONSTRAINT "question_option_unique" UNIQUE ("option", "q");
ROLLBACK;
```
The thing is, as I stated in the issue description, that if you were to replace the `queryInterface.addConstraint` with the exact same generated query, this error will not occur. It is sequelize itself (not the database) that errors because it cannot find `QuestionOption`.

**Comment by sushantdhiman** [comment]
You need to pass transaction in third argument not as forth argument.

```js
           await queryInterface.addConstraint('QuestionOption', ['option', 'q'], {
                type: 'unique',
                name: 'question_option_unique',
                transaction
            });
```

**Comment by herebefrogs** [comment]
The documentation for `QueryInterface.addConstraint` params does not list `transaction` as a possible attribute of `options`: http://docs.sequelizejs.com/class/lib/query-interface.js~QueryInterface.html#instance-method-addConstraint

Would be nice to add it since indeed transaction was the source of this problem.

**Comment by proftom** [comment]
Just ran into this issue as well. Except when I try running my migration it just hangs indefinitely. In my case I am adding table X's primary key as a foreign key on table Y, and then I am trying to enforce uniqueness on a field* in table X. 

(* actually more than 1 field, but testing with 1 field it still hangs. And enforcing uniqueness was a solution/workaround to the fact sequelize doesn't support composite foreign primary keys)
