### ISSUE TITLE
SequelizeDatabaseError: [Microsoft][SQL Server Native Client 11.0]Communication link failure

### ISSUE THREAD

**Issue by matt-pawley** [sequelize/sequelize#9989]
## What are you doing?

We are periodically losing database connection in our production environment, the error message we are seeing is below. Once connection is lost, every subsequent query gives the same error until the application is restarted. 

Restarting the application successfully reconnects with the database. 

The Sequelize connection configuration is as follows:

```js
new Sequelize({
    host: 'xxx',
    database: 'xxx',
    dialect: 'mssql',
    dialectModulePath: 'sequelize-msnodesqlv8',
    timezone: 'Europe/London',
    dialectOptions: {
        multipleStatements: true,
        trustedConnection: true,
    },
    storage: ':memory:',
    benchmark: true,
    omitNull: true,
    pool: {
        max: 4,
        min: 2,
        idle: 20000,
        acquire: 10000,
        handleDisconnects: true,
    },
});
```

## What do you expect to happen?

Automatically reconnect as per other disconnect errors. 

## What is actually happening?

Continuous errors on every query as below:

```
SequelizeDatabaseError: [Microsoft][SQL Server Native Client 11.0]Communication link failure

at Query.formatError (D:\\Smart-VUE\\Smart-VUE-V5\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:315:12)
at connection.beginTransaction.err (D:\\Smart-VUE\\Smart-VUE-V5\\node_modules\\sequelize\\lib\\dialects\\mssql\\query.js:66:25)
at Request [as callback] (D:\\Smart-VUE\\Smart-VUE-V5\\node_modules\\sequelize-msnodesqlv8\\lib\\connection.js:137:5)
at Connection.removeRequest (D:\\Smart-VUE\\Smart-VUE-V5\\node_modules\\sequelize-msnodesqlv8\\lib\\connection.js:187:13)
at context.connection.queryRaw (D:\\Smart-VUE\\Smart-VUE-V5\\node_modules\\sequelize-msnodesqlv8\\lib\\request.js:31:14)
at routeStatementError (D:\\Smart-VUE\\Smart-VUE-V5\\node_modules\\msnodesqlv8\\lib\\driverRead.js:20:7)
at D:\\Smart-VUE\\Smart-VUE-V5\\node_modules\\msnodesqlv8\\lib\\driverRead.js:204:13
at Object.cbFreeStatement [as end] (D:\\Smart-VUE\\Smart-VUE-V5\\node_modules\\msnodesqlv8\\lib\\driverMgr.js:202:7)
at onInvoke (D:\\Smart-VUE\\Smart-VUE-V5\\node_modules\\msnodesqlv8\\lib\\driverRead.js:203:24)
at onQuery (D:\\Smart-VUE\\Smart-VUE-V5\\node_modules\\msnodesqlv8\\lib\\driverMgr.js:114:9
```

__Dialect:__ mssql
__Dialect version:__ 4.1.0
__Database version:__ SQL Server 2017
__Sequelize version:__ 4.38.0
__Tested with latest release:__ No (If yes, specify that version)

Thanks in advance

**Comment by sushantdhiman** [comment]
We don't support `sequelize-msnodesqlv8`, we only support `tedious` for MSSQL

**Comment by toughdeveloper** [comment]
Thanks @sushantdhiman . We are required to use sequelize-msnodesqlv8 as we require integrated security support.

Is there a suggested place (middleware possibly?) to catch the error and attempt a reconnect?

**Comment by sushantdhiman** [comment]
Sequelize use dialect drivers to issue queries to database server, so it does so by calling that dialect driver specific API. You want to use `msnodesqlv8` whose API we don't support.

Looks like `sequelize-msnodesqlv8` bridge API gap between `msnodesqlv8` and `tedious`, but currently that API is mismatched somehow. You will need to work with `sequelize-msnodesqlv8` so it matches tedious API once again.

As for reconnect once `sequelize-msnodesqlv8` matches `tedious` API, it will automatically reconnect
